### ISSUE TITLE
cut/copy/paste while saving a sketch on OS X goes to the editor, not the save dialog

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1035]
_Original author: clankil...@gmail.com (February 18, 2012 12:22:15)_

Processing 1.5.1
Mac os x 10.7.3

If you save a sketch, and paste during that proces for either the filename of the sketch or the filename of a new folder then it paste the content you copied before in the sketch itself.

Not that i care...

_Original issue: http://code.google.com/p/processing/issues/detail?id=997_

**Comment by benfry** [comment]
Looks like an old Java bug that's no longer present.
