### ISSUE TITLE
Single transparent pixel at end of textures in OpenGL

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#115]
_Original author: b...@processing.org (June 07, 2010 01:00:24)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=602

Comment from ewjordan, 2007-07-27 15:05

In OpenGL mode, the edge pixels of an image are coming out partially
transparent, thus making exact matching of edges impossible for tiled (or
cylindrical/spherical) images.  This is apparent in the included example
with 0125 under Examples->3d and OpenGL->OpenGL->TexturedSphere, and it
shows up as a seam on the far side of the sphere.  It disappears if you
switch to P3D.

The reason this is happening is that in the process of creating the texture
for the graphics card, Processing has to increase the dimensions to powers
of 2 and I assume it is filling the extra spaces with 0s - this means that
when texture filtering is used, the edge pixels of the true texture are
blended with fully transparent pixels.  The fix would probably be to fill
in the filler pixels with the edge pixel colors in the actual texture, or
at least fill one extra row/column like that.

For the moment, a temporary workaround is to remap your texture coordinates
using something like:

u = map(u,0,1,0.01,0.99);
v = map(v,0,1,0.01,0.99);

(at least if you're in 0->1 texture mode), but this will slightly alter the
texture's appearance, so it's not a great fix.

_Original issue: http://code.google.com/p/processing/issues/detail?id=76_

**Comment by codeanticode** [comment]
fixed with https://github.com/processing/processing/commit/b92dc049ef08d04474aba4f250d75ff5f49e1b3a

**Comment by benfry** [comment]
Nice! An oldie.
