### ISSUE TITLE
strips when rendering spheres with lights and anti-aliasing

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1185]
_Original author: andres.c...@gmail.com (July 30, 2012 15:36:45)_

Running the following sketch:

void setup() {
  size(400, 400, P3D);
  
  noStroke();
  smooth(4);  
}

void draw() {
  background(0);
  lights();
  
  translate(width/2, height/2);  

  rotateY(frameCount * 0.02);
  translate(150, 0);
  
  sphere(40);
}

with 2.0a6 and 2.0a7 on newer nvidia hardware (570GTX, 650M) results in strips appearing along the edges of the triangles in the spehre. These strips disappear when disabling lights and/or smoothing. It doesn't occur on older nvidia hardware such as geforce 320M, or AMD Radeon HD 6490M and Intel HD Graphics 3000.

_Original issue: http://code.google.com/p/processing/issues/detail?id=1147_

**Comment by codeanticode** [comment]
cannot no longer reproduce this issue (tested on intel HD Graphics 5000 and geforce GT 750 M)
