### ISSUE TITLE
Large number of files in sketchbook folder causes slow startup or launch4j errors

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1190]
_Original author: amnonp5@gmail.com (July 31, 2012 16:19:56)_

When Processing is started for the first time after booting up the computer, it takes about 1 1/2 minute to startup, ending in a launch4j error message box and then most of the time a succesful start. When I close Processing and re-start it takes about 2 seconds to startup. This is consistent behavior. Long startup + launch4j error, after that no problems.

<b>What steps will reproduce the problem?</b>
1. (Re)boot computer.
2. Start Processing for the first time.

<b>What is the expected output? What do you see instead?</b>
I expect fast startup without an error (like on my laptop), instead startup is slow and ends in an error.

<b>What version of the product are you using? On what operating system?</b>
Processing 2.0a7 on WinXP SP3 32bit.

<b>Please provide any additional information below.</b>
I've had this problem since +/- 2010 with every Processing version I've used, which includes at least 1.2.1, 1.5.1 and the 2.0 alphas. I have already tried many things, such as:
- Updated to latest version of Processing (now testing with 2.0a7)
- Run with regular and expert editions of Processing
- Updated to latest version of Java after uninstalling prior versions
- Turned of Java Quick Starter
- Removed file &quot;C:\Documents and Settings[USERNAME]\Application Data\Processing\preferences.txt&quot;
- Run with: processing.exe --l4j-debug to see if there are problems

Nothing has solved this issue. After about 2 years I got used to it. Now I just start up Processing while surfing the web or something and come back later ;-)

_Original issue: http://code.google.com/p/processing/issues/detail?id=1152_

**Comment by JakubValtar** [comment]
Is startup still affected by loading the sketchbook?

Btw rebuilding sketch list asynchronously is requested in #2945.

**Comment by benfry** [comment]
Yes, especially on slow Windows machines, which can cause launch4j to fail because it thinks that the sketch has timed out.

**Comment by FSCSDD** [comment]
[Still a problem in v3.3.7 on Windows 7]
It seems that Processing recursively parses the sketchbook folder on startup opening files, including compiled applications.  This can take a long time especially when you have compiled applications within the sketch folder.  I've had this issue for a while through a few Processing versions - currently with 66 very small sketches - deleting the compiled applications within the sketch folder for 10 sketches fixed this problem for me.
Is it possible to add an option to not recurse the sketch folder on startup (or just not do it at all - not sure why it's needed).  If it is needed, can it be done just 1 level deep and not open anything but a .pde file?  I'm unsure what the purpose is of going through the folder - there might some java things, mode and tools things that need to load but they _should_ be in special folder names.

**Comment by benfry** [comment]
The actual problem to fix is [this one](https://github.com/processing/processing/issues/2945). If we don't recurse into folders, then people will be disappointed that they can't organize their sketches into subfolders. (I know this because at some point we didn't recurse into folders, and people complained.)

There's no magical way to know what's inside a folder—whether it's a sketch or application, so fixing #2945 is the best we can do.
