### ISSUE TITLE
Return "External Editor" option.

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1379]
_Original author: Ooks...@gmail.com (October 24, 2012 20:02:44)_

The External Editor option (removed between Processing 2.0 Beta 3 and Beta 5) should be returned to the options panel as the Command Line is not a full replacement.

As of Beta 5 the command line tools are difficult to use for many users, is unfriendly for beginners, and are not helpful for those who prefer to use a text editor without build tools or access to external commands. It also appears to be completely undocumented at the moment.

_Original issue: http://code.google.com/p/processing/issues/detail?id=1341_

**Comment by reidblomquist** [comment]
This entire exchange and decision is disappointing.
