### ISSUE TITLE
createShape() not yet implemented for the default (Java 2D) renderer

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1438]
_Original author: PallaviK...@u.boisestate.edu (November 19, 2012 18:30:55)_

createShape() does not render in this version is the error;

I was trying
rectangle = createShape(RECT,0,0,100,50);
shape(rectangle);

_Original issue: http://code.google.com/p/processing/issues/detail?id=1400_

**Comment by benfry** [comment]
Implemented in the 3.x series.
