### ISSUE TITLE
 Display 0 does not exist, using the default display instead.

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1457]
_Original author: diana231...@gmail.com (November 28, 2012 15:21:29)_

I am new to arduino and also processing. I am working with the pulse sensor with arduino board to detect heart rate.

I run PulseSensorAmpd_Processing_1dot1.pde, everything works fine.

But error &quot;Display 0 does not exist, using the default display instead.&quot; keep showing. How to fix it?

FYI, I am using processing 1.5.1 in windows 7 64-bit.

_Original issue: http://code.google.com/p/processing/issues/detail?id=1419_

**Comment by S-ed** [comment]
If someone in future will experience this error. It appears on multimonitor systems cause Processing trying to open a window on monitor it wasn't configured to use.
>a) drag Processing window on monitor that set in ```File > Preferences > Run sketches on display:``` and press ```run``` button

or

>b) set a proper monitor in ```File > Preferences > Run sketches on display:``` and ```run``` again
