### ISSUE TITLE
clean up 'ant doc' target to remove warnings

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1492]
_Original author: f...@processing.org (December 08, 2012 17:26:38)_

Because we're using a custom doclet, running javadoc on our source with the standard doclet causes hundreds of warnings. Need to sort out a way to ignore these so that the useful warnings can come through.

_Original issue: http://code.google.com/p/processing/issues/detail?id=1454_

**Comment by benfry** [comment]
Fixed for 3.1.1 by https://github.com/processing/processing/pull/4191
