### ISSUE TITLE
implement setImpl() instead of set() inside PGraphicsOpenGL

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#160]
_Original author: b...@processing.org (June 07, 2010 01:06:41)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=943

Comment from fry, 2008-10-05 20:23

setImpl() is more efficient because it'll properly handle cropping and
placement.

_Original issue: http://code.google.com/p/processing/issues/detail?id=121_

**Comment by codeanticode** [comment]
https://github.com/processing/processing/commit/f32254764da178bfd2db4871e121415b0bed1e21

**Comment by benfry** [comment]
Great to see these getting closed out! Nice work.
