### ISSUE TITLE
Implement a way to disable automatic key repeat

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1622]
_Original author: gargajcns@gmail.com (February 03, 2013 13:25:31)_

1. Write the following sketch: (I'm on Windows)

void setup(){ size(640,480,P3D); }
void draw(){}
void keyPressed() { println(&quot;Keydown: &quot;+keyCode); }
void keyReleased() { println(&quot;Keyup: &quot;+keyCode); }

2. Alt-Tab a few times so that the window loses/regains focus.
3. Press AND HOLD any key.

Result: 

Keydown: 69
Keyup: 69
Keydown: 69
Keyup: 69
Keydown: 69
Keyup: 69
Keydown: 69
Keyup: 69
[etc] 

...instead of one Keydown waiting for a Keyup.

I went to PGL.Java and added
  if (nativeEvent.isAutoRepeat()) return;

to
  protected void nativeKeyEvent

And that seemed to have fixed the problem, although I understand that for a textbox, that behaviour might be the exact opposite of the desired one. Unfortunately I was making a keyboard-controlled game, so I needed an isKeyPressed(&quot;X&quot;)-style behaviour. (Which, by the way, is badly needed.)

_Original issue: http://code.google.com/p/processing/issues/detail?id=1584_

**Comment by benfry** [comment]
@codeanticode is this done easily with JOGL? I suspect JavaFX can do it as well, though Java2D won't really do it properly.

**Comment by JakubValtar** [comment]
We can roll our own keyboard filter. For Java2D, there are multiple keyDown followed by one keyUp, so it's easy. For OpenGL, there is InputEvent.isAutoRepeat() which tells you if it's the real deal or not.

**Comment by benfry** [comment]
Let's skip it on Java2D and make it work with JavaFX and OpenGL.

**Comment by JakubValtar** [comment]
Sounds like a plan.

**Comment by Natura-Time** [comment]
Also, keyTyped() don't work at all with P2D/P3D.

**Comment by JakubValtar** [comment]
Ok, thanks for the report, I'll also try to standardize the key events across renderers when I get to this.

**Comment by benfry** [comment]
Let's make the default no auto-repeat, since that's what most people will expect. Maybe we use a `hint()` to turn it back on.

**Comment by benfry** [comment]
However, if we're going to make that the default, we may need to implement it for Java2D using a hack like the gist in the previous comment (the debouncing notes).

**Comment by benfry** [comment]
Implemented by @JakubValtar for 3.0 beta 6. Works with OpenGL, where key repeat is now disabled by default. `hint(ENABLE_KEY_REPEAT)` will turn it back on.

For Java2D, it doesn't make sense because we have to write a lot of platform-specific de-bouncing code. JavaFX will likely have an option more like the one used in OpenGL.
