### ISSUE TITLE
Output from processing-java badly encoded for Windows Command Prompt

### ISSUE THREAD

**Issue by Antony74** [processing/processing#1633]
This follows on from #1456 - Output from processing-java does not seem to be UTF-8 encoded.  Very similar problem, only it was OS X before, and Windows Command Prompt this time.

D:\>mkdir example

D:\>echo Hamster x; >example\example.pde

D:\>processing-java --build --sketch=D:\example --output=output --force
example.pde:1:0:1:0: Cannot find a class or type named ÔÇ£HamsterÔÇØ

Expected output:
example.pde:1:0:1:0: Cannot find a class or type named "Hamster"

Version:
processing-2.0b7, and also yesterday's Revision bbb16272ef5e23796311684c8934d255e3b070bb.

**Comment by satoshiokita** [comment]
comment memo

**Comment by benfry** [comment]
@satoshiokita Thanks for tracking down the fix. Mac OS X (and Linux?) had the opposite problem, so the code was changed during the 2.0 release cycle to write UTF-8. We'll add this code so that it works properly (the old way) on Windows.

Fix incorporated for 3.1.
