### ISSUE TITLE
Processing does not launch after splash screen

### ISSUE THREAD

**Issue by fxmech** [processing/processing#1647]
For no apparent reason processing stopped launching.
I click on its icon, get the processing splash screen then it goes away and nothing happens...
I noticed a few things...
1) none of my saved versions of processing launch now 
2) downloaded latest version... did not work either... same exact issue
3) no versions of arduino work either...
4)  other programs not related to processing or arduino seem to be OK
5) ran a  boot log for processing...here is the file contents:

CmdLine:    F:\Documents\Documents\Documents\Processing\processing-2.0b7\processing.exe --l4j-debug
WOW64:      yes
Working dir:    F:\Documents\Documents\Documents\Processing\processing-2.0b7.
Bundled JRE:    java
Check launcher: F:\Documents\Documents\Documents\Processing\processing-2.0b7\java\bin\javaw.exe (OK)
Substitute: EXEDIR = F:\Documents\Documents\Documents\Processing\processing-2.0b7
Add classpath:  lib\pde.jar
Add classpath:  core\library\core.jar
Add classpath:  lib\jna.jar
Add classpath:  lib\antlr.jar
Add classpath:  lib\ant.jar
Add classpath:  lib\ant-launcher.jar
Add classpath:  lib\org-netbeans-swing-outline.jar
Add classpath:  F:\Documents\Documents\Documents\Processing\processing-2.0b7\java\lib\tools.jar
Launcher:   F:\Documents\Documents\Documents\Processing\processing-2.0b7\java\bin\javaw.exe
Launcher args:  -classpath "lib;lib\pde.jar;core\library\core.jar;lib\jna.jar;lib\antlr.jar;lib\ant.jar;lib\ant-launcher.jar;lib\org-netbeans-swing-outline.jar;F:\Documents\Documents\Documents\Processing\processing-2.0b7\java\lib\tools.jar" processing.app.Base
Args length:    244/32768 chars
Exit code:  1

also I noticed that on this windows 8 system it kept asking for java on IE10... which I updated...

processing is stored in drive F: but I think Java is in C:...  I don't know if this means anything????

BTW I say java is in C: because I saw it in the java icon in the control panel but I did not remove any java folders from processing in drive F:

**Comment by shivmahesh** [comment]
My saved g code file does not run.same files are running ok on CAMoticl am running gcode executor on processing 301

**Comment by shivmahesh** [comment]
I am new bie in software .some body pls help

**Comment by shivmahesh** [comment]
Error message received
Error : unsupported statement 
G4 P150 ( wait 150ms)
