### ISSUE TITLE
size() sometimes erratic (i.e default size used), especially w/ large setup() functions

### ISSUE THREAD

**Issue by deisner** [processing/processing#1672]
I'm running a "Hello, World" type sketch on Ubuntu Linux (12.04 LTS). The `size()` method, invoked as the first statement in my `setup()` method, does not appear to be working correctly. The size of the output window is set correctly, but the `width` and `height` variables remain at 100x100, and the drawing area appears to be clipped at 100x100, too (based on other testing).

When I run the same sketch on Windows it works as expected. See attached screen captures. In both cases I'm using Processing 2.0b8.

Here is the sketch:

```java
void setup() {
  size(480, 320);
  noLoop();
}

void draw() {
 
  int centX = width/2;
  int centY = height/2;
  println( "width, height: " + width +", "+height);
  ellipse( centX, centY, 0.8*width, 0.8*height);
}
```

Linux output:
![linux_screenshot](https://f.cloud.github.com/assets/742277/208152/f395c1a2-8215-11e2-89de-20f3c1a419b8.png)

Linux PDE:
![linux_pde](https://f.cloud.github.com/assets/742277/208157/19f2ef6e-8216-11e2-80e5-bcd6782e0f2f.png)

Windows output:
![windows_screenshot](https://f.cloud.github.com/assets/742277/208158/26cfab8c-8216-11e2-973e-60937d7a3544.PNG)

Windows PDE:
![windows_pde](https://f.cloud.github.com/assets/742277/208159/2f9f5b04-8216-11e2-8d74-661049333e2b.PNG)

**Comment by benfry** [comment]
This should be completely fixed in 3.0a8.
