### ISSUE TITLE
Syntax highlighting with /

### ISSUE THREAD

**Issue by REAS** [processing/processing#1681]
See processing/processing-web#65

**Comment by JakubValtar** [comment]
Original bug with highlighting seems to be fixed. Can we close this?

**Comment by benfry** [comment]
Are you sure? I don't think we did anything to fix it.

**Comment by JakubValtar** [comment]
I can't reproduce the issue.

`/mouseX` and `/ mouseX` are both purple.

**Comment by REAS** [comment]
I also can't reproduce the error. I am closing.

**Comment by benfry** [comment]
Cool, thanks guys.
