### ISSUE TITLE
draw() called again before finishing on OS X

### ISSUE THREAD

**Issue by jwoLondon** [processing/processing#1709]
Has there been some change in the behaviour of the draw() thread in 2.0b8?

If in the draw loop, a sketch performs some time-comsuming processing, draw() appears to be called again before the processing has completed. This can result in either nothing or a partially drawn frame being displayed.

The sketch below reproduces the problem:

```
// Sketch to demonstrate possible threading bug?
void setup()
{
  size(400,250);
  fill(0);
}

void draw()
{
  background(255);  
  doSomethingComplex();
  println("Drawing frame "+frameCount);
  text("Drawing frame "+frameCount,40,20);
}

void doSomethingComplex()
{
  long startTime = millis();
  for (int i=0; i<1000000; i++) 
  { 
    float x = sqrt(i)+cos(i);
  }
  text("Something complex",40,60);
  println("Completed in "+((millis()-startTime)/1000f)+" seconds.");   
}
```

When run on my MacBookPro (OSX 10.8.3; Java 1.7.0_13), the println() text to console is as expected, but nothing is displayed in the sketch (grey background suggesting that not even background() has been called successfully). 

If I reduce the size of the for loop in doSomethingComplex(), or reduce the complexity of the calculation inside the for loop, screen output is then as expected.

What surprises me is that clearly draw() is being called multiple times, but it is just not updating the screen. This happening even though the time taken to complete the loop is a fraction of a second.

I have not seen this problem before, so perhaps it is a combination of OS and Java version? The sketch behaves as expected on Windows 7 (Processing 2.0b7 and 2.0b8) with Java 1.7_11

**Comment by kshitijhiremath** [comment]
when I run the processing sketch on processing software(I've tried on all versions) these errors
ArrayIndexOutOfBoundsException: 1
COM3 
handleDraw() called before finishing
Could not run the sketch (Target VM failed to initialize). occurs
also the software stops working, with error Java(TM) Platform SE binary is not responding although I've updated Java to lasted version. Also cleared cache.
