### ISSUE TITLE
Blending innacuracies (particularly ADD)

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#172]
_Original author: b...@processing.org (June 07, 2010 01:09:30)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=1008

Comment from davbol, 2008-11-13 09:22

I'm aware of the caveat that the blend operations are "fast not accurate" - primarily 
due to "255/256" type round-down issues caused by ">>8" type equations, but for 
some blend ops the error results in more severely impaired functionality.

Case is point is ADD, and I guess I'm wondering if a hint mode for toggling accurate 
blend math should be added, or something like that - I'm not quite sure exactly 
what to suggest, just starting a discussion for ya...

One likely use of ADD blending would be to accumulate many small color values, 
eventually pinning at white 255.  Problem is, the round-down occurs at *each* add, 
and the rounding errors accumulate quite dramatically.

For example, 16 sequential ADDs of the color(16) do not == 256 pinned to 255.  
Rather they round down by 1 on each step, giving only 240 at the end:

color gray = color(16);
color accum = color(0);
for (int i=0; i<16; i++) {
  accum = blendColor(accum, gray, ADD);
  println("i = " + i + " accum = " + red(accum)); // 15,30,45,60..240
}

And of course, the smaller the color value and greater number of accumulation steps, 
the greater the error.  (32 adds of color(8) gives only 224)

(in contrast, note that this problem does NOT occur in reverse with the SUBTRACT 
blend mode (255 - 16 does == 239) because the rounding occurs in the "right" 
direction - though really just coincidentally, not by design per se)

I could probably volunteer to write the "slower but accurate" version of blend_add_pin
() if ur interested

_Original issue: http://code.google.com/p/processing/issues/detail?id=133_

**Comment by JakubValtar** [comment]
Still a problem:
```processing
// blends background onto itself again and again
// result: white rectangle fades away after 255 frames

void setup() {
  size(500, 500);
  background(0);
  fill(255);
  rect(100, 100, 300, 300);
}

void draw() {
  PImage img = g.get();
  println("pre: ", hex(get(250, 250)));
  println("img: ", hex(img.get(250, 250)));
  blend(img,
        0, 0, width, height,
        0, 0, width, height,
        BLEND);
  flush();
  println("post:", hex(get(250, 250)));
  println("----");
}
```
Output:
```
pre:  FFFFFFFF
img:  FFFFFFFF
post: FFFEFEFE
----
pre:  FFFEFEFE
img:  FFFEFEFE
post: FFFDFDFD
----
pre:  FFFDFDFD
img:  FFFDFDFD
post: FFFCFCFC
----
pre:  FFFCFCFC
img:  FFFCFCFC
post: FFFBFBFB
----
pre:  FFFBFBFB
img:  FFFBFBFB
post: FFFAFAFA
----
pre:  FFFAFAFA
img:  FFFAFAFA
post: FFF9F9F9
```

**Comment by benfry** [comment]
Is it fixable without just making things impossibly slow?

**Comment by JakubValtar** [comment]
See https://github.com/processing/processing/issues/258#issuecomment-51020491, adding one apparently greatly reduces the error. Will test and get back to you with results.
