### ISSUE TITLE
Can't mask PGraphics with another PGraphics

### ISSUE THREAD

**Issue by velvetkevorkian** [processing/processing#1738]
Using a PGraphics to mask another PGraphics fails silently in 2.0b8, but works as expected in 1.5.1. 
Example code: 

```
PGraphics m;
PGraphics nMask;

void setup() {
  size(600, 255, P2D);
  m= createGraphics(width/3, height, P2D);
  nMask= createGraphics(width/3, height, P2D);
}

void draw() {
  background(255, 0, 0);
  drawMain();
  drawMask();

  image(m, 0, 0);
  image(nMask, 200, 0);

  m.mask(nMask); 
  image(m, 400, 0);
}

void drawMask() {
  nMask.beginDraw();
  nMask.background(255);
  nMask.fill(mouseX);
  nMask.noStroke();
  nMask.rect(0, 0, 200, 255);
  nMask.endDraw();
}

void drawMain() {
  m.beginDraw();
  m.background(255);
  m.fill(0, 255, 0);
  m.rect(0, 0, 200, 255);
  m.endDraw();
}
```

The rect on the far right should be the masked output, but in 2.0b8 it displays the unmasked PGraphics. 

There appears to be a [similar issue](https://processing-js.lighthouseapp.com/projects/41284/tickets/1880-possible-bug-in-interaction-between-pgraphics-and-mask) in Processing.js, although I don't know if that's relevant.

OSX 10.7.5

**Comment by BlueBoy1987** [comment]
I would like to add some more information too.
I tested this, but I do not get the error akiersky gets (in 2.2.1).
However, the code provided above does fail silently.
When edited to `PImage img = m.get(); img.mask(nMask); image(img, 400, 0);` it does work.

In 3.0a5, the code above works. However, there's some weird stuff going on in Processing 3 when the masked PGraphic contains an alpha channel. All the transparent parts get turned into opaque black pixels. When converting to PImages before masking, the alpha channel in the original image gets lost too (turns into grey).

**Comment by BlueBoy1987** [comment]
Maybe for a new issue, I'm not sure.
But, in 3.0a5, the code above works. However, there's some weird stuff going on in Processing 3 when the masked PGraphic contains an alpha channel. All the (original) transparent parts get turned into opaque black pixels. When converting to PImages before masking, the alpha channel in the original image gets lost too (turns into grey).

Example code:

```
PGraphics m;
PGraphics nMask;

void setup() {
  size(600, 255, P2D);
  m= createGraphics(width/3, height, P2D);
  nMask= createGraphics(width/3, height, P2D);
}

void draw() {
  background(255, 0, 0);
  drawMain();
  drawMask();

  image(m, 0, 0);
  image(nMask, 200, 0);

  m.mask(nMask); 
  image(m, 400, 0);

/* Alternative (also broken)
  PImage img = m.get();
  PImage mask = nMask.get();
  
  img.mask(mask); 
  image(img, 400, 0);
*/
}

void drawMask() {
  nMask.beginDraw();
  nMask.background(255);
  nMask.fill(mouseX);
  nMask.noStroke();
  nMask.rect(0, 0, 200, 255);
  nMask.endDraw();
}

void drawMain() {
  m.beginDraw();
  m.clear();
  m.fill(0, 255, 0);
  m.ellipse(width/6, height/2, 50, 50);
  m.endDraw();
}
```

**Comment by BlueBoy1987** [comment]
Now that I think about it, this might be intended behavior.
The mask image overwrites the alpha channel of ALL the pixels in the masked image.
There's no nothing anywhere in the reference that indicates that this function is aware of the alpha channel of the masked image.

**Comment by oshoham** [comment]
For anyone who comes across this issue in the future, I ran into the problem described by @BlueBoy1987 in Processing 3.3.6.

I ended up getting around it by writing a custom mask function (with a lot of help from @shiffman):

```
void alternateMask(PGraphics target, PGraphics mask) {
  target.loadPixels();
  mask.loadPixels();
  for (int i = 0; i < mask.pixels.length; i++) {
    float originalAlpha = alpha(target.pixels[i]);
    if (originalAlpha != 0) {
      float maskAlpha = brightness(mask.pixels[i]);
      float r = red(target.pixels[i]);
      float g = green(target.pixels[i]);
      float b = blue(target.pixels[i]);
      target.pixels[i] = color(r, g, b, maskAlpha);
    }
  }
  target.updatePixels();
}
```

This could probably be optimized, but it worked for my purposes.
