### ISSUE TITLE
Horizontal two finger scroll doesn't work in OS X

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#180]
_Original author: b...@processing.org (June 07, 2010 01:10:23)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=1046

Comment from ewjordan, 2008-11-23 16:22

Very low priority RFE: horizontal two finger scrolling doesn't work in the
PDE the way it does in most other applications on OS X.

Somehow this is probably possible in Java (Eclipse manages to get it to
work), but it might not be easy, and a quick Google didn't pop up any
information (doesn't help that Apple's support for Java is pretty much
non-existent these days).

Maybe one for the distant future if someone happens to stumble across a way
to enable it...

_Original issue: http://code.google.com/p/processing/issues/detail?id=141_

**Comment by Akarshit** [comment]
I am using linux and still horizontal two finger scrolling is not working. Insted right click is happening.

**Comment by benfry** [comment]
@Akarshit That's a separate issue, as the title says, this is specific to OS X. If it's broken on Linux, please file a report for it and look into what might be causing the problem.
