### ISSUE TITLE
pixels[] array not updated with Capture and P2D/P3D

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#1852]
Capture examples like AsciiVideo, Mirror, Mirror2 (possibly all the ones that access the pixels array) don't work when using P2D as the renderer, they only show a black screen. This is most likely due to the recent changes in the handling of the pixels array, which conflicts with the optimizations implemented in the video library when the renderer is GL (the video frames go directly into the texture of the Capture object, so the pixels array doesn't contain any valid data).

**Comment by nadineprigann** [comment]
> On my laptop the camera displays fine but when I try and copy it through the copy method or by pixel like in my example code all I get back is black.

@Wavewash did you consider plugging in a webcam on your desktop computer?

**Comment by Wavewash** [comment]
@nadineprigann Thank for your reply - I don't remember the problem anymore (it was 3 years ago) but I must've got past it. I still play with processing and video integration - and I don't have issues like this anymore so it must've gotten cleared up. Thanks!
