### ISSUE TITLE
Processing 2.0 fails to launch sketches (due to modified hosts file)

### ISSUE THREAD

**Issue by mattg73** [processing/processing#1868]
First posted as Issue #1817 under beta 9. I still can't get processing 2.0 full release to launch sketches. This problem never occurred under 2.0b8 and earlier (and still doesn't) it only effects beta 9 and the 2.0 release so I suspect it is something to do with Processing rather than Anti-virus software or my Firewall settings as Ben suggested in his original comments. 

To fix this I've tried:

Downloading and installing a fresh version of Processing 2.0
Downloading and installing up to date java and removing old versions
Downloading up to date NVidia graphics drivers
Definitely preventing the firewall from blocking Processing access
Deleting all anti-virus and malware software from my computer
Switching off anti-aliasing
Trying all levels of memory allocation within Processing
Killing just about every running process I can within Task Manager that might be blocking the sketch from running 

None of this makes any difference: when I press the run button or select run or present from the sketch menu nothing happens other than the run button highlighting yellow and a java process starting in Task Manager (and that can only be killed in Task Manager - pressing the stop sketch button does not terminate the process).

I can get sketches to work if I export an application. Launching this displays the sketch window as I'd expect but it's a bit tedious to have to do every time!

I'm at a bit of a loss as to what to try next. I appreciate there are a myriad ways my unique PC configuration may cause some obscure problem but as it stands I'm basically faced with three options:

1) Stick with 2.0b8
2) Export an application every time I want to test my sketch
3) Buy a new PC

Having donated $50 to the Processing Foundation (which I think you guys totally deserve BTW) to download the software, I was hoping I'd be able to use it. Any update on this bug would be appreciated. Thanks

**Comment by benfry** [comment]
For the next release (3.2.4 or 3.3), this will be detected and an error shown to the user: https://github.com/processing/processing/issues/4738

**Comment by jgreen99** [comment]
What I would recommend is installing the newest Processing on the website: https://processing.org/download/. I don't have Processing 2.0, but I do have the latest version installed on my computer and it works 100%, the sketches should run.

**Comment by benfry** [comment]
(Removing off-topic post and locking this long-since-closed issue.)
