### ISSUE TITLE
Processing Failed 

### ISSUE THREAD

**Issue by Baenlin** [processing/processing#1889]
Hi, I have some problems to run processing 2.0. 64 Bit or 32 Bit Version (Windows) For example I write only this line "ellipse(50, 50, 80, 80);" but the program don´t work. Please help. =)

Output:

Could not run the sketch
[0] "FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)"
ERROR: transport error 202: setsockopt TCPNODELAY failed: Invalid argument
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../../../src/share/back/debugInit.c:690]
Using startup command: java -agentlib:jdwp=transport=dt_socket,address=8570,server=y,suspend=y -Djava.library.path=;C:\Users\Chris\Desktop\projekt_game\processing-2.0\java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\system32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Common Files\Autodesk Shared;C:\Program Files (x86)\Autodesk\Backburner;C:\Program Files (x86)\Autodesk\Backburner;C:\Program Files (x86)\Windows Live\Shared;C:\Users\Chris\Desktop\projekt_game\processing-2.0\java\bin;. -cp C:\Users\Chris\AppData\Local\Temp\sketch_130613a7488989690479463573temp;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\core.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-linux-amd64.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-linux-armv6hf.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-linux-i586.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-macosx-universal.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-windows-amd64.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-windows-i586.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-linux-amd64.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-linux-armv6hf.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-linux-i586.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-macosx-universal.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-windows-amd64.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-windows-i586.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\core.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-linux-amd64.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-linux-armv6hf.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-linux-i586.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-macosx-universal.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-windows-amd64.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt-natives-windows-i586.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\gluegen-rt.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-linux-amd64.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-linux-armv6hf.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-linux-i586.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-macosx-universal.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-windows-amd64.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all-natives-windows-i586.jar;C:\Users\Chris\Desktop\projekt_game\processing-2.0\core\library\jogl-all.jar;lib;lib\pde.jar;core\library\core.jar;lib\jna.jar;lib\antlr.jar;lib\ant.jar;lib\ant-launcher.jar;lib\org-netbeans-swing-outline.jar;lib\com.ibm.icu_4.4.2.v20110823.jar;lib\jdi.jar;lib\jdimodel.jar;lib\org.eclipse.osgi_3.8.1.v20120830-144521.jar -ea processing.core.PApplet --editor-location=710,240 --external --display=0 sketch_130613a --sketch-path=C:\Users\Chris\AppData\Local\Temp\untitled5334350507013142041sketches\sketch_130613a

**Comment by hongmak** [comment]
I've encountered the same problem. How do you solve it?
