### ISSUE TITLE
Repo has huge files and is over 1.2Gb

### ISSUE THREAD

**Issue by amalagaura** [processing/processing#1898]
Wanted to download the sources so I could do some debugging. Was surprised to see the repo at over 1.2Gb.

Ran a large file script and saw the remnants of large files in the .git repo.  Would like to encourage the maintainers to get rid of the large files and change the repo. Rewriting the history would invalidate repo copies and make any references invalid, but a repo full of old binaries is difficult for others.

43183  42866  79ec8b290aafe7f3e30bcd066d053eafd741ca4d  build/linux/jre.tgz
43177  42860  c1d32e6caf36a0f157f674695634b1d21d4f0d67  build/linux/jre.tgz
43169  42848  bea0c4fea82be163e0bc3cc3d0830c75b1e09af3  build/linux/jre.tgz
42135  41812  5c2d06f83271e641193b2f436fe22d9ca393b324  build/linux/jre.tgz
39674  39387  9a2ea0ea74477b012a466ece6b725ed476fe3cdd  build/windows/jre.zip
39664  39386  016b95094c3bafc2c126b48d5300d65f6dd8ff2e  build/windows/jre.zip
39632  39355  5bcd218a100428f61705fc57412bcd352f0d54bc  build/windows/jre.zip
39096  38811  0ec33bfb62b277b8242db93bd9b6c1bc456396f8  build/windows/jre.zip
37947  11494  560db7547d92bb8fe5f4f37154b095e91cd84575  java/libraries/video/library/windows64/plugins/libgstffmpeg.dll
37886  37568  080131c7817e72701060adfeeab04786f27ac93d  build/linux/jre.tgz

**Comment by alokright** [comment]
I had the same issue but when i tried to push mu changes. It worked. So i am guessing we have to push after every Delete or Strip command+ Prune. 
Very helpful. Cheers

**Comment by ghjansen** [comment]
@benfry I am available for hire and would like to solve this issue, as many others. Do you have any interest?

**Comment by jeremydouglass** [comment]
> Wanted to download the sources so I could do some debugging.

Currently processing is ~1.7GB -- but if you just need to do some work on master, the shallow clone described above is still quite small:

    git clone --depth 1 https://github.com/processing/processing.git
    du -sh processing
    124M

Yes, it is a lot of useless bloat, but given this works just fine for the majority of casual contributors, I'm not sure what the value is of history rewriting given it would break an unknown but large number of git checkouts out there. Maybe instead initiating a new repo at the jump from 3.x-4.x?

**Comment by AngelOnFira** [comment]
After reading through a lot of this, it's unfortunate that this problem hasn't been solved. 1.7gb is an unreasonable size for this repo. I just wanted to bump it as a current issue.

**Comment by jeremydouglass** [comment]
Is a shallow clone not a workaround for your use case?

**Comment by benfry** [comment]
If this is a problem, use a shallow clone. Those instructions have been on the build page for a long time.

This issue has been resolved in the Processing 4 repository (https://github.com/processing/processing4), which was split out separately specifically for this issue. It removes the older pieces and is a smaller download.

We simply cannot safely do a major alteration of the 3.x repo without losing links to commits, essential history, and screwing up open pull requests. 

Removing two comments and locking since there's nothing additional to discuss here.
