### ISSUE TITLE
Comment/Uncomment should ignore leading whitespace

### ISSUE THREAD

**Issue by datguy** [processing/processing#1961]
If I use Comment/Uncomment (on the Edit menu, or via hotkey) to comment a line, then AutoFormat the code, the comments are preceded with spaces.  This prevents the Comment/Uncomment feature from recognizing the line as a comment, so I am unable to uncomment the line automatically.

**Comment by benfry** [comment]
This was fixed earlier and works properly (or as proper as it's gonna get) in 3.0 beta 3.
