### ISSUE TITLE
loadTable() doesn't work with csv file using semicolon as data seperator

### ISSUE THREAD

**Issue by goehte** [processing/processing#2013]
loadTable() function will not work with CSV file using semicolon as data separator.

In the us decimal places in numbers will be seperated with an point `.` but e.g. in germany decimal places will be separeted with an comma  `,`.
So really often will be used a semicolon `;` as seperator in CSV files. 
Also a vertical bar `|` wil be used somtimes.

file examples:

```
us_fromat.csv
// id,measurand,value,unit
// 0,meter,3.55,m
// 1,pressure,1.55,bar
// 2,voltage,5.02,V
// 4,current,0.24,A
```

```
de_format.csv
// id;measurand;value;unit
// 0;meter;3,55;m
// 1;pressure;1,55;bar
// 2;voltage;5,02;V
// 4;current;0,24;A
```

I guess loadTable() funtion shoud be enhanced to:

```
loadTable(filename, options, seperator, encoding)
```

See also:
http://forum.processing.org/topic/table-class-doesn-t-work-with-csv-file-using-semicolon-as-data-seperator

**Comment by troykyo** [comment]
Talk about completely "American" centered, even Excel uses semicolons.

**Comment by benfry** [comment]
You can follow the recommendation and use TSV or ODS, both of which are better formats for this exact reason. Or help me out and make a patch for supporting arbitrary delimiters and debugging it across a wide variety of files. CSV is a crummy format, whether I'm American or not.
