### ISSUE TITLE
Maven artifact

### ISSUE THREAD

**Issue by nbeloglazov** [processing/processing#2089]
It would be nice if processing was available on maven repository so any java/scala/clojure/$JVM_LANGUAGE can use it. I know there was attempts to do it: #426.

I'd like to help with it if you don't mind. I want to create ant task for deploying it to maven central repo using [this](https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide) tutorial. It is necessary to create processing repo on sonatype as described in [Step 3](https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-3.CreateaJIRAticket). I can do it if you don't mind or somebody from your team could do it. 

I need this repo for testing purposed: I can try uploading SNAPSHOT artifacts that are not synced to central maven repo. When I test it and decide it is ready I'll ask you about uploading RELEASE 2.0.3 version. 

Thank you,
Nikita

**Comment by sampottinger** [comment]
Just linking all these together... If Travis CI (#2747) is introduced by https://github.com/sampottinger/processing/pull/7 and #5753, it may be possible to support this with continuous integration automatically posting the artifact, reducing the labor required.
