### ISSUE TITLE
dialog box icon is fuzzy on OS X retina machines

### ISSUE THREAD

**Issue by benfry** [processing/processing#2117]
This should be coming from the bundle's app icon so maybe we're missing a size? Or maybe we're setting it in the code. 

For anyone who wants to help, the code is in processing/app/Editor.java, inside checkModified().

![screen shot 2013-09-22 at 4 55 12 pm](https://f.cloud.github.com/assets/1623101/1277752/0dbf934e-2ede-11e3-807d-6e8d8aae3019.png)

**Comment by Plastix** [comment]
Pretty sure this is fixed. Looks fine on my machine.
![screen shot 2015-04-01 at 9 32 24 am](https://cloud.githubusercontent.com/assets/1526881/6941969/0abc8eda-d852-11e4-971f-175bf9bd43a5.png)

**Comment by benfry** [comment]
Ok, thanks. I think it was a Java bug that was fixed.
