### ISSUE TITLE
P3d not working on windows 64 bit

### ISSUE THREAD

**Issue by muneeburrahman** [processing/processing#2118]
When i try to run a sketch with P3d support . i get the following error on windows 64 bit 

"Could not run the sketch (Target VM failed to initialize)."

without P3d everything is running fine
. Can anybody please help.

**Comment by shivmahesh** [comment]
After pressing g in processing window and selecting and opening saved g code fileerror message is received
Unsupported statement
G4 P150 ( wait 150ms).pls help.iam newbie in software
