### ISSUE TITLE
set(0, 0, image) does not set alpha channel to opaque in P2D/P3D

### ISSUE THREAD

**Issue by benfry** [processing/processing#2125]
Using set(0, 0, image) to set the background doesn't set the alpha channel opaque for the pixels that it covers. 

As a result, calling get() or saveFrame() on that PGraphics will leave out the pixels written with set().

**Comment by codeanticode** [comment]
when setting a texture with RGB pixels, the alpha is set to opaque:

https://github.com/processing/processing/blob/master/core/src/processing/opengl/Texture.java#L989
https://github.com/processing/processing/blob/master/core/src/processing/opengl/Texture.java#L1019
