### ISSUE TITLE
File-Print Bizzare Behavior

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#213]
_Original author: b...@processing.org (June 07, 2010 01:14:17)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=1230

Comment from JimAtArtsnova, 2009-04-17 18:28

Using Processing 1.0.1 on Windows XP on Dell inspiron 9300

File - Print to send program code to either the printer or to a virtual
printer that creates a PDF.

1) Printing does not start at line 1. 

2) Only prints between 17-20 lines per page (slightly more than 1/2 the page)

3) Does not print every line but instead skips 16-18 lines of code in
blocks at every page break.  So printing starts at line N, prints approx 20
lines, skips approx 18 lines, prints approx 20 lines, etc.

_Original issue: http://code.google.com/p/processing/issues/detail?id=174_

**Comment by joshgiesbrecht** [comment]
Just tested with a PDF print driver on Windows 7 and a current build.  Didn't see any lines skipped, print output used the whole page just fine. Looks fixed.
