### ISSUE TITLE
"Target VM failed to initialize" when using Present mode on Mac OS X

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#217]
_Original author: b...@processing.org (June 07, 2010 01:14:51)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=1257

Comment from pyramus, 2009-05-31 17:10

On my Macbook it seems to be impossible to run any sketch (no matter what
code) in "Present" mode. Everything seems to behave normal when I choose
standard "Run" button.
Disabling network (as suggested in previous bug 796) didnt solve the
problem, neither did reinstalling Java or Processing change a thing.
Any ideas what this could be?

Details:
1. Processing 1.0.3
2. MacOS 10.5.7  /  Java 1.5 Update 2 (build 1.5.0_16-b06-284) @ MacBook
3. Any code.... For example: size(200, 200);
4. com.sun.jdi.connect.VMStartException: VM initialization failed for: java
-Xrunjdwp:transport=dt_socket,address=127.0.0.1:8023,suspend=y
-Xdock:name=sketch_jun01a
-Djava.library.path=:/Applications/Processing.app/Contents/Resources/Java:/System/Library/PrivateFrameworks/JavaApplicationLauncher.framework/Resources:.:/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
-cp
/tmp/build16700.tmp:/Applications/Processing.app/Contents/Resources/Java/pde.jar:/Applications/Processing.app/Contents/Resources/Java/core.jar:/Applications/Processing.app/Contents/Resources/Java/antlr.jar:/Applications/Processing.app/Contents/Resources/Java/ecj.jar:/Applications/Processing.app/Contents/Resources/Java/registry.jar:/Applications/Processing.app/Contents/Resources/Java/quaqua.jar
processing.core.PApplet --editor-location=442,78 --external --display=1
--sketch-path=/tmp/untitled16698.tmp/sketch_jun01a --present --exclusive
--stop-color=#cccccc --bgcolor=#666666 sketch_jun01a
    at
com.sun.tools.jdi.AbstractLauncher$Helper.launchAndAccept(AbstractLauncher.java:174)
    at com.sun.tools.jdi.AbstractLauncher.launch(AbstractLauncher.java:114)
    at
com.sun.tools.jdi.RawCommandLineLauncher.launch(RawCommandLineLauncher.java:100)
    at processing.app.debug.Runner.launchVirtualMachine(Runner.java:408)
    at processing.app.debug.Runner.launch(Runner.java:122)
    at processing.app.Editor$43.run(Editor.java:1572)
    at java.lang.Thread.run(Thread.java:613)
Could not run the sketch (Target VM failed to initialize).

_Original issue: http://code.google.com/p/processing/issues/detail?id=178_

**Comment by Ystemroc** [comment]
This same bug happened to me with processing 3.0 on something that had worked fine previously. I tried restarting, but my computer is stuck. Sometimes the cursor appears, but then it disappears. It seem that some central part of my computer is broken.

**Comment by pedronrito** [comment]
I'm using Windows 10 PRO, and working with processing 3, 
when i tried to run an empty sketch or other it always shows
"Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.
"
