### ISSUE TITLE
textWidth() incorrect with default (JAVA2D) renderer and default font

### ISSUE THREAD

**Issue by monkstone** [processing/processing#2175]
This is sketch that shows it up...
```java
void setup(){
  size(400, 200);
  String string = "dddddddddddddddd";
  float textlen = textWidth(string);
  text(string, 100, 100);
  stroke(0);
  line(100+textlen, 89, 100+textlen, 102);

  String string2 ="drawerrormmmmmmm";
  float textlen2 = textWidth(string2);
  text(string2, 100, 120);
  line(100+textlen2, 109, 100+textlen2, 122);
}
```
Works fine with P2D renderer, this issue was reported to me by @marcel12bell over at [ruby-processing](https://github.com/jashkenas/ruby-processing/issues/77#issuecomment-27199987) (it affects his [livecoding app](https://github.com/marcel12bell/simple-live-coding) which needs to use JAVA2D), and the error seems to be much more pronounced on OSX,

**Comment by benfry** [comment]
Appears to be working properly in 3.0 beta 3.
