### ISSUE TITLE
Blank sketch opened even if opening an existing sketch by double-clicking

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#218]
_Original author: b...@processing.org (June 07, 2010 01:15:00)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=1261

Comment from crlf, 2009-06-02 00:22

Processing (1.0.4), when starting, always opens the sketches that were open in the last session, 
which is fine and saves time.

However, if there were no open sketches the last time (or the only sketch open was a new 
sketch that was never saved), it opens a new blank sketch even if another sketch is going to 
open anyway (the user is opening a sketch by double-clicking on it).

This is just a minor issue, though.

_Original issue: http://code.google.com/p/processing/issues/detail?id=179_

**Comment by JakubValtar** [comment]
When I click File -> Open... or open a sketch from examples, a new window is always created above the old empty one. Can we load the sketch into current (empty) window?

**Comment by iamutkarshtiwari** [comment]
Is this problem still up for up for some contributions?

**Comment by tessapower** [comment]
Still experiencing this issue now, using Windows 11, Processing version 4.0b8.

**Comment by benfry** [comment]
Resolved here for the next 4.x release: https://github.com/processing/processing4/issues/477
