### ISSUE TITLE
sketchPath() returns user.home in exported apps on OSX

### ISSUE THREAD

**Issue by ElectricJack** [processing/processing#2181]
Running the following:

```
println( "javaVersionName: "+ javaVersionName );
println( "java.home:       "+ System.getProperty("java.home") + "\n");
println( "os.arch:         "+ System.getProperty("os.arch") );
println( "os.name:         "+ System.getProperty("os.name") );
println( "os.version:      "+ System.getProperty("os.version") + "\n");
println( "user.home:        "+ System.getProperty("user.home") );
println( "user.dir:        "+ System.getProperty("user.dir") );
println( "dataPath():      "+ dataPath("") );
println( "sketchPath():    "+ sketchPath("") );
 
exit();
```

Returns expected results when run from the processing editor:
![screenshot 2013-10-28 17 11 55](https://f.cloud.github.com/assets/198026/1425140/0777de12-402f-11e3-84d3-8b5235460a8b.png)

However when running the exported app it returns invalid results for sketchPath():
```
JKERNOAKOSX2:sketchPathDiag jack.kern$ ./run.sh
javaVersionName: 1.7.0_45
java.home:       /Users/jack.kern/Desktop/sketchPathDiag/sketchPathDiag.app/Contents/PlugIns/jdk1.7.0_45.jdk/Contents/Home/jre

os.arch:         x86_64
os.name:         Mac OS X
os.version:      10.8.5

user.home:        /Users/jack.kern
user.dir:        /Users/jack.kern
/Users/jack.kern/Desktop/sketchPathDiag/sketchPathDiag.app/Contents/Java/data
dataPath():      /Users/jack.kern/Desktop/sketchPathDiag/sketchPathDiag.app/Contents/Java/data
sketchPath():    /Users/jack.kern/
```

**Comment by maudiruiz** [comment]
This is not repaired for Processing 2.2.1 running the command and just getting "/Users/myUser"
I can hardcode the path but it does not work when exporting to a .app 
Any ideas on how to make a local patch to solve it @benfry @01010101 ? 

Thanks!

**Comment by 01010101** [comment]
I used this workaround :

Say you want to use a file name yourfilename.ext in the data folder located
at the root of your exported app :

String fullpath =
dataPath("").replaceAll("NameOfYourSketch.app/Contents/Java/",
"")+"/yourfilename.ext"



* ✂------------------*
*       http://saint-clair.net <http://saint-clair.net>*
       *http://graffitiresearchlab.fr <http://graffitiresearchlab.fr>*
* ✂------------------*

**Comment by benfry** [comment]
Just confirmed to be working in 3.0 beta 3.
