### ISSUE TITLE
Javac not found - Processing in Android Mode (Processing 2.1, Mac OSX 10.9)

### ISSUE THREAD

**Issue by crcdng** [processing/processing#2187]
"/Applications/android/android-sdk-macosx/tools/ant/build.xml:734: Compile failed; see the compiler error output for details."
"-compile:
    [javac] Compiling 3 source files to /var/folders/y8/8c2f2nrd19vdmjg7w4f4ffsw0000gn/T/android6422669601300760188sketch/bin/classes
    [javac] Unable to locate an executable at "/Applications/Processing.app/Contents/PlugIns/jdk1.7.0_45.jdk/Contents/Home/jre/bin/javac" (-1)"

It looks for javac in the bundled jre. Reproducable; any bundled example.
Remark: Processing 2.0.3 Android mode works fine on the same machine.

**Comment by ozukaru** [comment]
i have this problem
![1](https://cloud.githubusercontent.com/assets/13461585/8844078/8c668738-30d6-11e5-833a-c108ee25570b.png)
