### ISSUE TITLE
Reduce scroll amount in contribution manager

### ISSUE THREAD

**Issue by aengelke** [processing/processing#2189]
Change blockamount in ContributionListPanel.java to a constant value like 10.

https://github.com/processing/processing/blob/master/app/src/processing/app/contrib/ContributionListPanel.java#L288

**Comment by benfry** [comment]
We need a more standard fix for this; the one suggested in #3135 might work on some machines but not others. Shouldn't this be coming from the LAF?

**Comment by Akarshit** [comment]
@benfry I think that this issue is not relevant now as the CM has been changed.
