### ISSUE TITLE
SimpleOpenNi examples give error on MacOS 10.8.5

### ISSUE THREAD

**Issue by jorrit-g** [processing/processing#2201]
What happens?

When I run any of the examples provided by the SimpleOpenNI lib, I get the following error right after initialization of the sketch:

---

A fatal error has been detected by the Java Runtime Environment:

SIGILL (0x4) at pc=0x0000000157fe00b4, pid=472, tid=50203
# 

JRE version: Java(TM) SE Runtime Environment (7.0_45-b18) (build 1.7.0_45-b18)
Java VM: Java HotSpot(TM) 64-Bit Server VM (24.45-b08 mixed mode bsd-amd64 compressed oops)
Problematic frame:
C [libfreenect.0.1.2.dylib+0x40b4] freenect_camera_init+0x178
# 

Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
# 

An error report file with more information is saved as:
/Users/xxxxx/Documents/Processing/libraries/SimpleOpenNI/library/osx/hs_err_pid472.log
# 

If you would like to submit a bug report, please visit:
http://bugreport.sun.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
## See problematic frame for where to report the bug.

How to reproduce:
1. Reinstall MacOS (version 10.8.5)
2. Download Processing
3. Install SimpleOpenNI through the autoinstaller

The provided libs libfreenect.0.1.2.dylib and libusb-1.0.0.dylib seem to be corrupt

How to solve: 
1. replace libfreenect.0.1.2.dylib and libusb-1.0.0.dylib in /Users/[yourname]/Documents/Processing/libraries/SimpleOpenNI/library/osx/OpenNI2/Drivers with the same drivers provided on https://github.com/kronihias/head-pose-estimation/tree/master/mac-libs
2. rerun sketch

On which system: 

Macbook air mid 2011 model

hardware specs: 

  Model Name:   MacBook Air
  Model Identifier: MacBookAir3,2
  Processor Name:   Intel Core 2 Duo
  Processor Speed:  1.86 GHz
  Number of Processors: 1
  Total Number of Cores:    2
  L2 Cache: 6 MB
  Memory:   4 GB
  Bus Speed:    1.07 GHz

Chipset Model:  NVIDIA GeForce 320M
  Type: GPU
  Bus:  PCI
  VRAM (Total): 256 MB
  Vendor:   NVIDIA (0x10de)
  Device ID:    0x08a3
  Revision ID:  0x00a2
  ROM Revision: 3571

Strangely I could not reproduce this issue on a newer MacBook (model oct. 2012) air running OSx 10.8.5 with the same java version.

**Comment by funkytaco** [comment]
Where do you file this bug? I just had the same problem.

**Comment by jorrit-g** [comment]
I never got around filing this bug, sorry.

**Comment by funkytaco** [comment]
I was asking what project this would be filed on. I think we'd have to send it to SimpleOpenNi

**Comment by funkytaco** [comment]
I modified one line in the Makefile:

    g++ src/OSCeleton.cpp src/viewer.cpp -O3 -Wno-write-strings -Iliblo-0.26-modified -I/usr/X11/include -I/usr/include/ni -lOpenNI -lstdc++ -L/usr/X11/lib -framework OpenGL -framework GLUT liblo-0.26-modified/src/.libs/*.o -o osceleton

Based on [this SO answer](http://stackoverflow.com/questions/21105983/include-gl-glut-h-file-not-found-in-xcode) I modified viewer.cpp:

	#ifndef __MAC__
	#define __MAC__ 1
	#endif

	#ifdef __MAC__
	# include <OpenGL/glu.h>
	# include <OpenGL/gl.h>

	#else
	#include <GL/glu.h>
	# include <GL/gl.h> 
	#endif


$ ls /System/Library/Frameworks/GLUT.framework/headers

	copy.h		glsmapint.h	glutf90.h	intersect.h	segment.h	vvector.h
	extrude.h	glut.h		glutstroke.h	port.h		tube.h
	glsmap.h	glutbitmap.h	gutil.h		rot.h		tube_gc.h

$ ls /System/Library/Frameworks/OpenGL.framework/Headers/

	CGLContext.h		CGLMacro.h		OpenGLAvailability.h	glext.h			glu.h
	CGLCurrent.h		CGLRenderers.h		gl.h			gliContext.h		gluContext.h
	CGLDevice.h		CGLTypes.h		gl3.h			gliDispatch.h		gluMacro.h
	CGLIOSurface.h		OpenGL.h		gl3ext.h		gltypes.h

I changed common.h to this:

	#ifndef __MAC__
	#define __MAC__ 1
	#endif

	#ifdef __MAC__
	# include <GLUT/glut.h>
	#else
	#endif

	extern int window;

	#include "viewer.h"

I may have modified another file or two, but if I did, they were all errors relationg to the GL library.

**Comment by kitab15** [comment]
This works for me! Thanks!
