### ISSUE TITLE
Stacktrace-printing hardcoded in PApplet.java

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#222]
_Original author: b...@processing.org (June 07, 2010 01:15:27)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=1281

Comment from taifunbrowser, 2009-06-16 20:44

To increase object-orientedness, could all

e.printStackTrace

be replaced with

printException(Throwable e)

in Papplet.java ?  Then those of us wanting to extend the error handling capabilities 
(i.e., if we have many registerDraws() that could throw exceptions), we could just 
override this single method.

_Original issue: http://code.google.com/p/processing/issues/detail?id=183_

**Comment by JakubValtar** [comment]
There are still 43 matches for e.printStackTrace() in PApplet.java, can we label this as `help`?

**Comment by benfry** [comment]
Added `printStackTrace(Throwable t)` for 3.2.
