### ISSUE TITLE
depth-preserving raw output in P3D needs depth sorting

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#2235]
Otherwise, the triangles are renderer in the order they were defined in the sketch code, which leads to incorrect occlusions, see for example:

http://forum.processing.org/two/discussion/1509/3d-scene-output-to-pdf-depth-buffer-issues

The triangle sorting algorithm can be used when rendering semitransparent geometry: https://github.com/processing/processing/issues/90

**Comment by JakubValtar** [comment]
Original code example works great in current HEAD when you export with ENABLE_DEPTH_SORT hint. Should we sort by default when people export to PDF from P3D, or should we explect people to enable the sorter themselves?

**Comment by benfry** [comment]
Need a processing-docs issue here to update the `PDF` and `beginRaw()` reference to tell people to use `hint(ENABLE_DEPTH_SORT)` with 2D renderers.

**Comment by codeanticode** [comment]
The functionality is already implemented, closing now since the documentation update is addressed in the processing-docs issue referenced above.
