### ISSUE TITLE
video playing (Movie class) doesn't work on Linux

### ISSUE THREAD

**Issue by akosmaroy** [processing/processing#2242]
Hi,

I'm trying to load & play a video on Linux, Ubuntu 13.04, but it doesn't work:

```
 A library relies on native code that's not available.
 Or only works properly when the sketch is run as a 32-bit  application.
```

unfortunately this is the only error message I get, it doesn't say what library would be missing, etc. I'm using processing 2.1 64 bit.

the code is very simple:

```
import processing.video.*;
Movie myMovie;

void setup() {
  size(200, 200);
  background(0);
  myMovie = new Movie(this, "/tmp/ize.mpg");
  myMovie.loop();
}

void draw() {
  image(myMovie, 0, 0);
}

// Called every time a new frame is available to read
void movieEvent(Movie m) {
  m.read();
}
```

**Comment by tomasciccola** [comment]
that didn't do it for me...I'm struggling to make video playback work on processing. Looking at other posts on processing forum I reached other answers that didn't work for me. I'm using p5 2.2.1 under Xubuntu 14.10.

**Comment by yurikleb** [comment]
This ZIP works well, tested on Ubuntu 18 and 16, 64bit:
https://github.com/processing/processing/issues/2242
