### ISSUE TITLE
Processing references incorrect sketch folder for manually added libraries - Mac

### ISSUE THREAD

**Issue by ld26464** [processing/processing#2258]
0) Mac OS 10.9 - Processing 2.1 and 1.5.1,
1) I use a custom location for the 'sketchbook' on a secondary drive. 

2) Adding ApacheCommonsCollections4 or JodaTime java libraries to the custom 'sketchbook' I specified in preferences does not make them available to Processing either in sketches or in the 'Sketch/Import Library: Contributed Library' pulldown tool. When 'import correctLibNam.*;' is put into sketch it returns a library not found error. 

3) When the same library is transfered to the default sketchbook location on my home drive, the library becomes adressable, and is available in the pulldown. 

4) Note: libraries imported through the 'normal' import tool 'Sketch/Import Library: Add Library' are correctly placed in the custom sketchbook location and are addressable from within sketches as usual. This is only for manually added libraries. 

Seems to be an update path type problem. 

Addl notes: Trying to debug this I also tried OS 7.5 - Processing 2.1. There were problems there as well, but I am not certain they were the same. The original file worked with OS 7.5 - Processing 1.5 I believe.

**Comment by benfry** [comment]
This is a misunderstanding in how a Processing “Library” works versus adding a couple JAR files to a project. The forum is a better place for this sort of question.
