### ISSUE TITLE
Errors in glsl code are only caught when set() is used

### ISSUE THREAD

**Issue by SableRaf** [processing/processing#2268]
These code snippets will explain the issue better:

```
try {  
    myShader = loadShader( "bad_shader.glsl" );
    myShader.set("resolution", float(width), float(height));
  } catch (RuntimeException e) {
    println("I see dead shaders...");  
  }
``` 

```
try {  
    myShader = loadShader( "bad_shader.glsl" );
  } catch (RuntimeException e) {
    println("this doesn't print");  
  }
```

Is it by design that loadShader doesn't catch syntax errors in glsl code?

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing/commit/5e7703e1c3285677e839e3198c3590b9651b72c1, compilation errors are consistently thrown when calling shader()
