### ISSUE TITLE
sketches that use the retina renderer are slow to start

### ISSUE THREAD

**Issue by mearsy** [processing/processing#2357]
When specifying the renderer processing.core.PGraphicsRetina2D on Processing 2.1.1 like so:

size(320, 460, "processing.core.PGraphicsRetina2D");

There is a noticeable delay (about 2 seconds) before the application begins where the background is the default grey of processing.

This does not happen when using

size(320, 460); // The default renderer

The text is obviously a lot nicer using the PGraphicsRetina2D

I have tried specifying background(rgb); // where RGB is the background of the final app, to overcome the issue but it makes no difference to the initial loading. As processing is a language aimed at artists, it detracts a little bit from the aesthetic while the application loads.

Please can you look at improving the performance of processing.core.PGraphicsRetina2D to make it work in the same manner as the default renderer.

Thank you

Chris

**Comment by benfry** [comment]
We're limited by what Java can do here. In 3.0 beta 3, startup is as fast as it can be with Java2D, but if that's still too slow, the `FX2D` renderer (the new default) in the final version of 3.0 should hopefully fix things up a bit.
