### ISSUE TITLE
Add --display option to processing-java to select the display where sketch is placed

### ISSUE THREAD

**Issue by rturknett** [processing/processing#2373]
This feature is needed to run sketches via the command line (processing-java) on multiple displays attached to the same machine.

The --display flag should override the run.display value set in ~/.processing/preferences.txt

I am looking into how best to implement this...suggestions welcome.

**Comment by benfry** [comment]
To pass the `--display` option, you'll need to write your own `main()`.

But a better option with 3.0 is to specify the display number with `fullScreen()`, since that's the usual case when you're specifying the display.
