### ISSUE TITLE
Add --location option to processing-java to set initial sketch screen location

### ISSUE THREAD

**Issue by rturknett** [processing/processing#2374]
This feature is needed to enable placing sketches at different screen locations via the command line (processing-java).

I am looking into how best to implement this...suggestions welcome.

**Comment by benfry** [comment]
#2552 covers passing arguments to the sketch itself, which is fixed for 3.0 beta 4. 

To set location, use `surface.setLocation()`. Most uses of `--display=` are with full screen, so use `fullScreen(N)` for the sketch number. Opening a non-full screen window on another display is very tricky to do in a consistent and cross-platform manner, and not something we want people relying on in this sort of context.
