### ISSUE TITLE
PDE is 2x smaller on high-res Windows machines

### ISSUE THREAD

**Issue by Ruby-Paredes** [processing/processing#2411]
I bought a new laptop with a high resolution, it's a "Lenovo Yoga" with windows 8. Processing worked on my old mac book,but now the tool bar (run, stop, new etc) and my actual sketches are tiny!! I've tried lowering my resolution on my laptop, and looked all through page setup and preferences in processing. Please help I'm very new to this

**Comment by JukePlz** [comment]
Scaling on modern Windows versions is governed by the DPI setting. There is available documentation on how aplications are expected to behave in relation to this. 

Just though I drop of the link here for anyone triying to implement this:
https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266%28v=vs.85%29.aspx

**Comment by vormplus** [comment]
Looks like this bug is back. Some of my students have a Dell Inspiron 15 7000 with a 4K UltraHD touch screen. (Resolution 3840 x 2160 pixels). These machines are running Windows 10.

Writing code works if you bump the editor font size to the maximum, but the biggest problem is that the menu items and tabs are too small to click with a trackpad. Sketches are also way too small, making it difficult to work with controlP5.

I think it would be good to find a solution that will work on any screen resolution. Two years from now, there will be quite a few 8K monitors on the market.

![processing-windows-4k-screen-bug](https://cloud.githubusercontent.com/assets/805141/13204509/42e6efae-d8d2-11e5-8cf4-11cf65b55fc1.png)

**Comment by adamribaudo** [comment]
Just repeating what others have found...same issue on a Microsoft Surface Pro 4 which has a high density screen. Screen shot attached showing Processing next to this post for reference.

![processing size](https://cloud.githubusercontent.com/assets/295592/13448625/9d406936-dff2-11e5-8084-2c54b4b79b5a.PNG)

**Comment by benfry** [comment]
Yes, this is a known issue, no need to repeat. Nobody has submitted a fix, and it will continue to be a problem until this bug is closed.

**Comment by garymike** [comment]
I'd like to begin addressing this issue. Any other ideas on an angle I should begin attacking this from?

**Comment by benfry** [comment]
I don't know, unfortunately—you might check what the Arduino folks did to modify our code to make it work.

**Comment by JukePlz** [comment]
@garymike if you will take on this, the arduino related discusion for the implementation of this is on this PRs:

https://github.com/arduino/Arduino/pull/2776
https://github.com/arduino/Arduino/pull/4376

The proper way to do this for UI would be with vector graphics, the Arduino people downscaled some of them. Search for .png in the repo files to find UI elements that may need consideration, many are unique to processing's IDE.

**Comment by garymike** [comment]
Thank you, those were the two I dug through yesterday on their repository. They seem to have added a lot of flexibility in their scaling range, I will likely focus on making 4k and 5k look pristine to keep the code lightweight.

**Comment by benfry** [comment]
The 2x image assets (and a means for switching between them) are already implemented for OS X. The difference is that I have no idea how the screen even reports that it's high-density (on Windows and Linux), nor how the other GUI elements that we get from Swing (menubars, windows, buttons) should be handled. On OS X, for instance, we get the Swing scaling for free (from the OS) when we set a parameter in the app's configuration.

**Comment by aglie** [comment]
Is it possible to pass a java argument to Processing.exe? Some recipes say that it is sufficient to turn off the Dsun.java2d.dpiaware to instruct windows to rescale the app automatically, but I could not test it. 

A bit more information on the flags [here](https://www.reddit.com/r/javahelp/comments/4aukb7/change_java_dpi_scaling/) and [here](http://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display).

**Comment by benfry** [comment]
Thanks for looking into it. You had my hopes up, but it looks like the setting is broken in Java 8: http://superuser.com/a/1007783. 

To try the setting, modify the `run.options` line your `preferences.txt` file to read:
```
run.options = -Dsun.java2d.dpiaware=false
```
That'll change it for sketches that you run (or export) from the PDE. If that *does* work, I can add it to the PDE itself (and make it the default until we have a more complete solution).

**Comment by aglie** [comment]
Thank you for the instruction on how to push the flag. It had no effect, though, as expected. Oh well, let's hope the problem will go away in the next versions of Swing/Java

**Comment by mastrolinux** [comment]
It is not windows only. I am able to reproduce the issue with Ubuntu Linux 16.04 LTS.

**Comment by benfry** [comment]
@mastrolinux There's a separate issue already open for Linux: https://github.com/processing/processing/issues/4183

**Comment by kaofishy** [comment]
As temporary workaround you can use a resource editor like Resource Hacker or Resource Tuner to edit the manifests of the java.exe and javaw.exe from Processing's JRE, and change the <dpiAware> tag from true to false. This will enable the "old style" scaling which, while not pretty, is at least usable.

**Comment by AlessandroSpadoni** [comment]
@kaofishy  I used Resource Hacker and I edited the files java.exe and javaw.exe contained in Processing folder->java->bin. Is this correct? because it is not working for me. I am using a Dell Inspiron 15 7000 series with Windows 10.

**Comment by JosephSamMorris** [comment]
@kaofishy Having the same issue as @kaofishy changed the dpiAware tag in the java manifests, but doesn't fix the issue.  Only allows for font size scaling in the IDE, not icons and interface.  I'm on Surface Pro 4 with Windows 10.

**Comment by JosephSamMorris** [comment]
@kaofishy Having the same issue as @AlessandroSpadoni.  I changed the dpiAware tag in the java manifests, but doesn't fix the issue. Only allows for font size scaling in the IDE, not icons and interface. I'm on Surface Pro 4 with Windows 10.

**Comment by hiemal** [comment]
I came from a pure designer background without reading into src of this project... Just curious, is there any "compiler/interpreter" like stuff for processing? i.e., something like 

`processing  myplot.pde > fig1.png`

**Comment by szhorvat** [comment]
If anyone has a workaround that makes Processing usable, please do post it here. @kaofishy's ResourceHacker based workaround didn't work for me (like for others). I am not sure if it is because I didn't do it correctly or because it just does not work with recent versions.  I experimented quite a lot with it before I gave up.

**Comment by aricooperdavis** [comment]
Would also be interested in this. For the moment I'm doing my coding in [Atom](https://atom.io/) and using the [Processing Package](https://atom.io/packages/processing) to run them.

**Comment by benfry** [comment]
Mostly fixed for the PDE for Processing 3.3. However, sketches don't yet auto-scale, which is now covered [here](https://github.com/processing/processing/issues/4894).

**Comment by benfry** [comment]
The Welcome screen is not fixed yet: https://github.com/processing/processing/issues/4896

If you find a part of the UI that's not scaling properly, [please file a new issue](https://github.com/processing/processing/issues/new). Do not add to this thread.

**Comment by KKprime** [comment]
I fixed the issue. 
here is how I did it. 


steps
Open the preferences menu, go down to the very bottom and click on the highlighted path. This will take you to the library where you can find additional preferences. Inline image 1
  It will work if you just click on the C:\ Users link. Next go down to the Preferences (text document not the the one with the .old file extension type) Open the txt doc in notepad if it does not do it automatically Inline image 2
  Once in the .txt doc scroll down to export.application.fullscreen=false MAKE THIS EQUAL TRUE. You have to close the application before you save the changes and close the preferences .txt doc. Save and exit the preferences.txt. open the processing page and check if this works. If not, you can also increase the editor font and console font directly in the original preferences menu. Just select the highest font in that specific case.  

-- Inline image 4
(INLINE IMAGES ARE ATTACHED)
![image](https://cloud.githubusercontent.com/assets/26018406/23328033/bfc33168-fae6-11e6-92e5-d6ba512a643a.png)
![inline 2](https://cloud.githubusercontent.com/assets/26018406/23328038/de65ecf0-fae6-11e6-9ea6-e38f213b06a0.PNG)
![inline3](https://cloud.githubusercontent.com/assets/26018406/23328056/04204ff8-fae7-11e6-8379-5f39a43825b3.PNG)
![inline4](https://cloud.githubusercontent.com/assets/26018406/23328063/2d282506-fae7-11e6-93e3-baa16790e2c0.PNG)
