### ISSUE TITLE
Problems with slow frame rates on OS X

### ISSUE THREAD

**Issue by arashsa** [processing/processing#2423]
In the Processing forums I have empirically verified that there is a problem with the latest version of Processing and latest version of Mac OsX. Sketches are running at a slower frameRate than should be expected. 

A simple sketch in full screen, size(displayWidth, displayHeight), where I just output the frameRate using text(), will have a frameRate of approximately 30, which is not what I have had in the past.

So I did some testing in Intellij. First I reverted back to older versions of Processing, which did not solve the issue. But then I reverted back to the Java v1.6 JDK, which solved the issue. When using the Java v.1.6 JDK I get frame rates over 160, whereas with the Java v1.8 JDK I max out at 30.

I also discovered some other things. In Java v1.6 there are some flickering, for instance if I run this:

    void setup() {
        size(displayWidth, displayHeight);
    } 

    void draw() {
        background(random(255));
    } 

There is this line that jumps up and down the screen. This line is not present when using the Java v1.8, the background changes colour without any flickering or lines.

**Comment by benfry** [comment]
So after a ton of effort, this is simply out of our control. To get a higher frame rate for a simple sketch like this, you're better off with P2D or P3D, which isn't limited by how fast the image can be moved to the screen. 

The difference between the Processing releases is Apple's Java 1.6 (which was much faster w/ graphics) and the Oracle's Java 1.7 and 1.8 (which is the only thing supported nowadays). Suffice to say, it's even more frustrating for me than it is for you.

I'm looking into other options for better performance with the default renderer, but the base issue here is unfixable.

**Comment by davidfokkema** [comment]
Thanks for your effort, @benfry!

**Comment by benfry** [comment]
Appreciated your help in looking into this, @davidfokkema.
