### ISSUE TITLE
'A library used by this sketch is not installed properly' with video on Windows

### ISSUE THREAD

**Issue by ggPeti** [processing/processing#2472]
Trying to open and loop a video on version 2.1.2 (same with 2.1.1) with this snippet

```
import processing.video.*;

Movie myVideo;
int video_width     = 768;
int video_height    = 576;
int video_slice_x   = video_width/2;
int window_width    = 1000;
int window_height   = video_height;
int draw_position_x = 0; 
boolean newFrame  = false;

void setup() {
  myVideo = new Movie(this, "input.mov");
  size(window_width, window_height, P2D);
  background(0);
  myVideo.loop();
}
```

but I get the following error:

```
A library used by this sketch is not installed properly.
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit  application.
```

on this line: `myVideo = new Movie(this, "input.mov");`

Tried installing GStreamer (x86-64), didn't help. Windows is 64 bit, but neither the 64 bit nor the 32 bit version of Processing 2.1.2 could run this code without error.
I'm out of ideas at the moment, can someone point me at the solution?

**Comment by AlhTronik** [comment]
Hello,
I have the same problem with my computer but i don't understand your solution
@ggPeti can you tell me what is the folder to move  and where ?

**Comment by ggPeti** [comment]
Try simply C:\Processing

**Comment by AlhTronik** [comment]
always the same problem.
What is the folder to move ?
