### ISSUE TITLE
Depth sorting wrong when drawing inside setup(), P3D

### ISSUE THREAD

**Issue by hamoid** [processing/processing#2483]
Depth sorting misbehaving when drawing inside setup()? (2.1.2, Linux, 4 year old Intel Graphics)

    void setup() {
      size(400, 400, P3D);
      // bug
      doit();
    }
    void draw() {
      // no bug
      //doit();
    }
    void doit() {
      fill(255);
      rect(200, 200, 100, 100);
      fill(128);
      translate(50, 50, -50);
      rect(200, 200, 100, 100);
    }

Bug:
![bug](https://cloud.githubusercontent.com/assets/108264/2823721/5ebe4804-cf23-11e3-9474-3c013f033632.png)

No bug:
![nobug](https://cloud.githubusercontent.com/assets/108264/2823722/63ee1e30-cf23-11e3-8a5b-9e79eed06d69.png)

**Comment by JakubValtar** [comment]
Can't reproduce on my integrated Intel HD Graphics 4600.

**Comment by hamoid** [comment]
My current laptop (Intel HD 4000) shows all the examples above correctly on Arch Linux and Processing 3.0a5. I guess this can be closed. Should there be a note somewhere mentioning that old GPUs may behave in strange ways?

**Comment by codeanticode** [comment]
Yes, it is noted in the [wiki](https://github.com/processing/processing/wiki/OpenGL-Issues).

**Comment by chrisjj** [comment]
Here, on Integrated Intel® HD Graphics 2500/4000 with Processing 3.0.2.

doit() inside setup() gives no rectangles:

![image](https://cloud.githubusercontent.com/assets/6157073/18468210/c745dbde-799a-11e6-9d32-298bc13248b2.png)

doit() inside draw() gives correct rectangles:

![image](https://cloud.githubusercontent.com/assets/6157073/18468234/df52bc06-799a-11e6-9426-541f0b8fe0c3.png)

**Comment by chrisjj** [comment]
> Maybe my 4 year old Intel graphics are buggy? Today I noticed this:
> Can anyone confirm it? I don't want to post another issue if it's just my computer.

In Integrated Intel® HD Graphics 2500/4000 with Processing 3.0.2 I get:

![image](https://cloud.githubusercontent.com/assets/6157073/18468376/8dc474c8-799b-11e6-9cfc-e5e35945e663.png)
