### ISSUE TITLE
Need to pass command-line args to sketch

### ISSUE THREAD

**Issue by JetForMe** [processing/processing#2552]
The Commander.java code as it is discards any unrecognized command-line arguments to processing-java. This limits the utility in more automated settings. Instead of balking, it should collect all unrecognized args and just pass them to the execution of the built sketch.

http://forum.processing.org/two/discussion/comment/18916

**Comment by benfry** [comment]
Implemented for 3.0 beta 4.

**Comment by JetForMe** [comment]
Thanks!
