### ISSUE TITLE
Check if library is installed before running sketch; if not, prompt to install

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#2566]
When sharing sketches with others, the sketches can't be run unless all required libraries are installed.

Add logic that, when a sketch is about to be run, checks to see if the required libraries are installed. This could be based on looking at any import statements in the code, and then taking a best guess about what's needed.  For example, if my code includes: `import peasy.*;` we can assume I would need the PeasyCam library installed.

If the libraries are installed, run per usual.  If they are missing, introduce a prompt to facilitate download and installation through the contribution manager.  (For example, "This sketch may require ___ and ___. Download and install them now?")

Request posted per @benfry in our conversation today.

**Comment by joelmoniz** [comment]
@Manindra29 Thanks! I've submitted PR #3155, where I've done the appropriate checks from within a function that calls prepareRun() in processing.mode.java

**Comment by benfry** [comment]
Incorporated for 3.0a6. Let the debugging begin!
