### ISSUE TITLE
Add retina/hi-dpi support to OpenGL

### ISSUE THREAD

**Issue by benfry** [processing/processing#2573]
Looks like it's on its way or may have arrived with JOGL 2.2:
https://jogamp.org/bugzilla/show_bug.cgi?id=741

I didn't think we had an open issue for this, so this is just to track any updates.

**Comment by neilpanchal** [comment]
@codeanticode Thanks. I tried this and found a problem.

```processing 
{ PJOGL.RETINA = true; }

void setup() {
    size(1200, 1200, P2D);
    background(255);
    ... do stuff;
}

void draw() {
    strokeWeight(1);
    stroke(0, 50);
    ... do stuff;
}
```

When using `P2D` as an argument to `size()`, I get the following result when plotting Lissajous curves on a retina display with `strokeWeight(1)` and `stroke(0, 50)`. 

![screen shot 2015-04-27 at 8 27 23 pm](https://cloud.githubusercontent.com/assets/8161031/7362312/eef8245a-ed1b-11e4-9f00-c859e2d4fd1f.png)

When using `P3D` or `OPENGL` as an argument, the result is smooth as shown below: 

![screen shot 2015-04-27 at 8 27 49 pm](https://cloud.githubusercontent.com/assets/8161031/7362316/f77e379a-ed1b-11e4-8fbf-b024af7a09b8.png)

`P3D` and `OPENGL` render fine but `P2D` render has those ugly blobs/artifacts. Also, the `saveFrame("####.png")`  doesn't save the image in full retina resolution despite of declaring `    hint(ENABLE_RETINA_PIXELS);` in the `void setup()` method. 

Hope this helps,
Neil

**Comment by benfry** [comment]
@codeanticode Is this officially set?

**Comment by codeanticode** [comment]
Yes.
