### ISSUE TITLE
[OpenGL] ending a noLoop() sketch with noSmooth() glitches

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#2592]
Processing 221
Mac OS X 10.9.3

The image i use:
![test_19](https://cloud.githubusercontent.com/assets/738650/3268917/e691d500-f2e3-11e3-9174-45bcba2a136f.png)

The result:
![screen shot 2014-06-13 at 12 14 49 pm](https://cloud.githubusercontent.com/assets/738650/3268923/f6dacc5a-f2e3-11e3-87d2-85a4bb2a0d4d.png)

If you remove noSmooth() the glitch is gone.

```java
PImage img;

void setup() {
  size(512, 512, P2D);
  img = loadImage("test_19.png");
  noLoop();

}

void draw() {
  image(img, 0 ,0);
  noSmooth();
}
```

**Comment by codeanticode** [comment]
starting with the next release, smooth()/noSmooth() will be callable only once during setup.

**Comment by REAS** [comment]
We've discussed this change at length and it's the result of the difference between how Java and OpenGL rendered back in 2001 in relation to how they do it in the present. We feel that we need to make smoothing something that is set once for each program.
