### ISSUE TITLE
Default font is used with PGraphicsRetina2D

### ISSUE THREAD

**Issue by slambert** [processing/processing#2617]
adding `"processing.core.PGraphicsRetina2D"` to `size()` causes the fonts loaded with `createFont()` to change to some default (like Lucida Grande or something). 

See sample sketch and screenshots below. For the sketch to work, you may have to change FranklinATFBQ-Regular to another font you have available.

```javascript
PFont myFont;

void setup() {
//  size(500, 500, "processing.core.PGraphicsRetina2D"); // font changes to some default
  size(500, 500); // font will load correctly
  smooth();

// uncomment the following two lines to get a list of available fonts
//  String[] fontList = PFont.list();
//  println(fontList);
  myFont = createFont("FranklinATFBQ-Regular", 25, true);
  textFont(myFont);
  textAlign(CENTER, CENTER);

}

void draw () {
  fill(0);
   text("Presto Change-o", 250, 250);
}
```
![off](https://cloud.githubusercontent.com/assets/67271/3413166/8a456bf6-fe08-11e3-8ed5-39c6a03e4df7.png)

![on](https://cloud.githubusercontent.com/assets/67271/3413179/ae3a61ba-fe08-11e3-9579-4641a35aef30.png)

**Comment by benfry** [comment]
Fixed for beta 1.

**Comment by slambert** [comment]
Exciting! Thanks.

**Comment by benfry** [comment]
Workaround in the meantime is that if you call `textFont()` again inside `draw()`, it should work properly. (I recommend using alpha 10, which also has a lot of updates for retina support and this sort of thing.)
