### ISSUE TITLE
Processing doesn't work with proxies

### ISSUE THREAD

**Issue by jimaobian** [processing/processing#2643]
Operation system: Mac OS X 10.9.4
Processing Version: 2.2.1

When using the SOCKS Proxy in Network configuration, Processing cannot start the Application normally.
Once the SOCKS Proxy is Off, Processing can run smoothly

![screen shot](https://cloud.githubusercontent.com/assets/3905677/3640963/dd5a2e34-10ab-11e4-92e3-cadd7c2473ba.png)

**Comment by Akarshit** [comment]
The socks proxy and port that we put into preference.txt is not getting used anywhere(in Preference.java) , i will do PR to fix this and hope that this bug is solved but someone will have to check as i don't have access to mac.

**Comment by benfry** [comment]
It should be getting set in `PApplet` (which is used by the PDE as well).

**Comment by Akarshit** [comment]
@benfry i was not able to find the code setting up socks proxy for the PDE, though i made a PR that sets socks proxy from preference.txt . This got the things working on my system and hopefully would work on others too.

**Comment by benfry** [comment]
Thanks, incorporated for 3.0a8.
