### ISSUE TITLE
radius for rect not working on PShape

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#2646]
Since we have round corners now it would be nice if that also works with createShape.
I looked in the code and I can understand it's a bit tricky to do.

Also shouldn't rectMode etc. not influence the createShape? I guess it would make sense.

```java
PShape square;  // The PShape object

void setup() {
  size(100, 100, P2D);
  rectMode(CENTER);

  square = createShape(RECT, 0, 0, 50, 50, 17); // <<<<<<<<<<<<<<<
  square.setFill(color(0, 0, 255));
  square.setStroke(false);
}

void draw() {
  shape(square, 25, 25);
}
```

**Comment by benfry** [comment]
Decision here is to drop the `mode` parameter and inherit from the parent sketch, the way that we do with other features like `fill()` and `stroke()`.
