### ISSUE TITLE
Edit/Enhance Auto-completion

### ISSUE THREAD

**Issue by REAS** [processing/processing#2681]
We need to discuss how to curate/edit the autocompletion list. It's too technical for beginners. Does it need to be this way? Should we have a "basic" and "advanced" mode for it? I've attached an image as a starting point. We have discussed it briefly before, but now it's a priority with these alpha releases. @shiffman 

![screen shot 2014-07-31 at 11 30 53 am](https://cloud.githubusercontent.com/assets/677774/3769450/33165810-18e1-11e4-8966-8c441c61e032.png)

**Comment by jondo** [comment]
Does version 3.0a5 provide autocompletion? It seems not.

**Comment by shiffman** [comment]
autocompletion was temporarily broken in earlier alphas  see #3111.

**Comment by shiffman** [comment]
@Manindra29, I propose we close this issue and I could open a new "enhancement" issues for "obtaining argument names" someday, but this is a larger endeavor that likely won't happen for 3.0.

I believe the last code completion "to do" item is #2951.

**Comment by benfry** [comment]
Closing per Dan's suggestion...
