### ISSUE TITLE
command-space on mac is shortcut for spotlight

### ISSUE THREAD

**Issue by shiffman** [processing/processing#2699]
On mac OS X, command-space for code completion is not working for me due to it being a shortcut for spotlight search.

![screen shot 2014-08-01 at 11 20 54 am](https://cloud.githubusercontent.com/assets/191758/3780781/841a8250-198f-11e4-8579-cb354231b900.png)

**Comment by enzyme69** [comment]
@shiffman It does not work on MacOS, I tried Cmd+Space (brings Spotlight), and Ctrl+Space, also didn't work :(

**Comment by shaabhishek** [comment]
@shiffman having the same problem as @enzyme69 :/
No trigger suggest as I press ctrl+space

**Comment by benfry** [comment]
If ctrl-space isn't working for you, please file a new issue. This issue is from two years ago, when command-space was accidentally assigned to autocomplete for a short time. It's been fixed.

**Comment by enzyme69** [comment]
I proceed to new Issue:
https://github.com/processing/processing/issues/4658

Thanks for looking into this.

**Comment by benfry** [comment]
Thanks; locking this issue to avoid confusion.
