### ISSUE TITLE
Missing localizations

### ISSUE THREAD

**Issue by AmnonOwed** [processing/processing#2710]
When using a local language (testing with Dutch), I found there are a few Strings in the menus missing from the localization and thus still in English, which now stands out, because the rest is in the local language. So far I found the following:

- [x] File > Sketchbook
- [x] File > Sketchbook Tree
- [ ] Edit > Undo (once you start typing something)
- [ ] Edit > Undo Addition (once you start typing something)
- [ ] Edit > Undo Deletion (once you start typing + deleting something)
- [ ] Edit > Redo Addition (once you start typing + deleting something)
- [x] Preferences > Tooltip for Editor and Console font
- [x] Preferences > Tooltip for Background color when Presenting
- [x] New tab popup
- [x] Change name of tab popup
- [ ] And on closing the application without saving: Save changes to [Sketch Name]? Yes / No / Cancel
- [ ] When archiving an unsaved sketch: Save => Please save the sketch before archiving.
- [ ] When canceling archiving a sketch: Archive sketch canceled.
- [ ] When renaming unsaved first tab: Sketch is untitled => How about saving the sketch first before trying to rename it?

**Comment by benfry** [comment]
Can this be closed? This seems to have been abandoned.

**Comment by AmnonOwed** [comment]
It seems so.

**Comment by nok** [comment]
Yes, all issues had been fixed.

Sorry for my dilatory reply, currently I'm working on my master thesis.

Happy coding,
Darius
