### ISSUE TITLE
Export unsaved sketch > agree to save prompt > export doesn't finish

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#2724]
iMac / OS 19.9.4 / Processing 302
When you want export and you'r sketch is not save. Processing ask to save before, when you click "OK" the sketch is save but nothing happen more : no export and the rollover stay yellow like the picture below.
![capture decran 2014-08-03 a 10 37 58](https://cloud.githubusercontent.com/assets/3332269/3790157/382cebce-1aea-11e4-9194-79b1673a3122.png)

**Comment by benfry** [comment]
Cannot reproduce with 3.0 beta 3.
