### ISSUE TITLE
Text looks blurry in GL Retina

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#2739]
```java
{ PJOGL.RETINA = true; } // for now

public void setup() {
//  size(640, 480, "processing.core.PGraphicsRetina2D");
//  size(640, 480, JAVA2D);
  size(640, 480, P2D);
//  smooth(4);
  textFont(createFont("Courier", 24));

  noStroke();
  fill(0);
}

public void draw() {
  background(180);

  for (int x = 0; x < width + 50; x += 50) {
    for (int y = 0; y < height - 50; y += 50) {
      ellipse(x, y, 40, 40);
    }    
  }

  text("Text doesn't look particularly crisp, though", 0, height - 20);
} 
```

A workaround is to create the text at double the size:

```java
textFont(createFont("Courier", 48));
textSize(24);
```

**Comment by dhawangupta** [comment]
Running the above code gives error : Cannot find anything named "PJOGL.RETINA". I have tried import processing.opengl.*;

When I run it without the first line, text is fine and sharp.
After adding the workaround suggested, text looks blurry.

I'm working on Processing 2.2.1 on Win8.1 (x64).

**Comment by codeanticode** [comment]
@dhawangupta  Retina is not supported on 2.2.1. This ongoing discussion is about implementing retina in 3.x

**Comment by codeanticode** [comment]
@benfry I started to look at this issue, and I think that one way to solve it could be to add a pixelFactor field to PFont, in a similar way you did for PImage, and scale up and down things appropriately. For instance, in PApplet.createFont:

```java
return new PFont(baseFont.deriveFont(size * g.pixelFactor), smooth, charset, stream != null, g.pixelFactor); 
```

and then in the PFont constructor:

```java
public PFont(Font font, boolean smooth, char charset[], int factor) {
  ...
  this.pixelFactor = factor 
  size = font.getSize() / factor;
  ...
```

among other things. I'm not 100% familiar with the way the PFont internal work, let me know if this could be a reasonable approach.

**Comment by benfry** [comment]
I think there's a more transparent option, let's look at it today/tomorrow.
