### ISSUE TITLE
Add continuous integration via Travis CI

### ISSUE THREAD

**Issue by federicobond** [processing/processing#2747]
I began playing this afternoon with building Processing using Travis CI. Travis is a continuous integration platform for open source projects. That means it attempts to compile and run tests for Processing on every pull request and commit, and can let you know when the build failed.

For the moment it does not run any tests (I couldn't figure out how to run them) but it attempts to build everything so it should catch the most flagrant errors. This could be improved later so that it makes sure that commits adhere to a certain code style, files are in the correct encoding and no extraneous whitespace is added.

This is how a build looks: https://travis-ci.org/federicobond/processing. Of course, you don't even have to visit their website. Travis can notify GitHub directly so that you see the status of the build right besides the merge button.

If you are interested in this, I can submit a PR.

**Comment by crazymaster** [comment]
How is the progress?

**Comment by federicobond** [comment]
Well, it's a bit stalled right now because I don't have enough permissions
to setup Travis at the processing/processing repo myself, but I would love
to help any of the core developers with this.

**Comment by andyli** [comment]
Anyone want to resume this work? If no, I can send a PR and help maintain it in the long run. I'm maintaining a handful of CIs for the [Haxe language](https://github.com/HaxeFoundation/haxe) and I can say it really helps to quickly identify bad commits and PRs.

**Comment by totovr** [comment]
[Travis-Processing](https://github.com/totovr/Travis)

**Comment by sampottinger** [comment]
Hello hello! Writing this to link together a few threads...

I am following up here in relation to #5753 which, in moving to OpenJDK / AdoptOpenJDK, makes it possible to do cross builds as described at https://gist.github.com/sampottinger/939441d7277d318189ec81844e3ca516. I am currently working on a PR at https://github.com/sampottinger/processing/pull/7 which demonstrates use of CI.

**Comment by benfry** [comment]
Further development here: https://github.com/processing/processing4
