### ISSUE TITLE
implement export to other platforms with processing-java on the command line 

### ISSUE THREAD

**Issue by rahji** [processing/processing#2760]
Typing:

    /usr/local/processing-2.2.1/processing-java --export --platform=windows

Results in:

    The --platform option has been removed from Processing 2.1.

It seems like processing-java has not been updated to be in sync with 2.2.1? (The platform option was missing in 2.1 but brought back in 2.2 as far as I understand it - using the export menu item allows me to export to Windows from Linux just fine).  

BTW this problem made itself known because I use the processing package for Sublime Text, which uses processing-java to export. https://github.com/b-g/processing-sublime

**Comment by GKFX** [comment]
Just to say I'm doing this now.
