### ISSUE TITLE
TweakMode replaces dots with commas

### ISSUE THREAD

**Issue by SableRaf** [processing/processing#2799]
After using tweak mode, a line like 

```float f = 0.5;```

becomes

```float f = 0,5;```

I'm using OSX 10.9.2 in French so this might be a problem with internationalization. However, I changed the number separator in the preferences to "." then restarted Processing and the issue was still there.

note: A friend reported the same issue in Windows 7 in German. Another using Ubuntu in English didn't have the issue.

**Comment by benfry** [comment]
Replaced the string compares. 

The `Locale.US` issue should have fixed this problem in the current source, because that Locale is always present: http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#getAvailableLocales()
