### ISSUE TITLE
Suggested Edits : "Contributing to Processing with Pull Requests" wiki

### ISSUE THREAD

**Issue by Manindra29** [processing/processing#2801]
We've created a wiki page on [Contributing to Processing with Pull Requests](https://github.com/processing/processing/wiki/Contributing-to-Processing-with-Pull-Requests)

If you'd like to suggest any changes or edits, please comment here. This issue shall stay open.

**Comment by benfry** [comment]
Style guidelines finally posted: https://github.com/processing/processing/wiki/Style-Guidelines

**Comment by kiwistrongis** [comment]
Thanks :).
