### ISSUE TITLE
Old version number shown in Mode Manager dialog.

### ISSUE THREAD

**Issue by jdf** [processing/processing#2843]
The Mode Manager, as of this writing, shows version 0368, but Python Mode is up to 0373. The 0368 version was replaced by 0369 nine days ago.

![screen shot 2014-09-07 at 2 31 16 pm](https://cloud.githubusercontent.com/assets/55948/4179234/49346db8-36bd-11e4-93e5-a92278bc0680.png)

![screen shot 2014-09-07 at 2 32 56 pm](https://cloud.githubusercontent.com/assets/55948/4179240/71aacc60-36bd-11e4-9af8-6cb43d1bba7e.png)

**Comment by Akarshit** [comment]
@alingedleft From the comments it looks that this issue has been fixed. Can someone close this.
