### ISSUE TITLE
JAVA 8 and Processing 3 / Export problem with moving window

### ISSUE THREAD

**Issue by knupel** [processing/processing#2909]
Hello, when we use Processing 3, with Java 8 on OSX.9 or 10. The export application have a window problem when we move the window, this one go to the minumum size.
![capture d ecran 2014-10-24 a 10 49 04](https://cloud.githubusercontent.com/assets/3332269/4767144/a332f4ee-5b5a-11e4-8370-577f9eaef303.png)
No problem with Processing 221 on Java 8.
No Problem with Java 7 with processing 3.
There is a trick, but I think is not really good : 

```
void setup() {
  size(600,600) ;
  /*
  With JAVA 8 and Processing 3
  if we use this function with "true" there is no bug export window when we move this one
  */
  frame.setResizable(true);
}
```

But when we write `frame.setResizable(false);`the bug is back

**Comment by StanLepunK** [comment]
I read in the [Supported-Platforms](https://github.com/processing/processing/wiki/Supported-Platforms) you restart to solve the problem with Java 8, but not with Java 9 :) So I think this post can be re-opened ? I can add information ; when you export an app with java embeded there is no problem to move the window, only when Java is not embeded.

**Comment by benfry** [comment]
That's why you should embed Java. It's an Oracle bug, and it sounds like you're using the version of Oracle's Java that doesn't have the fix.

**Comment by StanLepunK** [comment]
Weird because I reinstall java 8 just yesteday. My version is 8.45, I check is the last one.
That's good for Processing if it's a java bug, less work ; just hope Oracle fix that as soon as possible.
