### ISSUE TITLE
Even spacing on curves with bezierPoint() and curvePoint()

### ISSUE THREAD

**Issue by REAS** [processing/processing#2919]
The bezierPoint() and curvePoint() functions use algorithms that calculate points along the curves with higher density around around tighter curves rather than evenly spacing the points along the curves. This is the goal of these functions. The other way, even spacing, is sometimes preferred. This may be added in the future, but it's not a current priority. Andrew Glassner has written code for even spacing along curves in his http://www.imaginary-institute.com/resources/AULibrary/AULibrary.php library.

**Comment by JakubValtar** [comment]
Hi, I made an example and added it to the docs repository. This is my first example, feedback is welcome.

https://github.com/processing/processing-docs/pull/202

**Comment by benfry** [comment]
Awesome, thank you. Closing this feature request since we're handling it via an example rather than API.
