### ISSUE TITLE
Blank file when saving with full hard drive

### ISSUE THREAD

**Issue by oolong** [processing/processing#2923]
I just opened a sketch I've been working on in Processing 2.1.1 in Processing 3, only to find that the main file was totally blank. Looking with a file manager, the file is only 1 byte big. It's still blank when I open it in Processing 2.1.1, so maybe the Processing 3 thing is a red herring.

The other files of this sketch seem to be fine. I'm really pretty certain I didn't blank this file myself before I closed it and re-opened it.

*edit*: My hard drive is full, and I hadn't realised, so this is at least partly my fault - but shouldn't Processing say 'failed to save!!' if it fails to save, or something like that?

*edit 2*: I cleared a load of space on my hard drive, but *maybe* I didn't save it properly afterwards - it's truncated the file this time, rather than completely failing to save. This time I selected all and copied it to my clipboard before saving, in case something like this happened again, but apparently Processing also quietly empties the clipboard when you quit, or something?

**Comment by Pomax** [comment]
ran into this as well - effectively lost a day's work because it didn't report an error

**Comment by benfry** [comment]
Contributions welcome. Obviously anything that saves a file is code that needs to be rewritten very carefully. It's been on my list (to use proper practice and save temp files first), but I've never had the time to implement it.

**Comment by Pomax** [comment]
Unfortunately I'm involved in too many projects already and won't have time to help dive into this for probably a considerable amount of time. Happy to report, unable to do much more than that =/

**Comment by benfry** [comment]
Turns out this was mostly done in the alpha releases, but I've added more bulletproofing to hopefully avoid the situation.
