### ISSUE TITLE
ToolTipManager error

### ISSUE THREAD

**Issue by shiffman** [processing/processing#2926]
I've been seeing the following error with 3.0a4 periodically on my machine (Mac OS X, 10.9) as well as several student and classroom machines (also Mac OS X) at ITP. 

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at javax.swing.ToolTipManager.initiateToolTip(ToolTipManager.java:478)
```

[Here's the full error](https://gist.github.com/shiffman/15bf7d9f06908bf68388).  The error usually repeats ~3-5 times.

I have yet to pinpoint a precise sequence to trigger the error, but it fills the console and also periodically induces the PDE to crash.  

@Manindra29 is this perhaps related to code completion or a different ToolTip?  We are looking into it more and will discuss on this thread.

**Comment by douira** [comment]
This error still occurs with me like @shiffman described at the beginning. It shows up a few hundred times in the console and lags the Editor for a few seconds printing it all out. I'm running 3.0.2 on OS X 10.11.3 (El Capitan) but it has also happened on other versions of both PDE and OS X. Full error: (almost the same) https://gist.github.com/douira/55aea671a9c8a3d0fe72
