### ISSUE TITLE
Program not launching when changes are unsaved

### ISSUE THREAD

**Issue by REAS** [processing/processing#2931]
I'm still trying to get the facts straight, but when a program has unsaved changes, I'm having trouble launching. On Mac OS, it's a spinning beach ball. After I save the changes, it will launch. It may be exclusive to P2D and P3D, but I'm not sure.

**Comment by benfry** [comment]
Has anyone seen this recently?

**Comment by REAS** [comment]
I haven't seen it with the recent alpha and new beta releases. When I go back to 3.0a5 for some sketches, I have the issue. I think it's safe to close.
