### ISSUE TITLE
program wont close on OS X Yosemite 

### ISSUE THREAD

**Issue by Taitrnator** [processing/processing#2942]
Sometimes, the program will open, and will become uncloseable, to the point that it prevents shutdown, no force close command offered on shutdown.

![image](https://cloud.githubusercontent.com/assets/6832528/5031497/c5912714-6b1c-11e4-9337-fdd8f836a16e.png)

**Comment by benfry** [comment]
Need steps to reproduce this. Most development happens on Yosemite and I've never seen this, so we need some help tracking it down.

**Comment by benfry** [comment]
No followup; closing.
