### ISSUE TITLE
sketchbook window doesn't update when sketches are added, renamed, etc

### ISSUE THREAD

**Issue by benfry** [processing/processing#2944]
In the current source, new sketch names are not added to the sketchbook and they're not renamed after changes are made. This is an error (and a regression from earlier releases.)

Separately, there have been requests to reload the menu when the sketchbook folder is modified externally (i.e. from the Finder or Windows Explorer). That's a separate feature request: https://github.com/processing/processing/issues/1831

**Comment by Akarshit** [comment]
If @JayDusara is not working on improving  #3178 . I would like to work on the suggestion given there and fix issues related to the updation of SketchBook
