### ISSUE TITLE
PDE losing focus after closing a sketch

### ISSUE THREAD

**Issue by shiffman** [processing/processing#2948]
I'm having the following issue "sometimes", am not clear exactly why or why not it occurs.  I've also noticed it on a student's laptop at ITP.

OS 10.9
* Launch Processing
* Open a finder window
* Run a sketch
* Close the sketch by hitting esc or the red x

This results in the OS defaulting back to the finder and the Processing PDE going to the background.  if you close all finder windows, the error does not occur.

**Comment by Plastix** [comment]
I can't reproduce this on OSX 10.10.

**Comment by benfry** [comment]
I was able to reproduce this after Dan had reported it (and he demoed it in person), but still unsure why it was/is happening, and couldn't make it happen consistently. 

@shiffman are you still able to reproduce this on your machine with the current source? Wonder if a more recent Java update or OS X 10.10 fixed it.

**Comment by shiffman** [comment]
I can't seem to reproduce it anymore, tried a few different ways.  I think we can safely close this and re-open if it occurs again.

**Comment by benfry** [comment]
Thanks for checking.
