### ISSUE TITLE
Examples do not show if "compatibleModesList" field is absent in the .properties file

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#2954]
At present, examples-packages require that compatible modes be listed in the .properties file. Otherwise, the examples-packages never are never shown in the Examples dialog.

NB: To resolve this, shall I proceeding by assuming that if this field is left out, the examples-package ought to be compatible with both the Java (2.0) and the Java modes?

**Comment by benfry** [comment]
Just an update here... 
* No need to deal with ExperimentalMode any more. 
* It should be `examples.properties` not `examples-package.properties`.

**Comment by joelmoniz** [comment]
@benfry Ah yes. I'd forgotten to update the title name. I had (completely) renamed `examples-package` to `examples` in [this](https://github.com/processing/processing/commit/31a186ace3318d20fb88730a58cc95519548b9ab) commit (as a result of [this](https://github.com/processing/processing/issues/2953#issuecomment-63330444) discussion).

**Comment by joelmoniz** [comment]
@benfry It seems that contributed examples have been removed altogether from the Examples window. When adding them back in, under what heading do I list them? Here's what I see at present:

![image](https://cloud.githubusercontent.com/assets/4526417/8286992/fff09dea-191d-11e5-9685-9f0ce2cbde25.png)

So shall I add in one more folder at the bottom, that shows contributed examples? And what should it be titled? `Examples`, `Contributed Examples` or `Installed Examples`, maybe?

**Comment by benfry** [comment]
The base issue here—examples not compatible when they don't specify `compatibleModesList` is now fixed. 

Also, that entry in the .properties file is now `modes`, in keeping with the brief naming used everywhere else.

**Comment by joelmoniz** [comment]
@benfry : Thank you. Should I open another issue for the contributed examples not being visible in the `Examples` window? I have a fix ready as well, but am unsure about how to title this in the JTree.

**Comment by benfry** [comment]
If there's an issue with that, yes.
