### ISSUE TITLE
Add attrib() method to PGraphics

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#2963]
The shader API is currently limited to handle only the following vertex attributes: 

- position
- color (fill, stroke)
- texture coordinates
- normal vector
- material properties (ambient, specular, and emissive colors, shininess)

After the [Denver retreat](https://twitter.com/digitalcoleman/status/533784122179596288), it has been decided to add the "attrib" function to the PGraphics API to let users specify generic per-vertex attributes. This function tentatively has the following signature:

```java
void attrib(String name, float... values);
void attrib(String name, int... values);
void attrib(String name, boolean... values);
```

Usage example:

```java
float angle;
void setup() {
  size(400, 400, P3D);
  noStroke();
}

void draw() {
  background(0);

  pointLight(200, 200, 200, width/2, height/2, -200);

  translate(width/2, height/2);
  rotateY(angle);

  beginShape(QUADS);
  normal(0, 0, 1);
  fill(50, 50, 200);

  // A scalar attribute named brightness, affecting the next two vertices
  attrib("brightness", 0.1);

  // A vector attribute named tangent, affecting the first vertex
  attrib("tangent", 0.1, 0.8, 0.1);
  vertex(-100, +100);
  // Another tangent vector, affecting the second vertex
  attrib("tangent", -0.3, 1, 0);
  vertex(+100, +100);
  fill(200, 50, 50);

  // A new brightness value, affecting the last two vertices
  attrib("brightness", 0.5);

  attrib("tangent", 0.5, 0.5, 0.1);
  vertex(+100, -100);
  attrib("tangent", 0.1, -0.9, 0);
  vertex(-100, -100);
  endShape();

  angle += 0.01;
} 
```

The first time attrib() is called with a new attribute name, the renderer needs to automatically initialize all the corresponding internal variables (VBO's and backing arrays) needed to handle this attribute. The tessellator also needs to interpolate the values for the attributes, in the same way it now does for the built-in attributes.

**Comment by codeanticode** [comment]
Implemented, needs debugging.

**Comment by codeanticode** [comment]
Working on immediate and retained mode. 

However, attributes need special handling when they represent a position, a normal vector, or a color. Right now, the attribute "kind" is automatically guessed from its name using the following rule:

* names starting with "pos" indicate positional attributes
* names starting with "norm" indicate normal attributes
* names starting with "color" indicate color attributes
* regular attributes otherwise

This solution obviously is not very satisfactory. A separate method could be better, for example:

attribKind(name, kind)

where kind is a constant taking three values: POSITION, NORMAL, and COLOR:

Example of use:

```java
PShader sh;
PShape star;
public void setup() {
  size(400, 400, P2D);
  star = createShape();
  star.beginShape();
  star.strokeWeight(3);
  star.stroke(0);
  star.attrib("otherColor", color(0, 0, 1));
  star.attribKind("otherColor", COLOR);
  star.vertex(0, -50);
  star.vertex(14, -20);
  star.vertex(47, -15);
  star.vertex(23, 7);
  star.vertex(29, 40);
  star.vertex(0, 25);
  star.vertex(-29, 40);
  star.vertex(-23, 7);
  star.vertex(-47, -15);
  star.vertex(-14, -20);
  star.endShape(CLOSE);
  sh = loadShader("frag.glsl", "vert.glsl");
  shader(sh);
}

void draw() {
  background(150);
  fill(255, 0, 0);
  translate(mouseX, mouseY);
  shape(star);
}
```

attribKind() could be called only after the first attrib() call defining the new attribute. @benfry, @REAS, @shiffman any thoughts on this?

**Comment by benfry** [comment]
I think I like: 
* `attrib()` for the default fellas
* `attribColor()` 
* `attribPos()` (or position? or?)
* `attribNormal()`
With the idea being that it helps self-document the code (which helps with reading and debugging). So instead of a one-time init function that sets the type, this does it automatically behind the scenes the first time it's used.

**Comment by codeanticode** [comment]
I like your idea. I would go with attribPosition(), although is somewhat long, because we don't use pos anywhere else, and we do use position as the built-in attribute to transfer the xyz coords to the vertex shader.

**Comment by benfry** [comment]
Works for me. I'm planning to push out an alpha 11 sometime today (or tomorrow), which is hopefully the last alpha before the first beta.

**Comment by codeanticode** [comment]
I'm working on https://github.com/processing/processing/issues/3384 right now, but will be great if we can include this into alpha 11.

**Comment by codeanticode** [comment]
last bits implemented in https://github.com/processing/processing/commit/a99c094521bf24527eec01ac7c675c9b9e4db04a
