### ISSUE TITLE
OpenGL sketches do not terminate, have to be killed

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#2982]
When closing OpenGL window by clicking on the cross in the title bar, window closes but the process keeps running. To close it completely, it has to be stopped with stop button in Processing or killed when running directly from Eclipse.

Also, OpenGL sketches can't be closed with ESC key.

Encountered on Windows 8.1 64bit.

**Comment by merttim** [comment]
Hi all. I'm using Processing via Eclipse and trying to kill the OpenGL sketch from my code. Can you help me out with that?

**Comment by benfry** [comment]
@merttim Please use the forum for questions. 

@codeanticode This sounds like a blocker for 3.0a6.

**Comment by codeanticode** [comment]
Fixed with recent changes: https://github.com/processing/processing/commit/43166615f1e4a0fa2d97a8d9e5f35becc24ee775
