### ISSUE TITLE
Problems with XnVSessionManager for NITE examples

### ISSUE THREAD

**Issue by mucy129** [processing/processing#2983]
I'm working on one project at my university and I need to run Slider2d example. I always get error: cannot find a class or type named ''XnVSessionManager''. Same message appears for other NITE examples like circle ctr and hands. I've also tried to work with the older processing version 1.5.1 but there I can't import library. Does anyone knows the solution or a very similar example to Slider2d that I could run on the new version of Processing without using this XnVSessionManager?

**Comment by ningt** [comment]
I know this this is an old thread, but in case anyone are trying to run Slider2d example, **Processing 2.2.1 and Simple-OpenNI 0.27** can fix this issue. A working example with detail installation guide can be found here (https://github.com/ningt/slide2d)
