### ISSUE TITLE
Wrong width textbox in preferences.

### ISSUE THREAD

**Issue by gtitaev** [processing/processing#2986]
Menu File -> Preferences

Processing 3.0a4
![p3a4](https://cloud.githubusercontent.com/assets/6291442/5177509/7c98706e-7484-11e4-9f6c-2f9db920d0f0.png)

Processing 3.0a5
![p3a5](https://cloud.githubusercontent.com/assets/6291442/5177510/7c98f700-7484-11e4-93fc-9fd2fbf5302a.png)

**Comment by benfry** [comment]
https://github.com/processing/processing/issues/67
