### ISSUE TITLE
cannot run sketch with this particular SVG file

### ISSUE THREAD

**Issue by carheart** [processing/processing#2992]
In short sketch could not be built (java mode, processing v 3.0a5) with following SVG file at all
file: https://openclipart.org/detail/184667/2-euro-coin-by-frankes-184667

Build messages: 
```
Exception in thread "Animation Thread" java.lang.NullPointerException at 
processing.core.PShapeSVG.parseStyleAttributes(PShapeSVG.java:1334) at 
processing.core.PShapeSVG$Gradient.(PShapeSVG.java:1419) at 
processing.core.PShapeSVG$LinearGradient.(PShapeSVG.java:1441) at 
processing.core.PShapeSVG.parseChild(PShapeSVG.java:380) at 
processing.core.PShapeSVG.parseChildren(PShapeSVG.java:306) at processing.core.PShapeSVG.(PShapeSVG.java:295) at processing.core.PShapeSVG.parseChild(PShapeSVG.java:338) at 
processing.core.PShapeSVG.parseChildren(PShapeSVG.java:306) at processing.core.PShapeSVG.(PShapeSVG.java:295) at processing.core.PShapeSVG.(PShapeSVG.java:181) at 
processing.core.PGraphicsJava2D.loadShape(PGraphicsJava2D.java:1695) at 
processing.core.PGraphicsJava2D.loadShape(PGraphicsJava2D.java:1684) at 
processing.core.PApplet.loadShape(PApplet.java:11734) at test.setup(test.java:42) at 
processing.core.PApplet.handleDraw(PApplet.java:2365) at 
processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:245) at 
processing.core.PApplet.run(PApplet.java:2260) at java.lang.Thread.run(Unknown Source)
```

The problem is described in more detail here:
http://forum.processing.org/two/discussion/comment/31398#Comment_31398

**Comment by GKFX** [comment]
I'll look at this – I can still work on core while app is broken.

**Comment by JakubValtar** [comment]
It seems that Processing expects some attributes which are missing in the SVG. Add null checks to gracefully handle SVGs like this?

**Comment by GKFX** [comment]
@JacobValtar I've added the null checks, but I've add a few more improvements that seemed needed, and they need testing.
 I'm away from my PC for a week, but I'll try to get the fix posted ASAP.

**Comment by GKFX** [comment]
Sorry for the very long delay; I have got most of the work done and am just testing/refining, but exams are getting in the way. Will try to finish reasonably soon.
