### ISSUE TITLE
Focus on window's buttons while closing

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#2998]
The Save , Cancel , Don't Save Window's buttons are not binded to arrow keys.
The button could not be traversed using the arrow keys .

**Comment by benfry** [comment]
On what platform? That dialog is handled by Java/Swing, so we're inheriting whatever behavior is implemented there.

**Comment by Akarshit** [comment]
I tried it on linux and you are right that it is handled by java but there is a way to bind the arrow keys with the buttons of the dialog box as in #2999 .

**Comment by benfry** [comment]
Let's keep things simple. The extra code, and debugging it across all our platforms, isn't worth it for the cool factor.
