### ISSUE TITLE
PShape 3D: strange extra lines

### ISSUE THREAD

**Issue by RectangleWorld** [processing/processing#3006]
First observed in 2.1.1 and in the latest alpha 3.0a5. 

I'm pretty sure these extra lines I am seeing are the result of a bug, not my programming (sample program below). Am I missing something? I have seen the same behavior on two different windows machines. It seems only to happen when there is a lot of polygons.

If you try the sample program below (which requires PeasyCam), you'll see a bunch of random triangles arranged in a sphere. Zoom in to near the middle of the sphere and rotate around a bit and, if your results are the same as mine, you'll find some extra long lines drawn in the display that seem not to be part of any triangle. Here is a cropped screencap where you can see the lines:

![image_2079_crop](https://cloud.githubusercontent.com/assets/1840810/5425474/7af1b9a8-82e6-11e4-9b17-9836240164fa.jpg)

Complete code for this example:

```Java
import peasy.*;

int bgColor;
PeasyCam camera;
PShape testShape;
int numTriangles;

void setup() {
  size(1000, 650, P3D);
  //smooth(2);
  bgColor = 0xFF000000;
  background(bgColor);

  camera = new PeasyCam(this, 0, 0, 0, 1000);
  
  numTriangles = 10000;
  
  createSurface();
}

void rebuildShape() {
  createSurface();
}

void createSurface() {
  testShape = createShape();

  float theta;
  float phi;
  float mag;
  float x;
  float y;
  float z;
  float minMag = 10;
  float maxMag = 10;
  float bigRadMax = 500;
  float bigRadMin = 500;
  testShape.beginShape(TRIANGLES);
  testShape.stroke(0x80FFFFFF);
  for (int i = 0; i < numTriangles; i++) {
    testShape.fill(random(255), random(255), random(255), 128);
    mag = random(bigRadMin, bigRadMax);
    phi = asin(random(-1, 1));
    theta = random(TWO_PI);
    x = mag*cos(phi)*cos(theta);
    y = mag*cos(phi)*sin(theta);
    z = mag*sin(phi);

    testShape.vertex(x, y, z);
    for (int j = 0; j < 2; j++) {
      mag = random(minMag, maxMag);
      phi = asin(random(-1, 1));
      theta = random(TWO_PI);
      x += mag*cos(phi)*cos(theta);
      y += mag*cos(phi)*sin(theta);
      z += mag*sin(phi);
      testShape.vertex(x, y, z);
    }
  }
  testShape.endShape();
}

void draw() {
  lights();
  background(bgColor);
  shape(testShape);
}

void keyPressed() {
  if (key == 's') {
    saveFrame("image_####.jpg");
  }
  if (key == 'g') {
    rebuildShape();
  }
}
```

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing/commit/00fec711d8f2a5a482260f48805053edc346db94

**Comment by codeanticode** [comment]
by fixing https://github.com/processing/processing/issues/3756 realized this issue was not solved. Extra lines disappeared only because of a bug in the fix https://github.com/processing/processing/commit/00fec711d8f2a5a482260f48805053edc346db94, addressed with https://github.com/processing/processing/commit/e0e78b8996794eec789595f385be2a60ffa16e8e.

**Comment by codeanticode** [comment]
fixed (for real) with https://github.com/processing/processing/commit/1d1ccef46b87a99fdf739bacdf885eaa7808eca9
