### ISSUE TITLE
Problem (windows64): I tried example loadTable () from processing.org -> getInt() not working  

### ISSUE THREAD

**Issue by SBEN1979** [processing/processing#3011]
Hello together, 

I was trying the exapmle from the site processing.org and was confronted with following issue I desperatly can not solve:

---

// The following short CSV file called "mammals.csv" is parsed 
// in the code below. It must be in the project's "data" folder.
//
// id,species,name
// 0,Capra hircus,Goat
// 1,Panthera pardus,Leopard
// 2,Equus zebra,Zebra

Table table;

void setup() {

  table = loadTable("mammals.csv", "header");

  println(table.getRowCount() + " total rows in table"); 

  for (TableRow row : table.rows()) {

```
int id = row.getInt("id");
String species = row.getString("species");
String name = row.getString("name");

println(name + " (" + species + ") has an ID of " + id);
```

  }

}

// Sketch prints:
// 3 total rows in table
// Goat (Capra hircus) has an ID of 0
// Leopard (Panthera pardus) has an ID of 1
// Zebra (Equus zebra) has an ID of 2

---

I created a csv, everything works fine, the number of rows is printed correctly. But the getInt() function generates the following error message:
IllegalArgumentException: This table has no column named "id"

Can anyone help me please?

**Comment by rar0n** [comment]
I'm having the same issue, both in processing 2.2.1 and 3.1.1.

It seems the very first element of a table (whether a title or content) is disregarded and always reported as a 0. Changing the line with the "id" in it to simply refer to column 0 "works", as long as there is a header row in the comma separated file.
    int id = row.getInt(0);
Removing the header row and just refer to columns by number, invalidates the first colums first rows data, as it is set to 0.

**Comment by benfry** [comment]
That example works fine as-is, I don't see the problem:

<img width="729" alt="screen shot 2016-08-08 at 5 18 41 am" src="https://cloud.githubusercontent.com/assets/1623101/17475178/ac0db6aa-5d27-11e6-9d9a-8187b843463b.png">

**Comment by rar0n** [comment]
Ok, thanks for the quick reply! Then it seems it's something else. Very puzzling though. 
Btw using 64-bit Windows 7 (Ultimate).
Sorry for commenting on a closed issue btw (but I get the  same error message and have the same issue as OP).

**Comment by benfry** [comment]
If you find anything, please let me know. Weird to have two people reporting this so I went back and re-checked.

**Comment by zazazoe** [comment]
I have the same issue. Anyone figured this out in the end? If I am loading my own table, with just nrs in my case. It is not reading the very first value from Row 0, Column 0. It does read the value from Row 0, Column 1. And it also reads the value from Row 1, Column 0.

**Comment by benfry** [comment]
For anyone having this problem (as described by @zazazoe, that 0,0 doesn't work, but 0,1 and 1,0 are both fine) please post the `.csv` file you're using (and ideally, the simplest code that reproduces the problem) in a new issue.
