### ISSUE TITLE
Line ending support is broken

### ISSUE THREAD

**Issue by NPN** [processing/processing#3014]
The Processing IDE can handle files with Unix/DOS style endings, but when saving a file, it converts all line endings to Unix style. The worse part: **it appends a single ````^M```` to the end of the file**. When trying to it in conjunction with git (which already has its own share of confusing line ending problems), it is simply a headache.

The IDE should just leave line endings alone. Even if line endings are still normalized to Unix style, it should **not** append a ^M at the end.

**Comment by benfry** [comment]
We use UNIX line endings everywhere, because CRLF is an f*ing nightmare, but I've fixed the ^M problem for the next alpha.
