### ISSUE TITLE
ColorMode(RGB,1) not clipping to max value 

### ISSUE THREAD

**Issue by chrleon** [processing/processing#3017]
Just tried to make a 1-bit sketch, sort of.
When I go past 1 on the backgound-color, the sketch draw the backgound black again instead of remaining white.

Also tried to increase to 255 and beyond. Setting background(max+n) resets the background to the lowest RGB.

colorMode(RGB,1,1,1) works as expected with clipping the max value.

Might be that processing is designed not to clip for creative reasons, but then colorMode(RGB,1,1,1) should also loop around.

Issue reproduced below.
OSX 10.9.5
Processing 2.1.2
JAVA 8 v20 Build 1.8.0_20-b26

> int i = 0;
>
>void setup(){
  size(144,168);
  colorMode(RGB,1);
  background(0);
  noLoop();
> }
>
>void mouseClicked(){
  i+=1;
  redraw();
>}
>
>void draw(){
  println(i);
  background(i);
>}

**Comment by matteosistisette** [comment]
color() seems not to be affected, so this might be specific to background().

Obviously, the correct behavior is to clip, not to wrap around

**Comment by benfry** [comment]
You've hit a really weird edge case, based on what you're doing in your sketch.

See the "color(0, 0, 0, 0) is black" section here: https://github.com/processing/processing/wiki/troubleshooting

It's not something that can be fixed.

**Comment by chrleon** [comment]
Thanks.
