### ISSUE TITLE
Future of PShape

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3019]
I'm sorry if this is the wrong place.

I'm working on a library to provide more methods for PShape.
So far you can get the bezierPoint and Tangent of a loaded SVG.
This works with line, rect, ellipse, and paths. The paths can use vertex, bezierVertex, curveVertex and QuadraticVertex. There is also an option for arc length parameterization.
At the moment I work on a pathFinder like illustrator has to crop, merge etc.

I was wondering, what is the reason to have all the primitives? I understand it's easy for ellipse and arc.
But why triangle, rect and quad? Wouldn't it be much better to make a vertex path of it?
The reason I ask is cause it's really time consuming to deal with all those cases.
And I don't want to create my own Shape cause I prefer to keep it close to how processing is now.

Also where there any things planned for PShape? I wouldn't mind to work on it.

I did see the commented getLeft(), getBottom() etc. If that goes in I think getMinX() etc. Would be better so there can also be  getMinZ() and getMaxZ().

**Comment by benfry** [comment]
It's to keep parity with the rest of the API, and not lose information when moving between formats.
