### ISSUE TITLE
setVertex not working in P3D and P2D

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3022]
This seem to happen for a loaded SVG, not for a shape made with createShape.
It doesn't happen in Java2D so it's related to P2D and P3D.

```
PShape s;

void setup() {
  size(600, 600, P2D);
  s = loadShape("triangle02.svg"); 
  if (s.getFamily() == PShape.GROUP) {
      s = s.getChild(0);
  }
}

void draw() {
  background(255);
  s.setVertex(0,noise(0.02*frameCount)*width,10);
  shape(s);
}
```

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve">
<polygon points="409.7,406.3 102.2,368.7 261.2,107.7 "/>
</svg>
```

**Comment by redfieldp** [comment]
Is there a known fix for this? Definitely need the fix, and would be glad to help!

**Comment by redfieldp** [comment]
Bump on this. Is there any deliverable timeline or reason for the bug?

**Comment by benfry** [comment]
Please don't bump. There's no "deliverable timeline," we do this in our free time and we'll take a look when we have the chance. Or the code is all available, so anyone else can find and submit their own fix for us to incorporate.

**Comment by redfieldp** [comment]
Hey Ben, like I mentioned, I'm happy to help/work on the issue myself. I was just curious if the core team had a fix in the works, or if it made sense to pursue it on a fork. Thanks!
