### ISSUE TITLE
Add teardown() function

### ISSUE THREAD

**Issue by mail6543210** [processing/processing#3026]
Currently, there's a function named "setup" called once when the program starts.

When I'm processing videos, I have a value for each frame to be output.
Thus, there're a sequence of values to be output.

Without `teardown()`, I can only print them one by one as a text file of multiple lines.

With `teardown()`, I can collect the data in `read()`, then print them in `teardown()` at once.

**Comment by alignedleft** [comment]
I believe for this you can use `stop()` alongside `setup()` and `draw()`, as in:

```
void stop() {
  print(values);
}
```

See: http://processing.org/reference/javadoc/core/
