### ISSUE TITLE
orientation(...);              // crashes in JavaScript

### ISSUE THREAD

**Issue by toniholzer** [processing/processing#3034]
Only in the mode 'JavaScript' the sketch crashes at the statement  'orientation(...);' .
It should be possible to call this function to be compatible to other modes !!!

**Comment by GKFX** [comment]
Thanks for the report; unfortunately this is the wrong issue tracker. Could you post this to https://processing-js.lighthouseapp.com/ ?

**Comment by toniholzer** [comment]
Thanx for that hint...
Btw. Processing v2.2.1 is using processing.js v1.4.1. when running under Javascript.
Is there any plan to update to processing.js v1.4.8. ?

**Comment by REAS** [comment]
That's a question for the JavaScript Mode repo:
https://github.com/fjenett/javascript-mode-processing

**Comment by GKFX** [comment]
Sorry for the incorrect link @toniholzer – I was working from the README.

**Comment by REAS** [comment]
Well, issues with Processing.js should be referred to the Processing.js project. Issues that are specific to the Processing Mode should go to the repo. It's confusing, but these are two different projects, maintained by different people.

**Comment by toniholzer** [comment]
In the meantime Processing.js is updated to version 1.4.13.
Using Statement "orientation(...);"  with processing 3.0.1 in JavaScript mode still freezes the display frame!!!
And I don't know how to report that error to Processing.js project or to
https://github.com/fjenett/javascript-mode-processing.
I think it must be very easy to add this 'empty' function to Processing.js because it should do nothing!
The only request is NOT TO FREEZE with JavaScript.
Can somebody - who das a login - add this bug report to Processing.js project ? 
Thanx a lot!
