### ISSUE TITLE
Processing 2.2.1 export does not work on OSX 10.10.1 Yosemite

### ISSUE THREAD

**Issue by Neil129** [processing/processing#3036]
INFO:
Notebook: MacBook Pro (Retina, 15-inch, Early 2013),
OS: OSX 10.10.1 Yosemite
Java version: 7 update 71
Processing version: 2.2.1
Nationality: Dutch

Problem:
I'm currently working using the latest version of Processing for a school project. It's not complete yet, but it was good enough to try the export function of processing incase anything goes wrong. 
U would've probably guessed it already, it dit not work at al. 

The first problem occurred when exporting with embedded java and running the export file. While running the export-file this error message appeared within processing:

/Users/Niels/Documents/Fontys/Leerjaar 1/ Sem2/Rosetta/Rover_Programma/application.macosx/Rover_Programma.app/Contents/PlugIns/
jdk1.7.0_55.jdk.jdk: No such file or directory

In which immediately see that this part of the code:( /jdk1.7.0_55.jdk.jdk: No such file or directory) has a  dubbel reference to the file.extension. This has to be (from my point of view) a Processing problem. 
(I did not get this problem when exporting without embedded java)

The second problem I encountered, was that the simulation did not proceed. It keep showing a gray screen. Now while I was browsing through the contents folder of the export file.

In the folder MacOS I found a file similar to the actual export-file which also runs the terminal aside the simulation. The simulation stopped at this point:

- Terminal -
Last login: Fri Jan  9 19:15:04 on ttys000
MacBook-Pro-van-Niels:~ Niels$ /Users/Niels/Documents/Fontys/Leerjaar\ 1/Sem2/Rosetta/Rover_Programma/application.macosx/Rover_Programma.app/Contents/MacOS/Rover_Programma ; exit;
1440
The file "Logo zonder witte achtergrond.png" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
0.625
1.6
Scherm Breedte: 1440pix
Scherm Hoogte: 900pix
AVAILABLE COM PORTS:6
Port: /dev/cu.Bluetooth-Incoming-Port
Port: /dev/cu.Bluetooth-Modem
Port: /dev/cu.iPhonevanNiels-Wireless
Port: /dev/tty.Bluetooth-Incoming-Port
Port: /dev/tty.Bluetooth-Modem
Port: /dev/tty.iPhonevanNiels-Wireless
USED VIRTUAL PORT: /dev/cu.Bluetooth-Incoming-Port
Exception in thread "Animation Thread" java.lang.NullPointerException
	at processing.core.PGraphics.image(PGraphics.java:3593)
	at processing.core.PApplet.image(PApplet.java:12783)
	at Rover_Programma.load_Screen(Rover_Programma.java:532)
	at Rover_Programma.draw(Rover_Programma.java:308)

I have no experience with java programming and this my first project in Processing.

So my Question is mainly towards the developers of Processing to fix this problem. 
Or if someone else has a suggestion I would  much appreciate it.

**Comment by benfry** [comment]
Please use the forum for troubleshooting help: http://forum.processing.org
