### ISSUE TITLE
Examples contribution prevents processing startup when examples.properties file is missing

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3037]
When an examples contribution without an examples.properties is installed, the following error is thrown by processing at startup:
![examples_properties_startup_error](https://cloud.githubusercontent.com/assets/4526417/5690485/57b12226-98b2-11e4-876c-604ba8bdff50.png)

**Comment by benfry** [comment]
Ha, wait, isn't that in *your* code?

**Comment by joelmoniz** [comment]
Haha, yes, indeed it is :smile:. Just thought it'd report it before submitting in a PR (should I have avoided doing this?)

I've submitted a PR resolving this issue [here](https://github.com/processing/processing/pull/3047).

**Comment by benfry** [comment]
Nah, just giving you a hard time. 

For future reports, just let me know if/when you plan to look into it, that way I'm not trying to fix the same issue.

**Comment by joelmoniz** [comment]
Oh, sure thing. Thanks
