### ISSUE TITLE
loadTable() should let users specifiy the separator string - not working with semicolons

### ISSUE THREAD

**Issue by josephlarralde** [processing/processing#3039]
I think loadTable() should have an optional additional parameter which should let the user specifiy what the separator string should be while parsing a csv file, and not restrict it to tabulations and commas as it's the case with the only csv and tsv options available.
The csv format is not as strict as this, for example I'm working on files where the separator is a semicolon, and where there are commas in the fields of the table (actually geographic coordinates values in french numbers notation).
I don't know if this problem could arise with other characters or if it's specific to french numbers notation, but in both cases, I think the possible solutions would be : 
- let the user specifiy a separator string, which is the most universal (thus powerful) solution in my opinion
- add options to the existing ones (like a "scsv" option for semicolon, for example)

I hope this makes sense.
Cheers,
Joseph

**Comment by GKFX** [comment]
I'll take a look at that; in addition, the current implementation is very sniffy about new lines in cells, despite them being allowed in the RFC spec.

**Comment by josephlarralde** [comment]
Ok, great, and thank you for the quick answer !
Meanwhile I'll keep using loadStrings which does a great job.

**Comment by benfry** [comment]
We're not trying to parse every last kind of CSV file, and I didn't want to go down the road of allowing delimiters of all kinds because of the extra complexity it adds.

Newline characters in CSV files are supported if you include "newlines" in the options for `loadTable()`. That parsing code is far slower, so it's not the default.

**Comment by josephlarralde** [comment]
I understand the sake of clarity needed in Processing, and I agree that its simplicity is one of its most important features.

However, I still feel that the semicolon option is important, because of the many csv files I've already had to manipulate which contained semicolons as separators, and the time I spent using loadStrings on them rather than having simple methods to manipulate the fields. It's not the last kind of CSV file, it's one that has been very common for quite a long time.
In fact, I opened this issue after reading this thread : http://forum.processing.org/one/topic/table-class-doesn-t-work-with-csv-file-using-semicolon-as-data-seperator.html
So at least we are two guys wishing this feature ... I guess some others do.
As I was saying, a "scsv" option would be much appreciated.

By the complexity it adds to be able to specifiy an explicit separator, do you mean the complexity from the point of view of the new Processing user, the time it would take to develop it, or the extra cpu time it would take to execute the function ?

- In the first case, I would answer that personnally, I don't find less clear to give the explicit separator character than to have to use options which just imply a character change in the implementation behind. Just a bit less intuitive for the \t character for beginners.
- In the second case, I totally understand the lack of time argument, and in all cases I will probably go into writing a kind of library to do this, despite I would have found it logic to be a native feature.
- In the third case, I would argue that it's possible to write another function hidden in the original in some way, in which case the extra complexity would occur only when an explicit separator would be specified. I would also argue that complexity doesn't seem the most important aspect of this function to me, because either it's not used in real-time, either it should be used in a thread for real-time applications.

I'll try the "newlines" option, but I'm not sure to understand what you suggest to do with it.

Thanks for your reply anyway.
Joseph

**Comment by alignedleft** [comment]
This is not to dismiss your idea, but perhaps this would be a useful workaround in the meantime?

Before loading the table, load in your data file as, say, a single string.  Then replace all semicolons with commas. For example:

```
String semis = "20;40;60";
String commas = semis.replaceAll(";", ",");
println(commas);
```

This isn't pretty, but then you could save the new string out as a file, then load it back in as a table:

```
String[] array = { commas };
saveStrings("data.csv", array);
Table table = loadTable("data.csv");
```

Again, not ideal, but perhaps faster than writing a whole new library or forking the Processing code.

**Comment by josephlarralde** [comment]
Hi, and thank you for your suggestion.

Actually I finally chose a similar solution (more archaïc), it's not a big pain to do a simple find and replace in a text editor. But I encountered a problem with some files containing comma separators in the csv fields. Of course you can always find a workaround : in my case there were no "@" characters in the file (any other character that wouldn't have appeared to be in the file could have been used instead), so I first replaced all the commas by @s, then replaced the semicolons by commas, then I was able to use loadTable().

But with your solution, this can indeed be done programmatically in quite a few lines of code.
Actually by using indexOf() iteratively, we could find a generated alphanumeric string that is not contained in the file. Then we could replace the commas by this string, then the semicolons by commas, then parse the file, then restore the original commas in the parsed fields (or sub-parse them directly with the string).

Ok, not a very big deal in the end, just a bunch of functions to write instead of parsing everything manually from loadStrings() ...

Thanks again for this elegant solution.

**Comment by jdarias** [comment]
Man I came here by googling around... got a chunky 250 MB csv with semicolons instead of commas... 
Please Processing devs give us poor souls this...

**Comment by jeremydouglass** [comment]
See linked issue 5068 above -- that is the open issue on delimiters. There is draft code there, but pre-processing and replacing those characters might be your best bet. For advice on that, use the Processing discussion forum, not issues.

**Comment by benfry** [comment]
Closing and locking this since it's covered in https://github.com/processing/processing/issues/5068
