### ISSUE TITLE
generate an error when trying to save to a disk that is full

### ISSUE THREAD

**Issue by Pomax** [processing/processing#3040]
I ran into the rather edge-casy situation where I was working in Processing, while a download was filling up my working disk at the same time. At some point the disk was full, without me noticing, and hitting "run" simply generated a weird runtime error. thinking nothing of it, I saved my work and closed Processing, only to notice that the file it had saved was 0 bytes, and all my work had been lost.

It would be an extremely good idea to add a quick post-save validation to make sure the file written is in fact not 0 bytes, and to warn the user that something went catastrophically wrong (not via a JVM stack trace) when that happens, so they can save it somewhere else, or free up disk space, or do whatever they need to do before they lose a day's work.

**Comment by spasmsaps** [comment]
also see #2923

**Comment by benfry** [comment]
https://github.com/processing/processing/issues/2923
