### ISSUE TITLE
createShape() is always 3d when the renderMode is 3d

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3041]
Not sure if this should be considered a bug.
But I thought I report anyway.

```
void setup() {
  
  size(600, 600, P3D);
  
  PShape s = createShape();
  
  s.beginShape(POINTS);
  s.vertex(10, 10);
  s.endShape();
  
  println(s.is3D()); // true
  
}
```

**Comment by GKFX** [comment]
Certainly if you read through https://github.com/processing/processing/search?utf8=%E2%9C%93&q=PShape+createShape%28%29+language%3Ajava&type=Code, a lot of effort seems to have been put into implementing that behaviour. [PGraphics.java](https://github.com/processing/processing/blob/ac24c794b2907d3175e222a5f6899d1af29e987d/core/src/processing/core/PGraphics.java#L1662) doesn't have 2D or 3D defined and refuses to act:
````java
public PShape createShape() {
  showMissingWarning("createShape");
````
while all the 2D and 3D modes take care to implement their own type. There's no actual issue.

**Comment by clankill3r** [comment]
Well the method is almost redundant now. If the sketch renderer is 2D then you know for sure that `somePShape.is3D()` is `false` cause the renderer is 2D. If the renderer is P3D (the only 3D mode at the moment). Then it's only 2D if you loaded a svg... I can create a shape without using a z coordinate and it's still a 3D shape. I would not call that putting a lot of effort in the implementation.

**Comment by GKFX** [comment]
What benefit is there in using a 2D shape in a 3D world? What can't you achieve with a flat 3D shape?

**Comment by clankill3r** [comment]
speed.

**Comment by benfry** [comment]
This would add unnecessary complexity for an edge case with very limited utility.
