### ISSUE TITLE
README.md has a dead link

### ISSUE THREAD

**Issue by GKFX** [processing/processing#3042]
It says
````md
If it relates to the [JavaScript](http://processingjs.org) version, please use [their issue tracker](https://processing-js.lighthouseapp.com/).
````
but https://processing-js.lighthouseapp.com/ has been taken off-line. Should it be changed to https://github.com/fjenett/javascript-mode-processing, as mentioned in #3034?

**Comment by REAS** [comment]
Thanks for pointing this out. I just fixed it.
