### ISSUE TITLE
createShape() -> contains(x, y)

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3043]
No matter what renderMode, the createShape() makes a `GEOMETRY` (unless creating a primitive or loading a svg).

It would be nice to be able to create a 'PATH' so the contains method can be used.

```
  PShape s = createShape();
  
  s.beginShape();
  s.vertex(10, 10);
  s.vertex(100, 10);
  s.vertex(10, 100);
  s.endShape();
  
  println(s.contains(mouseX, mouseY));
```

**Comment by benfry** [comment]
https://github.com/processing/processing/issues/1280
