### ISSUE TITLE
The shortcut for right bracket "}" (alt gr + N) overlaps with create new tab on the Hungarian keyboard

### ISSUE THREAD

**Issue by x012** [processing/processing#3045]
When trying to write a "}", its writen and at the same time a pop up goes up asking for the name of the new file. 
(Processing version 3.0a5)
![image](https://cloud.githubusercontent.com/assets/7905790/5776373/c283297c-9d86-11e4-9c02-6654bf7c81e1.png)

**Comment by GKFX** [comment]
See also #2199. They are similar.

**Comment by benfry** [comment]
https://github.com/processing/processing/issues/2199
