### ISSUE TITLE
Cannot switch on a value of type String.

### ISSUE THREAD

**Issue by siiikooo0743** [processing/processing#3049]
Hi,

when i try to switch on an string i get this Error:
Cannot switch on a vlaue of type String. Only convertible int values or enum constatnts are permitted.
I know switching on String is not possbile in Java 1.6, but I'm using Processing V. 2.2.1, which has Java Version 1.7.0_40 (found out with: print(System.getProperty("java.version")); ).
This seems to be a bug in the error detection system.

**Comment by benfry** [comment]
It's not supported by the preprocessor, but we've never claimed it works: http://processing.org/reference/switch.html

Use an `if()` statement instead.

**Comment by siiikooo0743** [comment]
Well i know, but it should be supported anyway.
I'm no expert, but how hard can it be to get it to work ^^

**Comment by benfry** [comment]
It's hard, because it involves the preprocessor. It's at least a few hours of work for someone to do it (and then update the reference accordingly), and there is no someone to do it. 

But regardless, it's not a "bug". It's a feature we've never had.

**Comment by siiikooo0743** [comment]
Ok i undserstand.
Thank you for your efforts anyway.
