### ISSUE TITLE
Lists do not throw exceptions when non-existent elements are manipulated.

### ISSUE THREAD

**Issue by GKFX** [processing/processing#3052]
See #3044. The below code does not complain about increasing non-existent elements.
````java
FloatList list = new FloatList();
void setup(){
size(300,300);
list.add(0,000);
list.add(1,100);
list.add(2,200);
list.add(3,300);
}
void draw(){}
void mouseClicked(){
for(int i=0; i<3; i++){ println("list index "+i+" is "+list.get(i)); }
println("list length is "+list.size());
}
````

**Comment by benfry** [comment]
Should be an easy fix for someone who wants to look at it (across IntList, FloatList, etc).

**Comment by pvrs12** [comment]
I'd be willing to look at it. Is there a specific exception it should throw or should a new unchecked exception be made?

**Comment by GKFX** [comment]
Follow http://docs.oracle.com/javase/6/docs/api/java/util/ArrayList.html#get(int) and throw an standard `IndexOutOfBoundsException`.

**Comment by benfry** [comment]
Incorporated for 3.0a6.
