### ISSUE TITLE
Sorry, elliptical arc support for SVG files is not yet implemented (See issue 130 for updates)

### ISSUE THREAD

**Issue by BeauTurner** [processing/processing#3060]
I am trying a simple circle in inkscape and keep getting this. Seeing conflicting reports on this being fixed and the original bug (#130) I cannot find that matches this. .SVG and .ZIP attachments not permitted here, you can download a simple inkscape svg circle here: https://dl.dropboxusercontent.com/u/5106088/Temp/Soccerball2.svg

**Comment by benfry** [comment]
It was incorporated in the code on July 28, 2014:
https://github.com/processing/processing/pull/2659

Are you using a release that actually incorporates the fix?

**Comment by JakubValtar** [comment]
Just checked, works great in 3.0a5...

![svg](https://cloud.githubusercontent.com/assets/3177098/5892998/02cb57f2-a4d5-11e4-9777-1be708cae87c.png)

**Comment by benfry** [comment]
Thanks for looking into it.

**Comment by BeauTurner** [comment]
Thanks all.

**Comment by keredwink** [comment]
I'm getting this error when I use SVGs in a sketch in Android mode.

Can this be fixed for Android mode as well?
