### ISSUE TITLE
Build is currently broken on Ubuntu and Windows

### ISSUE THREAD

**Issue by GKFX** [processing/processing#3063]
After running `git checkout master; ant clean run` there are no error messages, but the splash screen appears for a moment and then nothing happens. I'm on Ubuntu, x64, Sun Java 1.8.0_25. Any thoughts? I've been compiling P5 for ages without this happening.

**Comment by benfry** [comment]
Lots of things moving around at once. I've not had a chance to finish debugging on Linux and Windows.

**Comment by GKFX** [comment]
@benfry I'm getting a `NullPointerException` [here](https://github.com/processing/processing/blob/master/java/src/processing/mode/java/JavaEditor.java#L2176)
````java
for (LineHighlight hl : breakpointedLines) {
````
Perhaps some null-checking would be good? If I add a check, it just reverts to the above behaviour, but at least it reduced the number of bugs.
![null pe](https://cloud.githubusercontent.com/assets/5357642/5943186/bf36fc8e-a714-11e4-8017-539b65defac2.png)

**Comment by benfry** [comment]
You can put a null check around that block to get it working. I've already done that in my version of the code. But mine is even more broken than what's on the head, so I've not pushed it yet.

**Comment by Akarshit** [comment]
I tried putting a null check around the statements , but still the error remains .  
But the strange thing is that even if i delete the 613 line in processing/app/src/processing/app/Base.java still the error is same , it's like the changes i am making are not being reflected.  
Can someone tell me what i am doing wrong.

**Comment by GKFX** [comment]
Normally `ant clean run` is the command I use to solve that error; failing that, I would delete the `build` directory entirely and check it out of git again. Also look into `git clean`. 

If that doesn't work, it's likely you're doing something daft like editing a different copy of the file to the one in your repository.

**Comment by pvrs12** [comment]
To get it to run for me I changed the code at line 1214 in Sketch.java to this

```
    try{
    editor.setCode(current);
//    editor.header.rebuild();
    editor.header.repaint();
    }catch(NullPointerException e){
      //e.printStackTrace();
    }
```
That seemed to get it to run for testing

**Comment by benfry** [comment]
Fresh builds should be working again. Don't forget to `ant clean` before doing an `ant run`. 

For any build issues, please file a new issue.
