### ISSUE TITLE
Processing.net problem: High timeout, when the client tries to connect and the server does not exist.

### ISSUE THREAD

**Issue by EmperadorTico** [processing/processing#3064]
Hello

I am making an android app.

the processing.net library works great while the server is working.

However, when I try to turn on the Android app (client) and the server is idle, the app crashes  for over a minute.
Using processing.net in windows, something similar happens, but the waiting time is reduced to about 10 seconds.

The main problem is that while java creates the connection, the app is frozen. and a high wait time is an important issue if the server goes down.

How can solved this, is there any way to jump code, if no socket is created in x seconds?

A greeting and thanks in advance,

Emperador_Tico

**Comment by benfry** [comment]
Please use the Android repo for reports about Android issues: https://github.com/processing/processing-android

**Comment by EmperadorTico** [comment]
but it is java and is a problem of processing.net java library

I think they should use this: setSoTimeout
