### ISSUE TITLE
ConnectException as reduce waiting time: processing.net

### ISSUE THREAD

**Issue by EmperadorTico** [processing/processing#3065]
Good afternoon,

I want to keep waiting for connection to lengthen more than 10 seconds during the execution of the client socket. This usually happens if the server is not running.

How do I can reduce the waiting time?

code problem:
myClient = new Client(this, "192.168.1.37", 5022);

I tried to make modifications to the library but it does not work:
socket.setSoTimeout(2888);
...catch(ConnectException e){}
still waiting 20 seconds....

Can anyone help, any idea?

Thanks, Emperador_Tico

**Comment by EmperadorTico** [comment]
I found a solution:
http://stackoverflow.com/questions/662712/how-to-prevent-application-freeze-if-server-unavailable



changing that the library would work best:

  /**
   * @param parent typically use "this"
   * @param host address of the server
   * @param port port to read/write from on the server
   */
  public Client(PApplet parent, String host, int port) {
    this.parent = parent;
    this.host = host;
    this.port = port;

    try {
socket = new Socket(); socket.connect(new InetSocketAddress(this.host, this.port), 3000);//3000 is time in millis
//change      socket = new Socket(this.host, this.port);
      input = socket.getInputStream();
      output = socket.getOutputStream();

      thread = new Thread(this);
      thread.start();

      parent.registerMethod("dispose", this);

      // reflection to check whether host sketch has a call for
      // public void clientEvent(processing.net.Client)
      // which would be called each time an event comes in
      try {
        clientEventMethod =
          parent.getClass().getMethod("clientEvent",
                                      new Class[] { Client.class });
      } catch (Exception e) {
        // no such method, or an error.. which is fine, just ignore
      }
      // do the same for disconnectEvent(Client c);
      try {
        disconnectEventMethod =
          parent.getClass().getMethod("disconnectEvent",
                                      new Class[] { Client.class });
      } catch (Exception e) {
        // no such method, or an error.. which is fine, just ignore
      }

    } catch (ConnectException ce) {
      ce.printStackTrace();
      dispose();

    } catch (IOException e) {
      e.printStackTrace();
      dispose();
    }
  }

  
  /**
   * @param socket any object of type Socket
   * @throws IOException
   */

**Comment by benfry** [comment]
Please use http://forum.processing.org for questions/discussions like this.
