### ISSUE TITLE
Further build attempts fail when processing fails to start (when it shows one of the "We're off on the wrong foot" or "Terrible News" dialogs)

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3068]
Once processing shows the "We're off on the wrong foot" or the "Terrible News" dialog, further ant builds fail with the following error:
  
```
BUILD FAILED
C:\Users\Joel\Documents\Code\p5\processing\build\build.xml:239: The following er
ror occurred while executing this line:
C:\Users\Joel\Documents\Code\p5\processing\build\build.xml:957: Unable to remove
 existing file C:\Users\Joel\Documents\Code\p5\processing\build\windows\work\jav
a\bin\awt.dll
```
  
The reason is most likely because pressing the "OK" button on the aforementioned dialog does not kill processing completely:  

![unkilled_p5](https://cloud.githubusercontent.com/assets/4526417/5957720/db5b680e-a7e2-11e4-97de-866697b4323f.png)

**Comment by benfry** [comment]
https://github.com/processing/processing/issues/3063

**Comment by joelmoniz** [comment]
Oops. This issue is different from the one mentioned, because it is not the fact that processing does not build that I meant to indicate, but the fact that when it doesn't build, rebuilding it requires one to go to the Task Manager (at least in Windows, not very sure about Linux/Mac OS) and manually kill the highlighted process there to build again.

**Comment by benfry** [comment]
Sorry about the confusion. I appreciate the report and the fix.
