### ISSUE TITLE
Finish the GUI for 3.x

### ISSUE THREAD

**Issue by benfry** [processing/processing#3072]
The new GUI for 3.x is half-implemented and hasn't been refined, so things are in an especially ugly in-between state.

This issue is not for opinions or input on the GUI, the forum is a better place to vent. Or better yet, wait until we've had a chance to finish the design and implementation. 

Similarly, we don't (at the moment) need reports on what's broken in the GUI—there's too much that's broken for that to be useful. Save that for when this issue is closed.

Thank you,
The Management

**Comment by GKFX** [comment]
@benfry The new GUI is beautiful. Thanks!

**Comment by benfry** [comment]
For reference, this is the current (but not final!) comp of how the GUI is intended to look, to give a better sense of where we're headed.

![141008-pde-sketch-r7](https://cloud.githubusercontent.com/assets/1623101/6083726/df3f8d80-adf8-11e4-8ae8-9b653670312b.png)

**Comment by REAS** [comment]
Here are some notes on the above comp:
- Line numbers less contrast
- Break point more contrast
- Bug icon needs an "on" state
- Consider Play button to have a new state for debug mode (color shift?)

**Comment by benfry** [comment]
A more refined comp... 

![pde-sketch-r13-error-update-001](https://cloud.githubusercontent.com/assets/1623101/9136685/a26eaaf8-3ce6-11e5-8cac-7aa548acc181.png)

**Comment by benfry** [comment]
Closing in favor of separate issues for the specific pieces that aren't yet implemented.
