### ISSUE TITLE
Opening and closing preferences window prompts user to save unmodified sketch

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3074]
Steps to reproduce this error:  
  
1. Open a new sketch, or an already existing one 
2.  Open the preferences window  
3. Close the preferences window  
4. Close the sketch  
  
A dialog box prompting the user to save the current sketch is displayed (even though the sketch has not been modified).

**Comment by benfry** [comment]
This might be https://github.com/processing/processing/issues/3057

Did you open preferences using a keyboard shortcut?

**Comment by joelmoniz** [comment]
Oh yes, I did use a keyboard shortcut. However, nothing gets typed into the Editor when I use this shortcut, unlike in #3057. Further, this problem doesn't seem to occur when I use other key combinations.

**Comment by benfry** [comment]
Though I suspect hitting alt or ctrl may mark the sketch as modified (on Windows), are you seeing that?

**Comment by benfry** [comment]
https://github.com/processing/processing/issues/3057

**Comment by benfry** [comment]
Fixed for 3.0a6.

**Comment by joelmoniz** [comment]
Thank you :)
