### ISSUE TITLE
color() function is not thread-safe

### ISSUE THREAD

**Issue by mattlathrop** [processing/processing#3077]
The following code:

```
    for(int j=0; j < dimention; j++) {
      color current = ledImage[i].pixels[j];
      ledImage[i].pixels[j] = color(red(current), green(current), blue(current)); //multiply color correction here
    }
```

Was acting as a place holder. The plan was to multiply the Red, Green, Blue by color correction values for each pixel of an LED Wall. This function occasionally returned the wrong color value when threading (each thread handles a different i). I reimplemented it using bit shifting and it worked fine.

**Comment by benfry** [comment]
See discussion at https://github.com/processing/processing/pull/4774

**Comment by benfry** [comment]
Won't be changing this behavior… An explanation and some words on thread safety explained here: https://github.com/processing/processing4/issues/431#issuecomment-1057979636 (These need to eventually move to a technical FAQ of some sort, but I don't have time at the moment…)
