### ISSUE TITLE
Install and Remove buttons in Contributions Manager not working smoothly

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3079]
The Install and Remove buttons currently don't seem to work smoothly. They have to be clicked on at least twice to get a contribution to install/remove. Not quite sure why this is happening, but I'll check this out soon.

**Comment by benfry** [comment]
Any word on fixes here?

**Comment by joelmoniz** [comment]
I'm looking into this. Hopefully should make headway by the weekend.

**Comment by benfry** [comment]
Cool, thanks.

**Comment by benfry** [comment]
#3172 is a duplicate of this but has more information, so I'm closing this feller as the duplicate.
