### ISSUE TITLE
Opengl error 1982 and 1986

### ISSUE THREAD

**Issue by x3sp3d3s** [processing/processing#3084]
Hi, we manage to compile the app, but when we run the app, appears this errors:
- Opengl error 1982 at bot beginDraw() : invalid operation
- Opengl error 1986 at bot beginDraw(): invalid framebuffer operation
- Opengl error 1986 at top endDraw(): invalid framebuffer operation
- Opengl error 1986 at bot endDraw(): invalid framebuffer operation

We reinstall the new drivers and nothing change. Any suggestion?? If you need more info, i can send you the log file.
P.D: I have the same error without compile, but the app runs.

**Comment by benfry** [comment]
@codeanticode I assume we can close this because it's specific to JOGL (and JOGL has been replaced)?

**Comment by codeanticode** [comment]
This should be fixed with the recent changes in the renderer, I haven't seen these errors myself. @x3sp3d3s do you still get them using 3.0a8?

**Comment by codeanticode** [comment]
@x3sp3d3s Do you still get these errors with the latest revision from git? If so, what OS are you on?

**Comment by x3sp3d3s** [comment]
Sorry for the delay. The project is closed, to many errors and bugs.. Thx
for help!!

2015-06-03 23:35 GMT+02:00 codeanticode <notifications@github.com>:
