### ISSUE TITLE
Feature request:  adding API for asynchronous IO

### ISSUE THREAD

**Issue by teo1978** [processing/processing#3085]
I filed an issue for requesting the addition of API for asynchronous IO.

I've been suggested to open a feature request instead. I thought that was what I had done in the first place.
I don't see a link anywhere for filing feature requests, perhaps I'm missing it. I thought they were to be filed the same way as issues and they would then be tagged as feature requests. But I can't ask for clarification in the original thread either because it was closed.

Apparently the thread was closed because of my "attitude" and because it was a "rant". I thought issues and feature requests were handled or withdrawn depending on the importance of the issue or feature, not depending on how nice or polite the person reporting them is.

So, feature request: may you please consider adding an API for asynchronous requests, taking also into account the portability to Processing JS? That would make Processing, which is awesome, even better.

**Comment by benfry** [comment]
Moved to https://github.com/processing/processing/issues/3165
