### ISSUE TITLE
OMG! certain byte array assignments (valid in Java) cause compilation error in Processing sketch without cast

### ISSUE THREAD

**Issue by counter-culture** [processing/processing#3086]
let's suppose we have a sequence of bytes we need to squirt to a device like so:
void emit() {
    byte[] bytes = new byte[27];
    bytes[0] = '[';
    bytes[1] = 0x55;
    bytes[2] = 0x28;
    bytes[3] = 0x1d;  // this works fine since it's a digit as the first char after '0x'
    bytes[4] = 0xec;  // FAIL!
// Processing won't compile leading hex [a-f][A-F] character
// unless a (byte) cast is made like ===> bytes[4] = (byte)0xec ---or--- bytes[4] = (byte)0xbe;
    bytes[5] = 0x26;
    bytes[6] = 0x06;
    bytes[7] = 0x00;
    bytes[8] = 0x00;
    bytes[9] = 0x5c;
    bytes[10] = 0x44;
    bytes[11] = '\n';
    bytes[12] = '[';
    bytes[13] = 0x55;
    bytes[14] = 0x28;
    bytes[15] = 0x1d;
    bytes[16] = 0xec;  // ditto here
    bytes[17] = 0x26;
    bytes[18] = 0x06;
    bytes[19] = 0x00;
    bytes[20] = 0x00;
    bytes[21] = 0x5c;
    bytes[22] = 0xbe; // and here
    bytes[23] = 'r';
    bytes[24] = ':';
    bytes[25] = '9';
    bytes[26] = '\n';
   gOutputString = new String(bytes);
}

**Comment by JakubValtar** [comment]
Your code is **not** valid Java code. Please check it next time. Bytes in Java have range (-128, 127), so if you try to assign value not in this range, you get a compilation error.
```
byte a = 0x70; // 112, ok
byte b = 0x79; // 127, ok
byte c = 0x80; // 128, error
byte d = 0x90; // 144, error
byte e = 0xA0; // 160, error
byte f = 0xF0; // 240, error
```
You might want to use `char` instead, they have range of (0, 255) so all your hex constants up to `0xFF` will compile just fine.
```
char g = 0xEF; // 239, ok, yay
char h = 0xFF; // 255, ok
char i = 0x100; // 256, error
```

@benfry I believe you can close this as invalid.

**Comment by counter-culture** [comment]
you are correct - i'm asleep...
