### ISSUE TITLE
processing.net.Server only cleans up internal Clients when trying to write

### ISSUE THREAD

**Issue by kfeuz** [processing/processing#3089]
This can lead to memory issues if the server only reads data and never/seldom attempts to write to the clients.  I see a few ways to attempt to resolve this.  We could check for dead clients in the available() method or the run() loop.  The other approach would be to add some sort of callback to the Server when the internal client dies.  Is there a preference for one technique over the other?  I would be happy to submit a PR once this is decided.

**Comment by gohai** [comment]
My first time looking really at the network code, but I see the issue you describe.. I'd suggest adding the check to available(), since this should work for all practical cases, and we're already iterating over the array there.

**Comment by kfeuz** [comment]
In looking at the issue a little closer, checking for dead clients in available does seem like the best choice.  It allows us to have a chance to retrieve the unread data from dead clients before they get discarded.  I have submitted a pull request.

**Comment by benfry** [comment]
Fix incorporated for 3.0a6.
