### ISSUE TITLE
Update manager broken?

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3090]
The update manager is not working for me in current build from source (it does work in 3.0a5).  I see the manager but nothing happens when I press `update` button for a particular contribution.

Processing 233, Mac OS 10.10.2

**Comment by shiffman** [comment]
Adding that none of the buttons in contributions manager are working: `install`, `remove`, etc.

**Comment by spasmsaps** [comment]
The Buttons issue was reported here #3079

**Comment by shiffman** [comment]
Ah great, thanks.
