### ISSUE TITLE
Large editor window opens the debugger window mostly off the screen

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3091]
Pressing the `debugger` button (Processing 233) works to reveal the debugger, however, if the main Processing window is the size of the screen's width it appears to not be working since the debugger interface is placed offscreen.    I'm not sure what the correct behavior should be or if it should be the user's responsibility to size Processing correctly but this confused me initially.

In the image below I'm showing what it looks like if the Processing window is slightly less than the screen's width (we see a small bit of the debugger interface).

![screen shot 2015-02-05 at 10 35 08 am](https://cloud.githubusercontent.com/assets/191758/6058799/b4bf2150-ad22-11e4-8622-4712155cffb9.png)

**Comment by benfry** [comment]
Changed this to have it show up relative to the editor window and use the OS defaults.
