### ISSUE TITLE
Moving sketch window breaks sketch window size

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3092]
In current build (233), Mac OS 10.10.2 I'm experiencing a strange behavior where a sketch window resizes to 0x0 if I manually move the window's position.  In other words, I first launch the sketch and it looks correct:

![screen shot 2015-02-05 at 10 39 12 am](https://cloud.githubusercontent.com/assets/191758/6058848/4018c2f6-ad23-11e4-8f2f-31df320a67b9.png)

I then use the mouse to drag the sketch window over to the right and:

![screen shot 2015-02-05 at 10 39 54 am](https://cloud.githubusercontent.com/assets/191758/6058855/591c36ca-ad23-11e4-8e67-48503af8483c.png)

This is not behavior I've experienced previously (3.0a5).

**Comment by REAS** [comment]
Yes, I'm seeing this too.

**Comment by benfry** [comment]
Yup, this is a nasty one I need to fix.

**Comment by benfry** [comment]
Now fixed. The window was claiming that it was maximized. Probably a bug in Java on OS X, but I'm just working around it.
