### ISSUE TITLE
Frame.setlocation(x,y)

### ISSUE THREAD

**Issue by x3sp3d3s** [processing/processing#3094]
Hi, I'm here again! Now I have another problem, we use : 
    size(client.getLWidth(), client.getLHeight(), SMT.RENDERER);
and our sketch starts outside of our screen, but we use too: Frame.setLocation(0,0).
The problem is that, when we run the project for the first time, it doesn't work : 
  OpenGL error 1282 at bot beginDraw(): invalid operation
  OpenGL error 1286 at bot beginDraw(): invalid framebuffer operation
  OpenGL error 1286 at top endDraw(): invalid framebuffer operation
  OpenGL error 1286 at bot endDraw(): invalid framebuffer operation

In internet I read that's a problem between SMT.RENDERER and frame.setLocation. Can anybody help me?? 
Thx

**Comment by Akarshit** [comment]
It would be very helpful if you could post a snippet of the code that is not working .

**Comment by x3sp3d3s** [comment]
The code is to extense for send you and need a lot of libraries for the correct work like that SMT, MPE, Unfolding Maps... I'm sorry but if possible that you help me without code?

Thanks!

**Comment by benfry** [comment]
This isn't a Processing but, and sounds like a question for the forum. Those errors and that use of Frame.setLocation() are specific to the SMT.RENDERER.
