### ISSUE TITLE
PGraphicsRetina2D not in class path when using core.jar in Eclipse

### ISSUE THREAD

**Issue by rooch84** [processing/processing#3095]
With a fresh clone I can use the processing.core.PGraphicsRetina2D renderer in the app, but when I use Eclipse I get the following error:

Exception in thread "main" java.lang.RuntimeException: The processing.core.PGraphicsRetina2D renderer is not in the class path.

This is after I add the following to my PApplet class:
public String sketchRenderer() {
	return "processing.core.PGraphicsRetina2D";
}

Any help would be appreciated.

**Comment by benfry** [comment]
At the moment it's called `PGraphicsJava2D2X`. Not sure if that'll be the final name, so it's not been documented yet.
