### ISSUE TITLE
after creating a tab, must switch to another before opening the new tab

### ISSUE THREAD

**Issue by AlexLardschneider** [processing/processing#3099]
When you create a new Tab you have to switch to another Tab before you can open the one you just created.

**Comment by REAS** [comment]
Which version of Processing are you using?

**Comment by AlexLardschneider** [comment]
3.0a5

**Comment by StanLepunK** [comment]
I confirm thsi proble m to on P305 / OSX

**Comment by benfry** [comment]
I can't reproduce this. The new tab should be the frontmost tab right after it's created, and that's what I'm seeing. What am I missing?

**Comment by Plastix** [comment]
I can't reproduce this either. When I make a new tab PDE automatically switches to it.

**Comment by AlexLardschneider** [comment]
Creating a new tab in 3.0a5 on OS X 10.10 does not switch to it and you can't click on it. You have to switch to another tab first and then to the newly created one to use it.

**Comment by benfry** [comment]
I suspect this is a bug with `repaint()` not being called, or not being called correctly (i.e. not in sync w/ the EDT), and therefore a threading issue. That's why it's showing up on some machines and not others. The issue is that it's changed to that tab, but the screen hasn't updated. Clicking the tab again doesn't do anything because the code thinks it's already there.

**Comment by AlexLardschneider** [comment]
But also the code window displays the code from the previous tab, and not a white empty tab.

**Comment by Plastix** [comment]
Have you you tried running from source?

**Comment by AlexLardschneider** [comment]
No I haven't tried that

**Comment by aengelke** [comment]
Some analysis: This happens, whenever the new tab is inserted *before* the current tab. In the sketch instance stores an index of the active tab, and doesn't update it whenever a new tab is inserted. Therefore, it thinks that the current tab *is the new tab from the index, but it is not from the sketch code instance* (which is used to determine the active tab elsewhere in the code).

Currently preparing a PR which fixes this.
