### ISSUE TITLE
missing parenthesis error message

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3103]
@Manindra29 

The following code:

```
if (x < 5 {
  ellipse(0,0,10,10);
}
```

produces the error message: `Error on ") Statement"`

I'm wondering if we could say `Missing closing parentheses ")"` instead?

I should note that

```
if x < 5) {
  ellipse(0,0,10,10);
}
```

produces the error message: `Missing opening parentheses "("`

**Comment by Manindra29** [comment]
Yeah, I'll investigate it to see what can be done.

**Comment by Manindra29** [comment]
Should be fixed.
