### ISSUE TITLE
Missing opening curly bracket error

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3104]
@Manindra29 

The following:

```
void setup() 
  if (mouseX > 10) {
  }
}
```

correctly produces the error: `Missing opening curly bracket "{"`

However if the missing opening curly bracket is inside another block, i.e.

```
void setup() {
  if (mouseX > 10) 
  }
}
```

we get `Error on ")"Consider adding a "Statement"	` and `Error on "}"`. Is it possible to detect a missing opening curly bracket here?

Missing closing brackets detect correctly in various combinations like above.

**Comment by Manindra29** [comment]
The Eclipse parser can't detect for the second case if a bracket or statement is missing. The internal error reported is: `Syntax error on ")", Statement expected after this`. It expects:
````if (mouseX > 10) <some code statement>````

So I could display an error like: `expecting a statement(code) after )`? What message would be appropriate?

**Comment by shiffman** [comment]
I think we should probably just leave it as `Syntax error on ")"` since that's pretty accurate.  I found the "Statement" expected to be confusing.  Unless we can specify what is expected (in this case a `{` but in other cases something else) I would just leave that out.  Thanks!

**Comment by Manindra29** [comment]
Okay, now it displays `Syntax error on ")"`
