### ISSUE TITLE
Support of 'long' in Procesing

### ISSUE THREAD

**Issue by user-999** [processing/processing#3105]
Maybe somebody read the news about:

http://arstechnica.com/business/2014/12/gangnam-style-overflows-int_max-forces-youtube-to-go-64-bit

Everything is inflating - space, money and even YouTube clicks. Big Data will come to every home.
It seems Processing should also support 'long int' in future releases. Of course in programming there is a (dirty) workaround for every missing feature. I wrote a program in processing to visualize the output of a logic analyzer which often has more than MAX_INT samples. It is working, but I would not like to show the code to anybody. So I would really appreciate if 'long int' could be fully supported. I am not sure where is the right place to ask for it, with best regards, Helmut, user999@web.de

**Comment by JakubValtar** [comment]
We already have that, it's called `long`. You can read about it in [reference](https://processing.org/reference/long.html).
```processing
long bigNumber = Integer.MAX_VALUE;
println(bigNumber); //  2,147,483,647
bigNumber *= 20;
println(bigNumber); // 42,949,672,940

```

**Comment by benfry** [comment]
As Jakub notes, it's already possible to use long. It's not part of the graphics APIs (because it's not useful enough there), but some of the data APIs support it (i.e. `getLong()` in `Table`).
