### ISSUE TITLE
CTRL + C / CTRL + X not working as intended in 3.0a5 (Ubuntu 14.10, US International keyboard)

### ISSUE THREAD

**Issue by JobLeonard** [processing/processing#3107]
* Works fine in 2.0
* CTRL + any other key works fine

I can check if the problem is the same in Windows 8.1 later, if you want.

**Comment by GKFX** [comment]
Bug does not exist on 0233, Ubuntu 14.04, UK Keyboard, which is odd. Nearly the same system.

**Comment by JobLeonard** [comment]
Ok, this is starting to get weird: 

* I can use CTRL + X as a workaround, EXCEPT with the new sketch that opens when starting the PDE.
* I can use CTRL + C starting with the third sketch opened
* Opening a new sketch does not retroactively fix CTRL + C or CTRL + X in the first two windows

**Comment by hamoid** [comment]
It happens to me sometimes too in Arch Linux 64bit. I press ctrl+x or ctrl+c and nothing happens. I notice because I then paste the wrong thing. If I use the menu to copy, it works. Then I can ctrl+v to paste without any issues.

For me it's not the first window. So far it feels random and rare, and I have not noticed a pattern.

**Comment by GKFX** [comment]
Hold on, I'm being dim. I already knew why it happens and how to fix it. It's when the menu item Action for cut/copy is disabled and not re-enabled until the menu is opened.

**Comment by JobLeonard** [comment]
So until a fix comes out, opening the menu is a simple workaround?

Because I am about to start a four week introduction to programming course with interaction designers, and would like to use 3.0 in class with my students because of all the shiny new features (like tweak mode).

**Comment by GKFX** [comment]
@JobLeonard If you're happy to recompile Processing, open `Editor.java`, and in the classes `CutAction` and `CopyAction`,  pass `true` to the function that controls the activation of the function wherever it appears.
Sorry I can't fix this properly now – I don't have a PC with me – but that's the best possible workaround.

**Comment by benfry** [comment]
Fixed here: https://github.com/processing/processing/pull/3138
