### ISSUE TITLE
convenience main() function is broken

### ISSUE THREAD

**Issue by woutgg** [processing/processing#3108]
The [main(String, String[]) function](https://github.com/processing/processing/blob/master/core/src/processing/core/PApplet.java#L9271) does not work correctly with extra arguments since it places the class name before the arguments.
runSketch() [stops processing arguments](https://github.com/processing/processing/blob/master/core/src/processing/core/PApplet.java#L9353) as soon as it finds the class name, hence the arguments (such as --display=0) are never processed.

**Comment by benfry** [comment]
That's the correct behavior. The second parameter are arguments passed to your sketch. If you want to pass arguments to PApplet itself, use its `main()` method, not a convenience method.
