### ISSUE TITLE
Auto-completion does not seem to be working

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3111]
Steps to reproduce the problem:

1. Open preferences
2. Check the ```Code completion with Ctrl+space``` option
3. Click on OK
4. Restart processing (just in case)
5. Try the following code:
```
void setup() {

} 
```
6.In between the 2 curly braces, insert ```backgroun``` and hit Ctrl+space

Tested with revision 0233 on Windows 8.1

**Comment by benfry** [comment]
Stumped on this one; not sure why it isn't firing. I just went in and waded around a bit but I don't know enough about how @Manindra29 implemented this that I can fix it.

**Comment by Manindra29** [comment]
I dug into this a bit today. Looks like 2-3 things are broken in the code completion component (preparePredictions() is acting a little strange in ASTGenerator.java). I was able to fix a NPE bug in CompletionPanel. But CC isn't fully working yet. Have to dig deeper.

**Comment by benfry** [comment]
Appreciate you looking into it. Let me know what you find.

**Comment by Manindra29** [comment]
A local variable was shadowing a critical local variable. Relieved to see it was not something major.
