### ISSUE TITLE
Sketch not appearing depending on arangement of external dIsplay on mac osx

### ISSUE THREAD

**Issue by pjryan93** [processing/processing#3118]
Running a fresh clones of processing from Github.
I'm on a late 2011 macbook pro running 10.10.2
Using an external Apple Cinema HD Display

I'm not sure if this is worth its own bug report, but I was trying to fix https://github.com/processing/processing/issues/3082 when i noticed some strange results.  

When the display is arranged like this everything works fine
![screenshot1](https://cloud.githubusercontent.com/assets/7769635/6315488/48ddd5a4-b9c9-11e4-9977-53ac9620ebcd.png)

but when set to any other arrangement like below, the sketch  usually doesn't appear.

![screen shot 2015-02-21 at 12 49 38 pm](https://cloud.githubusercontent.com/assets/7769635/6315491/63a9eeae-b9c9-11e4-849a-8c878eda8d16.png)

There are two situations resulting in weird behavior

1)In preferences, my display is set to 1(external display) and the editor is located on display 2(my macbook pro). So the main in the sketch is setting the window location, but the sketch never appears.

and,

2) My editor is located on display 1 and the sketch is set to be shown on display 1. It registers that the Editor and RunDevice are on the same display, but the sketch doesn't appear the majority of the time or it appears on the wrong display. I noticed the editor's coordinates being passed into PApplet are negative. When explicitly setting the location of the frame it still shows up on the wrong display.
The error persists regardless of the placement of the last launched sketch. 

Everything works regardless of display arrangement when fullScreen mode is enabled.

**Comment by benfry** [comment]
Thanks for reporting. Fixed for 3.0 alpha 10.
