### ISSUE TITLE
endShape(CLOSE) does not work for shapes with contours in Java2D renderer

### ISSUE THREAD

**Issue by tillnagel** [processing/processing#3122]
When drawing shapes having contours the main shape is not closed even if endShape(CLOSE) has been used. This only happens when inner contours are actually used, not if only the main shape is drawn as a contour. It works in the OPENGL renderers alright.

```
	beginShape();

	// main shape
	beginContour();
	for (Location location : shapeFeature.getLocations()) {
		ScreenPosition pos = map.getScreenPosition(location);
		vertex(pos.x, pos.y);
	}
	endContour();
			
	// interior rings
	for (List<Location> interiorRing : shapeFeature.getInteriorRings()) {
		beginContour();
		for (Location location : interiorRing) {
			ScreenPosition pos = map.getScreenPosition(location);
			vertex(pos.x, pos.y);
		}
		endContour();
	}

	endShape(CLOSE); // Does not close the shape in Java2D. 
```

**Comment by REAS** [comment]
To clarify, this is an issue in JAVA2D, but not in P2D and P3D. 
Are using 3.0a5 or an earlier version?
Are you sure the winding is correct?

**Comment by tillnagel** [comment]
Correct, doesn't work in JAVA2D, but works in P2D, P3D. I am using the latest stable P2. (Is P2 not in active development, anymore?)

Winding seems correct. (Outer ring is clock-wise, interior rings counter-clock-wise.) See below:

![Shape example with interior rings](http://i.imgur.com/9N0a782.png)

**Comment by REAS** [comment]
Please try in 3.0a5. The 2+ releases are not in active development. We have been working on related issues and I think it may be fixed now, but if not, we would like to fix it.

**Comment by tillnagel** [comment]
Tried it out in 3.0a5 and it doesn't work at all anymore. As in the shape is not drawn at all when using beginContour and endContour - whether using only the main shape or main plus interior rings.

This, again, is only in JAVA2D. It works correctly in the OpenGL renderers.

**Comment by tillnagel** [comment]
I tested it a bit further, and it seems in 3.05a with JAVA2D the shape is only drawn at all (and then correctly, i.e. closed) when the main shape is not inside a contour itself.

From your beginContour() example:

*Does not work: (main shape inside a contour)*
```
size(100, 100); // JAVA2D
translate(50, 50);
stroke(255, 0, 0);
beginShape();
// Exterior part of shape, clockwise winding
beginContour();
vertex(-40, -40);
vertex(40, -40);
vertex(40, 40);
vertex(-40, 40);
endContour();
// Interior part of shape, counter-clockwise winding
beginContour();
vertex(-20, -20);
vertex(-20, 20);
vertex(20, 20);
vertex(20, -20);
endContour();
endShape(CLOSE);
```

*Works: (Main shape not a contour)*
```
size(100, 100);
translate(50, 50);
stroke(255, 0, 0);
beginShape();
// Exterior part of shape, clockwise winding
vertex(-40, -40);
vertex(40, -40);
vertex(40, 40);
vertex(-40, 40);
// Interior part of shape, counter-clockwise winding
beginContour();
vertex(-20, -20);
vertex(-20, 20);
vertex(20, 20);
vertex(20, -20);
endContour();
endShape(CLOSE);
```

Both versions work fine in P2D.

**Comment by tillnagel** [comment]
And that (second version w/ main shape not a contour) works also in P2.2.1.

**Comment by REAS** [comment]
Is this a good one for @JakubValtar

**Comment by benfry** [comment]
The main shape should not be inside begin/endContour(). If you remove that from your code, does that work properly?

**Comment by tillnagel** [comment]
Yes, that's what I have done. Paging @shiffman to update PShape tutorial which still includes begin/endContour also around the main shape. 

https://processing.org/tutorials/pshape/ under "More Custom PShapes"

**Comment by benfry** [comment]
And perhaps @codeanticode should add something in P2D/P3D so that calling `beginContour()` is frowned upon for the exterior shape.

**Comment by JakubValtar** [comment]
I fixed some bugs in countours in #2927 because there were problems with closing strokes in all renderers. It is expected that main shape is not inside the countour block.

**Comment by tillnagel** [comment]
Ok, one more thing. The tutorial as well as the distributed example Topics/Create Shapes/BeginEndContour has a bug regarding winding. The interior ring (contour) is also clock-wise, and while being displayed it is not a hole.

![Contour test rendering](http://i.imgur.com/tmBoflr.png)

left: Original example, right: fixed code, now a hole.

```
s.beginContour();
s.vertex(-10,-10);
s.vertex(-10,10); // This vertex exchanged with
s.vertex(10,10);
s.vertex(10,-10); // this one.
s.endContour();
```

**Comment by tillnagel** [comment]
Closing it. Not a bug, just used it incorrectly (following tutorials, which got fixed in the mean time).
