### ISSUE TITLE
Processing starts, but sketches won't run when localhost is not resolvable

### ISSUE THREAD

**Issue by cibomahto** [processing/processing#3123]
System: OS X 10.9.5
Processing version: 2.2.1

The symptoms were that Processing was working fine one day, then later sketches stopped working (or sometimes would delay opening for 1-2 minutes). No errors were displayed in Processing, logged in console .err files, or reported to OS X Console. There was a repeating error in OS X Console for an unrelated service (mtmapp: MTM fs Mount server retrying...), and troubleshooting that lead to discovering that localhost wasn't resolvable. The issue was that localhost was set to "fe80::1%lo0", and IP6 routing was somehow broken. Resetting localhost to 127.0.0.1 allowed Processing sketches to work again.

**Comment by cibomahto** [comment]
This might be too esoteric of an issue to fix, but it would be excellent if there were some warning that this was happening, or a timeout error if Processing wasn't able to establish a connection to itself.

**Comment by benfry** [comment]
I'd like to fix this, but I can't imagine how we'd even detect that you've messed with your hosts file to cause resolution problems (outside of weird platform-specific hacks that don't work in all cases). 

Certainly we can detect timeouts, but that's a long ways from "hey, why'd you mess with your hosts file?"  or "your ipv6 routing is screwed up" in any fashion that would be suitable for our target audience.

**Comment by benfry** [comment]
Figured out a way to at least detect that it was happening (and confirmed we don't have any control over use of the `localhost` name). 

For the next release (3.2.4 or 3.3), this will be detected and an error shown to the user: https://github.com/processing/processing/issues/4738

**Comment by cibomahto** [comment]
Thanks!!!
