### ISSUE TITLE
Copyright Out Of Date

### ISSUE THREAD

**Issue by Cubit-Games** [processing/processing#3124]
My friend was looking through files in a exported program using your software and he noticed inside your "COPYRIGHT" file as found in the "java" file in the exported sketch folder, your copyright is out of date, i felt i needed to notify because as for now and for the past 2 years, it has been up-for grabs. -Cubit-Games

**Comment by spasmsaps** [comment]
see #224

**Comment by benfry** [comment]
Closing as duplicate of https://github.com/processing/processing/issues/224
