### ISSUE TITLE
When sketch is re-run the position of the window opened is below the location of the previous window.

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3125]
When sketch is re-run the position of the window opened is below the location of the previous window.  
void setup() {
  size(200, 200);
}

void draw() {
}  
When this sketch is run then stopped and then again run the new window opened is below the position of the previous one . if this is repeated many times the window position reaches to the bottom of the screen.  
Shouln't it open at the position where the previous window was opened or something like that ?

**Comment by benfry** [comment]
It should, that sounds like a regression.

**Comment by Akarshit** [comment]
I am unable to look into this because of issues with my system. But for someone who is looking into this i think the problem might be in https://github.com/processing/processing/blob/master/core/src/processing/core/PSurfaceAWT.java#L711

**Comment by benfry** [comment]
Should be fixed in alpha 10.
