### ISSUE TITLE
Feature Request - Display line numbers alongside code and add jump to line

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3128]
Wouldn't it be really helpful if line no is displayed alongside code ?
And the jump to line feature would be useful as well.

**Comment by Akarshit** [comment]
I would like to try to implement these if the community feels that they should be included.

**Comment by benfry** [comment]
We'll be adding line numbers to 3.x when I have a chance to work on the GUI.

**Comment by benfry** [comment]
Line numbers now implemented. No plans for jumping to a line. To be clear, we're not trying to build a full-featured programmer's editor—that's what Eclipse and Sublime et al are for.
