### ISSUE TITLE
Examples Manager Window

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3133]
I had some notes about how the examples manager window should look from a previous discussion but couldn't find a github issue about it so am filing one for tracking.  Currently it looks like:

![screen shot 2015-02-27 at 3 09 57 pm](https://cloud.githubusercontent.com/assets/191758/6414871/bfdd69a8-be92-11e4-8217-64f26c57ac7e.png)
My notes are as follows:

Examples Manager
  * Remove "Mode Examples" hierarchy
  * Modify how "Add Examples..." looks, CR to work with James
  * Should be
    * Basics
    * Topics
    * Demos
    * Foundation Libraries (Core Libraries if video not here)
      * dxf
      * net
      * pdf
      * serial
      * sound (if installed)
      * video (if installed)
    * Libraries
      * List of contributed libraries

**Comment by REAS** [comment]
Thanks for adding this. James, Ben and I discussed this last week, but we didn't make this concrete list yet. We have a plan for how to skin "Add Examples"

**Comment by Plastix** [comment]
Are there actually any examples that populate the `Basics`, `Topics`, and `Demos` folders?

**Comment by benfry** [comment]
Yes, all of them. You need to check out the processing-docs repo.

**Comment by Plastix** [comment]
@benfry I feel bad asking but how do I build processing with the docs from processing-docs? Or do I move the examples into the Processing folder in my documents?

**Comment by benfry** [comment]
Yep, covered in the build instructions: https://github.com/processing/processing/wiki/Build-Instructions

**Comment by shiffman** [comment]
I am re-opening this.  From our previous discussions if the "video" or "sound" foundation libraries are installed the examples for these libraries should appear under "core" or "foundation" libraries, rather than under the general libraries list.   I am not seeing this in 3.0a11.

**Comment by benfry** [comment]
Can you open something new for that issue? It's actually a really different thing code-wise that hadn't been considering as part of that other work that closed this particular issue.

**Comment by shiffman** [comment]
Yes, doing so now.

**Comment by benfry** [comment]
Thanks!
