### ISSUE TITLE
wrong jre download on ant linux-run

### ISSUE THREAD

**Issue by panictom** [processing/processing#3137]
i586 jre download , but executed it on armv7l armv7l armv7l GNU/Linux

steps to reproduce:
git clone https://github.com/processing/processing.git --depth 1
ant linux-run
.
.
[get] Getting: http://download.processing.org/java/jre-8u31-linux-i586.tar.gz
.
.
expected result:
download the current arm version of the jre

**Comment by benfry** [comment]
We don't have any ARM support, unfortunately. And nobody who can support it anyway, so there's no open issue about it.

Most likely this would be implemented by someone making proper Raspberry Pi support happen, which might be a Google Summer of Code project (or something we support through the Foundation).
