### ISSUE TITLE
No library found for processing.net

### ISSUE THREAD

**Issue by geokoz** [processing/processing#3139]
I am using Processing 3.0a5 on Win 7 64 laptop. 
Copied a simple example - web client using HTTP.

// A simple web client using HTTP
import processing.net.*; 

Client c; 
String data;

void setup() { 
  size(400, 400); 
  background(50); 
  fill(200);
  c = new Client(this, "www.nytimes.com", 80);  // Connect to server on port 80 
  c.write("GET / HTTP/1.0\n");  // Use the HTTP "GET" command to ask for a webpage
//  c.write("Host: my_domain_name.com\n\n"); // Be polite and say who we are
} 

void draw() {
  if (c.available() > 0) {    // If there's incoming data from the client...
    data += c.readString();   // ...then grab it and print it 
    println(data); 
  } 
}

When run as Java I get no errors, but not any result printed either (?)
When I run it as Android (on my Nexus 4 phone) I get several errors:
:disappointed: 
No library found for processing.net
java.io.FileNotFoundException: C:\Users\gkozinakov\Documents\Processing\modes\AndroidMode\icons\icon-96.png (The system cannot find the file specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at processing.app.Base.copyFile(Base.java:2458)
	at processing.mode.android.AndroidBuild.writeRes(AndroidBuild.java:807)
	at processing.mode.android.AndroidBuild.createProject(AndroidBuild.java:169)
	at processing.mode.android.AndroidBuild.build(AndroidBuild.java:91)
	at processing.mode.android.AndroidMode.handleRunDevice(AndroidMode.java:227)
	at processing.mode.android.AndroidEditor$16.run(AndroidEditor.java:513)
    [mkdir] Created dir: C:\Users\GKOZIN~1\AppData\Local\Temp\android18643543776710837sketch\bin
     [echo] C:\processing-3.0a5\tools/../modes/java/mode/ecj.jar
     [echo] org.eclipse.jdt.core.JDTCompilerAdapter

-set-mode-check:

-set-debug-files:

-check-env:
Android SDK Tools Revision 24.0.2
Installed at C:\Users\gkozinakov\AppData\Local\Android\android-sdk

-setup:
     [echo] Project Name: SimpleWebClient
Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
Using latest Build Tools: 21.1.1
     [echo] Resolving Build Target for SimpleWebClient...
Project Target:   Android 2.2
API level:        8
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: C:\Users\GKOZIN~1\AppData\Local\Temp\android18643543776710837sketch\bin\res
    [mkdir] Created dir: C:\Users\GKOZIN~1\AppData\Local\Temp\android18643543776710837sketch\bin\rsObj
    [mkdir] Created dir: C:\Users\GKOZIN~1\AppData\Local\Temp\android18643543776710837sketch\bin\rsLibs
    [mkdir] Created dir: C:\Users\GKOZIN~1\AppData\Local\Temp\android18643543776710837sketch\gen
    [mkdir] Created dir: C:\Users\GKOZIN~1\AppData\Local\Temp\android18643543776710837sketch\bin\classes
    [mkdir] Created dir: C:\Users\GKOZIN~1\AppData\Local\Temp\android18643543776710837sketch\bin\dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for SimpleWebClient...
Library dependencies:
No Libraries

------------------
API<=15: Adding annotations.jar to the classpath.
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
Merging AndroidManifest files into one.
Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
Generating BuildConfig class.

-pre-compile:

-compile:    [javac]  Compiling 3 source files to C:\Users\GKOZIN~1\AppData\Local\Temp\android18643543776710837sketch\bin\classes
----------
1. ERROR in C:\Users\gkozinakov\AppData\Local\Temp\android18643543776710837sketch\src\processing\test\simplewebclient\SimpleWebClient.java (at line 8)
	import processing.net.*; 
	       ^^^^^^^^^^^^^^
The import processing.net cannot be resolved
----------
2. ERROR in C:\Users\gkozinakov\AppData\Local\Temp\android18643543776710837sketch\src\processing\test\simplewebclient\SimpleWebClient.java (at line 24)
	Client c; 
	^^^^^^
Client cannot be resolved to a type
----------
3. ERROR in C:\Users\gkozinakov\AppData\Local\Temp\android18643543776710837sketch\src\processing\test\simplewebclient\SimpleWebClient.java (at line 31)
	c = new Client(this, "www.nytimes.com", 80);  // Connect to server on port 80 
	^
Client cannot be resolved to a type
----------
4. ERROR in C:\Users\gkozinakov\AppData\Local\Temp\android18643543776710837sketch\src\processing\test\simplewebclient\SimpleWebClient.java (at line 31)
	c = new Client(this, "www.nytimes.com", 80);  // Connect to server on port 80 
	        ^^^^^^
Client cannot be resolved to a type
----------
5. ERROR in C:\Users\gkozinakov\AppData\Local\Temp\android18643543776710837sketch\src\processing\test\simplewebclient\SimpleWebClient.java (at line 32)
	c.write("GET / HTTP/1.0\n");  // Use the HTTP "GET" command to ask for a webpage
	^
Client cannot be resolved to a type
----------
6. ERROR in C:\Users\gkozinakov\AppData\Local\Temp\android18643543776710837sketch\src\processing\test\simplewebclient\SimpleWebClient.java (at line 37)
	if (c.available() > 0) {    // If there's incoming data from the client...
	    ^
Client cannot be resolved to a type
----------
7. ERROR in C:\Users\gkozinakov\AppData\Local\Temp\android18643543776710837sketch\src\processing\test\simplewebclient\SimpleWebClient.java (at line 38)
	data += c.readString();   // ...then grab it and print it 
	        ^
Client cannot be resolved to a type
----------
7 problems (7 errors)

BUILD FAILED
C:\Users\GKOZIN~1\AppData\Local\Temp\android18643543776710837sketch\build.xml:15: The following error occurred while executing this line:
C:\Users\GKOZIN~1\AppData\Local\Temp\android18643543776710837sketch\build.xml:28: Compile failed; see the compiler error output for details.

Total time: 3 seconds

===========================
What do I need to change in my PC Processing environment and what on my Android phone to resolve this?

**Comment by qianlvable** [comment]
The Processing processing.net lib not work in android mode.You can try to use oscP5 library for network connection.

**Comment by benfry** [comment]
Please use the android repo for Android issues: https://github.com/processing/processing-android
