### ISSUE TITLE
lerpColor() outside of setup()/draw() kills sketch

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3145]
From https://github.com/jdf/Processing.py-Bugs/issues/127

This fails:

```
color c = lerpColor(color(0), color(100), .5);  // boom! crashes.
void setup() {}  // unless you comment this out
```

Checked and this works:

```
float c = lerp(0, 100 .5);
void setup() {} 
```

The error is likely due to: "If you call lerpColor in an active-mode sketch before setup() has run, there's no current graphics context, and it NPEs."

I would guess we can implement the same fix as https://github.com/jdf/processing.py/commit/5752ee3e79934f6984ab07dc45861d389e176558

**Comment by Akarshit** [comment]
@shiffman The fix was same as implemented in the provided link.

**Comment by benfry** [comment]
All set for 3.0a6 thanks to @Akarshit.
