### ISSUE TITLE
Running an empty sketch

### ISSUE THREAD

**Issue by coolutpal** [processing/processing#3149]
Running an empty sketch returns a default small window with the background same as that of an application running in background . Tested on linux 32 bit.

**Comment by coolutpal** [comment]
Might be referenced with a previous issue

**Comment by Akarshit** [comment]
I dont think this is an issue , there is no use of an empty sketch and the window is only there to show that its working.  
At most the background of the sketch could be set to a default value ( but i don't think its necessary )

**Comment by coolutpal** [comment]
Well but don't you think someone might get a wrong idea of sketch ?

**Comment by Akarshit** [comment]
I think that's why the background was same as that of an application running in background.  
But it might be worth looking into.

**Comment by hamoid** [comment]
Often when I teach, I start by running the simplest program possible: the one with 0 lines of code. And you get a window. I do this to show that what in other languages could be many lines of code, with Processing is trivial. In Arch Linux 64 bit it seems to work fine though.

**Comment by benfry** [comment]
It should be showing a window with the default background and default size (100x100), in part for the reason @hamoid describes. 

But perhaps you're seeing #3129, which is causing the window to be a little shorter than it's supposed to be?

**Comment by coolutpal** [comment]
No problem with sizes on my system (Linux based)might have to do with other Operating systems .
