### ISSUE TITLE
SVG with compound shapes not displaying correctly

### ISSUE THREAD

**Issue by vitorgalvao** [processing/processing#3150]
I have the following SVG:

![](http://vitorgalvao.com/pending/my_svg.svg)

It’s a single shape (compound path) and seems to display correctly in most places. However, when loading it with processing, this is how it looks:

![](http://i.imgur.com/hUEcOHe.png)

If we disable styles, we can see that all the information is there, just the intersections aren’t being handled correctly:

![](http://i.imgur.com/IVLLTX8.png)

If we record the sketch as a PDF, it is faithful to Processing’s representation (wrong considering the expected results).

The code in the screenshots is simply

```processing
PShape shape_to_use = loadShape("my_svg.svg");
shape_to_use.disableStyle();
shape(shape_to_use, 0, 0, 100, 100);
```

I’ve also [packaged everything as a zip](http://vitorgalvao.com/pending/test_svg.zip) for easy retrieval and testing.

Happens both with versions 3.0a5 and 2.2.1.

**Comment by Plastix** [comment]
This doesn't appear to be a bug but rather a consequence of Processing not supporting the full SVG style spec. When you load your SVG, Processing is ignoring the `fill-rule:evenodd;clip-rule:evenodd` from your shape.

**Comment by vitorgalvao** [comment]
@Plastix Seems like you might be right. I’ve recreated the svg with a different tool that didn’t output that style, and could get it to work as expected. Thank you.

Shouldn’t we open an issue regarding supporting the full SVG style spec, though? It would be useful to have.

**Comment by danielTorrer** [comment]
@vitorgalvao did you find a workaround for this? I'm facing the same issue and for a moment I thought my SVG file was currupt.

**Comment by vitorgalvao** [comment]
@danieltorrer Nope, no workaround. There isn’t much we can do since we [need the full SVG spec to be implemented](https://github.com/processing/processing/issues/3179).

**Comment by vitorgalvao** [comment]
@danieltorrer Nope, no workaround. There isn’t much we can do since we [need the full SVG spec to be implemented](https://github.com/processing/processing/issues/3179).

One thing you might try (depending on your needs) is to use [p5.js](http://p5js.org/). The API is similar, and since it runs in a browser presumably all the SVG heavy lifting has already been done.

**Comment by benfry** [comment]
The fix is to not use even-odd winding on the paths. Processing doesn't read the parameter, but also doesn't have support for different types of winding rules.
