### ISSUE TITLE
Export sketch in svg,png and other formats 

### ISSUE THREAD

**Issue by coolutpal** [processing/processing#3151]
It would be great if a sketch can be exported in other formats . It could be added as an enhancement . If someone is working on it please let me know . Again it can be referenced with previous issues if they exist .

**Comment by vitorgalvao** [comment]
You can already save as a `png` (or other image formats) very easily with [save()](https://processing.org/reference/save_.html) and [saveFrame()](https://processing.org/reference/saveFrame_.html).

As for SVG, there are a number of libraries for it, such as [Geomerative](http://www.ricardmarxer.com/geomerative/) and [P8gGraphicsSVG](http://phi.lho.free.fr/programming/Processing/P8gGraphicsSVG/).

**Comment by coolutpal** [comment]
Right ..
