### ISSUE TITLE
[REGRESSION] saveFrame broken with OPENGL. Only saves background

### ISSUE THREAD

**Issue by teo1978** [processing/processing#3152]
I have a sketch I wrote a long time ago for version 2.0.something or maybe earlier. It uses sizes(...,OPENGL) and it uses saveFrame() to save the output.
It used to work perfectly.

Now on 2.2.1, the output of saveFrames() are images with only the background (which happens to be an image). Nothing else is drawn.

**Comment by teo1978** [comment]
Same issue with P3D instead of OPENGL.

**Comment by teo1978** [comment]
Seems to be fixed in 3.0a5.
However 3.0 is still experimental, so the fix needs to be backported to the stable version, as this is a critical regression.

**Comment by benfry** [comment]
The source code for 2.x is available, and you're welcome to backport. We're doing this in our spare time and don't remotely have the time to support old releases or backports.
