### ISSUE TITLE
Console is printing without running the sketch

### ISSUE THREAD

**Issue by ziadewais** [processing/processing#3153]
Hi,
I have single println in my code that prints out 2 int values. The initial values are -1 and -1 and they change when the sketch runs. Now the console is printing out these initial values without running the sketch. and when i run the sketch i get a line with my expected values and the next line is the initial values. 
Please advise.
Thanks!

**Comment by Akarshit** [comment]
Can you please paste the code that is causing this ( or atleast snippet of it ). That would help immensly in figuring out the error.

**Comment by ziadewais** [comment]
the whole code is shared here
https://gist.github.com/ziadewais/bbe4bc8e71075aa21e39
all the print statements i used are commented out.

**Comment by ziadewais** [comment]
So I restarted processing...didn't solve it/// opened another sketch and still the console is printing out. So I restarted the machine and it fixed it.

**Comment by benfry** [comment]
There's still a print statement inside `SinterOutputModule`.
