### ISSUE TITLE
Ubuntu Unity prevents full screen from working properly

### ISSUE THREAD

**Issue by JobLeonard** [processing/processing#3158]
Processing 3.05a, Ubuntu 14.10

Looking around on the internet, this appears to be a general Java/Linux problem, although there are solutions:

http://stackoverflow.com/questions/12520658/java-fullscreen-mode-not-working-on-ubuntu
http://stackoverflow.com/questions/8837719/java-in-full-screen-on-linux-how-to-cover-task-bar

**Comment by hamoid** [comment]
As far as I've tested during the last 4 years or so, this is a Unity thing. It's not Ubuntu or Linux. And no matter what I tried, it never worked. It's not even Processing, Java programs developed in Eclipse also would not go full screen.

Unfortunately, a large part of Linux users are also using Unity, so none of them can probably get full screen in Java. 

You can install another desktop environment, which may be an option if you want to leave an art installation running. When you have several desktop environments, you can easily choose which one you want on the login screen.

**Comment by JobLeonard** [comment]
Thanks for the link hamoid.

Just a thought: why not include these snippets as advanced examples? (actually, there's a few snippets on the wiki - like the old trick for multiple simultaneous key presses - that I think might be worth including as examples)

**Comment by benfry** [comment]
This is unfortunate, I didn't realize Unity was doing this. 

And this is even a problem when `GraphicsDevice.setFullScreenWindow(window)` is used with Java 8u40? We're not using that in the current code (because of the goofy OS X handling, and it prevents multi-screen use), but it would be a consideration.

**Comment by hamoid** [comment]
The second link above offers a solution that should work on Java 7 and 8, Unity and Ubuntu 14.10, but I no longer have Ubuntu to try. Do you have Eclipse to trie that @JobLeonard ? Or to try what @benfry mentions?

**Comment by JobLeonard** [comment]
Well, I can get it of course, since it's free. But I really need a for-dummies instruction, since I never really used it before.

**Comment by hamoid** [comment]
Maybe we could export a jar file from [this full screen test program by Oracle](https://docs.oracle.com/javase/tutorial/displayCode.html?code=https://docs.oracle.com/javase/tutorial/extra/fullscreen/examples/DisplayModeTest.java) (or another test program). The jar file could be executed on different OSes / Java versions to notice if the full screen mode works or not.

If I understand it right, the person testing this on Ubuntu should have Java 8 installed. I leave here the link to [install Java 8](http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html) in case it's needed.

**Comment by Frozenfire92** [comment]
If maximized is what you mean than this isn't just on Unity. I use Gnome 3 and get unintended results with the menus when maximizing my windows. For example the menus show up in the middle of the screen and only when I hold the menu option down with my mouse. I tried taking a screenshot but when pressing a menu option `printscrn` seemed to be disabled

**Comment by hamoid** [comment]
What about a screenshot with your phone or camera? Polaroid specially
welcome :)

**Comment by Frozenfire92** [comment]
Forgot about that wonderful machine ;). The menu only shows up when being pressed

![img_20150403_100719](https://cloud.githubusercontent.com/assets/5893112/6982576/e0089906-d9e9-11e4-8400-55a42d3c4251.jpg)

**Comment by benfry** [comment]
Running that full screen test program with 8u40 (and the multi-buffer test in the same tutorial set) isn't hiding the Unity decorations, in line with the original report. This is happening in spite of the fact that `isFullScreenSupported()` returns `true`. 

I'm testing this inside VMware, so it's possible that others will get different results, but I'm closing this as 'cantfix' since it's a Java + Linux + Window Manager problem that's out of our control.

**Comment by hamoid** [comment]
The bug report at Oracle: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7057287

I don't see any ways to vote it up or leave a comment.
