### ISSUE TITLE
static mode—no setup() / draw()—broken in the repo for OpenGL

### ISSUE THREAD

**Issue by benfry** [processing/processing#3163]
Ala https://github.com/processing/processing/issues/3130 for Java2D, but this time with OpenGL.

Except on OpenGL, the sketch runs and then closes the window. We need the window to stay open after finishing.

**Comment by benfry** [comment]
For that matter, we'll also need to remove the error messages in the console. 

```
DISPLAY PARENT: null
DISPLAY SMOOTH: 2
200 200
CREATE THE DISPLAY
DESTROY
```

Even though I do like the all caps DESTROY in red. Kinda mirrors how folks might feel w/ coding: CREATE THE DISPLAY. DESTROY.

**Comment by benfry** [comment]
Looks like this one is fixed, though there are still a lot of debug messages coming through.

**Comment by codeanticode** [comment]
should be, will take a look anyways, and remove the debug messages while I'm at it.
