### ISSUE TITLE
Processing Serial Problem

### ISSUE THREAD

**Issue by bvernham** [processing/processing#3164]
I am trying to use "PID_FrontEnd_v03" to visualize data coming from the Arduino Uno.

The data is coming from the Uno just fine when you look at the serial monitor but when I run the processing sketch, nothing happen.

The sketch runs and show the correct active com ports.  

new Serial(this, Serial.list()[1], 9600); is correct because Serial.list()[0] is the default COM3.

But nothing happens.

How do I see if the processing schedule is really recieving the data.

Thanks

Bruce

**Comment by benfry** [comment]
This isn't likely a bug; please use forum.processing.org for questions and debugging help.
