### ISSUE TITLE
Fix placement and visual design when showing error on hover

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3173]
Related to #3119:

I like the idea of error info popping up on hover, but two comments:

1. Placement feels a bit awkward.
2. Visual design could use some work to be more consistent with overall PDE.  In particular the yellow color and padding feels off.

![screen shot 2015-04-04 at 10 59 45 am](https://cloud.githubusercontent.com/assets/191758/6992232/dd60e372-dab9-11e4-80c3-a9ee4730cc19.png)

**Comment by jamesjgrady** [comment]
Here is the hover I proposed a while back but I remember there being issue with the triangle in the top left. Let me know if we need to go without it.
![pde-sketch-r14-002](https://cloud.githubusercontent.com/assets/2600893/10009643/3328822c-60ae-11e5-9e5d-d449071bf8fb.png)

**Comment by jamesjgrady** [comment]
After working on the hover for #3407 I'm also questioning the need for this hover box. I think by clicking or hovering on the red dotted line and having the error console highlight the issue would be a better solution.
![pde-sketch-r15-error-hover](https://cloud.githubusercontent.com/assets/2600893/10051429/5a425e36-61ef-11e5-8a3c-019bd21c3896.png)

**Comment by shiffman** [comment]
I agree that the hover is not necessary and possibly just adding noise.

**Comment by benfry** [comment]
So this should probably change to having the correct line highlight in the error listing, and perhaps replacing the text in the big red bar as well?

**Comment by jamesjgrady** [comment]
Yes, this would be the same as the other error screen. See screen grab. No hover necessary.

![pde-sketch-r16-error-002](https://cloud.githubusercontent.com/assets/2600893/10081544/5ceaa0e2-62c3-11e5-8d9e-92bfb9b3bfde.png)

**Comment by benfry** [comment]
Actually we can't make it highlight the list item on over, because separately, highlighting a list item will *select* the line with the error (while promoting it to the console), which makes for a weird chasing-its-tail interaction.

**Comment by benfry** [comment]
Final implementation is a less hideous tooltip that matches the style of the list in the "Errors" tab at the bottom.
