### ISSUE TITLE
Unable to loadFont(vlw)

### ISSUE THREAD

**Issue by GrreenZ** [processing/processing#3174]
Processing-2.2.1 linux64, fonts created using builtin tool and saved in data directory.

```java
PFont font = loadFont("SansSerif.plain-16.vlw");
```
Generates error:

> java.lang.NullPointerException
> 	at java.io.DataInputStream.readInt(Unknown Source)
> 	at processing.core.PFont.<init>(PFont.java:339)
> 
> (...)
> 
> java.lang.RuntimeException: java.lang.RuntimeException: Could not load font SansSerif.plain-16.vlw. > Make sure that the font has been copied to the data folder of your sketch.
>	at processing.core.PApplet.runSketch(PApplet.java:10713)
> (...)

I have checked code using `strace` and PDE look for font in wrong places:

> stat("/home/fred/media/Apps/processing-2.2.1/null/data/SansSerif.plain-16.vlw", 0x7f34f4016db0) = -1 ENOENT (No such file or directory)
> stat("SansSerif.plain-16.vlw", 0x7f34f4016db0) = -1 ENOENT (No such file or directory)
> stat("SansSerif.plain-16.vlw", 0x7f34f4016db0) = -1 ENOENT (No such file or directory)
> open("SansSerif.plain-16.vlw", O_RDONLY) = -1 ENOENT (No such file or directory)
> stat("/tmp/gui4242979379840370889temp/data/SansSerif.plain-16.vlw", 0x7f34f4015fd0) = -1 ENOENT (No such file or directory)
> stat("/tmp/gui4242979379840370889temp/SansSerif.plain-16.vlw", 0x7f34f4015fd0) = -1 ENOENT (No such file or directory)
> lseek(3, 44412425, SEEK_SET)      = 44412425

So, the application searches IDE directory and temporary directory where class files are located, but not in data dir... 

also, I've checked exported aplication and it's behaves differently, despite searching in it's own directory it can not find file because of text "null" added to the search path.

> stat("/home/fred/media/sketchbook/gui/application.linux64/null/data/SansSerif.plain-16.vlw", 0x7f3598df1de0) = -1 ENOENT (No such file or directory)
> stat("SansSerif.plain-16.vlw", 0x7f3598df1de0) = -1 ENOENT (No such file or directory)
> stat("SansSerif.plain-16.vlw", 0x7f3598df1de0) = -1 ENOENT (No such file or directory)
> open("SansSerif.plain-16.vlw", O_RDONLY) = -1 ENOENT (No such file or directory)

**Comment by benfry** [comment]
Please try with 3.0a5.

**Comment by GrreenZ** [comment]
The same result. It looks for `processing-3.0a5/null/data/SansSerif.plain-16.vlw`
or when exported `application.linux64/null/data/SansSerif.plain-16.vlw`

aplication works as expected if I copy this file in those locations.

Thank you for very quick response.

**Comment by benfry** [comment]
Looks like it's already been in the current source, which will eventually be released in 3.0a6.
