### ISSUE TITLE
beginRecord() with a PGraphics2D interferes with the background of the main PApplet

### ISSUE THREAD

**Issue by erniejunior** [processing/processing#3180]
This should show a white background with a black diagonal line. But the background stays the default gray. If you remove the P2D argument to createGraphics, it works OK (then the default Java2D renderer is used).

```processing
PGraphics offscreenBuffer;

void setup() {
  size(200, 200, P2D);
  offscreenBuffer = createGraphics(width, height, P2D);
}

void draw() {
  beginRecord(offscreenBuffer);
  background(255);
  line(0, 0, width, height);
  endRecord();
}
```
Thanks anyway for producing this awesome software!

**Comment by erniejunior** [comment]
I do not know if it is really related but I found it while bughunting: There is a a 'Too many pushFramebuffer calls' exception with the following little sketch:
```processing
void setup() {
  size(200, 200, P2D);
}

void draw() {
  createGraphics(width, height, P2D).beginDraw();
}
```
Again the error disappears as soon as the P2D argument is removed. Apparently the framebuffer stack of the parent graphics (which is the main graphics) is pushed instead of the newly created one. Therefore it will eventually  be full. I do not understand why.

**Comment by erniejunior** [comment]
A closing endDraw will resolve the exception, but the following sketch will happily crash my computer (notice the increased resolution).
```processing
void setup() {
  size(1600, 600, P2D);
}

void draw() {
  println(frameRate);
  PGraphics test = createGraphics(width, height, P2D);
  test.beginDraw();
  test.endDraw();
}
```
I suspect that it fills the RAM faster than the garbage collector can clear it. But I am not sure.
An additional dispose() fixes that. 

*Hint:* if you test the above code stop the sketch as the framerate approaches 10 to avoid a hard reset of you computer. Also hit save on any important files and better close intelliJ. Now my project files are corrupted :-(

**Comment by benfry** [comment]
Don't call `createGraphics()` inside `draw()`. That example is creating new OpenGL drawing contexts at 60 frames a second. That's not a Processing problem, you're going to crash your machine no matter what language you use.

The initial report is a bug, but these two follow-ups are not a good way to debug the issue.

**Comment by JakubValtar** [comment]
Hi @erniejunior, thank you for your report. This is sadly not how you should use `beginRecord()`. Please see the [reference](https://processing.org/reference/beginRecord_.html). It will not work with P2D nor P3D.
