### ISSUE TITLE
Processing 2.2.1 thinks it's on Mac OS X when using Ubuntu 12.04.5

### ISSUE THREAD

**Issue by pinkfoot** [processing/processing#3182]
Using Python Mode / Processing 2.2.1 / Oracle JRE 8 / LXLE (Ubuntu 12.04.5):

Although it's running on Linux, on launch this error message is output twice before the Processing window appears:
"This version of Mac OS X does not support the Apple EAWT.  ApplicationEvent handling has been disabled (java.lang.ClassNotFoundException com.apple.eawt.Application"

Though not tested extensively (just installed), despite the appearance of these error messages python-mode sketches do seem to work...

**Comment by benfry** [comment]
It's detecting that you're running on Mac OS X. Are you sure you're using Oracle's Java?

**Comment by benfry** [comment]
No response, closing.
