### ISSUE TITLE
Resizing the PDE on Windows can make part of the interface unusable

### ISSUE THREAD

**Issue by jgall** [processing/processing#3184]
After working in Processing for a while, I've noticed that whenever you resize the bottom or the top of the frame all the way to the bottom or top of the screen and Windows automatically snaps the window to it's maximum vertical height, Processing duplicates the console, creating one static and useless one that takes up valuable screen real estate. 

The following screenshot was taken in Windows 7, but I have seen the same issue occur in Windows 8 and the 10 preview.
![processing glitch](https://cloud.githubusercontent.com/assets/743688/7023490/984b794a-dd03-11e4-964d-6ae0fcb173c5.png)

I'd be happy to try to work on a fix for this.

**Comment by benfry** [comment]
Please, by all means. The interface code in the current source is very different, but such a contribution is quite welcome.

**Comment by joshgiesbrecht** [comment]
Tested on Windows 7 with current build, bug no longer occurs for me.

**Comment by benfry** [comment]
Ok, closing.
