### ISSUE TITLE
 Error:incorrect classpath:lib

### ISSUE THREAD

**Issue by sureshparanjape** [processing/processing#3187]
I have opened processing 2.2.1 in C;\processing 2.2.1 folder. I tried day() sketch, provided in reference, by copying it to the sketch window of the software.I get error message "cannot parse error text:incorrect class path:lib".
I read one writing that by reinstalling this error disappear. Hence I deleted the folder created, de-fragemented the hard drive and reinstalled the software.The error continues. I have JavaFx2.1.0,Java(TM) 6 update 26 and Java(TM)7 update 4 on my Window XP. Do I need something more ?
Please help
sureshparanjae

**Comment by benfry** [comment]
This is a better question for the forum. This area is for bug reports.

**Comment by sureshparanjape** [comment]
Mr.benfry,
I might have found why the error message pops up.Should the sketch begin with "import  " a library into the sketch? The software that I downloaded is "processing-2.2.1-windows32.zip" and the folder in which unzipped files are stored is Processing 2.2.1.There is no libraries folder in this folder or in the folder C:\Documents and Settings\Suresh\My Documents\Processing\libraries has no files.The sketch located at file:///C:/processing-2.2.1/modes/java/reference/day_.html doesn't work in the processing window.
I am at lost which libraries should be included for a beginner like me, who wants just to learn how arduino and processing can exchange information.My immediate task is to modify the working digital clock sketch, which initializes the date and time manually, would initialize using PC current time and  date.
