### ISSUE TITLE
Issue in export application on processing v 1.5.1 with windows7  

### ISSUE THREAD

**Issue by fahadkalis** [processing/processing#3188]
I wrote a program and it is working properly on Processing V 1.5.1, but when I tried to Export it as Application (Standalone). I am getting an error below: Can you please guide me on how do I resolve it?

Could not copy source file: C:\Users\DANISH~1\AppData\Local\Temp\Project461640537993453470364temp\Project46.java

**Comment by benfry** [comment]
Please use the forum for questions.
