### ISSUE TITLE
Feature Request - Add a dialog to display all the shortcuts available in Processing

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3192]
Add a dialog to display all the shortcuts available in Processing.
This would be very helpful for all the users as they could see all the shortcuts at one place.
In future this could be modified to make the shortcuts customize-able so that user can edit the shortcuts for themselves. 
What are the views of others on this ?

**Comment by benfry** [comment]
This would be an advanced feature better suited for a contributed "Tool", not something that we'd include with the software.
