### ISSUE TITLE
API

### ISSUE THREAD

**Issue by FRadice1977** [processing/processing#3195]
If an API has security settings blocking the retrieval in Processing request, does anyone know of code I can use to override this? For example in this code the first 2 API's work and the third one does not. This could be because the security settings are different in the third API. 

Can I find Processing code to override this?

import proxml.*;

XMLInOut xmlInOut;

void setup(){
  size(600, 200);
  xmlInOut = new XMLInOut(this);
  xmlInOut.loadElement("http://api.wefeelfine.org:8080/ShowFeelings?display=xml&returnfields=feeling,postdate,sentence&limit=50"); 
xmlInOut.loadElement("http://api.wefeelfine.org:8080/ShowFeelings?display=xml&returnfields=imageid,feeling,sentence,posttime,postdate,posturl,gender,born,country,state,city,lat,lon,conditions&feeling=sad&city=tokyo&limit=500&extraimages=50"); 
 xmlInOut.loadElement("https://api.cabdirect.cab.semcs.net/select?q=dog");
}

void xmlEvent(proxml.XMLElement element){
  for(int i = 0; i < element.countChildren(); i++) {
    println(element.getChild(i).getAttribute("postdate"));
    println("\t"+element.getChild(i).getAttribute("sentence"));
  }
}

**Comment by spasmsaps** [comment]
You should ask programming questions on the forum: http://forum.processing.org/two/
This is the bug / issue tracker for the processing software.
Please close this issue on your way out.
