### ISSUE TITLE
Maxlink problem

### ISSUE THREAD

**Issue by jablonk** [processing/processing#3198]
For years I've been working with Maxlink, making many interactive setups between Processing and Max.

But now it suddenly stopped working. When I try to run a sketch that uses Maxlink, I get the error message below.
I haven't changed anything in the location of libraries etc.

It looks like there's a conflict between Max working in 32-bit mode and Processing in 64-bit Java. There seems to be no way anymore to let Processing run in 32-bit mode.

Does anybody have a suggestion?

initialized maxlink
java.lang.UnsatisfiedLinkError: com.cycling74.max.MaxSystem.doError([B)V
at com.cycling74.max.MaxSystem.doError(Native Method)
at com.cycling74.max.MaxSystem.error(MaxSystem.java)
at com.cycling74.net.MultiReceiver$MultiJoiner.run(MultiReceiver.java)
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.

**Comment by benfry** [comment]
Please use the forum for questions.

**Comment by jablonk** [comment]
Hi Ben,
Thanks for letting me know...I had already written on the forum but to no avail.
This is not just a discussion topic for me, but an urgent issue (I have several shows coming up where I need Processing/Maxlink/Max), that's why I chose to post on the 'issues' page.
I had no idea I was addressing you personally by doing that...sorry for having bothered you.
A helpful comment would have been very welcome though.
Best,
Jaap.
----Original Message----
From : notifications@github.com
Date : 17/04/2015 20:07
To : processing@noreply.github.com
Cc : jablonk@planet.nl
Subject : Re: [processing] Maxlink problem (#3198)
Closed #3198.
