### ISSUE TITLE
Use a better supported library than jEditSyntax

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3199]
jEdit is now 14 years old and is not maintained/updated. It would be very helpful if the code using jEdit can be replaced with something better maintained. RSyntaxArea is an alternative but other suggetions are welcome.  
This change might not get into Processing 3.x but will be very useful in future.

**Comment by benfry** [comment]
Updating the title—it's the jEdit "syntax" package, which was an offshoot for an embeddable editor component. jEdit itself is alive and well, but it's moved in another direction (into a full-featured programmer's editor).

**Comment by GKFX** [comment]
I thought we were maintaining it; is the lack of upstream help actually causing us problems?

**Comment by benfry** [comment]
We're maintaining it where possible/necessary, but it has many known bugs and the original authors have even disavowed it. @fjenett played with using RSyntaxArea as a possible replacement, but that work is unfinished. Of all the things I'm maintaining in this code, a text area is really a long ways from the category of "code that is important for us to write/control ourselves."

Edit: here's a link to Florian's work: https://github.com/fjenett/processing-rsyntaxtextarea-antlr4

**Comment by benfry** [comment]
Attempted this again for 4.x, and not moving forward with it. Long list of why is here: https://github.com/processing/processing4/blob/master/app/src/processing/app/syntax/README.md

Short version is that it's time better spent on [implementing a Language Server](https://github.com/processing/processing4/issues/117) and starting fresh with a new IDE.
