### ISSUE TITLE
Grey Visual Screen on Processing 

### ISSUE THREAD

**Issue by indiecindy** [processing/processing#3200]
Hi There,

I am running a motion sensor setup (Arduino MPU 6050) alongside Processing where I should see a plane-type object displayed on the Processing software, within a small box showing real-time movement of the sensor..

However, I am just seeing a grey box as shown below:
![elec error](https://cloud.githubusercontent.com/assets/12008428/7215896/2f96f388-e5e2-11e4-8e41-e24f9a0ce579.jpg)

Can anyone please help?

Thanks,

A very stressed final year design student!

**Comment by spasmsaps** [comment]
You should use the [forum](http://forum.processing.org/two/) for programming questions.
This area is for bug / issue tracking for the processing software only.
Please close this issue on your way out.
