### ISSUE TITLE
Heavy flickering for rectangle on top of image

### ISSUE THREAD

**Issue by federicobond** [processing/processing#3204]
This sketch is enough to trigger some heavy flickering for the rectangle on top of the image.

(OS X 10.10.3, latest Processing from repo).

````processing
PImage img = loadImage("PATH_TO_ANY_JPG_OR_PNG");

void setup() {
  size(500, 500);
}

void draw() {
  image(img, 0, 0, 500, 500);
  rect(200, 200, 200, 200);
}
````

**Comment by federicobond** [comment]
I looked into the graphics code for references to some sort of double-buffering to prevent tearing and saw some big changes in november, which removed all uses of `BufferStrategy`. My knowledge of low-level Java graphics is limited but seems to me, from the experiments I did, that either double-buffering was nuked at that point or some ad-hoc implementation attempted to replace it. I can take a look into this if you give me some pointers.

**Comment by benfry** [comment]
Just moved (to `PSurfaceAWT`), not removed. I'm actively working on it so I don't need help there, but there's plenty of other items tagged 'help' that could use it. Thanks!

**Comment by benfry** [comment]
Now fixed with https://github.com/processing/processing/commit/964f31adae335b5d1174a7d1c85cdbda27ea3b53

**Comment by federicobond** [comment]
Thanks! I can confirm there is no longer any flickering in my sketches.
