### ISSUE TITLE
Replace processing.mode.java.tweak.ColorSelector with processing.app.ColorChooser

### ISSUE THREAD

**Issue by benfry** [processing/processing#3209]
Some subclassing may still be required, but let's not have a near duplicate in the source (with the tweak mode version now behind what's in `processing.app.ColorChooser`).

**Comment by galsasson** [comment]
Also, TweakMode color selector is now broken since 1b9e12eb0718c335f71b18158ade6ddef542d95e
It fails in the function getMaximumSize.
frame.isResizable() returns true, even when I set my frame resizable to false. then it fails on super.getMaximumSize.
I tried messing around with it a bit but couldn't find the source.

**Comment by benfry** [comment]
@federicobond Wanna give me a hand here? Either applying the same changes as #2975, or better yet, a subclass that extends the original selector with only the necessary overrides?

**Comment by federicobond** [comment]
@benfry sure! I'll see what I can do. I managed to build a working tweak color selector from `1b9e12e`'s parent commit and some custom code fixes to see how it worked.

**Comment by benfry** [comment]
Awesome, thank you. Not looking for heavy reworking or refactoring (we have bigger issues to deal with), just a simple update based on the work you already did. Thanks!

**Comment by galsasson** [comment]
Thank you very much for the effort! Let me know if I can help.

**Comment by benfry** [comment]
Nevermind, now fixed. Had to get the build working again.

**Comment by shiffman** [comment]
ah, ok, was wondering why my build wasn't working, thought it was me.
