### ISSUE TITLE
Preferences window elements not sized correctly in 3.0a6

### ISSUE THREAD

**Issue by benfry** [processing/processing#3212]
Regressions introduced by https://github.com/processing/processing/pull/3191

![preferences-cropped](https://cloud.githubusercontent.com/assets/1623101/7332010/41c8fbd4-eaf9-11e4-929b-5a30bb7860e4.png)

On OS X, the window contents are not sized correctly. 

In addition, the "Editor font size" menu is enormous and runs the width of the window.

**Comment by benfry** [comment]
Fixed the bounds, but we're still definitely in the "ugly Java UI" category, which is why I didn't use a layout manager in the code in the first place. 

![prefs-mac](https://cloud.githubusercontent.com/assets/1623101/7333762/8d761ad0-eb49-11e4-9aec-32a218542675.png)

This should be a straightforward project to fix up, please help!

**Comment by benfry** [comment]
And for reference, this is what it looked like before the PR:

![screen shot 2015-04-25 at 12 52 51 pm](https://cloud.githubusercontent.com/assets/1623101/7333784/1c3286be-eb4a-11e4-9eb3-d1e5b24c0519.png)

Looks like we also lost the "MB" designation after the memory text field.

**Comment by benfry** [comment]
Hm, on further consideration, I wonder if it's time to have separate tabs for modes. Because of the PDE X integration, half of those items are specific to Java Mode.

**Comment by Akarshit** [comment]
Sorry, i was busy with some college project for my exams.  
This is not a issue that is happening on Ubuntu all the time, some time it does and some time the size is ok ( that's why it passed through my testing ). I will try to fix this today.

**Comment by benfry** [comment]
Thanks for looking into this. I've merged the changes but it looks like we still have some issues w/ the font drop-downs:

![font-boxes](https://cloud.githubusercontent.com/assets/1623101/7337339/9c63e83c-ebf4-11e4-8d7f-c38888adac32.png)

Let's just do setResizable(false) as well... Resizing the window doesn't do much for us.

**Comment by Akarshit** [comment]
I will hard-code these values for now.

**Comment by benfry** [comment]
They can't just use their default width and have extra empty space to their right (ala `BoxLayout` or `FlowLayout`)?

**Comment by Akarshit** [comment]
Actually they are working fine on Ubuntu, but i will try to do something to make them compatible with Mac. The main problem is i don't have access to a Mac to test.

**Comment by benfry** [comment]
Hm, wonder if we should switch to `BoxLayout`. Much simpler (to maintain as well), and it's not like we're not doing anything special. We had problems with MovieMaker and GroupLayout for a long time. Find/Replace seems to be working well, though.

**Comment by Akarshit** [comment]
I think it would a very simple fix if someone with Mac can play with it. I think only the parameters passed in https://github.com/processing/processing/blob/master/app/src/processing/app/PreferencesFrame.java#L602 and line 604 needs to be changed.

**Comment by benfry** [comment]
I'm looking through it but not familiar enough with GroupLayout to make it work. From [this](https://docs.oracle.com/javase/tutorial/uiswing/layout/group.html) it looks like the top-to-bottom list of items shouldn't be using a parallel group, because it'll force them all to the maximum width of the window.

**Comment by Akarshit** [comment]
I dont think that this is the problem, the problem is that the dropdown fields are taking way too much space by default ( on Mac ) and this is defining the width of the Pref Window

**Comment by benfry** [comment]
Well, one works... 

![screen shot 2015-04-26 at 5 42 21 pm](https://cloud.githubusercontent.com/assets/1623101/7339412/a5b12732-ec3b-11e4-8cb7-b15e5e3380eb.png)

**Comment by benfry** [comment]
Layout fixed for 3.0a7.

**Comment by Akarshit** [comment]
Oh nice!  
I will add the documentation for the complete code of Preference Window and would clean up old commented code as the implementation has changes totally.
