### ISSUE TITLE
Window size not passing with P2D and P3D

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3219]
When the method size in P3D or P2D  is not write in the void setup() the window display is 100x100 pix, may be can be the same problem than https://github.com/processing/processing/issues/3208
Procesing 306 on OSX 10.9
 ````
void setup() {
  parameter(500,500) ;
  // size(500,500,P3D) ; // ok
}

void parameter(int x, int y) {
  // size(x,y) ; // ok
  size(x,y,P2D) ; // problem display small window
  // size(x,y,P3D) ; // problem display small window
}
`````

**Comment by benfry** [comment]
`size()` must be the first thing in `setup()`, the reference couldn't be clearer:
https://processing.org/reference/size_.html

**Comment by StanLepunK** [comment]
plus, when the void parameter(int x, int y) are in an other tab. Processing return this error 

The sketchRenderer() method is not implemented.
Because you're not running from the PDE, add this to your code:
public String sketchRenderer() {
  return "processing.opengl.PGraphics2D";
}

**Comment by StanLepunK** [comment]
````size()```` must be the first thing in ````setup()````
It's very strange obligation, because If it's necessary to find the dimension from an external is not possible. That sound like a regression compares to Processing 305 ?

**Comment by benfry** [comment]
It's a strange requirement, but it hides an enormous amount of complexity that you don't want to deal with. Again, the reference couldn't be clearer on this point.
