### ISSUE TITLE
Error message changes from "function" to "method"

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3225]
In 3.0a7, Mac OS X 10.10, I'm noticing the following behavior.

```
size(200,200);
elipse(100,70,60,60); 
```

When I press run, I briefly see the error message `The function "elipse(int, int, int, int)" does not exist	` and a second later it changes to `The method "elipse(int, int, int, int)" does not exist`.  I believe we want to use the term "function" here?

@Manindra29 can you take a look at this?

**Comment by benfry** [comment]
It's part of the `PDE.properties` file (the language strings)

```
editor.status.undefined_method = The method methoddef does not exist
editor.status.empty_param = The method methoddef does not expect any parameters
editor.status.wrong_param = The method methoddef expects parameters like this:
```

@REAS will need to weigh in on the method vs function thing.

**Comment by Plastix** [comment]
I don't mean to barge in but in Java 'method' and 'function' can be used interchangeably. There might be some subtle differences if you go to different languages.

**Comment by shiffman** [comment]
Thanks @Plastix.  Yes, I agree they are interchangeable.  My sense is that "function" is the more colloquial language of use in Processing examples and tutorials rather than "method".  But I am not 100% sure.  @REAS do you agree?

**Comment by benfry** [comment]
We were very particular about it in the Processing book, which is why I was asking @REAS to weigh in... The general idea was that we used *method* when referring to something that was part of a class (that had been created by a user), but *function* when it wasn't. I agree that *function* is probably what we want to use here but wanted to verify w/ Casey so that we're all in sync.

**Comment by shiffman** [comment]
That makes perfect sense.  I suppose the error parser cannot distinguish easily between the two (and this likely comes up more often for beginners in the context of a mis-calling of a Processing core function) so I would err on the side of saying <em>function</em>.  But yes, I'll stop now and wait for Casey's thoughts!

**Comment by REAS** [comment]
In the world of Processing documentation, the word "function" is used like in C documentation for things like size() and line(). When a function is inside a class, it's called a method. Like with .toUpperCase(). This diverges from Java documentation, but it's how we've always done it.

**Comment by benfry** [comment]
Ok, swapped 'em for 3.0a8.
