### ISSUE TITLE
Pref Window Layout issues with JcomboBox and Ok button is not focussed of the Window is closed and then opened again.

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3231]
Sometimes on ubuntu the Preference Window looks like 
![bugwithpref](https://cloud.githubusercontent.com/assets/7762605/7413469/cea91420-ef69-11e4-88bb-7501d231964c.png)

**Comment by benfry** [comment]
Incorporated for 3.0a8, thanks.
