### ISSUE TITLE
Cmd-click behavior on function/variable is firing when cmd-click not pressed

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3242]
I'm experiencing some strange behavior in the PDE.  I've noticed that "command-clicking" a function or variable name jumps you directly to the function definition or variable declaration in the PDE.  This is a useful feature.

This may be my own personal faulty keyboarding, but I am experiencing this jump a lot at unwanted times. I use command-c and command-v quite often to copy/paste variable and function names.  I'm noticing that the jump is triggering from time to time and my copy/paste goes all crazy.

The answer may be for me to refine my behavior, but I'd thought I'd share / post in case anyone else experiences this.  @Manindra29 perhaps you could look at this with @joelmoniz during GSoC in case there's a small timing adjustment that can be made.

**Comment by shiffman** [comment]
I should add I'm on a Mac using 10.10 and 3.0a7.

**Comment by benfry** [comment]
Hm, that sounds like the mouse listener that handles jumping to declarations isn't set up properly and it may be firing at the wrong time (or isn't being prevented when it's a mouse/key event on something else).

**Comment by shiffman** [comment]
Also, related to this problem I've discovered on a mac that cntrl-click also jumps to a function declaration.  This is problematic when using cntrl-click as a right-click on Mac. For example:

![error](https://cloud.githubusercontent.com/assets/191758/7502378/936aa56c-f433-11e4-9f05-d6dc3afd13a3.png)

**Comment by Manindra29** [comment]
The jump to declaration is currently set to trigger when cmd or ctrl key is
pressed during mouse click. It should be changes to Cmd only for Mac. This
should be an easy fix. Will add it to my list.

Manindra Moharana
www.mkmoharana.com

**Comment by Manindra29** [comment]
That's a little odd. I'll take a look into the listener again.

Manindra Moharana
www.mkmoharana.com

**Comment by benfry** [comment]
I suspect this might be related to the cleanups I tried to do that are probably also causing   https://github.com/processing/processing/issues/3286. The whole setup for how listeners were piggybacking on each other to do the debugger (and then another set again for tweak mode!) was really problematic. We need to sort that out.

**Comment by Manindra29** [comment]
I've disabled Ctrl-Click jump to definition on Mac. It will only fire when Cmd is pressed on Mac. One way I can think of Cmd-C triggering jump to definition is if you may be accidentally touching your trackpad..? Because jump to definition is a mouse event only. If you are purely pressing keys, it shouldn't trigger ideally.

**Comment by benfry** [comment]
Hm, I wonder if right clicks are firing cmd-click on OS X (the reverse is true...)

**Comment by benfry** [comment]
@shiffman Can you confirm this is working, and if so, we'll close?

**Comment by benfry** [comment]
Looks like it's working in 3.0a8.
