### ISSUE TITLE
floor() and ceil() should take double rather than float as argument

### ISSUE THREAD

**Issue by teo1978** [processing/processing#3244]
Math.floor() takes a double as argument.
Processing's floor() and ceil() takes float. WHY?

Cons:
1. passing a double to floor() gives a compile error. (Note that, OTOH, If floor() expected a double, passing it a float wouldn't result in an error)
2. floor() has different behavior than Math.floor().
3 it forces you to use floats, so EITHER:
3.A you are encouraged to use floats pretty much everywhere, hence unnecessarily loosing precision, and
3.B when exporting to JavaScript Mode, you get unexpectedly different behavior (because in JS numbers are double precision)
OR
3.C you are obliged to cast doubles to floats prior to passing them to floor() and ceil(), which makes the code cumbersome, redundant, less readable, and just horrible. I also suspect edge cases may be found where you would get a different rounding in Java and JavaScript mode, but I may be wrong about this one.

Pros:
I can't see any.

So far I've stumbled upon floor() and ceil(), but I guess this might be a much broader issue in Processing.

**Comment by benfry** [comment]
We don't support double or use it anywhere in the reference. For people like you who know how to use doubles, you can use those alternative methods like `Math.floor()`.

**Comment by teo1978** [comment]
> We don't support double or use it anywhere in the reference

And why so?

**Comment by REAS** [comment]
It has been discussed at length in the past and I don't want to take the time to repeat it. The short answer is that it simplifies things for beginners and it doesn't affect experts because the Java stuff is there to be used. I am fixing the typo in the int() reference.

**Comment by teo1978** [comment]
> it doesn't affect experts because the Java stuff is there to be used

Actually it does affect the experts (and not only them) if they need to export a sketch via JavaScript and have the behavior be exactly the same, since numbers in JavaScript are double.

Anyway, I guess there's not even a remote chance you'll ever change this, so I just hope I can switch to P5*js as soon as possible and forget about the Processing/Processing.js nightmare.
