### ISSUE TITLE
int(double) is broken

### ISSUE THREAD

**Issue by teo1978** [processing/processing#3245]
Test code:
```
double x=2.34;
println(int(x));
```

Expected output:
> 2

Observed output (compile error):
> The method "parseInt" expects parameters like this: parseInt(boolean)

In case there is any doubt that this is not the expected behavior, 
https://processing.org/reference/intconvert_.html
> Description	Converts any value of a primitive data type (boolean, byte, char, color, DOUBLE, float, int, or long) to its integer representation.

(emphasys added)

**Comment by benfry** [comment]
That's a typo in the documentation. If it bothers you, you can file a bug for it in the processing-docs repo.
