### ISSUE TITLE
(PDE) The "Replace" button in Find should also find the next occurrence

### ISSUE THREAD

**Issue by teo1978** [processing/processing#3246]
In every text editor I have ever seen, when you do a search and replace, it works like this:
- you hit Find to find the next occurrence
- you hit Replace
=> it replaces that occurrences and it also finds the next one.
- then you can hit Replace again

In Processing's editor, Replace replaces the occurrence but doesn't find the next. You have to hit Find again.
A typical use case of using Find&Replace without using ReplaceAll is to "replace almost all occurrences in a supervised manner", that is, you hit Replace, Replace, Replace, oh wait I'lll skip this one, Replace, Replace, etc.
With Processing you have to hit Find, Replace, Find, Replace...

Besides being different from the widespread convention that prevails in every other editor on every platform, I can't see a single advantage that could justify not following the mainstream.

**Comment by benfry** [comment]
That's the "Find & Replace" button in the Find window.

**Comment by teo1978** [comment]
Oh, wow, I see.

1) You should name the button "Replace and Find", then.

2) Consider removing it and have the Replace button do the same. That's how EVERY other editor works and I don't see the advantage of having it different.
