### ISSUE TITLE
"Find and Replace" button should be labelled "Replace and Find"

### ISSUE THREAD

**Issue by teo1978** [processing/processing#3247]
The "Find and Replace" button in the Find window has a misleading label, because it indeeds replaces and finds, rather than find and replace. Its behavior is fine, it's just the label that is misleading.

If the Find window is going to be kept as unconventional as it is, it is important that the buttons are named properly, because it's already counterintuitive enough.

Note BTW that many editors have separate "Find" and "Find and Replace" windows, and in my opinion that's better. It's a bit "scary" when you just want to search and you see a Find&Replace window. You get the impression that you may too easily do a replace by mistake, even if that is not the case. For a long time I was too scared to type the keyword and press Enter, fearing that this would replace it with "", so I always clicked on the Find button just in case. Then I found out that precaution was not necessary, as Enter by default does a Find (which is the most reasonable behavior).

**Comment by benfry** [comment]
It was a typo introduced when that code was internationalized. It's now fixed.
