### ISSUE TITLE
Confirmation Dialog should have buttons of same size.

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3249]
The confimation dialog is as shown below on Ubuntu  
![confirmationdialogshortcut](https://cloud.githubusercontent.com/assets/7762605/7521570/797a9b7e-f50c-11e4-96a9-eff44d3ea36e.png)

**Comment by shmarsy** [comment]
helllo, 
I want to contribute in this issue.

**Comment by benfry** [comment]
Thanks, this is actually already resolved in Processing 4:

<img width="576" alt="issue4 3249 save changes" src="https://user-images.githubusercontent.com/1623101/192007917-19ddbe4c-d417-48a5-9b1b-d23e7a7a44ab.png">

But you should check out the issues in that repo if you'd like to contribute! https://github.com/processing/processing4/issues
