### ISSUE TITLE
Add shortcut for Cancel also in Confirmation Dialog 

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3250]
There is shortcut for Yes(Y) and No(N) buttons but not for the Cancel button, it would make sense to have the shortcuts for all of them.  
![confirmationdialogshortcut](https://cloud.githubusercontent.com/assets/7762605/7521635/12e556d2-f50d-11e4-948d-ffc06cd3e371.png)

**Comment by benfry** [comment]
I think this is another that we're getting from Swing...

**Comment by benfry** [comment]
Maybe more to the point, ESC works fine here.
