### ISSUE TITLE
change parseInt(string, int) to match Integer.parseInt(string,int) - i.e. second argument be the radix

### ISSUE THREAD

**Issue by teo1978** [processing/processing#3252]
Processing's current parseInt(String, int) uses the int parameter as a fallback value.
It would be much more useful to have it behave like Integer.parseInt(), so that the int parameter would be the radix/base. This way parseInt() could be used to parse a binary representation of an integer, which is a pretty common need (not to mention parse an integer with an arbitrary base).

A likely objection is that one can use Integer.parseInt(), but that's not portable to JavaScript mode, i.e. PJS.

Another possible objection is that this would break BC, but Processing has usually favoured improving the API over maintaining BC.

Writing user code from scratch for the fallback value is easy, while writing the code for parsing an integer with an arbitrary base is cumbersome. So a parseInt() whose second parameter is the base would be much more useful than the current one.

Also, this would make easier for Processing.js to match the Processing API, because the native JavaScript function parseInt() behaves like Java's Integer.parseInt(string,int), taking the second parameter as a radix. Actually, currently PJS's parseInt() does exactly that (so it's not compatible with the current Processing API for parseInt)

**Comment by benfry** [comment]
No. Since you know it exists, just use `Integer.parseInt()`.

You're completely missing the design of the Processing API. We're targeting the most-used things for the largest possible audience. We're not re-implementing everything that can be done in Java or even JavaScript. This is not a flaw, this is by design, for sake of simplicity. Trying to make it more complex and focusing on terms like "radix" is simply not a direction we're interested in, and more to the point, we explicitly avoid it.

**Comment by teo1978** [comment]
>You're completely missing the design of the Processing API. We're targeting the most-used things for the largest possible audience.

I was not missing that at all. I simply thought (and still think) that parsing a binary integer is as much among the "most used things" as parsing a hexadecimal number.

If there was a prefix for binary like there is for hex, i would agree that the need for the ability to specify an arbitrary radix is not as vital (though i am astonished that you consider the concept of radix as something too "complex" for the general audience)

**Comment by benfry** [comment]
Again, no. I made a decision a long time ago that an alternate value when parsing was far, far more useful than parsing with an arbitrary radix. I can also say with some degree of certainty that a vast majority of our audience has no idea what "radix" is. The complexity comes from adding that explanation and making that the default behavior.

If you want to deal with hex and binary, there are `hex()`, `unhex()`, `binary()`, and `unbinary()` methods for that.
