### ISSUE TITLE
String concatenation mistakes produce odd error messages

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3253]
This correct code:

```
void setup() {
  float w = random(20, 300);
  float x = random(w, width-w);
  float y = random(w/2, height-w/2);
  text(int(x) + "," + int(y),50,50);
}
```

produces strange error messages when I make a mistake in the `text`() line.

```
  text(int(x) + "," int(y),50,50); // Forgetting the second '+'
```
![screenshot 2015-05-08 10 59 52](https://cloud.githubusercontent.com/assets/191758/7534346/b35b4798-f571-11e4-9755-355223d9074b.png)

```
  text(int(x) + "," + int(y),50,50;  // Forgetting the last ')'
```

![screenshot 2015-05-08 11 01 44](https://cloud.githubusercontent.com/assets/191758/7534333/af5e5b44-f571-11e4-97c5-095ca0744bfa.png)

**Comment by benfry** [comment]
Fixed for 3.0a8.

**Comment by shiffman** [comment]
I can confirm this is mostly fixed.   I tried several combinations of errors and all worked except for one.  This line:
```
  text(int(x) + ","  int(y), 50, 50);  // missing + between "," and int(y)
```
produces:
```
Error on "PApplet"`
```
I believe it should say:

```
Error on "int(y)"
```

Also, during testing while adding and removing errors I received this stack trace a few times:


```
java.lang.Exception: setting notice to                                                                                                                                                                                                                
	at processing.app.Editor.statusNotice(Editor.java:2886)
	at processing.app.Editor.statusEmpty(Editor.java:2918)
	at processing.mode.java.JavaEditor.statusEmpty(JavaEditor.java:2444)
	at processing.app.Editor.prepareRun(Editor.java:2769)
	at processing.mode.java.JavaEditor.prepareRun(JavaEditor.java:1859)
	at processing.mode.java.JavaEditor$30.run(JavaEditor.java:1026)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by benfry** [comment]
The "Error on PApplet" is a much nastier problem—it's probably fooling the preprocessor and it's somewhere in @Manindra29's code. Go ahead and file a new one for that issue.

The "setting notice to" was a debug booger that I left in; now removed.
