### ISSUE TITLE
drawing in setup() not working P2D/P3D in 3.0a7

### ISSUE THREAD

**Issue by REAS** [processing/processing#3256]
For a test:
```
void setup() {
  size(400, 400, P3D);
  for (int x = 0; x < width; x+=4) {
    point(x, 200);
  }
}
```

**Comment by shiffman** [comment]
I was just about to post something similar!  I think the issue is drawing in `setup()` in `P2D`/`P2D`, see:

```
void setup() {
  size(400, 400, P3D);
  //for (int x = 0; x < width; x+=4) {
  //  point(x, 200);
  //}
}

void draw() {
  for (int x = 0; x < width; x+=4) {
    point(x, 200);
  }
  noLoop();
}
```

Also:

```
void setup() {
  size(400, 400, P2D);
  background(0);
  ellipse(200,200,100,100);
}


void draw() {
}

```
vs.

```
void setup() {
  size(400, 400, P2D);
}


void draw() {
  background(0);
  ellipse(200,200,100,100);
}
```

Am noticing some flickering (OS 10.10, retina) as well.  I see the stuff drawn in setup very very briefly and then it disappears.

**Comment by REAS** [comment]
Yes, you're right, I was doing more testing and found the same. You saved me the time in re-posting. Thanks.

**Comment by benfry** [comment]
Gentlemen, gentlemen... It's even listed in the "known issues" in the release notes: ;-)
https://github.com/processing/processing/issues/3163

**Comment by shiffman** [comment]
Oh yes of course I knew that. I was just playing along so @reas wouldn't feel embarrassed.

**Comment by benfry** [comment]
That's just good teamwork, sticking together.
