### ISSUE TITLE
Feature Request - Add a dedicated window to change Proxy settings.

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3258]
Add a new tab or something like that in the preference window so that user can set proxy at any time.
This could also be the start to breakdown Preference window into different tabs.

This would particularly be useful for those people whose proxy server allows connection for only a specific period of time and then they have to switch to another proxy as again and again going to preference.txt and changing it doesn't look cool. The window could be similar to the native window for changing proxies.

**Comment by benfry** [comment]
Too technical and obscure for our audience... We can cover this sort of thing with a manual change in the preferences.txt file. We work very hard to keep the Preferences window (and the rest of the UI) focused on the minimum number of options that the majority of users will actually use.
