### ISSUE TITLE
Simplify Debugger File Menu

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3267]
This came up over e-mail and I'm filing an issue to track.  The debugger file menu includes many unnecessary items.  We can probably lose everything under "list breakpoints."

![debuggermenu](https://cloud.githubusercontent.com/assets/191758/7561445/ee249e70-f7c3-11e4-9cfe-3db61612fcab.png)

"Step Into" and "Step out" are probably good to keep since these are conventions common to most debuggers, but they may be unclear to our audience (they are somewhat to me) and we'll likely need some good documentation which I can work on re: https://github.com/processing/processing-docs/issues/211.

**Comment by benfry** [comment]
All cleaned up.
