### ISSUE TITLE
Error message for incorrect function arguments is wonky

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3268]
In 3.0a7:

```
size(200,200);
ellipse(100,70,60); 
```

Error: 
```
The "ellipse" "ellipse"def expects parameters like this . . . 
```

Should say:
```
The function "ellipse" expects parameters like this . . . 
```

Not sure if this is related to already fixed #3225. (Not able to get current build to work, apologies for not being able to test there.)

![screenshot 2015-05-11 16 41 56](https://cloud.githubusercontent.com/assets/191758/7568783/a89395a8-f7fc-11e4-94ab-92ff5b09544c.png)

**Comment by benfry** [comment]
I probably goofed something with the replacements while trying to minimize some of that code. Should be an easy fix.

**Comment by benfry** [comment]
Fixed for 3.0a8. Had to do quite a bit of work on the simplifier, so please re-check any of those that may have broken in the process. It's also possible to edit more of that text directly inside `PDE.properties`. Before it was using its own substitution method.

**Comment by shiffman** [comment]
This fixed but it broke "the function ___ does not exist", i.e.

```
size(200, 200);
elipse(100,70,60,50); 
```

```
The function %s does not exist
```

![screenshot 2015-05-12 09 08 29](https://cloud.githubusercontent.com/assets/191758/7582535/82b9e0be-f886-11e4-95b1-b4c1c6176d7b.png)

**Comment by benfry** [comment]
Ok, checked in the fix for that. Go ahead and close this if it's working for you.

**Comment by shiffman** [comment]
I can confirm that both of these errors work properly.

**Comment by benfry** [comment]
Phew; progress!
