### ISSUE TITLE
Images are not included in Mac application after compile 

### ISSUE THREAD

**Issue by EnergySquid** [processing/processing#3270]
I have a program and in the program I need to display an image. For this I have a file in the home directory, but when I compile the program for Mac, it does not ever load. When I run the executable in Terminal it returns an error saying that it cannot find the image. [Here](https://github.com/EnergySquid/My-Life-As-A-Hobo)  is the link to the GitHub repository.

**Comment by benfry** [comment]
That's because you didn't add it to your sketch using "add to sketch" or manually put it in the 'data' folder yourself: https://processing.org/reference/loadImage_.html
