### ISSUE TITLE
Fullscreen window on second monitor without using present mode

### ISSUE THREAD

**Issue by jddamas** [processing/processing#3271]
On 3.0a5, latest Yosemite, if I draw a window on second monitor with the dimensions of the monitor size(displayWidth, displayHeight, P3D); the frame of the window is showing and a line(0,0,width,height) won't go from edge to edge. See picture below:

![screen shot 2015-05-12 at 00 04 34 2](https://cloud.githubusercontent.com/assets/11235075/7576967/36458dd2-f83b-11e4-8595-c03d27a6b64b.png)

**Comment by benfry** [comment]
Thanks for filing.

**Comment by jddamas** [comment]
No problem!

**Comment by codeanticode** [comment]
@jddamas do you still see this issue using the latest alpha (a8)?

**Comment by jddamas** [comment]
Actually a8 isn't drawing any window. I have this simple sketch:

void setup(){
  size(displayWidth, displayHeight, P3D);
}

void draw(){
  background(0);
  stroke(255);
  line(0, 0, width, height);
}

No window appears if I'm running sketches on display 2, nor if I change to display 1 on preferences. 

If I change to the default renderer, I get the following error message:


java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at sun.java2d.opengl.CGLGraphicsConfig.createCompatibleImage(CGLGraphicsConfig.java:204)
	at processing.core.PGraphicsJava2D.checkImage(PGraphicsJava2D.java:305)
	at processing.core.PGraphicsJava2D.beginDraw(PGraphicsJava2D.java:315)
	at processing.core.PApplet.handleDraw(PApplet.java:1931)
	at processing.core.PSurfaceAWT$13.render(PSurfaceAWT.java:1365)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:294)


I'm running a8 on the latest Yosemite update.
Cheers.

**Comment by benfry** [comment]
It's possible that `displayWidth` and `displayHeight` aren't being set properly in a8 because of other changes. 

What happens if you replace those with the actual values (i.e. `size(1920, 1080, P3D)`)

**Comment by jddamas** [comment]
Yes. That's the issue. I've replaced by size(1920, 1080, P3D) and it's working fine. Fullscreen, second monitor, no window frame.

**Comment by benfry** [comment]
So just to be clear, as long as `displayWidth` and `displayHeight` are fixed, the bug will be fixed?

**Comment by jddamas** [comment]
Yes. When I replace displayWidth and displayHeight by the monitor's resolution values, there are no bugs.

**Comment by benfry** [comment]
Ok, that's now filed here: https://github.com/processing/processing/issues/3295

**Comment by benfry** [comment]
This issue was fixed for 3.0a9, or if not, the fix will be in 3.0a10.
