### ISSUE TITLE
Changing default Sketchbook loses libraries, etc.

### ISSUE THREAD

**Issue by blueberrymusic** [processing/processing#3272]
Changing "Preferences/Sketchbook location" causes Processing to re-create the libraries, tools, and modes folders in the new directory (Version 2.2.1 on Mac OSX Yosemite). This can be inconvenient if one wishes to make the Desktop the default place for saving sketches, because then the Desktop gets cluttered with new, empty copies of these folders which must be re-populated and forever take up precious home screen real estate. I suggest that changing the Sketchbook directory should modify only that, and leave those other folders intact in their default location. Otherwise, the option should be more clearly labeled to indicate this broader result will occur, so one is not mystified by messages that things like libraries are suddenly not available. [Edit: I shouldn't have said "loses" in the title; "recreates" would have been more accurate. The old folders in fact still exist, which makes it even more perplexing when Processing says it can't find the libraries that are still in them!]

**Comment by benfry** [comment]
The libraries, modes, and tools are part of the sketchbook and need to be present. Making your Desktop folder the sketchbook directory sounds like a bad idea all around.
