### ISSUE TITLE
"processing-2.2.1-windows64" install does not work

### ISSUE THREAD

**Issue by jgdalal** [processing/processing#3277]
I download 2.2.1-windows64, extracted the files,and used processing.exe to install on my desktop running Windows64-professional. I see the Blue screen with title 'Processing 2' open and quickly vanish. This happened several times. The same happened with processing-1.5.1 except the title on the Blue screen was just 'Processing'.

I have no clue as to how to fix this issue. I have just started the online class, "Think. Create. Code." from edX which introduces the processing software based programming.

Thanks for any help with my problem. I do find the capabilities processing will offer me exciting and I want to use and learn more about processing that way.

**Comment by benfry** [comment]
Please use forum.processing.org for help with getting started.

**Comment by jgdalal** [comment]
Will do. Thanks.
