### ISSUE TITLE
lines are aliased in P3D with hint(ENABLE_STROKE_PERSPECTIVE)

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3281]
I try to have perspective with the strokeweight in P3D, but there is step on the line

``````
void setup() {
  size(300,300,P3D) ;
}

void draw() {
  bg() ;
 
  float z = sin(frameCount *.01) * width/2 ;
  
  strokeWeight(10) ;
  stroke(255) ;
  line(width/2,height/2,0,width *.6,height *.6,z) ;
  
  stroke(255,0,0) ;
  point(width/2,height/2,z) ;
  
  fill(255) ;
  text("z: " +z,width/2 +30,height/2,z) ;
  
  hint(ENABLE_STROKE_PERSPECTIVE) ;
  // smooth() ;
}

void bg() {
  pushMatrix() ;
  float canvasX = width*3 ;
  float canvasY = height*3 ;
  translate(-canvasX/2 +width/2,-canvasY/2 +height/2,-width -1) ;
  fill(0) ;
  rect(0,0,canvasX,canvasY) ;
  popMatrix() ;
}
```````````
I find this closed issue and the links inside are broken
https://github.com/processing/processing/issues/163

**Comment by StanLepunK** [comment]
I forgot, on Processing 3.07a / OSX 10.9

**Comment by codeanticode** [comment]
It is not very clear from your description what the problem is. Could you give us more details, or add a screenshot demonstrating the issue? Thanks!

**Comment by StanLepunK** [comment]
In this screenshot we can see a step on the line, may be that's be good to add "anti-aliasing" ?
Test on Processing 3.0a10 / iMac 2012 / OS 10.9
![capture d ecran 2015-07-16 a 21 29 42](https://cloud.githubusercontent.com/assets/3332269/8733074/ded345d0-2c01-11e5-8992-22735bb57ff9.png)

**Comment by JakubValtar** [comment]
Just use
```processing
void setup() {
  size(300,300,P3D) ;
  smooth(8); // enable antialiasing
}
```
