### ISSUE TITLE
mouseClicked() is not guaranteed to fire for every click if draw() is cpu-intensive

### ISSUE THREAD

**Issue by teo1978** [processing/processing#3283]
Test code:
```
void setup() {
  size(400,400);
  background(0);
}

void draw() {
  for (int i=0; i<10000000; i++) {
    // Just pretending to do some CPU-heavy stuff
  }
}

void mouseClicked() {
  strokeWeight(10);
  stroke(255);
  point(mouseX,mouseY);
  println("Mouse clicked at(?) "+mouseX+" "+mouseY);
}
```

How to reproduce: move the mouse around and click several times quickly

Expected: 
Given that draw() is consuming a lot of cpu time, There may be a delay between the time you click and the time the dot is actually drawn. However, exactly one dot should be drawn for each click.

Observed:
it happens pretty often that some clicks are "missed"

**Comment by teo1978** [comment]
I doubted the issue may be different than described, like the one in Processing.js https://github.com/processing-js/processing-js/issues/184, but then I added the println() call and it proves the issue here in Processing is as described in the title.

**Comment by benfry** [comment]
Nothing we can do about this if we don't get the mouse click from the OS.

**Comment by teo1978** [comment]
And are you positive that the issue is you're not getting the clicks from the OS?

I ask because Processing.js does not suffer from the same issue. It's possible, of course, that javascript inside a browser does get all the buffered clicks from the OS while java does not, but it seems a bit unlikely. In general, that's not something that one sees happen in Linux. That would have to be a Java issue, which again seems unlikely...
