### ISSUE TITLE
Merge glw code into the OpenGL library

### ISSUE THREAD

**Issue by benfry** [processing/processing#3284]
With the `PSurface` changes in place, it should no longer be necessary to have a separate glw library, we'll want to make it essentially the default.

**Comment by codeanticode** [comment]
I already removed the glw library from the source tree. Rendering through's JOGL native window is already in, the only piece of functionality in the glw library that is currently not part of the renderer is multiple windows. Do we need to merge that as well? If not, we should close this issue.

**Comment by benfry** [comment]
Nope, just the single window (or spanning multiple displays). From your response in the other bug report re: performance, it sounded like glw was necessary to avoid using `java.awt.Frame` (and the performance fixes that came with it) instead of what was built into the GL renderer. If that's not the case, then this can be closed.
