### ISSUE TITLE
"UDPTweakClient cannot be resolved to a type" when opening Processing

### ISSUE THREAD

**Issue by prisonerjohn** [processing/processing#3285]
I'm getting the error in the screenshot when trying to open Processing 3.0a7

![screen shot 2015-05-15 at 3 52 27 pm](https://cloud.githubusercontent.com/assets/119702/7660724/ab1aff20-fb1a-11e4-9c0b-13bf1ffb1b74.png)

I tried using a new sketchbook but I'm getting the same thing.
I'm on Mac OS X 10.10
Processing 3.0a5 works fine.

**Comment by benfry** [comment]
You need to uninstall PDE X. That's old code that's apparently conflicting with the current source.
