### ISSUE TITLE
Make FX2D key events work more like AWT key events

### ISSUE THREAD

**Issue by benfry** [processing/processing#3290]
If `FX2D` is to become the default renderer, we need to sort out its (very different) key handling from the [AWT handling](http://docs.oracle.com/javase/7/docs/api/java/awt/event/KeyEvent.html) that we had inside `PApplet` (now in `PSurfaceAWT`), otherwise we're gonna break a lot of code.

Note that JOGL no doubt handles keys very differently as well, so maybe this wasn't very consistent to begin with.

**Comment by JakubValtar** [comment]
Some work was done in #3686, not sure if it's "more" enough, though.

**Comment by benfry** [comment]
Let's call it "enough" and see how it goes.
