### ISSUE TITLE
size() method in Processing 308

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3291]
Congratulation for all the team for the new release !

I test the new method void setting() for the size.
The window opening close of the sketch that's nice. But it's not realy good to see the window at the top-left before for few frame before move close of the sketch. Is not big thing but sure is better if the window start immediatly to the finale position.

Plus I don't understand really the difference to write size(,) in void settings() or in void setup(), the both work on my computer. And when I write the method size(,) with any method that's work too.

````````
void truc() {
  size(400,400) ;
}
````````

**Comment by benfry** [comment]
If you have a bug report, please file it. This reads like commentary on the changes and isn't an "issue" and therefore not appropriate here.

**Comment by StanLepunK** [comment]
Like, I write. It's weird to see the window move from eeethe top-left to closeeeeec
