### ISSUE TITLE
Quitting P3D sketch throws an error

### ISSUE THREAD

**Issue by cdaein** [processing/processing#3293]
Processing 3.0a8, MacOSX Yosemite

Qutting P3D sketch with CMD+Q throws an error.

Sample code:
```
void setup() {
  size(400, 400, P3D);
}

void draw() {
  background(random(255));
}
```

Error message:
```
java.lang.ClassCastException: java.lang.ThreadDeath cannot be cast to java.lang.RuntimeException
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:272)
	at java.lang.Thread.run(Thread.java:745)
```

If I quit with the stop button on the PDE, there's no issue.

**Comment by codeanticode** [comment]
Actually, FPAnimator's setUncaughtExceptionHandler() is able to catch the ThreadDeath error, but not always... seems an upstream bug in JOGL.

**Comment by codeanticode** [comment]
Now filed in https://github.com/processing/processing/issues/3301

**Comment by benfry** [comment]
Let's leave this open since it's still broken, but hopefully #3301 will fix it.

**Comment by codeanticode** [comment]
it does fix it, thanks.
