### ISSUE TITLE
problem with where you write the line size(,)

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3294]
In P308, OSX 10.9.  
When you write the method size(,) in any method that's work, that's normal ?
And the window start at the top-left to after few millis to go close of the sketch.
``````
 void truc() {
      size(400,400) ;
}
`````

**Comment by StanLepunK** [comment]
In Processing 3.0a9 this code don't work
`````
void settings() {
  size(300,300) ;
}
void setup() {}
void draw() {}
`````

**Comment by StanLepunK** [comment]
related problem for the top-left window https://github.com/processing/processing/issues/3308

**Comment by benfry** [comment]
I don't understand what this is, but I suspect it's preprocessor issues that were sorted out in alpha 10. 

If not, please file a new bug with 1) a title that says what's broken, 2) a sketch that shows the problem, and 3) an explanation of why it's a problem.
