### ISSUE TITLE
Image overwritten upon quitting

### ISSUE THREAD

**Issue by cdaein** [processing/processing#3297]
Processing 3.0a8, MacOSX Yosemite

Sample code:
```java
void setup() {
  size(100, 100);
}

void draw() {
  background(random(255), 0, random(255));
}

void keyPressed() {
  save("image.png");
}
```

How to reproduce the error:

1. run the sketch
2. hit any key to save a png image.
3. watch the sketch folder on Finder and remember the color of the image.
4. quit the sketch by hitting CMD+Q
5. look at the image file again: the image is overwritten (now, in a different color)

Additional note:
When I tried the same thing in P3.0a7, the image was also overwritten, but this time, to an unreadable file.

**Comment by benfry** [comment]
That's a bug in your code: `keyPressed()` is called when you hit the command key to start typing cmd-Q.

**Comment by cdaein** [comment]
hah! didnt see this coming... thank you!
