### ISSUE TITLE
Exporting to Mac OS X does not work in Processing 2.2.1

### ISSUE THREAD

**Issue by matiasw** [processing/processing#3302]
There's an existing issue about this, #2533, but the discussion does not address the information in this forums post: http://forum.processing.org/two/discussion/5383/cannot-export-sketch-for-mac-with-processing-2-2-or-2-2-1 and the issue is closed as cantfix, on what I consider incomplete information.
As I wrote in the thread, I am on Linux x64.

**Comment by benfry** [comment]
We're not going back to fix 2.2.1. If something is broken, it's probably fixed in 3.0a8.

**Comment by matiasw** [comment]
Well, I'm unable to run Processing 3.0a8 on my machine. I get a "Processing 2" splash screen, and then a silent shutdown. 
With processing-java,  I tried `processing-java --sketch=/home/appas/sketchbook/sketch/ --export`, but was unable to get a working app for any platform with it. Note that (at least) the Linux app exported with 2.2.1 works, so I guess a new issue about this regression is in order - and has, in fact, been posted: #3303.
