### ISSUE TITLE
Window never shows with exported application on 64-bit Linux

### ISSUE THREAD

**Issue by matiasw** [processing/processing#3303]
I'm unable to run Processing 3.0a8 on my machine. I get a "Processing 2" splash screen, and then a silent shutdown. 
With processing-java,  I tried `processing-java --sketch=/home/appas/sketchbook/simulaatio15/ --export`, but was unable to get a working app for any platform with it. Note that (at least) the Linux app exported with 2.2.1 works. With 3.0a8, the --export option exports only for my current platform and arch (I suppose). The application does not work: it hangs on startup and has to be killed, whereupon it produces:
    Exception in thread "Animation Thread" java.lang.NullPointerException
     	at processing.core.PGraphicsJava2D.clearPixels(PGraphicsJava2D.java:2433)
     	at processing.core.PGraphicsJava2D.backgroundImpl(PGraphicsJava2D.java:2464)
     	at processing.core.PGraphics.backgroundFromCalc(PGraphics.java:7138)
     	at processing.core.PGraphics.background(PGraphics.java:7051)
     	at simulaatio15.setup(simulaatio15.java:37)
     	at processing.core.PApplet.handleDraw(PApplet.java:1944)
     	at processing.core.PSurfaceAWT$13.render(PSurfaceAWT.java:1365)
     	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:294)
    Killed

**Comment by benfry** [comment]
Regression from what? 3.0a7?

**Comment by matiasw** [comment]
From 3.0a5 (and 2.2.1, for that matter). I haven't tried with 3.0a7, but will do so soon.

**Comment by GKFX** [comment]
@matiasw Can you test a sketch like the following on your machine, to see if your bug is the same one I'm seeing? Correct images are saved to the sketch folder when exported Linux→Linux or Linux→Windows, but there's no visible window, so you have to kill it. Window displays fine in the PDE.
````java
void setup() {
  size(600, 600);
}

void draw() {
  fill(0, 50);
  rect(0, 0, width, height);
  fill(255);
  rect(width * (1.5 + sin(frameCount/30.0 + 2))/3, height * (1.5 + sin(frameCount/25.0))/3, 
    width * sq(sin(frameCount/20.0)) * 0.1 + 10, height * sq(cos(frameCount/20.0)) * 0.1 + 10);
  saveFrame();
}
````

**Comment by matiasw** [comment]
@GKFX I could export and run that sketch fine with Processing 3.0a5 on Debian Sid. I got a visible window, same as when running the pde from the IDE, and was able to exit from that with Esc/Stop button in the IDE.
Under 3.0a10, I get no window running from the IDE, but the sketch runs and the frames are saved fine, as you say. Exporting, the OS X option is grayed out. Running the exported Linux64 app, no window, but correct frames saved.

**Comment by benfry** [comment]
Need something that actually demonstrates the problem. I can't see your code, and I'm not sitting at your machine, so I have nothing to work from. What's a short sketch that reproduces the problem?

**Comment by matiasw** [comment]
I'm using the test sketch that's posted above. 
With 3.0a10, no window but the frames get saved fine. Same behavior in exported app and IDE. Under 3.0a9, the sketch works completely in both the IDE and as an exported app.

**Comment by benfry** [comment]
@matiasw the sketch posted by @GKFX works fine for me from the PDE and when exported as an application on Ubuntu 14.04 (64-bit) with the code in the current source (and presumably, alpha 10). 

Try exporting the Java VM along with your application and see if that fixes it.

**Comment by matiasw** [comment]
Same results: no window, frames are saved ok.

**Comment by benfry** [comment]
Fixed for a11.
