### ISSUE TITLE
Consider highlighting breakpoints more

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3307]
From #3093: "I would also personally like to see lines with breakpoints highlighted a bit more strongly (the `<>` feels quite subtle to me) but this is a more minor point and I defer to the wisdom of others with better design instincts."

Feel free to close if you disagree.

**Comment by benfry** [comment]
I agree. I think James may even have them more prominent in the comp, but we'll make it happen in either case.

Maybe an actual diamond shape instead of <> might help too.

**Comment by jamesjgrady** [comment]
I like the diamond - there is a diamond glyph in Source Code Pro, but it will need to be resized and the baseline and position shifted. Let me know if you have questions. 

![pde-sketch-r16-breakpoint](https://cloud.githubusercontent.com/assets/2600893/10055407/1dd8e7ac-6204-11e5-9d0d-25efd0f496dd.png)

**Comment by shiffman** [comment]
This looks great, thank you!

**Comment by benfry** [comment]
All set; along with the step arrow being a right-facing arrow instead of `->`
<img width="303" alt="screen shot 2015-09-24 at 5 50 31 am" src="https://cloud.githubusercontent.com/assets/1623101/10070417/53371e42-6280-11e5-9974-d9245779dcb5.png">

**Comment by REAS** [comment]
Wonderful.
