### ISSUE TITLE
draw() executes twice when noLoop() called in setup()

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3310]
Problem occurs in 3.0a7-3.0a9, does not occur in 3.0a5.

The behavior I expect is a single cycle through `draw()`.

```
void setup() {
  noLoop();
}

void draw() {
  println("draw(): " + frameCount);
}
```

![screenshot 2015-05-21 14 21 24](https://cloud.githubusercontent.com/assets/191758/7749337/aed8166c-ffc4-11e4-8f60-bba6bc526746.png)

**Comment by benfry** [comment]
Fixed for the next release (alpha 11? beta 1?)
