### ISSUE TITLE
map does not throw an error when producing NaN

### ISSUE THREAD

**Issue by liasomething** [processing/processing#3314]
example:
i have a Shape class and every Shape gets an id number.
i am mapping the id number to some speed variable like this.
float verticalSpeed = map(id, 0, maxShapeNum-1, 2, 5);

but when i only have 1 shape (maxShapeNum being 1) , then the mapping writes something like:
float verticalSpeed = map(id, 0,  0, 2, 5);
and this results in verticalSpeed  in being Nan which can easily be overlooked.

it would be great to get some error message when something like this happens... :)

**Comment by clankill3r** [comment]
I think it's up to you to deal with such a situation
for example:
 `map(id, 0, max(maxShapeNum-1, 1), 2, 5);`

**Comment by liasomething** [comment]
my point here was that it would just be _nice_ not to _have_ to deal with such a situation myself. :)

**Comment by benfry** [comment]
Hm, we don't throw errors for NaN anywhere in the API, so this would be a fairly huge shift to do it consistently. For instance, why would `map()` throw an error but `line()` or `vertex()` do not? (Answer: we probably would need to support all of them, and that's a lot of overhead.) As a rule, we only throw errors/halt the sketch for things that really mean the sketch can't continue. 

But... I can understand the interest, so I'll check with @shiffman @REAS and @codeanticode.

**Comment by shiffman** [comment]
Maybe this is less a question of dealing with `NaN` and more a question of how `map()` should deal with an invalid range.   If I understand correctly, the issue is:

```
float val = map(id, 0, 0, 2, 5); // returns NaN
```

What if we instead changed it to:

```
float val = map(id, 0, 0, 2, 5); // just returns id back? just always returns 2?
```

Maybe this is too much hocus-pocus and a bad idea.

In any case, I agree that as much as it would be nice I don't think we can add special error handling  for `NaN` everywhere in the API.  Adds to much overhead for somewhat of an edge case?  I am not confident in this opinion, just rattling off some thoughts.

**Comment by benfry** [comment]
Yeah, I'm not sure what the right behavior would be... In most cases we shouldn't halt a sketch based on a NaN value coming back. But I know this sort of thing can be really difficult to debug, so it'd be nice to have a way of warning users.

**Comment by shiffman** [comment]
We could detect an invalid range for `map()` and throw an error in the console like "vertex(x,y,z) not available with this renderer" kind of thing?  It's a wonky precedent (there are so many places we could do that) but `map()` is so incredibly useful and often introduced early on in a course/workshop context maybe it makes sense?

**Comment by benfry** [comment]
Would that be enough or do you think the audience that most needs to see that would also be most likely to ignore it unless it halted the sketch?

**Comment by shiffman** [comment]
It might not be enough, but at the moment I'm feeling like we should not halt any sketch that wouldn't "naturally" be halted by Java itself.  So maybe let's just try a warning and see?

**Comment by REAS** [comment]
There are so many things that can create issues with code; math errors, logic errors, infinite loops. I think NaN errors are one example of many. I see this as one part of a much larger conversation. To react specifically to the thread, I think a warning would be nice if it's possible, but I think I agree with Dan that if Java doesn't halt, Processing shouldn't too.

**Comment by liasomething** [comment]
i don't think processing necessarily needs to stop, but an error message would help very much i think.

if i would do something like this:
float myVarThatIThinkIsNotZero = 0;
float m = map(3, 0, myVarThatIThinkIsNotZero, 2, 5);
ellipse(100, m, 30, 30);
then i would probably ask myself for a very long time why my ellipse is not drawn.

would some error like "your code contains a (variable with a value of) NaN" or something like that be possible ?
without stopping processing...
this way it would be up to me to find the variable, but at least i would get a hint that something in my code is wrong...

**Comment by benfry** [comment]
Added the warning for 3.0 beta 3. This code: 
```
float myVarThatIThinkIsNotZero = 0;
float m = map(3, 0, myVarThatIThinkIsNotZero, 2, 5);
```
will produce the error message:
```
map(3, 0, 0, 2, 5) called, which returns NaN or infinity
```

**Comment by benfry** [comment]
On second thought, added separate checks so it will either say
```
map(3, 0, 0, 2, 5) called, which returns NaN (not a number)
```
or it would say `which returns infinity` if that's the case.

**Comment by liasomething** [comment]
lovely, thanks a lot !!!

**Comment by clankill3r** [comment]
@benfry Is it possible to output a stack trace as well when it happens?
I have the warning a few times in a 3d skecth but I don't even use the map method!!
