### ISSUE TITLE
Static mode broken with non-GL renderers on Linux

### ISSUE THREAD

**Issue by aengelke** [processing/processing#3315]
Using revision fbfb6a6 (HEAD), the static mode for Java2D and FX2D is broken on Linux. For this sketch:

```
size(400, 300);
background(100, 0, 0);
fill(0, 0, 255);
ellipse(width/2, height/2, 100, 100);
```

I get this output:

![image](https://cloud.githubusercontent.com/assets/4236689/7787494/11db8608-020f-11e5-85d0-3c6b6a66a150.png)

And for the new FX2D renderer:

![image](https://cloud.githubusercontent.com/assets/4236689/7787496/2973c028-020f-11e5-902f-6e93f90fd2b1.png)

The OpenGL renderers produce the expected result:

![image](https://cloud.githubusercontent.com/assets/4236689/7787498/45d20d10-020f-11e5-98fb-781176d471f6.png)

**Comment by benfry** [comment]
Hm, seems to be specific to Windows and Linux.

**Comment by joelmoniz** [comment]
Another test cases that causes this issue (from #3325):

Calling `size()` with only a `setup()` function, without `draw()`:
```
void setup() {
  size(320, 240);
  rect(20,20,50,50);
}
```

**Comment by benfry** [comment]
I believe I've got this working again for the next release (a11).

**Comment by aengelke** [comment]
Just tested: JAVA2D is working, FX2D isn't (but that's another issue: `size() cannot be used here...`).

**Comment by benfry** [comment]
FX2D isn't finished yet, and is completely unsupported.
