### ISSUE TITLE
sketch sometimes doesn't show with noLoop() on Linux

### ISSUE THREAD

**Issue by aengelke** [processing/processing#3316]
Sometimes, the sketch window doesn't show up. This only happens with the Java2D renderer. Using Fedora 21.

```
void setup() {
  size(400, 300, JAVA2D);
}
void draw() {
  background(255);
  noLoop();
}
```

**Comment by benfry** [comment]
Now fixed for a11.

**Comment by aengelke** [comment]
@benfry This is not fixed on the latest commit on Linux. The sketch still sometimes doesn't show.
