### ISSUE TITLE
PNG transparency broken with createGraphics() (regression in 3.0a9 from 3.0a5)

### ISSUE THREAD

**Issue by JukePlz** [processing/processing#3317]
On 3.05a loading a PNG with transparent pixels used to work but 3.09a the image displays with a black background on draw.

![trans](https://cloud.githubusercontent.com/assets/8497884/7789986/41fe11b6-024b-11e5-90f2-cec0279812ed.png)
Left: 3.09a   Right: 3.05a (correct behavior)

Test case:
```
PImage ball;
PGraphics pgBall;

void setup()
{
  size (50, 50);

  ball = loadImage("ball.png");

  pgBall = createGraphics(50, 50);
  pgBall.beginDraw();
  pgBall.image(ball, 0, 0);
  pgBall.endDraw();
}

void draw()
{
  image(pgBall, 0, 0);
}
```
png used.
![ball](https://cloud.githubusercontent.com/assets/8497884/7789998/f8244686-024b-11e5-82f9-a1f1b1fa94c9.png)

**Comment by benfry** [comment]
Fixed for 3.0 beta 1, same issue as https://github.com/processing/processing/issues/3378
