### ISSUE TITLE
Feature request: first-class Module system

### ISSUE THREAD

**Issue by isohedral** [processing/processing#3322]
In the winter I used Processing to teach introductory programming to non-computer science students. I think it was mostly a positive experience, but I discovered one or two opportunities for improvements that I think would help Processing to develop further as a teaching language.

Obviously, Processing's built-in library system is terrific. It makes it easy to discover new libraries that integrate with Processing, and to make use of those libraries within sketches. But the current library system is also too low-level -- it tends to expose the messy Java infrastructure of sketches, which is intended to be kept hidden from novice programmers. My main concern is that external libraries, as imported classes, break the illusion that one can avoid OO concepts:

 * Libraries like Fisica and ControlP5 require a "magic incantation" at initialization time, including the use of `this` in a context where the meaning of the keyword is entirely opaque. Similarly, one must pass `this` as an argument to the constructor of `processing.video.Capture`.
 * The Processing core appears to offer a number of "global functions", but no library can do the same, meaning that everything must work through classes. So libraries don't behave like the built-in environment, and students must learn the syntax for static method calls.
 * Worse yet, different libraries handle these issues in different ways. ControlP5 and Fisica look quite different at initialization time.
 * The meaning of the `import` directive is quite unclear, because really it's doing something at a level below Processing itself.

I think it would be great to define a standard for how libraries should interact with a Processing sketch, at least in Java mode. I suggest the following (modest, I think) changes to the Processing language, compilation, and runtime:

 * A new version of the `import` directive that targets officially supported libraries. A library would have an official one-word name, and that would be the only thing that needs to be imported within a sketch.  I'd write `import Fisica;`, `import ControlP5;`, `import Video;`, etc. The compiler would detect that I'm importing a built-in library and substitute in a list of Java-level import statements that are declared in some sort of metadata file associated with the library. If the library name isn't recognized, the directive defaults to a standard Java `import`. 
 * Standard libraries should come with an "initialization class" that includes a standardized library initialization entry point (a static method). When the `import` style above is used, the compiler inserts the necessary code (or reflection is used at runtime) to find that method and invoke it, passing a reference to the `PApplet` as an argument. Thus libraries would no longer need the sketch writer to pass in an explicit `this`.
 * Ideally, the initialization class, or a related class included in the library, would also be brought into the sketch using `import static`. That way, a library could also define a set of static methods and constants that would appear to be added to the sketch as global functions and variables.

Designing a programming language for teaching is hard, because concepts must be introduced in a very strict order, minimizing the places where I have to apologize for introducing syntax that I know students won't understand and that isn't motivated by anything they've seen. The ideas above don't make Processing more powerful, and are easily skipped by anybody with sufficient background in Java. But I think they could be a boon to students just beginning their journey with programming.

**Comment by benfry** [comment]
We're comfortable with the current library system striking an appropriate balance between exposing a degree of OOP principles (the need to pass `this`) and not breaking Java syntax by changing the behavior of the `import` statement. (We use import to suggest inclusion, but that doesn't break anything when someone moves to an IDE.) 

Because `import static` only works for static features, it tends to encourage bad library design, leading to bad assumptions about only one sketch object residing in memory at a time, causing libraries to fail in strange ways when that's not the correct assumption. As such, we don't provide extra `import static` methods. The majority of `PApplet` methods aren't static for this reason, and we don't use `import static` inside `processing.core` for that reason.

We spend an enormous amount of time on decisions about how things like this are handled, and while I've not had time to explain all these design decisions thoroughly in writing, suffice to say they aren't arbitrary or being developed by novices.

**Comment by isohedral** [comment]
It was never my intention to imply that the design decisions in Processing were in any way less than carefully considered by sophisticated programmers and language designers; I'm a huge fan of Processing, and you (both you personally and the entire team) have been doing amazing work on this project for many years now.  This was just a suggested language feature based on my personal experience of teaching Processing to beginning programmers. I'm grateful that you considered the idea, and I understand your reasons for rejecting it. It's been clear to me for a long time that you place high value on preserving the underlying Java syntax, and so a change like this one is dangerous.

The balance between OOP and imperative programming in Processing is a bit delicate. I had over 20 years of OO programming experience by the time I started using Processing, so it never bothered me when the OO scaffolding underneath a sketch poked through to the surface. But now, having taught this material to novices, I see that they can occasionally become confused when I must shatter the comfortable illusion that a sketch is a short imperative program. This confusion isn't crippling, and I can work around it; my proposed feature was merely the result of my rumination over how I might avoid it altogether.

Thanks.
