### ISSUE TITLE
Comments influence code (void settings() related I guess)

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3326]
If I run the code below (in 3.0.9a) I get:

iLLegalStateException: size() cannot be used here, see https://processing.org/reference/size_.html

If I remove the comment the sketch runs fine.
(same thing can be reproduced with a block comment).

```java
// size(600, 600);

void setup() {
  size(600, 600);

}

void draw() {
     
}
```

**Comment by benfry** [comment]
Should be sorted out for 3.0 alpha 10.

**Comment by fliperamma** [comment]
I'm with the same problem using 3.0.1

**Comment by clankill3r** [comment]
For me the problem is fixed using 3.0.1
OSX 10.11

**Comment by REAS** [comment]
Fixed for me too using 3.0.1. OS X 10.10.3

**Comment by fliperamma** [comment]
I've tried again today (in the same iMac and Processing version) and the problem is gone. I don't know what happened, but seems to be ok after restarting. 
Sorry for any inconvenience.

**Comment by jhandl** [comment]
I stumbled upon this problem without any discernible cause. Program was running fine, I moved an unrelated line to another tab and now it doesn't work. The size() call is the first thing in setup().
