### ISSUE TITLE
Partial window appearing on Retina Display (10.8.5) if "_2X" renderer is not selected with P2D and P3D

### ISSUE THREAD

**Issue by REAS** [processing/processing#3332]
```
void setup() {
  size(400, 400, P2D);
  fill(255, 0, 0);
}

void draw() {
  background(204);
  ellipse(200, 200, 100, 100);
}
```

![screen shot 2015-05-28 at 9 32 10 pm](https://cloud.githubusercontent.com/assets/677774/7876479/2def0980-0581-11e5-88a1-3131bbedc50b.png)

**Comment by codeanticode** [comment]
I tested opengl non-retina rendering on a retina machine and didn't observe this issue, but I was using 10.9.5. @REAS do you have access to a retina machine with newer OSX version to verify?

**Comment by REAS** [comment]
Yes, I have been testing with 10.8.5 and 10.10.x. What else can I look for?

**Comment by codeanticode** [comment]
fixed with https://github.com/processing/processing/commit/96d8859cb925d09b8789a0a960b43ccc20d5fc5e
