### ISSUE TITLE
How to manage images with "_2X" renderers

### ISSUE THREAD

**Issue by REAS** [processing/processing#3333]
When loading an image with a "_2X" renderer, should it be half the size as in the non "_2X" renderer or should it be half resolution, but the same size, as the rest of the sketch?

**Comment by clankill3r** [comment]
I found that sentence really hard.
Anyway, I would prefer that processing doesn't double every pixel to make the image larger.
Cause that would also make a blobscanner slower for example.

**Comment by benfry** [comment]
@REAS It should be half resolution, per other retina-oriented APIs on OS X and elsewhere. But with that, we probably need to add a way to actually load a real "retina" image (i.e. the nastily named `@2x` images you find on iOS/OS X). 

Right now, it can probably be done manually:
```
img.pixelFactor = 2;
img.pixelWidth = img.width * 2;
img.pixelHeight = img.height * 2;
```

**Comment by benfry** [comment]
Moving the discussion here: https://github.com/processing/processing/issues/3364
