### ISSUE TITLE
Unexpected error when start of run Processing

### ISSUE THREAD

**Issue by GEORGESLAVRA** [processing/processing#3341]
processing.app.SketchException: unexpected char: 'i'
	at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:386)
	at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:192

**Comment by benfry** [comment]
Need to see the code that's causing the problem, otherwise there's nothing here that we can use to even diagnose where there might be a bug.

**Comment by benfry** [comment]
This may be fixed in 3.0 alpha 10. If not, please re-file with an explanation of the problem and how to reproduce it.
