### ISSUE TITLE
launch Failed after building from source --windows

### ISSUE THREAD

**Issue by liquidzym** [processing/processing#3342]
not too sure what's happened here,it build successful,but it report some error message during the launching session,please to see the pic. i'm using jdk 1.8 64bit,windows 8,1

cheers
![p5_build](https://cloud.githubusercontent.com/assets/51957/7928100/d69c2628-091c-11e5-969b-0774fabc800f.png)

**Comment by joelmoniz** [comment]
Are you using a contributed mode when using processing? I've seen this
error pop up when using contributed modes because they aren't fully
compatible with 3.0 yet.

**Comment by liquidzym** [comment]
i thought about this,but after empty the contributed mode such as JavaScriptMode, still got same result

**Comment by aengelke** [comment]
These errors typically come from an unclean build. You could try `ant clean` to force a recompilation of all files.

**Comment by liquidzym** [comment]
thxs,that's works!
