### ISSUE TITLE
textFont() will override textSize()

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3351]
I'm not sure if this is a bug or a something to add to `textSize()` documentation, but `textSize()` will not be maintained if a call to `textFont()` is made afterwards, i.e.

```
PFont f1 = createFont("Arial", 26);
PFont f2 = createFont("Georgia", 26);
background(0);
fill(255);
textSize(26); 
textFont(f1);
text("WORD", 10, 50); 
textSize(14);
textFont(f2);
text("WORD", 10, 70);
```

I realize for the example above is somewhat nonsensical and should be written `textFont(f2, 14)` or `createFont("Georgia", 14);`.   However, I ran into this with a more complex scenario where there was a more legitimate reason for `textSize()` to be separated from `textFont()`.

Is this a bug or a documentation question?

The output of above:
![screenshot 2015-06-04 09 04 20](https://cloud.githubusercontent.com/assets/191758/7979639/d58fb538-0a98-11e5-8af0-9a57d00ff052.png)
vs what I expected:
![screenshot 2015-06-04 09 04 33](https://cloud.githubusercontent.com/assets/191758/7979640/d5921f44-0a98-11e5-933d-1533726db555.png)

**Comment by benfry** [comment]
If it's not in the documentation, it's a docs problem. The idea is that most of the time, you're doing `loadFont()` which has a specific size associated, or `createFont()` with a specific size, so rather than always having to re-set to the natural size of the font, changing the font also sets the size.

**Comment by shiffman** [comment]
Thanks, that's what I started thinking after I posted the report. I'll file something in processing-docs to consider if we need to adjust documentation.
