### ISSUE TITLE
contribs listed multiple times (because they're listed multiple times in contribs.txt)

### ISSUE THREAD

**Issue by benfry** [processing/processing#3353]
Help me @prisonerjohn, you're my only hope.

**Comment by benfry** [comment]
Quickly filing this per discussion; something for @Akarshit and @prisonerjohn to sort out.

**Comment by prisonerjohn** [comment]
Some more information on this:

In the current setup, if a contribution is listed in more than one category, it is duplicated in the contribs.txt file with two different ID numbers. See an example of this [here](https://github.com/processing/processing-docs/blob/master/contrib_generate/sources.conf#L162) and [here](https://github.com/processing/processing-docs/blob/master/contrib_generate/sources.conf#L59). This is bad for many reasons (hard to maintain, duplicated entries, etc.) so maybe now is a good time to fix it.

I propose formatting entries in `contribs.txt` with a comma-separated list of categories. For example:
```
library
category=Geometry,Typography
minRevision=0
authorList=[Ricard Marxer](http://www.ricardmarxer.com/)
name=Geomerative
maxRevision=0
sentence=Extends 2D geometry operations to facilitate generative geometry. Includes a TrueType font interpreter.
url=http://www.ricardmarxer.com/geomerative
prettyVersion=
paragraph=This library exposes the shapes (such as vector drawings or typographies) in a more approchable way. Geomerative makes it easy to access the paths, the handles and the points, making it easy to develop generative typography and geometry pieces in Processing.
version=40
download=http://www.ricardmarxer.com/geomerative/geomerative.zip
id=038
```
Is this something you would be able to work with in the PDE to assign a single contribution entry to many categories?

**Comment by alignedleft** [comment]
This idea sounds great to me. @Akarshit is this something you could help us implement while you are working on the CM?

**Comment by joelmoniz** [comment]
I think this might already be supported by the CM, since when it [parses the `category` field](https://github.com/processing/processing/blob/master/app/src/processing/app/contrib/Contribution.java#L247), it splits it up based on commas, and returns a List of Strings of valid categories?

**Comment by prisonerjohn** [comment]
Ok, that's great! I'll make the changes on my end and report back.

**Comment by prisonerjohn** [comment]
I made the changes to the build_listings script (and updated the field names). An entry now looks something like this:
```
library
minRevision=0
name=Hermes
maxRevision=0
sentence=Experimental game framework and engine for rapid prototyping of games and simulations.
url=http://rdlester.github.com/hermes
prettyVersion=2.0
paragraph=Leverges the strengths of Object-Oriented Design and the ease of Processing to make it easy to bring game mechanics to life. Built-in OSC support makes it easy to enable communication between your games and external data sources. Also includes animation/sprite and physics libraries that can be used outside the framework.
version=5
authors=Ryan Lester, Chris Novello, Sam Eilertsen, and Jen Kovnats
download=http://rdlester.github.com/hermes/downloads/hermes.zip
id=083
categories=Geometry,Compilation,Simulation,Animation
```

I'm not sure what I need to do to get this updated list at http://processing.org/contrib_generate/contribs.txt, paging @REAS @alignedleft

**Comment by REAS** [comment]
There's a "Pull Latest Changes" in Generate, that updates the entire site from GitHub.

**Comment by alignedleft** [comment]
@prisonerjohn Let me know if you want me to update this on the main site (or just beta).

**Comment by prisonerjohn** [comment]
OK, this is ready on my end. 
I built and ran Processing locally and used http://beta.processing.org/contrib_generate/contribs.txt to get the list, it seems to be working fine.

**Comment by alignedleft** [comment]
@prisonerjohn should we close this issue then? Do you want/need me to regenerate contribs.txt on the live site?

**Comment by prisonerjohn** [comment]
Yes and yes, unless someone wants to have a second look first.

**Comment by alignedleft** [comment]
At a glance, this looks OK to me. @Akarshit could you double-check this fix? (I think just click the URL above and scan for duplicates.)

Once we have another set of eyes on it, I can update the live site and close this issue. Thanks!

**Comment by Akarshit** [comment]
@alignedleft ya sure

**Comment by alignedleft** [comment]
Thanks, @Akarshit and @prisonerjohn.

I've updated the live site and tested 2.2.1 and the current 3.0a build, and it looks OK to me. If you see any problems, please log a new issue.
