### ISSUE TITLE
GNU is missing from Export frame.

### ISSUE THREAD

**Issue by mtsio** [processing/processing#3355]
In Export Options frame there is the option of exporting to 'Linux'. I think the correct term is GNU/Linux because Linux is only the kernel. The main reason though for changing it is to give credit to the GNU project for it's contribution.

**Comment by alignedleft** [comment]
Good idea, but adding GNU goes against the goal of minimizing jargon and unknown terminology as much as possible (in order to remain accessible to beginners).

**Comment by REAS** [comment]
Ben and I looked at this last night. I'm not sure what his opinion is. I am in favor or adding the GNU. We have it that way (GNU/Linux) on the homepage.

**Comment by mtsio** [comment]
I think the only place is that frame, so it isn't much of a change.
Also, the "Linux" is not very different from "GNU/Linux". If beginners
know already Linux it won't cause them any trouble.

Scott Murray:

**Comment by benfry** [comment]
“Linux” is the short name that's appropriate here as @alignedleft points out. We use GNU/Linux in some others where the length makes sense, but I'd like to avoid the software becoming a place for a holy war over naming, where we sacrifice clarity for ideology.
