### ISSUE TITLE
smooth(), noSmooth() behavior

### ISSUE THREAD

**Issue by benfry** [processing/processing#3357]
Dearest @REAS, @shiffman, and @codeanticode, 

I'm working through the `smooth()` changes described [here](https://github.com/processing/processing-docs/issues/251). 

It's a little gross because if it's the primary drawing surface, everything happens in `PApplet`, but if offscreen, it needs to happen in `PGraphics`. This means that both need a `smooth` variable that is set to 0 (no smoothing), 1 (default for the renderer), 2+ (specified by the user, behavior depends on the renderer). 

When the primary surface is created, the setting is retrieved from the sketch via `sketchSmooth()` (in line with `sketchWidth()` and others, which are now the public accessors for settings like this). When an offscreen surface is created, it's queried the same way, but can be overridden by calling `g.noSmooth()` (or whichever of the three) before the first `beginDraw()`. 

Essentially the behavior is very different, and I feel like it makes the internals a little confusing. Especially because in the past, the `PGraphics` version was just called by `PApplet`. But the tradeoff is:

1. We could change how this works, and add a `setSmooth()` method (that takes, 0, 1, 2+) to `PGraphics` to handle the `createGraphics()` usage. This would make it more apparent that things are a little different. 

2. We could do this as-is, which would be less confusing for people updating their code. 

3. We could add more parameters to `createGraphics()`, but that seems like a mess. We already have several `createGraphics()` variants (with/without renderer, with/without filename) and this would multiply things and be awkward: 
```
createGraphics(500, 300, "TiffFileRenderer", "output.tif", NO_SMOOTH);  // this sucks
createGraphics(500, 300, "TiffFileRenderer", "output.tif", "smooth=0");  // this is yuck
```

I'm moving forward with the second option (fewer changes to the behavior, but makes the internals a little awkward), but was hoping you three could confirm or shoot holes in this (or that I'd figure it out by having to write it out...) 

@codeanticode `boolean smooth` and `int quality` in `PGraphics` are being replaced by `int smooth`, but I'm open to better ideas here.

**Comment by REAS** [comment]
I think the good news with all scenarios is that if you're not changing the smooth() defaults, the code will remain as it has been since the default change to smooth() with 2.0. I'm working through the rest.

**Comment by shiffman** [comment]
I am not entirely sure I follow completely. . is the following understanding correct?

This used to be valid:

```
void setup() {
  size(200, 200);
  PGraphics canvas = createGraphics(200, 200);
  canvas.beginDraw();
  canvas.smooth();  // or noSmooth() or smooth(4)
  canvas.rect(0, 0, 100, 100);
  canvas.endDraw();
  image(canvas, 0, 0);
}
```

But now it has to be:

```
void setup() {
  size(200, 200);
  PGraphics canvas = createGraphics(200, 200);
  canvas.smooth();  // any smooth()/noSmooth() stuff now has to be before beginDraw()!
  canvas.beginDraw();
  canvas.rect(0, 0, 100, 100);
  canvas.endDraw();
  image(canvas, 0, 0);
}
```

But this makes it very awkward for you to implement behind the scenes so you are thinking of changing it?   

Or you cannot do any of the options above anymore all b/c you need to know what the smoothing should be the moment `createGraphics()` is called?

**Comment by shiffman** [comment]
Oh oh, sorry I should have clicked through your link where more is explained.   I think you are right, to keep as is and now that `smooth()` is something more of a global thing that cannot be changed through out a sketch it makes sense that `createGraphics()` would inherit it.   If there's some workaround for those who need a different smoothness for `PGraphics` vs `PSurface` that might be nice, but I think that's something of an edge case and doesn't need to be featured prominently in the documentation.

**Comment by benfry** [comment]
Thanks guys... I'll continue in this vein and see how it goes.

@codeanticode I'm also going to rename the `primarySurface` variable to `primaryGraphics` since that's what it is, to avoid confusion because we have something else actually called "surface" in the API now.

**Comment by codeanticode** [comment]
jumping late into the discussion... @benfry I agree with the direction you are taking, constraining the use of smooth/noSmooth to a single call before beginDraw() seems like a good solution to me.

However, just want to make one observation: the smooth() used to correspond to smooth(2), right? In fact,  a quality level of 1 in openGL represents the aliased setting with 1 sample, in other words no smoothing. Should the OpenGL renderer set 2 samples for smooth(1)?

**Comment by benfry** [comment]
Yes, that's correct, `smooth(1)` should be the appropriate default for the renderer... in Java2D, the default (bicubic) is 4, though you can drop it to 2 (bilinear) if you want. Even though OpenGL technically would see `smooth(1)` as `noSmooth()`, that's just too weird to foist on people, so you should override that.

**Comment by REAS** [comment]
Please check this out:
https://beta.processing.org/reference/smooth_.html

I think that I should mention the defaults, to confirm, that's `smooth(4)` for the default and JAVA2D_2X and `smooth(2)` for the OpenGL renderers. Or are you saying `smooth(1)` for OpenGL should be "2X" under the hood?

**Comment by codeanticode** [comment]
Ok, but now the current smooth levels -0, 1, 2, 4, 8- don't make much sense. For example in OpenGL:

0 -> no smooth
1 -> default smoothing (2 samples)
2 -> 4 samples (?)
...

with some hardware supporting up to 16 samples, or even 32. Shouldn't be simply consecutive 0, 1, 2, 3, 4... with the appropriate interpretation depending on the renderer?

**Comment by benfry** [comment]
The only smoothing levels that users will see is 2, 4, or 8 (or whatever the renderer uses). 0 and 1 are only used internally. 

The numbers are specific to the renderer, so if you want 2 to mean "2x" and 4 to mean "4x", for OpenGL, then great. For Java2D, it's bilinear or bicubic, so those might be 2 and 3. There's no 2x or 4x or 8x, so it has to be renderer-specific, so consecutive levels really don't make any sense.

**Comment by benfry** [comment]
@REAS please leave `smooth(0)` out of the reference. It's not useful and confuses things further. Also, you should mention that it's dependent on your machine's graphics capabilities (the card and the drivers) whether it supports 4x or 8x or whatever. Many won't be able to do that.

Should we make `smooth(2)` bilinear and `smooth(3)` bicubic for Java2D? (And therefore, `smooth(3)` will be the default.) Numbers-wise that seems to make more sense (linear = 2d degree, cubic = 3rd degree).

**Comment by benfry** [comment]
Alright, this is wrapped... `smooth(3)` is bicubic in Java2D (the default) and `smooth(2)` sets it lower to bilinear. On OpenGL, the smoothing level refers to the oversampling/multisampling/fsaa or whatever it's using these days, so it'll be 2 (the default), 4, 8, 16 depending on how your card works. 

But for 95% of users (and 99.99% of the time), the `smooth()` command can be all but ignored since it's on by default. The other 5% might want `noSmooth()` or `smooth(N)` sometime.

**Comment by REAS** [comment]
I will referencify these decisions.
