### ISSUE TITLE
implement "Welcome" screen for Processing 3

### ISSUE THREAD

**Issue by benfry** [processing/processing#3358]
Per notes from @alignedleft: 

- a summary of what’s new, plus a link to GitHub wiki page with details on “what’s new in 3”
- a warning that some Processing 2 sketches may not be compatible
- if a v2 sketchbook already exists, show a prompt to choose either creating a new Processing 3 sketch folder or use the existing v2 one, plus a link to GitHub wiki page with details
- a box which is checked by default (“show this welcome each time”), but can be unchecked
- a button to dismiss the welcome screen (e.g., “get started”)

**Comment by REAS** [comment]
@benfry Is this something you have have from here, or should, James, @alignedleft, or myself work up a UI diagram?

**Comment by benfry** [comment]
I'm all set, thanks.

**Comment by alignedleft** [comment]
I am working on wireframes for this.

**Comment by benfry** [comment]
No need to—it'll just be a web page to open up a window with a "get started" at the bottom. Y'all can go to town on the web page once it's all set.

**Comment by alignedleft** [comment]
@benfry I'm not sure I understand how this will work as a web page, but here are two concepts for the in-app welcome screen.

![screen shot 2015-06-11 at 11 13 41 am](https://cloud.githubusercontent.com/assets/1034002/8114659/fd535588-102a-11e5-8c56-1639e3ade067.png)

![screen shot 2015-06-11 at 11 14 02 am](https://cloud.githubusercontent.com/assets/1034002/8114665/00f8d65e-102b-11e5-8898-493ceb478a62.png)

**Comment by alignedleft** [comment]
Here are updated concepts with revised wording, after some discussion with @REAS:

![p3 welcome screen concept 1](https://cloud.githubusercontent.com/assets/1034002/8210230/e28c8180-14c5-11e5-807b-3c0ea5965341.png)
![p3 welcome screen concept 2](https://cloud.githubusercontent.com/assets/1034002/8210234/e5b6c186-14c5-11e5-828f-4a2e94ec3172.png)

**Comment by REAS** [comment]
I think they are great! What is the links?

Read about what's new in 3.0 -- [https://raw.githubusercontent.com/processing/processing/master/build/shared/revisions.txt] or is this also a new document?
What changed? -- https://github.com/processing/processing/wiki/Changes [Needs to be updated.]
"Read more about it" -- is this something new?

**Comment by alignedleft** [comment]
@benfry insinuated the links would point to new wiki pages, specific to 3.0.  I think these pages could be different from revisions.txt (less detailed) and also not the "something used to work and now it doesn't" page, although we could link to both of those.  I think we need two new wiki pages:

- What's new in 3.0 (high-level, not the nitty gritty of revisions.txt)
- Sketchbooks in 3.0 (explains options, trade-offs, ability to have 2 separate sketchbooks)

**Comment by REAS** [comment]
OK, agreed. I think "What changed?" should be the updated Wiki page. The other two pages will be entirely new. So, I think you or I should write them and Ben will do a technical review. Would you like to or shall I?

**Comment by benfry** [comment]
Yeah, revisions.txt is only for per-release changes—we'd never say "what's new? read these 1,533 lines to see what might have changed!" (actual count of lines since 2.2.1)

I think we update the [changes wiki page](https://github.com/processing/processing/wiki/Changes) to include what's in 3.0, the way we have with other releases. Or we can make a new page for 3.0 (or replace that page with only the 3.0 information), and have a link at the bottom that says "for 2.x and earlier, see here" and link to the current version of the page (we still have people updating code from 1.x). The intent for that page is to have some high level introduction and the top, and the syntax changes below. 

One argument for moving that page to the reference is that it'd be available offline and in the download, making it easier for us to link to it from error messages in the PDE. The argument against is that usually it's me writing and making the updates to it, and I only barely have my grubby mitts on the processing-docs repo (and don't control when it's updated for a release).

**Comment by alignedleft** [comment]
@REAS I'll take an initial stab at writing the wiki pages.

@benfry given that, it sounds much easier to use the wiki (vs. internal reference).  Let's not add anything else to your plate right now.

**Comment by alignedleft** [comment]
I started writing pages on [Changes for 3.0](https://github.com/processing/processing/wiki/Changes-in-3.0) and [Multiple Sketchbooks](https://github.com/processing/processing/wiki/Multiple-Sketchbooks).

**Comment by benfry** [comment]
Thanks, I've added those to the GUI.

**Comment by alignedleft** [comment]
@benfry how can I trigger the new welcome screen, to take a look at it?

**Comment by benfry** [comment]
It's in `build/shared/lib/welcome/index.html`. It'll just be that page, but opened to 400px wide (or so). 

Are you up and running with Processing inside Eclipse? If so, it's possible to run from there, but I'm guessing you're not?

**Comment by alignedleft** [comment]
@benfry thanks! No, I'm not set up with Eclipse. (Though I've heard such nice things about getting it set up.) I can install it if that helps. Can I help style this with CSS, images, anything? I don't understand how it will be rendered from within the Java app.

**Comment by benfry** [comment]
Ok, just posted an updated version so that you can debug. (You're at least building from Git on the command line, right?)

The screen is now (temporarily?) available as an item under the Help menu. Nobody will ever look there, so it's a safe place to debug this. Ha ha ha. Ahem.

When you select it, it reads the copy of the HTML from `build/shared/lib/welcome/index.html` and shows the window. You should edit that HTML file to your heart's content, adding any images or css to that `welcome` folder (or just putting the CSS inline). It [looks like](https://docs.oracle.com/javase/8/docs/api/javax/swing/text/html/HTMLEditorKit.html) it supports HTML 3.2 with some additions. Which will be *sweet*, but can't be worse than the ugliness if I were to create it with Java components.

On the code side, it'll just read the state of the form elements when someone hits "get started", and make the appropriate changes.

**Comment by benfry** [comment]
@alignedleft Is this something you'll be able to take care of in the next few days? I'd like to turn this on for alpha 11 (since it'd be good to test it before the beta 1), but I don't think we should until it's had some design love.

**Comment by alignedleft** [comment]
Thanks! Makes sense, and yes, I can take care of this in the next few days, and *yes* I am using git and the command line, thank you very much. :)

**Comment by alignedleft** [comment]
@benfry This is so cool! I can write HTML and CSS, then just reopen the welcome screen.  It's like making a real web page! :)

Here's the current state so far. Can you point me toward the new P3 logo file? Then I want to see if I can get the font and images correct.

![screen shot 2015-07-05 at 9 35 53 pm](https://cloud.githubusercontent.com/assets/1034002/8515760/1788abc4-235e-11e5-8e1a-e3fa97e448c1.png)

**Comment by benfry** [comment]
From the welcome folder, the icon/logo will be `../icons-pde-XXXX.png` depending on what you're looking for.

**Comment by benfry** [comment]
Now implemented. Though we need to write text for the non-sketchbook version.

**Comment by alignedleft** [comment]
@benfry for what it's worth, I tried:

- Using CSS to set the font-family to 'Source Sans Pro', but to no effect. Perhaps this HTML renderer doesn't support web fonts? (Likely.)
- Adding a reference to the P3 icon, but it fails to load (see screenshot).

![screen shot 2015-07-18 at 4 55 43 pm](https://cloud.githubusercontent.com/assets/1034002/8763997/46de6c46-2d6e-11e5-9e10-b11ae6a3cf1f.png)

**Comment by benfry** [comment]
Oh, it looks like it had picked up the font properly, did it not? 

The image thing is fixable. Do you still want the icon to work there?
