### ISSUE TITLE
Sketch window does not always display when running a sketch with a blank draw() function

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3363]
Sketch with a blank draw() function, often does not display, and the Run button needs to be pressed several times  (not necessarily an odd number of times), for the sketch to run, which in turn may cause the sketch to run without the Run button being (visibly) selected and turning green, as shown:

![image](https://cloud.githubusercontent.com/assets/4526417/8039430/b1308b24-0e1a-11e5-82f3-759ad7884100.png)

A sample sketch that gives this problem is this one:

```
void setup() {
  size(200,200);
  rect(20,20,40,40);
}

void draw() {
}
```

However, this sketch seems to work perfectly fine all the time:

```
 void setup() {
  size(200,200);
}

void draw() {
  rect(20,20,40,40);
}
```

The output of the above two sketches, however, is identical. The issue described is not consistent, and sometimes, the first sketch has to be run several times before getting an output window, while at other times, the output window is displayed immediately.
  
Possibly related to #3249.

**Comment by benfry** [comment]
I can no longer replicate this with the current source, after making a lot of changes to threading for #3315, #3303, and #3363. Fingers crossed...

**Comment by joelmoniz** [comment]
Thank you very much! I can no longer reproduce this issue on Windows 8.1.

**Comment by benfry** [comment]
That's great news, thank you!
