### ISSUE TITLE
send list of installed Libraries, Modes, Tools, and Examples when update checking

### ISSUE THREAD

**Issue by REAS** [processing/processing#3365]
Should we add something to include the library/mode/tool list (and versions) when checking for updates? We’ve discussed it before, but haven't made a hard decision.

**Comment by benfry** [comment]
I think it's a good idea and should be harmless. Users can turn it off by unsetting the "don't check for updates" preference. Which is also noted in the FAQ.

**Comment by alignedleft** [comment]
@REAS to clarify:  We currently just check for updates to the IDE.  Are you proposing also auto-checking for updates to all installed contributions?

I think this would be great, but it would require auto-downloading contribs.txt every time the IDE is opened (or once a week, or once per whatever time period is set).  Is @benfry OK with that additional hit to the server?  This would also involve more complex logic under the hood than the current IDE version check.

**Comment by benfry** [comment]
Yeah, we're already doing that, it's the only way to keep the contribs up to date. 

The thing to be implemented is to send a list of the user's currently installed modes/libraries/tools (and versions?) so that we understand what people are using and where to focus our efforts on getting things updated/fixed/improved.

**Comment by eric-brechemier** [comment]
@benfry There should be a different checkbox for the submission of user's config, separate from the permission to check for updates.

For example, Firefox has currently two checkboxes in `Preferences > Advanced > Data Choices`, each associated with a link to 'Learn More':

* [Enable Firefox Health Report](https://www.mozilla.org/en-US/privacy/firefox/#health-report)
* [Enable Crash Reporter](https://www.mozilla.org/en-US/privacy/firefox/#crash-reporter)

**Comment by benfry** [comment]
Firefox also has 10x as many preferences as us. It's not like this is sharing personal information, and if people want to shut it off, they can.

**Comment by eric-brechemier** [comment]
@benfry I personally feel uncomfortable with this change: while the [FAQ](https://github.com/processing/processing/wiki/FAQ#why-is-processing-connecting-to-the-network) states that the check for updates sends a uniquely identifying number, which is arguably a limited breach of privacy when used in isolation, sharing the list of Libraries, Modes, Tools, and Examples that I installed over time could be much more revealing.

**Comment by benfry** [comment]
The feature doesn't exist yet, so the FAQ hasn't been updated, nor has the phrasing of the text used in Preferences.

**Comment by eric-brechemier** [comment]
@benfry I am aware of that :) I do not expect the FAQ to describe a future implementation. While I feel OK with the current behavior as it is described in the FAQ, I am wary of the extension of the data collection in the name of "checking for updates".

**Comment by REAS** [comment]
We feel that this information is important for the development of the software, so I think people who are uncomfortable with it can and should flip the switch in the preferences.

**Comment by alignedleft** [comment]
On the web side, we probably need a PHP script or other way to receive and log the IDs of the installed contributions. Does that sound correct, @benfry? We could even consolidate things, so instead of one check for IDE version and one for all contributions, all values are returned from a single call to the server.
