### ISSUE TITLE
Processing crash with opening sketch with bad name.

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3371]
P 3.0a10 / OSX 10.9 
When I try to open a sketch with aname different of the folder sketch, Processing crash. May be it's normal, but it's a problem when you've open an other sketch unsaved, you lost your work.
![capture d ecran 2015-06-10 a 15 01 30](https://cloud.githubusercontent.com/assets/3332269/8083017/01cc3a98-0f82-11e5-9904-45b471ad90d1.png)
![capture d ecran 2015-06-10 a 15 01 50](https://cloud.githubusercontent.com/assets/3332269/8083022/083e47ae-0f82-11e5-973b-4ac8e8e0dfa2.png)

**Comment by benfry** [comment]
I can't reproduce this. What are the steps to make this error happen?

**Comment by benfry** [comment]
Closing; cannot reproduce and no response.
