### ISSUE TITLE
Re-sizing ccreen not the expected size

### ISSUE THREAD

**Issue by rala72** [processing/processing#3375]
Processing 2.2.1
Windows 7

    if (width==screenX) {
      size(displayX, displayY);
      frame.setSize(width, height);
      borderMaxX=displayX-borderX;
      borderMaxY=displayY-borderY;
    } else {
      size(screenX, screenY);
      frame.setSize(width, height);
      borderMaxX=screenX-borderX;
      borderMaxY=screenY-borderY;
    }

full code:
http://txt.ralaweb.bplaced.net/report/processing/star.txt

I want a small size on startup (screenX).
After a click it grows to the display size.
After another click it gets the small size again.

But after changing the size the sizes aren't correct.
I see that on the border. I've everywhere a border around my "star". But this is only on top and left correct.

I also tested it with a lineal.

**Comment by clankill3r** [comment]
Can you bring this question to the forum:
http://forum.processing.org/

**Comment by benfry** [comment]
This isn't a bug, please use http://forum.processing.org for programming questions.
