### ISSUE TITLE
Rendering differences in OpenGL between 3.0a5 and 3.0a10

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3377]
mac os x 10.10.3
processing 3.a10

without OpenGL:
![screen shot 2015-06-12 at 12 50 54 pm](https://cloud.githubusercontent.com/assets/738650/8128770/7e794abe-1102-11e5-914d-e972669ac952.png)

with OpenGL: (P2D and P3D look the same so 1 image)
![screen shot 2015-06-12 at 12 50 28 pm](https://cloud.githubusercontent.com/assets/738650/8128780/9ab66a72-1102-11e5-8394-04bc553ac850.png)

-A lot of lines are not showing up.
-The OpenGL window is slightly smaller
-Things are not on the same position
-The text is not showing up

But hey, the framerate is awesome ;P
I know things are undergoing a heavy progress so you might be already aware of those problems.
(Thats why I made it one issue...)

**Comment by codeanticode** [comment]
The actual rendering was not changed from 3.0a5 to 3.0a10, would you post a simple test skecth that shows the discrepancies between the two versions?

**Comment by clankill3r** [comment]
Maybe the problem was also there in 3.0a5.
I didn't use OpenGL for quite some time.
Maybe it's also due the strokeWeight I used.
Anyway, I will make a bare bones example asap!

**Comment by clankill3r** [comment]
Here is one to start with:
The text doesn't appear.
If i make the size a bit smaller like 1000, 1000 then it appears so this might be monitor size related.
My monitor is 1680x1050.

````java
public void settings() {
  size(1024, 1024, P3D);
  smooth();
}

void setup() {
}

void draw() {
  background(0);
  fill(255);
  text("dsfsdfsd", 20, 20);
  line(0, 0, width, height);
}
````

Update: I figured that the content is pushed away upwards if the window is to large:

![screen shot 2015-06-14 at 2 59 38 pm](https://cloud.githubusercontent.com/assets/738650/8148635/2f285d42-12a6-11e5-8bfd-05dbc258965c.png)

![screen shot 2015-06-14 at 3 00 31 pm](https://cloud.githubusercontent.com/assets/738650/8148636/3130ba94-12a6-11e5-939e-f04fc5d33031.png)

**Comment by clankill3r** [comment]
2nd. About the lines:

In this sketch the line is drawn 50% of the time in P3D and 100% of the time in the default renderer. 

````java
public void settings() {
  size(512, 512, P3D);
  smooth();
}

void setup() {
   frameRate(5);
}

void draw() {
  background(0);
  strokeWeight(0.25);
  stroke(255);
  line((0.25*frameCount)%width, 0, (0.25*frameCount)%width, height);
}
````

**Comment by codeanticode** [comment]
Issue 1: canvas pushed up if window's height larger than screen's height. This is due to the way JOGL handles its native GL window. I just opened a separate issue about this: https://github.com/processing/processing/issues/3401

Issue 2: OpenGL has always renderered lines in this way. The problem is that you are using a sub-pixel line strokes, and the sampling sometimes loses the geometry if antialiasing is disabled. I do see lines appearing half of the time if smooth is disabled, both with Processing 2.2.1 and 3.0a10.
