### ISSUE TITLE
clear() is broken

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3378]
https://processing.org/reference/clear_.html

Instead of a transparent background it results in a black background now.
The code from the link above is good to reproduce the problem.

Mac os x 10.10.3
processing 3.a10

older processing:
![screen shot 2015-06-12 at 1 38 59 pm](https://cloud.githubusercontent.com/assets/738650/8129320/7238f32a-1108-11e5-974c-13e463f0eacf.png)

current processing:
![screen shot 2015-06-12 at 1 39 15 pm](https://cloud.githubusercontent.com/assets/738650/8129324/7c53a382-1108-11e5-9b14-7a31f03c7ab2.png)

**Comment by codeanticode** [comment]
which renderer are you using?

**Comment by clankill3r** [comment]
Good point. I tested and it happens in the default as well P2D and P3D.

**Comment by JukePlz** [comment]
May be related to #3317

**Comment by benfry** [comment]
Fixed for 3.0b1.
