### ISSUE TITLE
Fail to load SVG in P3D

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3379]
Procesing 3.0a10, 3.0a9, 3.0a8
OSX 10.9 / iMac 2012 
`````````
PShape pirate ;
void setup() {
  size(640,480, P3D) ;
  pirate = loadShape("pirate.svg") ;
}
`````````
Problem to load.
the consol return:
ClassCastException: processing.opengl.PGraphics3D cannot be cast to processing.opengl.PGraphics

for Processing 3.0a7
```````
void draw() {
  shape(pirate, 0, 0, 100, 100); 
}
``````````
Problem to read
the consol return: NullPointerException

Work fine with file.obj, P2D and Processing 3.0a5.

@codeanticode The war versus openGL continue !

**Comment by codeanticode** [comment]
Thanks for the report, will look into it.

**Comment by benfry** [comment]
@codeanticode This may be due to the changes I made to remove the several copies of `loadShape()` that were sprinkled around OpenGL.

**Comment by codeanticode** [comment]
yes, thanks for the reminder. It is now fixed with https://github.com/processing/processing/commit/f0f95585235b9043a82c7f862bd6c2c8547f8fbf
