### ISSUE TITLE
sketches using the default renderer not grabbing focus by default

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3380]
I believe they should?   Otherwise the user has to alt-tab out of the sketch and find the stop button.  

I'm testing with this code:

```
void setup() {
  fullScreen();
}

void draw() {
  background(0, 100, 150);
  fill(255);
  ellipse(width/2, height/2, 200, 200);
}
```

Testing on Mac OS X 10.10.3

**Comment by benfry** [comment]
It's probably a focus problem. If you click in the window it should work. (But certainly a bug since it should be grabbing focus by default.)

**Comment by shiffman** [comment]
Confirmed that ESC does indeed quit the sketch after you click in.  Updating the title of this bug report.

**Comment by benfry** [comment]
Fixed for the next release.
