### ISSUE TITLE
fullScreen(SPAN) only showing up on display 1

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3381]
This code:

```
void setup() {
  fullScreen(SPAN);
}

void draw() {
  background(0, 100, 150);
  fill(255);
  ellipse(width/2, height/2, 200, 200);
}
```

I'm only seeing the results on display 1.  Using macbook pro OS X 10.10.3 with some casio projector via HDMI.   Same true for `P2D` and `P3D`.

**Comment by benfry** [comment]
What's your display arrangement like? I've tested this quite a bit with 10.10.3 and it was working correctly. It was fixed the day before the release, so also make sure your repo is all up to date.

**Comment by shiffman** [comment]
It was clearly working in that the circle appeared half on display 1. But I didn't see the second half of the window on display 2.  I came across while teaching a workshop and showing new 3.0 features.  So I wasn't able to dig into it too deeply.  I'll try to again soon. It was a standard setup: mac laptop connected to projector, mirroring turned off, laptop was display 1, projector display 2, resolutions were whatever the OS defaulted to.

**Comment by benfry** [comment]
Is it possible that you didn't have the projector plugged in when you started Processing? Trying to figure out where I might start looking into this.

**Comment by shiffman** [comment]
yes, I believe that was the case!

**Comment by benfry** [comment]
Tested adding and removing the display and it's still working fine for me. There was a bug in the preferences window that I just fixed, but I can't get `fullScreen(SPAN)` to break.

**Comment by shiffman** [comment]
let's close this for now and I'll re-open if I (or someone else) can reproduce?

**Comment by benfry** [comment]
Ok, though any chance you can get access to that projector again and see if you can reproduce?

**Comment by shiffman** [comment]
Sadly no, it was a one-time workshop at a school, won't be headed back there anytime soon.  Will check on another projector with the same laptop soon though.

**Comment by benfry** [comment]
Realized what this probably is... In System Preferences > Mission Control, there's an option called "displays have separate spaces". It's selected by default on recent versions of OS X, and probably breaks `fullScreen(SPAN)`. 

![screen shot 2015-06-15 at 9 20 23 pm](https://cloud.githubusercontent.com/assets/1623101/8173992/607cec74-13a4-11e5-863c-fdb6886910bb.png)

I already had a note in my todo list about warning users about this. If this was indeed the problem, it looks like that becomes a higher priority.

**Comment by shiffman** [comment]
Yup, indeed that setting is turned on for my machine.   Apologies that I'm not in my normal day-to-day life where I could easily check with a secondary display.

**Comment by benfry** [comment]
Marking this for beta since I think it's going to be fairly common (since it's the default on OS X).

**Comment by benfry** [comment]
Fixed for beta 1.

**Comment by clankill3r** [comment]
There is a bug where the warning doesn't show up. Maybe due to code rot.

**Comment by benfry** [comment]
Please file a new issue; that would be a separate problem.
