### ISSUE TITLE
Drag and Drop & "Add File" broken for .pde files in 3.0a10

### ISSUE THREAD

**Issue by JukePlz** [processing/processing#3383]
This was working fine on Processing 2.x, now dragging a .pde file into the editor will return an error. The file is added correctly to the sketch folder but the editor doesn't refresh the changes and pops up this dialog:

![drag_ _drop_problem_2015-06-14_03-59-47](https://cloud.githubusercontent.com/assets/8497884/8147606/361cbef6-124a-11e5-9cf9-fc310a780b30.png)

This also prints into the console after that error:

http://pastebin.com/89VNjGnW

Tested on Windows x32. Version 2.2.1 works as intended, versions after 3.x have this problem (Tested on 3.0a4, 3.0a5, 3.0a10) probably a PDE X issue.

**Comment by benfry** [comment]
PDE X doesn't work with Processing 3 at all. Are you really running PDE X somehow?

**Comment by JukePlz** [comment]
To clarify, what I meant by PDE X is the new, default "Java" mode that ships with 3.x but this also seems to happen with the fallback "Java (2.0)" mode so I may be mistaken about that.

I will test on other Windows computers later to see if this is somehow specific to my system, my first suspect to cause something like this would be large file paths or special characters in them but I don't know exactly what changed with the new IDE related to that. Processing 2.2.1 handles this without trouble for me.

**Comment by benfry** [comment]
Fixed for the next release. 

@joelmoniz This was in your "Add File" progress code... You can't run that stuff on another thread and just hope it finishes in time for it to be used. For data folder items it's no big deal, but a .pde file is used immediately by the environment, so you can't do that from a thread without waiting for the copy to finish.

**Comment by joelmoniz** [comment]
Oops, sorry about that. I had not realized that this segment would be run when the user tries to drag and drop something in, nor had I thought about adding a .pde file. My bad :(
