### ISSUE TITLE
Concurrency issues in OpenGL renderer

### ISSUE THREAD

**Issue by neilcsmith-net** [processing/processing#3384]
I'm currently trying to track down an occasional issue in Praxis LIVE when PGraphicsOpenGL and/or PShader instances are disposed of.  Every now and again this breaks rendering entirely.  That this isn't consistently repeatable would point to a concurrency issue.

A possible cause might be the finalize*() methods in PGraphicsOpenGL. The comments correctly recognise that finalization happens on a separate thread, so the methods are synchronized.  However, none of the code on the GL thread appears to take that lock at any point before touching those collections!

Another issue is that using GC / finalize() to manage native resources in the first place is a big Java anti-pattern, for good reason - there is no guarantee that GL resources will be released in a timely manner.

First (and easiest) solution would be to enforce manual disposal.  This would require an API change, although for many users only creating GL resources in setup() there would be no change.

The alternative might be changing the GLResource class to extend WeakReference, and remove all finalize() methods.  This still doesn't handle the second problem, but would help get rid of concurrency issues.  Java2D uses a similar approach.

ie. something like 

```java
static protected Set<GLResource<PShader>> glslPrograms = new HashSet<>();
// ...
protected static void deleteFinalizedGLSLProgramObjects(PGL pgl) {
  Iterator<GLResource> iter = glslPrograms.iterator();
  while (iter.hasNext()) {
    GLResource<PShader> res = iter.next();
    if (r.get() == null) {
      pgl.deleteProgram(res.id);
      iter.remove();
    }
  }
}
// ...
protected static class GLResource<T> extends WeakReference<T> {
  
  GLResource(T obj, int id, int content) {
// ...
```

**Comment by codeanticode** [comment]
Not sure how the resource disposal is causing the concurrency errors you are observing. It would be very useful to have a simple sketch that reproduces the issue, even if it is only some of the time, or at least a log of the error.

Just a quick note on how GL resources get deleted: the deleteFinalized*() methods are always called when a new resource of the same kind is created, so this ensures that, at least for those objects that were finalized by the GC, they are released by the GL driver.  

PGraphics does have a public dispose() method, which in PGraphicsOpenGL marks all GL resources as finalized, and then deletes them.

**Comment by benfry** [comment]
The `dispose()` is a `PGraphics` method since it's necessary to do disposal, and it's handled by the `PSurface`. 

Generally speaking, we should (and do) bend over backwards to not put the burden on users to call `dispose()` methods. It's a bad thing to add now, and on our side, it can lead to lazy implementations rather than fixing issues that we should be sorting out ourselves.

**Comment by neilcsmith-net** [comment]
On 18 June 2015 at 19:03, codeanticode <notifications@github.com> wrote:

> Not sure how the resource disposal is causing the concurrency errors you
> are observing. It would be very useful to have a simple sketch that
> reproduces the issue, even if it is only some of the time, or at least a
> log of the error.
>
Unfortunately, as with most concurrency issues, it's not generally
reproducible.  It's an occasional error - I'll work on getting an accurate
log for you if possible.  However, in tracing through the operations in the
code that happen when the bug is triggered, there's an obvious race
condition in finalization.

Just a quick note on how GL resources get deleted: the deleteFinalized*()
> methods are always called when a new resource of the same kind is created,
> so this ensures that, at least for those objects that were finalized by the
> GC, they are released by the GL driver
>
The issue is occurring at a time when some resources are being replaced -
some created, some disposed.  None of the deleteFinalized*() methods called
on the GL thread seem to lock on anything before manipulating the
collections that are being written to by the finalization thread.  It's
possible that the collection is being corrupted in some fashion.

You could keep this all single threaded anyway by using WeakReferences and
removing any need for finalization - this may improve GC too.


>  PGraphics does have a public dispose() method, which in PGraphicsOpenGL
> marks all GL resources as finalized, and then deletes them.
>
PShader doesn't though, for example.  The "correct" way to fix this would
be to force people to use dispose() on PShader, etc. and remove finalize()
entirely - a memory leak is possibly better than memory corruption?  I'm a
little wary that finalization() here is more akin to "do magic" - anyone
getting that advanced should understand the underlying hardware and
implications.

**Comment by benfry** [comment]
No, you're not hearing me: `dispose()` methods have no place for our target audience.

**Comment by neilcsmith-net** [comment]
> No, you're not hearing me: 

@benfry That would have been difficult! :-) Sorry, problem of replying via email - hadn't even seen your post when I replied to Andres.

I quite understand your viewpoint, hence suggesting WeakReference as an alternative as well. There is a minor issue that it's impossible to know when the Java object will be GC'd and release the GL resources as there's no pressure on Java memory.  This is related but tangential to the concurrency issue.

**Comment by codeanticode** [comment]
Ok, I found a better way to do resource disposal without relying on finalization, see the section "An Alternative to Finalization" in [this article](http://www.oracle.com/technetwork/articles/java/finalization-137655.html). Implementing it now, should solve the issues you have described since the glDelete*() functions are always called in the animation thread, and relies on weak references.

**Comment by neilcsmith-net** [comment]
Great!  I meant to share a link to that article with you. ;-) It's pretty much the suggestion at the top - the places I use that pattern I'm tending to use the "explicit" get() check rather than the "implicit" queue check - either would suit though.

Still think that making dispose() public (even if non-official API) would be a good move - GC is just not deterministic.

This should solve the concurrency issue.  Whether this is the cause of the problem that caused me to hunt for race conditions is another matter! :-\

**Comment by codeanticode** [comment]
done with https://github.com/processing/processing/commits/master
