### ISSUE TITLE
Processing 3.0a10 recognizes keyboard input only after a click into the sketch window

### ISSUE THREAD

**Issue by RetainCountZero** [processing/processing#3389]
Processing 3.0a10 seems to recognize any keyboard input only after the frame has at least been clicked once.
To reproduce the issue, try the following simple sketch:

    // setup
    void setup() {
      size(320, 200, JAVA2D);
    }
    
    // draw
    void draw() {
      line(0, height/2,width, height/2);
    }
    
    // keyboard events
    void keyPressed() {
      println("You pressed key: " + key);
      // q = ascii:113, Q = ascii:81
      if (key == 113 || key == 81) {
        println("quit initiated.");
        exit();
      }
    }

Run the sketch.  The window of the sketch becomes the active window.  Now press any key.  Nothing happens.
There's the problem.  The pressed key should be displayed in the console, and if the key q is pressed the sketch should quit.  However, once you clicked into the active sketch, the keypresses are shown in the console and everything works as it should.

I was able to reproduce this issue with Processing 3.0a10 on MacOSX and on Windows x86_32.  This problem did not occur with Processing 3.0a9.

**Comment by benfry** [comment]
Fixed: https://github.com/processing/processing/issues/3389
