### ISSUE TITLE
No sketch window OS X 10.10.3 

### ISSUE THREAD

**Issue by cnoblejr** [processing/processing#3390]
Tried old versions and 3.0 versions -- same thing.  Just beginning.  Have iMac 21.5" and Cintiq tables.  Sketch window is NOT visible on the Cintiq.  Tried mirroring displays, turned the Cintiq off -- still no sketch.

Can't even get started.

C

**Comment by benfry** [comment]
Sounds like something better handled on the forum: http://forum.processing.org. There's nothing here that I can even begin to debug.

**Comment by cnoblejr** [comment]
Thx Ben, I’ll give it a shot.

C
On Jun 16, 2015, at 4:11 PM, Ben Fry <notifications@github.com> wrote:

Closed #3390 <https://github.com/processing/processing/issues/3390>.
