### ISSUE TITLE
contributions.txt download progress bar still visible after download

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3393]
When a Contributions Manager dialog is opened (for example, to install a Library), and contributions.txt file finishes downloading, and another Contributions Manager dialog different from the first is opened (for example, this time to install a Tool), the progress bar is visible in the Tool Manager at the bottom right corner, although it is hidden in the Library Manager and the contributions.txt file has been downloaded:

![image](https://cloud.githubusercontent.com/assets/4526417/8204951/6946caa0-14fd-11e5-99fa-2dce2a941920.png)

**Comment by alignedleft** [comment]
Thanks, @joelmoniz.

I think we are doing away with this progress bar altogether as part of the CM UI redesign. I'm assigning this to @Akarshit for tracking purposes.

**Comment by Akarshit** [comment]
@benfry this can be closed now.
