### ISSUE TITLE
error message caused by curly bracket in a println string

### ISSUE THREAD

**Issue by kasperkamperman** [processing/processing#3394]
The code below give the following error: Found a { that's missing a matching }

````
// gives the error
  if(luminanceCurveInSteadOfGamma) {
    println("const uint16_t luminanceLUT[] = {");
  }
  else {
    println("const uint16_t gammaLUT[] = {");
  }
````

````
// doesn't give the error
  if(luminanceCurveInSteadOfGamma) {
    println("const uint16_t luminanceLUT[] = {");
  }
  else {
    //println("const uint16_t gammaLUT[] = {");
  }
````

The error warning algorithm doesn't seem to see that the curly bracket in the String is not part of the code. At least with multiple lines that do this. 

Processing 3.0a10
OSX 10.10.3

**Comment by benfry** [comment]
Nuts, that's probably the new `size()` parsing. Will fix asap.

**Comment by Manindra29** [comment]
`((?<![\\])['"])((?:.(?!(?<![\\])\1))*.?)\1` can match all quoted strings ([source](http://www.metaltoad.com/blog/regex-quoted-string-escapable-quotes)). Might be useful here.

**Comment by benfry** [comment]
We have to match both quoted *and* unquoted cases, i.e. `P3D` or `"processing.opengl.PGraphics3D` so it's even worse than that.

**Comment by Manindra29** [comment]
Then maybe try to match all the expected quoted strings, save any if found,
and then replace all quoted strings with spaces to avoid this issue?

There may be a simpler way though.
