### ISSUE TITLE
Memory Leaks on Tool Exiting

### ISSUE THREAD

**Issue by Bryce-Summers** [processing/processing#3395]
I have noticed that Processing 3 increases its system memory consumption when tools are opened, but it does not decrease its memory consumption when tools are closed. 

My repeatedly opening and closing tools, I was able to have Processing go from taking up ~187, 276 K memory to taking up ~400, 000 K. If I continued in this manner, Processing 3 would have continued to use up more and more memory.

On a side note, it is also important for tools to stop their PApplets before exiting.

**Comment by benfry** [comment]
This is likely a red herring unless you're actually running out of memory. The garbage collector doesn't bother running until it actually needs to.

We don't have any PApplets in tools in the current release (3.0a10), so it also sounds like you're using an old version.

**Comment by Bryce-Summers** [comment]
The PApplet is in the tool that I am currently developing.
I was just noting that bad things happened before I remembered to stop my PApplet on tool closure.
