### ISSUE TITLE
Enhancements to xxxxMode and textSize.

### ISSUE THREAD

**Issue by JukePlz** [processing/processing#3396]
Currently these functions are hard to track and make it a pain to make portable method collections using them, there is no straightforward way to check the current state of this modes inside the main program without hacky solutions.

I propose the following changes.

- Make xxxMode (ellipseMode(),rectMode(),imageMode(),shapeMode(),colorMode(),textureMode(),blendMode()) and textSize() return the mode set, when the function is called empty. Since most of these functions are used with a single parameter this shouldn't be a problem for new users.

- Allow push/popStyle() to contain textSize()

**Comment by benfry** [comment]
Please don't mix unrelated requests in a single report.

textSize() is already included in push/PopStyle().

The xxxMode() functions are primarily intended to be set once per sketch, and when not, to have low overhead. Just call the xxxMode() function again if you need a specific mode.
