### ISSUE TITLE
resizing PDE window from bottom-right corner moves (x,y) position of PDE

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3397]
Testing a10 and current source build, Mac OS X 10.10.3, Retina.

When I try to resize the PDE window from the bottom-right corder, the whole PDE jumps to a default position in my screen's window.  (Am I explaining this in an understandable way?)

**Comment by benfry** [comment]
Hm, not seeing anything like that. You sure you don't have something installed that's messing with window layout on your system?

**Comment by shiffman** [comment]
Hmmm, I don't think so but will investigate!

**Comment by benfry** [comment]
Or maybe post a video of it if you can reproduce? I just can't get it to do anything like this, and 90% of my development time is on 10.10.3 w/ retina.

**Comment by shiffman** [comment]
I'm not sure what was going on but I can no longer reproduce this with the latest build from source.
