### ISSUE TITLE
Linux  rsync build issue

### ISSUE THREAD

**Issue by undefinedMethod** [processing/processing#3398]
Issue with rsync as a Linux build dependency.

Attemped build on ArchLinux fails as rsync is required on the system to clean up the build before end of compilation. Rsync wasn't on my system and needed to be installed.

Build with Apache Ant executes fine after rsync installation. Maybe needs to be added to the Linux dependencies list or flagged up to users who may have issues building the source on some distros?.

**Comment by benfry** [comment]
ArchLinux is billed as a super stripped down version of Linux. It's not something we support, and when someone uses it and sees rsync is missing will presumably do exactly what you did, and install rsync. I'd rather not get into covering every possible exception case in the build instructions. This one explains itself as it happens.
