### ISSUE TITLE
Missing scrolling in Sketch->Import library...

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3399]
When the no of libraries increase the height of the screen there is no way to go to those libraries which are not visible. OS - Ubuntu

**Comment by alignedleft** [comment]
@Akarshit can you post a screenshot? It's not clear to me what this means.

**Comment by joelmoniz** [comment]
Is this issue similar to #2535?

**Comment by benfry** [comment]
Yes: https://github.com/processing/processing/issues/2535
