### ISSUE TITLE
Loading Fonts in Initializer NullPointerExceptionError 3.0a10

### ISSUE THREAD

**Issue by Luxapodular** [processing/processing#3400]
Hello All, 
While working on processing.py, one of Jonathan Feinberg's unit tests for loading in the initializer rather than the setup function caused a NullPointerException error. I tracked the error back to processing 3.0a10. Here's the code which causes the error

```processing
PFont font = loadFont("data/Cabal1-48.vlw");

void setup() {
  size(10,10,P3D);
  noLoop();
  println("OK");
  exit();
}
```

while the "equivalent" code below runs with no errors. 

```processing
void setup() {
  size(10,10,P3D);
  PFont font = loadFont("data/Cabal1-48.vlw");
  noLoop();
  println("OK");
  exit();
}
```

seems to run all the way back to the ```die()``` and ```dispose()``` functions. Here's a snippet of the stack trace. 

```
Caused by: java.lang.NullPointerException
	at processing.core.PApplet.dispose(PApplet.java:3420)
	at processing.core.PApplet.die(PApplet.java:3331)
	at processing.core.PApplet.die(PApplet.java:3341)
	at processing.core.PApplet.loadFont(PApplet.java:5887)
	at FontTest.<init>(FontTest.java:17)
```

I tested this with a few different .vlw files and got the same error each time.

**Comment by benfry** [comment]
That's a bug in the code. You can't use `loadFont()` until `setup()`.
