### ISSUE TITLE
P2D and P3D windows behave strangely when larger than the screen size

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#3401]
JOGL's [GLWindow](https://jogamp.org/deployment/webstart/javadoc/jogl/javadoc/com/jogamp/newt/opengl/GLWindow.html) has a peculiar way of handling sizes that are larger than the display: if the window's height surpasses the display's height, then the window's height is capped at the display's. In addition to that, the canvas is attached to the lower left corner so the contents come out of the viewport from the top. Haven't found a way in JOGL to chance this behavior and make it consistent with the rest of the renderers.

To check by yourself, run this code making sure that the height is larger than the current display's height:

```java
void setup() {
  size(512, 1000, P3D);
}

void draw() {
  background(150);
  line(0, 0, width, height);
  line(0, height, width, 0);
}
```

you should be getting something like this:

![image](https://cloud.githubusercontent.com/assets/62246/8236334/983a888e-15b5-11e5-98d2-42df357e1829.png)

**Comment by monkstone** [comment]
```java
void setup() {  
}

void draw() {
  background(150);
  fill(255);
  ellipse(width / 2, height / 2, 300, 1000);
  stroke(0);
  line(0, 0, width, height);
  line(0, height, width, 0);  
}

void settings(){
 size(512, 2000, P3D);
}
```
Spooky weird, kind of wonderful though. On linux (Mint-17.1) original sketch refuses to run, so I modified as above. Window then displays to maximum available height (but scaled) ie lines to corners. Same true when I [maximise sketch (scaling but does no affect ellipse screen 1920x1020).]
(http://martinpblogformasswritingproject.blogspot.co.uk/2015/06/opengl-behaviour-processing-30a10-on.html).

**Comment by JakubValtar** [comment]
Can't reproduce. It works as expected on my Windows 8.1 64bit. Window size is capped by the screen size, size of the sketch is automatically adjusted, `width` and `height` correctly reflect the actual size of the sketch.

When the `size()` is in `setup()` and width or height is greater than the size of the screen, the sketch freezes and I get `IllegalStateException: size() cannot be used here, see http://processing.org/reference/size_.html`, but in `settings()` it works with all sizes.

**Comment by benfry** [comment]
Adding “known” tag because this is listed in the “known issues” section [in the wiki](https://github.com/processing/processing/wiki/Changes-in-3.0). When this bug is fixed, it should be removed there.

**Comment by codeanticode** [comment]
JAVAFX does automatic window resizing as well when width/height are larger than the screen resolution, but the sketch's width/height variables are properly set to the actual resolution. I will reproduce that behavior on the GL renderers, at least until JOGL's changes the window behavior. I just wrote [a post](http://forum.jogamp.org/unusual-GLWindow-behavior-on-OS-X-td4035234.html) on their forum about this.

**Comment by xranby** [comment]
I can not reproduce this bug using Ubuntu Linux.
The window gets re-sized automatically if larger than the screen
however it is scaled correctly, the lines go from the corners of the window.

is this bug confined to MacOS X?

**Comment by codeanticode** [comment]
I believe it affects Windows as well, @JakubValtar could you confirm this?

**Comment by JakubValtar** [comment]
@codeanticode Nope, we talked about it yesterday, it's a Mac thing.

**Comment by benfry** [comment]
No, let's not limit everywhere if it's an OS + renderer problem. We should just fix the JOGL + OS X case seen here.

**Comment by xranby** [comment]
I have filed a bugreport to investigate
[a] the macosx GLWindow gets incorrectly auto-resized, content is rendered outside the window
https://jogamp.org/bugzilla/show_bug.cgi?id=1214

It would be very good if someone with MacOSX can copy and change one of the JOGL junit tests and make it demonstrate the issue without using processing 3.

**Comment by benfry** [comment]
@codeanticode This is a stopper for 3.0 final; don't we have a workaround to deal with the OS X case?

**Comment by codeanticode** [comment]
I have a potential workaround for 3.0: inside [initWindow()](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PSurfaceJOGL.java#L269) check if sketchWidth/Height is greater than displayWidth/Height, if so, resize the sketchWidth/Height to sketchWidth/Height. However, I would also need to subtract the sum of the height of the apple menu bar and the height of the window top bar. I can get the latter from window.getInsets().getTopHeight(), but don't know how to obtain the height of the apple menu bar. Can we add a getter to JAppleMenuBar for that purpose?

**Comment by benfry** [comment]
I was hoping that we could just get the window's dimensions after it's been resized by the OS, rather than guess what the window was going to be resized to (the calculations you describe). Can we not do that?

**Comment by codeanticode** [comment]
I was hoping the same thing, but GLWindow reports the original size, even though it has been capped to fit the screen. I [mentioned this](https://jogamp.org/bugzilla/show_bug.cgi?id=1214#c7) in the discussion in the JOGL bug tracker, but haven't heard back anything yet.

**Comment by codeanticode** [comment]
I implemented [a method](https://github.com/codeanticode/jogl/commit/2f0172d597b61629c428052ad412aaea2eb2b29d) in JOGL's native code that resizes the rendering window in OS X when it exceeds the screen size. Not sure if it will be included in JOGL's main repo, at least as it is and by the time we release 3.0 final. If not, as a last resort we could build our own modified jar files to bundle with Processing.

**Comment by benfry** [comment]
I don't suppose you've heard anything about the next planned release date for JOGL?

**Comment by codeanticode** [comment]
Nothing so far. I haven't received any replies in the bugtraker or the forum. By looking at the [objectives page](http://jogamp.org/wiki/index.php/SW_Tracking_Report_Objectives_for_the_release_2.3.2) for their next stable release, one would say is near. I will try to get some info on their IRC channel.

**Comment by benfry** [comment]
Ok, I'll remove the 3.0 final tag since it's out of our control.

**Comment by xranby** [comment]
It is now fixed in JOGL: https://jogamp.org/bugzilla/show_bug.cgi?id=1214

**Comment by benfry** [comment]
Good to hear! Thanks for the update.

**Comment by codeanticode** [comment]
We would need to update to an RC of JOGL 2.3.2, or the final release if it is ready by the time 3.0 comes out. Should we add the update to 2.3.2 as an issue in the 3.0 milestone?

**Comment by benfry** [comment]
I think we need to get 3.0 out w/o the 2.3.2. As far as I understand it, there isn't a committed release date for 2.3.2, nor is it fair for us to harass them for one or blame them for holding up our 3.0.

**Comment by codeanticode** [comment]
Of course not, what I was thinking was to open an issue on updating to 2.3.2, either to an RC, or the final release in case it is available. My point would be that it is worth updating to even an RC (I have been using the latest ones and did not have any problems) to fix this issue in 3.0 final, since it has been confusing many people. Otherwise, we could just update jogl whenever the 2.3.2 final comes out, and make into a 3.x release.

**Comment by benfry** [comment]
But we'd decided not to include RC binaries if we're about to replace them shortly after. Though if we think this is bad enough, maybe we should revisit that decision.

**Comment by codeanticode** [comment]
Ok, fair enough. We said before this is a stopper for 3.0, that's why I thought that making an exception to update to RC binaries could be desirable. But maybe the issue is not so serious after all, and @shiffman and @REAS could weight in based on their experience with students: do you think this should be fixed for 3.0 final, or could it wait?

**Comment by REAS** [comment]
I think this issue is an inconvenience and unfortunate, but it shouldn't stop our release. It's great to hear it's fixed in JOGL and it will be great to incorporate it when the time is right.

**Comment by codeanticode** [comment]
Ok, sounds good. I will keep an eye on the JOGL releases, so we can incorporate the latest stable version as soon as it becomes available.

**Comment by xranby** [comment]
http://forum.jogamp.org/Release-2-3-2-and-Bugzilla-Entries-td4035393.html

 Dear All, updated release wiki page for 2.3.2:
https://jogamp.org/wiki/index.php/SW_Tracking_Report_Objectives_for_the_release_2.3.2

- Notice the target release date of 2015-10-04,
  which is now being considered the worst case scenario.

- Testing the current RC builds is crucial, thank you!
http://jogamp.org/deployment/archive/master/?C=M;O=D

**Comment by codeanticode** [comment]
Hi Xerxes, thanks so much for the updates and all the hard work!

I will test the RCs from Processing and will report back in the issues opened in the jogl bug tracker.

**Comment by benfry** [comment]
Great, so that'll be perfect for (the inevitable) 3.0.1. Looking at Tuesday or Wednesday for 3.0 final.

**Comment by codeanticode** [comment]
https://github.com/processing/processing/commit/9a71778618ceb3a9a0bbafbc2285b2b120c466dc fixes this.
