### ISSUE TITLE
Not all updates are showing up when contribution.txt is not already present.

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3405]
When running updates manager for the first time(without contribution.txt) it looks like this 
![screenshot from 2015-06-19 11 39 18](https://cloud.githubusercontent.com/assets/7762605/8248062/2c449fca-1678-11e5-8603-83691555dd93.png)
and when running it the second time(with contribution.txt already downloaded) it looks like
![screenshot from 2015-06-19 11 40 34](https://cloud.githubusercontent.com/assets/7762605/8248070/45d40ab6-1678-11e5-97f6-df61abc19b11.png)

**Comment by alignedleft** [comment]
For what it's worth: I understood from @prisonerjohn that contributions.txt (or contribs.txt) should already be bundled with the IDE when it's downloaded.  So, in theory, there would always be that pre-loaded, cached (but perhaps out-of-date) version available to the app. Of course, when a network connection is available, we want to download the latest copy and replace the cached one.

**Comment by Akarshit** [comment]
@alignedleft Ok, i was talking about the case when the user deletes the contributions.txt from system because of some weird reason. But i guess that would be a very rare case and the updates would show when he restarts Processing, so i am guessing it would be safe to close this issue.
