### ISSUE TITLE
visually distinguish warnings from errors in the console

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3406]
Note the following code:

```
void setup() {
  int myVar = 10;
}

void draw() {
  ellipse(myVar, 10, 10, 10);
}
```

Produces one warning and one error.  These are distinguished in the editor with a yellow squiggly line and a red one.  However, in the console they appear equally as errors (though the tab is not colored red if only the warning is there.)   I see we have a preference to "show warnings" but should they also be visually distinctive if shown?

**Comment by benfry** [comment]
Yes, we should. I'll add it to the list.

**Comment by jamesjgrady** [comment]
Here are two screen shots outlining the warning vs. the error UI.

Let me know if this is clear or you have questions on the interaction.

![pde-sketch-r16-warning](https://cloud.githubusercontent.com/assets/2600893/10054847/4ceeea08-6201-11e5-895f-c49ff5f1d574.png)

![pde-sketch-r16-error](https://cloud.githubusercontent.com/assets/2600893/10054852/53f58104-6201-11e5-86c6-b751c961d9e5.png)

**Comment by benfry** [comment]
Not sure if we can have different highlight colors, though the idea here is that it needs to be possible to tell error/warning w/o having to click on it.

**Comment by benfry** [comment]
Maybe even just adding a red or orange dot next to the line, and then the highlight color could reinforce it....

**Comment by jamesjgrady** [comment]
I think that could work. Here are revised sketches.

![pde-sketch-r16-error-002](https://cloud.githubusercontent.com/assets/2600893/10057900/91dab78c-6210-11e5-8533-42cd27afc3f7.png)

![pde-sketch-r16-warning-002](https://cloud.githubusercontent.com/assets/2600893/10057905/9830d30a-6210-11e5-8d37-0237ec463303.png)

**Comment by benfry** [comment]
All set. Managed to get the selection background color to change as well.

**Comment by jamesjgrady** [comment]
One more thought on error vs warning so it's not so visually violating. Seems like the orange warning is a bit overkill. This would also remove any inner glow issues.

![pde-sketch-r16-error-003](https://cloud.githubusercontent.com/assets/2600893/10170847/f619aa30-66a4-11e5-9c5d-565d57a65907.png)

![pde-sketch-r16-warning-003](https://cloud.githubusercontent.com/assets/2600893/10170858/014f29de-66a5-11e5-8264-ce10823d59de.png)
