### ISSUE TITLE
Erroneous "unexpected token if"

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3408]
The following code:

```
void setup() 
  if (mouseX > 10) {
  }
}
```

correctly states `Missing left curly bracket "{"` on line 1 in the error console, however, upon running it states `unexpected token if` for line 2 in the red error bar.

![screen shot 2015-06-19 at 10 43 49 am](https://cloud.githubusercontent.com/assets/191758/8250957/3d1dc6b2-1670-11e5-9116-f719f26493fc.png)

If you give it some time (close to a minute later?), eventually the red bar text is replaced with ``Missing left curly bracket "{"``

**Comment by benfry** [comment]
Yeah, this is because different preprocessing code is used by the live checking than the one used when you hit Run. Not sure how we square these—usually the latter is better, but this is a case where the former is giving us something more useful.

**Comment by Manindra29** [comment]
Another option can be to gray out the Run button if Java Mode reports compilation errors?

**Comment by benfry** [comment]
Hm, that's an interesting idea.

**Comment by benfry** [comment]
Opting to not disable the Run button because it'll reinforce a slight delay before people can hit "Run" when the error checker service hasn't finished. This'll annoy people as the machine tries to catch up with someone typing quickly.
