### ISSUE TITLE
processing-java command line mode not working on Mac

### ISSUE THREAD

**Issue by mckennapsean** [processing/processing#3409]
On a Mac when you run the `processing-java` command for a sketch, the Commander java application runs... and stalls, doing nothing. There is no output visible in any terminal window, so not sure how to debug it (or I would). No sketch window opens, and you have to kill the `processing-java` command to close the application.

Using the latest source, 3.0a10, and 3.0a9, me and [one other person](https://github.com/b-g/processing-sublime/issues/73#issuecomment-113209457) have been unable to use `processing-java` on Mac. I am running Mac OS X Yosemite. We both were able to get the command line version working using 3.0a5.

This issue is Mac-specific. I was able to get it working under Linux & Windows just fine.

Also, I checked out commit 5037024 since it addressed #3224, and the same issue was occurring after that fix, too. I am guessing it is a result of all the major changes to the code base which happened before then.

If I can help, let me know!

**Comment by benfry** [comment]
Bummer... I could really use some help on this, especially a maintainer who was committed to making sure the command line version worked. For all the noise about it, I wish the people who use the command line version would do more to help out.

**Comment by mckennapsean** [comment]
Okay, I was able to get sketches running by playing with [`Commander.java`](https://github.com/processing/processing/blob/master/java/src/processing/mode/java/Commander.java).

A few lines of code were stalling in that file: *e.g.* [`Preferences.init()`](https://github.com/processing/processing/blob/master/java/src/processing/mode/java/Commander.java#L225) since `Color` was not working in [Preferences.java](https://github.com/processing/processing/blob/master/app/src/processing/app/Preferences.java) & also the [`JavaMode` variable](https://github.com/processing/processing/blob/master/java/src/processing/mode/java/Commander.java#L246) was holding up execution.

I added an import statement to `Commander.java`:

````java
import java.awt.*;
````

And I needed to use that import statement somewhere in the file:

````java
Color someColor = new Color(0);
````

Then it was working again. There is very likely a better way besides the hack above, but I figured this might help point someone towards a better solution. Not sure if this is at all related to the movement of classes like `Commander` from `app/src/processing/app` to `java/src/processing/mode/java` back in January; presumably affecting how `java.awt.*` is imported.

I still have *no clue* why this would be Mac-specific, unless it is some sort of Java bug...

**Comment by mckennapsean** [comment]
Now fixed!

Started working between d8dd354 and 240dde4.
