### ISSUE TITLE
Java 8 features not working

### ISSUE THREAD

**Issue by GKFX** [processing/processing#3411]
When I try to use a lambda expression in Editor.java, I get the message
````
    [javac] 7. ERROR in /home/bateman/Geek/processing/app/src/processing/app/Editor.java (at line 3042)
    [javac] 	item.addActionListener(e -> handleIndentOutdent(false));
    [javac] 	                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    [javac] Lambda expressions are allowed only at source level 1.8 or above
````
Is this right? The compiler asks me to install Java 8 if I'm on Java 7, but then doesn't use its features.

**Comment by benfry** [comment]
I don't know how we can be any clearer about this:
https://github.com/processing/processing/wiki/Supported-Platforms
