### ISSUE TITLE
Error on size() when using FX2D due to stage inset issues

### ISSUE THREAD

**Issue by aengelke** [processing/processing#3412]
This sketch:

```
void setup() {
  size(400, 300, FX2D);
}
void draw() {
  background(255, 0, 0);
}
```

This error when running (a window appears): `size() cannot be used here ...`

**Comment by benfry** [comment]
FX2D isn't finished yet or announced and is broken in many ways. 

In this case, the window's insets aren't properly being handled when sizing the FX Stage.

**Comment by benfry** [comment]
Working properly in the current beta.
