### ISSUE TITLE
Sketch name not visible in menu

### ISSUE THREAD

**Issue by paul59** [processing/processing#3414]
The name of the sketch isn't visible on the Sketch menu unless the mouse is hovered over it.

![](http://s21.postimg.org/5uslxdg9z/grab.jpg)

3.0 alpha 10, Linux Mint 17 xfce

Maybe a window manager issue?

EDIT I forgot to mention my Java version: Java(TM) SE Runtime Environment (build 1.8.0_45-b14)

**Comment by joelmoniz** [comment]
Interesting. I don't seem to be getting this issue on Windows 8.1:

![image](https://cloud.githubusercontent.com/assets/4526417/8271025/298768b2-1812-11e5-887b-b17801392f57.png)

**Comment by benfry** [comment]
Looks like a window manager problem, and therefore out of our control. The menu works fine in Ubuntu 12.04 and 14.04.
