### ISSUE TITLE
keyboard shortcut for switching tabs on Linux conflicts with other window manager features

### ISSUE THREAD

**Issue by paul59** [processing/processing#3416]
The default shortcut is Ctrl + Alt + Left/Right but on Linux systems this is usually intercepted by the window manager for switching desktops.

I'm not sure about Windows these days (and no idea about Mac!) but is Ctrl + PgUp/PgDn not feasible (the usual shortcut for  tab movement in browsers, spreadsheets, editors etc)?

**Comment by joelmoniz** [comment]
With regards to Windows (8.1), it seems that this shortcut makes everything displayed on the monitor rotate by 90 degrees (counter/)clockwise.

**Comment by aengelke** [comment]
On GTK+, the default is Alt+1, Alt+2, ..., Alt+0

**Comment by benfry** [comment]
We're following what browsers (Chrome, in particular) use for switching tabs on a per-platform basis.

So what's used on Linux?

**Comment by paul59** [comment]
Not sure about Chrome but Firefox uses Ctrl+PgUp/PgDn (as do many other applications).

**Comment by paul59** [comment]
Just checked - *Chromium* uses the same ctrl+pgup/pgdn so I guess Chrome does too.

**Comment by Manindra29** [comment]
The standard shortcut for switching between tabs I believe is Ctrl-Tab (next tab) and Ctrl-Shift-Tab (previous tab). This is standard across Chrome, Safari, Firefox, IE, Sublime Text.

Using Pg Up/Down is not intuitive for macbook keyboards (since they don't have a page up/down buttons)

**Comment by benfry** [comment]
For 3.0 beta 3, we'll use Ctrl+PageUp/Down on Linux (only) since that seems to be most common.
