### ISSUE TITLE
Contributed examples do not display in the Examples window

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3420]
At present, contributed examples do not seem to be displaying in the `Examples` window:

![image](https://cloud.githubusercontent.com/assets/4526417/8286992/fff09dea-191d-11e5-9685-9f0ce2cbde25.png)

**Comment by benfry** [comment]
And you're sure about this—are there any legitimate examples packages to even test against?

**Comment by joelmoniz** [comment]
Yeah. When I was testing out the Examples Manager for bugs, I'd created an examples package [here](https://github.com/joelmoniz/G4P_Examples) that consisted of code stolen, ummm... I mean borrowed, from the G4P library. It even contains a fake contributions.txt that I used to use to ensure that the Examples Manager unpacked, installed, displayed, updated downloaded examples properly. This package does not display. I traced this to the removal of a method when the Examples window was being redesigned, that I'd initially added in to display the contributed examples in this window.

**Comment by shiffman** [comment]
I'm re-opening this issue.  In 0239, I have the nature of code examples package installed, but I do not see them in the examples window.  The files are in the examples folder inside my sketchbook.

<img width="867" alt="screen shot 2015-07-24 at 2 00 47 pm" src="https://cloud.githubusercontent.com/assets/191758/8874814/6a0abd80-320c-11e5-9985-affb9c30feda.png">

**Comment by joelmoniz** [comment]
I can confirm that the error isn't fixed yet. 2 changes will need to be made:

1. The default value for `modes` is set to "null" if the field isn't present in the examples.properties file. The problem is, "null" is read as a string, not as `null`. @prisonerjohn could you please change this so that either nothing is added if the `modes` property is absent, or the `modes` property is written like the `paragraph` property (`modes=`) if nothing is specified in the properties file?
2. In case nothing is added, then this issue should be fixed. Otherwise, in case it is written in the form `modes=`, I'll file a PR if it is preferable to write the default as `modes=` as soon as the changes are made.

**Comment by alignedleft** [comment]
Thanks @shiffman and @joelmoniz. @Akarshit can you look into this as well?

**Comment by Akarshit** [comment]
Ya sure, but i think first @prisonerjohn should take a look into what @joelmoniz has suggested.

**Comment by prisonerjohn** [comment]
@joelmoniz What exactly do you mean when you say "nothing is added if the `modes` property is absent"? Where is something added that shouldn't be added?

FWIW, `paragraph=` is not added by default when the key is not present. I think we're seeing it often because it's part of the template and example .properties files.

**Comment by joelmoniz** [comment]
@prisonerjohn Oops. Sorry. My bad.This issue arises because the Contributions Manager adds in the extra line [here](https://github.com/processing/processing/blob/master/app/src/processing/app/contrib/AvailableContribution.java#L355) without a null check.

**Comment by benfry** [comment]
Fixed this for 3.0 beta 2.
