### ISSUE TITLE
Extra Byte being written by processing PrintWriter

### ISSUE THREAD

**Issue by mrfrankism** [processing/processing#3425]
There is an extra byte added when you use the write function of the PrintWriter library in processing.
for example..

PrintWriter writer;
writer = createWriter(filepath.txt);
writer.print(char(165));
this would actually print two bytes which would be the equivalent of 194 and then 165.

I know that it prints two bytes because if you were to read from that same text file and printed it to the console it showed me 194 and the 165.

compared to ..
import java.io.FileNotFoundException;
import java.io.File;
import java.io.PrintWriter;

PrintWriter writer;
writer = new PrintWriter(new File(filepath.txt));
writer.print(char(165));
this would actually only print a char with the equivalent value of 165.

This could be done on purpose i really do not know but it created an issue for me because it was crucial for me to write and then read byte per byte without interruptions.

P.s this is the first time i report an issue ever so im sorry if im missing something here, help would be appreciated :D

**Comment by benfry** [comment]
That's not a bug, as stated in the reference, the file is written using [UTF-8](https://en.wikipedia.org/wiki/UTF-8), which uses two bytes to write character 165.

**Comment by mrfrankism** [comment]
Ohh sorry see i didnt know that thank you for the clarification i will look into it more
