### ISSUE TITLE
Getting Error: 500 from server when downloading contribs

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3427]
`java.io.IOException: Server returned HTTP response code: 500 for URL: http://download.processing.org/contribs`  
Getting this error when fetching the link though the link works fine in browser

**Comment by benfry** [comment]
Try now?

**Comment by benfry** [comment]
And just fixed another problem. Hopefully we're set.

**Comment by Akarshit** [comment]
@benfry Yes it's working now, could you tell me what the error was, because it was working fine in the browser ?

**Comment by benfry** [comment]
Just a bug in the server-side code that handles recording what contribs are in use. I had used the wrong syntax for escaping inputs to the database.
