### ISSUE TITLE
contributions to come: JavaCV and TUIO

### ISSUE THREAD

**Issue by poqudrof** [processing/processing#3431]
Hello, 

I just read the processing "How to contribute" guide, and I found that I did some the elements in the TODO list. 
The smallest contribution is small edit of [TUIO Processing](https://github.com/potioc/ProcessingTUIO) to be more flexible, and it is updated and pushed on maven. 

The largest contribution is the integration of JavaCV in Processing. So here is a few "soon-to-come" contributions from JavaCV that I have in my library : 
* Camera support from multiple source: Gstreamer (current Processing Video library), OpenCV (Video4Linux on Linux, and most cameras on Windows & Mac), OpenKinect (Depth & color), FlyCapture with proprietary drivers. 
* All Camera streams are avaible as IplImages (OpenCV format) and PImage. 
* Support of ARToolkitPlus as the images are in the right format. 

The core of the library is Augmented Reality, so the cameras can be calibrated and a renderer created for it, same for projectors to do Projection mapping. The see-through AR part will go open-source soon, the other parts I don't know yet. I saw also in the todo list that the library for quad mapping was outdated, I might create some apps do to this with my framework, but I wait for my employer to say it's OK before publishing code. 

For now, the camera support is fully integrated in my library, and I did not plan to move it outside because it is part of the core of my library. But, I can have a look to write it as an extension to the current version of Processing Video. 

I also worked on [ControlP5](https://github.com/potioc/ControlP5), though at the time I did not find it was still active on github. I refactored it, and rewrote parts of it to handle multiple PGraphics, have multi-touch (in progress) and support for other languages. It is now working in [Ruby-Processing](https://github.com/ruby-processing) ([gem](https://rubygems.org/gems/ruby-processing/versions/2.6.12)), I did not look at Python Processing but writing a wrapper could be as easy as for the ruby version. 

Thanks for the great work for, now. All my work rely on Processing for many years, and I will work to improve Processing as I improve my software. 
Cheers, 

Jeremy.

**Comment by benfry** [comment]
Thanks; a better location for this are the “Create and Announce” sections of http://forum.processing.org
