### ISSUE TITLE
change undefined constructor error message for clarity

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3434]
The following code

```
void setup() {
  Thing t = new Thing();
  noLoop();
}

class Thing {
  Thing(int n) { }
}
```

produces two errors:

```
The constructor sketch_150626b.Thing() is undefined
The function "testFunction()" does not exist
```

I propose changing the first constructor related error message to:

```
The constructor Thing() does not exist
```

I think the full path of the inner class `sketch_150626b.Thing()`, though accurate, is confusing and unnecessary.  And since we're using "does not exist" with functions, we might as well be consistent.

**Comment by Manindra29** [comment]
I'll take this one.
