### ISSUE TITLE
Tweak mode broken (re: new settings() function)

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3435]
I believe the new `settings()` function has broken Tweak mode with recent 3.0 revisions.  @galsasson, can you take a look or advise?  

![screen shot 2015-06-26 at 10 50 23 am](https://cloud.githubusercontent.com/assets/191758/8374938/28455c6a-1bf1-11e5-9edb-f3e5233ad0df.png)

(FYI in 3.0, `size()` is moved to `settings()` in the preprocessor, a bit more here: http://beta.processing.org/reference/settings_.html)

**Comment by benfry** [comment]
Is this only when tweak mode attempts to mess with `size()`, or perhaps that's all the time with tweak mode?

**Comment by shiffman** [comment]
All the time.  I couldn't get to the point of tweaking anything.  I think tweak mode does its own preprocessing with `size()` and that's conflicting with the new `size()` moving to `settings()`.  But I am speculating not looking at the code.

**Comment by benfry** [comment]
Ouch, ok. We'll probably need to have tweak explicitly ignore the `size()` and `fullScreen()` methods.

**Comment by galsasson** [comment]
This should be an easy fix.
I will take a look toward the end of the week.

**Comment by galsasson** [comment]
Ok, after taking a look, I'm not sure what's wrong.

Tweak mode is not doing anything with size. The only thing it does is adding code to the end of the setup() function. It adds two function calls right before the closing bracket of the function:
tweakmode_initAllVars();
tweakmode_initCommunication();

Also, some code is being added to the beginning of the first pde file, maybe thats forbidden now?

If you set 'tweak.showcode=true' in preferences.txt, it will print the modified code every time you run in tweak mode. This way you can see what's wrong with the modified code and the recent change with the 'settings' function.

**Comment by galsasson** [comment]
This is a modified example of a test code I always use, can someone tell me whats wrong with this code? 
Size is the first command in setup() but I get "IllegalStateException: size() cannot be used here".
This was working until now.

```java
import java.net.*;
import java.io.*;
import java.nio.*;

int[] tweakmode_int = new int[11];
float[] tweakmode_float = new float[2];

class TweakModeServer extends Thread
{
	protected DatagramSocket socket = null;
	protected boolean running = true;
	final int INT_VAR = 0;
	final int FLOAT_VAR = 1;
	final int SHUTDOWN = 0xffffffff;
	public TweakModeServer() {
		this("TweakModeServer");
	}
	public TweakModeServer(String name) {
		super(name);
	}
	public void setup()
	{
		try {
			socket = new DatagramSocket(12345);
			socket.setSoTimeout(250);
		} catch (IOException e) {
			println("error: could not create TweakMode server socket");
		}
	}
	public void run()
	{
		byte[] buf = new byte[256];
		while(running)
		{
			try {
				DatagramPacket packet = new DatagramPacket(buf, buf.length);
				socket.receive(packet);
				ByteBuffer bb = ByteBuffer.wrap(buf);
				int type = bb.getInt(0);
				int index = bb.getInt(4);
				if (type == INT_VAR) {
					int val = bb.getInt(8);
					tweakmode_int[index] = val;
				}
				else  				if (type == FLOAT_VAR) {
					float val = bb.getFloat(8);
					tweakmode_float[index] = val;
				}
				else				if (type == SHUTDOWN) {
					running = false;
				}
			} catch (SocketTimeoutException e) {
				// nothing to do here just try receiving again
			} catch (Exception e) {
			}
		}
		socket.close();
	}
}


TweakModeServer tweakmode_Server;
void tweakmode_initAllVars() {
  tweakmode_int[0] = 156;
  tweakmode_int[1] = 71;
  tweakmode_int[2] = 222;
  tweakmode_int[3] = 85;
  tweakmode_int[4] = 10;
  tweakmode_int[5] = 15;
  tweakmode_int[6] = 242;
  tweakmode_int[7] = 10;
  tweakmode_int[8] = 14;
  tweakmode_float[0] = 196.1;
  tweakmode_int[9] = 291;
  tweakmode_float[1] = 163.7;
  tweakmode_int[10] = 111;
}

void tweakmode_initCommunication() {
 tweakmode_Server = new TweakModeServer();
 tweakmode_Server.setup();
 tweakmode_Server.start();
}





/* example 1 for tweak mode for Processing
 *
 * press play
 */

void setup()
{
  size(400, 450); // will not do any realtime change }
  smooth();

 tweakmode_initAllVars();
 tweakmode_initCommunication();

}

void draw()
{
  /* tweak the 123 background grayness */
  background(tweakmode_int[0]);

  /* tweak the stroke */
  stroke(tweakmode_int[1], tweakmode_int[2], tweakmode_int[3]);   
  fill(tweakmode_int[4]);
  strokeWeight(tweakmode_int[5]);

  /* tweak the fill */
  fill(tweakmode_int[6], tweakmode_int[7], tweakmode_int[8]);

  /* control the ellipse */
  ellipse(tweakmode_float[0], tweakmode_int[9], tweakmode_float[1], tweakmode_int[10]);
}
```

**Comment by shiffman** [comment]
A couple quick tests, I think that the `class
```java


import java.net.*;
import java.io.*;
import java.nio.*;


TweakModeServer tweakmode_Server;
void tweakmode_initAllVars() { }

void tweakmode_initCommunication() { }

void setup() {
  size(400, 450); // will not do any realtime change }
  tweakmode_initAllVars();
  tweakmode_initCommunication();
}

void draw() { }


class TweakModeServer extends Thread {
  public TweakModeServer(String name) {
    super(name);
  }
  public void setup() {  }
  public void run() { }
}

```

**Comment by shiffman** [comment]
A couple quick tests, I think that the `class` definition just needs to be below `setup()`.  This works for me:

```java
import java.net.*;
import java.io.*;
import java.nio.*;


TweakModeServer tweakmode_Server;
void tweakmode_initAllVars() { }

void tweakmode_initCommunication() { }

void setup() {
  size(400, 450); // will not do any realtime change }
  tweakmode_initAllVars();
  tweakmode_initCommunication();
}

void draw() { }


class TweakModeServer extends Thread {
  public TweakModeServer(String name) {
    super(name);
  }
  public void setup() {  }
  public void run() { }
}

```

**Comment by galsasson** [comment]
Thanks @shiffman !
If thats the issue, I will just add the class definition to the end of the first pde, this is not a big deal.
I guess that as a result of the change in the preprocessor a class definition is forbidden now before the setup function?
I just wonder if there is anything else that can go wrong as a result of the change in the preprocessor.

**Comment by benfry** [comment]
Fixed for alpha 11.

**Comment by galsasson** [comment]
Thanks @benfry
