### ISSUE TITLE
displayDensity() not functioning properly?

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3436]
This works for me:

```
void setup() {
  size(100, 100);
  println(displayDensity());
}
```

However, this fails:

```
void setup() {
  size(100, 100);
  pixelDensity(displayDensity());
}
```

`IllegalStateException: pixelDensity() cannot be used here`

And the following

```
void setup() {
  size(100, 100);
  int d = displayDensity();
  pixelDensity(d);
}
```

`d cannot be resolved to a variable`

**Comment by shiffman** [comment]
Update, moving everything to `settings()` works fine.

```
void settings() {
  size(600, 600);
  pixelDensity(displayDensity());  
}

void setup() {
  // etc.
}
```

**Comment by benfry** [comment]
Hm, that's not good. I'll take a look.

**Comment by benfry** [comment]
Now fixed, though we'll probably need to add the "no variables" caveat to the reference. There isn't a good way to make this work: 
```
void setup() {
  size(100, 100);
  int d = displayDensity();
  pixelDensity(d);
}
```

**Comment by shiffman** [comment]
That's actually from the reference, will open a processing-docs issue

**Comment by shiffman** [comment]
Does this mean you can't say

```
pixelDensity(displayDensity())
```

either?  But it's ok if you go ahead and use `settings()`?

**Comment by benfry** [comment]
Added notes to the docs item.
