### ISSUE TITLE
CM doubts and status

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3440]
@alignedleft  
I am opening this because I think there are more people involved in CM than us so they can also point out if we missed something.

Things left
* ~~display the progressbar that hides behind the label showing version.~~
* ~~Make the error Panel.~~
* do something(or don't do anything) when a contribution that is not compatible is clicked.
* convert the list to table
* handle the special case of update tab

Doubts
* ~~I opened the CM and then clicked on the BootStrap then the statusPanel shows information about BootStrap like this 
![screenshot from 2015-06-28 00 06 08](https://cloud.githubusercontent.com/assets/7762605/8393361/05e4e7f0-1d2a-11e5-8d65-32b2bd41ff5e.png)  
Then I change to `Modes` tab and the satusPanel is still showing the information about BootStrap(as it should ? I think) like
![screenshot from 2015-06-28 00 07 08](https://cloud.githubusercontent.com/assets/7762605/8393383/550fda56-1d2a-11e5-9b2a-398dd9fe1f0c.png)
Now when i select a mode it shows information about the in the statusPanel like 
![screenshot from 2015-06-28 00 07 33](https://cloud.githubusercontent.com/assets/7762605/8393388/6c7d5786-1d2a-11e5-9497-fecdf6669fde.png)
Now when i switch back to 'Tools` tab then the statusPanel is still showing the information about the Android Mode like 
![screenshot from 2015-06-28 00 07 41](https://cloud.githubusercontent.com/assets/7762605/8393391/b678f34a-1d2a-11e5-9918-b1d7cf6d70ed.png)
 So should it show information about Bootstrap or the mode ?~~
_Selection should be displayed in statusPanel_
* What if the user changes modes while CM is open?  
_Good question. Because when the mode changes, all the items in the CM window would be affected (as it only shows items for the current mode), correct?  
Maybe the CM should be a dialog box, i.e. always on top of everything else.  
Or… say I open the CM window, then go to an editor window and try to switch modes. Should we check to see if the CM window is open, then, if so, check to see if any updates/downloads are in progress? We could warn "switching modes will interrupt this update".  
None of these are great solutions — I just want to get the ideas out there._
* How to show errors that occur while downloading/installing/removing/updating a contribution ( in normal case and in `Update all` case ? These error can be of various types like __No net connection__, __poor format of contribution__, __file system error__, etc.
* ~~In the update tab, as according to wireframes there is only a update all button, so what happen when a user simply clicks on a list item?~~
_The Updates tab is just for quick updating, not for exploring details. Clicking a list item does nothing. To see details or update items individually, the user has to switch to one of the other tabs._
* ~~In update tab, wouldn't it make more sense to let the update and remove button stay as such and replace the install button with `Update all` button ?~~
_ it's confusing, because, in the first four tabs, the lower panel represents information specific to a given contribution. An "update all" button pertains to more than one contribution, so it would be confusing to have it in the lower panel._
* When the user clicks on `Update all` whose progress bar to show ? We are having a individual progress bar for every contribution so should the progress bar here be sum of all of them or should we skip the progressbar ?
![file3](https://cloud.githubusercontent.com/assets/7762605/8364530/9620d3d8-1ba4-11e5-8836-7670f2885fef.png)
* ~~Are the status messages like "Downloading contributions file...", "Done" to be completely removed because of the spinner ?~~
_Yes._
* ~~As in a conversation with @joelmoniz there is a undo button which becomes active when a contribution is removed unsuccessfully, where is it(if it is) supposed to be placed.~~
_I don't think we need this undo button. To "undo" the user needs to reinstall the contribution._
* @joelmoniz also mention there is a provision for restart button if a mode demands that, what to do with it ?
* When internet is not working and the message having the `Try Again` button is closed, should it appear again anywhere? If so how ?
_if my network connection was working, but then is interrupted? Yes, I suppose the "Try again" area should reappear._
But what if suppose i forgot to turn wifi on then opened processing and closed the `Try Again` box, then I realize my stupidity and turn on the wifi but there is no way now to "Try Again"
![file2](https://cloud.githubusercontent.com/assets/7762605/8364517/8426d5ce-1ba4-11e5-8870-d8bf23e22442.png)
* If i open the CM and then click on a contribution that is not compatible with like some mode so should the statusPanel be updated to show its information or not ?
* ~~Is the icon supposed to be shown in the status ?~~
_Yes_
* What to show in the statusPanel exactly when a contribution is clicked ? ( I am talking about the area where hyperlinks are shown right now)
* ~~And now the main one can someone give me an idea on how to make that list, i mean which layout to use ?~~
_JTable_

**Comment by alignedleft** [comment]
@Akarshit thanks for documenting all of this, but this is a huge thread, so I don't want to respond to everything at once. Let's take one at a time.

For the first concern, the description in the lower panel should always reflect what *selection* the user sees in the upper panel. So, if you select a library, then switch to another tab (say, "modes"), now there is no selection above, so the description below should be cleared out. Returning to the "libraries" tab, if we maintain the original selection there (and I suppose we should) then the description in the lower panel should populate.  Does that clarify?

In addition to everything above, I want to ensure we polish this UI visually, after everything is working technically. I'd like it to be visually consistent with the editor window, as much as possible.

@benfry I realize our Java window customization possibilities are limited. How realistic is it to create tabs and other elements that look like the wireframes (and the editor)?

**Comment by benfry** [comment]
@alignedleft Structurally this is all possible (and seems to be implemented), but at the moment, I think @akarshit took the wireframes to be design comps, not wireframes, so the design needs work at the moment (that's covered at #3464). Though I could have James work on the design so that it's consistent with his work on the editor.

**Comment by alignedleft** [comment]
@benfry Thanks. I'm communicating with Akarshit offline. I'm working on mockups and will post them in thread #3464 for comments.

@Akarshit I really appreciate that you documented all these concerns, but it is difficult in terms of workflow to have them all captured in a single GitHub issue, as it means we can't track them separately.  Some of these concerns should be regular questions (which you can email to me); I think issues should be reserved for clearly specified problems or planned enhancements.

**Comment by alignedleft** [comment]
@Akarshit I'm closing this, as I think we are already handling most of these concerns through other issues (and with the pending clarification of visual styling for the CM). If you have any outstanding concerns, please email me directly or open a new issue. Thanks!
