### ISSUE TITLE
calling Class.newInstance() or Constructor.newInstance() always throws an InstantiationException

### ISSUE THREAD

**Issue by bobvk** [processing/processing#3446]
I'm unable to create a new instance for a class in processing 2.2.1. 

If I'm just doing something wrong, my java isn't what it used to be, please enlighten me, all help would be greatly appreciated!

     void setup() { 
        Object o;
        o = Tester.class.newInstance(); //always throws :(
     }
     public class Tester { 
       public Tester() { }
     }

Thanks for an awesome play/dev environment, me and the kids love it!

(see also: http://stackoverflow.com/questions/31150337/unhandled-exception-type-instantiationexception-in-processing-org )

**Comment by aengelke** [comment]
This is no issue with Processing. To create a new instance of class, just do `Tester myTester = new Tester();`.

**Comment by bobvk** [comment]
Hi aengelke,
If u had that option I would.
Im working on a dynamic programming problem, the example i gave was the most simple reproducable example i could construct.

the actual call is within a loop over a HashMap<String,Class>, instantiating any class in that (dynamically filled) hashmap at runtime.

The hashmap is filled via reflection, but i can't hardcode as you propose since the actual list of classes is only enumerated at runtime.

If you try this exact example in regular java it works as expected, but within processing, exception.

When you say this is not an issue with processing, do you mean you can run the example without it throwing?

Thanks for your help.

________________________________

**Comment by aengelke** [comment]
I guess the reason for the exception is that the class (`Tester` in this case) is nested. Processing wraps the whole code you write in tabs which name does not end with`.java` in one class named as your sketch. Two ideas to fix: Make the class `static` OR put the class in a new tab named `Tester.java`.

It looks like an issue in your code, resulting from doing advanced Java programming, and is not related to the Processing preprocessor or graphics core itself.

**Comment by bobvk** [comment]
Ok, that makes sense! I'll try your suggestions and comment back if I manage to get something working, you've been a great help. 

Worst case I'll include processing as a lib in a regular java app, but as I'm also occasionally targeting processingjs I'm trying to avoid that. 

Thanks!

**Comment by bobvk** [comment]
Just for future visitors, simply sticking your classes in .java named files didn't do the trick :) the search goes on, time to hook this up to a debugger
![image](https://cloud.githubusercontent.com/assets/3190353/8503106/270104ac-21ba-11e5-9456-857b231c032e.png)

**Comment by KevinWorkman** [comment]
Here's my full answer: http://stackoverflow.com/a/31184583/873165

But I just wanted to note that putting your classes into .java files does indeed work (as I showed in the above link), but it looks like you forgot the .java part in your screenshot.

**Comment by benfry** [comment]
Please keep coding questions like this to forum.processing.org. It's not a bug and doesn't belong here.
