### ISSUE TITLE
Feature: Option to automatically save sketches when launching them

### ISSUE THREAD

**Issue by jondo** [processing/processing#3448]
I would like to have such an autosave to make it easier to use version control software.

I am a Processing newbie, currently using Processing 3.0a5.

**Comment by joelmoniz** [comment]
Processing provides an option to do this, although it is disabled by default. To enable this:

1. Go to `File>Preferences` (or `Ctrl+,` on Windows).
2. Double click on the file link below the line "More preferences can be found at".
3. Close processing, open up the preferences.txt file in the folder just opened via 2
4. Set the `pdex.autoSave.autoSaveEnabled` property to `true`, and processing should now save before launching if unsaved changes exist.

Hope this helps :)

**Comment by jondo** [comment]
This works, thank you!
