### ISSUE TITLE
Processing should notice when a loaded sketch file is changed on disk

### ISSUE THREAD

**Issue by jondo** [processing/processing#3449]
When there are unsaved changes, the user should be warned, otherwise a reload should be offered (or optionally done automatically).

Automatic reload would make it easier to switch between different versions with version control software.

**Comment by aengelke** [comment]
This was implemented by @pvrs12. There is the `editor.watcher` preference in the config file. (See the preference window to see where the file is located on your system.)

**Comment by jondo** [comment]
Should this already be contained in version 3.0a5? I see `editor.watcher=true`, but there is neither a warning nor an automatic reload when a sketch file is changed externally.

**Comment by benfry** [comment]
It's available in the current release, 3.0a11.
