### ISSUE TITLE
Reloading an open sketch does not work

### ISSUE THREAD

**Issue by jondo** [processing/processing#3450]
Create and save a sketch with the Processing IDE, then edit and save the sketch file with a text editor while leaving the Processing IDE open.
Now reopening the sketch file in the Processing IDE should load the edited file. Instead, it does nothing.

This would be useful when using version control software. Currently (3.0a5) I have to reopen the sketch GUI window instead.

**Comment by aengelke** [comment]
This is (nearly) the same as your bug #3449.

**Comment by jondo** [comment]
The difference to #3449 is: When automatic reload is off (or when it [does not work](https://github.com/processing/processing/issues/3449#issuecomment-117991873)), I still want to be able to manually reload the file without closing it.

**Comment by benfry** [comment]
The current behavior is the norm for most applications.

**Comment by jondo** [comment]
You could try to be less broken than others.
Notepad++ does this correctly, b.t.w..
