### ISSUE TITLE
THE open() FUNCTION

### ISSUE THREAD

**Issue by RomainAuroro** [processing/processing#3456]
I tried the following line of code:
open("Processing/TO_ADD_A_LONG_LIST_OF_SONGS_TO_SONG_LIST/NAME OF PLAYLIST.txt");

when i run it the .exe file in the folder is running instead of the .txt file stated last. In other words if i try to open a file in a folder that has an executable, then the executable is chosen over the file. And i cant put the file somewhere else cause its going to be used later and must be in the folder for loadStrings() to work.

**Comment by alignedleft** [comment]
Can you please specify all of the actual filenames involved?

Are you saying that you are trying to trigger opening of a file called "NAME OF PLAYLIST.**txt**" and instead a program called "NAME OF PLAYLIST.**exe**" is being opened?

Also, to clarify, `open()` is for opening files with your OS's usual behavior, not for loading data into a sketch, as with `loadStrings()`.  See:  https://processing.org/reference/open_.html

**Comment by RomainAuroro** [comment]
I know that open() is for opening files with your OS's usual behavior. The thing is i when i run open("Processing/TO_ADD_A_LONG_LIST_OF_SONGS_TO_SONG_LIST/NAME OF PLAYLIST.txt");
it opens the sketch file its self. that is, it opens: TO_ADD_A_LONG_LIST_OF_SONGS_TO_SONG_LIST.pde
i was wondering if its because part of the .pde file name is located in the path.

**Comment by alignedleft** [comment]
What version of Processing and what OS (and version) are you using?

Also, if you try using an absolute path to the file (e.g. `/Users/romain/file.txt`) does it behave differently?

**Comment by RomainAuroro** [comment]
No it doesn't. And i don't want to use that cause if i transfer the folder somewhere else on the computer it worst wont find the .txt file.  I'm using the latest version 2.2.1 and Windows 8.1

**Comment by JukePlz** [comment]
I was just testing this (Win7x32, Proc. 3.0a5) and it seems the trigger for the "opening itself" problem is having "Processing" as a folder inside the sketch and using it in the path name for open().

Still, after changing that folder name I can't get it to open a text file in a situation like this bug report. Nothing happens at all, and it seems directly using the windows command line from the working directory the file does open so it surely is something on processing's end.

**Comment by alignedleft** [comment]
Thank you both. Please test with 3.0a10 and let us know what you find:  http://processing.org/download

Note that `open()` has been renamed to `launch()` going forward. See: #3459

**Comment by benfry** [comment]
The [revisions](https://raw.githubusercontent.com/processing/processing/master/build/shared/revisions.txt) cover incremental changes between releases, and are especially important to read for pre-releases.
