### ISSUE TITLE
open() function does not exist in 3.0a10

### ISSUE THREAD

**Issue by rcrawfordEMX** [processing/processing#3459]
When attempting to call the open() function in 3.0a10, the following error occurs:
"The function "open(String)" does not exist".  The function works fine in 2.2.0.  Anyone else have this issue?

**Comment by JukePlz** [comment]
Not a bug, as of 3.0a10 the open() function has been renamed to launch()

commit 997407328125cd9719658d371d1cf2e8c71fcbd1

**Comment by benfry** [comment]
This was noted on the revisions page, and is part of avoiding confusion with Python and other modes.
