### ISSUE TITLE
AppBundler: Can we keep classpath jar files outside Contents/Java? Is there any way to refer them from Info.Plist?

### ISSUE THREAD

**Issue by ameyabap** [processing/processing#3460]
I used <classpath file="MyApp.jar"/> in build.xml and packager copies jar file into Contents/Java folder. Is it necessary that all classpath jar files should be preent in Contents/Java?
Is there any way so that instead of keeping jar files in Contents/Java, I can keep them some other path outside such as /Application/MyApp/lib? I think this was possible with Apple's 1.6 JarBundler. Can I add something in Info.plist so that it will point to the jars outside Contents/Java.

**Comment by benfry** [comment]
Please use forum.processing.org for questions.
