### ISSUE TITLE
Contribution Manager looking really rough

### ISSUE THREAD

**Issue by benfry** [processing/processing#3464]
@Akarshit what's going on here? This is a huge step backwards from the previous version. I'm trying to get alpha 11 out and it can't go out looking like this... cc @alignedleft 

(Also FYI, I moved the icon files around to keep them in line w/ how we handle all other assets. The `icons` directory is for the app's icons.) 

<img width="787" alt="screen shot 2015-07-15 at 10 02 52 am" src="https://cloud.githubusercontent.com/assets/1623101/8700259/c0c1593a-2ad8-11e5-99cc-dab1b714b1fe.png">

**Comment by Akarshit** [comment]
@benfry I think i understand what's the problem here. Working on it.

**Comment by benfry** [comment]
Discussion continues at https://github.com/processing/processing/issues/3482
