### ISSUE TITLE
A way to attach libraries to a sketch?

### ISSUE THREAD

**Issue by aidan-fitz** [processing/processing#3467]
An issue I'm having with my sketch is that it requires an external library, so I have to somehow include the library with [my sketch on GitHub](https://github.com/aidan-fitz/AudioProcessing/tree/master/ChiptuneMaker). However, users have to move the libraries to their `sketchbook` folders manually for this to work, and I don't want that. Is there a better way to make my sketch self-contained and work out of the box? If not, can you please add such a feature to v3?

http://programmers.stackexchange.com/questions/278909/uploading-processing-sketch-with-library-to-github

**Comment by aengelke** [comment]
You can try to place the jar files in the `code` folder of a sketch.

**Comment by benfry** [comment]
Please use forum.processing.org for questions.
