### ISSUE TITLE
cursor(CROSS) breaks when using surface.setTitle

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3472]
When setting the title with either frame or surface the custom cursor breaks.

tested in processing 3.0a10
OS X 10.10.4

Important detail: It only seems to happen with a title that is changing!

````java
void setup() {
  cursor(CROSS);  
}

void draw() {
  // this is no problem:
  //surface.setTitle("where ok");
  // this is:
  surface.setTitle("ouch "+frameCount); 
}
````

**Comment by benfry** [comment]
Looks like a Java bug. I've added a workaround for 3.0 beta 2.
