### ISSUE TITLE
"Enable complex text input" does not work on Linux

### ISSUE THREAD

**Issue by tiwawan** [processing/processing#3475]
OS: Ubuntu 14.10
Processing version: 3.0a11

I enabled "Preferences>Enable complex text input" and restarted Processing. Then, I tried to input Japanese, but I couldn't.
![processing-jpn_complex](https://cloud.githubusercontent.com/assets/4486076/8741692/b0c75d2a-2c97-11e5-9915-1a6f947b7d68.png)

On Windows, it looks working well, though the unfixed text is shown doubly(left one of below image).
![processing-jpn_complex_win](https://cloud.githubusercontent.com/assets/4486076/8741700/c0d958bc-2c97-11e5-8642-fcbb5ef49eeb.png)

**Comment by satoshiokita** [comment]
I dont test on Ubuntu 14.10. I tested 15.10. above my pull request will fix this problem.

**Comment by benfry** [comment]
Closed with https://github.com/processing/processing/pull/4293 for 3.0.2.
