### ISSUE TITLE
Implement 2x versions of the Contribution Manager icons

### ISSUE THREAD

**Issue by benfry** [processing/processing#3478]
We'll need double-size images for the files in lib/manager. As with other components, these should include -1x and -2x in their names.

In the code, select the necessary size based on `Toolkit.highResDisplay()`. You can see the implementations in other UI classes such as `EditorFooter.java` for an example.

**Comment by benfry** [comment]
cc @Akarshit

**Comment by Akarshit** [comment]
Thanks @benfry for pointing that out.

**Comment by REAS** [comment]
If possible, it would be best for @alignedleft or James to do this, they have the excellent design skillzz.

**Comment by alignedleft** [comment]
I will make the icons, but @Akarshit I'll need your help to implement them. I'm working on mockups for the CM now. The icons in the wireframes were just rough concepts.

**Comment by alignedleft** [comment]
@REAS Do you know who designed the new console and errors tab icons?

**Comment by benfry** [comment]
Those were done by James.

**Comment by REAS** [comment]
@alignedleft I'll send you James' email address over email.

**Comment by jamesjgrady** [comment]
@alignedleft @benfry I'm going to send you a .zip file with the icons now.

**Comment by benfry** [comment]
Icons are now checked in, changing title to refer to implementation.

**Comment by benfry** [comment]
Finished for 3.0 beta 7.
