### ISSUE TITLE
Finish Contributions Manager UI design

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3482]
For #3464 and other issues, we need to finalize the visual design of the new Contributions Manager.

I've started on mockups, but before I go further, I would like your input on whether or not this general approach matches the new editor stylistically. I've reached out to James by email, but in the meantime have lifted color values and approximated other design elements.

Would appreciate comments from: @benfry @REAS @shiffman 

![artboard 2](https://cloud.githubusercontent.com/assets/1034002/8763928/7486fa9a-2d6a-11e5-92ab-cca855419757.png)

Thanks!

**Comment by Akarshit** [comment]
I think it would be worth looking at this screenshot, most of the libraries have long description(even if we take only the first line) so the CM won't look as clean(with the default font size).
![screenshot from 2015-07-19 14 15 56](https://cloud.githubusercontent.com/assets/7762605/8765236/30e3980e-2e21-11e5-88a6-4c96cc53ed80.png)

**Comment by alignedleft** [comment]
@Akarshit Yes, thanks. My dummy text above doesn't reflect the real data. I'd like for text that doesn't fit to be abbreviated with an ellipsis ("…"), as you have done above. Then selecting that line will reveal the full description in the lower panel (as you have it working now).

**Comment by shiffman** [comment]
Personally I love how this looks!  I think I understand the icons (installed and updated, installed but needs an update, not compatible) but what do the greyed out ones indicate?  Not compatible and not installed?

**Comment by Akarshit** [comment]
@shiffman the greyed out once are those which are not compatible. The triangular icon is for installed and not compatible.

**Comment by alignedleft** [comment]
@shiffman Yes, sorry for not explaining. This mockup mirrors the wireframes I had emailed around earlier (with more clear explanations). @Akarshit’s explanation is correct. Thanks for the feedback!

**Comment by clankill3r** [comment]
Can't install / update not be merged in to one button and show whatever is appropriate for the situation?

**Comment by alignedleft** [comment]
@clankill3r Great point. I think you're right, although there was some reason why we went with three buttons here instead of three (not ideal UI, I know, but I remember something about it being simpler to have three separate buttons than fewer buttons who change their behavior dynamically). If anyone can think of a reason *not* to merge these buttons, please let us know here.

**Comment by alignedleft** [comment]
@REAS @benfry any comments? If not, I'm going to move forward with this, as we're nearing the end of GSoC, and @Akarshit needs to know what to work on next. Thanks.

**Comment by benfry** [comment]
I think it's close enough that you guys should charge ahead with it, and James will be providing some feedback, but it'll be less structural (so it should have less impact on @Akarshit's work, or be quicker modifications once this general setup is in place).

**Comment by alignedleft** [comment]
Super, thanks, @benfry. I'm communicating with @Akarshit separately to get this implemented.

**Comment by jamesjgrady** [comment]
@alignedleft @benfry here is the latest Contributions Manager UI comp. Let me know if you have comments/revisions. Also, let me know if you will need individual files for the Processing Foundation icons or the other icons (i.e. Installed, Update, Error)

![pde-contmgr-001](https://cloud.githubusercontent.com/assets/2600893/9074817/c4682b3c-3adb-11e5-851e-7c2a09863ad7.png)

**Comment by alignedleft** [comment]
Thank you @jamesjgrady! This looks really nice. However, there are several different states that this also needs to account for. I'll send you an email now with the full set of wireframes, which illustrate all the needed functionality.  This might need minor adjustments to accommodate.

**Comment by Akarshit** [comment]
Which design is to be implemented the one originally given by @alingedleft or the one given by @jamesjgrady

**Comment by jamesjgrady** [comment]
I have to look at the other wireframes and see where adjustments need to be made, but this latest comp is the general direction for design. I hope to have revised comps later today.

**Comment by Akarshit** [comment]
@alingedleft @jamesjgrady
Is the display "Version 0.9 available" below the install button removed ?
What about the progress bar, is it removed too ?

**Comment by JukePlz** [comment]
Is there really a point for separate install and remove buttons? Shouldn't they be different states for the same button?

**Comment by Akarshit** [comment]
@alignedleft the CM looks like 
![Uploading CM1.png…](this). If you could send me the finalized designs and icons it would help me to finalize the CM.  
What is the design of the filter and category strip ? ( it has been changed 3 times and i am still not sure which one is correct)

**Comment by clankill3r** [comment]
> Is there really a point for separate install and remove buttons? Shouldn't they be different states for the same button?

Good point! That would be nice.

Also, the blue color of the highlighted line is a way to dark blue color. It is really hard to read (on my monitor).

For the rest it looks nice.

I was wondering, will there be a new way to go to this menu?
Now you either have to use "add tool..." or "add mode..." to get there.

**Comment by Akarshit** [comment]
@clankill3r the blue color will be surely changed in next release.

**Comment by clankill3r** [comment]
This is also really hard to read:

<img width="119" alt="screen shot 2015-08-08 at 2 36 59 pm" src="https://cloud.githubusercontent.com/assets/738650/9150520/4d408982-3ddd-11e5-888e-e097e252aa82.png">

**Comment by benfry** [comment]
Locking to reduce noise until we can finish implementation.

**Comment by alignedleft** [comment]
@Akarshit Re: the filter and category strip, please reference the most recent mockup from James [above](https://github.com/processing/processing/issues/3482#issuecomment-127791166). Use that alignment, widths, and colors/grays. We can get the final icon images from @jamesjgrady and add them in later.

**Comment by benfry** [comment]
Closing this since I think we're mostly there, except for other more specific issues that have been filed. 

If anything is missing, please file individual issues for each specific problem so we can sort it out.
