### ISSUE TITLE
Missing seperate mode administration for v2.0 and v3.0

### ISSUE THREAD

**Issue by toniholzer** [processing/processing#3491]
Add the moment it seems that installing or updating modes in Processing v3.0alpha use then same file path as version 2.2.1  (used directory path is  "..\processing\_sketches_\modes\..."). 
Isn't it wrong to use a directory within the (variable) sketch path?

Modes should be stored in a version spezific file directory like e.g. the existing path 
      "..\processing\processing-3.0a11\modes !!!

A similar problem we have with the library path.

In any case, trying out beta versions of processing should not influence the development of a stable processing version!

**Comment by alignedleft** [comment]
I believe that the same sketchbook folder is used (whether you are building locally, running a downloaded alpha version, or a stable release) *unless* you have told 3.0 to create a new, 3.0-specific sketchbook folder (via the new Welcome screen). @benfry can confirm this is the intended behavior.

**Comment by benfry** [comment]
Change your sketchbook path in the Preferences. We're already accounting for this problem, but you need to point at a different folder when running 3.0. In a future release, we'll put up a prompt suggesting that users do it, but there's nothing to prevent you from doing it in the current release.
