### ISSUE TITLE
A little spacing issue with characters spacing in Welcome screen on Ubuntu

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3495]
There is a small spacing issue. I have drawn a circle(ish type of thing) where there is inconsistency.
![welcome](https://cloud.githubusercontent.com/assets/7762605/8783674/fe2cd248-2f3a-11e5-8f23-bf48965bd0da.png)

**Comment by alignedleft** [comment]
Interesting. I wonder if this is an issue with how the OS renders this particular typeface. If that's the case, we have limited control over this and probably can't fix it.

**Comment by benfry** [comment]
Yeah, not something we can fix, unfortunately.
