### ISSUE TITLE
processing-java cannot be installed on OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by hype** [processing/processing#3497]
after a day of poking and prodding - I cannot get processing-java to work on the newest version of OSX 10.11 El Capitan. it would seem that /usr/bin and /usr/sbin have been set to READONLY - so trying to install processing-java from the app obviously fails.

so I tried again, clicked "no" which added processing-java to my home directory, where I moved it into my Documents/Processing directory... I then tried adding it to my bash_profile :

export PATH=/Developer/AndroidSDK/platform-tools:/Developer/AndroidSDK/tools:/usr/bin:/usr/local/bin:~/Documents/Processing:$PATH

with no results and even tried running from command line : 

Joshuas-iMac:Processing joshuadavis$ ./processing-java --sketch='~/Desktop/test/test.pde' --ouput=tmp/ --run --force
~/Desktop/test/test.pde does not exist.

with still no results.

--

I should edit that sketches work fine when running within the IDE... but for my installations I run my sketches from command line to have greater control over memory allocations, etc.

**Comment by mckennapsean** [comment]
El Capitan introduces [System Integrity Protection](http://www.macworld.com/article/2948140/os-x/private-i-el-capitans-system-integrity-protection-will-shift-utilities-functions.html) which will not allow installation into those global directories (hence being read-only).

If I recall, you cannot use a tilde to represent the home directory to specify the location of a sketch. You must use an absolute path. Additionally, the sketch argument should point to the sketchbook folder (not the PDE file).

**Comment by hype** [comment]
rocking thank you @mckennapsean indeed ~ was my problem.

I would suggest anyone who considers upgrading to El Capitan and chooses to run an external editor or run sketches from command line needs to be made aware of how/why "install processing-java" isn't behaving as previously expected... with the read-only state of /usr/bin and /usr/sbin.

firing up terminal and using...

/Users/joshuadavis/Desktop/test/processing-java --sketch=/Users/joshuadavis/Desktop/test/build/ --output=/Users/joshuadavis/Desktop/test/build/build-tmp/ --force --run

ran perfect... please be careful in using --sketch and --output as... --output needs to be a new temp directory in order to work... it is very easy to run the risk of accidentally deleting your sketch folder if not done properly (from experience unfortunately).

I'll mark this as closed... though I'm not sure what the core processing team intends to do in regards to "install processing-java" going forward when El Captain moves out of beta. As this will fail and effect people using external editors like Sublime etc.

**Comment by mckennapsean** [comment]
Glad to help.

The issue of global install will likely be something to consider down the line for Mac OS 10.11.

P.S. the `output` flag is optional in Processing 3 if you wish to just use the system's temp folder instead (see `processing-java --help`)

**Comment by hype** [comment]
@mckennapsean awesome on the PS... still running 2_2_1 at the moment... yeah global install gives no warning that the install failed due to the read-only... but beta is beta... and I rolled back my main working machine back to 10.10.4 in the mean time.

**Comment by benfry** [comment]
Reopening because we'll need to sort out how we're supposed to do this under the new regime since we can't touch `/usr/bin` anymore. 

For anyone looking into it: how do we get something on the user's `PATH` in El Capitan? I'm guessing we'll have to mess with their profile and point to a binary/script inside Processing.app instead of installing the script in `/usr/bin`.

**Comment by benfry** [comment]
Fixed for 3.0 beta 5.
