### ISSUE TITLE
null pointer error in code directly from tutorial page on the processing website

### ISSUE THREAD

**Issue by retard232** [processing/processing#3498]
![failure](https://cloud.githubusercontent.com/assets/13429040/8793377/e0facbd2-2fc9-11e5-8097-f3745dab9fae.jpg)
![failure 2](https://cloud.githubusercontent.com/assets/13429040/8793400/277bfce8-2fca-11e5-8873-2fb7c5f936ab.jpg)

there is a problem with the tutorials on the base page for this program, as a null pointer error happens when the code is copied which stopped the tutorial dead for me.

**Comment by aengelke** [comment]
Did you added the images to the sketch? Also, at which line the exception is thrown?

**Comment by retard232** [comment]
Yeah the images were added to the sketch, the error is in the 22nd line or (pixels[loc] = color(r,g,b);) line. not sure what the problem is at all

**Comment by aengelke** [comment]
This is a bug in your code; you are missing a `loadPixels();` at the beginning of the draw function.

**Comment by retard232** [comment]
Thanks heaps, allready there is so much going on here wasnt aware 2 loadpixels were required. Think i deleted the 2nd one after i copied it
