### ISSUE TITLE
java.awt.MenuBar not appearing in processing 3 (Linux)

### ISSUE THREAD

**Issue by jsfa11** [processing/processing#3500]
The menu does not appear in the frame when using 3.0, but 2.2 will present this useless button without hesitation. 

The code with a full menu and listener gets a little complicated. I tried to write something simple as an example of the problem. If any more information is needed, I'll post.

This code works in processing 2, but not in processing 3 on a Ubuntu machine.
''' 
import java.awt.Menu;
import java.awt.MenuBar;
import java.awt.MenuItem;

MenuBar myMenu;
Menu aButton;
MenuItem aMenuItem;

void setup() {
  size(400, 400);
  makeMenu();
}

void draw() {
  
}

void makeMenu() {
  myMenu = new MenuBar();
  aButton = new Menu("Button A");
  aMenuItem = new MenuItem("MenuItem A");
  aButton.add(aMenuItem);
  myMenu.add(aButton);
  frame.setMenuBar(myMenu);
} // END makeMenu 
'''

**Comment by aengelke** [comment]
You probably didn't see the notice in the [readme file](https://github.com/processing/processing/blob/master/README.md). You are using an unofficial API that is broken due to fundamental changes. Try using `surface.frame.setMenuBar` instead. Reference: [PApplet.java:10201](https://github.com/processing/processing/blob/master/core/src/processing/core/PApplet.java#L10201)

**Comment by jsfa11** [comment]
Definitely read the README. I was hoping that I could make an ever so minuscule contribution (as was requested in the file) by reporting a bug. 
I've used Android Studio, IntelliJ, Eclipse, and other environments, but have always loved Processing's simplicity and functionality best. 

I'll try the alternative you've suggested. Thx.

**Comment by benfry** [comment]
You're using something undocumented that does not work the same way in Processing 3. This is not a bug, but a question that can be asked on the forum.
