### ISSUE TITLE
Processing doesnt open

### ISSUE THREAD

**Issue by Gunnersaurus** [processing/processing#3504]
Hello, 
I'm trying to download the processing software and it saves as a zip file. I've dragged it to the desktop and the program file on my hard disk, but it doesn't change the format of the file. This prevents the the software from opening as PDF DC does not support zip files. 

How can I change the zip file in order for the software to open? 

I have Windows 7 64-bit

**Comment by benfry** [comment]
Please use forum.processing.org for general questions.
