### ISSUE TITLE
Remove support for fixed-function pipeline

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#3505]
Right now the [default profile](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PSurfaceJOGL.java#L173) in the GL renderer is [GL2ES1](https://jogamp.org/deployment/jogamp-next/javadoc/jogl/javadoc/com/jogamp/opengl/GL2ES1.html), so users still have the chance to access the fixed-function pipeline (FFP).

However, with the [deprecation of FFP](https://www.opengl.org/wiki/History_of_OpenGL#Deprecation_Model) already being several years old,  and GLSL programming becoming more widespread, there is little reason to keep FFP around. The GL renderer does not use it at all, since we run our own shaders to handle all rendering operations, including lighting and texturing. We do incur in some redundancy by not removing it, since GL2ES1 still handles the FFP uniforms (transformation matrices, lighting parameters), but Processing does not use them.

**Comment by benfry** [comment]
So is your plan to remove it? Or are you asking whether you should? (FWIW, I definitely say remove it.)

**Comment by codeanticode** [comment]
Mainly the second, I wanted to get some feedback before going ahead.

**Comment by JakubValtar** [comment]
Are we done here?

**Comment by benfry** [comment]
That's for @codeanticode to answer.
