### ISSUE TITLE
Pr3.0a11 - Little bug in example code

### ISSUE THREAD

**Issue by roman30098** [processing/processing#3513]
Processing 3.0a11 - Windows64b
There is a missing ")" in example Tools/Simulate/ForcesWithVectors line 37:
Are:
if (liquid.contains(mover) {
Should be:
if (liquid.contains(mover)) {

Btw: Awesome project! :)

**Comment by alignedleft** [comment]
@roman30098 Great catch! That's fixed for the next release. Thanks.
