### ISSUE TITLE
Bug to update the size of the window.  

### ISSUE THREAD

**Issue by poqudrof** [processing/processing#3515]
Hey, 

-- low priority --

Firstly great work for the PSurface stuff, moving windows in Linux no longer crashes everything. It was a major flaw ! 
So I am updating my code to Processing 3, and I was used to have some hacks to set the size of the window in my library. I no longer call  size() to do this, but I call setSize after everything is loaded. 

I tried these two lines of code. I figured that the second one was the "new way". 
``` java
        applet.frame.setSize(frameSizeX, frameSizeY);
        applet.getSurface().setSize(frameSizeX, frameSizeY);
 ```
The second line leads to a nice crash : 

> handleDraw() called before finishing
> com.jogamp.opengl.GLException: Caught ThreadDeath: null on thread main-FPSAWTAnimator#00-Timer0

With the first line, it works with an warning message : 
> Use surface.setSize() instead of frame.setSize in Processing 3

I'm confused but it works :), so not much to worry for now right ?

Jeremy.

**Comment by poqudrof** [comment]
I found the solution, I update the solution in the  **post** method, so it does not interfere during the drawing. Both solution work this way.

**Comment by benfry** [comment]
The second is the correct method. And you should never, ever mess with the drawing surface while in the middle of drawing—that's why you got a legit OpenGL crash. That's not a Processing problem.
