### ISSUE TITLE
Foundation library examples should appear under "Core" or "Foundation"

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3524]
These are the current categories for Examples:

<img width="754" alt="screen shot 2015-08-01 at 2 04 08 pm" src="https://cloud.githubusercontent.com/assets/191758/9022914/3146ad7e-3856-11e5-8fea-0c6e00238279.png">

When the video and sound libraries are installed, their examples appear under "Libraries" above, however, they should appear under "Core Libraries."  We also discussed renaming "Core Libraries" to "Foundation Libraries."

**Comment by benfry** [comment]
Fixed for beta 3. I'm open to the "Foundation Libraries" change, though I'm not sure if it clarifies things enough or is worth the documentation change. Probably something for us to cover on a call.
