### ISSUE TITLE
Web camera listed by Capture.list() but fails "quietly" cam = new Capture

### ISSUE THREAD

**Issue by Bazmundi** [processing/processing#3525]
I have an old bloggie duo use as a webcam to work on the use of the unwrapped 360 degree lens as a visual collision detector for my robotics experiments.

Now the camera comes up in my windows driver list as a webcam.  I have used the free webcam software MyCam to view the Bloggie working as a webcam.

If I use the example code from Processing site for Capture (https://processing.org/reference/libraries/video/Capture.html)

The bloggie turns up in the Available list of cameras.  Although, confusingly it turns up as a number of cameras of alternate resolutions.  No matter, Capture appears to "see" the bloggie.

However, the cam = new Capture(...) returns null.
I have tried using various index values into cameras to, pick up alternate instances of the bloggie resolution instances, no no avail.  I have tried hard coding resolutions, frame rates, camera names etc. to no avail.  

MyCam reports the bloggie at a specific resolution and framerate so assuming that is the default I have made a special point of setting those parameters, to no avail.

Regardless, cam = new Capture(...) returns null.  There is no exception or other means to "explain" why the camera can be "seen" by Capture.list() but fails on creation.

**Comment by benfry** [comment]
Please post this in the correct location: https://github.com/processing/processing-video/issues
