### ISSUE TITLE
Run/Stop/Debug buttons do not fire if the mouse moves during the click

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3529]
Steps to reproduce:

1. Click and hold mouse on the button
2. Move mouse at least 1 px
3. Release the mouse button
4. Nothing happens

Expected result:

* as long as mouse down and mouse up happen over the button, the button should fire

**Comment by benfry** [comment]
Turns out that Java doesn't fire `mouseClicked()` if you move the mouse (at all) while clicking. Firing the button on press instead. Could do this on release but I think the UI will feel better this way.
