### ISSUE TITLE
Deleted tab still present in tab menu

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3534]
1. Create a tab
2. Open tab menu (button with small arrow) and delete the new tab
3. Open tab menu again, deleted tab is still present
![tab](https://cloud.githubusercontent.com/assets/3177098/9099827/6f6b6eb0-3ba2-11e5-87ac-3778aa3cbf1c.png)

**Comment by benfry** [comment]
Same problem as #3099 (the toolbar is not refreshed properly).
