### ISSUE TITLE
"Find in Reference" launching IE under Windows 10

### ISSUE THREAD

**Issue by shiv379** [processing/processing#3539]
Hi,

I am using Windows 10 and Processing seems to be working fine so far, however the "Find in Reference" feature seems to force use of Internet Explorer (which doesn't seem to work under Win10 for me), ignoring the default browser setting (Chrome) or Edge.

**Comment by benfry** [comment]
Is this with 3.0a11?

**Comment by shiv379** [comment]
Processing 2.2.1 for Windows.

**Comment by benfry** [comment]
Already fixed in the 3.0 releases.
