### ISSUE TITLE
error on size() when using exact size of screen 

### ISSUE THREAD

**Issue by liasomething** [processing/processing#3545]
in 3.0a11:
when using exactly the screen dimensions in size:
size(1920, 1080) 
i get 
IllegalStateException: fullSchreen() cannot be used here, see https://processing.org/reference/fullScreen_.html
(however, i can do 1921x1081 without problems... ;) )

sometimes i would like to have exactly 1920x1080 in a window (for instance to export images...) and not fullscreen.

not sure if this is a bug or if this is intended for some reason ?

**Comment by benfry** [comment]
Should be fixed in beta 1, posted yesterday.

**Comment by liasomething** [comment]
hm, just tested with 3.0 beta 1, still there...  same message.

**Comment by benfry** [comment]
Are you using P2D/P3D/OPENGL?

**Comment by liasomething** [comment]
i did not specify anything: size(1920, 1080).
but i tested now with:
 size(1920, 1080, P2D);
 size(1920, 1080, P3D);
 size(1920, 1080, OPENGL);
---> all three give me the error...

**Comment by benfry** [comment]
Nuts! Ok, will look into it. Thanks for checking.

**Comment by liasomething** [comment]
thanks for taking care of all this! :)

**Comment by benfry** [comment]
All set for the next release. Sorry for the trouble and thanks for using the 3.x series—I think you'll be much happier with it once all the kinks are worked out!

**Comment by liasomething** [comment]
cool, thanks!
i guess there is much less trouble on my side than on yours ;) 
and yes, 3 looks GREAT so far, all the debugging and stuff !!! 
very happy about it ! :)

**Comment by benfry** [comment]
Awesome, great to hear.
