### ISSUE TITLE
toggling between noLights and PointLight in draw() does not behave as expected

### ISSUE THREAD

**Issue by hype** [processing/processing#3546]
```
void setup() {
	size(600,600,P3D);
	background(153);	
}

void draw() {

	noStroke();
	fill(#FF3300); // orange
	rect(100, 100, 100, 100);

	pointLight(255, 0, 0,   width/2, 0, 0);
	pointLight(0, 255, 0,   width/2, height/2, 0);
	pointLight(0, 0, 255,   width/2, height, 0);

	// lets pretend you rock some 3D drawables here

	// now lets turn lights off,
	// so our rect gets displayed as expected, when draw() runs again
	noLights();
}
```
running this sketch our orange rect() is actually displayed as black... the only way I could get the orange rect to display as expected was actually to precede it with lights() which is odd.

**Comment by benfry** [comment]
Are you using beta 1? There were lighting changes there.

**Comment by hype** [comment]
@benfry yes sir. what's new convention?

**Comment by benfry** [comment]
@codeanticode or @JakubValtar will need to check on this one. The change was that geometry is properly flushed whenever a lighting change happens, so this may be a new problem that was introduced or bad syntax revealed by that fix.

**Comment by hype** [comment]
@benfry @codeanticode @JakubValtar understood... I'm just finishing up a new class (41 files) which has lighting as a major component... and I'm seeing a wide array of problems with lighting... if you'd like for me to zip up examples... please let me know whom and to where to send.

**Comment by codeanticode** [comment]
It is a regression introduced by https://github.com/processing/processing/issues/3533. Should be fixed with https://github.com/processing/processing/commit/a640a9e445cc2c73911a23ae8ecee3a0248454b8 and https://github.com/processing/processing/commit/47424b22326ba8636e92ca2cfd6dbdd7b04cd46b

**Comment by hype** [comment]
@codeanticode if/when there's a new PUSH I can PULL, I can stress test against a bunch sketches.

**Comment by codeanticode** [comment]
@hype the simple test you posted initially works after the fixes. Just pull the latest revision from the repo, and let me know how your more detailed tests go. Thank you!

**Comment by hype** [comment]
@codeanticode thanks Andres.

**Comment by hype** [comment]
ok to close this ?
