### ISSUE TITLE
Advanced-OpenGL / import to com.jogamp.opengl.GL2;

### ISSUE THREAD

**Issue by hype** [processing/processing#3547]
after pulling that latest from this morning... checking my shader specific sketches and reading this...
https://github.com/processing/processing/wiki/Advanced-OpenGL

as instructed I swapped my :
 
import javax.media.opengl.GL2;

to

import com.jogamp.opengl.GL2;

and get / "No library found for com.jogamp.opengl"

cc : @codeanticode

**Comment by benfry** [comment]
Fixed for beta 2.
