### ISSUE TITLE
add library fails

### ISSUE THREAD

**Issue by Diex** [processing/processing#3548]
when trying to install new libraries to new sketchbook folder, installation fails:
"Could not write to temporary directory."

mac osx 10.7
tried Ani and ControlP5.

**Comment by Diex** [comment]
just figure it out: after first run, restart processing, the folders are created into sketchbook.
examples       libraries      modes
then add library runs ok.

**Comment by benfry** [comment]
What version of Processing? We don't support  OS X 10.7 anymore.

**Comment by hype** [comment]
@benfry I had the same issue on 10.10.4.

1. download processing
2. when you install it prompts you for install folder I picked /Documents/Processing_3_0b1
3. it's at this point it created the folder but it didn't create the folders "libraries, modes or tools"
4. so trying to add libraries fail as the folders don't exist yet ?
5. as soon as I quit processing...  the "libraries, modes and tools" folders showed up.
6. restart processing... THEN... add libraries like minim, controlp5... etc.

**Comment by Diex** [comment]
processing 3. 

:)

**Comment by benfry** [comment]
Fixed for beta 2, thanks for the reports.
