### ISSUE TITLE
The wiggling cube sketch does not run properly in processing-3.0b1

### ISSUE THREAD

**Issue by monkstone** [processing/processing#3550]
Demos/Graphics/Wiggling
Half the faces do not display cut out circle, sketch freezes on 'w' with NullPointerException and crashes on 'spacebar'.
Actually just checked with processing-3.0a11 and half faces do not display cut out circle, but otherwise worked as expected. Processing-2.2.1 works fine.

**Comment by benfry** [comment]
Fixed for 3.0 beta 2.

**Comment by JakubValtar** [comment]
@benfry The example needs updating, because it does not draw contours counter-clockwise. I will make a pull request to processing-docs.

**Comment by benfry** [comment]
That'd be great, thank you.

**Comment by monkstone** [comment]
@JakubValtar I can confirm that the combination of your null pointer fix and re-writing of the sketch fix this see my refactored JRubyArt [sketch here](https://github.com/ruby-processing/samples4ruby-processing3/blob/master/processing_app/demos/graphics/wiggling.rb)
