### ISSUE TITLE
Breakpoint "jumps" after setting it (and subsequently hitting Enter) on a blank line

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3552]
To reproduce this issue:

1. Hit Enter a few times
2. Move the cursor to somewhere in between, and create a new breakpoint, like so:

![image](https://cloud.githubusercontent.com/assets/4526417/9151024/c9e50272-3e11-11e5-8a14-8ca8e0f5d801.png)

<ol start="3"><li>Hit Enter again:</li></ol>

![image](https://cloud.githubusercontent.com/assets/4526417/9151026/d5c7ac5c-3e11-11e5-9fd6-bd6ea2873e28.png)

NB: This only works when hitting Enter after setting a breakpoint on a blank line. Setting a breakpoint on a blank line, typing text below/above the line, and going back to the line and hitting Enter makes the breakpoint jump too.

**Comment by benfry** [comment]
@joelmoniz are you and @Manindra29 working on things like this? Or is this now a bug from your code or Manindra's that I'm now expected to fix?

**Comment by Manindra29** [comment]
Yes, assigned to @joelmoniz.
