### ISSUE TITLE
keyReleased() triggered when key is pressed in P2D/P3D

### ISSUE THREAD

**Issue by Natura-Time** [processing/processing#3556]
The `keyReleased()` event is triggered even if a key is being pressed and not released in P2D/P3D. (It works fine with the default renderer)

How to reproduce it : 

    void setup() {
      size(100, 100, P2D); // or size(100, 100, P3D);
    }
    
    void draw() {}
    
    void keyPressed() {
      print(key, keyPressed);
    }
    
    void keyReleased() {
      println(" ###", key, keyPressed);
    }

If you press a key (d for example) without releasing it, it will print this in the console : 

    d true ### d false
    d true ### d false
    d true ### d false
    d true ### d false
    d true ### d false
    d true ### d false
    d true ### d false
    // and so on ...

**Comment by benfry** [comment]
https://github.com/processing/processing/issues/1622
