### ISSUE TITLE
contribution manager: "Could not write to temporary directory."

### ISSUE THREAD

**Issue by emnullfuenf** [processing/processing#3557]
I just installed Processing 3.0b1 under OS X 10.9 and created a new sketch folder. When i am trying to install a mode or library it reports:
"Could not write to temporary directory."

Steps:
- Add Mode / Add Library
- Select Mode / Library
- Click "Install"
- Downloading progress bar fill up to 100%
-> "Could not write to temporary directory."

After closing and reopening Processing the problem is gone. Libraries and modes are installing fine.

**Comment by benfry** [comment]
Already fixed for beta 2: https://github.com/processing/processing/issues/3548
