### ISSUE TITLE
fullScreen() behaves different in JAVA2D, P2D/P3D

### ISSUE THREAD

**Issue by hamoid** [processing/processing#3560]
In my system, fullScreen() does cover the screen, but fullScreen(P2D) does not: the tiling window manager I use splits the window in two, showing the editor on the left and the sketch on the right. I can then press Win+F to actually make it full screen, which works fine.  It would be nice if it behaved the same way in both modes.

    void setup() {
      //fullScreen();
      fullScreen(P2D);
    }
    void draw() {
      ellipse(width/2, height/2, width, height);   
    }

// ArchLinux 64bit, Processing 3 beta 1, i3 window manager, Intel HD 4600

**Comment by benfry** [comment]
This is how your window manager is interacting with Java; it's out of our control unfortunately.

**Comment by hamoid** [comment]
Ok thanks!

**Comment by hamoid** [comment]
Ok, I thought that it was Processing related since it works fine when not using P2D/P3D. Cheers :)

**Comment by benfry** [comment]
Unfortunately it's just that JOGL and Java2D have completely different ways of working with the window system that aren't in sync with each other. Still possible that a fix may present itself, but I think our hands are tied.
