### ISSUE TITLE
Issue ? `frame` no longers contains informations in 3.0b1

### ISSUE THREAD

**Issue by Natura-Time** [processing/processing#3565]
`frame` no longer have width, height, insets, etc ... Everything returns 0. If we print `frame`, it prints this : 
`processing.core.PApplet$5[frame0,0,0,0x0,invalid,hidden,layout=java.awt.BorderLayout,title=,resizable,normal]`

Is it an issue or it's part of the changes in the 3.0 ? And if it will stay like that, how can we get informations from the window/frame now ?
Thanks !

**Comment by benfry** [comment]
`frame` should not be used in 3.0. It was never a documented part of the language, and it's no longer in use. We have basic features in there to not break the majority of user's code that used `frame`, but we haven't had time to document everything yet.

**Comment by Natura-Time** [comment]
Ok, I wasn't sure, thanks for the answer !
