### ISSUE TITLE
ControlP5frame example doesn't work in Processing 3

### ISSUE THREAD

**Issue by ewelinka** [processing/processing#3567]
This bug was already reported to controlP5 (https://github.com/sojamo/controlp5/issues/17), but I'm not sure if the issue is not caused by the changes in Processing (with Processing 2.2.1 it works fine), so I report it here also:

I just installed Processing 3 and installed controlP5 library ( the newest version 2.2.5 ) . I tried to run the examples and I got error message by running examples -> extra -> ControlP5frame. The error message is : 
The function "add()" expects parameters like: "add(Component)" 
and the error line is the line 45:
f.add(p);

With Processing 2.2.1 everything works fine.
I'm on Mac Yosemite, x64.

**Comment by benfry** [comment]
It's not a Processing bug. ControlP5 needs to be updated for Processing 3.
