### ISSUE TITLE
unable to run fullScreen() in setup() / processing-java 3.0b2

### ISSUE THREAD

**Issue by hype** [processing/processing#3570]
in lieu of

```
boolean sketchFullScreen() {
  return true;
}

Cannot override the final method from PApplet
```

throwing errors in processing-java (3.0b2)... I went to test...

```
void setup() {
	size(700, 700, P3D);
	fullScreen();
}
```

fails to run fullscreen / OSX 10.10.4 / Sublime Text 2 + processing-java (3.0b2) It launches (see it in dock for a brief second) and then quits immediately... "[Finished in 0.9s with exit code 1]"

I did however get it to work by doing the following...

```
void setup() {

}

void settings() {
	size(700, 700, P3D);
	fullScreen();
}
```

I was under the impression we could simply call ```fullScreen();``` in setup and NOT have to use the ```void settings()``` function...

AND ```settings()``` doesn't work unless it has the ```size()``` method. So if you write this...

```
void setup() {
	size(700, 700, P3D);
}

void settings() {
	fullScreen();
}
```

you get renderer errors:

Listening for transport dt_socket at address: 8311
noLights() is not available with this renderer.
translate(), or this particular variation of it, is not available with this renderer.
rotateX() can only be used with a renderer that supports 3D, such as P3D.
rotateY() can only be used with a renderer that supports 3D, such as P3D.
rotateZ() can only be used with a renderer that supports 3D, such as P3D.
lights() is not available with this renderer.
sphere() is not available with this renderer.
pointLight() is not available with this renderer.
texture() is not available with this renderer.
vertex() with x, y, and z coordinates can only be used with a renderer that supports 3D, such as P3D. Use a version without a z-coordinate instead.
Finished.
[Finished in 5.9s]

(I'd propose that if you don't specify ```size()``` in ```settings()``` it simply adopts it from ```setup()```, but that's maybe a separate discussion/issue)

this page https://github.com/processing/processing/wiki/Changes-in-3.0 makes it seem that, for sake of efficiency, that ```fullScreen()``` should run in ```setup()``` without using ```settings()``` ?

when opening the sketch in the P.3.0b2 IDE - it tells me that ```size()``` and ```fullScreen()``` cannot exist together... but we want them to... the ability to define a fixed ```size()``` and have ```fullScreen()``` take over the screen and expanding our top,right,bottom,left, etc.

to have ```fullScreen()``` in the ```setup()``` is the efficiency we want as a replacement for :

```
void setup() {
	size(700, 700, P3D);
}

boolean sketchFullScreen() {
	return true;
}
```

without having to restructure past sketches by moving ```size()``` to ```settings()``` just to use ```fullScreen()```

**Comment by benfry** [comment]
How about just `fullScreen(P3D)`. Don't mix `size()` and `fullScreen()`. 

If you're inside the PDE, `fullScreen()` or `size()` can be inside `setup()`. You should only bother with `settings()` if you're not using the PDE (or `processing-java`) to compile.

**Comment by hype** [comment]
@benfry I'd argue there's a huge advantage to being able to specify a ```size(700,700,P3D);``` and using...

```
boolean sketchFullScreen() {
    return true;
}
```

in tandem... this past arrangement meant I could define a virtual canvas 700,700 but fullscreen would expand deadspace top,right,bottom,left... this was especially helpful for using ScreenFlow to Desktop capture sketches for video.

so naturally when I saw ```fullScreen()``` I thought this meant I could streamline the above/past functionality :

```
void setup() {
    size(700, 700, P3D);
    fullScreen();
}
```

which is not the case... and opening past work to change...

```
void setup() {
    size(700, 700, P3D);
}

boolean sketchFullScreen() {
    return true;
}
```

to

```
void setup() {

}

void settings() {
    size(700, 700, P3D);
    fullScreen();
}
```

I'd argue is not helpful OR more efficient... just my 2 cents.

**Comment by hype** [comment]
@benfry let me also say it's Monday and I'm not 100% I understand your reply... ha ha ha... so please put me in my place... if I'm misunderstanding you.

**Comment by benfry** [comment]
`fullScreen(P3D)` gives you the same thing as what this used to do:

```
void setup() {
    size(700, 700, P3D);
}

boolean sketchFullScreen() {
    return true;
}
```

In the past, your 700x700 was ignored and it just made everything full screen. 

Are you thinking of "Presentation" mode, where the sketch shows at 700x700 and blanks the rest of the screen? If so, you can still do that with `size(700, 700, P3D)`, and start the sketch with cmd-shift-R, or you can add `--present` to the command line if you're writing your own `main()`.

**Comment by hype** [comment]
@benfry perfect... using

```
void settings() {
	fullScreen(P3D);
}
```

as an update... thank you for the clarity.

**Comment by nonlineari** [comment]
@joshuadavis P3D @benfry  I still having issue /off topic outputing that
 fullScreen() and how to save the output, seemed like the only way is
screencapture movie?
