### ISSUE TITLE
Shaders output to bottom left corner rather than full window in 3.0b2

### ISSUE THREAD

**Issue by gsuberland** [processing/processing#3572]
When applying shaders, I'm getting the post-processed output shown in the bottom left quarter of the window, and the original shown behind in the full window.

Here's my code:

	PShader testShader;
	
	void setup()
	{
	  size(1280, 1024, P3D); 
	  background(0);
	  fill(255);
	  stroke(0);
	  testShader = loadShader("simple.glsl");
	}

	void draw()
	{
	  background(0);
	  float frameTime = float(millis());
	  
	  pushMatrix();
	  translate((width / 2) + (sin(frameTime / 1000.0) * 512), height / 2);
	  rotateX(0.2);
	  rotateY(0.4);
	  box(200);
	  popMatrix();
	  
	  filter(testShader);
	}

Here's simple.glsl:

	#ifdef GL_ES
	precision mediump float;
	precision mediump int;
	#endif

	#define PROCESSING_TEXTURE_SHADER

	uniform sampler2D texture;

	varying vec4 vertColor;
	varying vec4 vertTexCoord;

	void main() {
		gl_FragColor = texture2D(texture, vertTexCoord.st);
	}

Hardware is as follows:

* GTX 980 Ti G1 Gaming 6144MB
* Intel i7-4790K
* Asus Maximus VII Hero
* 32GB RAM
* 4K + 1920x1200 monitors, Processing settings using 4K (primary) as default.

OS is Windows 10, but I've confirmed this on 8.1 on the same hardware too. The exact same code works perfectly in Processing 2.2.1.

Screenshots:

![processing3_bug](https://cloud.githubusercontent.com/assets/6430604/9187079/5703b97e-3fc4-11e5-93a2-c89eaa44a06a.png)

![processing3_bug2](https://cloud.githubusercontent.com/assets/6430604/9187102/9efbc7c6-3fc4-11e5-831b-3737b1b154d7.png)

**Comment by codeanticode** [comment]
changing the line https://github.com/processing/processing/blob/master/core/src/processing/opengl/PGraphics3D.java#L82 to modelview.translate(0, -height); fixes the problem, but not sure why @JakubValtar could you take a look?

**Comment by codeanticode** [comment]
found the actual reason, fixed with https://github.com/processing/processing/commit/715a4e88816702175101074ebb026e6de7affad2

**Comment by gsuberland** [comment]
Thanks for the prompt fix! :)
