### ISSUE TITLE
name for contributed examples

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3573]
Related to discussion with #3524, the name "Examples" for contributed example packages doesn't seem right given it's a "sub-category" under "Examples".   

Should we called it "Contributed"?  "Other"?  

<img width="758" alt="screen shot 2015-08-10 at 9 44 27 pm" src="https://cloud.githubusercontent.com/assets/191758/9188340/292a3be2-3fa9-11e5-8bd9-51095402f4e5.png">

**Comment by alignedleft** [comment]
Agreed. "Contributed" works. "Third-Party" feels more descriptive, but doesn't feel consistent with language we use elsewhere.

**Comment by benfry** [comment]
We have two kinds of "Contributed" in that window, however: Examples and Libraries. Perhaps this is what you're looking for?
* Core Libraries → Libraries
* Libraries → Contributed Libraries
* Examples → Contributed Examples

**Comment by benfry** [comment]
Which leaves us with this for beta 3:
<img width="365" alt="screen shot 2015-08-11 at 11 09 48 am" src="https://cloud.githubusercontent.com/assets/1623101/9201169/9c6d732e-4019-11e5-97ac-b20d2c369f47.png">
I see downsides for most options—they're all too long or not descriptive enough or not consistent enough—so I'm looking for input.

**Comment by alignedleft** [comment]
If I understand this, the examples for official Processing Foundation libraries are in "Libraries", while examples for all other libraries (3rd party) are in "Contributed Libraries".

Is there any reason to keep these separate? I don't think users care if a library is from us or someone else. They are all just "libraries".

So why not lump them all into a "Libraries" folder?  Cut "Contributed Libraries". Then "Contributed Examples" could keep the same name or be shortened to "Other Examples" (other as in, not originally part of your Processing installation).

**Comment by joelmoniz** [comment]
With respect to the too long/not descriptive enough problem, maybe we could add in something like a small description pane at the bottom? So the description might be hard-coded for each of the folders, and describe what the contributed example represents, and perhaps, later on, even parse the top-most comment of the main sketch and show that in the description?

**Comment by benfry** [comment]
@alignedleft We've always thought it was important to keep them separate. Otherwise we have a situation where people perceive all contributions to be part of Processing itself, and with that, all bugs/errors/inconsistencies are ours.

**Comment by alignedleft** [comment]
Ah, well we can't have that.

Some other options:

- "Other Libraries" and "Other Examples" (other, as in, not ours)
- "Installed Libraries" and "Installed Examples" (installed, as in, you had to install it yourself)
- "External Libraries" and "External Examples"

*Or* if it's worth it to complicate the folder structure, we could group third-party stuff together like:

```
Basics
Topics
Demos
Libraries
Third-Party
     Examples
     Libraries
```

**Comment by shiffman** [comment]
I like @alignedleft's last idea above (since having "examples" in the title of some is strange / redundant).  However, I prefer "contributed" over "third-party", i.e.

```
Basics
Topics
Demos
Libraries
Contributed
     Examples
     Libraries
```

**Comment by REAS** [comment]
I'm always not quite satisfied with the term "contributed", but I think we've been using it long enough that it would be arbitrary to change it unless there's something else that's clearly better. It has the advantage over the other options that it references the fact that other people (third-party sources) have offered this. So, I think we should stick with what is currently in 3.0b4 for reasons of consistency with our language for Processing 1 and 2.

**Comment by benfry** [comment]
All set; closing.
