### ISSUE TITLE
Invalid OS X code signature

### ISSUE THREAD

**Issue by semaperepelitsa** [processing/processing#3575]
I downloaded the latest app 3.0b2 and was warned about "unidentified developer" by OS X. I thought you didn't have the signature so I proceeded with launching it, adding it to the whitelist. Now, I learned that you do in fact have the signature, and I don't know how to remove it from the whitelist to show you the issue. However, I downloaded 3.0b1 and it has the same error:

<img width="532" alt="screen shot 2015-08-11 at 09 56 27" src="https://cloud.githubusercontent.com/assets/347921/9191977/a548e8b6-400f-11e5-8455-3167ec0dd499.png">

<img width="700" alt="screen shot 2015-08-11 at 10 03 53" src="https://cloud.githubusercontent.com/assets/347921/9192087/56686734-4010-11e5-82b4-6062bb6abff0.png">

How do I troubleshoot this? The download from Github must be authentic. I'm running OS X 10.10.4.

**Comment by benfry** [comment]
Thanks a lot for the report. I suspect it's legit and my certificate wasn't installed properly. I'm baffled that I received no errors during the code signing process, however, and haven't seen this on any other machines. I'll look into it today and get back shortly.

**Comment by benfry** [comment]
Hm, I'm not seeing anything wrong with [this tool](http://brockerhoff.net/RB/AppCheckerLite/): 

![screen shot 2015-08-11 at 3 49 01 pm](https://cloud.githubusercontent.com/assets/1623101/9208299/d99d536e-4040-11e5-9eb6-bf11abd57a3b.png)

Though code signing is dark magic, so I must be missing something...

**Comment by benfry** [comment]
And `codesign` tells me that it's properly passing:
```
% codesign --verify --deep --verbose=2 Processing\ 3.0b2.app
--prepared:/Users/fry/Desktop/Processing 3.0b2.app/Contents/PlugIns/jdk1.8.0_51.jdk
--validated:/Users/fry/Desktop/Processing 3.0b2.app/Contents/PlugIns/jdk1.8.0_51.jdk
Processing 3.0b2.app: valid on disk
Processing 3.0b2.app: satisfies its Designated Requirement
```
Is your system up to date with all security updates?

**Comment by benfry** [comment]
Tested on a clean machine and can't reproduce. I would make sure you have the latest security updates installed and that your clock is set correctly. If not, check Applications > Utilities > Console.app to see if it's printing any information about why it's failing. Or try the same `codesign` incantation on the command line as I used in the last comment, and see if it gives you any information about what's going on.

**Comment by semaperepelitsa** [comment]
Codesign works:

```
> codesign --verify --deep --verbose=2 Processing-3.0b1.app/
--prepared:/Users/sema/Downloads/Processing-3.0b1.app/Contents/PlugIns/jdk1.8.0_51.jdk
--validated:/Users/sema/Downloads/Processing-3.0b1.app/Contents/PlugIns/jdk1.8.0_51.jdk
Processing-3.0b1.app/: valid on disk
Processing-3.0b1.app/: satisfies its Designated Requirement
```

This is what I get in console when launching the app:

```
12/08/15 08:47:12,717 CoreServicesUIAgent[13865]: File /Users/sema/Downloads/Processing-3.0b1.app/Contents/Java/modes/java/application/launch4j/bin/windres failed on loadCmd /opt/local/lib/libgcc/libgcc_s.1.dylib
12/08/15 08:47:12,717 CoreServicesUIAgent[13865]: Fails dylib check
12/08/15 08:47:15,819 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000029.Processing[19779]) Service exited due to signal: Killed: 9
12/08/15 08:47:15,820 CoreServicesUIAgent[13865]: unexpected message <OS_xpc_error: <error: 0x7fff79b26c60> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x7fff79b26f70> { length = 18, contents = "Connection invalid" }
}>
```

**Comment by semaperepelitsa** [comment]
I have installed all the updates and my system time is sync with Apple time server.

**Comment by benfry** [comment]
Hm, that looks like something on your machine: `/opt/local/lib/libgcc/libgcc_s.1.dylib` doesn't exist on the build machine. Does that file exist on your machine? Do you have macports installed? If so, try renaming `/opt/local` to `/opt/local.hide` and try running Processing.

**Comment by semaperepelitsa** [comment]
It doesn't exist on my machine either! I have never installed Macports.

```
> ls /opt
ls: /opt: No such file or directory
```

I have Homebrew installed at /usr/local but that's a different location.

**Comment by benfry** [comment]
What steps did you use to download and install? (What browser, what version, did it auto-extract itself or did you have to double-click, etc.)

Only other thing I can think of is that `windres` is referring to an external library, which is [sort of disabled](https://developer.apple.com/library/mac/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG207) in 10.10.4. But I can't figure out why it would be failing on your machine and not for others.

**Comment by semaperepelitsa** [comment]
I've downloaded the ZIP archive via Chrome. Here is the SHA sum. Does it match your release?

```
c41efbd8b373404a390231e454fde976f2343cec  processing-3.0b1-macosx.zip
```

The link you provided looks to match my issue exactly. I tried `otool` as suggested and here is the result:

```
> otool -L /Users/sema/Downloads/Processing-3.0b1.app/Contents/Java/modes/java/application/launch4j/bin/windres
/Users/sema/Downloads/Processing-3.0b1.app/Contents/Java/modes/java/application/launch4j/bin/windres:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
	/opt/local/lib/libgcc/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

The binary `windres` references an external library, so my Gatekeeper rejects the app. Do you compile that Java thing yourself? Possibly, the build machine has macports and the compiler picks up the wrong thing?

**Comment by semaperepelitsa** [comment]
By the way, I think Command Line Tools do not include GCC for a few years already.

**Comment by semaperepelitsa** [comment]
Also, I didn't ask before, do you have this Security option enabled in System Preferences?

<img width="325" alt="screen shot 2015-08-12 at 22 13 54" src="https://cloud.githubusercontent.com/assets/347921/9234095/72c1efe2-413f-11e5-8fec-98a022770f61.png">

**Comment by benfry** [comment]
No, we don't compile the windres used in the beta releases (in 2.x releases). 

And yes, of course I'm testing with the "identified developers" setting turned on. 

Looks like we have a launch4j problem.

**Comment by benfry** [comment]
Found a different launch4j build that works on 10.8+ and doesn't have the /opt reference so we should be all set for 3.0 beta 4.

Still unclear why it passes Apple's checks and works on most(?) machines (yours is the first and only report of this, but we have a few thousand people using the beta on OS X), but who knows. Code signing is dark magic.
