### ISSUE TITLE
pixelDensity(2) not supported inBootcamp

### ISSUE THREAD

**Issue by Lachie9383** [processing/processing#3576]
When ``pixelDensity(2);`` is used in Processing running in Bootcamp, the console displays the error:

pixelDensity(2) is not available for this display

 My computer is a MacBook Pro 15″ with retina display running Windows 8.1 in Bootcamp. Is this addressable? Or is just a unavoidable consequence of using Bootcamp? I need to use Windows for the Kinect support.

**Comment by benfry** [comment]
No support on Windows yet: https://github.com/processing/processing/issues/2411
