### ISSUE TITLE
Keystone library broken but listed as compatible

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3578]
Keystone got broken by moving PGraphicsJava2D into a different package, but it is still listed as compatible.

I wonder if other libraries were affected as well but are still marked as compatible.

**Comment by JakubValtar** [comment]
Probably one for @prisonerjohn

**Comment by benfry** [comment]
Assigning @prisonerjohn, though I thought he'd made these changes already. Elie, is the new version not on the server yet?

**Comment by prisonerjohn** [comment]
The new version is up, but I probably missed a few broken ones. 

I just took keystone out of the list. Let me know if you find others with issues.

**Comment by benfry** [comment]
Thanks Elie.
