### ISSUE TITLE
Temp files in Processing 3

### ISSUE THREAD

**Issue by geraldar** [processing/processing#3580]
I would like to remind that the Processing does not delete the temporary files.

This issue has existed for more than 2 years (#1896, #2752).

This is very bad that Processing creates so many temporary folders in folder "%TEMP%\",
because a large number of files in temporary folder can slow down the operating system.
Better change temp path to "%TEMP%\Processing\" (#3428).
For example now I have in the "%TEMP%\" folder about 9000 processing temp folders.

Why do you ignore this problem so long?

It's easy to fix.
1. Change temp path from "%TEMP%\" to "%TEMP%\Processing\".
2. Delete all files from "%TEMP%\Processing\" when you exit
   (or not all and with a date more than one day/week/month).

This issue should have a high priority for release 3.0.

**Comment by benfry** [comment]
No need to re-file duplicates https://github.com/processing/processing/issues/1896

**Comment by geraldar** [comment]
Sorry for the duplicate.
I'm just tired of every time to remove these files manually.
@benfry, can you answer, is it planned to fix for versions 2.x and 3.x?
