### ISSUE TITLE
P2D and P3D sketches won't exceed screen size

### ISSUE THREAD

**Issue by REAS** [processing/processing#3584]
Sketches that have a size larger than the screen are resized to fit the screen in P2D and P3D on Mac OS X 10.10.3 on Processing 3 beta 3 and the prior betas as well. For example:

```
void setup() {
  size(200, 3000, P3D);
}

void draw() {
  line(0, 0, width, height);
}
```

**Comment by codeanticode** [comment]
this issue was originally reported in https://github.com/processing/processing/issues/3401
