### ISSUE TITLE
Processing is not working since version 3.0a8

### ISSUE THREAD

**Issue by gtitaev** [processing/processing#3588]
OS: Windows 7 SP1 x32
I have two problems in versions from 3.0a8 to 3.0b3.
Versions 1.5.1, 2.2.1 and 3.0a2 to 3.0a7 does not have these problems.

**I. Sketch window is not shown.**

1. Click Run sketch
2. Window is not shown. No error messages. In Task Manager, new process "java.exe" is running.
3. Click Stop sketch. In Task Manager, process "java.exe" doesn't stop.
4. Quit from Processing.
5. In Task Manager, process "java.exe" doesn't stop. I have to manually kill the process.

**II. Processing doesn't start.**

1. Delete file "preferences.txt" in folder C:\\[USER]\AppData\Roaming\Processing\
2. Run Processing. 
   - Splash screen is shown
   - Splash screen is closed
   - Processing is running.
3. Quit Processing.
4. Run Processing again.
   - Splash screen is shown.
   - In Task Manager. Processes "javaw.exe" and "processing.exe" is running.
   - And nothing happens.
   - After one minute splash screen is closed.
   - In Task Manager. Process "processing.exe" is stopped. Process "javaw.exe" doesn't stop.
   - I have to manually kill "javaw.exe" process.
5. I delete string "instance_server.port=61074" in file "preferences.txt" in folder C:\[USER]\AppData\Roaming\Processing\
6. Run Processing.
7. Processing is running.
8. Quit and Run Processing again.
9. Processing does not start again.
10. Again delete string "instance_server.port=61135" (Now another port number.)
11. Run Processing.
12. Processing is running.
13. I have to delete string "instance_server.port=" in file "preferences.txt" before each run.

**Comment by benfry** [comment]
A better place to get help with this is http://forum.processing.org. There are thousands of people actively using Processing on Windows since 3.0a8, and there's likely a problem with your machine or setup.

**Comment by geraldar** [comment]
The friend of mine has similar problems in 3.0b1.
Versions 2.2.1 and 3.0a5 works great.
Version 3.0b1 does not start if the file "C:\Users\[USERNAME]\AppData\Roaming\Processing\preferences.txt" exists.
And button "run sketch" not work too.

Later I'll try to test versions 3.0a7 and 3.0a8 on his computer and write the result.

**Comment by gtitaev** [comment]
I disabled the system proxy (in Internet Explorer) and these problems  have been solved.

Perhaps the emergence of these problems in 3.0a8 has something to do with this:
```
PROCESSING 3.0a8 (REV 0235) - 17 May 2015
...
[ akarshit contributions ]
...
+ Use system proxy by default
  https://github.com/processing/processing/issues/1476
  https://github.com/processing/processing/pull/3251
```
With enabled proxy not working versions from 3.0a8 to 3.0b7.
