### ISSUE TITLE
Text disappears in page tabs

### ISSUE THREAD

**Issue by hughes42** [processing/processing#3589]
I love using heaps of tabs to sort my code. When there are too many on the screen, the title of each sketch page disappears:

![capture](https://cloud.githubusercontent.com/assets/13776134/9242881/d8d084c4-41cb-11e5-97fe-22724c85230e.PNG)

Perhaps a way to mark certain tabs would be good (similar to when the yellow line appears if the page isn't saved). If I am working on something on one page and a class on another at the same time, I am sticking Blu-Tak to my monitor to mark which tabs I am currently working on.

Maybe a right click could add a coloured "marker" line?

**Comment by benfry** [comment]
Not a situation we're interested in supporting. If you want that many tabs, a full-featured IDE is a better choice.

**Comment by hughes42** [comment]
No worries!
Thanks for your hard work on making Processing great.
