### ISSUE TITLE
PVector lacks a PVector.add(PVector, float, float) method

### ISSUE THREAD

**Issue by teo1978** [processing/processing#3593]
With a "3D PVector" you can do:

    PVector mypv=new PVector(100, 200, 300); 
    mypv.add(10, 20, 30); // returns (110, 220, 330)

However, with a "2D PVector" you cannot do:

    PVector mypv=new PVector(100, 200); 
    mypv.add(10, 20); // compile error

I know, there's no such thing as a 2D PVector. PVector always has a z component and you could always do .add(x, y, 0). However, if you allow to write new PVector(x,y) omitting the z, giving the illusion that one is handling a 2D point without forcing to include a zero z component, it's inconsistent to not allow the same syntax and the same "illusion" when adding.

**Comment by benfry** [comment]
Your call, @shiffman. We'd need `sub()` as well.

**Comment by shiffman** [comment]
Yes, I am in favor.   I'm hesitant to add *new* functionality, but I think this is more of a case of cleaning up old functionality.  No new documentation is really required.   I also like the "illusion" of `PVector` objects being 2D or 3D and this helps with that.  I can implement if you like, just assign to me.

**Comment by benfry** [comment]
Nah, it's easy and I have the stuff open. All set for beta 4.

**Comment by teo1978** [comment]
What does that mean?
