### ISSUE TITLE
textSize not working in setup()

### ISSUE THREAD

**Issue by timpulver** [processing/processing#3594]
`textSize` only works in `draw()`, not in `setup()`.

**In setup:**  

```
void setup(){
  size(1024, 768);
  textSize(100);
}

void draw(){
  text("text", width/2, height/2);
}
```

Output:

![call in setup](http://i.imgur.com/nLakwOh.png)

**In draw:**

```
void setup(){
  size(1024, 768);
}

void draw(){
  textSize(100);
  text("text", width/2, height/2);
}
```

Output:

![call in draw](http://i.imgur.com/gjJ6aw0.png)

**Comment by benfry** [comment]
Works fine in the current default download of Processing, 3.0 beta 3.

<img width="1136" alt="screen shot 2015-08-14 at 9 18 21 am" src="https://cloud.githubusercontent.com/assets/1623101/9274636/7a748be2-4265-11e5-8cfa-d7ced2fa884b.png">

**Comment by timpulver** [comment]
Yes, sorry, tried with 3.0 beta 1.
