### ISSUE TITLE
java subdir in processing folder should be ONLY java without any processing related files

### ISSUE THREAD

**Issue by mark-orion** [processing/processing#3595]
The "java" sub directory should only contain a JRE and no processing related files. The reason I am proposing this is that I (and others probably as well) use the systems JRE or JDK to run Processing. While Processing 2x could be run by replacing the java folder with a symlink to the JRE / JDK you want to use, this does not seem to work anymore with Processing 3x: I am getting a "Font Sadness" popup complaining about missing fonts. Even when I install the missing fonts on my system they are not recognized by processing.

**Comment by benfry** [comment]
We test against a specific Java release and embedding that helps minimize the already ridiculous amount of cross-platform, cross-release testing we have to do with our tiny number of volunteers. There's no compelling (enough) reason to support swapping the JVM.
