### ISSUE TITLE
CM selected tabs are too tall

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3598]
When CM tabs are highlighted, the height of the tab shifts, to move up. It shouldn't move and become taller than the other tabs; only the color should change.

Note how "Libraries" here is a few pixels higher than the other tabs.

![screen shot 2015-08-14 at 2 59 08 pm](https://cloud.githubusercontent.com/assets/1034002/9284896/07bf3748-4295-11e5-9217-eb3445860d82.png)

**Comment by benfry** [comment]
#3703 merged, @alignedleft please close if fixed.

**Comment by benfry** [comment]
Taking over this one since it's not been fixed.

**Comment by benfry** [comment]
Fixed for beta 7.
