### ISSUE TITLE
CM blue bar missing

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3599]
In the reference mockup, there is a 1px tall horizontal light blue bar that separates the tabs from the content below.  Look closely here:

![screen shot 2015-08-14 at 3 01 06 pm](https://cloud.githubusercontent.com/assets/1034002/9284922/511541b2-4295-11e5-824e-a7e65b303231.png)

Currently, that bar doesn't appear:

![screen shot 2015-08-14 at 2 59 08 pm](https://cloud.githubusercontent.com/assets/1034002/9284929/67a2280a-4295-11e5-8c83-0172117e919b.png)

**Comment by benfry** [comment]
Fixed in #3636 for beta 5.
