### ISSUE TITLE
CM info panel should use correct typeface

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3601]
The info panel at bottom should use Source Sans Pro, just as other UI elements do. (This appears to be Times New Roman.)

![screen shot 2015-08-14 at 3 06 55 pm](https://cloud.githubusercontent.com/assets/1034002/9284991/21373ff8-4296-11e5-9a96-1d8613c22fbc.png)

**Comment by Akarshit** [comment]
@alignedleft I am not able to understand this, the info panel is using Sans already.

**Comment by alignedleft** [comment]
Note at the bottom where the linked text appears, the version number, author, and description. That all appears in Times (or similar). It should use the same font as in the tabs and list above.

**Comment by Akarshit** [comment]
Ok got it. Its working fine on linux, have to figure out what's wrong with mac.

**Comment by benfry** [comment]
Fixed in https://github.com/processing/processing/pull/3626
