### ISSUE TITLE
CM list should be sortable by status and author name

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3608]
Currently, the list can be sorted by Name, but not Status or Author.  Clicking the Status or Author column titles does nothing.

**Comment by Akarshit** [comment]
What's the order of sorting for status ?

**Comment by alignedleft** [comment]
Let's use a primary sort of:

- Installed (OK)
- Installed (update available)
- Installed (incompatible)
- Not yet installed (whether compatible or not)

Within each category, use a secondary sort by "Name".

Does that work?

**Comment by Akarshit** [comment]
Ok thanks

**Comment by Akarshit** [comment]
This has been implemented, so can be closed.
