### ISSUE TITLE
CM column widths change with selection

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3609]
This is a weird one. Here is the CM panel showing the Android mode selected. Note the column widths.

![screen shot 2015-08-14 at 9 47 45 pm](https://cloud.githubusercontent.com/assets/1034002/9287532/3c61eaa2-42ce-11e5-85a2-ae117d38179f.png)

Now, when I select the Python mode in the list (which is disabled and incompatible), the Name column jumps to be much wider, pushing the Author column (and install/update/remove buttons) out to the right.

![screen shot 2015-08-14 at 9 47 55 pm](https://cloud.githubusercontent.com/assets/1034002/9287535/507e6588-42ce-11e5-8173-645ed592121f.png)

The column widths should not change when the selection changes.

**Comment by Akarshit** [comment]
@benfry I am unable to track the exact cause of the issue, but i have found out that this is occurring in libraries whose pretty version contains some text.  
These libraries are - 
1. Python - prettyVersion=Build 0412, built 2015/07/08 14:03
2. Syphon - prettyVersion=1.0-RC3
3. HE_Mesh 2014 - prettyVersion=2.0.15 „Random”
I think this is occurring because of somewhere a exception getting thrown when these are tried to convert to a integer form or something like that.
Do you have any idea regarding this.

**Comment by benfry** [comment]
I don't really understand--the point of prettyVersion is that it can contain text. So all of them should.

**Comment by Akarshit** [comment]
I am sure about this because if i edit the contribs.txt and change Python's prettyVersion to something like 01 the column width doesn't change when selecting Python now.

**Comment by Akarshit** [comment]
@benfry i figured out what was wrong. Actually there is a label above the update button which shows text like "Version `prettyVersion` available/installed". This was set invisible but coded to occupy space still. This was causing the statusPanel to resize.  
One of a solution would be to extract the version part from the `prettyVersion` but to do this all the libraries having different forms of prettyVersion would require a check. I was wondering if this was supposed to be done at server-side ?

**Comment by benfry** [comment]
No, don't mess with the contents of `prettyVersion`. The Python Mode is an issue that should be fixed separately in contribs—that's a whole build string he's using, not a version. But even in fixing that, it sounds like you're looking for ways to paper over something bad in the code. There shouldn't be a reason that columns are resizing when a user clicks different rows in an interface.

**Comment by Akarshit** [comment]
I think i was not able to express my self clearly.  
When i select a contibution there is text displayed below the install button like below
![screenshot from 2015-08-16 19 14 53](https://cloud.githubusercontent.com/assets/7762605/9293520/882e23b4-444b-11e5-8f1e-c61a19f5c368.png)  
When Python mode is selected the actual size of statusPanel increases to accommodate the text like below 
![screenshot from 2015-08-16 19 15 32](https://cloud.githubusercontent.com/assets/7762605/9293548/aa6f20ee-444c-11e5-82fb-e8a177d1363b.png)

  
This is causing the table to widen.

**Comment by benfry** [comment]
Why not set the maximum width of that `JLabel` (or whatever it is) to the width of the buttons?

**Comment by benfry** [comment]
Fixed(?) with https://github.com/processing/processing/pull/3675
