### ISSUE TITLE
CM: Enable arrow keys for navigating list

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3610]
If it's easy to implement, it would be nice to be able to use the up/down arrow keys to change the selection in the CM list. Currently, I have to click on each item to select it and view details in the info panel. But it would be nice to be able to just arrow up or down to navigate the list more quickly.

**Comment by Akarshit** [comment]
Ok sure, btw this is there in the updates tab.

**Comment by alignedleft** [comment]
Thanks. Unfortunately, I'm not able to test the Updates tab because I am already all up-to-date. :)

**Comment by Akarshit** [comment]
@alignedleft By the look of status icons in the screenshot you posted [here](https://github.com/processing/processing/pull/3626#issuecomment-131417661) i guess you have nothing installed. :smile:

**Comment by benfry** [comment]
Closed with #3631.
