### ISSUE TITLE
CM tab order

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3613]
Currently, the tab order in the CM is:

- Tools
- Libraries
- Modes
- Examples
- Updates (at far right)

Yet I think the order should be:

- Examples
- Libraries
- Modes
- Tools
- Updates (at far right)

That order is alphabetical, and also happens to flow sort of from least technical (Examples) to most technical (Modes and Tools).  Before we make this change, however, I'd like to hear if others agree on this order.

**Comment by Akarshit** [comment]
Also specify the order in the rows of update tab

**Comment by alignedleft** [comment]
Do you mean the sort order? I think items could be sorted by Name alphabetically as the default sort (just as it appears is being done in the other tabs).

**Comment by Akarshit** [comment]
No i mean the order for various categories of updates ( tools, libraries, examples(?) , modes)

**Comment by alignedleft** [comment]
Ah, of course, thanks. Yes, pending input from others, once we decide on a (left to right) tab order here, let's use the same (top to bottom) order for grouping updates in the updates list. Thanks.

**Comment by Akarshit** [comment]
@alignedleft Is the order given above finalized ?

**Comment by alignedleft** [comment]
@Akarshit I am working on soliciting feedback and will get back to you soon.

**Comment by benfry** [comment]
My vote would be Libraries, Modes, Tools, Examples, then Updates on the far right, with the idea being that 95% of users will install at least one library, two thirds will install a mode, only “power users” will install a tool, and the Examples are so new that it’ll take a little while to catch on. (I found the current ordering/what's now in the build a little awkward/unfamiliar.)

But maybe I could be convinced that Examples should be all the way at the left (with the argument that they'll be very useful/important for the future) and that would make everything alphabetical order as well: Examples, Libraries, Modes, Tools, Updates (like you have above).

**Comment by REAS** [comment]
I'm with Ben on this one, including the logic and soft twist.

**Comment by alignedleft** [comment]
OK, thanks, @benfry and @REAS.

@Akarshit let's go with what Ben proposed (even though it's not alphabetical!). From left to right:

* Libraries
* Modes
* Tools
* Examples
* Updates
