### ISSUE TITLE
Topics/Shaders/BlurFilter needs glReadBuffer (unavailable in GLES2)

### ISSUE THREAD

**Issue by gohai** [processing/processing#3620]
Please close if this is expected behavior - I am currently testing all P2D/P3D examples with GLES2 hardware, and came across a few examples that try to use functions unavailable to GLES2.

The BlurFilter example depends on glReadBuffer, which is [not available](https://www.khronos.org/opengles/sdk/docs/man3/html/glReadBuffer.xhtml) in GLES2.

**Comment by gohai** [comment]
Not sure if this even feasible without - see [this StackOverflow thread](http://stackoverflow.com/questions/25084456/glreadbuffer-vs-glreadbuffernv-in-opengl-es-2-0).

The list of extensions supported by this particular hardware: GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_APPLE_rgb_422 GL_EXT_debug_marker

**Comment by JakubValtar** [comment]
Does it display a message like "GL function ... is not available on this hardware (or driver)"?

**Comment by gohai** [comment]
It did back when I tested it.

**Comment by JakubValtar** [comment]
I think this is expected behavior, it's not supported on your hardware and we tell you that. It's working on all desktops though and it will be supported in ES3 (when we eventually move to it) so that's why we are keeping it.

**Comment by gohai** [comment]
Sounds good - closing.
