### ISSUE TITLE
ctrl+r not restarting sketch when debug is enabled

### ISSUE THREAD

**Issue by colouredmirrorball** [processing/processing#3623]
Not sure if that's intended or not but when the sketch is running and debugging is enabled, hitting ctrl+r in the IDE does not restart the sketch. If that's the expected behaviour, is it then possible to have a shortcut to stop the sketch? (Maybe that's a good idea anyway).

(version 3.0b3)

**Comment by benfry** [comment]
Fixed for 3.0 beta 4, thanks for the report.
