### ISSUE TITLE
CM: filtering standard/accented characters

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3627]
Currently in the CM, go to the Tools tab. Note the "Bézier Editor" in the list. In the filter box, type "bez" (note no accent on the `e` character).

If this is easy to implement, it would be useful to change the filter logic to accept non-accented characters in place of their accented counterparts. (Sorry, I don't know the technical term for this, but it is common search/filter behavior.)  So, for example, entering either "bez" or "béz" would both result in the "Bézier Editor" appearing in the list.

This is useful because many people don't know how to type the accented characters, or want to search/filter quickly without doing so.

**Comment by benfry** [comment]
Merged into beta 4.
