### ISSUE TITLE
Please help.

### ISSUE THREAD

**Issue by jokedd** [processing/processing#3634]
Greetings.
First,my English is poor, so sorry about this.

I'm interested in Processing, but I don't have any knowledge with any code or java or program. Right now I want to get two idea from the Processing,( 1. load one image and falling down to the bottom and  explode as small point (random strokeWeight)  (2.One Point move from left to right and the back ground is fill with the other point and when the moving point come through they will separate and stop by a load image).

Is there any one could help me(recommand me with the code or and bood that can help me to deal with these two pic)? I'm so appreciate for your reading and help.

Thanks again!

**Comment by benfry** [comment]
Please use http://forum.processing.org for questions like this.
