### ISSUE TITLE
access frameCount leads to performance degradation

### ISSUE THREAD

**Issue by rtpg** [processing/processing#3637]
(using Java backend and the `Processing.app` editor, if that's important)

I'm writing a simple program, and running into some strange issues regarding accessing `frameCount`.

```
color bg = color(200,200,200);
color white = color(255,255,255);
void setup(){
  size(500, 500);
  background(bg);
  frameRate(30);
}

float pulse(float t){
   return 20*sin(t/8);
}

void draw(){
  background(bg);
  fill(white);
  ellipse(width/2,height/2,150+pulse(frameCount),150+pulse(frameCount));
}
```

This program runs more or less fine, and makes a circle that is growing and shrinking slowly.

However, if I change my implementation of pulse to:

```
float pulse(float t){
   return 20*sin(frameCount/8);
}
```

Everything runs _much_ slower. Like, 3 frames per second instead of 30. Not quite sure what could trigger this

**Comment by benfry** [comment]
You're imagining it. You're dividing two integers by each other, so the result is an integer, and `pulse()` is stair-stepped. Divide `frameCount` by `8.0` instead of `8` and it'll make the animation smooth.

**Comment by rtpg** [comment]
oh, right, that makes complete sense. Thanks for the clarification
