### ISSUE TITLE
zip corrupt

### ISSUE THREAD

**Issue by azrawasia** [processing/processing#3639]
i m unable to download 

after download it says xzip is corrupt download again

i tried 64 and 32 bit versions twice

**Comment by azrawasia** [comment]
![error zip](https://cloud.githubusercontent.com/assets/678510/9294514/d8e2a04c-4468-11e5-8927-54a8c3606946.png)

**Comment by benfry** [comment]
Downloaded the 64-bit version on Windows 7 (64-bit) and it looks fine here:
<img width="860" alt="screen shot 2015-08-17 at 10 44 53 am" src="https://cloud.githubusercontent.com/assets/1623101/9307555/10577b24-44cd-11e5-935e-d7d900a46241.png">
Check to see if your .zip file is very small (and is instead the text of an error page), you may be getting blocked by your internet provider.
