### ISSUE TITLE
CM: Info panel text color and alignment

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3642]
The text in the info panel of the CM should be left aligned with the contents of the "Name" column directly above it. So, for example, in this screenshot of the current state of things, "Ani 2.7" in the info panel (and the text below that) should be pushed over to the right a few pixels, so it aligned exactly with "BRigid" directly above it.

![screen shot 2015-08-16 at 3 01 49 pm](https://cloud.githubusercontent.com/assets/1034002/9295598/e16c7706-4427-11e5-8f6a-13397ca48933.png)

In addition, the linked text should not be blue or underlined. It should be black and not underlined (but still clickable). Please reference the latest mockup, as we are trying to match this as close as humanly possible (colors, alignment, typeface, pixel spacing):

![james s mockup](https://cloud.githubusercontent.com/assets/1034002/9295605/2e6322c6-4428-11e5-9a87-a81a8e0ca30f.png)

**Comment by Lachie9383** [comment]
Who better to post this issue than Mr Alignedleft himself :)

**Comment by benfry** [comment]
@alignedleft This is merged in #3684, please close this if it's fixed for you.

**Comment by alignedleft** [comment]
@Akarshit Linked text still appears blue and underlined, when it should be black, no underline.

Alignment of the text is better, but the info panel text really should be moved over to the right just a few pixels.

**Comment by alignedleft** [comment]
@Akarshit looks great, thank you!
