### ISSUE TITLE
CM: Button formatting

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3643]
The Install/Update/Remove buttons should match the design shown in the mockup as closely as possible. Changes I see that are needed:

- buttons should be wider, to match the width of the Author column above
- buttons need more internal padding, between the button edges and the image and text within each button
- buttons should not have a drop shadow, only a thin, 1px border with rounded corners
- buttons need the icons designed by James, as shown here (we already need other icons from him for #3478)
- button vertical spacing should match the mockup, but that means the space below "Install" will disappear. Could the text and a progress bar that currently live here move below the "Remove" button? (Would this make sense in terms of UI?)

The current state:

![screen shot 2015-08-16 at 3 01 49 pm](https://cloud.githubusercontent.com/assets/1034002/9295615/6c80c4f0-4428-11e5-9b4e-c4a6f34c880a.png)

The mockup:

![james s mockup](https://cloud.githubusercontent.com/assets/1034002/9295613/6a1f79f4-4428-11e5-820f-9026f64d6d92.png)

**Comment by jamesjgrady** [comment]
@alignedleft buttons are on the way.

**Comment by Akarshit** [comment]
@alignedleft In the third point
>buttons should not have a drop shadow, only a thin, 1px border with rounded corners
This is the way OS renders buttons. I don't think that could be done away with without introducing inconsistency, because even if the button is changed it would be difficult to change the category dropdown.

**Comment by alignedleft** [comment]
@Akarshit Thank you for asking about this. Please disregard point number 3 above. For now, let's use the standard (non-customized) buttons and dropdown UI elements (as you have it already). The alignment of things is more important than customizing their styling.

Please let me know if you have more questions about this!

**Comment by benfry** [comment]
I think I've fixed the remaining issues here this past weekend, and they'll be in 3.0 beta 7 (tweaked alignment, size, added 2x retina versions of the icons). If you find anything that's not done, let's open a new issues for specific problems.
