### ISSUE TITLE
CM: Category dropdown alignment

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3644]
The category dropdown should be left-aligned with the left edge of the "Author" column below it.

Current state:

![screen shot 2015-08-16 at 3 01 49 pm](https://cloud.githubusercontent.com/assets/1034002/9295648/5e4bdf18-4429-11e5-9e4f-d48e4cc8d44c.png)

Mockup:

![james s mockup](https://cloud.githubusercontent.com/assets/1034002/9295649/613b8700-4429-11e5-8d28-cfdfc9e411f6.png)

**Comment by benfry** [comment]
@alignedleft Please confirm and close.

**Comment by alignedleft** [comment]
@Akarshit This is better, but not perfect. This should be aligned as in the mockup, but the drop down is too far to the right.  See:

![screen shot 2015-08-19 at 12 40 19 pm](https://cloud.githubusercontent.com/assets/1034002/9367007/9b6031ea-466f-11e5-8bd8-1c81970ff39a.png)

**Comment by Akarshit** [comment]
@alignedleft Please check now.

**Comment by alignedleft** [comment]
Will do, but I won't be able to check on this or reply to other issues until tomorrow morning. Thanks.

**Comment by benfry** [comment]
https://github.com/processing/processing/pull/3669
