### ISSUE TITLE
Release 3.0 Beta 4 missing?

### ISSUE THREAD

**Issue by solange** [processing/processing#3645]
Hello, 
The links to the latest stable release (3.0 beta 4) on the processing.org download page all lead to 'page not found' and the latest release in this repository is 3.0b3.  

Where can I find 3.0b4?

Cheers

**Comment by REAS** [comment]
This is a mistake that I just corrected. 3.0b3 is the latest today. Thanks for the report.

**Comment by solange** [comment]
Thanks Reas.
