### ISSUE TITLE
Processing for OSX 10.10.4?

### ISSUE THREAD

**Issue by Simcat** [processing/processing#3647]
I'm currently reading the Processing book Reas and Fry. The download link for the editor isn't currently working. I found a link  to p5* but it wont launch on 10.10.4. Perhaps there isn't a version that works on OSX 10.10.4? If someone could let me know I'd really appreciate it. Thanks!

**Comment by benfry** [comment]
Sorry, the download link was broken for a few hours on Sunday. Should be fine now.
