### ISSUE TITLE
"Your sketch has been modified externally" with encrypted OS X volumes

### ISSUE THREAD

**Issue by 1deadpixl** [processing/processing#3650]
Everytime I open an example from the Examples menu, Stop the execution of a running example sketch or the Processing regains focus with an example sketch open, the warning "Your sketch has been modified externally." appears and prompts me to reload the sketch. Clicking Yes results in an endless loop as it reloads the sketch (without any changes occurring in the code) and then tells me the same thing again. Clicking No dismisses the dialog until the next action which causes Processing to think that the sketch has changed.

**Comment by benfry** [comment]
Is Processing on a USB drive, i.e. https://github.com/processing/processing/issues/3387 ?

**Comment by 1deadpixl** [comment]
No. Processing is stored in ~/Applications/ and the sketchbook is in ~/Development/Processing 3. New sketchbook got created when first launching the new Processing.

**Comment by benfry** [comment]
And this is beta 4 on OS X 10.10 and just standard formatting for the drive (i.e. Journaled, not case-sensitive)?

**Comment by 1deadpixl** [comment]
Yea, running OS X 10.10.4. The file system is Mac OS Extended (Journaled, Encrypted) per Disk Utility; untouched from Apple.
I've been trying to get beta 4 this morning, on a terrible internet connection right now though. I get the error as reported on beta 3. Once I get b4 up and running I will report back.

**Comment by benfry** [comment]
Ah, the “encrypted” may be the thing... That would make (some) sense.

**Comment by 1deadpixl** [comment]
Encrypting the file system was the default option from Apple during system setup. I've been running Processing 1 and 2 with no problems on the same configuration. Just been having the problem with 3. And beta 4 still has the same problem.

**Comment by benfry** [comment]
Yup, aware of it being the default; will look into it. For now, just turn off the auto-detect.

**Comment by 1deadpixl** [comment]
Sounds good. Thanks for the help. Really appreciate your responsiveness.

**Comment by 1deadpixl** [comment]
Actually, couldn't find the option for turning off auto-detect, but set editor.watcher to false in preferences.txt. That did fix the problem with the prompts. Is that the setting you're referring to?

**Comment by benfry** [comment]
Yes, that's the one. I'd intended to add it to Preferences because we were having so many problems with it, but apparently I didn't get around to doing so. The original submitter has rewritten the detection code four or five times but it's still problematic.

**Comment by benfry** [comment]
Can you try this pre-release and report back the results? 
http://download.processing.org/processing-150915b-macosx.zip

It should fix the infinite loop problem, and also print messages to the console about why it's updating the file. Could you paste them here?

**Comment by 1deadpixl** [comment]
Looks like it's fixed! No more dialog box complaining about the example being modified. I tried some of the included examples as well as a contributed example.

**Comment by benfry** [comment]
Great! Thanks for trying it out. 

That version has "debug" mode turned on, so when there are external changes you'll see things in the console. But the final release won't have that.
