### ISSUE TITLE
Issue Connecting Novation Launchpad

### ISSUE THREAD

**Issue by egrissino** [processing/processing#3653]
I am attempting to control my Novation Launchpad with Processing software. I have found a library that is made to do just this (https://github.com/rngtng/launchpad). I have installed the library correctly but when i load an example and attempt to run it, i receive an error, it is coming from a statement inside of my, void setup(){}, function. The statement is as follows:   launchpad = new Launchpad(this);. so all together i have 
void setup() {
  launchpad = new Launchpad(this);
}

The error is as follows: NoSuchMethodError: You may be using a library that's incompatible with this version of Processing.

I have tried to uninstall and reinstall the library and restart the program. neither have worked. also, i do not recieve any errors or problems when i open the program before running.

**Comment by benfry** [comment]
Just like the error says, that library is incompatible with the version of Processing that you're using. Please contact the library author about updating their software.
