### ISSUE TITLE
PDE window leaks undisposed Timer objects even when closed

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3655]
1) Run PDE
2) Open jVisualVM
3) Open new PDE window File/New
4) Bunch of new threads appear
5) Close the new PDE window
6) Timer-xx thread created with the new PDE stays alive

After trying out some examples I have 30 waiting timer threads here (one for each exmple). Not good.

**Comment by benfry** [comment]
What's creating the thread?

**Comment by JakubValtar** [comment]
Don't know, it get's created when I create a new PDE window. Maybe error checker is using it to run periodically?

**Comment by benfry** [comment]
Try setting `DISABLE_CARET = true` inside `JEditTextArea` and see if that fixes it.

**Comment by JakubValtar** [comment]
It's `Timer timer` in `processing.ap.ui.Editor`.

**Comment by benfry** [comment]
!#%#@ not my code... Try with my most recent commit?

**Comment by JakubValtar** [comment]
Solved.
