### ISSUE TITLE
_2X renderers don't exist in Processing 3

### ISSUE THREAD

**Issue by 1deadpixl** [processing/processing#3657]
Just saw the documentation for the new high-resolution renderers on Environment documentation page (https://processing.org/reference/environment/#Renderers), but I get a "Variable not found" error when trying to use them in Processing 3.0b4 running on OS X 10.10.4.

**Comment by shiffman** [comment]
This is a documentation error.  The new method for dealing with "2X" rendering is `pixelDensity()`.

https://processing.org/reference/pixelDensity_.html

Could you please re-file this issue at https://github.com/processing/processing-docs/issues?

Thanks!
