### ISSUE TITLE
Replace startup & about screen for 3.0

### ISSUE THREAD

**Issue by benfry** [processing/processing#3665]
Screen still says "alpha" instead of "beta", but more importantly, needs replacement with final design for 3.0.

**Comment by benfry** [comment]
This is one for @jamesjgrady to design when he has a chance, and I can implement.

**Comment by jamesjgrady** [comment]
Ben, let me know what you think of this.

![150921-launch-screen-3 0-001](https://cloud.githubusercontent.com/assets/2600893/10009487/ad381562-60ab-11e5-8ed4-3024a83de0c3.png)

**Comment by benfry** [comment]
Works for me; though we could go even more ambitious with it—we're not wedded to the old design/layout/shape so you're free to move in a new direction.

**Comment by jamesjgrady** [comment]
Ok, I can think about this some more.

**Comment by jamesjgrady** [comment]
Making it round. @benfry we can chat after lunch.
 
![150929-launch-screen-3 0-003](https://cloud.githubusercontent.com/assets/2600893/10171261/349dc7da-66a7-11e5-9fc3-f1cea9f5e99c.png)

**Comment by jamesjgrady** [comment]
Revised layout. It matches the proportions of the default editor which I think feels nice. Let me know if you think I should continue exploring other options. If this is good, I'll provide 1 and 2x versions.

![150929-launch-screen-004](https://cloud.githubusercontent.com/assets/2600893/10177433/337eee30-66c8-11e5-9baa-2280ffa4c857.png)

**Comment by REAS** [comment]
I like the last option if you do too. We need to "3.0 beta" text to be dynamic, so that should be coordinated with Ben. Can you make the copyright numbers "tabular figures" so they are monospaced and align?

**Comment by jamesjgrady** [comment]
More refinements. Let me know what you think of this option.

![150929-launch-screen-005](https://cloud.githubusercontent.com/assets/2600893/10179086/afba1d04-66d1-11e5-88e8-2b6358710eed.png)

**Comment by REAS** [comment]
Works for me and thank you! It's for Ben.

**Comment by jamesjgrady** [comment]
not sure where to check these guys into so here is the 1 and 2x versions.

![150929-launch-screen-3 0-1x](https://cloud.githubusercontent.com/assets/2600893/10179498/52faf6e4-66d4-11e5-9ad9-ff8e6c3ad64b.png)
![150929-launch-screen-3 0-2x](https://cloud.githubusercontent.com/assets/2600893/10179499/52fe4588-66d4-11e5-98f8-15ae6377e6f7.png)

**Comment by REAS** [comment]
I'll do it! Thanks again James.

**Comment by benfry** [comment]
Lemme take care of it—I need to change how they're handled.

**Comment by REAS** [comment]
OK... standing down.

**Comment by benfry** [comment]
All set!
