### ISSUE TITLE
CM: Category dropdown disabled except for Libraries

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3668]
Do we not have any categories for Examples, Modes, and Tools? If not, perhaps we should just hide this dropdown rather than disabling it. (A grayed out dropdown appears as though there is a circumstance in which it *could* be enabled, but that's not the case here.)

Correct me if I'm wrong!

**Comment by Akarshit** [comment]
We currently don't have any categories for  Examples, Modes, and Tools.  
Hiding it might look inconsistent (just saying).

**Comment by alignedleft** [comment]
I normally am opposed to inconsistency, but I also think it's confusing to show a disabled dropdown in a context when it can never be *en*abled.

What do others think? @shiffman?

**Comment by shiffman** [comment]
I think I would prefer it hidden as well.  Disabling it feels like it is "broken" to me.   I can imagine a future where we have categories for these other contributions in which case we can re-enable it.

**Comment by benfry** [comment]
Closing with https://github.com/processing/processing/pull/3676
