### ISSUE TITLE
mouseY in P2D

### ISSUE THREAD

**Issue by Cmxu** [processing/processing#3673]
mouseY is reported to be higher than the mouse's actual position when using P2D. In the example below, I have found that the rectangle is drawn above the mouse.
```
void setup(){
  size(800,800,P2D);
  background(255);
}

void draw(){
  background(255);
  rect(mouseX, mouseY, 5,5);
}
```
When you do this, it's fine.
```
void setup(){
  size(800,800);
  background(255);
}

void draw(){
  background(255);
  rect(mouseX, mouseY, 5,5);
}
```

**Comment by benfry** [comment]
How many pixels tall is your screen?

**Comment by codeanticode** [comment]
might be related to https://github.com/processing/processing/issues/3401, @Cmxu what is the resolution of your screen?

**Comment by benfry** [comment]
No response since the initial report; let's assume it's #3401.
