### ISSUE TITLE
CM - Label below the Install button is not visible

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3683]

**Comment by alignedleft** [comment]
Not sure what this issue was, and there is no description, *and* it appears to be resolved, so I'm closing this. :-)

**Comment by Akarshit** [comment]
Well for future reference the issue was that the label(0.2.0 installed) was not getting displayed while selecting a library.
![screenshot from 2015-08-25 02 05 38](https://cloud.githubusercontent.com/assets/7762605/9451753/1e36a6be-4ace-11e5-994d-33bbb5d4a510.png)
@alignedleft Do we still need this display as we are displaying the version number with the name.

**Comment by alignedleft** [comment]
@Akarshit In the case of this screenshot, when the installed version is also the most current version, no, I don't think we need to show the version number a second time.

But what if this library had a newer version available? Then v 0.2.0 would appear on the left side of the panel (adjacent the lib name), and we'd also show the current version (e.g., 0.5) on the right side, to indicate the newer version available.

Does that help?

**Comment by Akarshit** [comment]
@alignedleft Do you want me to hide the label when there is no update available ?
