### ISSUE TITLE
Wrong positioning of circles in SVG shapes

### ISSUE THREAD

**Issue by sinuit** [processing/processing#3685]
With Processing 3.0 (I used 3.0b4) circles in SVG shapes are drawn to the wrong position. The following SVG file should look like this:

![a01](https://cloud.githubusercontent.com/assets/2828139/9404640/8778e6da-47f1-11e5-829b-a78ccf1a6142.png)

```
<svg version="1.1" id="Ebene_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100px" height="100px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
<circle fill="#1A171B" cx="50" cy="50" r="50"/>
<circle fill="#FFFFFF" cx="50" cy="50" r="43.75"/>
<circle fill="#1A171B" cx="50" cy="50" r="37.5"/>
<circle fill="#FFFFFF" cx="50" cy="50" r="31.25"/>
<circle fill="#1A171B" cx="50" cy="50" r="25"/>
<circle fill="#FFFFFF" cx="50" cy="50" r="18.75"/>
<circle fill="#1A171B" cx="50" cy="50" r="12.5"/>
<circle fill="#FFFFFF" cx="50" cy="50" r="6.25"/>
</svg>
```
But when loading and displaying it with Processing it looks like this. Other shapes like lines or rectangles seem to be ok.
```
size(300, 300);
background(255);
noStroke();

PShape module1 = loadShape("a01.svg");
shape(module1, 150, 150);
fill(255, 0, 0);
ellipse(150, 150, 10, 10);
```

![img](https://cloud.githubusercontent.com/assets/2828139/9404786/953fad98-47f2-11e5-81c2-21bcc21f10f5.png)

You'll find the sketch here:
https://dl.dropboxusercontent.com/u/3009093/SVG_Issue.zip

**Comment by benfry** [comment]
Thanks for the report.

**Comment by benfry** [comment]
Fixed for 3 beta 5.
