### ISSUE TITLE
CM: Processing Foundation icons

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3687]
I haven't seen this new icon for the Foundation before (note small and large versions shown here):

![screen shot 2015-08-21 at 11 41 45 am](https://cloud.githubusercontent.com/assets/1034002/9416364/170f84b8-47fa-11e5-9708-4eff8c4fe03a.png)

Just to confirm: @REAS does this look right? (I was expecting white on a navy background.)

**Comment by benfry** [comment]
That's the new Foundation icon, yes.
