### ISSUE TITLE
CM: Libraries missing descriptions and PFoundation credit

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3688]
In the current master build, note that some of the official libraries do not display with descriptions or "[icon] Processing Foundation" as the author.

![screen shot 2015-08-21 at 11 48 12 am](https://cloud.githubusercontent.com/assets/1034002/9416650/c8eef8d4-47fb-11e5-8fee-189f99a980b7.png)

Or, is it possible this is just on my machine? If so, then why is the Foundation credit appearing below in the info panel, but not in the list above?

**Comment by Akarshit** [comment]
@alignedleft 
Some of these libraries are missing in the contribs.txt file [here](http://download.processing.org/contribs), but there is something more that's causing the description to go blank. I am looking into it.

**Comment by alignedleft** [comment]
@Akarshit This is extremely odd. I'm doing some more testing here. Notice the "video" library. With "all" selected in the category drop down, the Video library appears correctly.

![screen shot 2015-08-24 at 1 37 25 pm](https://cloud.githubusercontent.com/assets/1034002/9451760/6414b158-4a65-11e5-9009-68da92dcf4cf.png)

Note it appears as "Video" and not "video".

But when I choose the "Unknown" category, a number of libs that didn't appear before now display, including "video" (lowercase).

![screen shot 2015-08-24 at 1 37 40 pm](https://cloud.githubusercontent.com/assets/1034002/9451770/7bff6664-4a65-11e5-9b63-836ade3d55d5.png)

It is this latter lib ("video") and some of its siblings that are missing descriptions.

**Comment by Akarshit** [comment]
@alignedleft This might be occurring because of the presence of a "video" folder within your sketchbook. Please check your sketchbook folder if it contains two folder by the name of "video" and "Video". If present deleting the "video" folder should fix this.

**Comment by alignedleft** [comment]
I will test this tomorrow and report back. But if this behavior is a side effect of me having old libraries installed, I don't think me deleting the folders is a good fix for the problem. (Lots of other people will have lots of old libraries installed when upgrading to 3.0!) We will need a graceful way of handling this.

**Comment by alignedleft** [comment]
@Akarshit I tested this. I do *not* have the video library installed at all (old or new version). In fact, the only thing I have installed in my 3.0 sketchbook library folder is the Arduino library, which I installed through the CM just as a test.

Any other ideas for why these phantom listings are appearing?

**Comment by REAS** [comment]
In addition to the phantom listings for PDF Export, SVG Export, Serial I/O, Network, and DXF Export, these Core libraries can also be Removed through the CM, but then can't be added back again. When they are "removed" the examples are removed from the Java Examples window. I think the best solution is to keep the Core Libraries out of the CM?

**Comment by benfry** [comment]
The problem here is the difference between "core" libraries that are installed through the CM (video and sound) versus all the others (PDF, DXF, etc). In order to get them to show up in the right place in the Import Library menu and the Examples window, all of them need to be in the "core" list. But that confuses the CM, which now includes the "core" list so that it can update video and sound. 

So the CM needs to distinguish between core libraries that are in the sketchbook (probably of type `AvailableContribution` or `LocalContribution`, I can't remember which) and those in the download.

**Comment by benfry** [comment]
Fixed for beta 7.
