### ISSUE TITLE
Trouble with turning Android Mode

### ISSUE THREAD

**Issue by YUKUDA** [processing/processing#3704]
![image](https://cloud.githubusercontent.com/assets/4420498/9430314/ab52719a-4a1a-11e5-810b-c104cb111194.png)

Android SDK installed.

What's wrong?

**Comment by codeanticode** [comment]
Hello, thanks for reporting the issue. However, this should be in the [processing-android repo](https://github.com/processing/processing-android/issues). As a matter of fact, sounds like a duplicate of https://github.com/processing/processing-android/issues/139. Let's continue the discussion over there.

**Comment by benfry** [comment]
Fixed for 3.0 beta 5, thanks for the report.
