### ISSUE TITLE
CM - Icon instead of an "X" for the "could not connect" message

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3706]
@alignedleft 
This is how the error appears when there is no connectivity. 
![screenshot from 2015-08-24 19 30 44](https://cloud.githubusercontent.com/assets/7762605/9442019/f77c0672-4a96-11e5-9220-f664b4168a43.png)  
The closing button contains an "x" right now. I think there should be a icon rendered there. Can you please provide the icon for the button.

**Comment by iamutkarshtiwari** [comment]
With the above PR, the CM "Could not connect" message will show the following icon in the below image.
![cross](https://cloud.githubusercontent.com/assets/6258810/10706712/d40b320e-7a06-11e5-9e75-f45bf913874a.png)

**Comment by benfry** [comment]
Incorporated for 3.0.2.
