### ISSUE TITLE
Wrong handling of number modifiers

### ISSUE THREAD

**Issue by PhiLhoSoft** [processing/processing#3707]
I have this line:

    float rem = 1.0F - pos;

in a legacy code working fine (I can run it with 3.0b4).
I get an error « Error on "f" » in the error report pane, and it highlights the space after the F.
Number modifiers (L, l, F, f, D, d...) are case insensitive, so they should no be flagged as error..

Note: I change float to double, and F to d: the error disappears. If I put D in place of d, I get the same « Error on "f" » error. f?

**Comment by benfry** [comment]
@Manindra29 any idea where this would be in your parser?

**Comment by benfry** [comment]
Nevermind, found it. 

Fixed for 3.0 beta 5, thanks for reporting.
