### ISSUE TITLE
3.0b4 demos fail to create PDF files [resolved, it works]

### ISSUE THREAD

**Issue by dxjones** [processing/processing#3708]
The "PDF Export" examples included with Processing 3.0b4 execute without error messages, but fail to create PDF files.  I even searched for any PDF files created today, just to be sure that no new files were created anywhere.  I am using a recent Mac Pro laptop with OSX 10.9.5

Examples I tried:  OneFrame, LargePage, MousePress

**Comment by benfry** [comment]
Did you use Sketch > Show Sketch Folder? I just tried these and they seem to be working fine.

**Comment by JakubValtar** [comment]
Works for me too.

**Comment by dxjones** [comment]
Thanks Ben.  Using Sketch > Show Sketch Folder shows me where the PDF was created.

I thought "Search This Mac" was looking everywhere.  Evidently, it doesn't looking inside certain folders.

The file was being created in a folder that Search ignores:

/Applications/Processing.app/Contents/java/modes/java/libraries/pdf/examples/LargePage/Line.pdf


Anyway, ... PDF Export is working in 3.0b4.

-- David
