### ISSUE TITLE
loadPixels() with PGraphicsJava2D

### ISSUE THREAD

**Issue by hype** [processing/processing#3717]
@benfry 

Synopsis: We are refactoring HYPE to run as a proper Processing library, using Processing 3.0(b5) and Java 8. For some reason, I’m having difficulty getting the HCanvas class to run.  It throws a null pointer exception when attempting to instantiate the HCanvas class. I traced this to the ```_graphics.loadPixels()``` call on line 51 (https://github.com/hype/HYPE_Processing/blob/library/src/main/java/hype/HCanvas.java) of the updateBuffer method in HCanvas. Here’s the full stack trace:
```
Exception in thread "Animation Thread" java.lang.NullPointerException
	at processing.awt.PGraphicsJava2D.getRaster(PGraphicsJava2D.java:2714)
	at processing.awt.PGraphicsJava2D.loadPixels(PGraphicsJava2D.java:2738)
	at hype.HCanvas.updateBuffer(HCanvas.java:51)
	at hype.HCanvas.size(HCanvas.java:219)
	at hype.HCanvas.<init>(HCanvas.java:31)
	at hype.HCanvas.<init>(HCanvas.java:26)
	at Demo.setup(Demo.java:39)
	at processing.core.PApplet.handleDraw(PApplet.java:2376)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1499)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:312)
```
As you can see, it fails on ```getRaster()``` in PGraphicsJava2D.  When I debug, I see that ```this.image``` is null at the following line on getRaster:
```
raster = ((BufferedImage)this.image).getRaster();
```
Strangely enough, if I change the ```createGraphics()``` call to use P2D instead of JAVA2D, it runs fine. But looking at the Processing source, it seems like JAVA2D is the default renderer for this method, so I don’t want to hack around that if possible. 

I’ve also tried moving ```beginDraw()``` above ```loadPixels()``` in the updateBuffer method, and when I do that the sketch compiles but nothing is drawn on the canvas. But there’s no null pointer. 

Any thoughts or insights would be greatly appreciated!

**Comment by benfry** [comment]
You definitely can't do anything outside `beginDraw()` and `endDraw()`, so that `loadPixels()` is failing for good reason. I'm not familiar with what else you're doing so I can't say why it's not drawing anything after that, but that's where you should be looking. 

The idea behind `loadPixels()` and `updatePixels()` is just that it fills the `pixels[]` array. The load puts the contents of the `PGraphics` into `pixels`, and `updatePixels()` says "I've modified `pixels[]`, so next time you draw, make sure that's taken into account".

**Comment by hype** [comment]
ok I'll keep hammering away... Ironically this works fine in P2.2.1 (of course) :)

**Comment by benfry** [comment]
Just a lot of things that had to get more strict so that we can make the sort of performance gains and rendering improvements that we're into with 3. In the end it'll be all ducky and speedy, but it makes things a bit bumpy at the moment.
