### ISSUE TITLE
Code auto-complete not working when Box2D library imported

### ISSUE THREAD

**Issue by xnastudio** [processing/processing#3720]
If I import Shiffman's Box2D library, the code autocomplete not working.
With Mac OSX Processing 3.0b5  , after I input "box2d." , it should display method of box2d but not.
(with 3.0b3 , code autocomplete sometime OK, sometime not, I need to restart Processing to make it work again.)

With  Windows 7 64bit ,Processing 3 beta 3,4, 5 , code autocomplete never working.
I noticed the "code promote" , display for a second and disappear.

**Comment by benfry** [comment]
@Manindra29 what's the expected behavior here?

**Comment by Manindra29** [comment]
I'd broken this in a recent commit. Now fixed. :)
