### ISSUE TITLE
Feature: Add sketch folder/library as library search path

### ISSUE THREAD

**Issue by kroko** [processing/processing#3723]
- There is need for per-project libraries, that is - every project uses a different set of libraries **and** different versions / forks. We regularly use some libraries forks that deal with a bug or add some specific feature.
- Libraries used in project on "project archiving" should be copied next to the project in case of a future project revival so that the original or another coder would not have to guess what libraries and their versions were used (sure, you can find what was used in the source, but not the versions).

If we assume these two assuptions to be true :) - would it be possible to add dynamic library search path in sketch folder? 

`$sketchfolder/libraries/*`

If duplicate libraries exist (thus library with same name/signature is found both in "Sketchbook location" as well as sketch folder) then sketch folder takes precedence. That would give the ability to put some more popular libraries in the usual place (sketchbook library location), but some really project specific things straight into sketch folder + do overrides.

Would it be possible? The way currently libraries are loaded is "IDE global", however if per sketch overrides functionality is done, then it needs some dynamic loading (i.e., two project opened in IDE, needs dynamic menu update when switching between projects).

**Comment by liquid600pgm** [comment]
I know you might've already found the solution, but any libraries that you want to add to the classpath per sketch can be put in the `<sketch>/code/` folder.
