### ISSUE TITLE
Unclear which version is the latest release version

### ISSUE THREAD

**Issue by xyproto** [processing/processing#3727]
Hi,

I'm currently maintaining the [processing](https://www.archlinux.org/packages/community/x86_64/processing/) package for Arch Linux.

However, it was flagged as out-of-date by a user, because your webpage lists "3.0 beta 5" under "Stable releases" on this page: https://processing.org/download/?processing

* What is your latest stable release, is it 2.2.1 or 3.0 beta 5?
* Could you please state clearly on your webpage which version number is the version number for the latest stable release?

Best regards,
Alexander F Rødseth / "xyproto"

**Comment by benfry** [comment]
The version that's the default download on that page is our most stable, I'm not sure how much more clearly it can be stated when it's front and center on that page, and also the top entry under "stable releases". 

More details here: https://github.com/processing/processing/wiki/FAQ#whats-with-the-version-numbers

**Comment by xyproto** [comment]
The FAQ does not answer which version number is the latest stable release version.

The FAQ states:
> A "beta" release means that the API is locked up for the final, but not all the bugs are necessarily worked out.

Doesn't sound like a stable release to me.

But at the same time, the beta version is listed on the download page under the "Stable Releases" headline.

The question is still unanswered. Which is your latest stable release? Version `2.2.1` or `3.0 beta 5`?

**Comment by alignedleft** [comment]
As you've just pointed out, it is all semantics at this point.

If by "stable" you mean "as bug free as possible" use 2.2.1.

If by "stable" you mean "it mostly works and is our latest work, but is not bug free yet" use 3.0b5.

**Comment by xyproto** [comment]
Of all the projects I know of that have official Linux packages, they all provide one version or download that they consider to be "the one to use", for users. A version that is not alpha/beta/testing, but the most representative version of their software. It is highly unusual, and surprising to me, that you don't have a single version that you offer users that want both the latest version and the most stable version, but that users must choose between the two. It is also surprising to me that the "default download" is the beta version, and not the stable version.

I'll just have to meditate on this and come to terms with your unusual versioning scheme, then select a version.

Thanks.

**Comment by benfry** [comment]
3.0 beta 5 is the latest, most stable release. Links to it make up the entire top half of the download page, the portion most likely to be seen by virtually any person that visits that page. If you click "Linux" on the download page, you'll get 3.0b5, unless you go digging through the links below, in which case the topmost item will still be 3.0b5. Your users are getting that message because they're not using the most stable, most current release. The FAQ covers this in the first paragraph. I don't know how else we can explain this.

**Comment by xyproto** [comment]
Thanks for the clear answer, I will consider "3.0 **beta** 5" to be your latest stable release version, for the purposes of Arch Linux.

To answer the question about what you could do about your web design, I think you could do a user interaction test. You could ask a group of people to download the latest version from your webpage, that is not a beta/testing version, but the most stable version. I personally believe you would get wildly varying results.
