### ISSUE TITLE
Code editor wrongly detects errors for libraries in code folder

### ISSUE THREAD

**Issue by colouredmirrorball** [processing/processing#3732]
When a .jar file is inside the code folder, classes and methods from the jar used in the sketch will be displayed as an error (nonexisting functions/classes) even though the code compiles and runs just fine.

(Processing 3.0b5)

**Comment by benfry** [comment]
Sounds like the code folder isn't being added to the error checker. Surprised this hasn't been found earlier. Thanks for the report.

**Comment by Manindra29** [comment]
Code folder is added to the error checker [classpath](https://github.com/processing/processing/blob/master/java/src/processing/mode/java/pdex/ErrorCheckerService.java#L836). I'm not sure if it broke recently. Will it be possible to for you to share your sketch and the jar that would help reproduce the issue? (a small working sample of the sketch should suffice).

**Comment by colouredmirrorball** [comment]
I was using this library: http://www.jibble.org/pircbot.php, it provides a way to connect to an IRC server as a bot. This is how the code editor looks like (just a Processing adaptation of the example provided on the library's website):

![schermafdruk 2015-08-28 14 06 29](https://cloud.githubusercontent.com/assets/8689817/9546001/15f2e3fa-4d8f-11e5-999e-ad080452cc45.png)

The code compiles and runs without errors. The pircbot.jar file was added to the sketch by dragging and dropping it into the program.

I haven't tested it with other jars but it occurred with version 3.0b3 as well.

**Comment by colouredmirrorball** [comment]
The errors disappeared when adding the statement `import org.jibble.pircbot.*;` to the beginning of the sketch.

**Comment by timpulver** [comment]
@colouredmirrorball Thanks for the tip. Had the same problem with `org.apache.commons.io.FilenameUtils` – using `org.apache.commons.io.*` passes the syntax-check.

**Comment by Manindra29** [comment]
I believe the expected behaviour here is that even after adding the jar to the code folder, the import statement is required so that the compiler can know the package in which a class is located.

**Comment by benfry** [comment]
No, that's not correct—putting something in the code folder will automatically add its imports.

**Comment by colouredmirrorball** [comment]
But not to the sketch code which is why the live code checker gives errors
Op 8-sep.-2015 20:23 schreef Ben Fry <notifications@github.com>:No, that's not correct—putting something in the code folder will automatically add its imports.

**Comment by benfry** [comment]
I was responding to @Manindra29. The correct behavior is that the error checker should be automatically adding the imports. His error checking code is doing the wrong thing.

**Comment by Manindra29** [comment]
@benfry I wasn't aware of this behaviour. So the current preprocessor (as part of the JavaBuild), adds the import statements to the processed java code of the sketch for classes that it can't find? Please clarify.

**Comment by benfry** [comment]
@Manindra29 Imports for any packages found in a JAR file in the code folder are automatically added by the preprocessor.

**Comment by Manindra29** [comment]
@benfry I've now added the logic to automatically add code folder imports. @colouredmirrorball, feel free to checkout the latest master.

**Comment by benfry** [comment]
Thanks Manindra.
