### ISSUE TITLE
Message in console when the code is commented

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3733]
Processing 3.0b5 send message of error when the line is under comment like that 
`````
/*
import japplemenubar.*;
*/
`````
but not when the comment is like that
``````
// import japplemenubar.*;
```````

I don't know if it's normal or not ?

**Comment by StanLepunK** [comment]
I think the error paste is not important. the interest it's Processing return a message from something is under comment ````/* */`````or ````/**   */```` I thought Processing don't read the comment ?

**Comment by JukePlz** [comment]
Something similar happens when leaving commented functions in a static mode sketch, if the line is commented it should never get parsed for errors, even if the code would be incorrect.

**Comment by benfry** [comment]
I see no errors when running that code.

**Comment by StanLepunK** [comment]
Is not about the error, I don't understand why Processing read the under this type of comment `````/* */`````. and when it's use a classic `````//`````there is no problem
![capture d ecran 2015-08-31 a 15 32 16](https://cloud.githubusercontent.com/assets/3332269/9579822/9786efac-4ff5-11e5-85d9-99ba9898a51f.png)
