### ISSUE TITLE
Incomplete text rendering of strings with consecutive line breaks

### ISSUE THREAD

**Issue by jwmatthys** [processing/processing#3736]
When using the 5-argument version of text(), if there are multiple consecutive line breaks, the text after the line break is not rendered. Minimal example:

```java
void draw() {
  background(0);
  String s = "Hello\n\nWorld.";
  fill(255);
  text(s,10,10,100,100);
}
```

Output only shows "Hello"

This bug appears to have been introduced after 3.0b3, where the text is rendered correctly.

Tested with Processing 3.0b4 on OSX, Linux, and Windows,, and 3.0b5 on OSX.

**Comment by benfry** [comment]
Bummer, sounds like a problem introduced by fixing #211 (or #3487). Thanks for the report.

**Comment by kasperkamperman** [comment]
The code below still gives a "zero length string passed to TextLayout constructor" error. Removing the textAlign(CENTER, CENTER) solves it or adding a space behind the \n.

In Android mode this code just works normally (discovered it when working with the Ketai library. 

```
void setup() {
  size(800,480);

  textAlign(CENTER, CENTER);
  textSize(48);
}

void draw() {
  background(128);
  text("x: " + nfp(100, 1, 0) + "\n" , 20, 0, width, height);
}
```

**Comment by LotteM** [comment]
I'm having the same problem in 3.0.1. 
Removing the first CENTER solves it.. 
(but I need my text centered..)

**Comment by benfry** [comment]
The original problem was fixed, so open a new report.
