### ISSUE TITLE
Annoying message on console about disposing texture, verteces and shader

### ISSUE THREAD

**Issue by darkwave** [processing/processing#3738]
Following message is repeated infinitely on console:

<code>Disposing texture resource 0 ...</code> 

The "incriminated" println is inside <a href="https://github.com/processing/processing/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L774">PGraphicsOpenGL.java</a> at line 774.

Similar messages are produced at lines 858 and 936.

**Comment by codeanticode** [comment]
part of implementing https://github.com/processing/processing/issues/3384, will be removed shortly.
