### ISSUE TITLE
using "new color()" instead of "color()" results in "color type detected" message

### ISSUE THREAD

**Issue by allonestring** [processing/processing#3739]
I've just started typing a class containing the lines

  color colour;
  
in the declarations and

    colour = color(random(255), random(255), random(255));

in the constructor, and have got the message

color type detected! 
This shouldn't be happening! Please report this as an issue.
color type detected! 
This shouldn't be happening! Please report this as an issue.

So I'm reporting it.:-)

I'm on version 3.0b2

**Comment by benfry** [comment]
Can you supply actual code that causes the error? I can't reproduce it from this.

**Comment by allonestring** [comment]
My code was as bald as this

class SomeClass
{
  color colour;
  
  SomeClass()
  {
    colour = color(random(255), random(128), random(64));
  }
  
  void drawSomething()
  {
    fill(colour);
    ellipse(width/2, height/2, 10, 10);
  }
}

When I (wrongly, I know) put new into this line

   colour = new color(random(255), random(128), random(64));

then I got the error. Sorry for not including this; I hadn't noticed the error at first and so didn't know what had caused it.

**Comment by benfry** [comment]
Ahh... That makes sense, and yes, we need to detect for that. It's a common confusion since `color` is a primitive type (like `int`, `float`, etc) not a class (which would be uppercase). Thanks for the report.

**Comment by benfry** [comment]
@JakubValtar this is another one to keep an eye out for if you see it today. But it probably points to a trickier (and lower priority) issue, so don't spend extra time on it.
