### ISSUE TITLE
Processing-Java

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3740]
I have met a problem when I have re-installed Processing-Java on my Mac.
I use Processing with Sublime Text, so when I have tried to change from Processing 3.0a5 to 3.0b5. I have re-installed processing-java from the last Processing, but when I was in Sublime Text, the console return me an error about Processing-Java, who said I don't a good java jdk.
The problem when I have search Processing-Java from spotlight...I had a good one.

Finally I find there is three Processing-Java on my computer, but two are hiden, and Processing replace just the visible one. And Sublime search for the hide one...and the hide one is the uggly-old one.

I found the bad ones here :  `````usr/local/bin`````and in the ````usr/bin```` and replace by the good one. Now sublime have a sublime behavior with Processing !

So May be it's interresting to understand why Processing re-install Processing-Java only on the no hiden place...

**Comment by benfry** [comment]
We have no control over where Apple's Spotlight software searches for files. And the point of installing it into `/usr/local/bin` is that it's automatically available on the command line, otherwise users would have to mess with their PATH.
