### ISSUE TITLE
Hitting enter on code completion completes the code and then creates a new line.

### ISSUE THREAD

**Issue by StuartFarmer** [processing/processing#3741]
Hitting enter on the method, variable, etc. you want to complete fills in the rest of the code for you, but also creates a new line, which means the coder has to delete the whitespace before finishing their expression.

**Comment by benfry** [comment]
Hm, I'm having trouble reproducing this. So I type “el” and hit ctrl-space, and the window pops up. Then I hit return and it inserts ellipse(,,,) and the cursor is between ( and ,

And that's not the case for you?

**Comment by benfry** [comment]
Suspect this may be part of #3812.

**Comment by benfry** [comment]
No response and can't reproduce.
