### ISSUE TITLE
Tweak Mode does not always work in version 3.0b5

### ISSUE THREAD

**Issue by PhilipSharman** [processing/processing#3742]
Using "tweak mode" (Sketch > Tweak) does not always work.  The presence of some comments before the variable(s) to be tweaked seems to make a difference.

For example, this sketch works:

	void setup() {
		size(800, 800);
		background(0);
		fill(255);
	}

	void draw() {
		// 
		float diam = 100;
		ellipse(width/2, height/2, diam, diam);
	}

But this sketch does not (the sketch runs, but the ``diam`` variable is not tweakable):

	void setup() { 
		size(800, 800);
		background(0);
		fill(255);
	}

	void draw() {
		// test tweak
		float diam = 100;
		ellipse(width/2, height/2, diam, diam);
	}
	
The only different is the comment.

**Comment by galsasson** [comment]
Hi,
This is actually an old feature of tweak mode.
If you want to tweak only certain values in the code you can add a comment with 'tweak' at the end of the lines that you want tweakable. Like so:
```java
float diam = 100   // tweak
```

In this case tweak mode will ignore all other numbers in the sketch.

Any suggestions what to do here? @shiffman, @benfry, @REAS?
Do we want to eliminate this behavior?

**Comment by benfry** [comment]
Huh... wasn't aware of that. I think I'd lean toward using something slightly less generic, i.e.:

* use `/// tweak` (with three slashes) or something more specific than just "tweak"
* also only do it when it's the only thing in the comment. 
* only allow it for a comment on the same line?

The case in this report seems way too likely to happen on accident (with confusing results—I figured this was just a bug too). 

Does it still work if there are multiple variables on the same line?

**Comment by REAS** [comment]
I'm with Ben. I think that behavior should either be removed or modified to make it a more specific syntax.

**Comment by galsasson** [comment]
Ok thanks,
I'll change it to be '///tweak' as the last characters on the line, let me know if you want more specific.
If you have multiple numbers on the same line, it will apply to all of them (they all be tweakable). This way its up for the coder to set it up:
```java
// all
ellipse(100, 100, 300, 500);   ///tweak
// one
ellipse(100, 100, 
             300, ///tweak
             500);
```

Actually, what started as a way to "toggle" tweak-mode, became later on, on [this](/galsasson/TweakMode/tree/evolution) branch a feature to setup a limit to the range. I needed it for a project where I created random sketch versions.
```java
ellipse(x, y, 100, 100) // tweak[0-200]
```
I can bring it to life if theres interest.

**Comment by benfry** [comment]
The ranges sound like a useful feature, but not if it's too much work or additional mess.

**Comment by benfry** [comment]
Changed `hasTweakComment()` to use `/// tweak` for 3.0 beta 6.
