### ISSUE TITLE
Cannot build Debian package

### ISSUE THREAD

**Issue by darkwave** [processing/processing#3744]
Issuing ant deb command gives this, <i>cryptic to me</i>,  output:

<pre>Buildfile: /opt/myProcessing/processing/build/build.xml

revision-check:

dist:
    [input] Enter version number: [0244]
0244

BUILD FAILED
/opt/myProcessing/processing/build/build.xml:309: To do a distribution, the processing-docs repo must be checked out at the same level as the processing repo.

Total time: 3 seconds</pre>

**Comment by benfry** [comment]
You need to check out the processing-docs repo as well. It should have the same parent directory as the processing repo.
