### ISSUE TITLE
message in console is too much down ?

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3747]
May be the message of the console start too down ?
![capture d ecran 2015-08-31 a 10 37 18](https://cloud.githubusercontent.com/assets/3332269/9574989/71c9d87a-4fcc-11e5-9044-019058ebb305.png)

**Comment by benfry** [comment]
The console prints a couple blank lines (5 or so?) to separate between the messages each time you hit "Run". That's the intended behavior to avoid confusion.

**Comment by StanLepunK** [comment]
ok
