### ISSUE TITLE
Processing not compatible with MAC OSX10.10.5

### ISSUE THREAD

**Issue by ednaus** [processing/processing#3750]
All new MAC's pre install OSX10.10.5 which is not compatible with Processing 3. It launches but there are no menu options.

**Comment by benfry** [comment]
The majority of development for Processing is done on Mac OS X 10.10.5, and there are thousands of OS X 10.10.5 users running the software. You might be better off getting help from [the forum](http://forum.processing.org) to figure out why it's not running on your machine.
