### ISSUE TITLE
syntax highlighting doesn't make mouseReleased() font bold

### ISSUE THREAD

**Issue by Johannes-Larsson** [processing/processing#3751]
All other similar methods use a bold, blue font. (mousePressed(), setup(), etc) but this one is blue but not bold.

**Comment by benfry** [comment]
@REAS is this just that `mousePressed` works differently because it's both a variable and a function?

**Comment by REAS** [comment]
It's a bug, it should be FUNCTION4 in keywords.txt, but it's FUNCTION1. I'll fix it.
