### ISSUE TITLE
Augmented Reality in Processing 3

### ISSUE THREAD

**Issue by sidu7** [processing/processing#3754]
Hello,

I'm trying to a simple markerbased Augmented Reality application in processing 3.. But I'm encountering an error..
![12](https://cloud.githubusercontent.com/assets/9669758/9607389/7fb6d404-50e6-11e5-853d-703a6ad83f30.jpg)

This code works perfectly in the processing 1.5.1... but I'm unable to run the same code in processing 3. Please help me

**Comment by alignedleft** [comment]
So many things that it could be! 1.5.1 is quite old by now.

Did you read these?

https://github.com/processing/processing/wiki/Changes
https://github.com/processing/processing/wiki/Changes-in-3.0

Have all the libraries you're using been updated to work with 3.0?

What have you tried so far? This is probably best answered in: forum.processing.org
