### ISSUE TITLE
SimpleOpenNI library on processing not working

### ISSUE THREAD

**Issue by Cesar93Triana** [processing/processing#3755]
Hi,

I recently got a hold of an old Xbox 360 Kinect that a friend of mine wasn't using anymore so I started to wonder what interesting things I could do with it, and that's how I heard about Kinect + Processing + Arduino. The thing is I can't get the SimpleOpenNI library to work on my computer.

I am running Processing 2.2.1+ OpenNi 2.2 + SimpleOpenNI 1.96 + Kinect SDK 1.8 on a Windows 8.1 64bit PC.

I install the library just like the google code page says and it installs correctly (or so it looks like), but whenever I try to Run the example code from the google code page I get the following error message:

![Captura](http://forum.processing.org/two/uploads/imageupload/787/E17GBZTWQKQD.PNG "Captura")

I tried using different versions of processing, different versions of simpleopenni, different versions of openni, but ALWAYS get the same error message.

Has anyone here had such a problem? I would greatly appreciate any input on the subject.

Thanks in advance,
Cesar

**Comment by benfry** [comment]
This is not a Processing bug. Please report with the library author, or use the forum to get debugging help.

**Comment by totovr** [comment]
https://github.com/totovr/SimpleOpenni/blob/master/README.md
