### ISSUE TITLE
private keyword is ignored

### ISSUE THREAD

**Issue by kasperkamperman** [processing/processing#3757]
I notice that the private keyword is ignored and that I can still access variables with the private keyword. I know we don't use it a lot in Processing. But I wanted to explain it to show the students the similarities between Unity(C#) and Processing (Java).

Processing 3.0b5. 
Mac OSX 10.10.5

```
Ball ball;

void setup(){
  size(600,600);
  ball = new Ball(100,100);
}

void draw() {
   background(255);
   ball.display();
   ball.x = ball.x + 1;
}

class Ball 
{
  private float x;
  private float y;

  Ball(float tempX, float tempY){
    x = tempX;
    y = tempY;
  }
  
  void display() {
     fill(255,0,0);
     ellipse(x, y, 100,100); 
  }
}
```

**Comment by benfry** [comment]
That's not a bug, it's how Java works: “Non-static nested classes (inner classes) have access to other members of the enclosing class, even if they are declared private.”
https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html

**Comment by kasperkamperman** [comment]
Clear. I understand that is because Processing hides that we are actually working in a main class. Thanks for your explanation and sorry I filled it as a bug.

**Comment by kasperkamperman** [comment]
I feel that the reference documentation probably needs an update on this point though:
https://processing.org/reference/private.html

"In Processing, all fields and methods are public unless otherwise specified by the private keyword." 

This is not true then or at least confusing. Since classes are always an inner class if you write them in the editor (I think?).

**Comment by REAS** [comment]
I added this to processing/processing-docs#304
