### ISSUE TITLE
Red error underline is sometimes at wrong location

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3759]
Some  time the red subline is in the bad place. Processing 3.0b5
![capture d ecran 2015-09-03 a 15 07 23](https://cloud.githubusercontent.com/assets/3332269/9659011/dfd17822-524d-11e5-93cb-c584ddd669a8.png)

**Comment by benfry** [comment]
I don't know what this means, and PDE X doesn't exist anymore as a supported project.

**Comment by StanLepunK** [comment]
Like the picture show the error lines show a white part ! That's happen not all the time, but some time. So it's like a bug.

**Comment by JakubValtar** [comment]
I have a similar problem, red underwave does not span multiple lines and just goes on:

![error](https://cloud.githubusercontent.com/assets/3177098/9748356/2221c42c-5652-11e5-8e1d-1b37659ad7db.png)

```java

void setup() {

}

void draw() {

  int cursors = {
    ARROW, CROSS, HAND, MOVE, TEXT, WAIT
  };

}

```

**Comment by JakubValtar** [comment]
@StanLepunK We can't fix the problem withtout being able to reproduce it. Are you able to reproduce the problem? Could you please post the code shown in your screenshot?

**Comment by StanLepunK** [comment]
I try to reproduce th

**Comment by StanLepunK** [comment]
I suspect a refresh problem. Because just now I have a case, I close Processing and re-open to see if it's still here , but the the wrong underline go away.
So my idea is :
It's like Processing find a problem, underline this one. Very quick you solve it and you remove a part of code above, your code go little up, and the underline stay in the same place. When Processing come back to analyze your sketch the error is disapear. but Processing keep the underline red in memory on something blank, because it don't watch the blank part. I hope my idea is clear !!!

**Comment by StanLepunK** [comment]
keep the redline on something blanc or something whitout error.

**Comment by benfry** [comment]
This looks like broken logic inside `JavaTextAreaPainter.paintErrorLine()`.
