### ISSUE TITLE
text( str, x1, y1, x2, y2 ) displays nothing if the string has a space as the first character

### ISSUE THREAD

**Issue by solchant** [processing/processing#3761]
@ Processing 3.0b5

The five parameter text function (String,int,int,int,int) does not display anything to the screen if the first character in the argument string is a space char (" ").

Code snippet:
```
void setup() { fullScreen(); }
void draw () {
  background( 0 );
  text( "this one displays" , 100 , 100 , 100 , 100 );
  text( " this one does not" , 100 , 250 , 100 , 100 );
}
```

Works on P2, however.

**Comment by colouredmirrorball** [comment]
In addition text following a "\n" gets ignored.

**Comment by benfry** [comment]
Already fixed by @JakubValtar for beta 6.

<img width="512" alt="screen shot 2015-09-03 at 1 35 49 pm" src="https://cloud.githubusercontent.com/assets/1623101/9665823/ba500ddc-5240-11e5-9bb1-072912bb5696.png">

**Comment by benfry** [comment]
See also https://github.com/processing/processing/issues/3736
