### ISSUE TITLE
Overriding exitActual() leaves OpenGL windows open

### ISSUE THREAD

**Issue by neilcsmith-net** [processing/processing#3763]
When overriding exitActual() so as to not actually exit(!) :smile: the sketch window remains open with the last drawn frame visible.  This is with the OpenGL renderer - not sure if it affects all surfaces.  Closing the window when this happens is not always easy, and sometimes requires force killing the process.

Adding in a call to surface.setVisible(false) during dispose() fixes the issue for me.  Should this be in PApplet, or is it the OpenGL surface not behaving correctly?

**Comment by codeanticode** [comment]
You need to call stopThread() before exitActual() in order to stop JOGL's animator thread. I added a [brief note](https://github.com/processing/processing/wiki/Advanced-OpenGL#overriding-shut-down-process) in the wiki about this.

**Comment by neilcsmith-net** [comment]
Sorry, Andres, but not sure you've understood the issue.  surface.stopThread() is already called in dispose() - animation is stopped but the window remains visible.  I'm not sure this is an OpenGL bug, either.  There is a showSurface() method in PApplet, but not a corresponding hideSurface() method during dispose().  This is reproducible with the default renderer too.  If you override exitActual() so as to not exit the VM, the window is left open although the sketch stops running.
