### ISSUE TITLE
When running a sketch, the window no longer has an X Window class

### ISSUE THREAD

**Issue by hamoid** [processing/processing#3764]
Low priority (I assume).

The window with the running sketch used to have an X Window class like "processing-core-PApplet". On b5, if I use xprop to find information about the running sketch window, it does not seem to have a class. This is the output:

    WM_NAME(STRING) = "mySketch"
    WM_STATE(WM_STATE):
                    window state: Normal
                    icon window: 0x0
    _NET_WM_ICON(CARDINAL) =        Icon (16 x 16):
                 ▒▓▓▓▓▒     
               ▒▓▓▓▓▓▓▓▓▒   
              ▒▓▓█▓▓▓▓▓▓▓▒  
             ▒▓▓█▓▓█▓▓▓▓▓▓▒ 
             ▓▓█▓▓▓▓▓▓▓▓▓▓▓ 
            ▒▓▓▓▓▓░▓▓█▓▓▓▓▓▒
            ▓▓▓▓▓█  ░▓▓▓█▓▓▓
            ▓▓▓▒▓▓    ▒▓▓▓▓▓
            ▓▓▓▓▓▓    ▒▓▓▓▓▓
            ▓█▓▓▓▓  ░▓█▓▓▓▓▓
            ▒▓▓▓▓▓░▓▓█▓▓▓▓█▒
             ▓▓▓▓▓█▓▓▓▓▓▓█▓ 
             ▒▓▓▓▓▓▓▓▓█▓▓█▒ 
              ▒▓▓▓▓▓▓▓▓▓▓▒  
               ▒▓▓▓▓█▓▓▓▒   
                 ▒▓▓▓▓▒     

            Icon (32 x 32):
              ...

    _MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
    _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
    NEWT_JAVA_OBJECT(NEWT_JAVA_OBJECT) = 0x347a3308, 0x7f28
    WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW

Currently there's no way to notice if a window was created by Processing or not, which can be useful with advanced window managers. I took a quick look but did not find where on the source code the sketch window is created.

**Comment by benfry** [comment]
I think this is inherited from JOGL and completely out of our control. @codeanticode?

**Comment by benfry** [comment]
Closing as something out of our control.

**Comment by hamoid** [comment]
For some reason, in b6 the class is back. I don't know what changed, but it works fine now :+1:
