### ISSUE TITLE
Should the debugger "break" on a blank line?

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3765]
I was doing a demonstration of the debugger today and got stuck on a certain point -- the sketch does not stop when a breakpoint is set on a blank line.  In other words, the following works as expected with the sketch stopping on `x = x + 1;`.

<img width="875" alt="screen shot 2015-09-04 at 4 20 52 pm" src="https://cloud.githubusercontent.com/assets/191758/9693769/f31ae480-5320-11e5-9342-357fc8e866ac.png">

However, I was confused by the sketch never stopping with this scenario, a breakpoint set to a blank line.

<img width="875" alt="screen shot 2015-09-04 at 4 21 44 pm" src="https://cloud.githubusercontent.com/assets/191758/9693782/0c1f58a8-5321-11e5-8d77-1e94d9af0842.png">

What is the correct / intended behavior?

**Comment by benfry** [comment]
I suspect it can't stop where there's no code, but the correct behavior is probably that behind the scenes it sets the breakpoint for the line with code on it, or we don't allow breakpoints to be set for empty lines. The latter might be simpler.

**Comment by benfry** [comment]
In 3.0 beta 6, it won't set the breakpoint if the line contains no code.
