### ISSUE TITLE
Size with variables

### ISSUE THREAD

**Issue by pierrejd** [processing/processing#3767]
I can´t run sketches that have the size determined by a variable. For example  size(img.width, img.height); in this part of the code:
 
void setup() {
  frameRate(100);
  animation = Gif.getPImages(this, imgFileName + "." + fileType);
  img = animation[0];//loadImage(imgFileName+"."+fileType);

  size(img.width, img.height);

  image(img, 0, 0);
  gifExport = new GifMaker(this, imgFileName+"_"+mode+ ".gif");
  gifExport.setRepeat(0);
  //gifExport.setTransparent(0,0,0);
}
 

I'm running Processing 3 b5. The code is the animated pixel sort sketch found in OpenProcessing: http://www.openprocessing.org/sketch/76283

**Comment by Spinewe** [comment]
I learned that as well, you have to put real numbers in instead of variables...not sure why, but it worked for me

**Comment by clankill3r** [comment]
As far as I know It has to do with the precompiler. Correct me if i'm wrong but I believe it copies the size from setup and put it in void settings(). Having it relay on variables could potentially break it cause a variable could be in setup only and therefor be out of scope in settings.

**Comment by hamoid** [comment]
From https://processing.org/reference/settings_.html "The settings() function is new with Processing 3.0. It's not needed in most sketches. It's only useful when it's necessary to define the parameters to size() with a variable..."

**Comment by mexitalian** [comment]
It's mentioned in [Changes-in-3.0#things-that-may-break-your-2x-sketches](https://github.com/processing/processing/wiki/Changes-in-3.0#things-that-may-break-your-2x-sketches) with an example of changing sketch size using the new `surface.setSize(w, h)` method.
