### ISSUE TITLE
cursor() command with PImage stopped working in 3.0 with P2D

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3769]
someone reported the issue on the forum where cursor(PImage img) no longer works:

http://forum.processing.org/two/discussion/12352/cursor-command-with-pimage-stopped-working-in-processing-3-0

**Comment by benfry** [comment]
I suspect if they call `cursor()` again during `draw()` it may work, but this is news to me.

**Comment by codeanticode** [comment]
implemented in https://github.com/processing/processing/commit/86c042eb5ef4b0cb361a072bc2bf2ebb3396e1cb
