### ISSUE TITLE
Sketch has incorrect height

### ISSUE THREAD

**Issue by jarmohurri** [processing/processing#3772]
At least in the Linux distribution of 3.0 beta 5 the following code

    size (600, 50);
    rect (0, 0, width, height);

opens a window whose height is approx 130 pixels instead of the requested 50 (see graphics below).

![foo](https://cloud.githubusercontent.com/assets/3823344/9704099/dfa86480-54a2-11e5-8b6c-02f2f596fe52.png)

**Comment by colouredmirrorball** [comment]
Minimum height in Processing is 100 (not sure why).

**Comment by jarmohurri** [comment]
I see. Maybe it could be fixed now? (I am also using Processing.js, and it does not have a similar limitation.)

**Comment by benfry** [comment]
We're limited by the OS, and in the case of Linux, the Window Manager as well.
