### ISSUE TITLE
PGraphicsJava2D g2 attribute not set with createGraphics (PS3)

### ISSUE THREAD

**Issue by quarks** [processing/processing#3774]
When using createGraphics to create an offscreen PGraphicsJava2D buffer the attribute g2 is not set (i.e. remains null). This  code demonstrates what I mean.

```Java
import processing.awt.PGraphicsJava2D;
import java.awt.*;

PGraphicsJava2D buffer;

void settings() {
  size(200, 200);
}

void setup() {
  buffer = (PGraphicsJava2D)createGraphics(300, 300, JAVA2D);
  println(buffer.g2);            // null
  println(buffer.getNative());   // null

  Object g2d = buffer.checkImage();
  println(g2d.getClass().getName());
  println( ((Graphics2D)g2d).getClass().getName());
}
```

The out put is
<pre>null
null
sun.java2d.SunGraphics2D
sun.java2d.SunGraphics2D
</pre>

I use g2 so that I can do text formatting using java.text.AttributedString

**Comment by benfry** [comment]
It won't exist until you're inside `beginDraw()` and `endDraw()`, which is important because the `g2` object changes on each frame.
