### ISSUE TITLE
Exported application does not copy data directory

### ISSUE THREAD

**Issue by markstock** [processing/processing#3777]
I am using Processing 3.0b5 on Fedora 21 and OSX 10.10. When I export the application, my sketch's `data` directory (containing sound and text files) should be copied into the application bundle. This works properly on Linux. But on OSX, the new `data` directory in the application is empty, and my application does not function. When I copy the contents manually, it begins working.

Upon trying this all again, the `data` directory was not even created in the application folder on OSX.

**Comment by benfry** [comment]
This is working fine here—below is an exported application which has its data folder intact. Perhaps you're having permissions problems with that folder? Check to see if there's any error text in the console when you try to export.

<img width="752" alt="screen shot 2015-09-11 at 8 47 21 am" src="https://cloud.githubusercontent.com/assets/1623101/9815143/d21dbfbe-5861-11e5-87d7-d0cc10468942.png">

**Comment by markstock** [comment]
I don't recall seeing error text in the console. data dir has 755 permissions.
