### ISSUE TITLE
surface.setTitle in combination with hover brings frameRate down from 60 to 15

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3782]
Processing 3b5
Mac OS X 10.10.5

If my mouse is not on the frame then my frameRate is 60.
If my mouse hovers over the frame (Applet) then the frameRate climbs all the way down to around 15.
Also my cursor is flickering all the time when on the frame. 

This is only the case when I use `surface.setTitle`. Without that it keeps a steady frameRate.

````java
public void settings() {
  size(512, 512);
}

public void setup() {
}

public void draw() {
  background(255);
  fill(0);
  text(""+frameRate, 20, 20);
  surface.setTitle(""+frameRate);
}
````

edit:

There also seems to be huge impact lag from the mouse (even without setting surface.setTitle), but I will look into this later).

**Comment by benfry** [comment]
Not surprising, you're doing a heavyweight OS operation like messing with the frame title in the middle of a rendering loop. It's really bad practice.

@JakubValtar can check on whether there's a way we can work around this, but I'd never recommend this is a method for getting the frame rate.

**Comment by brendanmatkin** [comment]
Didn't realize this was bad practice! I use this all the time: frame/surface.setTitle((int)frameRate + " fps") or other dynamic info.

Anyway 10.10.5, 3.0b6 and I see no change in frameRate. 

BUT I have also never noticed a speed difference in previous versions of Processing as far back as 2.0 alpha (this was on Windows usually). I've been doing that for several years.

**Comment by clankill3r** [comment]
Well it's gone now. I think it is an OS X bug that only happens under certain conditions.
