### ISSUE TITLE
"Rename..." context menu item fails silently

### ISSUE THREAD

**Issue by JukePlz** [processing/processing#3783]
Sometimes the rename function/variable tool fails to do so at random, this happens often in code with many tabs and usage of said function/variable in different parts of the code, but is not reproducible 100% of the time. Renaming may even fail multiple times in a row before it actually works.

If this is done on a separate thread from the editor it needs to be checked, I had very strange behavior (files reverting to pre-saved state) after seeing this error before.

**Comment by benfry** [comment]
There's nothing in this report that can help anyone track down or begin to identify this problem. If you have something that's repeatable, please file it. But "this is behaving strangely" isn't something I can fix.

**Comment by JukePlz** [comment]
I have managed to reproduce it consistently (albeit not on all rename attemps) doing the following:

- create a new sketch with this content on the main tab:

```
test1 myTest = new test1();

void setup()
{
  size(200, 200);
}

void draw()
{
  myTest.something();
}
```
- create a new tab, with this class:
```
class test1
{
  test1()
  {
  }

  void something()
  {
    ellipse(50, 50, 50, 50);
  }
}
```

- right click on the class (test1) constructor and rename it multiple times, as quickly as possible.

renaming will fail sometimes (about 50% of the time as I tested on two different computer with on Windows) and when it does so you can save the sketch, and it will be broken after you reopen it (the class will have a different name on different tabs)

I can provide a video later if you still can't reproduce.

**Comment by processo** [comment]
I can confirm this exists, though not a very serious problem. Here is my take on explaining it.
##### How to reproduce
There is no need for the complex example of @JukePlz. This does it:
```java
public void setup() {
  int someVariable = 0;
}
```
1. right click on `someVariable` and *Rename...*
2. write any name and click *Rename*
3. right click on the new name **within 1-2 seconds**\*
4. rename it again
5. no renaming will happen

\* It is important to note, if you do step 3 real fast (<0.5 sec) the system will give an error saying there is no such variable to rename.
![processing rename bug](https://cloud.githubusercontent.com/assets/5299789/9830610/e8974934-5935-11e5-825b-4919dce59faf.png)

##### Workaround
Do NOT rename variables within 3 seconds!

**Comment by benfry** [comment]
@Manindra29 thoughts on this?

**Comment by Manindra29** [comment]
The error checker service builds a tree representation of the code (AST). This structure needs to be updated every time the code of the sketch is updated. The way it works is: after some interval (less than 1 second) after the last keystroke, the AST is updated. If you try to rename a variable before it has been updated in the AST, this error will occur consistently. This is a known limitation. It is difficult to reproduce on a Mac. I don't think this is something that I can fix. 

If someone would like to improve this and make it better, contributions are welcome.
