### ISSUE TITLE
Some modes fail to install

### ISSUE THREAD

**Issue by JukePlz** [processing/processing#3785]
On 3.0b5 when installing REPL mode from the contributions manager the installation fails, the manager shows "Error during download and install of REPL Mode." and prints "err is java.lang.reflect.InvocationTargetException" on the console.

Similarly, the Javascript mode fails with a not-compatible message, but is not grayed out in the editor like other incompatible modes.

**Comment by alignedleft** [comment]
Thanks, @JukePlz. What OS and version are you using?

Hoping @Akarshit can look into this.

**Comment by joelmoniz** [comment]
Sorry. The REPL Mode not working is my fault. Base was broken down
recently, and I've not been able to update the REPL Mode yet to make it
compatible with this changed structure. I should be able to get to this
done in a few days.

**Comment by benfry** [comment]
Closing since this is a REPL Mode bug.
