### ISSUE TITLE
Remove old version of processing-java when installing on OS X

### ISSUE THREAD

**Issue by benfry** [processing/processing#3786]
Need to remove `/usr/bin/processing-java` when installing to the new (El Capitan compatible) location `/usr/local/bin/processing-java`.

**Comment by StanLepunK** [comment]
On OSX 10.9 / Processing 3.0b6
When we install a new Processing-Java it is remove from the folder "usr/bin" but the new one is installed or modifify the older in "/Users/computerName/processing-java" so it's necessary to copy and paste in "usr/bin" manuelly. and that's work fine with Sublim Text.
When I run this version of Processing-java in the terminal, the name of the version is 244, like Processing 3.0b6 but the date of installation or modification is 29 august, when I've installed the Processing-java from 3.0b5. To test I delete the file "Processing-Java" and try to install again from Processing 3.0b6 but nothing happen, my computer ask authorization to install, but nothing is install. very weird. I hope my explication is clear ?
