### ISSUE TITLE
Close window during dispose()

### ISSUE THREAD

**Issue by neilcsmith-net** [processing/processing#3787]
Kind of re-opening #3763 now I've managed to check with other renderers - this doesn't seem to be specific to the OpenGL renderer, and that was actually closed for the wrong reason.

In order to support usages that override VM exit when a sketch exits (multiple windows, embedding in other applications) dispose() needs to call surface.setVisible(false)  Or surface needs a dispose() method?  This might also ensure native resources are shut down cleanly.

On a related note - could overriding exitActual() be replaced / enhanced by a setting (similar to JFrame.setDefaultCloseOperation()) in order to better support multiple windows?

**Comment by benfry** [comment]
We're not here to support any random way in which someone might like to use the software. If you'd like it to behave differently for an esoteric purpose or have something in mind for your own library, you should subclass the code or simply modify it yourself. That's one nice aspect of all the code being available. But this report has nothing to do with normal use of the Processing software for any other user.

**Comment by neilcsmith-net** [comment]
I didn't think multiple windows was that esoteric, but happy if you want to
mark Won't Fix - your prerogative. I'm only reporting things that seem
relevant to Processing users, rather than Praxis LIVE specific workarounds
- I am grateful that it's all open, but also trying to help upstream where
feasible.

Best wishes,

Neil

Neil C Smith
Artist : Technologist : Adviser
http://neilcsmith.net
