### ISSUE TITLE
setAlwaysOnTop does not work in P2D and P3D on Mac

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#3793]
This sketch:

void setup() {
  size(600, 600, P2D);
  surface.setAlwaysOnTop(true);
}

void draw() {
  background(0);  
}

works as expected on Windows and Linux, but not on Mac (tested on OS X 10.9.5). I think it is an upstream bug in JOGL, as I can reproduce it with a simple JOGL test case. Started [discussion on JOGL forum](http://forum.jogamp.org/GLWindow-setAlwaysOnTop-does-not-work-on-OSX-td4035266.html).

**Comment by benfry** [comment]
Marking as cantfix but leaving open until we have the upstream fix.

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing/commit/9a71778618ceb3a9a0bbafbc2285b2b120c466dc
