### ISSUE TITLE
about Processing

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3794]
When you click on the dropdown menu "Processing/about" the name of Processing is "3.0 alpha 3.0b6" is good name is not "3.0 beta 3.b6" 
Plus, may be is good to add the number of the revision in this window? 
![capture d ecran 2015-09-12 a 14 38 35](https://cloud.githubusercontent.com/assets/3332269/9831528/78a7add6-595c-11e5-9f9e-df13d221c707.png)

**Comment by benfry** [comment]
https://github.com/processing/processing/issues/3665
