### ISSUE TITLE
Trackpad scrolling breaks in other applications when using FX2D on OS X

### ISSUE THREAD

**Issue by brendanmatkin** [processing/processing#3798]
This is a strange issue and I cannot replicate it consistently. Also a good chance it's a java issue not processing but thought I'd put it here anyway. 

Using FX2D renderer on 6.0b3, 2015 mbp, OSX 10.10.5.

Running a sketch that is iterating through thousands of lines (eventually ~100,000) from a csv using Table. After a while, frame rate is still between 60-200 fps but mousepad 2 finger scroll stops working in OTHER applications (Chrome). 2-finger scroll still works in the processing IDE. Closing the sketch does not fix, closing Processing DOES fix. Only happens sometimes.

Not something I'm worried about, just an inconvenience, but if it's a real issue then there you have it! Over my head to try to fix or even diagnose.

**Comment by benfry** [comment]
Sounds like a JavaFX bug; we're not doing anything low-level that would be able to touch other applications.

**Comment by benfry** [comment]
Closing since this one's out of our control.
