### ISSUE TITLE
size() still executes in misspelled 'setupe()'

### ISSUE THREAD

**Issue by RectangleWorld** [processing/processing#3799]
A student accidentally misspelled setup as setupe, and oddly enough the size() function within it still executed!

Here is an example:
Of course the short program
```Java
void setup() {
  size(800, 600);
  background(0xFFFF0000);
}
```
results in a 800x600 red window. But surprisingly,
```Java
void setupe() {
  size(800, 600);
  background(0xFFFF0000);
}
```
(note the misspelling) results in a 800x600 gray window!

Bug or feature, you decide. Not sure if this illustrates an issue that might create problems in another context.

**Comment by benfry** [comment]
Hm, so this is causing a problem because it sees that you have no `setup()` method, so it assumes you're in a static mode sketch. It's a new problem caused by fixing #533, so we'd have to decide which is worse, this or that other one. (Or come up with a smarter parser...)

**Comment by JakubValtar** [comment]
Went the "smarter parser" route...
