### ISSUE TITLE
UnsatisfiedLinkError on startup "Access is denied" on Windows 10

### ISSUE THREAD

**Issue by B3040** [processing/processing#3800]
Hi, when I try to start processing.exe following "serious problem" pops up and the sketch doesn't show up:
![image](https://cloud.githubusercontent.com/assets/14276112/9855691/5211608a-5b10-11e5-931d-d724111f252d.png)
The corresponding log-file says:

![logfile](https://cloud.githubusercontent.com/assets/14276112/9856193/8bcb4356-5b13-11e5-8cf8-8cc47e82e3c0.jpg)

Platform used:

Processing version: 3.0b6 (Windows 64 bit)
sketch version: 150914a

Operating system: Windows 10 Home
Processor: Intel(R) Core(TM) i5-4210Y CPU @ 1.50 GHz 1.50 GHz
Installed RAM: 8.0 GB (7.88 GB usable)
System type: 64-bit operating system
Pen and touch: Full Windows touch support with 10 touch points

Notebook: Lenovo Ideapad Yoga 11S
Monitor: Generic PnP monitor
Display adapter: Intel(R) HD Graphics Family

On the platform given previous versions of processing don't work either.
Needless to say, the same processing version (3.0b6, Windows 64 bit) works well on my other PC.

How could this be fixed?

**Comment by benfry** [comment]
This is a problem in JNA, a library that Processing uses, but we need to find a workaround

Do you have a C:\TEMP folder? If so, try deleting it and then restarting Processing. 

Or if there is no C:\TEMP, try creating one and starting Processing.

Or if not, it's possible that the workaround I implemented for #3624 may not be compatible with new security settings in Windows 10.

**Comment by B3040** [comment]
I did not have a C:\TEMP when the error occurred.
After having created a C:\TEMP the same error still pops up ("java.lang.UnsatisfiedLinkError: Failed to create temporary file ... Access is denied")
Is there anything that I reasonably could do?

**Comment by benfry** [comment]
Try this version: http://download.processing.org/processing-150915a-windows64.zip (temporary link)

**Comment by B3040** [comment]
Many thanks for trying to help me so rapidly, but unfortunately it still does not work.
Now it says (with C:\TEMP):
"JNA could not be loaded properly." and 
"java.io.IOException: Access is denied."

**Comment by benfry** [comment]
Can you try creating C:\TEMP yourself and see if that works?

**Comment by B3040** [comment]
Probably I was not clear enough in my last reply:
After having created C:\TEMP <processing-150915a> still does not work.
The relevant parts of the error message are:
"JNA could not be loaded properly." and  "java.io.IOException: Access is denied."
And after having removed C:\TEMP the error message is:
"JNA could not be loaded into C:\TEMP."

**Comment by benfry** [comment]
Bummer... Are you running a standard or administrator account on that machine? Is it a clean install of Windows 10 or an upgrade? (Just trying to track down what's different from the Windows 10 machines I'm testing on.)

**Comment by B3040** [comment]
It is an Administrator account and a clean installation of Windows 10 Home, not an upgrade.

**Comment by B3040** [comment]
and I am signing in with my Microsoft account, not with a local account.

**Comment by benfry** [comment]
Oh... interesting. Wonder if that's a clue.

**Comment by B3040** [comment]
Signing in with a Microsoft Account or a Local Account doesn't make a difference. The same errors pop up as we know them, with or without a c:\temp folder, executing "processing-150915a" or "processing-3.0b6".
Do you continue to find a solution, or should I forget it and wait for the next update?

**Comment by benfry** [comment]
I haven't found free time to do a clean install of Windows 10 and test, unfortunately. Anyone want to help?

**Comment by neilcsmith-net** [comment]
Have you considered the alternative approach of shipping jnidispatch outside of the JNA jar, rather than relying on the JNA extraction mechanism?

**Comment by benfry** [comment]
Not really, because that just pushes the problem to the next component/library/etc that makes use of JNA.

**Comment by neilcsmith-net** [comment]
@benfry not sure why you think that?

JNA library extraction works brilliantly .. until it doesn't! :smile:  I'm a developer and / or maintainer of two JNA based libraries (both used often with Processing) - permission issues crop up from time to time.  The recommended way to handle this, and I can point you to posts on the JNA list about it, is to bypass automatic extraction.  The safest place to load jnidispatch from is probably the Processing installation directory.  It'll also probably make the process faster.

I don't know exactly how you're setting up java.library.path at the moment, but you could put jnidispatch somewhere there that it will be picked up.  Or possibly safer use jna.boot.library.path, and set jna.nosys back to false obviously.  Or there are a few other options.  None of which require anything of any additional component / library though!

Hope that helps, best wishes, Neil

**Comment by benfry** [comment]
Well, worth a try.

**Comment by benfry** [comment]
For people having problems with this, please try these versions and let me know how it goes:
http://download.processing.org/processing-150919a-windows32.zip
http://download.processing.org/processing-150919a-windows64.zip

**Comment by B3040** [comment]
With my Clean installation of Windows 10 Home and signed in on my microsoft account as administrator:
- processing-150919a-windows32: 
-- with as well as without C:\Temp: JNA Error. JNA could not be loaded.  java.lang.UnsatisfiedLinkError: Failed to create temporary file for jnidispatch library. Access denied ...

- processing-150919a-windows64: 
-- with C:\Temp:  Could not create temp directory.  java.io.IOException: Access is denied ... 
-- without C:\Temp: Could not create temp directory. JNA could not be loaded into C:\TEMP.

**Comment by benfry** [comment]
That's bizarre—the code to use C:\TEMP has been removed. Are you sure you quit out of any running version of Processing before trying this release?

**Comment by benfry** [comment]
Hold that thought—I think I've found a way to debug it. Looking into it now...

**Comment by B3040** [comment]
you are right. After a Restart processing-150919a-windows65 also reports: JNA Error. JNA could not be loaded. java.lang.UnsatisfiedLinkError: Failed to create temporary file for jdnidisplatch. Access denied.
BTW: How can I quit out a running version of Processing without making a Restart? I do not immediately see it in the Task Manager.

**Comment by benfry** [comment]
New versions, this time I think I've got it:
http://download.processing.org/processing-150920a-windows32.zip
http://download.processing.org/processing-150920a-windows64.zip

Sorry for the confusion—if the window isn't open, it's not running.

**Comment by B3040** [comment]
Not quite yet.
processing-150920a-windows32 and processing-150920a-windows64 report:
Setting issues. Processing cannot run because it could not create a folder to store your settings.

**Comment by benfry** [comment]
Huh... Is there more to that error message like a stack trace or more specific error?

**Comment by benfry** [comment]
So that means the JNA problem seen in this bug is fixed, but we've uncovered a new problem that's specific to Windows 10. I'm closing this issue as fixed, and we can continue the discussion here: https://github.com/processing/processing/issues/3838

**Comment by B3040** [comment]
no. that's all I get:
![image](https://cloud.githubusercontent.com/assets/14276112/9981730/6cf6c4b2-5fc5-11e5-96c6-4e0cef108f7c.png)

**Comment by benfry** [comment]
Ok, watch for updates over here: #3838.

**Comment by B3040** [comment]
thanks a lot so far, benfry, for your efficiency.
curious for the solution of item #3838.
