### ISSUE TITLE
CM: Able to update/download incompatible libraries

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3801]
I tried updating Greg's OpenCV library. The download and install was successful, but now it shows as grayed out and with a red exclamation ("incompatible") icon. Why did CM let me "update" if the current version is incompatible?  (Or, perhaps it *is* compatible, but is displayed incorrectly here.)

![e4540bde-5b9a-11e5-91d0-f84b5ce17850](https://cloud.githubusercontent.com/assets/1034002/9886011/095a2c0e-5b9d-11e5-8a3f-29a2724fc30c.png)

**Comment by Akarshit** [comment]
@alignedleft  There is currently no check if the updated version will be compatible or not.  
@benfry What should be done with these kind of updates that make the contribution incompatible.
A solution is to let only those updates take place that do not make the contribution incompatible.  

Should these kind of contributions be shown as fully updated in the CM ?

**Comment by benfry** [comment]
I'm confused as to why it's even listed for installation if it's known to not be compatible, which I think is @alignedleft's question as well.

**Comment by Akarshit** [comment]
@benfry A contribution(not installed) that will not be compatible is displayed in gray?( I am not sure but i remember a discussion somewhere that showing them in gray would encourage developers to update them)  
A contribution(installed) updating which will make it incompatible should be shown as fully updated.  
Is the above implementation correct ?

**Comment by alignedleft** [comment]
@Akarshit that's correct.  Incompatible contributions (installed or not) should appear in gray.

Incompatible contributions (installed) additionally show the red ! icon.

That said, we should not allow updating any contribution to the latest version when the latest version is not compatible. Could you disable the "Update" button in those cases? (There is no need to waste the user's time in downloading and installing in these cases.)
