### ISSUE TITLE
text editor window freezes (mac os x Yosemite 10.10.5)

### ISSUE THREAD

**Issue by nikolajRoager** [processing/processing#3803]
After a while, the text editor window (the one you write your code in, not the window with your running sketch), starts reacting very slowly, and will eventually stop responding at all, even if i try closing the window or program, (by pressing the red close window buttom in the top right, or by pressing cmd+q).

I am using a macbook pro from 2012, with mac os x yosemite 10.10.5

**Comment by benfry** [comment]
I've never seen anything like this, so what can you tell me about your setup? Do you have any Tools installed? What Mode are you using?

**Comment by benfry** [comment]
No response; closing.
