### ISSUE TITLE
fullScreen() error in Eclipse

### ISSUE THREAD

**Issue by riebschlager** [processing/processing#3807]
I'm attempting to use the new `fullScreen()` method in setup. It works fine in the Processing IDE, but in an Eclipse project it's throwing this:

`Exception in thread "Animation Thread" java.lang.IllegalStateException: fullScreen() cannot be used here, see https://processing.org/reference/fullScreen_.html`

If it's any help, trying to call `size(displayWidth, displayHeight)` throws the same error. Swapping those values out with ints allows it to run. Here's the entire app:

```
import processing.core.*;

public class MyAppName extends PApplet {

	 public void setup() {
		fullScreen();
	}

	public void draw() {
	}

	public static void main(String args[]) {
		PApplet.main(new String[] { "MyAppName" });
	}
}
```

**Comment by benfry** [comment]
Documented here: https://github.com/processing/processing/wiki/Changes-in-3.0#new
