### ISSUE TITLE
Memory leak in PGraphicsOpenGL

### ISSUE THREAD

**Issue by neilcsmith-net** [processing/processing#3809]
Just been doing some profiling on a memory leak and found a big issue with the fix for #3384  Any resources that are part of a PGraphics instance never get collected because the weak references contain a strong reference back to the referents via the PGL field.  Also means PGL and any offscreen graphics will never get collected either.

Possible fix might be to make the PGL field itself a WeakReference, perhaps in a GLResource abstract superclass for ease of managing it.

eg.

```java
WeakReference<PGL> pgl;
```

**Comment by neilcsmith-net** [comment]
Follow up thought - it's no use using the PGL instance from the offscreen graphics as that's likely to get GC'd at the same time - should be a WeakReference to the *primaryPGL*, which AFAIK has the same lifecycle as the GL context?  Speaking of which, do the resources need to check the PGL context is still current before cleaning up?

Does there *really* need to be a separate PGL per graphics?  That makes this whole thing more problematic.

**Comment by codeanticode** [comment]
what about adding a static PGL pglPrimary member to PGraphicsOpenGL, initialize in the constructor as:

```java
public PGraphicsOpenGL() {
    pgl = createPGL(this);
    if (primaryGraphics) {
      pglPrimary = pgl;
    }
```

and the use this static instance from the resource objects, instead of the pgl copy, like so:

```java
    public GLResourceTexture(Texture tex) {
      super(tex, refQueue);

      drainRefQueueBounded();

      pglPrimary.genTextures(1, intBuffer);     
```

**Comment by neilcsmith-net** [comment]
I would be wary of adding in more static state to fix this, particularly with a GC issue - it's the sort of thing that can pop up and bite later.  Remember anything static doesn't get GC'd until the Classloader does (so, effectively never).  In fact, probably the reference queues and lists would be better as instance fields of the primary PGL, but that's a bigger change that might not offer anything at the moment.

Also out of interest, does Processing officially support multiple windows?  There is at least one shipped example!  Wouldn't the above approach also be problematic in that case?  In fact, multiple window support might be a reason to move the queues into the primary PGL, if they're not using the same context - what happens when a resource tries to clear itself from the wrong context?

**Comment by benfry** [comment]
Processing does not support multiple windows. The demo was a fun hack, but if it requires much to get it running again, we'll just remove it. If it's not [here](https://processing.org/reference/), then it's not supported.

**Comment by codeanticode** [comment]
The memory leak problem is solved by using WeakReferences to store the offscreenFramebuffer and multisampleFramebuffer objects, see https://github.com/processing/processing/commit/da5c050433f73feb213adb3bd90fde36907439a2. I have been testing with this code:

```java
public void settings() {
  size(640, 360, P2D);
   smooth(2);
}
  
public void setup() {
}
  
public void draw() {
  if (mousePressed) {
    PGraphics pg = createGraphics(width, height, P2D);
    pg.beginDraw();
    pg.background(random(255), random(255), random(255));
    pg.endDraw();
    image(pg, 0, 0);
  }
}
```

**Comment by neilcsmith-net** [comment]
@benfry to be clear, the bug has nothing to do with multiple windows, although it would be a shame if the fix for this made them more difficult (even if unofficial).  I don't think the fix has to.

The *pathological* test case for this issue - use the CreateGraphics demo but move the createGraphics() into draw().  Yes, I know that's a stupid thing to do, but it makes the leak happen quickly! :smile: Checking in VisualVM (or similar), and pressing the force GC button just in case, you'll notice with the Java2D renderer the offscreen PGraphics get cleared, but changing them to P2D they don't.

Interestingly, this also happens in Processing 2, so it's not just the fixes for #3384 at work here. I think there might be another referent loop through the cacheMap.  It looks like offscreen PGraphics are stored in the cacheMap as a WeakReference key, but the Texture is a strong reference referring back to the PGraphics, so it never gets collected.  I would have expected PGraphicsOpenGL instances to be special cased because they have a direct access to their own texture?

**Comment by benfry** [comment]
@neilcsmith-net You can either be pedantic about things like this, or you can give us a break when we try to include a demo like that with a "nice to have" feature like multiple windows. If you're gonna be pedantic about it, then you ruin it for others because it's easier for us to remove it than being nagged about everything not running to perfection in all cases.

**Comment by neilcsmith-net** [comment]
@benfry What?? How do you read trying to help you fix a memory leak as being pedantic? The reason I asked about multiple windows is because my proposed solution wouldn't have affected that scenario and @codeanticode possibly would.  Officially supported, unsupported or "nice to have" might change how the bug is fixed.  And as stated, the bug itself, and my own concerns, have nothing to do with multiple windows!

My comment above crossed paths with @codeanticode fix.  Look forward to testing it in the next beta, though am puzzled by the cacheMap query above - might just be VisualVM wrongly calling out a GC root.

Anyway, Andres, thanks for the fix!  (this one's similar to something with GStreamer I was looking into - too much staring at VisualVM this week :smile: )
