### ISSUE TITLE
keep the method frame.setUndecorated(true)

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3811]
I try to switch from fullscreen and window in the process, so I must do that in the draw(), but with new method fullscreen() I must use the method in the settings() or setup().
So my idea it's use the old method to make a fullscreen, but Processing don't want and explain I must use the method fullscreen, because the method .setUndecorated(true) is not available. May be it's possible to keep few old methods for the people like me who want make their own fullscreen ?
![capture d ecran 2015-09-17 a 16 59 47](https://cloud.githubusercontent.com/assets/3332269/9936893/709e14e4-5d5e-11e5-93f8-2e107fdea369.png)

**Comment by benfry** [comment]
We won't be bringing that method back. This is a hack.

**Comment by StanLepunK** [comment]
What you mean by this is a hack ????
So maybe give the possibility to recover the decoration when we change the size on the window by the method surface.setSize(x,y); ?

**Comment by StanLepunK** [comment]
Like surface.setSize(x,y,true) or surface.setSize(x,y,false) if we want decoration or not.

**Comment by benfry** [comment]
Using `removeNotify()`, `addNotify()`, and `setUndecorated()` to get a full screen window is a hack. You have no idea what `removeNotify()` does, for instance.

**Comment by StanLepunK** [comment]
I trust you, I go to search information about that. thx for the light.
