### ISSUE TITLE
autocomplete timing errors

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3812]
I am not able to get code completion to work properly in 0245.   It is working properly for me in 3.0b5.  It appears to be some sort of timing problem, as sometimes the correct completion menu pops up, but quite a bit of time as passed since I hit cntrl-space.  There is some very awkward video documentation of this here:

https://www.youtube.com/watch?v=LOcSnePMfb0&feature=youtu.be&t=1076

Are others seeing this or just me?

**Comment by benfry** [comment]
Yes; confirmed. I saw it Tuesday and @JakubValtar and I are trying to track it down.

**Comment by benfry** [comment]
Possibly a regression in https://github.com/processing/processing/commit/24508804ddac585a9356e64f214a4bb8c4a92a45

**Comment by benfry** [comment]
@shiffman Can you try the current source?

**Comment by shiffman** [comment]
It's working better for me now in that the sever delay/getting stuck issue is resolved.  However, and I can't pinpoint exactly why this occurs (speed/timing of my typing?), I am sometimes seeing a syntax error which then I think kills the code completion.  It is working ~75% of the time and I'm getting an error ~25%.  Here is a video showing you what I'm seeing (though you will have to use your imagination as to when I am hitting cntrl-space.)

https://www.dropbox.com/s/nkizev14xiv6tvp/code_completion.mov?dl=0

I also just noticed if I turn off "continously check for errors" the code completion works without fail.

**Comment by benfry** [comment]
Pull request to fix this one is on its way from @JakubValtar for 3.0 beta 7.
