### ISSUE TITLE
Tools are getting redundantly added when installing new tool

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3818]
After a tool is installed from the CM, all the tools get added again to the tool menu.  
Here is how it looks after installing a single tool
![screenshot from 2015-09-18 14 47 59](https://cloud.githubusercontent.com/assets/7762605/9956219/b77b4e66-5e14-11e5-8633-8d0884154196.png)
and after installing two tools 
![screenshot from 2015-09-18 14 48 23](https://cloud.githubusercontent.com/assets/7762605/9956228/c903d50e-5e14-11e5-8811-b705061fdfbc.png)

**Comment by benfry** [comment]
Hopefully fixed in #3820.
