### ISSUE TITLE
fullscreen() is maybe too rigid ?

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3822]
I work around the fullscreen, and I've feeling this method is very rigid with the obligation to write this one at the first line of the setup. Sure there is a ton of reasons for that, but I give my feeling.

this code is not possible : 
````
void setup() {
  int screen = 2 ;
  if (screen == 1 ) { 
    fullScreen(1) ;
  } else {
    fullScreen(2) ;
  }
}
````
this one is not possible too 
void setup() {
  boolean fullscreen = false ;
  if ( fullscreen) { 
    fullScreen(1) ;
  } else {
    size(300,300) ;
  }
}
````
So it's very hard - see impossible - when you want use information from outside to decide if you want a fullscreen or not. And if you want fullscreen to choice on which one you want display. Maybe there is something to do to give to give a little flexibility to this method ?

**Comment by benfry** [comment]
You can do that inside `settings()`.

**Comment by REAS** [comment]
FYI: https://processing.org/reference/settings_.html

**Comment by StanLepunK** [comment]
@REAS When I read about the fullscreen() I don't see that I can use fullScreen() in the settings(), may be add a little word about that in the description ?
Now the challenge, read an external file to choice which screen must be display in full screen, in the settings() is not easy without sketchpath(), but that it's my problem :)

**Comment by StanLepunK** [comment]
@benfry @codeanticode @REAS 
Some time i'm a headstrong, but for me to have a possibility to manipulate ````fullScreen()````like ````size()````can really be good. 
With the obligation to put this method at the top of the ````setup()```` that remove the possibility to choice on which screen display from an external file, for the simple reason it's not possible to open file in the ````settings()````
So my idea, if it's not possible to move the ````fullScreen()````from the first line of the ````setup()````may be it's possible to add a method like ````surface.fullScreen(int which_screen) ```` to change that after.

I'm really sorry for the disturbing, but I try to find a solution to choice where I want display my full screen from a external file and I'm totally lock by this obligation to write ````fullScreen()````at the top of the ````setup()````
