### ISSUE TITLE
setResizable broke with oscilating behavior in 3.0b6 

### ISSUE THREAD

**Issue by aradke** [processing/processing#3825]
The `P2D` and `P3D` render modes in _core_ now cause a strange oscillating motion when dragged to a new size with `setResizable` enabled.  The following code reproduces the issue:

```java
void settings(){size(640,480, P2D);}
void setup(){surface.setResizable(true);}
void draw{rect(10,10,10,10);}
```

The entire window will oscillate back and forth from the new size to the original size several times a second.

The `FX2D` and `JAVA2D` still work.  This issue was not present in previous alpha or beta versions before 3.0b6. _(Note: This was tested on a Windows 7 machine with the 64bit distribution)_

**Comment by benfry** [comment]
@codeanticode will you be able to look at this one?

**Comment by codeanticode** [comment]
This commit https://github.com/processing/processing/commit/42c0150da0f400637de916db1f94a687a7bc4288 fixes the issue.
