### ISSUE TITLE
Some keys is not recognized properly in P2D / P3D rendering modes

### ISSUE THREAD

**Issue by StanislavGrinkov** [processing/processing#3827]
Issue: Some keys is not recognized in P2D / P3D mode on ubuntu trusty (14.04).

Environment: Ubuntu Trusty, Processing 3.0b6

How to replicate: run sketch in different render modes and press keys

Expected: Keys is recognized properly in each render mode
![render-keys-default](https://cloud.githubusercontent.com/assets/7836782/9974829/80b05c76-5ec5-11e5-8a03-2bccb8b0cd8f.png)

Actual: see screenshots
P2D
![render-keys-p2d](https://cloud.githubusercontent.com/assets/7836782/9974833/99e192d2-5ec5-11e5-871b-14bb15cd32e7.png)

P3D
![render-keys-p3d](https://cloud.githubusercontent.com/assets/7836782/9974834/9b8380be-5ec5-11e5-9a77-8329141b05de.png)

Possibly linked to #3352

// ~~~~~~  Sketch  ~~~~~~~
import java.awt.event.KeyEvent;

void setup()
{
  size(100,100);
  // size(100,100, P2D);
  // size(100,100, P3D);
}

void draw()
{
  background(123);
}

void keyPressed() 
{
  println("Key is ==>"+KeyEvent.getKeyText(keyCode)+"<==");
}

**Comment by nakednous** [comment]
Same processing version, but in my archlinux-64 bit all the keys are recognized. Perhaps it has to do with your ubuntu version which seems a bit dated. Can you try to test it under a different (perhaps newer) environment?

**Comment by StanislavGrinkov** [comment]
I will try on another distro version when possible.
p.s. 14.04 is a LTS version of ubuntu and I have all available updates installed. (I feel that it could be issue with my system, as usual when I report issues :) )

**Comment by StanislavGrinkov** [comment]
Tried on live ubuntu 15.04. No issues. It could be something with my java version /keybd daemon or something else.
Sorry for taking your time.
Please close this issue.

**Comment by JakubValtar** [comment]
Hmm, I don't think AWT will give you correct results for NEWT events which are used in OpenGL. Try to use something like this:
```java
import com.jogamp.newt.event.KeyEvent;

void keyPressed()
{
  switch (keyCode) {
    case KeyEvent.VK_DELETE:
      println("DELETE");
      break;
    case KeyEvent.VK_INSERT:
      println("INSERT");
      break;
  }
}
```

**Comment by benfry** [comment]
Switching this to a docs issue: https://github.com/processing/processing-docs/issues/318
