### ISSUE TITLE
text()/textWidth() mismatch

### ISSUE THREAD

**Issue by nakednous** [processing/processing#3829]
* What steps will reproduce the problem?

run the following sketch:

```java
PFont buttonFont = loadFont("FreeSans-36.vlw");
textFont(buttonFont);  
String str = "last";//last character 't' is not printed
text(str, 10, 10, textWidth(str), textAscent() + textDescent());
```

* What is the expected output? 

the string "last" should be printed.

* What do you see instead?

only "las" is printed

* What version of the product are you using? 

P5-3.0-b6

* On what operating system?

ArchLinux-x64.

**Comment by benfry** [comment]
Oh come on, it's not going to be fractionally pixel perfect. Just use `text(str, 10, 10)` for this.
