### ISSUE TITLE
Short-cuts used for stepping in debug also insert newlines into source

### ISSUE THREAD

**Issue by IanBadcoe** [processing/processing#3830]
The short-cuts for stepping involve ctrl-J.  That's a newline (or maybe a carriage return) and gets typed into the editor.  Is editing supposed to be possible at all during debugging?

**Comment by dnlopez** [comment]
I'm encountering the same problem. I'm using Processing 3.0.1 on Arch Linux, 64-bit.

Also happens with Ctrl-Shift-J (step into) and Ctrl-Alt-J (step out).

Duplicate bugs I found in search: 4003, 1803

**Comment by JakubValtar** [comment]
Ctrl+J is a shortcut to insert newline character and it is not properly filtered. Working on a fix.

*Note to self: should ckeck if event was consumed (by menu action) before sending it to the editor, but JSplitPane keeps consuming all arrowkeys and home/end etc. so figure that one out first.*

**Comment by midinerd** [comment]
Can you just set the keyboard shortcuts to I instead of J?  I won't complain.

**Comment by benfry** [comment]
Fixed with https://github.com/processing/processing/pull/4806
