### ISSUE TITLE
Make git commit messages descriptive

### ISSUE THREAD

**Issue by hamoid** [processing/processing#3834]
I take a look at https://github.com/processing/processing/commits/master almost daily to know what is happening in the development of Processing. I believe it could be a great resource to know what and why things are happening, but often there's not much to learn from the commit messages. Wouldn't it be great if the commit log also served as an educational tool?

I found this post about writing commit messages useful: http://chris.beams.io/posts/git-commit/

Even just applying point 5 would make a big difference. Basically, using this template when writing the message: 

    If applied, this commit will [your message here]

See the link above for examples. I think it does not need to take any more time than it does now to write the message, and it might help people understand the evolution of the code. Maybe the how-to-write-commit-messages could be part of the code style-guide in the wiki?

What do you think?

**Comment by benfry** [comment]
I think it's subjective. The commit messages I write are intended to be descriptive in the context of the code they represent. In an ideal world I'd have all sorts of time to write beautiful prose. I don't. I'm doing this in my free time.
