### ISSUE TITLE
"update all" button appears to do nothing in library manager

### ISSUE THREAD

**Issue by JobLeonard** [processing/processing#3837]
Ubuntu 15.04, Processing 3.0b6.

Noticed when updating the Sound library to v1.3

Clicking on "update all" has no visible consequences. Moving to individual libraries doesn't show that they are being downloaded either.

Individually starting updates seems to work fine though.

**Comment by Akarshit** [comment]
Progress bar will be visible in the individual libraries now after `update all` is clicked

**Comment by benfry** [comment]
Incorporated for beta 7.
