### ISSUE TITLE
"Processing cannot run because it could not create a folder to store your settings" on Windows 10

### ISSUE THREAD

**Issue by benfry** [processing/processing#3838]
Having sorted out the JNA issues in #3800, we now need to get a settings folder that's safe to use on a clean install of Windows 10.

**Comment by benfry** [comment]
@B3040 can you try this version? 
http://download.processing.org/processing-150920b-windows64.zip

It should provide a better error message about what's going on, including the path that it's trying to write to, which should tell us why it's failing.

**Comment by B3040** [comment]
here is the path:
![image](https://cloud.githubusercontent.com/assets/14276112/9982185/3ba8101a-5fd3-11e5-9f18-a906e825ba96.png)

**Comment by benfry** [comment]
Ok, so that looks entirely correct. What happens if you go to that folder (AppData > Roaming) and try to create a folder named "Processing"?

**Comment by benfry** [comment]
Nevermind that, posting an alternate version. One second...

**Comment by benfry** [comment]
Here we go: http://download.processing.org/processing-150920c-windows64.zip

And if this doesn't work, please check the path that's seen in that dialog box (Users > herbe > AppData > Roaming). The AppData folder is hidden, so you may have to type it in at the top of the Windows Explorer window.

**Comment by B3040** [comment]
I created that folder, 
![image](https://cloud.githubusercontent.com/assets/14276112/9982337/c8b070b0-5fd8-11e5-976f-b12db2cf1133.png)

and the result is:
![image](https://cloud.githubusercontent.com/assets/14276112/9982348/fff72564-5fd8-11e5-8fc5-1ef08615abe1.png)

**Comment by benfry** [comment]
Are you running Processing as a different user? This is really odd... Or is the "Roaming" folder owned by another user than you?

**Comment by B3040** [comment]
no, there are 2 accounts on this machine: my microsoft account and my local account, and for both I have administor rights. Currently I am using the microsoft account.
Does this info help you?
![image](https://cloud.githubusercontent.com/assets/14276112/9982416/02c71d46-5fdc-11e5-9c76-6a9d76c0c591.png)

**Comment by benfry** [comment]
Yeah, so for some reason, you don't have write (or full control) access to your own "Roaming" folder. For instance, this is what it looks like on my Windows 10 installation:

<img width="1154" alt="windows 10 permissions" src="https://cloud.githubusercontent.com/assets/1623101/9982493/799716cc-5fac-11e5-86a9-325c6f530e72.png">

**Comment by benfry** [comment]
I've seen one report that installing Acrobat might cause this, but I'm not finding much definitive.

**Comment by B3040** [comment]
Now I have changed the setting for Roaming as such:
![image](https://cloud.githubusercontent.com/assets/14276112/9982647/7a73fb32-5fe3-11e5-864f-eae266918306.png)
Looks that OK? Do you need additional info?
Nevertheless, processing-150920c-windows64 delivers:
![image](https://cloud.githubusercontent.com/assets/14276112/9982664/ce1a6adc-5fe3-11e5-88a1-04febfd04ee9.png)

Yes, I installed Adobe Acrobat X Pro and Distiller X.

**Comment by benfry** [comment]
Ok, I've added more code for this that'll try to find an alternate workaround and give a better error message about permissions, but that's as far as we can go to fix this issue.

**Comment by B3040** [comment]
OK, let's hope the best for 3.0 beta 7.
And meanwhile many thanks again for the great work you have done so far.

**Comment by benfry** [comment]
Fingers crossed! Appreciate your help in tracking this down.
