### ISSUE TITLE
problem with sketchPath() in void settings()

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3839]
When ````sketchPath()```` is uded in ````void settings()````, it don't return the good path in the Processing IDE, but when it's an App the path is good.
`````
String path ;
void settings() {
  path = sketchPath() ;
  size(1200,150) ;
}

void setup() {
  background(0) ;
  fill(255) ;
  text(path,12,12) ;
}
````
In Processing
![capture d ecran 2015-09-21 a 11 21 08](https://cloud.githubusercontent.com/assets/3332269/9988736/67cda792-6053-11e5-9ff0-7f1f36cf55fb.png)
in APP
![capture d ecran 2015-09-21 a 11 21 24](https://cloud.githubusercontent.com/assets/3332269/9988740/6e2a2b6a-6053-11e5-8774-710a9fc7adc7.png)

**Comment by benfry** [comment]
This is clearly stated in the reference: https://processing.org/reference/settings_.html
> The settings() method runs before the sketch has been set up, so other Processing functions cannot be used at that point. For instance, do not use loadImage() inside settings(). The settings() method runs "passively" to set a few variables, compared to the setup() command that call commands in the Processing API.

**Comment by StanLepunK** [comment]
I understand and I read this post about ''''settings()'''' before. 
But when you want use ''''fullscreen()'''' and choice on which screen display from an external file you are lock because you must use ''''fullscreen()'''' on the first line of the ''''setup()'''' with no possibility to open any file to read info. I try to make a java code to find the path but it's very to difficult for me.
It's reason why I try to open something from the ''''settings()''', may be it's possible make few exceptions for a little method, to give the possibility to use in the ''''settings()'''' ? 

If I understand, I must move on Ecclipse or Netbean to do that ? In this case I use Processing like a library ?

**Comment by benfry** [comment]
No. You should only use `settings()` if you're in Eclipse or Netbeans. If you're using the PDE, just pretend it's not there.

**Comment by StanLepunK** [comment]
So it's dead to choice the ````fullscreen(int which_one)```` from an external file :(  May be it's possible to create a method to switch the display for the full screen, like ````surface.whichScreen(int var)```  to give the possibility to the user to choice from an external file ?

I can open an issue for that if you think is good idea ?
