### ISSUE TITLE
MouseWheel count wrong (backwards?) in P2D and P3D

### ISSUE THREAD

**Issue by tillnagel** [processing/processing#3840]
In the [documentation](https://processing.org/reference/mouseWheel_.html) it says it should return "positive values when the mouse wheel is rotated down". This is true only for JAVA2D. In other renderers the values are negative. 

It happens on mouseWheel as well as when registering to mouseEvents.

```
void setup() {
  size(400, 400, JAVA2D); // switch to P2D for testing
  registerMethod("mouseEvent", this);
}

void draw() {
}

void mouseWheel(MouseEvent e) {
  println("mouseWheel.c:" + e.getCount());
}

public void mouseEvent(MouseEvent e) {
  if (e.getAction() == MouseEvent.WHEEL) {
    println("mouseEvent.c:" + e.getCount());
  }
}
```

Possibly related to #3828.

**Comment by tillnagel** [comment]
On further investigation I believe it is due to the direct use of the AWT and the JOGL implementation values which are opposite to each other. 

[PSurfaceAWT](https://github.com/processing/processing/blob/master/core/src/processing/awt/PSurfaceAWT.java#L1249) uses getWheelRotation() which, according to [Oracles's Javadoc](http://docs.oracle.com/javase/7/docs/api/java/awt/event/MouseWheelEvent.html#getWheelRotation%28%29), returns "positive values if the mouse wheel was rotated down/ towards the user."

[PSurfaceJOGL](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PSurfaceJOGL.java#L945), however, uses getRotation() which, according to [JOGL's Javadoc](https://jogamp.org/deployment/webstart/javadoc/jogl/javadoc/com/jogamp/newt/event/MouseEvent.html#getRotation%28%29), returns values "< 0.0f" when "vertical rotation [...] is down."

**Comment by benfry** [comment]
@codeanticode Haven't you solved this one before?

**Comment by codeanticode** [comment]
I don't remember, if I did it was quite a while ago, at least since we first implemented NEWT support...

I just committed https://github.com/processing/processing/commit/c09ef8e80f5c98b344ea90f99adb876332d2a7d8, which fixes the issue. Tested on OS X.

**Comment by codeanticode** [comment]
Just confirming that wheel count is consistent between JAVA2D and P2D/P3D on Windows as well.

**Comment by benfry** [comment]
Cool, thanks.

**Comment by tillnagel** [comment]
Great, thanks. 

Just as a side note, the values still differ. With a Apple Magic Mouse in P2D I can get values up to 1000 and more, while in JAVA2D I cannot get values higher than 200. (No idea if those are the actual max values, just jerking over the mouse's surface.) Not important, IMO, just to mention.
