### ISSUE TITLE
FX2D Images turned upsidedown in Linux

### ISSUE THREAD

**Issue by nakednous** [processing/processing#3844]
* What steps will reproduce the problem?

Run the alphamask example or any other image example, using the ```FX2D``` new renderer.

* What is the expected output? 

Image displayed correctly as when using ```JAVA2D```

* What do you see instead?

Images turned upsidedown in Linux

* What version of the product are you using? 

P5-3.0-b6

* On what operating system?

ArchLinux-x64.

**Comment by benfry** [comment]
Is this https://github.com/processing/processing/issues/3795?
