### ISSUE TITLE
RFC: randomColor() function

### ISSUE THREAD

**Issue by ybakos** [processing/processing#3852]
This is a request for comment for a contribution that would add a `randomColor()` function to the Processing core.
```
color c = randomColor(); // where r, g and b are in the range (0, 255), and alpha is 255.
```

The benefits are to provide beginners with a simple method of incorporating a variety of colors into a sketch without having to verbosely invoke `color(random(0, 255), random(0, 255), random(0, 255))`.

However, I can understand how making it too easy to use random colors can negatively influence praxis.

_Note to core contributors: A simple "no" is succinct enough. I get it._

**Comment by REAS** [comment]
I will invoke "no" at this time, but thank you for thinking about the API and communicating. :)

I think there's a wide open space for color libraries and a simple way to make a random color could be a part of that.
