### ISSUE TITLE
Simple graph program does not work

### ISSUE THREAD

**Issue by AlanTJohnstone** [processing/processing#3853]
I have come back to Processing after some time away so forgive me if this is obvious but the following program, roughly copied from the Arduino examples works in Processing 2.1.1
 import processing.serial.*;

  Serial myPort;        // The serial port
  int xPos = 1;         // horizontal position of the graph
  ArrayList points = new ArrayList  ();
  void setup () 
  {
    // set the window size:
    size(1000, 300);

    // List all the available serial ports
    // if using Processing 2.1 or later, use Serial.printArray()
    println(Serial.list());

    // I know that the first port in the serial list on my mac
    // is always my  Arduino, so I open Serial.list()[0].
    // Open whatever port is the one you're using.
    myPort = new Serial(this, Serial.list()[0], 115200);

    // don't generate a serialEvent() unless you get a newline character:
    myPort.bufferUntil('\n');

    // set inital background:
    background(0);
  }
  void draw () 
  {
    // everything happens in the serialEvent()
  }

  void serialEvent (Serial myPort) 
  {
    // get the ASCII string:
    String inString = myPort.readStringUntil('\n');

    if (inString != null)
      {
      // trim off any whitespace:
      inString = trim(inString);
      // convert to an int and map to the screen height:
      //println(inString);
      float inNo = float(inString);
      print("inNo = ");println(inNo);
      inNo= map(inNo, 0, 1023, 0, height);
      

      // draw the line:
      stroke(127,34,255);
      line(xPos, height, xPos, height - inNo);

      // at the edge of the screen, go back to the beginning:
      if (xPos >= width)
        {
        xPos = 0;
        background(0);
        }
       else 
        {
          // increment the horizontal position:
          xPos++;
        }
        }
  }

If you comment out the line in Serial event which says
 print("inNo = ");println(inNo);
the program fails because it gets an "NaN" in the Map function
With the line in place there is no error but no graph is shown.
What am I doing wrong?
Alan

**Comment by benfry** [comment]
Please use forum.processing.org for programming questions.
