### ISSUE TITLE
surface. dont work with full screen P3D et P2D

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3859]
Processing 3.0b7 / OSX 10.9.5 
@codeanticode 
````fullScreen(P3D)````and ````fullScreen(P2D)```` FX2D and the default rendered work fine.
````surface.setLocation(x.y)````don't work
````surface.setSize(x.y)````work bad, the size change but the most of part of screen became black
````
void setup() {
  fullScreen(P3D) ;
}

void draw() {
  surface.setLocation(30,30) ;
  surface.setSize(300,300) ;
}
````
![capture d ecran 2015-09-23 a 15 30 34](https://cloud.githubusercontent.com/assets/3332269/10046274/161f084e-6208-11e5-98bf-fd7b402e3370.png)

**Comment by benfry** [comment]
No, this is silly... You told it to go full screen. That's it.

**Comment by StanLepunK** [comment]
Why is silly ???? 
In case you want change the position of your full screen, you must resize and change location, I think that can be good, to have this option when the ````fullScreen()```` have the obligation to be at the top of the ````setup()```` like in my suggestion method https://github.com/processing/processing/issues/3857

**Comment by StanLepunK** [comment]
Plus, if a people want display his sketch P3D or P2D without decoration but not on full screen, the only way to do that it's by ````fullScreen()````because now it's not possible to remove decoration.

**Comment by benfry** [comment]
As I already said in #3857, this is better handled by a library. It's enormously complex to make this work in a supportable, consistent way across platforms and renderers. We have no plans to incorporate this in the core.

**Comment by StanLepunK** [comment]
Thx for the explication. It's very very very bad news for me and my project https://github.com/StanLepunK/ROMANESCO, but that's life. So the only option I have is create one sketch with ````fullScreen()````an other with ````size()```` is not really good option, I already have four sketches :( So If you have any idea, track to help me on this way that's very very welcome. I'm little desperate !
