### ISSUE TITLE
Enable complex text input? 

### ISSUE THREAD

**Issue by CyberianWolf** [processing/processing#3860]
Hmm..

[ Processing / Preferences / Enable complex text input (i.e. Japanese..) ] 
does not work properly
in the case of the 2 bytes Asian character set Input
(i.e. Chinese, Japanese, Korean, especially in Korean).

**Comment by benfry** [comment]
What operating system? What version of Processing?

**Comment by CyberianWolf** [comment]
I'm so sorry about that. 

OS: Microsoft Windows 8.1 Enterprise K (Build 9600) // 'K' means 'Korean Language'?
Processing Version: 3.0 b7 and 3.0

On writing text with Processing 3 IDE, if the font set is the Korean character set font, 

1) each characters are over-wrapped? over-written? half-over-written! 
Interval space between (for example) 'A character' and 'B character'is very short, very very shorter than '0'. It's 'negative'. Is this called 'over-wrapped'? 

Ohh, my English writing ability is very poor!!
I don't know what shoud I say. I'm not a English speaker. So, please, think about this problem.

2) Another case, I didn't mis-type. But  the result is so weird. 
No, virus, No malware. My 'new' computer is clean. 

But, English goes well!

ㅠ.ㅠ;

(Wait, I'll show you some screenshots.)

![processing_3_0_a_](https://cloud.githubusercontent.com/assets/12027179/10233699/1bc8ed04-68cb-11e5-9d74-6890099ee23e.jpg)
![processing_3_0_b_](https://cloud.githubusercontent.com/assets/12027179/10233694/1bb4b6a4-68cb-11e5-820d-a96ac543e702.jpg)
![processing_3_0_c_](https://cloud.githubusercontent.com/assets/12027179/10233698/1bc83e36-68cb-11e5-8479-10c30f9f4db5.jpg)
![processing_3_0_d_](https://cloud.githubusercontent.com/assets/12027179/10233695/1bc5267e-68cb-11e5-887d-40384ba31933.jpg)
![processing_3_0_e_](https://cloud.githubusercontent.com/assets/12027179/10233696/1bc56832-68cb-11e5-9535-af878132ea4f.jpg)
![processing_3_0_f_](https://cloud.githubusercontent.com/assets/12027179/10233697/1bc77b40-68cb-11e5-9296-df9173380c9e.jpg)

**Comment by CyberianWolf** [comment]
But, 'Copy and Paste' function works well. 

Processing 3 Input function bugs me, so, ...

I wrote the print() with Windows 8.1 K Notepad program and then copy all of the text  and paste into Processing IDE. 

It works well !! 

So, strange!

But I love Processing!

![processing_3_0_g_](https://cloud.githubusercontent.com/assets/12027179/10234371/1943c30c-68cf-11e5-8d54-12eba126f57e.jpg)
![processing_3_0_h_](https://cloud.githubusercontent.com/assets/12027179/10234372/1945cf08-68cf-11e5-8e08-e7f9c2970279.jpg)

**Comment by CyberianWolf** [comment]
I did 'copy/paste' the last line.

![processing_3_0_i_](https://cloud.githubusercontent.com/assets/12027179/10234604/b1b450f6-68d0-11e5-9031-1489e7eb3019.jpg)

Help me, please!

**Comment by CyberianWolf** [comment]
// 6 characters typed but 4 characters displayed!

![processing_3_0_j_](https://cloud.githubusercontent.com/assets/12027179/10234734/b3ada83e-68d1-11e5-9d45-02cb8ea8cc80.jpg)

**Comment by CyberianWolf** [comment]
// Another Korean Font Test.

print("Hello, James! = 헬롱, 젱임!");
// Not correct!
// Processing 3 IDE typing.


print("Hello, James! = 헬로우, 제임스!"); 
// Correct!
// Copy/Paste.

![processing_3_0_k_](https://cloud.githubusercontent.com/assets/12027179/10234914/f4f55da4-68d2-11e5-872e-7aaa34e0705a.jpg)

**Comment by satoshiokita** [comment]
I installed Korean input method in my window8.1 64bit(japanese). and tested above probrem.
current processing3 following method  is only support Japanese.  this logic can not handle korean input method correctly.

InputMethodSupport#inputMethodTextChanged
```
  public void inputMethodTextChanged(InputMethodEvent event) {
    if (Base.DEBUG) { // my debug print
      StringBuilder sb = new StringBuilder();
      sb.append("#Called inputMethodTextChanged");
      sb.append("\t ID: " + event.getID());
      sb.append("\t timestamp: " + new java.util.Date(event.getWhen()));
      sb.append("\t parmString: " + event.paramString());
      Messages.log(sb.toString());
    }
    
    AttributedCharacterIterator text = event.getText();
    committed_count = event.getCommittedCharacterCount();
    if(isFullWidthSpaceInput(text)){
      textManager.insertFullWidthSpace();
      caretPositionChanged(event);
      return;
    }
    if(isBeginInputProcess(text, textManager)){
      textManager.beginCompositionText(text, committed_count);
      caretPositionChanged(event);
      return;
    }
    if (isInputProcess(text)){
      textManager.processCompositionText(text, committed_count);
      caretPositionChanged(event);
      return;
    }
    textManager.endCompositionText(text, committed_count);
    caretPositionChanged(event);
  }
```

```
BK Key
Starting error check
#Called inputMethodTextChanged	 ID: 1100	 timestamp: Mon Feb 08 14:09:02 JST 2016	 parmString: INPUT_METHOD_TEXT_CHANGED, "" + "ㅎ", 0 characters committed, caret: TextHitInfo[0L], visible position: TextHitInfo[0L]
debug: FontRenderContext is Antialiased = Antialiased text mode
Starting error check
#Called inputMethodTextChanged	 ID: 1100	 timestamp: Mon Feb 08 14:09:02 JST 2016	 parmString: INPUT_METHOD_TEXT_CHANGED, "" + "헤", 0 characters committed, caret: TextHitInfo[0L], visible position: TextHitInfo[0L]
debug: FontRenderContext is Antialiased = Antialiased text mode
Starting error check
Starting error check
#Called inputMethodTextChanged	 ID: 1100	 timestamp: Mon Feb 08 14:09:02 JST 2016	 parmString: INPUT_METHOD_TEXT_CHANGED, "" + "헬", 0 characters committed, caret: TextHitInfo[0L], visible position: TextHitInfo[0L]
debug: FontRenderContext is Antialiased = Antialiased text mode
Starting error check
Starting error check
#Called inputMethodTextChanged	 ID: 1100	 timestamp: Mon Feb 08 14:09:08 JST 2016	 parmString: INPUT_METHOD_TEXT_CHANGED, "헬" + "", 1 characters committed, caret: TextHitInfo[0L], visible position: TextHitInfo[0L]
#Called inputMethodTextChanged	 ID: 1100	 timestamp: Mon Feb 08 14:09:08 JST 2016	 parmString: INPUT_METHOD_TEXT_CHANGED, "" + "ㄹ", 0 characters committed, caret: TextHitInfo[0L], visible position: TextHitInfo[0L]
debug: FontRenderContext is Antialiased = Antialiased text mode
Starting error check
#Called inputMethodTextChanged	 ID: 1100	 timestamp: Mon Feb 08 14:09:08 JST 2016	 parmString: INPUT_METHOD_TEXT_CHANGED, "" + "로", 0 characters committed, caret: TextHitInfo[0L], visible position: TextHitInfo[0L]
debug: FontRenderContext is Antialiased = Antialiased text mode
Starting error check
Starting error check
#Called inputMethodTextChanged	 ID: 1100	 timestamp: Mon Feb 08 14:09:25 JST 2016	 parmString: INPUT_METHOD_TEXT_CHANGED, no text, 0 characters committed, caret: TextHitInfo[0L], visible position: TextHitInfo[0L]
Starting error check
#Called inputMethodTextChanged	 ID: 1100	 timestamp: Mon Feb 08 14:09:25 JST 2016	 parmString: INPUT_METHOD_TEXT_CHANGED, "로" + "", 1 characters committed, caret: TextHitInfo[0L], visible position: TextHitInfo[0L]
Starting error check

```

Hangul - ascii type.
----------
헬 gpf
로 fh
,
제 wp
임 dla
스 tm

**Comment by satoshiokita** [comment]
I rewirte to CJK support now. i wll send the pull-request.

https://github.com/satoshiokita/processing/tree/FIX-IM-CJKSupport/

Korean support!
![issue3860_01](https://cloud.githubusercontent.com/assets/16870334/12879102/db5ad0e0-ce71-11e5-853f-29022a6c1f2d.png)


#2968 maybe same problem.

**Comment by benfry** [comment]
Closed with https://github.com/processing/processing/pull/4293 for 3.0.2.
