### ISSUE TITLE
Give a name to the APP for the exportation

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3862]
May be that can be good to have a possibility to give a name to the application when you export this one ?

**Comment by benfry** [comment]
No plans to implement this. Lots of complexity for very little benefit. It's trivial to rename the application after it's been created if you don't want to use the sketch name.

**Comment by StanLepunK** [comment]
No problem it's suggestion, but not sure is a "trivial" functionnality, may be superfluous, but useful :)
