### ISSUE TITLE
IDE Error checking bug with multi line comments.

### ISSUE THREAD

**Issue by 7e11** [processing/processing#3866]
The processing ide thinks that there are errors with the following code:
```java
int[] a = {4, 5, 6}; //This semicolon throws: "Missing right curly bracket "}""
println(a); //The "a" throws: "...VariableDeclaratorId"

/*
void test() {}
*/
```
However, this code works fine.
output:
```java
[0] 4
[1] 5
[2] 6
```

I've noticed that changing the `void test() {}` to `Void test() {}` makes the ide show no errors.
Also changing the multi line comment to a single line: `//void test() {}` fixes it as well.
Removing the multi line comment entirely (just leaving `void test() {}`) also fixes the `Missing right curly bracket "}"` error, but not the `...VariableDeclaratorId` on the "a".

**Comment by JakubValtar** [comment]
This was fixed in 3.0b7.
