### ISSUE TITLE
Frame size displays incorrectly if surface.setResizable(true) 3.0b7

### ISSUE THREAD

**Issue by MackSix** [processing/processing#3868]
If surface.setResizable(true) for the default renderer, the frame displays with the circle out of bounds on the right and bottom of frame.  (Processing 3.0b7)

CODE:
```
public void settings() {
    size(400, 400);
}

public void setup() {
    surface.setResizable(true);
}

public void draw() {
    fill(0,255,255);
    stroke(0,0,255);
    strokeWeight(10);
    ellipse(200, 200, 390, 390);
}
```

**Comment by benfry** [comment]
What OS, etc are you using? That's working fine for me:

<img width="512" alt="screen shot 2015-09-25 at 3 25 55 pm" src="https://cloud.githubusercontent.com/assets/1623101/10110202/c287c5de-6399-11e5-8368-cf7a0d509b3c.png">

**Comment by JukePlz** [comment]
I can confirm on Windows 7:

![](http://i.imgur.com/jNxL86S.png)

**Comment by MackSix** [comment]
I am running Windows 7 too.
