### ISSUE TITLE
Font face for bold getting ignored on Linux

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3873]
The bold font is not visible in the CM's `Name` column and statusPanel as can be seen in the screenshot.
![screenshot from 2015-09-26 01 11 59](https://cloud.githubusercontent.com/assets/7762605/10110638/21ef8398-63ec-11e5-8e07-362af432c952.png)

**Comment by benfry** [comment]
Looks like you're testing with another IDE instead of using `ant run`. It's working fine:

<img width="743" alt="screen shot 2015-09-25 at 7 03 38 pm" src="https://cloud.githubusercontent.com/assets/1623101/10113944/284f797a-63b8-11e5-809d-e5763ae84ad3.png">

**Comment by Akarshit** [comment]
@benfry I am building using `ant run`. Just tested again with `mater` same result.
