### ISSUE TITLE
No sketch path specified (processing-java)

### ISSUE THREAD

**Issue by ActionNerd** [processing/processing#3878]
Not much on the web yet for running processing-java from the command line, and this one took me a good hour or two to figure out even though it was right in front of me on the help page.  Global and local installs consistently gave me "No sketch path specified".  I read issues and forum posts about absolute paths; I changed permissions; it seemed like everything I had was right; and finally I noticed this on the help:
```
The --build, --run, --present, or --export will be the final parameter
passed to Processing.
```
I should have read more thoroughly early on.  In other words, the script will not run if one of these four arguments is not at the end.  I'm putting this issue up for reference for other folks who missed it in the help page.

Also, I was using [this site](http://www.dsfcode.com/using-processing-via-the-command-line/) for reference which listed this code (which is **now incorrect**):
```
% mkdir test_sketch
% mkdir test_sketch/output_dir
% echo "size(500,500);" > test_sketch/test_sketch.pde
% processing-java --run --sketch=`pwd`/test_sketch --output=`pwd`/test_sketch/output
```

Recommend changing "The --build, --run, --present, or --export **will** be the final parameter
passed to Processing" to "The --build, --run, --present, or --export **must** be the final parameter
passed to Processing."

Running OS X 10.10.5 Yosemite with Processing 3.0b7.  This issue ready for closure.

**Comment by benfry** [comment]
Changed "will" to "must" for the next release.
