### ISSUE TITLE
Contribution Manager - example pack listed twice

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3886]
When I go to Examples I see this:

![2](https://cloud.githubusercontent.com/assets/3177098/10124768/6b657d3a-652b-11e5-945d-459f005d054b.png)

When I reinstall the pack I get into the same situation again. Both versions have different description and names. Possibly connected to #3885 (contribution file not updating properly?)

**Comment by Akarshit** [comment]
similar to #3802 
@REAS `contribs.txt` and the properties file in the downloaded example show difference.

**Comment by REAS** [comment]
OK, will fix this. Thanks.

**Comment by REAS** [comment]
@Akarshit was correct, mismatched files.
