### ISSUE TITLE
OpenGL with fullScreen() always opens on default display

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3889]
All of these do the same thing: open fullscreen window on the first display.
```processing
fullScreen(P2D);
fullScreen(P2D, SPAN);
fullScreen(P2D, 1);
fullScreen(P2D, 2);
```

**Comment by codeanticode** [comment]
this windows right? I tested fullscreen with a multiple display config on OS X, only a couple of days ago, and worked as expected.
