### ISSUE TITLE
Contribution Manager says library is installed while it's not.

### ISSUE THREAD

**Issue by kasperkamperman** [processing/processing#3899]
The manager says that a library is installed while it's not (since I manually removed it to test). 

I also posted this issue in the Github of the library, however it might be an issue relating to the Contribution Manager. Feel free to close it if that's not the case. 

https://github.com/atduskgreg/opencv-processing/issues/87

<img width="815" alt="screen shot 2015-09-29 at 12 01 27" src="https://cloud.githubusercontent.com/assets/1760616/10161188/93f68f32-66a2-11e5-9265-d85176bbf9ac.png">

**Comment by JakubValtar** [comment]
Thank you for your report, but we already track this one in #3895

**Comment by kasperkamperman** [comment]
How is it decided if a library is compatible or not? I have the OpenCV library running myself in Processing 3.0 by the old fashioned manual install. The examples are not all compatible (due change in the size() method), however I can use the library and my code. 

I'd like to have this library updated so it appears as compatible in the CM (that's way easier for students). Is there a page with guidelines?
