### ISSUE TITLE
CM: displays wrong mode version before installation

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#3900]
The [latest android mode](https://github.com/processing/processing-android/releases) version is 3.0-beta2, however the CM shows the previous version as available before installing it:

![image](https://cloud.githubusercontent.com/assets/62246/10162285/a1657916-6680-11e5-828c-6db2234c1179.png)

After installation, it shows the correct version:

![image](https://cloud.githubusercontent.com/assets/62246/10162336/d3002bf6-6680-11e5-8283-db75cbfbff91.png)

**Comment by aengelke** [comment]
Looks like a contribs.txt issue...

**Comment by benfry** [comment]
@prisonerjohn Can you confirm? I think this is just that the new Mode is not magically/instantly added to the contribs list.

**Comment by codeanticode** [comment]
I know that there is typically a cache delay so contribution updates take some time to show up in the CM. But I uploaded the new version of the android mode three or four days ago, so that's why I was wondering if could be something else.

**Comment by benfry** [comment]
Looks like it isn't updated yet: http://download.processing.org/contribs

**Comment by prisonerjohn** [comment]
Right, updating the `contribs.txt` file is still a manual process. See https://github.com/processing/processing-docs/issues/16

I'm generating new files now, so it should be available shortly.
