### ISSUE TITLE
Sound library 1.3.1 not showing up properly in the CM

### ISSUE THREAD

**Issue by REAS** [processing/processing#3902]
The Sound library was updated yesterday. I looked at the data files and they look right to me, but I hope @prisonerjohn can look as well. https://github.com/processing/processing-sound/releases

I built the contribs.txt file and that looks fine too:
https://processing.org/contrib_generate/contribs.txt

First, the latest release 1.3.1 wasn't appearing in the CM to update. I tried removing the prior release 1.3 to see what would happen. Now, when I close and open Processing and let the file load from the server, the Sound library is grayed out, but it claims 1.3.1 is installed.

There's more on this at processing/processing-sound#50

I'm testing with 3.0b7 and building from the current repo.

**Comment by benfry** [comment]
Its min and max revision is set to 0228, which means it's only compatible with 3.0 alpha 1.

**Comment by REAS** [comment]
Yes, sorry for the chase; I'm wasted about 30 minutes on this and now your time too. I'll get it fixed.

**Comment by REAS** [comment]
The files for the Sound library are correct, however. Both are the same:
minRevision = 228
maxRevision = 0

So, I'll post this as a bug in processing/processing-docs
