### ISSUE TITLE
A typing mistake in processing reference for text()

### ISSUE THREAD

**Issue by abdulhannanali** [processing/processing#3908]
In the parameters of text() [here](https://processing.org/reference/text_.html)

The definition for the y1 is *float: by default, the x-coordinate of text, see rectMode() for more info*. It should be **the y-coordinate of text** instead.

**Comment by REAS** [comment]
Thank you. I'll take care of it. Please post Reference errors to processing/processing-docs in the future.

**Comment by abdulhannanali** [comment]
Thank you! Sorry I wasn't aware about it.... Will take care next time.
