### ISSUE TITLE
replace icons in the debugger window

### ISSUE THREAD

**Issue by benfry** [processing/processing#3909]

**Comment by jamesjgrady** [comment]
@benfry here are the new icons. Let me know if you need anything else.

![var-icons-1x](https://cloud.githubusercontent.com/assets/2600893/10198684/15deb52e-676b-11e5-9b8b-1bc9039a6850.png)
![var-icons-2x](https://cloud.githubusercontent.com/assets/2600893/10198685/15e1ec6c-676b-11e5-9bb0-672f34b21215.png)

**Comment by benfry** [comment]
Now implemented. 2x versions issue: https://github.com/processing/processing/issues/3921
