### ISSUE TITLE
click "show this welcome" text to check/uncheck the box

### ISSUE THREAD

**Issue by benfry** [processing/processing#3912]
Rather than needing to click the box itself, make it work when users click the text as well. Like #3911, this is a problem with its current implementation as a web page, and something we don't control, unless we rewrite the Welcome window.

**Comment by whetfire** [comment]
Hey, I want to fix this and #3911 by rewriting the welcome window in Swing.

This is my first time contributing, is there anything I need to look out for to maintain compatibility?

**Comment by benfry** [comment]
Fixed for the next release (3.3.8 or 3.4)
