### ISSUE TITLE
Editor menu is outside the visible screen when using the Raspberry Pi 800×480 7" TFT 

### ISSUE THREAD

**Issue by xranby** [processing/processing#3913]
On 8 sept 2015 Raspberry Pi foundation announced an 7" TFT add-on display with 10 point multi-touch for use with the Raspberry Pi
https://www.raspberrypi.org/blog/the-eagerly-awaited-raspberry-pi-display/

This screen has a quite small screen size 800×480 causing issues displaying the processing editor, the main menu gets hidden outside the screen as seen on the screenshot below:
![3b7 on raspbery pi with 7" touchscreen](http://labb.zafena.se/processing/3.0b7+rpi/image20150930_133211201.jpg)

workarounds:
The user has to know arcane workaround such as holding down ALT and moving the window or right clicking on the menu bar and forcing the editor window to maximize.

Tested using Processing 3.0 b7

**Comment by gohai** [comment]
Will look into shrinking the Text Editor on small resolutions. Post 3.0 material in any way.

**Comment by benfry** [comment]
To fix, set `editor.window.height.min` inside ~/.processing/preferences.txt to a value that works. Then we can add that to the `defaults.txt` file.

**Comment by benfry** [comment]
Fixed for the next release.
