### ISSUE TITLE
blank window on startup where the "welcome" screen should be

### ISSUE THREAD

**Issue by benfry** [processing/processing#3933]
Reported by @orglennon but haven't been able to confirm/reproduce yet. She thought the window also said "About" in the title bar, but definitely wasn't "Welcome to Processing 3".

**Comment by benfry** [comment]
@orglennon was this actually on Windows? Just ran into this today.

**Comment by orglennon** [comment]
@benfry nope the original was on my macbook pro

**Comment by benfry** [comment]
And was it doing the same thing as in the Windows image above?

**Comment by orglennon** [comment]
Yeah, and because I just opened the program, not a sketch directly, it essentially froze on the blank screen.

**Comment by benfry** [comment]
Has anyone seen this issue with the current release?

**Comment by benfry** [comment]
Can no longer reproduce, hopefully fixed with `EventQueue` fix in `Base` in 3.3.
