### ISSUE TITLE
image() in void setup() along with surface.setSize() 

### ISSUE THREAD

**Issue by Xeronimo74** [processing/processing#3935]
Here's my code: 

PImage img;

void setup() {
  size(200, 200);
  img = loadImage("http://i.imgur.com/HwblOYx.jpg");
  surface.setResizable(true);
  surface.setSize(img.width, img.height);
  image(img, 0, 0);
}

The display window will have the correct size, from the image, but the image itself won't be displayed. It will be displayed though if I move image(img,0,0) to draw() ...

**Comment by REAS** [comment]
Through testing, this is the line causing the sketch to not draw the image:
`surface.setSize(img.width, img.height);`

I'm not sure if it should work... @benfry will know.

**Comment by tsulej** [comment]
I vote for high priority for this issue.

**Comment by benfry** [comment]
Calls to `surface` can't run while drawing. So the resize happens after `setup()` finishes, which causes the screen to blank. That's one reason that the `setSize()` function lives in `surface`... if it were a drawing command, we wouldn't be using this other `surface` object.

To do that sketch, the proper approach would be:
```
PImage img;

void setup() {
  size(200, 200);
  img = loadImage("http://i.imgur.com/HwblOYx.jpg");
  surface.setResizable(true);
  surface.setSize(img.width, img.height);
}

void draw() {
  image(img, 0, 0);
  noLoop();
}
```
This is something that should be documented, but isn't a "bug" or something that can be "fixed".

**Comment by REAS** [comment]
I'll document with `surface`. Thanks for the clarification.

**Comment by Xeronimo74** [comment]
But so what if you want to have an image as the starting background on which you continuously draw afterwards? Isn't that possible anymore?

**Comment by REAS** [comment]
This is a question for the Forum now (http://forum.processing.org) but something like:

```
PImage img;

void setup() {
  size(200, 200);
  img = loadImage("http://i.imgur.com/HwblOYx.jpg");
  surface.setResizable(true);
  surface.setSize(img.width, img.height);
}

void draw() {
  if (frameCount == 1) {
    image(img, 0, 0);
  }
  ellipse(mouseX, mouseY, 30, 30);
}
```

**Comment by Xeronimo74** [comment]
Ok, that works. Thanks!

It's a bit unfortunate though that two lines:

img = loadImage();
image(img,0,0);

have been replaced by six lines:

  img = loadImage("http://i.imgur.com/HwblOYx.jpg");
  surface.setResizable(true);
  surface.setSize(img.width, img.height);

  if (frameCount == 1) {
    image(img, 0, 0);
  }

but I guess there are good reasons for this.

Just to be sure though: so even if you only want to transform a static photo using Processing you have to put all the code (or the function call) into draw() nevertheless?

**Comment by REAS** [comment]
Really, this is a question for the Forum... link above.

**Comment by Xeronimo74** [comment]
I've posted it there too now ... but still, this is a big and crucial change from Processing 2 and breaks a lot of sketches. I think it deserves a bit more attention ...

**Comment by HaydenHoran** [comment]
I am merely trying to set up a window. However, when running void setup () {....}, I get an unexpected token {. Any idea why?
