### ISSUE TITLE
"Client got end-of-stream" with network library example

### ISSUE THREAD

**Issue by REAS** [processing/processing#3937]
This Network Library example has the error `Client got end-of-stream` and I'm having trouble defining the issue. Is it the Network library or the configuration of the Processing server. I'm posting here for other eyes.

```
import processing.net.*;

Client c;
String data;

void setup() {
  size(200, 200);
  background(50);
  fill(200);
  c = new Client(this, "www.processing.org", 80); // Connect to server on port 80
  c.write("GET / HTTP/1.0\r\n"); // Use the HTTP "GET" command to ask for a Web page
  c.write("\r\n");
}

void draw() {
  if (c.available() > 0) { // If there's incoming data from the client...
    data = c.readString(); // ...then grab it and print it
    println(data);
  }
}
```

The full console output is:
```
Client got end-of-stream.
HTTP/1.1 301 Moved Permanently
Date: Wed, 30 Sep 2015 21:52:30 GMT
Server: Apache/2.4.7 (Ubuntu)
Set-Cookie: cookiecookiecookie=ca086811.520fdf27b6191; path=/; expires=Sun, 23-Sep-40 21:52:30 GMT; domain=.processing.org
Location: https:///
Content-Length: 296
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https:///">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at processing.org Port 80</address>
</body></html>
```

**Comment by shiffman** [comment]
I looked into this briefly and found an old forum post which adds additional metadata to the GET request.

http://forum.processing.org/one/topic/http-get-requests-strange-results.html

The posted fix, however, did not work for me.   At the end of the forum post @benfry points out that this can more easily be accomplished with `loadStrings()`.  In addition the [HTTPRequests-for-Processing](https://github.com/runemadsen/HTTP-Requests-for-Processing) library covers this scenario well.  I think perhaps this example can be removed and the network library examples should focus more on sockets?

**Comment by REAS** [comment]
I ran this by Ben before I posted it; he thought it should work or should be fixed. I'm fine with any strategy, but I'm not knowledgeable in this area.

**Comment by benfry** [comment]
Sorry, I didn't read that closely enough. This is the correct behavior: a set of data comes through (the 301 redirect) and then the server closes the stream. This is the response from the server:
```
HTTP/1.1 301 Moved Permanently
Date: Thu, 01 Oct 2015 14:24:14 GMT
Server: Apache/2.4.7 (Ubuntu)
Set-Cookie: cookiecookiecookie=cea93ffa.5210bcd33fde8; path=/; expires=Mon, 24-Sep-40 14:24:14 GMT; domain=.processing.org
Location: https:///
Content-Length: 296
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https:///">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at processing.org Port 80</address>
</body></html>
```
Ours and many other sites are redirecting to https:// URLs. I think the `loadStrings()` version will actually follow the redirect and get the text content. 

The confusion in the forum post is just people not understanding how sockets work or the HTTP protocol; not Processing bugs in either case.
