### ISSUE TITLE
'key' variable is always uppercase in FX2D renderer

### ISSUE THREAD

**Issue by tsulej** [processing/processing#3938]
When using FX2D renderer, 'key' variable in keyPressed() method returns uppercase character.

test code:
void setup() {
  size(500,500,FX2D);
}
void draw() {}
void keyPressed() {
  println(key);
}

**Comment by JakubValtar** [comment]
This is how FX key events work. Use `keyTyped()` if you need correct case.

**Comment by iamutkarshtiwari** [comment]
I have written a fix for this issue. Could anyone here please guide me how to create a patch and a pull request?

**Comment by iamutkarshtiwari** [comment]
### Patch(PR) to fix this bug
#### https://github.com/processing/processing/pull/4006

**Comment by Aeoll** [comment]
Just ran into this - it would be nice if the behaviour was documented since it causes inconsistencies across renderers. 

```
void keyPressed() {
    switch (key) {
      case 'a' :
        // do something
        break;
    }
}
```
The user should surely get some kind of warning when trying to do this in FX2D?
