### ISSUE TITLE
Event queue processing is very slow during heavy calculations in draw() [FX2D]

### ISSUE THREAD

**Issue by tsulej** [processing/processing#3939]
When using FX2D, event processing is dramatically slower than default mode.
Press keys when following code is run.

Test code:
void setup() {
  size(500,500,FX2D); // without FX2D is better
}
void draw() {
  for(int i=0;i<10000000;i++) {
    float a = sin(random(TWO_PI));
  }
  background(random(255));
}
void keyPressed() {
  println(key);
}

**Comment by benfry** [comment]
Yes, if you do ridiculous things and starve the CPU of cycles, that will cause problems in any language. FX2D is a little more sensitive to this, which is why it's not the default renderer.
