### ISSUE TITLE
Tooltip over variable decl has wrong style and content

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3940]
Tooltip should display the warning instead of a variable name.

The style is not consistent with error tooltips (text size is bigger and possibly it has wrong color):

![untitled](https://cloud.githubusercontent.com/assets/3177098/10212155/296f70ac-67c9-11e5-8605-2a4afb56b42b.png)

![untitled2](https://cloud.githubusercontent.com/assets/3177098/10212158/2d5305d0-67c9-11e5-8f02-6667528c8fb7.png)

**Comment by benfry** [comment]
Odd; that's just a default tooltip (not running our code at all), but I can't find where `setToolTipText()` is being called to make this happen.

**Comment by JakubValtar** [comment]
I think we are setting it to null if we don't want it to show, so maybe we need that if there is no error or warning.

**Comment by benfry** [comment]
But in that particular case, there's a warning, so I don't know why that isn't what's shown, and with it, the correct style.
