### ISSUE TITLE
"tweak" crash on my win 8.1 

### ISSUE THREAD

**Issue by daimonWolf** [processing/processing#3949]
When i use "tweak" option all Processing is blocked, I can not interact with JVM and I can not use the API, after some seconds the interface start be black or glitched.
I am using Win 8.1 and the last Java software

**Comment by Talinf** [comment]
Same here. Unable to close or interact with editor windows. Must use task manager to kill the JVM. Btw the version 3.0b5 was working fine with tweak.

**Comment by galsasson** [comment]
Same issue as #3928

**Comment by REAS** [comment]
Closing as duplicate.
