### ISSUE TITLE
Problems with sound library on linux64

### ISSUE THREAD

**Issue by sidec** [processing/processing#3950]
I'm not able to run sound library examples with Processing 3 release.
Error that I get when trying:

 ```bash
A library used by this sketch is not installed properly.
```
My system is Linux Mint 17 (Ubuntu 14.04 LTS)

**Comment by hamoid** [comment]
Additionally, the console shows:

    UnsatisfiedLinkError: processing.sound.MethClaInterface.busConstructMono()I
    A library relies on native code that's not available.
   Or only works properly when the sketch is run as a 32-bit application.

I think it's a duplicate of this error: https://github.com/processing/processing-sound/issues/45

**Comment by benfry** [comment]
Moved to the correct repo: https://github.com/processing/processing-sound
