### ISSUE TITLE
Project 14 of the Arduino Starterkit doesn't compile with processing 3.0

### ISSUE THREAD

**Issue by agdl** [processing/processing#3951]
As described in the object because is no more possible to use:

size(logo.width, logo.height);

because logo.width and logo.height are variables and not constants. Any work-around?

**Comment by REAS** [comment]
Please read this: https://github.com/processing/processing/wiki/Changes-in-3.0#things-that-may-break-your-2x-sketches

**Comment by REAS** [comment]
FYI, jump to 5:50 in this video to see the code in `setup()`:
https://www.youtube.com/watch?v=Z6Y6Gj0fgb8&list=PLT6rF_I5kknPf2qlVFlvH47qHvqvzkknd&index=9
