### ISSUE TITLE
Opening the Contributions Manager throws an error

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3953]
The following error is thrown when the Contributions Manager is opened:

```
The Editor class has moved to the processing.app.ui package in Processing 3
```

**Comment by joelmoniz** [comment]
Hmm... So I've looked into this, and it seems that this is caused due to incompatible tools being present in the `Tools` folder. Perhaps this error should be made more descriptive? Such as:

```
Error in Tool X. The Editor class has moved to the processing.app.ui package in Processing 3.
```

**Comment by benfry** [comment]
It does say that, as best it can. It's probably the error line before it. But we don't have a lot of control over how console messages show up.
