### ISSUE TITLE
Minim Don't Work When Application Exported 

### ISSUE THREAD

**Issue by RomainAuroro** [processing/processing#3957]
Ok i used processing-3.0b7 launch a sketch that uses minim, and serial port. It works fine from the IDE. But when i export it it crashed when in tries to create a new class for minim. So i used processing-2.2.1 but this crashes when it try to create the serial port. I know where the program is going wrong by placing different "saveStrings()" functions at different areas.  For example:

saveStrings("minimtest1.txt", porttest1);
  minim= new Minim(this);
  saveStrings("minimtest2.txt", porttest1);
  nowPlayingLocation= ProcessedMusicList[songnumber];
  saveStrings("songlocationtest.txt", porttest1);
  nowPlaying= SongNames[songnumber];
  songAt= songnumber+1;
  saveStrings("songtest1.txt", songtest1);
  song = minim.loadFile(nowPlayingLocation, 1024);
  saveStrings("songtest2.txt", songtest2);
  fft= new FFT(song.bufferSize(), song.sampleRate());

  if (PortSelected==false)
  {
    saveStrings("porttest1.txt", porttest1);
    String p= str(COMport);
    String[] port= {p};
    saveStrings("comport.txt", port);
    ArduinoPort= new Serial(this, Serial.list()[COMport], 9600);
    saveStrings("porttest2.txt", porttest2);
    PortSelected=true;
  }

in processing-3.0b7 the minimtest2.txt file is not created. While in  processing-2.2.1 the porttest2.txt file is not created. The COMport is taken from a txt file and as u can see above i checked to make sure it has the right integer value. Tried changing the value and dont work either. And I have the latest sound and minim libraries for processing-3.0b7. Please help me with the issue. when this program is fully finished im gona need a stand alone application.

**Comment by benfry** [comment]
Please use forum.processing.org for coding questions.
