### ISSUE TITLE
shaders preprocessor messup with GLSL texture functions (texture -> texMap String replace)

### ISSUE THREAD

**Issue by stmaccarelli** [processing/processing#3961]
Eg. textureOffset() becomes texMapOffset()
I'm using a workaround (by letting preprocessor replace texMapCube to texture, so texMapCubeOffset() becomes textureOffset()

I think you could simply add the texture functions to Search and Replace Strings in the shaders pre-processor setup

**Comment by JakubValtar** [comment]
You should have #version directive in your shaders. The preprocessor is there to preserve compatibility with older GLSL 110 shaders which were used in Processing 2. If you have #version directive, we leave your code alone, otherwise we assume it is old 110 code and we preprocess it so it can run at all.

**Comment by codeanticode** [comment]
But the function [textureOffset](https://www.opengl.org/sdk/docs/man/html/textureOffset.xhtml) is 1.30+, so it will still create conflicts if used.

**Comment by JakubValtar** [comment]
@codeanticode I will add it to the replacement map. However, if there is no #version, we assume the code is 110 (or 120 at most) and there should be no textureOffset in the first place. We should probably clarify if users should use #version or not and what GLSL version we support. Then modify the preprocessor according to that.

**Comment by JakubValtar** [comment]
@codeanticode There seems to be a lot of different textureXXX functions in 440 so I will add a regular expression to the preprocessor to deal with all of them at once.

**Comment by codeanticode** [comment]
Wait... I don't think we need to add any of this to the replacement map, as you pointed out none of these functions are part GLSL <130

**Comment by JakubValtar** [comment]
However different OpenGL version we can be running on support different minimum version of GLSL, so we should also be able to convert e.g. from 130 to 440, so users don't have to deal with this.

**Comment by codeanticode** [comment]
you man that the pre-processor shuld be able to convert between any to GLSL version? But the only purpose of the pre-preprocessing step is to make 120 shaders compatible with newer GLSL versions, right? The simplest solution is to add the #version directive in the shader code, isn't it?

**Comment by JakubValtar** [comment]
Some systems have minimum version higher than 130 so if you hardcode #version 130 it won't run on some systems. That's why it may be a good idea to just take what people wrote and upgrade it to minimum required version.

**Comment by codeanticode** [comment]
Ok. I will mark it as enhancement. Let's discuss it further once you create a PR for it.

@stmaccarelli are you able to use your shaders if you add the #version directive, so no need of hacking the function names?

**Comment by stmaccarelli** [comment]
With #version 400 it works ok.
I didn't test with #version 130, I'll do it asap.


-- 
--


*Stefano Maccarelli*Art director, designer, creative coder.

Via San Donato, 20 – Torino, Italy
www.stefano-maccarelli.com

*www.linkedin.com/in/stmaccarelli <http://www.linkedin.com/in/stmaccarelli>*
(+39) 340 6247854
st.maccarelli@gmail.com

**Comment by stmaccarelli** [comment]
I just hadn't clear the preprocessor logic.
I used to just write 120 syntax, thinking Processing preprocessor would
have convert any syntax to the newer available one.
On my system #version 130 is not supported. The first supported one is 140,
so having the ability to write 120 syntax made me think so.

Declaring a #version makes code work properly. And to me, that's the way.
To me, talking about GLSL shaders, the less "under the hood" logic, the
better.

**Comment by codeanticode** [comment]
@JakubValtar I tend to agree with @stmaccarelli, what you are suggesting, if I understand correctly, is that users should be able to write code for #version 130, and if the driver only supports a newer version of GLSL, then the preprocessor should update the code accordingly, am I right?

**Comment by stmaccarelli** [comment]
Well, not exactly.
Maybe it's ok as is right now. , but can't you say in references /
javadoc that in P3 shaders declaring a #version is mandatory? A straight
approach that would make less confusion.
You could then print a warning when preprocessor runs, telling users that
a preprocessor converted #version OLD syntax to #version NEW, and suggests
to update syntax.
This way compatibility is preserved, and users know what's happening under
the hood.


-- 
--


*Stefano Maccarelli*Art director, designer, creative coder.

Via San Donato, 20 – Torino, Italy
www.stefano-maccarelli.com

*www.linkedin.com/in/stmaccarelli <http://www.linkedin.com/in/stmaccarelli>*
(+39) 340 6247854
st.maccarelli@gmail.com
