### ISSUE TITLE
Tab navigation problems - where is include?

### ISSUE THREAD

**Issue by HenriAugusto** [processing/processing#3962]
Hi.

I'm working on a big project and i have just noticed i'm heading for a problem with Processing's IDE that is a really workflow killer.

This is a picture showing how much classes i have. Every tab here have at least 200 lines, so i can't even think on putting some of them together. That would be reeeally messy.
![captura de tela 2015-10-06 01 03 55](https://cloud.githubusercontent.com/assets/11790621/10299898/531b13e2-6bc6-11e5-9d9b-64110bf585aa.png)

As you can see it is almost reaching the end of the screen. I'm running a 1080p monitor, so on my notebook it will not display some classes! 

I've just procedurally generated 50 tabs in another sketch just so you can see what happens:

![captura de tela 2015-10-06 00 58 17](https://cloud.githubusercontent.com/assets/11790621/10299864/c98032ca-6bc5-11e5-8845-b37e07857c6a.png)

AS you can observe some tabs just won't show. If you try to mouseWheelScroll that window it simply closes. If you use the arrow keys you can select them, but you won't see what you're selecting.

Also, Thomas Diewald's Tab Management tool is not compatible anymore. But it exists. It shows us already that the necessity of better Tab handling existed before and as you can see it still does.

Now either processing 3 could have good tab management by default or, as an alternative solution we could have [`#include`](https://msdn.microsoft.com/en-us/library/36k2cdd4.aspx). Then you leave only the stuff you're working on in the processor tabs. The stuff that's already working you would get with #include.

I really don't want to change to eclipse (specially because i've never used and i have one week to finish this work. And i still have some of more 40 totally different Classes to make). Also that would defeat the purpose of having a cozy awesome IDE with debugging, tweaking that you can simply extract and start coding.

Or maybe Processing could load .pde files inside the `data` folder, or a `include` folder, but those loaded that way wouldn't appear in a tab. I think it's pretty reasonable that a big project might use more than 50 different classes, but the chances that someone might actually want to edit more than 50 tabs is absolutely low. In any case you need to modify 50+ text files you're better of with some regex stuff.

Plus, as explained in [this tutorial](https://processing.org/tutorials/eclipse/) about using Processing with eclipse, it adds extra work and headache when working with multiple classes due to nested classes. And proclipsing haven't been updated in a while and won't solve the classes complications.

Right know i'm having nightmares with the day where i will have like 10 tabs that i can't click. So that's it. Thanks for your patience in reading everything. Hope somebody have some clue on how to solve this.

**Comment by benfry** [comment]
Use Eclipse or another IDE. If you have that many classes, Processing is not the right tool.
