### ISSUE TITLE
Empty while  never quit

### ISSUE THREAD

**Issue by frank4466** [processing/processing#3967]
In this exemple : 
while (!FichierACacherOK ) {
    print(".");// Sans ce print la fonction while ne marche pas ?
  }

If I delete the print line, the program never comes out of the while loop.

**Comment by clankill3r** [comment]
You can bring this to the processing forum.
http://forum.processing.org/two

Also, with the print it should never come out of the while loop.

**Comment by benfry** [comment]
That's a bug in your code, not Processing.
