### ISSUE TITLE
new PShader(PApplet, String[] String[]) does not work on Mac

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3969]
It seems `new PShader(PApplet, String[] String[])` only works on a PC.
On a Mac it reports the following error:

**Cannot compile vertex shader:ERROR:0:3 'attribute' : syntax error: syntax error**

````java
void setup() {
 
    size(600, 300, P2D);
 
    PImage someImage = loadImage("http" + "://forum.processing.org/two/uploads/userpics/970/n4IUAUUTANWJL.png");
 
    updateShader();
    image(someImage, 0, 0, 300, 300);
 
}
 
void updateShader() {
 
    String[] vertSource = {
        "#version 410",
 
        "uniform mat4 transform;",
 
        "attribute vec4 vertex;",
        "attribute vec4 color;",
        "attribute vec2 texCoord;",
 
        "varying vec4 vertColor;",
        "varying vec2 vertTexCoord;",
 
        "void main() {",
            "gl_Position = transform * vertex;",
 
            "vertColor = color;",
            "vertTexCoord = texCoord;",
        "}"
    };
    String[] fragSource = {
        "#version 410",
 
        "#define PROCESSING_TEXTURE_SHADER",
 
        "uniform sampler2D texture;",
        "varying vec4 vertTexCoord;",
 
        "void main() {",
            "vec4 result = texture2D(texture, vertTexCoord.st).rgba;",
            "gl_FragColor = result;",
        "}"
    };
 
    PShader myShader = new PShader(this, vertSource, fragSource);
    
    shader(myShader);
 
}
````

**Comment by codeanticode** [comment]
Your shader code is not written using version 4.10, for example it should use ```out``` instead of ```varying```, ```in``` instead of ```attribute``` and so on. The reason it works on PC is because the compiler is more permissive than on OS X.

**Comment by clankill3r** [comment]
Thanks for pointing that out. I'm a bit new to all this.
I (and Poersch ) updated the code. Now I get **Cannot link shader program:Unknow error**
Notice it says **Unknow** instead of **Unknown** so you still have something small to fix :smile: 

What can a possible reason be for a Unknown Error?

````java
 void setup() {
    size(600, 300, P2D);
    PImage someImage = loadImage("http" + "://forum.processing.org/two/uploads/userpics/970/n4IUAUUTANWJL.png");
    updateShader();
    image(someImage, 0, 0, 300, 300);
}
 
void updateShader() {
    String[] vertSource = {
        "#version 410", // First class arrays require GLSL version 1.20 (or higher)
 
        "uniform mat4 transform;",
 
        "in vec4 vertex;",
        "in vec4 color;",
        "in vec2 texCoord;",
 
        "out vec4 vertColor;",
        "out vec2 vertTexCoord;",
 
        "void main() {",
            "gl_Position = transform * vertex;",
 
            "vertColor = color;",
            "vertTexCoord = texCoord;",
        "}"
    };
    String[] fragSource = {
        "#version 410", // First class arrays require GLSL version 1.20 (or higher)
        "#define PROCESSING_TEXTURE_SHADER",
 
        "uniform sampler2D texture;",
 
        "in vec4 vertTexCoord;",
 
        "out vec4 fragColor;",
 
        "void main() {",
            "vec4 result = texture(texture, vertTexCoord.st).rgba;",
            "fragColor = result;",
        "}"
    };
        
    PShader myShader = new PShader(this, vertSource, fragSource);
    shader(myShader);
}
````

**Comment by clankill3r** [comment]
Our should I post a new Issue for this?

**Comment by codeanticode** [comment]
There is a bug in your shader: the type of the varying variable vertTexCoord is not consistent between the vertex and the fragment shaders: it is declared as vec2 in the vertex, and vec4 in the fragment. 

Another thing is that you don't longer need #define PROCESSING_TEXTURE_SHADER" in Processing 3. These pre-processor directives were required up to 2.1

**Comment by clankill3r** [comment]
Ah thanks, I learned so much today :)

Really great the #define PROCESSING_TEXTURE_SHADER is not needed anymore. :+1: 
That always felt kinda dirty.

Thanks for pointing out the vec2 vec4 thing, someone on the forum is helping me and his drivers are way more forgiving then they are on my mac. I will look closer next time before I post an issue :)
