### ISSUE TITLE
clientEvent / serverEvent

### ISSUE THREAD

**Issue by ertdfgcvb** [processing/processing#3970]
It would be useful to be able to process the incoming messages outside the draw loop in both "client" and "server" applications. 
This already works "client side" with the clientEvent() method: the client can parse messages coming from the server in this event-like method.
The server on the other hand doesn't have a similar method: the only way to process incoming messages  from the connected clients is trough the draw loop and Client.available()…  
It would maybe make more sense to have a new serverEvent(Server s, Client c) method which gets fired when a client writes to the server. For clarity the actual serverEvent(Server s, Client c) method could eventually be renamed to connectEvent() as this is the only moment where the method gets called (cfr. disconnectEvent()).

Or 

Both server and client could have a mirror function like messageEvent(Server, Client) fired when a client or a server send a message with write().

**Comment by benfry** [comment]
Fixed for 3.3.7 or 3.4 (whichever comes first).
