### ISSUE TITLE
fragment shader coordinates scaled incorrectly using pixelDensity(2)

### ISSUE THREAD

**Issue by setphen** [processing/processing#3972]
when pixelDensity(2) is set, glsl X,Y coordinates are no longer normalized 0.0 – 1.0, but 0.0 – 2.0.

using the shader
```
uniform vec2 res;

void main(void)
{
    float f = distance(gl_FragCoord.xy/res.xy,vec2(0.5));
	gl_FragColor = vec4 (vec3 (f),1.0);
}
```

pixelDensity(1):
<img width="949" alt="screen shot 2015-10-07 at 2 52 19 pm" src="https://cloud.githubusercontent.com/assets/3891632/10347706/3de296ce-6d03-11e5-9def-68cbbcf9811a.png">
pixelDensity(2):
<img width="959" alt="screen shot 2015-10-07 at 2 52 38 pm" src="https://cloud.githubusercontent.com/assets/3891632/10347715/465ddfe8-6d03-11e5-9a4d-03a5d657fece.png">

**Comment by codeanticode** [comment]
I'm not on a retina machine at the moment, but what I understand is that gl_FragCoord goes between 0 and 2*w/h, while res is w/h, correct? I don't think it is a bug in Processing, but a result of how the retina resolution is handled by OpenGL (gl_FragCoord is set by OpenGL, not Processing). You would need to normalize gl_FragCoord using 2*res. In fact, there is a set of variables in Processing called pixelWidth/pixelHeight that contain the resolution in pixel space, meaning they are identical to width/height for non-retina resolution, and 2*width/height for retina. I haven't seen the code in your sketch, but I'd imagine you need to set your res uniform using pixelWidth/pixelHeight. Does it makes sense?

**Comment by setphen** [comment]
Ah, yes. I see now. Thanks for the explanation
