### ISSUE TITLE
Editing caret not working properly when files have tabs

### ISSUE THREAD

**Issue by HenriAugusto** [processing/processing#3975]
For some reason my cursor caret is behavnig like that:

![caret bug](https://cloud.githubusercontent.com/assets/11790621/10386295/c4f9dba8-6e2b-11e5-91d8-a0c00bb7124c.gif)

This started to happen when i've started saving my files with sublime text 2. The same file opens normally on windows notepad and notepad++

**edit**: seens a problem with the tab character. It doesn't seem to happen on lines without it.
Also when i first type on Processing and then load the files on ST or NP++, those text editors shows that the Tab entered in processing is actually four spaces, not a Tab character.

**Comment by jegb** [comment]
I can confirm the same issue, after starting using ST for pde files.

**Comment by sldx** [comment]
Can confirm, also edited with Sublime (v3). 

Pretty sucky.

**Comment by mikechambers** [comment]
Seeing the same thing (on mac and windows).  Including a video that shows it, and code that demonstrates the issue.

![editor_bug](https://cloud.githubusercontent.com/assets/37918/11830719/7766ab6c-a35c-11e5-869f-1183c34877b0.gif)

[BezierPlay2.zip](https://github.com/processing/processing/files/63491/BezierPlay2.zip)

Go to line 59, put cursor at the end of the line, and try to delete characters.

Processing 3.0.1.

(and yes, the code structure / files are weird, I had to throw some stuff together to log the issue).

**Comment by sldx** [comment]
U da man Jakeub
