### ISSUE TITLE
change file extension check when switching modes

### ISSUE THREAD

**Issue by fjenett** [processing/processing#3980]
In Processing 3.0 … when switching between modes there is a check against the file extensions in place that the currently active mode allows as SketchCode.class file extensions:
https://github.com/processing/processing/blob/master/app/src/processing/app/Base.java#L899

I assume the intention was to check wether the main code file (extension) could be handled by the next mode … but instead all code file (tab) extensions are being checked. This leads to not being able to switch between JS and Java modes if extra .js or .java files are present although these could exist in the sketch folder with no problems.

https://github.com/fjenett/javascript-mode-processing/issues/34

I propose to change the check to only test against the main program (code[0]) file extension.

**Comment by fjenett** [comment]
The line mentioned moved to here:
https://github.com/processing/processing/blob/2c0fe8397ba03a3204c4f281f48737282dc620b0/app/src/processing/app/Base.java#L925

**Comment by benfry** [comment]
No longer relevant due to change in https://github.com/processing/processing4/issues/189
