### ISSUE TITLE
Error console will stop refreshing itself until sketch is closed and reopened

### ISSUE THREAD

**Issue by serebit** [processing/processing#3983]
This persists even as the user edits the sketch.

**Comment by JakubValtar** [comment]
Sorry, this is like writing "my computer is broken" to a tech support.

Could you please provide some details? What do you mean by "error console"? There is "Console" pane and there is "Errors" pane.

I need to know: which of the two you are talking about, what it is doing, what it should be doing, and possibly when it happens and how can I reproduce it.

Thanks.

**Comment by gingerdeadshot** [comment]
The errors pane. It should be refreshing itself as I type, to both remove errors that no longer apply and to display errors that currently apply. Occasionally, the errors pane will stop automatically refreshing. The only way to get it to refresh is to either close and reopen the sketch, or to switch to a different tab within the sketch. Upon returning to the original tab, the error checking refreshes normally.

**Comment by JakubValtar** [comment]
Are you using Processing 3.0 final? There has been a lot of work done on it between beta and final.

**Comment by gingerdeadshot** [comment]
Yes. I make sure to keep up with the updates. In fact, the final 3.0 has a
lot more bugs in my case than 3.0 beta 6 did.

**Comment by serebit** [comment]
No idea if this is still a problem, but given it's been almost 5 years, probably not. Closing.
