### ISSUE TITLE
"Show usage..." does not locate keywords on correct line

### ISSUE THREAD

**Issue by gingerdeadshot** [processing/processing#3988]
The orange highlight box also highlights the wrong section of code.

System: iMac Desktop (late 2011), OS X El Capitan
Build: 3.0 alpha

**Comment by iamutkarshtiwari** [comment]
Looking into this.

**Comment by gingerdeadshot** [comment]
Also, sometimes error checking does not show the correct line, Rename
replaces the wrong keywords, and undoing Rename messes up the code further
by replacing only parts of the messed-up code.

**Comment by iamutkarshtiwari** [comment]
@Manindra29 There seems to be problem with ASTNodeWrapper. When we click on the 1st item in the "Usage of" window of "Show usage" option, it hightlights the correct location of the variable. But when we click the ****2nd**** item, there is a difference of ***7 indices*** between the ***exact starting index*** and the ***current starting index*** to be highlighted. Similarly all the items beyond and including 3rd item show a differnces of ***14 indices***.
