### ISSUE TITLE
PShapeOBJ error String for missing MTL texture file

### ISSUE THREAD

**Issue by stmaccarelli** [processing/processing#3990]
When importing a OBJ file in PShape, if MTL file has a wrong filename/path in the texture definition, we simply get a generic:
"The File /Users/........./filename.ext is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable."
(That's the default Processing missing file string.)
And Processing IDE is unable to tell me in what line error occurred.

It would be much more useful if those error strings could tell you that the error is in the MTL file definition, or at least in PShape object, if not able to hightlight the line of code in which the error occurred.

**Comment by gingerdeadshot** [comment]
This happens to me as well.
