### ISSUE TITLE
Ability to set IDE to fullscreen

### ISSUE THREAD

**Issue by gingerdeadshot** [processing/processing#3993]
With the new Split View function on OS X, I'd like to be able to put the Processing IDE in fullscreen so I can code and look at the reference at the same time, without having to resize the windows to the perfect positions and sizes. Is this something that could be implemented easily?

**Comment by clankill3r** [comment]
+1

**Comment by hamoid** [comment]
How much of that functionality belongs to Processing, and how much to the OS? In my desktop environment that's the default functionality and it works all programs. Is it maybe something OS X specific that should be implemented in Processing?

**Comment by gingerdeadshot** [comment]
Normally, there are 3 "stoplight" buttons on the top left corner of an OS X
window—a red X to close the window, a yellow "–" to minimize, and a
diagonally cleaved square to enter fullscreen. If you hold down the Option
key, the green square will change to a green +, indicating that instead of
entering fullscreen, the application window will simply fill the desktop.

With Processing windows, you don't have the option to enter fullscreen at
all. Therefore, it is something OS X specific, and is a basic functionality
of the operating system.
