### ISSUE TITLE
Rotating in P3D

### ISSUE THREAD

**Issue by MattPelland** [processing/processing#3994]
when I rotateY in P3D, the rotateX function remains defined relative to the reference frame of the space, while rotateZ is defined based on the object in space that I am rotating.  If I rotateY Pi/4 radians,  rotateX and rotateZ then do the same thing, and rotate my object around the same axis.

**Comment by benfry** [comment]
This isn't a bug. Transformations in 3D are very tricky, and forum.processing.org is a better place to get help.
