### ISSUE TITLE
Can not run Android app with processing v3.0

### ISSUE THREAD

**Issue by martiSteiger** [processing/processing#3995]
Get this error message with Windows-7 when target mode is Android:
debug: 
Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED]

Here's the 'Android.xml' file content...

![androidxmlv3 0](https://cloud.githubusercontent.com/assets/9280351/10480920/79bd49fe-726d-11e5-8e1c-ef7ed85057f6.png)
Because of old Manifest.xml files may cause problems, this manifest file was created new!

What I am also still missing are the permission statements like...

  < uses-permission android:name="android.permission.SET_ORIENTATION"/>
  < uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

when permissions SET_ORIENTATION and WRITE_EXTERNAL_STORAGE are still set!

Any idea how to bring it to run?

**Comment by codeanticode** [comment]
Hi, please use the processing-android repo to report issues specific to the android mode. Now in https://github.com/processing/processing-android/issues/157
