### ISSUE TITLE
OSX: processing-java stealing focus even with --build flag

### ISSUE THREAD

**Issue by myrjola** [processing/processing#3996]
I want to use processing-java with the --build flag for on-the-fly syntax checking https://github.com/ptrv/processing2-emacs/pull/8.

The problem I'm facing on OSX is that every time processing-java is run it steals focus from the editor, even though no window is created. This makes editing the code as syntax checking is running a frustrating experience. I can reproduce this by running processing-java from the terminal as well.

I found out a fix, which is to add `-Djava.awt.headless=true` to the java run options in /usr/local/bin/processing-java. I didn't notice any issues when running my sketches, but does anyone more knowledgeable in Java settings know what that headless-option could break?

**Comment by myrjola** [comment]
I guess one solution to this problem would be to add a conditional to processing-java, that adds `-Djava.awt.headless=true` to the java command line parameters if `--build` has been used. This will marginally increase the complexity of processing-java, but would otherwise be a simple enough solution.

**Comment by benfry** [comment]
Appreciate you looking into it and finding a fix.

**Comment by neilpanchal** [comment]
```/usr/local/bin/processing-java: line 8: [: too many arguments
/usr/local/bin/processing-java: line 8: [: too many arguments
Listening for transport dt_socket at address: 8439```

I get this error since this change in sublime text build console. Is this related?

**Comment by myrjola** [comment]
@neilpanchal, interesting find. I think I found the explanation and solution for the problem http://stackoverflow.com/questions/13781216/bash-meaning-of-too-many-arguments-error-from-if-square-brackets.

Could you try by applying this diff to `/usr/local/bin/processing-java`

```
@@ -5,7 +5,7 @@
 OPTION_FOR_HEADLESS_RUN=""
 for ARG in "$@"
 do
-    if [ $ARG = "--build" ]; then
+    if [ "$ARG" = "--build" ]; then
         OPTION_FOR_HEADLESS_RUN="-Djava.awt.headless=true"
     fi
 done
```

So just put double quotes around `$ARG`.

**Comment by neilpanchal** [comment]
@myrjola Works perfectly, I just tested it. Thanks! Closing #4119
