### ISSUE TITLE
Keyboard input laggs insane?

### ISSUE THREAD

**Issue by ocdy1001** [processing/processing#4000]
hello.

i wanted to make a game, so got the code from the official tutorial:

if ((keyPressed == true) && (key == 'a')){
    x -= 5;
  }
  if ((keyPressed == true) && (key == 'd')) {
    x += 5;
  }

this laggs a lot, tested on windows 10 and on 2 different pc's.

if you press the key, the object moves as expected, but if you switch key, it takes a second before moves the other way. It is a bit like when you type in the chrome adress bar: hold q,then release and press w. it takes a second before it start typing a lot of w's. also, if you press a key, and it does what it should do(moving)  and you tab another key (example: spacebar), the object stops moving and you need to press the key used to trigger the movement again. with this, it is really hard to make a game...

hope this helps

**Comment by JakubValtar** [comment]
This is caused by key repeat, it behaves exactly the same as what you see in chrome address bar. Try to use P2D or P3D renderers, the key handling is different and it would work better for you.

**Comment by ocdy1001** [comment]
even if i use P3D it still doesnt work at all for a game. if you hold a, event 1 happens, then tab d and it triggers event 2, but event 1 stops. I did  find a solution:

public void keyPressed(){
  if (key == 'w')
    w = true;
  if (key == 's')
    s = true;
  if (key == 'a')
    a = true;
  if (key == 'd')
    d = true;
}

public void keyReleased(){
  if (key == 'w')
    w = false;
  if (key == 's')
    s = false;
  if (key == 'a')
    a = false;
  if (key == 'd')
    d = false;
}

then check every frame:

if(w){
  //what you want  to do
}

ofcourse a boolean array is better:

boolean[] keys = new boolean[256];

public void keyPressed(){
  if (key == 'w')
    keys['w'] = true;
  if (key == 's')
    keys['s'] = true;
  if (key == 'a')
    keys['a'] = true;
  if (key == 'd')
    keys['d'] = true;
}

public void keyReleased(){
  if (key == 'w')
    keys['w'] = false;
  if (key == 's')
    keys['s'] = false;
  if (key == 'a')
    keys['a'] = false;
  if (key == 'd')
    keys['d'] = false;
}

if (keys['a']){
   // do stuff
}

now i get total fluid keyboard response.

the problem is that in the official processing tutorial only this is covered:

if(KeyPressed && Key == 'w')

i think the information about input and the different renders and the functions KeyPressed() and KeyReleaded() should be added to this tutorial, otherwise people may think the input is just broken.(like me)

thanks,

cody

**Comment by JakubValtar** [comment]
Maybe you missed the "Key Events" chapter of [the tutorial](https://processing.org/tutorials/interactivity/)? The technique with boolean is covered there and it works out of the box.

**Comment by ocdy1001** [comment]
i did missed it, sorry. now i reinvented the wheel.

sorry to waste your time.

**Comment by JakubValtar** [comment]
@ocdy1001 No worries, but next time try to ask on the [Processing forum](http://forum.processing.org/two/) first. There are nice folks who can give you great advice, and if there *really* is a bug, they will send you here.
