### ISSUE TITLE
Stroke glitches

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#4007]
I noticed on multiple occasions that stroke creates strange glitches when drawing larger number of primitives:

### Java2D

![grid](https://cloud.githubusercontent.com/assets/3177098/10539230/6b9a7c9c-73fe-11e5-8409-51c008f8c07c.png)

```processing
size(600, 600);

translate(341, 297);
scale(0.952381);
rotate(0.40000004);

background(0);
stroke(128);
for (int x = -50; x < 50; x++) {
  line(20 * x, -1000, 20 * x, 1000);  
}
for (int y = -50; y < 50; y++) {
  line(-1000, 20 * y, 1000, 20 * y);  
}
// Edit: I removed functions drawing the ellipse and center lines, they are not important
```

### P3D

![gl1](https://cloud.githubusercontent.com/assets/3177098/10538984/b09169b6-73fc-11e5-9e75-1f31e4e1e71f.png)

```processing
// modified example from Generative Design P_2_1_2_03
void setup(){
  size(600, 600, P3D);
}

void draw() {
  background(255);
  noFill();
  stroke(0, 180);
  strokeWeight(10);
  for (int gridY=0; gridY<width; gridY+=50) {
    for (int gridX=0; gridX<height; gridX+=50) {
      float diameter = dist(mouseX, mouseY, gridX, gridY);
      diameter = diameter/500 * 80;
      pushMatrix();
      translate(gridX, gridY, diameter*5);
      ellipse(0, 0, diameter, diameter);
      popMatrix(); 
    }
  }
}

```

Probably caused by the same bug:

![gl2](https://cloud.githubusercontent.com/assets/3177098/10539068/3b4d0ed4-73fd-11e5-959e-e33c3ebf4301.png)

```processing

void setup(){
  size(600, 600, P3D);
}

void draw() {
  background(255);
  noFill();
  stroke(0, 180);
  strokeWeight(100);
  ellipse(width/2, height/2, width*2/3, height*2/3);
}

```

**Comment by codeanticode** [comment]
I think these are two separate issues, the origin of the stroke glitches is probably different for JAVA2D and P3D.

**Comment by JakubValtar** [comment]
Yes, I thought so too, but didn't have time to investigate further. Do you have some idea about P3D? You were fixing strokes recently.

**Comment by codeanticode** [comment]
No, I need to look into it. I did some fixes that took care of glitches that appeared when you had very large stroke geometry, which does not seem to be the case. I wonder if I introduced a regression with those fixes.

**Comment by codeanticode** [comment]
The JAVA2D portion of this issue is now reported in #4030, and the P3D glitches in #4027 and #4029

**Comment by JakubValtar** [comment]
@codeanticode Thanks for cleaning this up. I guess that both P3D issues will be related, but let's see what we find.

**Comment by codeanticode** [comment]
The P3D issues with strokes should be fixed with https://github.com/processing/processing/commit/ed76e73cb310c1b9287cb42bd167449890f4daee and https://github.com/processing/processing/commit/1145839fe9d4a489fc0a6552d407fde6e0230ab0. If you have a chance, take a look to see if there is anything else behaving weirdly.

**Comment by JakubValtar** [comment]
@codeanticode Oh wow, you are amazing. Will check it asap.

**Comment by JakubValtar** [comment]
@codeanticode Works like a charm!
