### ISSUE TITLE
size() cannot be used here, see ...

### ISSUE THREAD

**Issue by alperaydemir** [processing/processing#4008]
Hi,

A super new (10 mins) processing user here.

I'm having a `size() cannot be used here, see <URL to size docpage>`

for the following snippet: 
https://gist.github.com/anonymous/402ab895a5410e4cd250

Though the docs seems to indicate this should work.

I'm on Mac OS El Capitan with a build of processing from source (latest master).

**Comment by benfry** [comment]
You have a typo in your code. `setup()` is called `setup_()`.

**Comment by JakubValtar** [comment]
@alperaydemir Hm, this is what [docs](https://processing.org/reference/size_.html) say: `In a program that has the setup() function, the size() function must be the first line of code inside setup().`

Put `size()` directly into `setup()` and it will work.
