### ISSUE TITLE
new translation file

### ISSUE THREAD

**Issue by tmelorc** [processing/processing#4018]
Hello people, this is my first message here after few minutes using Processing 3.0.

I'd like to share a new translation file. Since there are some differences between _Portuguese_ and _Brazilian Portuguese_, I created the file `PDE_pt-br` based on `PDE_pt`.

I saved it in `../processing-3.0/lib/languages` and also added `pt -br # Brazilian Portuguese` in `languages.txt` but `pt-br` does not appear on the _Preferences Window_.

How to use it? Is necessary to recompile something? How to send this new file to be uploaded for new versions?

Regards.
Thiago

**Comment by crazymaster** [comment]
You need to add the language code and recompile Processing.
https://github.com/processing/processing/blob/master/build/shared/lib/languages/languages.txt
https://github.com/processing/processing/blob/master/app/src/processing/app/Language.java#L91

**Comment by tmelorc** [comment]
Thanks. I'll try as soon as possible.

2015-10-26 11:34 GMT-02:00 Kenichi Ito <notifications@github.com>:

> You need to add the language code and recompile Processing.
>
> https://github.com/processing/processing/blob/master/build/shared/lib/languages/languages.txt
>
> https://github.com/processing/processing/blob/master/app/src/processing/app/Language.java#L91
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/processing/issues/4018#issuecomment-151134608>
> .
>



-- 
Thiago de Melo

**Comment by benfry** [comment]
Localizations are now covered on [this wiki page](https://github.com/processing/processing/wiki/Localization).
