### ISSUE TITLE
error in video library 1.0.1--com.sun.jna.native

### ISSUE THREAD

**Issue by tybowman** [processing/processing#4022]
the update to Video 1.0.1 The Processing Foundation GStreamer-based video library for Processing 3 for windows throws the same error when i try to run *any* of the examples, "noclassdeffounderror:could not initialize class com.sun.jna.native". i updated my java, uninstalled and reinstalled the library and restarted the os, win 7, 3 times and still the error. i will now revert to version 1.0.0 until this is fixed.

**Comment by codeanticode** [comment]
Already reported in https://github.com/processing/processing-video/issues/35.
