### ISSUE TITLE
opengl depth occlusion test when use glBeginQuery、glGetQueryObjectiv

### ISSUE THREAD

**Issue by yingyue219** [processing/processing#4024]
display（）{
        glMatrixMode(GL_MODELVIEW);
	glLoadIdentity();
	glRotatef(30.0f, 1.0f, 1.0f, 0.0f);
        glEnable(GL_DEPTH_TEST);
	glClear(GL_DEPTH_BUFFER_BIT|GL_COLOR_BUFFER_BIT |  GL_STENCIL_BUFFER_BIT );

	
	glDepthMask(GL_TRUE);

	//first  TRIANGLE
	glBeginQuery(GL_SAMPLES_PASSED/*GL_SAMPLES_PASSED*/, ids[0]);
	glBegin(GL_TRIANGLES);
	glColor3f(0.f, 0.0f, 1.0f); //blue
	glVertex3f(1.0f, 0.5f, 0.50f);
	glVertex3f(-0.5f, 1.0f, 0.50f);
	glVertex3f(-1.0f, -1.0f, 0.50f);
	glEnd();
	glEndQuery(GL_SAMPLES_PASSED);

	//second TRIANGLE
	glBeginQuery(GL_SAMPLES_PASSED/*GL_SAMPLES_PASSED*/, ids[1]);
	glBegin(GL_TRIANGLES);
	glColor3f(1.0f, 0.0f, 0.0f); //red
	glVertex3f(1.0f, 1.0f, -0.5f);
	glVertex3f(-1.0f, 1.0f, -0.5f);
	glVertex3f(-1.0f, -1.0f, -0.5f);
	glEnd();
	glEndQuery(GL_SAMPLES_PASSED);
	
	glutSwapBuffers();

	glBindFramebuffer(GL_READ_FRAMEBUFFER, framebuffer);

	{
		for (size_t i = 0; i < FACE_CNT; i++)
		{
			GLint params = 0;
			GLint queryReady = GL_FALSE;
			size_t count = 10000000;//wait
			while (!queryReady && count--)
			{
				glGetQueryObjectiv(ids[i], GL_QUERY_RESULT_AVAILABLE, &queryReady);
			}
			glGetQueryObjectiv(ids[i], GL_QUERY_RESULT, &params);
			std::cout << i << " GL_QUERY_RESULT = " << (int)params << std::endl;

		}

	}
}
the ssue is params of glGetQueryObjectiv(ids[i], GL_QUERY_RESULT, &params) is diffrent from draw oder(firt draw first  TRIANGLE or second  TRIANGLE );but display is right all;
result:
1.firt draw first  TRIANGLE
0 GL_QUERY_RESULT = 27183
1 GL_QUERY_RESULT = 20172

2.firt draw second  TRIANGLE
0 GL_QUERY_RESULT = 27183
1 GL_QUERY_RESULT = 26376 //diffrence

**Comment by JakubValtar** [comment]
This is Processing issue tracker, we can't help you with your C++ code.  Try http://stackoverflow.com
