### ISSUE TITLE
how to cross compiling mesa for windows

### ISSUE THREAD

**Issue by yingyue219** [processing/processing#4025]
I have done refer to follow  link
http://lists.freedesktop.org/archives/mesa-users/2014-April/000810.html
https://wiki.qt.io/Cross_compiling_Mesa_for_Windows
http://stackoverflow.com/questions/17871781/building-mesa-for-windows-7-mesa-9-1
https://wiki.qt.io/Cross_compiling_Mesa_for_Windows
http://www.mesa3d.org/install.html
(msys2 + python +LLVM):
1.echo Build LLVM...
①  export PYTHON=/usr/bin/python2 
  mkdir build
  cd build
 ② echo 'ac_cv_have_decl_strerror_s=${ac_cv_have_decl_strerror_s=no}' > config.cache
 ③../configure -C --prefix=$HOME/mesa3D/llvm-3.7.0/build/install64  --host=x86_64-w64-mingw32 --enable-optimized --disable-assertions --disable-pthreads --enable-targets=x86_64 --enable-bindings=none --disable-libffi --with-c-include-dirs=/mingw64/bin/x86_64-w64-mingw32 --with-gcc-toolchain=/mingw64/bin/x86_64-w64-mingw32 --with-default-sysroot=/mingw64/bin/x86_64-w64-mingw32  
--------------------------------------------------------------------------------------------------------------------------
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
configure: loading cache config.cache
checking for x86_64-w64-mingw32-clang... no
checking for x86_64-w64-mingw32-gcc... x86_64-w64-mingw32-gcc
checking for C compiler default output file name... a.exe
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... .exe
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-w64-mingw32-gcc accepts -g... yes
checking for x86_64-w64-mingw32-gcc option to accept ISO C89... none needed
checking for x86_64-w64-mingw32-clang++... no
checking for x86_64-w64-mingw32-g++... x86_64-w64-mingw32-g++
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-w64-mingw32-g++ accepts -g... yes
checking how to run the C preprocessor... x86_64-w64-mingw32-gcc -E
checking whether GCC or Clang is our host compiler... gcc
checking build system type... x86_64-pc-mingw32
checking host system type... x86_64-w64-mingw32
checking target system type... x86_64-w64-mingw32
checking type of operating system we're going to host on... MingW
checking type of operating system we're going to target... MingW
checking target architecture... x86_64
checking whether GCC is new enough... yes
checking optimization flags... -O2
checking for GNU make...
----------------------------------------------------------------------------------------------------
④make
⑤make install
2. 
①modified SConstruct file
env = Environment(
	options = opts,
	tools = ['gallium'],
	toolpath = ['#scons'],	
	ENV = os.environ,
)
env.Append(CXXFLAGS = '-std=c++11') 
env.Append(CXXFLAGS = '-D_USE_MATH_DEFINES') 

export LLVM=$HOME/mesa3D/llvm-3.7.0/build/install64
cd $ROOT_DIR/$MESA_SRC
②LDFLAGS="-static -s" scons build=release platform=windows toolchain=crossmingw machine=x86_64 libgl-gdi

but have more issue like:

C:/msys64/home/Administrator/mesa3D/llvm-3.7.0/build/install64/lib\libLLVMCodeGen.a(Passes.o):Passes.cpp:(.text+0x2205): undefined reference to `llvm::createSafeStackPass()'
C:/msys64/home/Administrator/mesa3D/llvm-3.7.0/build/install64/lib\libLLVMSupport.a(Compression.o):Compression.cpp:(.text+0x2a): undefined reference to `compressBound'
C:/msys64/home/Administrator/mesa3D/llvm-3.7.0/build/install64/lib\libLLVMSupport.a(Compression.o):Compression.cpp:(.text+0xbe): undefined reference to `compress2'
C:/msys64/home/Administrator/mesa3D/llvm-3.7.0/build/install64/lib\libLLVMSupport.a(Compression.o):Compression.cpp:(.text+0x288): undefined reference to `uncompress'
C:/msys64/home/Administrator/mesa3D/llvm-3.7.0/build/install64/lib\libLLVMSupport.a(Compression.o):Compression.cpp:(.text+0x3ba): undefined reference to `crc32'
collect2.exe: error: ld returned 1 exit status
scons: *** [build/windows-x86_64/gallium/targets/libgl-gdi/opengl32.dll] Error 1

**Comment by gohai** [comment]
Why do you want to cross-compile MESA for Windows?

**Comment by boubpopsyteam** [comment]
Nothing to do with processing ...

**Comment by codeanticode** [comment]
Closing, this is not a Processing issue.
