### ISSUE TITLE
NullPointerException in ContributionManager.deleteTemp()

### ISSUE THREAD

**Issue by w249054234** [processing/processing#4026]
I can't open the Processing... I use the Mac OX. I have tried to re-install the JAVA, processing 2/3.0 b7/3.0 even the OS system.... But I can't solve this problem. Can you help me? I'm a beginner. Thank you!
![1 pic](https://cloud.githubusercontent.com/assets/15196615/10579295/2fc2b5ae-766f-11e5-9fee-abc60dbed69f.jpg)

**Comment by alignedleft** [comment]
@w249054234 What version of the OS are you using? Do you have any external libraries / tools / modes installed?

**Comment by w249054234** [comment]
@alignedleft 
OS 11 Capitan. Yes, I have download some libraries form my teacher and the examples of The nature of code.
But I don't know how can I find it, and what's wrong it is? I just a beginner, and don't know much of programming.
Thank you very much!!!!

**Comment by alignedleft** [comment]
This is a good question for the forum: forum.processing.org

That said, @Akarshit, could you take a look at the error above? I wonder if this is CM-related. Thanks!

**Comment by w249054234** [comment]
@alignedleft Thank you very much... I'm waiting to complete my homework...

**Comment by benfry** [comment]
Fixed for 3.0.1.
