### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by bcman12358** [processing/processing#4038]
I am using windows 8.1 x32. I am attempting to run the sketch from the laser maze 2011 instructable. I am using processing 2.2.1 for compatibility reasons with some libraries. when ever i try to run the sketch, this like of code gets highlighted:
      if (grn < 1 || alarm.isPlaying()) grn = random(50,200);
and I get the error:
Could not run the sketch (target VM failed to initialize) PLEASE HELP I NEED THIS TO WORK BY THE 28TH!

http://www.instructables.com/id/LASER-Maze-Halloween-Haunted-House/

**Comment by benfry** [comment]
Please use forum.processing.org for programming questions.
