### ISSUE TITLE
GL related crashes when closing the display window on Ubuntu (Intel)

### ISSUE THREAD

**Issue by neilcsmith-net** [processing/processing#4041]
Not the same as #3977 though similar cause.  After updating my Intel graphics driver on Ubuntu, I get consistent segfaults when closing the display window.  Cause is the call to pgl.swapBuffers() at https://github.com/processing/processing/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L614  Commenting it out stops the issue.  Seems likewise related to accessing a GL resource that no longer exists, though I can't understand the comment for that line of code - why would you bother when the window is closing?

Salient bit of error log -

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  jogamp.opengl.x11.glx.GLX.dispatch_glXSwapBuffers0(JJJ)V+0
j  jogamp.opengl.x11.glx.GLX.glXSwapBuffers(JJ)V+41
j  jogamp.opengl.x11.glx.X11GLXDrawable.swapBuffersImpl(Z)V+17
j  jogamp.opengl.GLDrawableImpl.swapBuffers()V+67
j  jogamp.opengl.GLAutoDrawableBase.defaultSwapBuffers()V+23
j  com.jogamp.newt.opengl.GLWindow.swapBuffers()V+1
j  processing.opengl.PJOGL.swapBuffers()V+15
j  processing.opengl.PGraphicsOpenGL.dispose()V+15
j  processing.core.PApplet.dispose()V+28
j  processing.opengl.PSurfaceJOGL$NEWTWindowListener.windowDestroyNotify(Lcom/jogamp/newt/event/WindowEvent;)V+7
```

**Comment by codeanticode** [comment]
That swapBuffers() call might be superfluous after recent changes in the renderer. I will take a look and check if it can be indeed removed safely.

**Comment by codeanticode** [comment]
addressed with https://github.com/processing/processing/commit/8b75adc6601599bfba65a52b794b5540514ce297
