### ISSUE TITLE
Sketch will not run (Macbook Air 13 inch, OS X 10.11.1, Intel HD Graphics 5000 1536 MB)

### ISSUE THREAD

**Issue by dhey24** [processing/processing#4049]
Processing will not even run a simple "line(15, 25, 70, 90);" command.
I have tried moving the file folder as is suggested.
No errors are generated when the console utility is used, or when I run via command line.
Just for kicks I have tried running on my home wifi, work wifi, and with the wifi off, but the problem persists.
The oddest part is that 2 days ago I had a more complicated file running perfectly. In addition, yesterday a simple sketch did run once (but took around 15 minutes). However, after waiting for even hours, the sketches do not seem to ever run now.
Any help would be much appreciated.

**Comment by benfry** [comment]
Please use forum.processing.org for troubleshooting questions like this.
