### ISSUE TITLE
KeyCode error with OpenGL

### ISSUE THREAD

**Issue by ludiccc** [processing/processing#4050]
I found an error when using OPENGL in size and the keyCode for the Fn keys in OSX (not tested on other platforms):

    import java.awt.event.KeyEvent;
    void setup() {
    	size(1024,768,OPENGL);
    }

    void draw() {
    }

    void keyPressed() {
      println(keyCode + " " + KeyEvent.VK_F1);
    }

The output is:

    97 112

And should be:

    112 112

**Comment by benfry** [comment]
Nope, the key codes are different because we're not using AWT key events in OpenGL. You'll need to use JOGL key events instead.

**Comment by ludiccc** [comment]
Should it be corrected or noted in the docs? 

in
    java/reference/keyCode.html

it states that "Other keyCode values can be found in the Java KeyEvent reference.".
