### ISSUE TITLE
Export without a stop button using P3D or P2D

### ISSUE THREAD

**Issue by joemckay5** [processing/processing#4056]
Using Processing 3.0 on a mac (10.10.2) 
If I export a sketch that uses P3D or P2D and do NOT check "Show a Stop button", I get a stop button anyways.

**Comment by codeanticode** [comment]
good find, thank you.

**Comment by joemckay5** [comment]
No problem, (and thank YOU).

**Comment by codeanticode** [comment]
You are welcome! We just released 3.0.1 without noticing this bug, so we will hopefully be able to fix it in the next release (3.0.2 or 3.1?)

**Comment by iamutkarshtiwari** [comment]
@joemckay5 Could you please elaborate that bug or post a screenshot which could help figuring out how to get around to the solution?

**Comment by joemckay5** [comment]
Are you unable to replicate the bug? It may be OS dependent, I'm on a mac. 
1. Make a simple sketch and using either P2D or P3D as the renderer, and save it. 
2. Go under file to Export application. 
3. Uncheck the box next to "Show a Stop button" and export. 
4. Open the application and there's still a stop button, even though I didn't select it. 
I have no idea how to get around the solution, although I imagine this is a pretty trivial problem for those that do.

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing/commit/9fd08c21082afc5d698c73a0bd369e7b65f659e7. I still need to work on the colors and size of the button.
