### ISSUE TITLE
PDE Console is not resizable after window settings are changed

### ISSUE THREAD

**Issue by Artpen** [processing/processing#4059]
If you change : 
editor.window.height.default=950
editor.window.width.default=600

these two options in preference.txt file your console window is not resize itself to fit a new size. It just split s the whole window in half. 

So every time you open PDE it looks like this.
Please see attached image.

![screen shot 2015-10-25 at 10 11 29](https://cloud.githubusercontent.com/assets/15308495/10715159/3f56ae2e-7b03-11e5-8f93-be10685600df.png)

**Comment by benfry** [comment]
Don't change that setting.
