### ISSUE TITLE
how to extract  decompress  images from an IVE

### ISSUE THREAD

**Issue by yingyue219** [processing/processing#4061]
OSG issue : I have a question about extracting images from an IVE with compressed textures. 
osg::Texture2D *texture2D = dynamic_cast<osg::Texture2D *>
					(geometry->getOrCreateStateSet()->getTextureAttribute(0, osg::StateAttribute::TEXTURE));
osg::ref_ptr<osg::Image> image = texture2D->getImage();//but image is compressed

**Comment by codeanticode** [comment]
@yingyue219 please post your OpenGL/C++ programming questions in the appropriate forums, this site is only meant to report Processing issues.
