### ISSUE TITLE
mode android

### ISSUE THREAD

**Issue by kingjo47** [processing/processing#4063]
env: ubuntu14
issue: hi , when I try to install android mode, processing show a error " can't find android SDK", of course I have android SDK and developed some android application, I wish I can setup SDK by myself but I can't find any clues.

PS: you started a good project.

**Comment by codeanticode** [comment]
Please report issues related to the android mode in the [processing-android repo](https://github.com/processing/processing-android). Thanks!

Re-openend at https://github.com/processing/processing-android/issues/172
