### ISSUE TITLE
Background size and window render glitch

### ISSUE THREAD

**Issue by Digitalblueeye** [processing/processing#4069]
Hi, I am using processing-3.0.1 on Elementary OS Freya (Basically Ubuntu). During use in eclipse or in the PDE, I seem to be getting a re-appearing rendering glitch. When I launch a sketch, every so often, the background/visuals of the sketch do not fully fill the window, leaving this whitespace on the bottom and also right side that appears to be about 10 or less pixels. This seemingly happens at random times. In order to fix that issue, I usually have to stop the sketch and start it again.

**Comment by benfry** [comment]
Sorry, this is much too esoteric an issue for us to even begin to try to fix it: 1) an unsupported OS, 2) no idea what your graphics drivers are, 3) no code, 4) nothing to reproduce... Nothing here we can fix.

**Comment by Digitalblueeye** [comment]
Alright, my drivers are the amd proprietary drivers supplied by Ubuntu. The
issue happens no matter what my code is.
