### ISSUE TITLE
'Update' Status Still Shows in Libraries tab of Contributions Manager After Update

### ISSUE THREAD

**Issue by brendanmatkin** [processing/processing#4071]
Minor issue: 

![image](https://cloud.githubusercontent.com/assets/5040862/10752699/d5f43f7c-7c48-11e5-9c0d-9169d33bd0af.png)

After auto-updating in the 'updates' tab - the updated libraries still show an update is required in the 'libraries' tab. The 'installed version' in the lower right shows current, just the orange exclamation is still showing. 

The 'updates' tab is clear (shows no updates required).

**Comment by Akarshit** [comment]
Thanks @brendanmatkin, looking into this.

**Comment by Akarshit** [comment]
@jamesjgrady The authors of the libraries need to be notified to update the version number in the `library.properties` file. For example SketchMapper is having this issue.

Also `GenerativeDesign` has a problem, the version 1.0.5 had folder named `GenerativeDesign` while the recent 1.0.6 version has a folder `generativedesign`. This is causing duplicates and leading to some bad situations if these are downloaded within same sketchbook.

**Comment by benfry** [comment]
@Akarshit James did the UI design; he's not the person to handle this sort of thing. @prisonerjohn is in charge of contributions and may be able to help, but I'm not sure why you're doling out tasks.

**Comment by prisonerjohn** [comment]
This is unfortunately a recurring problem with library updates, and there's currently no way to check this without downloading, unzipping, and verifying each package. Thanks for flagging, I'll look into it and notify the authors.

**Comment by Akarshit** [comment]
@benfry I just thought it would be better if the authors are informed by @prisonerjohn.

**Comment by benfry** [comment]
Closing this since it's a problem with the libraries, not the PDE.
