### ISSUE TITLE
"Could not find a library in the downloaded file.": Contribution Manager (specific to Punktiert?)

### ISSUE THREAD

**Issue by brendanmatkin** [processing/processing#4072]
Suspect partly punktiert issue, partly contribution manager: 

Attempt to install punktiert from contribution manager. Allows me to download but then gives error: "Could not find a library in the downloaded file."

If I install the old fashioned way (copy into libraries), it works fine (but still shows as not installed in contribution manager). 

When I download punktiert from [the website](http://www.lab-eds.org/punktiert) - the folder is contained within another folder: punktiert/punktiert/[library contents] - I imagine this is the issue but I'm not sure where contributions manager is getting the libraries.

**Comment by brendanmatkin** [comment]
(the contribution manager shows v 2.0, lab-eds website shows current as 2.0.1 [github](https://github.com/djrkohler/punktiert) shows 2.0 as most recent it seems? Not sure if there is a difference.

**Comment by Akarshit** [comment]
@jamesjgrady I think the contribs.txt need to be updated regarding the version number and also the author has to be notified to correct the directory structure.

**Comment by benfry** [comment]
This is entirely an issue with the library; please get in touch with the library author.
