### ISSUE TITLE
Mode out of Date issue after downloading latest version

### ISSUE THREAD

**Issue by HeroLabsAndroid** [processing/processing#4075]
Today, I downloaded the newest version of your software (3.0.1) but whenever I try to start it, I receive a message that the Android mode is out of date and I should update it. I have even tried going back to an older version (3.0) that worked before, which did not help either.

Edit: Found out that 2.2.1 works.

**Comment by codeanticode** [comment]
Please report issues related to the android mode in the [processing-android](https://github.com/processing/processing-android) repo.

I re-openend this issue [here](https://github.com/processing/processing-android/issues/173).
