### ISSUE TITLE
help box grayed out!

### ISSUE THREAD

**Issue by joesh1** [processing/processing#4076]
I seem to be having a problem with the help option on the menu bar. Does anyone have any suggestions as it used to work fine! I'm going to try reseting permissions as maybe there's a problem there, although normally I imagine that should be related?

Thanks in advance.

Here's a screen shot in case I wasn't clear:
![help](https://cloud.githubusercontent.com/assets/6313086/10786042/3aa599e6-7d68-11e5-83ff-272dd6ad9170.jpg)

**Comment by joesh1** [comment]
Problem solved - I don't know if that was the problem, but I updated permissions on the computer.

**Comment by davschne** [comment]
I just installed Processing 3 in OSX El Capitan, and I'm having the same problem. It looks like others are experiencing this too (https://forum.processing.org/two/discussion/1377, https://forum.processing.org/two/discussion/14144/help-menu-items-greyed-out). @joesh1 , can you please clarify how you solved the problem? For what files/directories did you set permissions, and what did you set them to?

**Comment by benfry** [comment]
Yeah, it's a known issue: https://github.com/processing/processing/issues/4353#issuecomment-237715947 

Just happens randomly, I haven't seen/found a fix for it.
