### ISSUE TITLE
Impossible to use variables in size()

### ISSUE THREAD

**Issue by Berkmann18** [processing/processing#4080]
I'm trying to make responsive programmes so I'm using variables to set the size of the program  like:
int w=320, h=480;
void setup(){
  size(w, h);
...
}
...
But it gives me an error message: "The size of this sketch could not be determined from your code" when it used to work without any problems on previous versions.

**Comment by iamutkarshtiwari** [comment]
@Berkmann18 As per the requirements of Processing 3.0, you need to use the variable names as ***"displayWidth"*** and ***"displayHeight"*** for width and height respectively inside the size() function to work.

**Comment by iamutkarshtiwari** [comment]
@benfry Do we need to do work on any modifications in the code for this or the default "displayWidth" and "displayHeight" naming is fine?

**Comment by Berkmann18** [comment]
@iamutkarshtiwari What about the problem with the variables usage ?

**Comment by aengelke** [comment]
You can use variables by putting the size line into `void settings() { /* here */ }`. See https://processing.org/reference/settings_.html

**Comment by bilmor** [comment]
Here's how to resize a window:

https://github.com/processing/processing/wiki/Changes-in-3.0#things-that-may-break-your-2x-sketches

**Comment by Berkmann18** [comment]
Cheers guys.

**Comment by iamutkarshtiwari** [comment]
@Berkmann18 Could you please close this issue ?
