### ISSUE TITLE
Soundfile.loop() only plays once

### ISSUE THREAD

**Issue by sjernigan** [processing/processing#4081]
#soundfile.loop() only plays once.  Tested with wav, mp3, and aif on mac with Processing 3.0.1 and Sound 1.3.1

Here's an example
```
import processing.sound.*;
SoundFile background;

void setup() {
  background = new SoundFile(this,"path/to/sound.mp3");
}

void draw() {}
  
void keyPressed() {
    background.loop();
}
```

**Comment by sjernigan** [comment]
moving issue to sound, sorry

**Comment by benfry** [comment]
Moved to the correct location: https://github.com/processing/processing-sound/issues/58
