### ISSUE TITLE
"don't show welcome to processing 3 msg again" checkbox does nothing

### ISSUE THREAD

**Issue by okeribok** [processing/processing#4100]
Processing 3 shows a welcome dialog, with a checkbox labeled "show this welcome message each time". It is default "on". 

I expect that unchecking this checkbox makes processing "remember" my wish and respect it the next time I open it. Not so much; I see this message each time I open processing 3.

I see this behaviour on both windows 7 and Mac 10.10.4.

Can we please ERASE the whole dialog and exchange it for a more prominent change history/what's new link on the download page? Would save on transferred bytes too!

**Comment by benfry** [comment]
https://github.com/processing/processing/issues/3911
