### ISSUE TITLE
Java PApplet Integration Broken...? (no init() method)

### ISSUE THREAD

**Issue by DerTarchin** [processing/processing#4120]
I was following outdated tutorials of how to display Processing as PApplet in a Swing component, however Processing 3.0 and 3.0.1 have a broken implementation (no init() method, it seems to be commented out in the processing core files). Why is this?

Is there a new way to do this or do i have to use Processing 2 for my java app purposes?

**Comment by aengelke** [comment]
That is on intention: https://github.com/processing/processing/wiki/Changes-in-3.0#things-that-may-break-your-2x-sketches

> **Applet is gone** — Java's `java.awt.Applet` is no longer the base class used by `PApplet`, so any sketches that make use of Applet-specific methods (or assume that a `PApplet` is a Java AWT `Component` object) will need to be rewritten.

See also: https://github.com/processing/processing/blob/master/core/README.md
