### ISSUE TITLE
Crashing when trying to run code

### ISSUE THREAD

**Issue by lazorkitten** [processing/processing#4123]
So any version of processing I use crashes when I try to run my code. I make sure the code works on a different machine and when I try to run it off mine, the Processing application freezes and stops responding, requiring a force quit. I am on windows 10 and it is not giving me any error codes so I have no idea what is going on. Any help would be appreciated.

**Comment by benfry** [comment]
Nothing here for us to look at... Visit the troubleshooting page for tips: https://github.com/processing/processing/wiki/Troubleshooting
