### ISSUE TITLE
ClassCastException when PGraphics is used where PImage is expected

### ISSUE THREAD

**Issue by nbeloglazov** [processing/processing#4127]
`PApplet.copy()` can take an instance of `PImage` as source. Processing 2 supported following use case:
1. Create an instance of `PGraphics` with `PApplet.createGraphics()`. 
2. Draw on the graphics object.
3. Copy part of the graphics to main window using `PApplet.copy()`: `PGraphics` extends `PImage` so one might expect it to work.

In processing 3, however, `PImage.getNative()` is used when making a copy. And `copy()` method expects it to return an instance of `java.awt.Image`. At the same time `PGraphics` and classes extended from it return different objects, not Images resulting in error like this:

```
java.lang.ClassCastException: sun.java2d.SunGraphics2D cannot be cast to java.awt.Image
    at processing.awt.PGraphicsJava2D.copy(PGraphicsJava2D.java:2985)
```

I understand that it might be intended behavior as use case I described might be quite rare and fixing it not easy. Is there a way to convert any `PGraphics` into an `PImage` so it can be used as source later? 

Thanks,
Nikita

**Comment by 71c** [comment]
If you specify the renderer as P3D in the`size()` function, it doesn't give this error.

**Comment by benfry** [comment]
Just use `set()` to quickly move the pixels from a `PImage` or `PGraphics` to the main drawing surface. If you need a subset of the image, first call `get(x, y, w, h)` on the image to get the parts you want.

**Comment by ssilverman** [comment]
I know there are workarounds, but isn't this a case of the API doing something unexpected when an object passed as a PImage isn't actually behaving according to the API spec?

**Comment by ssilverman** [comment]
I just tried set(). I get another NullPointerException:
> java.lang.NullPointerException
> at processing.awt.PGraphicsJava2D.getRaster(PGraphicsJava2D.java:2736)
> at processing.awt.PGraphicsJava2D.setImpl(PGraphicsJava2D.java:2913)
> at processing.core.PImage.set(PImage.java:907)

(Processing v3.4)
