### ISSUE TITLE
surface.setSize() not always working when using P2D/P3D on Linux

### ISSUE THREAD

**Issue by Zeroji** [processing/processing#4129]
I have a project using a variable size window, where the size is determined through a config file.

Basically here's the size stuff in setup:

```
  size(480, 270);
  loadPrefs();
  surface.setSize(w, h);
```

![withoutP2D](http://i.imgur.com/0ppgAmT.png)
As you can see, this is working well. Then I worked with translate() and rotate() and had big performance issues, so I switched to
`size(480, 270, P2D);`
and that's what I got:
![withP2D](http://i.imgur.com/icsMgBv.png)
I tried multiple things, including adding `surface.setResizable(true);` which gave me this:
![withP2Dresizable](http://i.imgur.com/iMn9bVJ.png)
I could resize the window manually, but that's not convenient, plus I don't want it to be resizable.

I tried using `frame.setSize`, `surface.setSize` and `setSize` but none of them worked.

I'm running Linux Mint 17.1 64-bit, and I'd like to note that at school this worked on Kubuntu 14 32-bit, also my graphic drivers are up-to-date.

_Silly side note: when switching from normal mode to P2D, the 'α' in the window title goes wrong._

**Comment by codeanticode** [comment]
what version of Processing are you using? This seems to be a platform specific issue, as I tested surface.setSize() on OS X, and works without problem (Processing 3.0.1)

**Comment by Zeroji** [comment]
Using latest 3.0.1

I sent the following code to some friends:
```
void setup()
{
  size(400, 200, P2D);
  surface.setSize(1600, 800);
}
void draw() {}
```
Works well on OS X, Windows 7 64b, Kubuntu 14 32b
Doesn't work on Mint 17 64b, Ubuntu 14 64b

It seems platform-specific, but it's annoying because not using P2D causes my framerate to drop from 60 to 8.

**Comment by codeanticode** [comment]
What window manager(s) are you using in Mint and Ubuntu?

This sounds like an upstream bug in [JOGL](http://jogamp.org/jogl/www/), I would probably need to check  with them.

**Comment by Zeroji** [comment]
I'm using XFCE and my friend on Ubuntu has the default for 14.04, I guess it's Unity.
Any idea about the P2D not handling correctly the special character in window title?

Thanks for your quick replies :)

**Comment by codeanticode** [comment]
My recommendation for the time being would be to use a different window manager.

I think both are upstream bugs, will check in the [JOGL forum](http://forum.jogamp.org/issues-with-GLWindow-on-XFCE-Linux-Mint-td4035760.html).

**Comment by codeanticode** [comment]
Based the [response](http://forum.jogamp.org/issues-with-GLWindow-on-XFCE-Linux-Mint-tp4035760p4035764.html) I got in the JOGL forum, this might even be a bug in the window manager. I don't think this can be fixed from Processing. Did you try switching to another window manager?

**Comment by Zeroji** [comment]
I know it bugs in Unity and XFCE, works in KDE. I don't really want to switch, but if anyone with another window manager runs across this issue, try the following code:
```
void setup()
{
  size(200, 200, P2D);
  surface.setSize(600,600);
}
void draw() {}
```
A big window means it works.
I'll ask some friends and coworkers to see if I can grab information about different window managers.

**Comment by obackhoff** [comment]
I solved this issue by calling surface.setSize() in the draw() once (using a boolean) instead of calling it from setup(). I don't know why this happens but that solved the problem for me.

**Comment by Calendis** [comment]
This bug still exists! surface.setSize in setup works on my Fedora 33 KDE machine, but not on my Fedora 32 KDE machine

**Comment by benfry** [comment]
This seems to be a window manager issue that's out of our control. I'm opting to close it since we aren't setting any expectation about a "fix" being on the way. But as far as we know, it's not something that we can fix. If someone wants to look into it, or finds otherwise, please open a new issue in the Processing 4 repository: https://github.com/processing/processing4

If you want to set the size after loading some preferences, you could put that code into `settings()` (https://processing.org/reference/settings_.html) and then call `size()` based on that. But *very little* code will run in `settings()`, so you'll need to be careful about what methods you're using (i.e. assume you're basically on your own/writing raw Java code at that point… don't rely on the sketch path to be set and other internal Processing functions to work).
