### ISSUE TITLE
Windows SmartScreen can't be reached right now

### ISSUE THREAD

**Issue by froth30** [processing/processing#4130]
After extracting all files from the downloaded zipped folder for Processing 3.0.1 (Windows 64-bit) and attempting to run the main application "processing.exe", I am alerted of a security risk (or inability to assess its security).  I tried running it anyway, but then my Norton Security software removed it.  It seems like this has something to do with the fact that the publisher is "unknown".  Any advice would be appreciated.

**Comment by EsEhKa** [comment]
In version 3.4 Norton Security Scan deleted both executable files with the message, that there was the risk of "WS.Reputation.1". Why is this still going on?

**Comment by benfry** [comment]
You'd have to ask the Norton folks. Closing since we can't control their false positives.
