### ISSUE TITLE
[OpenGL] Serious bug in clear()

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#4131]
Using clear on a PGraphics makes the main canvas black:

````java
PGraphics result;

public void settings() {
  size(512, 512, P2D);
}

public void setup() {

  result = createGraphics(512, 512, P2D);
  result.beginDraw();
  result.endDraw();
}

public void draw() {

  // a white background...
  background(255);
  // just became black...
  result.clear();
}
````

Processing 3.0.1
(fuck) Mac OS X 10.11

**Comment by codeanticode** [comment]
You need to enclose any drawing call on a PGraphics surface between begin/endDraw(), i.e.:

```java
public void draw() {
  background(255);
  result.beginDraw();
  result.clear();
 result.endDraw();
}
```

**Comment by clankill3r** [comment]
In that case, is it wrong to use clear like this:
https://processing.org/reference/clear_.html
?

**Comment by codeanticode** [comment]
ok, I think you are right @REAS @alignedleft what do you think? pg.clear() without begin/endDraw() works with JAVA2D, but does not with P2D/P3D, shouldn't the reference be updated so the example works irrespective of the renderer?

**Comment by alignedleft** [comment]
@codeanticode Good catch. My first choice would be to make the behavior consistent across renderers, so we don't have to complicate the documentation. Assuming that's not possible, we could either:

- address this difference between renderers explicitly in the description, and provide two separate examples, or
- just modify the current example to use `pg.clear()` only within begin/endDraw()

Do you have a preference?

**Comment by REAS** [comment]
I like your second option, @alignedleft in addition to starting that in the Reference. I'll open an issue, can I assign it to you?

**Comment by alignedleft** [comment]
Yes, please! Thanks.

**Comment by benfry** [comment]
`clear()` should definitely only be used between `beginDraw()` and `endDraw()`. I'm surprised it would work with Java2D, but it's likely that it won't in all (most?) cases.
