### ISSUE TITLE
Very strange simple math problem...

### ISSUE THREAD

**Issue by Adiou** [processing/processing#4132]
Hi, 

That's strange, when I run this sketch : 

float test = (1920/512); 
println("test : "+test);

processing gimme test : 3.0
But 1920/512 is equal to 3.75...

So...do you know where I make a mistake?

Thanks

**Comment by Adiou** [comment]
Ok, if I write      float test = (float)1920/512 or float test = 1920./512. 
I have the correct answer...didn't know processing give you an int when you divide int number whithout specify "make them float", even if your variable is a float...

**Comment by alignedleft** [comment]
Yes, that's called casting. Please save questions like this for the forum: forum.processing.org

**Comment by benfry** [comment]
https://github.com/processing/processing/wiki/Troubleshooting#why-does-2--5--0-instead-of-04
