### ISSUE TITLE
Show the current line number and tab location of the cursor in the Editor

### ISSUE THREAD

**Issue by iamutkarshtiwari** [processing/processing#4135]
There should be a feature in the Editor to display the line number and tab index of the current cursor location.

**Comment by iamutkarshtiwari** [comment]
Working on this.

**Comment by benfry** [comment]
This is the sort of thing we leave out of the PDE on purpose. Advanced users who would want something like this can use another editor (i.e. Sublime) or a full-fledged IDE (Eclipse, IntelliJ).
