### ISSUE TITLE
A serious error occurred while trying to create a new editor window

### ISSUE THREAD

**Issue by ntroufan** [processing/processing#4137]
Have not modified anything.  Tried opening Processing the next day and started getting this error window in all Processing versions.  Downloaded v 3.0.1 still the same error.
Any ideas what happened?
Thank you!

![processing](https://cloud.githubusercontent.com/assets/15824328/11132807/01b5ee70-8947-11e5-80d5-82cc442195e8.JPG)

**Comment by Geoffree3** [comment]
Processing 3.0.1 grinds to a halt occasionally, this time with a java.lang.OutOfMemoryError: Java heap space.  It's using 600MB memory currently.

**Comment by benfry** [comment]
That looks like you have a bad library installed that includes an old version of `pde.jar`. You should get troubleshooting help on the forum.
