### ISSUE TITLE
hint doesn't exist in reference, has DISABLE_ASYNC_SAVEFRAME?

### ISSUE THREAD

**Issue by gohai** [processing/processing#4138]
Stumbled upon this while trying out some old sketch (pre-2.0 I believe). Something like this used to work:

    save("frame.jpg");
    // ...
    PImage img = loadImage("frame.jpg");

But now it either throws an exception (file not found), or `img` might end up being `NULL`, supposedly because the (partial) file read wasn't a valid image. It *does* work when I add a delay().

**Comment by gohai** [comment]
Thinking a bit more about this: perhaps this is really the expected behavior, for not holding up draw(). Please close in this case..

**Comment by benfry** [comment]
Yeah... that's something @JakubValtar implemented for 3.0. Try disabling it with `hint(DISABLE_ASYNC_SAVEFRAME)`. (Is this not in the docs yet?)

**Comment by gohai** [comment]
Ah, good to know, sorry for the noise - sounds like a useful optimization
indeed. Hint doesn't exist in reference currently!

**Comment by benfry** [comment]
Moved to the correct repo: https://github.com/processing/processing-docs/issues/393
