### ISSUE TITLE
Raspberry Pi:  pathnames should be shown in the window caption

### ISSUE THREAD

**Issue by VogonJeltz** [processing/processing#4141]
Raspberry Pi: 
not to confuse things having same file names opened in different folders, pathnames should be shown in the window caption please

**Comment by gohai** [comment]
The file name is the same name as the folder (sketch), so unlikely to be a problem IRL.

**Comment by VogonJeltz** [comment]
yes, but maybe 1 is at
/pi/programs/test/mysketch/
and the other one at
/pi/programs/project/mysketch/

**Comment by gohai** [comment]
Most people have all their sketches in a single "sketchbook", e.g. ~/sketchbook/mysketch. So not an issue. Thanks for your suggestion, though.

**Comment by VogonJeltz** [comment]
you're welcome,
but I'm using my own directory tree, as I'm already doing it for Arduino Sketches and gcc C/C++ so far.
