### ISSUE TITLE
Raspberry Pi: Progress Meter or status messages wishful while compiling

### ISSUE THREAD

**Issue by VogonJeltz** [processing/processing#4142]
Raspberry Pi:  
a Progress Meter or status messages would  wishful while compiling, after mouse click on "run" button.
One does not know what's happening at all during minutes of compile time...

**Comment by gohai** [comment]
Estimating how much time is spent doing what is a pretty difficult task on its own, and dependent on many external factors, such as the speed of I/O (which is pretty limited on the Pi). So this is unlikely to happen, but I do have an eye on sketch startup times, and will see if we can make them faster for less powerful machines.

**Comment by VogonJeltz** [comment]
I was thinking of something simple like the status messages at Arduino IDE when compiling/uploading

**Comment by gohai** [comment]
Thanks for your suggestion.

**Comment by aengelke** [comment]
See #136.
