### ISSUE TITLE
RasPi: missing feature or missing documentaion about threads / multitasking like by pthread ?

### ISSUE THREAD

**Issue by VogonJeltz** [processing/processing#4146]
missing feature or missing documentaion about threads / multitasking ?

How to create parallel task like using pthread tasks/threads ?

**Comment by gohai** [comment]
The scope of Processing is limited to tasks and functions that a beginner might encounter. To do multithreading, please read up on what Java 8 is providing you out of the box, or consider using a more technically-minded framework.

**Comment by VogonJeltz** [comment]
thanks for your reply, 
I'm not a Java programmer at all, I'm using just C/C++ and Arduino Sketch C/C++ so far and will stick to it. I thought Processing Sketch was like Arduino C/C++ Sketch.
Sorry that I didn't recognize this so far.

**Comment by aengelke** [comment]
Also, see the [Processing reference for `thread()`](https://processing.org/reference/thread_.html).

**Comment by VogonJeltz** [comment]
this  actually looks quite ambiguous to me, as threads, once been started, are running simultaneously by proprietary control (endless or by semaphores or due to internal conditions or even killed by a different tasks), 
but they shouldn't  have to be repetitively called by an endless loop.

As for Arduino Wiring,  refer to Scheduler ::
https://www.arduino.cc/en/Reference/Scheduler

~~~
#include <Scheduler.h>

int counter = 0;
int counter1 = 0;

void setup()
{
  Scheduler.startLoop(loop1);
}

void loop () {
 analogWrite(9, counter);
 counter++;
 if (counter > 255){
  counter = 0;
 }
 delay(33);
}

void loop1 () {
 analogWrite(10, counter1);
 counter1=counter1+5;
 if (counter1 > 255){
  counter1 = 0;
 }
 delay(10);
 yield();
}

~~~
