### ISSUE TITLE
RasPi: drop draw() and have main() instead?

### ISSUE THREAD

**Issue by VogonJeltz** [processing/processing#4147]
how to drop 
draw() 
and have 
main() 
instead like the way it's common to C/C++  ?

**Comment by gohai** [comment]
@VogonJeltz This isn't C/C++.

**Comment by VogonJeltz** [comment]
but it is compiled to C/C++, not?

(also for Arduino I can substitute
setup()
and 
loop()
by
~~~
int main() {
   setup();
   while(1) {loop();}
}
~~~

**Comment by gohai** [comment]
It is Java, not C.

**Comment by VogonJeltz** [comment]
sorry, I thought is was like the Arduino Shetches which are C/C++ coded
