### ISSUE TITLE
Esoteric error for methods with a similar signature

### ISSUE THREAD

**Issue by gohai** [processing/processing#4149]
I tried implementing a `void write(byte)` in a library class that also has a `void byte(int)`. This compiles without problems, but when I try to use `write(literal)` in a sketch I get this error at startup:

    crashed in event thread due to Timeout occurred while waiting for packet 29.
    org.eclipse.jdi.TimeoutException: Timeout occurred while waiting for packet 29.
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:186)
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:197)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:191)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:226)
	at org.eclipse.jdi.internal.ThreadReferenceImpl.frames(ThreadReferenceImpl.java:257)
	at org.eclipse.jdi.internal.ThreadReferenceImpl.frames(ThreadReferenceImpl.java:240)
	at processing.mode.java.runner.Runner.findException(Runner.java:726)
	at processing.mode.java.runner.Runner.reportException(Runner.java:709)
	at processing.mode.java.runner.Runner.exceptionEvent(Runner.java:631)
	at processing.mode.java.runner.Runner$2.run(Runner.java:523)

Some [searching](https://forum.processing.org/two/discussion/3912/program-crashes-because-of-timeout) pointed me at the right direction, but perhaps this is an easy fix? Curious to know whether two methods with just a different argument type (byte vs int) are legal or not!

**Comment by gohai** [comment]
Perhaps https://github.com/processing/processing/blob/master/java/src/processing/mode/java/runner/Runner.java#L748 could be extended by a catch-all exception handler?

**Comment by JakubValtar** [comment]
I wonder what the problem could be? Do you call different `write` function than you wanted? Literals are `int` by default.
```processing
void setup() {
  write(0x03);         // int
  write((byte) 0xFF);  // byte
  write(6);            // int
  write((byte) 6);     // byte
}

void write(int i) {
  println("int");
}

void write(byte i) {
  println("byte");
}
```

**Comment by gohai** [comment]
Aw, good catch, it probably was my error after all. Seems like the message above is triggered for an infinite recursion (my byte-variant was calling itself, instead of the int one).

**Comment by gohai** [comment]
Thanks @JakubValtar!

**Comment by JakubValtar** [comment]
You're welcome. Ghostbusters signing off.

![](https://38.media.tumblr.com/tumblr_mawaleOx9A1qfr6udo1_400.gif)

**Comment by gohai** [comment]
:+1:

(But shouldn't we make the message more descriptive while we're at it?)

**Comment by JakubValtar** [comment]
Hm, I agree that this message is only partially helpful, but what do you want to do? Just not print the message?

**Comment by gohai** [comment]
If I read the code correctly, we might actually have a more useful message at that point (the `message` argument), but we crash here before we get to do anything with it: https://github.com/processing/processing/blob/master/java/src/processing/mode/java/runner/Runner.java#L726

I haven't looked into this part of the codebase ever, but couldn't adding a more general `catch (Exception e) {}` to that block fix it so that we print the actual message further below? (Just a thought)

**Comment by JakubValtar** [comment]
@gohai Ah, sorry. I think it was already decided in #2623

**Comment by gohai** [comment]
@JakubValtar Point taken! Thanks again for looking into this.
