### ISSUE TITLE
feature request: uninstall program or guide

### ISSUE THREAD

**Issue by VogonJeltz** [processing/processing#4151]
what does one have to do to uninstall / remove Processing ? 
Is there a uninstall procedure? 
Or which folders have to be removed manually from the Raspi SD card?

**Comment by gohai** [comment]
Remove `/usr/local/lib/processing-3.0.1` and the (now dangling) symlink `/usr/local/lib/processing`. Remove the dangling symlinks `/usr/local/bin/processing` and `/usr/local/bin/processing-java`. Finally, remove `/usr/local/share/applications/processing.desktop`.

**Comment by VogonJeltz** [comment]
what is a symlink? is it just a folder name ?

**Comment by gohai** [comment]
That's because of UNIX file permissions. Try deleting it in a Terminal with `sudo rm -Rf /usr/local/lib/processing` etc.

Anyway, that's more of a general Raspberry Pi how-to type of question than an issue with Processing ;)

**Comment by VogonJeltz** [comment]
I'm new to Raspi and new to Linux, I never uninstalled or deleted anything and even don't know all the Linux commands!
