### ISSUE TITLE
exit() is not called in P2D/P3D

### ISSUE THREAD

**Issue by darthyoshi** [processing/processing#4156]
With the OpenGL renderers (P2D/P3D), exit() is only called if closing the sketch via the ESC key. Closing the sketch via the close window button or ALT+F4 does nothing.

```
void setup() {
  size(800,600,P2D);
  //size(800,600);
}

void draw() {}

void exit() {
  println("closing");
  super.exit();
}
```

**Comment by codeanticode** [comment]
@darthyoshi Ok, I'm able to reproduce this on Mac OS X. I assume you are on Window, right?

**Comment by darthyoshi** [comment]
Primarily Windows, yes, but I've also seen this on Linux.
