### ISSUE TITLE
Tab and .pde file deleted after compiling 3.0.1

### ISSUE THREAD

**Issue by CreateiveRobotics** [processing/processing#4157]
Processing keeps deleting some of my tabs after I compile then quit my app. After closing the app (the one I'm writing, not Processing its self) I get an error message saying that one of my files has been changed by another application and asking if I want to reload it. If I click 'no' the message pops up again (and repeats when I click 'no') but if I click 'YES' then one of my tabs will disappear and the corresponding .pde file for that tab will have been deleted.

Fortunately there is always a copy in my sketch folder with a tmp extension appended to the filename so deleting that extension will restore the file.

As far as I can tell it happens whenever I have unsaved data in one tab but have selected another tab when I compile the code. 

My guess as to the cause ... Processing and my sketchbook are both in my Dropbox folder?

I'm running winXP 32bit.

**Comment by CreateiveRobotics** [comment]
Ok, it doesn't seem to depend on whether the tab had been saved, and it has also happened when switching back to Processing from a different application.

**Comment by andyengria** [comment]
I found this bug already recorded and open. I experience exactly the same issue with my sketches also being saved in a Dropbox folder. In my case I am using processing ide 3.2.1 on Windows 10 64bit.

**Comment by CreateiveRobotics** [comment]
I've moved to Win10 x64 and the problem has got better - but still occurs very occasionally ...

**Comment by benfry** [comment]
The problem is being tracked here: https://github.com/processing/processing/issues/3965
