### ISSUE TITLE
Trying to draw to the PGraphics of a PSurface during draw() crashes the app

### ISSUE THREAD

**Issue by atduskgreg** [processing/processing#4160]
I'm trying to update [this old technique](https://gist.github.com/atduskgreg/ad689ff9685345ae6cee) for creating a second window in Processing 3.x. That old technique relied on access to the Frame and hence is incompatible with the new PSurface-based rendering. @codeanticode pointed me in the right direction on Twitter. But I've hit a crash in actually trying to draw dynamically into the second window.

Here's example code that produces the crash:

     PGraphics pg;
     PSurface surf;
     
     void settings() {
       size(320, 240);    
     }
       
     void setup() {
       pg = createGraphics(500, 200);
       surf = pg.createSurface();
       
       surf.initFrame(this);
       surf.placeWindow(new int[] {100, 100}, null);
       surf.setVisible(true);
       surf.startThread();
     }
     
     void draw() {
       background(255, 0, 0);
       fill(255);
       rect(10, 10, frameCount, 10);
       
       pg.beginDraw();
       pg.background(0);
       pg.endDraw();
     }
     
     void mousePressed(){
       println("mousePressed"); 
     }  

Available also in [this gist](https://gist.github.com/atduskgreg/23f4e40940a9b9645f20).

The error says "Could not run the sketch":

    handleDraw() called before finishing
    Could not run the sketch (Target VM failed to initialize).
    Make sure that you haven't set the maximum available memory too high.
    For more information, read revisions.txt and Help → Troubleshooting.
    
It happens at varying times after hitting "run" from immediately up to four or five seconds.

In the longer run, what I'd really like to do is create an API where I can define my own subclass of PApplet that's responsible for the second window. This will make it easy to handle events in that window. That's a pattern that existed with the old Frame-based method for making second windows ([ControlP5 has a great example](http://www.sojamo.de/libraries/controlP5/examples/extra/ControlP5frame/ControlP5frame.pde) of how useful this can be).

Maybe it should be a separate issue, but to achieve that goal I also need to be able to use this PSurface window with my own PApplet subclass. Currently, when I try to do that I get a NullPointerException in start():

    java.lang.NullPointerException
	    at processing.core.PApplet.start(PApplet.java:1291)
	    at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:298)

Code [here](https://gist.github.com/atduskgreg/c6c1eff8aaf99e30dac0).

Apologies for combining multiple questions into a single issue. I'm happy to pull this separate question about how to initialize a PApplet subclass out of if you think it doesn't belong here.

**Comment by codeanticode** [comment]
Actually, my comment on twitter was misleading, as you cannot use the secondary pg graphics inside the main thread. It needs its own PApplet to drive a separate rendering loop. Something like this works:

```java
PWindow win;

public void settings() {
  size(320, 240);
}

void setup() { 
  win = new PWindow();
}

void draw() {
  background(255, 0, 0);
  fill(255);
  rect(10, 10, frameCount, 10);
}

class PWindow extends PApplet {
  PWindow() {
    super();
    PApplet.runSketch(new String[] {this.getClass().getSimpleName()}, this);
  }

  void settings() {
    size(500, 200);
  }

  void setup() {
    background(150);
  }

  void draw() {
    ellipse(random(width), random(height), random(50), random(50));
  }

  void mousePressed() {
    println("mousePressed in secondary window");
  }
}

void mousePressed() {
  println("mousePressed in primary window");
}  
```

However, this is not a valid Processing issue, since multiple windows is not an officially supported feature. As a cool/useful hack is ok though. I hope the code above helps!

**Comment by df-unhuman** [comment]
Hi @codeanticode  what does one import to get at PWindow from Java?

**Comment by codeanticode** [comment]
Hi @df-unhuman, do you mean how to use the PWindow class from straight Java code, not Processing?

**Comment by df-unhuman** [comment]
@codeanticode yup

**Comment by df-unhuman** [comment]
OMG Ignore me :/
