### ISSUE TITLE
how do we select the correct capture device

### ISSUE THREAD

**Issue by FrankOcean11** [processing/processing#4161]
so i when to https://processing.org/reference/libraries/video/Capture_list_.html and copy and paste the code found there in processing, the code gave me this results
Available cameras:
name=Microsoft LifeCam Rear,size=640x360,fps=30
name=Microsoft LifeCam Rear,size=640x480,fps=30
name=Microsoft LifeCam Rear,size=424x240,fps=15
name=Microsoft LifeCam Rear,size=424x240,fps=30
name=Microsoft LifeCam Rear,size=320x240,fps=15
name=Microsoft LifeCam Rear,size=320x240,fps=30
name=Microsoft LifeCam Rear,size=320x180,fps=15
name=Microsoft LifeCam Rear,size=320x180,fps=30
name=Microsoft LifeCam Rear,size=160x120,fps=15
name=Microsoft LifeCam Rear,size=160x120,fps=30
name=Microsoft LifeCam Rear,size=1280x800,fps=5
name=Microsoft LifeCam Rear,size=1280x720,fps=30
name=Microsoft LifeCam Rear,size=960x544,fps=30
name=Microsoft LifeCam Rear,size=848x480,fps=30
name=Microsoft LifeCam Rear,size=960x544,fps=15
name=Microsoft LifeCam Rear,size=848x480,fps=30
name=Microsoft LifeCam Rear,size=640x360,fps=30
name=Microsoft LifeCam Rear,size=640x480,fps=30
name=Microsoft LifeCam Front,size=640x360,fps=30
name=Microsoft LifeCam Front,size=640x480,fps=30
name=Microsoft LifeCam Front,size=424x240,fps=15
name=Microsoft LifeCam Front,size=424x240,fps=30
name=Microsoft LifeCam Front,size=320x240,fps=15
name=Microsoft LifeCam Front,size=320x240,fps=30
name=Microsoft LifeCam Front,size=320x180,fps=15
name=Microsoft LifeCam Front,size=320x180,fps=30
name=Microsoft LifeCam Front,size=160x120,fps=15
name=Microsoft LifeCam Front,size=160x120,fps=30
name=Microsoft LifeCam Front,size=1280x800,fps=5
name=Microsoft LifeCam Front,size=1280x720,fps=30
name=Microsoft LifeCam Front,size=960x544,fps=30
name=Microsoft LifeCam Front,size=848x480,fps=30
name=Microsoft LifeCam Front,size=960x544,fps=15
name=Microsoft LifeCam Front,size=848x480,fps=30
name=Microsoft LifeCam Front,size=640x360,fps=30
name=Microsoft LifeCam Front,size=640x480,fps=30
name=USB2.0 Camera,size=640x480,fps=30
name=USB2.0 Camera,size=352x288,fps=30
name=USB2.0 Camera,size=320x240,fps=30
name=USB2.0 Camera,size=176x144,fps=30
name=USB2.0 Camera,size=160x120,fps=30

now given the above theres 3 cameras but the code does not tells you how to go about using any of the above given cameras or how many of this cameras can i use for my project application in the development with Arduino and processing, now i thought this was going to be address in the given https://processing.org/reference/libraries/video/Capture_list_.html but it did not so maybe i can get that pointer* ?

by the way the cam i want to use is USB2.0 Camera,size=640x480,fps=30 so how do i make this be the one in any processing sketch ?> how or where do i define this fact? 
how do i select the correct capture device?

**Comment by codeanticode** [comment]
This is not a valid bug report. Please ask questions about how to use Processing in the [forum](https://forum.processing.org/two/). The examples that accompany the video library should also help you figuring this out.

**Comment by FrankOcean11** [comment]
the example supposed to be a empty ready to use code, this code here is the example used and the only thing i get is the actual result from the last person who updated this

**Comment by codeanticode** [comment]
Hi, [here you have a full example](https://processing.org/reference/libraries/video/Capture.html) that shows you how to select the camera using the output of Capture.list()

**Comment by FrankOcean11** [comment]
well i have this come up on the  Capture.list() and that name is USB2.0 Camera,size=640x480,fps=30 so when i use that full name in the constructor i get errors if i use this USB2.0 Camera,640, 480, 30 in here  cam = new Capture(this, cameras[0]); i even change the instance of the name Capture cam; to say Capture USB2.0 Camera; and change anything named 'cam' to say 'USB2.0 Camera' and i keep getting token unexpected what is it im doing wrong?

**Comment by FrankOcean11** [comment]
can you please help me use this camera USB2.0 Camera,size=640x480,fps=30  in this sketch found in the examples of opencv_processing folder ? i will learn from how you manage to incorporate the USB2.0 Camera,size=640x480,fps=30 in to the face detection sketch cuz as in right now im not even getting the regular cam to pick up the live feed, rather i get a picture stored in the data folder inside that face detection folder in opencv_processing and i cannot get my face to show up and if i delete that data folder so it stop picking that photo ill just endup with a error.

import gab.opencv.*;
import java.awt.Rectangle;

OpenCV opencv;
Rectangle[] faces;

void setup() {
  opencv = new OpenCV(this, "test.jpg");
  size(opencv.width, opencv.height);

  opencv.loadCascade(OpenCV.CASCADE_FRONTALFACE);  
  faces = opencv.detect();
}

void draw() {
  image(opencv.getInput(), 0, 0);

  noFill();
  stroke(0, 255, 0);
  strokeWeight(3);
  for (int i = 0; i < faces.length; i++) {
    rect(faces[i].x, faces[i].y, faces[i].width, faces[i].height);
  }
}
