### ISSUE TITLE
unable to upgrade

### ISSUE THREAD

**Issue by FrankOcean11** [processing/processing#4162]
im trying to install the newest download and theirs like no way im being allowed to uninstall or deleted old folders or program it self not from uninstall under control panel, not from program files x86 not from search on C:/ this happened to me before with Arduino tho i forgot how i when about that back then

**Comment by alignedleft** [comment]
This is a great questions for: forum.processing.org

**Comment by FrankOcean11** [comment]
thanks you but i figured it out, but since im here i did come across another problem using the processing for opencv

**Comment by FrankOcean11** [comment]
// The camera can be initialized directly using an element
// from the array returned by list():
cam = new Capture(this, cameras[0]);
// Or, the settings can be defined based on the text in the list
//cam = new Capture(this, 640, 480, "Built-in iSight", 30); 

now my cam name i see in the list numbered 18 so in this code i change from 0 "default pc cam" to #18 which is the cam i want to use "name=USB2.0 Camera,size=640x480,fps=30" now IN this sketch i can see that is easy for me to use a easy swap in number to select my capture device BUT NOW if we exit this example file "gettingstartedcapture" and enter the other one i mentioned earlier "backgroundsubtraction" and you will see quick i DO NOT have the easy option of just swapping number around to select that capture device number 18 or known as name=USB2.0 Camera,size=640x480,fps=30 SO WHAT DO I DO? 

 the Main example sketch i was trying to use the one in opencv_processing folder the one called face_detection when i open that example and i run it i get greg borenstein face in the example but i cant stop it from doing that when all i want the example to do is detect my face using my camera "name=USB2.0 Camera,size=640x480,fps=30" but i cant swap i cant exchange im just about lost

can i please get a pointer ?

**Comment by alignedleft** [comment]
Please ask these kinds of questions in the forum. This area is for reporting bugs with the software.
