### ISSUE TITLE
Contribution Manager: Provide fallback URL outside of Github

### ISSUE THREAD

**Issue by gohai** [processing/processing#4163]
At least certain ISPs inside China seem to be blocking access to Github, which is what the Contribution Manager uses to get its sources.

**Comment by Akarshit** [comment]
Currently http://download.processing.org/contribs URL is used to fetch information about the contributions in the Contribution Manager, though many contribution themselves are hosted on Github.

**Comment by gohai** [comment]
Hm, perhaps I am mistaken then. I heard from a friend teaching in China that he's unable to download Processing or use the Contribution Manager.

**Comment by benfry** [comment]
That URL redirects to Github, so yeah, we need a mirror.

**Comment by gohai** [comment]
I am in Shenzhen right now, using filtered hotel WiFi - and currently github.com and the Contribution Manager seems to work, so perhaps the Chinese authorities came to the conclusion that GitHub was too big a fish to ban...

(Closing this issue for now)
