### ISSUE TITLE
"camera()" Acts Differently on Processing 3 when in P3D Mode

### ISSUE THREAD

**Issue by DavidB-TPW** [processing/processing#4164]
I have a sketch that I wrote in Processing 2 that utilizes P3D. In order for things to be displayed properly in the app, I used the camera() method. Since upgrading to Processing 3, all of my apps that use P3D now show what used to be the horizontal and vertical midpoint of the sketch as the point at the bottom left-hand corner of the sketch.

Previously, I believed this was deliberate, but the Processing 3 reference does not show any difference from the Processing 2 reference on the camera() method.

If my explanation provided is unclear, here's an example of what I am trying to say.

Suppose this is my sketch written and compiled with Processing 2:

![dkg5zdzqdi8e](https://cloud.githubusercontent.com/assets/13968410/11326863/d7f838f0-9142-11e5-92ea-88fcedc89f6c.png)

If I take the same sketch and run in on Processing 3 without making any changes, this is how it would look:

![a7oofkpflzrm](https://cloud.githubusercontent.com/assets/13968410/11326871/ffbd02bc-9142-11e5-894d-cc93e9981686.png)

The red lines to show the quadrants on the second image were left in place to show each quadrant. The sketch would more accurately look like this:

![ffbd02bc-9142-11e5-894d-cc93e9981686](https://cloud.githubusercontent.com/assets/13968410/11326903/b2be7990-9143-11e5-9fef-1bc4fdb8de2f.png)

**Comment by codeanticode** [comment]
I'm not aware of any difference in the way camera works between 2 and 3. Are you using orthographic projection? Can you post a minimal code that reproduces the issue you just described?

**Comment by DavidB-TPW** [comment]
Yes, the sketch uses orthographic projection. Unfortunately, I do not have time to put together a full-size sketch of the issue at the moment, but I will provide you with the two lines that I use to declare the orthographic projection and camera positioning:

    ortho(0, width, 0, height, -100, 100);
    camera(width/2, height/2, 10, width/2, height/2, 0, 0, 0.1, 0);

**Comment by codeanticode** [comment]
Ok, I see. The reason for the difference is the change in the way the arguments of the ortho() are interpreted, so that it is more consistent with the original glOrtho() function. See [the reference](https://processing.org/reference/ortho_.html). You should use:

```java
ortho(-width/2, width/2, -height/2, height/2, -100, 100);
```

**Comment by DavidB-TPW** [comment]
@codeanticode Thank you. I cannot figure out how to manipulate the values of ortho from Processing 2 to match in 3 despite reviewing the reference.
