### ISSUE TITLE
why am i getting errors when i switch variables?

### ISSUE THREAD

**Issue by FrankOcean11** [processing/processing#4165]
i try to ask this question but i got my conversation closed on me

**Comment by alignedleft** [comment]
@FrankOcean11 *Please* ask these questions in the forum. This area is not for questions. This area is for reporting bugs in the software. By posting questions here you are wasting the time of the developers who all volunteer their time to make Processing possible.

**Comment by FrankOcean11** [comment]
make it possible so that it can be used! and as in now all i been getting is errors so why go to a forum and talk with non professionals like this developers you speak of when my question should have a easy response such as "do this"  BY you sending me here or there after i reposted my errors or bugs your wasting my time and all cuz i wanted to use something that YOU GUYS the developers made to be used

**Comment by alignedleft** [comment]
@FrankOcean11 If you are having trouble with the forum, you can report issues here: https://github.com/processing/processing-forum/issues

**Comment by FrankOcean11** [comment]
well yes but at the end of the day im just going in circles when im already
speaking to a developer who should know the answer to my question, and by
the way i register to ASK questions on that link you submitted and im
unable to ak anything and now where going on a whole hour and a half with
no resolution when im speaking to someone who can help me


Frank's Desig'Nature

"Designed Signature Inspired by Nature"
