### ISSUE TITLE
Exported Mac Application Won't Work With Sound Library

### ISSUE THREAD

**Issue by MSpill** [processing/processing#4166]
I have found that with my Processing 3 b4 sketch that has the sound library imported, the exported Mac application doesn't work.  My sketch will run perfectly inside of Processing, but once exported, the Mac app just opens and shows a blank screen.  I have all of my files in my program's data folder.  I created the sound files above the setup function and defined which sounds they would have inside the setup function.  I have found by commenting the code that the app will run fine when the sound library is imported, but won't if there are actual sound files that need to be played.  I opened the application's contents and even found the data folder inside its contents in Contents/Java/data.  Even though it has the data folder contained in its contents, the application seems to be having trouble finding the files defined by the code and just won't run.  For clarity, the part that causes the application to not run are these lines:

back = new SoundFile (this, "Music.mp3");
Drop = new SoundFile (this, "Drop0.mp3");
Drop1 = new SoundFile (this, "Drop1.mp3");
Drop2 = new SoundFile (this, "Drop2.mp3");
Drop3 = new SoundFile (this, "Drop3.mp3");

 (even though the folder with these files is contained in the application and the sketch and is titled "data").

**Comment by carlguoshanghai** [comment]
Same here. I also have the same problem. It works perfectly fine when running using processing, but it just won't work when I export it as application. (only background is shown) Is your problem fixed yet?

**Comment by REAS** [comment]
I didn't catch this when it was first posted in November. Please file this error in the processing/processing-sound repo.
