### ISSUE TITLE
Add readBytes(count) function to network library (and serial)

### ISSUE THREAD

**Issue by profany** [processing/processing#4167]
Can the DEVOLPER'S, PLZZZ :D, add a basic function in the NETWORK library, of reading ONLY the number of bytes i tell read, something like:

Client c = new Client(this,"127.0.0.1",25565);

while(true){
    if(c.available() > 0){
       byte[] a = c.readBytes(50);   <<<<---------- '50' represents thenumber of bytes to read
       byte[] b = c.readChars(20);
        ///////////////// or even a function that let u read from the buffer , but doesnt take it from the buffer.
    }
}

ty for reading
i hope not been to mutch a pain in the ass :D

**Comment by kfeuz** [comment]
I have implemented this for both the network and serial libraries.  I have tested the network version and it works well but I have not been able to test the serial library.  I'll submit two separate PRs, one for each library.

**Comment by benfry** [comment]
Now merged for 3.1. These didn't exist in the past because they're a good way to have beginners lock up their sketches while IO blocks for enough data, but hey, let's not let that get in the way of a useful feature.
