### ISSUE TITLE
.PDF and .NET libraries in Android mode

### ISSUE THREAD

**Issue by Degeerdoethetweer** [processing/processing#4172]
I'm trying to run a program originally made in java mode in android mode.
Both the .net and .pdf libraries don't seem to be working and give the following error when compiling:

----------
1. ERROR in C:\Users\AppData\Local\Temp\android7291393924322010817sketch\src\processing\test\neurosky_app_v7\Neurosky_app_v7.java (at line 8)
	import processing.net.*; 
	       ^^^^^^^^^^^^^^
The import processing.net cannot be resolved
----------
2. ERROR in C:\Users\AppData\Local\Temp\android7291393924322010817sketch\src\processing\test\neurosky_app_v7\Neurosky_app_v7.java (at line 9)
	import processing.pdf.*; 
	       ^^^^^^^^^^^^^^
The import processing.pdf cannot be resolved

Is there a way to get these to get these libraries to work?

**Comment by GKFX** [comment]
This is a question for http://forum.processing.org. This is the bug tracker for the mainstream Processing project. If you ever think that Processing for Android is *broken*, go to https://github.com/processing/processing-android/issues. But you just need some help, so please go to the forum.

**Comment by GKFX** [comment]
And please click "Close" beneath the comment box!

**Comment by Degeerdoethetweer** [comment]
Reposted the issue here:
https://github.com/processing/processing-android/issues/177
