### ISSUE TITLE
createShape(GROUP) + textured child + non-textured child = P3D render problems

### ISSUE THREAD

**Issue by mkmori** [processing/processing#4176]
P3D: When texture is applied to one child in a PShape group, a second, non-textured child does not render as expected, (i.e., fill() does not work: In my case, depending on fill() values, it renders black, very dark...or a shade of one of the texture colors...?!)

Child shapes render as expected when drawn separately. (Issue disqualified for "Workaround too easy"???) Stroke color renders as expected either way.

Uv's are provided for the textured child and not for the non-textured child. Providing uv's for the non-textured child faces seems to help render a very dark version of something corresponding to the expected fill() value....

Winding is CCW for both child shapes; child shapes are of type TRIANGLES; textureMode(IMAGE); order of addChild() does not seem to matter; default lights; etc.

FWIW!

Processing 3.0.1, Win10

**Comment by codeanticode** [comment]
I'm able to reproduce this issue, and currently working on it. Thanks for letting us know!

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing/commit/7e0a1d6dd5851d1c8f1c259bc36d710b24c953c4

**Comment by mkmori** [comment]
Cool!
