### ISSUE TITLE
Resizable screen no good with noLoop() for Processing v3xx

### ISSUE THREAD

**Issue by jimcd** [processing/processing#4179]
In the "noLoop()" reference for Processing v3 - the last paragraph of the "description" is as follows:- 

Description
Note that if the sketch is resized, redraw() will be called to update the sketch, even after noLoop() has been specified. Otherwise, the sketch would enter an odd state until loop() was called. 

The aforementioned paragraph is correct for v2xx but is incorrect for v3xx because for v3xx the redraw() is NOT called - in fact this makes the use of surface.setResizable(true); or frame.setResizable(true); useless for v3xx if one wishes to use the loop()/noLoop() pair.

**Comment by jimcd** [comment]
The following simple program will show the problem. Run it with v2.2.1 and v3.0.1 and resize the screen for both -  v3.0.1 does not update the width and height values for the display.

void setup(){
  size(300,300);
  frame.setResizable(true);
  noLoop();
}
void draw(){
  line(0,150,300,300);
  println(width,height);  
}
void mousePressed(){
  println(width,height);
}

**Comment by jimcd** [comment]
2 Dec 2015
The following simple program demonstrates a workaround for v3.0.1 (will also run OK for v2.2.1).

int pWidth,pHeight;
boolean firstTimeThroughDraw = true;

void setup(){
  size(300,300);
  frame.setResizable(true);  
  pWidth = width;
  pHeight = height;
}

void draw(){
  if(firstTimeThroughDraw){
   myDraw();
   firstTimeThroughDraw = false;
  }
  if((pWidth != width) || (pHeight != height)){
    pWidth = width;
    pHeight = height;
    myDraw();
  }
}

void myDraw(){
  //Place all you normal "draw()" code here - not in "draw()"
  line(0,150,300,300);
  //debug
  println("myDraw()",width,height);
}

void mousePressed(){
  //debug
  println("mousePressed",width,height);
}

**Comment by jimcd** [comment]
The following work-around uses a thread to check for any changes in width and height variables and if there are, then calls redraw()


boolean threadCanRun = true;
int pWidth, pHeight;


void setup(){
  size(300,300);
  frame.setResizable(true);
  pWidth = width;
  pHeight = height;
  thread("checkForResize");
  noLoop();
}

void draw(){
  line(0,150,300,300); 
}

void mousePressed(){
  println("mousePressed",width,height);
}

void checkForResize(){
  try {
    println("ThreadStart");    
    while(true){
      //note: the following sleep delay is required
      //otherwise the thread does not seem to notice
      //any width and height changes.    
      Thread.sleep(10); // 10ms      
      if(threadCanRun == false){
        println("ThreadFinished");
        return;
      }      
      if((pWidth != width) || (pHeight != height)){
        pWidth = width;
        pHeight = height;
        //println("ThreadRedraw",width,height);  //debug    
        redraw();      
      }
    }
  } catch (Exception e) {};
}

**Comment by Niels-NTG** [comment]
Thank you @jimcd, this was exactly what I was looking for. Processing really needs a standard `windowResized()` method that get's triggered automatically whenever a window resize event is detected. Functionally identical to [what p5 does already](http://p5js.org/reference/#/p5/windowResized).
