### ISSUE TITLE
Autoformat does not work correctly with enums

### ISSUE THREAD

**Issue by JobLeonard** [processing/processing#4185]
![image](https://cloud.githubusercontent.com/assets/259840/11590074/03e574c4-9a8e-11e5-97c5-b1ecc81d7321.png)

Compiles just fine, so I just put them in a separate tab for now to not mess up the formatting of the rest.

**Comment by GKFX** [comment]
I'm familiar with the autoformatter, so I'll deal with this.

**Comment by benfry** [comment]
Incorporated fix from @GKFX for 3.0.2.
