### ISSUE TITLE
Processing 3 does not start correctly

### ISSUE THREAD

**Issue by brentcarpenter** [processing/processing#4187]
Processing 3.0.1 and Processing 2.2.1 fails to start correctly and yields the chain of errors shown in the attached file.  These seem to be related to Java. 

![processing errors](https://cloud.githubusercontent.com/assets/16160061/11604595/fe18dbf8-9aab-11e5-9b63-72334eb1e6dc.PNG)

**Comment by djokjulapfe** [comment]
Have you tried running Processing as admin?

**Comment by brentcarpenter** [comment]
Thanks for the response.  I've tried running both versions as administrator and get the same error.  I've also uninstalled both versions and reinstalled 3.0.1 but I get the same error as before.   

Brent

**Comment by GKFX** [comment]
http://www.sevenforums.com/general-discussion/251856-cannot-create-file-c-user-appdata-roaming-access-denied-2.html?s=6b8efea0107b3611e407eda84994cebf suggests that you should delete preferences.txt. (Its path is in the error message you gave.) This will reset your settings; you can keep a copy if you want to restore them later.
The existence of this bug over multiple apps suggests that it's a Windows bug, not one in Java or Processing.

**Comment by brentcarpenter** [comment]
George
Thanks for the advice.  I did as suggested and it seems to have corrected the problem.  Both my older version and 3.0.1 are up and running.  
Appreciate it.  
Brent

**Comment by GKFX** [comment]
@brentcarpenter Could you close this issue? Thanks.
