### ISSUE TITLE
strokeWeight works differently in normal, P2D and P3D mode for point() function

### ISSUE THREAD

**Issue by ynaoto** [processing/processing#4188]
Hello,

strokeWeight with scale doesn't make any effect to point() in P3D mode?
I wrote the following 3 sketches for testing with Processing 3.0.1 for Mac.

    void setup() {
      size(100, 100);
      scale(10);
      strokeWeight(1);
      line(0, 0, 3, 3);
      point(4, 4);
    }

<img width="128" alt="normal" src="https://cloud.githubusercontent.com/assets/1597357/11612852/765e90ba-9c4d-11e5-9da1-6cc6ee6595e1.png">
The point is drawn in same size as line.

In P2D mode:

    void setup() {
      size(100, 100, P2D);
      scale(10);
      strokeWeight(1);
      line(0, 0, 3, 3);
      point(4, 4);
    }

<img width="100" alt="p2d" src="https://cloud.githubusercontent.com/assets/1597357/11612863/09f1f70e-9c4e-11e5-98d3-287db3fc0c13.png">
Line cap is slightly different from normal mode, but point size is fine.

P3D mode:

    void setup() {
      size(100, 100, P2D);
      scale(10);
      strokeWeight(1);
      line(0, 0, 3, 3);
      point(4, 4);
    }

<img width="100" alt="p3d" src="https://cloud.githubusercontent.com/assets/1597357/11612873/7252eee8-9c4e-11e5-8a09-c146b047801e.png">

The point size is very small.

Is this expected result?

Thanks,

**Comment by djokjulapfe** [comment]
You've put the same code for P2D and P3D. Pleas put the P3D code.

**Comment by codeanticode** [comment]
@ynaoto P3D does not apply line caps, but the point should at least be a large square. I will look into it. Thanks for the report!
