### ISSUE TITLE
An error occurred during startup

### ISSUE THREAD

**Issue by devartstudio** [processing/processing#4189]
I have an error opening processing, see attachment.

Many thanks

![immagine](https://cloud.githubusercontent.com/assets/890926/11613937/bca11aae-9c32-11e5-8926-8f589d9bede9.png)

**Comment by pr1est0r** [comment]
I have the same error with Processing 2.2.1.
1.5.1 doesn't work anymore either. 3.0.1 does work, but my sketches don't with Processing 3.
Suddenly the error just appeared, I don't know what has changed in my system.

**Comment by maxbul** [comment]
That helped to me

https://github.com/processing/processing/wiki/Troubleshooting
"Try moving or renaming your Sketchbook."

(Problem was in "contributions" file)

**Comment by tomschofield** [comment]
I receive the same error on processing 2.2.1 processing 3 opens fine. I've updated java, binned the preferences.txt and renamed the sketch folder. No change. I'm running OSX 0.11.2. On a high spec retina MBP. Any thoughts?
![screen shot 2016-01-12 at 10 27 55](https://cloud.githubusercontent.com/assets/897687/12261141/2a23ae6a-b917-11e5-9874-f7474b009de9.png)

**Comment by maxbul** [comment]
Deletion of "preferences.txt" does'nt helped to me, but when I deleted a "contributions.txt" - everything is fine now.

I tryied to start Processing 3 - that caused the same error message (I use the  Win32 version)

**Comment by tomschofield** [comment]
Ah, thank you Maxbul, confirmed here. Deleting contributions.txt in ~/Library/Processing solved the issue.

**Comment by pr1est0r** [comment]
You saved my life! On Windoze, removing / renaming the Processing folder in C:\Users\<*>\AppData\Roaming did the job. That's where contributions.txt is...

**Comment by benfry** [comment]
Nothing we can fix here; closing.

**Comment by chennatrinath** [comment]
> I have an error opening processing, see attachment.
> 
> Many thanks
> 
> ![immagine](https://cloud.githubusercontent.com/assets/890926/11613937/bca11aae-9c32-11e5-8926-8f589d9bede9.png)

same problem occurred what I have to do to resolve it.

**Comment by chennatrinath** [comment]
please help me...... :(
