### ISSUE TITLE
[P3D] Drawing a sphere with shape() first changes sphereDetail from default.

### ISSUE THREAD

**Issue by RectangleWorld** [processing/processing#4192]
I created a 3D PShape with `createShape(SPHERE)`, then later tried to display this PShape and a second sphere drawn simply with `sphere()` and the latter came out with a sphere detail changed to 4 points per latitude instead of the usual default 30. This behavior depends on drawing order.

The following code:
```Java
void setup() {
  size(800,600,P3D);
  
  noStroke();
  PShape shapeSphere = createShape(SPHERE, 100);
  
  lights();
  
  background(0xFF000000);
  
  //sphere with sphere function
  pushMatrix();
  translate(600, 300);
  sphere(100);
  popMatrix();
  
  //sphere from prepared PShape
  pushMatrix();
  translate(200, 300);
  shape(shapeSphere);
  popMatrix();
}
```

creates a fine display of two spheres:

![screencap0](https://cloud.githubusercontent.com/assets/1840810/11621018/fb7c0b14-9c85-11e5-85c8-546098f7992a.jpg)

But if we reverse the drawing order:

```Java
void setup() {
  size(800,600,P3D);
  
  noStroke();
  PShape shapeSphere = createShape(SPHERE, 100);
  
  lights();
  
  background(0xFF000000);
  
  //sphere from prepared PShape
  pushMatrix();
  translate(200, 300);
  shape(shapeSphere);
  popMatrix();
  
  //sphere with sphere function
  pushMatrix();
  translate(600, 300);
  sphere(100);
  popMatrix();
}
```

then the second sphere is drawn with a reduced sphere detail:

![screencap1](https://cloud.githubusercontent.com/assets/1840810/11621045/39e95456-9c86-11e5-9979-297e1c9c930e.jpg)

Putting in `sphereDetail(30)` prior to drawing the second sphere remedies the problem, but `shape()` should probably not be changing this default. Note that it is the display of the PShape with `shape()` that seems to cause the error, not the creation of the PShape with `createShape()`.

You can use the following code with PeasyCam to get a better look:

```Java
import peasy.*;

PeasyCam camera;
PShape shapeSphere;

void setup() {
  size(800,600,P3D);
  
  camera = new PeasyCam(this, 400, 300, 0, 500);
  
  fill(0xFFFF0000);
  shapeSphere = createShape(SPHERE, 100);  
}

void draw() {
  lights();
  
  background(0xFF000000);
  
  //sphere from prepared PShape
  pushMatrix();
  translate(200,300);
  shape(shapeSphere);
  popMatrix();
  
  //sphere with sphere function
  stroke(0);
  fill(0xFF0080FF);
  //sphereDetail(30);
  pushMatrix();
  translate(600, 300);
  sphere(100);
  popMatrix();
}
```

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing/commit/4a247a3264d7d3f1f2dffc8b2bd826a6bda26888
