### ISSUE TITLE
Processing 3.0.1 could not detect android sdk 2.2.1

### ISSUE THREAD

**Issue by schadaram453** [processing/processing#4193]
I have installed all the sdks from android sdk manager from 2.2.1 to 4.4.2. But processing could detect only versions above 4.0.4. Why? Is there anything I did wrong?
![processing 3 0 1](https://cloud.githubusercontent.com/assets/16203734/11650328/1f260ffa-9dae-11e5-82ee-5af44ccad421.jpg)

**Comment by codeanticode** [comment]
Please report android issues in the [processing-android](https://github.com/processing/processing-android/issues) repo. Reopened [here](https://github.com/processing/processing-android/issues/181)
