### ISSUE TITLE
Processing 3.0 incompatible Windows 10 ?

### ISSUE THREAD

**Issue by StarWar2015** [processing/processing#4194]
Bonjour,
  Je possede un ordinateur HP 355 G2 equipe de AMD Radeon R5 M200 serie sous Windows 10 "1511". Au lancement de processing une fenetre "I3" s'affiche pendant 1 seconde environ puis se ferme sans lancer Processing? Y-a-t-il des incompatibilites ou des drivers a telecherger?
Merci
Cordialement
JC Sarhy

**Comment by REAS** [comment]
We can only support Issues in English, please translate or machine translate before posting.
