### ISSUE TITLE
Custom menu bar is not displaying with v3.0.1

### ISSUE THREAD

**Issue by kritixilithos** [processing/processing#4197]
Basically, I tried to create a custom menu bar in processing using eclipse as my IDE, but it is not displaying (the rest of the code is working, however). My code is on [stackoverflow](http://stackoverflow.com/q/34110218/4936954). I have tried many things, but none come to avail. My custom menu bar is a "File" menu.

I am posting this because I suspect there may be something "wrong" with Processing that disabled the menu bar. I have tried `System.setProperty` as Apple suggests (I am using a mac), but it is still not working.

**Comment by alignedleft** [comment]
@kritixilithos Is there a reason you are using 3.0b6? Why not use 3.0.1, the latest version?

**Comment by kritixilithos** [comment]
@alignedleft I am now using version 3.0.1 and it *is* still not working.

**Comment by benfry** [comment]
This isn't something that was ever supported or documented. It's still sort of possible but will only work with the default renderer, and requires digging into how `PSurface` works to make it happen. But that's a better question for the forum.

**Comment by kritixilithos** [comment]
@benfry Thank you for your help.
