### ISSUE TITLE
Call endRecord() on a PGraphicsPDF object?

### ISSUE THREAD

**Issue by neilpanchal** [processing/processing#4201]
Hello all,

I've got a sketch that does not refresh the background. As I draw in the sketch, I want to be able to create PDFs along the way. I've tried all the options suggested in the PDFExport documentation but none of the PDFExport functions work for capturing each animated frame (with recording that starts in `setup()`). I can get each frame in PDF, but not the accumulated graphics from previous frames.

Therefore, I tried to do this. Basically, I have a loop that creates an array of `PGraphicsPDF[]` as follows:

```Processing
PGraphicsPDF[] pdfs = new PGraphicsPDF[num];
for (int i = 0; i < num; i++) {
    pdfs[i] = (PGraphicsPDF) createGraphics(width, height, PDF, i + ".pdf");
    beginRecord(pdfs[i]);
}
``` 

Now, in the loop above, I can start recording each PDF file by calling
```Processing
beginRecord(PGraphicsPDF[i]);
```
All good so far. The problem is that there is no way to call
```Processing
endRecord(PGraphicsPDF[i]);
```

So, when I call `endRecord()`, all recordings stop and just one file is saved. How best to achieve what I am trying to do?

**Comment by benfry** [comment]
Please use the forum for questions; this is for bug reports in the software.
