### ISSUE TITLE
issue processing give the list of serial port when i try to communicate with arduino its error message,com1 port is busy not available 

### ISSUE THREAD

**Issue by muhammadtahir** [processing/processing#4205]
my arduino uno is also at com port1 and its working fine with arduni,but in processing error port not available busy

**Comment by gohai** [comment]
@muhammadtahir Hi, can you tell me more about your setup? Which operating system are you running? Have you closed the Arduino application when you try to run the Processing sketch that fails?

**Comment by gohai** [comment]
@muhammadtahir Need more info to look into this. Closing for now.
