### ISSUE TITLE
surface.setSize is randomly ignored when called from external editor

### ISSUE THREAD

**Issue by mikechambers** [processing/processing#4208]
Processing 3.0.1
Windows 10
I am using an external editor to call and launch processing. I could not reproduce when using the processing editor.

Test code:

```
void settings() {
	size(100, 400, FX2D);
}

void setup() {
	surface.setResizable(true);
	surface.setSize(640, 640);
}
```

Compile and launch example multiple times. Sometimes window size will be 100 x 400, sometimes 640 x 640.

**Comment by benfry** [comment]
Might be a problem with the version of Java you're using when running outside the PDE. Unfortunately, when outside the PDE, you're on your own with this sort of thing.
