### ISSUE TITLE
width / height does not accurately report width after call to surface.setSize

### ISSUE THREAD

**Issue by mikechambers** [processing/processing#4209]
Processing 3.0.1
Windows 10

Code Example:

```
void settings() {
	size(100, 400, FX2D);
}

void setup() {
	surface.setResizable(true);
	surface.setSize(640, 640);

	System.out.println(width);
	System.out.println("End Setup");
}

void draw() {
	System.out.println(width);
}
```

Output:

```
120
End Setup
120
120
120
640
640
640
640
```

Notice that width does not return correct value after call to setSize, and doesn't seem to report it correctly until 3 frames have passed.

This can lead to very difficult to find bugs, and makes it complicated and unreliable to reference width / height within the draw function.

**Comment by iamutkarshtiwari** [comment]
@alignedleft I would like to get my hands on it. How would you suggest me to proceed?

**Comment by iamutkarshtiwari** [comment]
@JakubValtar  This is what I was talking about. ;)

**Comment by alignedleft** [comment]
@iamutkarshtiwari Not sure why you are asking me, but I recommend first verifying with the core dev team that this is an issue before you spend time trying to solve it. Following that, I believe you can make a pull request with your fix.

**Comment by iamutkarshtiwari** [comment]
@alignedleft  I am sorry. I am new here. How to connect with the core dev team?

**Comment by alignedleft** [comment]
@iamutkarshtiwari This is the right place! Posting an issue or submitting a PR is the right way to go about it. But @benfry or @codeanticode are probably the right people to review this issue, not me.

**Comment by benfry** [comment]
It's not something we can fix. The actions of `surface.setSize()` are handled by the OS, so we're at its mercy (and that of JavaFX) when that happens. It won't be instantaneous, and happens separately from the drawing thread, so you may have a couple cycles before it changes.
