### ISSUE TITLE
dead link in wiki / FAQ

### ISSUE THREAD

**Issue by gViro** [processing/processing#4215]
In the section titled,  *"Where does this project come from? Is this DBN?"* , the link to *Design By Numbers* ( http://dbn.media.mit.edu/ ) returns a file-not-found error in Firefox, Safari and Chrome ( I didn't try Explorer / Opera ). 

There may be a suitable replacement web page here: https://web.archive.org/web/20030923172031/http://dbn.media.mit.edu/

**Comment by REAS** [comment]
Thank you, good catch. It's fixed now with your link suggestion.
