### ISSUE TITLE
processing to arduino serial communication error 

### ISSUE THREAD

**Issue by muhammadtahir** [processing/processing#4216]
void draw(){
myPort=new Serial(this,"COM1",9600);
}
this chunk of code give error (error opening serial port com 1 port not found)
same this code when i run in loop() method it not give me error 
void loop(){
myPort=new Serial(this,"COM1",9600);
}

**Comment by gohai** [comment]
@muhammadtahir `loop` is a function used in Arduino, but it refers to something different in Processing. For the other issue, could you please reply to my comments in #4205?
