### ISSUE TITLE
PGraphics.isGL() threw out a NullPointerException on Eclipse

### ISSUE THREAD

**Issue by horsehour** [processing/processing#4217]
I am using the latest version Processing on Eclipse, and trying to run the example as indicated at:
https://processing.org/reference/libraries/pdf/, 

```processing
import processing.core.PApplet;

public class PDFProcessing extends PApplet{
public void setting() {
  size(400, 400);
  beginRecord(PDF, "everything.pdf");
}

public void draw() {
  // Be sure not to call background, otherwise your file
  // will just accumulate lots of mess, only to become invisible
  // Draw something good here
  line(mouseX, mouseY, width/2, height/2);
}

public void keyPressed() {
  if (key == 'q') {
    endRecord();
    exit();
  }
}
```

It did not work, and threw out a NullPointerException 
        at processing.core.PApplet.makeGraphics(PApplet.java:2068)
	at processing.core.PApplet.createGraphics(PApplet.java:2040)
	at processing.core.PApplet.beginRecord(PApplet.java:10023)

I have downloaded all the source code, therefore I could debugged it line by line. I found that the method isGL() of PGraphics always return false. However, the method has be called by the method PAppet.makeGraphics():
```java
if (!primary && <b>!g.isGL()</b>) {
			if (renderer.equals(P2D)) {
				throw new RuntimeException(
				        "createGraphics() with P2D requires size() to use P2D or P3D");
			} else if (renderer.equals(P3D)) {
				throw new RuntimeException("createGraphics() with P3D or OPENGL requires size() to use P2D or P3D");
                       }
}
```

Here, PApplet.g==null in setting(), therefore the statement could be changed to 
```java
if (!primary){
   //block as above
}
```

It's my first post on github. Hope that it's helpful to men who are using Processing on Eclipse. 

Happy new year, guys~

**Comment by JakubValtar** [comment]
Hi @horsehour, `settings()` method is not a good place to start recording, put your `beginRecord()` into `setup()`, like this:
```processing
import processing.core.PApplet;

public class PDFProcessing extends PApplet{
  public void setting() {
    size(400, 400);
  }

  public void setup() {
    beginRecord(PDF, "everything.pdf");
  }

  public void draw() {
    // Be sure not to call background, otherwise your file
    // will just accumulate lots of mess, only to become invisible
    // Draw something good here
    line(mouseX, mouseY, width/2, height/2);
  }

  public void keyPressed() {
    if (key == 'q') {
      endRecord();
      exit();
    }
  }
}
```

Please read [Changes in 3.0](https://github.com/processing/processing/wiki/Changes-in-3.0#new) to learn what to put into `settings()`:
> A new settings() method that is called behind the scenes. Most users will never notice this, but if you're using Processing without its preprocessor (i.e. from Eclipse or a similar development environment), then put any calls to size(), fullScreen(), smooth(), noSmooth(), and pixelDensity() into that method. More information can be found in the reference. Only users who are in other development environments should use settings(). It shouldn't be used for any other purpose.

**Comment by horsehour** [comment]
thank you.

**Comment by horsehour** [comment]
Sorry, I noticed that one method was wrongly spelled. It should be settings() rather than setting().

**Comment by JakubValtar** [comment]
Ah thanks, didn't notice.
