### ISSUE TITLE
Symlinks in sketchbook window?

### ISSUE THREAD

**Issue by isohedral** [processing/processing#4223]
For teaching purposes, I have my sketchbook set up in a funny way. The sketches related to the course are in their own directory, and I have a symlink from my main sketchbook directory over to that one. This worked fine in Processing 2.2.1 -- the hierarchical Sketchbook menu would follow the symlink transparently. But it seems as if the "Sketchbook..." window in Processing 3 doesn't.  As a result, I can't easily navigate to sketches that I plan to use as examples in lectures. Would it be possible to have the Sketchbook window recognize and follow symlinks?

**Comment by Akarshit** [comment]
@isohedral I set up my sketchbook in a similar way, and the symlinks were recognized.
I have the following directory structure
Sketchbook location -> /home/akarshit/sketchbook
This directory contains a symlink by the name `link`
The link points to a directory that has the sketch abc
Now the `Skaetchboook...` gives me the following tree  
sketchbook
 >  link
  >>    abc
Is there something i am missing ?

**Comment by isohedral** [comment]
@Akarshit You're absolutely right.  I tried it again this morning, and it seemed to work. Either there was some kind of spurious bug last time, or I hadn't set things up the way I thought I had. Not sure. Anyway, thanks.

**Comment by aengelke** [comment]
You can click the Close button below the comment box.
