### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by amonwong** [processing/processing#4233]
Good morning all, 

I am trying to figure out https://www.youtube.com/watch?v=RDrHHsez3nU this code for Processing 3.0.

int allxpoints[] = new int[50];
int allypoints[] = new int[50];

//boolean fullScreen() {
//return true;
//}

void setup() {
  fullScreen(P3D);
  background (249);
  stroke(21);
  smooth();
}
void draw () {
 // delay(30);
  background(222);
  for (int n = 0; n<50; n++) {
    allxpoints[n] = int(random(50, width-50));
    allypoints[n] = int(random(50, height-50));
    for (int j = 0; j<n; j++) {
      line(allxpoints[n], allypoints[n], allxpoints[j], allypoints[j])
        ;
    }
    noLoop();
  }
}

This is what I have so far. If I remove noLoop();, the code re-runs and it's too fast. What I am trying to achieve is like the video, where the points are constantly shifting and it's generative.

**Comment by mrzl** [comment]
lol
