### ISSUE TITLE
createFont nullPointerException

### ISSUE THREAD

**Issue by RadianSmile** [processing/processing#4234]
V3.0.1  mac OSX  and Window 10. (I tried at both systems)
My program works fine in v3.0.0, after upgrade createFont throws me nullPointerException, and I have no idea with this. And I did't change any of my code. Please tell me why. There is no imfomation on google.

**Comment by Akarshit** [comment]
@RadianSmile Thanks for reporting the issue.
Can you please provide some more information, like the code that you were trying to run or the stack trace of the error?

**Comment by benfry** [comment]
No reply; closing.

**Comment by vk2gpz** [comment]
I'm getting the same Exception with the code I downloaded from https://github.com/blprnt/Kepler-Visualization
