### ISSUE TITLE
Resizing causes surface to behave weirdly

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#4236]
The sketch to reproduce the issue:

public void setup() {
size(500, 360);

surface.setResizable(true);

}

public void draw() {
}

When running the above code on Linux, I got some weird result while resizing the window that is opened. Following are the screenshots of the window while resizing:
![screenshot from 2016-01-20 18 53 52](https://cloud.githubusercontent.com/assets/7762605/12459719/229cba36-bfd6-11e5-982e-b06b31fde9ac.png)
![screenshot from 2016-01-20 18 53 17](https://cloud.githubusercontent.com/assets/7762605/12459726/2b1e1344-bfd6-11e5-988f-eac96ece4a95.png)
![screenshot from 2016-01-20 18 53 02](https://cloud.githubusercontent.com/assets/7762605/12459725/2b15926e-bfd6-11e5-8dfd-3b2cec1531f9.png)

**Comment by benfry** [comment]
Put something in `draw()`, like a single `background()` call. We can't magically know what you want, and can't pick an arbitrary default because folks who have a proper `draw()` will see flickering.
