### ISSUE TITLE
mousePressed() not working well - Android Mode

### ISSUE THREAD

**Issue by 94Conti** [processing/processing#4246]
Hi! I am doing an Application for Android. I am using a Samsung Galaxy Tab 3 (Android 4.4.2) and last version of Processing.

I have read some people saying that Android 4.1+ versions have some issues with some Processing events (like mousePressed...). In Java Mode works perfectly, but when using Android Mode I have to tab two times instead of one click as in Java Mode. 

I was using this example code here: https://processing.org/examples/button.html

Someone knows if there is any way to fix it? Or it is just me doing something wrong?
Thanks!

**Comment by codeanticode** [comment]
Hi, please report Android mode-related issues in the [processing-android repo](https://github.com/processing/processing-android). I just re-opened this issue there: https://github.com/processing/processing-android/issues/186
