### ISSUE TITLE
Memory leak w/ app on OSX

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#4248]
I make a complex programme with Processing https://github.com/StanLepunK/ROMANESCO/tree/master/Software_28 It's three sketches who work together. One is controller, the two others are a display rendering in P3D. The sketches work together with OSC protocol. When the sketch run in processing there is no problem, but when I build the OSX application, that's work but there is a big memory leak in the "Prescene application". 
Same result with Java embeded or not.

I don't know if it's a right place to post an issue about this the problem ? But I have no control on the problem to find the origin of this memory leak because it's ok when that's run in Processing.

**Comment by StanLepunK** [comment]
Close, because maybe the frameRate is the origin of this memory leak.

**Comment by SlightlyCyborg** [comment]
What does this mean? How is the frameRate the source of the memory leak?
