### ISSUE TITLE
Comment/uncomment removes indenting

### ISSUE THREAD

**Issue by gdsentropy** [processing/processing#4249]
Version 3.0.1, running on Mac Mini El Capitan.
I have not tried to reproduce this on any other platform.

I have the processing preference editor.tabs.size set to 4.

When I comment/uncomment, each time one space is removed from the indentation of curly brace contents until such is eventually aligned with the braces. It does not proceed further. In the case of deeply nested code, the issue gets a bit more interesting.

I can submit my preferences and theme files as well, because there may be some ancillary interaction responsible for this issue.

**Comment by gdsentropy** [comment]
Crap stupid iPhone submitted in the middle of editing the comment. Sorry for the butchery.

**Comment by DarkPrince304** [comment]
Hello, with the PR #4313 this issue is fixed if I am correct. Please review it and let me know :)

**Comment by gdsentropy** [comment]
None of my machines are setup to build this repo, but I will have a go at it this weekend, unless there is a binary I can easily acquire and test.

**Comment by aengelke** [comment]
This issue is rooted at 81fce07 where the behaviour was changed to `// ` (with space). However, the space was removed later in ebbbdc6. The question is whether there should be a space after the comment or not.

**Comment by benfry** [comment]
There should not be a space, just as it was prior to that contributed commit that changed the original (no additional space) behavior.
