### ISSUE TITLE
Column edit inconsistency 

### ISSUE THREAD

**Issue by gdsentropy** [processing/processing#4250]
Version 3.0.1, running on Mac Mini El Capitan.
I have not tried to reproduce this on any other platform.

There is an inconsistency in the behavior of column edit between removal and addition.
Removal works as expected; selecting a column and backspace correctly removes the contents of that column. However addition will only apply to the top line.

I can submit my preferences and theme files if needed.

**Comment by benfry** [comment]
Column edit?

**Comment by gdsentropy** [comment]
Vertical text edit across multiple rows.

Ian McDonald
----------------------------------------
Senior Software Engineer Lead,
Architect and Security Analyst
ASP.NET | MVC | MVVM | WCF
.NET 4.5+, Mono, C#, F#, C++
Web, Win, iOS, Linux, Android
Cell: (919)-830-4606 M-F 365d
------------------------------------------
Please consider this email before printing the environment.
(ノಠ益ಠ)ノ彡┻━┻

**Comment by GKFX** [comment]
I can confirm it on Debian Linux, so don't worry about sending your files.

**Comment by GKFX** [comment]
Just fixing it now.
