### ISSUE TITLE
consistency between loadString and loadJSONObject/loadJSONArray error message formatting

### ISSUE THREAD

**Issue by ekeneijeoma** [processing/processing#4265]
For consistency I think it'd be good if loadStrings and loadJSON functions had the same error messages had the same format. At the moment for loadStrings it says
The file filename.txt is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
and for loadJSONObject/loadJSONArray its
filename.json does not exist or could not be read

**Comment by benfry** [comment]
Fix incorporated for the next release with #4268.
