### ISSUE TITLE
Feature: customisable line-height in the editor

### ISSUE THREAD

**Issue by JobLeonard** [processing/processing#4267]
I love trying out different monospace fonts in the editor, but some don't work very well with the standard line-height. For example, currently I'm giving [Fantasque](https://github.com/belluzj/fantasque-sans) a try, for that casual Comic Sans feeling without the bad parts. It looks nice, but I feel like a bit more height between the lines would really help this font.

**Comment by payal97** [comment]
This looks like a nice feature. I would like to implement it, if it is so decided.

**Comment by JobLeonard** [comment]
Can I be greedy and also request custom letter spacing? ;)

**Comment by payal97** [comment]
I'll look into it. :)

**Comment by iamutkarshtiwari** [comment]
@benfry Sounds cool! What do you think about this feature?

**Comment by benfry** [comment]
This sounds like something better handled by a full-featured editor; let's keep the PDE simple. Doing this means messing with an additional setting, a new preference, making sure it works with Chinese/Japanese/Korean input methods, and so on. More effort to maintain than what we'd be getting out of it.
