### ISSUE TITLE
'Background Color when Presenting' not visible on Preferences window

### ISSUE THREAD

**Issue by PARAG00991** [processing/processing#4272]
When we select the background color used when using present from color selector in preferences window, it doesn't get displayed in the color selector icon. This could be illustrated from the following snapshots:
![screenshot from 2016-02-06 19 03 20](https://cloud.githubusercontent.com/assets/8044561/12866978/1da4981c-cd07-11e5-972b-397e7e913c8e.png)
![screenshot from 2016-02-06 19 03 56](https://cloud.githubusercontent.com/assets/8044561/12866979/2015f55a-cd07-11e5-8c34-6fac989eed44.png)

**Comment by benfry** [comment]
Fixed in https://github.com/processing/processing/pull/4278
