### ISSUE TITLE
Feature Request- Start processing using desktop icon or menu icon in Linux

### ISSUE THREAD

**Issue by PARAG00991** [processing/processing#4274]
I think it would be nice to have PDE getting started by clicking its desktop icon or menu icon instead of starting it from command line by typing in the command *./processing* everytime in linux. I would like to work on this. Any help in the context would be appreciated.

**Comment by monkstone** [comment]
If you are a linux user, you really should know how to create a desktop entry. Right click mouse on desktop select `Create new Launcher here` , the fill out the launcher properties. For the icon choose `/home/tux/processing-3.0.1/lib/icons/pde-48.png`, assumes you are using mint with cinnamon desktop or similar (eg ubuntu), if you are using anything else you are probably using the wrong distro for your experience level.

**Comment by PARAG00991** [comment]
@monkstone , Well as of now I'm using Ubuntu 14.04 LTS (pinguy) and sorry, but I don't get any such option after right clicking on desktop. Moreover, I was talking about optional desktop icon and menu icon feature to come along with processing software, so that a user using any of the distros of linux would be able to make it (may be using some `make install-desktop-icon` command).

**Comment by monkstone** [comment]
You can't honestly expect support for  such a low ranked distro http://distrowatch.com/ linux is great for individuals, so expect to do some work unless you are using bog standard mainstream distro.

**Comment by gohai** [comment]
Thanks @monkstone - that's indeed a packaging & distribution issue, and outside of the scope of the (tar-ball) release. Processing ships with a .desktop file btw.
