### ISSUE TITLE
Convention for directional lights in OpenGL-Binding for GLSL

### ISSUE THREAD

**Issue by KnutHartmann** [processing/processing#4275]
The standard GLSL shader uses the homogeneous component of the uniform variable lightPosition to differentiate between point and directional light.

uniform vec4 lightPosition

core/src/processing/opengl/shaders/LightVert.gls
line 101: bool isDir = zero_float < lightPosition[i].w;

Many textbooks in computer graphics suggest to differentiate between points and vectors by setting the homogeneous component to 1 for points and to 0 for directions.

This is conform with the normalization = division by the homogeneous component.

All the examples in other GLSL shader NOT using processing looks likes this:

if ( lightPosition.w == 0.0 ) {
  // it is a directional light
  // get the direction by converting to vec3 (ignore W) and negate it
  vec3 lightDirection = -lightPosition.xyz
} else {
  // point light
}

http://www.tomdalling.com/blog/modern-opengl/08-even-more-lighting-directional-lights-spotlights-multiple-lights/ 

My processing GLSL shader code looks likes this:

if ( lightPosition.w != 0.0 ) {
  // it is a directional light
  direction = -lightNormal;
} else {
  // point light
  direction = lightPosition.xyz - position.xyz;
}

Could you take over the convention w == 1 for point lights to minimize the confusion of cross-plattform programmers?

**Comment by codeanticode** [comment]
@KnutHartmann I think this would be a reasonable improvement so Processing follows the accepted on convention on the use of the w coordinate to differentiate directional from point lights. I don't see any unintended consequences from inverting the convention, as these values are not used for anything else. I will go ahead with the change. Thanks for bringing this up!

**Comment by codeanticode** [comment]
I went ahead and made the switch with commit https://github.com/processing/processing/commit/59dd00fe8db63a8e2a9b8b923bd586fdc36c1edc, as it does not break any API and the shader code follows accepted CG conventions.

**Comment by hype** [comment]
grrrr - this change means all my projects running in 3.0 work fine... but now break in all other 3.1+ versions - meaning I have to now update ALL my GLSL - damn you... and your convention standards... lol

**Comment by hype** [comment]
search and replace... 637 .GLSL files... ha ha ha.

**Comment by codeanticode** [comment]
sorry... there should any further changes in the shader API... unless we move to Vulkan :-)

**Comment by hype** [comment]
:) .... and iiiiiiiiiiiii eeee iiiiiiiiiiii will always love you @codeanticode
