### ISSUE TITLE
handleCtrlClick misbehaving

### ISSUE THREAD

**Issue by lpdunwell** [processing/processing#4281]
double clicking a word and copying it (ctrl + c) often throws me to the definition of the word.
it's probably handleCtrlClick(evt) in JavaTextAreaPainter.java on line 86.

playing around I noticed a quick sequence of one left mouseclick -> ctrl + c does the same, but timing is essential.

What I'd expect here is: this should only happen if ctrl is held down before actually clicking.

**Comment by joelmoniz** [comment]
Hmm... I can't seem to reproduce this easily. But when I do, I think what is happening is that I hit `ctrl` _just_ before I do the second click in a double-click sequence.

Also, I can do this with a `one left click`+`ctrl` sequence, but it triggers but only when done really, _really_ fast, at which speed I think I might be hitting `ctrl` first by accident.

Or perhaps this has been solved in the latest release?

**Comment by lpdunwell** [comment]
I'm totally sure I'm not hitting ctrl first.

---

Luke P. Dunwell
