### ISSUE TITLE
random "'variable' is not defined in this sketch"

### ISSUE THREAD

**Issue by lpdunwell** [processing/processing#4282]
the red error message at the bottom. I have no idea what triggers it, but I know the sketch with a total of beyond 2000 lines of code including all tabs is actually large, and the stated object is defined as the code runs. running it also clears that message.

**Comment by benfry** [comment]
Please include some code that actually causes the problem; without it, I have no way to even begin looking into this issue.

**Comment by benfry** [comment]
No response; closing.
