### ISSUE TITLE
Random system freeze

### ISSUE THREAD

**Issue by lpdunwell** [processing/processing#4289]
I have a sketch with a couple of 1000 lines in multiple files that is being used in multiple kiosks.
The machines run windows 10 x64, Processing is the recent x64 release.
Now I'm absolutely not going to say my code is fault free, but every now and then (like 3 machines within 2 days, while 700 users logged in and out) a machine totally hardlocks/freezes.
this can only be solved by hard resetting it. I have found no traces or logfiles, even running the resource monitor showed nothing suspicious.
Am I right in saying this should not happen? How can I debug this? I cannot trigger it on purpose (yet).

**Comment by gohai** [comment]
Are you using 3D graphics? Could be a driver issue - I'd check if it also occurs with a GPU from a different vendor.

**Comment by lpdunwell** [comment]
We're using a compact asus computer, no chance to exchange graphics cards.
It's 2d only. I'll have a go with rendering modes on a couple of them
tomorrow in the field and see what happens. Drivers should be up to date.

On Wed, Feb 10, 2016, 17:52 Gottfried Haider <notifications@github.com>
wrote:

> Are you using 3D graphics? Could be a driver issue - I'd check if it also
> occurs with a GPU from a different vendor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/processing/issues/4289#issuecomment-182476006>
> .
>
-- 

---
Printed on recycled electrons.

**Comment by gohai** [comment]
Applications on modern OS are sufficiently isolated from the actual hardware, so that should be able to cause a hang themselves. I'd try running some other software, that stresses the memory and/or GPU, and see how long it stays up. Similarly, you could try running the same Processing sketch on different hardware. Closing.
