### ISSUE TITLE
"Font Sadness" - unable to start "processing 3 - 64bit" under Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by Prabhnith** [processing/processing#4290]
trying to execute the processing file 

`bash processing`

trying to open after giving the execute permission ,the processing file display this error.

![font sadness](https://cloud.githubusercontent.com/assets/11560449/12951908/89456caa-d03a-11e5-81f9-d155757322e9.png)

**Comment by gohai** [comment]
Is it the same if you simply download and extract the 64-bit Processing for Linux (w/ `tar vfx processing-3.0.1-linux64.tgz`), then `cd` into the new directory and then simply run `./processing` (without bash)?

**Comment by Prabhnith** [comment]
yes, i have tried all that you have mentioned, it doesn't work.
and the ./processing (without bash) says: command not found (given the +x permission doesn't work too)

**Comment by gohai** [comment]
If `./processing` does not work then something is wrong with your current directory, which also would explain the font sadness. Are you inside the same directory as the `processing` script? What does `pwd` say?

**Comment by Prabhnith** [comment]
yes sir, it's in the same folder
![processing is1](https://cloud.githubusercontent.com/assets/11560449/12955276/49da2c96-d048-11e5-9e2d-54e9ab0308a8.png)

**Comment by gohai** [comment]
Are you by chance trying to run the Windows version of Processing under Linux (since your folder on the external media is called Program Files)? What happens when you move Processing to a path that doesn't have a space character in it? What happens when download and unpack Processing to a location on a file system that is not FAT - e.g. in your home directory?

**Comment by Prabhnith** [comment]
1.no sir, actually the package is the linux one but I thought of extracting it in the "Program Files" folder rather then extracting it in the drive itself.
2. It's the same for the other directory too.
-----------------------------------
3. Hurray!!! that worked at the end. Extracting it in the home folder does the magic and without throwing any errors.

Thanks @gohai sir :)
