### ISSUE TITLE
Multiple Sketchbook recommendation not working

### ISSUE THREAD

**Issue by ld26464** [processing/processing#4294]
Processing 3 install linked me to https://github.com/processing/processing/wiki/Multiple-Sketchbooks. Both recommending that separate sketchbooks be used for Processing 2 and 3 sketches (to ease transition). But both versions 2 and 3 use the same preferences.txt to define their path to Sketchbook used, so this can't be done. Can the different versions perhaps refer to different preference files... or another solution. Otherwise recommendation should be removed or if there is a workaround some pointer to that.

**Comment by benfry** [comment]
They use the same preferences file, but 2.0 and 3.0 use different entries from that file to determine the sketchbook location.
