### ISSUE TITLE
Undo is a little "jerky" in insert mode

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#4302]
Steps to reproduce the error:

1. Enter some text
2. Make the editor in Insert mode (by hitting the `insert` key)
3. Type to overwrite text entered in `1.`
4. Undo

PS: I think I've identified the root of the issue. I should hopefully have a fix in soon.

**Comment by benfry** [comment]
Zero effort has been made to even make the editor compatible with insert mode, but contributions welcome.

**Comment by joelmoniz** [comment]
Ah, I wasn't aware of that. Except for undo, though, insert mode seemed to work perfectly (although I don't think I tested all of its aspects, copy-paste being one of the first among these that come to mind, although I am not sure how pasting would work in this context, however). I think [PR #4310](https://github.com/processing/processing/pull/4310) helped fix this particular issue though (although I didn't test other aspects of undo in insert mode or insert mode in general).
