### ISSUE TITLE
Default Template?

### ISSUE THREAD

**Issue by BeauTurner** [processing/processing#4306]
Is there a template that controls the startup sketch shown? I would like to add a starting bit (Arduino now doing something similar) instead of being blank having the following on new sketches:

void setup() {
  // put your setup code here, to run once:

}

void draw() {
  // put your main code here, to run repeatedly/loop:

}

**Comment by alignedleft** [comment]
This isn't a bug, and therefore is a great question for: forum.processing.org

But no, right now, I don't think there is a "template" feature.  New sketches are always empty.

**Comment by BeauTurner** [comment]
Thank you for the pointer.

**Comment by REAS** [comment]
This is the kind of thing we'd like to be covered with a contributed Tool. In fact, there used to be a nice tool, but the developer stopped maintaining it. Sometimes you don't want a setup() and draw() in your program, so we don't think it's good to have it there by default.

**Comment by benfry** [comment]
We've a template feature in Processing 3.2: https://github.com/processing/processing/wiki/Templates
