### ISSUE TITLE
Font problem in menu on linux

### ISSUE THREAD

**Issue by s777s** [processing/processing#4307]
When I start Processing on my Arch Laptop (15'', 1366x768, KDE), Processing 3.0.1 from repos. Font on menus and buttons is almost unreadable. It is too small and it looks like there is some kind of problem with antialiasing. It looks like a letter from font size 6 is stretched to 10. I've played with config files in `/usr/share/processing/lib/` directory, but it doesn't look like something changed. In what file and parameter I can change menu font?
P.S. Everything is OK with font in Editor.

**Comment by benfry** [comment]
Sounds like a problem with the repo or your window manager. We don't provide any sort of installer that puts anything in `/usr/share/processing/lib`. Maybe a better question to debug via the forum until you can determine if it's actually a Processing issue?
