### ISSUE TITLE
ant deb no longer works for non-arm based processors.

### ISSUE THREAD

**Issue by kfeuz** [processing/processing#4308]
Commit 8f30d42672734466ef1d8f4a3814cd36c9cec454 adds conditions that are always true.  i.e. "linux-arm32" always equals "linux-arm32".  I am guessing that one of those is supposed to be a property/variable instead.  Something along the lines of `<equals arg1="${linux-arm32}" arg2="linux-arm32" />` .  A pull request will follow shortly.

**Comment by benfry** [comment]
Incorporated for 3.0.3 with https://github.com/processing/processing/pull/4309.
