### ISSUE TITLE
symlinking to an exported linux application fails

### ISSUE THREAD

**Issue by kfeuz** [processing/processing#4318]
Although you can now run exported linux applications from outside of their application directory, you cannot do so using a symlink.

Steps to reproduce:
1. Export an application in linux
2. Create a symlink to the exported application outside of the application directory.
3. Attempt to execute.

Expected result:
The exported application launches and runs.

Actual result:
Error: Could not find or load main class

**Comment by benfry** [comment]
Thanks for the fix. Now merged for 3.1.
