### ISSUE TITLE
Possible regression: size() with final ints as input seems to fail

### ISSUE THREAD

**Issue by Pomax** [processing/processing#4328]
The following code refuses to compile in Processing 3.0.2, despite the fact that the `final` keyword is used to create constants, not variables.
```
final int dim = 40;

void setup() {
  size(dim, dim); 
}
```
The error is "the size of your sketch could not be determined", but reasonably speaking it should be entirely possible to.

It feels like this is either a regression w.r.t Processing 2.x, which compiled this code just fine, or is an issue with the IDE's syntax validator possibly using "numbers" (very easy to verify, but wrong) rather than "number constants" (harder to verify because a symbol table needs to be consulted to check for `final [int|long|etc]` type, but correct) to do its signature validation.

**Comment by suheb** [comment]
The `size()` method accepts only numbers as input. There's a specific check for this in `PdePreprocessor`. Although I can't seem to find a reason for such behavior.

**Comment by Pomax** [comment]
(note that this could be considered a regression wrt to 2.x, which accepted "fixed numbers", so variables that were `final int` did not lead to errors)

**Comment by suheb** [comment]
Perhaps @benfry has some thoughts on this?

**Comment by rzats** [comment]
@suheb : this appears to be intentional as per https://github.com/processing/processing/wiki/Changes-in-3.0#things-that-may-break-your-2x-sketches

**Comment by Pomax** [comment]
That text is about variables. The `final` keyword changes all of that: `int x = 100` can change at any time. It should absolute be rejected as input to `size`. `final int x = 100` is a primitive constant, not a variable. It cannot change, and is symbolically identical to the primitive value it aliases.

**Comment by suheb** [comment]
I know it's intentional but why?
Why variables should absolutely not be allowed in `size()`?

**Comment by Pomax** [comment]
The main rationale is because `size()` is not just another function, it's essentially the executable entry point, responsible for bootstrapping the entire graphics environment for the sketch, so its input should be computationally stable. Calling it with variables as arguments makes very little sense: you cannot do compile-time analysis to guarantee the sketch won't crash immediately, which you *can* with pure numbers or constants.

**Comment by rzats** [comment]
Upon further research you can still call `size()` with variable-defined parameters using `settings()`:

    final int foo = 30;
    int bar = 40;

    void settings() {
        size(foo, bar);
    }

The [reference page](https://processing.org/reference/settings_.html) specifically mentions this usecase so it shouldn't cause any issues.

**Comment by Pomax** [comment]
that should be an unnecessary workaround for true numbers, which normally would include named numeric constants.

**Comment by JakubValtar** [comment]
HI @Pomax, you have to type the numbers into the size() directly. The reason is that we need to extract the size with the preprocessor, which becomes difficult and error-prone when we have to deal with any identifiers (people do crazy stuff with them, which breaks things). If you want to use size() in some other way, please put it into settings().

**Comment by Pomax** [comment]
Can the error for this at least be changed, then? Any tool that is supposed to make things easy for people should never only say "this is wrong", but should always say "this is wrong, but you can do the following things instead: ... ". Mentioning or linking to the `settings()` function is no effort on the IDE's part, but will save *a lot* of people from not understanding what they should be doing instead.

**Comment by GoToLoop** [comment]
Funnily Pre-Processor got no problems at accepting variables for the 3rd renderer parameter:  
```pde
static final String RENDERER = FX2D;

void setup() {
  size(300, 200, RENDERER);
  noLoop();
}
```

And that still works even w/o `final` or `static`!  O_o

**Comment by benfry** [comment]
Explained at length here: https://github.com/processing/processing/wiki/Changes-in-3.0#things-that-may-break-your-2x-sketches
