### ISSUE TITLE
Mac Pro Mid 2012 - Sample Sound file crashes

### ISSUE THREAD

**Issue by GCCInformationTechnology** [processing/processing#4329]
Our Art Department is teaching a course using Processing 3.0.2.  When we try to open and run the Sound Sample file, it crashes.  (crash details below)

It works on the Instructor's MacBook Pro (2012), works on an iMac we purchased last year, but doesn't run on iMacs from 2010.   All of the Macs are running El Capitan.

Mac Pro model:  Mac Pro (Mid 2012) ATI Radeon HD 5770 1024 MB

Any suggestions would be greatly appreciated!!

WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: RtAudioDriver: No audio devices found
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help → Troubleshooting.

**Comment by benfry** [comment]
Moved to https://github.com/processing/processing-sound/issues/72
