### ISSUE TITLE
x

### ISSUE THREAD

**Issue by FrankOcean11** [processing/processing#4330]
x

**Comment by hamoid** [comment]
You know Ex_04A is Arduino code, right? It's not Processing code. Notice it uses loop() instead of draw(). To make Ex_04B work, check Examples > Libraries > serial > SimpleRead / SimpleWrite. Specifically, see how Serial is instantiated.

This is not a processing bug. You should ask general questions in the forum. If you ask here you're distracting developers from improving Processing.

**Comment by FrankOcean11** [comment]
wow, can you NOT assume that arduino is what i was talking about when im pointing out a group of sketch that dont compliment each other?  how about you download those section i highlighted and find out what is the issue im referring before you go and call me out

**Comment by hamoid** [comment]
Sorry but I think you got it wrong. I would say it's your task to be precise, not others to assume things :) Issues should include the necessary details to know what and how it was tested, what was the expected result, and what was the actual result, so others can help.
But please don't get offended and excuse me if I sounded harsh. You can just improve the issue title and description. "found some example code that does not do what it says it does" gives zero context. The description does not mention what steps do you take, what results you expect, and what you actually get.
I believe (not sure) Processing Handbook issues are in a different repository: https://github.com/processing/processing-docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+handbook but someone else should confirm.

**Comment by FrankOcean11** [comment]
dude if your looking for an argument i have no issue here doing just that...

**Comment by FrankOcean11** [comment]
what do you mean what was i expecting ? its that a rhetorical question ? i dont have to expect nothing nothing every sketch YOU guys upload has a description telling you what to expect so that i dont have to figure shit out so when you asking me "what was the expected result," im not sure if your being funny or just not reading my initial post and when you're saying "what was the actual result, so others can help."  YOU aren't reading because my initial post was being really detail about just 'that'

**Comment by FrankOcean11** [comment]
there really aint nothing else to say here the sketch dont do what it says it does, what setup i follow and what was i expecting falls back on what the written sketch says it does and how it works, so if im telling you that it does not work "check it out then" dont try to call me out as if im not being descriptive enough because there is nothing else i can say or do to elaborate on my simple statement, if you're yo busy to check out what im saying then you shouldn't be picking up this post to answer and just let someone else answer it because now your making me want to re-post this question again just to get someone else  to reply who actually has time to look at this manner,....it takes less then 30second for you to open this sketch and run it and you will see what im talking about

**Comment by FrankOcean11** [comment]
the arduino algorithm makes sense and compile despite the fact that who ever uploaded that code did not include the library, the processing mouse function work fine at run what doe not work is the Transmitting via serial to control the arduino i will say that the arduino led is flickering meaning it is getting something but i cant debug it because when you run processing serial you cant open arduino's serial so i dont know whats being sent although looking at the processing sketch i see what suppose to be sent and this is why i say it is not working

**Comment by hamoid** [comment]
It seems we are on different wavelengths. I spent more than 30 minutes with your issue. I never ask rhetorical questions. I'll let others comment.

**Comment by FrankOcean11** [comment]
Thank you and that being said please delete your comments "i don't want tarnished communication from the next commenters"
