### ISSUE TITLE
Syntax for TableRow methods aren't recognized by the highlighter

### ISSUE THREAD

**Issue by clayheaton** [processing/processing#4332]
The `TableRow` methods `setDouble()` and `setLong()` are not highlighted by the syntax highlighter in the IDE. They're also not listed in the documentation. The problem holds for the getters, too: `getLong` and `getDouble`.

Other `TableRow` methods may have the same problem -- haven't tested them all yet.

**Comment by suheb** [comment]
Can you provide an example of the code you used?

**Comment by clayheaton** [comment]
You've probably resolved this by now, but here are some examples with `getLong()` and `setLong()`:

<img width="487" alt="screen shot 2016-02-27 at 12 40 15 pm" src="https://cloud.githubusercontent.com/assets/205364/13374326/5c6ab38a-dd4f-11e5-9386-ada112cfd8ef.png">

<img width="718" alt="screen shot 2016-02-27 at 12 40 21 pm" src="https://cloud.githubusercontent.com/assets/205364/13374328/608dfc74-dd4f-11e5-8045-6ab19c6599b1.png">

**Comment by benfry** [comment]
They're not included since we don't use `long` or `double` anywhere in the core API. They're included in the `processing.data` classes for people who 1) know what they are, and 2) are probably (or at least can) work from the javadoc.
