### ISSUE TITLE
JSONObject get() method is private

### ISSUE THREAD

**Issue by jarkman** [processing/processing#4334]
The JSONObject get() and put() methods are alluded to in the docs - see the text at the top of http://processing.github.io/processing-javadocs/core/processing/data/JSONObject.html - but they both seem to be private in the source and can't be used in a Processing app (with an error about visibility).

They need to be public to allow any work with JSON files of unknown content. Which we're a bit in the middle of, so even an ugly workaround would be very welcome.

JSONArray also seems to be missing a get().

Thanks!
Richard

**Comment by jarkman** [comment]
Ugly workaround found, in case anyone comes here with the same problem  - it's possible to write a get() by calling getBoolean, getDouble, etc in turn until one of them doesn't throw an exception.

It would be a lot nicer to just call get(), though... :-)

**Comment by Akarshit** [comment]
@jarkman I am not sure of the reason the get() method was private. Though i have created a fix which, if merged, would make get() public in future release.

**Comment by jarkman** [comment]
@akarshit - thanks! Could you do the same for put() ?

**Comment by Akarshit** [comment]
@jarkman Done.

**Comment by benfry** [comment]
It wasn't public because we go out of our way to avoid methods that return `Object` and require users to do a cast for the data coming back. Incorporated the change for 3.2.2/3.3 since there's demonstrated need for it.
