### ISSUE TITLE
Unable to add .pde file to web page

### ISSUE THREAD

**Issue by rohitsam** [processing/processing#4345]
here is my html code
<html>
  <head>

<script src="game/processing.min.js"></script>
<canvas data-processing-sources="game/game.pde"></canvas>

  </head>
  <body>
  	
  </body>
  </html>
error i was getting:
Uncaught Processing.js: Unable to load pjs sketch files: game/Game.pde ==> XMLHttpRequest failure, possibly due to a same-origin policy violation. You can try loading this page in another browser, or load it from http://localhost using a local webserver. See the Processing.js README for a more detailed explanation of this problem and solutions.n @ processing.min.js:18b.onreadystatechange @ processing.min.js:17e @ processing.min.js:18b @ processing.min.js:19k.loadSketchFromSources @ processing.min.js:19p @ processing.min.js:19

**Comment by JamesJDillon** [comment]
I've encountered this error before using a different Js library. What I assume you're doing is just trying to open you're index.html file directly in your browser? What you should try is setting up a local webserver (such as XAMMP if you're on windows), and try running it through that. For instance, on windows:

1.Download XAMMP.
2. Install XAMMP.
3. Navigate to the htdocs directory (in your xammp folder).
4. Place your project in this directory.
5. Start XAMMP administrator, and start apache. 
6. Navigate to: localhost:(port number, usually 80)/foldername/index.html

**Comment by benfry** [comment]
Wrong project. This repository has nothing to do with processing.js.
