### ISSUE TITLE
AttachingConnector not attaching

### ISSUE THREAD

**Issue by AeroX2** [processing/processing#4346]
Hello,
So I have been trying to get Processing 3.0.2 working on my laptop, currently running ArchLinux 
And the issue is that when I click on the run button in the IDE the program refuses to run. 
I get no error messages or any message at all.

System details:
[http://pastebin.com/RdHb8trA](http://pastebin.com/RdHb8trA)

Things I have tried:
- Running with present mode
- Using Oracle and OpenJDK
- Testing on another computer (Same OS, Same Window Manager, Same Java), IDE works perfectly, run button work and runs the application
- Using both the embed java version and the locally installed version.
- Exporting the application and running it with java -jar program (Works perfectly)
- Using the command line tool processing-java (--export works but --run and --present hangs)
- Using a different window manager
- Building from source
- Reinstalling Oracle JDK
- Updating all packages

After trying a number of different methods and hacks I have resorted to looking into the source code.
Eventually I found that on line 223 in Runner.java, the AttachConnector was failing to attach and kept throwing a IOException with Connection refused, possibly indicating the program is never launched?

As of now I'm officially stumped, hopefully someone can shed some light on why Processing is not working on my laptop.

Thanks

**Comment by benfry** [comment]
Sounds like you have a firewall or something else that's preventing the PDE connect to the java process via the debugger. Regardless, it's not a bug, but something happening on your machine. forum.processing.org is a more appropriate place for troubleshooting.
