### ISSUE TITLE
Allow library access to registerMethod(), handleMethod(), etc.. 

### ISSUE THREAD

**Issue by pentaphobe** [processing/processing#4347]
When applications increase in complexity, it would be beneficial for non-`PApplet` classes to listen to events (beyond the builtin ones).

ControlP5 currently registers a `draw` method, which allows clean sketch code since the library can default to handling its own updates.

Having similar capabilities for (eg.) `Serial`'s `serialEvent` and `Capture`'s `captureEvent` would allow far more interoperability between libraries, as well as providing a cleaner interface for task-specific behaviours.

A consistent conduit for modules just makes sense, and would only require a few members to be `public`, or at least `protected` so that advanced users can access it in subclasses of `PApplet`

Happy to make the necessary changes in `PApplet` and some core libraries if deemed acceptable.

**Comment by benfry** [comment]
`registerMethod()` is already public. What are you asking for?

**Comment by pentaphobe** [comment]
You can only `registerMethod()` on a few built-in events, I'm suggesting that it'd be worth exposing for use by library developers. (eg. `Serial`'s `serialEvent`, etc.. as mentioned in original post).

Since the functionality already exists and is merely hidden from end user it doesn't seem a stretch to implement (scatter a few publics around, maybe a couple safety checks)

---

I got around this in a recent project by making an interim class which basically has public duplicates of all the required `PApplet` functionality, but that's just nasty.

Point is that the final code was a lot cleaner and more readable than it would have otherwise been, and allowed far better decoupling in areas.

---

All I exposed was:

- `registerMethod()` (all variants)
- `registerNoArgs()`
- `registerWithArgs()`
- `unregisterMethod()`
- `handleMethods()` (all variants)

Also had to replicate the declarations of the following, but they could probably stay private if done in core:

- `registerMap` variable
- `RegisteredMethods` inner class

**Comment by benfry** [comment]
`registerMethod()` and `unregisterMethod()` are already exposed. The others would be really problematic if they were exposed—having a sketch call `handleMethods()` could cause serious problems; same for letting people mess with the internals of `registerMap`. 

And adding other handlers like `serialEvent()` is straightforward (see the source), so I don't see enough upside for implementing more of this but do see plenty of downsides, sorry.

**Comment by pentaphobe** [comment]
Hi Ben,

Seems like there's a misunderstanding here, not saying that my clarifying is going to change your mind - but at least worth discussing the same topic :)

> The others would be really problematic if they were exposed—having a sketch call handleMethods() could cause serious problems; same for letting people mess with the internals of registerMap.

Not suggesting you expose those other methods/variables, I simply mentioned that *I had to* in order to make the methods which depend upon them public.

You can indeed register other events to the main PApplet-derived class, however with built-in events you can register from *any* class (which is where it becomes particularly useful)

---

Am wary of ranting on further - but happy to clarify with code samples if there's still confusion.
