### ISSUE TITLE
Raspbian image is incompatible with Raspberry Pi 3

### ISSUE THREAD

**Issue by joernroeder** [processing/processing#4349]
Hey,
I've just got the newly released raspberry pi v3 and tried to run the image found on the [Pi wiki page](https://github.com/processing/processing/wiki/Raspberry-Pi). This didn't work as expected ([got 8 flashes on boot](http://elinux.org/R-Pi_Troubleshooting#Green_LED_blinks_in_a_specific_pattern)) and the pi needs a newer firmware which i've found at https://github.com/raspberrypi/firmware/tree/master/boot

After updating `bootcode.bin` and `start(*).elf` the pi booted successfully but processing froze the pi immediately.

I didn't try to load a fresh Raspbian and install processing as docs suggested to use the prepared image and i was short on time.

I know that the release of the RPi3 was just a couple of days ago so maybe we can use this thread to collect fixes/ideas etc to get processing running on the new pi3 …

**Comment by joelbaumann** [comment]
I tried installing the latest version of Raspbian and then adding the latest processing build via the terminal. But I ran into problems. Processing could not start because it could not write prefs in /home/pi. I tried changing the permissions to no avail. Any pointers welcome...

**Comment by codeanticode** [comment]
I have been using this Raspbian image that @gohai put together for the RPi3:

http://sukzessiv.net/~gohai/p5-arm/processing-3.0.2.1-linux-raspbian.tar.bz2

**Comment by benfry** [comment]
@gohai Can you confirm or close?

**Comment by gohai** [comment]
@benfry Confirmed. The distribution used for the current image doesn't support the Pi 3. I'll spin a new one after the new Processing release.

**Comment by gohai** [comment]
Pi 3 should work with the 3.1 image available for Download [here](https://github.com/processing/processing/wiki/Raspberry-Pi#download).
