### ISSUE TITLE
Cannot Run Processing.exe

### ISSUE THREAD

**Issue by kahermans** [processing/processing#4354]
I downloaded the zip, extracted the files to a folder, and tried to run processing.exe. I get an error that says Processing cannot run because it could not create a folder to store your sketchbook. I have attempted to look for a preferences.txt file in order to redirect to a folder that I've created. I'm on a lab computer, but I do have administrator privileges.

**Comment by ZachSundberg** [comment]
Try [right-click]->Run as administrator
If that works you can then [right-click]->properties->compatibility
Check []run as administrator

**Comment by benfry** [comment]
Please use forum.processing.org for troubleshooting help.
