### ISSUE TITLE
Calling texture2D() in shader script do not work as expected.

### ISSUE THREAD

**Issue by martiSteiger** [processing/processing#4360]
Shadertoy is the leading shader collection with thousands of brilliant shader examples.
Most impressive shaders are using the shader programming statement ...
   
   vec3 color = texture2D (texture, position);

If the texture coordination 'vec2 position' are outside the range 0.0 .. 1.0
they will be internally mapped to '0.0 <= position < 1.0' from Shadertoy. 
It would be very helpful that processing do it in the same way, 
so that we must not rewrite all the great shader examples from Shadertoy. 

As a workaround we can rewrite the shaders using the 'mod' function.

   vec3 col = texture2D (texture, mod(position, 1.0));
  
But this workaround do also not exactly produce the expected result.
The frame pixel are flickering as you can see starting the test example.

**Is there a chance to correct this in the processing kernel ?
If it is, it would be great to have a compatible shader interpreter!**

Here's the test sketch and the shader for testing ...
Save them as files "ShaderTextureError.pde" and "TextureMover.glsl"
and add a tile picture named "texture1.jpg".		   

```
//-------------------------------------------------------------
// sketch:  SHADERS/ShaderTextureError.pde           2016-03-16
// This shader example should display an endless moving texture 
// background using a tile texture. Because of an error in the
// shader script interpretation it produces an ugly background.
//-------------------------------------------------------------
PImage tileTexture;
PShader shader1;

void setup()
{
  size(640, 480, P2D);
  tileTexture = loadImage("texture1.jpg");
  loadShader();
}
void loadShader()
{  
  shader1 = loadShader("TextureMover.glsl");
  shader1.set("resolution", float(width), float(height));  
  shader1.set("textureImage", tileTexture);
}
void draw() 
{
  shader1.set("time", millis() / 1000.0);
  shader(shader1);                    
  rect(0, 0, width, height);
  //frame.setTitle("ShaderTextureError: " + nf(frameRate,0,1) + " fps");     
}
void keyPressed()
{
  if (key == 'r') loadShader();   // reload shader
  if (key == 's') save ("ShaderTextureError.png");
}
```
---
```
//---------------------------------------------------------
// TextureMover.glsl
// demonstrate background moving using a tile texture
//---------------------------------------------------------
uniform float time;
uniform vec2 resolution;
uniform sampler2D textureImage;
void main()
{
  vec2 pos = gl_FragCoord.xy - vec2(4.0*time);
  vec2 p = (resolution - 4.0 * pos) / resolution.x;
  // this texture2D call do not work as expected! 
  vec3 col = texture2D (textureImage, p).xyz;
  // this workaround should normally be not necessary!
  //vec3 col = texture2D (textureImage, mod(p, 1.0)).xyz;
  gl_FragColor = vec4 (col, 1.0);
}
```

**Comment by codeanticode** [comment]
I think you should be able to achieve the wrapping of the texture coordinates by using in the sketch textureWrap(REPEAT), for example inside setup().

**Comment by martiSteiger** [comment]
Thank you very much! 
With **textureWrap(REPEAT)** it is now running as expected!

Wouldn't it be better to set the REPEAT mode as default texture wrapping mode ?

However, texture wrapping is a often used technique for 2d and 3d shaders and there is no basic shader example within processing how to use it.
Can you include a shader example like this at the next release? 


```
//-------------------------------------------------------------
// sketch:  Shaders/TextureMover.pde
// Display endless moving background using a tile texture.
//-------------------------------------------------------------
PImage tileTexture;
PShader shader1;
void setup()
{
  size(640, 480, P2D);
  textureWrap(REPEAT);
  tileTexture = loadImage("texture1.jpg");
  loadShader();
}
void loadShader()
{  
  shader1 = loadShader("TextureMover.glsl");
  shader1.set("resolution", float(width), float(height));  
  shader1.set("textureImage", tileTexture);
}
void draw() 
{
  shader1.set("time", millis() / 1000.0);
  shader(shader1);                    
  rect(0, 0, width, height);
}
```

```
//---------------------------------------------------------
// file:  TextureMover.glsl
// Display endless moving background using a tile texture.
//---------------------------------------------------------
uniform float time;
uniform vec2 resolution;
uniform sampler2D textureImage;
#define TILES_COUNT_X 4.0
void main()
{
  vec2 pos = gl_FragCoord.xy - vec2(4.0*time);
  vec2 p = (resolution - TILES_COUNT_X * pos) / resolution.x;
  vec3 col = texture2D (textureImage, p).xyz;
  gl_FragColor = vec4 (col, 1.0);
}
```

**Comment by codeanticode** [comment]
Cool, good to know that textureWrap(REPEAT) solves the issue! Marking it as an enhancement now. Yes, I think adding your example to the Shader topics on how to use the REPEAT wrapping is a good idea, thanks a lot for your contribution!

**Comment by codeanticode** [comment]
Add your example to the shaders topic: https://github.com/processing/processing-docs/commit/3708be262b80d210597dceeb933feb46fac54e71

Thanks again!
