### ISSUE TITLE
Downloads page typo

### ISSUE THREAD

**Issue by Thegamerplus1** [processing/processing#4362]
Earlier releases have been removed because we can only support the current versions of the software. To update old code, read the changes page. **_Per-release_** changes can be found in revisions.txt. If you have problems with the current release, please file a bug so that we can fix it. Older releases can also be built from the source. Read More about the releases and their numbering. To use Android Mode, Processing 3.0 beta or later is required.

**Comment by REAS** [comment]
This is correct, but I see how it's confusing. I just modified the wording to clarify for the next update.
