### ISSUE TITLE
parseXML returns void instead of XML object

### ISSUE THREAD

**Issue by cansik** [processing/processing#4363]
In the [documentation](https://processing.org/reference/parseXML_.html) there is written that parseXML returns an XML object:

```java
...
XML xml = parseXML(data);
  if (xml == null) {
...
```

But Processing complains about that it just is a void method. I can't find the method in the source code of processing, maybe it's a magic function?

**Comment by alignedleft** [comment]
Sorry, can you clarify what the problem is? Are you seeing an error message?

When I paste the example code from that page into Processing, it runs as expected, with no errors:

```
String data = "<mammals><animal>Goat</animal></mammals>";

void setup() {
  XML xml = parseXML(data);
  if (xml == null) {
    println("XML could not be parsed.");
  } else {
    XML firstChild = xml.getChild("animal");
    println(firstChild.getContent());
  }
}
```

**Comment by cansik** [comment]
Ok that's really strange because it now works. Maybe there was something wrong with the processing code verifier.
