### ISSUE TITLE
processing runs but i have to close it for it to run what ever im working on

### ISSUE THREAD

**Issue by gpcmax** [processing/processing#4367]
same as in title.

it works perfectly but when ever I hit run it says its running but it wont show anything until i close the sketch.

what can i do about this? thanks for the help

**Comment by GKFX** [comment]
Is this for all sketches, or just for one? If just the one, can you post the sketch below? Does any text appear in the console, and if so can you post that? And what's your OS and Processing version? I don't see it on my machine with a current copy.

**Comment by gpcmax** [comment]
i have a ASUS 17.3" Republic of Gamers G752VL Gaming Notebook which runs windows 10 and it does it for all sketches. but it didn't do this originally. i use to be able to use it before but than it just randomly changed even though i didnt do anything

**Comment by GKFX** [comment]
Okay, thanks. I guess the next thing to try is to move your Processing settings folder, which will cause Processing to be reset to how it was when installed. If that makes it work as it did initially, then comparing the two folders before and after will help us diagnose the fault.
Open Processing and press `Ctrl`+`,` to open the settings dialog (Don't change anything now!). Click the link at the bottom labelled "More preferences can be edited...". A folder will appear. Close Processing, then rename the folder that opened. If that cures your problem, then please attach both folders to the thread. I don't have a Windows machine myself, so if that doesn't work you'll have to wait for someone who knows more.

**Comment by benfry** [comment]
Closing; forum.processing.org is a better place for this discussion.
