### ISSUE TITLE
Library not found in "Contribution Manager" but listed

### ISSUE THREAD

**Issue by q2dg** [processing/processing#4371]
When I want to download Andrew's Utilities (AULib) library from  "Contribution Manager", I get a 404 error when I want to go to https://imaginary-institute.com/resources/AULibrary/AULib.php and an error message like this: "Could not find a library in downloaded file". 

If a library is not available, should not be there some method to delete it (or at least, disable it) from the list?

Thanks!

**Comment by REAS** [comment]
I just checked and it looks like Andrew changed his files and didn't update the file he provides for linking through the contribution manager. The new file is https://imaginary-institute.com/resources/AULibrary/AULibrary.php

@prisonerjohn Can you have a look?

**Comment by prisonerjohn** [comment]
Just fixed the link, it looks like he switched from http to https. It should download out of the PDE Contribution Manager again.

**Comment by REAS** [comment]
Thank you!
