### ISSUE TITLE
Rendering glitch

### ISSUE THREAD

**Issue by algoint** [processing/processing#4372]
I was doing colour exercises when I came across a rendering glitch that seems to affect the Red channel.

```processing
float startingAngle = 180+15;
float incrementAngle = 30;

void setup() {
  size(1000, 1000);
  pixelDensity(2);
  background(0);
  strokeCap(SQUARE);
  colorMode(HSB, 360, 100, 100);
}

void draw() {
  noFill();
  strokeWeight(200);
  for (int i = 0; i < 12; i++) {
    stroke(i*incrementAngle, 100, 100);
    arc(width/2, height/2, 700, 700, 
      radians(startingAngle+(i*incrementAngle)), 
      radians(startingAngle+((1+i)*incrementAngle)));
  }
}
```

The above code renders just fine:
<img width="1112" alt="screen shot 2016-03-24 at 12 03 51 pm" src="https://cloud.githubusercontent.com/assets/18057289/14028206/98fdc0c6-f1b8-11e5-8a25-6b1119ae730b.png">

However when a second colour wheel is added a glitch appears.
```processing
float startingAngle = 180+15;
float incrementAngle = 30;

void setup() {
  size(1000, 1000);
  pixelDensity(2);
  background(0);
  strokeCap(SQUARE);
  colorMode(HSB, 360, 100, 100);
}

void draw() {
  noFill();
  strokeWeight(200);
  for (int i = 0; i < 12; i++) {
    stroke(i*incrementAngle, 100, 100);
    arc(width/2, height/2, 700, 700, 
      radians(startingAngle+(i*incrementAngle)), 
      radians(startingAngle+((1+i)*incrementAngle)));
  }

  startingAngle = 0+15;
  incrementAngle = 1;
  strokeWeight(100);

  for (int i = 0; i < 360; i++) {
   stroke(i*incrementAngle, 100, 100);
   arc(width/2, height/2, 300, 300, 
     radians(startingAngle+(i*incrementAngle)), 
     radians(startingAngle+((1+i)*incrementAngle)));
  }
}
```

<img width="1112" alt="screen shot 2016-03-24 at 12 05 57 pm" src="https://cloud.githubusercontent.com/assets/18057289/14028254/cb503cf2-f1b8-11e5-9fcb-b5cf653608f1.png">

changing the startingAngle for the second wheel just moves the glitch:

<img width="1112" alt="screen shot 2016-03-24 at 12 07 52 pm" src="https://cloud.githubusercontent.com/assets/18057289/14028332/338be9ce-f1b9-11e5-942c-abcad8a98313.png">

Changing the number of colour segments in the second wheel does not help, the rendering of the outer wheel is still unexpected:

```processing
float startingAngle = 180+15;
float incrementAngle = 30;

void setup() {
  size(1000, 1000);
  pixelDensity(2);
  background(0);
  strokeCap(SQUARE);
  colorMode(HSB, 360, 100, 100);
}

void draw() {
  noFill();
  strokeWeight(200);
  for (int i = 0; i < 12; i++) {
    stroke(i*incrementAngle, 100, 100);
    arc(width/2, height/2, 700, 700, 
      radians(startingAngle+(i*incrementAngle)), 
      radians(startingAngle+((1+i)*incrementAngle)));
  }

  startingAngle = 0;
  incrementAngle = 10;
  strokeWeight(100);

  for (int i = 0; i < 36; i++) {
   stroke(i*incrementAngle, 100, 100);
   arc(width/2, height/2, 300, 300, 
     radians(startingAngle+(i*incrementAngle)), 
     radians(startingAngle+((1+i)*incrementAngle)));
  }
}
```

<img width="1112" alt="screen shot 2016-03-24 at 12 17 24 pm" src="https://cloud.githubusercontent.com/assets/18057289/14028548/67b3b76c-f1ba-11e5-84d4-03da75b0fe9f.png">

**Comment by boubpopsyteam** [comment]
A question for the forum as it's not a processing bug.

startingangle and incrementangle aren't re-initialized on each loop of
draw.

Add noLoop(); in your setup ...

2016-03-24 20:27 GMT+01:00 algoint <notifications@github.com>:

**Comment by algoint** [comment]
Thanks boubpopsystem!
