### ISSUE TITLE
IllegalStateException when run PApplet as Java application

### ISSUE THREAD

**Issue by HeinPauwelyn** [processing/processing#4380]
I'll try to use Eclipse IDE for Java Developers (version Mars.2) to make processing (version 3.0.1) applications. But when I run my application I've got this error:

> **Exception in thread "Animation Thread" `java.lang.IllegalStateException`:** `size()` cannot be used here, see https://processing.org/reference/size_.html

If I place `size(200, 200);` in comment, my window is to title but it works.

I've follow the steps on this article [Processing in Eclipse](https://processing.org/tutorials/eclipse/). Here is the code I've made:

```java
import processing.core.PApplet;

public class MyProcessingSketch extends PApplet {

	public void setup(){
		
	    size(200, 200); // --> error on this line
	    background(0);
	}
	
	public void draw(){
		
		stroke(255);
	    if (mousePressed) {
	      line(mouseX,mouseY,pmouseX,pmouseY);
	    }
	}
	
	public static void main(String[] passedArgs) {
	    String[] appletArgs = new String[] { "MyProcessingSketch", "--present" };
	    
	    if (passedArgs != null) {
	        PApplet.main(concat(appletArgs, passedArgs));
	    } else {
	        PApplet.main(appletArgs);
	    }
	}
}
```

I've also added the `core.jar` file and added to build file like explained into the article I've read.

Thanks in advance for helping me.

**Comment by hamoid** [comment]
size() should be called inside settings() when using Eclipse.

See https://processing.org/reference/settings_.html
