### ISSUE TITLE
curveVertex() behaves differently in FX2D compared with other renderers

### ISSUE THREAD

**Issue by jwoLondon** [processing/processing#4382]
In FX2D, a set of `curveVertex()` calls between `beginShape()` and `endShape()` result in a closed polygon when the line should be open.

Subsequent calls to a `curveVertex()` between a separate `beginShape()` -  `endShape()` pair are joined to the previous shape. There appears to be no 'pen up' between calls to `curveVertex()`.

Here's a minimal example:

``` java
void setup() {
  size(600, 400, FX2D);   // All lines joined.
  //size(600,400);        // Expected (documented) behaviour
}

void draw() {
  background(255);
  noFill();

  // First curved line
  beginShape();
   curveVertex(100, 10);
   curveVertex(100, 100);
   curveVertex(500, 100);
   curveVertex(500, 190);
  endShape();

  // Second curved line
  beginShape();
   curveVertex(100, 210);
   curveVertex(100, 300);
   curveVertex(500, 300);
   curveVertex(500, 390);
  endShape();  
}
```

(Tested on Processing 3.0.2, MacOSX 10 Yosemite, iMac retina)

**Comment by M4riko** [comment]
Same problem on Processing 3.1.1 on Windows.

A bit annoying since I try to implement a function Plotter, and he always closes the functions :)
