### ISSUE TITLE
Missing text in UI elements, odd sizes

### ISSUE THREAD

**Issue by Derpford** [processing/processing#4394]
So, I just installed Processing on Arch x64. I'm getting some minor weirdness with the menu bar.
![weird](https://cloud.githubusercontent.com/assets/10187719/14338324/c38b1c16-fc3b-11e5-9457-8ed23dce07fd.png)
Yeah. Weird.
Drop-down menu items are similarly blank and huge. This is kind of crippling.

WM is Notion. Again, running on Arch Linux x64. I'm using the standard repo's version of Processing, but this also happens with the version downloaded from the website.

**Comment by alignedleft** [comment]
Which version are you downloading from the website? Don't rely on building from the latest master branch; that may not be stable.

**Comment by benfry** [comment]
Looks like a problem with your Window Manager (or distro), not really something we can hope to fix. I only barely have time to support Ubuntu 14.04 and 16.04 with the default window managers.
