### ISSUE TITLE
Multi-line comments ending in '**/' cause ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by colinmorris** [processing/processing#4397]
Small repro:

```
/*
 * Hello World
**/

void foo() {
}
```

Pasting that into a sketch gives me exceptions galore when I try to move the cursor around or select a block of text. Same error message as #1940, but I figured I'd open a new issue since that one was closed, and looks like it probably was a different root cause.

**Comment by GKFX** [comment]
Thanks; I think I've fixed this now.
