### ISSUE TITLE
Problems editing files in the IDE (OSX)

### ISSUE THREAD

**Issue by weymouth** [processing/processing#4398]
I copy/pasted a class and started editing the names. Very soon I was unable to select text or even move the cursor using the arrow keys. I believe this was from the automatic bug finding scripts going nuts. 

This is processing version 3.0.2 on OSX 10.10.5

**Comment by benfry** [comment]
There's nothing here that we can even begin to debug... If you have an example for how we can reproduce this, please file a bug that includes the details.
