### ISSUE TITLE
Setting the alpha channel of a blue color returns grayscale color

### ISSUE THREAD

**Issue by maxdee** [processing/processing#4399]
A fairly small and but weird bug. I use a method to set the alpha channel of a color, which works fine except when its `color(0,0,x)` and I set the alpha to 0, in which case it behaves like `color(x)`. With P2D the bug behaves differently with PShape. See the attached sketch.

[setAlpha_bug.zip](https://github.com/processing/processing/files/211541/setAlpha_bug.zip)

The method is basically: 
`return color(red(_color), green(_color), blue(_color), _alpha);`
The following also behaves the same.
`return (_color & 0xffffff) | (_alpha << 24);`

**Comment by GKFX** [comment]
This is a known, probably never-to-be-fixed bug, described [here](https://github.com/processing/processing/wiki/Troubleshooting#color0-0-0-0-is-black). That page lists some workarounds; you can also override stroke with the code below, and similarly for fill.
````java
public void stroke(color c) {
  if (c < 256) {
    noStroke();
  } else {
    super.stroke(c);
  }
}
````
 Sorry!
