### ISSUE TITLE
IDE hangs on launch on OSX

### ISSUE THREAD

**Issue by hawkw** [processing/processing#4403]
I'm using Mac OS X Yosemite version 10.11.3, and Processing 3.0.2. I first experienced this issue with Processing 3.0.1, but it persists upon updating. 

When I open the Processing IDE, the window and menu bar are both completely unresponsive as soon as the IDE opens. Keyboard shortcuts are also unresponsive. After clicking on things for a short period of time, the app will display the spinning "beach ball" cursor, and the OS (left-click menu, Activity Monitor) will flag Processing as "not responding".

**Comment by hawkw** [comment]
I have opened the Console, and it appears that launching Processing doesn't generate any log messages in the console.

**Comment by benfry** [comment]
Open Applications > Utilities > Terminal.app

Assuming you have Processing installed in Applications, type: 
```
cd /Applications
./Processing.app/Contents/MacOS/Processing 
```
What messages does it print?

**Comment by hawkw** [comment]
I actually fixed this issue pretty recently by deleting the Processing preferences.
