### ISSUE TITLE
numeric literals with underscores not handled consistently

### ISSUE THREAD

**Issue by jwoLondon** [processing/processing#4409]
Processing 3 seems to be able to handle numeric literals with underscores with simple assignment:

```java
int literal = 10_000;
```

But when combined with operators, Processing throws 'unexpected token: int' at runtime (but no red wavey line in the editor):
```java
int literal = 10_000 + 1;
```

**Comment by JakubValtar** [comment]
Hi, thanks for your report. The preprocessor does not support all of Java 7 features, but error checker has full Java 7 support. This is something I'm working on right now. There is already similar issue (#3054), so I'm closing this as a duplicate.
