### ISSUE TITLE
Sketch output window size won't change

### ISSUE THREAD

**Issue by LFBFerreira** [processing/processing#4414]
I downloaded some of the most popular sketches from Openprocessing and 90% of them present the same problem when running. Independently of the size(...) i specify in the Setup phase, the output window is always about 100x100 px.

I was using Processing 3.0.2 and cannot solve this problem. Then i tried Processing 2.2.1 on the same machine and everything works as expected.

This is stopping me from using the new IDE and latest version, so i would appreciate some help.

More info:
- windows 10 Pro
- java 8 (update 77)

**Comment by JakubValtar** [comment]
Hi @LFBFerreira, thanks for the report.

Could you please post some example code which doesn't work?

**Comment by LFBFerreira** [comment]
I downloaded some sketches from the [best sketches in openprocessing.org](http://www.openprocessing.org/browse/?viewBy=most&filter=favorited)
[Plasma](http://www.openprocessing.org/sketch/7035) and the [output i get](https://dl.dropboxusercontent.com/u/3885768/imgs/plasma.PNG)
[doodle 3](http://www.openprocessing.org/sketch/6742) and the [output i get](https://dl.dropboxusercontent.com/u/3885768/imgs/doodle.PNG)

No errors are displayed and as you can see in the code the size defined doesn't match. On Doodle 3 something is actually drawn on the output window, but on Plasma i just get a blank default background.

**Comment by JakubValtar** [comment]
Thanks! This looks like a problem with parsing size() function. I'll try to reproduce it.

**Comment by LFBFerreira** [comment]
Alright, thanks for the quick reply, and good luck :)

**Comment by StanLepunK** [comment]
When you remove the folder code in the sketch folder after that's work. 
For the other one there is problem with processing.xml you must comment the line 
````// import processing.xm````
that's work at the first frame, may be there is something must be change in the code.

**Comment by JakubValtar** [comment]
@LFBFerreira Just delete/rename the code folder and delete the plasma4.jar file. They are not part of the sketch and processing is trying to use them as part of the sketch. Other change to make this sketch work is to add `updatePixels()` at the end of `draw()` so that the changes to pixels get written back. This is a problem of OpenProcessing, their downloads have bad structure.

@benfry Do we want to (can we) handle this somehow? The problem is that the code folder contains compiled sketch in *.jar file (exported by Processing 1.0.9). It gets imported as a library and the sketch runs as PApplet from Processing 1.0.9.

**Comment by benfry** [comment]
Where the hell are people finding stuff that has core from Processing 1.0.9 embedded in the `code` folder? Not only is that a total nonsense practice, but 1.0.9 is seven years old (October 2009).

**Comment by JakubValtar** [comment]
OpenProcessing.

http://www.openprocessing.org/sketch/7035, click on "download" link in the center of the screen

**Comment by benfry** [comment]
Yes, core is included in the exported jar files, but how is that jar file winding up in the code folder of another sketch? 

Is this an openprocessing problem?

**Comment by JakubValtar** [comment]
The OpenProcessing downloads are structued like this:
- downloadedFolder
  - code
    - sketch.jar (exported sketch)
  - sketch.pde
  - sketch.java (exported java code)

When you open sketch by clicking on sketch.pde, java file gets loaded as a second tab and jar from code folder is added to classpath. Not sure how many downloads have this structure, but it looks like all exported from similar version of processing.

**Comment by benfry** [comment]
Ok, so it's an openprocessing problem. That's a nonsensical way to re-package a sketch.

Only issue for us is https://github.com/processing/processing/issues/95
