### ISSUE TITLE
rect & ellipse

### ISSUE THREAD

**Issue by sgddfcgvjbk** [processing/processing#4418]
guys, can you please add these two methods to the core-library??
public void rect(float a, float b, float c)
  {
 rect(a, b, c, c);
}

and 
 
  public void ellipse(float a, float b, float c)
  {
Ellipse(a, b, c, c);
}

this is so annoying everytime i just want a square or circle....
thanks

**Comment by REAS** [comment]
I appreciate the suggestion and the time taken to propose it. It's something that has been discussed in the past and we feel good about the current implementation. This is something that you can add to your own programs, but it's not something that we will modify with the core library.
