### ISSUE TITLE
Error in Examples -> Network -> SharedCanvasServer and Client  (Mac OS X)

### ISSUE THREAD

**Issue by lteixeira0** [processing/processing#4419]
I am trying to run the code of the SharedCanvasServer in Mac OS X and I am getting the error
ArrayIndexOutOfBoundsException

I have the 2.07 version but after download the most recent version I am still getting the same error.
I have tried in Windows 8.1 and the example is running without problems.
Thanks

**Comment by gaocegege** [comment]
Hi, I have tried [processing/java/libraries/net/examples/SharedCanvasServer/SharedCanvasServer.pde](https://github.com/processing/processing/blob/master/java/libraries/net/examples/SharedCanvasServer/SharedCanvasServer.pde) in processing 3.2.1, macOS 10.12.3, JDK 1.8. It doesn't cause ArrayIndexOutOfBoundsException.

Could I get more info about the error, the full stack trace?

**Comment by benfry** [comment]
Fixed by @JakubValtar for 3.3.7 or 3.4 (whichever comes first).
