### ISSUE TITLE
PApplet.frame.setLocation(x,y) does not print deprecation warning in 3.0

### ISSUE THREAD

**Issue by drp0** [processing/processing#4421]
The setLocation code works in Processing 2.2.1.
It is ignored in Processing 3.x.x

```processing
boolean flag;

void setup() {
flag = false;
size(100, 400);
}

void draw() {
  if (!flag) {
    println("Setting position");
    frame.setLocation(20, 20);
    flag = true;
  }
}
```

**Comment by JakubValtar** [comment]
In 3.0 you should use `surface.setLocation(20, 20);` which works.

We have a dummy frame which printes warnings to the console when used, but it looks like setLocation can't be overridden:
```processing
// PApplet.java:10353

        // Can't override this one because it's called by Window's constructor
        /*
        @Override
        public void setLocation(int x, int y) {
          deprecationWarning("setLocation");
          surface.setLocation(x, y);
        }
        */
```

**Comment by drp0** [comment]
surface.setLocation(x,y) works-
However, the window initially opens (momentarily) in the centre of the screen and jumps to the x-y coordinates.
(Using processing 3.0.2, windows 7 or windows XP and latest java)

`boolean flag;

void setup() {
flag = false;
size(100, 400);
fill(#FFFF00);
stroke(#FFFF00);
background(#4040FF);
}

void draw() {
  if (!flag) {
    println("Setting position");
    surface.setLocation(20, 20);
    flag = true;
  }
}`

With a larger application the centre of screen reveal lasts longer.
The phantom frame is in the default grey background, prior to moving.
See example application at:
[https://github.com/processing/processing/issues/4422](url)
I also note that surface.setLocation(x,y) will work in the startup routine, negating the need to use the boolean trick in void draw.

David

**Comment by benfry** [comment]
Cannot be fixed, and it's never been part of the documented API at processing.org/reference.

**Comment by drp0** [comment]
Is surface.setLocation() a documented API and if so where?
This all begs the question, what is the correct/official method to set the initial frame position of a compiled executable? Preferably one that causes the window to appear directly at the specified coordinates, without first centering a default window.
David
