### ISSUE TITLE
setIndex( ) not defined 

### ISSUE THREAD

**Issue by rkentmc** [processing/processing#4425]
I am working a project that you have written support code for. I need a solution for the remapping code. I am new to programming and really don't understand how the setIndex( ) function in the GUI_EZ_Key_Remapper on the Processing IDE is supposed to work. It is giving me an error saying that it is not created. What do I need to do to create it. What is the function's purpose? I am trying to make a button press computer login remote that will send the username and password with one press.

Robert Kent McArthur

![ez key](https://cloud.githubusercontent.com/assets/13988345/14770509/72a2c34e-0a41-11e6-9982-db944c138e83.PNG)

**Comment by JakubValtar** [comment]
Hi @rkentmc, this is a problem with your code and sadly we can't help you here.

Quick google search revealed this:
> If you get the error "the function setindex(int) does not exist", try using Processing version 2.2.1 and ControlP5 version 2.0.4

https://learn.adafruit.com/introducing-bluefruit-ez-key-diy-bluetooth-hid-keyboard/remapping-the-buttons-wireless

For any programming questions, please ask at https://forum.processing.org
