### ISSUE TITLE
Carnivore for ARM

### ISSUE THREAD

**Issue by siusoon** [processing/processing#4427]
I have been using Carnivore library in Mac with Processing, but recently I want to port to Pi. It doesn't really work as it says "A library relies on native code that's not available Or only works properly when the sketch is run as a 64-bit application". Obviously, the library is related to network architecture, that's might be the reason why it doesn't work in Pi processing ARM ver.

**Comment by gohai** [comment]
Hi Winnie! Since the Carnivore library makes use of native code, it would need to be modified to support other architecture, such as ARM. @RSG If I send you a libjpcap.so compiled on 32-bit ARM (armv6hf) - could you add support?

**Comment by RSG** [comment]
Carnivore is only supported on a small number of platforms, given the complications w/ compiling multiple native libraries. However if @gohai wanted to handle the library, i'd be happy to try to recompile a version of Carnivore that talks to it. no guarantees -- and i unfortunately don't have a Pi board at my fingertips to test -- but maybe we can make it work :)

**Comment by gohai** [comment]
@RSG I'd be happy to help - could also expose a vanilla Pi to the net and send you ssh access...

For compiling jpcap: I just tried compiling the most recent version from https://github.com/jpcap/jpcap, but running e.g. "ant all" (with libpcap & libpcap-dev installed), threw some errors in the Java part. Any suggestions? Is it possible that this doesn't work with Java 8?

**Comment by RSG** [comment]
[this file](https://github.com/RSG/Carnivore/blob/master/build/docs/README-Linux.txt) documents some of the fixes necessary to get jpcap to compile -- although your mileage may vary. and note: carnivore was made to use the sourceforge version of jpcap. i'm not sure if/how the github version is different or not. (i remember several years ago there actually used to be at least two completely different projects floating around both with the name "jpcap")

**Comment by gohai** [comment]
@RSG Thanks for the very helpful instructions! Uploaded the file here: http://sukzessiv.net/~gohai/p5-arm/processing-carnivore-native.zip

I haven't looked at the Carnivore source too closely, but I learned that one can also use simply System.loadLibrary(), and have Processing take care of setting the java.library.path to point per-architecture sub-folders inside the `library` folder. (E.g. [this](https://github.com/gohai/processing-simpletouch/blob/master/src/gohai/simpletouch/SimpleTouch.java#L53) is the code in Java, and [here](https://github.com/gohai/processing-simpletouch/tree/master/library) are the dynamic libraries.) Just in case it makes things easier!

Please ping me if I can help with testing! Thanks so much.

**Comment by RSG** [comment]
@gohai cool thanks. try putting [these two files](http://R-S-G.ORG/carnivore/download/ArchiveTest26Apr16.zip) inside Processing/libraries/carnivore/library folder and let me know if it works. it would take a miracle ;) if not, then i might accept your ssh offer and figure out some way to test it remotely.

**Comment by gohai** [comment]
@RSG Thanks! I believe it worked, got this output from the first example sketch

```
[org.rsg.carnivore.Log] setDebug: true
[org.rsg.carnivore.CarnivoreP5] starting carnivore core
[org.rsg.carnivore.Core] Linux (4.1.19-v7+), arm, 32 bit
[org.rsg.carnivore.Core] Running Java version 1.8.0_74
[org.rsg.carnivore.Core] Starting Carnivore Core version 8
[org.rsg.carnivore.net.Devices] Found network devices: {eth0=eth0}
[net.sourceforge.jpcap.capture.PacketCapture] loading native library jpcap... jpcap-linuxARM
[org.rsg.carnivore.Core] opened capture on device "eth0"
[org.rsg.carnivore.Core] starting PacketCacheThread
[org.rsg.carnivore.Core] addCarnivoreListener: org.rsg.carnivore.CarnivoreP5@8e88fb
[org.rsg.carnivore.Core] starting Packet Capture on PacketCaptureThread net.sourceforge.jpcap.capture.PacketCapture@14282e0...OK
[org.rsg.carnivore.Preferences] loading preference file: .carnivore_preferences.txt
[org.rsg.carnivore.Preferences] preference file not found -- saving default values instead
[org.rsg.carnivore.Preferences] saving prefs to disk: .carnivore_preferences.txt
[org.rsg.carnivore.Preferences] saving prefs to disk: .carnivore_preferences.txt
(TCP packet) 192.168.2.2:22 > 192.168.2.1:58596
(TCP packet) 192.168.2.1:58596 > 192.168.2.2:22
(...)
```

@siusoon I uploaded a zip of the library for you to test to: http://sukzessiv.net/~gohai/p5-arm/processing-carnivore.zip
@RSG Will take it down whenever you get around to pushing a new release! Cheers again!

**Comment by RSG** [comment]
@siusoon @gohai great! yes if you're getting those lines that say TCP packet then it's working. that's what i call teamwork. i just pushed a new version (Carnivore 8). makes me want to pay around with Pi!

**Comment by gohai** [comment]
Record time, too!

@siusoon I took my preliminary zip file down - you can get the latest release, with support for the Pi and friends, through the Library manager or from http://r-s-g.org/carnivore/download/carnivore_p5lib.zip

**Comment by siusoon** [comment]
@gohai @RSG Thanks both for your helpful support and quick responses. I am going to try it now, can't wait!! 
Million thanks!!
