### ISSUE TITLE
Files get cleaned

### ISSUE THREAD

**Issue by Shorttail** [processing/processing#4431]
Processing Java for Windows 8.1, version 3.0b3.

A student of mine had his files end up empty a few times. The most recent had .pde files containing only spaces. It happened on opening the project in Processing, which has been just fine the day before. Is this a known issue?

Is there anything else we should supply?

**Comment by gohai** [comment]
3.0b3 is an old beta (as in "testing") version. I'd start with updating to a recent release, such as 3.0.2, which also got much better testing from actual users, compared to the test version.

**Comment by Shorttail** [comment]
Thanks anyway. Closing.
