### ISSUE TITLE
Resizing sketch window produces crash in loadPixels()

### ISSUE THREAD

**Issue by Splitter4** [processing/processing#4436]
The crash in question happens in version 3.0.2 and is shown in the console as

> ArrayIndexOutOfBoundsException: Coordinate out of bounds!

Here's the code:

```
void setup()
{
  surface.setResizable(true);
}

void draw()
{
  loadPixels();
}
```

Then, with the sketch running, try resizing its window to make it larger.

This issue does not happen in an earlier version like 2.2.1 using `frame.setResizable(true)` instead of `surface.setResizable(true)`.

P.S.: I didn't know if this was worthy of another issue, but a crash also happens if you resize the window so that the height equals 0 ("Width(128) and height (0) cannot be <= 0"). I imagine the same must occur for a width of zero, but I was unable to resize the window to make it so. Is it the sketch author's responsibility to deal with this issue? If so, how?

**Comment by JakubValtar** [comment]
@Splitter4 Thanks for the report, we are already tracking this as #4407
