### ISSUE TITLE
How are pde files compiled?

### ISSUE THREAD

**Issue by HeinPauwelyn** [processing/processing#4437]
I've a little but searching how processing _(version 2.2.1)_ compiles. I've looked into the `build-tmp/source` directory and I've found a file named `project.java`. This is the same file name (without extention) that I use for the pde file named `project.pde`.

I've open the java file and read the code. Around the methodes `draw` and `setup` is a class added named `project` that extends from `PApplet`. If I view closer to the code into the methodes, I see old code I've removed and changed by other code in the `project.pde` file. So the content of this the `project.java` file is complete out of date. If I run my project, I've the correct output and works how I've code it.

So my question is now when is the `project.java` file generated and what is the reason why the code into the `project.java` file is out of date?

I've also see into the `build-tmp` directory of my solution that there is a `project.class` file added. If I open this, I see a lot of serialized text. Is the text into that file not out of date or is it the same like the file `project.java`?

**Note one:** I've added two other files into the main directory of my project named `Line.java`, that extends from PApplet because I use the logical code for draw and move a line and `LineRepo.java`, that collect all the lines into an `ArrayList<Line>`. This two file I could see into the `build-tmp` directory at all.

**Note two:** I use processing version 2.1.1 for use the package `SimpleOpenNI.*` for a Kinect.

**Comment by benfry** [comment]
Please use forum.processing.org for questions.
