### ISSUE TITLE
Interface glitches on Windows when changing Mode

### ISSUE THREAD

**Issue by AntonioFroger** [processing/processing#4444]
I just don't know why , it happens at every moment . anybody could tell me how to solve this ?
Now i am using the **V3.0.2 on Windows 10 X64**

Please help me !

![image](https://cloud.githubusercontent.com/assets/19239873/15092607/34836fc2-14a1-11e6-9e57-01b6b81eb648.png)

**Comment by AntonioFroger** [comment]
Still, this problem exists in the **V3.1**

This problem happens when click the **"change mode" button** no matter you change it or not.

I've read the issue [#4079](https://github.com/processing/processing/pull/4079) but i still have no idea.

I'm new to Processing and i'm working with it to make interactive projections. I want to bring surprises to people.

Sorry for my poor English and I really hope if anyone could help me or just give me some guide or advice.

This problem does not matters too much, I can avoid it by not touching that button, you can ignore it if there is something more important to fix for more people.

And, Processing showed me a wonderful world!

**Comment by benfry** [comment]
I just don't have any idea where to start on this one, sorry. We've not seen the problem, otherwise we'd never ship the software with something this bad. 

Do you have any Modes installed?

What type of machine is this? Have you updated the graphics drivers for your machine?

**Comment by AntonioFroger** [comment]
This problem happens on a DESKTOP COMPUTER running Windows 10 X64 Build 10586.
Processing works well on my MacBook.

It happens no matter any Modes installed or removed.

When I am using V3.0.2, it also happens when I click on anything on the toolbar(File Edit Sketch Debug Tools Help),it happens all the time and drives me mad when i load examples or change preference.
Several days ago, I reinstall the operating system and that thing only happens when i click the Mode button ( V2.2.1   V3.0.2    V3.1).

Motherboard: ASUS MAXIMUS VIII GENE
GPU: NVIDIA GeForce GTX 780 Ti (with the latest driver V365.10)

It shall not be the GPU problem.I tried take off the NVIDIA GPU from the motherboard and using INTEL HD GRAPHIC 530, that still happens.

It seems very likely that something went wrong with my Desktop, but, 
I'm also using Auduino, and I've made several interactive installations and everything works well.
Since they are very similar, and every other software on my computer are working well,
I just really don't know what goes wrong.

Maybe Microsoft made some mistakes.

**Comment by AntonioFroger** [comment]
Sorry for not tested older versions before, i tested V2.2.1 just now, that just happens the same.

**Comment by AntonioFroger** [comment]
I feel really excited when Benfry reply me ! 
hahaha!

**Comment by AntonioFroger** [comment]
I feel really excited when Benfry reply me ! 
hahaha!

**Comment by AntonioFroger** [comment]
Err......Sorry for click "close" by accident......

**Comment by AntonioFroger** [comment]
Today，I open the **Contribution Manager** and type words in the Filter,and that thing happen again. 

It happens when typing with **CHINESE INPUT** , nothings happens with **ENGLISH INPUT** .

**Comment by AntonioFroger** [comment]
Well, that also happens in the preference panel when click the **Language Drop-down menu, Editor font size Drop-down menu,Console font size Drop-down menu**.

It won't happen when click the **Editor and Console font Drop-down menu**, but ,
The **Editor and Console font Drop-down menu** is grey for about 5 seconds when first open the preference panel after open Processing.
And, the **resolution Drop-down menu** is unable to click all the time.

![image](https://cloud.githubusercontent.com/assets/19239873/15266121/5db38e6e-19cd-11e6-8c24-15c44437dac9.png)

**Comment by AntonioFroger** [comment]
I found something new and very important.

When first open the Processing program after login windows 10, everything works well no matter what button is clicked or what language input program is using.
I can create new files or open existed files, everything works well.

When close all the Processing windows and open a new one, everything I listed above will show up.

Restart the system will help.
Logout and login again helps, too.
But, only for one chance.
Things still happen if I close all the Processing window and start a new one.

Keep at least one Processing window open, no matter what I do, everything works well.

**Comment by AntonioFroger** [comment]
And Processing must run as administrator.

**Comment by AntonioFroger** [comment]
Something more to say

Close other programs (_such as Microsoft word, Adobe, Autodesk. Actually, any programs_) before launch Processing will also cause the problem.

**Comment by Mahdniss** [comment]
I also have this issue. My specs:

Motherboard: Maximus Viii Hero
CPU: Intel 6700k
OS: Windows 10 x64
GPU: AMD R9 390

It may be java related as I run a minecraft server in the background.

It appears that the window fails to properly refresh when the toolbar is navigated. 

One thing that Antonio and I have in common is that we have similar Asus Motherboards.

**Comment by SkydeFR** [comment]
Same issue (windows 7, nvidia geforce gtx 970, intel core i5-4670k)

**Comment by benfry** [comment]
It's a graphics driver problem. We couldn't make the menus and window look like that even if we tried. Not something we can fix, unfortunately.
