### ISSUE TITLE
Command line exception for 3.1

### ISSUE THREAD

**Issue by leadedge** [processing/processing#4464]
With the latest 3.1 release I have come across a problem using the command line "processing-java.exe" that does not occur with 3.0.2, with all previous sketches that did work, and with a basic sketch :

void setup() {
  size(640, 360);
} 

void draw()  { 
  
}

My command line is :

"C:\PROCESSING\processing-3.1\processing-java.exe" --sketch="SpoutBox" --run

Result is :

err is java.lang.reflect.InvocationTargetException

Exception in thread "main" java.lang.NullPointerException
        at processing.mode.java.Commander.<init>(Commander.java:263)
        at processing.mode.java.Commander.main(Commander.java:86)

--no-java makes no difference. --build, --present - same error.

**Comment by gohai** [comment]
Already reported and fixed for 3.1.1.

**Comment by benfry** [comment]
Duplicate of https://github.com/processing/processing/issues/4452
