### ISSUE TITLE
add option to disable cmd-click to jump to definition

### ISSUE THREAD

**Issue by antoineschmitt** [processing/processing#4466]
Hi,
I use cmd-C and cmd-V a lot when writing code. Actually, my finger is often still/already on the cmd key when I (double-)click on a variable or function name to select it.
But in the processing editor, cmd-click on a name jumps to its definition. So I end up very often jumping to the definition of a variable or function when I actually just wanted to select it.
This is a real burden.
Strangely, it seems that it only happens since I just updated to 3.1.
Is this a bug ?
Alternatively, is there a way to disable this behavior in the Processing preferences ? I looked in the preferences.txt file but did not find anything.
Thanks

**Comment by benfry** [comment]
Yes, that's a bug. It should be ctrl-click on the Mac. 

@JakubValtar this is a serious regression for Mac users.

**Comment by JakubValtar** [comment]
Sorry about that. I'll iron it out asap.

**Comment by antoineschmitt** [comment]
Attention : ctrl-click on Mac can be used for right-clicking.
See https://github.com/processing/processing/issues/3242
After which ctrl-click was disabled on Mac, and cmd-click enabled, or so it seems (may 19 2015).
Which does not explain why I'm only getting this weird behavior only lately…
My advice would be to do the "jump-to-definition" only if cmd-clicking on a word that is already selected.

**Comment by benfry** [comment]
Ugh, sorry @JakubValtar, I misread/misspoke. Jump should be cmd-click on Mac, ctrl-click is for right-click. 

We could add a preference to remove the behavior, though most people want the default behavior. The behavior can probably be shut off easily, so let's just put the preference in preferences.txt but not add it to the prefs window.

**Comment by JakubValtar** [comment]
Sounds good, but I still want to do some tweaks because the interaction doesn't feel right.

**Comment by antoineschmitt** [comment]
I confirm that this did not happen in 3.0.2 (the jump-to-definition behavior was altogether not implemented).
I reiterate my suggestion : implement the behavior only when the click happens on a word that is already selected. I think that this would please everyone...
Cheers !

**Comment by benfry** [comment]
The current/intended behavior is the same as I've seen in any other editor (actually, with Eclipse you have to move the mouse slightly after hitting cmd so that it underlines the text first), so no, I don't think that would please everyone.

**Comment by antoineschmitt** [comment]
Ok.
Actually, after using it a bit more, it happened once that the editor thought that the cmd key was down whereas it was actually not (any more). In this state, whenever I clicked on any word, it jumped to its definition.
I think that there is a quirk in the code where the cmd-down flag is not reset fast enough or always properly. Which would account for the number of times where it jumps-to-definition when not intended, which is often.

**Comment by JakubValtar** [comment]
Yeah, I noticed too and I'm working on a fix.
