### ISSUE TITLE
Crash with fullscreen(P3D) / Processing 3.1

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#4468]
I write a complex code, who use sometime size, sometime fullscreen.
the program work perfectly with size(,,P3D) but crash 99% of the time with fullscreen(P3D) ;
I try all my last two day I reproduce this bug in something simple to post it, but I fail to do that
So the error message : 
````
java.lang.RuntimeException: Waited 5000ms for: <6b277f8f, 65e08c9b>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1>
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:449)
	at java.lang.Thread.run(Thread.java:745)
````
The bug is the same with Processing 3.0.2

I try to continue to find a simple code to isolate the bug !

**Comment by StanLepunK** [comment]
Plus Processing crash not all the time at the same line in the program

**Comment by StanLepunK** [comment]
I understand nothing what happen with fullscreen() sometimes that's work, sometime no. 
For example I add a println to check the step in the program, I run and after that's work fine, I remove the println, I run that's work...and after five run good, crash. 
It's like a random crash on the big program
Not sure that can help but just In case the link of the random-crash-code : 
https://www.dropbox.com/s/y5pv0loifj538v4/Scene_30_random_crash_code.zip?dl=0

**Comment by gohai** [comment]
@StanLepunK Are you running this on the Raspberry Pi or an ARM device perhaps?

**Comment by StanLepunK** [comment]
nop, sorry only on mac OSX. I don't use Raspberry Pi or ARM
it's often with fullscreen, and always with the first run with size().
But I don't find why that's happen, may be because I use video. very very weird.

**Comment by JakubValtar** [comment]
Sadly I can't reproduce your issue. Your sketch has 50 tabs and 15k lines of code and I didn't even manage to launch it when I got all the libraries because it does not compile.

If it works with simpler sketches, I would bet there is some problem somewhere in your sketch. Unless you provide some shorter example I'm sorry but I can't really help.

P.S.: I think you should move this to some better IDE like Eclipse or IntelliJ IDEA. It would make your life much easier.

**Comment by StanLepunK** [comment]
I take my day to try to isolated the problem and write a simplest code to see where is the problem...but I just find a few tracks.
One is when I call two OSC
````
  osc_1 = new OscP5(this, 9000);
  osc_2 = new OscP5(this, 9001);
````
with a ````fullScreen()````

but only in my huge code not in the simple one.
After that I disable each method step by step to find which one can make a bug in association with ````OSC```` and ````fullScreen()```` after few try the program run good. I think find the gulty method, and to be sure I re-activate the other method step by step and every thing work fine... it's crazy. It's like when Processing or Sublim Text work fine once it work fine for few next run... I continue my investigation. 
One thing is pretty sure, it's when I use two canals for OSC and FullScreen...it's my little a tiny track to find a solution to isolated this weirdy buggy.

**Comment by JakubValtar** [comment]
If that happens only when there are two OscP5, you may have problem with synchronization. I believe each OscP5 runs its own thread and both can be calling `oscEvent` at the same time. Try to make `oscEvent` synchronized like this:
```processing
void synchronized oscEvent(OscMessage receive) {
  ...
}
```
If it does not help, try to put received `OscMessage`s into `BlockingQueue` and process them inside `draw()`.
```processing
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

BlockingQueue<OscMessage> oscQueue = LinkedBlockingQueue<OscMessage>();

void oscEvent(OscMessage receive) {
  oscQueue.offer(receive);
}
  
void processOscEvent(OscMessage receive) {
  if(receive.addrPattern().equals("Controller")) {
    catchDataFromController(receive) ;
    splitDataButton() ;
    splitDataSlider() ;
    splitDataLoadSaveController() ;
  }
  if(receive.addrPattern().equals("Prescene")) {
    catchDataFromPrescene(receive) ;
    splitDataFromPrescene() ;
    splitDataLoadSavePrescene() ;
  }
}

void draw() {
  while (!oscQueue.isEmpty()) {
    OscMessage receive = oscQueue.poll();
    processOscEvent(receive);
  }
}
```

Otherwise I'm out of ideas.

**Comment by StanLepunK** [comment]
Thanks  a lot I try this solution asap. And keep in touch if that's resolve this problem of crash ````	java.lang.RuntimeException: Waited 5000ms for: <7421852c, 7ae675d8>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1>
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:449)
	at java.lang.Thread.run(Thread.java:745) ````

**Comment by StanLepunK** [comment]
That's change nothing ! 
for information you forget to write ````new````in sentence ````BlockingQueue<OscMessage> oscQueue = new LinkedBlockingQueue<OscMessage>();````
I have an other track. I must launch the Scene in first before all sketch to have no problem of synchronization but not sure. 
But I continu to don't understand why that's happen just with ````fullScreen()```` and not with ````size()````

**Comment by JakubValtar** [comment]
I think that I managed to reproduce your problem:
```processing
void setup() {
  size(300, 300, P3D);
  surface.setLocation(100, 100);
  try { Thread.sleep(6000); } catch (InterruptedException e) { }
}
```
You call `surface.setLocation()` and then you initialize your OSC, which probably takes more than 5 seconds to complete. JOGL then complains that it could not set the location for 5 seconds and it is giving up. In your `setup()`, try to call `OSCSetup()` first and `size_scene()` after it and I'm sure it will be alright.

**Comment by StanLepunK** [comment]
The problem is solve with new ordering launch. Now the Scene if launching in first and OSC wait the receive message quietly. I don't do a lot of opening to be sure if it's ok, but that's sound good. To be sure I will add your security to be sure. Thx a lot for to be take a time on it. 
I close this issue ?

**Comment by JakubValtar** [comment]
You're welcome.

**Comment by StanLepunK** [comment]
@JakubValtar Now you saw and put your hand magic hands in a little part of my project you should add a tiny star on my project :) https://github.com/StanLepunK/ROMANESCO-Processing

**Comment by kasperkamperman** [comment]
I saw exactly this error in a project of a student of me on a Windows system. This happened when I combined the Arduino library and the OpenCV library. Turning on Arduino would throw this error. 

I'll try if I can reproduce this, but to what is this error related? Has it to do with where you call the size() function?

Running your code, throws an error on osx as well. However what is this surface.setLocation() call? I can't find it in the Processing reference.

```
void setup() {
  size(300, 300, P3D);
  surface.setLocation(100, 100);
  try { Thread.sleep(6000); } catch (InterruptedException e) { }
}
```

**Comment by JakubValtar** [comment]
@kasperkamperman The problem is that you block the main thread for more than 5 seconds after you call setLocation. Put the setLocation at the end of setup and the problem will go away. The long sleep is triggering JOGL's detection of blocked thread.

**Comment by kasperkamperman** [comment]
@JakubValtar The problem is that I don't use setLocation... 
So probably something else is blocking the thread for more then 5 seconds. 

I could reproduce the error on my mac as well with the following code (of course part of a bigger project).

````
import processing.serial.*;
import cc.arduino.*;
import processing.video.*;

Arduino arduino;
Capture video;

void setup() {
  
  size(1280,720, P2D);
  
  // remove one of the lines below (either one) and there is no error
  frameRate(25);
  video = new Capture(this); 
  arduino = new Arduino(this, Arduino.list()[0], 57600);
}

void draw() {
  background(0);
}
````

**Comment by kasperkamperman** [comment]
@JakubValtar Do you prefer I create a separate issue for this, because it doesn't completely relate to fullscreen(P3D)?

**Comment by JakubValtar** [comment]
Sorry for not getting back to you earlier. The problematic call here is
frameRate(), it calls through to JOGL and you should not block the thread
afterwards. Put it at the end of setup() and it will be okay.

Let's keep it here for now and I will investigate what we can do and create
new issue if needed.

Thanks!

**Comment by appakabar** [comment]
Don't know if it can help somebody, I had the same issue (java.lang.RuntimeException: Waited 5000ms ).
I was saving a big image at each processing draw(). 
Fixed by putting the save method call in a new thread (I was inside a java class)
new Thread( () ->  mysaveMethod() ).start();
