### ISSUE TITLE
NoSuchFieldError: useNativeSelect on startup

### ISSUE THREAD

**Issue by ymmt2106** [processing/processing#4470]
When software is begun, an error goes out.

![ss](https://cloud.githubusercontent.com/assets/1802993/15212711/4ace5a5a-187d-11e6-9b05-60a66e962547.png)

MacOSX 10.11.4
Java 1.6.0_65

|o|...

**Comment by benfry** [comment]
What version of Processing are you using? (And if not 3.1, please try that)

Do you have any Tools installed?

**Comment by fusepilot** [comment]
I'm getting the same error with 3.1.1.

**Comment by benfry** [comment]
That looks like you have another copy of `pde.jar` somewhere in your `CLASSPATH`. Have you installed it somewhere? 

Or perhaps you have a Mode or Tool installed that foolishly includes it. If so, your sketchbook folder temporarily will probably allow you to start the app, and you can figure out what Mode or Tool is causing the problem.

**Comment by benfry** [comment]
Fixed for Processing 3.2: https://github.com/processing/processing/issues/4608
