### ISSUE TITLE
 Kinect v2 for Windows

### ISSUE THREAD

**Issue by dfamil** [processing/processing#4474]
Kinect v2 for Windows stops working after 3.0b4.

**Comment by AntonioFroger** [comment]
What do you mean "3.0b4" ? The Version?

Now I'm using Kinect V2 for windows ,too. And everything works well with V3.0.2 and V3.1

**Comment by benfry** [comment]
That's out of our control. Please contact the author of the library.

**Comment by dfamil** [comment]
sorry
