### ISSUE TITLE
export processing for linux obuntu

### ISSUE THREAD

**Issue by azizeh1356** [processing/processing#4482]
hi
my code in processing 2.2.1 in windows 7 64 bit worked perfect.i export codes for linux but now have below error 
![9](https://cloud.githubusercontent.com/assets/17374898/15324210/c494c14a-1c5a-11e6-8412-4cdbaeb9ed0b.jpg)

**Comment by benfry** [comment]
Just like the messages say: the "Fullscreen" library is not compatible, and SimpleOpenNI isn't installed properly. Neither of which is part of Processing.
