### ISSUE TITLE
... are allowed only at source level 1.8 or above.

### ISSUE THREAD

**Issue by GoToLoop** [processing/processing#4484]
Processing builds have been bundling Java 8 for some time now.
Why then all source are still bound to Java 7? 
Why can't we use Java 8 stuff even inside ".java" tabs?

And btW, when PDE's pre-processor gonna be upgraded above Java 5 and reach Java 8 like all IDEs?
We can't even use Java 5's `enum` inside ".pde" tabs for goodness' sake!

**Comment by benfry** [comment]
https://github.com/processing/processing/wiki/Supported-Platforms#java-versions

**Comment by JakubValtar** [comment]
Enums were implemented in August 2014. Right now we support Java 6 and most of Java 7. Please check your facts before being hostile.

For the reason why you can't use Java 8: we are using old version of ANTLR (language parser) which can't handle Java 8. To support Java 8, we would have to replace ANTLR with a new version (which has different API) or replace it with something completely different. Any of these is going to take probably more than hundred hours, because whole build and export system has to be rewritten.

I just spent more than 200 hours on the backend, in part making sure it is ready for Java 8. Replacing the parser is planned for near future. Meanwhile I ask you for a little bit of patience and cooperation, since I'm spending all the hours I can afford on it.

**Comment by GoToLoop** [comment]
> Enums were implemented in August 2014.

I've been awaiting for it since Processing v1.5.1. Thanks a lot!  :tada: 
Which version exactly has `enum` arrived in Processing? Last time I've checked it didn't work @ v2.1.1.

BtW, thx again for Java 7's `0b` & `_` literals:  :bow:  I wonder what else have arrived as well?

```processing
void setup() {
  println(CONSTS.FI);

  int num = 100_000;
  println(num);

  int inBinary = 0b10011;
  println(inBinary);

  exit();
}

enum CONSTS {
  FEE, FI, FO
}
```

However, multi catch isn't working yet. :cry:
The `catch (ReflectiveOperationException | IllegalArgumentException e) {` line:

```processing
static final Object invokeMethod(java.lang.reflect.Method m, Object obj, Object... args) {
  try {
    return m.invoke(obj, args);
  }

  //catch (ReflectiveOperationException | IllegalArgumentException e) {
  catch (ReflectiveOperationException e) {
    System.err.println(e);
    return null;
  }
}
```

Again, much obliged for your 200 hours dedicated to advance Processing's API & PDE.
Hope this sad state will be overcome soon and PDE can match Java 8 and on like any other IDE!  :pray:

**Comment by JakubValtar** [comment]
> Which version exactly has enum arrived in Processing?

3.0a3

> Again, much obliged for your 200 hours dedicated to advance Processing's API & PDE.

No problem. It was Ben's idea after all. We're always trying to make Processing the best we can, however it takes insane amount of hours to take care of everything and sometimes we have to make tough decisions to work on something and postpone something else.

It just makes me sad when you post these issues, it seems like you are attacking us while we are trying to do our best here. And don't be angry on Ben for closing your issues, he's just trying to keep our issue tracker clean quickly so we have time to fix real bugs you and other people report. I would just like you to understand that we have hundreds of bug reports here which need to be fixed and every extra report is eating our time we could use to make Processing better.

I wish we all could get along well in here, we are all on the same side, just please be a little bit patient. We hear you, but it takes lots of time and careful planning to make these bigger changes :+1: 

Thanks.

**Comment by Lord-of-the-Galaxy** [comment]
@GoToLoop Coming to the multi catch question, why not just use -  
```processing
static final Object invokeMethod(java.lang.reflect.Method m, Object obj, Object... args) {
  try {
    return m.invoke(obj, args);
  }

  //catch (ReflectiveOperationException | IllegalArgumentException e) {
  catch (ReflectiveOperationException e) {
    System.err.println(e);
    return null;
  }catch (IllegalArgumentException e){
    System.err.println(e);
    return null;
  }
}

**Comment by GoToLoop** [comment]
@Lord-of-the-Galaxy Obviously, if we don't have the new syntax feature yet, we are obliged to use boilerplates as workarounds!

**Comment by benfry** [comment]
Opting to remove an unproductive comment and locking the issue since this has been closed. 

@Lord-of-the-Galaxy thanks for the workaround, there's no information on the Java 8 preprocessor updates. We'd love to do it, but none of us have had time. We're all just volunteers.
