### ISSUE TITLE
NPE with createFont("Helvetica", 96) on OS X

### ISSUE THREAD

**Issue by vk2gpz** [processing/processing#4486]
I've tried to run a code downloaded from https://github.com/blprnt/Kepler-Visualization with Processing v3.1.1 and keep getting NullPointerException with the following line:

PFont label = createFont("Helvetica", 96);

Do i need to install anything special to get this method working?

**Comment by gohai** [comment]
Helvetica is most likely not available on Windows or Linux. Try replacing `"Helvetica"` with `"Arial"` e.g.

**Comment by vk2gpz** [comment]
this was on the latest OS X.

**Comment by vk2gpz** [comment]
also, i get the same NullPointerException with

PFont label = createFont("Arial", 96);

**Comment by gohai** [comment]
What does `printArray(PFont.list());` say?

**Comment by vk2gpz** [comment]
it does show Helvetica on the list along with many other fonts.
however, createFont() method always produces NullPointerException regardless of which font I specify.

**Comment by gohai** [comment]
Does it print a stack trace - i.e. more information than just "NullPointerException"?

**Comment by vk2gpz** [comment]
just says "NullPointerException" in the "Red" band.  No stack trace.

**Comment by gohai** [comment]
Odd. Don't know what's going on.

**Comment by JakubValtar** [comment]
I think this is because `createFont` is called before the sketch starts. Try to modify the code like this, and I'm pretty sure it will work:
```processing
PFont label;

void setup() {
  label = createFont("Helvetica", 96);
}

```
