### ISSUE TITLE
TimedEventGenerator - not working in 3.1.1

### ISSUE THREAD

**Issue by mblade87** [processing/processing#4489]
I want to use timed Event generator by Jason Gessner in my v3.1.1 windows64 environment.  However while the example program works in v2.1.1 (i.e. draws the ellipses) , in v3.1.1 no ellipses are drawn.

Also when Timed Event Generator works in v3.1.1, is it possible to localize to a class?   It seems that all coding needs to be done in the main program.

Thank you

[New Text Document.txt](https://github.com/processing/processing/files/270934/New.Text.Document.txt)

**Comment by benfry** [comment]
Other people's code is out of our control: please contact them about it.
