### ISSUE TITLE
processing-java can't find the sketch

### ISSUE THREAD

**Issue by FabriceCastel** [processing/processing#4490]
I've been trying to run my sketches via the commandline with `processing-java`

No dice

The docs say the `--sketch` option is required. Great, so I've been trying all permutations of it and I've been hitting the same useless error message over and over again. Please advise or make the error message more verbose so I can figure out what I'm doing wrong.

```
Fabs-MBP:30_min_flex fab$ processing-java --sketch="sketch_000_template/"
sketch_000_template does not exist.
Fabs-MBP:30_min_flex fab$ cd sketch_000_template/
Fabs-MBP:sketch_000_template fab$ processing-java --sketch="sketch_000_template"
sketch_000_template does not exist.
Fabs-MBP:sketch_000_template fab$ ls
total 16
-rw-r--r--  1 fab  staff  3120 17 May 21:44 sketch_000_template.pde
```

**Comment by benfry** [comment]
Please use forum.processing.org for questions about getting started.

**Comment by kritixilithos** [comment]
@FabriceCastel It's because you need to provide the **full path** to the sketch. (I was facing the same problem, but I solved it by providing the full path). Even something like `~/sketch_dir` is not enough, you have to do something like `/Users/username/sketch_dir` instead.
