### ISSUE TITLE
Library path mismatch between processing-java and export

### ISSUE THREAD

**Issue by gohai** [processing/processing#4493]
I recently discovered that the file structure for libraries is a bit different between runtime and exported applications. This is currently biting me with the GL Video library.

The GL Video library is structured like this

```
- library
  * glvideo.jar (JAVA code)
  - linux-armv6hf
    * libglvideo.so (native code)
    * libgstreamer-1.0.so.0 and friends
    - gstreamer-1.0
        * various gstreamer plugins
```

But, once exported the `linux-armv6hf` directory disappears and the directory structure looks like this

```
- lib
  * glvideo.jar
  * various other jar files
  * libglvideo.so
  * libgstreamer-1.0.so.0 and friends
  - gstreamer-1.0
    * various gstreamer plugins
```

... which currently makes the library not work, since it's looking for the plugins in the inexistent `lib/linux-armv6hf/gstreamer-1.0/`.

Is this something that might be possible/worth changing in Processing proper, or should I rather find a local way to hack around it?

**Comment by benfry** [comment]
Hm, that's a tough one. For now, I'd say see about workarounds. It'll be a little while before I have a chance to dig in and fix/test it properly.

**Comment by gohai** [comment]
The workaround turned out to be very easy for the issue at hand. So this isn't a pressing issue by any means..

**Comment by benfry** [comment]
This was a problem specific to the video library, and it's now being tracked here: https://github.com/processing/processing-video/issues/188

Specifically, the video library wasn't set up properly and was hard-wired to use specific directories that made it easier to use with Eclipse but broke it when it was used as intended inside the PDE and with Export to Application.
