### ISSUE TITLE
Line() in Mac OSX

### ISSUE THREAD

**Issue by kmckernan** [processing/processing#4494]
I am using processing with the arduino tutorial (https://www.arduino.cc/en/Tutorial/Graph).  The communication seems to be working properly as I can get the value from the serial port to print() in the command line.  However, when it comes to draw the line in the java window it simply does not work.
I tried modifying the stroke() and background() colors, but that did not resolve the issue.  I created a small sketch to draw a single line in a 100 X 100 window, and still no line.

**Comment by kmckernan** [comment]
I am using Processing 3.1 and MAC OSX yosemite

**Comment by benfry** [comment]
Please use forum.processing.org for getting started/troubleshooting questions. Or the Arduino forum if it's about their code/tutorial—we don't have any control over that.
