### ISSUE TITLE
I think the website's readability is bad..

### ISSUE THREAD

**Issue by CyberianWolf** [processing/processing#4497]
I think the processing website's readability is not good. 

Compare the neighbor site "http://p5js.org/" and the processing site "http://www.processing.org/".

I know the short-cut key(?) "Ctrl + Mouse Wheel" to zoom in.

But, I had tested the site and compared it using FF, IE11, Edge, and etc. on Raspberry Pi 3.

I think the site p5js.org's policy about the CSS font-size is better.

Please, think about it.

Only young people doesn't use the processing site, right?

And the default font size for the documents and examples is so small, I think.

And I appreciate the recent upgrade to V3.1.1.

Have a nice day!

**Comment by alignedleft** [comment]
Thanks, @CyberianWolf. We realize our HTML is a bit dated, and we need to redesign (or re-code) the website at some point to support current best practices for accessibility and so on. With an all-volunteer team, though, it may take some time to tackle this. We appreciate any specific requests be posted to: https://github.com/processing/processing-docs/issues/

Thanks!
