### ISSUE TITLE
createFont is awkward because of JavaFX surface

### ISSUE THREAD

**Issue by jdf** [processing/processing#4498]
It is awkward that createFont can't be called until after the surface is created. It's natural to be able to construct fonts statically like

```python
yuppy = createFont('YuppySC-Regular', 48)
roboto = createFont('Roboto-Bold', 48)

def setup():
    size(300, 300)
    
def draw():
    background(0)
    fill(255)
    if mousePressed:
        textFont(roboto)
    else:
        textFont(yuppy)
    text("BANANA", 10, 200)
```

but that results in a crash `processing.app.SketchException: java.lang.NullPointerException at processing.core.PApplet.createFont(PApplet.java:6181)`.

requiring the awkward

```python
def setup():
    size(300, 300)
    global yuppy, roboto
    yuppy = createFont('YuppySC-Regular', 48)
    roboto = createFont('Roboto-Bold', 48)
    
def draw():
    background(0)
    fill(255)
    if mousePressed:
        textFont(roboto)
    else:
        textFont(yuppy)
    text("BANANA", 10, 200)
```

Digging through the source reveals that this is because only the JavaFX renderer has special requirements for font caching. If a Processing owner agrees with me that this situation is awkward, I'd be happy to provide a pull request that both permits static initialization of fonts and provides the caching the FX seems to want.

**Comment by JakubValtar** [comment]
I don't think we are ready for this. In ideal case no user code should run before `setup()`, because the sketch is not initialized yet. Otherwise things will break, because sketch path is not ready (so you can't load things from sketch folder), primary graphics is not ready (you don't know size, you don't even know which renderer will be used), etc.

@benfry What do you think about this? Should we push for methods being available as soon as PApplet instance is created?

**Comment by jdf** [comment]
It actually used to work as I describe, until this commit:

    https://github.com/processing/processing/commit/d96a6923de86b2ef21be6fe885917ef822662f1f

which, unless I misunderstand, has nothing to do with sketch path, and is related only to a requirement of the JavaFX renderer. My guess is that the JavaFX renderer's requirement can be otherwise met.

**Comment by benfry** [comment]
This is part of why the idea of a Surface exists... As Jakub was mentioning with the image loading, fonts are similarly tied to the actual graphics context, which can be one of multiple displays which are/are not hi-dpi, different bit depths, and all sorts of other weird things.

**Comment by benfry** [comment]
At the end of the day, `createFont()` touches/requires the drawing context, which doesn't exist outside `setup()` and `draw()` (or a function called from them).
