### ISSUE TITLE
Can't kill Processing processes on OSX

### ISSUE THREAD

**Issue by infusion** [processing/processing#4500]
Hi,

I'm on OSX 10.11.5 and have problems with stray Java processes. I was tinkering around a bit with Processing and have dozens of old processes lingering around (nothing special, some basic shapes):

![image](https://cloud.githubusercontent.com/assets/197742/15453804/36d2443c-2023-11e6-9de0-1eceb0037ec9.png)

I can't kill these processes with OSX tools. They don't appear in `ps -ef` or the Activity Monitor and as such, I can't kill them manually. `killall Dock` did the job now, but that's nasty.

Thanks

**Comment by infusion** [comment]
It seems, it's not necessarily Processing, but Java 1.8.0_92, I installed for Processing to work. I have similar trouble with Netbeans and other programs. `killall` was just a little fix, as it continues to run in the background.

**Comment by monkstone** [comment]
I understand that since MacOS 10.8 pgrep and pkill are available per default, so solution might be to:-
```bash
pgrep java
pkill -s KILL xxxx # where xxxx is proc number works on linux when all else fails
```

**Comment by benfry** [comment]
Why are the processes around? Did you close their windows and they stayed in the dock? What's in the sketch?

**Comment by oolong32** [comment]
I have the same issue. A ‘play button icon’ shows up in the dock when running a sketch (e.g. one of the samples) and stays there after stopping. It doesn’t matter whether one stops it with the ‘stop button‘ or by clicking on the ‘x’. The processes are not to be found, neither with `ps`, `pgrep`, nor with the ‘activity monitor’. `killall Dock` doesn’t help in my case.

* Processing Version "3.1.2"
* Java Version "1.8.0_102"
* OS X "El Capitan 10.11.5"
 
There is this unresolved [thread](https://forum.processing.org/two/discussion/17172/java-does-not-quit) in the processing forum.

**Comment by benfry** [comment]
I've never seen this. 

So again:
> Why are the processes around? Did you close their windows and they stayed in the dock? What's in the sketch?

I need something to work from before I can help.

**Comment by infusion** [comment]
I think it's a general Java problem on my computer and I have no idea how to fix it yet. It started when I upgraded to the latest version for processing, so I thought it is processing. But other Java apps like Netbeans suffer the same since then. I re-installed the whole Java setup already, without success. So it might be the wrong address here and the ticket can be closed.

**Comment by benfry** [comment]
Let us know if you find anything.
