### ISSUE TITLE
Java error when launching on OS X 

### ISSUE THREAD

**Issue by paul-mc** [processing/processing#4503]
I'm getting the following error when launching v3.1.1 (or v3.1) for the first time on OS X (10.11.5):

<img width="906" alt="screen shot 2016-05-22 at 22 58 14" src="https://cloud.githubusercontent.com/assets/1164753/15456738/bd0a1f72-2071-11e6-8158-8c44444ab307.png">

thanks

**Comment by JakubValtar** [comment]
@paul-mc Did you have other versions of Processing installed before (like 3.0 or 3.0 betas)?

@benfry This looks like Processing is trying to use old eclipse jars. Do you have any idea how this could happed on OSX?

**Comment by paul-mc** [comment]
@JakubValtar No, I've run Processing on other laptops before (v2 and v3), but this is the first time trying on the MacBook Pro.  

Are the eclipse jars included in the install package or are there other requirements?  Can I remove/upgrade the old versions?

thanks for your help,

Paul

**Comment by paul-mc** [comment]
I've installed the latest v2 and that works.  Still no joy with any of the v3 builds though.

Any further advise would be appreciated.

thanks

**Comment by benfry** [comment]
Should be fixed with 3.2, more here https://github.com/processing/processing/issues/4608
