### ISSUE TITLE
transmit video frame to LED

### ISSUE THREAD

**Issue by mkeyno** [processing/processing#4504]
I have Idea and really appreciated for any comments comments 
 Actually I intend to send the video frame from processing on my laptop to couple of ESP node through my home wifi-modem , each ESP has couple LED strip attached to it and processing slice the frame and add node IP address to each of them and transmit to those , can I have your idea which following way is fast and reliable

plain TCP?
UDP?
server websocket of processing and client websocket on ESP node?
client websocket of processing and server websocket on ESP node?
does lib websocket  support multiple websocket connection at the time ?
if we consider screen of 6060 LED we should deliver 6060*30 byte less than 40ms (25 fps)

**Comment by gohai** [comment]
@mkeyno This is a bug tracker for Processing, not a place for general discussion. Have a look at the Processing Forum.

**Comment by mkeyno** [comment]
so sorry for that but you may aware most guys immigrate from processing forum to github , like most other open source project
