### ISSUE TITLE
Processing 3.1.1 IDE graphics issue with AMD drivers/hardware

### ISSUE THREAD

**Issue by kingkaffeine** [processing/processing#4509]
Hi,
I am encountering a problem which prevents me from running processing. Right after processing starts, when I hover mouse pointer over the menus, the content of menus and the IDE enviroment mix together in some sort of graphical glitch. Problem does not go away with refreshing or re-sizing the window. It only gets worse.

I have attached some screenshots here:
http://imgur.com/dVP8j2Q
http://imgur.com/RStVBas
http://imgur.com/URrkOLZ
http://imgur.com/FVtxC61

My PC specs are:
Windows 7 ultimate 64bit SP1
Intel core i7 6700 3.4GHz
Kingston HyperX Fury Black 16GB DDR4 2133 MHz
AMD Radeon R9 380 4GB DDR5
ASUS MAXIMUS VIII HERO

Graphic drivers are up to date.
I must say that I uninstalled all of my graphics drivers (adapter went back to Standard VGA) and Processing worked with no problems; however as soon as I installed them again the problem appeared.

**Comment by SkydeFR** [comment]
Hi,

I've got the same problem, how to solve it ? (I've got NVIDIA Drivers)

**Comment by benfry** [comment]
It's a graphics driver problem. We couldn't make your window look like that even if we tried. Not something we can fix, unfortunately.
