### ISSUE TITLE
Parsing of nested generics

### ISSUE THREAD

**Issue by zhaar** [processing/processing#4514]
Consider the following code:

```
class Three<A, B, C> {}
class Two<A, B> {}
class One<A> {}
Two<One<One<Integer>>, Integer> fn = null;
```

The processing pre-processor give us the error "Maybe too many >characters" even though the type signature is correct at line 4.

Interestingly enough both of those compile correctly:

```
Two<One<One<Integer> >, Integer> fn = null;
Two<Integer, One<One<Integer>>> fn = null;
```

Trying with `Three` gives us those results:

```
Three<One<One<Integer>>,Integer, Integer> fn = null; //doesn't compile
Three<Integer,One<One<Integer>>, Integer> fn = null; //doesn't compile
Three<Integer, Integer, One<One<Integer>>> fn = null; //compile
```

There definitely is a problem with how processing parses intermediate Type arguments.
tested with processing 3.1.1

**Comment by JakubValtar** [comment]
Hi @zhaar, thanks for the report. This is a limitation of current ANTLR-based preprocessor and will be fixed when our plan to replace it by JDT-based preprocessor becomes a reality.

**Comment by benfry** [comment]
Fixed with https://github.com/processing/processing4/pull/1 and continued development happening at https://github.com/processing/processing4
