### ISSUE TITLE
getSettingsFolder() How can I define settings folder in Processing 3?

### ISSUE THREAD

**Issue by pyy** [processing/processing#4516]
Hello,

I'm now trying to define the setting folder instead using system's default setting folder in Processing 3, in order to separate from Processing 2 's setting folder.

I find this function was removed in Processing 3 after commit at https://github.com/processing/processing/commit/afe12e995b7a732b3007a6d41c33e043cff5d40d#diff-b6fda0bf6be0a53c0741a9b02ac16f37 . 

I try to add `settings.path` function back at file  `app/src/processing/app/Base.java`  as showing below in:

```
static public File getSettingsFolder() {
    File settingsFolder = null;

    String preferencesPath = Preferences.get("settings.path"); //$NON-NLS-1$
    settingsFolder = new File(preferencesPath);

    return settingsFolder;
}
```

and add `settings.path=./data` at defaults.txt and create the folder `data` under processing folder manually. 

It builds well, no errors. But when I run processing.exe, it get error like cannot find setting folder.

![capture](https://cloud.githubusercontent.com/assets/4225935/15675036/3ddce682-2740-11e6-9dfa-f0f42e3b74cf.PNG)

Should I change other files?

I can change setting folder in Processing 2, but how can I change the setting folder in Processing 3? I know it will be easy to always use a static setting folder. But if it comes out Processing4, how to solve the setting file conflicting problem with Processing3? 

Thank you.

**Comment by benfry** [comment]
Please don't change this. It would be an absolute nightmare to have people messing with the location of files and folders like this. It's difficult enough just with the number of default configurations people have between versions of Windows, Linux, and Mac OS.
