### ISSUE TITLE
PShape in 2D have problem with argb colors.

### ISSUE THREAD

**Issue by ingrossod** [processing/processing#4521]
Hi,
I noticed that making whatever shape using a transparent color as fill (argb), it will draw correctly the edges, but will produce an approximate fill that doesn't bind correctly with the edges.

Here a sample image:
![boxes](https://cloud.githubusercontent.com/assets/17088880/15764438/361de1c0-292b-11e6-9c1f-35dd55a19c78.png)

Almost all the boxes are correctly drawn...
Only the light blue boxes are transparent and, as you can see, the body doesn't properly bind with the edges.

**Comment by codeanticode** [comment]
What renderer are you using, default (JAVA2D), FX2D, or P2D?

**Comment by benfry** [comment]
Closing; no response for 5 months.

**Comment by ingrossod** [comment]
The default one, Java2D
