### ISSUE TITLE
Mac IDE font aliasing issues when moving the editor from a retina to a non-retina screen

### ISSUE THREAD

**Issue by cyle** [processing/processing#4526]
I'm using Processing 3.1.1 on a Retina MacBook Pro running El Capitan 10.11.5. When I have my macbook hooked up to a non-retina second screen, and I move a Processing IDE window from the retina screen over to the non-retina screen, the font aliasing in the editor window gets really bad, probably because it's expecting the pixel density of the retina screen since that's where the window was first instantiated.

Not sure how easy it is to tell from the provided screenshot, but here's an example:

![screen shot 2016-06-04 at 10 58 09 am](https://cloud.githubusercontent.com/assets/770158/15800301/4800bba6-2a43-11e6-9852-8631815361f0.png)

When I move the window back to the retina screen, it looks properly aliased again.

**Comment by benfry** [comment]
Hm, not sure if we can fix this one. I don't think we get any sort of event when the window moves to another screen. We'd have to track each movement event, figure out that it's been moved, and re-open the editor window.

**Comment by cyle** [comment]
Right now it looks like all new Processing windows open on the same monitor (the primary one) -- would it be possible to attempt to open a new window on the monitor that the last one is currently in? That way I could open Processing, drag the empty sketch to the secondary non-retina monitor, and then open my actual project, and it'd open on the non-retina monitor with the correct pixel density.

Maybe that's ridiculous. I dunno. I understand that this is weird edge case.

**Comment by benfry** [comment]
Closing this since we don't get notified when moving between retina/non-retina displays. The window opening issue is covered here: https://github.com/processing/processing/issues/1566
