### ISSUE TITLE
Licencing issue with Eclipse code

### ISSUE THREAD

**Issue by GKFX** [processing/processing#4528]
While working on issue #4266 (Debian distribution), I was looking into the licences Processing used, and discovered the following statement [by Eclipse](https://eclipse.org/legal/eplfaq.php#GPLCOMPATIBLE).
>*Are the Eclipse Public License (EPL) and the General Public License (GPL) compatible?*
>The EPL and the GPL are not compatible in any combination where the result would be considered either: (a) a "derivative work" (which Eclipse interprets consistent with the definition of that term in the U.S. Copyright Act ) or (b) a work "based on" the GPL code, as that phrase is used in the GPLv2, GPLv3 or the GPL FAQ as applicable. Further, you may not combine EPL and GPL code in any scenario where source code under those licenses are both the same source code module.
>
>Based upon the position of the Free Software Foundation, **you may not combine EPL and GPL code in any scenario where linking exists between code made available under those licenses**. The above applies to both GPL version 2 and GPL version 3. 

I believe package processing.java is GPL, and the Eclipse libraries are EPL, and processing.java links to those libraries. Is this legal?

**Comment by benfry** [comment]
My understanding is that as long as we're not mingling source, we're ok. We're linking against the binary libraries, but if we were to modify them in some fashion, that'd be a whole other can of worms.

**Comment by GKFX** [comment]
Okay, thanks for reassuring me.

**Comment by neilcsmith-net** [comment]
@GKFX @benfry Just saw this linked from the Debian packaging issue.  This situation doesn't sound strictly legit unless the GPL license for Processing includes a specific EPL linking exception.  This is nothing major, assuming all GPL licensed code in Processing is part of Processing.  If there are third-party GPL licensed files then this could be much more of a problem.
