### ISSUE TITLE
Cannot run Python example with `java.security.ProtectionDomain` error.

### ISSUE THREAD

**Issue by Spaxe** [processing/processing#4529]
Referring to https://github.com/jdf/processing.py/issues/208.

The error occurs on 3.1.1, but not version 3.0.1. I suspect there is something that Jython requires that is inaccessible in 3.1.1.

**Comment by GoToLoop** [comment]
This was also reported here, but for Java Mode: https://github.com/processing/processing-docs/issues/436
Up till version 3.0.2 no `java.security.ProtectionDomain` was thrown.
But something very wrong happened to P3.1.1. 
Here's the problematic code from the link above adapted to Python Mode:

```python
'''
 ' SelectInput() for loadImage() in settings() (v1.0)
 ' GoToLoop (2016-Jun-09)
 '
 ' forum.Processing.org/two/discussion/16705/
 ' null-pointer-exception-when-loading-image-in-settings-p3-1-1#Item_1
 '
 ' https://GitHub.com/processing/processing/issues/4529
'''

canvas = None

def settings():
    selectInput('Please select canvas picture:', 'selectImage')
    print 'awaiting...' # needed for P3.1.1
    while not canvas: delay(1000)

    size(canvas.width, canvas.height)
    noSmooth()
    noLoop()

def draw(): background(canvas)

def selectImage(f):
    if not f and f.isDirectory():
        print "Window was closed or you've hit cancel.\n"
        System.exit(0)

    canvasPath = f.getPath()
    print canvasPath

    global canvas
    canvas = loadImage(canvasPath)

    if not canvas:
        print 'is invalid image file. Try again...\n'
        selectInput('Please select canvas picture:', 'selectImage')
```

**Comment by Spaxe** [comment]
Thanks @GoToLoop. I had thought it was a Python/Jython issue.

Hope someone can shine some lights.

**Comment by DominusDodo** [comment]
Revision 0251 seems to work fine, but not the current 3.1.1 (rev. 0250).

**Comment by Spaxe** [comment]
Thanks to @DominusDodo, this can be tracked with https://github.com/processing/processing/pull/4547
