### ISSUE TITLE
Cannot load a jsonp response

### ISSUE THREAD

**Issue by igarbla** [processing/processing#4531]
I have a sketch in which i load a json file from an url in the internet with no problem but i was having issues with that response in p5.js, so after investigating the issue and find the posible solution i asked the provider of the dataset to apply the changes. So they did and fixed the issue and now my p5.js sketch works.
They wrapped it in a callback function but now my processing sketch crashes because the loadJSONArray() function expects an array.

Any idea on how to load a jsonp response in Processing?

Thank you

**Comment by cchan** [comment]
Could you provide example code? Not sure what you mean.

**Comment by igarbla** [comment]
Hi @cchan , the response wrapps the json data in a callback function. See this url: http://opendata.euskadi.eus/contenidos/ds_recursos_turisticos/pueblos_euskadi_turismo/opendata/pueblos.json

**Comment by cchan** [comment]
Oh. JSONP is designed very specifically for the cross-origin XMLHTTPRequest workaround in which you load JavaScript in a <script></script> element with a callback to give you the data. Processing shouldn't be able to load JSONP unless you do some string pre-processing to remove the padding and end up with a plain JSON string. How come it didn't work with the plain JSON originally?

**Comment by cchan** [comment]
You can try
```java
String json = jsonp.substring(jsonp.indexOf("(") + 1, jsonp.lastIndexOf(")"));
```

**Comment by cchan** [comment]
(in any case, this isn't an issue with Processing, so you should close this issue and ask on StackOverflow or something if you have more questions)

**Comment by igarbla** [comment]
Thank you @cchan, i agree with you and is probably the best solution.
