### ISSUE TITLE
No Display Window

### ISSUE THREAD

**Issue by Analytics12345** [processing/processing#4532]
I am sure this is a newbie question but after watching the hour introduction training video and spending some time in the entry level tutorials I decided to download processing.

I can not however seem to get my display window to show up!

Is there some other settings or box I need to select in order to get my display window to show up?

As a beginner I was only trying to get the simple code lines to run.

Thanks in advance for you help!!!

-Matt
_____________________________
void setup() {
  size(480, 120);
}

void draw() {
  if (mousePressed) {
    fill(0);
  } else {
    fill(255);
  }
  ellipse(mouseX, mouseY, 80, 80);
}

**Comment by StanLepunK** [comment]
Your code work perfectly, but I think the Processing forum is better for you.
https://forum.processing.org/two/
