### ISSUE TITLE
Net library: Connect has long timeout when no server is available (20sec freeze)

### ISSUE THREAD

**Issue by Paul-Ver** [processing/processing#4533]
I'm using the processing net library to connect to a server.

The user can connect to the server by pressing a button.

However, if the server is not available, the whole application freezes for about 20seconds.
The constructor for Client should have an (optional) argument for the timeout.
Or shouldn't completely freeze the application.

(I can't guarantee the server to be online, this will be an ethernet connected "robot", it could be out of battery.)

**Comment by benfry** [comment]
To prevent the application from freezing, you need to run the connection code in another thread. A simple way to do this is with a function that's called using the `thread()` command. Or you can read up on how threads are implemented in Java to do something more sophisticated: https://docs.oracle.com/javase/tutorial/essential/concurrency/
