### ISSUE TITLE
Cannot open previous version while newer version open

### ISSUE THREAD

**Issue by gdsentropy** [processing/processing#4534]
There is an old sketch 33444 which uses controlp5, which does not work with p3...so I have p2 in a folder. If I try to open its exe p3 opens instead. Why? What good does that do? Who decided this? Not cool. Do not contradict the will of the user.

Clarification:
I can open older versions only if there are no newer versions open at the time, otherwise only latest versions open. This is really annoying.

**Comment by benfry** [comment]
Only one copy of the application can be run at a time. The old and new versions share settings and sometimes even a sketchbook, which will cause weird problems if they're both running simultaneously.
