### ISSUE TITLE
Windows Volume Mixer Graphics bug

### ISSUE THREAD

**Issue by yousifucv** [processing/processing#4536]
This is a weird one. On three different Windows 7 machines, the volume mixer for the processing window has a weird graphics bug. You can still adjust the audio, you just have to estimate where the volume handle is and drag it.
![untitled](https://cloud.githubusercontent.com/assets/5132105/16030494/831ba0b0-31bf-11e6-8b4f-955c21461d95.png)

**Comment by cchan** [comment]
[No issue for me on Windows 10; maybe it's just a Win7 issue.]

In any case, I think this is more a problem with the [Processing Sound library](https://github.com/processing/processing-sound). No volume mixer icon shows up unless I've installed and `import`ed the processing.sound library, and so it seems that the icon is provided with that library.

**Comment by benfry** [comment]
Moved to https://github.com/processing/processing-sound/issues/88
