### ISSUE TITLE
PVector.equals() doesn't return true when fields in both objects are NaN

### ISSUE THREAD

**Issue by mguenther64** [processing/processing#4537]
There's a subtle flaw in `PVector`'s implementation of `equals()`. As it is currently written, the `float` fields x, y, and z are tested for equality using the `==` operator. This is fine for almost all float values, but several like `Float.NaN` and `-0.0f` can cause problems. For instance, when `Float.NaN` is tested against itself using `==` it returns `false`.

``` java
//evaluates as false so never prints
if (Float.NaN == Float.NaN)
{ System.out.println("numbers are equal"); }
```

Float values in overriden `equals()` implementations should be tested for equality either by using `Float.compare()` or `Float.floatToIntBits()` to get around this.

``` java
//this is fine, if semantically inferior
if ((Float.compare(this.x, that.x) == 0) &&
    (Float.compare(this.y, that.y) == 0) &&
    (Float.compare(this.z, that.z) == 0)
{ return true; }

//this works too and is more semantically accurate, but is a little verbose
if (Float.floatToIntBits(this.x) == Float.floatToIntBits(that.x) &&
    Float.floatToIntBits(this.y) == Float.floatToIntBits(that.y) &&
    Float.floatToIntBits(this.z) == Float.floatToIntBits(that.z))
{ return true; }
```

If `PVector` were immuatable or if it protected it's fields with accessors and mutators, you could reject or mutate troublesome assignments to x, y, and z. However, since x, y, and z are not encapsulated,
users are free to assign `Float.NaN` or other tricky values to them and the `==` operator can not be used safely.

I haven't looked through the source code of other Processing classes that override equals, but this bug may be present in other places as well. BTW, the same issue hold true for `double` values.

See https://stackoverflow.com/questions/3667932/why-use-float-floattointbits-in-java-float-comparisons and
https://stackoverflow.com/questions/8819738/why-does-double-nan-double-nan-return-false for more discussion.

**Comment by cchan** [comment]
I'm fairly certain that NaN equality with itself is _supposed_ to be false.

**Comment by mguenther64** [comment]
You're absolutely right that `Float.NaN == Float.NaN` is supposed to evaluate `false` according to JLS ([https://docs.oracle.com/javase/specs/jls/se7/html/jls-4.html#jls-4.2.3](url)) due to the way `NaN` is calculated in the IEEE 754 standard. However,  when used in `equals()` comparisons `NaN == NaN` is supposed to evaluate to `true` because otherwise hash tables that store objects with "significant" `float` fields won't operate properly. See the Java source code and documentation information: [http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/lang/Float.java#Float.equals%28java.lang.Object%29](url).

**Comment by benfry** [comment]
I think the general user expectation would be that `NaN` values won't equal (in consideration with how `PVector` is actually used, and introducing six `Float.floatToIntBits()` calls just to solve an edge case of an edge case (in a way that may be unexpected anyway) strikes me as a direction we'd rather avoid.
