### ISSUE TITLE
Unexpected behavior using soft links on Linux

### ISSUE THREAD

**Issue by marqrdt** [processing/processing#4538]
Hi,
    A common practice in creating external configuration files (XML in this case) is to create multiple files and create a soft link to the desired file. Here is an example:
cd data
ls -l
-rw-rw-r-- 1 marqrdt marqrdt 270 Jun 16 20:43 parameters-live.xml
-rw-rw-r-- 1 marqrdt marqrdt 270 Jun 16 20:27 parameters-test.xml

// Create a soft link from parameters-test.xml to parameters.xml
ln -s parameters-test.xml parameters.xml

ls -l
-rw-rw-r-- 1 marqrdt marqrdt 270 Jun 16 20:43 parameters-live.xml
-rw-rw-r-- 1 marqrdt marqrdt 270 Jun 16 20:27 parameters-test.xml
lrwxrwxrwx 1 marqrdt marqrdt  19 Jun 16 19:12 parameters.xml -> parameters-test.xml

In my Processing code, I reference the soft link:
String XMLconfigFile = "parameters.xml";
   XML params =  loadXML(XMLconfigFile);

This produces an error on Linux using Processing 3.1.1:
This file is named parameters-test.xml not parameters.xml. Rename the file or change your code.

I would expect the soft link to be invisible to Processing.
I may be wrong but would like to understand the behavior.

Thanks,

Paul

**Comment by hamoid** [comment]
I searched in the Processing source code and found it here: https://github.com/processing/processing/blob/9bafe4c0c2d6c80331128b53be53521ae50a2740/core/src/processing/opengl/PSurfaceJOGL.java#L560

It seems like an attempt to detect file names with wrong (upper/lower) case characters with the unexpected side effect you discovered.

**Comment by benfry** [comment]
Yeah, that dates to when Java had no support for determining whether something was a symlink (and a much larger issue was people—mostly new users who'd be hit the worst—messing with capitalization). If you think we should change it to allow symlinks, please file a new issue so we can mark it as an enhancement.
