### ISSUE TITLE
gtsvideo video library on kubuntu 16

### ISSUE THREAD

**Issue by ricardoglez** [processing/processing#4539]
im trying to run a sketch using the video library of Processing and openCV with an external webcam. Im runnig processing 3.02 on Kubuntu 16, i used this sketch with the same setup Wednesday,and im tryng to running now but it doest run well,  i am  gettin this message in the console :
__** (Processing core video:25895): WARNING **: gstvideo: failed to get caps of pad rgb:sink__

Ive checked if the capture objet is available and it says that is false, so i dont get where is issue i have  my start and read functions are initialized before the error has shown

**Comment by gohai** [comment]
This belongs here: https://github.com/processing/processing-video
