### ISSUE TITLE
Add resize() method

### ISSUE THREAD

**Issue by cchan** [processing/processing#4540]
This probably has been mentioned before, but I couldn't find any similar github issues and I thought I would mention it.

The following variable-sizing code seems to work fine. I'd assume there's some significant overhead associated with surface.\* functions, but since it's only supposed to be used on setup anyway it's alright.

```
void size2(int w, int h){
  surface.setResizable(true);
  surface.setSize(w, h);
  surface.setResizable(false);
}

void setup() {
  int w = round(random(200, 500));
  int h = round(random(200, 500));
  size2(w, h);
}
```

**Comment by DominusDodo** [comment]
A quick sketch cycling through 100 of your setup calls a frame takes ~300ms or less a frame. That's about 3ms per resize, which seems perfectly reasonable for a single call. I don't know if there are any reasons against implementing a function like this. Perhaps a function like this:

```java
public void resize(int w, int h) {
  surface.setResizable(true);
  surface.setSize(w, h);
  surface.setResizable(false);
}
```

**Comment by usser123** [comment]
Using setResizable() and setSize() did not work with P3 renderer. I get NullPointerException error after resizing. This occurs when I try to access pixels array. It seems like after resizing, the pixels array is not accessible because the program fails at location 0.

**Comment by benfry** [comment]
This issue is resolved with `windowResize()` and the other `windowXxxx()` methods in Processing 4.

Download it here: https://github.com/processing/processing4/releases
