### ISSUE TITLE
text not clear

### ISSUE THREAD

**Issue by Diex** [processing/processing#4541]
"You are running Processing revision 0227, the latest build is 0250."

I want to keep my processing version up to last 2.x.x release.

should say something like: ""You are running Processing 2 (rev 0227), the latest build is Processing 3 (rev 0250)."

I do not know if it is an issue or not. :)

**Comment by benfry** [comment]
I can't go back in time and change the Processing 2 release that's already installed on your computer.

**Comment by Diex** [comment]
good point. :)

**Comment by benfry** [comment]
And I appreciate your confidence in me, that I'd have such otherworldly powers.
