### ISSUE TITLE
args[] array is null when running from PDE in 3.1.1

### ISSUE THREAD

**Issue by xenobytezero** [processing/processing#4543]
I had a Processing 2 (Windows) application that would take command line parameters using the `args[]` array. When running from the PDE after updating to 3.1.1, the `args[]` array is null.

```
void setup() {
  size(200,200);
  surface.setResizable(true);
  
  println("Sketch Path - " + sketchPath());
  println("Arguments - " + args.length);
  
  for(int x = 0; x < args.length; x++){
    println("Arg # " + x + " - " + args[x]);
  }
}
```

The above code fails with `java.lang.NullPointerException` on `args.length`

**Comment by benfry** [comment]
The `args[]` array will always be null when run from the PDE, because you can't pass any parameters to an application inside the PDE.
