### ISSUE TITLE
comment/uncomment keyboard doesn't work

### ISSUE THREAD

**Issue by cjdg** [processing/processing#4544]
Im using Ubuntu Studio 16.04 and i cant use the key shortcut to comment uncomment

**Comment by benfry** [comment]
Is this your problem? https://github.com/processing/processing/issues/2199

I'm not familiar with Ubuntu Studio, so I don't know if that's causing the issue.

**Comment by cjdg** [comment]
Yeap! that one, but it seems fixed on 3.1.2 it works now !
