### ISSUE TITLE
NullPointerException at PApplet.java:7411 in versions 3.*

### ISSUE THREAD

**Issue by DavidDReimann** [processing/processing#4545]
I am running Processing from Java, specifically the Dr. Java IDE with JDK 8.0_45.  When any PApplet starts, I get a NullPointerException as follows:
_java.lang.NullPointerException
	at processing.core.PApplet.calcSketchPath(PApplet.java:7411)
	at processing.core.PApplet.runSketch(PApplet.java:10138)
	at processing.core.PApplet.main(PApplet.java:10024)
	at P3Error.main(P3Error.java:5)_

Here is the Java code:
```java
import processing.core.*;

public class P3Error extends PApplet {
  static public void main(String args[]) {
    PApplet.main(new String[] {"P3Error" }); // ERROR IS HERE
  }  
  
  public void settings() { 
    size(100, 100); 
  } 
  
  public void setup () {
  }
  
  public void draw () {
    line(10,10,90,90);
  }
```

This error occurs for me with the following versions: 3.01, 3.02, and 3.1.1.  No error occurs with version 2.2.1.

**Comment by hamoid** [comment]
Your sketch runs fine without any changes on my system from both Eclipse 4.6.0 and IntelliJ Idea 2016.2. Processing 3.0.2 and 3.1.1 on Linux, JDK 8.0_92.

**Comment by benfry** [comment]
Something is weird with your IDE, since it's not properly setting the location of the class files; it's dying inside this code: 
```

      URL jarURL =
          PApplet.class.getProtectionDomain().getCodeSource().getLocation();
      // Decode URL
      String jarPath = jarURL.toURI().getPath();
```
Not really something we can "fix," though, since it's your IDE causing the problem.
