### ISSUE TITLE
random(low, high) can return high

### ISSUE THREAD

**Issue by atgeflu** [processing/processing#4551]
On the Processing.js github an [issue](https://github.com/processing-js/processing-js/issues/244) was opened, that `random(low,high)` can return `high `when the interval `low .. high` is sufficiently small.

I thought that this might only be a Processing.js issue, but Processing (and P5.js) seem to be affected as well. (I've opened an issue for P5.js as well).

I guess this use case should be rather rare, but I thought you might still like to know about this issue.

Code example:
```

float answer;
int found1 = 0;
float myLow = 0.9999; 
int trials = 100000;

for (int i = 0; i < trials; i++) {
  answer = (random(myLow,1.0));
  if (answer >= 1) {
    found1++;
  }
}

println("highs found: " + (found1) + " (correct): " + (trials-(found1)));
```

**Comment by benfry** [comment]
Ha, that's funny... It was implemented properly for the random(1) case but not the range. Now fixed for 3.1.2.
