### ISSUE TITLE
Sound Library Not Working On Linux (Ubuntu)

### ISSUE THREAD

**Issue by toliaferrode** [processing/processing#4553]
Getting back into Processing after a hiatus.

Sound library installs and the error says something different than what it used to say so I guess that's progress. It used to say that the library wasn't installed, but now I get this error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  RtApiAlsa::probeDeviceOpen: pcm device (hw:0,3) won't open for input.
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help → Troubleshooting.

**Comment by gohai** [comment]
@toliaferrode Could you submit this here: https://github.com/processing/processing-sound/issues
