### ISSUE TITLE
all is too small in non Hi-DPI 4K (28") display pannel

### ISSUE THREAD

**Issue by sl1pkn07** [processing/processing#4562]
downstream bug: https://github.com/ShikOfTheRa/scarab-osd/issues/259

https://forum.processing.org/two/discussion/comment/70613/#Comment_70613

![](http://wstaw.org/m/2016/07/05/Screenshot_20160705_215020.png)

**Comment by benfry** [comment]
We can only use the OS settings for scaling. You're using a nonstandard display/setup, we don't have a way to manually override this sort of thing (and it's not possible anyway, within Java).

**Comment by sl1pkn07** [comment]
is not possible set the size of font manually (and make the UI scalated with it)?
