### ISSUE TITLE
UnsatisfiedLinkError: no t2k in java.library.path on startup

### ISSUE THREAD

**Issue by Throatsinger** [processing/processing#4566]
Hi, I just downloaded the program for Mac 10.11.2 (15C50) and it either won't open or crashes on start up with this error: 
![screen shot 2016-07-08 at 12 52 52 pm](https://cloud.githubusercontent.com/assets/20360567/16696812/3bf459d8-450c-11e6-9242-3c41a028fb7f.jpg)

Please advise, thanks.

**Comment by benfry** [comment]
This is with the latest version of the software? That's complaining that it's somehow missing a file that's embedded in the download. Have you modified the application in any way?

**Comment by benfry** [comment]
Should be fixed for Processing 3.2, see #4608
