### ISSUE TITLE
Contribution Manager, Update Status, visual glitch (minor)

### ISSUE THREAD

**Issue by mkmori** [processing/processing#4571]
Minor issue related to issues #4105, #4154, & #4229....

Processing 3.1.1, Win 10, I'm experiencing a little visual hiccup in the Contribution Manager where update progresses normally, (through download and install, per the bottom status panel), but the wheel icon in the Status column does not change to the green checkmark until one clicks away from, and then back on, the updated contribution.

_Might_ be restricted to 

(So...no, not as big a problem as the "gym glitch" in Pokémon Go....)

**Comment by Akarshit** [comment]
Just to add information, I tested this on Linux and the wheel is changing into a tick there.

**Comment by mkmori** [comment]
Umm, so a very minor issue to begin with--I haven't been using the IDE much lately, but just updated everything in 3.5.4: No spinning icons at all, but got green check marks afterwards, so I'm going to go ahead and close this issue....
