### ISSUE TITLE
the background goes from gray to blue

### ISSUE THREAD

**Issue by ronca85** [processing/processing#4574]
Here, https://processing.org/tutorials/interactivity/ under Mouse events the example shows a background color that changes into a more and more light gray, then white, then back to black and then - blue! Why is that?

**Comment by hamoid** [comment]
That's not a Processing bug, but it may look confusing and could be mentioned in that example.

In Processing all 16.777.216 possible colors are represented as different integers. What happens in that example is that you are "scanning" through the palette of all possible colors when increasing that integer value. The first 256 colors are black > gray > white. Other colors follow. What makes it more confusing I guess is that the variable is called "gray". To keep the variable name valid an ```if(gray > 255) { gray = 255; }``` would help

**Comment by benfry** [comment]
Moved here https://github.com/processing/processing-docs/issues/457
