### ISSUE TITLE
Wav file causing error after upgrade to P3

### ISSUE THREAD

**Issue by kdragon87** [processing/processing#4576]
The code ran fine in P2 as soon as I moved to P3 it now throws this error:
 fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00000001275fa547, pid=1128, tid=0x000000000000e34f
#
# JRE version: Java(TM) SE Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libsndfile.1.dylib+0x2547]  psf_open_file+0xc3
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/kurtvega/hs_err_pid1128.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by benfry** [comment]
If you're having a problem with the sound library, please file a bug here: https://github.com/processing/processing-sound with some details about what's going on.
