### ISSUE TITLE
Cannot use loadImage() inside settings()

### ISSUE THREAD

**Issue by dvschultz** [processing/processing#4579]
prior to latest version, this worked (using a loaded image to determine size of sketch):

```
PImage img;

void settings() {
  img = loadImage("test.png");
  size(img.width,img.height,P2D);
}

```

as of latest version this returns a `NullPointerException` at line 4.

**Comment by dvschultz** [comment]
nm. I see this was already closed. Bummer.

**Comment by hamoid** [comment]
The documentation about settings() mentions you should not call loadImage() inside it.

A work around here: https://github.com/processing/processing/wiki/Changes-in-3.0 (search for "surface.setSize"). There's already an issue to mention the surface functions in the documentation: https://github.com/processing/processing-docs/issues/55

**Comment by JakubValtar** [comment]
This should work. There was a bug in 3.1.1 which was fixed by https://github.com/processing/processing/pull/4505 in 3.1.2.
