### ISSUE TITLE
Too many popStyle() RuntimeException

### ISSUE THREAD

**Issue by ihsanyounes90** [processing/processing#4581]
I use several PGraphics objects to draw in off-screen buffering, the problem is that I every 5 minutes of debugging I get the following Exception.
I checked very carefully and my code doesn't miss any popStyle or doesn't have any extra pushStyle. I think the problem is regarding the events(because I use serveral PGraphics) and how processing process them.

Exception in thread "Animation Thread" java.lang.RuntimeException: Too many popStyle() without enough pushStyle()
	at processing.core.PGraphics.popStyle(PGraphics.java:6145)
	at processing.core.PShape.post(PShape.java:1430)
	at processing.core.PShape.draw(PShape.java:1593)
	at processing.core.PShape.drawGroup(PShape.java:1618)
	at processing.core.PShape.drawImpl(PShape.java:1603)
	at processing.core.PShape.draw(PShape.java:1592)
	at processing.core.PGraphics.shape(PGraphics.java:3995)
	at Element.display(Element.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1400)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1393)
	at processing.core.PApplet.handleMethods(PApplet.java:1587)
	at processing.core.PApplet.handleDraw(PApplet.java:2419)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1527)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

**Comment by hamoid** [comment]
How can the error be reproduced? Do you have a minimal sketch that produces this error?

**Comment by ihsanyounes90** [comment]
here is it. This causes processing always to crash:

```
import java.util.ArrayList;
import java.util.List;
import processing.core.PApplet;
import processing.core.PGraphics;
import processing.core.PShape;


public class TestMultiplePGraphics extends PApplet {

	public static void main(final String[] args) {
		main(TestMultiplePGraphics.class.getName(), null);
	  }

	
	PShape protein;
	List<PGraphics> graphics = new ArrayList<>();
	
	public void setup() {
		
		size(1024, 768);
		background(217,240,250);
		

        protein = loadShape("protein.svg");
       
		textMode(PApplet.MODEL);
		textFont(createFont("OpenSans-CondBold.ttf", 17, true));
		
			
		smooth();
		loop();
		
		for(int i=0 ; i < 5 ; i++){
			PGraphics graphic = createGraphics(200, 200);
			graphics.add(graphic);
		}
		
	}

	public void draw() {
		smooth();
		
		background(217,240,250);
		
		for(int i=0 ; i < graphics.size() ; i++){
			PGraphics graphic = graphics.get(i);
			
				redrawGraphic(graphic);
				
			double x = Math.random() * 1024;
			double y = Math.random() * 768;
			image(graphic.get(), (float)x, (float)y);
		}
		
		 //FrameRate
        fill(255);
        rectMode(PApplet.CORNER);
        rect(0,768-21,40,20);
        fill(24, 24, 24, 128);
        textAlign(PApplet.LEFT, PApplet.TOP);
        textSize(17);
        text(""+Math.round(frameRate), 12, 768-22);
	}
	
	public void mouseMoved() {
		
		System.out.println("mouse moved");
		super.mouseMoved();
		for(int i=0 ; i < graphics.size() ; i++){
			PGraphics graphic = graphics.get(i);
			
			
				redrawGraphic(graphic);
				
			
			loop();
			redraw();
		}
	}
	
	void redrawGraphic(PGraphics graphic){
		graphic.beginDraw();
			graphic.pushStyle();
				for(int i=0; i < 100 ; i++){
					double x = Math.random() * 200;
					double y = Math.random() * 200;
					
					graphic.clear();
		
					graphic.pushMatrix();
						graphic.scale(0.8f);
											
						graphic.shape(protein, (float)x, (float)y);
						
						graphic.textAlign(PApplet.CENTER, PApplet.CENTER);
						int textSize = 0;
						for(int g = 0; g < 100 ; g++){
							textSize+= graphic.textWidth("pp");
						}
						System.out.println(textSize);
						graphic.text("pp", (float)x, (float)y);
						
		
					graphic.popMatrix();
				graphic.popStyle();
			graphic.endDraw();
			
		}
		
	}
	

}
```

**Comment by benfry** [comment]
That `mouseMoved()` method is really problematic. That'll fire dozens (or hundreds) of times as you're moving the mouse, incessantly restarting the animation thread and forcing a redraw. One of those is going to collide. Use forum.processing.org to get some help on how to rewrite the sketch in a different way.

**Comment by ihsanyounes90** [comment]
I now the logic is heavy and not correct, but this was an example to show you that a mechanism of lock must be present on the PGraphics object to avoid this kind of problems.
In a complex situation (like my project) it's really difficult to understand where I must change the logic.
Thank you anyway.

**Comment by benfry** [comment]
I'm telling you that the problem is in the way your code is designed. It's not possible for us to structure Processing in a way that will save you from breaking your project this way. It needs to be written differently, but that's not a "bug" to be discussed here, so please use the Forum.
