### ISSUE TITLE
A fatal error has been detected -- glClearDepth+0xd

### ISSUE THREAD

**Issue by marqrdt** [processing/processing#4585]
I'm getting JVM crashes in Processing 3.1.1. The JVM log is attached. I'm running on a MacBook Pro Retina, 15-inch Mid-2015, with a AMD Radeon R9 M370X 2048 MB graphics card.

I've been able to isolate where the crash is occurring and reproducible scenarios where the crash both does and does not occur.

I wrote a method to reset my drawing:
void reset() {
    // make a new Fractal drawing
    // I tried wrapping the graphics calls in noLoop() and loop() methods to no avail.
    //noLoop();
    background(255);        // erase the previous drawing
    frac = new MyFractal();  // get a new set of values
    this.pg = createGraphics( this.screenX, this.screenY, P3D);
    setScale();
    //loop();
}

If I call the reset() method within a keyPressed() method, it does NOT crash and works 100% of the time:

void keyPressed(){
  // This never crashes
  else if(key=='c') {
    reset();
  }
}

If I call the reset() method within my own method processXMLConfig, it always crashes. In this case, processXMLConfig is called from within an MQTT callback:

  public void messageArrived(String topic, MqttMessage message) throws Exception {
    MqttReceivedMessage receivedMessage = (MqttReceivedMessage) message;
    String content = new String( receivedMessage.getPayload(), Charset.forName( "utf-8") );
    processXMLConfig( content );
  };

Here is the processXMLConfig method:

public void processXMLConfig( String xmlContent ) {
   XML params = parseXML( new String(xmlContent) );
   // Eliminating null checks for brevity...
   // Calling reset() from here always crashes.
   child = params.getChild("reset");
   if ( child != null ) {
     reset();
   }
}

I hope this distinction gives some insight into the problem. I've seen other unsolved problems relating to this call.

[hs_err_pid67824.log.txt](https://github.com/processing/processing/files/382736/hs_err_pid67824.log.txt)

Thanks,
Paul

**Comment by marqrdt** [comment]
After some experimenting, I've found that I get a crash any time I execute any graphics code inside the messageArrived() method in my MQTTCallBack implementation. These calls include:
saveFrame();
background(255);
clear();
The Processing MQTT library is the Eclipse Paho client:
http://www.eclipse.org/paho/files/javadoc/index.html

Again, if I call the same methods from inside a keyPressed() block, they never crash.

**Comment by benfry** [comment]
You can't draw from any random function like that... You can only draw from the `draw()` or `setup()` methods, or from mouse and key events (which take this threading issue into account).
