### ISSUE TITLE
Video playing slowly

### ISSUE THREAD

**Issue by Bradamante12** [processing/processing#4592]
I have a problem with HD videos 1920 x 1080, (40 seconds) don't playing correctly, playing very slowly. For correct play I must reduce at 50% this measure. I prove with .mp4 and .flv. This last have small files, around 8 Mb, but is slow too. My platform is Windows 8.1, 64 and processing 3.1.1
Thanks for any help.

**Comment by benfry** [comment]
Please file video issues here: https://github.com/processing/processing-video
