### ISSUE TITLE
Processing sound library not working

### ISSUE THREAD

**Issue by XyLoNaMiyX** [processing/processing#4601]
### Steps to reproduce
1. Open Processing `3.1.2` under a Linux distribution (tested on Xubuntu 16.04)
2. Paste the example sketch from https://processing.org/reference/libraries/sound/SoundFile.html
3. Add a `sample.mp3` file under the `/data` folder
4. Press run

### What should happen
The file `sample.mp3` should play

### What actually happens
→ _Could not run the sketch_
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  RtApiAlsa::probeDeviceOpen: pcm device (hw:0,3) won't open for input.
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help → Troubleshooting.
```

### What I've tried
I've tried editing `/etc/modprobe.d/alsa-base.conf` by adding `options snd-hda-intel index=-2` at the end as pointed in this [StackOverflow answer](http://stackoverflow.com/a/23256908/4759433 "How can I solve a conflict between openFrameworks and other audio applications?") but since it didn't work I decided to post it help, in case it useful for some people running into the same issue.

**Comment by XyLoNaMiyX** [comment]
Oh sorry! I found a duplicate https://github.com/processing/processing/issues/4553. Closing this!

**Comment by kmvtxx** [comment]
Having the same problem! Did you find a solution?

**Comment by Lonami** [comment]
Nope @kmvtxx, discussing it [here](https://github.com/processing/processing-sound/issues/81).

**Comment by Lordgoderic** [comment]
I gave up on them as this has been an issue for about a year or more.  I use the Minim library, it works fine.

**Comment by juberjj** [comment]
I'm using Fedora 27, same issue on my side. Possible solutions anyone?

**Comment by benfry** [comment]
This is the location for Sound Library issues: https://github.com/processing/processing-sound
