### ISSUE TITLE
value of parameter theMessage is not used

### ISSUE THREAD

**Issue by jazzisfaction** [processing/processing#4604]
Hey there,
my patcher always worked perfectly.
I have the line:
void oscEvent(OscMessage theMessage){
}
all of a sudden, i get a 'problem' message:
'the value of the parameter theMessage is not used.'
I updated Processing and P5 to the latest versions.
I'm not good enough in programming to know what is going on.
Please help if it is a bug.
Thanx

**Comment by Chromadude** [comment]
You can ignore that message. Presumably you are going to use the variable "theMessage" in that function at some point? If so then that message will go away when you do this. If not then just don't worry about the 'problem' message.

**Comment by benfry** [comment]
That's just a “warning,” not an error. It won't affect whether your code runs or not.
