### ISSUE TITLE
Move general PDE code from JavaMode into its own base classes

### ISSUE THREAD

**Issue by benfry** [processing/processing#4606]
The side gradient and other basic handlers should live in `processing.app` not the JavaMode classes.

From the source: 

> We're overriding more things in JEditTextArea than we should, which makes it trickier for other Modes (Python, etc) to subclass because they'll need to re-implement what's in here, but first wade through it. To fix, we need to clean this up and put the appropriate cross-Mode changes into JEditTextArea (or a subclass in processing.app)

**Comment by benfry** [comment]
Looks like the converse is also true... @JakubValtar it looks like `fetchPhrase()` and `parsePhrase()` have been added to `JEditTextArea` but they're specific to Java (or at least Java-like) languages, and don't belong in a general text area component. Am I missing something?

**Comment by JakubValtar** [comment]
Correct, there are bits of stuff here and there which need some cleaning. I didn't want to go down this rabbit hole last time because I was trying to focus on PDEX (and get it done).

**Comment by benfry** [comment]
Yup; not a critique—this is just moving my old TODO note from the top of the source into the issues list so that it's actually tracked.

**Comment by JakubValtar** [comment]
Not taken as a critique, I got a notification with you mentioning me and I was trying to answer that, though it seems you deleted it. Nevermind.

**Comment by benfry** [comment]
Sorry for the confusion.

**Comment by benfry** [comment]
Fixed for the next release (3.2).
