### ISSUE TITLE
PGraphicsOpenGL : camera info not updated

### ISSUE THREAD

**Issue by FreewheelinFranklin** [processing/processing#4609]
camera fields in PGraphicsOpenGL (cameraFOV, cameraX, cameraY, cameraZ, cameraNear, cameraFar, cameraAspect) are not updated by call to perspective(float fov, float aspect, float zNear, float zFar) or frustrum

**Comment by codeanticode** [comment]
Thanks for pointing out to this. We should have a set of protected default values that cannot be changed, and are set when the user calls perspective() w/out arguments, and the public ones that are updated with the latest camera info.
