### ISSUE TITLE
3.1.2 breaks sketch - splitLineCSV()

### ISSUE THREAD

**Issue by pushtheworldllc** [processing/processing#4611]
Working on 3.1.1, updated to 3.1.2 and broke my sketch because of `splitLineCSV`. Please see issue opened here https://github.com/OpenBCI/OpenBCI_GUI_v2.0/issues/22

**Comment by benfry** [comment]
`splitLineCSV()` is a protected method inside `Table`, was never documented, and its interface changed in 3.1.2 to properly support newlines. 

What's the bug?

**Comment by pushtheworldllc** [comment]
![screen shot 2016-08-10 at 1 36 25 pm](https://cloud.githubusercontent.com/assets/11437469/17573764/8726859c-5f2a-11e6-84e6-2de75a3f3703.png)

**Comment by benfry** [comment]
You're showing me a portion of your code running in the PDE. You're trying to use an undocumented method called `splitLineCSV()` whose interface has changed.

**Comment by pushtheworldllc** [comment]
Ok I'll open an issue on our end then @benfry. I did look in the change log and didn't see anything. I'm very new to processing and I didn't know public functions can change on a minor patch, in fact I'm new to the whole changing the IDE changes the core functions so I'll close and move on. Thanks for the fast response time!

**Comment by benfry** [comment]
No public function changed on a minor patch. This is the version from 3.1.1:
```
  static protected String[] splitLineCSV(String line) {
```
It looks like that code is trying to subclass the `Table` class, and again, made use of an undocumented—not public, but protected—function that has changed in 3.1.2. It wasn't `public` to avoid people using it.
