### ISSUE TITLE
java/bin/java: Syntax error: end of file unexpected (expecting ")") on Linux x64

### ISSUE THREAD

**Issue by mskogly** [processing/processing#4612]
Getting this error on ubuntu.

mskogly@stav4:~$ processing
mskogly@stav4:~$ /opt/Processing/3.1.2/java/bin/java: 1: /opt/Processing/3.1.2/java/bin/java: Syntax error: end of file unexpected (expecting ")")

**Comment by benfry** [comment]
Working fine here; have you modified the /java folder in some way?

<img width="1392" alt="screen shot 2016-08-10 at 6 24 36 pm" src="https://cloud.githubusercontent.com/assets/1623101/17573348/c0bcaf64-5f27-11e6-84f3-26623b67970a.png">

**Comment by mskogly** [comment]
No, I haven't touched the code at all

**Comment by benfry** [comment]
Maybe try a fresh install? What are the contents of java/bin/java? It should be the java binary, but it looks like it has gibberish instead.

**Comment by mskogly** [comment]
I downloaded the 2.2.1 version, but I'm actually getting the same error there. Strange.

**Comment by mskogly** [comment]
Copypaste of the end of java/bin/java \00\00\95\00\00\00\00\00\00\00\00\00\00
\00\F0@\00\00\00\00\00\00\00\00\00\00\00\00\00\00call_gmon_start\00__CTOR_LIST__\00__DTOR_LIST__\00__JCR_LIST__\00__do_global_dtors_aux\00completed.6075\00dtor_idx.6077\00frame_dummy\00__CTOR_END__\00__FRAME_END__\00__JCR_END__\00__do_global_ctors_aux\00const_launcher\00const_progname\00_GLOBAL_OFFSET_TABLE_\00__init_array_end\00__init_array_start\00_DYNAMIC\00data_start\00__libc_csu_fini\00_start\00__gmon_start__\00_Jv_RegisterClasses\00_fini\00__libc_start_main@@GLIBC_2.2.5\00SUNWprivate_1.1\00_IO_stdin_used\00__data_start\00__dso_handle\00__DTOR_END__\00__libc_csu_init\00JLI_Launch@@SUNWprivate_1.1\00__bss_start\00_end\00_edata\00main\00_init\00

**Comment by mskogly** [comment]
Sorry, my bad. Os on this machine is actually 32bit. Downloaded that version and in runs fine. Embarrassed :) Please delete this thread.

**Comment by benfry** [comment]
I'll just update the title of the bug in case anyone runs into the same problem.

**Comment by Sabotazh** [comment]
Up, the same problem.

**Comment by jeremydouglass** [comment]
@Sabotazh -- the solution was: if you are running 32bit Linux, download the "Linux 32" 32bit version!

https://processing.org/download/
