### ISSUE TITLE
hex() and unhex() withotu alpha

### ISSUE THREAD

**Issue by agrignard** [processing/processing#4616]
The way unhex work now is this:

String hs = "FF006699";
int hi = unhex(hs);

I wonder if you could also have this without alpha (right now it does not works)

String hs = "006699";
int hi = unhex(hs);

**Comment by benfry** [comment]
`unhex()` doesn't really have anything to do with alpha (or colors, for that matter), but I think what you're looking for is:

```
int hi = unhex(hs) | 0xff000000;
```

which would convert a 6-digits of hex into an opaque color. The second part sets it to opaque.

**Comment by agrignard** [comment]
Thanks indeed it does the trick.

I was just curious if you could overload the unhex() method so that it can accept both #FF006699 and #006699

**Comment by benfry** [comment]
That's a different sort of thing; let's handle it this way: https://github.com/processing/processing/issues/4617
