### ISSUE TITLE
problems with running Processing

### ISSUE THREAD

**Issue by Rhodiae** [processing/processing#4621]
I am running Windows 7 Home Premium on ASUS K53SV and latest Processing 3.1.2 version. At first Processing was running as expected. Recently when it runs, a green frame around all the windows Processing opens are shown. One can still continue programming, and project runs as it should. However, once the project is saved and closed, it becomes invisible to open from the location where it's saved.

Thank you in advance for help with this problem.
In attachments are few screen shots of what happens when I start running Processing.

![1](https://cloud.githubusercontent.com/assets/21077104/17730237/329d26be-6468-11e6-9e68-b18965848e06.JPG)
![2](https://cloud.githubusercontent.com/assets/21077104/17730238/32a55ca8-6468-11e6-9034-a99babb92496.JPG)
![3](https://cloud.githubusercontent.com/assets/21077104/17730241/32b8e552-6468-11e6-8abe-d0778aa21292.JPG)
![4](https://cloud.githubusercontent.com/assets/21077104/17730240/32b02ba6-6468-11e6-836f-0c15cd871bd4.JPG)
![5](https://cloud.githubusercontent.com/assets/21077104/17730239/32af47e0-6468-11e6-8d59-0ec60d968c9d.png)

**Comment by benfry** [comment]
That looks like something is wrong with the graphics driver on your machine or Windows is in a weird state that's highlighting each frame. We couldn't even make that green outline happen if we wanted to... Maybe check with forum.processing.org to see if anyone has seen something similar?
