### ISSUE TITLE
implement file/directory/path listing features

### ISSUE THREAD

**Issue by benfry** [processing/processing#4622]
Moving from the discussion [here](https://github.com/processing/processing-docs/issues/460#issuecomment-240447969) where @shiffman says: 

> I think some "file management" features could be useful especially as we think of Processing as a desktop application environment.  I have used this example with students who want to bulk load a directory of images or data files.  Some possibilities:
> - `listFiles(String dir)`
> - `directoryList(String dir)`
> 
> It should probably by default use the "sketchPath" (or "dataPath"?) but also allow full paths?

Inside `processing.app.Util` we have methods to recursively list items in a folder, with options that include whether to just return relative paths (as `String`s) or full paths, and to specify an extension being searched for. 

Such a menagerie of options! We could also use our funky quoted syntax the way we do with `Table` and have something like:
- `listFiles(String dir, "directories")`
- `listFiles(String dir, "extension=js")`
- `listFiles(String dir, "extensions=js,csv,txt")`
- `listFiles(String dir, "recursive,extensions=js,csv,txt")`
- `listFiles(String dir, "relative,recursive,extensions=js,csv,txt")`

In keeping with other API, I'd recommend `listPaths()` to return a `String` array (or `StringList`) and a `listFiles()` version to return `File` objects.

**Comment by benfry** [comment]
@shiffman I also like your point about the desktop environment...

**Comment by benfry** [comment]
Another thought is whether we should be handling those comma-separated argument lists via `String...` which would mean:
```
listFiles(String dir, "relative", "recursive", "extensions=js|csv|txt");
```
Also just realizing that extensions can't be a comma-separated list in an already comma-separated list, so the example above uses `|` instead. We could also just say:
```
listFiles(String dir, "relative", "recursive", "extension=js", "extension=csv");
```

**Comment by shiffman** [comment]
I think I like.  . .

```java
listFiles(String dir, "relative", "recursive", "extensions=js|csv|txt");
```

Can "relative" be assumed (unless preceded with `/` meaning it's full path)?

**Comment by benfry** [comment]
Relative should probably be named differently... The idea is that if I say: 
```
String[] paths = listPaths("/Users/shiffman/rainbow/images", "recursive")
```
that the paths it returns will not all be prefixed with `/Users/shiffman/rainbow/images`, the `String`s returned will be `001.jpg`, `tortoise.jpg`, `subfolder/something.jpg`, and so on.

When returning `File` objects, this wouldn't have any impact.

**Comment by benfry** [comment]
Added for what will likely be Processing 3.3 (if not 3.2.4).
