### ISSUE TITLE
Ellipse Rendering not beautiful

### ISSUE THREAD

**Issue by mxmlnkn** [processing/processing#4625]
When drawing a simple ellipse with the following code I see a plethora of problems.

    void setup()
    {
        background(255);
        size(100,100);
    }

    int iFrame = 0;
    void draw()
    {
        ellipse( 50, 50, 50,50 );

        if ( iFrame < 1 )
          saveFrame();

        ++iFrame;
    }

The left circle is always the circle as rendered in the viewable window (I'm using Debian sid, Linux 3.16.0-4-amd64, XFCE 4.12, Processing 4.1.1) and the right circle is the tiff-image exported with saveFrame. The images are resized to 4x the original size without interpolation in order to better show the pixel-wise problems.
![circle-white-window-render-problem](https://cloud.githubusercontent.com/assets/6842824/17771135/d767acb2-6541-11e6-8921-0cdad6789110.png)
As can be seen the rendering in the window does not antialias the outer borders of the circle outline in the right upper, lower and left lower quadrants. In the first place, why are different renders used for the window output vs. the file output.

Next, when using a black background another problem appears, i.e. the circle felling bleeds over the edge. This happens in both the file and the window output:
![circle-black-bleeding-problem](https://cloud.githubusercontent.com/assets/6842824/17771305/95d11922-6542-11e6-995b-bc00367d4758.png)
Again for some reason only the upper left quadrant behaves differently. In both cases the the pixels transparency seems to be wrong and applied to the white circle background instead of the black image background.
Changing the circle filling also changes the color of the bleeded pixels.

    fill( 255,0,0 );

Resulting Image:

![red-circle-black-bleeding-problem](https://cloud.githubusercontent.com/assets/6842824/17771437/34fccdde-6543-11e6-9977-faecd7affd34.png)

I tried using `smooth` as a workaround, but it does not seem to have any effect on both rendering bugs.

In my opinion everything should behave like the right half of the circle in the tif-file saved with `saveFrame`.

**Comment by benfry** [comment]
You're not clearing the background in draw().

**Comment by mxmlnkn** [comment]
I'm sorry, that was indeed at least partly a beginners' problem, but I still vote that this is a bug. If the clear is missing, then that should mean, that after x steps the antialiasing effect should completely vanish, but the renderer behaves incongurently both in the tiff vs. windows and also depending on the circle quadrant itself.

Moreover after adding clear the error remains! Although admittedly less visible (Now the tif output is the same as the window output, meaning saveFrame only saves the last frame while the window shows all frames partly wrongly blended together).
![tmp](https://cloud.githubusercontent.com/assets/6842824/17773820/8a3be6a6-6550-11e6-8037-31296569753f.png)


    void setup()
    {
        background(0);
        size(100,100);
    }

    int iFrame = 0;
    void draw()
    {
        clear();
        fill( 255,0,0 );
        ellipse( 50, 50, 50,50 );

        if ( iFrame < 1 )
          saveFrame();

        ++iFrame;
    }

**Comment by benfry** [comment]
You need `background()`, not `clear()` so that the pixels are opaque.

**Comment by mxmlnkn** [comment]
Replacing `clear()` with `background(0)` yields the same result as posted above.
