### ISSUE TITLE
the new version 3.2 can't start in the folder  'Program File(s)'

### ISSUE THREAD

**Issue by n0wave** [processing/processing#4629]
i have tried many times on windows 10, no matter in which disk, when Processing 3.2 in the folder named 'program files' or 'program',  it will not start

**Comment by Phlosioneer** [comment]
Same issue here, also doesn't work in a folder named "Program Files (x86)".

**Comment by benfry** [comment]
Duplicate of https://github.com/processing/processing/issues/4623
