### ISSUE TITLE
library compilations appear last (not alphabetical order)

### ISSUE THREAD

**Issue by shiffman** [processing/processing#4630]
I have been working on reviving toxiclibs which is a compilation of several libraries.  The current directory structure is as follows:

<img width="546" alt="screen shot 2016-08-18 at 7 08 47 pm" src="https://cloud.githubusercontent.com/assets/191758/17793692/3c26f7d6-6577-11e6-9658-967622b602f2.png">

The listings for toxiclibs show up last in both "Examples" and under "Sketch --> Import Library":

<img width="250" alt="screen shot 2016-08-18 at 7 10 01 pm" src="https://cloud.githubusercontent.com/assets/191758/17793719/731bd0b8-6577-11e6-8721-858466e6739a.png"> <img width="250" alt="screen shot 2016-08-18 at 7 10 21 pm" src="https://cloud.githubusercontent.com/assets/191758/17793721/756703ce-6577-11e6-80dd-f4f70faada6a.png">

Would be nice for the compilation directory structure to be maintained in "Examples" (like it is under "Sketch --> Import Library") and for it to appear properly in alphabetical order.

**Comment by benfry** [comment]
Working fine with the current version of toxiclibs… Not sure whether this was fixed in the meantime or we got rid of library compilations anyway, but closing for now.
