### ISSUE TITLE
coding issue

### ISSUE THREAD

**Issue by venkat1viswanathan** [processing/processing#4632]
I run win 10 on a home built pc with gigabyte motherboard
i3 processor, 4 GB RAM
Processing  3.12 unpacked
following code gives blank window

float a = 2.0;
float b = 5.0;
float y = a / b;

**Comment by alignedleft** [comment]
That *should* produce a blank window. What visual output were you expecting?

**Comment by venkat1viswanathan** [comment]
Well I was expecting an answer to the equation----foolish of me--? Am a beginner.
Btw if you can oblige me coding for
--- for.  10-6/3*2
Thanks in advance.

Sent from my iPhone

On 21 Aug 2016, at 19:29, Scott Murray <notifications@github.com<mailto:notifications@github.com>> wrote:

That *should* produce a blank window. What visual output were you expecting?

> On Aug 21, 2016, at 6:46 AM, venkat1viswanathan <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> I run win 10 on a home built pc with gigabyte motherboard
> i3 processor, 4 GB RAM
> Processor 3.12 unpacked
> following code gives blank window
>
> float a = 2.0;
> float b = 5.0;
> float y = a / b;
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

-

**Comment by rzats** [comment]
@venkat1viswanathan: to display the result you'll have to add a statement that actually outputs it, i.e.

```java
float a = 2.0;
float b = 5.0;
float y = a / b;

// Print the result to the console.
print (y);

// Draw the result in the output window at x-coordinate 15 and y-coordinate 20.
text (y, 15, 20);
```

**Comment by venkat1viswanathan** [comment]
Hi Zatserkovnyi,


Thank you very much for the code and it worked wonderfully.

But when I saved it, it got saved with file extension .pde and when

I click it, it takes me back to the processing window with the code

and not the output I saved.


appreciate your advice on this


Venkat


________________________________

**Comment by benfry** [comment]
Folks, please use forum.processing.org for coding questions.
