### ISSUE TITLE
modelX not working in JAVA2D

### ISSUE THREAD

**Issue by benureau** [processing/processing#4635]
The `modelX` is not working in the default renderer (`JAVA2D`), but nothing is mentioned about it in the documentation. And the warning is easy to miss if you are printing a lot of stuff.

**Comment by benfry** [comment]
`modelX()` is a concept that doesn't exist in 2D, so it prints a message saying that it's not available. Our only other option is to halt the sketch, are you suggesting we do that instead?

**Comment by benureau** [comment]
The concept of `modelX()` is perfectly valid in 2D. The following program works:

```
void setup(){
    size(100, 100, P2D);
    
    translate(1.0, 0.0);
    print(modelX(1.0, 0.0, 0.0));
}
```
and returns `2.0`. 

The same one with `FX2D` (or `JAVA2D`) instead of `P2D` returns 0.0, and an error message (the error is not displayed in Python mode, by the way). 
```
modelX(), or this particular variation of it, is not available with this renderer.
0.0
```

My guess is that the implementation details of `FX2D` make it hard to extract information about the current transformation. My question is: is there any plan to support `modelX` across all renderers, or is it not considered for future development?

**Comment by benfry** [comment]
That's a bug, I've just filed [an issue](https://github.com/processing/processing/issues/4813) for it. It's an artifact of the fact that `P2D` inherits from the OpenGL renderer behind `P3D`.

In 2D, you're looking for `screenX()` and the rest. Unlike 3D, there's no model-view matrix that's being used to transform objects to the screen.
