### ISSUE TITLE
loadPixels() and updatePixels() issue using P3D renderer

### ISSUE THREAD

**Issue by lubimaer** [processing/processing#4637]
The following code draws a line from top-left to bottom-right of the screen

```
PGraphics offscreen;

void setup() {
  size(300, 300, P3D);
  offscreen = createGraphics(300, 300, P3D);

  offscreen.beginDraw();
  offscreen.background(255, 0);
  offscreen.line(0, 0, offscreen.width, offscreen.height);
  offscreen.endDraw();

  // add back this two lines and drawn line goes from top-right to bottom-left in my screen
  //offscreen.loadPixels();
  //offscreen.updatePixels();

}

void draw() {
  image(offscreen, 0, 0);
}
```

When adding the two lines:
```
offscreen.loadPixels();
offscreen.updatePixels();
```

The behavior change and the line is drawn from top-right to bottom-left

I tested the code with Processing 3.2 on a windows machine and on a linux machine with same results

Issue seems to be in P3D renderer
Changing  
```
size(300, 300, P3D);
offscreen = createGraphics(300, 300, P3D);

```
to:
```
size(300, 300);
offscreen = createGraphics(300, 300);

```
Fixes the problem in my case

**Comment by AmnonOwed** [comment]
Enclosing the load/updatePixels calls within begin/endDraw() calls also fixes the problem.

**Comment by codeanticode** [comment]
Calls to an offscreen PGraphics should always being enclosed by begin/endDraw(), as [documented in the reference](https://processing.org/reference/PGraphics.html).
