### ISSUE TITLE
Arbitrary Minimum x-size of P3D render window

### ISSUE THREAD

**Issue by cnewswanger** [processing/processing#4644]
In previous versions of Processing I was able to render very small square images down to 12 x 12 pixels.   
Processing 3 limits the x dimension of the render window to 126 pixels. 

for example, If I set the size to size(20,20,P3D) and render and save the image I get an image that is 126 pixels wide by 20 pixels high.  Am I missing something?

like this:
`  

void setup() {
  size(20, 20,P3D);
}

void draw() {
  background(153);
  line(0, 0, width, height);
}
`

**Comment by benfry** [comment]
We have to make this work across Windows, macOS, and Linux. The minimum is based on what's reliably supported across platforms so that the same sketch runs the same way elsewhere.
