### ISSUE TITLE
I would very much appreciate a column counter for the editor. 

### ISSUE THREAD

**Issue by BS-007** [processing/processing#4648]

**Comment by iamutkarshtiwari** [comment]
https://github.com/processing/processing/pull/4136

**Comment by BS-007** [comment]
@iamutkarshtiwari. Thanks Utkarsh for your response. 
I gather your 'tab index location' is the same as my column counter/indicator. 

I strongly disagree with @alignedleft and @benfry that this is an advanced feature. 
It's so basic that even 'notebook' (the most primitive editor around) has it. 

I need it because I put my comments to the right of my code. 
And I want these comments in neat columns (to improve readability). 

Only part of your code '#4136' is visible. 
Could you post a link to the complete code?

BTW, I'm new to GitHub. 
Should my suggestion have been posted as a 'Pull request', or something else?

I like Processing very much. Remarks like: 

- @alignedleft: 'This is a power user feature; will it appeal to beginners (our primary audience)?'

and

- @benfry: 'This is the sort of thing we leave out of the PDE on purpose. 
- Advanced users who would want something like this should use another editor'

surprise me.

Processing has some very advanced features, and just the libraries I need. 

It is very suitable for beginners, 
but advanced users should not be excluded (on the contrary). 

At least, that is my view. Thanks again.

**Comment by benfry** [comment]
Advanced users are not excluded. We simply have to make a lot of decisions about what features to leave out of the PDE to keep it as simple as possible for the largest number of people. 

The point is that you can use any editor you want to create code with the Processing libraries. If you're asking for a column editor, you're likely to be much happier with a programmer's text editor like Sublime, or a full-featured IDE.
