### ISSUE TITLE
OS X : File > New does not create new sketch

### ISSUE THREAD

**Issue by mpbraendle** [processing/processing#4650]
OS X Processing Version 3.2.1  File > New does not create a new sketch
Processing 3.1.2 works fine

**Comment by jeremydouglass** [comment]
Odd. I'm not a maintainer, but I just saw your bug when reporting a different one and checked it -- I'm also running Processing 3.2.1 on OS X (10.10.5), and File > New *does* create a new sketch for me. I wonder if there is some temp file permissions / caching problem. On my system when I create a new sketch temporary new files are written to a deep subfolder of /private/var/folders/

**Comment by mpbraendle** [comment]
It might be some slight difference.
On my Home Mac with OS X 10.11.6, Java 8 Update 101, everything runs as expected.
On my Work Mac with the same setup, the new sketch is not created.
I will check your suggestion. Maybe also delete the Java cache.

**Comment by mpbraendle** [comment]
I have found the reason.
It is only the JavaScript Mode (Version 0.4.0 by @fjenett, see https://github.com/fjenett/javascript-mode-processing/issues/35 ) that causes this (non-)behavior.
If you turn on again Java Mode, everything runs as expected.
I will continue my bug report at the link above. 
Issue closed here.
