### ISSUE TITLE
SketchCode.getProgram() not returning current code

### ISSUE THREAD

**Issue by benfry** [processing/processing#4653]
Calling `getProgram()` on the current tab won't return the current version of the code if there are changes. Discovered while working on p5jsMode, but this doesn't seem to cause problems in Java Mode. Switching to another tab and coming back to the modified tab will make `getProgram()` work again. Ideas on what's happening here @JakubValtar? Is this a regression from the `Document` changes? Did you add something extra so that all the `program` variables are updated on a build?

**Comment by benfry** [comment]
Nevermind that; it's just a matter of not calling `prepareRun()`.

**Comment by JakubValtar** [comment]
That's how it always was: for the current tab, you have to get Document and get text. Program is updated on tab exit or manually at some other places. Caused me a lot of headaches to dodge all the bullets here...

**Comment by benfry** [comment]
Oh you betcha.
