### ISSUE TITLE
Executing exported .exe file from external program

### ISSUE THREAD

**Issue by bobhaha** [processing/processing#4657]
Running jre-8u74-windows-i586 on 32 bit Windows 7 machine.

I can run the exported .exe file from processing-3.2.1 if double clicked in windows file explorer. I can even run the program using a batch file from command line.

I just cant execute the .exe file from an external program. I can run the batch file fine, I can execute the .exe file... but nothing opens up. The external program works with any other .exe files on the windows system.

Maybe its a permission issue? I cant work out the reason for it not to start.

**Comment by benfry** [comment]
However you launch it, you probably need to set the current working directory to be the same folder as the .exe file. That way it find the lib folder and other support files.

**Comment by benfry** [comment]
No idea on this one (or how to start testing it)… probably a better question for forum.processing.org to see if anyone else has the same problem. If you find anything, please report here.
