### ISSUE TITLE
Procsessing cannot run,nothing happen

### ISSUE THREAD

**Issue by Shirakivan** [processing/processing#4666]
I updated the java to the lastest and rename the processing folder in my mac. Then I run the processing again. There is a notice like 

Setting 'Run Sketches on Display' preference to display 1

Please some one help me to solve this problem!ThankS

**Comment by gohai** [comment]
Does regular Processing 3.2.1 work (without doing any changes)?

**Comment by Shirakivan** [comment]
Thank u I reinstall my system and I think java is key problem....
