### ISSUE TITLE
launch() doesn't seem to work as described

### ISSUE THREAD

**Issue by theluckyfellow** [processing/processing#4667]
I'm using Ubuntu 16.04

I have launch() working in Windows, but I'm having issues under Linux.

First I tried: 
`launch("/usr/bin/lame", "/home/name/test.wav", "/home/name/test.mp3");` 
nothing...

Next I tried:
 `launch("lame", "/home/name/test.wav", "/home/name/test.mp3");` 
nothing...

According to the reference, one of these should work... "On Linux, it first tries gnome-open, then kde-open, but if neither are available, it sends the command to the shell without any alterations."

**Comment by gohai** [comment]
What happens if you put the arguments in an array?

**Comment by theluckyfellow** [comment]
That's actually what I normally do in the rest of the code. It also doesn't work.
```
  String[] params2 = { "/usr/bin/lame", "/home/name/test.wav", "/home/name/test.mp3"};
  launch(params2);
```
nor
```
  String[] params2 = { "lame", "/home/name/test.wav", "/home/name/test.mp3"};
  launch(params2);
```
work

I have lame installed. When I type `lame /home/name/test.wav /home/name/test.mp3` into the terminal, it work fine.

**Comment by benfry** [comment]
Aren't you looking for `exec()` not `launch()`?

**Comment by theluckyfellow** [comment]
Well that works fine... Thank you!
I suppose the documentation isn't foolproof, with me playing the part of the fool here :-)

Also, Benfry just responded to my post! I did a little dance...

**Comment by benfry** [comment]
Sorry, just realized that `exec()` isn't documented in the main reference—no wonder people are getting confused. I've updated the `launch()` documentation to be clearer, and [we'll look into](https://github.com/processing/processing-docs/issues/476) adding a mention of `exec()`.
