### ISSUE TITLE
Add Jump to Declaration to PDE right-click menu (enhancement)

### ISSUE THREAD

**Issue by jeremydouglass** [processing/processing#4668]
Could the PDE right-click menu include an option for Jump to Declaration / jump to definition?

This is highly useful, and there is a keyboard shortcut for it, but no menu items or contextual menus expose the fact that this is possible. Like "Find in Reference" it might be nice if users could discover this functionality.

(enhancement)

**Comment by benfry** [comment]
Added for 3.3.1.
