### ISSUE TITLE
printTempo

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#4671]
I use often line
`if(frameCount%30 == 0 ) println("stuff") ;`
because like it's write in the description methode is dangerous to use it in the loop, plus some time it's too much to write println 10000000 once by frame :) 
so maybe it's can be interesting to write a method like that : 

```
void draw() {
  printTempo(30, 1.2, "muche", true) ;
}
void printTempo(int tempo, Object... var) {
  if(frameCount%tempo == 0 ) {
    println(var) ;
  }
}
```

If you think that's can be good, I can try to write my first pull request ?

**Comment by benfry** [comment]
This is a situation where the documentation would be much longer than the code to actually implement the feature. Better to leave it to individual users.

**Comment by StanLepunK** [comment]
All right captain !
