### ISSUE TITLE
macOS Sierra Problem

### ISSUE THREAD

**Issue by leos2000171** [processing/processing#4673]
I am using macOS Sierra Beta 7. But when I am using processing 3 there is a bug. I am trying to type something in my program, when I type a letter or number, the program popup a windows which told me that the program is crash.

**Comment by cdbattags** [comment]
Thank God I'm not the only one... Please, please, please anyone have a fix?

**Comment by StanLepunK** [comment]
Processing 3.2.1 / iMac 2011 2,5 GHz Intel Core i5 / AMD Radeon HD 6750M 512 Mo
No problem for me with Sierra

**Comment by benfry** [comment]
I can't tell what's going on from these descriptions. [Here's some info](https://github.com/processing/processing/wiki/Troubleshooting) about what we're looking for—I want to help but I need more information than what's here. I can't tell if you're having trouble in the editor, in a program you've created, etc.

**Comment by benfry** [comment]
No response, closing.
