### ISSUE TITLE
Contribution Manager lists compatible libraries which fail to install

### ISSUE THREAD

**Issue by jeremydouglass** [processing/processing#4677]
The Processing contribution Manager lists compatible libraries which fail to install.

Example:

In Processing 3.2.1 on OS X 10.10.5, my Libraries tab lists as available / compatible:

    ToxicLibs 22

Installing ToxicLibs via the Contribution Manager > Library Tab (Install button) results in a temporary folder briefly appearing in my /libraries folder, e.g.:

    library5842271132355056316tmp/toxiclibs/

...and then a few seconds later the folder is deleted, with Processing Contribution Manager the message:

    Could not find a library in the downloaded file.

I had a daemon grab a copy of the folder pre-delete, and it looks like a full copy of toxiclibs. I would expect that either:

1. The folder would be downloaded and not deleted, or
2. It would not be marked as available to install in the manager

**Comment by gohai** [comment]
I believe there's currently an effort underway to update ToxicLibs to be compatible with Processing 3. But in any way, I'll point the people in processing-docs to this report, since that's where the library manager list is being maintained.

**Comment by benfry** [comment]
Moved to https://github.com/processing/processing-docs/issues/475
