### ISSUE TITLE
exported application doesn't work with latest jre

### ISSUE THREAD

**Issue by konstruktin** [processing/processing#4682]
The exported .exe says "This application requires a Java Runtime Environment 1.8.0_74", when 1.8.0_101 is installed. It probably didn't expect the versions to go into 3 digits.

**Comment by GoldenQubicle** [comment]
> It probably didn't expect the versions to go into 3 digits.

Doesn't seem to be the case. I'm running into the same issue, however, application export with the previous version of Processing ( 3.1.2 ) works fine.

**Comment by TobiasWehrum** [comment]
> Doesn't seem to be the case. I'm running into the same issue, however, application export with the previous version of Processing ( 3.1.2 ) works fine. 

This is exactly what I'm also observing. I just downloaded fresh 64bit versions of 3.1.2 and 3.2.1 and exported a windows build with both. The export of 3.1.2 is starting without any problems, the export of 3.2.1 displays the problem the opening posts describes.

**Comment by benfry** [comment]
Fixed for 3.2.2 or 3.3 (whatever we use for the next release) by updating to a newer version of launch4j.
