### ISSUE TITLE
Add options to saveJSONArray documentation (enhancement)

### ISSUE THREAD

**Issue by jeremydouglass** [processing/processing#4683]
[Documentation for saveJSONArray](https://processing.org/reference/saveJSONArray_.html) lists 'options' but doesn't say what they are.

It would be useful to add a list of common options in the documentation. A *particularly* useful example option would be 'compact'; it is a common need for JSON export.

Discussed in a [Processing forum thread](https://forum.processing.org/two/discussion/18246/minified-json#latest).

**Comment by benfry** [comment]
Yep—the options are `"compact"` and `"indent=N"` where you replace N with the number of spaces you'd like for indents. Moving this to the correct repo: https://github.com/processing/processing-docs/issues/479
