### ISSUE TITLE
"An unexpected, unknown, and unrecoverable error has occured.   Please report this."

### ISSUE THREAD

**Issue by cmallary** [processing/processing#4688]
What I was doing:  I had been debugging a sketch with a memory leak on Windows 7 Home Premium 64 bit, SP 1, 8GB of RAM and an Intel i7.  Max available memory set to 2048 MB.  I was "End Task"-ing Processing as a whole when the sketch would hang, then restarting it.  

What went wrong:  Once, when I restarted Processing via a desktop shortcut, I got the error message "An unexpected, unknown, and unrecoverable error has occured.   Please report this.",  Then Processing crashed.  I had not yet opened a sketch (I had, however, opened the Sketchbook.)

Since the Task Manager was running at the time, I have a screenshot of my CPU and RAM usage around the time of the crash, if it would be useful.

(Note:  This version of Processing was downloaded yesterday, so is up-to-date);

**Comment by benfry** [comment]
Unfortunately, we can't fix this unless we actually see what the error message says in the text below the "please report this" or in the console.
