### ISSUE TITLE
weird precision in float operation

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#4692]
Wrong result with plus and minus operation. I feel it's only happen when the first arg have two numbers avec the comma, and the next have zero or one number after comma.
![capture d ecran 2016-10-06 a 12 24 29](https://cloud.githubusercontent.com/assets/3332269/19149044/31bf77c2-8bc0-11e6-85b1-09943b44760f.png)

**Comment by benfry** [comment]
That's not a bug in Processing, that's just how floating point numbers work. We have no control over it.
