### ISSUE TITLE
CreateFont suggestion

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#4693]
I work around createFont, and I try the set char, but I cannot with only one. I look in PApplet and read it's write like that : 
```
  public PFont createFont(String name, float size,
                          boolean smooth, char[] charset)
```
maybe that can be better to write like that 
```
  public PFont createFont(String name, float size,
                          boolean smooth, char... charset) 
```
I try to make a pull request :)

**Comment by StanLepunK** [comment]
I try to do a pull request but it's a big fail 
![capture d ecran 2016-10-06 a 16 28 35](https://cloud.githubusercontent.com/assets/3332269/19156424/1b84ea2e-8be2-11e6-88fd-c1dc1df9eb23.png)

**Comment by benfry** [comment]
Just pass `new char[] { 'a', 'b', 'c' }` instead. Changing this right now would change the [method signature](https://en.wikipedia.org/wiki/Type_signature#Java_2), which would break all code that relies on that function.

**Comment by StanLepunK** [comment]
understood, that's big move for nothing important :)
