### ISSUE TITLE
When clicking on the error message : "Could not open the url" 

### ISSUE THREAD

**Issue by KhaledTo** [processing/processing#4695]
Hi, 

So when i click on the error message (see screenshot) i get the message "Could not open the url" : 

![screenshot from 2016-10-06 22 52 17](https://cloud.githubusercontent.com/assets/20525775/19177550/3208d27a-8c18-11e6-89f6-bea31286befa.png)

Is it supposed to open my web browser ?

**Comment by gohai** [comment]
@KhaledTo Which version of Processing is this? (Looks like you've compiled it yourself?) This is Ubuntu Linux?

**Comment by KhaledTo** [comment]
@gohai Sorry i forgot to precise. 

Yeah, I complied myself, I followed : 
https://github.com/processing/processing/wiki/Build-Instructions

Ubuntu 14.04.5 LTS
Processing 3.2.1
Java 8 (1.8.0_101)

**Comment by gohai** [comment]
Does this happen the same way when you use a downloaded version of Processing 3.2.1? Do you have the vlw file in your sketch directory?

**Comment by gohai** [comment]
Could you also copy and paste the entire stacktrace (the text in red in your screenshot)? That might help.

**Comment by KhaledTo** [comment]
I didn't try yet with a downloaded version, I don't have a correct vlw file in the example i showed you, the message appears whenever i click on the error message, for instance it appears when i click on the empty space where the message is supposed to be displayed (with the correct file name) :

![screenshot from 2016-10-07 09 13 57](https://cloud.githubusercontent.com/assets/20525775/19191026/953b0902-8c6e-11e6-9798-b5885253dd10.png)

Could this come from the fact that `openURL()` in `Platform.java` uses `java.awt.Desktop` and the fact that i use a Linux distribution ?

**Comment by KhaledTo** [comment]
Ok, I just tried with a downloaded version and got the same result.

**Comment by gohai** [comment]
What happens if you run `xdg-open http://processing.org/` in a terminal?

**Comment by KhaledTo** [comment]
It opens correctly the web page and i got this warning : 

`(firefox:5956): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed`

**Comment by benfry** [comment]
Fixed for whatever release follows 3.2.1.
