### ISSUE TITLE
right bracket missing error

### ISSUE THREAD

**Issue by bworld1** [processing/processing#4702]
I'm using Processing 3.2.1

I have had the mysterious "right bracket missing error" on several occasions and like a lot of people, I couldn't resolve it easily based on where it was telling me the error was at. I clearly have found the issue and can demonstrate it in the minimal code (all extra code and comments removed) that I will upload.

The problem occurs if there are at least three tabs (three in my example), and if a right bracket is missing in the middle tab (in my example, the bottom bracket is missing for closing the class), two symptoms/errors will occur. The last tab will show that it thinks a right bracket should be added at the bottom, and then it appears happy. But either way, the main program will show that the class based on the last tab does not exist. And finally, the middle tab will not show any error.

So, the error throws off the programmer into the wrong tab to try to solve the problem.

[RightBracketError.zip](https://github.com/processing/processing/files/531424/RightBracketError.zip)

I added 4 more tabs to the example above to see what would happen. The tab called Animal, which went in front of the Boundary tab (which has the missing bracket), does show up as an existing class in the main program. But all of the others have "class does not exist" in the main program, and the red indicator that a right bracket is missing is now at the last tab. So, it seems like Processing is adding up the total pairs of brackets for the whole sketch to verify them, and then, if there is one missing, indicates that there is one missing in the last tab, and all other tabs after the tab with the actual missing bracket are classified as classes that do not exist.

[RightBracketErrorWMoreTabs.zip](https://github.com/processing/processing/files/531961/RightBracketErrorWMoreTabs.zip)

**Comment by gohai** [comment]
Could you put them in a zip and attach it to this GitHub issue?

**Comment by bworld1** [comment]
I've attached it to this email, is that adequate?

**Comment by gohai** [comment]
@bworld1 No, you need to go the issue website, an attach it by dragging & dropping or selecting them in the dialog.

**Comment by benfry** [comment]
(Just dropping the 'infamous'—this is the first that I know of that it's been reported. If the bug isn't here on Github, we have no idea it exists.)

**Comment by bworld1** [comment]
No problem. I initially had searched the internet in general, and found 
that many people have had the problem, don't know for how long, but 
probably none ever thought to get it in the bug list. It has been 
driving people a bit bonkers, since any help that they got was usually 
insinuating that there was something wrong with the way they wrote the 
code, which is partly true (there has to be a missing bracket 
somewhere!), but the people couldn't isolate their problem based on the 
error that was displayed.

**Comment by jeremydouglass** [comment]
I believe I previously described this error cascade when reporting #4649 

The right bracket is often missing at the end of a tag due to the related bug -- cutting-and-pasting a full page of code into an empty tab will often drop the final character. What is that final character? Usually, a right bracket. So when the user is reorganizing code or copying classes between sketches, they get hit with a wall of confusing error messages about the tab *after* the tab that exhibited copy-paste-bug #4649.

**Comment by bworld1** [comment]
Actually, if you have 20 tabs, and your missing bracket is near the 
front, all tabs afterwards have invalid classes. an unsuspecting user 
would be trying to troubleshoot the invalid classes in 15 or more tabs.
