### ISSUE TITLE
Updates tab blank after failed contribution manager install

### ISSUE THREAD

**Issue by jeremydouglass** [processing/processing#4704]
In Processing 3.2.1 on MacOS 10.10.5:

When the Contribution Manager fails on individual install, _all_ updates disappear from the Contribution manager Updates tab. They have not been updated -- they are just no longer listed. Closing and then restarting Processing correctly repopulates the Updates tab.

I am testing with the failing p5.js update reported in [p5js issue 11](https://github.com/fathominfo/processing-p5js-mode/issues/11).
---

Before a failed update:

![contribution manager -- updates tab](https://cloud.githubusercontent.com/assets/798570/19420528/21132628-93a2-11e6-8c02-c9fbf3481655.png)

After:

![contributions manager -- updates tab empty](https://cloud.githubusercontent.com/assets/798570/19420555/af06e74e-93a2-11e6-895d-624f5fa00d32.png)

On closing and restarting, Updates tab listings are restored (until next failed update).
---

I wasn't sure if this should be reported here or to [processing-docs](https://github.com/processing/processing-docs/issues/)

**Comment by benfry** [comment]
This is the correct place, thanks. 

Do you get any red error messages in the console?

**Comment by jeremydouglass** [comment]
-  No error messages in an open Processing sketch console while replicating the error.
-  No error messages in the system Console while replicating the error.

The only recent error I see with Processing in the system Console logs is "excessive wakeups" -- possibly when I work the computer or launched processing just before running the first test.

10/19/16 09:33:42.000 kernel[0]: process Processing[88834] caught causing excessive wakeups. Observed wakeups rate (per sec): 167; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 95421
10/19/16 09:33:54.634 spindump[87535]: Saved wakeups_resource.diag report for Processing version 3.2.1 (0253) to /Library/Logs/DiagnosticReports/Processing_2016-10-19-093354_Bundtcake.wakeups_resource.diag

However it seems probable that this is unrelated to the Updates tab. I then closed and restarted Processing 3.2.1 and walked through replicating the error two more times, and the error occured without triggering another system Console error either time.

**Comment by benfry** [comment]
Now fixed for the release after 3.2.2: https://github.com/processing/processing/issues/4082
