### ISSUE TITLE
Download metrics of library

### ISSUE THREAD

**Issue by Glagnar** [processing/processing#4708]
Dear Processing,
   we have a library that is published with the processing.org site. We are interested in knowing more about how many people have downloaded it. This is going to help us decide how much effort we put into improvements. If no-one uses it then perhaps we will not spend much time on it, but if we have a large following - then we would put more effort into it

Sincerely
Thomas

**Comment by gohai** [comment]
@Glagnar 
Not sure if this helps in your situation, but there's an easy way go get download counts in case you're using GitHub releases as the means of distributing your library:

e.g. https://api.github.com/repos/gohai/processing-glvideo/releases

(notice the `download_count`)

**Comment by benfry** [comment]
You have a large following and you should put more effort into it. :-)

But since you're interested in understanding actual data rather than me making things up, I'm also working on how to make information about library/tool/mode usage public.

**Comment by Glagnar** [comment]
@gohai Your link works find - good enough for now. @benfry Thanks, I will let my colleague know :)

**Comment by benfry** [comment]
Now implemented here: https://github.com/processing/processing/wiki/Usage-Statistics
