### ISSUE TITLE
Using from linux Terminal

### ISSUE THREAD

**Issue by divinoob** [processing/processing#4709]
Hi,

First of all, great work on the software, i'ts an awesome tool.
I would like to know if it's possible to use pyprocessing from a linux terminal, program my script on any text editor that I want, and somehow compile it using terminal and not the processing gui, is that possible?

Thank you!

**Comment by gohai** [comment]
You might want to try asking at https://github.com/jdf/processing.py - afaik Processing only comes with a command-line interface for the Java Mode (`processing-java`).

**Comment by AminLer** [comment]
got the same problem and pretty new at this can someone explain to me how i can get the tool (processing-java) Im on ubuntu and it wont show under tools

Thank you

**Comment by benfry** [comment]
Closing since this is Python related…
