### ISSUE TITLE
RIGHT mouseButton with ALT bug

### ISSUE THREAD

**Issue by theRussetPotato** [processing/processing#4711]
Here's something I just noticed. Take this simple example:

```
void setup() {
}

void draw() {
 println(mouseButton); 
}
```

if I hold the right mouse button it prints 39. Now if I hold down the ALT key then hold the right mouse button it prints 3. 3 is actually the value for CENTER, so what gives?

This is in Processing 2.2.1 in Java mode, and doesn't occur with processing.js.

**Comment by quarks** [comment]
This issue appears to be with just the JAVA2D render, when I tried it with P2D it correctly identified the mutton as RIGHT

Tested on OSX with Processing 3.2.1

**Comment by benfry** [comment]
There's such a thing as a three-button mouse, and depending on your platform, Java will interpret an alt-click as the middle mouse button (the same way that ctrl-click on the Mac is interpreted as a right-click). The P2D behavior is actually incorrect, though I guess you could file a bug for "please remove all 3-button mouse support."

**Comment by theRussetPotato** [comment]
I'm pretty sure after you alt click, if you hold alt without clicking at all it will still print 39. I'm not in front of a computer to confirm this, but I do remember I could eaily replicate it.
