### ISSUE TITLE
Some semi-transparent edges of sphere() meshes are rendered in higher density.

### ISSUE THREAD

**Issue by chrisjj** [processing/processing#4720]
On Processing 3.2.1 for Windows, run

```
void setup() {
  size(480, 480, P3D);
  colorMode(HSB, 6.0, 1.0, 1.0, 1.0);
  noFill();
}
 
void draw()
{ // For tweaking
  translate(width/2, height/2);  
  background(0);
  stroke(0.0, 0.4, 1.0, 0.5);
  rotateX(-0.1);
  rotateY(0.01*millis()/100);
  strokeWeight(5);
  sphereDetail(4);sphere(100);
}
```

Expected: wireframe sphere with edges rendered in uniform density
Observed: wireframe sphere with some edges rendered in higher density:

![image](https://cloud.githubusercontent.com/assets/6157073/19776355/96c249ea-9c6b-11e6-8e53-e7903c5f3b44.png)

Discussed here: http://web.archive.org/web/20161027162717/https://forum.processing.org/two/discussion/comment/77501%23Comment_77501

**Comment by jeremydouglass** [comment]
In tests, the single high-density edge is the ring immediately below the mesh pole (see forum thread linked in issue).

**Comment by codeanticode** [comment]
thanks for reporting the issue, fixed with https://github.com/processing/processing/commit/4da26d107cd9036de0bb4f13466699b9b92e6e2e
