### ISSUE TITLE
P2D and P3D not stopping with empty draw() blocks

### ISSUE THREAD

**Issue by benfry** [processing/processing#4722]
P2D and P3D seem to continue running when there's no `draw()` method (i.e. with a 'static mode' sketch). See https://github.com/processing/processing/issues/4721

**Comment by codeanticode** [comment]
The buggy situation in P2D/P3D is when the sketch has setup() but no draw(), because it keeps calling draw(). Other cases (static sketch without setup/draw, or sketch with noLoop() are ok. Fixed with https://github.com/processing/processing/commit/db6095e04634a187960cecc28572e3c240375b61

**Comment by benfry** [comment]
Thanks for the fix.
