### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by mweels** [processing/processing#4723]
First, thank you for your time and effort.

Second, it would be nice if you use an example from the Example area that Processing asks you if you would like to copy this to your own project folder.

A lot of the times the examples are good reference points and I find myself overwriting them with my own code.

Thank you,
Marty

**Comment by gohai** [comment]
Odd. I have exactly this on OS X (w/ 3.2.1)

![screen shot 2016-11-01 at 6 15 00 pm](https://cloud.githubusercontent.com/assets/4945451/19899132/33661ff0-a05f-11e6-8dad-833322626786.png)

**Comment by alignedleft** [comment]
I see that, too. Then a dialog pops open, defaulted to your sketchbook directory.

@mweels Did we understand your suggestion? Let us know if you intended something else.

**Comment by benfry** [comment]
No response; closing… this feature has been implemented for a long time, for the reasons cited in the original request. 

If it's not working properly, that should be filed as a bug. (Or if the current implementation is confusing, a new issue should also be filed with suggestions about how it can be improved.)
