### ISSUE TITLE
beginRecord not capturing all frames in display.

### ISSUE THREAD

**Issue by Dillonownsrs** [processing/processing#4726]
I've been trying to create pdf's of a few sketches which randomly generate on top of themselves, creating interesting and varied layered looks. I've found, however, that all the different methods of creating pdf screenshots fail to capture the image that processing displays.

I've taken a screenshot of my processing window, and I've uploaded a pdf similar to every other pdf I've captured using processing's tools. The difference is the amount of layering (obvious in the top left corner).
[decay4.pdf](https://github.com/processing/processing/files/571839/decay4.pdf)
<img width="719" alt="screen shot 2016-11-04 at 10 07 19 am" src="https://cloud.githubusercontent.com/assets/1448274/20010606/b3812874-a276-11e6-925c-e84c89bde48e.png">

Any idea how to create a true-to-display pdf screen capture of every frame?

Thank you.

**Comment by benfry** [comment]
Please use forum.processsing.org for programming/practice questions, unless you find that this is actually a bug, in which case it should go here.
