### ISSUE TITLE
Sound Library causing JRE VM runtime error

### ISSUE THREAD

**Issue by bworld1** [processing/processing#4727]
I installed 3.2.2 about three days ago, but I have seen others online with the same problem with older versions of 3, not sure about before that. I could not find this issue in the list, sorry if it is duplicated. The error just started this afternoon, I was working with sounds for the first time all day yesterday and today. The sketch is barebones and just has the sound library, SoundFile ballsnd, the call to load the sound, and play it. I included the sound, it's not the sound file, I have several they all worked fine until it broke this afternoon. It is now a hard failure when using the sound library, but fine without it.
I installed the latest versions of Java and JRE, no help.  

[sketch_161104a.zip](https://github.com/processing/processing/files/572754/sketch_161104a.zip)

**Comment by benfry** [comment]
Moving to https://github.com/processing/processing-sound/issues/100

**Comment by bworld1** [comment]
Here is the Sound  src, and the Windows64 library, since I use Windows 10 64 bit 

[windows64.zip](https://github.com/processing/processing/files/572785/windows64.zip)

**Comment by benfry** [comment]
Please use that other link.
