### ISSUE TITLE
P2D and P3Ddoesn't work

### ISSUE THREAD

**Issue by origapepe** [processing/processing#4729]
I have windows 10,downloaded Processing 3.2.2,but when I use P2D or P3D ,there are a lots of error. Why?? What can i do for solve the error?
Thanks

**Comment by benfry** [comment]
Here are some troubleshooting instructions: https://github.com/processing/processing/wiki/Troubleshooting

If you have a bug report, you can file it here. But if you need general help, please use forum.processing.org.
