### ISSUE TITLE
Null pointer with P3D and P2D with svg with text

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#4730]
There is problem with SVG that contain text element, Processing stop with null pointer exception when the method `getChildren()` is used, no problem with the default mode and JAVA2D
![capture d ecran 2016-11-06 a 17 34 09](https://cloud.githubusercontent.com/assets/3332269/20039622/48dac868-a447-11e6-8769-43f21851361b.png)

**Comment by codeanticode** [comment]
I tested an svg file with a text element, and didn't get any null pointer exception with P2D. Could you upload your file somewhere?

In any case, Processing does not support text and fonts in svg files.

**Comment by StanLepunK** [comment]
Here the link the bug file https://www.dropbox.com/s/6sgc3a8gwn6ewx2/PShape_text_svg.zip?dl=0
I'm on Processing 3.2.3 / OS Sierra / iMac 2012
I know Processing don't support the text but I write a sketch who can read the text from SVG and style tag from Illustrator CC, just in case here the link of the full SVG sketch. I love to translate to add the feature to Processing but I don't know how :( I'm not really expert to push. https://github.com/StanLepunK/SVG_Vertex-Processing

**Comment by benfry** [comment]
Rolling SVG requests into https://github.com/processing/processing/issues/5935
