### ISSUE TITLE
Canvas size for FX2D is invalid in fullscreen

### ISSUE THREAD

**Issue by Dolphin101546015** [processing/processing#4737]
Then i try using fullscreen application in processing, i settup first
fullscreen();
and write application for this mode.

After it i change setting to:
fulscreen(FX2D);
and got wrong screen size. I made changes to using second way, but then i select first mode again, i got same issue.
![fullscreen](https://cloud.githubusercontent.com/assets/23341913/20108428/cb3ec6a6-a627-11e6-9427-dfcc32ca90d8.png)
![fullscreen fx2d](https://cloud.githubusercontent.com/assets/23341913/20108432/ce087fd0-a627-11e6-8c06-6029e52c32cf.png)

**Comment by Dolphin101546015** [comment]
Window have write rectangle around screen, and when using:
fullscreen();
right side and bottom side is disapear, but when using 
fullscreen(FX2D);
all ok, and white rectangle showing good.
So difference is 1 pixel from right and bottom.

**Comment by benfry** [comment]
Is this #4527?

**Comment by Dolphin101546015** [comment]
Not sure for #4527, but sometimes in FX2D mode, fullscreen open in wrong positions also.
This issue apears only when windows using multi-monitor mode. 
Bug disapear if you close IDE, and start again.

**Comment by benfry** [comment]
Ah, ok… that's not really a bug, it's just an artifact of how different renderers handle those tradeoffs differently. It has to decide “how do you fill pixels on the screen to draw a line that's slightly less than a pixel wide,” and there's more than one solution to that.
