### ISSUE TITLE
How to reindex code completion for a custom library?

### ISSUE THREAD

**Issue by cansik** [processing/processing#4739]
I have a java library that I am working on in my `code` folder. The problem now is, that processing is telling me I have an error in my code, because (I believe) it doesn't really check if there is a new library version and reindex the code completion information.

![image](https://cloud.githubusercontent.com/assets/5220162/20175815/f62b7fda-a744-11e6-8db0-943cb98b5719.png)

But I've implemented a method overloading in my library for exactly this type.

![image](https://cloud.githubusercontent.com/assets/5220162/20175837/1861124a-a745-11e6-9047-e77dfdf524d6.png)

So is there a way to reindex the code completion index or could something be wrong with my setup?

**Comment by benfry** [comment]
Paging @JakubValtar…

**Comment by JakubValtar** [comment]
There is no file watcher, so we can't detect that the file changed. I think the code folder is reindexed when you drop a jar file into processing window. Let me get back to you later when I have a chance to check it.

For development, I'd recommend to create a test sketch as a runnable class in you IDE and run it from there (just add the core.jar from processing installation as a library). If you use IDEA you can create a new module in you project and put the class there.

**Comment by cansik** [comment]
@JakubValtar Adding the jar again to the sketch didn't work. I tried this earlier. Yeah, I think I will go this way to just test it.

**Comment by JakubValtar** [comment]
I will look in the code to tell you the triggers, but this is a very specific use case.

Having the sketch in the IDE also allows you to debug and step into your library code, so I prefer it.

**Comment by cansik** [comment]
Ok after trying it in intellij I found also an error in my setup. So it could be that re-applying the JAR to the sketch could reindex it.

**Comment by cansik** [comment]
Yep, dropping a JAR onto processing reindexes the folder. Thank you!
