### ISSUE TITLE
Rotate problem in deg

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#4741]
there is a problem to render the rotation in degrees, if we give the value directly or if the value is convert from radian. in Radians there is no problem.
![capture d ecran 2016-11-11 a 10 44 50](https://cloud.githubusercontent.com/assets/3332269/20210982/8d27aad2-a7fc-11e6-9b9e-826f6a110a55.png)

```
void setup() {
  size(300, 300) ;
  background(0) ;
  fill(255) ;
  stroke(255) ;
  strokeWeight(.5) ;
  line(width/2, 0, width/2, height) ;
  line(0, height/2, height, height/2) ;
  line(0, 0, width, height) ;
  line(0, height, width, 0) ;
  
  textSize(24) ;
  
  float angle = 45 ;
  angle = PI / 4 ;
  angle = degrees(angle) ;
  rotate_text(angle) ;
  
  noFill() ;
  rotate_rect(angle, 50) ;
}

void rotate_text(float angle) {
  pushMatrix() ;
  translate(width/2, height/2) ;
  rotate(angle) ;
  text("Rotate 45", 0, 0) ;
  popMatrix() ;
}

void rotate_rect(float angle, int size) {
  pushMatrix() ;
  translate(width/2, height/2) ;
  rotate(angle) ;
  rect(0,0, size, size) ;
  popMatrix() ;
}
```

**Comment by gohai** [comment]
I believe you're mixing up degrees and radians. The `translate` function wants to be fed radians.

If I am not mistaken, you're taking 45 degrees, converting to radians, converting back to degrees, and then passing this number to `rotate`.

**Comment by StanLepunK** [comment]
hmmm, sorry you're right...I return read the tutorial. I've forget that the computer cannot know if I send degrees or radians :( I close this fantaisy issue.
