### ISSUE TITLE
"it was not meant to be"

### ISSUE THREAD

**Issue by roxana1367** [processing/processing#4742]
hi,

my processing startup has an error saying: a serious problem happened during the start up and asked me  please report here

**Comment by alignedleft** [comment]
@roxana1367 do you have any details to report, like what version of Processing you're using, what OS and version?  Any error messages?  That will help us troubleshoot.

**Comment by benfry** [comment]
Please copy & paste the text below the message that says, “please report.”

**Comment by jeremydouglass** [comment]
It seems like this might be related to https://github.com/processing/processing/issues/4929

At any rate perhaps this could be closed as it gives no details. I'm adding the link above because this is a top search hit for that error msg.

**Comment by benfry** [comment]
No response; closing.
