### ISSUE TITLE
Problem With ListBox in g4p

### ISSUE THREAD

**Issue by DoeringChristian** [processing/processing#4746]
Whenever i start this project [https://www.dropbox.com/sh/pirmg24uz0rz6io/AAA0skTr9mW2hvPTDbMVRRHea?dl=0](url), add a new oscilator and try to select one it crashes.

Thank you for helping me.

Ps: for some reasons you have to copy the link into a new tap.

**Comment by benfry** [comment]
Please use forum.processing.org for coding questions.
