### ISSUE TITLE
KeyEvent.isAutoRepeat() not working

### ISSUE THREAD

**Issue by mMerlin** [processing/processing#4751]
Environment: Processing 3.2.1, Fedora 4.8.8-200.fc24.x86_64
$ javac -version
javac 1.8.0_111
$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b16)
OpenJDK 64-Bit Server VM (build 25.111-b16, mixed mode)
$ ./.local/share/processing-3.2.1/java/bin/java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

isAutoRepeat() always returns false

demo sketch code
```java
KeyTest kt;
void setup ()
{
  kt = new KeyTest ( this );
}
void draw () {}

public class KeyTest
{
  public final PApplet papplet;
  public KeyTest ( final PApplet theApplet )
  {
    papplet = theApplet;
    papplet.registerMethod( "keyEvent" , this );
  }
  public void keyEvent ( final KeyEvent ev )
  {
    println ( "key event:" , ev.getAction () , ev.getModifiers () ,
      "code" , ev.getKeyCode () , "autoRepeat =" , ev.isAutoRepeat ());
  }
}
```

Single press and release of 'a' key gets:
```
key event: 1 0 code 65 autoRepeat = false
key event: 3 0 code 0 autoRepeat = false
key event: 2 0 code 65 autoRepeat = false
```

Pressing and holding 'a' key for awhile gets:
```
key event: 1 0 code 65 autoRepeat = false
key event: 3 0 code 0 autoRepeat = false
key event: 1 0 code 65 autoRepeat = false
key event: 3 0 code 0 autoRepeat = false
…
key event: 1 0 code 65 autoRepeat = false
key event: 3 0 code 0 autoRepeat = false
key event: 2 0 code 65 autoRepeat = false
```

I would expect:
```
key event: 1 0 code 65 autoRepeat = false
key event: 3 0 code 0 autoRepeat = false
key event: 1 0 code 65 autoRepeat = true
key event: 3 0 code 0 autoRepeat = true
…
key event: 1 0 code 65 autoRepeat = true
key event: 3 0 code 0 autoRepeat = true
key event: 2 0 code 65 autoRepeat = false
```

EDIT: Insert java version info from processing install folder

**Comment by benfry** [comment]
OpenJDK [is not supported](https://github.com/processing/processing/wiki/Supported-Platforms#linux). Does this also occur when run from the PDE using Oracle's Java?

**Comment by pratham-pc** [comment]
Same is occuring in my case too.
Ubuntu 16.04 64-bit
$ javac -version
javac 1.8.0_111
$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**Comment by mMerlin** [comment]
Actually, processing is using Oracle's Java.  I incorrectly reported the global java version for my machine.  Instead of the one that is installed with processing.

$ which processing
~/.local/bin/processing
$ ls -l ~/.local/bin/processing
…/.local/bin/processing -> ../share/processing-3.2.1/processing
$ ./.local/share/processing-3.2.1/java/bin/java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Unless simply having multiple java versions installed is mixing things up someplace.

**Comment by mMerlin** [comment]
I just installed the latest stable processing release version and get identical results.

Environment: Processing 3.2.3, Fedora 4.8.8-200.fc24.x86_64
$ ./.local/share/processing-3.2.3/java/bin/java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**Comment by JakubValtar** [comment]
`isAutoRepeat()` is supposed to work only for P2D/P3D, since there is not other way to handle key repeats in OpenGL. We need to mention this in docs.

**Comment by mMerlin** [comment]
I changed `void setup()` to:

```java
  size ( 100, 100, P2D );
  kt = new KeyTest ( this );
```

Now I do not even get the autorepeat events.  Press and hold 'a' for awhile gets:

```
key event: 1 0 code 65 autoRepeat = false
key event: 3 0 code 0 autoRepeat = false
```

When finally release the a key:
```
key event: 2 0 code 65 autoRepeat = false
```

**Comment by JakubValtar** [comment]
Ah, sorry, forgot about the hint. Auto repeat is blocked in P2D/P3D by default, you can enable it with `hint(ENABLE_KEY_REPEAT)`

Our decisions are explained here: https://github.com/processing/processing/issues/1622#issuecomment-139648383

**Comment by mMerlin** [comment]
I read the #1622 thread, the associated gist, and did web searches.  I can not figure out how to actually use the hint.  The closest I found (https://platform.netbeans.org/tutorials/nbm-java-hint.html) was to add
```
@hint(ENABLE_KEY_REPEAT)
```
before `public class KeyTest`, but by itself that say: The class "hint" does not exist.
The sample has a bunch of org.netbeans imports.  Which are not currently available in my environment. 

I work with lots of programming languages, but java hint is not something I have previously encountered.  I found a bunch of information about them, creating new, etc.  But not how to actually use | call | reference them.

**Comment by JakubValtar** [comment]
It's a function, you call it once inside setup():

```processing
void setup() {
  size(100, 100, P2D);
  hint(ENABLE_KEY_REPEAT);
}

void draw() {
  ...
}
```

**Comment by mMerlin** [comment]
Got it!

Add
```
hint ( ENABLE_KEY_REPEAT );
```
to the KeyTest constructor.

Updated Code:
```java
KeyTest kt;
void setup ()
{
  size ( 100, 100, P2D );
  kt = new KeyTest ( this );
}
void draw () {}

public class KeyTest
{
  public final PApplet papplet;
  public KeyTest ( final PApplet theApplet )
  {
    papplet = theApplet;
    papplet.registerMethod( "keyEvent" , this );
    hint ( ENABLE_KEY_REPEAT );
  }
  public void keyEvent ( final KeyEvent ev )
  {
    println ( "key event:" , ev.getAction () , ev.getModifiers () ,
      "code" , ev.getKeyCode () , "autoRepeat =" , ev.isAutoRepeat ());
  }
}
```

Output from press and hold 'a' key:
```
key event: 1 0 code 65 autoRepeat = false
key event: 3 0 code 0 autoRepeat = false
key event: 2 0 code 65 autoRepeat = true
key event: 1 0 code 65 autoRepeat = true
key event: 3 0 code 0 autoRepeat = true
key event: 2 0 code 65 autoRepeat = true
key event: 1 0 code 65 autoRepeat = true
key event: 3 0 code 0 autoRepeat = true
key event: 2 0 code 65 autoRepeat = true
key event: 1 0 code 65 autoRepeat = true
key event: 3 0 code 0 autoRepeat = true
key event: 2 0 code 65 autoRepeat = true
key event: 1 0 code 65 autoRepeat = true
…
```

**Comment by mMerlin** [comment]
Have to think whether I want the hit in setup or in the library for my starting case.  I wanted the library to be able to pickup all available events.  Design decision whether the use should (need to) turn on auto repeat, or the library code should do so automatically under appropriate conditions.  My method worked for the sample, but would it break things in a more general library environment?  As mentioned in the referenced thread, in a lot of situations, have it turned off would give the expected results.
