### ISSUE TITLE
javax.media.opengl.GL cannot be resolved

### ISSUE THREAD

**Issue by iorobertob** [processing/processing#4756]
This error appears when trying to run a number of examples from the menu Examples...

The full error goes:

The type javax.media.openGl.GL cannot be resolved. It is indirectly referenced from required .class files

For example, patch GLLights does this in line 36

35        GLGraphics renderer = (GLGraphics)g;
36        renderer.beginGL();

I have a fresh Processing 3.2.3 install, on macOS 10.12.1 Sierra.

**Comment by benfry** [comment]
Which examples have the problem? I don't know of an example called `GLLights` that's included with Processing 3.2.3.

**Comment by iorobertob** [comment]
I am sorry, but I have actually erased also the scripts folder, delted the application file and re downloaded Processing. The example folder that I was referrin to is no longer there!! I surely was mixed with a previous version, so you are right! Anyway, as a note, the example was following Menu File - Examples and then in the file tree:

Contributed Libraries/GLGraphics/Models/GLLights

**Comment by gohai** [comment]
That was the 1.5.1-era GL library, which is now obsolete (and not compatible with Processing 3.x).
