### ISSUE TITLE
P3 3.2.2/3.2.3 selectInput() under Mac OS X El Capitan & Sierra does not display user prompt

### ISSUE THREAD

**Issue by ajohnsonlaird** [processing/processing#4758]
Running Processing 3.2.2 and 3.2.3 under Mac OS X El Capitan and Sierra, selectInput() does not display the user prompt at the top of the dialog box.

![image](https://cloud.githubusercontent.com/assets/24278486/20807197/c4ff654c-b7b2-11e6-9bd3-d47c5ee9dc33.png)

However, under the earlier version of Mac OS X Mavericks, it does work correctly.

The sketch that demonstrates this is from the examples for selectInput():

```
void setup() {
  selectInput("Select a file to process:", "fileSelected");
}

void fileSelected(File selection) {
  if (selection == null) {
    println("Window was closed or the user hit cancel.");
  } else {
    println("User selected " + selection.getAbsolutePath());
  }
}

```

**Comment by benfry** [comment]
Thanks for the report. Hope that's one we can fix (and that Apple hasn't just taken that away…)

**Comment by benfry** [comment]
Looks like this one's out of our control, unfortunately. Either something is broken in Java, or Apple has removed the way the prompt is handled in the UI.

You can add `useNativeSelect = false;` to `setup()` and it'll bring the prompt back, but it'll be the ugly Java (Swing) dialog box.

**Comment by ajohnsonlaird** [comment]
Thanks, Ben.
I'll give it a try.

Cheers
Andy

Ben Fry wrote:

**Comment by ajohnsonlaird** [comment]
Just as a followup, this prompt problem also applies to selectFolder() under Mac OS Sierra.
Ben's suggestion of using `useNativeSelect = false;` in setup() does work.

Andy
