### ISSUE TITLE
Crash on startup as non-admin on 64 bit Windows 10

### ISSUE THREAD

**Issue by rushio0x58** [processing/processing#4760]
I downloaded the processing 3.2.3 64 bit binaries today and tried to launch it on my Windows 10 machine.
It crashed on startup with the following [error screen](http://imgur.com/a/balgE).

After having it run once as admin, I was able to start it without a crash as non-admin.
![processing_error_java](https://cloud.githubusercontent.com/assets/18518370/20859506/9f27a2fc-b961-11e6-81cd-966accb3dfe7.png)

**Comment by benfry** [comment]
Did you try to run it without first extracting it from the .zip file?

**Comment by rushio0x58** [comment]
No, I did extract the .zip file.

**Comment by benfry** [comment]
It's having trouble finding/opening a file that's included as part of the download. 
* Do you have any Tools or Modes installed? If one has its own (conflicting) copy of the netbeans outliner classes, that'll cause problems
* Are you running from a user directory with non-ASCII characters? Sometimes that causes trouble.
* Have you modified or replaced the 'java' folder included with the download? 
Trying to think of why running once as an admin would have an impact on this sort of error…

**Comment by rushio0x58** [comment]
I tried to reproduce the error, to no avail. Your listed points are also not applicable in my case. So either, contrary to my former statement, the .zip file was not fully unpacked or I missing something else...
Im closing this issue since it has probably nothing to do with the processing project. Thank you benfry.
