### ISSUE TITLE
(Processing language) Rotation problem

### ISSUE THREAD

**Issue by dominikanas** [processing/processing#4766]
Hi, so i'm making this project using the Processing language and i want to make something know as the theodorus wheel. 
 
![screenshot_2](https://cloud.githubusercontent.com/assets/24459442/21017835/5dad14e0-bd73-11e6-8019-9ec64d1d753d.png)

I want to make the wheel's triangles appear one by one each time i press the mouse button but even though the triangles parameters are right, and the rotating angle is calculated correctly, the rotation on the screen is too small (except for the first 2 triangles). But when i put the code in a for loop everything works perfectly.

Here is the result:
![screenshot_3](https://cloud.githubusercontent.com/assets/24459442/21017872/788c196e-bd73-11e6-86b7-cf1c9241033e.png)

And here is the code(the texts are draw to see if the angles are correct):

int x;
int y;
int i;
void setup(){
  x = 0;
  y = 0;
  size(800,800);
  smooth();
}

void draw() {
  translate(width/2+100,height/2);  
}

void mousePressed() { 
      i+=100;
      rotate(-asin(1/sqrt(i/100)));
      triangle(x-sqrt(i*100), y, x, y, x-sqrt(i*100), y-100);
      text(degrees(-asin(1/sqrt(i/100))), 100,100);
}

**Comment by benfry** [comment]
Please use forum.processing.org for coding questions.
