### ISSUE TITLE
Ability to close tab and not delete it

### ISSUE THREAD

**Issue by DollarAkshay** [processing/processing#4769]
I was wondering whether or not you are able to close a file tab without deleting a file. If not could this be implemented ?

Also ability to rearrange the tabs would be a nice feature too.

**Comment by benfry** [comment]
Thanks for the suggestion, but it's not on the radar… To do this, we'd need to add new UI to bring the tab back, and add a project file that stored the state of all the tabs. The editor is meant to be extremely simple and work for a few tabs, not re-implement all the features of a full IDE.
