### ISSUE TITLE
println() returning code gibberish instead of strings

### ISSUE THREAD

**Issue by WinnerEX** [processing/processing#4771]
Processing 3.2.3
Windows XP

println() used on a string array correctly returns each element of the array in console:
println(test);
//a
//b
//c

however when including other variables to the function, returns gibberish:
println(test + "words " + var);
//[Ljava.lang.String;@#####words var

PDE also gives an error without the example string included:
println(test + var);
The operator + is undefined for the argument type(s) String[], int

**Comment by WinnerEX** [comment]
Using a comma in lieu of + gets rid of the PDE warning, but still returns the list as gibberish.

**Comment by colouredmirrorball** [comment]
I believe this is intended behaviour. println() tries to parse data types as good as it can (like printing individual array elements) but when you use the + operator, Java first concatenates the elements and then passes the result on to the println() method. Arrays, like other data types, have a toString() method that automatically gets called when trying to parse something as a String (the + operator calls this). This toString() method usually prints out stuff like the class name and the memory location.

So to get some meaningful result, try it like this: println(test, "words", var).

**Comment by benfry** [comment]
Not a bug… The behavior you're describing for `println()` is the behavior inherited from Java. There's no way for us to know that `test` in your example is an array, because Java has already called its `toString()` method. To avoid confusion, use `printArray()` to print arrays.
