### ISSUE TITLE
custom function variables have incorrect attribution

### ISSUE THREAD

**Issue by WinnerEX** [processing/processing#4772]
<code>int z;</code>
<code>int i;</code>
<code>int u;</code>

<code>//in this example, draw loops "test(z);", yet the actions of test(z) being "z++" are not cumulatively added, and the result remains 0.</code>
<code>//meanwhile, "i++" after "test(z);" increases with every draw, and so does the result of "test2()"'s u++;</code>

<code>void test(int r){</code>
<code>  r++;</code>
<code>}</code>

<code>void test2(){</code>
<code>  u++;</code>
<code>}</code>

<code>void draw(){</code>
<code>  test(z);</code>
<code>  test2();</code>
<code>  i++;</code>
<code>  println(z, i, u);</code>
<code>}</code>

**Comment by benfry** [comment]
That's a bug in your code… Do a search for "pass by value" versus "pass by reference" for a more complete description than I can give here. You're passing a value to the function, not the variable itself, so it won't update the original variable.

**Comment by WinnerEX** [comment]
only bug I can find is Java likes pass by value too much.
