### ISSUE TITLE
Spaces not handled correctly in when installing "processing-java" on macOS

### ISSUE THREAD

**Issue by jakeKonrad** [processing/processing#4779]
I have Processing 3.1.1 and am running it on Mac OS. After running install "processing-java" from the dropdown menu Tools, and then trying to run proccesing-java --help in Terminal, I received the message
/usr/local/bin/processing-java: line 13: /Users/jakekonrad/Downloads/Processing: No such file or directory. This was easily fixed by navigating to /usr/local/bin/processing-java and editing the file so that line 13 looked like this 

cd "/Users/jakekonrad/Downloads/Processing 3.app/Contents/Java" && /Users/jakekonrad/Downloads/Processing\ 3.ap    p/ ... (I've omitted the rest)

as opposed to

cd "/Users/jakekonrad/Downloads/Processing 3.app/Contents/Java" && /Users/jakekonrad/Downloads/Processing 3.ap    p/ ...

The key difference being the \ after the Processing in the path after &&.

**Comment by benfry** [comment]
Surprised this one hasn't come up earlier. Thanks for the report.
