### ISSUE TITLE
JDWP No transports initialized,Address already in use

### ISSUE THREAD

**Issue by hellowewe** [processing/processing#4785]
Hi All.
I run under the network environment in processing is no problem.
But, when I run it without Internet will appear the error like this.
My friend can run in without the Internet, very strange.
(processing 3.2.3   macOS 10.12.1)

`[0] "FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)"
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
`

Thanks in advance - any help or suggestions would be appreciated.

**Comment by benfry** [comment]
What do you mean by no internet? That wifi is turned off? Or that no wifi connection is available?

**Comment by hellowewe** [comment]
There is no wifi connection is available.Because my projects is in outdoor.
Can't run without internet Is this normal?
think you for answer : )

**Comment by benfry** [comment]
The software runs fine without internet, so I'm trying to figure out why it's not working on your machine.

I'm asking whether you've also turned off wifi, in addition to not having a connection available. If you have not, try that and see what happens. (This means going to the wifi menu at the top of your screen and selecting "Turn Wi-fi Off", or re-enabling it the same way.)

**Comment by hellowewe** [comment]
yes，i turned Wi-fi Off.And I did 3 tests.

1 turn off wifi - open processing - run - not work
2 turn off wifi - open processing - turn on wifi connection to the internet - run - work
3 turn on wifi connection to the internet - open processing - run - work - stop - turn off wifi - run - work

So I guess ' JDWP No initialized ' is key in ERROR.Then i google the JDWP,I found ' It is a packet-based network binary protocol. '.Maybe my machine lacks something, so I have to do JDWP.May be usually not needed, but I do not know what is that.

**Comment by benfry** [comment]
When running a sketch, Processing uses a “network” connection that is re-connecting to your machine. It's something we get from Java, and JDWP is the name of the protocol used. You don't need anything additional. 

So the problem that's happening is that while the network isn't available, your machine is somehow causing connections even to the same machine to fail, which is weird. Maybe it's a macOS Sierra problem. 

Other possibilities… 
* Do you have the macOS firewall turned on? 
* What devices are listed in your network 
* Have you ever modified your `/etc/hosts` file? (if so, it could be this problem: https://github.com/processing/processing/issues/4738)

**Comment by hellowewe** [comment]
- Firewall is turned off.
- There is Wi-Fi,BluetoothPAN,Thunderbolt Bridge in the Network Preferences window.
- I try to check `/etc/hosts` and I got this.

> /etc/hosts: line 7: 255.255.255.255: command not found
> /etc/hosts: line 8: ::1: command not found
> /etc/hosts: line 9: 162.212.59.2: command not found
> /etc/hosts: line 10: 162.212.59.2: command not found
> /etc/hosts: line 11: 162.212.59.2: command not found
> /etc/hosts: line 13: 127.0.0.1: command not found
> /etc/hosts: line 14: 127.0.0.1: command not found
> /etc/hosts: line 15: 127.0.0.1: command not found
> /etc/hosts: line 16: 127.0.0.1: command not found
> /etc/hosts: line 17: 127.0.0.1: command not found
> /etc/hosts: line 18: 127.0.0.1: command not found
> /etc/hosts: line 19: 127.0.0.1: command not found
> /etc/hosts: line 20: 127.0.0.1: command not found
> ...
 
I don't know why this `162.212.59.2`.It seems like I used to VPN,and I don't need it now.

`127.0.0.1: command not found` It look not good,
Please tell me how to correctly set hosts.
Thanks.

**Comment by benfry** [comment]
Oh, don't try to run /etc/hosts; just type: 

`cat /etc/hosts` 

And print the contents here.

**Comment by hellowewe** [comment]
I have repaired my processing.
The reason is I modified hosts before.I miss deleted  `127.0.0.1 localhost `
And I try to restored the original hosts file, my processing can be run without internet environment!

Thank you for your answer,
Have a good New Year ！：）
