### ISSUE TITLE
coming up with a new website and an overall translation of the ide, the documentation and the website to as many languages as possible

### ISSUE THREAD

**Issue by tiagmoraismorgado** [processing/processing#4789]
**_Greetings_**

The current processing website, is almost as old as the environment (ide + libraries) are. Some minor updates have actually been added to the entire thing, but I think it would actually be interesting to:
- **A)** _coming up with a new website._
- **B)** _coming up with a translated version of the website and the overall documentation to as many languages as we can_

Regarding the first topic:
Since processing is actually javascript based, a blend of technologies (and this is only a suggestion), like: **html5, css, php, javascript, c#, bootstrap, angular.js, rubyonrails. node.js**. and subsequently **webgl** and **processing**. could actually allows us to get a responsive interactive site, that could bring some delightfulness to new users, and possibly even helping to engage the community (don't understimate the power of UI/UX in user community management).

Regarding the second topic:
Something like https://hosted.weblate.org/accounts/register/ could eventually be of much interest to the overall community. sonic pi community leaded by **sam Aaron,** is already taking a lot of advantage out of this website, and it has bindings with **GitHub**, **bitbucket** and a few more websites

**Looking forward,**
_kind regards - tiago_

**Comment by DJSandmannTV** [comment]
German translator volunteer here...

**Comment by benfry** [comment]
This is a better discussion for https://github.com/processing/processing-docs/issues.
