### ISSUE TITLE
Creating a second window using any method not working

### ISSUE THREAD

**Issue by ForwardMetrics** [processing/processing#4791]
I've tried all the methods I've found to create a second window (primary is 3D, secondary is 2D) - but all have serious problems. Using libraries such as G4P and ControlP5 cause crashing on exit and have problems with mouse interaction. I've tried JFrame which does not have these problems but seems to not be supported anymore as I cannot draw on the secondary window or find a working sample. 

What is the correct way to create a second window?

**Comment by Insanityandme** [comment]
There are definitely ways of creating second windows in Processing 3, I've been digging a few hours to find a way and here's a few links and resources with functional examples:

https://gist.github.com/atduskgreg/666e46c8408e2a33b09a

**Comment by GoToLoop** [comment]
Only 1 _**PApplet**_ can use an OpenGL-based renderer (P2D & P3D) for the same sketch.  
Same rule for FX2D renderer too. However, we can have more than 1 _**PApplet**_ under JAVA2D renderer.

**Comment by benfry** [comment]
Multiple windows are not a supported feature, so this doesn't belong here. There are some ways to get two windows working, but that's a better discussion for the [forum](http://forum.processing.org).
