### ISSUE TITLE
console print(); in p5.js mode not functioning

### ISSUE THREAD

**Issue by kwsherwood** [processing/processing#4793]
`function draw() {
  print("text");
}`

Does not seem to be functioning in the Processing editor when set to p5.js mode.  
Working with Processing 3.2.3, Windows 64bit.

**Comment by benfry** [comment]
That's a separate project, you can file issues here: https://github.com/fathominfo/processing-p5js-mode/issues

Though the quick answer is that you have to use the web browser's console, since we can't get `console.log()` output from the PDE.
