### ISSUE TITLE
Disable Image Interpolation in P2D (Eclipse)

### ISSUE THREAD

**Issue by DJSandmannTV** [processing/processing#4794]
We currently develop a little game in Processing. To keep thins simple and get into the workflow I use Eclipse. I now struggle to find a solution to disable image interpolation for my sprites. I already found different solutions on the internet, but most of them refer to Processing 2.x.

I also read about adding
`hint(DISABLE_TEXTURE_MIPMAPS);
((PGraphicsOpenGL)g).textureSampling(2);`
to the `setup()` function, however it gives me a NullPointer Exception.

Is there any way in the current processing version to disable image interpolation?

**Comment by cacheflowe** [comment]
These methods still work in Processing 3. Just call them in the `draw` loop rather than in `setup()`. If you only want to set it once, you could set it on the first frame: 

```
public draw() {
  if(frameCount == 1) {
    hint(DISABLE_TEXTURE_MIPMAPS);
    ((PGraphicsOpenGL)g).textureSampling(2);
  }
}
```
