### ISSUE TITLE
New Version Download Not Working

### ISSUE THREAD

**Issue by ThatGuyFromKA** [processing/processing#4803]
Processing keeps telling me "A new version of Processing is available..." However, when I try and download the latest version(3.2.3), I get a copy of my current version(3.1.2) This is for Mac OS X El Capitan (v10.11.6)

**Comment by benfry** [comment]
Just tried downloading the Mac version from the download page and it's working fine. Make sure you've quit out of the old version before starting the new one. It's not possible to run two copies/versions at the same time.
