### ISSUE TITLE
OpenGL shader regex bug

### ISSUE THREAD

**Issue by neilcsmith-net** [processing/processing#4810]
There seems to be a bug in the regex for updating GLSL code, which breaks the default texture rectangle shader.  I think `textureRect` should be `texture2DRect` in https://github.com/processing/processing/blob/master/core/src/processing/opengl/PGL.java#L1957

Noticed this while having a look at what might be involved in getting Syphon to work.

**Comment by JakubValtar** [comment]
You're right. My bad, I left it out when rewriting preprocessor into regex. https://github.com/processing/processing/pull/4052/files#diff-88c7dd4e8f37672d20e228a71a433a6dL1889
