### ISSUE TITLE
Not all files are exporting to application

### ISSUE THREAD

**Issue by quazzart** [processing/processing#4814]
My little program uses custom fonts
Like: When I'm exporting application fonts aren't exporting

Windows x64 / Processing 3.2.3 x64

**Comment by benfry** [comment]
Are they in the "data" folder?

**Comment by quazzart** [comment]
They are in sketch folder

**Comment by benfry** [comment]
They won't be copied unless they're in the data folder: 
https://processing.org/reference/loadFont_.html
https://processing.org/reference/createFont_.html
