### ISSUE TITLE
Image window never opened

### ISSUE THREAD

**Issue by Bliep1** [processing/processing#4817]
Hi, 

I am working with Mac OS Sierra 10.12.2. 
After installing Processing 3, I tried working with it, but somehow the window in which the drawings are supposed to show (I don't know if this window has a specific name), never opens. It looks like Processing works fine, I get errors in red in the downside of the screen, which disappear when I write right code, but the image window just never runs. I tried installing older versions of Processing, and the same issue occurs. I tried re-installing my OS, but even then, the same problem. 

Another thing that I noticed, is that no text shows in the console, in the black part underneath (message window?), when I try a println. 

What can I do now? I'd really like to get this fixed. 

Thanks, in advance, for the help.

**Comment by gohai** [comment]
Does this also happen when you try to run an empty sketch?

**Comment by Bliep1** [comment]
Yes

**Comment by benfry** [comment]
Have you messed with your /etc/hosts file, in particular, to redefine localhost?

**Comment by Bliep1** [comment]
I don't know what that means. Therefor I can't remember doing that. What is my /etc/host file supposed to look like? 

I've had this mac for about 6 years, and I can't recall everything I did. So I can't be certain that I didn't. 

How can I find out?

**Comment by gohai** [comment]
@Bliep1 Open up a Terminal (Spotlight: `Terminal`), and type `cat /etc/hosts` followed by `[Return]`.

**Comment by Bliep1** [comment]
I don't know what it should look like, but this is what I get:


##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1     
255.255.255.255 brodcasthost
::1             localhost
fe80::1%lo0     localhost 
127.0.0.1 hl2rcv.adobe.com
127.0.0.1 t3dns.adobe.com
127.0.0.1 3dns-1.adobe.com
127.0.0.1 3dns-2.adobe.com
127.0.0.1 3dns-3.adobe.com
127.0.0.1 3dns-4.adobe.com
127.0.0.1 activate.adobe.com
127.0.0.1 activate-sea.adobe.com
127.0.0.1 activate-sjc0.adobe.com
127.0.0.1 activate.wip.adobe.com
127.0.0.1 activate.wip1.adobe.com
127.0.0.1 activate.wip2.adobe.com
127.0.0.1 activate.wip3.adobe.com
127.0.0.1 activate.wip4.adobe.com
127.0.0.1 adobe-dns.adobe.com
127.0.0.1 adobe-dns-1.adobe.com                 
127.0.0.1 adobe-dns-2.adobe.com
127.0.0.1 adobe-dns-3.adobe.com
127.0.0.1 adobe-dns-4.adobe.com
127.0.0.1 ood.opsource.net
127.0.0.1 practivate.adobe
127.0.0.1 practivate.adobe.com
127.0.0.1 tpractivate.adobe.newoa
127.0.0.1 practivate.adobe.ntp
127.0.0.1 practivate.adobe.ipp
127.0.0.1 ereg.adobe.com
127.0.0.1 ereg.wip.adobe.com
127.0.0.1 ereg.wip1.adobe.com
127.0.0.1 ereg.wip2.adobe.com
127.0.0.1 ereg.wip3.adobe.com
127.0.0.1 ereg.wip4.adobe.com
127.0.0.1 wip.adobe.com
127.0.0.1 wip1.adobe.com
127.0.0.1 wip2.adobe.com
127.0.0.1 wip3.adobe.com
127.0.0.1 wip4.adobe.com
127.0.0.1 www.wip.adobe.com
127.0.0.1 www.wip1.adobe.com
127.0.0.1 www.wip2.adobe.com
127.0.0.1 www.wip3.adobe.com
127.0.0.1 www.wip4.adobe.com

**Comment by benfry** [comment]
Yeah, so you've edited that file so that you can run a pirate version of Adobe's apps. The result is that you've broken that file. 

The first line should read `127.0.0.1 localhost`. Once that's changed, Processing will work again.
