### ISSUE TITLE
Black Screen on Raspberry PI 3

### ISSUE THREAD

**Issue by PrinzJuliano** [processing/processing#4818]
I have a simulation that i want to run and the graphical representation works fine on windows but I get a black screen for the same PDE on my pi. 

Any clues?

BTW: No errors, no warnings, nothing that raises suspicion.  
In fact: 2D seams to work fine but 3D does not work. But running `glxgears -info` works just fine with 33 FPS.

Specs:  
Model:                   Raspberry Pi 3 Model B Rev 1.2  
Ram Split: arm=752MB + gpu=256MB  
GL_RENDERER   = Gallium 0.4 on llvmpipe (LLVM 3.7, 128 bits)  
GL_VERSION    = 3.0 Mesa 11.1.0  
GL_VENDOR     = VMware, Inc.

**Comment by gohai** [comment]
@PrinzJuliano
Which operating system (Linux distribution) are you running on the Raspberry Pi? You seem to be using the vc4 Mesa driver, which isn't what the Raspbian distribution is using by default.

How did you set the RAM split? Can you share the sketch for us to reproduce?

**Comment by PrinzJuliano** [comment]
I use the newest version of PIXEL (Raspbian).  
You can do the ram split in the settings of the raspberry. [Here is a picture](http://prntscr.com/dtbhsu)  
And the sketch is basically this: 
```java
import peasy.*;

float x = 1;
float y = 1;
float z = 1;

int scale = 5;

float a = 10; //o
float b = 28; //p
float c = 8/3;//B

boolean fullS = false;

ArrayList<PVector> points = new ArrayList<PVector>();

PeasyCam cam;

void settings(){
  PJOGL.setIcon("titleBar.png");
  //fullScreen(P3D, SPAN);
  size(800, 800, P3D);
}

void setup() {
  cam = new PeasyCam(this, 500);
  colorMode(HSB);
  frameRate(60);
}

void draw() {
  background(15);
  float dt = 0.005;
  float dx = (a * (y - x))*dt;
  float dy = (x * (b - z) - y)*dt;
  float dz = (x * y - c * z)*dt;
  x = x + dx;
  y = y + dy;
  z = z + dz;

  points.add(new PVector(x, y, z));

  
  //translate(width/2, height/2);
  translate(0, 0, -80);
  scale(scale);
  noFill();

  float hu = 0;
  beginShape();
  for (PVector v : points) {
    stroke(hu, 255, 255);
    vertex(v.x, v.y,v.z);
    //PVector offset = PVector.random3D();
    //offset.mult(0.1);
    //v.add(offset);

    hu += 0.1;
    if (hu > 255) {
      hu = 0;
    }
  }
  endShape();
  


  //println(x,y,z);
}

void keyPressed(){
 if(keyCode == UP){
   scale++;
 }
 else if(keyCode == DOWN){
  scale--; 
 }
 
 scale = constrain(scale, 1, 20);
 
}
```

**Comment by gohai** [comment]
@PrinzJuliano Thanks. Did you by chance enable the "experimental" OpenGL renderer (e.g. in `raspi-config`)?

**Comment by PrinzJuliano** [comment]
@gohai Thanks for the quick help. Disabling the experimental version helped but the problem persists while using VNC (main method of supervision). When connecting a hdmi cable it runs fine.

**Comment by gohai** [comment]
@PrinzJuliano Did you test the experimental driver via VNC only, or was this also not working with HDMI?

As for the regular driver over VNC: did you enable direct capture as detailed [here](https://www.realvnc.com/docs/raspberry-pi.html#running-directly-rendered-apps-such-as-minecraft-remotely)?

**Comment by PrinzJuliano** [comment]
I do now. Everything is working fine!
For all others: Disable experimental GL Drivers (which haad no effect though) and enable direct capture!
