### ISSUE TITLE
Combining fullScreen(P3D) and smooth(8) makes the animation stop (late 2009 iMac)

### ISSUE THREAD

**Issue by LePhasme** [processing/processing#4820]
Configuration:

- Processing 3.2.3
- iMac 27" (late 2009: ATI Radeon HD 4850 512 Mo, 2560x1440 pixels)
- macOS Sierra 10.12.2

Sample sketch:

```
void setup() {
  fullScreen(P3D);
  frameRate(60);
  smooth(8);
  background(255);
  stroke(0);
  noFill();
}

void draw() {
  line(random(0, width), random(0, height), random(0, width), random(0, height));
}
```

Steps to reproduce:

- Run the sketch above
- **Expected behavior:** random lines are displayed across the screen
- **Actual behavior:** a single line is displayed across the screen (then the animation seems to stop) — sometimes the screen remains blank

Workarounds:

- Replace `smooth(8);` with `smooth(3);`
- Or replace `fullScreen(P3D);` with ` size(W, H, P3D);`, where `W` and `H` are inferior to the actual full screen dimensions (here not much more than 2350x1322 for instance)

**Comment by benfry** [comment]
This isn't really a "bug" we can fix… it just means your 2009 iMac can't do 8x smoothing at full screen…
