### ISSUE TITLE
NoSuchFieldError: useNativeSelect

### ISSUE THREAD

**Issue by vvac** [processing/processing#4821]
![zrzut_ekranu-it was not meant to be](https://cloud.githubusercontent.com/assets/18726567/21782052/490f8c9a-d6b2-11e6-9fd0-3c9f9fdf21bd.png)

Linux:
Linux vvacbook 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:41:14 UTC 2012 i686 i686 i386 GNU/Linux

Java:
oracle-java8-jre
lrwxrwxrwx 1 vvac vvac 26 sty  9 21:20 processing-3.2.3/java -> /usr/lib/jvm/java-8-oracle

**Comment by benfry** [comment]
That looks like you have a Library or Tool in your sketchbook folder that includes the contents of `core.jar`. Try renaming your `tools` folder and adding them back one-by-one to figure out which one it is. When you find out, please zip it up and post a copy here so we can find a way to work around this.

**Comment by vvac** [comment]
A had to download processing IDE again in order to test what you said. This time processing run without a problem. The only Tool present in tools directory was MovieMaker.

**Comment by benfry** [comment]
Any libraries in your sketchbook?

**Comment by benfry** [comment]
No response; closing.
