### ISSUE TITLE
JRE download fails during ant build

### ISSUE THREAD

**Issue by jdf** [processing/processing#4823]
```sh
/usr/local/google/home/feinberg/processing/build/build.xml:288: The following error occurred while executing this line:
/usr/local/google/home/feinberg/processing/build/build.xml:234: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at Downloader.download(Downloader.java:177)
```

**Comment by benfry** [comment]
Yeah, Oracle has changed something again in their download process. Patched it for 8u112, but the same code doesn't work for 8u121 so we won't move to that yet… We'll have to keep an eye on [this page](http://stackoverflow.com/questions/10268583/downloading-java-jdk-on-linux-via-wget-is-shown-license-page-instead) for any updates.
