### ISSUE TITLE
Array print issue

### ISSUE THREAD

**Issue by kjwamlex** [processing/processing#4825]
When Processing tries to print out 200 elements in 3 arrays, Processing itself freezes and must force quit the application. macOS 10.12.2

**Comment by gohai** [comment]
Can you share your sketch with us, or at least the relevant parts?

**Comment by Lord-of-the-Galaxy** [comment]
Too much `print`/`println` also tends to kill processing sketches. Perhaps it's the same problem?  

This, for example, crashes for me:  

```java  
void setup(){
  size(100, 100);
}

void draw(){
  for(int i = 0; i < 10000; i++){
    for(int a = 0; a < 10000; a++){
      print(i + " " a);
    }
    println();
  }
}

**Comment by kritixilithos** [comment]
@Lord-of-the-Galaxy `print` statements generally slow the program down, especially in loops. Now you are calling over `100,000,000` print statements every fraction of a second (because of the `draw()` statement).

**Comment by Lord-of-the-Galaxy** [comment]
@kritixilithos I _know_ why Processing crashes with many print statements and I'm _not_ expecting anyone to be able to allow Processing (in fact, Java itself (it would be System.out.print there)) to have thousands of print statements. I was only wondering if this current issue may be related to the fact that too many print statements crash Java/Processing.

**Comment by kritixilithos** [comment]
@Lord-of-the-Galaxy  I'm guessing it's because they are high level languages. I tried this with `C`, and it started printing tons of stuff without crashing or freezing for some time (but later I `^C`ed it because it was spamming my Terminal).

**Comment by Lord-of-the-Galaxy** [comment]
@kritixilithos You're probably right. But we still don't know if the printArray problem occurs because of it.

**Comment by benfry** [comment]
Taking a look into this one… close to a fix.
