### ISSUE TITLE
Movie Maker gets confused with numbers

### ISSUE THREAD

**Issue by PrinzJuliano** [processing/processing#4829]
I have a captured 20000+ Frames with saveFrame('####.tif') and I used the Movie Maker Tool to create a 60 FPS movie. But it first processed 1 to 20000 and then processed from 7000. The result is a mixed up movie which has some frames totally mixed up and weird flickering occours!

Fixing the error is simple:
Add more # in your saveFrame which will add more 0 to the filename.

**Comment by benfry** [comment]
We can't prevent you from making errors in your code… I don't know how we'd sensibly handle this situation.
