### ISSUE TITLE
My program remains in the background

### ISSUE THREAD

**Issue by Error1000** [processing/processing#4831]
So when i run my program made in processing and close it the background process is closed BUT when i run the program and it crashes for example: processing didn't found the location of a PImage, when i  close the window and look in task manager there is still a javaw process in the background and windows doesn't let me delete the jar file until i manually kill the process.
Note: I use eclipse so i can export my project as a jar file.

**Comment by gohai** [comment]
Does the same happen to you when you run it with the Processing IDE?

**Comment by Error1000** [comment]
I don't know the project is too big to port it to the processing ide

**Comment by gohai** [comment]
Does your project use threads by chance? The P2D or P3D renderer?

Not sure if there is much to narrow this down further... you could of course try to narrow it down to a small test case that exhibits the issue. But whatever it is, it doesn't seem to be biting the majority of users that make use of the IDE.
