### ISSUE TITLE
Processing3 running really slow on RPI3

### ISSUE THREAD

**Issue by usernamevalis** [processing/processing#4836]
Im not sure what I could expect performance wise from Processing3 so I just want to throw this out there. 

I have a really simply app running on a RPI3 it displays a (750kb .png) at full screen(1920x1080) and occasionally draws some ellipses on top of it.

It runs at about 6 fps - is this normal , or am I doing something incorrectly?

Thanks

**Comment by benfry** [comment]
Please use forum.processing.org for general questions about usage.
