### ISSUE TITLE
mouseWheel() incorrectly documented

### ISSUE THREAD

**Issue by triss** [processing/processing#4837]
Documentation for `mouseWheel()` at https://processing.org/reference/mouseWheel_.html states that:

> The mouseWheel() function returns positive values when the mouse wheel is rotated down (toward the user), and negative values for the other direction (up or away from the user). 

`mouseWheel()` actually has return type `void`.

The event passed in to users implementation of `mouseWheel()` needs to be interrogated to find the direction mouse wheel has been rotated. 

Does the documentation need updating?

Perhaps details of how to use `MouseEvent`'s `.getAmount()` might be appropriate here?

**Comment by benfry** [comment]
Moved to the correct location for documentation issues: https://github.com/processing/processing-docs/issues/514
