### ISSUE TITLE
Processing 1.5.1 Package Error

### ISSUE THREAD

**Issue by a2304** [processing/processing#4841]
Keeps happening on Mac OSX 10.4 with Processing 1.5.1.  I am trying to read a sensor (simple potentiometer) from an Arduino and plot the result.

### Here is the full error message:

dyld: lazy symbol binding failed: Symbol not found: _open$UNIX2003
 Referenced from: /Applications/Processing 2.app/Contents/Resources/Java/modes/java/libraries/serial/library/macosx/librxtxSerial.jnilib
 Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _open$UNIX2003
 Referenced from: /Applications/Processing 2.app/Contents/Resources/Java/modes/java/libraries/serial/library/macosx/librxtxSerial.jnilib
 Expected in: /usr/lib/libSystem.B.dylib

**Comment by benfry** [comment]
Please use a newer release of Processing; we can't possibly support a release from five years ago.
