### ISSUE TITLE
Program will not open: "Problem while trying to get the sketchbook"

### ISSUE THREAD

**Issue by persimmony** [processing/processing#4851]
I just downloaded version 3.2.3 and every time I try to open it I get an error window saying "problem while trying to get the sketchbook", when I click okay the program shuts down. iOS X

**Comment by QueJo** [comment]
I don't know if it's related, i just updated nvidia drivers and i can't run any sketch, "Could not run the sketch (Target VM failed to initialize).". My processing 3.2.3 over Windows 7 worked fine until now. Exported sketches still working.

**Comment by aarondbaron** [comment]
QueJo, strangely I was noticing the same thing.  I updated my nvidia drivers and then all of a sudden targetvm failed to initialize

**Comment by QueJo** [comment]
Definitively is a nvidia drivers issue. I reinstalled previous drivers and processing works again.

**Comment by JakubValtar** [comment]
Please use this issue only for the original topic. Go to #4853 for Nvidia driver issue.

**Comment by persimmony** [comment]
This problem is still here. I've been able to download Processing and open it on other computers but mine (MacBook Pro 10.12 running on Sierra) cannot open it. I've tried going through the files manually to look for missing sketchbook files but the program won't let me in far enough to look.

**Comment by JakubValtar** [comment]
Hi, try to delete your preferences file, it should reset sketchbook location in case there is some nonsense:

~/Library -> Processing -> preferences.txt

**Comment by benfry** [comment]
No responses; closing. https://forum.processing.org is a better place for general troubleshooting questions anyway.

**Comment by jgarces02** [comment]
Sorry, but I've got the same problem and delete the preferences file don't fix it... any other idea, please?
