### ISSUE TITLE
Cursor() crashes Java VM

### ISSUE THREAD

**Issue by drewhamiltonasdf** [processing/processing#4852]
I was having issues with the Java VM crashing while running a rather complex processing sketch running multiple PApplets with runSketch() on multiple monitors in fullScreen() mode. 

After about 2 minutes, the program would crash, spitting out the dreaded "Could not run the sketch (Target VM failed to initialize)." After testing multiple versions I am 100% confident that the issue is cursor().

I assume this is some fatal combination of multiple PApplets within a sketch and Cursor(). Just thought I should mention it so the gurus know. Here's the rest of the dump: 

_#
A fatal error has been detected by the Java Runtime Environment:
#
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff26083def, pid=12912, tid=0x000000000000341c
#
JRE version: Java(TM) SE Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode windows-amd64 compressed oops)
Problematic frame:
C [msvcrt.dll+0x73def]
#
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
An error report file with more information is saved as:
C:\Users\DREWHA~1\AppData\Local\Temp\hs_err_pid12912.log
#
If you would like to submit a bug report, please visit:
http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

**Comment by aarondbaron** [comment]
I don't know if this is related, but today after an nvidia graphics card update, suddenly a message that says "Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.
"  started to show even on a blank sketch with nothing in it, preventing anything from running.  sorry to piggyback, but my search for the most recent post lead me here.

**Comment by JakubValtar** [comment]
@aarondbaron Please use this issue only for the original topic. Go to #4853 for Nvidia driver issue.

@drewhamiltonasdf Which renderer are you using? Default (Java2D), P2D, P3D, FX2D? Multiple windows are currently not supported, so I'm not sure if I will be able to help you.

**Comment by drewhamiltonasdf** [comment]
I've been using P3D.

**Comment by benfry** [comment]
Multiple `PApplet` objects in one sketch is bound to cause a lot of problems, not just with `cursor()`. That's not a supported or documented way of working.
