### ISSUE TITLE
Tag with version number

### ISSUE THREAD

**Issue by xyproto** [processing/processing#4855]
Hi,

Could you please tag releases as two separate tags:

* A version number tag, like `v3.2.3` or `3.2.3`
* A revision tag, like `0255`

Currently, when upgrading the Arch Linux package for processing, I have to visit your webpage to find both the latest version number and revision number. If tags would only contain the version number, it would be much easier. I extract the version number automatically from the processing/build/shared/revisions.txt file in master.

Please, stick either to the version number or the revision number, or tag both.

Best regards,
Alexander F. Rødseth

**Comment by GKFX** [comment]
You can get the full tag name by running
````bash
git tag --list | grep $(head -n 2 build/shared/revisions.txt | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
````
assuming the version number is in the form `x.x.x` (or even `x.xx.xx`) in the first two lines of revisions.txt.

**Comment by xyproto** [comment]
Yes, but that would only help for retrieving the version number and revision number. When selecting a version number for the package, version 3.2.3 is a natural choice, but then the package does not know the revision number and can not download the correct source package.

For example, the current PKGBUILD for processing has this set at the top:

    pkgver=3.2.3

And there is a comment at the bottom for where to automatically retrieve the version number, used by a custom tool, which retrieves `3.2.3`, as it should:

    # getver: https://raw.githubusercontent.com/processing/processing/master/build/shared/revisions.txt

But when retrieving the source tarball, the revision number 0255 is also needed, since it's part of the filename.

If `pkgver` was set to either `0255` or `3.2.3` and the source tarball used either `0255` or `3.2.3`, this would not be an issue. But the current method is different to all other packages I've ever encountered, and it makes packaging cumbersome.

I assume you want `processing` to be an official package on as many distros as possible, and make the packaging smooth and easy. Selecting a single version number, instead of two, would help immensely.

If you think that the version number **is** for instance `0255.3.2.3`, why does the "About box" say only `3.2.3`? And don't you think that looks slightly worse than just `3.2.3`?

**Comment by GKFX** [comment]
I don't run Processing, I just help, so I can't tell you exactly why policy is as it is or offer to change it. 3.2.3 is the version number and probably is what you want to put in `pkgver`. I'm assuming that you want to retrieve the file `https://github.com/processing/processing/archive/processing-0255-3.2.3.tar.gz`; is there any reason you can't use the shell code I gave to generate URLs of that form automatically on package build? `processing-0255-3.2.3` in that URL looks like it's just the tag name.
Anyway you can always wait for an official response from Ben Fry et al.

**Comment by xyproto** [comment]
It's possible to use the shell code above, but the idea of running a custom shell script per package when upgrading version numbers adds an extra step that could easily be avoided by just using a single version number instead of two.

Perhaps a version number on the form `0255.3.2.3` could be used? It would make things easier and also be more in line with how other open source projects does it.

**Comment by benfry** [comment]
So either you can do an extra step for the specific way you want this done, or we have to add an extra step (tagging twice) or change our build process (breaking consistency with all previous builds). I don't have enough free time to support every last thing like this, so we need to go with the former.

**Comment by xyproto** [comment]
I respect the decision, but it's weird.

**Comment by benfry** [comment]
And to be sure, calling it weird is an the best way to express that respect. 😄
