### ISSUE TITLE
Code executing even after putting more than one semicolon at the end

### ISSUE THREAD

**Issue by aryan10jangid** [processing/processing#4856]
processing 3.2.3

**Comment by GKFX** [comment]
That's valid Java; the line
````java
thingy();;
````
decomposes into the statement `thingy();` and the empty statement `;`, which does nothing. Not a bug.

**Comment by GiantTreeLP** [comment]
I don't think this is an issue.
Java allows as many semicolons as you want.

Unneeded semicolons will be dropped (they are merely obsolete but not wrong).
