### ISSUE TITLE
Cannot unzip 

### ISSUE THREAD

**Issue by yogeshlee** [processing/processing#4859]
When I download processing for Mac OS X, double-clicking the .zip file merely duplicates it—the file does not uncompress.

**Comment by gohai** [comment]
@yogeshlee This works fine with for me. Could you try to see if this is the same with some other zip file you download online? What do you see under `Open with` when you right click the file? (I see: `Archive Utility.app`)

**Comment by gohai** [comment]
Closing. Please reopen if you can reproduce this Issue (I can't here).

**Comment by yogeshlee** [comment]
Thanks for your help. I figured out that it’s a glitch with the Mac, not with Processing. Got it downloaded now and I’m enjoying it.

Yogesh
