### ISSUE TITLE
Could not run the sketch, Target VM failed to initialize

### ISSUE THREAD

**Issue by itisltw** [processing/processing#4863]
Somebody caught this issue before. However, at this time, I cannot run any sketch in Processing, even an empty one. I have done nothing before, there is no new installed software or kind of things, it just happens today.

I tried:

Remove directory of Processing
Download the newest version of our Windows
Remove directory of Processing and any files or folders of default sketchbook, Roming and Temp
Remove any things associated with Processing in regedit
Clean memories, temps, etc.
Restart system
Reinstall Java newest x64 JDK
Running command line checks whether the Java is recognized
Shutdown the firmware and viruses defender

Everything above I have done for at least 20 times give me nothing. The issue still exists

Please give me a help as quickly as possible, thanks, I must use Processing on projects recently

**Comment by Momel15** [comment]
Do you have a Nvidia graphics card? If yes, you should have a look at this: #4853

**Comment by benfry** [comment]
And if not, make sure you're using 3.2.4 (posted yesterday), and haven't messed with `c:\windows\system32\drivers\etc\hosts`.

**Comment by itisltw** [comment]
Thanks, after previous version of Nvidia driver installed the processing works fine now

**Comment by MrThoe** [comment]
I have this same issue whenever I unplug my headphones.  My sketch works perfectly (well it works like it's supposed to at least) when I have earphones on but when I unplug and try and play through the speakers it crashes.  Speakers work for all other programs.  

Any idea why processing would care if I am using the speakers or the headphones???  So strange....

**Comment by animanoir** [comment]
@MrThoe I'm here experiencing the same.

Sometimes it works. Sometimes it doesn't. Seems to be a thing with the feeble Sound library, since I'm using it too...

**Comment by benfry** [comment]
(Removed two unrelated posts and locking this issue since the problem was resolved 18 months ago.)
