### ISSUE TITLE
Kinect V1 and Processing Error Code! 

### ISSUE THREAD

**Issue by paigey95x** [processing/processing#4866]
Hello,

I've downloaded the kinect library, when I try playing an example it keep coming up with the error message "32 windows, A library relies on native code that's not available. Or only works properly when the sketch is run as a 64-bit application". Does anyone know the solution to fixing this problem? 

Thank you!!

**Comment by benfry** [comment]
Please use forum.processing.org for coding and troubleshooting questions.
