### ISSUE TITLE
Point Doesn't Appear With Square Stroke Cap in Default Renderer

### ISSUE THREAD

**Issue by behreajj** [processing/processing#4871]
`size(400, 400);
background(255);
strokeWeight(20);
stroke(0);
strokeCap(SQUARE);
point(200, 200);`

Compare with `size(400, 400, P2D);` .

Using v3.2.4.

**Comment by benfry** [comment]
That's correct. You're looking for `strokeCap(PROJECT)`:
https://processing.org/reference/strokeCap_.html
