### ISSUE TITLE
"Could not find sketch size" pop up is not clickable.

### ISSUE THREAD

**Issue by algotrash** [processing/processing#4876]
I tried using: size(800,width*.8);

This opens a pop up stating that you can only use numbers and not variables for the size command.
But when I click OK or on the cross to close the pop up and go back to my code, nothing happens. I'm stuck on the pop up. I can move it, but there is no mouseover animation of the OK button. If i click outside, it beeps.
Any idea?

**Comment by benfry** [comment]
Duplicate of #4893.
