### ISSUE TITLE
crashes, not responding after updating [Macbook, Sierra]

### ISSUE THREAD

**Issue by njkiray** [processing/processing#4877]
Hello processing people,

When I was prompted to download the newest update to Processing, it froze (had 3.2.3, updating to 3.2.4), so I deleted it and manually downloaded the newest version of Processing. Now, what will happen is the initial window will open, I get the beach ball of death, and have to force quit. When I open a previous sketch with the application closer, it will open the sketch, but freeze the UI and I'll have to force quit. Not sure why, could someone kindly help me with this? Thank you!

<img width="345" alt="screen shot 2017-02-02 at 11 59 54 pm" src="https://cloud.githubusercontent.com/assets/7988816/22580139/dc1287be-e9a3-11e6-9624-c81d92513a90.png">

**Comment by gohai** [comment]
You should be able to reset Processing's state with executing this in a Terminal

    rm -Rf ~/Library/Processing/

Afterwards, your installation of 3.2.4 should work as intended.
