### ISSUE TITLE
No error messages shown when it should.

### ISSUE THREAD

**Issue by GX20Ty** [processing/processing#4880]
I was testing a project of 14 tabs when I got an error. The error was weird but it's not the problem.
 No error message was shown, the sketch just didn't run and it highlighted the area which was supposed to give the error.
![image](https://cloud.githubusercontent.com/assets/12967824/22622948/5600555e-eb4a-11e6-9a9c-f089124e0afd.png)

**Comment by Lord-of-the-Galaxy** [comment]
The nature of the error may be important, so please mention that too.

**Comment by benfry** [comment]
I don't see an error there, it's just a line that's been selected. What's your indication that this is an error?

**Comment by Lord-of-the-Galaxy** [comment]
Actually, if you look at line 25 and line 28 (highlighted line), there's a discrepancy - in case of line 25, `shape.bBox` is an `int`, whereas by line `28`, it seems to have become a PShape (or maybe some other custom class having `getVertexCount()` as a function). this points to an error on you side. However, this was not mentioned by the IDE. Perhaps you might done something when the error message was shown.  
@benfry This, however, proves that there _is_ an error in the code, for what it's worth.

**Comment by benfry** [comment]
Ok, though there's still nothing I can reproduce from this screenshot to find the issue. With the original sketch in this exact state, sure… But for now, I need to close this issue unless someone can post a reproducible version of the problem.

**Comment by shadoxxhd** [comment]
I have the same problem - independent of what the exact error is, processing doesn't show me any error code. It correctly highlights the relevant line, but doesn't display any text.

**Comment by Lord-of-the-Galaxy** [comment]
If there's a way to reproduce the problem, please let us know @shadoxxhd
