### ISSUE TITLE
Auto Format feature wrongly indents switch blocks

### ISSUE THREAD

**Issue by oxxie** [processing/processing#4881]
The editor's Auto Format feature (Cmd-T on Mac) wrongly indents `switch` blocks, by indenting the contents of the block (between `{` and `}`) on the same indent level as the `switch` statement itself, like so:

```
switch (foo) {
case 0:
  bar = 1;
  break;

case 1:
  bar = 0;
  break;
}
```

IMHO, the `case` statements should be indented one level deeper than the `switch` statement.

**Comment by gohai** [comment]
I am very much used to seeing code that _doesn't_ indent the `case` line - e.g. [here](https://developer.gnome.org/programming-guidelines/stable/c-coding-style.html.en), [here](http://syque.com/cstyle/ch6.12.htm).

Thanks for your suggestion, but I believe this should be kept as is.

**Comment by oxxie** [comment]
Thank you for your feedback @gohai. It turns out there are multiple styles around for indenting `case` statements; the [Processing reference](https://processing.org/reference/switch.html) itself uses the following style:

```
switch(num) {
  case 0: 
    println("Zero");  // Does not execute
    break;
  case 1: 
    println("One");  // Prints "One"
    break;
}
```

I guess in the end it's up to the developers' preference on how the Auto Format feature behaves.

**Comment by gohai** [comment]
@oxxie Agree. With these small behavioral changes, where one could have preferences for either, it's often more a question whether someone cares _strongly enough_ to put together (and test, submit, argue for) a patch that implements the change.

Chances are that the folks that contribute to Processing in their spare time will primarily tackle the most pressing issues. Or, work on what catches their own eyes, they feel like improving.

If you want to jump in yourself and submit a patch: the code for the auto formatter is in java/src/processing/mode/java/AutoFormat.java - happy to review any PR
