### ISSUE TITLE
Bug for ascii > 128 with Windows 10

### ISSUE THREAD

**Issue by DDEFF** [processing/processing#4883]
Hi !

If I want the   ASCII(197) , I want   ┼, for example.
It's normal.
But in the listing, I have 
![ascii](https://cloud.githubusercontent.com/assets/25547803/22628190/ff4c4700-ebcf-11e6-9955-2984c216217a.png)

The problem appears before 3.2.4 version.

Thank's

**Comment by benfry** [comment]
Those characters should work fine in the editor. That looks like you've edited the file outside Processing, and didn't use UTF-8 encoding. If that's not the case, please re-open.
