### ISSUE TITLE
Processing 3.2.4 windows32 Trojan warning

### ISSUE THREAD

**Issue by SuperLongNameImNotSureItsTakenOrNot** [processing/processing#4884]
My Windows Defender found a Trojan virus (Trojan:win32/Mefurac.E!cl)  at the processing.exe file.

I downloaded the zip file again and scanned it (just in case, idk). The new file had the virus too.

I tried to check if anyone knows about it but saw no threads about it, so I just wanted to let everyone know.

p.s
I checked the 64 bit version just now: no virus detected.

**Comment by gohai** [comment]
Two possibilities:

Either Microsoft had an intermittent false-positive detection - but this seems to have been cleared with the latest definitions. (VirusTotal has [no detection](https://www.virustotal.com/en/file/5c1c9839cec9eba875c461fe54bc8c50af70d6c73da5928581a0ffa7c154196a/analysis/1486425416/) on the 32-bit Processing 3.2.4 ZIP file for Windows).

Or, something indeed infected your file, before you tried executing it. (The SHA1 has of the ZIP file I got is `cce076e404d045fca923374b2a8fba6cd4fb4922`.)

**Comment by NickNVM** [comment]
Got the same problem with Windows Defender marking it as Trojan:Win32/Mefurac.E!cl. Anyway it only appears to be in the 32-bit version. I had no problems with 64-bit(except that half of the GUI were cyrillic letters which i couldnt read).

**Comment by benfry** [comment]
I've filed a report with Microsoft; hopefully they can fix the definitions. 

I guess there's a really tiny outside chance that somehow the VM that I use for development was infected, but it's also running Defender and hasn't reported anything like this.

**Comment by jarcane** [comment]
Hello. I'm having this same issue with the current release. Windows Defender quarantinese the executables after extracting the zip, telling me it's found Trojan:Win32/Critet.BS.

**Comment by benfry** [comment]
3.3.7 reports as Trojan:Win32/Critet.BS?
