### ISSUE TITLE
PDE flickers/flashes/random glitchiness when just showing code

### ISSUE THREAD

**Issue by aburstein** [processing/processing#4885]
A few moments after opening any code sketch, the text editor of the PDE starts acting bizarrely. [This screencast](http://screencast-o-matic.com/watch/cbn1YV6nYm) will show you exactly what I mean. This is happening in 3.2.4, but was happening in the previous version too. It's occurring on more than one of the computers in my workplace. The OS is Windows 7 Pro.

**Comment by Lordgoderic** [comment]
Already an issue #4700
