### ISSUE TITLE
Maven message

### ISSUE THREAD

**Issue by libasoles** [processing/processing#4886]
I'm pulling processing using Maven. Like this:
```
<dependency>
      <groupId>org.processing</groupId>
      <artifactId>core</artifactId>
      <version>3.2.3</version>
</dependency>
```
And I get this message:

> 
[WARNING] The POM for org.processing:core:jar:3.2.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

Repo link: https://repo.maven.apache.org/maven2/org/processing/core/
pom link: https://repo.maven.apache.org/maven2/org/processing/core/3.2.3/core-3.2.3.pom

By the way, would it be good to add jna as a dependency? I now it's not always required, but it is for the openkinect library. So, if you are ok to include it, it's found here: 
http://search.maven.org/#artifactdetails|net.java.dev.jna|jna|4.2.0|jar

**Comment by benfry** [comment]
You'll have to contact whoever is providing that; there's no official Maven repository.
