### ISSUE TITLE
Colored window instead of skeleton with Thomas Sanchez skeleton3D sketch

### ISSUE THREAD

**Issue by Nolazz** [processing/processing#4888]
Hello !
I am encountering some difficulties with Thomas Sanchez Lengeling's processing sketch "skeleton3D" in the "OpenCV-Processing" library.
I've a kinect V2 that seems to be well installed since it works like a charm with others sketches. But when i run this sketch i've a whole colored window instead of seeing the skeleton when detected.
I've no error messages in the console window in Processing when running the sketch.
I work on W10 and Processing 3.2.4
Any idea ?

**Comment by benfry** [comment]
Please use forum.processing.org for questions.

**Comment by Nolazz** [comment]
Ok sorry !
