### ISSUE TITLE
Prcessing wont start the "Run" window

### ISSUE THREAD

**Issue by Starbuck7410** [processing/processing#4889]
Whenever i run ANYTHING in processing the main window will show that the program is running, but no window with the actual program shows up. help?
my code:

void setup(){fullScreen(P3D); frameRate(60);}

void draw(){
  background(200);
  translate(50,50,0);
  fill(255,0,0);
  box(100,50,0);
}

**Comment by gohai** [comment]
@Starbuck7410 Same with the default renderer? (i.e. just a blank sketch)

**Comment by Starbuck7410** [comment]
yes

**Comment by benfry** [comment]
Are you using Processing 3.3? 

The [troubleshooting](https://github.com/processing/processing/wiki/Troubleshooting) page provides some steps to try. And in general, [the forum](http://forum.processing.org) is a better place to get help with troubleshooting. Of course if you find that there's a bug that's preventing the software from working, please report it here.
