### ISSUE TITLE
Version 3 hangs on every exception

### ISSUE THREAD

**Issue by WimWWimW** [processing/processing#4890]
Both Versions 3.2.4 and 3.2.3 (Windows 64-bit) hang on program exceptions:
- (3.2.4) at program startup entering "d:" as project directory (expecting to arrive stepwise at the desired directory): Processing frozen only to be closed by the task manager;
- (3.2.4) when detecting variables in the size-statement: run window and IDE frozen and code lost; only to be closed by the task manager;
- (3.2.3) when executing example sketch: run window and IDE frozen, presumably when Test.png not found; only to be closed by the task manager;

I have returned now to version 2.2.1 which works fine sofar.

**Comment by gohai** [comment]
@WimWWimW What does this do w/ latest Processing on your machine?

    void setup() {
      throw new RuntimeException();
    }

**Comment by WimWWimW** [comment]
It opens a runtime-window that remains transparent; the IDE-window remains responsive, i.e., the menus still react to the mouse and keyboard, and it reports "RuntimeException". So exactly the expected behaviour, I presume.

What made me think of the most consize piece of code to show the issue:
`int x=100;
size(x,x);`
Today, I get a neat warning "Pleae fixe the size() line to continue". Also the example sketch handles the nullPointerException well. This doesn't help much, I am afraid...

I tried to remove the processing-folder from AppData to most closely restore yesterday's environment, but apparently there's another place where settings are stored. If you could tell me where to look for that, I can try it again.

**Comment by gohai** [comment]
I wouldn't know any way to restore your environment from a day ago, I am afraid. Could you perhaps just reopen this bug when this happens again and you can narrow it down to some reproducible steps? Thank you!
