### ISSUE TITLE
Conflict:  createWriter & renameTo 

### ISSUE THREAD

**Issue by ld26464** [processing/processing#4891]
I seem to be having an issue when using createWriter targeting one directory and then using origFile.renameTo(newFile) where the new file is targeting a different directory. If they both target the same directory I have no problem with the file writes.  
See attached code: swapping lines 36 & 37 do what I have described. line 36 renames files to the same directory that createWriter is working in, line 37 has createWriter use a different directory. 
In the case where the operations are targeting different directories the file.renameTo() fails to move or rename the files. This is the failure. 

`
// ******** IMPORTANT *************
// files will be RENAMED AND MOVED, NOT COPIED, so make a copy before running script

//int fileStartNum = 1; 
String[] fileNames;
String[] dataFile;
String line;

File newFile, origFile, imgFolder, infoFolder, exportFolder, exportInfoFolder;
String newFileName;
PrintWriter output;  // for info if I want it
BufferedReader reader;

String infoFile = "latSort_picInfoTable_";
// fileStartNum here are for 100 test files in 'images'
//String tripID = "NW.txt";  int fileStartNum = 1;
//String tripID = "SW.txt";  int fileStartNum = 101; 
//String tripID = "NE.txt";  int fileStartNum = 201;
String tripID = "SE.txt";  int fileStartNum = 301;

String infoDir = "info";
String sourceDir = "images";
String exportImgDir = "export images";
String infoExportDir = "export info";
String imgSuffix = ".jpg";

void setup() {  
  infoFolder = new File(sketchPath(""), infoDir);
  imgFolder = new File(sketchPath(""), sourceDir);
  exportFolder = new File(sketchPath(""), exportImgDir);
  exportInfoFolder = new File(sketchPath(""), infoExportDir);
  
  output = createWriter(exportFolder + "/info" + tripID);
  //output = createWriter(exportInfoFolder + "/info" + tripID);
  reader = createReader(infoFolder + "/" + infoFile + tripID);
  String[] dataFile = loadStrings(reader);
  //printArray(dataFile);

  output.println(dataFile.length + " files in this batch");
  output.println("  batch started at " + fileStartNum);
  output.println((fileStartNum + dataFile.length) + " would be the name/id of the next image file");
  output.println("- - - - - - - - - - - - - - - - -");

  fileNames = imgFolder.list();
  //printArray(fileNames);
 
  // ?? how do we know there are the same files (# and name) in both the info file and the images file
  // no error checking at this point 
  for (int i = 0; i < dataFile.length; i++) {
    String[] dataLine = split(dataFile[i], TAB);
    println(dataLine[1]);
    //println("latitude data: " + dataLine[4] + " ----- image \'" + dataLine[1] + "\' to name as " + (i+1) + imgSuffix);
    newFileName = (i + fileStartNum) + imgSuffix; // NB this numbers the files starting at 'fileStartNum = XXX'
    println(newFileName);
      newFile = new File(exportFolder, newFileName); // this is getting redefined again and again 
      println("newFile:  " + newFile);
      origFile = new File(imgFolder, dataLine[1]);
      println("origFile: " + origFile);
      origFile.renameTo(newFile);

      output.println(newFileName + TAB + dataLine[1]);
  }
  output.flush(); // Writes the remaining data to the file
  output.close(); // Finishes the file
  

  exit();
}
    `

This is txt of the .pde file. Same as code inserted above
[Save_Files_NumericallyUsingSortFile__WORKING.txt](https://github.com/processing/processing/files/767193/Save_Files_NumericallyUsingSortFile__WORKING.txt)

**Comment by benfry** [comment]
Please use forum.processing.org for coding questions.
