### ISSUE TITLE
Extremely blurry code editor

### ISSUE THREAD

**Issue by Clayden45** [processing/processing#4892]
[What it look like]
![capture](https://cloud.githubusercontent.com/assets/25691443/22835055/6e25fa5a-ef85-11e6-96e2-5169bdaf6ca8.JPG)

**Comment by benfry** [comment]
That's an amazing image… My best guess is that your graphics card is running out of memory, or has some other conflict. 

Does the issue persist after restarting? 

Also try it with the just-released Processing 3.3, which disables hardware acceleration for the GUI, which might avoid the issue.

**Comment by Clayden45** [comment]
Yes it had something to do with hardware acc and the version 3.3 resolved it!

**Comment by benfry** [comment]
Sad to see it go, but glad it's fixed for you.
