### ISSUE TITLE
Sketches on Windows don't take UI sizing into account

### ISSUE THREAD

**Issue by benfry** [processing/processing#4894]
Starting with 3.3, the editor [scales properly](https://github.com/processing/processing/issues/2411), however the sketch window is another set of issues entirely. 

Another issue covers the cross-platform parts of these problems: https://github.com/processing/processing/issues/4897

This issue is for the Windows integration portion. The most acute issue at the moment is that there doesn't seem to be a way to get the DPI setting without using JNA, so we might have to move JNA into core. But first, it'll be necessary to do more digging through `GraphicsDevice` in Java2D and `Screen` in JavaFX to see if there are methods available for this. 

`Platform.getSystemDPI()` is the method that handles this for the PDE. Only the `WindowsPlatform` has a real implementation, all others return 96.

**Comment by chaotixcalibur** [comment]
Hi,
I don't know if this was solved or not but here is what I did for the wondering.

I am running Processing 3.3.7 on Surface Pro 4. I managed to solve this problem by overriding High DPI scaling behavior and changing scaling to be preformed by System under the Compatibility  tab in the properties for both processing.exe and processing-java.exe.

This solved the issue with both Sketches scaling and Welcome screen size.

However this made the console window too big and it became annoying to write any code.
This issues seemed to be related to the default scaling performed by my surface (which is 200% by default) and luckily processing has an option for changing interface scale which I set to 100% and now everything is working perfectly! (To be honest, everything besides the main window is still big but I think we can live with that, for now.)

**Comment by netham45** [comment]
Can we get a fix? Getting the same scaling BS with my desktop scaling set to 100%, can't run any sketches at the normal size.

**Comment by netham45** [comment]
It looks like it's assuming my scaling is at 300%. If I don't have it at 300% everything is tiny. I run everything at 100%, and it doesn't seem like it cares if I turn off scaling for Java.

**Comment by benfry** [comment]
This is the repository for 3.x. Please use the 4.x releases and that repository for issues as well. 

(Locking this issue because we won't be fixing this particular problem—sketch size and hidpi displays—in the 3.x series.)

**Comment by benfry** [comment]
Should be resolved in 4.0 beta 6 when it's available: https://github.com/processing/processing4/releases

If not, please open an issue in the 4.0 repository: https://github.com/processing/processing4/issues/new
