### ISSUE TITLE
Welcome screen doesn't size properly for HiDPI screens

### ISSUE THREAD

**Issue by benfry** [processing/processing#4896]
Even with fixes to the editor in Processing 3.3 (https://github.com/processing/processing/issues/2411, https://github.com/processing/processing/issues/4183), attempts to fix the Welcome screen didn't work out. So… that still needs to be fixed.

**Comment by cammorales** [comment]
Hi all,
I recently downloaded processing to my surface book 2 and the sketch window is very small. Any suggestions on how to fix this? I looked through the threads but i'm not finding a solution. Any help would be greatly appreciated.

**Comment by benfry** [comment]
Fixed for 4.0 alpha 5, hopefully available soon: https://github.com/processing/processing4/releases
