### ISSUE TITLE
Implement sketch scaling in PApplet/PGraphics

### ISSUE THREAD

**Issue by benfry** [processing/processing#4897]
Need to implement the ability to (semi-)arbitrarily size sketches (both displayed output and re-scaling mouse coordinates) on HiDPI screens. 

There is another issue opened for the Linux-specific parts of the problem: https://github.com/processing/processing/issues/4895
As well as the Windows-specific parts of the issue: https://github.com/processing/processing/issues/4894

This issue is about how it should be handled by the renderers within `processing.core`.

In particular:
* it needs to be handled across the JavaFX, OpenGL, and default (Java2D) renderers
* we should figure out how `pixelDensity()` works in these situations
* this is an arbitrary scaling thing, which could also be a useful feature, but that can be considered separately

**Comment by chrisbeamond** [comment]
https://stackoverflow.com/questions/6544510/how-to-get-the-screen-dpi-in-java

 Trejkaz's comment points to GraphicsConfiguration.getNormalizingTransform() as a possible solution. I'd test it myself, but don't have time right now to setup a java coding environment.

https://docs.oracle.com/javase/8/docs/api/java/awt/GraphicsConfiguration.html#getNormalizingTransform--

It looks at least a little promising.

**Comment by benfry** [comment]
Should be resolved in 4.0 beta 6 when it's available: https://github.com/processing/processing4/releases

If not, please open an issue in the 4.0 repository: https://github.com/processing/processing4/issues/new

(Locking so that follow-up happens in the correct repository.)
