### ISSUE TITLE
Contribution Manager text is garbled

### ISSUE THREAD

**Issue by MichaelHemingway** [processing/processing#4898]
![help](https://cloud.githubusercontent.com/assets/13852458/22867021/6b3ddb68-f14d-11e6-90c5-ca70fe4cdf49.jpg)

First time seeing this on any processing version. The most recent thing I've done is connect an Android phone via ADB, but I doubt that's got anything to do with it. I'd previously installed libraries (in Processing 3.2.4) without issue, both by moving folders and through the manager.

**Comment by benfry** [comment]
This is with Processing 3.3? It should be fixed: https://github.com/processing/processing/issues/4747
