### ISSUE TITLE
Download problems

### ISSUE THREAD

**Issue by skcareer** [processing/processing#4900]
Hi Guys,

I have been finding it difficult to download processing IDE on its website.
The download process always fail along the way,

I use Window 7 64-bit PC.

Could anyone please assist me with neccessary information to resolve this issue?
Thanks in anticipation.

Regards.

**Comment by alignedleft** [comment]
What happens when it fails? Do you get an error message? What browser are you using? Have you tried a different browser? Do you have enough free disk space? 

Here's the link, for reference.

http://download.processing.org/processing-3.3-windows64.zip

**Comment by skcareer** [comment]
Thanks, i have rectified the problem. My browser was the problem.
I was using moxilla firefox when it failed. It downloaded once when i used
chrome.
