### ISSUE TITLE
Ugly button images at 125% and 150% scaling on Windows

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#4901]
Toolbar buttons and status bar icons seem to use low res version.

![scaling](https://cloud.githubusercontent.com/assets/3177098/22934014/b316252c-f2cd-11e6-90f4-237727089a28.png)

**Comment by benfry** [comment]
Hm, it should be pulling the 2x version if zoom is anything above 1x, but it may be doing an ugly job of scaling it down. Quick fix would be more rendering hints set in `Toolkit.prepareGraphics()` to do nicer image scaling.

**Comment by JakubValtar** [comment]
Adding `g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);` to `Toolkit.prepareGraphics()` fixed Console and Error icons, but not toolbar buttons (because `prepareGraphics()` is not called there). After casting the graphics manually in `EditorButton.paintComponent()` and setting the hint there, buttons are nice too.

Not sending pull request, because I'm not sure if there should also be `prepareGraphics` call and where to put it.

**Comment by benfry** [comment]
Oh, right—`EditorButton` is just an image button, it's more Swing-style than the other custom image stuff that makes heavier use of `prepareGraphics()`. But those sound like the right fixes to me, so please go ahead and check them in or submit a PR if you'd like me to review first.
