### ISSUE TITLE
Gap between tab headers and text area at 125% and 150% scaling on Windows

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#4902]
![scaling](https://cloud.githubusercontent.com/assets/3177098/22934213/75a0ed34-f2ce-11e6-8340-076bbe30357d.png)

**Comment by benfry** [comment]
But doesn't everything look like s*t on your machine at 125%? :)

As a quick fix, try using `Math.ceil()` inside `Toolkit.zoom()`.

**Comment by benfry** [comment]
If that looks funky, we could disable UI scaling for the 125% case, since it's unlikely to bother folks much at that scale, and the cure might be worse than the sickness.

**Comment by JakubValtar** [comment]
> But doesn't everything look like s*t on your machine at 125%? :)

Not really, only 3.3 :)

> If that looks funky, we could disable UI scaling for the 125% case, since it's unlikely to bother folks much at that scale, and the cure might be worse than the sickness.

I set scaling to 100% in preferences and it looks good (i.e. same as 3.2.4).

I'd even argue that the auto size of the UI is too big compared to system windows and other apps:

### 100%
![scaling100](https://cloud.githubusercontent.com/assets/3177098/22938550/604a6f74-f2dc-11e6-90f4-bab883edc5b8.png)

### 125%
![scaling125](https://cloud.githubusercontent.com/assets/3177098/22938557/647e93a4-f2dc-11e6-935e-e535eefe2f59.png)

### 150%
![scaling150](https://cloud.githubusercontent.com/assets/3177098/22938564/691db160-f2dc-11e6-8659-31bf1d3640c8.png)

**Comment by JakubValtar** [comment]
`Math.ceil()` helped

**Comment by benfry** [comment]
Yeah, in general the UI is a little larger than the standard Windows components, in line with the trend towards UIs being larger in general (i.e. the Windows settings pages in 8+ vs. NT-era windows like System Properties), so that part is normal/intentional.
