### ISSUE TITLE
Editor incorrectly says that there are too many '}' characters

### ISSUE THREAD

**Issue by dzaima** [processing/processing#4903]
The Processing editor by some reason gives an error of `Found one too many '}' characters without '{' to match it.`
The sketch still runs and functions correctly (I'm surprised that processing ignores errors). It wouldn't be much of a problem without the fact that it doesn't display other errors.
The file: https://github.com/dzaima/SOGL/blob/master/P5ParserV0_8_2/execute.pde
It's possible that this is my overuse of unicode characters.

**Comment by JakubValtar** [comment]
@dzaima Ah, thanks. There was a bug in the preprocessor, double backslash was not parsed correctly.
