### ISSUE TITLE
Transparent blue color 0x000000ff renders as solid white

### ISSUE THREAD

**Issue by mcslee** [processing/processing#4904]
The color 0x00000000 composites incorrectly, showing as solid black instead of full transparency. Similarly, the color 0x000000ff composites as solid white instead of full transparency.

This simple sketch illustrates the issue. Its output its attached below. Over a red background, we draw 256 squares with each different alpha values, for black, white, green, and blue. The positions in which errors occur are clear, instead of the red background showing through, we see a solid black 
square and a solid white square.
```processing
void setup() {
  size(800, 800);
  int chunk = 25;
  background(#ff0000);
  stroke(#000000);
  for (int i = 0; i < 256; ++i) {
    int blackAlpha = (i << 24);
    int whiteAlpha = (i << 24) | 0xffffff;
    int greenAlpha = (i << 24) | 0x00ff00;
    int blueAlpha = (i << 24) | 0x0000ff;
    int redAlpha = (i << 24) | 0xff0000;
    int x = 25 * (i % 16);
    int y = 25 * (i / 16);
    fill(blackAlpha);
    rect(x, y, 25, 25);
    fill(whiteAlpha);
    rect(400+x, y, 25, 25);
    fill(greenAlpha);
    rect(x, 400+y, 25, 25);
    fill(blueAlpha);
    rect(400+x, 400+y, 25, 25);
  }
}
```
![screen shot 2017-02-14 at 5 21 57 pm](https://cloud.githubusercontent.com/assets/597850/22956961/1f42f7aa-f2da-11e6-96c7-ab8ea2d0560a.png)

**Comment by mcslee** [comment]
I see that the black case is intentional, as covered by:
https://github.com/processing/processing/wiki/Troubleshooting#color.280.2C_0.2C_0.2C_0.29_is_black

The issue with the transparent blue still stands, don't think that should be turning to solid white.

**Comment by JakubValtar** [comment]
`fill(0x000000FF)` is the same as `fill(255)`, which is white. If the value is between 0 and 255, we can't tell if it's ARGB color or gray value.

To work around it, use either color with a tiny bit of alpha (`0x010000FF`) or a two component `fill(blueAlpha, alpha(blueAlpha))` which takes color and alpha separately. It will also interpret the color as white, but make it transparent.

@benfry @REAS Maybe we should add a "Transparent blue is black/gray/white!" to the [Troubleshooting page](https://github.com/processing/processing/wiki/Troubleshooting#color0-0-0-0-is-black).

**Comment by mcslee** [comment]
Gotcha - makes sense, and I figured this might be related when I found that note about black on the Troubleshooting page. Thank you for the prompt explanation!

**Comment by benfry** [comment]
You could also probably avoid the issue (and make the code clearer?) by using
```
fill(i, 0, 0, 255);
```
instead of all the bit shifting and then `fill(blueAlpha)`.

**Comment by mcslee** [comment]
Yes - the code example was a contrived illustration, definitely not an idiomatic way of writing Processing code. The case in which I actually discovered this issue was while working with another library, which was manipulating color values in the standard integer ARGB format. Then I was rendering those values.

This is probably not a totally uncommon scenario, as many libraries work in 32-bit ARGB format. But I totally get that Processing is biased towards the simple case, which makes sense.

I suppose the answer here is just that when using outside libraries involving alpha compositing, one should take care to sanitize color values before using Processing's rendering methods.

**Comment by benfry** [comment]
Closing; known issue as covered in the FAQ.
