### ISSUE TITLE
processing.exe seems to be missing from version 3.3 win-64

### ISSUE THREAD

**Issue by pr-jluc** [processing/processing#4905]
Processing gets upset when I try to using processing.exe from version 2.2 3

**Comment by benfry** [comment]
It's in the archive… You might need to try extracting the .zip file again.

<img width="808" alt="screen shot 2017-02-15 at 12 02 10 pm" src="https://cloud.githubusercontent.com/assets/1623101/22985489/97df4a1e-f376-11e6-814d-619a8fc9e88f.png">
