### ISSUE TITLE
Bug with mouseY

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#4908]
(I think I reported something like this a year ago but I'm not sure, and I can't find it either)

let's say: size(500, 500);

mouseX goes from 0 to 499 inclusive
mouseY goes from 1 to 499 inclusive

This makes the cursor(CROSS) to be 1 pixel off.
Also the height is now 499 instead of the 500.

This is super annoying.

It happens on OSX.

**Comment by benfry** [comment]
It's here: https://github.com/processing/processing/issues/4057
