### ISSUE TITLE
arc() function - angle direction

### ISSUE THREAD

**Issue by cdaein** [processing/processing#4909]
When an arc is drawn clockwise, it works. Drawn counter-clockwise, it doesn't.

```java
arc(width/2, height/2, 50, 50, PI+HALF_PI, HALF_PI); // this doesn't display
arc(width/2, height/2, 50, 50, HALF_PI, PI+HALF_PI); // this works
```

Is it intentional?

**Comment by patakk** [comment]
https://github.com/processing/processing/blob/master/core/src/processing/core/PGraphics.java#L2871

It looks just like a matter of choice, and the easy fix would be just to swap the values in _start_ and _stop_, but that's also what you can do in your own code while calling the _arc_ function.

**Comment by benfry** [comment]
Hm, I guess I've never seen a graphics API do opposite directions. I figure it's something of a sanity thing… We'd have to guess whether you mean to go clockwise or not, which gets close to questions like, if you draw an arc from 45° to 225°, which way do you intend the arc to go? 

I've just added a note to the docs for us to mention that it's clockwise, so thanks for pointing out the omission: https://github.com/processing/processing-docs/issues/533
