### ISSUE TITLE
GUI issues, unreadable texts

### ISSUE THREAD

**Issue by guillaumeguerin** [processing/processing#4916]
Hello everyone,

I'm using Processing 3.2.4 on windows 7 - 64bits

And whenever I prompt a processing window, the text is unreadable
here is an example : 
![image](https://cloud.githubusercontent.com/assets/677290/23084012/c1fe95ac-f560-11e6-8e87-b216b9de71ee.png)

other example :
![image](https://cloud.githubusercontent.com/assets/677290/23084044/e6908826-f560-11e6-96bb-13c0a47642f3.png)

**Comment by benfry** [comment]
Use the latest version, 3.3 or later.
