### ISSUE TITLE
Possible issue with Processing-Java command line tools installation?

### ISSUE THREAD

**Issue by brennan-pilcher** [processing/processing#4917]
I came across this issue when preparing Processing command line tools for deployment in an academic enterprise environment. I believe that it's an actual bug, not just a mistake on my part.

There appears to be a syntax error in the 'processing-java' bash script that Processing generates when you download it from the Tools menu with certain versions of Processing on macOS (possibly Unix too?). When I installed processing-java via Processing 3, it does not appear to install correctly. Essentially, it looks like someone may have decided not to wrap the second parameter in quotes inside the bash script downloaded to '/usr/local/bin', so when it tries to find the JDK within "/Applications/Processing 3.app" it fails. Here is the offending line:

`cd "/Applications/Processing 3.app/Contents/Java" && /Applications/Processing 3.app/Contents/PlugIns/jdk1.8.0_102.jdk/Contents/Home/jre/bin/java -Djna.nosys=true $OPTION_FOR_HEADLESS_RUN -cp "ant-launcher.jar:ant.jar:core.jar:jna-platform.jar:jna.jar:pde.jar:core/library/core.jar:core/library/gluegen-rt-natives-linux-amd64.jar:core/library/gluegen-rt-natives-linux-armv6hf.jar:core/library/gluegen-rt-natives-linux-i586.jar:core/library/gluegen-rt-natives-macosx-universal.jar:core/library/gluegen-rt-natives-windows-amd64.jar:core/library/gluegen-rt-natives-windows-i586.jar:core/library/gluegen-rt.jar:core/library/jogl-all-natives-linux-amd64.jar:core/library/jogl-all-natives-linux-armv6hf.jar:core/library/jogl-all-natives-linux-i586.jar:core/library/jogl-all-natives-macosx-universal.jar:core/library/jogl-all-natives-windows-amd64.jar:core/library/jogl-all-natives-windows-i586.jar:core/library/jogl-all.jar:modes/java/mode/antlr.jar:modes/java/mode/classpath-explorer-1.0.jar:modes/java/mode/com.ibm.icu.jar:modes/java/mode/JavaMode.jar:modes/java/mode/jdi.jar:modes/java/mode/jdimodel.jar:modes/java/mode/jdtCompilerAdapter.jar:modes/java/mode/jsoup-1.7.1.jar:modes/java/mode/org.eclipse.core.contenttype.jar:modes/java/mode/org.eclipse.core.jobs.jar:modes/java/mode/org.eclipse.core.resources.jar:modes/java/mode/org.eclipse.core.runtime.jar:modes/java/mode/org.eclipse.equinox.common.jar:modes/java/mode/org.eclipse.equinox.preferences.jar:modes/java/mode/org.eclipse.jdt.core.jar:modes/java/mode/org.eclipse.osgi.jar:modes/java/mode/org.eclipse.text.jar:modes/java/mode/org.netbeans.swing.outline.jar" processing.mode.java.Commander "$@"`

When I run 'processing-java' from Terminal after this file is generated, I get an error. Terminal is trying to evaluate "Applications/Processing" as a directory because it is followed by a space. When I inserted a backslash to escape the space, I am then able to run 'processing-java' from Terminal without any errors because it can evaluate the full filepath.

`cd "/Applications/Processing 3.app/Contents/Java" && /Applications/Processing\ 3.app/Contents/PlugIns/jdk1.8.0_102.jdk/ ... etc etc etc`

**Comment by benfry** [comment]
Are you using 3.3? There was a problem with this in past versions.

**Comment by brennan-pilcher** [comment]
I was using 3.2.1, so I downloaded 3.3 and noticed that the app name had been changed to Processing as well as the line in 'processing-java' to reflect that so the error no longer occurs. Whoops!

Since this was already fixed in a previous release, I will close the issue. Thanks for your input.

**Comment by benfry** [comment]
Yeah, it's been fixed since 3.2.4. https://github.com/processing/processing/issues/4779
