### ISSUE TITLE
Processing doesn't detect when "variable might not have been initialized"

### ISSUE THREAD

**Issue by HenriAugusto** [processing/processing#4918]
The error goes undetected when you declare an object and don't instantiate in the "global" scope.

    A a; //declare a here and the code runs, but executes unexpectedly and print result is "a is null"
    
    void setup(){}
    
    void draw(){
      
        Test test = new Test();
        //A a; //but if you declare it here, then the error is detected! It won't run!
        test.setA( a );
        
        if( a==null){
          System.out.println("a is null ");
        } else {
          System.out.println("a is not null ");
        }
       noLoop();
       
    }
        
    public class A{
      
    }
    
    public class Test{
      
      A getA(){
        return new A();
      }
      
      void setA(A a){
        a = getA();
      }
      
    }

This was driving me crazy as i was getting a null pointer "out of nowhere". Took me some hours to figure it out :p

**Comment by HenriAugusto** [comment]
Probably because the preprocessor actually put those variables inside the sketch class. This indeed can happen in Java, but i don't know why!

    public class HelloWorld
    {
      public static void main(String[] args)
      {
        Test test = new Test();
        test.setA( test.a );
        
        if( test.a==null){
          System.out.println("a is null ");
        } else {
          System.out.println("a is not null ");
        }
        
      }
    }
    
    public class A{
    }
    
    public class Test{
      A a; //use this and a is null
      //A a = new A(); //use this and a is not null
      
      
      A getA(){
        return new A();
      }
      
      void setA(A a){
        a = getA();
      }
      
    }

**Comment by Lord-of-the-Galaxy** [comment]
@HenriAugusto Close enough. But you can't have two top-level Java classes in a single .java file. What Processing (preprocesser) does is put the _classes also_ into sketchName class.

**Comment by benfry** [comment]
That's not a solvable problem. The scoping can only really be detected when it's within a function. If it's global and accessible to other classes, there's no way for the compiler to know (until runtime) whether it's been initialized. But even then it doesn't matter, because initialization in Java also has specific traits (Objects are null, numbers 0, booleans false), and those values may be legitimate.

**Comment by HenriAugusto** [comment]
@Lord-of-the-Galaxy i was testing it in https://www.compilejava.net/ that automatically spread the classes in multiple files. Sorry, forgot to add that.

@benfry thanks. Should we add some kind of warning in some tutorial about this?

**Comment by Lord-of-the-Galaxy** [comment]
@HenriAugusto Most newbies will understand so much by reading the tutorials and testing their code, we wouldn't need to add any such warning in the tutorials.
