### ISSUE TITLE
Feature request: suppress Update dialog at startup from CLI

### ISSUE THREAD

**Issue by richelbilderbeek** [processing/processing#4923]
I love Processing and even teach 7-17 year old kids in it. Those kids are Dutch and the youngest do not know English well. For them, the `Update` dialog is confusing:

![2017-02-19-115017_431x145_scrot](https://cloud.githubusercontent.com/assets/2098230/23101680/9947f29a-f699-11e6-80e5-13c0eba22232.png)

Sure, I do teach them how to respond to this dialog, but there could have been no need to.

For those kids, I'd suggest to either:

 * let the dialog only be a notification and just close after a second or so. Updates can then be done from the menu
 * let the dialog be suppressable from the CLI, e.g. `./processing --no-update-dialog`, so I can make a menu item that calls Processing as such

I am willing to test and/or help implementing it, but it may be a too controversial feature request.

**Comment by gohai** [comment]
You could set `update.check=false` in the `preferences.txt`, which is e.g. found in `~/Library/Processing` on macOS.

**Comment by richelbilderbeek** [comment]
Thanks! I've found it in `lib/defaults.txt`. I am happy to have found a solution that now others can also find.

Keep up the good work!
