### ISSUE TITLE
mouseMoved() call on fullScreen() sketch on Windows

### ISSUE THREAD

**Issue by garciadelcastillo** [processing/processing#4924]
When running a sketch on fullScreen() mode, it seems that an initial call to mouseMoved() is performed without the user moving the mouse. For instance, running the following sketch:

```
void setup() {
  fullScreen();
}

void draw() {
  println(frameCount);
}

void mouseMoved() {
  exit();
}
```

causes Processing to run one frame and exit. 

This behavior has been noticed on Processing versions 3.2.4 and 3.3 on Windows 8.1 machines. This issue reportedly does not arise on Mac OS X.

**Comment by benfry** [comment]
Not much we can do; the problem is in Java or Windows, which is giving us the event and we're just passing it through to the sketch.
