### ISSUE TITLE
Contributed library never appears installed 

### ISSUE THREAD

**Issue by gratefulfrog** [processing/processing#4926]
Since version 3.3, I see that contributed libraries don't appear as installed, even though they are physically present...

Please see the same report made on android mode: https://github.com/processing/processing-android/issues/300

**Comment by drwoohoo** [comment]
Inside of your Processing/libraries/HYPE folder, is their a "distribution" folder that contains the HYPE.jar? If so, rename it to "library" and restart Processing.

**Comment by gratefulfrog** [comment]
@drwoohoo:
Thanks for the tip, but there is no "distribution" folder. My sketchbook folder structure is below. the olny solution I found was to put the ketai.jar file in each sketch!
* examples
* templates
* tools
* modes
** AndroidMoid
** PythonMode
...
* libraries
** Ketai
*** reference
*** examples
*** library
**** ketai.jar

**Comment by benfry** [comment]
Try renaming the `Ketai` folder to `ketai` (or `ketai.jar` to `Ketai.jar`).

**Comment by gratefulfrog** [comment]
changing the names to that same case worked!

Even though I had already tried that yesterday... maybe I failed to completely close processing..

Anyway, it works now. 

How can we inform the ketai library maintainers that their install script is broken?

Thanks for your help!
Ciao,
Bob

**Comment by benfry** [comment]
I don't have contact info for them, but it looks like the site may? http://ketai.org/

We also have an open issue to detect this: https://github.com/processing/processing/issues/4507
