### ISSUE TITLE
Processing does not complain if java is not installed

### ISSUE THREAD

**Issue by tam4s** [processing/processing#4927]
Processing requires to have a java installed to fully function, still, it does not check whether it is available, but it is buggy instead: I got an empty white window as the welcome screen. Package Manager worked fine, though. I only guessed that something is wrong, when a sketch resulted in a similar empty white window. After installing java, the problem went away.

MacOS Sierra 10.12.3
Processing 3.3

I installed processing like this:
```brew install Caskroom/cask/processing```

I installed java like this, which fixed the empty white windows problem:
```brew cask install java```

**Comment by gohai** [comment]
@tam4s That looks more like a Homebrew packaging problem than a problem with Processing proper. The version of Processing distributed via processing.org and this GitHub project comes with a version of the JVM. You might want to take up this issue with the Homebrew maintainers/packagers...

**Comment by benfry** [comment]
Processing *does not* require Java to be installed to function: https://github.com/processing/processing/wiki/Supported-Platforms#java-versions

Everything is embedded inside the software itself. Unfortunately it looks like someone created a Homebrew release that broke it. Can we have that removed?
