### ISSUE TITLE
Why does this program run out of memory on Linux? (Processing 3.2.3)

### ISSUE THREAD

**Issue by patakk** [processing/processing#4932]
I'm working on a large project which generates images in a loop using a few PGraphics objects. Each image is totally independent of the previous ones so I can "forget" everything and use those objects (pointers), which I do, but somehow memory gets full (the heap) and the program crashes after about 300-400 frames. This happens only on Linux (Ubuntu), and NOT on Windows.

Here's a simple demo of what causes the crash, I've also included the memory diagnostics to show what's happening. 

```
PGraphics pg;

void setup(){
	size(600, 600, P2D);
	textSize(24);		
}

void draw(){
	background(29);
	fill(255);

	Runtime runtime = Runtime.getRuntime();
	text("Frame:" + frameCount, width/2, height/2);
	text("Used Memory:" + (runtime.totalMemory() - runtime.freeMemory()) / (1024*1024), width/2-50, height/2+40);
	text("Free Memory:" + runtime.freeMemory() / (1024*1024), width/2-50, height/2+80);
	text("Total Memory:" + runtime.totalMemory() / (1024*1024), width/2-50, height/2+120);
	text("Max Memory:" + runtime.maxMemory() / (1024*1024), width/2-50, height/2+160);
        
        int ww = int(random(300, 500));
        int hh = int(random(300, 500));
	pg = createGraphics(ww, hh, P2D);
	pg.beginDraw();
	pg.background(44);
	pg.fill(222);
	pg.ellipse(pg.width/2, pg.height/2, 30, 30);
	pg.filter(BLUR, 2);
	pg.endDraw();

}
```

The exception I get when the program crashes is "java.lang.OutOfMemoryError: Java heap space" and it's obvious that the heap gets full, but I don't know why... Why is it getting full on Linux and not on Windows?? On Windows I can see the "usedMemory" keep getting reseted, but not on Linux.. whaiii?

I've tried something like using System.gc(); to suggest the VM to collect the garbage, but to no avail.

Thanks in advance!

**Comment by gohai** [comment]
This might be a legitimate bug concerning P2D. But have you tried moving the `createGraphics` call into `setup`?

**Comment by PaoloCeric** [comment]
Of course, and that helps, BUT the images I generate have to be of variable size (I'll edit my example code to show that) and since PGraphics doesn't support resizing, '''createGraphics''' must be called on each new image, and thus can't be put in '''setup'''.

**Comment by patakk** [comment]
Good question, and of course that helps, BUT the images I generate have to be of variable size (I'll edit my example code to show that) and since PGraphics doesn't support resizing, `createGraphics` must be called on each new image, and thus can't be put in `setup`.

**Comment by gohai** [comment]
Does it make a difference when you assign `pg` to `null` after you're done using it inside `draw` _and_ trigger `System.gc()` afterwards?

**Comment by patakk** [comment]
Just tried that on the demo example, but it doesn't help unfortunately, the `usedMemory` keeps going up...

**Comment by patakk** [comment]
I also tested your suggestion on my project on Windows and I can see that memory usage never exceeds some constant value, and that's awesome, but for some reason it doesn't work on Linux and I really need it to be runable on Linux because I'd like to run my sketch on a Linux server to get performance.

**Comment by benfry** [comment]
You should never use `createGraphics()` inside draw. You're setting up an entire OpenGL graphics context 60 times a second, there's no way for your computer to keep up with that. 

Unfortunately we can't simply prevent all situations like this because there isn't a consistent way to detect that the wrong thing is being done. I've made a note in the `createGraphics()` documentation for the next release.

**Comment by patakk** [comment]
Yeah, I understand, but there's simply no elegant way of generating many
images of different size in one sketch without doing so.
Fortunately I managed to make a dirty workaround (by making a bug initial
PGraphics) and drawing only to restricted parts defined by the wanted
dimensions. It required a lot of code changing but it got the work done,
and I really think there should be another, better way of doing something
like that, by making PGraphics resizeable when in P2D mode or something.

**Comment by patakk** [comment]
edit: "making one BIG PGraphics object"

**Comment by benfry** [comment]
Just create the buffers in `setup()` and reuse them throughout `draw()`. There's just no reason to be creating 60 new graphics contexts every *second*. Your eye can't even see that many new images.

**Comment by patakk** [comment]
Of course, but the intention is not to display them at all, the purpose of
my sketch is to generate "layers", combine them and save them, repeatedly,
because I want to generate about 50000 randomly parametrized images which I
later use as a dataset for a neural net. In draw() I'm just displaying some
info like percentages and stuff just to see the progress info.
If I create them in setup then I'm not able to control their size which I
really need.

I found a workaround in which I do what you suggested and then I draw only
in the restricted part of the buffer (defined by the wanted dimensions) and
then save only that part by which I get the images of variable size. Then I
just reuse that big buffer repeatedly, but that seems like an ugly solution
and it would be much more convenient to be able to resize the buffer after
its creation.
