### ISSUE TITLE
Small line height in utility windows and error table at 200%

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#4936]
3.3 @ Windows 10

### Utility windows
![utility](https://cloud.githubusercontent.com/assets/3177098/23375680/808d2fae-fd29-11e6-80f5-7f67db706e20.png)

### Error table
![errortable](https://cloud.githubusercontent.com/assets/3177098/23375683/827ed448-fd29-11e6-8ae0-7dfc1fa448f5.png)

**Comment by benfry** [comment]
Should all be fixed in the current source and for 3.3.1.
