### ISSUE TITLE
Debugging: Continue within class steps out

### ISSUE THREAD

**Issue by jas0501** [processing/processing#4938]
This may be related to #2946: debugging within a class. **Step** does work within a class but **Continue** doesn't see the breakpoints and steps all the way out of nested class.

The workaround is the **CTRL-SHIFT-J** continually. Very annoying.

**Comment by benfry** [comment]
This should be fixed in #5008, if not, please give us more explanation of what's going wrong in the latest release (3.3.3 or later).
