### ISSUE TITLE
Extended ASCII characters won't display on Windows (regression)

### ISSUE THREAD

**Issue by DDEFF** [processing/processing#4940]
Hi,
![ascii test](https://cloud.githubusercontent.com/assets/25547803/23544529/aed8ef94-fff7-11e6-8c0e-b389175d39bd.png)
I use Processing 3.3 (but the problem is older) on Windows 10.
I use directly Processing, as shown in the picture, without any extern editor.
Thank's in advance

**Comment by gohai** [comment]
@DDEFF Is the problem that you're trying to type this character in the editor and it doesn't show correctly, or, does it not show when you have your Processing sketch draw the character using the `text()` function, or output it to the console using the `print()` function?

What happens when you copy the character from a website, paste it into Processing, save, and later re-open that sketch? Is it still there and the glyph looking as you expect?

**Comment by DDEFF** [comment]
My problem is that I'm trying to type "ALT"+197 in the editor and it doesn't show correctly.
I dont use it with `text()` or `print()`.

I try to get the character frow Word and the "┼" become an "envelope" :
![ascii test 2](https://cloud.githubusercontent.com/assets/25547803/23577296/cef6e1f4-00bb-11e7-885c-604e5da16cdf.png)

The most surprising is that if I copy the "envelope" from my Processing sketch and that I paste it in my answer Github, I have the good "┼" !!

And it is also the good  "┼" when I print the sketch !!

The problem is only on my screen, from Processing (I have the good "┼" on my screen from Word and on the Github forum)
And that worked on my screen in a previous version of Processing (3.2.0).
Strange ??

**Comment by benfry** [comment]
So this definitely worked in 3.2 and doesn't in 3.3? 

The only change I can think of related to text input was intercepting the step commands for the debugger (ctrl-j was inserting a new line into the editor). But maybe that's consuming more events than it should be.

**Comment by DDEFF** [comment]
I'm sure that it doesn't work since 3.2.3.
I wrote my sketch since 3.2.0, with the good ┼ on my screen, and that began an envelope at some point, without having made anything except updating Processing.

**Comment by benfry** [comment]
Working with 3.3.3 and Windows 10. May have been the same Oracle bug as https://github.com/processing/processing/issues/4992

<img width="363" alt="screen shot 2017-05-03 at 9 05 11 pm" src="https://cloud.githubusercontent.com/assets/1623101/25687566/6fd021f4-3045-11e7-8e93-5a4895eef21f.png">
