### ISSUE TITLE
Wrong libraries folder in error message

### ISSUE THREAD

**Issue by HenriAugusto** [processing/processing#4942]
I was trying to import a library and got

> No library found for oscP5.
> Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder.

Just happens i had it right, in this folder:

> C:\Users\Henri\Desktop\Software\Processing\Sketchbook\libraries

Just to test i installed an library with the built-in tool manager and noticed it was installed instead in:

> C:\Users\Henri\Desktop\Software\Processing\libraries

Moved everything there and it started working. The message should be update to reflect that.
(maybe this is an issue because i've used a custom sketchbook folder)

Love your work.
Best regards,
Henri.

**Comment by benfry** [comment]
Is the suggestion just that the message include the location of your sketchbook folder?

**Comment by HenriAugusto** [comment]
Actually thats what was in the message. It said to put stuff in 

> "Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder."
> or
> `...\Sketchbook\libraries`

but it didn't worked after putting stuff there.

My setup is actually

> Processing executables
> `C:\Users\User\Desktop\Software\Processing\processing-3.3`

> Sketchbook folder
> `C:\Users\User\Desktop\Software\Processing\Sketchbook`

> Libraries folder that did not worked
> `C:\Users\User\Desktop\Software\Processing\Sketchbook\libraries`

> Libraries folder that works
> `C:\Users\User\Desktop\Software\Processing\libraries`

If it changes anything, the processing executables were once located in
> `C:\Users\User\Desktop\Software\Processing`

Does the IDE always search for libraries in the same place? I think it's because i moved the "processing 3.3" directory and set a custom sketchbook path

**Comment by benfry** [comment]
Did you manually edit `preferences.txt` to  use `..\Sketchbook\libraries` as your sketchbook path?

**Comment by HenriAugusto** [comment]
Yes, i've indeed got this line
`sketchbook.path.three=C:\Users\User\Desktop\Software\Processing`

I'm deducing it looks for libs on 

`sketchbook.path.three\libraries`

Which can be deceiving because of the message

`Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder.`

Because sketchbook.path.three is where the ide looks for the "Sketchbook" folder. Not the sketchbook folder itself as the name suggests.

**Comment by benfry** [comment]
So I should take the quotes off of 'sketchbook' in that error message?

**Comment by HenriAugusto** [comment]
No. I think i wasn't able to show you the problem. Let me put it this way

Let's say you're trying to use a library and you get a message

`Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder.`

Then you will think you should put a your libs in 
`whatever/Sketchbook/libraries`

But processing actually looks for the libraries folder in 

`whatever/libraries`

The message says the libraries folder should be **inside** the sketchbook folder. But it actually must be on the **same level** as the Sketchbook folder.

**Comment by benfry** [comment]
But you said:
```
sketchbook.path.three=C:\Users\User\Desktop\Software\Processing
```
and that the libraries folder that worked was:
```
C:\Users\User\Desktop\Software\Processing\libraries
```
Which is correct.

**Comment by HenriAugusto** [comment]
Exactly. As far as i understand english when we say **Sketchbook** folder we mean `a folder called Sketchbook`, which should look something like `whatever/Sketchbook`.
That is, when we say sketchbook folder we are talking about **the folder itself**.

But in the message **Sketchbook** actualy means `the folder where processing will store a folder called Sketchbook`. That's totally counterintuitive and i've took some time to figure this out!
