### ISSUE TITLE
"Field cannot be declared static in a non-static inner type" although the class is not an inner type

### ISSUE THREAD

**Issue by Simonibo** [processing/processing#4946]
In my recent project I noticed that whenever I declared a static member in an other class than the base class, the following error would show up:
"The field <field name> cannot be declared static in a non-static inner type, unless initialized with a constant expression"
This message seems wrong, because the classes in which I observed this bug were no inner classes. 
One simple example for this bug would be:
`class Test {
static boolean testfield;
}`

**Comment by JakubValtar** [comment]
Under the hood, the whole sketch is a class, and all the classes you make yourself are inner classes. It does not matter if you write your class into first tab or second tab, all tabs get joined and inserted into the body of the sketch class. We do this so beginners don't have to wrap their head around Java classes and other funkiness before getting any visual output.

`static class Test { static boolean testfield; }` should work alright.

Or just move the static field outside if you can't make your inner class static:
```processing
static boolean testfield;
class Test {  }
```

**Comment by benfry** [comment]
Alternatively if you're trying to write Java code like this, you can put the class in a new tab with `.java` as its extension, which will result in a class that's not compiled into the sketch. However, you'll need to pass the `PApplet` object into it if you want to use any built-in functions.
