### ISSUE TITLE
`revisions.txt` (linked from website) is missing

### ISSUE THREAD

**Issue by JobLeonard** [processing/processing#4947]
Not sure if this is something that needs fixing on the website or in the repository, but just an FYI.

I'm talking about this link:

https://raw.github.com/processing/processing/master/build/shared/revisions.txt

As linked from:
https://processing.org/download/?processing

**Comment by gohai** [comment]
@JobLeonard That link works for me...

**Comment by JobLeonard** [comment]
Ok, tha's odd. I'm getting DNS errors, even though regular github works fine for me. It works if I navigate the regular repository, and then click on `raw`, but the link is different:

https://raw.githubusercontent.com/processing/processing/master/build/shared/revisions.txt

**Comment by gohai** [comment]
Both work for me. Guessing this might have been an intermittent DNS issue on your side, or perhaps your organization black-listing raw.github.com?

**Comment by JobLeonard** [comment]
Wait, why are you closing this *when the link on the website is still broken for me?*

I did a bit of googling, the real issue is related to this:

> In order to better isolate your content from potentially malicious content uploaded by other users (e.g., content that might contain Cross-Site Scripting or other embedded attacks), we now serve user-generated content from subdomains of githubusercontent.com. This content is no longer served from subdomains of github.com.
> 
> ##What's affected?
>
> This change affects the following subdomains:
> 
> - `raw.github.com` : Serves raw file content from your repository.
> - `embed.github.com` : Allows users to embed rich GitHub content on other sites.
> - `render.github.com` : Displays rich content on GitHub.com.
> - `f.cloud.github.com` : Hosts all those amazing gifs you use in Pull Requests and Issues.
>
> Content formerly served by these subdomains is now served from subdomains of `githubusercontent.com`.

https://developer.github.com/changes/2014-04-25-user-content-security/

For whatever reason, raw.github.com no longer redirects for me. With that I mind, I think the website should switch to https://raw.githubusercontent.com/processing/processing/master/build/shared/revisions.txt

I'll open an issue on the website repository.

**Comment by gohai** [comment]
Yes, please open an issue in processing-docs, or send a PR that does the change.
