### ISSUE TITLE
Processing .exe does not work with Kinect

### ISSUE THREAD

**Issue by ClaraBellinMMI** [processing/processing#4948]
I have a program that works with a Kinect (v1 model 1414), I did a tracking point. When I export the program, and then launch it as an .exe it does not work. A window comes but it's only grey and then my pc freeze. 

I've seen that it's possible to change things in some .jar files, but I don't know which one

**Comment by gohai** [comment]
@ClaraBellinMMI This might be something that the author of the library of the Processing Forum can help you with, but this isn't the right place to this out.
