### ISSUE TITLE
adding JOCL (OpenCL binding to processing), to processing libraries

### ISSUE THREAD

**Issue by tiagmoraismorgado** [processing/processing#4950]
**Greetings**

I came across with something really cool, which is this processing binding of **OpenCL** by **Khronos Group**, which, on my standing point, **should be included in processing libraries**, both ind the site, and in the menu in processing, which allows installing further libraries (if it's still up and running). you can find the link to a demo of the library here:

- https://www.youtube.com/watch?v=4NU37rPOAsk
- https://www.youtube.com/watch?v=mNjbOqFsEvQ

Looking forward
cheers

**Comment by gohai** [comment]
Sounds like an interesting idea for a library, which is the preferred way to extend Processing these days. See the [Library Overview](https://github.com/processing/processing/wiki/Library-Overview) and [Library Basics](https://github.com/processing/processing/wiki/Library-Basics) wiki pages for some pointers for how to get started.

**Comment by benfry** [comment]
Definitely something for a Contributed Library. With enough interest, it could be later considered for inclusion in the core, but these extended features are why the Library/Tool/Mode mechanism is in place.
