### ISSUE TITLE
Sketch size is always set to full screen, as if the size() function is ignored. [Ubuntu]

### ISSUE THREAD

**Issue by patakk** [processing/processing#4955]
No matter which arguments I give to the `size()` function, it acts as if I'm calling it with `size(displayWidth, displayHeight)` and I can't figure out why.
For me, this issue is present only on Ubuntu and not on Windows. I'm not sure for how long has this been an issue, but could my graphics drivers (nVidia) be the cause of this?

**Comment by gohai** [comment]
Do you see the message "The sketch has been automatically resized to fit the screen resolution" in the console after you quit the sketch? (Do you know whether your Ubuntu OS is running the Mir display server? Could be some weird interaction with Mir...)

**Comment by benfry** [comment]
(No response; closing.)
