### ISSUE TITLE
Making a Quartz Composer/Touch Designer/VVVV/Unreal engine blue print way of implementing Processing sketches

### ISSUE THREAD

**Issue by tiagmoraismorgado** [processing/processing#4958]
**Greetings everyone**

**Processing is already a matured project**. **In the last ten years** it proved to have **evolved on a. consistent way** and get to a point in which **there is plenty of available code,** **anyone can dig into it**, and **you can make pretty sophisticated stuff with it.** Despite the fact that **it is easier and easier to build cool processing sketches pretty fastly,** it would be definitely cool if **we could have like a User interface that would allow us to:**

- **having a Quartz Composer/Touch Designer/VVVV/Unreal engine blueprint UI/UX Gui style of implementing Processing sketches**

the **advantages of such an idea would be:**

- you could **create prototypes;**
- the could be done using **pre-existing libraries and examples**
- you could easily **make new work in Processing, in a easy way**
- you could **extend this environment with further examples**
- that **could be done in a similar way to what you may extend ableton with m4l**

xx

**Comment by benfry** [comment]
This is a major effort but could be implemented as part of a Contributed Tool or Mode. However it's not a high priority for the main project.

**Comment by jeremydouglass** [comment]
@tiagmoraismorgado -- if you are thinking about developing a Quartz Composer-style related tool as a Contributed Tool or Mode, see this discussion on the Processing forums:

-  https://forum.processing.org/two/discussion/18298/node-based-ide-for-processing-or-p5-js

...and in particular check out PraxisLive
