### ISSUE TITLE
adding plethora library to main processing distro

### ISSUE THREAD

**Issue by tiagmoraismorgado** [processing/processing#4960]
**Hey Guys**

I have been using **plethora library** for already few years. **you can find it in the links below**:

- **https://www.youtube.com/watch?v=QT_S--8ufgE**
- **http://www.plethora-project.com/Plethora-0.3.0/index.html**

I think it **should definitely be added to the main processing distribution**.

**Looking forward to hear from you guys**
**xx**
**T.**

**Comment by benfry** [comment]
This is best handled by a Contributed Library, not part of the main distribution.

**Comment by tiagmoraismorgado** [comment]
that's what I mean (adding it to contributed libraries repository
