### ISSUE TITLE
Making processing render and basic 2d/3d primitives natively Vulcan/openGL 4.0 optimized

### ISSUE THREAD

**Issue by tiagmoraismorgado** [processing/processing#4961]
**Greetings everyone**

I would **suggest that we would consider to:**
- **making processing render and basic 2d/3d primitives (plus some other things) natively Vulkan/openGL 4.0 optimized** (but also compatible with OpenGL 2.0, and OpenGL 3.0)
 
**Looking forward**
**xx**
**T.**

**Comment by gohai** [comment]
@tiagmoraismorgado Feel free to send patches. This sounds like a major undertaking though.

**Comment by q2dg** [comment]
I wouldn't close this issue as a reminder of the need of making this step in a (near?) future

**Comment by benfry** [comment]
A drastic rewrite like that would be better started in a separate library and merged in later once it had stabilized. As @gohai mentioned, it's a significant undertaking. Most important, we need someone to actually work on it.
