### ISSUE TITLE
porting google tensorflow to processing

### ISSUE THREAD

**Issue by tiagmoraismorgado** [processing/processing#4962]
**Greetings everyone**

We **all like artificial intelligence**. specially if **it is GPGPU accelerated**, and if it allows us to **do some really interesting things**. that's the purpose of **Google Tensorflow**, a really **powerful library** **that allows us to do some really interesting things with artificial intelligence and our GPUs**. So, I was wondering, that: 

- **Tensorflow was implemented in Openframeworks by MemoAkten**
- to **port Openframeworks C++ code that he created to Processing** (in case it was not ported yet). 
- such a thing **should be included in processing distribution**
- if there is an already existing port of tensor flow to processing we should just include it

xx
T.

**Comment by benfry** [comment]
This is best handled by a Contributed Library, not part of the main distribution.

**Comment by tiagmoraismorgado** [comment]
that's what I mean, how can it be added to the contributed libraries main repository?

**Comment by benfry** [comment]
Library documentation is here: https://github.com/processing/processing/wiki/Library-Overview
