### ISSUE TITLE
Java Runtime Environment configurable? 

### ISSUE THREAD

**Issue by ChaosCom** [processing/processing#4964]
(The following was tested on the 32bit version of Processing 3.3 on windows 7)

Is there no way to configure the Java runtime environment for Processing to use the System JRE? 
What I did was rename the "java" subfolder underneath the main processing folder to "java-old" (as preparation to delete it later on, because i don't wish to have multiple versions of the JRE spreading on my system). 

Running `processing.exe --l4j-debug` corrently indicates picking up the System-wide JRE (log posted below), however, when actually **running** any example ends up in the IDE trying to reference the java executable inside Processing's subfolder (which in my case doesn't exist):

> Exception in thread "Thread-12" java.lang.RuntimeException: Could not open X:\processing-3.3-windows32\\**processing-3.3\java\bin\java.exe** -agentlib:jdwp=tr [...]

Is this behaviour "hardcoded" into the release or configurable somehow (there's no evident entry in preferences.txt)?

Any help appreciated.

**Output of `processing.exe --l4j-debug`**

> Version:	3.9
> CmdLine:	X:\processing-3.3-windows32\processing-3.3\processing.exe --l4j-debug
> WOW64:		yes
> Working dir:	X:\processing-3.3-windows32\processing-3.3\.
> Bundled JRE:	java
> Check launcher:	X:\processing-3.3-windows32\processing-3.3\java\bin\javaw.exe (not found)
> 64-bit search:	SOFTWARE\JavaSoft\Java Runtime Environment...
> 32-bit search:	SOFTWARE\JavaSoft\Java Runtime Environment...
> Check:		SOFTWARE\JavaSoft\Java Runtime Environment\1.8
> Ignore:		1.8
> Check:		SOFTWARE\JavaSoft\Java Runtime Environment\1.8.0_121
> Check launcher:	C:\Software\Java\jre8\bin\javaw.exe (OK)
> Match:		1.8.0_121
> 64-bit search:	SOFTWARE\JavaSoft\Java Development Kit...
> 32-bit search:	SOFTWARE\JavaSoft\Java Development Kit...
> Runtime used:	1.8.0_121 (32-bit)
> Heap -Xmx:	Requested 256 MB / 0%, Available: 5083 MB, Heap size: 256 MB
> Substitute:	EXEDIR = X:\processing-3.3-windows32\processing-3.3
> Add classpath:	lib\pde.jar
> Add classpath:	core\library\core.jar
> Add classpath:	lib\jna.jar
> Add classpath:	lib\jna-platform.jar
> Add classpath:	lib\antlr.jar
> Add classpath:	lib\ant.jar
> Add classpath:	lib\ant-launcher.jar
> Launcher:	C:\Software\Java\jre8\bin\javaw.exe
> Launcher args:	-Xmx256m -Djava.ext.dirs="X:\processing-3.3-windows32\processing-3.3\\java\\lib\\ext" -Djna.nosys=true -Djna.boot.library.path=lib -Djna.nounpack=true -Dsun.java2d.d3d=false -Dsun.java2d.ddoffscreen=false -Dsun.java2d.noddraw=true -classpath "lib;lib\pde.jar;core\library\core.jar;lib\jna.jar;lib\jna-platform.jar;lib\antlr.jar;lib\ant.jar;lib\ant-launcher.jar" processing.app.Base
> Args length:	381/32768 chars
> Exit code:	259
>

**Comment by benfry** [comment]
It's not something that's encouraged. We have to test Processing across many different OSes (Windows, macOS, Linux) on 32- and 64-bit environments, and all manner of machine setups; keeping the JRE a constant version that we're debugging against is one way for us to reduce the crazy number of things we have to test.
