### ISSUE TITLE
Severe discrepancy between ellipse fill path and stroke path

### ISSUE THREAD

**Issue by chrisjj** [processing/processing#4969]
On Processing 3.2.1 in Windows, run this:

```
  colorMode(HSB, 6.0, 1.0, 1.0, 1.0);
  background(0);
  scale(1000.0);
  fill(color(2,1,1));stroke(color(0,1,1));
  strokeWeight(0.005);
  ellipseMode(RADIUS);    
  ellipse(0.05,0.05, 0.017997507,0.017997507);
```
Expected: fill and stroke paths accord
Observed: They don't:

![image](https://cloud.githubusercontent.com/assets/6157073/24082381/a013908c-0cbc-11e7-885b-f50cff9440a0.png)

Workaround: Use a smaller scale.

**Comment by benfry** [comment]
Yeah, don't draw things at tiny fractional sizes then scale them up a thousand times.

Circle outlines are drawn as approximations of line segments. This is how you break them, because it has no idea that you're trying to draw it much larger.

**Comment by chrisjj** [comment]
> Circle outlines are drawn as approximations of line segments. This is how you break them, because it has no idea that you're trying to draw it much larger.

So what's the excuse for circle stroke failing despite that circle fill succeeds?
