### ISSUE TITLE
Export mac OS 32 bits vs 64 bits

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#4971]
Hello,
I work on project use differents apps on Mac OS, and I see one of my app is 176 M and the other one only 46 M. The lightest is 64bit and the biggest one in 32bits, and the 32 bits is very heavy and it's a defaults exportation, I find no option in menu to export in 64bits by defaults. Maybe there is ; so I use the trick and add 'import processing.video.* ;' to force processing to export in macOS 64 bits.

May be in the future can be good add this option or export by default in 64 bits because is lighter and and mac OS 64 are most common now ?

**Comment by benfry** [comment]
Only 64-bit exists on the Mac these days, what library are you using that provides a 32-bit version?

**Comment by StanLepunK** [comment]
I don't use any library to provided the 32 bits version, it's like a usual version, but it's necessary to use library video to provided a 64 bits version. It's a supposition.
 See the screenshots.

![capture d ecran 2017-04-23 a 12 12 22](https://cloud.githubusercontent.com/assets/3332269/25312629/88ddbb18-281e-11e7-8c9b-d1dc3812a527.png)

The result is 64 version, heavy 44 Mo

![capture d ecran 2017-04-23 a 12 05 19](https://cloud.githubusercontent.com/assets/3332269/25312630/88e285f8-281e-11e7-98e6-6a1d135cbe8e.png)

Processing return a pop-up window to say it's not possible to make a 32 bits version.

![capture d ecran 2017-04-23 a 12 12 58](https://cloud.githubusercontent.com/assets/3332269/25312631/88e6b574-281e-11e7-9004-318fcbd9881f.png)

The size of the standard version in 32 bits is 176 Mo.

**Comment by benfry** [comment]
I've tracked down the error message, it's because the video library is marked differently. I've added a fix to 3.3.1 that will prevent this error message from showing up. 

The difference in the sizes is unrelated—it's probably because one of them you had "embed Java" selected, and the other you did not.

**Comment by StanLepunK** [comment]
hmmm, the both are embeded java.
But the sketch used librarie video is lighter... weird ? But the good with that, that build an app very light agains the classid export with the processing.video :)
![capture d ecran 2017-04-23 a 17 07 01](https://cloud.githubusercontent.com/assets/3332269/25314597/78a3dab0-2847-11e7-8c24-11709ba2684b.png)

**Comment by benfry** [comment]
Not sure what's happening exactly, but it's not possible to have the "embed" option selected and the result to be 44 MB. It's much larger than that. Hopefully the 3.3.1 release will at least clear up the confusion!
