### ISSUE TITLE
Processing Crashing in mac OS Sierra

### ISSUE THREAD

**Issue by WindmillG** [processing/processing#4975]
I am having problems with the processing application.

Macbook Pro Retina 
2,4 GHz Intel Core i5 / Intel Iris 1536 MB
MacOS Siera 10.12.3

Processing 3.3.

The application starts up but I can't interact with it. I can't write a piece of code or open an example. 
After a few seconds in the force quit menu shows that Processing (not responding). 
 The system seems up to date. I don't know what is wrong. 

Event:           hang
Duration:        1.80s (process was unresponsive for 18 seconds before sampling)
Steps:           18 (100ms sampling interval)

**Comment by benfry** [comment]
Please use forum.processing.org for questions like this. There are also troubleshooting instructions here: https://github.com/processing/processing/wiki/Troubleshooting
