### ISSUE TITLE
Processing crashes computer macbook pro os Sierra

### ISSUE THREAD

**Issue by droomcommissaris** [processing/processing#4977]
After a few sketch runs the screen starts glitching and eventually my computer just shuts down. Could this be something related to Processing?

This is the report I get after restarting.

*** Panic Report ***
panic(cpu 0 caller 0xffffff8007a05ecd): Kernel trap at 0xffffff8007b07f70, type 13=general protection, registers: ...

Backtrace (CPU 0), Frame : Return Address
0xffffff80e9a04c50 : 0xffffff80078f210c 
...

BSD process name corresponding to current thread: NowPlayingTouchU
Boot args: kext-dev-mode=1

Mac OS version:
16D32

**Comment by benfry** [comment]
No, but from the error report, it looks like it's a crash inside something called `NowPlayingTouchU`.
