### ISSUE TITLE
libraries in java tabs (separate .java files) are reported missing

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#498]
_Original author: fjen...@gmail.com (November 27, 2010 14:41:10)_

Libraries imported in .java tabs are reported missing. This happens even for the included libraries as for example processing.pdf . Workaround is to import the library again in one of the &quot;normal&quot; tabs.

_Original issue: http://code.google.com/p/processing/issues/detail?id=459_

**Comment by benfry** [comment]
Not going to pursue this—we don't mess with `.java` files in any other way, and I'm not comfortable with breaking that general contract. The notion of adding libraries to the classpath based on `import` statements is unique to Processing, and makes sense to be used in connection with `.pde` files. 

And there's a simple workaround, where users can add the necessary import to any `.pde` file itself.
