### ISSUE TITLE
Processing.js closes active Processing session when set

### ISSUE THREAD

**Issue by kfrajer** [processing/processing#4984]
I post this originally in the Processing.js GitHub and they sent me here, so here I am.

-----------------------------------------------

This is to document a bug in the processing IDE. I am using processing 3.3 Win10 x64. This is what happens. I open Processing and it starts in java mode. I switched to javascript mode and the window closes. I tried to restart processing and it won't open any new sketch window. Then, I decided to open a pde file and processing runs and opens the file in JavaScript mode. Good. Then I create a new sketch as a **next step** and it fails, throwing the following error in the console:

> Error while assigning the sketch template.

I can switch back to Java mode and everything goes back to normal. In addition, this behavior is not observed in Processing 3.1.1 or 3.1.2

This issue was also posted here
https://forum.processing.org/two/discussion/21590/processing-js-closes-active-processing-session-when-set

Previous related issue:
fjenett/javascript-mode-processing#35

kfrajer

**Comment by benfry** [comment]
Processing.js Mode isn't our project.
