### ISSUE TITLE
When opening a file, if you double-click the direction key, the program Processing is certain to crash!!!

### ISSUE THREAD

**Issue by ShadowChenCSD** [processing/processing#4986]
System:Mac OX Sierra
Version:10.12.4
Version of Processing:3.3

The troublesome problem is described in the title.
Please tell me how to fix this bug, thank you!

**Comment by benfry** [comment]
What's the direction key?

**Comment by benfry** [comment]
No response, closing.

**Comment by ShadowChenCSD** [comment]
OK. Thanks.

发自我的 iPad
