### ISSUE TITLE
Updated to a new version of Processing (32-bit), but it does not start

### ISSUE THREAD

**Issue by wolfram77** [processing/processing#4989]
I have download it from the latest stable release:

Here is the error:
![0](https://cloud.githubusercontent.com/assets/3179612/24444747/241f80a0-1485-11e7-82df-af738f5b71f6.png)

**Comment by wolfram77** [comment]
The same error occurs on 64-bit version too.

**Comment by benfry** [comment]
Duplicate of https://github.com/processing/processing/issues/4972
