### ISSUE TITLE
Trouble launching Processing on locked down (school) machines

### ISSUE THREAD

**Issue by zane49er2** [processing/processing#4990]
I would like to use processing's official IDE in school, but the security measures are far too extreme. Programs may not write to anywhere except a network location and a portable drive. I have the processing folder on my flash drive, but it crashes immediately on startup. I would expect it to take 10 seconds to load on the typical school computer, but the loading tile pops up for less than a second before closing with no error message. I have tried changing the defaults file (there is no preferences file). I have also tried moving processing to the network location, which has been renamed to documents, but the program will not start because of security (I'm already using a strange loophole to open them on the USB).

**Comment by CaptianNemo** [comment]
Does it work with 3.2.4? Had the same issue with 3.3 on my personal PC, switched to 3.2.4 and it worked.

**Comment by benfry** [comment]
Is this on a Windows PC or a Mac? What happens during the crash? Can you check [this page](https://github.com/processing/processing/wiki/Troubleshooting) for info about how to get the actual error messages and report back?

We've put a lot of effort into making it work in environments like this (it's part of why we don't have an installer, for instance), so this should be easily possible.

**Comment by zane49er2** [comment]
this is on a windows computer (7 enterprise), and it shows the loading splash for a few frames, then closes. no errors or windows appear. I cannot debug, as command prompt is disabled.

**Comment by zane49er2** [comment]
The school's IT people have confirmed that it is an access error.

**Comment by jeremydouglass** [comment]
Thank you for following up. So can this issue be closed now?

> because it was on a flash drive which has since been wiped, since those aren't allowed either

Wow -- I've never heard of a network auto-wiping flash drives rather than just refusing to mount them, but *being deleted* would definitely definitely interfere with Processing's ability to function.

**Comment by zane49er2** [comment]
It wasn't deleted by the school, I deleted it because I wasn't allowed to have it in school and it was useless as a portable software kit. I'm now using it as a tiny amount of extra drive space for word documents and non-code assets. Yes, the issue can be closed.
