### ISSUE TITLE
building on ubuntu requires dependency

### ISSUE THREAD

**Issue by themancalledjakob** [processing/processing#4991]
on Ubuntu 16.04 I got the error
`The import javafx cannot be resolved`
had to run
`sudo apt-get install openjfx`
before build worked

**Comment by benfry** [comment]
Did you not install the JRE 8 from Oracle?

**Comment by themancalledjakob** [comment]
Yes, pretty sure I followed the build instructions properly.
I'll try it on a vanilla ubuntu to check if it is reproducable.

**Comment by benfry** [comment]
I can't reproduce this on a clean Ubuntu install. The fact that reinstalling OpenJFX fixes it would suggest that the Oracle JDK wasn't installed per the instructions.
