### ISSUE TITLE
Hebrew punctuation mark causes editor caret to be placed in the wrong location

### ISSUE THREAD

**Issue by dzaima** [processing/processing#4992]
String chars = "⁰¹²³⁴⁵⁶⁷⁸\t\n⁹±∑«»æÆø‽§°¦‚‛⁄¡¤№℮½ !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~←↑↓≠≤≥∞√═║─│≡∙∫○׀′¬⁽⁾⅟‰÷╤╥ƨƧαΒβΓγΔδΕεΖζΗηΘθΙιΚκΛλΜμΝνΞξΟοΠπΡρΣσΤτΥυΦφΧχΨψΩωāčēģīķļņōŗšūž¼¾⅓⅔⅛⅜⅝⅞↔↕∆≈┌┐└┘╬┼╔╗╚╝░▒▓█▲►▼◄■□…‼⌠⌡͏→“”‘’";
Paste that in PDE and after that string the caret will be offset in the editor.
From further testing I found that it's something with `ø⁄׀` or `⁄ø׀` appearing in that order anywhere in the string.

**Comment by aosman96** [comment]
can you send your code

**Comment by dzaima** [comment]
The OP has the problematic code. Paste it in PDE and try to write something after that. The caret will be offset. If you need the full code, [here](https://github.com/dzaima/SOGL/blob/master/P5Parser/P5Parser.pde)

**Comment by benfry** [comment]
Probably due to `׀` which is a punctuation mark and seems to be handled differently.

**Comment by dzaima** [comment]
This seems to be fixed now in 3.3.1 or 3.3.2

**Comment by benfry** [comment]
Huh… did you change the font used in your editor? What language do you have the PDE set to? For Greek, Arabic, Chinese, Japanese, and Korean, we explicitly switch fonts (which was a fix in 3.3.1).

Oh, or maybe it was a Java bug, fixed by switching to a newer version of Java in 3.3.1.
