### ISSUE TITLE
keyPressed is false if one key is released while multiple keys are pressed

### ISSUE THREAD

**Issue by name-here** [processing/processing#4993]
keyPressed is false if one key is released while multiple keys are pressed.  For example, if Q and W keys are pressed, and only Q is released, keyPressed becomes false.  Code to test it:
`void setup(){
  size(100, 100);
}

void draw(){
  background(0);
  if(keyPressed){rect(25, 25, 50, 50);}
}`

**Comment by Lord-of-the-Galaxy** [comment]
Foematted code :   
```processing  
void setup(){
size(100, 100);
}

void draw(){
background(0);
if(keyPressed){rect(25, 25, 50, 50);}
}

**Comment by benfry** [comment]
Fixed for the next release.
