### ISSUE TITLE
commentary bug

### ISSUE THREAD

**Issue by thereventonshow** [processing/processing#4995]
Hi everyone, I have an issue with the commentary "/*  */", so I have created an class that contain multiple information about item, 
![capture1](https://cloud.githubusercontent.com/assets/27006725/24796731/82eb1b20-1b8e-11e7-93af-3384630835fc.PNG)
they are displayed like that, you can see between "M1911" and "G17" there is commentary that I use for
displaying information, (by that way I can see what information is with other information.
So with the first picture the code work. So I want to display information about other item like that 
![capture2](https://cloud.githubusercontent.com/assets/27006725/24796732/82ef6036-1b8e-11e7-968f-26259a5dd9e7.PNG)
But when I do that, the code don't want to work.
![capture3](https://cloud.githubusercontent.com/assets/27006725/24796733/82f2f610-1b8e-11e7-81c8-018b53feeb4e.PNG)
Also sorry for my english, I'm french.

**Comment by Lord-of-the-Galaxy** [comment]
I can confirm the bug. Also note, the highlighting is correct. Maybe a problem with the compiler.
