### ISSUE TITLE
Nvidia driver 381.65 breaks Processing sketches (Target VM failed to initialize)

### ISSUE THREAD

**Issue by glvjr** [processing/processing#4997]
Hello,

1) Windows 10 x64 latest updates.
2) Nvidia GeForce 745
2) Additional details in the output:
![nvida breaks](https://cloud.githubusercontent.com/assets/11392209/24837270/25ee3d50-1cfe-11e7-8c28-1fe55e71b942.PNG)
3) I had a similar problem this year with Nvidia driver 378.49:
https://github.com/processing/processing/issues/4853
4) I reverted back to an older driver that worked.
5) Working now with 376.33 (10/27/2016); I went back a few versions because I never had any issues last year with drivers.

:)

**Comment by glvjr** [comment]
I thought I would try it with the latest Windows update and still not working:
1) Windows 10 Creators Update x64
2) Nvidia GeForce 745
![image](https://cloud.githubusercontent.com/assets/11392209/25065128/2f4ac34a-21d7-11e7-9daf-4421eb4bf492.png)

**Comment by glvjr** [comment]
GeForce Hotfix driver 381.78 corrects the problem:
http://nvidia.custhelp.com/app/answers/detail/a_id/4453/~/geforce-hotfix-driver-381.78

**Comment by benfry** [comment]
Added the same warning message for this version of the driver for 3.3.1.
