### ISSUE TITLE
option to print all code in a project

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#50]
_Original author: b...@processing.org (June 06, 2010 23:36:28)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=28

Comment from fry, 2005-05-12 20:18

make a well-formatted version of printing all the tabs as a single concise
document, once the printing support is complete.

_Original issue: http://code.google.com/p/processing/issues/detail?id=11_

**Comment by JakubValtar** [comment]
Still can print one only tab at a time.

Printing could use some improvements, the output is not very printer friendly, some parts have black background with white letters, etc.

**Comment by GKFX** [comment]
I'm working on this.
