### ISSUE TITLE
Python mode not working on Mac?

### ISSUE THREAD

**Issue by mschillo** [processing/processing#5001]
hi,

when I turn processing to python mode and type some code and let it run, processing shows no response. Symptoms remain for valid or invalid python code. Mac's console log does not show anything related.

Can you help?

Cheerio,

Michael.

PS: I installed processing 3.3 on my machine with macos 10.12.4, python mode installed via build number is 3020

**Comment by gohai** [comment]
@mschillo I believe this should probably be reported over at the dedicated repository for processing.py, where @jdf might be able to troubleshoot the issue: https://github.com/jdf/processing.py/issues
