### ISSUE TITLE
why this show the problem about Port

### ISSUE THREAD

**Issue by jae7438** [processing/processing#5003]
`void setup() {
  size(400, 460, P3D);
  //println(Serial.list());
  new Serial(this, "COM4",  57600); 
  noLoop();
  PFont font = loadFont("ArialUnicodeMS-48.vlw"); 
  textFont(font, 14);
}`

new Serial(this, "COM4", 57600);
what is that mean?? 
what "this"
what "COM4"    <<-- I know the computer Port
what "57600" ????

but again to again I saw that the allocated object is never used.
I don't know why was it?

**Comment by gohai** [comment]
You might want to post this questions in the Forum, this place here is for reporting bugs. See here: https://forum.processing.org/two/

**Comment by jae7438** [comment]
Really Thank you!!
 
I'm Korea. University student.
Actually I don't  have a lot of English skills.
Now I'm self taught.
I will make a drone for my contest.
But I have few data about mpu6050+avr128
May I ask that if you do not mind?
 
 
-----Original Message-----
