### ISSUE TITLE
PShaders crash with Mesa 17.0.3

### ISSUE THREAD

**Issue by hamoid** [processing/processing#5004]
I don't know if this is a bug with the latest drivers, or something that needs to be updated in Processing or in its OPENGL dependencies. I'll try to revert my drivers for now.

```
java.lang.RuntimeException: main-FPSAWTAnimator#00-Timer0: createImpl ARB n/a 
    but required, profile > GL2 requested (OpenGL >= 3.1). 
    Requested: GLProfile[GL4/GL4.hw], 
    current: 3.0 (Compat profile, compat[ES2], FBO, hardware) - 3.0 Mesa 17.0.3
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:482)
	at java.lang.Thread.run(Thread.java:745)
```

This happens when running any of the shader examples.

_quad core i7 laptop, up to date ArchLinux, Intel graphics 4600._

**Comment by hamoid** [comment]
The issue is not present on Mesa 17.0.2.

**Comment by obackhoff** [comment]
Same error message and same Mesa version... if I try P3D or P2D renderer I get this issue.

**Comment by hamoid** [comment]
17.0.4 works fine again. I assume this was a problem with Mesa, and it's now fixed.

**Comment by benfry** [comment]
Thanks for the update; I'll close this unless we hear otherwise.
