### ISSUE TITLE
Overlapped lines in Show Usage and Examples Windows

### ISSUE THREAD

**Issue by glasscanvas** [processing/processing#5007]
Overlapped lines. Examples using the Microsoft Surface Studio screen capture,

![processing crunched lines](https://cloud.githubusercontent.com/assets/12136395/25062718/8b43c3d2-219f-11e7-800f-0c224a8ec692.PNG)

Window 10 Pro 10.0.15063 build 15063
Processing 3.3
I am seeing that the "Examples" and the "show usage" windows have overlapping text lines making them hard to read. Adjusting the font does not help on these panels. Interface scale defaulted to 200%. Setting it to 100% and restarting processing does not solve the issue with the two panels. The main IDE window does scale accordingly. Display density reports a 1. I definitely willing to test a solution or try to fix code if I can get some help in the right direction.

**Comment by benfry** [comment]
Yeah, sorry about that. Here's another report about it: https://github.com/processing/processing/issues/4936

**Comment by benfry** [comment]
All fixed for 3.3.1.

**Comment by glasscanvas** [comment]
Thanks Ben. Yes it is fixed in 3.3.1

**Comment by benfry** [comment]
Thanks for following up.
