### ISSUE TITLE
selectInput() crash in Windows 10 creators update and P3D

### ISSUE THREAD

**Issue by glasscanvas** [processing/processing#5009]
If I open the system file requester, Processing crashes. 

The file requester opens to the last location but you can't select or type anything in the file dialog.
Can't close it either but can stop it with the stop button.

The error message is from a very long program so I  wrote a brief example. It does not cause the error message but it hangs in the same way. I suspect that there is a file processing does not like or that the folder is in DropBox. How do I make processing forget the last path in Windows 10 ? Maybe that will unlock it.

Window 10 Pro 10.0.15063 build 15063
Processing 3.3

This program was working before.
Here is the error reported.

From error log:
```
Apr 15, 2017 9:56:44 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
```

From Console - large program:
```
RunnableTask.run(): A caught exception occured on thread main-Display-.windows_nil-1-EDT-1: RunnableTask[enqueued true[executed false, flushed false], tTotal 0 ms, tExec 0 ms, tQueue 0 ms, attachment null, throwable java.lang.RuntimeException: Waited 5000ms for: <5e50fab4, eb41730>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>]
java.lang.RuntimeException: Waited 5000ms for: <5e50fab4, eb41730>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at jogamp.newt.WindowImpl.setVisibleActionImpl(WindowImpl.java:1234)
	at jogamp.newt.WindowImpl$VisibleAction.run(WindowImpl.java:1318)
	at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:450)
	at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2782)
	at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:1330)
	at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:1335)
	at com.jogamp.newt.opengl.GLWindow.setVisible(GLWindow.java:578)
	at processing.opengl.PSurfaceJOGL$4.run(PSurfaceJOGL.java:513)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:127)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:375)
DefaultEDT.run(): Caught exception occured on thread main-Display-.windows_nil-1-EDT-1: RunnableTask[enqueued false[executed true, flushed false], tTotal 5001 ms, tExec 5001 ms, tQueue 0 ms, attachment null, throwable java.lang.RuntimeException: Waited 5000ms for: <5e50fab4, eb41730>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>]
java.lang.RuntimeException: Waited 5000ms for: <5e50fab4, eb41730>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at jogamp.newt.WindowImpl.setVisibleActionImpl(WindowImpl.java:1234)
	at jogamp.newt.WindowImpl$VisibleAction.run(WindowImpl.java:1318)
	at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:450)
	at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2782)
	at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:1330)
	at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:1335)
	at com.jogamp.newt.opengl.GLWindow.setVisible(GLWindow.java:578)
	at processing.opengl.PSurfaceJOGL$4.run(PSurfaceJOGL.java:513)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:127)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:375)
```

Here is a short piece of code that causes problem:

```
 //<>//
int doneFlag = 0;
void setup()
{
  try {
    println("About to do requester");
    selectInput("Select a file to process:", "fileSelected");
  }
  catch(Exception e) {
    println("Exception 1");
  }
}



void fileSelected(File selection) {
  try {
    if (selection == null) {
      println("Window was closed or the user hit cancel.");
    } else {
      println("User selected " + selection.getAbsolutePath());
    }
  }
  catch(Exception e) {
    println("Exception 2");
  }
}
```

**Comment by benfry** [comment]
Can you confirm that the code you posted causes the same crash? Because the error messages are from a P2D or P3D version of the application.

**Comment by glasscanvas** [comment]
[sketch_20170415b.zip](https://github.com/processing/processing/files/951269/sketch_20170415b.zip)

Ben,

I have a very long multi tab application which produces the full error message. I'll be happy to put it somewhere. It does output the above massage. the short code above is just a file requester example. 
( the example above does have a draw() loop). These programs run on the Mac.
It just freezes and does not produce a message, however the console log files produce this:

Apr 24, 2017 4:57:13 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

I just went to processing 3.3.1 same issue. crunched lines are fixed.

**Comment by glasscanvas** [comment]
[sketch_20170424_generateme.zip](https://github.com/processing/processing/files/951339/sketch_20170424_generateme.zip)

Ben full file. It will need several libraries

**Comment by glasscanvas** [comment]
Where does processing in Windows store the last folder location used in a file requester?
I would like to try to delete that location as it is remembering a DropBox folder and wondering if that is an  issue

**Comment by benfry** [comment]
Does this only happen since the Windows 10 Creators Update? Did previous versions of Windows 10 work?

What happens if you call `selectInput()` a different function than `setup()`?

**Comment by glasscanvas** [comment]
Hi codeanticode, It ran before creators update. I only had the computer for about a week before the creators update was installed.
Here is calling from another function , no difference.

int doneFlag = 0;
void setup()
{
 myTest();
}

void myTest()
{
  
   try {
    println("About to do requester");
     selectInput("Select a file to process: ", "fileSelected2");
    //selectFolder("Select a folder to process: ", "fileSelected");
  }
  catch(Exception  e) {
    e.printStackTrace();
    println("Exception 1");
  }
  
}

void draw(){
}

void fileSelected2(File selection) {
  try {
    if (selection == null) {
      println("Window was closed or the user hit cancel.");
    } else {
      println("User selected " + selection.getAbsolutePath());
    }
  }
  catch(Exception e) {
    println("Exception 2");
  }
}

**Comment by benfry** [comment]
That's still a function called from `setup()`. What happens when it's in `draw()` or `keyPressed()`?

**Comment by glasscanvas** [comment]
keypress just does nothing:

// ------------------------------------------------------------------------------------------------
// setup()
// ------------------------------------------------------------------------------------------------

int doneFlag = 1; // Change to zero to test inside draw, but it just does nothing with keypress
void setup()
{
  size(600,400, P3D);
 //myTest();
}


// ------------------------------------------------------------------------------------------------
// draw()
// ------------------------------------------------------------------------------------------------

void draw(){
  while (doneFlag == 0)
  {
    myTest();
    doneFlag = 1;
    println("Inside Draw");
  }
}


// ------------------------------------------------------------------------------------------------
// fileSelected2(File selection)
// ------------------------------------------------------------------------------------------------

void fileSelected2(File selection) {
  try {
    if (selection == null) {
      println("Window was closed or the user hit cancel.");
    } else {
      println("User selected " + selection.getAbsolutePath());
    }
  }
  catch(Exception e) {
    println("Exception 2");
  }
}

// ------------------------------------------------------------------------------------------------
// myTest()
// ------------------------------------------------------------------------------------------------

void myTest()
{
  
   try {
    println("About to do requester");
     selectInput("Select a file to process: ", "fileSelected2");
    //selectFolder("Select a folder to process: ", "fileSelected");
  }
  catch(Exception  e) {
    e.printStackTrace();
    println("Exception 1");
  }
  
}

// ------------------------------------------------------------------------------------------------
// KeyPress handlers
// ------------------------------------------------------------------------------------------------

void keyPressed()
{
  if (key == 'l'|| key == 'L') {
    println("File load with Key");
    myTest();
    println("Done File Load");
  }
}

**Comment by codeanticode** [comment]
I can confirm that the last two sketches work without problem on a Windows 10 Home edition. I would need to update to the new "Creators" version to see what's might be causing the crash...

**Comment by glasscanvas** [comment]
codeantidote.  the selectInput did work in windows10 pro before the creators update. I broke with the creators update

**Comment by glasscanvas** [comment]
I found this clue:
http://forum.imagej.net/t/file-open-image-command-freezes-on-windows-10-creator/4930/4

**Comment by glasscanvas** [comment]
I loaded this program on an older PC with windows 10 home, version 1607, build 14393.953 and it works on that configuration. This issue is with the creators update 
Window 10 Pro 10.0.15063 build 15063
Processing 3.3.2

**Comment by glasscanvas** [comment]
The Windows 10 update 2017-05 Cumulative Update for Windows 10 Version 1703 for x64-based Systems (KB4016871) 

**Has fixed the problem.**

No need to run in compatibility mode or admin, just defaults work.

I tested this with Processing 3.3.2 and 3.3.3

**Comment by benfry** [comment]
Ok, thanks for the update.
