### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by limooch** [processing/processing#5012]
Hello dear friends,
I have some problem with loading of Processing. 
Here is the error message.
The problem has started after installtion of JAVA.

Best regards

Mehdi
![error](https://cloud.githubusercontent.com/assets/27758263/25164626/c50b05ce-24da-11e7-9c46-c301b44eee9a.jpg)

**Comment by gohai** [comment]
@limooch Which version of Windows is this on? Is this a 64-bit OS or 32-bit one? And finally: are you attempting to launch the 64-bit or 32-bit version of Processing? Thanks!

**Comment by limooch** [comment]
Hello dear friends!
I am using the Windows 10 , 64 bit.I should say I could resolve the problem just by re-extacting the zip file and putting the whole folder on the desktop. I don't know if this was the real "Trick".
Thanks for your kind and quick answer
All the best
Mehdi 

    Il Mercoledì 19 Aprile 2017 12:16, Gottfried Haider <notifications@github.com> ha scritto:
 

 @limooch Which version of Windows is this on? Is this a 64-bit OS or 32-bit one? And finally: are you attempting to launch the 64-bit or 32-bit version of Processing? Thanks!—
