### ISSUE TITLE
File not shown in file

### ISSUE THREAD

**Issue by yujungchoi2649** [processing/processing#5015]
Hi, I have been using Processing for a year now.

Recently I bought a new laptop and downloaded Processing on Windows 10 64bits.
I have the icon for the software but when I save the file it is now shown in the folder.
They are not hidden files, and I know they are saved because when I click export application, they are shown in the exact same folder I have saved.

Is any setting causing this problem? 
This is the first time happening to me, and is very frustrating since I am not be able to access to the files that I need to work with.

I have tried saving files in different folders, paths, authority, and showing all hidden files.

What would you recommend me to do in this case?

**Comment by gohai** [comment]
Downloading the file should save it as a regular file in your Download folder. In any way, this seems more like a bug or issue in your browser, or operating system than in Processing proper.

**Comment by yujungchoi2649** [comment]
What can possibly go wrong, do you have any idea? because the system hasn't changed that much since I just bought this laptop.
