### ISSUE TITLE
Prevent arbitrary command injection

### ISSUE THREAD

**Issue by NateUniAccount** [processing/processing#5018]
PApplet allows any command to be run on the command line via the public methods `PApplet.launch(String...)` and `PApplet.exec(String... args)`.
Both of these methods should be replaced with a single method that calls `Desktop.getDesktop().open(file);`
which accomplishes the same goals without exposing the user to command injection and with the further benefit of being OS independent.
A bandaid fix would be to make both methods private or at least have default visibility.
Not going to post any code here, but it would be an easy matter to create a processing project that destroys a computer when it's run.

**Comment by gohai** [comment]
@NateUniAccount Would you mind sending a pull request that replaces `launch` and `exec` with the method your suggesting?

**Comment by JakubValtar** [comment]
@NateUniAccount I don't think your argument holds. How do I run commands on the command line without `exec()`? What prevents me to use `Runtime.getRuntime().exec()` instead?

Can you please post a scenario how this would be used to destroy a computer and a sample sketch which suffers from the command injection vulnerability?

**Comment by NateUniAccount** [comment]
@gohai Sure yes will do
@JakubValtar There shouldn't be a need to run anything directly on the command line, the JDK is meant to provide the abstraction to do whatever is needed. Nothing prevents it, but it's one matter to know about that class and methods and quite another to provide an easy and public shortcut to it.
All that would be needed is to have a main method which calls `PApplet.exec("<insert commands>");`
Not going to post any commands here, but deleting directories and files would be the obvious first choice.

**Comment by gohai** [comment]
@NateUniAccount If there is malicious intent then `Runtime.getRuntime().exec()` does the same thing, as Jakub pointed out. What "accidental" scenario do you have in mind that would make users shoot themselves in the foot with `launch` or `exec`?

**Comment by benfry** [comment]
There is most certainly a need to run things directly on the command line, otherwise `exec()` and `launch()` wouldn't be part of the API. This is just like `system()` in C/C++, or  `os.system()` in Python, and so on. And users need to be just as careful in those cases. 

From a technical standpoint, support for the `Desktop` methods are extremely inconsistent across platforms, and the suggested solution would likely create more problems than the problem that it hypothetically solves.

**Comment by NateUniAccount** [comment]
@gohai Please see the previous comment
@benfry It was my understanding that Processing is designed to be a graphics editor rather than a general purpose programming language, if I have that wrong I apologise. If it is the former then the methods should at least be private

**Comment by NateUniAccount** [comment]
Afraid am gonna have to wash my hands of this - the inter-dependencies, exposed class members and procedural style make it a nightmare to re-factor. Best of luck though
