### ISSUE TITLE
Issue in example "MouseSignals"

### ISSUE THREAD

**Issue by Rajduino** [processing/processing#5020]
Int the example of "MouseSignals", the topmost graph showing the x-position of the mouse pointer does not map the x-value (xvals[]) from [0,width] to [0,height/3].

_ORIGINAL CODE Line 49_
```point(i, xvals[i]/3);```

_MODIFIED_
```point(i, map(xvals[i],0,width,0,height/3-1));```

```height/3-1``` so that the line is visible when the mouse is on the extreme right.

The code for showing the ```mousePressed``` state could also be a little different.

_ORIGINAL CODE_
```
if(mousePressed) {
    bvals[width-1] = 0;
  } else {
    bvals[width-1] = 255;
  }
```

``` line(i, 2*height/3+bvals[i]/3, i, (2*height/3+bvals[i-1]/3));```

The values 0,255 and ```bvals[i]/3``` is little misleading.
They can be

```
if(mousePressed) {
    bvals[width-1] = 10;
  } else {
    bvals[width-1] = 110;
  }
```

```line(i, 2*height/3+bvals[i], i, (2*height/3+bvals[i-1]));```

**Comment by benfry** [comment]
Moved to https://github.com/processing/processing-docs/issues/546

**Comment by REAS** [comment]
OK. I've updated the example with nearly all of the suggestions above. Thank you.
