### ISSUE TITLE
Array out of bounds, even though it's not?

### ISSUE THREAD

**Issue by PedroZardo** [processing/processing#5025]
```java
PImage img;
Circle[] circles;
float x, y, pos;
void setup(){
  size(640, 360);
  circles = new Circle[5000]; //this number
  img = loadImage("img.jpg");
  img.resize(0,360);
  img.loadPixels();
  println(circles.length);
  for(int i = 0; i < circles.length; i++){
    x = random(width);
    y = random(height);
    pos = x + y*width;
    println(i);
    circles[i] = new Circle(x, y, random(5,20), img.pixels[int(pos)]); // this line is giving errors
  }
}

void draw(){ 
  for(int i = 0; i < circles.length; i++){
    circles[i].show();
    circles[i].move(); // added later for tests, see *edit below
  }
}

```
That does not work for some reason. It did with lower numbers, then it didnt with a 1000, givin ArrayIndexOutOfBoundsException, then when I put println(i). right before the line that is giving errors, it did ok with 1000, but not with 5000, and it prints just up to 300-500. What is happening here? I still have plenty ram btw

*edit:
before I was just using circles[i].show(); If I use circles[i].move() it wont work with even 200 circles

Thanks in advance

**Comment by gohai** [comment]
@PedroZardo This is not the place to solicit programming advice - please use the Forum for this.
