### ISSUE TITLE
Having int variables in size(a,b) creates uncloseable window

### ISSUE THREAD

**Issue by schang1146** [processing/processing#5030]
![image](https://cloud.githubusercontent.com/assets/20074034/25422423/b6bc9326-2a15-11e7-936e-221b3b69298f.png)

I tried setting integer global variables to control the size of the window that pops up but it's been creating this window that I can't close. Clicking on 'OK' does absolutely nothing (no clicking animation). Clicking on the red 'x' on the top right looks like it's being clicked but nothing happens either.

**Comment by benfry** [comment]
Yeah, sorry, same issue as here: https://github.com/processing/processing/issues/5030 

Only happens on some machines so it's been tricky to track down.
