### ISSUE TITLE
keyPressed not returning false once a key is released

### ISSUE THREAD

**Issue by pieteroyens** [processing/processing#5033]
### Issue description
using the keyPressed boolean call (https://processing.org/reference/keyPressed.html), the value keeps being true once pressed, even after release. 

for instance: 
if (keyPressed) {  
// some code
}

then never leaves the if statement when the key is released.

**Comment by benfry** [comment]
Ouch, a dumb typo caused that one. Fixed for 3.3.3. (Caused by the attempt to fix https://github.com/processing/processing/issues/4993)

**Comment by benfry** [comment]
Now fixed: https://github.com/processing/processing/releases/tag/processing-0260-3.3.3

**Comment by clankill3r** [comment]
This bug is still there in 3.3.3
I think it only happens for CODED keys, and after like 3 seconds. Press up for example for 3 seconds.

```
void draw() {  
  println(keyPressed);
}
```

**Comment by epar** [comment]
Not fixed in 3.3.3 for me either macOS Sierra 10.12.04

**Comment by benfry** [comment]
Another problem was found, which will be fixed in 3.3.4: https://github.com/processing/processing/issues/5049
