### ISSUE TITLE
Processing zip file not properly unzipping on Windows

### ISSUE THREAD

**Issue by baileydocter** [processing/processing#5035]
I was able to download processing just fine, but when I unzipped the file my program quit halfway through saying the file was damaged. I tried it again just to see if my computer was at fault, but the same thing happened. I have a processing folder full of assets and programs, but I searched my whole CPU and processing.exe does not exist. I'm sure there's something I'm doing wrong, but I can't for the life of me figure out what.

**Comment by gohai** [comment]
You might want to try to clear your browser's cache, re-download Processing from the website (if you can: using a different browser could also be a good idea), and unzipping it.
