### ISSUE TITLE
text() with PFont (loadFont) occur ArrayIndexOutOfBoundsException, with negative value, only in MAC

### ISSUE THREAD

**Issue by icq4ever** [processing/processing#5036]
hi.

when drawing negative value to text with text(), with vlw font by createFont tool, **ArrayIndexOutOfBoundsException Error** occur in mac.

it happen only with negative value. 

I tested with mac and pc both. but it happen only in mac.

<img width="559" alt="screen shot 2017-04-28 at 5 05 42 pm" src="https://cloud.githubusercontent.com/assets/530796/25520136/c018cc88-2c35-11e7-937b-f8dadc7a24dd.png">
<img width="559" alt="screen shot 2017-04-28 at 5 05 48 pm" src="https://cloud.githubusercontent.com/assets/530796/25520135/c018ddae-2c35-11e7-9de7-b07dfd6187f0.png">
<img width="418" alt="screen shot 2017-04-28 at 5 11 06 pm" src="https://cloud.githubusercontent.com/assets/530796/25520137/c01fda00-2c35-11e7-87b4-683e42dd8232.png">

**Comment by endoh0509** [comment]
I worked in Processing 3.3.2 and MacOS 10.12.4
Did you try latest version?

<img width="295" alt="img1" src="https://cloud.githubusercontent.com/assets/7820411/25521721/b39be3ae-2c3b-11e7-9f1d-2751e2f377b2.png">
<img width="479" alt="img2" src="https://cloud.githubusercontent.com/assets/7820411/25521720/b3982b6a-2c3b-11e7-899f-a7fffa7502d1.png">

**Comment by icq4ever** [comment]
oh. I already downloaded newer version but I forgot to overwrite it. what a stupid..
thanks for point that! 

issue is closed!!
