### ISSUE TITLE
Error with processing.net.*

### ISSUE THREAD

**Issue by EventHorizon27** [processing/processing#5039]
With the example client code for processing.net.* for the client and with a modified version using variables inside a class
  `Client c;
c = new Client(this, IP, port);`
it also gives the error The constructor Client(sketch_170430a.Database, String, int) is undefined
sketch_170430a/Database.pde7:12(1, 9)

**Comment by benfry** [comment]
Please use forum.processing.org for coding questions.

**Comment by EventHorizon27** [comment]
Sorry
