### ISSUE TITLE
tint(rgb, alpha) bug

### ISSUE THREAD

**Issue by cameyo42** [processing/processing#5040]
I think this is a **tint(rgb, alpha)** error (processing 3.3.2 windows10):
The same code works well with 3.3 version.
```
PGraphics pg0;
float t0=128;

void setup() 
{
  size(200, 200);
  pg0 = createGraphics(200, 200);
  pg0.smooth();
  pg0.beginDraw();
  pg0.fill(255,0,0);
  pg0.rect(30, 30, 100, 100);
  pg0.endDraw();   
}

void draw() 
{
  background(255);
  // uncomment the following line to get NullPointeException  
  //tint(255,t0); 
  image(pg0, 0, 0);    
}

void mousePressed() 
{
  t0 = random(20, 255);
  println(t0);
}
```

**Comment by jeremydouglass** [comment]
Forum discussion: https://forum.processing.org/two/discussion/22322/transparency-on-processing-3-3-2

**Comment by benfry** [comment]
@JakubValtar regressions related to image changes?

**Comment by JakubValtar** [comment]
@benfry I reverted the change which caused the NPE.

There is however a deeper issue with how `PImage.modified` is used which I will address later. Check the PR description #5042.

**Comment by benfry** [comment]
Now fixed: Now fixed: https://github.com/processing/processing/releases/tag/processing-0260-3.3.3
