### ISSUE TITLE
random() in Eclipse

### ISSUE THREAD

**Issue by XYZ01RH** [processing/processing#5041]
random is not recognized in eclipse. I have the processing.core.* imported into my class and still the  function random doesn't work and eclipse prompts me to create the method. I am using the hermes library and working on something for a testing class I am in. Following their examples, there have been other issues but I have resolved them (mainly hard coding ints in size() and removing their constants) but this issue with random is throwing me.
Deriving their example in tutorialA here you can see the code they used to call random()

https://github.com/rdlester/hermes/blob/master/examples/tutorialA/TutorialWorld.pde

<img width="411" alt="screen shot 2017-05-01 at 6 07 25 pm" src="https://cloud.githubusercontent.com/assets/9342538/25596866/706332ee-2e99-11e7-8d7c-b85f0edd28ad.png">
<img width="548" alt="screen shot 2017-05-01 at 6 10 47 pm" src="https://cloud.githubusercontent.com/assets/9342538/25596883/8bbcb772-2e99-11e7-8903-44ab024b3226.png">

**Comment by benfry** [comment]
This isn't a Processing bug; please use forum.processing.org for coding questions.
