### ISSUE TITLE
keyPressed probem when holding

### ISSUE THREAD

**Issue by skp10** [processing/processing#5048]
When I press a key in processing by using keyPressed variable, it does go to (true) and back to (false) when I release it.
 
However, when I press a key and hold it for few sec and then release it then it does not go to (false).

`void draw() {

  if (keyPressed) {
    println(true);
  } else {
    println(false);
  }
}`

**Comment by benfry** [comment]
Use the latest version, which has a fix for this. https://github.com/processing/processing/issues/5033

**Comment by skp10** [comment]
I am using the latest version which is 3.3.3.

just add this code to processing and when you run the code, hold any key for (5 sec) and release it.
IT WOULD NOT TURN BACK TO (FALSE)

`void draw() {

  if (keyPressed) {
    println(true);
  } else {
    println(false);
  }
}`
