### ISSUE TITLE
problem when pressing and holding key

### ISSUE THREAD

**Issue by skp10** [processing/processing#5049]
I am using the latest version of processing which is 3.3.3.

just add this code to processing and when you run the code, hold any key for (5 sec) and release it.
IT WOULD NOT TURN BACK TO (FALSE)

```processing
void draw() {
  if (keyPressed) {
    println(true);
  } else {
    println(false);
  }
}
```

**Comment by benfry** [comment]
Sorry for the confusion; I'd forgotten that when a key repeats, it never sends a "key released" event, which means that if you hold a key long enough, it would cause things to stay stuck. At any rate, we now have a fix for the next release.

**Comment by hkiel** [comment]
Using 3.3.6 I see the same problem (on macOS) again.
The example code will either stay showing true, or if it shows false it will not accept any keypress for quite some time. keyReleased() is still called, but not keyPressed()

System usually recovers after some time. I one case, however, even the IDE did not respond to any key press. Operating the menus via mouse worked (mark some code and cut the selection, or quit processing)

**Comment by benfry** [comment]
You're probably running into this problem that Apple introduced in Sierra: https://github.com/processing/processing/wiki/Troubleshooting#key-repeat-on-macos-sierra
