### ISSUE TITLE
The IDE freezes when too many logging calls are issued

### ISSUE THREAD

**Issue by felixdivo** [processing/processing#5053]
When there is a script that produces too much output in the console, the IDE freezes and cannot be recovered. (maybe by waiting a long time for it to be processed)

Other IDEs prevent this behaviour by denying that log calls and displaying "to much output to process" in the corner of the logging box.

**Comment by benfry** [comment]
Already fixed for the next release (3.3.4 or 3.4) https://github.com/processing/processing/issues/4825

**Comment by felixdivo** [comment]
Okay great! Thanks.
