### ISSUE TITLE
Check visible state 

### ISSUE THREAD

**Issue by Fenestron** [processing/processing#5056]
Is it possible to check the visibility state?
For example, I have this code:
```
void draw() {
  if (!isVisible()) {
    surface.setVisible(true);
  }
}

/**
 * @return true if visible, false otherwise
 */
boolean isVisible() {
  
}
```

What should the `isVisible()` method look like?

**Comment by gohai** [comment]
@Fenestron Please make use of the Processing Forum for general questions like this.
