### ISSUE TITLE
problem with frameRate

### ISSUE THREAD

**Issue by caomingxin** [processing/processing#5058]
void setup(){
        size(300, 300, P3D);
    }

    void draw(){
        background(255);
        frameRate(180);
        translate(width / 2, height / 2);
        rotateX(radians(frameCount));
        rotateY(radians(frameCount));
        rotateZ(radians(frameCount));
        rect(0, 0, 100, 100);
    }

The exception is thrown when run Sketch after a short while

`java.lang.RuntimeException: Error making context 0x20000 current on Thread main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1-FPSAWTAnimator#00-Timer2-FPSAWTAnimator#00-Timer3-FPSAWTAnimator#00-Timer4-FPSAWTAnimator#00-Timer5-FPSAWTAnimator#00-Timer6-FPSAWTAnimator#00-Timer7-FPSAWTAnimator#00-Timer8-FPSAWTAnimator#00-Timer9-FPSAWTAnimator#00-Timer10-FPSAWTAnimator#00-Timer11-FPSAWTAnimator#00-Timer12-FPSAWTAnimator#00-Timer13-FPSAWTAnimator#00-Timer14-FPSAWTAnimator#00-Timer15-FPSAWTAnimator#00-Timer16-FPSAWTAnimator#00-Timer17-FPSAWTAnimator#00-Timer18-FPSAWTAnimator#00-Timer19-FPSAWTAnimator#00-Timer20-FPSAWTAnimator#00-Timer21-FPSAWTAnimator#00-Timer22-FPSAWTAnimator#00-Timer23-FPSAWTAnimator#00-Timer24-FPSAWTAnimator#00-Timer25-FPSAWTAnimator#00-Timer26-FPSAWTAnimator#00-Timer27-FPSAWTAnimator#00-Timer28-FPSAWTAnimator#00-Timer29-FPSAWTAnimator#00-Timer30-FPSAWTAnimator#00-Timer31-FPSAWTAnimator#00-Timer32-FPSAWTAnimator#00-Timer33-FPSAWTAnimator#00-Timer34-FPSAWTAnimator#00-Timer35-FPSAWTAnimator#00-Timer36-FPSAWTAnimator#00-Timer37-FPSAWTAnimator#00-Timer38-FPSAWTAnimator#00-Timer39-FPSAWTAnimator#00-Timer40-FPSAWTAnimator#00-Timer41-FPSAWTAnimator#00-Timer42-FPSAWTAnimator#00-Timer43-FPSAWTAnimator#00-Timer44-FPSAWTAnimator#00-Timer45-FPSAWTAnimator#00-Timer46-FPSAWTAnimator#00-Timer47-FPSAWTAnimator#00-Timer48-FPSAWTAnimator#00-Timer49-FPSAWTAnimator#00-Timer50-FPSAWTAnimator#00-Timer51-FPSAWTAnimator#00-Timer52-FPSAWTAnimator#00-Timer53-FPSAWTAnimator#00-Timer54-FPSAWTAnimator#00-Timer55-FPSAWTAnimator#00-Timer56-FPSAWTAnimator#00-Timer57-FPSAWTAnimator#00-Timer58-FPSAWTAnimator#00-Timer59-FPSAWTAnimator#00-Timer60-FPSAWTAnimator#00-Timer61-FPSAWTAnimator#00-Timer62-FPSAWTAnimator#00-Timer63-FPSAWTAnimator#00-Timer64-FPSAWTAnimator#00-Timer65-FPSAWTAnimator#00-Timer66-FPSAWTAnimator#00-Timer67-FPSAWTAnimator#00-Timer68-FPSAWTAnimator#00-Timer69-FPSAWTAnimator#00-Timer70-FPSAWTAnimator#00-Timer71-FPSAWTAnimator#00-Timer72-FPSAWTAnimator#00-Timer73-FPSAWTAnimator#00-Timer74-FPSAWTAnimator#00-Timer75-FPSAWTAnimator#00-Timer76-FPSAWTAnimator#00-Timer77-FPSAWTAnimator#00-Timer78-FPSAWTAnimator#00-Timer79-FPSAWTAnimator#00-Timer80-FPSAWTAnimator#00-Timer81-FPSAWTAnimator#00-Timer82-FPSAWTAnimator#00-Timer83-FPSAWTAnimator#00-Timer84-FPSAWTAnimator#00-Timer85-FPSAWTAnimator#00-Timer86-FPSAWTAnimator#00-Timer87-FPSAWTAnimator#00-Timer88`

**Comment by gohai** [comment]
You might want to call `frameRate` from inside `setup` - with this it doesn't cause an exception for me. (Note that frame rates above 60 Hz are probably useless, since your display will only refresh so often.)

**Comment by benfry** [comment]
@codeanticode This almost looks like the timer failing to complete and winding up calling itself recursively? (Note the error there is a single line…)
