### ISSUE TITLE
Processing build is broken at head

### ISSUE THREAD

**Issue by jdf** [processing/processing#5059]
https://travis-ci.org/jdf/processing.py/builds/230183455?utm_source=github_status&utm_medium=notification

```
compile:
  [methods] No changes to PApplet API.
    [mkdir] Created dir: /home/travis/build/jdf/processing.py/processing/core/bin
    [javac] Compiling 52 source files to /home/travis/build/jdf/processing.py/processing/core/bin
    [javac] ----------
    [javac] 1. ERROR in /home/travis/build/jdf/processing.py/processing/core/src/processing/javafx/PSurfaceFX.java (at line 249)
    [javac] 	float renderScale = Screen.getMainScreen().getRenderScale();
    [javac] 	                                           ^^^^^^^^^^^^^^
    [javac] The method getRenderScale() is undefined for the type Screen
    [javac] ----------
    [javac] 2. ERROR in /home/travis/build/jdf/processing.py/processing/core/src/processing/javafx/PSurfaceFX.java (at line 252)
    [javac] 	renderScale = Math.max(renderScale, s.getRenderScale());
    [javac] 	                                      ^^^^^^^^^^^^^^
    [javac] The method getRenderScale() is undefined for the type Screen
    [javac] ----------
    [javac] 3. ERROR in /home/travis/build/jdf/processing.py/processing/core/src/processing/javafx/PSurfaceFX.java (at line 255)
    [javac] 	float uiScale = Screen.getMainScreen().getUIScale();
    [javac] 	                                       ^^^^^^^^^^
    [javac] The method getUIScale() is undefined for the type Screen
    [javac] ----------
    [javac] 3 problems (3 errors)
BUILD FAILED
/home/travis/build/jdf/processing.py/processing/build/build.xml:303: The following error occurred while executing this line:
/home/travis/build/jdf/processing.py/processing/build/build.xml:362: The following error occurred while executing this line:
/home/travis/build/jdf/processing.py/processing/core/build.xml:57: Compile failed; see the compiler error output for details.
```

**Comment by gohai** [comment]
JDK update broke it? If I parse [this](http://stackoverflow.com/questions/35555338/get-screen-scale-in-javafx-using-only-public-api) correctly, then this might not have been part of a stable API?

**Comment by JakubValtar** [comment]
@jdf Make sure you have at least JDK 1.8.0_93. Your build uses JDK 1.8.0_31. I didn't realize this was not available before.

**Comment by jdf** [comment]
But it's the processing ant build itself that specifies the required Java version!

https://github.com/processing/processing/blob/master/build/build.xml#L73

**Comment by JakubValtar** [comment]
@jdf Right, sorry...

@benfry Can we update Java version in build.xml? Latest is `1.8.0_131-b11`, but `1.8.0_74-b02` should be enough.

Although it is not a stable API it is not going to change in Java 8 and methods to query DPI scaling are going to be a part of the stable API in Java 9 (and we'll be able to clean this DPI scaling mess a bit).

**Comment by gohai** [comment]
Wait, isn't `131` > `74`?

So looks more like the API (?) was `getScale` up until  8u60 b15, then `getRenderScale` up until recently, and now with 8u131 b11 either either something else or back to `getScale` perhaps?

**Comment by JakubValtar** [comment]
It used to be `getScale()` and then they remade DPI scaling around 8u60 and since then there is `getRenderScale()` and `getUIScale()`. Jonathan can't compile, because `build.xml` specifies 8u31 which does not have those two new methods yet. So we have to update `build.xml` to something newer than 8u60.

**Comment by gohai** [comment]
Isn't it 131?

https://github.com/processing/processing/blob/master/build/build.xml#L73

**Comment by JakubValtar** [comment]
You are right, our Java is up to date. But looking at the log linked in the original post Travis is using 8u31 anyway.
```
...

$ java -Xmx32m -version

java version "1.8.0_31"

Java(TM) SE Runtime Environment (build 1.8.0_31-b13)

Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

$ javac -J-Xmx32m -version

javac 1.8.0_31

...
```

**Comment by gohai** [comment]
Ah, that makes sense then! Believe the JDK isn't enforced on Linux - on the Pi I am also compiling with an older Java 8 build, but since we're skipping FX this problem doesn't occur.

**Comment by jdf** [comment]
I think the problem is here

  https://github.com/processing/processing/blob/master/build/build.xml#L60

where the condition isn't specific enough. The build stops with an error if you're using a version before 1.8, but should look more carefully at the JDK version in use.

**Comment by benfry** [comment]
This is the first time that it's been necessary to have a specific Java 8 build, so yes, that check isn't specific enough. 

The simple fix in the meantime is to use an up-to-date JRE to do the build. Which arguably is important anyway for security concerns. 

For the specific issue, someone can either fix the build script and submit a PR, or you're stuck waiting until I have time to do it myself.

**Comment by jdf** [comment]
For anyone who runs into this, you can force travis to update to the latest jdk8 by adding this yaml stanza to your .travis.yml file:

```yaml
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
```
