### ISSUE TITLE
Saved in a project's folder by mistake and now getting weird errors!!! BUG

### ISSUE THREAD

**Issue by Mikeryp** [processing/processing#5061]
I made a project named "PeasyCam" , and by mistake saved it in a project folder called "P3D" instead of saving it in the project folder. That started giving me an error "cannot find the constructer PeasyCam". I then moved it to project folder and reopened , but the error did not go away, and I cannot access even a single function of any imported library on a project named "PeasyCam".And the same code runs if I save the project with any other name .Please help!!!!!

**Comment by benfry** [comment]
Please use forum.processing.org for coding questions.

**Comment by Mikeryp** [comment]
this is not a coding question
