### ISSUE TITLE
File not found: PDE.properties

### ISSUE THREAD

**Issue by Knoxeus** [processing/processing#5064]
When i am not at my main computer, i cannot launch : Processing3 help me to see what's the problem.
![problem](https://cloud.githubusercontent.com/assets/28714605/26073902/235fe60a-397e-11e7-9c84-7211b50070e1.PNG)

**Comment by benfry** [comment]
Did you extract the files from the .zip archive before trying to run the software?

**Comment by benfry** [comment]
No response; closing.
