### ISSUE TITLE
./processing: 118: ./processing: java: not found

### ISSUE THREAD

**Issue by LoliLord** [processing/processing#5066]
I am new to Linux, and know almost no commands and all that. 
I am kinda experienced with processing, and while installing it on Ubuntu, this error came up when trying to run the actual program.

Is this just a matter of not being able to find processing-java, or something entirely different?
Either way, help would be much appreciated.

**Comment by gohai** [comment]
How did you install Processing on Ubuntu? Downloaded versions from processing.org come with a local copy of the Java Runtime, so you should really have a `java` binary available here.

**Comment by benfry** [comment]
No response; closing.
