### ISSUE TITLE
“DPI detection failed, fallback to 96 dpi” message showing up

### ISSUE THREAD

**Issue by cameyo42** [processing/processing#5067]
With processing 3.3.3 and Windows 10 i got the following message when run a sketch from an external editor (notepad++ or VS Code):
**DPI detection failed, fallback to 96 dpi.**
Then, the sketch run normally.
I have found the output string within: _WindowsPlatform.java_

**Comment by benfry** [comment]
That can be ignored… It's related to a feature that's in-progress (sketch scaling to the machine's DPI) but hasn't been finished yet.
