### ISSUE TITLE
Nothing draws until draw function ends

### ISSUE THREAD

**Issue by Error1000** [processing/processing#5069]
Nothing draws until draw function ends,for example if we have the sketch:
void setup(){
 size(400,400);
}

void draw(){
 fill(0);
 ellipse(width/2,height/2,20,20); 
  
  try{
    Thread.sleep(10000);
  }catch(Exception e){
  e.printStackTrace();
  }
  
  exit();
}

This sketch will draw nothing on the screen even though we have ellipse();

![capture1](https://cloud.githubusercontent.com/assets/15368037/26145608/b5ac01c4-3af5-11e7-8bcd-d675e45cd901.PNG)

and if we just change it so that it will go through 1 cycle before stopping, it will work:

int x= 0;
void setup(){
 size(400,400);
}

void draw(){
 fill(0);
 ellipse(width/2,height/2,20,20); 
 
  if(x == 1){

 try{
  Thread.sleep(10000);
  }catch(Exception e){
  e.printStackTrace();
  }
  
  exit();
  
}
 
   x++;
}

![capture1](https://cloud.githubusercontent.com/assets/15368037/26145647/dad8728e-3af5-11e7-85c6-d5de8394e994.PNG)

Oh and it will also draw if you minimize the window and maximize it back again without going through the draw cycle once.

So why is that why is it not rendering the circle.

**Comment by jeremydouglass** [comment]
Your title is a literal description of how draw() is designed to work. If you look it up in the reference:

> All Processing programs update the screen at the end of draw(), never earlier. https://processing.org/reference/draw_.html

If your frameRate is 60fps, draw attempts to return about 60 times a second. The screen when it returns. If you are trying to do timed events, don't put delays in draw. Use millis().

Further discussion should be programming questions on the processing forum: https://forum.processing.org/two/discussions

**Comment by Error1000** [comment]
thanks

**Comment by jeremydouglass** [comment]
No problem -- see you on the forum if you have questions!
