### ISSUE TITLE
Processing 3.3.3 on Linux: keyCode == ENTER not working

### ISSUE THREAD

**Issue by toliaferrode** [processing/processing#5070]
I'm doing a simple test with keyboard input. Entering keys and having them print to the screen. 

Doing a test with the ENTER key, I've got this going:

```
void keyReleased() {
  if(key == CODED) {
    if(keyCode == ENTER)
      println("Hello.");
  }
}
```

The previous code does nothing. Moreover if you press ENTER Processing stops receiving input altogether.

**Comment by gohai** [comment]
Does it work with `keyCode == RETURN`?

**Comment by gohai** [comment]
Also, are you using the default or the P2D/P3D renderer?

**Comment by toliaferrode** [comment]
@gohai Hi, I'm using the default renderer. I tried RETURN as well and it didn't work.

**Comment by gohai** [comment]
@toliaferrode Thanks for clarifying!

What do you get when you `println((int)key)` and `println(keyCode)`? Does the function even get called with Enter?

And what if you try `keyPressed` instead of `keyReleased`?

**Comment by toliaferrode** [comment]
@gohai No problem!

Nothing happens when I tried all 3. I even tried to println() with both keyPressed and keyReleased.

**Comment by benfry** [comment]
What happens with this? I don't think `ENTER` is coded.
```
void keyReleased() {
    if (key == ENTER)
      println("Hello.");
}
```

**Comment by toliaferrode** [comment]
@benfry Wow, I can't believe I'm on with Ben Fry. I bow to you, sir.

Nope, still nothing happens.

**Comment by REAS** [comment]
You need to have a `draw()` in the program to keep it running to get key events. Without a draw, the code doesn't run continuously.

**Comment by toliaferrode** [comment]
@REAS Hi Casey. it's an honor. Actually even though I didn't post the whole thing, in my original code I had both setup() and draw(). Sorry for the miscommunication. I was just getting to grips with posting code to a Github issue.

**Comment by gohai** [comment]
@toliaferrode AFAICS Enter and Return are not meant to be coded:

_The variable keyCode is used to detect special keys such as the arrow keys (UP, DOWN, LEFT, and RIGHT) as well as ALT, CONTROL, and SHIFT.  (...) The keys included in the ASCII specification (BACKSPACE, TAB, ENTER, RETURN, ESC, and DELETE) do not require checking to see if the key is coded_

**Comment by toliaferrode** [comment]
@gohai Ah, this clears everything up. Thanks so much.

And thanks to all for helping me understand. I'll be more thorough in my reading of the docs in the future.
