### ISSUE TITLE
Serial.readBytesUntil hangs forever on Windows

### ISSUE THREAD

**Issue by thanhvu94** [processing/processing#5072]
I execute this code to get serial data from Arduino DUE (2 float data for X and Y position) and publish it on Processing which will move the circle according to the change in X and Y data. However, everything works fine up to 2 minutes and then the circle just stops moving. The "Run" button is still highlighted at that time. I have to stop and run Processing again, which is very annoying. I guess my code doesn't have any problem, but I just cannot figure out why this is happening.

Here is my code:

```
// import libraries
import java.awt.Frame;
import java.awt.BorderLayout;
import processing.serial.*;
 
// Serial port to connect to
String serialPortName = "COM3";
float xf;
float yf;
// SETTINGS END
 
Serial serialPort; // Serial port object
 
void setup() {
  size(900,900);
  background(51);
  noStroke();
  //frameRate(100);
  serialPort = new Serial(this, serialPortName, 9600); 
}
 
void draw() {
  if (serialPort.available() > 0) {
    byte[] inBuffer = new byte[30]; // holds serial message
    serialPort.readBytesUntil(ENTER,inBuffer);
    if (inBuffer == null) {
      return;
    }
 
    String myString = new String(inBuffer);
    String[] nums = split(myString, ' ');
 
    if (nums.length == 2) {
      xf = float(nums[0]);    //Position X
      yf = float(nums[1]);    //Position Y
    }
 
    background(51);
    float x_m = map(xf,-0.4,0.4,0,800);
    float y_m = map(yf,-0.4,0.4,0,800);
    ellipse(x_m,y_m,50,50);
  }
}
```

**Comment by gohai** [comment]
@thanhvu94 Attempt to figure out where your code is hanging by adding `println` calls to it. The obvious places would be before and after `serialPort.available()` and before and after `serialPort.readBytesUntil()`.

Note: the check for `inBuffer` to be `null` is not correct, since `readBytesUntil` won't modify inBuffer in the event no newline character has been found. Instead, it will _return_ 0.

**Comment by gohai** [comment]
Not enough information from the reporter to further debug this, unfortunately.
