### ISSUE TITLE
getting fragment shader error of void 

### ISSUE THREAD

**Issue by shirish47** [processing/processing#5079]
`PShader pointShader;
float weight = 40;
 
void setup() {
 
    size(600, 600, P3D);
 
    String[] vertSource = new String[] {
        "#version 330",
        "#define PROCESSING_POINT_SHADER",
        "uniform mat4 projection;",
        "uniform mat4 modelview;",
        "uniform float weight;",
        "in vec4 position;",
        "in vec4 color;",
        "in vec2 offset;",
        "out vec4 vertColor;",
        "out vec2 texCoord;",
        "void main() {",
            "vec4 pos = modelview * position;",
            "vec4 clip = projection * pos;",
            "gl_Position = clip + projection * vec4(offset, 0, 0);",
            "texCoord = (vec2(0.5) + offset / weight);",
            "vertColor = color;",
        "}"
    };
    String[] fragSource = new String[] {
        "#version 330",
        "#ifdef GL_ES",
        "precision mediump float;",
        "precision mediump int;",
        "#endif",
        "uniform sampler2D sprite;",
        "out vec4 vertColor;",
        "out vec2 texCoord;",
        "out vec4 FragColor",
        "void main() {",
            "FragColor = texture2D(sprite, texCoord) * vertColor;",
        "}"
    };
 
    pointShader = new PShader(this, vertSource, fragSource);
    pointShader.set("weight", weight);
    pointShader.set("sprite", loadImage("particle.png"));
 
    strokeWeight(weight);
    strokeCap(SQUARE);
 
}
 
void draw() {
 
    background(#000000);
 
    shader(pointShader, POINTS);
    blendMode(ADD);
    hint(DISABLE_DEPTH_TEST);
 
    translate(width / 2, height / 2);
    rotate(frameCount * 0.001, 1.0, 0.75, 0.5);
    scale(40.0);
 
    float offset = frameCount * 0.001;
    for(int x = -14; x < 15; x += 2)
        for(int y = -14; y < 15; y += 2)
            for(int z = -14; z < 15; z += 2) {
                stroke(noise(offset + x * 0.2) * 255, noise(offset + y * 0.2) * 255, noise(offset + z * 0.2) * 255, 127);
                point(x, y, z);
            }
 
}`

now the error shows 
`cannot compile fragment shader :ERROR: 0:10: 'void' : syntax error: syntax error` whats the problem ?

**Comment by shirish47** [comment]
sorry my mistake just missed a ; at out vec4 FragColor declaration but now showing error for texture2D undeclared identifier..

**Comment by shirish47** [comment]
also got this its now changed to texture from texture2D

**Comment by shirish47** [comment]
lots of things I did not understand about processing. for some codes I have seen there is no need to mention version for glsl while for this code processing asks for version also gl_FragColor gives error. I have to define and out variable for it. here is the code that compiles and runs but I don't see any output... I have taken it from processing forum [here](https://forum.processing.org/two/discussion/3847/#Comment_12836)
 `PShader pointShader;
float weight = 40;
 
void setup() {
 
    size(600, 600, P3D);
 
    String[] vertSource = new String[] {
         "#version 330",
        "#define PROCESSING_POINT_SHADER",
        "uniform mat4 projection;",
        "uniform mat4 modelview;",
        "uniform float weight;",
        "in vec4 vertex;",
        "in vec4 color;",
        "in vec2 offset;",
        "out vec4 vertColor;",
        "out vec2 texCoord;",
        "void main() {",
            "vec4 pos = modelview * vertex;",
            "vec4 clip = projection * pos;",
            "gl_Position = clip + projection * vec4(offset, 0, 0);",
            "texCoord = (vec2(0.5) + offset / weight);",
            "vertColor = color;",
        "}"
    };
    String[] fragSource = new String[] {
        "#version 330",
        "#ifdef GL_ES",
        "precision mediump float;",
        "precision mediump int;",
        "#endif",
        "uniform sampler2D sprite;",
        "out vec4 vertColor;",
        "out vec2 texCoord;",
        "out vec4 FragColor;",
        "void main() {",
            "FragColor = texture(sprite, texCoord) ;",
        "}"
    };
 
    pointShader = new PShader(this, vertSource, fragSource);
    pointShader.set("weight", weight);
    pointShader.set("sprite", loadImage("particle.png"));
 
    strokeWeight(weight);
    strokeCap(SQUARE);
 
}
 
void draw() {
 
    background(#000000);
 
    shader(pointShader, POINTS);
    blendMode(ADD);
    hint(DISABLE_DEPTH_TEST);
 
    translate(width / 2, height / 2);
    rotate(frameCount * 0.001, 1.0, 0.75, 0.5);
    scale(40.0);
 
    float offset = frameCount * 0.001;
    for(int x = -14; x < 15; x += 2)
        for(int y = -14; y < 15; y += 2)
            for(int z = -14; z < 15; z += 2) {
                stroke(noise(offset + x * 0.2) * 255, noise(offset + y * 0.2) * 255, noise(offset + z * 0.2) * 255, 127);
                point(x, y, z);
            }
 
}`

**Comment by benfry** [comment]
Please use https://forum.processing.org for coding questions.

**Comment by shirish47** [comment]
that does not work for me I tried it .. it does says invalid email . I tried contacting mail@florianjenett.de but got no response.
