### ISSUE TITLE
PROCESSING - how to LAY LIVE WEBCAM ON TOP OF EACH OTHER? :)

### ISSUE THREAD

**Issue by nicolejansen** [processing/processing#5083]
# Hola! I'm writing this code with my webcam, and want to lay video's on top of another, so it looks like their blended. I'm trying to lay a video on top of a live webcam video, so you will see the contents of the video happening over yourself. I Hope you can help me, its for my graduation project...

// Example 16-12: Simple background removal

// Click the mouse to memorize a current background image
import processing.video.*;
import gab.opencv.*;

// Variable for capture device
Capture video;
OpenCV opencv;

// Saved background
PImage backgroundImage;

// How different must a pixel be to be a foreground pixel
float threshold = 20;

void setup() {
  String[] cameras = Capture.list();
  //printArray(cameras);
  size(1280, 720);
  //video.width = 1280;
  //video.height = 720;
  video = new Capture(this, 1280, 720, cameras[76]);

  video.start();

  opencv = new OpenCV(this, 1280, 720);
  opencv.startBackgroundSubtraction(5, 3, 0.5);
  
  // Create an empty image the same size as the video
  backgroundImage = createImage(video.width, video.height, RGB);
  
}

void captureEvent(Capture video) {
  // Read image from the camera
  video.read();
}

void draw() {
  if (video.available() == true) {
    video.read();
  }
  image(video, 0, 0);
  
  opencv.loadImage(video);
  
  opencv.updateBackground();
  
  opencv.dilate();
  opencv.erode();

  noFill();
  stroke(255, 0, 0);
  strokeWeight(3);
  for (Contour contour : opencv.findContours()) {
    contour.draw();
  }
}

void mousePressed() {

}

**Comment by benfry** [comment]
Please use forum.processing.org for coding questions.
