### ISSUE TITLE
new user! installed processing 3.3.3, tried to run the example- continuouslines. No output screen is appearing!!!

### ISSUE THREAD

**Issue by NOOBIE140614** [processing/processing#5085]
pleasw help i am very interested in learning processing i watched many tutorials but after installing processing couldnt run it .

i tied running on my friends laptop with the same setup and it worked for him.
and in both-mine as well as his, case their was an error --

May 23, 2017 6:42:07 PM com.google.classpath.JARClassPath loadEntries
WARNING: Failed to read Jar file C:\Users\Mr Z\Desktop\processing-3.3.3\modes\java\libraries\pdf\library\itext.jar

inspite of this the example worked well in his laptop.

pleeeeeeeease helppppppp!!!!

**Comment by hamoid** [comment]
Mayb try having processing in a path without spaces? "Mr Z" has a space, and some programs don't like them :)

**Comment by NOOBIE140614** [comment]
no success!!   ;(  ;(

May 24, 2017 6:33:59 AM com.google.classpath.JARClassPath loadEntries
WARNING: Failed to read Jar file C:\backup\processing-3.3.3\modes\java\libraries\pdf\library\itext.jar

**Comment by NOOBIE140614** [comment]
I think it doesn't matter because the same error was showing in my firends laptop but it worked for him!!!!!!

**Comment by hamoid** [comment]
To verify, you're trying to run this program:

```java
void setup() {
  size(640, 360);
  background(102);
}

void draw() {
  stroke(255);
  if (mousePressed == true) {
    line(mouseX, mouseY, pmouseX, pmouseY);
  }
}
```

Then click and drag the mouse, and nothing happens, right?

**Comment by NOOBIE140614** [comment]
yes!!!
After loading the above code from >files>examples , I click run and nothing happens!!!!

**Comment by gohai** [comment]
@NOOBIE140614 Are you running a 32-bit or 64-bit version of Windows? Care to re-download the matching version of Processing, and to try to unzip it again to a similar location (without the space in the path)?

**Comment by NOOBIE140614** [comment]
now the error is not showing!!

but still the example didn't work ---no output screen is showing after running code!!!!

**Comment by NOOBIE140614** [comment]
is their any other way of running my processing codes---like running in java net bean or something !!!

**Comment by gohai** [comment]
@NOOBIE140614 Can you post your hosts file? This shows how this is done on Windows: https://support.rackspace.com/how-to/modify-your-hosts-file/

**Comment by NOOBIE140614** [comment]
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost

**Comment by NOOBIE140614** [comment]
thanks a lot guys, really !!!

it worked -----actually i was using proxifier,
because you mentioned DNS host
 I tried after closing proxifier and it worked !!

also can you explain what was happening because it didnt came to me earlier ?? 
thanks again otherwise

**Comment by gohai** [comment]
Your "proxifyer" seems to have issues with computer-internal network connections, such as used by Processing.

**Comment by NOOBIE140614** [comment]
thanks!!
