### ISSUE TITLE
Unspecified Loop Exception Causes Crash During Many Iterations

### ISSUE THREAD

**Issue by bksugiyama** [processing/processing#5086]
I cloned [Dr. Brent Werness'](https://bitbucket.org/BWerness/) Voxel Automata Terrain sketch [here](https://bitbucket.org/bksugiyama/voxel-automata-terrain), adding a method to print voxel coordinate data to an output file by pressing 'f' while randomly generated terrain is loaded and displayed in the viewfinder.

The triple-nested _for_ loop that handles coordinate output printing hangs after a certain number of iterations, sometimes in different places depending on the number of chars printed. I originally thought it might be a heap-space problem, but increasing the memory available to Processing did not fix the issue.

Thorough testing in processing did not elucidate the cause for this problem. Adding a _try-catch_ in Processing around the loops was not fruitful, the loop did not appear to terminate so no exception was thrown.

A bit stumped, I used [this method at stack exchange](https://stackoverflow.com/a/25577198/8022745) to port the project into eclipse IDE where it compiled, ran, and produced the expected output with no issues! So this is seemingly a bug with Processing, but I wasn't able to glean very much useful information on _why_ this is occurring. Feel free to ask me questions, I hope this turns out to be useful.

Cheers!
(MacOS 10.12.4, Processing 3.3.3-0260, MBP2016-15", 16 GB 2133 MHz LPDDR3)

**Comment by gohai** [comment]
@bksugiyama What's exactly being done inside the loop? Could you perhaps post this snippet (or pseudocode even)?

**Comment by bksugiyama** [comment]
Certainly!

```
//Instance of PrintWriter
PrintWriter output;

//This func() iterates through every state in the world (volume K^3) and, if the state is populated,
//(ie state[x][y][z] != 0) prints the xyz coordinates and state number (1 or 2). K-k is a term used
//to invert the z-axis
void fileOut() {
  output = createWriter("threestate" + int(random(100)) + ".txt");

  for ( int i = 0; i < K; i++) {
    for ( int j = 0; j < K; j++) {
      for ( int k = 0; k < K; k++) {
        if (state[i][j][k] != 0) {
          output.println(i + " " + j + " " + (K-k) + " " + state[i][j][k]);
        }
      }
    }
  }
  //Flush the write buffer here
  output.flush();
}
```

For reference, K, a thee dimensional array in which each element represent a unit cube (voxel):
`int[][][] state = new int[K][K][K]`

whether using:
`output.println(i + " " + j + " " + (K-k) + " " + state[i][j][k]);`

as in the actual code snippet above, or using:
`println(i + " " + j + " " + (K-k) + " " + state[i][j][k]);`

the data written is truncated. It wasn't until after I tried the latter though that I realised the loop was actually crashing Processing, hanging around i == 20 for the randomly generated model I was using to test.

**Comment by benfry** [comment]
Probably this problem: https://github.com/processing/processing/issues/5053

**Comment by bksugiyama** [comment]
Seems likely these issues are related, but this is curious: When writing to the output file, rather than Processing's console, the output is still truncated but Processing _doesn't hang_. Perhaps it has to do with a Processing-system I/O interaction?

What was the nature of the fix for issue #5053, Ben? And if possible, can you try compiling this sketch on that build and seeing if the same behaviour manifests?

**Comment by gohai** [comment]
@bksugiyama Building Processing from git is actually surprisingly painless, if you want to try: https://github.com/processing/processing/wiki/Build-Instructions

(Really just installing Oracle JDK 8u131, `brew install ant`, checking out the repo, `cd build && ant run`.)

**Comment by bksugiyama** [comment]
Oh sweet, I will give that a shot! Thanks for the heads up @gohai , also your name reminds me of ５杯 which can mean five glasses of beer in Japanese 😄

**Comment by JakubValtar** [comment]
@bksugiyama Logging to console should be fixed, and I think logging to file will be fixed if you add `output.close();`

**Comment by benfry** [comment]
Should be fixed in current releases (via https://github.com/processing/processing/commit/672a01ff5c5a1eebba4deb70b316f23fac32b9e8)
