### ISSUE TITLE
Key presses sometimes not registered with keyPressed()

### ISSUE THREAD

**Issue by hoganavery49** [processing/processing#5087]
In certain projects in which keyPressed is used, pressing multiple keys at once will stop keyPressed() from being called (as far as I can tell). For example, in one project I am registering key presses for movement of a character and have a println() in keyPressed() and in keyReleased() that just print "Pressed" or "Released" respectively. Pressed will stop being printed when multiple keys are pressed, but released will not. The weird thing is that presses are still registered for the control, option, command, shift, and function keys, and that this bug does not occur in another project of mine which uses the same movement system. The operating system that this is happening on is macOS Sierra 10.12.3, with a standard Apple (?) keyboard. I will try to reproduce the bug on my Windows 10 machine at home later today. Attached are the two projects I talked about, with SlimeSetup being the one that bugs and CrabCharacter being the one that works as intended.

Update: I've run the code on my Windows desktop and I can't reproduce the issue. Maybe it's a problem with macOS or the school iMac I've been using.
[SlimeSetup.zip](https://github.com/processing/processing/files/1023752/SlimeSetup.zip)
[CrabCharacter.zip](https://github.com/processing/processing/files/1023753/CrabCharacter.zip)

**Comment by gohai** [comment]
@hoganavery49 Thank you, this is a known bug (#5049) and a fix for it is queued for a future release of Processing.

**Comment by benfry** [comment]
This is probably this macOS Sierra problem: https://github.com/processing/processing/issues/4952
