### ISSUE TITLE
cannot find build.xml

### ISSUE THREAD

**Issue by MasterYushi** [processing/processing#5088]
I was having problems with the *automatic sdk download* options so I decided to install the whole Android Studio, which places the SDK in `C:\Android\sdk` which I assigned as the sdk directory when prompted by processing, but when I try to run a sketch I get the following error:

![image](https://cloud.githubusercontent.com/assets/24858182/26403331/7caf6d96-40ab-11e7-8109-8f553646f8cd.png)

>     [mkdir] Created dir: C:\Users\MASTER~1\AppData\Local\Temp\android4120630829030815330sketch\bin
>[echo] org.eclipse.jdt.core.JDTCompilerAdapter
BUILD FAILED
C:\Users\MASTER\~1\AppData\Local\Temp\android4120630829030815330sketch\build.xml:81: Cannot find C:\Android\sdk\tools\ant\build.xml imported from C:\Users\MASTER~1\AppData\Local\Temp\android4120630829030815330sketch\build.xml
Total time: 0 seconds

**Comment by gohai** [comment]
Android issues should go here instead: https://github.com/processing/processing-android
