### ISSUE TITLE
PFont Class Doesn't Exist

### ISSUE THREAD

**Issue by relddir123** [processing/processing#5090]
Okay, this sounds really weird, but let me start off by saying that this is in Android mode only. Whenever I try to use PFont in Android mode, I get the error saying "The class 'PFont' does not exist." I don't understand what's happening here. I could be missing something, but every tutorial I have seen uses PFont like I do (code below) without any errors whatsoever.

```
PFont font;

void setup() {
  font = createFont("Arial Bold", 32);
}
```

There is of course more to the code, but I feel like you don't need to know about stuff not related to the text. If you need the full code, please tell me!

**Comment by gohai** [comment]
Thanks @relddir123. Since this is an Android mode issue, you might want to file this here: https://github.com/processing/processing-android

**Comment by relddir123** [comment]
Thank you for the tip!
