### ISSUE TITLE
It says a serious problem happened during startup. Please report.............

### ISSUE THREAD

**Issue by robinsidhu** [processing/processing#5095]
<img width="307" alt="capture" src="https://cloud.githubusercontent.com/assets/29007082/26524770/4d43db92-42f3-11e7-8e3d-9c4576ce9e71.PNG">

**Comment by gohai** [comment]
@robinsidhu To which folder did you unzip Processing to?

Are you running a 64- or 32-bit version of Windows? Which version of Processing are you trying this with?

**Comment by robinsidhu** [comment]
64

**Comment by gohai** [comment]
@robinsidhu Which folder did you unzip Processing to?

**Comment by benfry** [comment]
And are you using the latest release?

**Comment by benfry** [comment]
No response; closing.
