### ISSUE TITLE
add menu mnemonics for editor

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#51]
_Original author: b...@processing.org (June 06, 2010 23:45:19)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=26

Comment from fry, 2005-05-12 20:15

add mnemonics for menus (i.e. alt-f to open 'file')

_Original issue: http://code.google.com/p/processing/issues/detail?id=12_

**Comment by javadba** [comment]
Is there a version with mnemonics on Mac - or is it possible to hack it to do so?  I know of at least one major software that it is possible. I DETEST the lack of mnemonics on mac and came to this page solely for searching for that support.

**Comment by GKFX** [comment]
@javadba You can delete all the if-statements about Mac from Toolkit.java that got introduced in #2382. That should mean the code runs, at least.

**Comment by javadba** [comment]
Ah great - just what I was looking for.
