### ISSUE TITLE
Maximum tabs possible in Processing

### ISSUE THREAD

**Issue by JoseAparecido** [processing/processing#5102]
Hello guys,

Does anyone know the maximum number of tabs you can use the Processing?

As mention before, we are developing an application where we add the options (more animations, games and other activities), in separate tab ...

Which arrived at 32, is not accepting more ... this would be (32) the maximum possible number of tabs?

Note: We are using the Processing 2.2.1

Below the link about a discussion at some time ...
https://forum.processing.org/two/discussion/17598/maximum-tabs-possible-in-processing

Thank you very much

**Comment by GKFX** [comment]
I can't reproduce a limit of 32 on Processing 3.

**Comment by JoseAparecido** [comment]
Hi, thanks for the feedback ...

So, in fact I need to increase the amount of tabs, due to the need to extend the project, I still use Processing 2.2.1 for this case because I use some libraries, which needs to change a lot if I update the version, so this is A job we intend to do in the future.

For now we have the need to increase the amount of tabs in the Project, if it is possible only from Processing 3, that's fine, so we have to update as soon as possible.

But from what I understand, even in Processing 3 this is not possible ... that's right, would not it be possible to add more than 32 tabs in the Project?

Sorry for English, I'm from Brazil, and I write like Google Translate.

Thank you very much for the attention.

**Comment by GKFX** [comment]
No, you can get more than 32 tabs in Processing 3. It worked on my computer. Also, I tried to get more than 32 tabs in Processing 2.2.1 and what eventually happened (after about 37) was that the tab menu button got covered by the tabs. Is that the problem you had?

In Processing 3 that doesn't happen any more, but the drop-down menu does get so long that it doesn't fit on the screen (after about 45 tabs), and on Linux at least it won't scroll. If your project is too complex for the Processing editor, and you don't want to upgrade, I would suggest that you either:
* Use Processing in Eclipse, or with `javac` directly. You can ask for help with that on the forum.
* or edit the files by hand in another editor, then only open the Processing editor to run the program.

**Comment by StanLepunK** [comment]
You can also use Sublim Text like Processing. It's very easy to use. A The part little tricky, is install P5 via Processing-Java, but after it's very cool !
http://www.sublimetext.com/
https://github.com/b-g/processing-sublime

**Comment by JoseAparecido** [comment]
Hello guys,

Thanks for the feedback...

For you to understand what is happening, when I try to create a new tab, when I type the name, and select OK, nothing happens (as if it were locked)

Thanks for the suggestions, I had already taken a look at how to use it in Eclipse, I have some doubts about exporting the application (by Eclpse), to create the executable for other machines, but I will research about it.

I found the hint interesting to open in another editor, even if the new tab does not appear, which would compile normal with the others, I will do tests ...

As for the tip of StanLepunK, I'll take a look too, thanks guys!

In the project we intend to always make updates, which eventually are additional programs, that for better organization, it would be better to stay on separate tabs ...

Thanks a lot for the help.

**Comment by benfry** [comment]
There's no limit to the number of tabs; but we recommend using another editor or a full IDE if you need more than ~5 of them.

**Comment by JoseAparecido** [comment]
Okay, thank you folks!

I'm doing tests in Eclipse, I'm following the steps quoted in this link ...
https://processing.org/tutorials/eclipse/

Now I need the next step which is to create a Menus home screen (only buttons to access the Project options), and use additional libraries in Eclipse, such as ControlP5, and Minim, etc ... we also use LeapMotion, which is A device used in the Project, I will continue the tests, and in case I need to ask for your help again.

Thank you all for your attention.

**Comment by GKFX** [comment]
Please use the forum at https://forum.processing.org/two/ or StackOverflow. This page is only for discussing Processing bugs. Thanks!
