### ISSUE TITLE
keyPressed gets stuck as true when keys are pressed for a longer period

### ISSUE THREAD

**Issue by epar** [processing/processing#5104]
Using

```
void draw() {
  println( keyPressed );  
}
```

When pressing a key for a short period it works as expected, when holding a key down a little longer keyPressed gets stuck as true.

Same issue as [#5033](https://github.com/processing/processing/issues/5033)

Not fixed in 3.3.3 though. On macOS Sierra 10.12.4

**Comment by JakubValtar** [comment]
This is fixed in #5049 and will be released in 3.3.4 or 3.4.
