### ISSUE TITLE
Console window losing text

### ISSUE THREAD

**Issue by GenJamGuy** [processing/processing#5110]
I just installed Processing, version 3.3.4 on a Mac (OS 10.12.5).  The Console window displays only the most recently generated line or two of text, and there is no scroll bar.  For example, this program:

    void setup() {
    }
    void draw() {
      println("In draw " + frameCount);
    }

displays only the last two lines of text, regardless of how big the Console window is, and there is no scroll bar in the Console window. Doing Edit->Select All from the Console window only selects what is visible (not surprisingly).

**Comment by tolkanabroski** [comment]
I confirm
Processing version 3.3.4 Windows 10 64bit

Recompiled my own version of Processing from source 4 Weeks ago, i I thought, i did something wrong. Now with the official release, i see, - it is broken.

**Comment by benfry** [comment]
Bummer; this is a regression from trying to fix https://github.com/processing/processing/issues/4825… It should be keeping several thousand characters or a few hundred lines, whichever comes first.

**Comment by J-M-L** [comment]
Same here indeed -  OS 10.12.5, Processing 3.3.4, Java 8 update 131 (build 1.8.0_131-b11)

**Comment by StanLepunK** [comment]
`println`, work fine on Sublim Text.

**Comment by luistoledo** [comment]
I increased the `console.lines` property in preferences.txt

It was set on 2, changed it to 500, and now console shows (500) the proper output.

(@benfry I guess some systems doesn't update the property from #4825)

**Comment by GenJamGuy** [comment]
That fixed it for me too.  Thanks!

**Comment by jeremydouglass** [comment]
Increasing the `console.lines` setting in `preferences.txt` worked for me as well.

**Comment by benfry** [comment]
Thanks for the update @luistoledo, that at least tells me where the problem is. Probably just a typo that it's using the variable that refers to the height of the console (in lines) instead of the number of lines to *save* in the console.

**Comment by tolkanabroski** [comment]
Nice, this workaround seems to to fix the issue! 

and my personal opinion: a tutorial how to read and write to a tmp file would fix https://github.com/processing/processing/issues/4825 too.

**Comment by Geoffree3** [comment]
Increasing the console.lines setting works.  But had to edit preferences.old as well as preferences.txt.
