### ISSUE TITLE
[Suggestion] image() consuming too many resources, and frameRate dropped

### ISSUE THREAD

**Issue by davidhcefx** [processing/processing#5114]
## Description:
The five-parameter function of image(), `image(img, a, b, c, d)`, will be a huge resource sink, **when the PImage to be loaded has a different size than (c, d)**.
This issue might due to the fact that Processing needs to RESIZE the image, and thus results in a very 
low frameRate. (frame rate dropped from 60 to 8 !)

## Suggestion:
Although this is not a problem of Processing, I suggest Processing.org to include a little more description of this RESIZING functionality in the [Processing Reference](https://processing.org/reference/image_.html) ! So that others using it would have more details, and hopefully, would eventually avoid possible tragedies!

**Comment by gohai** [comment]
I'd imagine that the speed of `image()` greatly depends on the renderer being used, so adding those warning to the general description of the function might be undue.

If you care strongly about this you might want to open an issue in https://github.com/processing/processing-docs, where documentation-related bugs would go.

**Comment by benfry** [comment]
There's no such resizing of the image data itself, so nothing to document. Performance will vary across renderers, as @gohai points out, but the differences in speed aren't in the Processing code, it's in the code we rely on from Java and the OS.
