### ISSUE TITLE
Processing 3.3.4 on Windows 10 errors while unzipping file.

### ISSUE THREAD

**Issue by archalien** [processing/processing#5117]
After unzipping the file from processing.org for version 3.3.4 it returned with these errors. 
![processing error](https://user-images.githubusercontent.com/22973817/26898523-51e860aa-4b9a-11e7-883d-d2e734410ab4.JPG) .
 I still tried to run the program after it was done and got this message. At the end it says 16 more problems but I cannot expand that at all.  
![processing error 2](https://user-images.githubusercontent.com/22973817/26898646-b2834dee-4b9a-11e7-8bc6-953cfbe13f7a.JPG)

FYI : I can run version 3.3.3 just fine. Thanks for the help in advance.

**Comment by gohai** [comment]
Have you tried clearing your browser's cache and re-downloading the ZIP file?

**Comment by archalien** [comment]
I cleared my cash a few times a day, but did and tried again. Fully downloaded in chrome and while unzipping gave me the same errors. I tried the opera browser and it stopped at 75% for about 5 minutes and then gave me a download error. Tried again, same thing. Here is a pic at 75% right before download error.
![processing_again](https://user-images.githubusercontent.com/22973817/26911400-237c9fc4-4bdb-11e7-845c-9d8313bc611d.JPG)

**Comment by JakubValtar** [comment]
I've just downloaded 3.3.4 win64 version in Firefox and it works for me without a problem. It's probably some temporary problem with amazon web services or internet in general in your location. Please let us know if you managed to resolve the problem.

**Comment by archalien** [comment]
I just tried Firefox and Chrome, both downloaded just fine now. Unzip went well, and Processing 3.3.4 runs. Thanks for the comments and help.
