### ISSUE TITLE
Screen Interface is a Retina Burner!!

### ISSUE THREAD

**Issue by Ishibashi108103** [processing/processing#5120]
I LOVE the Processing application and how easy it makes it to program large projects. However when I stay up late programming the white screen burns my eyes. Being able to toggle the interface color from black to white would greatly increase the value of Processing in my eyes.
P.S. If this problem isn't fixed soon I wont have any eyes for Processing to be great in!!

**Comment by jeremydouglass** [comment]
Ishibashi108103 --

Also keep in mind that on OS X, System Preferences > Accessibility > Display > Invert Color will take a bright desktop and make dark -- including every white-page application (browsers, notepads, Processing, etc.).

I believe that Windows has a similar feature.

**Comment by hamoid** [comment]
https://github.com/jeffThompson/DarkProcessingTheme_2.0

**Comment by benfry** [comment]
Perhaps someone could add a wiki page (or FAQ entry) for this? https://github.com/processing/processing/wiki

**Comment by jeremydouglass** [comment]
Draft wiki page --

https://github.com/processing/processing/wiki/Dark-Theme-for-PDE

**Comment by benfry** [comment]
Cool, thanks so much.
