### ISSUE TITLE
Feature request: Linux native file choosers

### ISSUE THREAD

**Issue by GKFX** [processing/processing#5122]
Linux native file dialogs are currently disabled by default. As I understand it, this was because they weren't very nice a few years back and so the JFileChooser was a safer choice. However, Linux has moved on, and they now look very nice, 
![screenshot from 2017-06-10 18-13-27](https://user-images.githubusercontent.com/5357642/27004835-9909e4a2-4e08-11e7-9c37-7b4283dbc9f5.png)
certainly much better than JFileChooser, which has layout issues, crude folder navigation, no access to user's favorite/often used folders, and so on.
![screenshot from 2017-06-10 18-15-39](https://user-images.githubusercontent.com/5357642/27004842-d8b28a46-4e08-11e7-9e9c-5920dc3846af.png)

So please can you change the Linux default?

**Comment by GKFX** [comment]
To confirm, this is the result of changing just the preference, with no other tinkering, on GNOME 3 on Debian.

**Comment by benfry** [comment]
I'll have to take your word for it, but will change the default to use the native chooser.

For current installations, change `chooser.files.native` in `preferences.txt`.

**Comment by hamoid** [comment]
I'm happy about this change. The native one is much more usable. Keyboard navigation works too! :)

**Comment by benfry** [comment]
Great! Thanks for letting me know. (It's rare that I hear about it when things are working or people are happy!)
