### ISSUE TITLE
win10 processing noting hanppen when I click the "run"

### ISSUE THREAD

**Issue by channnnge** [processing/processing#5127]
when i click "run", nothing hanppend. 
If i close processing,it can not opened once more unless after restart my computer.
_on Windows 7 and later, it's Users → username → AppData → Roaming → Processing.__
in can't find the file in my computer(win 10)
oh ,i use AMD Graphics.

**Comment by benfry** [comment]
Please read the troubleshooting page: https://github.com/processing/processing/wiki/Troubleshooting and use [the forum](http://forum.processing.org) to get help with this sort of thing.
