### ISSUE TITLE
Failed install of Android Mode

### ISSUE THREAD

**Issue by notklaatu** [processing/processing#5131]
1. Go to Add Modes
2. Go to Modes tab
3. Install Android Mode
Result: "Error during download and install of Android Mode."
Python mode, however, installs successfully. 

Platform: Slackware Linux
Processing 3.3.4

I've tried as root user and standard user.

**Comment by kfrajer** [comment]
Are you aware of this link? http://android.processing.org/tutorials/getting_started/index.html  
Also, there is a repo for AM: https://github.com/processing/processing-android 

kfrajer

**Comment by benfry** [comment]
Please file this with the Android repo (linked above) so that someone can see what's going on.
