### ISSUE TITLE
Detect errors involving curved quotation marks

### ISSUE THREAD

**Issue by chrstphrchvz** [processing/processing#5133]
I was helping some students go through [some online examples](https://docs.google.com/document/d/1NWp53xKKdWX6YT7bAIozGum8iWPctzZfJNDOaMTmnzo/pub). Many of them attempted to copy statements directly from the example, some of which use string literals with curved quotation marks instead of straight ones (like how they would be if typed manually):

```
text(“Stroke size: 3”, x, y)
```

instead of

```
text("Stroke size: 3", x, y)
```

This results in the linting error:

```
Syntax error on tokens, ArgumentList expected instead
```

and compilation error:

```
unexpected char: '\'
```

This might also happen if the source code is put through a word processor.

Would it be possible for Processing to reword these messages? The cause in this case is rather difficult for anyone to spot.

**Comment by benfry** [comment]
That's a great idea. I've seen the same thing, and it's so common (especially on the Mac, which is hyper about auto "correction").

**Comment by GKFX** [comment]
Also it would be nice to correct this in the autoformatter, I'll have a go at that.
