### ISSUE TITLE
Console broken since version 3.3.4

### ISSUE THREAD

**Issue by kasperkamperman** [processing/processing#5139]
The console doesn't have a scrollbar anymore and doesn't show all the printed values. I've noticed this on Windows (on a students computer) while printing a camera.list array. However in OSX 10.10.5 this error is also present. See the test code below. 

Test code
```
int [] numbers = { 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19 };

void setup() {
  printArray(numbers);
  noLoop();
}

void draw() {
}
```
Result in Processing 3.3.4 (the console shows only the last indexes and there is no way to scroll up):

<img width="403" alt="screen shot 2017-06-17 at 10 56 12" src="https://user-images.githubusercontent.com/1760616/27251680-06dbf036-534c-11e7-9230-7b2de7a0ec1d.png">

Result in Processing 3.3 (as expected)

<img width="406" alt="screen shot 2017-06-17 at 10 57 07" src="https://user-images.githubusercontent.com/1760616/27251683-0e94357c-534c-11e7-8e23-09e1fb126aae.png">

**Comment by GKFX** [comment]
Duplicate of #5110, now fixed. As noted in that thread there is a workaround (https://github.com/processing/processing/issues/5110#issuecomment-307647547) until the next release comes out.

**Comment by kasperkamperman** [comment]
Thanks. I had searched the open issues, but I missed it.
