### ISSUE TITLE
Terminal-Window only displays last two lines with println()

### ISSUE THREAD

**Issue by inhalte** [processing/processing#5143]
In the new version there seems to be a bug in the terminal window, since it only displays the last two lines with println(). Tested on macOS Sierra (Version 10.12.5).

Example-Code:
```
println(1);
println(2);
println(3);
println(4);
```

Output in Processing 3.3.3:
```
1
2
3
4
```

Output in Proceesing 3.3.4:
```
3
4
```

**Comment by benfry** [comment]
Sorry about that; it's already fixed for the next release:    https://github.com/processing/processing/issues/5110
