### ISSUE TITLE
console area only shows up to 2 lines?

### ISSUE THREAD

**Issue by Geoffree3** [processing/processing#5145]
println() should add another line to the end of the console area, which then scrolls as it fills up. It's been like this for as long as I remember.  Now, only 2 lines at most are shown, the rest disappearing into the ether!  Most annoying when debugging. I now have to write to a file.

Mac version 3.3.4

**Comment by jeremydouglass** [comment]
Fixed for the next release: #5110

**Comment by Taeclimax** [comment]
#5145
