### ISSUE TITLE
Osc Library

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5153]
There is weird information with information about the Osc library, when the library is more recent, Processing propose to update this one with an older one ????
![capture d ecran 2017-06-24 a 15 29 37](https://user-images.githubusercontent.com/3332269/27509066-6c9cc6e0-58f4-11e7-8705-932a7f4c1515.png)

**Comment by benfry** [comment]
You'll have to contact the OSC Library authors about that; we don't control their project.
