### ISSUE TITLE
Processing + Python

### ISSUE THREAD

**Issue by arthur109** [processing/processing#5155]
It would really be awesome If you guys could make the processing library importable into python, like a full on the real compatible library. This would be awesome because then people could use tensorflow in processing.

**Comment by GKFX** [comment]
http://py.processing.org/

**Comment by jeremydouglass** [comment]
A tensorflow in processing.py example: http://www.magicandlove.com/blog/2017/04/14/tensorflow-in-processing/

Questions like this should begin on the forum -- if you can't find your answer there, *then* open an issue on GitHub:

forum.processing.org/two/discussions
