### ISSUE TITLE
Debugger output marks wrong tab for missing curly bracket

### ISSUE THREAD

**Issue by mxa** [processing/processing#5156]
Since 3.3.5, the debugger sometimes marks the wrong tab (a class) for a missing curly bracket when actually it is missing in the main program, not the class tab. It seems to always be in the rightmost (last) tab where the error is (wrongly) found.

**Comment by mxa** [comment]
Minimal working example

[bugtest.zip](https://github.com/processing/processing/files/1100225/bugtest.zip)

**Comment by mxa** [comment]
Minimal example
[bugtest_.zip](https://github.com/processing/processing/files/1100227/bugtest_.zip)

**Comment by JakubValtar** [comment]
I was not able to reproduce it with your code. Did you send the right one? (First tab has only setup an draw and other two tabs are empty.)

**Comment by mxa** [comment]
I did sent the right one and the problem was present before, but I can't reproduce it now. Closing this.
