### ISSUE TITLE
Processing using 200% CPU and not responding after simple task (OS X)

### ISSUE THREAD

**Issue by dragnsurferz** [processing/processing#5157]
Hello, 
To start off my specs: 
  iMac(Mid 2011)
  OS X 10.11.6
  2.7 GHz i5
  4 GB DDR3 
  AMD Radeon HD 6770M 512 MB

  Processing: 3.3.5 && 3.3

Everything was working fine with my code, but after experimenting around its not working anymore. My code is using up to 250% of my CPU, calculating something it did it with 60% before. After that processing and the sketch stop responding.

This is the smallest piece of code that can replicate this "bug".
Instructions: just press 't' for 5 secs or so.

`
PGraphics a1;

// CAMERA
float cameraX;
float cameraY;
float cameraZ;
float eyeX;
float eyeY;
float eyeZ;
float cameraDist=2000;
float mouseSens=0.3;
float k;
float l;

// DRAG
float F;
float p=1.2;
float A=0.0028;
float cw=0.2;
float m=0.075;
int i=0;

// PROJECTILE
float acc;
float t=0.001;
float Vinit=300;
float V;
float Vxy;
float Vx;
float Vy;
float Vz;
float posX;
float posY;
float posZ;
float a=35;
float b=10;
float g=9.81;
PVector h1;

// POINTS
float[] pointX=new float[10000];
float[] pointY=new float[10000];
float[] pointZ=new float[10000];

// BOOLEANS
boolean gravity=true;
boolean drag=true;
boolean calculated=false;
boolean painted=false;

void setup(){
  size(displayWidth, displayHeight,P2D);
  background(255); 
  a1 = createGraphics(int(width*0.75),int(height*0.75),P3D);
  stroke(0);
}

void draw(){
  background(0);
  image(a1,0,0);
  cameraStuff();
  calculate();
  paint(a1);
  input();
  
}

void calculate(){ 
  if(calculated==false){   
    calculateVectors();    
    for(i=0;i<pointX.length;i++){          
      if(drag==true){        
        calculateDrag();        
      }      
      if(gravity==true){        
        calculateGravity();        
      }      
      calculatePosition();      
    }    
    calculated=true;    
  }  
}

void paint(PGraphics _a1){
  _a1.beginDraw();
    _a1.background(255);
    _a1.camera(cameraX,cameraY,cameraZ,eyeX,eyeY,eyeZ,0,1,0);
    if(painted==false){
      drawTrajectory(_a1);  
      painted=false;
    }
  _a1.endDraw();
}

void cameraStuff(){
  cameraY=eyeY+sin(radians(k))*cameraDist;
  cameraZ=eyeZ+cos(radians(l))*sqrt(pow(cameraDist,2)-pow(cameraY,2));
  cameraX=eyeX+sin(radians(l))*sqrt(pow(cameraDist,2)-pow(cameraY,2));   
}

void input(){
  if(keyPressed==true){
    if(key=='t'){
      a++;
      calculated=false;
    }    
  }      
}

void calculateDrag(){
  V=sqrt(pow(h1.x,2)+pow(h1.y,2)+pow(h1.z,2));
  
  F=0.5*pow(V,2)*p*cw*A;
  float n=F/V;
  PVector d1=new PVector(n*h1.x,n*h1.y,n*h1.z);

  acc=d1.y/m;
  Vy=Vy-acc*t;
  acc=d1.x/m;
  Vx=Vx-acc*t;
  acc=d1.z/m;
  Vz=Vz-acc*t;  
  h1=new PVector(Vx,Vy,Vz);
}

void calculateGravity(){
  Vy=Vy-g*t;
}

void calculateVectors(){
  V=Vinit;
  Vxy=cos(radians(b))*V;
  Vz=sin(radians(b))*V;
  Vx=cos(radians(a))*Vxy;
  Vy=sin(radians(a))*Vxy;
  h1=new PVector(Vx,Vy,Vz);
  posX=0;
  posY=0;
  posZ=0;
}

void calculatePosition(){
  posX=posX+Vx*t;
  posY=posY+Vy*t;    
  posZ=posZ+Vz*t;
  pointX[i]=posX;
  pointY[i]=posY;
  pointZ[i]=posZ; 
  if(pointY[i]>0){
    println(pointX[i]);
  }
}

void drawTrajectory(PGraphics __a1){
  for(int i=0;i<pointX.length;i++){            
    __a1.strokeWeight(3);
    __a1.stroke(0);
    if(pointY[i]<0){
      __a1.stroke(200);
    } 
    __a1.point(pointX[i],-pointY[i],pointZ[i]);
  }
}
`

**Comment by benfry** [comment]
Please use https://forum.processing.org for coding questions.
