### ISSUE TITLE
Doesn't show me or respond to any midi value - ThemidiBus

### ISSUE THREAD

**Issue by wgarcias2015** [processing/processing#5158]
Processing Version 3.3.4
MacBook Pro el Capitan 10.11.5
Controllers, Novation Circuit and M-Audio Oxygen 61

It  reads midi value, channel, and number well, but when I run it shows a blank canvas, I can't draw a line or circle with my controller, any help? Thaks 4 your time 

// CODE:

import themidibus.*;

MidiBus myBus;

void setup() {
  size(630, 400);
  background(255);

  MidiBus.list();
  myBus = new MidiBus(this, "Oxygen 61", "Oxygen 61" );
}
void draw() {
  background(255);
}

void controllerChange(int channel, int number, int value) {
 
  println(number);
  println(value);
 
  if(number == 75) {
    float y = map(value, 0, 127, 0, height);
    line(0, y, width, y);
  }

  if(number == 76) {
    ellipse(width/2, height/2, value*2, value*2);
  }
}

**Comment by benfry** [comment]
You'll need to report that to the authors of the MidiBus library.
