### ISSUE TITLE
noSmooth() issue

### ISSUE THREAD

**Issue by WinnerEX** [processing/processing#5160]
Older version of processing, 3.0.2, and unaware whether or not this issue has been addressed for successive versions. 

I'm aware how `size()` and `smooth()` are now called only once within `setup()`, but is there really no wiggle room with having these values be conditional nevermind variables?

For example, placing a loadStrings command to an option.txt file in the sketch folder at the top of `setup()`, then a conditional `if (read[0].equals("AA: 0")){ noSmooth(); }` directly after `size()`, this will not get triggered, defaulting to `smooth(2)`, and I'll get the error "noSmooth() can only be used inside setup()", despite it really being right there in setup.

If this hasn't been addressed as an issue in later Processing versions, is there any workaround to creating optional visual environments for the end user, such as relating to `size()` or `smooth()`?

**Comment by JakubValtar** [comment]
Firstly, use a newer version of processing, 3.0.2 is more than a year (14 releases) old and you may encounter issues which were already fixed.

You can use settings(), it gets called before setup(). It is generated automatically from the code in setup unless you write your own.
```processing
void settings() {
  // do your conditional size and smooth things here
  // sketch is not fully initialized yet so keep it minimal and do other stuff in setup
}

void setup() {

}

void draw() {

}
```

**Comment by WinnerEX** [comment]
thanks
