### ISSUE TITLE
processing inside tomcat

### ISSUE THREAD

**Issue by jcdutton** [processing/processing#5161]
Hi,

Is there any way to use processing inside tomcat?
When I try to use it, I always get the following message:
Cannot run sketch without a display. Read this for possible solutions:
https://github.com/processing/processing/wiki/Running-without-a-Display

I have tried starting tomcat with -Djava.awt.headless=false and -Djava.awt.headless=true
but it makes no difference.
I am using Xvfb on :1 and have set "export DISPLAY=:1"

**Comment by benfry** [comment]
Please use the forum for project questions. This section of Github is for tracking problems in the software.
