### ISSUE TITLE
Parsing errors?? envolving print statement

### ISSUE THREAD

**Issue by x13420x** [processing/processing#5163]
I am getting wierd errors.  I think it has to do with the code to prevent too many print statements....
example println(int[i],float).....this in a loop will work but sometimes I will get an error at the comma point(after about 180 times of looping).....I am only looping 200 times but its an old winxp machine and also got another error with 
cat=dang*pope[j-1]+temp[j-1];
  //println(am,pope[am]);

error says expecting an array got an int??? LOL  then run it again and it works.....just the print overload protection is creating very random behavior..........

P3.3.5

**Comment by GKFX** [comment]
Thanks for posting your code. To properly investigate bugs, we need a short, complete piece of code that shows the problem. I can't test the code `cat=dang*pope[j-1]+temp[j-1];` because I don't know the data type of `cat`, `dang`, `pope`, `j`, or `temp`. So, if possible, please create the shortest possible clear sketch that shows the problem, and attach all of it to a comment, and also post a screenshot of the error. However, if you're not certain that something is a bug in Processing, rather than your own code, then ask for help on the forums or StackOverflow first. Thanks!

**Comment by x13420x** [comment]
also digi=j-1;  ....gets error "no exist variable j1"  sorry cant post my code

**Comment by x13420x** [comment]
print("void level");

OUTPUT;
void
level
NEED AN OFF SWITCH FOR PRINT OVERLOAD PROTECTION OR AT LEAST A WARNING THIS IS REALLY GIVING ME PROBLEMS:::::NOW WITH A WIN 7 machine.............Please help!!!!!!

**Comment by GKFX** [comment]
Does `print("void level");`, with nothing else at all in the sketch, really give that output? That would be very odd, to say the least. Also I don't see fully what you're saying about the overloading of the print function being to blame; the two possible matching method signatures are `print(String)` and `print(Object...)`; as I understand it, `print(String)` should be what gets called, but either would give the correct output of
```text
void level
```
which is what I see. Is there any other output of the sketch? Is the line break always between `void` and `level` or do you sometimes see different things when you run the same code?

**Comment by x13420x** [comment]
I am super sorry man....I am so stupid...it was because the following text (after void)was too long and carried over.....So this problem only exists on Winxp on a machine with a stressed cpu....maybe its not important....but lots of people still use winxp.  Personally I am now using win7 machine....also this strange behavior happened on 2 different xp machines...so it wasnt the machine....but the cpu was under stress in both occasions....and I think that may have triggered the print overload protection even though I wasnt printing that much.  Having an off switch may help xp users.....also under win7 with less memory the ide will freeze when it doesnt have sufficient resources.....which doesnt happen when I am on the xp machines.....may not have anything to do with it....but yeah for me personally I have no more problems....just depends on how well you guys want to support old old xp machines.
