### ISSUE TITLE
IDE doesn't recognize functions returning PVectors

### ISSUE THREAD

**Issue by whetfire** [processing/processing#5164]
In ver 3.3.5, the editor underlines methods returning PVectors. The code does properly compile though.

```
PVector validFunction(){
    return new PVector(0, 0);
}
```

`PVector validFunction` is underlined and the IDE thinks I want to declare a new PVector. The red bar says "error on "PVector" ".
`return new PVector(0, 0);` is underlined, saying "void methods cannot return a value"

**Comment by StanLepunK** [comment]
The code below work perfectly on P 3.3.5 / OS Sierra

```
void setup() {
  println(validFunction());
}

PVector validFunction(){
  return new PVector(0,0);
}
```

**Comment by whetfire** [comment]
It works for me too, it's just that the IDE underlines it and thinks that there's something wrong.

Forgot to add:
OS: Ubuntu 16.04 LTS
Using Linux 64 bit version of Processing

**Comment by Thzn** [comment]
**1. In this case, the red bar says " Missing left curly bracket  { "** 

PVector function1(){
  return new PVector(0,0);
}

PVector function2(){
  return new PVector(1,1);
}

**2. But in this case, no syntax errors  shown in the bar.**

PVector function1(){
  return new PVector(0,0);
}

void anyfunction(){
}

PVector function2(){
  return new PVector(1,1);
}

I think if we define another type function (without PVector involvement) then there will be no syntax errors. But the code is properly compiling in both cases.
Processing 3.3.5 (64 bit)
Ubuntu 16.04 LTS

**Comment by JakubValtar** [comment]
You can write sketch in two modes: one where you have functions (active mode) and one which only includes statements to run once (static mode). You can read more [here](https://processing.org/tutorials/overview/), sections *Hello world* and *Hello mouse*. IDE check if there is any function with a primitive return type (void, int, etc.) , in which case it uses Active mode.

In your case there is no function with a primitive return type and IDE thinks you are trying to use static mode. If you include `void setup()` or `void draw()` everything will work. Your sketch won't do anything anyway, so you need to include them at some point if you want something to happen.

The mode detection should be improved when I finish removing ANTLR and switch to a new build system.
