### ISSUE TITLE
Debugger marking wrong tab for missing curly brackets

### ISSUE THREAD

**Issue by UnnamedMinecrafter** [processing/processing#5165]
processing 3.3.3 & Ubuntu 16.04 LTS
found another thread: https://github.com/processing/processing/issues/5156 [closed] [processing 3.3.5]
this is the bit marked by the error:

![grafik](https://user-images.githubusercontent.com/27627336/27986802-291e4b58-6404-11e7-9869-d161a6d06301.png)

here is the bit i got wrong:

![grafik](https://user-images.githubusercontent.com/27627336/27986811-5df0b2f8-6404-11e7-950d-36bd7d8b8bd5.png)

why does it mark something in a different class & tab ?

**Comment by jeremydouglass** [comment]
> why does it mark something in a different class & tab ?

Because all tabs are concatenated together and processed like one long file.

**Comment by JakubValtar** [comment]
> Because all tabs are concatenated together and processed like one long file.

The live error checker checks each tab separately and you get the error on the correct tab. However if you try to run it, the build process checks it as one long file and highlights the last tab.

This should be fixed when I'm done replacing ANTLR with the new build process based on Eclipse JDT.

**Comment by GKFX** [comment]
@JakubValtar Is replacing ANTLR going to be something that happens quite soon? I'm nearly finished putting the correct functionality in JavaBuild.java but I won't PR it if it'll quickly become obsolete.

**Comment by JakubValtar** [comment]
@GKFX I hope to get it out mid/late August, so it's not very high priority, but your PR is still welcome.

Btw. pdex.SourceUtils have a static method to check for this, so if you change the parameter from StringBuilder to CharSequence and create an array with tab offsets (extract them from each SketchCode), you can reuse it without much fuss to get the same functionality as Error Checker.

**Comment by GKFX** [comment]
@JakubValtar I've done something similar.

**Comment by JakubValtar** [comment]
@GKFX Great! Looking forward.
