### ISSUE TITLE
Movie Maker only works once per session (subsequent uses require restart of PDE)

### ISSUE THREAD

**Issue by altibzz** [processing/processing#5168]
I recently updated to Processing 3.3.5 and now I can only run the Movie Maker tool once per session - i.e. if I launch processing and run the Movie Maker tool, I have to restart Processing before I use it again. I don't get any error messages, but the 'create movie...' button is greyed out, even though there is a path specified to the frames folder. I've checked a bunch of times and the path to the frames folder is correct. If i restart processing and use the exact same path, it'll work - but just once and then I have to repeat the whole process again. I've test this on the previous version of Processing and there is no issue with Movie Maker. 

macOS 10.12.5 Quicktime 10.4 frames are .tif

**Comment by Stigjb** [comment]
Same issue here, Processing 3.3.5 on Windows 10 Home 1703. Frames are .png

**Comment by danlj** [comment]
The last version that worked for me was 3.3.4.

**Comment by benfry** [comment]
Huh… will look into it. Thanks for reporting back.
