### ISSUE TITLE
Comment/Uncomment sometimes inserts slashes at wrong indent

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#5171]
It looks like Comment/Uncomment inserts slashes at the indent of the first line.
```processing
void setup() {
  println();
}

void draw() {
  println();
}
```

Selecting the five lines in the middle (from `println()` to `println()` inclusive) and commenting them out produces this:

```processing
void setup() {
  //println();
}
////
vo//id draw() {
  //println();
}
```

instead of this:

```processing
void setup() {
//  println();
//}
//
//void draw() {
//  println();
}
```

**Comment by benfry** [comment]
Yeah, I think we need to back out the changes to the comment/uncomment that were submitted several months back… I've been seeing weird cases where they break, and I think it's trying to be too clever.

**Comment by JakubValtar** [comment]
It counts indent only on the first line of the selection instead up of the
min. indent of all selected lines. Should be easy to fix.

**Comment by benfry** [comment]
Sssshhh, you're not supposed to put “easy to fix” in writing. That's just taunting the bug.

**Comment by JakubValtar** [comment]
You have to taunt it until it crawls out into a clear sight and then kill it by applying a generous amount of debugger. That's how we did it in school. 

**The author has a degree in software engineering*
