### ISSUE TITLE
No support for HiDPI when running sketch on Linux! Practically unusable?

### ISSUE THREAD

**Issue by zacharisharris** [processing/processing#5179]
I have an Acer Chromebook 14 with a HiDPi screen, running GalliumOS. I installed Processing IDE the other day but there seems to be no support for HiDPI screens. (especially when running a sketch.)
I have tried the "Interface Scale" option for the UI and it works but not for when running the sketch.

(e.g when trying to draw a simple ellipse the sketch window is so small that only a portion of the ellipse is shown.)
![myscreenshot2](https://user-images.githubusercontent.com/147350/28291691-3c13b52a-6b54-11e7-974e-96b1802adcbc.png)

P.S: Please let me know if there is a solution or workaround to this because it practically renders Processing unusable and I really need to do some work on it.

**Comment by StanLepunK** [comment]
hmmm, with Processing you need to define a window by the method `void setup()` like this

after if you want refresh your sketch your method must be in the `void draw()`
`
if it's your first time with Processing visit https://processing.org/ and look the Video tutorial.

With the code below that's work fine.
```
void setup() {
  size(800,800) ;
  ellipse(100,200,618,912);
}
```

**Comment by zacharisharris** [comment]
Thank you very much for your reply. I am new to Processing so I didn't know that it was an option!

**Comment by StanLepunK** [comment]
Your welcome, after if you need more about Processing you can ask your question in the [forum](https://forum.processing.org/two/) here it's more the bug, or weird behavior :) You will see Processing is awesome !!!!!

**Comment by benfry** [comment]
We're still working on better HiDPI support for Windows and Linux. Stay tuned!

**Comment by maxdevjs** [comment]
In #4183 I read [There's no API for this on Linux, so you have to set it in Preferences.](https://github.com/processing/processing/issues/4183#issuecomment-455878321) ... But what should be set in Preferences (Linux)? 

I tried `GDK_SCALE` and works for Arduino IDE but not for PDE. Any hint?

**Comment by dzaima** [comment]
> In #4183 I read [There's no API for this on Linux, so you have to set it in Preferences.](https://github.com/processing/processing/issues/4183#issuecomment-455878321) ... But what should be set in Preferences (Linux)?

In Processing, under File -> Preferences (alternatively, <kbd>ctrl</kbd>+<kbd>,</kbd>), there should be an "interface scale" line - uncheck automatic, and some higher number.

Alternatively, in `~/.processing/preferences.txt` change `editor.zoom.auto` to false and edit `editor.zoom=100%`.

**Comment by maxdevjs** [comment]
@dzaima thank you so much for your reply. 

Yes, I already did that. I am looking forward to set the IDE itself menus etc.

I tried [GDK_SCALE](https://github.com/arduino/Arduino/pull/4376) (also `gui.scale`) but it works only with the Arduino IDE, not for PDE
