### ISSUE TITLE
Processing 3.3.5 (64-bit and 32-bit) startup errors on Windows 10

### ISSUE THREAD

**Issue by kamuizero** [processing/processing#5188]
I'm trying to get Processing 3.3.5 64 bit version to run on my windows machine without any luck. I execute processing, shows the splash screen and never starts the IDE.

I've deleted the preferences files as instructed on the Processing troubleshooting page, deleted the Processing folder in the User/AppData/Roaming folder, and ran 'processing.exe --l4j-debug' from the console.

The debug file shows the following message:

Version:	3.9
CmdLine:	C:\Users\AEPM\Downloads\processing-3.3.5-windows64\processing.exe --l4j-debug
WOW64:		yes
Working dir:	C:\Users\AEPM\Downloads\processing-3.3.5-windows64\.
Bundled JRE:	java
Check launcher:	C:\Users\AEPM\Downloads\processing-3.3.5-windows64\java\bin\javaw.exe (OK)
Heap -Xmx:	Requested 256 MB / 0%, Available: 8256 MB, Heap size: 256 MB
Substitute:	EXEDIR = C:\Users\AEPM\Downloads\processing-3.3.5-windows64
Add classpath:	lib\pde.jar
Add classpath:	core\library\core.jar
Add classpath:	lib\jna.jar
Add classpath:	lib\jna-platform.jar
Add classpath:	lib\antlr.jar
Add classpath:	lib\ant.jar
Add classpath:	lib\ant-launcher.jar
Launcher:	C:\Users\AEPM\Downloads\processing-3.3.5-windows64\java\bin\javaw.exe
Launcher args:	-Xmx256m -Djava.ext.dirs="C:\Users\AEPM\Downloads\processing-3.3.5-windows64\\java\\lib\\ext" -Djna.nosys=true -Djna.boot.library.path=lib -Djna.nounpack=true -Dsun.java2d.d3d=false -Dsun.java2d.ddoffscreen=false -Dsun.java2d.noddraw=true -classpath "lib;lib\pde.jar;core\library\core.jar;lib\jna.jar;lib\jna-platform.jar;lib\antlr.jar;lib\ant.jar;lib\ant-launcher.jar" processing.app.Base
Args length:	389/32768 chars
Exit code:	1

And as mentioned before, never starts the IDE, no error message, just nothing, shows the splash screen for a fraction of a second and then disappears.

Additionally, if I try running the 32-bit version from the console with the same command, I get the An error Occurred during startup and a NullPointerException and the execution stack, with the problem apparently being at processing.app.Base.buildCoreModes(Base.java:419). The message from the launch4j file for the 32 bit gives the following message:

Version:	3.9
CmdLine:	C:\Users\AEPM\Downloads\processing-3.3.5-windows32\processing.exe --l4j-debug
WOW64:		yes
Working dir:	C:\Users\AEPM\Downloads\processing-3.3.5-windows32\.
Bundled JRE:	java
Check launcher:	C:\Users\AEPM\Downloads\processing-3.3.5-windows32\java\bin\javaw.exe (OK)
Heap -Xmx:	Requested 256 MB / 0%, Available: 8252 MB, Heap size: 256 MB
Substitute:	EXEDIR = C:\Users\AEPM\Downloads\processing-3.3.5-windows32
Add classpath:	lib\pde.jar
Add classpath:	core\library\core.jar
Add classpath:	lib\jna.jar
Add classpath:	lib\jna-platform.jar
Add classpath:	lib\antlr.jar
Add classpath:	lib\ant.jar
Add classpath:	lib\ant-launcher.jar
Launcher:	C:\Users\AEPM\Downloads\processing-3.3.5-windows32\java\bin\javaw.exe
Launcher args:	-Xmx256m -Djava.ext.dirs="C:\Users\AEPM\Downloads\processing-3.3.5-windows32\\java\\lib\\ext" -Djna.nosys=true -Djna.boot.library.path=lib -Djna.nounpack=true -Dsun.java2d.d3d=false -Dsun.java2d.ddoffscreen=false -Dsun.java2d.noddraw=true -classpath "lib;lib\pde.jar;core\library\core.jar;lib\jna.jar;lib\jna-platform.jar;lib\antlr.jar;lib\ant.jar;lib\ant-launcher.jar" processing.app.Base
Args length:	389/32768 chars
Exit code:	259

Am I missing some additional configuration? Is there something wrong with the way I'm running the executables? Any help here would be greatly appreciated, if you need any additional information please let me know.

Thanks in advance!

**Comment by JakubValtar** [comment]
This is strange. Some ideas:

- make sure the zip is unpacked completely, sometimes people try to run it without unpacking
- try to move the unpacked folder to a different location (desktop) and run it from there
- some antivirus software runs unknown programs in "sandbox" mode, check if that's the case or try to disable antivirus and windows defender

**Comment by kamuizero** [comment]
@JakubValtar thank you for your reply.

I extracted the files from the zip file before executing the program so it should be fine.

I tried disabling the antivirus, moving the folder to the desktop and ran the same command 'processing.exe --l4j-debug' and got pretty much the same output.

64-bit version

Version:	3.9
CmdLine:	C:\Users\AEPM\Desktop\processing-3.3.5-windows64\processing.exe --l4j-debug
WOW64:		yes
Working dir:	C:\Users\AEPM\Desktop\processing-3.3.5-windows64\.
Bundled JRE:	java
Check launcher:	C:\Users\AEPM\Desktop\processing-3.3.5-windows64\java\bin\javaw.exe (OK)
Heap -Xmx:	Requested 256 MB / 0%, Available: 8305 MB, Heap size: 256 MB
Substitute:	EXEDIR = C:\Users\AEPM\Desktop\processing-3.3.5-windows64
Add classpath:	lib\pde.jar
Add classpath:	core\library\core.jar
Add classpath:	lib\jna.jar
Add classpath:	lib\jna-platform.jar
Add classpath:	lib\antlr.jar
Add classpath:	lib\ant.jar
Add classpath:	lib\ant-launcher.jar
Launcher:	C:\Users\AEPM\Desktop\processing-3.3.5-windows64\java\bin\javaw.exe
Launcher args:	-Xmx256m -Djava.ext.dirs="C:\Users\AEPM\Desktop\processing-3.3.5-windows64\\java\\lib\\ext" -Djna.nosys=true -Djna.boot.library.path=lib -Djna.nounpack=true -Dsun.java2d.d3d=false -Dsun.java2d.ddoffscreen=false -Dsun.java2d.noddraw=true -classpath "lib;lib\pde.jar;core\library\core.jar;lib\jna.jar;lib\jna-platform.jar;lib\antlr.jar;lib\ant.jar;lib\ant-launcher.jar" processing.app.Base
Args length:	387/32768 chars
Exit code:	1

32-bit version

Version:	3.9
CmdLine:	C:\Users\AEPM\Desktop\processing-3.3.5-windows32\processing.exe --l4j-debug
WOW64:		yes
Working dir:	C:\Users\AEPM\Desktop\processing-3.3.5-windows32\.
Bundled JRE:	java
Check launcher:	C:\Users\AEPM\Desktop\processing-3.3.5-windows32\java\bin\javaw.exe (OK)
Heap -Xmx:	Requested 256 MB / 0%, Available: 7890 MB, Heap size: 256 MB
Substitute:	EXEDIR = C:\Users\AEPM\Desktop\processing-3.3.5-windows32
Add classpath:	lib\pde.jar
Add classpath:	core\library\core.jar
Add classpath:	lib\jna.jar
Add classpath:	lib\jna-platform.jar
Add classpath:	lib\antlr.jar
Add classpath:	lib\ant.jar
Add classpath:	lib\ant-launcher.jar
Launcher:	C:\Users\AEPM\Desktop\processing-3.3.5-windows32\java\bin\javaw.exe
Launcher args:	-Xmx256m -Djava.ext.dirs="C:\Users\AEPM\Desktop\processing-3.3.5-windows32\\java\\lib\\ext" -Djna.nosys=true -Djna.boot.library.path=lib -Djna.nounpack=true -Dsun.java2d.d3d=false -Dsun.java2d.ddoffscreen=false -Dsun.java2d.noddraw=true -classpath "lib;lib\pde.jar;core\library\core.jar;lib\jna.jar;lib\jna-platform.jar;lib\antlr.jar;lib\ant.jar;lib\ant-launcher.jar" processing.app.Base
Args length:	387/32768 chars
Exit code:	259

As before, I only got the NullPointerException when running the 32-bit version. Any additional thoughts on this issue?

Thank you very much in advance.

**Comment by kamuizero** [comment]
@JakubValtar thanks again for your reply.

I did as you suggested, created the debug.txt file and executed the 64-bit processing from the console and I found out something curious, there were no new .out and .err files created in the directory C:\Users\AEPM\AppData\Roaming\Processing\console\ (just the ones created from previous executions), and no new preferences.txt file, even though it created a registry as usual in the C:\Users\AEPM\Desktop\processing-3.3.5-windows64\launch4j.log file.

When I run the 32-bit version, it created the preferences.txt file and generated the two files in the C:\Users\AEPM\AppData\Roaming\Processing\console\ directory, with the following contents:

170722_124346.err

```
ModeContribution.load() failed for processing.mode.java.JavaMode
java.lang.ClassNotFoundException: processing.mode.java.JavaMode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at processing.app.contrib.ModeContribution.<init>(ModeContribution.java:88)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:51)
	at processing.app.Base.buildCoreModes(Base.java:418)
	at processing.app.Base.<init>(Base.java:332)
	at processing.app.Base.createAndShowGUI(Base.java:215)
	at processing.app.Base.access$0(Base.java:128)
	at processing.app.Base$1.run(Base.java:117)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

170722_124346.out

```
About to create Base...
No properties file at C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode.properties
err is java.lang.ClassNotFoundException: processing.mode.java.JavaMode
```

I hope this helps a bit to find out what could be happening. I find it quite weird that the 64-bit version seems to be completely unresponsive, whereas the 32-bit version seems to at least try to do something...

**Comment by kamuizero** [comment]
@JakubValtar 

OK I got the 32-bit version to start. I moved the 'mode' folder 
```
C:\Users\AEPM\Desktop\processing-3.3.5-windows32\processing-3.3.5\mode
```
to 
```
C:\Users\AEPM\Desktop\processing-3.3.5-windows32
```

And I could get the 32-bit IDE to start, now the .out file contents is

```
About to create Base...
No properties file at C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode.properties
checking mode folder regarding class name processing.mode.java.JavaMode
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\antlr-src.zip for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\antlr.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\classpath-explorer-1.0.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\com.ibm.icu.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\JavaMode.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\jdi.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\jdimodel.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\jdtCompilerAdapter.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\jsoup-1.7.1.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\org.eclipse.core.contenttype.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\org.eclipse.core.jobs.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\org.eclipse.core.resources.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\org.eclipse.core.runtime.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\org.eclipse.equinox.common.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\org.eclipse.equinox.preferences.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\org.eclipse.jdt.core.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\org.eclipse.osgi.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\org.eclipse.text.jar for java
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\modes\java\mode\org.netbeans.swing.outline.jar for java
loading above JARs with loader java.net.URLClassLoader@8b160f
Got mode class class processing.mode.java.JavaMode
No properties file at C:\Users\AEPM\Desktop\processing-3.3.5-windows32\core\library.properties
Load PDEX prefs
Nothing set for last.sketch.mode, using default.
Calling handleNew() to open a new window
No properties file at C:\Users\AEPM\Desktop\processing-3.3.5-windows32\tools\MovieMaker\tool.properties
checking mode folder regarding null
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\tools\MovieMaker\tool\jai_imageio.jar for MovieMaker
Found archive C:\Users\AEPM\Desktop\processing-3.3.5-windows32\tools\MovieMaker\tool\MovieMaker.jar for MovieMaker
loading above JARs with loader java.net.URLClassLoader@831b85
Error with font null for attribute console.font
PPS: Hi!
PPS: Starting
Base() constructor succeeded
Opening SingleInstance socket
Starting SingleInstance thread
Done creating Base...
PPS: Done
#Called getTextLocation:TextHitInfo[0L]
#Called getTextLocation:TextHitInfo[0L]
```

Tried something similar with the 64-bit version, moving the 'lib' folder
```
C:\Users\AEPM\Desktop\processing-3.3.5-windows64\processing-3.3.5\lib
```

to 

```
C:\Users\AEPM\Desktop\processing-3.3.5-windows64
```

And it seemed to do the trick. If I experience any other problems will let you know but it seems to be working fine now.

Thank you very much for your help, if you have any final comments or suggestions please let me know.

**Comment by kfrajer** [comment]
Quick question. Did you have another version of Processing before in your machine or this was a fresh/brand new/first time install? I installed my 3.3.5 recently on a Win10 x64 and I didn't experience any issues.

Kf

**Comment by kamuizero** [comment]
@kfrajer This was a new install of the software, I had never used processing before. 

It seems like this was a problem caused by the program I was using to extract the files.

**Comment by JakubValtar** [comment]
@kamuizero Thanks for sharing your solution with us! Which program did you use to extract the files? Looks like it messed up the directory structure. It would be great to know so we can help other people with the same problem.

**Comment by kamuizero** [comment]
@JakubValtar Yes it was something so simple, but I never asked myself if the directory structure was correct, I was just blindly trusting that the program was doing the extraction properly hehe.

I used PeaZip to extract the files.

**Comment by JakubValtar** [comment]
@kamuizero Thanks, we never figured out why these problems were happening. I think we should update our wiki.

**Comment by kamuizero** [comment]
@JakubValtar Thank you very much for your support!

I hope this could help improve everyone else's experience in the future.
