### ISSUE TITLE
PShape.getFill() throws OutOfBoundsException for SVG <path> or <polygon>

### ISSUE THREAD

**Issue by jango-fx** [processing/processing#5196]
whenever i call the [`PShape.getFill()`](https://github.com/processing/processing/blob/d363bd3c98b2a0fccd43202b06174ebcca3a213d/core/src/processing/core/PShape.java#L2356) method for a `<path>` or `<polygon>` element of an SVG, it throws an 
> ArrayIndexOutOfBoundsException: 6

when the same method is called for a `<circle>` or `<ellipse>` element, it works fine.

As I see it `getFill()` should actually return `fillColor`, but only does so, if the element doesn't contain any vertices (which `<path>` and `<polygon>` do).
Instead, it is trying to call `vertices[index][PGraphics.A]` for whatever reason and [PGraphics.A](https://github.com/processing/processing/blob/514d420907593471cbbf7c3def12a59e5bd638c5/core/src/processing/core/PGraphics.java#L244) == **6**.

**Comment by jango-fx** [comment]
e.g.:

calling
`println(hex(bot.getChild(24).getFill(0)));` 
in the **_LoadDisplaySVG_ example** works fine.

while 
`println(hex(bot.getChild(25).getFill(0)));`
doesn't.

**Comment by benfry** [comment]
You probably need to check the actual type… it's probably not the object you're expecting. `PShape`'s hierarchy works a little differently than the SVG itself.
