### ISSUE TITLE
error message: Target VM failed to initialize

### ISSUE THREAD

**Issue by WilsonFerg** [processing/processing#5198]
I am trying to run the following code using Processing 3.3:
void setup() {
  size(600, 600);
}

void draw() {
  background(51, 51, 51);
}

I have saved in appropriate place with new name. When I try to run it gives me the error saying "could not run the sketch (Target VM failed to initialize). I also tried this in version 3.5 and didn't work.

**Comment by benfry** [comment]
You'll have better luck getting troubleshooting help from the forum. Also make sure you haven't set the amount of RAM too high in the Preferences dialog box, and that you don't have a firewall turned on that's preventing the app from connecting to the sketch that it's launching.

**Comment by F4Tornado** [comment]
It seemed to be a firewall thing for me, I let processing through the firewall and it worked.
