### ISSUE TITLE
Show this welcome message each time wont be disabled after unchecked box

### ISSUE THREAD

**Issue by realchessx** [processing/processing#5199]
processing 3.3.5
java 8 131
windows 10

1. click processing and start
2. unchecked welcome message 
3. exit processing
4. click processing again and start
5. welcome message still showing

**Comment by whetfire** [comment]
Looks like it's this problem:  https://github.com/processing/processing/issues/3911
The Getting Started button needs to be clicked for the checkbox to take effect.
