### ISSUE TITLE
problem with created equals() method

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5200]
I write my own method `equals()` with different arguments, this one work fine when it's used directly in the method setup() or when it's nested in other method, but when it's write in a class, Processing return an error message.

```
 //  println(equals(1,2)) ;  // work fine
 // method();
}

void method() {
  println(equals(1,2)); // work fine
}
boolean equals(int a, int b) {
  return true ;
}

class C {
  void test () {
    println(equals(1,2)); // don't work 
  }
}
```
![capture d ecran 2017-07-29 a 15 06 51](https://user-images.githubusercontent.com/3332269/28745045-a3c74802-746f-11e7-8e0e-88fe7bea0f4b.png)

**Comment by jeremydouglass** [comment]
If I understand correctly, you are asking why this code is valid if you use `boolean myName(int a, int b)` but fails if you override the name of a built-in Processing function. Is that right?

**Comment by StanLepunK** [comment]
hmmm, my code is not clear like my tired brain. The problem the `equals()` stop processing when it's implement with multiple arg and nested in other class
like that : 
```
C c = new C() ;

void setup() {
 //  equals(1,2) ;  // work fine
 // method(); // work fine
 c.my_medthod() ; // don't work
}

void method() {
  equals(1, 2); // work fine
}

class C {
  void my_medthod() {
    equals(1,2); // don't work with multiple arg
  }
}

void equals(int... arg) {} // don't work when it's nested in class

void equals(int a, int b) {} // don't work when it's nested in class

void equals(int a) {} // work fine
```

I hope clarify the problem ?

**Comment by JakubValtar** [comment]
`equals()` is a special function in Java used to compare if some other object is the same as this object, every object instance has one.

Please use a different name unless you are 100% sure you need to change the behavior of `equals()`.

See e.g. [this](http://www.drdobbs.com/jvm/java-qa-how-do-i-correctly-implement-th/184405053) if you want to learn more.

**Comment by StanLepunK** [comment]
Ok @JakubValtar I already used `compare()`instead `equals()`. So, if I understand well, anything cannot do it. Because it's a special behavior from Java. 
Thx for the precision.
