### ISSUE TITLE
mouseWheel event.getCount() not consistent between FX2D and the default renderer

### ISSUE THREAD

**Issue by tarabishy2020** [processing/processing#5204]
```
void setup(){
  size(300,300,FX2D);
  //size(300,300);
}

void draw(){
  
}

void mouseWheel(MouseEvent event){
println(event.getCount());
}
```

activating FX2D and then not activating it produces completely different numbers, specifically, when its activated a lot of zeros are returned as opposed to when its not, rendering it a bit useless when using it as an input to edit anything (i.e zooming for example)

**Comment by Bobby54** [comment]
@benfry Has this issue already been fixed?
Either I'm not having this issue or it was fixed.
If not I would like to work on this one.

**Comment by benfry** [comment]
Ok, closing since it can't be reproduced.
