### ISSUE TITLE
Problem with openGL on AMD driver

### ISSUE THREAD

**Issue by yih6208** [processing/processing#5206]
I am using AMD RX460 graphic card and install the newest driver (amdgpu-pro-17.30-458935)
But when I run the examples using openGL library , it will show the error message below:

P.S. My processing version is 3.3.5 (23 June 2017)
**Caught handled GLException: X11GLXDrawableFactory - Could not initialize shared resources for X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x3d07a294, isOwner false, <7a1c1d24, 22dd114a>[count 0, qsz 0, owner <NULL>]]] on thread main-SharedResourceRunner
    [0]: jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:306)
    [1]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [2]: java.lang.Thread.run(Thread.java:748)
Caused[0] by GLException: main-SharedResourceRunner: Error making temp context(1) current: display 0x7effb0000fa0, context 0x7effb016c3f0, drawable X11OnscreenGLXDrawable[Realized true,
	Factory   jogamp.opengl.x11.glx.X11GLXDrawableFactory@2f61f6da,
	Handle    0x6c00002,
	Surface   WrappedSurface[ displayHandle 0x7effb0000fa0
, surfaceHandle 0x6c00002
, size 64x64
, UOB[ OWNS_SURFACE | WINDOW_INVISIBLE ]
, X11GLXGraphicsConfiguration[X11GraphicsScreen[X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x7effb0000fa0, owner true, ResourceToolkitLock[obj 0x35fae8e6, isOwner true, <1a0b133d, 3d7f5464>[count 2, qsz 0, owner <main-SharedResourceRunner>]]], idx 0], visualID 0xd4, fbConfigID 0x84,
	requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL2.sw], on-scr[.]],
	chosen    GLCaps[glx vid 0xd4, fbc 0x84: rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL2/GL2.sw], on-scr[.]]]
, surfaceLock <1d08a237, 7fd7d4a8>[count 1, qsz 0, owner <main-SharedResourceRunner>]
, X11DummyUpstreamSurfaceHook[pixel 64x64]
, upstreamSurface false ]] on thread main-SharedResourceRunner
    [0]: jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:393)
    [1]: jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
    [2]: jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
    [3]: jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
    [4]: jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:277)
    [5]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [6]: java.lang.Thread.run(Thread.java:748)
OpenGL error 1280 at bot beginDraw(): invalid enumerant**

Once I uninstall the AMD driver, all things will back to normal.

## Here is my openGL information:
**$ glxinfo | grep "OpenGL"**
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon (TM) RX 460 Graphics
OpenGL core profile version string: 4.5.13491 Core Profile Context 17.30.0
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.13491 Compatibility Profile Context 17.30.0
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: 4.5.13491 Compatibility Profile Context 17.30.0
OpenGL ES profile shading language version string: 4.50
OpenGL ES profile extensions:

**Comment by codeanticode** [comment]
Hi, are there any newer drivers available to see if the crash still happens?

**Comment by benfry** [comment]
No response; closing.
