### ISSUE TITLE
Fails to export data folder : OSX

### ISSUE THREAD

**Issue by quarks** [processing/processing#5207]
A forum member noticed that the 'data' folder was not being exported on OSX. I have just tried an experiment creating a simple sketch to load and display some images and then exported it to create Windows, Osx and Linux distributions. The data folder was only exported for Windows and Linux.

The experiment was performed with
Processing 3.3.5
OSX 10.12.6

**Comment by benfry** [comment]
Thanks for the heads up, though it seems to be working fine for me… The data folder on macOS is embedded inside the .app structure, so perhaps they were confused? I was able to open the “LoadDisplayImage” example, hit Export, and then run the app with no trouble.
