### ISSUE TITLE
Please Support Multi-version on One Account

### ISSUE THREAD

**Issue by ray7551** [processing/processing#5209]
I have 2 processing, version 3.3.5 and 3.1.1. I found they use same directory to store settings, in windows it's AppData\Roaming\Processing.
This cause they share the same sketchbook path, where modes, libraries, examples stored.
It may cause some problems. Some modes only works in lower level processing, but higher level processing also show it at right corner, and I cannot install different version of modes for different version of processing. What's more, mode incompatible may cause processing start fail.

It will be nice to support multi-version.

**Comment by benfry** [comment]
You can do this between 2.x and 3.x, but not for multiple 3.x versions. We don't have nearly enough volunteers and people developing the project where we would want to encourage people to use anything but the latest 3.x release.
