### ISSUE TITLE
background() don't work after surface.setSize()

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5211]
`background(PImage img)` don't work if `surface.setSize()`is used in the `draw()` no problem when it's used in the `setup()`

P 3.3.5 / iMac 2011 / OS Sierra

```
PImage img ;

void setup() {
  size(100,100,P2D) ;
  img = loadImage("purosGirl_small.jpg");
  // surface.setSize(img.width,img.height) ; // that's work 
}

void draw() {
  surface.setSize(img.width,img.height) ; // don't work
  background(img); 
}
```

**Comment by cchaine** [comment]
As mentioned by BenFry #3935
> Calls to surface can't run while drawing.

**Comment by StanLepunK** [comment]
ok I close the topic.
