### ISSUE TITLE
void vertexTexture(float u, float v) is not public?

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5217]
I see in Processing there is method `protected void vertexTexture(float u, float v) `and to use this one it's necessary to pass by `public void vertex(float x, float y, float z, float u, float v)` ; why protected `void vertexTexture()` I think it's easier to code and understand code to can write the code like : 

```
vertex(xyz_1);
vertex(xyz_2);
vertex(xyz_3);
texture();
vertexTexture(uv_1);
vertexTexture(uv_2);
vertexTexture(uv_3);
```

**Comment by benfry** [comment]
Because the u, v coordinates (almost, nearly) always go with a specific texture vertex. The code you've written above wouldn't work at all.

**Comment by StanLepunK** [comment]
Thx @benfry for the information.
