### ISSUE TITLE
/**/ not handled properly by the preprocessor/parser

### ISSUE THREAD

**Issue by dzaima** [processing/processing#5219]
If `/**/` appears somewhere in the code, something in the error generating code will treat it like it's only a comment opening, and ignore the closing, although the syntax highlighter and compiler treat it like a closed comment and it runs without any problems.

Example code which gives false errors:
```
void setup() {
  /**/
  print("Hello, World!");
}
```

**Comment by kritixilithos** [comment]
If I understand it right, the PDE gives the syntax error before running? What was the exact error?

**Comment by dzaima** [comment]
The exact code gives the error `Found one too many { characters without } to match it` because it thought that the closing bracket was a part of an unfinished comment.

**Comment by kritixilithos** [comment]
Everything seems to lead to `org.eclipse.jdt.core.compiler.IProblem`.

**Comment by benfry** [comment]
Fix incorporated for 3.3.7 or 3.4.
