### ISSUE TITLE
Workaround register allocation issue in shader for Raspberry Pi VC4

### ISSUE THREAD

**Issue by gohai** [processing/processing#5223]
Looks like Raspbian distribution will switch their default graphics driver to the open source Mesa driver fairly soon (most users interested having KODI perform nicely will probably already throw the switch themselves with the newly released version).

Unfortunately we have one issue with this driver currently: the compiler runs out of registers with our LightVert & TexLightVert shaders. And this is even when reducing the number of possible lights to two, as we already do for the Pi.

The driver author is aware of the issue, and will hopefully be able to address this at some point. But in case this won't be ready in time before Raspbian makes the switch: what part of the shader would you sacrifice to just get to _some_ halfway decent visual output? @codeanticode @JakubValtar Any ideas?

[Here](https://github.com/anholt/mesa/issues/63#issuecomment-282163707) are some suggestions from the driver author FWIW.

**Comment by JakubValtar** [comment]
I might be able to get rid of some conditional breaks to make the code
simpler while keeping the functionality. Would this help?

Let's see if I can find some time for this soon.

**Comment by gohai** [comment]
@JakubValtar I just tried running the loop unconditionally, without the `break` but it still blows up.

But if you could take a stab at implementing a _poor-man's 3D_, that'd be great help indeed. I could test any shader that you send my way, or setup a Pi for you to SSH into...

**Comment by gohai** [comment]
Fixed by #5297
