### ISSUE TITLE
win7系统下面打开不了软件

### ISSUE THREAD

**Issue by huangweida** [processing/processing#5236]
![image](https://user-images.githubusercontent.com/13655170/29816454-a7b6d48e-8ce6-11e7-91c2-016c33030fc4.png)
始终在启动界面，软件是3.3.5版本

**Comment by jeremydouglass** [comment]
The text says:

> Win7 system can not open the software below.
> 
> Always start the interface, the software is 3.3.5 version.

**Comment by benfry** [comment]
You should check through the [troubleshooting](https://github.com/processing/processing/wiki/Troubleshooting) page first, or see if someone on the forums can help.
