### ISSUE TITLE
processing-java.exe can not run, flash and closed.

### ISSUE THREAD

**Issue by bassvv** [processing/processing#5238]
processing-java.exe can not run, flash and closed.

**Comment by gohai** [comment]
@bassvv Can you provide us with more information about your setup and the issue you're experiencing?

**Comment by benfry** [comment]
`processing-java.exe` isn't meant to be run as a double-clickable application. It's the command line version of the software, to be used from the Command Prompt. If you double-click it, this is what will happen.
