### ISSUE TITLE
Create GitHub issue template to avoid issues being posted here without enough info

### ISSUE THREAD

**Issue by hamoid** [processing/processing#5239]
Often developers must ask for more details that could have been provided initially.

Here how to create an issue template: https://github.com/blog/2111-issue-and-pull-request-templates

I'm not sure what should the template include, maybe: 
* Processing version
* OS version
* Steps to reproduce the issue?

What to do with feature requests? Mark them as [x] feature request?
What to post as issue and what goes to the forum?

**Comment by benfry** [comment]
Want to take a stab at this for us?
