### ISSUE TITLE
click and drag selects the wrong line of code in the editor window

### ISSUE THREAD

**Issue by timrodenbroeker** [processing/processing#5240]
I have been trying to mark a line of code with the mouse, but instead another line has been marked. The bug disappeared by shutting down and restarting Processing.

I've attached a screenshot. 

[bug2.zip](https://github.com/processing/processing/files/1263984/bug2.zip)

**Comment by benfry** [comment]
Very odd… never seen this one.

**Comment by GRsni** [comment]
@timrodenbroeker Did this issue ever resolve? Has it happened again?

**Comment by Bobby54** [comment]
@timrodenbroeker What System are you using?
In case this issue appears again, could you try to mark something using [Shift] + [cmd] + the arrow keys (if you are using macOS || [Shift] + arrow Keys on widows).
Also check if this issue only appears in the editor or in other applications as well. This would mean, that this issue hasn't got anything to do with processing but with your os.

**Comment by timrodenbroeker** [comment]
Hey @Bobby54, I'm on a mac. The problem did not appear again, i guess the last update fixed the bug anyway. The issue only happended in Processing but not in any other application.
