### ISSUE TITLE
Autosave feature deletes code before saving.

### ISSUE THREAD

**Issue by TheWithz** [processing/processing#5242]
Google Pixel C using version 4.0 of the mobile app. 

The autosave feature deletes all code in the current tab before saving, so all code in that tab is lost. Tabs that are unselected are not affected, only the tab that has focus.

**Comment by gohai** [comment]
@TheWithz Which mobile app are you referring to?

**Comment by benfry** [comment]
The PDE doesn't run on the Pixel C, and doesn't have an auto-save feature, so I think this might be the wrong project…
