### ISSUE TITLE
problem when run [oscp5] can't run

### ISSUE THREAD

**Issue by bassvv** [processing/processing#5247]
`java.lang.NoClassDefFoundError: oscP5/OscPacket
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at processing.core.PApplet.runSketch(PApplet.java:10688)
	at processing.core.PApplet.main(PApplet.java:10464)
Caused by: java.lang.ClassNotFoundException: oscP5.OscPacket
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.
`

## run The simple from processing to grasshopper can't run from my laptop, but ok on my desktop

`<html><body><pre>
<span style="color: #666666;">//PROCESSING-GRASSHOPPER&nbsp;real&nbsp;time&nbsp;OSC&nbsp;communication</span>
<span style="color: #666666;">//&nbsp;send&nbsp;2d&nbsp;processing&nbsp;array&nbsp;and&nbsp;split&nbsp;it&nbsp;in&nbsp;GH</span>
<span style="color: #666666;">//</span>
<span style="color: #666666;">//this&nbsp;method&nbsp;can&nbsp;serve&nbsp;to&nbsp;send&nbsp;stuff&nbsp;to&nbsp;Grasshopper&nbsp;in&nbsp;general,&nbsp;although&nbsp;the&nbsp;example&nbsp;is</span>
<span style="color: #666666;">//concerned&nbsp;with&nbsp;a&nbsp;2d&nbsp;array</span>
<span style="color: #666666;">//</span>
<span style="color: #666666;">//You&nbsp;need&nbsp;to&nbsp;have:&nbsp;</span>
<span style="color: #666666;">//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--oscP5&nbsp;processing&nbsp;library&nbsp;-&gt;&nbsp;http://www.sojamo.de/libraries/oscP5/</span>
<span style="color: #666666;">//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--gHowl&nbsp;GH&nbsp;plug-in&nbsp;-&gt;&nbsp;http://www.grasshopper3d.com/group/ghowl</span>

<span style="color: #666666;">//thanks&nbsp;to&nbsp;Luis&nbsp;Fraguada&nbsp;for&nbsp;the&nbsp;gHowl&nbsp;plug-in&nbsp;</span>
<span style="color: #666666;">//thanks&nbsp;to&nbsp;Andreas&nbsp;Schlegel&nbsp;for&nbsp;the&nbsp;OscP5&nbsp;library</span>
<span style="color: #666666;">//by&nbsp;Constantinos&nbsp;Miltiadis&nbsp;&amp;&amp;&nbsp;Petros&nbsp;Koutsolambros&nbsp;/&nbsp;architecture&nbsp;NTUA&nbsp;</span>

<span style="color: #33997E;">import</span> oscP5.*;
<span style="color: #33997E;">import</span> netP5.*;
OscP5&nbsp;oscP5;&nbsp;

<span style="color: #33997E;">final</span> <span style="color: #E2661A;">int</span> nX=6; <span style="color: #666666;">//array length at X</span>
<span style="color: #33997E;">final</span> <span style="color: #E2661A;">int</span> nY=7; <span style="color: #666666;">//array length at Y</span>
<span style="color: #E2661A;">PVector</span> [][] myArray=<span style="color: #33997E;">new</span> <span style="color: #E2661A;">PVector</span>[nX][nY]; 

NetAddress&nbsp;myBroadcastLocation;
OscMessage&nbsp;arrayMsg&nbsp;=&nbsp;<span style="color: #33997E;">new</span> OscMessage(<span style="color: #7D4793;">&quot;/array&quot;</span>); <span style="color: #666666;">// &quot;/array&quot; is an arbitrary header/filter that the</span>
<span style="color: #666666;">//message&nbsp;will&nbsp;be&nbsp;delivered&nbsp;with.</span>
<span style="color: #666666;">//you&nbsp;can&nbsp;create&nbsp;multiple&nbsp;of&nbsp;these&nbsp;OscMessage&nbsp;variables&nbsp;with&nbsp;different&nbsp;filters&nbsp;to&nbsp;push&nbsp;streams&nbsp;of</span>
<span style="color: #666666;">//different&nbsp;data&nbsp;to&nbsp;GH</span>

<span style="color: #33997E;">void</span> <span style="color: #006699;"><b>setup</b></span>() {  
&nbsp;&nbsp;<span style="color: #006699;">size</span>(400, 400);
&nbsp;&nbsp;
&nbsp;&nbsp;oscP5&nbsp;=&nbsp;<span style="color: #33997E;">new</span> OscP5(<span style="color: #33997E;">this</span>, 6882); 
&nbsp;&nbsp;myBroadcastLocation&nbsp;=&nbsp;<span style="color: #33997E;">new</span> NetAddress(<span style="color: #7D4793;">&quot;localhost&quot;</span>, 6881);  <span style="color: #666666;">//broadcast to port 6881 and</span>
&nbsp;&nbsp;<span style="color: #666666;">//receive at 6882 /use the opposite for GH</span>
&nbsp;&nbsp;<span style="color: #666666;">//the numbers &quot;6881&quot; and &quot;6882&quot; are arbitrary. </span>
&nbsp;&nbsp;<span style="color: #666666;">//&quot;localhost&quot; is for sending to my own PC. To send over ethernet or other devices you have to enter </span>
&nbsp;&nbsp;<span style="color: #666666;">//an IP number.</span>

&nbsp;&nbsp;<span style="color: #669900;">for</span> (<span style="color: #E2661A;">int</span> i=0;i&lt;nX;i++) { <span style="color: #666666;">//fill in the array //in this case with random numbers</span>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #669900;">for</span> (<span style="color: #E2661A;">int</span> j=0;j&lt;nY;j++) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;myArray[i][j]=<span style="color: #33997E;">new</span> <span style="color: #006699;">PVector</span>(<span style="color: #006699;">random</span>(i*20, (i+1)*20), <span style="color: #006699;">random</span>(j*20, (j+1)*20));
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}
}

<span style="color: #33997E;">void</span> <span style="color: #006699;"><b>draw</b></span>() {
&nbsp;&nbsp;
&nbsp;&nbsp;<span style="color: #006699;">background</span>(0);
&nbsp;&nbsp;<span style="color: #E2661A;">String</span> toSend=<span style="color: #7D4793;">&quot;&quot;</span>; <span style="color: #666666;">//create a new string to assemble the message</span>
&nbsp;&nbsp;arrayMsg=<span style="color: #33997E;">new</span> OscMessage(<span style="color: #7D4793;">&quot;/array&quot;</span>);
&nbsp;&nbsp;<span style="color: #669900;">for</span> (<span style="color: #E2661A;">int</span> i=0;i&lt;nX;i++) {
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #669900;">for</span> (<span style="color: #E2661A;">int</span> j=0;j&lt;nY;j++) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #666666;">//Display array points in Processing</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #006699;">pushMatrix</span>(); <span style="color: #666666;">//to actually compare the prossecing display window with grasshopper we</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #666666;">//have to change the coordinate system of processing so as the positive Y values are</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #666666;">//upwards. This is done by translate and scale(1,-1) (something like mirror)</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #006699;">translate</span>(<span style="color: #D94A7A;">width</span>/2,<span style="color: #D94A7A;">height</span>/2); 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #006699;">scale</span>(1,-1);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #006699;">stroke</span>(255);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #006699;">ellipse</span>(myArray[i][j].x, myArray[i][j].y, 3, 3); 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #006699;">line</span>(-<span style="color: #D94A7A;">width</span>,0,<span style="color: #D94A7A;">width</span>,0); <span style="color: #666666;">//draw X and Y axis</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #006699;">line</span>(0,-<span style="color: #D94A7A;">height</span>,0,<span style="color: #D94A7A;">height</span>);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #006699;">popMatrix</span>();

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #666666;">//now assemble the message to send in a string</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;toSend+=<span style="color: #7D4793;">&quot;{&quot;</span>; 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;toSend+=myArray[i][j].x&nbsp;+&nbsp;<span style="color: #7D4793;">&quot;,&quot;</span>;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;toSend+=myArray[i][j].y&nbsp;+&nbsp;<span style="color: #7D4793;">&quot;,&quot;</span>;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;toSend+=myArray[i][j].z&nbsp;+&nbsp;<span style="color: #7D4793;">&quot;}&quot;</span>;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #666666;">//this assembles &quot;{x,y,z)&quot; : a &quot;Grasshopper ready&quot; point</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #669900;">if</span> (j&lt;nY) toSend+=<span style="color: #7D4793;">&quot;*&quot;</span>; <span style="color: #666666;">//this places a &quot;*&quot; between points of the same row</span>
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #669900;">if</span> (i&lt;nX) toSend+=<span style="color: #7D4793;">&quot;&amp;&quot;</span>; <span style="color: #666666;">//this places a &quot;&amp;&quot; between points of different columns </span>
&nbsp;&nbsp;}

&nbsp;&nbsp;arrayMsg.<span style="color: #006699;">add</span>(toSend); <span style="color: #666666;">//this loads the string to the message container prior to sending</span>
&nbsp;&nbsp;<span style="color: #666666;">// you can actually load(add) many strings/values before sending them. The OSC library</span>
&nbsp;&nbsp;<span style="color: #666666;">//separates these values with commas. Thats why in this example we &quot;devised&quot; this trick with</span>
&nbsp;&nbsp;<span style="color: #666666;">//with * and &amp; to send the whole array as a single string, everytime the &quot;void draw&quot; runs,  </span>
&nbsp;&nbsp;<span style="color: #666666;">//and separate the array into rows and columns in Grasshopper.</span>
&nbsp;&nbsp;<span style="color: #666666;">//The way we did this was to assemble &quot;Grasshopper-ready&quot; points: {x,y,z}</span>
&nbsp;&nbsp;<span style="color: #666666;">//in the case of a 3x3 array, the string will be something like this:</span>
&nbsp;&nbsp;<span style="color: #666666;">// {0,0,0}*{1,0,0)*{2,0,0}&amp;{0,1,0}*{1,1,0)*{2,1,0}&amp;{0,2,0}*{1,2,0)*{2,2,0}</span>
&nbsp;&nbsp;<span style="color: #666666;">//which in grasshopper we will read more or less like this:</span>
&nbsp;&nbsp;<span style="color: #666666;">//{0,0,0},{1,0,0),{2,0,0}</span>
&nbsp;&nbsp;<span style="color: #666666;">//{0,1,0},{1,1,0),{2,1,0}</span>
&nbsp;&nbsp;<span style="color: #666666;">//{0,2,0},{1,2,0),{2,2,0}</span>

&nbsp;&nbsp;oscP5.send(arrayMsg,&nbsp;myBroadcastLocation);&nbsp;<span style="color: #666666;">//this is the actual command that sends</span>
&nbsp;&nbsp;<span style="color: #666666;">//the message</span>
}

<span style="color: #33997E;">void</span> <span style="color: #006699;"><b>keyPressed</b></span>() { <span style="color: #666666;">//this is to check refresh rate. press a key to reset array values</span>
&nbsp;&nbsp;<span style="color: #669900;">for</span> (<span style="color: #E2661A;">int</span> i=0;i&lt;nX;i++) {
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #669900;">for</span> (<span style="color: #E2661A;">int</span> j=0;j&lt;nY;j++) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;myArray[i][j].<span style="color: #006699;">set</span>(<span style="color: #006699;">random</span>(i*20, (i+1)*20), <span style="color: #006699;">random</span>(j*20, (j+1)*20), 0);
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}
}

<span style="color: #666666;">//have&nbsp;fun&nbsp;and&nbsp;share&nbsp;alike&nbsp;:)</span>

</pre></body></html>`

## Current Behavior
I check all the environment and can't find a bug.

## Your Environment
* Processing version:3.3.5
* Operating System and OS version: win 10 pro
* Other information:

**Comment by benfry** [comment]
Please use forum.processing.org for coding questions, or contact the author of oscp5 is you're having trouble with that library.
