### ISSUE TITLE
Error "is out of range" appears incorrectly

### ISSUE THREAD

**Issue by CLOVIS-AI** [processing/processing#5260]
## Description
The literals 06258 and 06259 produce a "The literal 06258 of type int is out of range", even though it is far smaller than `Integer.MAX_VALUE`

## Expected Behavior
Alike literals 06257 or 06260 or any other, the code below should compile. I do not know if the two literals specified above are the only affected, they are the two I found by testing.

## Current Behavior
Literals 06258 and 06259 produce a compile-error.

## Steps to Reproduce
1. Use the code : 
```
int x = 06258;
println(x);
```
2. Hit the "Execute" button
3. Error shows up : "The literal 06258 of type int is out of range"

## Your Environment
* Processing version: 3.3.5
* Operating System and OS version: Debian 8

**Comment by jeremydouglass** [comment]
This is a programming error in Java, not a bug.

Leading-zero numbers in Java are octal -- however not all octal are valid.

10102 is invalid binary. 201A is invalid decimal. Both 08 and 06258 are invalid octal.

For more details see:

https://stackoverflow.com/questions/7218760/why-is-08-not-a-valid-integer-literal-in-java

If you have more questions, visit the forum for programming discussios:

https://forum.processing.org/two/discussions
