### ISSUE TITLE
processing can't work with VPN

### ISSUE THREAD

**Issue by EECSGEEK** [processing/processing#5261]
processing version(3.34、 3.35、 3.36)

## Description
turn on VPN->can't open processing
or
turn on processing->can't turn on VPN

I try to edit preferences.old file add proxy address
but don't work!

## Expected Behavior
whether VPN is open, processing can work

## Current Behavior

None

## Steps to Reproduce

1.turn on VPN
2.can't open processing

## Your Environment
* Processing version: 3.36
* Operating System and OS version: win10
* Other information: VPN proxy

## Possible Causes / Solutions
arduino IDE is alike processing,
but arduino software can work in VPN
arduino and processing both develop on Java,
but arduino software don't have this problem

**Comment by crazymaster** [comment]
> I try to edit preferences.old file add proxy address
> but don't work!

Why did you edit preferences.old? 
Don't you have to edit preferences.txt?

**Comment by EECSGEEK** [comment]
C:\Users\76320\AppData\Roaming\Processing>type preferences.txt
chooser.files.native=true
console.auto_clear=true

............
preproc.substitute_unicode=true
preproc.web_colors=true
proxy.http.host=127.0.0.1:3323
proxy.http.port=127.0.0.1:3323
proxy.https.host=127.0.0.1:3323
proxy.https.port=127.0.0.1:3323
proxy.socks.host=127.0.0.1:3323
proxy.socks.port=127.0.0.1:3323
proxy.system=true
recent.count=10

> Don't you have to edit preferences.txt?
After I edit preferences.txt(add proxy port) successfully and reboot my computer
reset my VPN, now I can use processing with VPN
Since I can't learn processing without google, but China can't visit google without VPN.

now I can use processing and google at the same time.

**Comment by JakubValtar** [comment]
Seems to be solved, closing.
