### ISSUE TITLE
No menu items appear with 3.3.6 on MacOSX High Sierra

### ISSUE THREAD

**Issue by Hzikajr** [processing/processing#5272]
Hi guys,
I did download a copy of Processing 3.3.6 from processing.org and launched it on my Mac with OSX High Sierra (10.13).
I could run my sketch and install extra modes or libraries correctly, but I can't see any single item on the top bar (things like "File" or "Edit" or "Help")....
Additionally, quitting processing app can't be done by any control except force quit.

Does anyone have a solution for this phenomenon?

**Comment by SekiTakakazu** [comment]
Unfortunately no solution. The same problem appears in the Arduino IDE. [Martino Facchin](https://github.com/facchinm) solved this in his latest hourly builds ... ok, that doesn't help here but it gives hope for a close solution! You can find the discussion for Arduino [here](https://github.com/arduino/Arduino/issues/6548).

**Comment by d3p** [comment]
a quick temporary fix is to force the language to english. open `Terminal` and run `defaults write org.processing.app AppleLanguages '(en)'`

BTW the issue affect all ( or most ) java applications … e.g also the *Arduino IDE* which can be fixed with `defaults write cc.arduino.Arduino AppleLanguages '(en)'` ( via https://github.com/arduino/Arduino/issues/6548 )

**Comment by benfry** [comment]
Yeah, it's an Apple/Oracle bug… more discussion here: https://youtrack.jetbrains.com/issue/JRE-434

In the meantime you can try the fix in the previous comment, or the other fixes in the link here. Unfortunately the languages fix will screw up localization a little bit, but that's decidedly less of a problem than no menus at all.

**Comment by Hzikajr** [comment]
Thank you for all of your comments. I think I can fix the issue temporarily by the method from @d3p.
I'll keep tracking on this issue...

**Comment by benfry** [comment]
Installing Apple's Java 6 is also said to fix the issue: https://support.apple.com/kb/DL1572?locale=en_US Though after doing so, you should check the App Store for security updates.

**Comment by benfry** [comment]
And the official bug tracker is here: https://bugs.openjdk.java.net/browse/JDK-8188085

**Comment by benfry** [comment]
That bug is now closed and marked EXTERNAL, which suggests that Apple has confirmed and will have a fix in a future release. However, macOS 10.13.1 beta 2 doesn't yet have the fix.

**Comment by benfry** [comment]
For anyone having this problem, does it still happen with the recent 10.3.2 update?

**Comment by Niels-NTG** [comment]
It does **not** happen anymore for me. (MacOS High Sierra 10.13.2 (17C88), Processing 3.3.6)

**Comment by benfry** [comment]
Meaning that things are working on 10.13.2?

**Comment by benfry** [comment]
Hey folks, can anyone confirm that this is working for them (only for people for whom it *was not* working before? This didn't affect everyone…)

**Comment by lauraellengreene** [comment]
I continue to be unable to run Processing on High Sierra v. 10.13.2. I have re-installed Processing, updated Java but once I open the Processing Application it does not allow me to type or use drop down menu. After about a minute, the spinny ball of death appears and Force quit window confirms program is not responding. Attempting to use the program for a Grad Project, help!

**Comment by benfry** [comment]
That sounds like a different issue @lauraellengreene… Check out the [troubleshooting page](https://github.com/processing/processing/wiki/Troubleshooting) or try https://forum.processing.org for questions.

Can @Hzikajr @SekiTakakazu @d3p or any others confirm that it's working in 10.13.2 without needing the `defaults write` fix?

**Comment by benfry** [comment]
No responses; assume Apple has fixed the issue.
