### ISSUE TITLE
With many tabs, can't scroll using drop down menu

### ISSUE THREAD

**Issue by aarondbaron** [processing/processing#5273]
## Description

i have many tabs in an application i'm building.   the drop down menu can only display about 25-30 or so.  Then i have to use ctrl alt and left or right arrow to get to the tab i want.  

## Expected Behavior

I'd like there to be a scroll feature.

## Current Behavior

there currently is no scroll feature , so when many tabs that go beyond the resolution of the screen, it doesnt show.

## Steps to Reproduce

to reproduce, just make a bunch of new tabs/classes

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version:  Windows 10
* Other information:

**Comment by kfrajer** [comment]
Would the **Tab Manager**, which you can install via the menu "Add tool", help in your case? 

I can see this to be a desirable feature. 

Kf

**Comment by aarondbaron** [comment]
Actually Tab Manager is very helpful, thank you for pointing it out. I feel it would be nice to be a standard thing that comes with the IDE rather than having to download it though.

**Comment by benfry** [comment]
Closing this one as it's the same thing covered here: https://github.com/processing/processing/issues/1968#issuecomment-96377621
