### ISSUE TITLE
It was not meant to be

### ISSUE THREAD

**Issue by gedapeleda** [processing/processing#5276]
## Description

When I start the program I get the blue loading and then a fatal error saying it was not meant to be
![scann](https://user-images.githubusercontent.com/32372233/30985887-07537d8a-a492-11e7-87b0-37e0e762740c.PNG)

## Your Environment
Windows 10 x64
Processing 3.3.6
I tried  to redownload , admin, compatability
Same results

**Comment by benfry** [comment]
Duplicate of https://github.com/processing/processing/issues/4929
