### ISSUE TITLE
Problem with video capture and win8, GStreamer error

### ISSUE THREAD

**Issue by erwrow** [processing/processing#5277]
## Description

I have an windows tablet that runs on a intel Z3735G processor, and when i try to access to the webcam it throws the following error:

(java.exe:1172): GStreamer-CRITICAL **: _gst_util_uint64_scale_int: assertion `denom > 0' failed

## Steps to Reproduce

It can be reproduced with the example: "GettingStartedCapture". Although it does show the list of all available cameras.

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: windows 8, 32 bits
* Other information: Processor Intel Z3735G and Intel camera

## Possible Causes / Solutions

I believe that the problem is win 8

**Comment by gohai** [comment]
Hi @erwrow. Bug reports concerning Processing's video library should go here: https://github.com/processing/processing-video

**Comment by FrankOcean11** [comment]
any resolutions ?
