### ISSUE TITLE
Problem adding texture to square

### ISSUE THREAD

**Issue by NetSlum89** [processing/processing#5278]
Hi everyone,

New to the forums, and I can't seem to find a solution to this problem...

I'm currently working on a project for school. I'm trying to make these little squares here Tie Fighters from Star Wars using this image: **http://www.scifi3d.com/images/wip/1808_src_tiefighter14.jpg**. I can't seem to make the rectangles display this texture though. Here is the code I'm working with:

Square[] Squares;
int x, y, speed;
float direction;
PImage tie;
PShape rect;

 
void setup() 
{
  size(800, 600);
  gameReset();
  
  tie = loadImage("tie.png");
  rect=createShape(RECT, 0,0,25,25);
  rect.setTexture(tie);
  
}
 
void draw() 
{
  background(255);
 
  for (int i = 0; i < Squares.length; i++)
  {
    Squares[i].update();
    Squares[i].display();
  }
}
 
void gameReset() {
  Squares = new Square[20];
  for (int i = 0; i < Squares.length; i++)
  {
  Squares[i] = new Square((int)random(width), (int)random(height), (int)random(7), 0);
  }
}
 
class Square {
  int x, y, speed;
  float direction;
 
  Square(int _x, int _y, int _s, int _d)
  {
    x = _x;
    y = _y;
    speed = _s;
    direction = _d;
  }
 
  void update() {
    x += speed * cos(TWO_PI);
    y += speed * sin(TWO_PI);
    if (x > width) {
      x = 0;
    } else if (x < 0) {
      x = width;
    }
    if (y > height) {
      y = 0;
    } else if (y < 0) {
      y = height;
    }
    
    
  }
 
 
  void display() {
    rect(x,y,25,25);
    rect.setTexture(tie);
    
    
  }
}

//////////

I feel like the problem is in the square/rect code I have going on. I know I also might not need to even use squares or rectangles to get an image to just fly across the screen, but I'm not sure how to do that either. Any advice on how to texture these squares, or simply get rid of the squares and add just the image in place of them?

This is part of a bigger code I'm working on, and this will be added to that. I'm just having problems with this portion of the project, though.

Thanks for checking it out.

**Comment by jeremydouglass** [comment]
@NetSlum89 -- as it said right at the top of the form you filled out:

> Issues are for new bugs & feature requests.
> **For coding questions visit https://forum.processing.org**

This is a coding question. Please post it on the forum -- not as a bug.
