### ISSUE TITLE
When building new clone, 404 from jre-downloader

### ISSUE THREAD

**Issue by Buskcoin** [processing/processing#5284]
## Expected Behavior
When running `sudo ant build`, I was expecting the processing downloader to succeed in downloading java.

## Current Behavior
After running `sudo ant build` or `sudo ant run`:

```
jre-download:

[downloader] Redirecting to https://edelivery.oracle.com/otn-pub/java/jdk/8u144-
b01/090f390dda5b47b9b721c7dfaa008135/jre-8u144-linux-x64.tar.gz

[downloader] Redirecting to http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jre-8u144-linux-x64.tar.gz?AuthParam=1508292321_930435223beb13b8c396855ea848dd8c

[downloader] Header Name:Accept-Ranges

[downloader] Header value:bytes

[downloader] 

[downloader] Header Name:null

[downloader] Header value:HTTP/1.1 404 Not Found

[downloader] 

[downloader] Header Name:Server

[downloader] Header value:Apache

[downloader] 

[downloader] Header Name:ETag

[downloader] Header value:"477d9862374177c810b0b7d73b4f1e53:1319689022"

[downloader] 

[downloader] Header Name:Connection

[downloader] Header value:keep-alive

[downloader] 

[downloader] Header Name:Last-Modified

[downloader] Header value:Wed, 31 Aug 2011 20:28:54 GMT

[downloader] 

[downloader] Header Name:Content-Length

[downloader] Header value:7073

[downloader] 

[downloader] Header Name:Date

[downloader] Header value:Wed, 18 Oct 2017 02:03:21 GMT

[downloader] 

[downloader] Header Name:Content-Type

[downloader] Header value:text/html

[downloader] 
```

## Steps to Reproduce

1. clone a fresh processing so that the downloader will look for the jre.
2. run `sudo ant build`
3. wait

## Your Environment

 

* Processing version: latest
* Operating System and OS version: Kubuntu, and raspbian 
* Other information:

## Possible Causes / Solutions
I believe this is related to the latest release of Java. Oracle must have changed the download link. Or maybe I am being block from downloading it for some reason of my own.

**Comment by benfry** [comment]
Thanks for the report. A new release arrived today, so they may have changed something about the old link. Or maybe just bumping to the newer release will take care of it. 

Also… there's no need to use `sudo` when building, I'd definitely avoid that.

**Comment by benfry** [comment]
Now fixed in the source by using 8u152.
