### ISSUE TITLE
Sketch becomes unresponsive when holding 'a' key

### ISSUE THREAD

**Issue by galsasson** [processing/processing#5285]
## Description

A sketch becomes unresponsive when holding the 'a' key, using the following code:
```
void setup()
{
  size(100,100);
}

void draw() {}

void keyPressed()
{
  rect(0,0,100,100);
}

void keyReleased()
{
  background(0,0,0);
}

```

## Expected Behavior
Expecting the sketch to continue to respond to key presses.

## Current Behavior
Sketch gets unresponsive, even to Esc.
I found that sometimes after pressing a different key for a while the sketch resumes to be responsive.

## Steps to Reproduce
1. Launch the provided sketch
2. Press 'a' for more than 1 second
3. Release 'a'
4. Sketch is unresponsive

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: macOS Sierra 10.12.6
* Other information:

**Comment by benfry** [comment]
Probably this: https://github.com/processing/processing/wiki/Troubleshooting#key-repeat-on-macos-sierra

**Comment by galsasson** [comment]
Yes, thats the issue.
After disabling the little menu everything works properly.
