### ISSUE TITLE
Delay in Serial plot using Processing

### ISSUE THREAD

**Issue by SureshaNS** [processing/processing#5288]
## Description
We are using Processing to plot the incoming serial data. 
Incoming data is of 'Float' type & there is a value arriving at the serial port once in 4mS. 

## Expected Behavior
Ideally processing should plot the data immediately without any delay. 
In this case, data plotting will get completed as soon as the data arrival stops at the serial port. 

## Current Behavior
Processing is taking time to receive & plot each value from serial port. 
This delay to read serial data value & plot is around 16mS. 
Due to this delay, Processing plot will not be real time when compared to incoming serial data.

## Steps to Reproduce

1. Send data at higher rate from to Serial port of PC (At a rate of 250Hz)
2. Verify that the plotting takes higher time to plot compared to incoming data rate

Below is the code we are using for the plot.
[Serial_Plotter.txt](https://github.com/processing/processing/files/1406976/Serial_Plotter.txt)

## Environment
* Processing version: 3.3.6
* Operating System and OS version: Windows 8

Is there any way to decrease this delay so that data can be plotted real time. 
Looking forward to valuable suggestions. 

Thanks,
Suresha

**Comment by benfry** [comment]
The forum (forum.processing.org) is a better place for coding questions like this. The issue here is most likely less to do with a bug than in understanding how the `draw()` loop works and how that relates to incoming data from serial.
