### ISSUE TITLE
apps placed in Login Items don't play properly help

### ISSUE THREAD

**Issue by GeorgeRoland** [processing/processing#5289]
I am using a MacMini running OS X 10.7.5 and Processing 2.2.1. My app runs fine when I double-click its icon. If I put it into the Login Items for the default account launched at startup, the app doesn't play properly. The mouse pointer shows, the dock shows and the menu shows with my sketch running under them. None of this occurs when the app icon is double-clicked.
Has anyone solved this?

**Comment by benfry** [comment]
Processing 2.x is no longer supported, sorry. This is a better question for the forums.
