### ISSUE TITLE
NoClassDefError on StructuralPropertyDescriptor when starting 3.3.6 on Windows 10

### ISSUE THREAD

**Issue by flamixin** [processing/processing#5290]
## Description

I can't boot processing 3.3.6 editor and it throws me a Serious Problem dialog after the welcome image.
It tells me to report so I'm here.

I tried serval old versions I stashed on my hard drive:
3.3.5 bootable but codes won't run. 
3.3 Working perfectly.
3.1 Working perfectly.
3.0.1 disappeared after the welcome image.

## Expected Behavior

Editor should show up and codes should runnable

## Current Behavior

Throws me this.
<url>https://forum.processing.org/two/uploads/imageupload/131/XXEUQT3XYZ4I.jpg </url>

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: Windows 10 Pro 64Bit
* Other information:

**Comment by benfry** [comment]
Hm, a couple things to try:
* Did you copy the Processing folder out of the .zip file that you downloaded? 
* Try searching your system for a `.jar` file with `jdt` somewhere in the name. It might be in a place that it's causing a conflict. 
* If you're on a non-English system, try moving the Processing folder to the root of your C:\ drive and see if that works.
Let us know…

**Comment by flamixin** [comment]
Hi benfry

I'm using English system and I did extract the zip file. 

Nothing found from searching jdt suffixed with .jar except in processing folders. I deleted the JRE from my system after I meet the trouble to eliminate the possibility of conflict.

**Comment by flamixin** [comment]
I formatted and reinstalled my Win 10 (for some other reasons) but 3.3.6 still no luck. I found a error log about RegCreateKeyEx has error 5 in appdata/processing folder. I guess it could be an incompatible issue with Java, because my hardware is 6 years old which win10 barely fitted in.

**Comment by kfrajer** [comment]
Please provide java version. Open a Command prompt window (Hit Win key + R and type **cmd**, then press ENTER) and type **javac -version**.

One more question. Was Processing running on your machine before of was this the first time? 

Kf

**Comment by flamixin** [comment]
I haven't install any JRE yet, so  **javac -version** returns nothing. 
Last time I use processing is one-and-half months ago before a windows 10 major update and a java update.  Processing version 3.3, nothing ever goes wrong before this.

**Comment by flamixin** [comment]
After Windows 10 1709 update everything back to normal !!  This problem seems like a java glitch in some recent Win10 builds. I saw many threads about issues of running java with recent builds of windows 10. Case closed.

**Comment by benfry** [comment]
Very odd; thanks for the update.
