### ISSUE TITLE
Background transparency not working.

### ISSUE THREAD

**Issue by mathacka** [processing/processing#5293]
"backgound(0,0);" command is not adding alpha channel to incorporate transparency.

* Processing version: 3.3.6
* Operating System and OS version: Windows 10
* Other information:

**Comment by m8w** [comment]
I have never seen a double numbered background command usually something like 
Background(255) :  also word background is missing the "r" letter after the g in background.

this is code for alpha channel opacity in processing.. from the color tutorial
seems the background value is zero...
______________________________

size(200,200);
background(0);
noStroke();

// No fourth argument means 100% opacity.
fill(0,0,255);
rect(0,0,100,200);

// 255 means 100% opacity.
fill(255,0,0,255);
rect(0,0,200,40);

// 75% opacity.
fill(255,0,0,191);
rect(0,50,200,40);

// 55% opacity.
fill(255,0,0,127);
rect(0,100,200,40);

// 25% opacity.
fill(255,0,0,63);
rect(0,150,200,40);

**Comment by Sardtok** [comment]
Are you using background on the main display, or a PGraphics object made with createGraphics?

From the background documentation:
> It is not possible to use the transparency alpha parameter with background colors on the main drawing surface. It can only be used along with a PGraphics object and createGraphics().

**Comment by kfrajer** [comment]
Please check the reference: https://processing.org/reference/createGraphics_.html

> Unlike the main drawing surface which is completely opaque, surfaces created with createGraphics() can have transparency. This makes it possible to draw into a graphics and maintain the alpha channel. By using save() to write a PNG or TGA file, the transparency of the graphics object will be honored.

Any further clarification, please post in the forum: https://forum.processing.org/two/

Kf

**Comment by mathacka** [comment]
from the processing page

background(rgb)
background(rgb, alpha)
background(gray)
background(gray, alpha)
background(v1, v2, v3)
background(v1, v2, v3, alpha)
background(image)

alpha | float: opacity of the background
-- | --

**Comment by Sardtok** [comment]
Yes, that's correct. However, alpha cannot be used on the main display. I don't want to get too technical about this, but this has to do with how graphics cards work and how you optimize rendering by drawing to different parts of memory, and simply change an address for where data for the screen is sent from.

Now you can create a surface/framebuffer that is not the main display buffer:

    PGraphics myGraphics;
    void setup() {
        size(800, 600, P2D);
        myGraphics = createGraphics(width, height);
    }
    
    void draw() {

**Comment by dackdel** [comment]
working with a transparent display right now, this is so relevant

**Comment by benfry** [comment]
Locking since this is not a feature, and it's clearly explained as such in the reference.
