### ISSUE TITLE
Android Mode - Processing-3.3.6

### ISSUE THREAD

**Issue by JamesPwi** [processing/processing#5294]
Is there any way i can use this library with android mode inside processing language ?

**Comment by kfrajer** [comment]
@JamesPwi Please post this question in the forum: https://forum.processing.org/two/

Make sure you explore the Android section: https://forum.processing.org/two/discussions/tagged/android

For example: 
https://forum.processing.org/two/discussion/comment/98031/#Comment_98031  [ !!! ]
https://forum.processing.org/two/discussion/comment/107069/#Comment_107069
https://forum.processing.org/two/discussion/comment/105467/#Comment_105467
https://forum.processing.org/two/discussion/comment/103761/#Comment_103761

Kf

**Comment by JamesPwi** [comment]
Hello Kfrager 

its nice to see you here  .

but my code compiles  without using "import.processing.serial.*;" but when i want to use this library its not working with Android mode and showing error to me .

**Comment by gohai** [comment]
@JamesPwi Issues with the Android mode should go here: https://github.com/processing/processing-android

That said, Processing's Serial library is for Windows/macOS/Linux only, and does not support the Android runtime.
