### ISSUE TITLE
Windows 10 64bit and 32 bit version freeze on save as

### ISSUE THREAD

**Issue by androvisuals** [processing/processing#5295]
## Description

Runs fine, go to save as, can browse to 2 or 3 locations, it then just freezes up, rest of the computer is fine

No clue, should just save I suppose
## Expected Behavior

That save as allows me to go to a location and change the file name of the file to be saved 

## Current Behavior

It crashes

## Steps to Reproduce

1.Read above
2.
3.

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: windows 10 up to date
* Other information:

**Comment by kfrajer** [comment]
I cannot reproduce your problem. I have Win 10 x64 and Processing 3.3.6 64bit. I can hit "Save as" on a running sketch and browse different folder structures without any problem. Can you provide your Java version?  At the command prompt, type: _javac -version_ . I get on my machine: **javac 1.8.0_121**

Usually when you hit "Save as", you have to wait like 10 or 15 seconds so for Processing to create the alternate folder structure and copy the files. However, base on your description, you are saying Processing crashes when browsing the different folder and subfolders? 

Kf

**Comment by androvisuals** [comment]
So i can wait up to 2 minutes and its still frozen with processing, not the rest of the computer that works fine.
My java version is:
**javac 9**
Do's this matter though ? I thought that Processing used its own version of Java.

**Comment by VictorGaiva** [comment]
It probably is something to do with Windows it self, since navigating thought the file system is made by an external call. 

Try making the same actions in the explorer window but in a different program.

**Comment by gohai** [comment]
@androvisuals Do you perhaps have some network shares set up, or similar, that could take a while before they time out?

**Comment by flamixin** [comment]
This may cause by some bugs in recent builds of Win10. Try update your Windows 10 to 1709 it may helps.

**Comment by androvisuals** [comment]
Awesome, 1709 fixed it. Thanks !
