### ISSUE TITLE
dim edit menus as appropriate during selection/no selection/etc

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#53]
_Original author: b...@processing.org (June 06, 2010 23:51:07)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=33

Comment from fry, 2005-05-12 20:33

just lots of things to make the app behave properly. 

these situations need to be thoroughly catalogged so that fixing can begin.
anyone?

_Original issue: http://code.google.com/p/processing/issues/detail?id=14_

**Comment by GKFX** [comment]
I'm taking this. It's half-done anyway.

**Comment by benfry** [comment]
This one's been implemented.

**Comment by GKFX** [comment]
@benfry No it hasn't. "Copy as HTML", "Find next", "Find previous" and "Use selection for find" aren't done. I'll get on with it now.
