### ISSUE TITLE
Serial Library outputting incorrect values from Arduino 101

### ISSUE THREAD

**Issue by cjsimon** [processing/processing#5300]
## Description
The serial library seems to be reading in the wrong values from the Arduino 101 serial.

## Expected Behavior
The values from the Arduino 101 com port. See below.

## Steps to produce
![serial](https://user-images.githubusercontent.com/8083922/32401190-6b7ae090-c0c7-11e7-88d4-7487d08ae21f.png)

## Your Environment
This was tested on a MacBook Air running Mac OS High Sierra using an Arduino 101 and Processing 3.3.6.

## Possible Causes / Solutions
Potentially rewriting the library to support the 101 if necessary at all?

**Comment by gohai** [comment]
@cjsimon If you look closely at the values in Processing's console, you'll see the reoccurring number 13, followed by 10: those are the ASCII values for the characters coming in. 13 is the character return (`\r`), 10 is the new-line character (`\n`), other numbers are the ASCII codes for the different digits.

In other words: this is working exactly as it should. To instead get the bytes being sent by the Arduino, which is what you seem to want, try using e.g. `readStringUntil(10)`. This will return one line of your output.

**Comment by cjsimon** [comment]
That makes so much more sense. Thank you for the explanation!
