### ISSUE TITLE
P3D don't work on AMD dynamic switchable graphics

### ISSUE THREAD

**Issue by yangwenbo99** [processing/processing#5308]
## Description

I have a laptop with a low end AMD graphicial card R5 230M. Since my Intel integrated card gave me a slow performance in a program, I tried to use AMD card to render this file. (Using PRIME) Sadly, it can not work. 

## Expected Behavior

The program can normally run.

## Current Behavior

Normal window does not open, and the error informations are:
`
java.lang.InternalError: XXX0 profile[1]: GL3bc -> profileImpl GL4bc !!! not mapped 
	at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2071)
	at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1954)
	at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1875)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1842)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2297)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:988)
	at com.jogamp.opengl.GLProfile.getGL2ES2(GLProfile.java:909)
	at processing.opengl.PSurfaceJOGL.initGL(PSurfaceJOGL.java:192)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:136)
	at processing.core.PApplet.initSurface(PApplet.java:10889)
	at processing.core.PApplet.runSketch(PApplet.java:10776)
	at processing.core.PApplet.main(PApplet.java:10476)
`

## Steps to Reproduce

1. Write a processing file, use P2D or P3D.
2. DRI_PRIME=1 processing-java --sketch=../_theTestFile_/ --run

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: Arch Linux
* Other information:
I'm using PRIME to manage hybrid graphics.

**Comment by gohai** [comment]
This issue seems to be rather deep down inside JOGL, which are the OpenGL bindings that the P3D renderer uses. Unfortunately JOGL hasn't received much love lately, and their website https://jogamp.org/bugzilla/ seems to be down as well :(

**Comment by adrianhe** [comment]
I experience the same problem with Radeon R9 270 Graphics Card, OpenGl 4.2, Processing 3.3.6, Ubuntu 16.04 OS

**Comment by AQUILA-SC2** [comment]
# I found a 5min workaround for those who don't want to wait for a java patch.
Had the same issue under **Linux Mint** , R9285 and the new 3.0 Mesa 17.2.8

As being said, the P2D, P3D , OPENGL  issue is with JOGL and occurs since Mesa >17.2.0:
There is a patched class available here :

  https://jogamp.org/bugzilla/attachment.cgi?id=799

**1. Download and save the file**
**2. Go to your processing folder :   processing-3.3.6/core/library/**
**3. In the archive "jogl-all.jar" : open folder jogamp/opengl/**
**4. Copy and paste the file "GLContextImpl.class" here.**

- for me it did overwrite the existing file , but you may have to delete it first.
- don't bother about the other GLContextImpl  $2-$3.classes.

## For me P2D, P3D rendering works perfectly again, Good luck !
# Thanks @julien from jogamp

**Comment by gohai** [comment]
For record, this is the JOGL bug the patch from @AQUILA-SC2 came from: https://jogamp.org/bugzilla/show_bug.cgi?id=1357

@codeanticode @benfry We should get this into any upcoming release - let me know if you want me to go ahead and push an updated `jogl-all.jar`. (The patch makes sense to me, doesn't affect any OS other than Linux, and fixes all contemporary Mesa OpenGL versions.)

**Comment by codeanticode** [comment]
@gohai is there a way to apply the patch at the source code level and rebuild jogl-all.jar?

**Comment by neilcsmith-net** [comment]
@gohai tracking this because it obviously affects us too, but if there's anything I can usefully help with, let me know.  Partly tempted to help with the effort to move to (in my case, return to) LWJGL, but it does look like some things might be happening at the JOGL end finally?!

**Comment by gohai** [comment]
@codeanticode I will rebuild jar. Realized we need to.

**Comment by gohai** [comment]
@yangwenbo99 @adrianhe @AQUILA-SC2 Could you test this `jogl-all.jar` file to see if it still works with your setup? https://sukzessiv.net/~gohai/p5/jogl-all.jar Please also report the output of `glxinfo`. Thanks!
