### ISSUE TITLE
3D-Terrain printing unbelievable slow

### ISSUE THREAD

**Issue by scorixear** [processing/processing#5316]
## Description

I've created a 3d terrain, using the noise function and Vertex shapes, following Daniel Shiffmans tutorial for 3d Terrain Creating. 
## Expected Behavior

By Changing the starting point of the two dimensioned array for the noise function, an illusion should appear that the user would fly over the terrain.
## Current Behavior

The draw function gets called every second which destroys the illusion.
## Steps to Reproduce

1. This is the used code:
[https://hastebin.com/hitanixoze.cpp](https://hastebin.com/hitanixoze.cpp)
2. Use processing 3.3.6 in Java mode
3. There are also the Extended Code Completion from Jonathan Dahlberg and the Font Highlighting Editor from Rostyslav Zatserkonvyi installed

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: Windows 10 64bit
* Other information: It is a personal Computer, not a laptop, it should have enough power to calculate this.

## Possible Causes / Solutions

Resseting the frames to millisecond?
Is there a maximal amount of calculations per Second?

**Comment by gohai** [comment]
@scollovati Link does not work

**Comment by scorixear** [comment]
@gohai now working

**Comment by gohai** [comment]
@scorixear I don't know much about 3D, but I put in a few `println` into your code:

The value of `rows` is 45, the value of `cols` is 6000. This seems excessively large. I can't see how one would see 6000 columns on a 600 pixel output.

Each frame, your code is creating two vertices for `rows * cols`, which means creating (and discarding) 540000 vertices each time through `draw`. If you _really_ needed this large number of vertices you should look into "retained mode" rendering, as described [here](https://processing.org/tutorials/pshape/).

**Comment by jeremydouglass** [comment]
@scorixear -- note that, in general, questions about performance may often be coding questions -- *not* bugs. For coding questions, visit the Processing forum: https://forum.processing.org
