### ISSUE TITLE
sudo ./processing on RPi

### ISSUE THREAD

**Issue by BLCKPSTV** [processing/processing#5318]
For a code I need to run processing on sudo. This works in my Linux ubuntu  environment (when cd'ing to /opt/processing(version))

But when I do this on raspberry, It says command not found? 
```

pi@raspberrypi:~/Documents $ sudo ./processing
sudo: ./processing: command not found
```

Also I don't know the origin of the installation of processing, or where the libraries folder is located. This is not explained in the guide or I overlooked it.

**Comment by gohai** [comment]
@BLCKPSTV The `./` in front of an executable tells the shell to look for it in the current directory. Do you indeed have Processing installed in `~/Documents`?

What happens if you try `sudo processing`?

**Comment by BLCKPSTV** [comment]
It runs! I didn't know it was sym-linked automatically! Ty!! :+1: 

Can be closed!
