### ISSUE TITLE
TextureWrap() unexpected behavior

### ISSUE THREAD

**Issue by MysticalHerobine** [processing/processing#5322]
## Description

TextureWrap() only allows one overall setting per draw() call in Processing 3.x. I'm trying to set it to clamp for a skybox, but also repeat later on for a floor, but only the last TextureWrap() call per draw() cycle appears to be used for all textures.
```processing
textureWrap(CLAMP); // Never used because of the textureWrap(REPEAT) later in the code
texture(rectangle1Texture);
drawRectangleOne();

textureWrap(REPEAT); // Only this texture mode is used for both textures on both of the rectangles
texture(rectangle2Texture);
drawRectangleTwo()
```

## Expected Behavior

I'd expect that when I call TextureWrap() the textures below it would act as the texture mode states until a new TextureWrap() is called changing it.

## Current Behavior

No matter what you've called previously in terms of TextureWrap() the final call is what is applied to all textures that current draw()

## Steps to Reproduce

1. Call the textureWrap(CLAMP) and draw a texture to a rectangle and stretch the texture
2. Call textureWrap(REPEAT) and draw a texture on another rectangle
3. Should cause all textures to wrap

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: Windows 10
* Other information: Not important

## Possible Causes / Solutions

Probably caused by the setup of the texture system.
One way to work around this is by using shaders instead.

**Comment by tolkanabroski** [comment]
@MysticalHerobine 
just for my own education, can you post the hole code to reproduce the bug. 

Did you push and pop the (Texture) Matrix properly?

**Comment by MysticalHerobine** [comment]
@tolkanabroski That may have been my error, but I'm not sure, below is the code (or close to it) that I used when I encountered the problem.
```
pushMatrix(); // Stars a camera world translation
// Skybox drawn into the world
textureMode(NORMAL);
textureWrap(CLAMP);
beginShape(QUAD);
texture(skyboxTextureTop);
// Vertices
endShape(Quad);
// Above was repeated for each face of the skybox cube

//Quad on the ground used as a temporary floor visual:
textureWrap(REPEAT);
beginShape(TRIANGLES);
texture(tile);
 // Vertices went here
endShape();
popMatrix(); // Ends camera world translation
```

I'm assuming because I wasn't pushing or popping a texture matrix it wasn't working, but I also wasn't aware I could do this [I couldn't find it in the Processing Reference List]. I had just guessed that since there wasn't a particular way to actually push() and pop() a texture matrix, then simple switching the mode would allow all texture calls under it to be that specific way.

**Comment by tolkanabroski** [comment]
@MysticalHerobine 
Okay, man, that was what i was thinking, when i saw you ticket. 
Just to be sure we are on the same page - here few links.
forum: [link](https://forum.processing.org) 
a very useful search form: [link](https://forum.processing.org/two/search?Search=TextureMode+unexpected+behavior)   
stackoverflow: [link](https://stackoverflow.com/questions/tagged/processing)   
Be sure what you are trying to do, already been done be humans more then 10000x in processing, a [simple google search](https://www.google.de/search?q=texturemode+processing) might also help. 
Just in case you kind of this type of person, who wants to go more in detail. 
I find it useful to read the blog from codeanticode:
 ((PGraphics2D)g).textureWrap(Texture.REPEAT); 
https://codeanticode.wordpress.com/2012/08/03/shaders-in-processing-2-0-part-2/


Also some cool markdown github tricks:  💫💥🚀
(using duckduckgo ftw)
https://duckduckgo.com/?q=markdown+github

So maybe someone have time 🕔 to give a more detailed explanation what is happening under the hood.
here (again) some useful links: [link](http://www.codinglabs.net/article_world_view_projection_matrix.aspx) | [link](https://stackoverflow.com/questions/16225815/object-world-camera-and-projection-spaces-in-opengl)

- - - 
Yes i agree, lack of documentation.   
 
I also have not time to get through the docs, what i know, you can read between the lines  in 
[reference of RotateY](https://processing.org/reference/rotateY_.html) 
**For example, calling rotateY(PI/2) and then rotateY(PI/2) is the same as rotateY(PI).**  
- - -  
Keep us posted!

![alt-text](http://digitalspyuk.cdnds.net/16/36/480x197/gallery-1473269189-giphy-8.gif)

**Comment by benfry** [comment]
@codeanticode can you confirm whether this is a bug or a misunderstanding (to be closed)?

**Comment by MysticalHerobine** [comment]
Well, I'm a dip and wrote the wrong function down as the problem. The real one is textureWrap(), which is now updated in the original problem. Before, while reading the docs, I had assumed I could do this
```
textureWrap(CLAMP);
// Draw shapes with textures
textureWrap(REPEAT);
// Draw shapes with textures
```
and the textures below CLAMP would be clamped, while REPEAT would cause textures below to repeat.

In order to solve this problem, I have to do something like this:
```
shader(generic_shader);
textureWrap(CLAMP);
// Draw shapes with textures
resetShader();
shader(generic_shader);
textureWrap(REPEAT);
// Draw shapes with textures
resetShader();
```
So, I'm not sure whether it's a bug anymore, or just a misunderstanding by me when I had read the documentation on [textureWrap](https://processing.org/reference/textureWrap_.html)

**Comment by tolkanabroski** [comment]
@MysticalHerobine Okay, i also misunderstood.
yes, all verts get passed to a shader in a singel texture slot for the fragment shader. And [textureWrap](https://processing.org/reference/textureWrap_.html) is kind of misleading, the user clicks with the mouse and might come to the idea he can create to object with difrent textureModes. But under the hood the shader gets recompiled. 

Yes, to get you code running, - you can reset the Shader or use difrent uniforms 
```
PImage[] img = new PImage[2];
  img[0] = loadImage("image1.jpg") ;
  img[1] = loadImage("image2.jpg");

  // some stuff 
  myshader.set("tex[0]", img[0]);
  myshader.set("tex[1]", img[1]);

 //frag.shader
 uniform sampler2D tex[2];
 if(check uv coords)
 fragColor = texture(tex[0],uvv);
 else ... texture(tex[1],uvv)
```

**Comment by codeanticode** [comment]
Hi, yes I think this is a bug. textureWrap() should behave like any other mode-setting function, which change the corresponding parameter until they are called again.

**Comment by benfry** [comment]
@codeanticode Yep, that'd be the correct behavior.
