### ISSUE TITLE
Feature Request: Auto Complete 

### ISSUE THREAD

**Issue by SaiTheCodeGuy** [processing/processing#5323]
## Description
We need auto-complete without ctrl-space!
Though I have only used swift and java, a feature that I found very helpful –and took for granted– was autocomplete. The software automatically suggested how to complete the code, from pre-made functions to variables that had been initialized. When I started to use processing, I did not know there was an auto-complete feature until I went to preferences, but when I saw it, I was a little disappointed that I had to press ctrl-space in order to use it every-time.

## Expected Behavior
I feel that if the software does not always suggest completions to your half-written code, there should be a way for users to toggle it with a certain key, or turn it on and off, instead of having to press ctrl-space every time they want to autocomplete something. I don't know if it's just me, but I really liked Xcode's convenient auto-complete feature.

## Current Behavior
Currently, pressing ctrl-space turn on auto-complete, and just for that line, and it would be more helpful to be able to just toggle it on or off. 

## Possible Causes / Solutions
 As I have stated before, being able to toggle it on and of with a certain key or in the settings/preferences might help.

**Comment by benfry** [comment]
We use the ctrl-space to avoid assaulting beginners with a lot of stuff popping up in the editor. I don't think there's much interest in having it continually pop up, or us having to debug a feature like this to be turned on/off.
