### ISSUE TITLE
IDE Incorrectly handles functions, impossible to add CONDITIONAL or LOOP outside functions

### ISSUE THREAD

**Issue by ronniebasak** [processing/processing#5324]
In the *latest stable* version 3.3.6
There is **definitely** a bug that prevents us to run a code that contains loops outside any function!

## Description
If you add a loop/conditional outside the functions, it's impossible. Not critical, as they can be moved inside setup(), but a bug nevertheless
PROPOSED CHANGE: Possibly fixing how the ide checks for coding error

## Expected Behavior
If you add a conditional/loop outside the functions, it should work

## Current Behavior
Currently it's not possible to add any if/for loops outside the func

## Steps to Reproduce
Try this:
for(int i=0; i<2; i++){

}
void setup(){

}

## Your Environment
* Processing version: 3.3.6
* Operating System and OS version: Linux Mint 18.2
* Other information:

**Comment by gohai** [comment]
Not a bug - as soon as you put in `setup`, your sketch is using Processing's "active mode" semantics, and the only things valid outside functions are declarations. See: https://stackoverflow.com/a/6660645
