### ISSUE TITLE
windows defender blocks processing 3.3.6

### ISSUE THREAD

**Issue by eyaler** [processing/processing#5329]
library/core.jar identified as TrojanDownloader:Java/Vigorf.A

**Comment by benfry** [comment]
Did you download from a different location than processing.org (or the Github page)? 

If not, it sounds like a false positive or Windows Defender problem… We've got over a thousand Windows downloads a day, and this release has been out for over two months, so out of ~70-80k people this is the first report.

**Comment by eyaler** [comment]
official site

**Comment by DiegoMC9** [comment]
second report of detecting it as a trojan downloader

**Comment by benfry** [comment]
Not sure what we can do here. It's not a trojan, obviously, but we can't control what Windows Defender does. 

Perhaps you can report it to Microsoft? I've already wasted time going through their false report process the very first time this happened, and there was never any response or resolution.

For everyone having this problem, does it remove `core.jar` and then give you an error about `java.lang.NoClassDefError: processing/core/PApplet`?

**Comment by BuckStarchaser** [comment]
Thanks to tolkanabroski for providing a step-by-step workaround in thread: https://github.com/processing/processing/issues/5374

**Comment by dylmye** [comment]
Make sure to submit it here if you haven't already:

https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by benfry** [comment]
This should be fixed in 3.3.7 because it'll have a different hash. Still no idea why we were flagged in the first place.

**Comment by AwkweirdMan** [comment]
Hello, I've download processing today but I have an error when I start it. Do you guys know how to fix it ? Because I will need it soon for my school project.
![capture d ecran 21](https://user-images.githubusercontent.com/37631818/37725419-36720346-2d33-11e8-8231-42d1d1fba168.png)

**Comment by AwkweirdMan** [comment]
Hello guys, I've download processing this morning and I have an error when I launch it. Do you know how to fix it ? Because I will need it soon for a school project.
![capture d ecran 22](https://user-images.githubusercontent.com/37631818/37725608-a38fb82e-2d33-11e8-9b01-ac9f85083021.png)
