### ISSUE TITLE
void cursor() don't work after void noCursor() in P2D and P3D

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5330]
## Description

void cursor() don't work after void noCursor() in P2D and P3D

When the method `noCursor()` is used in P2D or P3D, it's not possible to change the statement of cursor, that's stay in `noCursor()` mode. May be the bug have a same root  https://github.com/processing/processing/issues/4687

## Expected Behavior

switch between different method `cursor()`

that's work, in all mode JAVA2D, P2D, P3D... :)

```
void setup() {
  size(400,400,P2D); // don't work
  // size(400,400,P3D); // don't work
  // size(400,400,JAVA2D); // ok
  // size(400,400); // ok
}

void draw() {
  background(0);
  if(display) {
    println("display cursor");
    cursor(CROSS);
  } else {
    println("hide cursor");
    noCursor() ;
  }
}

boolean display = true;
void keyPressed() {
  if(display) display = false ; else display = true ;
}
```

## Your Environment
* Processing version:3.3.6
* Operating System and OS version: OS Sierra
* Other information: MacOS 2012

**Comment by alexanderghurst** [comment]
I submitted a fix for this, but in the mean time, here is a workaround.

```
void setup() {
  size(400,400,P2D); // don't work
  // size(400,400,P3D); // don't work
  // size(400,400,JAVA2D); // ok
  // size(400,400); // ok
}

void draw() {
  background(0);
  if(display) {
    println("display cursor");
    cursor();  // Sets the cursor visible.
    cursor(CROSS); // Sets the cursor to CROSS.
  } else {
    println("hide cursor");
    noCursor() ;
  }
}

boolean display = true;
void keyPressed() {
  if(display) display = false ; else display = true ;
}
```

**Comment by StanLepunK** [comment]
Cool, I wait the Processing 3.3.7 to test it !
