### ISSUE TITLE
Cannot download tools/libraries when behind a proxy.

### ISSUE THREAD

**Issue by brolifen** [processing/processing#5331]
When behind a proxy PDE cannot connect to the internet probably due to the fact it's not using the configured proxy settings or pac file in IE.

**Comment by gohai** [comment]
Proxy servers are rather rare these days, but you can set these settings in Processing's `preferences.txt`:

```
proxy.http.host=
proxy.http.port=
proxy.https.host=
proxy.https.port=
proxy.socks.host=
proxy.socks.port=
proxy.system=true
```

**Comment by jeremydouglass** [comment]
Hopefully that resolved this issue. If the proxy needs authentication, there is also an open enhancement request here: https://github.com/processing/processing/issues/5203

**Comment by benfry** [comment]
Added a note to https://github.com/processing/processing/wiki/Troubleshooting
