### ISSUE TITLE
processing 3

### ISSUE THREAD

**Issue by thesauband** [processing/processing#5335]
## Description

I have successfully installed processing 3.3.6 in ubuntu. but 1st time i tried to run processing 3 then  it display the logo screen only and it display the error message as follows
 _**

>  Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/bandula/processing-3.3.6/java/lib/i386/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
> 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
> 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
> 	at java.lang.Runtime.load0(Runtime.java:809)
> 	at java.lang.System.load(System.java:1086)
> 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
> 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
> 	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
> 	at java.lang.System.loadLibrary(System.java:1122)
> 	at java.awt.Toolkit$3.run(Toolkit.java:1636)
> 	at java.awt.Toolkit$3.run(Toolkit.java:1634)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
> 	at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
> 	at java.awt.EventQueue.invokeLater(EventQueue.java:1266)
> 	at processing.app.Base.main(Base.java:115)**_

Then I renamed the java folder inside the processing 3.3.6 into temp then it successfully commenced the  Processing 3 , and then i loaded the example sketch into the ide and tried to run it but unfortunately another error message displayed as follows 

**_

> Exception in thread "Thread-14" java.lang.RuntimeException: Could not open /home/bandula/processing-3.3.6/java/bin/java -agentlib:jdwp=transport=dt_socket,address=8740,server=y,suspend=y,quiet=y -Djna.nosys=true -Djava.ext.dirs=/home/bandula/processing-3.3.6/java/lib/ext -Djava.library.path=:/home/bandula/processing-3.3.6/core/library:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib -cp /tmp/process1717768461230584595temp:/home/bandula/processing-3.3.6/core/library/jogl-all.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-windows-amd64.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-macosx-universal.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-linux-amd64.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-windows-i586.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-linux-i586.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-windows-i586.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-linux-armv6hf.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-linux-armv6hf.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-windows-amd64.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-macosx-universal.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-linux-aarch64.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-linux-amd64.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-linux-aarch64.jar:/home/bandula/processing-3.3.6/core/library/core.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-linux-i586.jar:/home/bandula/processing-3.3.6/lib/ant-launcher.jar:/home/bandula/processing-3.3.6/lib/ant.jar:/home/bandula/processing-3.3.6/lib/jna-platform.jar:/home/bandula/processing-3.3.6/lib/jna.jar:/home/bandula/processing-3.3.6/lib/pde.jar:/home/bandula/processing-3.3.6/core/library/core.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-linux-aarch64.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-linux-amd64.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-linux-armv6hf.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-linux-i586.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-macosx-universal.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-windows-amd64.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt-natives-windows-i586.jar:/home/bandula/processing-3.3.6/core/library/gluegen-rt.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-linux-aarch64.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-linux-amd64.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-linux-armv6hf.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-linux-i586.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-macosx-universal.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-windows-amd64.jar:/home/bandula/processing-3.3.6/core/library/jogl-all-natives-windows-i586.jar:/home/bandula/processing-3.3.6/core/library/jogl-all.jar:/home/bandula/processing-3.3.6/modes/java/mode/JavaMode.jar:/home/bandula/processing-3.3.6/modes/java/mode/antlr.jar:/home/bandula/processing-3.3.6/modes/java/mode/classpath-explorer-1.0.jar:/home/bandula/processing-3.3.6/modes/java/mode/com.ibm.icu.jar:/home/bandula/processing-3.3.6/modes/java/mode/jdi.jar:/home/bandula/processing-3.3.6/modes/java/mode/jdimodel.jar:/home/bandula/processing-3.3.6/modes/java/mode/jdtCompilerAdapter.jar:/home/bandula/processing-3.3.6/modes/java/mode/jsoup-1.7.1.jar:/home/bandula/processing-3.3.6/modes/java/mode/org.eclipse.core.contenttype.jar:/home/bandula/processing-3.3.6/modes/java/mode/org.eclipse.core.jobs.jar:/home/bandula/processing-3.3.6/modes/java/mode/org.eclipse.core.resources.jar:/home/bandula/processing-3.3.6/modes/java/mode/org.eclipse.core.runtime.jar:/home/bandula/processing-3.3.6/modes/java/mode/org.eclipse.equinox.common.jar:/home/bandula/processing-3.3.6/modes/java/mode/org.eclipse.equinox.preferences.jar:/home/bandula/processing-3.3.6/modes/java/mode/org.eclipse.jdt.core.jar:/home/bandula/processing-3.3.6/modes/java/mode/org.eclipse.osgi.jar:/home/bandula/processing-3.3.6/modes/java/mode/org.eclipse.text.jar:/home/bandula/processing-3.3.6/modes/java/mode/org.netbeans.swing.outline.jar -ea processing.core.PApplet --editor-location=361,168 --external --display=1 --sketch-path=/home/bandula/sketchbook/process1 process1
> 
> _

_

> at processing.core.PApplet.exec(PApplet.java:3506)
> 	at processing.mode.java.runner.Runner$1.run(Runner.java:498)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.io.IOException: Cannot run program "/home/bandula/processing-3.3.6/java/bin/java": error=2, No such file or directory
> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
> 	at java.lang.Runtime.exec(Runtime.java:620)
> 	at java.lang.Runtime.exec(Runtime.java:485)
> 	at processing.core.PApplet.exec(PApplet.java:3504)
> 	... 2 more
> Caused by: java.io.IOException: error=2, No such file or directory
> 	at java.lang.UNIXProcess.forkAndExec(Native Method)
> 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
> 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
> 	... 5 more

_

 **

- 

It is difficult to me to identify the problem, please be good enough to help me to get rid from this problem.
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:  processing 3.3.6
* Operating System and OS version: Ubuntu 14.04 LTS
* Other information: java 8

**Comment by benfry** [comment]
That looks like you're using the 64-bit version of Processing on a 32-bit version of the OS, or vice versa.

**Comment by thesauband** [comment]
thanks, i will try it

**Comment by thesauband** [comment]
Ben Fry! Thank you very much for your advice , I reinstalled the processes
64 version and now it is  working .
Bandula
