### ISSUE TITLE
Problems loading Processing 3.3.6

### ISSUE THREAD

**Issue by scubaseanf** [processing/processing#5342]
## Description

Processing.exe produces a page with 7 Processing errors and 15 Java errors. Then Processing terminates.
![error](https://user-images.githubusercontent.com/34750464/34270940-2196ed1e-e658-11e7-9b09-22877304c9b0.png)

## Expected Behavior

I've deleted, reinstalled, restarted, updated, re downloaded older versions and made sure the I had the newest Java and deleted previous version. All produces the same error screen.
## Current Behavior

I remember coding, then the next day 

## Your Environment

 

* Processing version:  3.3.6 (64 bit)
* Operating System and OS version: windows 10
* Other information:

**Comment by scubaseanf** [comment]
Yes I was programming with Processing for the month previous

**Comment by gohai** [comment]
@scubaseanf As a quick band-aid you could try temporarily moving any installed modes/tools/libraries out of their respective folders in your sketchbook folder and restarting.

**Comment by scubaseanf** [comment]
@gohai thanks for the quick response. I've just removed all the working sketches et al to an USB stick, then wiped out the existing Processing that I had and downloaded a new copy, restarted and installed.
I had forgotten about the libraries , on the second attempt to start Processing the above error did not appear.
Thank You

**Comment by benfry** [comment]
Fixed for whatever release comes after 3.3.6.
