### ISSUE TITLE
[FEATURE REQUEST] - processing interactive 3d animations as part of the gui

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [processing/processing#5343]
## [FEATURE REQUEST] - processing interactive 3d animations as part of the gui

**from my standing point, it would be really amazing to:**
- *add interactive 3d animatons as part of the gui of the program*

---

**that could be accomplished using a combination of**:
- *p5.js*
- *three.js*
- *openframeworks and cinder compiled via emscripten*

---

**that makes sense for me, as:**
- *as far as i am concerned atom is written in java/javascript*

---

**this would be an advantage because:**
- *it would give the program a more futuristitc feel, definitely contributing to engage and innovate in terms of user experience*

**Comment by gohai** [comment]
Currently the PDE is written in Java, and while there is always room to improve or innovate, I believe it has served us quite well. If you are interested in contributing to a web-based interface instead, have a look at the in-progress p5.js Editor project.
