### ISSUE TITLE
trying to make leaves rotate with the mouse

### ISSUE THREAD

**Issue by estuary24** [processing/processing#5346]
//Note: I tried to write an array with this code, but then I got an error saying NullPointException 

float x = 50;
float y = 0;
 
PImage a1;

int x1=1;
int y1=1;
int w1;
int h1;
int front;  

boolean a1IsSet= false;

void setup() {
  size(600, 400);
  frameRate(9);
 background(255,255,255);
 
}

void draw()  {
  
  front = int(random(1,5));

  
  if (a1IsSet)
    image (a1, 1, 1 );
}

void mousePressed() {
 
  if (mousePressed ) {
      
    float angle = atan2(mouseY, mouseX );
    pushMatrix();
     rotate(angle);
    PImage imgFront = loadImage(front + "leaf.jpg"); 
      image(imgFront, mouseX-150, mouseY-200);
popMatrix();
 
  }
}

**Comment by gohai** [comment]
Please post questions or issues you encounter with your sketches to the Processing Forum at forum.processing.org. Thank you!
