### ISSUE TITLE
Processing Error: It was not meant to be 

### ISSUE THREAD

**Issue by hezi-k** [processing/processing#5347]
Hi everyone, 

So I've just downloaded the 64-bit version of processing (Version 3.3.6). I extracted the files to another folder and have updated my Java however i still get the error attached in the image. I am running Windows 10 64-bit version.

Thanks. 

![capture](https://user-images.githubusercontent.com/34650192/34377638-f493fbe0-eb02-11e7-8a65-86599294adb8.PNG)

**Comment by karanganesan** [comment]
![screenshot 74](https://user-images.githubusercontent.com/6049925/34438841-82166a98-eccf-11e7-9b5a-6badccd52664.png)

Same error

**Comment by karanganesan** [comment]
64 bit is not working I tried the 32 bit version it works 
![screenshot 75](https://user-images.githubusercontent.com/6049925/34438897-face0e5a-eccf-11e7-88d5-0155b6ecc781.png)

**Comment by benfry** [comment]
The non-working image looks like you're running the software without first extracting the .zip file. Is that possible?

**Comment by hezi-k** [comment]
Tried the 32-bit version worked great :)
