### ISSUE TITLE
Gradle dependency missing jogl-all-natives jar (from MVNrepository)

### ISSUE THREAD

**Issue by Dawars** [processing/processing#5350]
## Description
I'm writing a sketch in IntelliJ, everything works fine if I manually add the dependencies from the downloaded Processing zip.

However I want to use Gradle from https://mvnrepository.com/artifact/org.processing/core/3.3.6

## Current Behavior
I get this error when running with the P3D renderer on Win10:
```
com.jogamp.opengl.GLException: Profiles [GL4bc, GL4, GL3bc, GL3, GLES3, GL2, GLES2] not available on device WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x71423665]]
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1039)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1050)
	at com.jogamp.opengl.GLProfile.getMaxProgrammable(GLProfile.java:826)
	at processing.opengl.PSurfaceJOGL.initGL(PSurfaceJOGL.java:203)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:136)
	at processing.core.PApplet.initSurface(PApplet.java:10889)
	at processing.core.PApplet.runSketch(PApplet.java:10776)
	at processing.core.PApplet.main(PApplet.java:10513)
	at processing.core.PApplet.main(PApplet.java:10485)
	at Sketch.main(Sketch.java:11)
```
On Mac:
```
com.jogamp.opengl.GLException: No default device available
	at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2300)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1021)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1050)
	at com.jogamp.opengl.GLProfile.getMaxProgrammable(GLProfile.java:826)
	at processing.opengl.PSurfaceJOGL.initGL(PSurfaceJOGL.java:203)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:136)
	at processing.core.PApplet.initSurface(PApplet.java:10889)
	at processing.core.PApplet.runSketch(PApplet.java:10776)
	at processing.core.PApplet.main(PApplet.java:10513)
	at processing.core.PApplet.main(PApplet.java:10485)
	at Sketch.main(Sketch.java:11)
```
## Steps to Reproduce
1. Add dependency to build.gradle:
```compile group: 'org.processing', name: 'core', version: '3.3.6'```
2. Click 'Import changes' in dialog
3. Set renderer to P3D
4. Run sketch in IntelliJ

Or clone https://github.com/Dawars/processing_sketch_gradle

## Your Environment
* Processing version: 3.3.6 https://mvnrepository.com/artifact/org.processing/core/3.3.6
* IntelliJ IDEA 2017.3.1 (Ultimate Edition)
* Operating System and OS version: Win 10, 64 bit and MacOS High Sierra

## Solutions
Manually adding the native JOGL-all jar solves the problem for both platforms.
Is it possible to fix this in MVN repository or am I doing something wrong?

**Comment by gohai** [comment]
@Dawars Do you know how packaging on MVN works? I am not entirely sure the maintainers of the Processing project are responsible for the listing there...

**Comment by Dawars** [comment]
Not really, I could look into it.

**Comment by Dawars** [comment]
The jogl-all dependency is set in the Maven repo, but it should probably be jogl-all-main.

According to https://jogamp.org/wiki/index.php/Maven:
"If you don't know which packages you want, you almost certainly want to use the jogl-all-main and gluegen-rt-main packages, as **these automatically set up the correct dependencies on the native jar files for all platforms**."

I tried adding it as a dependency (compile group: 'org.jogamp.jogl', name: 'jogl-all-main', version: '2.3.2') and it added the native jars and works perfectly.

**Comment by gohai** [comment]
@Dawars This looks good to me, especially if you can confirm that this change works. However, I still don't know how one can "push" the updated pom file to Maven Central - or who took care of doing this previously. The pom file doesn't seem to be part of the Processing source tree, and I don't see any uploader or source URL at Maven Central either.

(have a look at #3109 also)

**Comment by benfry** [comment]
We're definitely not involved in the Maven release, and precisely for this reason: there's nobody to maintain it, and whoever set that up has (predictably) disappeared, leaving us with something that looks like its ours, and us getting the bug reports.

Can we have it removed somehow?

**Comment by poqudrof** [comment]
Hi guys, I will post a fix on this, feel free to mention me (@poqudrof) for maven related issues.
You can submit a fix on my github fork where I have the poms for each release. The versions are maintained as branches. 

https://github.com/poqudrof/processing/tree/release-3.3.6

I don't follow much the processing issues, I just saw this today. Other projects rely on this distribution like [propane](https://github.com/ruby-processing/propane).

**Comment by Dawars** [comment]
Hi @poqudrof,
Thanks for answer, I have already submitted a pull request, I hope it works:
https://github.com/poqudrof/processing/pull/3

**Comment by christo** [comment]
Thanks @Dawars and @poqudrof
