### ISSUE TITLE
Locate SDK path manually no works

### ISSUE THREAD

**Issue by Bedjes** [processing/processing#5352]
## Description

Hi,

I have download the mode "Android Mode". 
For the first start, Processing cannot find an Android SDK ( it's normal ), here i have 2 choice : 

- Download SDK automatically  : 
the download stop at 32% with the message : 

> The Android SDK could not be loaded. The Android Mode will be disabled 

- Locate SDK path manually : 
After installing _Android Studio_, i have a path : 

> C:\Users\Hugo\AppData\Local\Android\sdk 

But when i choose this path i have the same message : 

> The Android SDK could not be loaded. The Android Mode will be disabled 

## Solutions

Maybe it's not the good path but when i search on many website they say it's him.

## My Environment

* Processing version : 3.3.6 64 bit
* Operating System and OS version : Windows 7 64 bit
* Other information : Android Studio version 3.0.1

**Comment by gohai** [comment]
@Bedjes Could you report this over in the processing-android repository? http://github.com/processing/processing-android Thanks!
