### ISSUE TITLE
Problem when import multiple jar file

### ISSUE THREAD

**Issue by pdcxs** [processing/processing#5357]
I use Processing 3.3.6 64bit on windows 10, I create the code folder, put two jar files into it, and import them respectively. But the second one reports an error: cannot parse error text, invalid class-path header in manifest of jar file.

I try to import only one jar file, it works.

This is the content of the code folder:
![snipaste_2018-01-07_13-00-42](https://user-images.githubusercontent.com/3760797/34646727-e1a595b0-f3aa-11e7-8a1e-2330d3124c82.png)

This is the problem:
![snipaste_2018-01-07_13-02-22](https://user-images.githubusercontent.com/3760797/34646733-0496549c-f3ab-11e7-94fb-2f499ad2c4fe.png)

If delete the json.jar:
![snipaste_2018-01-07_13-00-42](https://user-images.githubusercontent.com/3760797/34646736-22fa9132-f3ab-11e7-9c3e-50067c383e15.png)

It works:
![snipaste_2018-01-07_13-02-22](https://user-images.githubusercontent.com/3760797/34646740-5504c24c-f3ab-11e7-9f41-320c0fa22fa8.png)

**Comment by gohai** [comment]
@pdcxs Can you upload the `json.jar` file somewhere so that we can have a look at it?

**Comment by pdcxs** [comment]
The jar files are in this project.
https://github.com/Tencent-YouTu/java_sdk

**Comment by gohai** [comment]
The manifest of the `json.jar` file reads like this:

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.7.1
Created-By: 10.0-b23 (Sun Microsystems Inc.)
Main-Class: org.json.Test
Class-Path: 
X-COMMENT: Main-Class will be added automatically by build


```

The issue here is the (empty) `Class-Path` line. Other manifests of jars I looked at don't even specify this field, so removing it should do the trick.

In any way, not an issue with Processing, but with the third-party jar file you're trying to include.
