### ISSUE TITLE
Updates not triggering from Library Manager

### ISSUE THREAD

**Issue by dhowe** [processing/processing#5358]
Updated a new version 1.3.11 here:  

 http://rednoise.org/rita/rita.zip
 http://rednoise.org/rita/rita.txt

Library Manager shows no update from 1.2.12 (after several days):

![screen shot 2018-01-07 at 2 24 51 pm](https://user-images.githubusercontent.com/737638/34647176-8f87a514-f3b6-11e7-96d4-28131e0b1216.png)

Might this be related to https://github.com/processing/processing/issues/4507 ?

Note that the build scripts also create:

http://rednoise.org/rita/RiTa.zip
http://rednoise.org/rita/RiTa.txt

cc: @prisonerjohn

**Comment by prisonerjohn** [comment]
Hi Daniel, the updates aren't automatic. I'll run the script manually tonight or tomorrow.

**Comment by prisonerjohn** [comment]
It should be fixed now, let me know if it isn't.
