### ISSUE TITLE
Rename dialog is unusable on high density screen.

### ISSUE THREAD

**Issue by jokigenki** [processing/processing#5368]
## Description
The rename window opens but is too small, so the buttons cannot be seen, just the text entry field. (see screengrab). 

## Expected Behavior
For the window to be bigger (or just resizable)

## Steps to Reproduce
Right click a variable -> Rename

## Your Environment
* Processing version:
Processing 3.3.6
* Operating System and OS version:
Windows 10 Pro, Version 1709
* Other information:
Dell XPS 15 9550, screen resolution 3840x2160

![renamewindow](https://user-images.githubusercontent.com/436436/34907467-2caa1bfa-f8c2-11e7-9734-59ab6050edd9.PNG)

**Comment by benfry** [comment]
Whups. Thanks for the report.

**Comment by tejasavkhattar** [comment]
Hi! I am Tejasav a Computer Science Undergrad student. I would be more than happy to contribute to this organization. Can you please help me get started and also can I get the link to the Slack Channel if any?
Thank you for your help.

**Comment by benfry** [comment]
Fixed for 3.3.7 (or 3.4 if we call it that). 

Thanks @tejasavkhattar for your interest; this wound up being quicker than expected, but we'd be happy for help with one of the many "help wanted" issues. We don't have a slack channel but the basics of getting started are these two pages: 
* https://github.com/processing/processing/wiki/Build-Instructions
* https://github.com/processing/processing/wiki/Style-Guidelines
