### ISSUE TITLE
Processing 3 possibly incompatible with JDK 9

### ISSUE THREAD

**Issue by agreyson** [processing/processing#5371]
Has anyone else been having this same problem running a sketch in Eclipse with JDK 9? Will Processing need updating to be compatible with this new version? If so, when?

https://stackoverflow.com/questions/47343612/cannot-compile-when-importing-processing-library-into-eclipse/48292239#48292239

**Comment by benfry** [comment]
Covered here: https://github.com/processing/processing/wiki/Supported-Platforms#java-9
