### ISSUE TITLE
Failure of Show Usage location.

### ISSUE THREAD

**Issue by chrisjj** [processing/processing#5377]
## Description
With multiple tabs, Show Usage often fails to place the highlight on the usage.

## Expected Behavior
Highlight on usage

## Current Behavior
Highlight somewhere else

## Steps to Reproduce
1 Create a new sketch
2 On tab #1 enter

```
void setup()
{
}
```
3 Add a second tab
4 Enter

```
// comment comment  comment  comment  comment  comment  comment   
// comment comment  comment  comment  comment  comment  comment
// comment comment  comment  comment  comment  comment  comment
// comment comment  comment  comment  comment  comment  comment

int fred2;
```

5 Click fred2, right-click, click Show Usage..., click the reference https://i.imgur.com/xhQ5dBC.png

## Your Environment
* Processing version: 3.0.2
* Operating System and OS version: Windows 7

**Comment by JakubValtar** [comment]
It's been fixed last year, please update your processing! :)

https://processing.org/download/

**Comment by chrisjj** [comment]
> It was fixed last year

Verified on 3.31 https://i.imgur.com/hDepzut.png

Thanks!
