### ISSUE TITLE
static methods doesn't work

### ISSUE THREAD

**Issue by masterstroggo** [processing/processing#5382]
Static methods does not work in Processing 3. The same code compiles fine in other java IDEs but not in Processing. 

Example code that won't compile. 
class Test { 
   Test(int i) {
   //no code here right now
   }

  static int do_something(int i) {     //Static method
    return i*2;
  }
}

The code throws the error: 
The method do_something cannot be declared static; static methods can only be declared in a static or top level type. 

I tried  one workaround.
Declaring the whole class static. This makes the static methods works but 
makes my other methods that are not static to throw errors. 

Can someone confirm if this is a bug or just me doing something wrong?

**Comment by benfry** [comment]
If you want to write straight Java code, put it in a separate tab with a `.java` extension. The preprocessor is just getting confused about what you're trying to do, mostly because there's no `setup()` or `draw()` in your code.

**Comment by masterstroggo** [comment]
Oh, there is a setup() and draw() function in there. What I'm showing here is just pseudo code to show the issue. The actual code is a part of a neural network i'm building in Processing 3 to test out some AI algorithms. 

I think it´s too early to dismiss this issue without either giving a proper explanation on how to use static methods in in processsing or atleast confirming whether this is a bug in processing3

**Comment by benfry** [comment]
The code you provided isn't legitimate Processing code, so I closed the issue. But if you have an example that reproduces the problem I'd re-open. 

However if you're trying to write straight Java code, you'll be happier putting it in a tab with a `.java` extension, so that the preprocessor ignores it. Or if you're familiar with Java and want to code that way, you're better off using Eclipse, IntelliJ, etc with the Processing libraries.

**Comment by benfry** [comment]
Actually, your code isn't even valid Java code, because you're putting a static method inside an inner class, so that's not a preprocessor bug.

**Comment by masterstroggo** [comment]
I wasn't aware that all the user created code was placed inside a class until I did some more reading last night. Thanks for clarifying though. /Cheers W
