### ISSUE TITLE
https://processing.org/reference/String_substring_.html  example can be wrong interpreted 

### ISSUE THREAD

**Issue by buiecg** [processing/processing#5383]
.substring in https://processing.org/reference/String_substring_.html, example comments are not relevant 

Examples	
String str1 = "CCCP"; 
String str2 = "Rabbit"; 
String ss1 = str1.substring(2);     // Returns "CP" // Returns last two or cut first two? // cut first two!
String ss2 = str2.substring(3);     // Returns "bit"  // Returns last three or cut first three?
String ss3 = str1.substring(0, 2);  // Returns "CC"
println(ss1 + ":" + ss2 + ":" + ss3);  // Prints "CP:bit:CC"

please find new example !
Thanks

**Comment by gohai** [comment]
Please report this to https://github.com/processing/processing-docs - or, better, propose pull-request over there. Thanks!
