### ISSUE TITLE
‘Error loading’ in Processing console on macos high sierra

### ISSUE THREAD

**Issue by wvdc** [processing/processing#5386]
I'm new to Processing and GitHub. 

After I ran Repair Disk and restarted Processing, I am getting the following message repeatedly when I try to run any Sketch, even the smallest `println("hello");`. In the console it reads:
```
2018-01-31 11:01:09.101 java[2112:583745] Error loading /Library/QuickTime/DivX Decoder.component/Contents/MacOS/DivX Decoder:  dlopen(/Library/QuickTime/DivX Decoder.component/Contents/MacOS/DivX Decoder, 262): no suitable image found.  Did find:
	/Library/QuickTime/DivX Decoder.component/Contents/MacOS/DivX Decoder: no matching architecture in universal wrapper
	/Library/QuickTime/DivX Decoder.component/Contents/MacOS/DivX Decoder: no matching architecture in universal wrapper
```
It still works but it's much slower.
What's going wrong?

## Your Environment
* Processing version: Processing 3.3.6
* Operating System and OS version: MacOS High Sierra 10.13.3

**Comment by gohai** [comment]
@wvdc That looks odd. Have you checked your system for malware?

**Comment by wvdc** [comment]
Yes, I did.

**Comment by benfry** [comment]
Looks like you have an old DivX Decoder installed… some other 3rd party app. Not really a Processing thing. The Mac version of Java must be loading QuickTime codecs to see what's available. (You can see other people struggling with the same issue [here](https://www.google.com/search?q=%22%2FLibrary%2FQuickTime%2FDivX+Decoder.component%2FContents%2FMacOS%2FDivX+Decoder%3A+no+matching+architecture+in+universal+wrapper%22&oq=%22%2FLibrary%2FQuickTime%2FDivX+Decoder.component%2FContents%2FMacOS%2FDivX+Decoder%3A+no+matching+architecture+in+universal+wrapper%22&aqs=chrome..69i57.727j0j7&sourceid=chrome&ie=UTF-8))
