### ISSUE TITLE
tools reference and libraries reference are empty

### ISSUE THREAD

**Issue by msongz** [processing/processing#5395]
on MacOS 10.13.3
     processing 3.3.6

**Comment by gohai** [comment]
Sorry, this does not give us enough information about what exactly is wrong, or how the program ended up in this particular state.

**Comment by msongz** [comment]
![](http://ww1.sinaimg.cn/large/66e22e28ly1fo8u6oiia7j20el05a75c.jpg)

**Comment by gohai** [comment]
Okay. But what kind of libraries and tools do you have installed?

**Comment by msongz** [comment]
I did not installed any tools or libraries. But I remember I could open the (https://processing.org/reference/) offline.But now get a reference must online.
