### ISSUE TITLE
Processing is not starting up on Windows

### ISSUE THREAD

**Issue by samurzl** [processing/processing#5396]
When i open the Processing.exe there is a error ("A serious problem happened during startup. Please report: https://github.com/processing/processing/issues/new"). Also there are written over 30 error codes like java.lang.NoClassDefFoundError: processing/core/PApplet etc.
![sdf](https://user-images.githubusercontent.com/36239813/35931580-47467766-0c35-11e8-80a0-168dd630b0c0.JPG)

**Comment by gohai** [comment]
@samurzl Did you extract the entire ZIP file before trying to execute the application?

**Comment by samurzl** [comment]
Yes i did

Am 08.02.2018 03:34 schrieb "Gottfried Haider" <notifications@github.com>:

**Comment by APalendat12** [comment]
I had the same problem, I have a project I need to do so I'm hoping there will be a quick fix.

**Comment by benfry** [comment]
Perhaps this problem? https://github.com/processing/processing/issues/5329

**Comment by shivmahesh** [comment]
Error message when running p3 on arduino and gcode executes 
Error :unsupported statement
G4  P150 ( wait 150ms )
Will some body help me with this problem. I am 72 yrs hobbyist and tottaly new be as far as software concern.thanks in adavance

**Comment by shivmahesh** [comment]
Processing version 3.0.2

**Comment by benfry** [comment]
Closing as duplicate of https://github.com/processing/processing/issues/5329
