### ISSUE TITLE
Rename dialog missing default button

### ISSUE THREAD

**Issue by chrisjj** [processing/processing#5400]
## Expected Behavior
In fresh Rename dialog, press ENTER performs Rename.

## Current Behavior
In fresh Rename dialog, press ENTER does nothing.

## Steps to Reproduce
Bring up Rename dialog, press ENTER.

## Your Environment
* Processing version:
3.3.6
* Operating System and OS version:
Windows 7

**Comment by benfry** [comment]
You already reported this https://github.com/processing/processing/issues/5391

**Comment by chrisjj** [comment]
This is my first report of the ENTER failure.

**Comment by chrisjj** [comment]
I've removed the reference ot the ESCAPE failure, since, as you said, it is a duplicate report.

**Comment by benfry** [comment]
Fixed for 3.4.
