### ISSUE TITLE
Problem durring startup processing3.3.6win64

### ISSUE THREAD

**Issue by Podatus** [processing/processing#5401]
I dl and extract the .zip processing-3.3.6-windows64
then launch processing.exe and this message appear. 
win10 64 bits
thanks
![capture](https://user-images.githubusercontent.com/17066441/36030729-99e26b96-0da8-11e8-9573-5593581fdc1c.PNG)

(no pb with the 32 bit version)

**Comment by benfry** [comment]
Did you get a message from Windows Defender?
 https://github.com/processing/processing/issues/5329

**Comment by Podatus** [comment]
no, no messages at all. Only the one from Processing upper.

**Comment by benfry** [comment]
Does 3.3.5 work for you?

**Comment by Podatus** [comment]
Well, the `core.jar` file was in the a folder named processing-3.3.6 ; 
I just download again processing-3.3.6-win64.zip today, and it works fine ; 
thanks for your feedback.
