### ISSUE TITLE
java (tm) se platform binary has stopped working 

### ISSUE THREAD

**Issue by DeadlyDingo** [processing/processing#5403]
I am currently writing some code which uses the Video & Sound Libraries.

I had everything working perfectly fine, but came back to work on the project yesterday and now when I run the sketch I get the error message: java (tm) se platform binary has stopped working.

I have tried everything i can think of, I've reinstalled and rolled back all my drivers, updated and rolled back Java, re downloaded processing etc.

If i run a sketch with just video, it works fine, and the same with Sound. It seems to be an issue when i combine the two, however that was all working just fine a few days ago. 

Thanks

**Comment by benfry** [comment]
If you're looking for troubleshooting help, please use forum.processing.org.
