### ISSUE TITLE
Document actual behaviour of '==' on PVector etc.

### ISSUE THREAD

**Issue by chrisjj** [processing/processing#5405]
## Expected Behavior
Docs make clear myPVector1 == myPVector2 does not give the behaviour one would expect from the equality article https://processing.org/reference/equality.html 

> Determines if two values are equivalent. The equality operator is different from the assignment operator.Note that when comparing String objects, you must use the equals() method instead of == to compare their contents.

esp. given the PVector article https://processing.org/reference/PVector.html doesn;t say otherwise.
https://stackoverflow.com/a/19966154/896451

## Current Behavior
Docs falsely indicate myPVector1 == myPVector2 compares values.

## Steps to Reproduce
Read docs. Run myPVector1 == myPVector2 where the two are equal but distinct objects.

## Your Environment
*  version:
3.3.6 
* Operating System and OS version:
Windows 7

**Comment by benfry** [comment]
Yeah, we should mention `PVector` and other objects in there, where it mentions `String` objects. That reference predates `PVector` and most other classes by quite a bit.

**Comment by benfry** [comment]
Moved here https://github.com/processing/processing-docs/issues/648
