### ISSUE TITLE
Undeclared variable 'g' not faulted at edit time and can lead to run-time errors.

### ISSUE THREAD

**Issue by chrisjj** [processing/processing#5407]
## Expected Behavior
Edit-time error: 'The variable 'g' does not exist.'

## Current Behavior
No edit-time error. Sometimes run-time error: 'NulPointerException' (sic).

## Steps to Reproduce
In an empty sketch, enter

>   g=null;

on in a real sketch, accidentally include that statement out of scope of a declaration of g in the sketch.

## Your Environment
* Processing version:
3.3.6
* Operating System and OS version:
Windows 7.

## Possible Causes / Solutions
Processing's internal 'g' varaible leaking into the sketch's scope.

**Comment by MLanghof** [comment]
That's because there is a global PGraphics object named `g`. And if you set that one to null, bad things will happen.

**Comment by benfry** [comment]
Closing since there's not a great solution for this; the `g` object is there and as implemented, we can't prevent people from messing with it.

**Comment by chrisjj** [comment]
How about make the syntax checker fault use of a dangerous name?

Else add to the docs a warning and list of the dangerous names?
