### ISSUE TITLE
Fail on Explorer Open in new window

### ISSUE THREAD

**Issue by chrisjj** [processing/processing#5410]
## Give a description of the proposed change. 
Fix it.

## Expected Behavior
Command succeeds.

## Current Behavior
Command fails:  https://i.imgur.com/k9J8qAt.png

## Steps to Reproduce
File, Open, on folder right-click, click Open in new window. https://i.imgur.com/CBbVxu3.png

## Your Environment
* Processing version:
3.3.6
* Operating System and OS version:
Windows 7 64-bit.

**Comment by benfry** [comment]
Not enough information here to fix or address this.

**Comment by chrisjj** [comment]
Was the information I gave sufficient to reproduce it? It is 100% sufficient to reproduce it here.

I have no further information that would help _fix_ it :)
