### ISSUE TITLE
PDE prioritizes libraries from /sketchbook/libraries/, while the compiler prioritizes libraries from /sketchbook/<sketch>/code/

### ISSUE THREAD

**Issue by liquid600pgm** [processing/processing#5415]
## Description

I have a library in `/sketchbook/libraries/`, which is also in `/sketchbook/<sketch>/code/`. The version in `/sketchbook/<sketch>/code/` is newer than the one in `/sketchbook/libraries`. PDE shows no errors in the Errors tab, but when I try to run the sketch there's an error `The function newFunction() doesn't exist`.

## Expected Behavior

The PDE should underline any `newFunction()`s red and show that the function doesn't exist.

## Current Behavior

It just shows that everything is fine, until I start the sketch.

## Steps to Reproduce

1. Install a new version of a library in `/sketchbook/libraries/`
2. Install an old version of a library in `/sketchbook/<sketch>/code/`
3. Try a method from the new version that is not available in the old one and run the sketch

## Your Environment

 

* Processing version: 3,3,6
* Operating System and OS version: Windows 10 Fall Creators Update build 1709
* Other information: Java 8u161

## Possible Causes / Solutions

Make PDE prioritize the `/sketchbook/<sketch>/code/` folder instead of `/sketchbook/libraries/`

**Comment by benfry** [comment]
Please don't put a library in the `code` folder that's already installed in your libraries folder. 

The point of the `code` folder is that it's for code that's not available as a library. This just isn't a use case that makes sense to put extra time into coding around it.

**Comment by liquid600pgm** [comment]
@benfry I have my own library that I'm developing, but I don't want to publish the source code, because it is heavily unfinished, but I want to include the library with another program's source code. That's basically why I have my library both in /libraries/ and /code/. Anyways, I get the point, I will probably modify build.xml so it exports to /code/ only.
