### ISSUE TITLE
Code bookmarks in PDE

### ISSUE THREAD

**Issue by liquid600pgm** [processing/processing#5419]
## Description
It would be nice if PDE had some sort of a code bookmarking system, because with large sketches it is pretty hard to find your way in all the code.

## Expected Behavior

You'd be able to right click a line number and bookmark it, then it would highlight the number somewhere, or there'd be a GUI which would list all your bookmarks and you could quickly jump to it.

## Current Behavior

As of now, it is somewhat hard to find your way in very large sketches, like my exCircuit (one file has almost 1000 lines of code, all the others have less), but with such a bookmarking system it would be way easier.

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: Windows 10
* Other information: Java 8u161

## Possible Causes / Solutions

 - Right-clicking a line number and having a "Bookmark" option
 - An always-on-top GUI that would list bookmarks
 - Maybe some sort of preview on the right side of the code editor, like these small error/warning lines when something's not right with your code

**Comment by MLanghof** [comment]
Unless another hack-ish solution like for debug breakpoints (appending //<>// to the end of line, hidden in text rendering within the IDE) is used, this would necessitate introducing project files.

I am under the impression that this would go against some core design choice, as otherwise the IDE would quickly turn into a monstrosity.

**Comment by benfry** [comment]
This would be better implemented by a contributed Tool. For code projects that complicated, we also recommend using a more full-featured IDE. The PDE is intended to stay as simple as possible for the widest possible audience.
