### ISSUE TITLE
Processing can't run any code on Windows 10 64-Bit on my computer.

### ISSUE THREAD

**Issue by SuperHostile** [processing/processing#5420]
I'm using Processing 3.3.6. I used Processing for a short time, so i get curiosity to press the "Get Started" button in the pop-up on the startup. And now, i can't run any code in Processing. I'm not using any lib or mode in Processing. I tried to totally re-install Processing deleting the files in AppData and documents, i tried Processing 3.3.5, im tried the 32-bit Processing version on my 64-bit computer but nothing happened. 
launch4j.log:

Version:	3.9
CmdLine:	D:\Programacion\Processing\processing-3.3.6\processing.exe --l4j-debug
WOW64:		yes
Working dir:	D:\Programacion\Processing\processing-3.3.6\.
Bundled JRE:	java
Check launcher:	D:\Programacion\Processing\processing-3.3.6\java\bin\javaw.exe (OK)
Heap -Xmx:	Requested 256 MB / 0%, Available: 4585 MB, Heap size: 256 MB
Substitute:	EXEDIR = D:\Programacion\Processing\processing-3.3.6
Add classpath:	lib\pde.jar
Add classpath:	core\library\core.jar
Add classpath:	lib\jna.jar
Add classpath:	lib\jna-platform.jar
Add classpath:	lib\antlr.jar
Add classpath:	lib\ant.jar
Add classpath:	lib\ant-launcher.jar
Launcher:	D:\Programacion\Processing\processing-3.3.6\java\bin\javaw.exe
Launcher args:	-Xmx256m -Djava.ext.dirs="D:\Programacion\Processing\processing-3.3.6\\java\\lib\\ext" -Djna.nosys=true -Djna.boot.library.path=lib -Djna.nounpack=true -Dsun.java2d.d3d=false -Dsun.java2d.ddoffscreen=false -Dsun.java2d.noddraw=true -classpath "lib;lib\pde.jar;core\library\core.jar;lib\jna.jar;lib\jna-platform.jar;lib\antlr.jar;lib\ant.jar;lib\ant-launcher.jar" processing.app.Base
Args length:	382/32768 chars
Exit code:	259

OS: Windows 10 Pro 64-bit
preferences.txt in AppData:

chooser.files.native=true
console.auto_clear=true
console.font.size=12
console.lines=4
console.scrollback.chars=40000
console.scrollback.lines=500
contribution.backup.on_install=true
contribution.backup.on_remove=true
editor.caret.blink=true
editor.caret.block=false
editor.completion.auto_close=false
editor.font.family=Source Code Pro
editor.font.size=12
editor.indent=true
editor.input_method_support=false
editor.keys.alternative_cut_copy_paste=true
editor.keys.home_and_end_travel_far=false
editor.keys.home_and_end_travel_smart=true
editor.keys.shift_backspace_is_delete=false
editor.smooth=true
editor.tabs.expand=true
editor.tabs.size=2
editor.token.comment1.style=#666666,plain
editor.token.comment2.style=#666666,plain
editor.token.function1.style=#006699,plain
editor.token.function2.style=#006699,plain
editor.token.function3.style=#669900,plain
editor.token.function4.style=#006699,bold
editor.token.invalid.style=#666666,bold
editor.token.keyword1.style=#33997e,plain
editor.token.keyword2.style=#33997e,plain
editor.token.keyword3.style=#669900,plain
editor.token.keyword4.style=#d94a7a,plain
editor.token.keyword5.style=#e2661a,plain
editor.token.keyword6.style=#33997e,plain
editor.token.label.style=#666666,bold
editor.token.literal1.style=#7D4793,plain
editor.token.literal2.style=#718a62,plain
editor.token.operator.style=#006699,plain
editor.untitled.prefix=sketch_
editor.untitled.suffix=yyMMdd
editor.watcher=true
editor.watcher.debug=false
editor.watcher.window=1500
editor.window.height.default=600
editor.window.height.min=530
editor.window.width.default=700
editor.window.width.min=400
editor.zoom=100%
editor.zoom.auto=true
export.application.embed_java=true
export.application.fullscreen=false
export.application.stop=true
export.delete_target_folder=true
instance_server.key=0.0033056710401638822
instance_server.port=51353
last.sketch.count=0
last.sketch.restore=true
mode.last=processing.mode.java.JavaMode
pdex.autoSave.autoSaveByDefault=true
pdex.autoSave.autoSaveEnabled=false
pdex.autoSave.promptDisplay=true
pdex.autoSaveInterval=5
pdex.completion=false
pdex.completion.trigger=false
pdex.dbgOutput=false
pdex.errorCheckEnabled=true
pdex.inspectMode.hotkey=true
pdex.suggest.imports=true
pdex.warningsEnabled=true
pdex.writeErrorLogs=false
platform.auto_file_type_associations=true
preproc.color_datatype=true
preproc.enhanced_casting=true
preproc.output_parse_tree=false
preproc.save_build_files=false
preproc.substitute_floats=true
preproc.substitute_unicode=true
preproc.web_colors=true
proxy.http.host=
proxy.http.port=
proxy.https.host=
proxy.https.port=
proxy.socks.host=
proxy.socks.port=
proxy.system=true
recent.count=10
run.display=-1
run.options=
run.options.memory=false
run.options.memory.initial=64
run.options.memory.maximum=256
run.present.bgcolor=#666666
run.present.stop.color=#cccccc
run.window.bgcolor=#F0F0F0
sketchbook.path.three=C:\Users\My User\Documents\Processing
update.check=true
update.id=-1862160903735373052
update.last=1519226057147
welcome.seen=false
welcome.show=true

Java Version: 1.8.0_111

I'm trying to run this code:

void draw() {
 rect(0, 0, 10, 10);
}

But on every code i try to run isn't working.

**Comment by gohai** [comment]
What is the error you are seeing when you run this code?

**Comment by SuperHostile** [comment]
It gives me no error, but if i kill the task of java that is running the code gives me this error

Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.

I read revisions.txt and Help ? Troubleshooting, i tried the things that are listed on, totally reinstall Processing, but nothing happened.

**Comment by benfry** [comment]
Please use https://forum.processing.org for issues like this.
