### ISSUE TITLE
Problem with AMDGPU on Processing 3.3.6

### ISSUE THREAD

**Issue by tomasgvivo** [processing/processing#5429]
## Description
When running sketches with P2D, the java error `Problematic frame: # C  [amdgpu_dri.so+0x205746e]` shows up.

## Your Environment
* Processing version: Processing 3.3.6
* Operating System and OS version: Ubuntu 16.04
* Graphics: AMD Radeon R9 380 - Driver: amdgpu-pro_16.20.3-294842_amd64

## Possible Causes / Solutions
There's an issue with similar problem but the solution didn't work for me: [#4584](https://github.com/processing/processing/issues/4584)

**Comment by gohai** [comment]
@tomasgvivo Hi, Unfortunately this is not enough information for us to pursue this further. You might want to try to file a bug report against the JOGL project, which is was Processing is using to interface your OpenGL implementation, but I am not sure how active they are still.
