### ISSUE TITLE
Problem with sound waves in Processing: 3.3.6 

### ISSUE THREAD

**Issue by Crazymans2** [processing/processing#5430]
## Description
When running a my program with sin waves, saw waves, and a low pass filter (only sin wave is active at the start of program but if any of them is left not commented then the sketch won't run) it can't run the sketch. It opens then closes itself without windows task manager, but errors do pop up and it closes itself. 

## Expected Behavior
I would like to be able to run the sketch so I could finish my project.

## Problem Code
 // Sine
  soundOutput = new SinOsc(this); 
  soundOutput.play();
  soundOutput.freq(0);     
  waves.add(new SinOsc(this));
  
 // Saw
  saw = new SawOsc(this); 
  saw.play();
  saw.freq(0);      
  waves2.add(new SawOsc(this));
  
  //Low pass
  lowPass = new LowPass(this);
Note that the sound library is installed and being imported into the code
 

## Your Environment
* Processing version: 3.3.6
* Note that not all of my project is done and there are things that have no purpose yet.
## Here is the rest of the code to show you how it works with the rest of my project:
 import processing.sound.*;

// Piano Notes
float C4, D4, E4, F4, G4, A4, B4;

char currentNote; 
boolean nowPlaying = false;

// Variables 
SinOsc soundOutput;
SawOsc saw;

// Low, High and mid EQ
LowPass lowPass;

//Arrays
ArrayList<SawOsc> waves2;
ArrayList<SinOsc> waves; 

// No idea what this does
int numWaves = 0; 

// Controls the wave input
//0=sine, 1=saw, 3=square
int waveControl = 0; //default to sine
int filter = 0;

void setup() {  
   
  // Piano note frequency
   C4 = 261.626;    
   D4 = 293.665;
   E4 = 329.628;
    
 // Settings
  size(600, 600);
  background(255);
  fill(0);
  currentNote = '-';
 
  //Waves for sin and saw
  waves = new ArrayList<SinOsc>();
  waves2 = new ArrayList<SawOsc>();
 
  // Sine
  /*soundOutput = new SinOsc(this); 
  soundOutput.play();
  soundOutput.freq(0);     
  waves.add(new SinOsc(this));
  
 // Saw
  saw = new SawOsc(this); 
  saw.play();
  saw.freq(0);      
  waves2.add(new SawOsc(this));
  
  //Low pass
  lowPass = new LowPass(this);*/
 
  
}

void draw() {
  drawLegend();
  stroke(0);
  fill(0);
  ellipse(mouseX,mouseY,10,10);
  
  // Printed Note
  textSize(64);
  text(currentNote, width/2-55, height/2+150);
  
  // Sin Waves
//  waves.get(waves.size()-1).freq(map(mouseX,0,width,32.70,4186.01));
 // waves.get(waves.size()-1).amp(1.0-map(mouseY,0,height,0,1));
  
  // Saw waves
//  waves2.get(waves2.size()-1).freq(map(mouseX,0,width,32.70,4186.01));
//  waves2.get(waves2.size()-1).amp(1.0-map(mouseY,0,height,0,1));
  
  
}

void drawLegend() {
  
  // Theramin
  background(255);
  strokeWeight(2);
  stroke(#BF5700);
  fill(#BF5700);
  textSize(16);
  float pExtension = map(mouseX,0,width,0,width/4);
  line(width/2-40,height/2+30,width/2-30+pExtension,height/2+30);
  triangle(width/2+pExtension-30,height/2+35,
           width/2+pExtension-30,height/2+25,
           width/2+pExtension-15,height/2+30);
  text("pitch",width/2+pExtension,height/2+35);
  float vExtension = map(mouseY,height,0,0,height/4);
  line(width/2-40,height/2+30,width/2-40,height/2+20-vExtension);  
  triangle(width/2-35,height/2+20-vExtension,
           width/2-45,height/2+20-vExtension,
           width/2-40,height/2+5-vExtension);
  text("volume",width/2-65,height/2-vExtension); 
  
}

void keyPressed()
{
   if (key == '2')
   {
    filter = (filter +1)%3;
   }
  if (key == '1') 
   {
     waveControl = (waveControl + 1)%3;
      
   }
  switch(filter)
    {
      case 0:
      {
        if(!nowPlaying)
        {
          lowPass.process(soundOutput, 300);
          nowPlaying = true;
        }
        else
        {
          lowPass.process(soundOutput, 0);
          nowPlaying = false;
        }
        break;
      }
      case 1:
      {
        if(!nowPlaying)
        {
          saw.freq(D4+map(mouseX,0,width,32.70,4186.01));
          //soundOutput.play();
          saw.amp(1.0-map(mouseY,0,height,0,1));
          nowPlaying = true;
        }
        else
        {
          soundOutput.freq(0);
          saw.freq(0);
          //square.freq(0);
          nowPlaying = false;
        }
        break;
      }
      case 2:
      {
        
        break;
      }
    }
  //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
  if (key == 'c')
  {
    switch(waveControl)
    {
      case 0:
      {
        if(!nowPlaying)
        {
          soundOutput.freq(C4+map(mouseX,0,width,32.70,4186.01));
          //soundOutput.play();
          soundOutput.amp(1.0-map(mouseY,0,height,0,1));
          nowPlaying = true;
        }
        else
        {
          soundOutput.freq(0);
          saw.freq(0);
          //square.freq(0);
          nowPlaying = false;
        }
        break;
      }
      case 1:
      {
        if(!nowPlaying)
        {
          saw.freq(C4+map(mouseX,0,width,32.70,4186.01));
          //soundOutput.play();
          saw.amp(1.0-map(mouseY,0,height,0,1));
          nowPlaying = true;
        }
        else
        {
          soundOutput.freq(0);
          saw.freq(0);
          //square.freq(0);
          nowPlaying = false;
        }
        break;
      }
      case 2:
      {
        
        break;
      }
    }
  } 
  //DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
  if (key == 'd')
  {
    switch(waveControl)
    {
      case 0:
      {
        if(!nowPlaying)
        {
          soundOutput.freq(D4+map(mouseX,0,width,32.70,4186.01));
          //soundOutput.play();
          soundOutput.amp(1.0-map(mouseY,0,height,0,1));
          nowPlaying = true;
        }
        else
        {
          soundOutput.freq(0);
          saw.freq(0);
          //square.freq(0);
          nowPlaying = false;
        }
        break;
      }
      case 1:
      {
        if(!nowPlaying)
        {
          saw.freq(D4+map(mouseX,0,width,32.70,4186.01));
          //soundOutput.play();
          saw.amp(1.0-map(mouseY,0,height,0,1));
          nowPlaying = true;
        }
        else
        {
          soundOutput.freq(0);
          saw.freq(0);
          //square.freq(0);
          nowPlaying = false;
        }
        break;
      }
      case 2:
      {
        
        break;
      }
    }
  }
}

void keyReleased()
{
  if (waveControl==1)
  {
    if (key == currentNote)
    {
      currentNote = '-';
      soundOutput.freq(0);
    }
  }
  if (waveControl==2)
  {
    if (key == currentNote)
    {
      currentNote = '-';
      saw.freq(0);
    }
  }
  
  if (key == 1) 
      waveControl=1; 
  if (key == 2) 
      waveControl=2;
 
}

**Comment by gohai** [comment]
This belongs here: https://github.com/processing/processing-sound
