### ISSUE TITLE
Program crashes after running for first time

### ISSUE THREAD

**Issue by DoNguyenHung** [processing/processing#5431]
Hi, 
This is my first time using Processing. I'm using the 64-Bit on my Windows. I finished downloading but it crashed every time I opened it.
Does anyone know what to do about it?
Thanks in advance

**Comment by gohai** [comment]
What does it say when it crashes? Did you unpack the all the files in the compressed archive to a folder, before attempting to execute the program?

**Comment by DoNguyenHung** [comment]
Hi,
It doesn’t say anything when it crashes, it just crashes when I open the application. I’ve unpacked all of the archives. I’ve tried out on an older version of Processing and it still hasn’t worked.
Is there anything I can do?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10


________________________________

**Comment by benfry** [comment]
Please use https://forum.processing.org for this type of question. Or you can start with the Troubleshooting guide: https://github.com/processing/processing/wiki/Troubleshooting
