### ISSUE TITLE
Code won't run due to application "requested the Runtime to terminate it in an unusual way"

### ISSUE THREAD

**Issue by 123Amber123** [processing/processing#5433]
Every time I run my sketch, the window for the drawing pops up but when i click to run the sounds, the following error message shows up:

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.

What should I do to get my code to run? Thanks in advance.

**Comment by gohai** [comment]
Is this with the Sound library?

**Comment by gohai** [comment]
If your sketch has `import processing.sound.*` at the beginning you might want to try to report this problem to the [processing-sound](https://github.com/processing/processing-sound) repository. If it uses minim, then reporting it to the [Minim](https://github.com/ddf/Minim) project would be the way to go.
