### ISSUE TITLE
Sketch Crashes When Run

### ISSUE THREAD

**Issue by cloudfacesplaces** [processing/processing#5435]
I'm running on a 2.5GHz 6GB RAM PC. I have the latest version of Processing and of Java. 
I'm trying to run a sketch through my Arduino UNO using this guide http://www.instructables.com/id/Touche-for-Arduino-Advanced-touch-sensing/
I've done every step but now am stuck at processing.
When I run the sketch, another blank window opens, which seems like it will display something, but nothing happens, so I close it. And when I do, sometimes it stays open and keeps loading, with a white screen, and sometimes it crashes and says "Java (TM) Platform SE binary is not responding". I've attached the print screen of the errors in the code (I think)

I'd really like to get it working so I can continue with the project!!

Thanks

![image](https://user-images.githubusercontent.com/37248391/37244956-dfd8810c-2488-11e8-91bf-909e5b09a675.png)

**Comment by gohai** [comment]
@cloudfacesplaces The `Processing_graph` sketch you are using mistakingly assumes that the system it is running on has three serial ports and tries to open the third one (`PortSelected = 2`). Nothing wrong with Processing, and not a bug...

**Comment by cloudfacesplaces** [comment]
that's good to hear, but how do I fix it?

**Comment by gohai** [comment]
@cloudfacesplaces Please discuss issues with your sketches in the Processing Forum, or in the Instructable you're following.
