### ISSUE TITLE
Feature Request - Default Code in Editor

### ISSUE THREAD

**Issue by Elite01** [processing/processing#5437]
Hey, awesome project guys!
this one is a simple feature request
id like the processing exe to open by default with some text
so i could have some code added automatically everytime i open it
is it possible?
thanks!

to be clear about my request...
i want to open the executable and find

> void setup() {
size(300, 400)
}
void draw() {
    background(51);
}

**Comment by benfry** [comment]
I'm happy to say you can already do this: https://github.com/processing/processing/wiki/Templates
