### ISSUE TITLE
Processing sketch window just a grey window?

### ISSUE THREAD

**Issue by sillinesses** [processing/processing#5439]
## Description

Hey, I'm new to Processing and I've been following the new tutorials on hello.processing.org - I got to the part where I draw a rectangle and I'm already having an issue. Embarassing, I know.

So every time I hit run, the sketch window only opens up a small grey box. It doesn't matter what I type into the code. I found one forum topic of the same issue, but it looks like it was unresolved / people thought it was an issue with code... but I'm literally following the tutorial and typing in one line of code, so I'd like to think that's not the issue. I also followed the troubleshooting guide, but I have no created folders or files - no sketchbook, and I deleted the preferences file.

Here's a screenshot of what that looks like: 
![image](https://user-images.githubusercontent.com/37374985/37410019-0f3d226e-2776-11e8-85fd-c0ce82579d10.png)

## Expected Behavior

Well, from the tutorial, this is what I was expecting: 
![image](https://user-images.githubusercontent.com/37374985/37410156-5c000332-2776-11e8-96fe-055db768cc88.png)

## Current Behavior

Well, uh, I'll show you the other screenshot again.
![image](https://user-images.githubusercontent.com/37374985/37410019-0f3d226e-2776-11e8-85fd-c0ce82579d10.png)

## Steps to Reproduce

1. Download Processing from Processing.org
2. Extract files to my downloads folder
3. Navigate to Processing folder in download folder and run "Processing.exe"
4. Try to draw a rectangle
5. ???

## Your Environment

 

* Processing version: 3.3.7 (also happened on 3.3.6)
* Operating System and OS version: Windows 7
* Other information:

## Possible Causes / Solutions

I wish I had any idea.

**Comment by benfry** [comment]
You just need to add `size(500, 400)` to the beginning. (I think the tutorial must be doing that behind the scenes.) That'll give you the 500x400 pixel window that's being used in the tutorial, and then you'll be able to see those rectangles. You're only seeing gray at the moment because the window is only 100x100, and your rectangle is drawn starting at 100 over, 100 down.

**Comment by sillinesses** [comment]
Yeeeeeeeeup. That fixed all of my issues.
Thanks for the quick answer to an embarrassingly simple question!

**Comment by shiffman** [comment]
Great job filing your first github issue @sillinesses! Glad you worked it out. I'm not sure if it can be easily added to the tutorial unless we reshoot the videos, but this has come up before:

https://github.com/processing/Processing-Hour-Of-Code/issues/68
(back then I guess I thought I said it but clearly maybe I have not.)

@sillinesses you can also ask for help at forum.processing.org as github is more of a place for "bug reports". It's very hard to know the difference when you are just beginning so have no fear if you end up in the wrong place, we'll help!
