### ISSUE TITLE
Processing 3.3.7 reports as Trojan:Win32/Critet.BS

### ISSUE THREAD

**Issue by benfry** [processing/processing#5442]
Reported here: https://github.com/processing/processing/issues/4884#issuecomment-373704821 but unconfirmed.

**Comment by benfry** [comment]
@jarcane Is this on 32-bit or 64-bit? And what version of Windows?

**Comment by gohai** [comment]
`Trojan:Win32/Critet.BS` was only added in the most recent definition from Microsoft, `1.263.598.0`. So probably a false positive. Affected [Kerbal Space Program](https://forum.kerbalspaceprogram.com/index.php?/topic/172357-trojanwin32critetbs/) also.

**Comment by jarcane** [comment]
@benfry Windows 10 Pro 64-bit. Not at my laptop so can't say for sure which version.

**Comment by Alex-dlc** [comment]
I'm on Windows 10 Home 64 bit. I just tried to extract Processing 3.3.7 from the zip and got this trojan warning for Critet.BS. Should I quarantine?

**Comment by benfry** [comment]
I'm all but certain it's a false positive. The builds are done on an isolated VMware instance that's used for nothing except for Processing development.

**Comment by benmikewill** [comment]
I also got this issue, I can't even download it right now

**Comment by kmwright** [comment]
This happened to me too when I tried to extract 3.3.7 on Win10 Pro 64 bit. Win Defender reported finding Trojan:Win32/Critet.BS with alert level 'Severe'. The affected files are ...\processing-3.3.7\processing-java.exe and ...\processing-3.3.7\processing.exe. I'm taking no chances - will not install this!

**Comment by benfry** [comment]
Submitted to Microsoft as a false positive: https://www.microsoft.com/en-us/wdsi/filesubmission which is all we can do at this point. 

It would be more of a concern if these reports said that it was the same trojan or piece of malware, but it identified 3.3.6 as something else.

**Comment by benfry** [comment]
Microsoft says we're clean, though they don't say if/when the detection will be fixed. At least this is more information than they've provided in the past…

<img width="1157" alt="screen shot 2018-03-18 at 10 41 28 am" src="https://user-images.githubusercontent.com/1623101/37567147-1995d564-2a99-11e8-9166-822f3c9ae3a0.png">
