### ISSUE TITLE
Java sketch not working 

### ISSUE THREAD

**Issue by abby539** [processing/processing#5443]
## Description

When I press run, the java sketch pad opens up as a little square but nothing is drawn on it. 
This is on a new Mac system so not sure what to do. 
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by gohai** [comment]
What's your sketch like?

**Comment by VegaVen2ra** [comment]
Did you use the [size](https://processing.org/reference/size_.html) command to adjust the window size?

**Comment by benfry** [comment]
Please check out the troubleshooting page first: https://github.com/processing/processing/wiki/Troubleshooting and the forum is a better place to ask questions about your code.
