### ISSUE TITLE
Dark theme: themes.txt relocation request

### ISSUE THREAD

**Issue by kfrajer** [processing/processing#5445]
This is related to the wiki: https://github.com/processing/processing/wiki/Dark-Theme-for-PDE

The wiki suggest to change the following files to create a Dark Theme:
theme.txt and preferences.txt

However, theme.txt file is located in the main Processing folder under the lib/ folder. If there is a new version of Processing, this file will be lost and to create the dark theme, it has to be changed again manually.

My suggestion: Move this file to the sketch folder to a folder called Themes, at the same level as the `templates` folder.

Kf

**Comment by benfry** [comment]
That wiki page is a contribution from someone in the community; not anything "official".

**Comment by kfrajer** [comment]
This is not clear: `themes.txt` is not supported by Processing at all? The file comes with every install of Processing under the `lib/` folder, hence my suggestion. Now that I get a new version of processing, one needs to update this file to maintain the dark color theme, so it is my understanding. Everything would be easier if all the changes were encapsulated in the preferences.txt file as this file already lives outside the Processing core folder.

Kf

**Comment by benfry** [comment]
No, it's really supported at all, and isn't meant to be messed with. But I already added the ability to override it for the next release. So you should be all set with 3.4.
