### ISSUE TITLE
Processing Application not included.

### ISSUE THREAD

**Issue by Gazzanz** [processing/processing#5446]
Processing.exe could not be found in the latest download 13/03/2018 ver 3.3.7
I downloaded the previous version to get it to work ver 3.3.6
It works fine.

**Comment by benfry** [comment]
Did Windows Defender delete it? https://github.com/processing/processing/issues/5442

**Comment by Gazzanz** [comment]
No Defender is turned off.

**Comment by benfry** [comment]
You sure you're using our download, in that case? It's definitely in the 64-bit Windows .zip file, and I assume the 32-bit as well.

**Comment by benfry** [comment]
The `.exe` is in there; might want to double-check Windows Defender again.

```
% unzip -l processing-3.3.7-windows32.zip | grep processing.exe
   627200  03-13-2018 21:36   processing-3.3.7/processing.exe
```
and
```
% unzip -l processing-3.3.7-windows64.zip | grep processing.exe
   627200  03-13-2018 21:30   processing-3.3.7/processing.exe
```
