### ISSUE TITLE
screen is blocked when run button is pressed and no output in 3.3.7 

### ISSUE THREAD

**Issue by ghost** [processing/processing#5447]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by 7032060596** [comment]
I am using 3.3.7 p3 on windows 10 .
when an example is run it ,firewall blocks java se binary and  asks for permission.
Later is doesn't run at all .

**Comment by benfry** [comment]
If you let the firewall block the app, it's not going to work anymore. 

Or if you allowed the app, try the troubleshooting page: https://github.com/processing/processing/wiki/Troubleshooting 

The forum is a better place to ask questions about getting up and running with the software.
