### ISSUE TITLE
Using Processing

### ISSUE THREAD

**Issue by jbowers9** [processing/processing#5449]
**## Description
Trying to use https://processing.org/,
but on a public machine, @ Brooklyn Public Library which will not allow installation of remote software.
Is there an alternative? I use Python at DataCamp and PythonAnywhere, IDE(?).
Can I do this w/Processing?**

**Comment by gohai** [comment]
Hi @jbowers9 - please use the [Forum](https://forum.processing.org/) for general questions like this one, thank you!
