### ISSUE TITLE
clip() weird behavior

### ISSUE THREAD

**Issue by liquid600pgm** [processing/processing#5450]
## Description
`clip()` behaves weirdly when I try to use it multiple times (nested) without `noClip()`.

## Expected Behavior

My sketch code:
```Processing
size(300, 300);
background(0);

noStroke();
clip(0, 0, 192, 192); noFill(); stroke(255); rect(0, 0, 191, 191);
fill(#FF0000); noStroke();
rect(0, 0, 128, 128);
clip(32, 32, 100, 100); fill(255, 127); stroke(255); rect(32, 32, 99, 99);
fill(#00FF00); noStroke();
rect(96, 96, 128, 128);
```

## Current Behavior

![Screenshot](https://i.imgur.com/S7JjzL1.png)

I expected the white tinted rectangle to be what's clipped in the end, but the result was rather strange.

## Steps to Reproduce

Run the code that I provided.

## Your Environment

 

* Processing version: 3.3.7
* Operating System and OS version: Windows 10 Fall Creators Update
* Other information: Java 8u161, JAVA2D renderer

**Comment by kfrajer** [comment]
Not sure what is strange about your result in your code. For starters, the first clip call is ineffective as all drawing is happening within this region. Second, if you remove your second clip function and semi-transparent rectangle, you get the red and green squares, both having the same dimensions. If you enable the clip call (the second one) then as expected, the red square is drawn and only the corner of the green square is drawn. Only those object within the region defined by the clipping call are drawn. Nothing weird here unless something I am missing.

Notice that if you moved the second clip call to the top to replace the first one, only a portion of the red square is drawn together with the "observed" corner section of the green square. 

Clip is working as advertised. 

Kf

Kf

**Comment by liquid600pgm** [comment]
@kfrajer I get it, my example didn't show the problem too well.
My point is, when you use clip(), you expect those to "stack", like with `PGraphics#beginDraw` and `PGraphics#endDraw` not to overwrite each other. I know that it might be hard to implement this. but with `Graphics2D#clip` (not `setClip`) it might be possible.

I have done some research to potentially fix the issue, maybe I will fix it.

**Comment by liquid600pgm** [comment]
> Limits the rendering to the boundaries of a rectangle defined by the parameters. The boundaries are drawn based on the state of the imageMode() fuction, either CORNER, CORNERS, or CENTER.

*from the Processing Reference*

Turns out I misunderstood how `clip()` works, I fixed the issue in my sketch afterwards. Closing.
