### ISSUE TITLE
Video# A library relies on native code that's not available. Or only works properly when the sketch is run as a 32-bit appliaction

### ISSUE THREAD

**Issue by ArthurSongChina** [processing/processing#5453]
## Description

I am a new for processing.and I followed the video class from Youtube 11.1: Capture and Live Video - Processing Tutorial。 but when I run the code then there was a problem.
Is there someone could help me, thanks a lot!
## Expected Behavior

![2018-03-27 9 17 10](https://user-images.githubusercontent.com/30542763/37970824-0739d56c-3207-11e8-94d0-8fb40d1ad2bc.png)

## Current Behavior

![2018-03-27 8 43 59](https://user-images.githubusercontent.com/30542763/37969335-08c78392-3203-11e8-8c36-1baa3d871b04.png)
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
![2018-03-27 9 18 02](https://user-images.githubusercontent.com/30542763/37969916-9ede491e-3204-11e8-98c6-e0814a71fcb7.png)

* Operating System and OS version:
* Other information:
![2018-03-27 9 12 10](https://user-images.githubusercontent.com/30542763/37969927-a20b34d0-3204-11e8-9ce0-b96efd1e5fb7.png)

**Comment by benfry** [comment]
Paging @shiffman…

**Comment by gohai** [comment]
@ArthurSongChina That's odd - can you check which version of the Video library you have installed? You should have a file called `library.properties` inside the `video` folder, inside the `libraries` folder of your Processing sketchbook. If you open this file with a text editor, you should see a line `prettyVersion=`.

**Comment by ArthurSongChina** [comment]
@gohai Hi, I have followed your instruction and got the Version in the file. **The prettyVersion is 1.0.1.**
and there are more information about this.
![2018-03-28 12 32 22](https://user-images.githubusercontent.com/30542763/38008955-4d9e4290-3284-11e8-8bae-7c69d6826083.png)

**Comment by gohai** [comment]
Pinging @codeanticode

**Comment by benfry** [comment]
Hey folks, let's move this discussion to the correct repo: https://github.com/processing/processing-video/issues/90

(Was paging @shiffman in the hope that he might have a quick answer based on what he said in the tutorial, but barring that, let's at least discuss in a more productive place.)

**Comment by shiffman** [comment]
Thanks, apologies for joining late, will head over to processing-video!
