### ISSUE TITLE
PGraphics issue

### ISSUE THREAD

**Issue by SAI16497307** [processing/processing#5455]
Hey guys,
I am new to coding and I am having a problem everytime I try to run this sketch using createGraphics.

I get an error saying "cannot convert from processing.core.PGraphics to PGraphics"
Anyone can help please?
Here is the code I am using

//PGraphics

PGraphics pg; //declair PGraphics class

void setup() {
  size(500, 500);
  background(255);
  pg = createGraphics (400, 200);
}

void draw() {
  fill(0);
  rect(mouseX, mouseY, 50, 50);
  fill(255, 0, 0);
  stroke(0);
  strokeWeight(5);
  ellipse(mouseX, mouseY, 20, 20);

  pg.beginDraw();
  pg.background(100);
  pg.stroke(255);
  pg.ellipse(mouseX-120, mouseY-20, 20, 20);
  pg.endDraw();
}

**Comment by benfry** [comment]
For coding questions visit https://forum.processing.org
