### ISSUE TITLE
Delete preference preproc.substitute_unicode

### ISSUE THREAD

**Issue by GKFX** [processing/processing#5456]
In #5152 I made the preference `preproc.substitute_unicode` non-functional, thus later causing issue #5413. However I didn't know how to properly delete the preference; it's still sitting in defaults.txt as true. (I mentioned this in the original PR but it wasn't dealt with.)

Probably it should be got rid of now? I imagine this is just deleting the line in defaults.txt.

**Comment by benfry** [comment]
All set for 3.4.
