### ISSUE TITLE
clear() and background() method not working on Android mode with PGraphics class

### ISSUE THREAD

**Issue by Scemenzo** [processing/processing#5458]
I'm developing a simple live wallpaper for Android.
I'm drawing coloured pixels with the set() methon on a PGraphic object to obtain a particle effect. 
During the cycle I need to clean the frame before updating the drawing of the particles on their new position.
While in Java mode, everything works fine and performances are good.
In Android mode, after compiling and installing the live wallpaper on my device, everything works fine except for the clear() mechanism (like it was not executed at all, the new image is the result of the previous image summed up with the new drawings) and I have a tiny performance drop.
Trying with background(0,0) I have the exact same problem, but there is no performances drop and background(255,255) gives correct execution, so the method is technically being executed.

I've searched the web for every kind of solution and I've tried manipulating pixels directly or changing my problem logic, but those times the program worked fine, performances where really bad.

I've tried with both P2D and P3D renders. With both I have the exact same problem and both works fine in Java mode.

---
The project is very simple. It uses:

- P2D rendering
- fullscreen 
- portrait mode for android
- the famous "((PGraphicsOpenGL)g).textureSampling(2)" trick in order to set nearest neighbor in OpenGL
- a PGraphic object of the same size of the screen
- a post-drawing scaling of the PGraphic image obtained with the copy() method

```
background(0,0);

//"pioggia" is the PGraphics object. "gocce" is just a 2D array of float values.
pioggia.beginDraw();
pioggia.clear();            //best performances with pioggia.background(0,0);
for(int i = 0; i<gocceNum; i++){
  gocce[i][2] = (gocce[i][2]+gocceSpX*0.25)%back1.width;
  gocce[i][3] = (gocce[i][3]+gocceSpY*0.25)%back1.height;
  pioggia.set((int)gocce[i][2],(int)gocce[i][3], #355B4A);
}
pioggia.endDraw();
copy(pioggia, (int)quantize(disp*0.4, scalaH), 0, sw, sh, 0, 0, width, height);
```

## My Environment
* Processing version: 3.3.7
* Operating System and OS version: Windows 10 64-bit

**Comment by gohai** [comment]
Bug reports concerning the Android mode should go here: http://github.com/processing/processing-android
