### ISSUE TITLE
Wrong error message when array is write outside method

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5460]
`unexpteted token:[` is maybe a bad message to show this error, I pass one hour to find the token error, before find is not possible to write that before method or class... this console message put me in the trouble :)

![capture d ecran 2018-04-01 a 14 24 31](https://user-images.githubusercontent.com/3332269/38173126-f7f7d044-35b8-11e8-96cc-94f9249e624d.png)

**Comment by jeremydouglass** [comment]
You may declare or assign in a function or method:

```
void setup(){
  int[] n = {0, 1};
  n = new int[]{2}; // legal
  n[0] = 3;         // legal
  print(n[0]);
}
```
...but you may only declare(+assign) globally:

```
int[] n = {0, 1};

n = new int[]{2};   // illegal
n[0] = 3;           // illegal

int x;
x = 0;              // illegal

void setup(){
  print(n[0]);
}

```

**Comment by StanLepunK** [comment]
Thx for the information, sorry for this outside question :(
