### ISSUE TITLE
TIS/TSM warning message with P2D/P3D/OPENGL since macOS 10.13.4

### ISSUE THREAD

**Issue by ramunde** [processing/processing#5462]
I posted this issue on the Coding forum and found no solutions, so I'm presenting it here.  

I am running Processing 3.3.7 on a Mac Pro running MacOS 10.13.4.  Whenever I run a sketch that uses P3D, the sketch runs, but I get the following error message:

2018-04-01 23:47:20.680 java[56414:3391796] pid(56414)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!

As an example, here is a sketch I keyed in from Read and Fry's Processing handbook, ed. 2 that produces the error on my system:

size(100, 100, P3D);
background(0);
lights();
translate(0, height/2, -height/4);
sphere(50);
translate(width, 0, -height/2);
sphere(50);

Thanks in advance.

**Comment by gohai** [comment]
Really puzzled by this error, as I can't even find any reference to "TIS/TSM" elsewhere online. Not happening when I try it. (Is this a Macbook Pro with dedicated graphics?)

**Comment by gohai** [comment]
BTW: I am running 10.13.3. I see that 10.13.4 added support for external GPUs, so this could plausibly have changed things. Have you seen this error also before updating macOS recently?

**Comment by gohai** [comment]
@ramunde You say the sketch is running correctly?

**Comment by ramunde** [comment]
It's a Mac Pro (2013) with dual AMD FirePro D500 3072 MB graphic  cards.  I hadn't tried any sketches using P3D before upgrading to MacOs 10.13.4 so I can't say if the error appeared in version 10.13.3.  Yes, the sketch runs, but the error message is written to the console.

**Comment by gohai** [comment]
Thank you, @ramunde. We'll see if more people report this - thinking that this could either be an issue with the specifics of your graphics situation (driver), which is complaining about the way OpenGL is done in Processing. Or the same, but discouraged instead by macOS 10.13.4.

In either way, there is probably not much we can do in the immediate future about this. Hope you can ignore the message for the time being.

**Comment by ramunde** [comment]
I’m running MacOs 10.13.4 on a MacPro (early 2013) with dual AMD FirePro D500 3072 MB cards.

**Comment by owenscymru** [comment]
I am getting the same error with either P3D or OPENGL in the size declaration.

**Comment by ramunde** [comment]
Sorry for your woes, but at least we're not alone.  Must be a High Sierra thing.

**Comment by skatalites** [comment]
Hello same I have the error, MacOS High Sierra 10.13.4, Processing 3.3.7, MacBook Air

**Comment by gohai** [comment]
Just updated to 10.13.4, and now I see it as well.

**Comment by skatalites** [comment]
Hello, I was checking my Java version

java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

Anyone has the same version of Java?

**Comment by gohai** [comment]
@skatalites We already narrowed it down to the newly-released macOS version causing this message. In any way, this might be irritating, but just a warning in the Console... sketches work the way they did before!

**Comment by ramunde** [comment]
Just realized that after I reinstalled High Sierra I never installed Java.  I just did and (drum roll) I got the same error message. I'm running Version 8 Update 161 (build 1.8.0_161-b12) on a Mac Pro running High Sierra 10.13.4.

**Comment by ramunde** [comment]
Thank you.

**Comment by marcedwards** [comment]
Same issue here. macOS 10.13.4, iMac Pro, Radeon Pro Vega 56.

The error doesn’t seem to be stopping Processing from working as expected though.

**Comment by toto3** [comment]
Same issue with macOS 10.13.4, Mac mini late 2012 , Inter Hd Graphics 4000 1536 mo

java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

and Processing 3.3.7.
At Lest the sketch still run fine.

**Comment by zeynepozcan** [comment]
Same issue
10.13.4, Mac Book pro mid 2015, AMD Radeon R9 M370X 2048 MB graphics

I am using Processing 3.3.6 and my sketch also runs.

**Comment by gohai** [comment]
We have by now more than established that this message got introduced with macOS 10.13.4 and that it happens on all systems running macOS.

No need to add more comments saying that you are seeing this as well! Thanks for everyone's reports so far.

**Comment by Menokillah** [comment]
Same machine and OS, but also getting warning when using P2D.

**Comment by gohai** [comment]
@Menokillah Expected, since P2D uses the JOGL OpenGL library just like P3D does.

**Comment by JE55E** [comment]
Within the same context of this TIS/TSM warning, has anyone run into issues with sample.loop() causing a "quit unexpectedly" popup at the loop point? Using processing.sound library...

Tried switching to minim library but the loop() sketch won't run - strange coincidence.

**Comment by yufzhang5** [comment]
Same problem when using P3D on mac OS 10.13.4.

**Comment by Lou66** [comment]
Try running Daniel Shiffman's coding challange no.2 Menger Sponge.
This sketch has always run perfectly since last september, now I'm getting the TIS/TSM error, and while the sketch runs only the cube is drawn not the sponge part.
I'm using a mac-mini.

**Comment by gohai** [comment]
Locking this thread for comments (see https://github.com/processing/processing/issues/5462#issuecomment-380654805). The warning should be harmless and was introduced with macOS 10.13.4 - this shouldn't affect your sketches adversely, but it's something we sure hope to silence in due time.

**Comment by codeanticode** [comment]
Yes, does not seem that we can do much about this error message other than silence it, unless it is fixed upstream in JOGL :-)

I run a simple [test JOGL program,](https://github.com/codeanticode/jogl2-tests/blob/master/src/test/animator/AnimatorNEWT.java) and simply creating a NEWT window object without doing anything else is enough to trigger the error.

**Comment by codeanticode** [comment]
@benfry I silenced the error with https://github.com/processing/processing/commit/f512457c6e6034a1230161a01080ede5f431eebb

[This discussion](https://forums.developer.apple.com/thread/105244) makes me think it should not be a huge source of concern... at least for the time being.

**Comment by benfry** [comment]
Ok, closing as fixed for the next release (whatever comes after 3.4).
