### ISSUE TITLE
Crash when try to start my compiled jar file using Processing lib in Intellij P3D Ubuntu

### ISSUE THREAD

**Issue by alagerkvist** [processing/processing#5469]
Hello fellas, couldn't find anything about this in issues.

I using processing core lib in Intellij (also has peasycam and so on), setup by Maven. Saying that, it goes very smooth running it directly from Intellij. How ever, when I do an Artifact with Intellij so it creates a .jar file, but when I try to run it, the program crashes when starting.
The error message I get is following, 

> FatalError Java_jogamp_nativewindow_x11_X11Lib: can't find javax/media/nativewindow/util/Point

Before I got this error, it said that it couldn't find nativewindow_x11_X11Lib file, so I found that file on internet and downloaded it, and placed it where it said it could find it (~/IdeaProjects/myproject/natives/linux-amd64).

This is my pom.xml file using in the project. 

    <dependencies>
        <dependency>
            <groupId>org.processing</groupId>
            <artifactId>core</artifactId>
            <version>3.3.6</version>
        </dependency>
        <dependency>
            <groupId>org.processing</groupId>
            <artifactId>net</artifactId>
            <version>3.3.7</version>
        </dependency>
        
       <dependency>
           <groupId>org.jogamp.jogl</groupId>
           <artifactId>jogl-all-main</artifactId>
           <version>2.3.2</version>
       </dependency>
        
        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt-main</artifactId>
            <version>2.3.2</version>
        </dependency>
        <dependency>
            <groupId>peasycam</groupId>
            <artifactId>peasycam</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>/home/deggo/sketchbook/libraries/peasycam/library/peasycam.jar</systemPath>
        </dependency>
    </dependencies>

And I've the simplest sketch ever, 4 points and line to each point (works in Intellij as I said so shouldn't be that, right?). 

I've no idea where to start actually, so a helping hand would be great. And if I forgot something, please let me know and I'll update the post. please

Thanks in advance!

My environment:
Linux  4.4.0-119-generic #143-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
javac 1.8.0_162
Intellij 2017.1.5

**Comment by gohai** [comment]
That sounds like an issue related to your custom setup rather than a bug in Processing. You might try to get help in the [forum](http://forum.processing.org/) for this.
