### ISSUE TITLE
PShape::strokeWeight doesnt create the lines that corresponds with the actual value when using upscaled objects

### ISSUE THREAD

**Issue by AndreusMaximus** [processing/processing#5472]
## Description
PShape::setStrokeWeight() wont set the right stroke weight. When the stroke weight is 1 it wont show, and when its 1.1 its so thick that the shape itself gets covered.
setStroke(color(255,0,0)) will only show black
It are low poly objects made in Maya

## Expected Behavior
i expexted to see a small line over the edges of the object in the selected color. 

## Current Behavior
When i set the strokeweight to 1f it doesnt show any lines
![hand](https://user-images.githubusercontent.com/12559003/38780975-ce9baa32-40de-11e8-8168-c65f68914f03.PNG)

And when i set the strokeWeight to 1.01f it just gets completely blurred
![hand2](https://user-images.githubusercontent.com/12559003/38780990-fe10bad2-40de-11e8-975c-7336589d4c63.PNG)

## Steps to Reproduce

1.Object is made in Maya, and its low poly
2. Loaded in using loadShape()
3. setStroke(enable) is called
4. stroke is set with setStroke(color(0,0,0))
5. strokeWeight is set with setStrokeWeight(1.01f);
6. object is drawn in draw()

## Possible Causes / Solutions
I've tried different steps
- setting the color and weight before scaling
- disableing the style 
- putting in a really small number in the strokeweight but still >1
- loading in a really big model and then scaling it down does give the desired result

**Comment by benfry** [comment]
Please use https://forum.processing.org for coding questions.
