### ISSUE TITLE
In linux, processing3.3.7 is only showing black screen in the mpu6050 - teapot example. The data is coming in the console but the screen is black only

### ISSUE THREAD

**Issue by Sreekiranar** [processing/processing#5474]
## Description
I have installed processing 3.3.7 64 bit version. Im doing the basic example or mpu6050 gyrometer+ accelerometer sensor visualising using processing example. 
The reference link for the example is given below:
https://maker.pro/education/imu-interfacing-tutorial-get-started-with-arduino-and-the-mpu-6050-sensor
Everything is working correctly except the output of the processing is showing only black screen.
The data is coming to the console
## Expected Behavior
Please specify the pre-requisite software required to clear this issue.
* Processing version:3.3.7
* Operating System and OS version: Ubuntu 14.04

**Comment by gohai** [comment]
Do some of the default P3D examples, such as `Basics/Lights/Directional` work?
