### ISSUE TITLE
Are HDR colorspaces and HDR displays supported?

### ISSUE THREAD

**Issue by quinton-ashley** [processing/processing#5477]
When will HDR support be available or is it already available?

**Comment by benfry** [comment]
No current support for it, and unlikely to be implemented anytime soon. This is a *massive* undertaking, and nearly impossible to do in a cross-platform way at the moment.

**Comment by quinton-ashley** [comment]
I just want to say that I'm huge fan of yours and thank you for responding.  I started learning how to program using Processing! 😁  

It would actually be impossible to do cross platform right now since macOS does not support HDR yet.  Couldn't it be supported on Windows first though?  macOS will probably support HDR by next year since there's already an HDR iPad.  More and more people have HDR displays and that will result in more people that want to make HDR art with Processing. Youtube and Netflix have supported HDR for a while now so people can easily view HDR content.  I'm eager to be able to use an expanded color palate with Processing so your response disappoints me.  I think it would be a big mistake putting this off for much longer.  I would like to help implementing it but I don't know where to start.  What do you think needs to be done to get it working?  Why is it such a massive undertaking?

**Comment by benfry** [comment]
I'd love to have HDR support, but there's no OS support for it, and nobody's helping me implement it. Like so many features with Processing, it's less about whether I think it's important, whether I want it, etc than whether it's even possible given constraints of time, platforms, priorities, and how much time/energy I have to work on Processing after I've put in a full day's work. It's disappointing for me too.

**Comment by quinton-ashley** [comment]
HDR support is available on Windows 10.  There is an HDR switch in the OS display settings.  There is OpenGL support for HDR as well.  If you could re-open this issue so other people could see it then maybe someone would offer to help.
