### ISSUE TITLE
stroke() adds 1px to height and width of rect()

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#548]
_Original author: kevvy.lo...@gmail.com (January 17, 2011 09:17:16)_

<b>If it's a problem with the Processing Core and Android software, please</b>
<b>answer the following:</b>

<b>What steps will reproduce the problem?</b>

for example, compare these two rectangles:

pushStyle();
  noStroke();
  fill(0);
  rect(10, 10, 3, 3);
popStyle();

pushStyle();
  stroke(255, 0, 0);
  fill(0);
  rect(15, 10, 3, 3);
popStyle();

<b>What is the expected output? What do you see instead?</b>

stroke() should be contained entirely within the pixels which define the rect().

<b>What version of the product are you using? On what operating system?</b>

1.2.1 on 10.6.6

_Original issue: http://code.google.com/p/processing/issues/detail?id=509_

**Comment by aengelke** [comment]
Isn't this the same as #2065?

**Comment by JakubValtar** [comment]
The center of the stroke goes through the verices of the shape. If your stroke weight is 1 px, then 0.5 px overlaps the shape and 0.5 px goes outside of the shape. If your stroke weight is 10 px, you get 5px overlap.

In case of rect and 1 px stroke, total width increases by 0.5 px on the left + 0.5 px on the right = 1 px.

In P2D with default transformation matrix, we move thin strokes by 0.5 px down and to the right so they align with pixel grid and don't get blurred by being in 0.5 px in one pixel column/row and 0.5 px in the other.

**Comment by benfry** [comment]
The explanation is really helpful, can you add it to the "common problems / not bugs" FAQ?

**Comment by JakubValtar** [comment]
I'll add it.
