### ISSUE TITLE
An error occurred during startup.

### ISSUE THREAD

**Issue by minjii8971** [processing/processing#5482]
## Description

<img width="690" alt="screen shot 2018-04-23 at 4 22 13 pm" src="https://user-images.githubusercontent.com/38662017/39133014-7fc7fb82-4713-11e8-829b-96bd14b41955.png">

## Expected Behavior
 open the processing

## Current Behavior
 I cannot open the processing. 

## Steps to Reproduce

1.
2.
3.

## Your Environment
 
 

* Processing version: processing 3
* Operating System and OS version: macOS Sierra version 10.12.6
* Other information:

**Comment by gohai** [comment]
Looks like your copy of Processing is missing some file. Can you try clearing your browser cache, downloading http://download.processing.org/processing-3.3.7-macosx.zip, extracting the ZIP file, and moving the contained application into your "Applications" folder - before trying to launch it from there?

**Comment by benfry** [comment]
No response; closing. It appears this was using version 3.3.7, but if anyone else sees a `NullPointerException` inside `buildCoreModes()` like this, please file a new bug.
