### ISSUE TITLE
Unable to load webcam stream

### ISSUE THREAD

**Issue by willtmakinen78** [processing/processing#5483]
## Expected Behavior
I print the capture devices list, see the entry I want to use, and open the one I want. Upon runnning some basic almost-example code, I see my video stream in the window.

## Current Behavior
For certain webcam configurations above a certain data rate, I only see a gray screen. It works for lower resolution, high framerate (480p 30fps) configurations, and higher resolution, lower framerate (720p 9fps) configurations. However fairly reasonable configurations, such as 720p 30fps, result in a gray screen. Any auxiliary code runs fine. This persists even with several different webcams. When it does work, the webcam light turns on, when it doesn't the light is off.

## Steps to Reproduce
Code:

import processing.video.*;
Capture video;

void setup() {
  size(1280, 720);
  printArray(Capture.list());
  video = new Capture(this, Capture.list()[0]);
  
  video.start();
}
void draw() {
  image(video, 0, 0);
}
void captureEvent(Capture video) {
  video.read();
}

## Your Environment
Processing 3.3.7
Windows 10

## Possible Causes / Solutions
Attached are two screenshots showing the issue.
![high_res_not_working](https://user-images.githubusercontent.com/35124538/39136662-c2878660-46e9-11e8-94e0-12d8fb3a018c.png)
![low_res_working](https://user-images.githubusercontent.com/35124538/39136664-c2a91212-46e9-11e8-9b88-0699b014c389.png)

**Comment by gohai** [comment]
This is an issue pertaining to the Video library - issues for which are collected over at: http://github.com/processing/processing-video
