### ISSUE TITLE
PGraphics Issue with transparent color

### ISSUE THREAD

**Issue by thereventonshow** [processing/processing#5484]
I need to reproduce PGraphics image into another PGraphics image with a larger or smaller size for 2D pixelised Image, I'm using this method to create the PGraphics expected : 
`//pxIN : size of an pixel in the new image
//actSier : size of an pixel in the actual image

```
void setSize(int pxIN) {
    PGraphics newImage = createGraphics((image.width/actSize)*pxIN, (image.height/actSize)*pxIN);
    newImage.beginDraw();
    newImage.noStroke();
    int k = 0;
    for (int i = 0; i < image.pixels.length; ) {
      if (alpha(image.pixels[i]) != 0) {
        newImage.fill(image.pixels[i]);
        newImage.rect(k%newImage.width, k/newImage.width, pxIN, pxIN);
      }
      k += pxIN;
      if (k%newImage.width == 0) {
        k += (pxIN-1)*newImage.width;
      }
      i += actSize;
      if (i%image.width == 0) {
        i += (actSize-1)*image.width;
      }
    }
    newImage.endDraw();
    image = newImage;
    actSize = pxIN;
}
```
Problem is that with pixel color that have an alpha not equal to 255 (so that have transparency) will appear distorted (not the exact color) exept that the alpha will be fine.
To simplify the problem we can see in this code the distortion that i'm talking about:

```
PGraphics original, A, B;

void setup(){
  original = createGraphics(5, 5);
  original.beginDraw();
  original.background(198, 198, 198, 198);
  original.endDraw();
  println("COLOR original");
  printcolor(original.pixels[0]);
  
  A = createGraphics(15, 15);
  A.beginDraw();
  A.noStroke();
  A.fill(original.pixels[0]);
  A.rect(0, 0, A.width, A.height);
  A.endDraw();
  println("COLOR A");
  printcolor(A.pixels[0]);
  
  B = createGraphics(15, 15);
  B.beginDraw();
  B.background(original.pixels[0]);
  B.endDraw();
  println("COLOR B");
  printcolor(B.pixels[0]);
}

void printcolor(color a){
  println(red(a) + " " + green(a) + " " + blue(a) + " " + alpha(a));  
}
```

![image](https://user-images.githubusercontent.com/27006725/39172470-2a0f63f8-47a2-11e8-99aa-705a61d2829f.png)

For some reason using the background method (with B) will not make that distorsion, but we can see that using the rect method (with A) we have this distortion, the problem is that I can't use the background to draw pixelised Image.

Processing version : 3.2.3
Os : Windows 10

**Comment by thereventonshow** [comment]
I have tried it on another PC with Windows 8 and Processing 3 and I'm not having this distorion.

![capture](https://user-images.githubusercontent.com/27006725/39172753-fa11d45a-47a2-11e8-8356-9bb795f80f97.PNG)

 I'll check on my PC with an updated version of processing

**Comment by thereventonshow** [comment]
No, even with the updated version of processing it still make that distortion in my computer

![image](https://user-images.githubusercontent.com/27006725/39179991-0ba7ccac-47b6-11e8-80e0-08564ab61ee9.png)

Could it do that because of the OS ?

**Comment by thereventonshow** [comment]
I've already tried with the updated driver but I still have this issue.
If someone have an gtx970  and don't have the issue, please let me know your driver version.

**Comment by hamoid** [comment]
Does it help to call
```
original.loadPixels();
A.loadPixels();
B.loadPixels();
```
before trying to access the pixels arrays?

**Comment by hamoid** [comment]
What about this version that uses P2D instead of JAVA2D?
```
PGraphics original, A, B;

void setup(){
  size(100, 100, P2D);
  original = createGraphics(256, 256, P2D);
  original.beginDraw();
  original.background(198, 198, 198, 198);
  original.endDraw();
  println("COLOR original");
  original.loadPixels();
  printcolor(original.pixels[0]);
  
  A = createGraphics(256, 256, P2D);
  A.beginDraw();
  A.noStroke();
  A.fill(original.pixels[0]);
  A.rect(0, 0, A.width, A.height);
  A.endDraw();
  println("COLOR A");
  A.loadPixels();
  printcolor(A.pixels[0]);
  
  B = createGraphics(256, 256, P2D);
  B.beginDraw();
  B.background(original.pixels[0]);
  B.endDraw();
  B.loadPixels();
  println("COLOR B");
  printcolor(B.pixels[0]);
}

void printcolor(color a){
  println(red(a) + " " + green(a) + " " + blue(a) + " " + alpha(a));  
}
```

**Comment by thereventonshow** [comment]
![image](https://user-images.githubusercontent.com/27006725/40496468-19f8fe62-5f7a-11e8-872a-da44147726d1.png)

Surprisingly the distortion is reduced with P2D, the size do not affect the distortion, tried with 10, 100, 1000 width/height.

Switching to P3D get the same result as P2D, but we still have an bigger distortion with JAVA2D.

So well with P3D/P2D render mode + loadPixels() the distortion isn't that bothering, thank for the advice.

**Comment by benfry** [comment]
Is this issue resolved? Can we close it?

**Comment by thereventonshow** [comment]
I guess there is no better solution so I'll close it.
