### ISSUE TITLE
P2D and P3D not working in WIndows 10 on Surface Pro i7 with 3.37

### ISSUE THREAD

**Issue by nosarious** [processing/processing#5494]
## Description
Using P2D and P3D will not open a window if I use Processing 3.3.7 for windows 64-bit ...

## Expected Behavior
I expect a window to open so the result of a my sketch is displayed

## Current Behavior
No window opens, not even in the task bar. No errors are given.

## Steps to Reproduce
If I start a sketch, even the simplest, with P3D set in size, there will be no window (not even in the task bar). Letting the system run for several minutes will not open a delayed window.

void setup() {
   size(120, 120, P3D);
}
void draw() {
}

## Your Environment
Processing 3.36 works properly. this only started happening with Processing 3.37

This is on Windows 10, latest update, on a Surface Pro i7 (late 2017)

If I start a sketch, even the simplest, with P3D set in size, there will be no window (not even in the task bar). Letting the system run for several minutes will not open a delayed window.

I have updated video drivers (intel Iris 640) and Java (version 8 update 171), but 3.3.7 will not open a window for P2D or P3D.

## Possible Causes / Solutions
My current solution is to use Processing 3.3.6 for exploring ideas.

**Comment by nosarious** [comment]
Processing 3.36 works properly. this only started happening with Processing 3.37

This is on Windows 10,latest update, on a Surface Pro i7 (late 2017)

If I start a sketch, even the simplest, with P3D set in size, there will be no window (not even in the task bar). Letting the system run for several minutes will not open a delayed window.

'''void setup() {
  size(120, 120, P3D);
}
void draw() {
}'''

I have updated video drivers (intel Iris 640) and Java (version 8 update 171), but 3.3.7 will not open a window for P2D or P3D.

**Comment by gohai** [comment]
@nosarious Could you replace the `jogl-all.jar` in 3.3.7 with [this file](https://github.com/processing/processing/raw/691fc29d9529266a4cff7294353147cb8cdb728c/core/library/jogl-all.jar) and report back if this makes a difference? Thanks!

**Comment by nosarious** [comment]
Thanks for getting back so soon, @gohai 

Unfortunately, replacing that jogl-all.jar file and re-running the simplest program did not make a difference for running a P2D or P3D sketch on this computer.

**Comment by gohai** [comment]
@nosarious Finally, you could also try if using the `java` folder from 3.3.6 makes it work on 3.3.7.

**Comment by nosarious** [comment]
I swapped the java folder from 3.3.6 to 3.3.7 and it still does not open a window for the sketch, nor anything in the task bar.

**Comment by benfry** [comment]
Perhaps try turning off Windows Defender or your virus scanning software? It's possible they're interrupting the sketch from running.

**Comment by nosarious** [comment]
I tried disabling Windows Defender but it did not seem to make a difference. It did not seem to be keeping a log of anything it stopped from running that was processing/java related.

I also tried updating Java and that did not make a difference either.

**Comment by nosarious** [comment]
The latest version of Processing, version 3.4 works properly. YAY!

**Comment by benfry** [comment]
That’s great news! Thanks for reporting back. Sounds like it may have been a java problem that was fixed with the new version included in 3.4.
