### ISSUE TITLE
NoClassDefError: processing/core/PApplet on startup with Windows 10

### ISSUE THREAD

**Issue by SR--** [processing/processing#5495]
![image](https://user-images.githubusercontent.com/1008059/39463538-dded7f90-4d5b-11e8-9982-2162cf924095.png)

**Comment by gohai** [comment]
@SR-- Could you try re-download the ZIP file, and uncompressing it entirely into a folder before executing Processing.

**Comment by ganeshmuni** [comment]
tried but didn't work

**Comment by benfry** [comment]
Perhaps this issue? https://github.com/processing/processing/issues/5537

**Comment by benfry** [comment]
Closing as duplicate of #5537.
