### ISSUE TITLE
Backspace not calling keyReleased on Android

### ISSUE THREAD

**Issue by hunterkiddo** [processing/processing#5499]
## Description
I'm using processing Android version, so I'm using the android keyboard to edit a String. A very weird and unwanted behavior has come up where for each key I press, I have to press the backspace key that many times before the backspace key starts calling the keyReleased

My code:
`void keyReleased() {`
 ` println("key released: " + keyCode);`
   ` if (key == ENTER || key == RETURN || keyCode == 66) {`
      `closeKeyboard();`
      `partySave.setString(0, "name", popUp.returnInput()); //set name`
   ` } else {`
    `  popUp.update();`
   ` }`
   ` break;`
`}`

and the popup.update() code:
`void update() {`
   ` key = newKey;`
    `if (newKey != CODED) {`
    `  if ((newKey >= 'A' && newKey <= 'Z') || (newKey >= 'a' && newKey <= 'z')) {`
      `  input += newKey;`
      `}`
    `} else if ((key == BACKSPACE || key == DELETE || keyCode == 67) && input.length() > 0) {`
   `   println("backspace");`
  `    input = input.substring(0, input.length() - 1);`
 `   } else {`
    `  println("key is coded");`
    `}`
 ` }`

If backspace is the first thing I press, then it calls it no problem. If I press 'a' and then 'backspace;' 'a' will be pressed, but 'backspace' won't be. If I press 'a' and then 'backspace,' and then 'backspace' again, it will type 'a' and then delete 'a' after the second press of 'backspace.' How can I get it to call keyPressed() every single time, or at least be able to use the backspace key every single time. Thank you!

(I even opened the keyboard input example provided by processing and loaded it up on android to see if it had the same behavior, and it does)

**Comment by gohai** [comment]
Android issues go [here](https://github.com/processing/processing-android)
