### ISSUE TITLE
Ellipse rendering past stroke

### ISSUE THREAD

**Issue by samsamson33** [processing/processing#5500]
## Description
When displaying an ellipse with stroke, the ellipse displays outside of the stroke.
![image](https://user-images.githubusercontent.com/35579293/39836321-f139a790-53a0-11e8-98d1-71744a28381f.png)

## Steps to Reproduce
1. display an ellipse with a stroke that differs from the background

## Your Environment

 

* Processing version:3.3.7
* Operating System and OS version: x64 Windows 10 home

**Comment by jeremydouglass** [comment]
@samsamson33 can you provide sample sketch code, or should this issue be closed?

**Comment by benfry** [comment]
No response; closing.

**Comment by samsamson33** [comment]
For anyone having this problem in the future, it was caused by Windows 10 high-DPI display scaling.

**Comment by jeremydouglass** [comment]
@samsamson33 -- if you want this to be testable with Windows 10 high-DPI scaling, provide the code for a sample sketch that produces the problem, please.
