### ISSUE TITLE
Mac build fails on current master

### ISSUE THREAD

**Issue by Sosukodo** [processing/processing#5509]
## Description
Mac build fails on latest in master

## Current Behavior
compile:
  [methods] No changes to PApplet API.
    [javac] Compiling 5 source files to /Users/sosukodo/Developer/Git/processing/core/bin
    [javac] ----------
    [javac] 1. ERROR in /Users/sosukodo/Developer/Git/processing/core/src/processing/javafx/PSurfaceFX.java (at line 249)
    [javac] 	float renderScale = Screen.getMainScreen().getRenderScale();
    [javac] 	                                           ^^^^^^^^^^^^^^
    [javac] The method getRenderScale() is undefined for the type Screen
    [javac] ----------
    [javac] 2. ERROR in /Users/sosukodo/Developer/Git/processing/core/src/processing/javafx/PSurfaceFX.java (at line 252)
    [javac] 	renderScale = Math.max(renderScale, s.getRenderScale());
    [javac] 	                                      ^^^^^^^^^^^^^^
    [javac] The method getRenderScale() is undefined for the type Screen
    [javac] ----------
    [javac] 3. ERROR in /Users/sosukodo/Developer/Git/processing/core/src/processing/javafx/PSurfaceFX.java (at line 255)
    [javac] 	float uiScale = Screen.getMainScreen().getUIScale();
    [javac] 	                                       ^^^^^^^^^^
    [javac] The method getUIScale() is undefined for the type Screen
    [javac] ----------
    [javac] 3 problems (3 errors)

## Steps to Reproduce
git clone https://github.com/processing/processing.git
cd build
ant run

1.
2.
3.

## Your Environment
10.9, javac 1.8.0_25

 

* Processing version:
* Operating System and OS version:
* Other information:

## Possible Causes / Solutions

git checkout

**Comment by benfry** [comment]
As the build instructions say, use Java 8 (I'll add a note there to more explicitly say that later versions of Java are not supported)
https://github.com/processing/processing/wiki/Build-Instructions

More about Java 9 and later:
https://github.com/processing/processing/wiki/Supported-Platforms#java-9-10-and-11

**Comment by Sosukodo** [comment]
What does javac 1.8.0_25 indicate?
