### ISSUE TITLE
Provide SHA512 and SHA256 checksums

### ISSUE THREAD

**Issue by einsteinsfool** [processing/processing#5510]
## Description
Provide SHA512 and SHA256 checksums for all files both on the [download page](https://processing.org/download) and GitHub in the releases section. All in plaintext so users don't need to download the checksum which would defeat the whole purpose of them.

PS Both [MD5](https://en.wikipedia.org/wiki/MD5#Security) and [SHA1](https://en.wikipedia.org/wiki/SHA-1#SHAttered_%E2%80%93_first_public_collision) are breaked and shouldn't be provided because they give a false sense of security.

## Expected Behavior
After downloading the file I should be able to verify if the file I have is the same as the one uploaded by the maintainers.

## Current Behavior
Users can't verify the downloaded files.

## Steps to Reproduce
1. Download an installer.
2. An attacker intercepts the file and swaps it with a modified malicious one.
3. Don't verify the file because there are no checksums.
4. Get ~~f...~~ hacked. (couldn't resist)

**Comment by gohai** [comment]
You're downloading the file from GitHub through HTTPS. If an attacker is able replace the installer on GitHub, then he/she is also able to replace the checksum posted there.

**Comment by einsteinsfool** [comment]
Correct. That's why I also asked for posting the checksums on your download page. Attacker would also have to hack (or make a phishing version) that site. Also, it would be a good idea to add the `releases` page to the [Internet Archive](https://web.archive.org) after adding each release. That way someone can compare current checksum with checksum from release date.

**Comment by benfry** [comment]
No plans to implement this, as @gohai suggests, the odds of this happening are vanishingly small.
