### ISSUE TITLE
Solution For a Processing Lib Bug: Video# A library relies on native code that's not available. Or only works properly when the sketch is run as a 32-bit application.

### ISSUE THREAD

**Issue by YunhuaGong** [processing/processing#5511]
## Description
**Running into an error when running Processing example code**

I was using the latest version of Processing to run Mr. Schiffman's example code for the Video Chapter. But I encountered a problem. The programme showed an error saying: 

> A library relies on native code that's not available. Or only works properly when the sketch is run as a 32-bit application.

![image](https://user-images.githubusercontent.com/33687545/40268416-765d793c-5b9f-11e8-99cf-f2d0a36f8aaa.png)

## Possible Causes / Solutions
I asked my Coding Mentor John and he saw what the cause of the problem was. I used a Chinese character as my computer username. Non-ASCII chars in the path are unacceptable for the system. 
![image](https://user-images.githubusercontent.com/33687545/40268474-5d2130a2-5ba0-11e8-8000-9bbb60302b5e.png)

So there are two solutions for this problem.

**

> - Solution 1: Remove all files to a C:/ folder.
> - Solution 2: Change username.

**

I chose Solution 1, and it worked! 

1. I copied the new path.
2. I opened Processing. File > Preferences > Paste the new path into the Sketchbook location.
And now I can run the example code with lib smoothly.
![image](https://user-images.githubusercontent.com/33687545/40268493-c8736294-5ba0-11e8-85af-964d6eb07bbe.png)
![image](https://user-images.githubusercontent.com/33687545/40268555-2ae556b6-5ba2-11e8-914c-d5e04012bf13.png)

## Expected Behavior
Possible Fixes: **Unicode Support** for Library Paths

## Your Environment
* Processing version:  **Processing 3.3.7**
* Operating System and OS version: **Windows 10**
* Other information: **64 bit**

**Comment by YunhuaGong** [comment]
**A list of all the associated threads related to this problem.**
https://github.com/processing/processing-video/issues/90
https://github.com/processing/processing/issues/5453
https://github.com/shiffman/OpenKinect-for-Processing/issues/30
https://github.com/processing/processing-docs/issues/633
https://forum.processing.org/two/discussion/7094/library-is-not-installed-properly-the-sketch-is-not-run-as-a-64-bit-application

**Comment by benfry** [comment]
Please post video issues over here: https://github.com/processing/processing-video
