### ISSUE TITLE
"A serious problem happened during startup."

### ISSUE THREAD

**Issue by IPandaI** [processing/processing#5512]
im getting this error when i try to download processing

![image](https://user-images.githubusercontent.com/23087156/40280444-38c436a6-5c08-11e8-8426-60ec9f634346.png)

im not sure what or why its happening.

**Comment by jeremydouglass** [comment]
1. What is your operating system / version?
2. Did you extract the zip before running?
3. Have you looked at these other issues with the same error message?

-  https://github.com/processing/processing/search?q=%22meant+to+be%22&type=Issues

**Comment by IPandaI** [comment]
Ya i just looked at the one recommended, and the 32-bit does work for me.
