### ISSUE TITLE
No toolbar/menu in processing 

### ISSUE THREAD

**Issue by bjente** [processing/processing#5516]
Hi, 

<img width="1680" alt="schermafbeelding 2018-05-25 om 14 26 17" src="https://user-images.githubusercontent.com/39591427/40562470-624234b2-6061-11e8-9e6c-5c4d52e4e609.png">
I downloaded the latest version of Processing but as you can see in the attached image, I don't have a toolbar/menu. I have to do everything with shortcuts but they often don't work or I simply don't know the keyboard shortcut. I had the same problem with the previous versionS of Processing. Does anybody know how this is possible and how I can fix this?

Thanks in advance

**Comment by benfry** [comment]
Probably a better question for the forum, since this is likely something installed on your machine that's causing a problem.
