### ISSUE TITLE
SelectInput work bad on OSX Sierra with thumbnail display

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5517]
## Description
 Cannot select other file after the first with the mouse, and selection work bad with the keyboard with UP,DOWN,LEFT and RIGHT, only on thumbnail mode, work fine with the other. 
Maybe it's a Java bug, that's work fine with other application like Photoshop.
![capture d ecran 2018-05-28 a 11 11 48](https://user-images.githubusercontent.com/3332269/40607725-91aa75f2-6269-11e8-94d2-1342f530e755.png)

## Your Environment
* Processing version: 3.3.7
* Operating System and OS version: OS sierra 10.12.6

```
void setup() {
  selectInput("Select a file to process:", "fileSelected");
}

void fileSelected(File selection) {
  if (selection == null) {
    println("Window was closed or the user hit cancel.");
  } else {
    println("User selected " + selection.getAbsolutePath());
  }
}
```

**Comment by jeremydouglass** [comment]
@StanLepunK are you saying that you want to multi-select many files in the file dialog, and have a list of them returned to selectInput?

**Comment by StanLepunK** [comment]
I don't try with a multi-selection, just change selection. That's work fine with column but not in this mode window displaying. The behavior is very erratic behavior, I hope my description give an idea of problem.

**Comment by benfry** [comment]
This is out of our control, unfortunately. The dialog is provided by Java/the OS.
