### ISSUE TITLE
On Specifying the Renderer, sketch is taking too much time to open the Sketch 

### ISSUE THREAD

**Issue by viv1kk** [processing/processing#5521]
I’m currently using Processing 3, version 3.3.7.

PC Specs :
Windows 10 Home
Core i5 7200u
4GB RAM
Intel Graphics 620

I’m beginner to Processing 3, so, I don’t know much about it now but the size function has three Parameters. When I don’t specify the third Parameter the Sketch opens quickly.
eg. size(640,480);

But, when it specify the third Parameter with P3D or P2D, the sketch takes about 1-2 minutes to open.
eg. size(640,480,P3D);

From other forums, I found that its a problem of Open GL which can be removed by Updating my
graphic driver but the problem still exist. Also all the other drivers are also updated…

There is not any resource shortage issues as the processor remains under 20%, ram and disk usage is at normal when i try to open the sketch.

**Comment by JakubValtar** [comment]
Are you using any antivirus software? It might be caused by an antivirus software scanning the OpenGL libraries. Could you try to run the sketch with disabled antivirus to see if that is the problem?

**Comment by viv1kk** [comment]
This worked for me.. Thanks for the help
