### ISSUE TITLE
Unable to pass arguments to exported sketch (OSX)

### ISSUE THREAD

**Issue by onimatrix** [processing/processing#5527]
Command line arguments are not being sent into exported sketches on OSX on Processing 3.3.6

I just added a feature that requires arguments to the Windows build of the sketch, where it behaves as I expected.
It should behave the same on OSX.

I've written a testbed to replicate the issue:

```
static public void main(String args[])
{
  if (args == null)
    println("[main] Null args!");
  else if (args.length == 0)
    println("[main] No args!");
  else
  {
    for (String s : args)
      println("[main] > " + s);
  }
  PApplet.main("MainSketch");
}

void setup()
{
  if (args == null)
    println("[setup] Null args!");
  else if (args.length == 0)
    println("[setup] No args!");
  else
  {
    for (String s : args)
      println("[setup] > " + s);
  }
}
```

This prints "[main] No args." followed by "[setup] Null args.".

I've tried both running the app bundle (via open path-to-app arg1 arg2) and by running the executable in Contents/MacOS (via ./MainSketch arg1 arg2).

The only way to get it working was to run the sketch with path-to-bundle/Contents/PlugIns/jdk1.8.0_144.jdk/Contents/Home/jre/bin/java -cp path-to-bundle/Contents/Java -Djava.ext.dirs=path-to-bundle/Contents/Java MainSketch arg1 arg2.

I'm running High Sierra 10.13.2 and using Processing 3.3.6.
The sketch in question uses the P3D renderer.

Thank you for your time!

**Comment by gohai** [comment]
Hello @onimatrix - thanks for reporting this issue this clearly. The launchers that are part of the exported applications are unfortunately all rather complex, and outside of what I am familiar with, but I presume it would be a matter of passing [these arguments to main](https://github.com/processing/processing/blob/master/build/macosx/appbundler/native/main.m#L61) on to the `launch` method, and modifying [this block](https://github.com/processing/processing/blob/master/build/macosx/appbundler/native/main.m#L243) to include those values (to be passed to `jli_LaunchFxnPtr`).

**Comment by benfry** [comment]
Yeah, unfortunately I guess the launcher we use doesn't seem to pass the arguments in. I'd recommend using something instead of args that way, since it's unlikely that it'll get implemented upstream (most Mac apps don't support args that way).

**Comment by jeremydouglass** [comment]
FYI as an alternative, I am able to pass arguments into a sketch on macOS when running it with `processing-java`.

e.g., if the sketch is MySketch.pde

 * To use from the command line:
 *        processing-java --sketch=`pwd`/MySketch --run
 * ...or:
 *        processing-java --sketch=`pwd`/Edger --run myarg="/path/to/edge/files/"

...then check and parse the built-in `args` variable as normal.

```
  // if there are command line arguments, print them:
  println(args == null ? "null" : args);

  // load command line arguments
  argDict = new StringDict();
  if (args != null) {
    for (String arg : args) {
      String[] entry = split(arg, "=");
      if (entry.length == 1) {
        argDict.set(entry[0], "");
      }
      if (entry.length == 2) {
        argDict.set(entry[0], entry[1]);
      }
    }
  }
  
  for (String arg : argDict.keyArray()) {
    switch(arg) {
    case "myarg":
        doSomething();
      }
      break;
    }
  }
```
