### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by seewhylowgithub** [processing/processing#5528]
Dear Sir

When I click on the processing icon. It start installation and give me this error message "error getting the processing the settings folder"

After that nothing happen.
What is the problem. My PC is win10, 64bit.
What the problem?

![processing installation error](https://user-images.githubusercontent.com/9388651/41078490-ba6ab2a2-6a4f-11e8-969b-a2918b18b74f.jpg)

Thanks
Low Chong Yang

**Comment by gohai** [comment]
Hello, are you sure you have extracted the contents of the ZIP file you downloaded before executing the Processing application? I don't use Windows, but I believe ZIP files can appear similar to regular folders in the Explorer, yet it is necessary to extract it before starting Processing.

**Comment by seewhylowgithub** [comment]
Hi processing developer
I'm sure I had unzip processing before installation.Attach picture show that I can unzip it.
Any advise.Low Chong Yang


    On Thursday, 7 June 2018, 1:08:56 PM SGT, Gottfried Haider <notifications@github.com> wrote:  
 
 
Hello, are you sure you have extracted the contents of the ZIP file you downloaded before executing the Processing application? I don't use Windows, but I believe ZIP files can appear similar to regular folders in the Explorer, yet it is necessary to extract it before starting Processing.

**Comment by seewhylowgithub** [comment]
Hi processing developer
I had manage to get the processing software to install.I download again and use another brand of unzip software and it can install.

Regards.Low Chong Yang


|  | Virus-free. www.avast.com  |

**Comment by gohai** [comment]
@seewhylowgithub Great to hear, closing this issue.
