### ISSUE TITLE
FX2D strange framerate and "default" window size problem

### ISSUE THREAD

**Issue by liquid600pgm** [processing/processing#5531]
## Description

I had a project for school that I was making in Processing, today we were presenting it, and I had to use an older version of the project because of a peculiar bug that happened.

## Expected Behavior

The window should start as normal, framerate should be locked to 60fps, the resolution should be the one set in `size()`.

## Current Behavior

When I started the sketch, everything was very laggy, when I enabled its debug mode the framerate was 300-500, even though it was lagging *a ton*. It seemed like 3 fps. JAVA2D worked normally (15fps, because school computers are crap).
Apart from that, the resolution was wrong: it was supposed to be 960\*540, instead it was (probably) 800\*600 (didn't have time to measure).
I am unable to reproduce this issue on my own computer.

## Steps to Reproduce

???
I have no idea how to reproduce this. I would have to run this again on the school computer, which I don't have access to anymore.

## Your Environment

 

* Processing version: 3.3.7
* Operating System and OS version: Windows 7 (unknown version)
* Other information: FX2D renderer, [this project](https://github.com/liquid600pgm/exCircuit).
* From what the school admin has told me, Java 8u171 (or any latest update) is installed on all school computers. This might be important, as I am not bundling Java with my sketch, and I use a completely different build system from Processing's.

## Possible Causes / Solutions

This might be unsolvable by the team if this is an issue with graphics drivers or JavaFX itself.

**Comment by benfry** [comment]
Yeah, it's not something we can solve on our end… too many variables here. This is why, for instance, we've implemented the ability to embed the JRE. But most likely, you're dealing with graphics drivers, angry virus scanning software, who knows what else is installed on that machine.

**Comment by liquid600pgm** [comment]
It was probably due to the graphics drivers on that machine. Those computers are who-knows-how-many years old with Intel Core Duos and with no graphics cards. JavaFX seems to have minimal support for outdated software and hardware.

**Comment by benfry** [comment]
Oh right—if they don't have discrete graphics, performance is absolutely miserable with `FX2D`. Newer on-CPU graphics aren't quite as bad, but many of the earlier integrated graphics were so bad that it was a big reason we didn't make `FX2D` the default.
