### ISSUE TITLE
Console mouse drag can fail to select last character

### ISSUE THREAD

**Issue by chrisjj** [processing/processing#5533]
## Expected Behavior
On the last line of text in the console, drag from left end to right end selects all the line's characters.

## Current Behavior
On the last line of text in the console, drag from left end to right end selects all the line's characters but the rightmost.

![image](https://user-images.githubusercontent.com/6157073/41206929-515359ba-6d04-11e8-954f-380af30b093a.png)

## Workaround
At end, drag down one line.

![image](https://user-images.githubusercontent.com/6157073/41206936-64db9222-6d04-11e8-9c78-6089e0f8a867.png)

## Your Environment
* Processing version: 3.2.1
* Operating System and OS version: Windows 7

**Comment by benfry** [comment]
Looks like a bug inherited from Java's text area; not something we can fix.

**Comment by chrisjj** [comment]
If that were true, wouldn't you expect the editor window to show the same? It doesn't, here.
