### ISSUE TITLE
3.3.7 core.jar (false) flagged as trojan on win10

### ISSUE THREAD

**Issue by GoldenQubicle** [processing/processing#5537]
So I opened up processing this morning and it didn't boot, instead gave a warning something went seriously wrong (forgot to screengrab it). Then I recalled java needed updating on my machine so did that, but to no avail. Then I figured a reinstall might fix the issue, however, while extracting the files the following warning popped up; 

![image](https://user-images.githubusercontent.com/21037627/41497433-52714d16-7155-11e8-93ea-f47716d7734c.png)

and the defender details; 

![image](https://user-images.githubusercontent.com/21037627/41497390-b359bf10-7154-11e8-8fdd-b5b69746b06b.png)

Luckily I still have the previous version at hand, and in addition telling windows defender to restore the file works too. So there's no immediate need for a fix on my end, however, I figured reporting it nonetheless would be useful since it's an annoying issue and could potentially scare off newcomers installing Processing only to have this, what I presume is a false positive quarantine, render it unusable.

**Comment by ZachSundberg** [comment]
Windows real time protection actually stops core.jar from even extracting.

To resolve this, open Windows Defender Security Center -> Virus and Threat Protection Setting.  Turn off real time protection (temporary).  Download and extract processing.   Back in the Settings, Add and Exclusion -> Folder (your local processing folder).  Then turn real time protection back on.

**Comment by gohai** [comment]
I just submitted the file to Microsoft for review.

**Comment by BatteryDie** [comment]
You are not alone. I have similar issue on latest Windows 10 build.  I knew I was using Processing 3.3.7 (I trusted Processing) until M$ flagged it. I guess I am going add exclusion to processing.

![image](https://user-images.githubusercontent.com/13942195/41504985-90afe8fe-71cc-11e8-9d22-6e0fea2ba305.png)

**Comment by gohai** [comment]
FYI: on my pretty regular version of Windows 10, I just installed the latest round of available updates, and afterwards Processing was able to be installed without an issue. Can anyone else, who saw this earlier confirm that this resolved itself?

**Comment by Jean-no** [comment]
@gohai : I guess the problem only occurs for those who use Microsoft Security Essentials as their antivirus

**Comment by gohai** [comment]
@Jean-no Isn't this built into Windows 10 as "Microsoft Security Essentials"? Anyway, submitting `core.jar` to Microsoft came back clean.

**Comment by benfry** [comment]
Added extra checks for this during startup in Processing 3.4.
