### ISSUE TITLE
Processing-3.3.7 doesn't work on win 10. My computer has recently updated my windows and after that suddenly proessing program says 'A serious problem happend during the startup.' And I can't run the program. I seems there is no problem with my Java program. I'm in real hurry because of my project in school. I hope there is a solution with this error. 

### ISSUE THREAD

**Issue by jihoon0722** [processing/processing#5538]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by ZachSundberg** [comment]
Windows defender is flagging core.jar as a trojan.  Follow my instructions on this post:
https://github.com/processing/processing/issues/5537
