### ISSUE TITLE
When I open processing loading screen flashes then disappears and processing never opens.

### ISSUE THREAD

**Issue by Ryzon3** [processing/processing#5543]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version :3.37
* Operating System and OS version: Windows 10
* Other information:

**Comment by Jean-no** [comment]
See there : [https://github.com/processing/processing/issues/5537](https://github.com/processing/processing/issues/5537)

**Comment by Ryzon3** [comment]
I had already tried this it did not work

**Comment by Jean-no** [comment]
Do you have this message when you start ? 
![image](https://user-images.githubusercontent.com/5811393/41503516-cce6a010-71d6-11e8-88af-91c43ba17a4c.png)

**Comment by Ryzon3** [comment]
No i do not get any errors.

**Comment by julianrusso92** [comment]
I have the same problem

**Comment by liquid600pgm** [comment]
Try running Processing from your terminal (cmd on Windows, Terminal on other platforms): navigate to the Processing folder using your terminal and type:
```
On Windows:
> processing.exe
On Linux/Mac:
$ ./processing
```
Then tell what was written in stdout (the console) after running this command and Processing crashed.

**Comment by Ryzon3** [comment]
I redownloaded processing just today and it works.

**Comment by benfry** [comment]
Closing as resolved.
