### ISSUE TITLE
weird Stroke behavior of Boxes with compared huge Y values

### ISSUE THREAD

**Issue by Hendiadyoin1** [processing/processing#5552]
## Description

If U use for example a Box with the values 1,10000000,1 the side outlines are scaöed way to big

## Steps to Reproduce
CODE:
`
import peasy.*;

PeasyCam cam;
int[][] grid;
int scl = 5;
void setup() {
  size(600, 600, P3D);
  cam = new PeasyCam(this, 500);
  surface.setAlwaysOnTop(true);
  //frameRate(2);

  lights();

  grid = new int[width/scl][height/scl];
  grid[width/scl/2][height/scl/2] = 1000000;
  //strokeWeight(.1);
}

void update() {
  int[][] ngrid = new int[width/scl][height/scl];
  for (int x = 0; x<width/scl; x++) {
    for (int y = 0; y<height/scl; y++) {
      if (grid[x][y]<4) {
        ngrid[x][y] = grid[x][y];
      }
    }
  }

  for (int x = 0; x<width/scl; x++) {
    for (int y = 0; y<height/scl; y++) {
      if (grid[x][y]>=4) {
        ngrid[x][y]+=grid[x][y]-4;
        if (x>0)
          ngrid[x-1][y]+=1;
        if (x<width/scl-1)
          ngrid[x+1][y]+=1;
        if (y>0)
          ngrid[x][y-1]+=1;
        if (y<height/scl-1)
          ngrid[x][y+1]+=1;
      }
    }
  }
  grid = ngrid;
}

void render() {
  for (int x = 0; x<width/scl; x+=1) {
    for (int y = 0; y<height/scl; y+=1) {
      int X = x*scl;
      int Y = y*scl;
      //int i = x + y*width;
      color col = color(0);
      switch(grid[x][y]) {
      case 0:
        col = color(50);
        break;
      case 1:
        col = color(200, 0, 0);
        break;
      case 2:
        col = color(0, 200, 0);
        break;
      case 3:
        col = color(0, 0, 200);
        break;
      default:
        col = color(200);
      }
      fill(col);
      pushMatrix();
      translate(-width/2, -height/2);
      translate(X, Y);
      box(scl, scl, grid[x][y]*scl);
      popMatrix();
    }
  }
}

void draw() {
  println(frameRate);
  //frameRate(2);
  background(0);
  render();
  for (int i = 0; i<1; i++)
    update();
  cam.reset(0);
  cam.rotateZ(radians(3*frameCount));
  cam.rotateX(-radians(45));
}
`

## Your Environment

 

* Processing version:
3.3.7
* Operating System and OS version:
Windows
* Other information:
with huge Number:
![image](https://user-images.githubusercontent.com/37629766/41674179-8bad52e2-74bf-11e8-8b12-752894d9785f.png)
with not as huge Number:
![image](https://user-images.githubusercontent.com/37629766/41674208-a673a040-74bf-11e8-951a-b591f1b6bd87.png)

## Possible Causes / Solutions

let the  box - function take the ratio of the Box in consideration

**Comment by Hendiadyoin1** [comment]
Sorry for the bad cod format (I don't know how to add it proparly to GitHub...)

**Comment by Hendiadyoin1** [comment]
View from the Top:
![image](https://user-images.githubusercontent.com/37629766/41674820-4b995b5e-74c1-11e8-8c33-f088f09a97ac.png)

**Comment by liquid600pgm** [comment]
Format your code like this:
    ```processing
    // your code here
    ```

**Comment by benfry** [comment]
This is too weird a contrived example for us to pursue it… A y value of 10 million is going to be problematic because of what numbers can be used and manipulated with a 32-bit `float`.
