### ISSUE TITLE
Some Examples from the Contribution Manager fail to download

### ISSUE THREAD

**Issue by Darkboy17** [processing/processing#5554]
## Description

I can't seem to download Examples  from the Author Daniel Shiffman and a few others as well.
Some works some don't.
## Expected Behavior

The first time I used Processing, all seems to work fine.
## Current Behavior

When I click "Install" I get the message "Could not find a examples in the downloaded file"
## Steps to Reproduce

1. Goto the 'Tools' menu. 
2. Then  click 'Add Tool' .
3. Click the 'Examples' Tab.
4. Select 'The Nature of Code'.
5. And then click 'Install'

## Your Environment

 

* Processing version: 3.3.7
* Operating System and OS version: Windows 10 Pro 64-Bit
* Other information:

**Comment by benfry** [comment]
What happens when you try to download them?

**Comment by Darkboy17** [comment]
When I try to download them,I get the following error as shown in the
screenshot.

In the screenshot below, I'm actually trying to download the second example
"Learn Processing 2nd Edition"  from the Contribution Manager.

[image: processing_err.png]
​

**Comment by benfry** [comment]
That screenshot didn't come through; you probably need to visit the Github site and post it there rather than responding to the email.

**Comment by benfry** [comment]
Thanks for that. Turns out the problem was that some of the URLs redirect to https:// locations, which the code wasn't handling automatically (because it's a potential security issue).

That's now fixed for the next release (3.3.8 or 3.4).

**Comment by Darkboy17** [comment]
Thanks.

**Comment by benfry** [comment]
Don't know; it's dependent on when I have enough free time to finish things up and post. 

In the meantime, the library/example/mode/tool authors should be updating their entries to use the real download URLs, since this is happening when their sites are automatically redirecting `http` to `https` connections.

**Comment by francorfs** [comment]
my program is displaying a "setupZoom (); // in mouse tab"

**Comment by SmantikVJ** [comment]
I am running Processing 3.5.3 in an ARM 64 bits Ubuntu 18.04 Jetson Nano. I had to use Zulu JDK (from here: https://www.azul.com/downloads/zulu-embedded/) to be able to open and run Processing sketches. Now, when I go to "Tools" and try to download "Hardware I/O" library or another, it says "Error during download and install of (name of the library)".
 Could somebody help me, please?

**Comment by benfry** [comment]
(Removing unrelated comment and locking since this was resolved a year ago.)
