### ISSUE TITLE
Find in Reference - draw() reference missing

### ISSUE THREAD

**Issue by jaewhyun** [processing/processing#5555]
## Description
draw() doesn't come up for Find in Reference. 

## Expected Behavior
I should expect to see file:///Applications/Processing.app/Contents/Java/modes/java/reference/draw_.html in my browser when searching for the _draw_ reference. 

## Current Behavior
It says "No available reference for "draw"."

## Steps to Reproduce

1. Type in draw(); into the text editor
2. Then highlight _draw_ and click _Help > Find in Reference_

## Your Environment

 

* Processing version: 3.3.7
* Operating System and OS version: macOS High Sierra

**Comment by gohai** [comment]
Thank you for your report @jaewhyun!

**Comment by benfry** [comment]
Thanks; looks like it's a larger issue: https://github.com/processing/processing/issues/5562 so I'm going to merge things into that issue.
