### ISSUE TITLE
Debugging : Question

### ISSUE THREAD

**Issue by christianbender** [processing/processing#5559]
Hello,

how can I debug the code of a certain file?  Can I put ```System.out.println(...)``` into the code?

At the moment I keep on #5317 . But I don't know on wich place I should look for. 

Greetings

Christian

**Comment by StanLepunK** [comment]
Hello, the best place for any question about Processing code, is here https://discourse.processing.org/

**Comment by gohai** [comment]
Yes, you'd put in `System.out.println()` in the code and compile and run the resulting Processing app. Your messages show up mixed-in with the regular ones in the Console.

**Comment by christianbender** [comment]
@gohai  Thanks for help!
