### ISSUE TITLE
Broken links https://processing.org/download/ 

### ISSUE THREAD

**Issue by token0** [processing/processing#5569]
## Description

Links for 2.2.1 are broken

## Current Behavior

404 Not Found
The requested URL /processing-2.2.1-windows64.zip was not found on this server.
The requested URL /processing-2.2.1-windows32.zip was not found on this server.

## Steps to Reproduce

1. https://processing.org/download/ 
2. Press download 2.2.1

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by gohai** [comment]
I just tried and those links worked for me.
