### ISSUE TITLE
Background task outputs error while writing sketch

### ISSUE THREAD

**Issue by ThierryKamber** [processing/processing#5570]
## Description
First of all, I think this is a minor issue or maybe just a possible improvement rather than an issue.
It doesn't break anything, but it might be confusing to some new users.
I'm not sure what the background task exactly does, so feel free to edit the title to something more meaningful.

The issue happens when first adding "void draw()" and then adding "void setup()" above it. I assume this also happens when declaring another function above "void draw()".

Note: I am aware that the example used below is an incomplete sketch.

## Expected Behavior
I've expected Processing to not display that error as I was just typing in my sketch and not running anything yet.

## Current Behavior
Instead Processing outputs the error shown below.

## Steps to Reproduce
1. Create a sketch with 
```
void draw()
{
  
}
```
as content.
2. Add
```
void setup()
{
```
at the beginning of the sketch.
3. An error similar to the following will be shown:
```
Status ERROR: org.eclipse.jdt.core code=4 Exception occurred during compilation unit conversion:
----------------------------------- SOURCE BEGIN -------------------------------------
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;
import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_180705b extends PApplet {
void setup()
{void draw()
{
  
}

}

----------------------------------- SOURCE END ------------------------------------- java.lang.IllegalArgumentException
```

## Your Environment
* Processing version: 3.3.6
* Operating System and OS version: Windows 7 64Bit
* Other information: -

## Possible Causes / Solutions
My suggestion would be to not display errors like these (except when in debug-mode for example) as they don't really cause any issues for the user (as far as I'm aware) and might just confuse newer users.

**Comment by christianbender** [comment]
@ThierryKamber 
Have you only write 
```processing
void setup()
{
```
or have you write the full body of the function? such as  
```processing
void setup()
{

}
```

**Comment by ThierryKamber** [comment]
It only happens to me when the "{" is next to "void".

![grafik](https://user-images.githubusercontent.com/8191379/42425090-e5ba243e-8317-11e8-960a-157e944043fc.png)


If I make sure there's a newline before typing, it works expected.

![grafik](https://user-images.githubusercontent.com/8191379/42425103-274ab99a-8318-11e8-977f-dee34d2dd306.png)
