### ISSUE TITLE
Error installing OpenKinect for Processing

### ISSUE THREAD

**Issue by bitengines** [processing/processing#5571]
Error when installing "Open Kinect for Processing" using the contribution Manager

 

## Current Behavior

Instalation files and shows error message "Could not find a library in the downloaded file."

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version: v3.3.7
* Operating System and OS version: Win7
* Other information:

**Comment by gohai** [comment]
CC @prisonerjohn @shiffman

**Comment by benfry** [comment]
That means that the library is not packaged properly; please contact the Open Kinect project.
