### ISSUE TITLE
loadStrings() omits last empty line

### ISSUE THREAD

**Issue by Spongman** [processing/processing#5572]
## Description
`loadStrings()` returns an array of all the lines in a file, _except_ if the last line is empty, in which case it is omitted.

## Expected Behavior
`loadStrings()` should return all lines in the file, empty or otherwise.

## Steps to Reproduce
String[] strings;

void setup() {
  strings = loadStrings("file.txt");
  println(strings.length);
}

file.txt contains 4 bytes: \r\n\r\n

println prints 1

* Processing version: 3.3.6
* Operating System and OS version: windows 10

**Comment by christianbender** [comment]
@Spongman 
I tested your problem on my machine. But the file will be correct read. Even the empty lines!

```processing
void setup() {
 String lines[] = loadStrings("data.txt");
 for (String line : lines) {
   println(line);
 }
 println(lines.length);
}
```

Test file contains:  
```text
line 1

line 3
line 4
line 5

line 7

```

Output: 

```
line 1

line 3
line 4
line 5

line 7
7

```

**Comment by christianbender** [comment]
No, it was 7 lines. The```7``` at the end it the output of the program.

**Comment by Spongman** [comment]
Ok, so your text file is not relevant to this issue. The bug only occurs when the last line of the file is empty. Sorry, I thought I had made that clear.

**Comment by christianbender** [comment]
@Spongman 
I added two empty lines at the end of the file. 
![screenshot](https://user-images.githubusercontent.com/23243382/42464220-a54e2d82-83a8-11e8-9fd0-c5bb3ce2297a.png)
Both lines will be readed. Sorry I misunderstood you. But I can't confirm your problem. The ```loadString(...)``` function works good.

**Comment by Spongman** [comment]
can you reproduce with a text file containing four bytes: \r\n\r\n ?

**Comment by jeremydouglass** [comment]
Cannot reproduce this problem in Processing 3.3.7 on macOS 10.12.1, when running the example sketch against the described four-byte file '\r\n\r\n' (that is, <CR><CR>).

Processing prints: "2"
