### ISSUE TITLE
Feature: Custom code macros/snippets placed throughout code within PDE

### ISSUE THREAD

**Issue by ffd8** [processing/processing#5578]
Had a random idea last night while copy+pasting about 4 snippets of code from a previous sketch to another one, essentially importing a certain library, declaring the instance variables, initializing in the setup, updating within the draw and a custom function that extended it. I do this alllll the time– "let's make it audio reactive.." = find previous sketch, copy + paste snippets.. bam, up and running. 

What if there was a technique within the PDE for one to store macros that could insert a chunk of code at the following places:

- global (above setup)
- setup (top / bottom, incase order of events is important)
- draw (top / bottom)
- keyPressed, mousePressed, etc.. all listeners
- very bottom (if adding custom functions)

It seems like it would be easy for the macro to keep track of all of these places when scanning for the function and parsing the first and last { }'s... if one suggested adding a snippet within the keyPressed, but it hadn't been created yet, then it would add it with the snippet, otherwise, respect what's already there and add it. 

Libraries could include their own for adding that functionality to any sketch.. in a later phase, they could be stored in a folder where people could swap them and activate them with a searchable dropdown.

This would be amazingly efficient when a basic sketch on the train, suddenly should use a peasycam, or favorite controlp5 sliders addon, or drag+drop support, or videoExport, or or or... 

I've already made many such snippets for my courses, so I end up referencing that teaching material locally for fast copy + paste.. but it would increase our efficiency by at least 500%! ;)

+ did a quick search and found a [thread on the forum discussing code-snippets](https://forum.processing.org/two/discussion/26861/code-snippets) (although multiple insert points would be necessary) and thought it made sense to add as a feature request to the code repo. 

Hope you can consider such a feature and curious to hear your thoughts on it.

**Comment by liquid600pgm** [comment]
This should be possible with a custom Tool.

**Comment by benfry** [comment]
Yeah, this is exactly the kind of thing the Tools menu is for. It's unlikely to be a feature we'd put into the PDE itself, but something that power users might want to use.
