### ISSUE TITLE
mouseMoved() and mouseDragged() called more than once between draw calls

### ISSUE THREAD

**Issue by wlycdgrfromflatiron** [processing/processing#5584]
ENV:
Processing 3, v 3.3.7
Windows 10 Home 64-bit, v 1803, build 17134.112
Intel Pentium N3710, Intel HD Graphics 405

Did a little test to explore order of invocation for mouse event handlers:

```
int frame;

void setup(){
  size(100, 100);
  
  frame = 0;
}

void draw(){
  frame += 1;
  
  println("draw " + frame);
}

void mouseMoved(){
  println("mouseMoved " + frame);
}

void mouseDragged(){
  println("mouseDragged " + frame);
}
```

EXPECTED:
mouseMoved() and mouseDragged() called 0 or 1 times after the corresponding draw calls and before the next one, as per https://processing.org/tutorials/interactivity/
this is the way that mousePressed() and mouseReleased() are behaving, as expected.

OBSERVED:
mouseMoved() and mouseDragged() getting called up to 3 times between consecutive draw calls. see image for sample console output demonstrating the issue. 

![image](https://user-images.githubusercontent.com/29666909/43039498-94dcf714-8cfc-11e8-951a-79666b52ce42.png)

**Comment by benfry** [comment]
This is a feature, not a bug. If there are three mouse events between frames, you'll get all three events. 

Otherwise even simple things like a drawing/sketching program would have huge gaps in the lines being drawn.
