### ISSUE TITLE
naming a sketch.

### ISSUE THREAD

**Issue by viv1kk** [processing/processing#5585]
In Processing 3, does naming of a sketch affects the code inside of it. like, using a keyword as name?? actually, I created a sketch and named it  "Boolean" and It does not execute but after changing the name It runs fine.

**Comment by gohai** [comment]
The name of the sketch is used as the class name the sketch's content is being wrapped in automagically.

**Comment by hkiel** [comment]
Maybe you could automagically prepend some string (like an underscore) to allow any sketch name!?
At least it is not obvious that tere exists a restriction on the sketch name.

**Comment by jeremydouglass** [comment]
Currently there is an invalid sketch name error triggered by e.g. beginning a sketch name with a number, or using an invalid character. Currently the invalid name renamer prepends "sketch_" to those names.

It might be a nice feature to expand the sketch name validator to check against Java and Processing keywords and builtins that could be shadowed -- although I'm not sure that they should be automatically disallowed. For example, if you really want to name your sketch Table, maybe you should be able to. One option would be to just print a warning when the sketch is saved. Another would be to automatically prepend "sketch_" and warn on first save, but then allow the user to rename manually if they really want to and not complain on every re-save.

**Comment by benfry** [comment]
Yes, that's covered here: https://github.com/processing/processing/issues/196
