### ISSUE TITLE
Python mode installer gives error "Could not find a mode in the downloaded file."

### ISSUE THREAD

**Issue by Nking92** [processing/processing#5587]
## Description

When I try to install the Python mode within Processing, I get the error "Could not find a mode in the downloaded file."

## Expected Behavior

The installer should install Python mode without errors

## Current Behavior

The installer gives an obscure error message: "Could not find a mode in the downloaded file."

## Steps to Reproduce

1. Open Processing
2. Click "Add mode..."
3. Select Python mode and click Install

## Your Environment

 

* Processing version: 3.3.7-windows64
* Operating System and OS version: Windows 10
* Other information: Downloaded and freshly installed Processing today (July 24, 2018)

## Possible Causes / Solutions

I traced the network activity from Processing and I think I know the problem. It's a server issue that will hopefully be an easy fix.
The installer sends an HTTP request to http://py.processing.org/3/PythonMode.zip.
The HTTP response is HTTP 301 Moved Permanently with "Location:  https://py.processing.org3/PythonMode.zip" in the Location header. There's a slash missing between org and 3 - it should be https://py.processing.org/3/PythonMode.zip
Hope that helps!

**Comment by benfry** [comment]
Thanks, just fixed last night: https://github.com/processing/processing/issues/5554

**Comment by raj-raghuwanshi** [comment]
@benfry I'm still getting this error (Mac OS). I'm running the latest version of Processing. Is there a way to manually download the mode into Processing?

**Comment by benfry** [comment]
Download the .zip file, uncompress it, drag the `PythonMode` folder it creates into `modes` folder of your sketchbook.
