### ISSUE TITLE
Can Processing for MacOS let go of the Documents folder, please!

### ISSUE THREAD

**Issue by reppolice** [processing/processing#5588]
Installing the latest Processing on OSX 10.13 creates an ever-expanding subdirectory under "Documents". Perhaps this was the Mac way before iCloud, but with the new cloud-sync situation it triggered "Your iCloud is full" nagging messages. Hopefully it can relocate off cloud?

Thanks!

**Comment by gohai** [comment]
You can change the sketchbook location in the Processing's Preferences.
