### ISSUE TITLE
Processing won't open

### ISSUE THREAD

**Issue by aky91** [processing/processing#5589]
## Description

When I open processing.exe, the logo window of processing shows up for about 2-3 seconds then it simply closes. Nothing happens after that. Even Task Manager has no process related to it.
I have been using processing for 3 months and it had worked great. But suddenly one day onwards it is showing this behaviour.

## Expected Behavior

Whenever we open processing.exe, after displaying the logo window, the editor should open up. 

## Current Behavior

But in my case, it just closes after the logo window.

## Steps to Reproduce

I have tried the following steps:
1. Delete processing, and download a new one
2. Download the latest version of java
3. Run processing as admin

But none of these makes things better.

## Your Environment

 

* Processing version: 3.3.7
* Operating System and OS version: Windows 10 Home 
* Other information: 64bit

**Comment by benfry** [comment]
Please use the forum for troubleshooting questions.
