### ISSUE TITLE
Could not find a mode in the downloaded file.

### ISSUE THREAD

**Issue by alexquacksalot** [processing/processing#5591]
## Description
Hi, I’m new to this so I apologize if I’ve made some really simple mistake. So I downloaded the 64-bit latest version and I wanted to use the Python mode to code but every time I try to install it, it starts the download but then seconds later it gives me the error, “Could not find a mode in the downloaded file.” I also tried Processing 3.3.6 and it also didn't work. What am I doing wrong? 

## Expected Behavior
Successfully downloading the Python mode

## Current Behavior
Could not find a mode in the downloaded file error appearing 

## Steps to Reproduce

I'm not sure what to put here.
1. Try to install python mode

## Your Environment

 

* Processing version: 3.3.7
* Operating System and OS version: Windows 10 64-bit
* Other information:

**Comment by benfry** [comment]
Sorry about that; it's an issue that's been fixed but I haven't had time to post a new release yet.

See the end of [this thread](https://github.com/processing/processing/issues/5587) for how to work around it in the meantime.

**Comment by alexquacksalot** [comment]
thank you
