### ISSUE TITLE
Cannot install Python Mode for Processing 3.4 on ubuntu 17.10 x64

### ISSUE THREAD

**Issue by camiKD** [processing/processing#5592]
* Processing version: 3.4
* Operating System and OS version: ubuntu 17.10, x64

Hi, having the same problem with not being able to install PythonMode from the contribution manager. I just get the error msg: "Error during download and install of Python Mode for Processing 3."

 I tried to download the file from https://py.processing.org/3/PythonMode.zip, unzip it, and move it to the modes folder giving the result: ~/processing-3.4/modes/PythonMode
Then I tried also unzipping the src file in the PythonMode directory. This did not help either. 
Is it a directory IN the PythonMode directory I should place in ~/processing-3.4/modes ?

I also tried downloading processing 3.7 and doing the same thing as described above.

I have both python2.7 and 3.6 on my system. In the cmd line when writing 'Python -V' it says 'Python 2.7.14'

any ideas on what can solve my problem?

**Comment by camiKD** [comment]
// Should have been placed on processing.py

**Comment by camiKD** [comment]
should have been placed on processing.py: https://github.com/jdf/processing.py/issues/300

**Comment by benfry** [comment]
(Closing since it belongs in the other repo)
