### ISSUE TITLE
Movie Playback fail (video not playing)

### ISSUE THREAD

**Issue by Diex** [processing/processing#5595]
Trying to play a .mp4 movie it simply do not start.

after a whole evening of trial/error I realized the problem was I have no connected speakers/headphones to my computer, so there was no audio output available.

this leads you to this situation:

you try examples/video/movie/loop.pde example (runs fine)
you try your own movie. it does not (even using the same encoder/format/dimensions/framerate.)

after trying many different encoders, formats, containers, it was not until I tryed a videoprofiler I realized the problem maybe have something to do with audio stream (after discovering that **transit.mov has no audio channels**).

I thing this is an issue. I can not say it is a Processing video library issue. but for sure is a problem very strange and difficult to solve.
I couldn't find any post/issue related so it was a very very frustrating evening. but I solved it in the end.

so, I am letting this here so maybe it could help someone in the future. (or maybe p5 devs could find a workarround... i.e. throwing an exception/warning will be great !!!)

thank you !

processing: any versions from 2.0.1 to 3.4
os: windows 7 64 bits
audio harware: on board msi

**Comment by gohai** [comment]
Hi @Diex - this is an issue for https://github.com/processing/processing-video .. perhaps you could give the test-version (I believe labeled "2.0") available for download there under "Releases" a try. This is using a later GStreamer version and might be nicer to your video file.
