### ISSUE TITLE
Movie.isPlaying()

### ISSUE THREAD

**Issue by kfrajer** [processing/processing#5596]
Possible duplicate: https://github.com/processing/processing/issues/1327 also a PR already exist: https://github.com/processing/processing-video/pull/29

## Description
Feature request: Add function `isPlaying()` to the movie library to detect when a movie ends playing

## Current Behavior
No method available atm. Users fall back to `time()` and `duration()` methods to check if the current movie is still playing. 

## Steps to Reproduce

Currently this a code to play three movies one after the other, looping all three. Adding this feature will reduce complexity. Next demo based on GoToLoop's demonstration:

```java
//===========================================================================
// IMPORTS:
import processing.video.*;

//===========================================================================
// FINAL FIELDS:
final int N=3;

//===========================================================================
// GLOBAL VARIABLES:

Movie[] mov;
int cidx=0;

//===========================================================================
// PROCESSING DEFAULT FUNCTIONS:

void settings() {
  size(400, 600);
}

void setup() {
  mov = new Movie[N];
  mov[0]=new Movie(this, "processing-movie.mp4") {
    @Override public boolean hasBufferSink() {
      return playing;
    }
  };
  mov[1]=new Movie(this, "transit.mov") {
    @Override public boolean hasBufferSink() {
      return playing;
    }
  };
  mov[2]=new Movie(this, "video720x480.mp4") {
    @Override public boolean hasBufferSink() {
      return playing;
    }
  };

  mov[cidx].play();  //Start playing first movie
}

void movieEvent(Movie m) {
  m.read();
}

void draw() {
  background(0);
  image(mov[cidx], 0, 0, width, height);
  
  //B&W info banner
  fill(255);
  text("Current "+cidx, 10, 30);
  fill(0);
  text("Current "+cidx, 10, 50);

  checkCurrentMovieStatus();
}

//===========================================================================
// OTHER FUNCTIONS:

void checkCurrentMovieStatus() {

  if (mov[cidx].hasBufferSink()==false) {

    mov[cidx].stop();  //Rewind 
    cidx=(cidx+1)%N;    
    mov[cidx].play();
  }
}
```

## Your Environment
P3.3.7 Win10 x64

## Possible Causes / Solutions
Discussion in [this post](https://discourse.processing.org/t/help-with-text-and-video/2104/10) suggest to expose the `playing` field via `isPlaying()` method.

**Comment by gohai** [comment]
Closing, since this is a case for processing-video.

**Comment by AlvaroHermida** [comment]
> Closing, since this is a case for processing-video.

Unfortunately, [processing/processing-video](https://github.com/processing/processing-video/pulls) is a dead end, where the useful contributions are just ignored for years and years.

As @kfrajer says, the solution for this issue is waiting there [(https://github.com/processing/processing-video/pull/29)](https://github.com/processing/processing-video/pull/29), but it is forgotten in the dust from more than three years ago. It is a good, simple and safe patch:
```
 public boolean isPlaying(){
    return playing;
  }

  public boolean isPaused(){
    return paused;
  }

  public boolean isRepeating(){
    return repeat;
  }
```

¿Which door should we knock to unfreeze that repository?

**Comment by AlvaroHermida** [comment]
> It is a good, simple and safe patch

And, over all, it is a **useful** patch, **necessary to simplify the educational use of Processing**. Although it is possible to use the `movie.time() >= movie.duration()` workaround, it fails when the movie is just paused. The alternate boolean expression `movie.playbin.isPlaying()` works fine, but it confuses my students and forces us all to waste time teaching and learning and then debugging and keeping track of another unnecesary and counterintuitive exception, while the Minim-like `sound.isPlaying()` is a good and previously learnt interface. 

The fact that, someday in the future, a shiny fully-rewritten library will be published, is no reason to reject the patch that today solves the current needs (where "today" and "current" mean "2015").

**Comment by einraum-design** [comment]
I'm glad my pull request attracts attention again. As a workaround I usually provide my students an extended Movie class to provide the isPlaying() ect. helper functions. I hope someday it will not be necessary anymore ...
