### ISSUE TITLE
Adding subfolder support

### ISSUE THREAD

**Issue by Pomax** [processing/processing#5598]
Processing currently only allows a project layout with all .pde files in the same directory, which becomes rather unwieldy for larger projects, especially ones intended to be shared. It would be very helpful if processing added subfolder support so that files can be organised in a way that makes maintenance and sharing (parts of) the code a nicer experience.

And it should probably not follow the java package convention with namespaces and imports and all that silliness: just have the aggregation step (which currently just concats all file content as a single class file) run through the dir tree instead of just the working dir and concat all `.pde` files in the tree, irrespective of which dir it found them in; if someone puts a .pde file in the "data" directory, for instance, then that should be fine... It'd be a questionable place to put it, of course, but no dir needs special treatment, which makes this a really powerful feature to add, at very little dev time required.

**Comment by gohai** [comment]
I am pretty sure the decision to have all code files in the same folder was a conscious one. You have to keep in mind that the whole PDE concept was built around the idea of it being a "sketchbook" - not a fully built-out developing environment à la Visual Studio.

If your projects are complex enough to warrant a bigger "hammer": you might want to try using the Processing core library with the Eclipse IDE, as a couple of folks do.

**Comment by Pomax** [comment]
That... is not a reason to close this? Yes, it was a conscious choice at the time, but it's an easy choice to revisit now that Processing has been around for over a decade and a half. Please reopen this so that this can be discussed further.

**Comment by benfry** [comment]
Larger projects should be done with an actual IDE. That's always been the intent, and it's important to keep the PDE simple.
