### ISSUE TITLE
Add a small section to the README to explain how to build the src?

### ISSUE THREAD

**Issue by Pomax** [processing/processing#5599]
I'd like to help implement a feature for Processing (and possibly more than one) so I can file a PR rather than having you spend time on doing the work, but I can't find instructions for the steps between "cloning the repo" and "and now you have a freshly compiled, custom processing executable". Could a small section be added to the README.md that explains how to run the compilation process?

**Comment by gohai** [comment]
@Pomax Under **Please Help**, the Readme contains a visible link to [this wiki page](https://github.com/processing/processing/wiki/Build-Instructions) which has all the steps in detail.

**Comment by Pomax** [comment]
I was apparently blind. Thanks.
