### ISSUE TITLE
“Could not open the URL” message when using Find in Reference on Windows 10

### ISSUE THREAD

**Issue by PieVieRo** [processing/processing#5600]
## Description
I can't search reference of a function directly from an editor. Instead, it gives me an error saying "Could not open the URL".
![error](https://user-images.githubusercontent.com/29150618/43395651-1103aa0a-93ff-11e8-8e38-2b72e43448ae.png)

## Expected Behavior
Open functions reference.

## Current Behavior
It gives me an error.

## Steps to Reproduce
1. Download Processing
2. Unpack it
3. Write a function
4. Right-click it
5. Choose "Find in Reference"

## Your Environment
* Processing version: Processing 3.4
* Operating System and OS version: Windows 10 x64 version 1803

## Possible Causes / Solutions
I don't know.

**Comment by gohai** [comment]
@RedstonekPL Is the file present when you look for it on your hardisk under the displayed path? If so, does it open when you double-click?

**Comment by RedstonekPL** [comment]
@gohai yes, it does open

**Comment by Rajeshwari0826** [comment]
I want to work on it can I get the access

**Comment by Shahmaz0** [comment]
if you are using the proxy server to connect to internet , then check that your editor is configured
these type of issues comes due to internet connnectivity I thought so.
I hope this helps.
