### ISSUE TITLE
Processing cannot run under OpenJDK 11

### ISSUE THREAD

**Issue by hbs** [processing/processing#5602]
The way PApplet extracts the Java Version number expects it to include a dot, but recent OpenJDK (and Oracle JDK) releases changed the format of the java.version and java.specification.version strings which no longer include dots.

JDK 11 uses '11' instead of '1.11' for example

**Comment by benfry** [comment]
Yep: https://github.com/processing/processing/wiki/Supported-Platforms#java-versions

**Comment by neilcsmith-net** [comment]
@benfry given that public updates of Oracle Java 8 end in 4 months, and there will be no more free Oracle JDK's after that, wouldn't relaxing warnings and restrictions in source around OpenJDK 8 and above actually be a good move to allow people to test and report issues?  Or just switch wholesale to OpenJDK 8?
