### ISSUE TITLE
Multible keypress does not work 

### ISSUE THREAD

**Issue by findux** [processing/processing#5603]
## Description
I needed to know 8 keys  are holding or not in same time . So I wrote basic keypressed and keyreleased events with an array with 8 boolean items.
I expected to do when pressed 8 of them, keypressed must run each keys, and I want to change each boolean items of array to "true" value. But it is not.
for example , I pressed 'a' , 's' ,'d' ,'f' keys then "keypressed" function emited, so far so good, when press the letter 'g' "keypressed" function it is not working. I observe for the letter 'h'  same behaviour. but letter 'j' and 'k' works. I be able to press only 6 keys at the and of the process.
it does not work even though it says "every keypress moment running" in the guidelines.
  it does not work multiple key press 8 keys same time, even though it says "every keypress moment running" in the guidelines.

## Expected Behavior
running 'keypressed()' event every key pressed

## Current Behavior
it work only 6 six of keys.

letter 'a'  key pressed -> keyPressed() emitted.
letter 's'  key pressed -> keyPressed() emitted.
letter 'd'  key pressed -> keyPressed() emitted.
letter 'f'  key pressed -> keyPressed() emitted.
letter 'j'  key pressed -> keyPressed() emitted.
letter 'k'  key pressed -> keyPressed() emitted.
letter 'g'  key pressed -> keyPressed() not emitted.
letter 'h'  key pressed -> keyPressed() not emitted.

## Your Environment

 

* Processing version: 3.4 (java)
* Operating System and OS version: Win 10 
* Other information: tested normal processing window and  processing P3D

**Comment by StanLepunK** [comment]
I don't know if problem it's a bug or not, but for the multikey is better to work like that.
Are you asking on the forum ?
https://discourse.processing.org/

````
import java.awt.event.KeyEvent;
boolean[] keys = new boolean[526];

void setup() {
  size(200,200); // don't work
}

void draw() {
}

boolean checkKey(int k) {
  if (keys.length >= k) {
    return keys[k]; 
  } else {
    return false;
  }
}

void keyPressed() {
  println(frameCount);
  keys[keyCode] = true;

  if(checkKey(157)) {
    println("CMD");
    if(key == 'a') println("A");
  }
  
  if(checkKey(157) && checkKey(SHIFT)) {
    println("CMD + SHIFT");
    if(key == 'a') println("A");
    if(checkKey(KeyEvent.VK_A)) println("A");
  }
}

void keyReleased() { 
  for(int i = 0 ; i < keys.length ; i++) {
    keys[i] = false ;
  }
}
````

**Comment by findux** [comment]
I know this approach. also I wrote same code . I am not talking about that .  You will see if you print 'key'  instead of 'frame count' in keyPressed(). Hold the keys 'a,s,d,f' as pressed then press 'g' it is not work. Also, I release that, when you hold 'a,s,d,f,g' as pressed , "keypressed" does not work for other keys. But for only 'g' working.

**Comment by benfry** [comment]
Any behavior like this is coming from beneath Processing, so unfortunately there's not much we can do. 

You may get different results by switching between P2D/P3D, FX2D, and the default renderer because the renderer determines how events interact with the OS. You'll probably also get different results when using Mac/Windows/Linux.

**Comment by benfry** [comment]
@JakubValtar please confirm just in case this is a new interaction from the improved key press handling you implemented…

**Comment by JakubValtar** [comment]
This is a limitation of your keyboard, unless you have a high-end gaming keyboard with [n-key rollover](https://en.wikipedia.org/wiki/Rollover_(key)).

Test your keyboard rollover [here](http://gadzikowski.com/nkeyrollover.html) and let us know if it is different than in Processing. You will find that some keys work together well, but others not. Try to find a combination which gives you a high number of keys and stick to it. For example, my keyboard can't do `ASDFG`, but `ASDFUIOP` works fine.

**Comment by findux** [comment]
I am using laptop , also using usb keyboard instead of built in keyboard. Laptop own keyboard working as expected. I could not realise that until now. thank you problem solved .
