### ISSUE TITLE
'118:java not found' still persists.

### ISSUE THREAD

**Issue by Socrates-at-goamazing** [processing/processing#5609]
Catch 22: The video library will not run in the 64 bit version of Processing, either in Windows or Ubuntu, where I am intending to run it.
The 64-bit version installs and runs very well in Ubuntu, but will not run video capture!
The 32-bit version produces the 'Java not found' error at line 118 of the processing launch script.
I have wasted half a day trying to mix and match between the two versions, with no success.
Transferring the 64 bit java/bin to replace the 32 bit one runs fine - but launches a 64 bit environment in which video will not run!
I suspect that installing a 32 bit java runtime might work the trick, but the launcher claims that a more appropriate java in contained in the package!
I see that a year ago this same problem arose, but the notes were closed before a solution was offered.
Cheers, John

**Comment by benfry** [comment]
Please report problems with the video library to the video library project: https://github.com/processing/processing-video Thanks!
