### ISSUE TITLE
Version check can fail when Processing is used as a library

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [processing/processing#5610]
## Description

I have imported Processing as a library as described in the [official tutorial](https://processing.org/tutorials/eclipse/). The JVM I used was Java RE 9, but I had 1.8 and 10.0 installed as well. I created a PApplet extending class in the default package, referenced its name, threw in some test code (`size`, `background `etc.) into `settings`, `setup `and `draw`, and run it. It gave me the error described below, but after looking into the respective source code, I found out that there is a use of substring in line 121 of the PApplet class, which is out of bounds because the version number of the JRE has only one character (9) and not 2+ characters (10.0, 1.8 etc.). I hope this gets fixed soon, as it seems to me that it is a trivial bug and not related to my environment.

## Expected Behavior
Normal start of Processing sketch.

## Current Behavior
An error pops up: "A Java Exception has occurred." in dialog window entitled "Java Virtual Machine Launcher". After closing the dialog window, the console showed the following error message:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at processing.core.PApplet.<clinit>(PApplet.java:122)
```

I found out that the error actually lies one line above what the message says, probably because my processing version is running one revision behind.

## Steps to Reproduce
1. Install Eclipse, Processing and the Java Runtime Environment 9
2. Import Processing as described in the tutorial (see above)
3. Create Eclipse Project which uses JRE 9
4. Create `PApplet `extending class, call `PApplet.main` with class name, create functions `settings`, `setup`, `draw`:

```
import processing.core.PApplet;

public class UsingProcessing extends PApplet {

	public static void main(String[] args) {
		PApplet.main("UsingProcessing");
	}
	
	public void settings() {
		size(300, 300);
	}
	
	public void setup() {
	}
	
	public void draw() {
		background(51);
               //more test code could go here
	}

}
```

5. Click "Run as" -> "Java Application"

## Your Environment

 

* Processing version: 3.3.6
* Operating System and OS version: Windows 10 version 1803
* Other information: Java (RE) 9 and Eclipse Oxygen.3a Release (4.7.3a)

## Possible Causes / Solutions
I am sure this has to do with the `substring`ing that is done in line 121 in the PApplet source code. I am not a processing source code "insider" but I would consider more checks for version type and length. 

**This is of course easily fixed by switching to Java 1.8 or even 10.0, but it might be necessary for some people to use this particular version.**

Thanks in advance!

kleinesfilmröllchen

**Comment by benfry** [comment]
Java 9 and later are not supported: https://github.com/processing/processing/wiki/Supported-Platforms#java-versions

**Comment by neilcsmith-net** [comment]
@benfry there's a big difference between not supported and actively stopping if you want people to help with testing towards that support?!

@kleinesfilmroellchen you know Java 9 is dead and unsupported now already?
