### ISSUE TITLE
[feature request] - processing/processing - adding transpilers to processing

### ISSUE THREAD

**Issue by tmm2018** [processing/processing#5611]
#### [feature request] - processing/processing - adding transpilers to processing

**i think it would be interesting, within certain regard, to:**
- *add in transpilers to processing*

**this would definitely make it easier to:**

- *get the processing native language, and potentially generating binaries, for different kinds of languages*

**an example of that would defintely be:**
- *openframeworks emscripten*

**while openframeworks emscripten is a great tool, ofx lacks of:**
- *maintainance*
- *stability*

**the reason for that is that:**
- *they expanded their code base really quickly*
- *they lost a sense of hype*
- *most of their addons are no longer being maintained*
- *the source is currently very unstable*

**however:**
- *they introduced a lot of very interesting concepts*
- *those concepts can be applied to processing and many other different kinds of things*

**if processing could be added in an addon that could transpile its source to:**
- *javascript python*
- *java c++*
- *other languages*

**it would be years light ahead**

**Comment by gohai** [comment]
Any form of translation adds a layer of complexity and indirection, which more experienced programmers can sometimes navigate, but which makes it even harder (and opaque) for beginners to understand why their code is not working the way it should.

This should not discourage you from trying this out, or experimenting with these interesting possibilities.

**Comment by jeremydouglass** [comment]
Currently both Processing's Python mode and R mode use transpiling under-the-hood to run Python / R on JVM with jython / renjin -- so it is transpiling in the opposite direction, to JVM rather than away from it.

However, that suggests that one way of approaching what you want might be to begin developing either a new Mode or a new Tool that targets the form of output you want.
