### ISSUE TITLE
P2D can't draw lines of 1 pixel

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#5612]
* Processing version: 3.4
* Operating System and OS version: OSX 10.12.6
* Other information:

The P2D renderer is not able to draw lines of 1 pixel.
The minimum line length is 2 pixels.
This is not the case with the default renderer.

```java
void setup() {
  size(600, 600, P2D);  
}

void draw() {
  background(50);
  stroke(255);
  line(10, 10, 10, 10);
}
```

**Comment by gohai** [comment]
@clankill3r Is this on a high-DPI ("retina") display?

**Comment by clankill3r** [comment]
Yes, also setting `pixelDensity` to either 1 or 2 has no effect.

**Comment by mishazawa** [comment]
Try to draw one-pixel line from (10,10) into some direction f.e. x + 1 or y - 1 ... I think your line that start at (10, 10) and finished in (10, 10) have zero length.

**Comment by Sardtok** [comment]
It does indeed work differently from other renderers, but is there a real use case for this? If you need to set a single pixels value, can't you do it with: `point(10, 10);`
Do you have lines changing shape and disappearing unexpectedly or something?

**Comment by benfry** [comment]
Yeah, this is why `point()` exists. The behavior of drawing a line of zero-length is going to be different given graphics card, OS, renderer, etc.
