### ISSUE TITLE
Escape key does not close the sketch in processing 3.4

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#5614]
Processing 3.4
Max OSX 10.12.6

In older versions when I run a sketch and press escape the sketch closes.
In 3.4 this does not work anymore.

(It was quite convenient cause you can leave the mouse wherever it is).

**Comment by gohai** [comment]
@clankill3r Which renderer are you seeing this on?

**Comment by clankill3r** [comment]
Hmm I can't reproduce it anymore.
I will report back once I have it again.
