### ISSUE TITLE
Using custom `main(String[] args)` breaks file reading functions in Windows (e.g. `loadShader()`, `loadImage()`)

### ISSUE THREAD

**Issue by haschdl** [processing/processing#5615]
## Description
Adding a custom `main(String[] args)` to sketch in Processing breaks `loadShader()`, throwing exception 

> The file "file" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.

The same exception is thrown for `loadImage()`.

## Expected Behavior
Calling `loadShader()` should work also when using a custom `main()` function.
,

## Current Behavior

Sketch no longer executes, throwing the exception described above.
In addition to that, adding a custom  `main()` changes the output of `sketchPath()` to the location of Processing executable:
* Without `main(String[] args)`, `sketchPath("")` returns the location of the `.pde` file: C:\processing-3.3.7\modes\java\examples\Basics\Image\Alphamask\
* With `main(String[] args)`, `sketchPath("")` returns the location of my Processing installation:  C:\processing-3.3.7\

## Steps to Reproduce
1. Open Processing example "BlurFilter"
2. Add the following code to sketch:
``` Java
static public void main(String[] args) {
  String[] appletArgs = new String[] {  "BlurFilter"};
  PApplet.main(appletArgs);
}
```
3. Run the sketch
Error is the same for example "AlphaMask", which uses `loadImage()`.

## Your Environment
* Processing version: 3.3.5 
* Operating System and OS version: Windows 10 64

## Possible Causes / Solutions
No idea, but I suspect this affects all file reading operations, not only `loadShader()` and `loadImage()` due to how Processing resolves the path.

**Comment by benfry** [comment]
That code isn't correct, it doesn't include your sketch class… You would need something like

```
static public void main(String[] args) {
  PApplet.main("YourSketchName", "BlurFilter");
}
```

**Comment by haschdl** [comment]
hi @benfry , what do you mean? Sketch class is included in String array.  "BlurFilter" is the sketch name by the way... Could you reopen?

**Comment by benfry** [comment]
Then why are you creating a custom `main()` method if it's just launching the sketch?

**Comment by haschdl** [comment]
@benfry the code example I posted is the minimum to reproduce the problem. In my example I used main to parse different inputs coming from args[] in a Windows environment.
