### ISSUE TITLE
Problem with my simple Breaker game.

### ISSUE THREAD

**Issue by Biascuit** [processing/processing#5629]
I use windows 10.

I'm working on my first full project and i decide to do a simple game of breaker. Everything so far except for collisions has been a piece of cake so i started to add the bricks. Thats when catastrophe struck.
I expected the boxes to appear and to have collision. but when i run the program it does load. gray screen and spinning wheel of death till i close out of it. I don't think it is my computer as i have never had trouble with any other code even more complex. Anyway as i am very new to the ideas of what "classes", "voids", and "arrays" are this was as to be expected but going over it and changing things makes no difference. Here is my code for the bricks

class Brick {

 int[] bricks;
 float x;
 float y;
 int i; 

 Brick() {
 int i;  
 bricks = new int [20];
 x = myball.x;
 y = myball.y;
 for (i=0; i<20; i++) {
    bricks[i] = 1;
  }
 }

 void act() {
   int i, xTmp, yTmp;
   int bricksGone;
   
   bricksGone = 1;
   for (i=0; i<20; i++) {
     bricks[i] = 1;
     
     xTmp = i%5*100+10;
     yTmp = 40*(i/5)+10;
     
     if(bricks[i] == 1) {
       
       rect(xTmp + 40, yTmp + 10, 80, 20);
       
       bricksGone = 0;
     }
     if (((x>(xTmp-1) && x<(xTmp+5)) || (x>(xTmp+75) && x<(xTmp + 81))) &&
     y>yTmp && y<(yTmp+20) && bricks[i] == 1) {
       bricks[i] = 0;
       myball.vx = -myball.vx;
       myball.vy = -myball.vy;
     }
     if (((x>(xTmp-5) && x<xTmp) || (x>(xTmp+80) && x<(xTmp+85))) &&
      y>yTmp && y<(yTmp+20) && bricks[i]==1) { 
      bricks[i]=0;
      myball.vx = -myball.vx;
    }
     if (((x>(xTmp-1) && x<(xTmp+5)) || (x>(xTmp+75) && x<(xTmp+81))) &&
      y>yTmp && y<(yTmp+20) && bricks[i]==1) { 
      bricks[i]=0;
      myball.vx = -myball.vx;
      myball.vy = -myball.vy;
      
    }
   }
 }
}

I have my game set up simply with if else statements that declare if its the intro or if im playing or if im dead. along with that i have functions for all of those as well that go in the if else statements. for reference.

void draw() {
  if (mode == intro) {
    intro();
    if(keyPressed)
    mode += 1;
  } else if (mode == playing) { 
    playing();
  } else if (mode == pause) {
    pause();
  } else if (mode == win) {
    win();
  } else if (mode == lose) {
    lose();
  }
  
  
}

In my playing function when i comment out my mybrick.act(); everything works fine my ball and paddle are back with working collisions. can someone help?

**Comment by liquid600pgm** [comment]
I think this is a question you should ask on the [Processing forum](https://discourse.processing.org).
The issues are a place where you should submit problems with Processing itself, and not your code.
