### ISSUE TITLE
processing wont let me download python

### ISSUE THREAD

**Issue by jacksonk1** [processing/processing#5630]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* window 64bit:
* Other information:

###

**Comment by jacksonk1** [comment]
im not very good with this stuff im in a class trying to learn in college please help my stuff is due monday

**Comment by liquid600pgm** [comment]
Please describe your issue with greater detail. Just saying "it doesn't work" doesn't help, as we don't know what could be causing the issue. Edit your issue following the instructions in the template.

**Comment by benfry** [comment]
No response; closing.
