### ISSUE TITLE
enum & interface after a bad line logs an error

### ISSUE THREAD

**Issue by dzaima** [processing/processing#5637]
## Description
Entering (just pasting) the following code throws a long error in the console:
```java
void f (int) {}
enum e {a}
interface i {}
```
does strange stuff.

## Expected Behavior

Some error should appear in the errors tab about the unnamed parameter `int`

## Current Behavior
This is written to the console:
```
Status ERROR: org.eclipse.jdt.core code=4 Exception occurred during compilation unit conversion:
----------------------------------- SOURCE BEGIN -------------------------------------
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;
import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_180902a extends PApplet {
void f (int) {}
enum e {a}
interface i {}

}

----------------------------------- SOURCE END ------------------------------------- java.lang.IllegalArgumentException
```
`ctrl+click`ing on `f`, among other things, can also freeze the editor

## My Environment

* Processing version: 3.4, also happens on latest commit here
* OS: Linux Mint 18.3 Cinnamon

**Comment by mishazawa** [comment]
You should specify parameter name in function signature. For me it works.

```
void f (int parameter) {}
enum e {a}
interface i {}
```

**Comment by dzaima** [comment]
I know how to fix it (as per `Some error should appear in the errors tab about the unnamed parameter "int"`), just that I didn't expect a simple mistake to spam the console and freeze the editor.

**Comment by Sardtok** [comment]
Just to clarify, if you instead enter
```
void f (int) {}
void g() {}
```
int is marked as problematic with the following error message: Error on "...VariableDeclaratorId",
and trying to build gives the error: unexpected token int.

The same should happen with enums and interfaces.

If you instead declare a class right after, you get an additional syntax error marked in the code. The right curly brace gets the error message: Syntax error on "}", delete this.

So the behaviour of the parser is a bit inconsistent here.

**Comment by dzaima** [comment]
@Sardtok Yes, though the curly brace error is understandable, as the parser is probably incorrectly trying to "recover" from the error to give further errors, but failing.

---

Searching for the error in the closed issues I found https://github.com/processing/processing/issues/5570 which seems to still be working, but is closed by some reason.

**Comment by dzaima** [comment]
Doesn't happen in Processing 4, assuming this can be closed.
