### ISSUE TITLE
unable to relaunch after closing in mac

### ISSUE THREAD

**Issue by amitsingh19975** [processing/processing#5643]
## Description
After clicking the close button it closes to the docker in mac and when I try to relaunch
its not showing up.

## Expected Behaviour
It should launch the window when we click on app

## Current Behaviour 
It does not launch the window when we click on app

## Steps to Reproduce
1.lauch the app
2.close the window
3.relaunch from docker

## Your Environment
* Processing version:3.37
* Operating System and OS version:macOS High Sierra
* Other information:

**Comment by gohai** [comment]
Other applications behave the same way when no window is open. You have to press *File* > *New...* to open up a new window from the menu.

**Comment by amitsingh19975** [comment]
not every app for example vs code, whenever when you click on vs code either it reopens previous window or new window

**Comment by gohai** [comment]
Sure, but not all apps either.

**Comment by amitsingh19975** [comment]
I could be added as feature

**Comment by hamoid** [comment]
Today I saw this happening on a Mac with Processing 3.4. Choosing File > New did **not** help (it did nothing). The way to bring it back was to go to File > Sketchbook, which showed one previously saved sketch and double clicked that sketch, which brought back the editor.

**Comment by hamoid** [comment]
Based on my last comment, should this issue be closed?

**Comment by benfry** [comment]
The behavior is consistent with how Mac apps work (closing the window doesn't close the app; clicking on the app doesn't create a new document window). 

In the past (before 2.x?) we had the most recent sketches reload on startup, but it was difficult to implement consistently across platforms, and some people found it annoying anyway.

@hamoid that sounds like a bug, please file it separately
