### ISSUE TITLE
v3.4.1 - Could not create virtual machine (ArchLinux)

### ISSUE THREAD

**Issue by hamoid** [processing/processing#5649]
Processing does not start after upgrading from v3.3.7 to v3.4.1

## Your Environment

* Processing version: 3.4.1
* Operating System and OS version: up to date ArchLinux

## Possible Causes / Solutions

Is it Processing or is it the ArchLinux Processing package?

```bash
~ $ processing
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp
-Djava.ext.dirs=/usr/share/processing/java/lib/ext is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
~ $ cd /var/cache/pacman/pkg/
/v/c/p/pkg $ ls -la *processing*
-rw-r--r-- 1 root root 96835352 Mar 16 12:30 processing-3.3.7-1-x86_64.pkg.tar.xz
-rw-r--r-- 1 root root 43898380 Sep 13 15:19 processing-3.4-1-x86_64.pkg.tar.xz
...
/v/c/p/pkg $ sudo pacman -U processing-3.3.7-1-x86_64.pkg.tar.xz 
[sudo] password for xxxx: 
loading packages...
warning: downgrading package processing (3.4-1 => 3.3.7-1)
resolving dependencies...
looking for conflicting packages...

Packages (1) processing-3.3.7-1

Total Installed Size:  263.62 MiB
Net Upgrade Size:      202.02 MiB

:: Proceed with installation? [Y/n] 
```
After downgrading things work fine again.

**Comment by benfry** [comment]
There's no 3.4.1 release, and I have no idea who built that. Please use the release posted on the download page.

**Comment by hamoid** [comment]
Interesting. It seems it was built by Alexander Rødseth
https://www.archlinux.org/packages/community/x86_64/processing/

It seems like the ArchLinux Processing package exists since 6 years ago:
https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/processing

These are the changes to the package from 25 hours ago (in case anyone cares):
https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/processing&id=0b27d4bf57e68fb1d20707dbf25420dabf487f8b

I'll ask what's going on.

**Comment by eli-schwartz** [comment]
cf. https://bugs.archlinux.org/task/60052

Our processing package is actually 3.4-1 (version 3.4, distro build number 1), so at least this is indeed the real release.

Whether you wish to support distro builds of your software I cannot say... just wanted to clear up this confusion.

**Comment by hamoid** [comment]
I think I found out the reason.

The ArchLinux Processing 3.4 package no longer includes java, so it's 44 Mb instead of 97 Mb. That means Processing uses the default Java environment, which in my case was Java 10 OpenJDK. With that version it fails to start. But if I run

    $ sudo archlinux-java set java-8-openjdk

then it starts normally. Sorry for the noise.

**Comment by freetz13** [comment]
> I think I found out the reason.
> 
> The ArchLinux Processing 3.4 package no longer includes java, so it's 44 Mb instead of 97 Mb. That means Processing uses the default Java environment, which in my case was Java 10 OpenJDK. With that version it fails to start. But if I run
> 
> ```
> $ sudo archlinux-java set java-8-openjdk
> ```
> 
> then it starts normally. Sorry for the noise.

Ran into this on Manjaro. I ran `archlinux-java status`:

```
Available Java environments:
  java-13-openjdk (default)
  java-8-openjdk/jre
```

so then I ran `sudo archlinux-java set java-8-openjdk/jre`
