### ISSUE TITLE
Scancode error

### ISSUE THREAD

**Issue by Pterelas** [processing/processing#5651]
The dead keys seem to ignore the shift key. They generate the same keyCode whether it is pressed or not. This concerns among other, the ^¨ key of the French keyboard (France), the ^\` and ¨! keys of the French keyboard (Switzerland), the \`^ and ´¨ keys of the Spanish keyboard (Spain), the ´\` and ~^ keys of the Portuguese keyboard (Portugal) and the ^! key of the BÉPO layout (a kind of Dvorak layout for the French language).
My operating system is Windows 10 and I’m using the 3.4 version of Processing.

**Comment by benfry** [comment]
I don't know what “The dead keys seem to ignore the shift key” means. If you're having an issue, please use the template that's provided when you create a new issue, so that it's in a format we can understand.
