### ISSUE TITLE
Chrome ver 69 fails to download Processing for Windows - thinks there is a virus. 

### ISSUE THREAD

**Issue by sortofsleepy** [processing/processing#5664]
## Description
Chrome version 69 fails to complete download when trying to download Processing for windows 

## Expected Behavior
Chrome should complete download 

## Current Behavior
Chrome blocks download 

## Steps to Reproduce
Try to download Processing from Chrome version 69 

## Your Environment
* Processing version: latest (3.4)
* Operating System and OS version: Windows 10
* Other information:

## Possible Causes / Solutions
Not sure why this is happening - I'm certain I've completed a download before. According to the Chrome help docs, it's possible this is interference surprisingly from the system's own Virus scanner(in my case Windows Defender) 

It's entirely possible this is a non-issue and it's something on my end but just wanted to make sure someone brought it up just in case it's a more serious matter.

**Comment by sortofsleepy** [comment]
likely related to #5537

**Comment by LemuelCushing** [comment]
Not sure if I should post this here or on #5537, but I seem to be getting a similar error. 
Specifically, ```processing-3.4-windows64.zip``` is being flagged as containing a Trojan Downloader ```JS/Jasobfus.B!ml``` 
 
Detailed alert:
![image](https://user-images.githubusercontent.com/7855659/46254126-0d77ed00-c493-11e8-86fa-d5a37f8af04c.png)

**Comment by benfry** [comment]
Please report it to Microsoft as a false positive. There's nothing we can do about it.
