### ISSUE TITLE
There is a VIRUS!

### ISSUE THREAD

**Issue by krsultov** [processing/processing#5665]
I download processing 3.4 from processing.org
and after the download

Windows defender tells me that : " TrojanDownloader:JS/Jasobfus.B!ml 
category:  Trojan Downloader 
details:   This program is dangerous and downloads other programs."

![image](https://user-images.githubusercontent.com/33312330/46258026-bb53bd80-c4cc-11e8-9852-c026646618b9.png)

![image](https://user-images.githubusercontent.com/33312330/46258042-dde5d680-c4cc-11e8-8a43-79686bf661a6.png)

**Comment by benfry** [comment]
No there isn't. It's a false positive, and a Microsoft problem. It [happens](https://github.com/processing/processing/issues?utf8=%E2%9C%93&q=is%3Aissue+virus) [frequently](https://github.com/processing/processing/issues?utf8=%E2%9C%93&q=is%3Aissue+trojan) but Microsoft won't help.
