### ISSUE TITLE
iteration problem between PApplet call and method rotate

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5669]
I try to use the method rotate via PApplet, but Processing return an error of iteration, my method to call and use PApplet work perfectly with `translate()` `rect()` `ellipse()` `box()` so it's little weird that's don't work with translate

A StackOverflowError means that you have a bug that's causing a function
to be called recursively (it's calling itself and going in circles),
or you're intentionally calling a recursive function too much,
and your code should be rewritten in a more efficient manner.
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help → Troubleshooting.

sketch to reproduce : 
```
void setup() {
  size(500,500);
  init_pa(this);
}

float val;
void draw() {
  val += .01;
  rotate(val);
}

PApplet pr;
void init_pa(PApplet pa) {
  this.pr = pa ;
}

void rotate(float arg) {
  pr.rotate(arg);
}
```

Processing 3.4 on OSX High Sierra

**Comment by gohai** [comment]
@StanLepunK I believe the behavior you are seeing is in fact correct, and there is no bug:

Your sketch lives in `PApplet`. Thus when you call `pr.rotate(float)`, this will re-invoke the current function you are in. You can change that like to `super.rotate(float)`, and the problem will go away, as you're no longer invoking the function you're overloading, but the default implementation of `rotate` in `PApplet`.

If you make `init_pa` and `rotate` methods of a new class this issue will also go away, as this class won't be extending `PApplet`.

**Comment by StanLepunK** [comment]
@gohai thx for your explication, it is very clear. Plus there is an other way to do it's call `g.rotate(float)`that's work too.
