### ISSUE TITLE
Processing opencv.detect() crash on Mojave

### ISSUE THREAD

**Issue by sssss465** [processing/processing#5682]
## Description

The opencv library on MacOS Mojave crashes upon using the opencv.detect() function.

## Current Behavior

Error: NullPointerException

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version: Mac OS Mojave
* Other information: Macbook Pro 2015

**Comment by gohai** [comment]
Reporting this hear might bring it to the attention of the right set of eyes: https://github.com/atduskgreg/opencv-processing
