### ISSUE TITLE
Processing sometimes doesn´t register when key is pressed!

### ISSUE THREAD

**Issue by Testamentor** [processing/processing#5689]
[Little Game.zip](https://github.com/processing/processing/files/2515775/Little.Game.zip)

**Processing Code doesn´t work**
Hey, im a Student and in my free time I wrote a litte game in Processing.
But there is a bug with Processing. My game includes a startscreen and you have to press the key 1 to start the game. But now the Problem is that sometimes the game starts and sometimes not. I tryed the Code on many different devices but everywhere there is the same error.

To figure out if the Problem is in my code I made the Programm to show "stage 1,2,... done" in the output window. With this help I was sure the problem is not in my code but in Processing because sometimes Processing doesn´t register that im Pressing the key "1".

I will add the code to this message so you can check if im wrong, please.

**Comment by dzaima** [comment]
Your code errors if you click in the screen while the game hasn't been started yet, because then you're doing `balls[i].pointInEllipse(...)` before you've made any objects in the array. I'm guessing you've clicked in the screen before pressing `1`.

**Comment by Testamentor** [comment]
Thanks for your answer but thats not the problem I mean. You have to start the program and press 1 first before you click to get the problem. But sometimes it works andund sometimes not.

Thanks to make me aware of your problem but thats not the one I mean. :)

**Comment by dzaima** [comment]
I've restarted & clicked `1` probably ~50 times and I'm not getting any errors & the game seems to be starting (after fixing the error). You sure you had the window focused, while not having clicked in the window before, making `1` useless after the error? Either way, you could try using the different renderers to see whether it occurs for all (by adding a 3rd argument to `size` of either `P2D` or `FX2D`)

**Comment by Testamentor** [comment]
Good idea. I'll try it later and let you know if it worked. 
An other question: On which Processing version are you running the code?
Thanks.

**Comment by Testamentor** [comment]
### Now it seems to work :)
I put `P2D` as 3rd Argument to `size` and started the program ~20 times and every time it worked.
Im very happy now, thank you for helping me to fix this problem.
