### ISSUE TITLE
How to generate `processing-java` on macOS from the command line

### ISSUE THREAD

**Issue by vitorgalvao** [processing/processing#5690]
I understand the template says this is only for bugs and feature requests, but this is related to Processing’s internals so it seems like the best place.

How is the `processing-java` CLI generated on macOS? [The wiki](https://github.com/processing/processing/wiki/Command-Line) does not specify how it’s done, though it says that for Windows and Linux, it’s a separate file with the download.

I’m a [Homebrew Cask](https://github.com/Homebrew/homebrew-cask) maintainer (we allow the installation of GUI apps from the command line) and have been supporting Processing there for a long time. But I’d also like to add support for `processing-java` directly, so when someone installs Processing, they immediately get `processing-java` without further action. This also has the advantage that when upgrading, users won’t need to readd it, as we’ll do it automatically.

I’ve looked inside `Processing.app` but didn’t find `processing-java`. Looking at it, it looks like it’s generated on the fly. Is it? Is there a way that we could, via command line, tell `processing-java` to be created?

**Comment by gohai** [comment]
It's in [app/src/processing/app/tools/InstallCommander.java](https://github.com/processing/processing/blob/master/app/src/processing/app/tools/InstallCommander.java)

**Comment by vitorgalvao** [comment]
@gohai That’s its location *in the repo*. What I’m asking is how to access it from the compiled `.app`.

**Comment by gohai** [comment]
@vitorgalvao You access it from the menu bar. The source file I pointed to should inform you how it is being created.

**Comment by vitorgalvao** [comment]
> You access it from the menu bar.

My question was *specifically* for a way to create it via command-line, so it can be automated.

**Comment by gohai** [comment]
_Looking at it, it looks like it’s generated on the fly. Is it?_ 🤷
