### ISSUE TITLE
selectInput() and selectFolder() shouldn't be asynchronous

### ISSUE THREAD

**Issue by ZOLDIK0** [processing/processing#5696]
## Description

Bug in the SelectInput() and SelectFolder() methods 
## Expected Behavior

I think that these methods should give a window to prompt the user to give an input . till he do they shouldn't go to the next lines of code .
## Current Behavior

But currently they doesn't wait until the user give an input they directly go to the next lines of code
processing sees them as a normal executable line of code 
## A Code  Example

As an example if you run this you will get an ask for input window but you will see the println and the variable t will be changed to 20 and printed also . even before you select an input.
```
PImage img;

void setup(){
    int t = 0;
    selectInput("Choose an image","imageSelected");
    println("bug");
    t = 20;
    println(t);
 }
void imageSelected(File selection){
    if(selection ==null){
       println("Error");
    }else{
      img = loadImage( selection.getAbsolutePath() );
    }
  }
```
## My Environment

 

 Processing version: 3.4 .
Operating System and OS version: windows 7 Ultimate / service pack 1 / 32bit .
Other information: new to Processing (newbie)

## Solutions

Currently i have found a way to round on the problem which is to make a loop exactly after the select mothode and making it checking a boolean variable that will be true if the selection happens like this :

```
PImage img;
boolean hasChoosed;
void setup(){
    int t = 0;
    selectInput("Choose an image","imageSelected");
    while(!hasChoosed){
      println("waiting");
      }
    println("now it is okey");
    t = 20;
    println(t);
 }
void imageSelected(File selection){
    if(selection ==null){println("Error");}
    else{
      img = loadImage( selection.getAbsolutePath() );
     hasChoosed = true;
    }
  }
```
the loop will execute even if the user didn't choosed because of that bug but it will make the program stuck there till the variable 'hasChoosed' becomes true . when the user selects an input
However this will overload the processor..

**Comment by dzaima** [comment]
There's a reason the function takes a callback function name as an argument, and doesn't just return a file - to allow the file selection asynchronously and continuing doing stuff in the background. The [reference](https://processing.org/reference/selectInput_.html) - "The callback is necessary because of how threading works."

**Comment by ZOLDIK0** [comment]
> There's a reason the function takes a callback function name as an argument, and doesn't just return a file - to allow the file selection asynchronously and continuing doing stuff in the background. The [reference](https://processing.org/reference/selectInput_.html) - "The callback is necessary because of how threading works."

but sometimes you need the program to stop working till a file has been selected ,because the next lines of code are relative to the file and will start working on the file . you can't work on the file if it has not been chosen yet ! , why they don't make an option in the method arguments that decides whether to stop the flow of the program or stop it temporarily like a choose/cancel message

**Comment by ZOLDIK0** [comment]
for who had the same issue i've found the solution , now this program will start working only when the user chose a file ... no checking-loop in background is required
```
PImage img;
void setup(){
    int t = 0;
    selectInput("Choose an image","imageSelected");
 }
void imageSelected(File selection){
    if(selection ==null){println("Error");}
    else{
      img = loadImage( selection.getAbsolutePath() );
      startImageProcessing();
    }
  }
void startImageProcessing(){
   // now the picture is loaded 
  // we can now do some stuff with the picture
}
```

**Comment by benfry** [comment]
As explained in the reference, this behavior is a necessity.
