### ISSUE TITLE
Add a way to tell if the mouse is over the window.

### ISSUE THREAD

**Issue by Angular-Angel** [processing/processing#5700]
## Description

I want an easy way to tell if the mouse is over the window.

## Expected Behavior

I should be able to call a method or check a boolean to know if the mouse is currently over the window.

## Current Behavior

There is no way that I can find to know if the mouse is over the window. If it is not, mouseX and mouseY will remain in their last values.

## Steps to Reproduce

1. Make some code that does something depending on where the mouse is.
2. Move the mouse off the window.

## Your Environment

 

* Processing version: 3.4
* Operating System and OS version: XUbuntu 18.10
* Other information: Using processing as a library in Eclipse.

## Possible Causes / Solutions

Ideally, a boolean, mouseOverWindow or something like that, updated the same way mouseX and mouseY are.

**Comment by Angular-Angel** [comment]
I implemented this myself with 

    ```
public boolean mousePresent = true;
    
    public void mouseExited() {
    	mousePresent = false;
    }
    
    public void mouseEntered() {
    	mousePresent = true;
    }
```

**Comment by calebccff** [comment]
It is possible to get the data you need from the Java Robot class, you can check mouse position on the desktop a compare it to the mouse position on the window.

This is however only a short term fix, I would agree that a feature like this would be useful.

**Comment by benfry** [comment]
This is better handled by the solution in the original report. `mouseOver` isn't a property we want to maintain—too tricky to figure out how it's handled when dealing with other/newer display devices like touch screens. It's easy enough to do the quick workaround, but a heavier lift on documentation, etc.
