### ISSUE TITLE
Error: Could not create the Java Virtual Machine (Ubuntu 18.04)

### ISSUE THREAD

**Issue by yvig** [processing/processing#5701]
After installing processing, I tried to launch it and received this message 

`-Djava.ext.dirs=/usr/share/processing/processing-3.4/java/lib/ext is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
`
My java version was

`anne@anne-Aspire-5810T:~$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)
`
`
anne@anne-Aspire-5810T:~$ javac -version
javac 10.0.2
`

I changed it in a Oracle one after reading in this page [https://github.com/processing/processing/wiki/Supported-Platforms](url) that "Due to incompatibilities, OpenJDK is not supported. "

Now my java version is
` anne@anne-Aspire-5810T:~$ java -version
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)`
 `
anne@anne-Aspire-5810T:~$ javac -version
javac 11.0.1
`

but the problem remains.

**Comment by benfry** [comment]
[Use Oracle Java 8](https://github.com/processing/processing/wiki/Supported-Platforms#java-8)

**Comment by SmantikVJ** [comment]
I have the same problems installing processing in an Ubuntu 18.04 Jetson Nano SBC. 
I can't install Oracle Java 8 neither following the steps that appear on : [](https://tecadmin.net/install-oracle-java-8-ubuntu-via-ppa/)
Any possible alternative solution?
