### ISSUE TITLE
PApplet.frameMoved() and frameResized() are not called when the frame is moved or resized.

### ISSUE THREAD

**Issue by Angular-Angel** [processing/processing#5703]
## Description

These methods look like they're supposed to be called the same way that the other events are, but when I override them, my versions are not called, even when it looks like they should be.

## Expected Behavior

When the frame is moved or resized, my overridden frameMoved() and frameResized() should be called, and the println statements at their beginnings should be printed to the console. 

## Current Behavior

When the frame is moved or resized, my overridden frameMoved() and frameResized() are not called, and the println statements at their beginnings are not printed to the console.

## Steps to Reproduce

1. Create a class that extends PApplet, and have it enable frame resizing.
2. Override frameMoved() and frameResized().
3. Run, move and resize the window, and observe that the overridden methods are never called.

## Your Environment

 

* Processing version: 3.4
* Operating System and OS version: Xubuntu 18.10
* Other information:

**Comment by glynternet** [comment]
I'm experiencing the same thing on Ubuntu 18.10

**Comment by benfry** [comment]
This isn't a part of the API, and not documented anywhere; I'm not sure why you'd expect this to exist.
