### ISSUE TITLE
Processing 3.4 takes 60 seconds before can edit file

### ISSUE THREAD

**Issue by gpteacher** [processing/processing#5707]
## Description
<When you launch Processing 3.4, the insertion mark (cursor) does not flash for at least>
<60 seconds. Cannot start editing a file/running a program until then.>

## Expected Behavior
<When IDE window opens, I should be able to start editing file immediately>

## Your Environment

* Processing version: 3.4 (July 2018)
* Operating System and OS version: Windows 8.1 Pro, 64 Bit
* Other information: 4 Gigabytes RAM, 2.16GHz Celeron

**Comment by dzaima** [comment]
Pretty sure this is the same issue as #4731. Clearing up the `Documents/Processing/` directory should help.

**Comment by gpteacher** [comment]
Thanks so much for your response Dzaima. I looked in the directory and the 'android' and 'modes' folders are in there for compiling Android apps. I moved those two folders out and relaunched Processing and it's nice and immediately available. I put those folders back and it takes a minute before I can edit.

Thank you for the clarification Much appreciated.

**Comment by benfry** [comment]
@codeanticode Can you make sure that Android Mode isn't doing something that's blocking the UI thread on init/startup?

**Comment by codeanticode** [comment]
@benfry sure, I will look into this.

@gpteacher glad that removing the android mode files serves as a workaround, but this is indicating some issue in the mode. I will let you know when the problem is solved.

**Comment by codeanticode** [comment]
@gpteacher do you remember when you started experiencing this editor delay issue? Was it immediately after installing the android mode for the first time, or did it work fine for a while until you  updated it? Thanks!

**Comment by dzaima** [comment]
I believe the issue is just a bunch of files/folders in the Processing sketch directory. Changing the Processing sketchbook location to `~` (or any other folder with way too many files) makes it open very, very slowly.

**Comment by codeanticode** [comment]
ok, so it might not be related to the mode after all. I haven't seen it myself, but perhaps it is just that I don't have enough sketches :-)

**Comment by gpteacher** [comment]
It was a coincidence that I had upgraded to Version 3.x at the same time I started experimenting with Android Mode.I would experience a 1 minute delay before the cursor was available inside the Editor screen.
But as forum member, 'dzaima' informed me, because Processing reads ALL files in the Processing folder at startup, it was now having to read through the 'SDK' folder and the 'android' folder in the 'modes' folder that were now inside the Processing directory.
That's what slows down launch of Processing.
As soon as I moved the 'mode' folder which contains the Android support code out of the Processing folder, the IDE launches nice and quickly and the cursor is available for editing immediately upon open.
That moving of android files out of the Processing folder fixes the issue.
So now, I just leave those android folders somewhere else unless I want to do Android work at which time I re-install those folders into the Processing folder and I recognize that it will take longer for processing to complete startup before I can use it.
Problem solved.
Thanks very much
Gord
    On Tuesday, December 11, 2018, 9:55:02 AM EST, codeanticode <notifications@github.com> wrote:  
 
 
@gpteacher do you remember when you started experiencing this editor delay issue? Was it immediately after installing the android mode for the first time, or did it work fine for a while until you updated it? Thanks!

**Comment by codeanticode** [comment]
Ok, got it. The reason I moved the location of the sdk from inside the android mode to the root of the skechbook folder was that updating the mode would result in losing the SDK, which is in itself a fairly large download (around 1 GB), and could be even larger if it includes system images... 

A couple of alternative solutions could be:

1. Leave the SDK inside the android mode folder, but move it from the old to the new when updating. However, the update is not handled by the mode, so this would require changing the mode update code.

2. Skip the android/sdk folder when Processing scans the sketchbook folder looking for sketches. This would also require a modification outside the android mode, but probably a fairly small one (simply ignore android/sdk)

3. Move the SDK folder somewhere else. The question would be where.

@benfry do you have any thoughts? My choice would be 2 since it seems the simplest solution.

**Comment by benfry** [comment]
The second option seems correct; though I can't recall offhand if we already have a callback for skipping that sort of thing (I thought we might for things like dot files, screenshots, and others, but it may be hard-coded).

**Comment by codeanticode** [comment]
ok, found it. This commit should fix the problem: https://github.com/processing/processing/commit/5b653263cc6151f838c11a61689d756901c11e37

Users will still be able to have a folder called sdk inside the sketchbook folder, if they want. Only android/sdk is skipped.

@gpteacher until this fix is available in the next version of Processing, you can simply move your android/sdk folder to another location outside the sketchbook folder and select it manually when switching back into the Android mode.

**Comment by gpteacher** [comment]
Thanks everyone for your responsiveness to this issue. I'm personally happy just to temporarily relocate the folders when I'm not doing Android work. But your fix is appreciated.
Please keep doing your terrific work on this amazing environment.
Best wishes,
Gord
    On Thursday, January 3, 2019, 9:51:24 AM EST, codeanticode <notifications@github.com> wrote:  
 
 
ok, found it. This commit should fix the problem: 5b65326

Users will still be able to have a folder called sdk inside the sketchbook folder, if they want. Only android/sdk is skipped.

@gpteacher until this fix is available in the next version of Processing, you can simply move your android/sdk folder to another location outside the sketchbook folder and select it manually when switching back into the Android mode.
