### ISSUE TITLE
Feature request: Version numbers in Reference Manual URLs

### ISSUE THREAD

**Issue by scolobb** [processing/processing#5711]
## Description

The reference manual is currently downloadable from http://download.processing.org/reference.zip.  This URL does not include the version number of the reference.  This is somewhat problematic for automatic downloads and hash checks, because the versions of Processing itself are fixed in the download URL.

## Expected Behavior

It would be great to have "permanent" URLs like http://download.processing.org/reference-3.4.zip.

## Current Behavior

Currently, the download link for the reference manual does not appear in the download URL.

## Your Environment

 

* Processing version: 3.4
* Operating System and OS version: [NixOS](https://nixos.org/)
* Other information:

## Possible Causes / Solutions

Store 2 or 3 latest stable versions of the reference manual and have separate URLs for these.

**Comment by benfry** [comment]
The reference.zip file is only there for the build process, it's not intended as a public link, and AFAIK isn't listed anywhere except deep in a build script. 

The entire recent reference is included with each release. There's no need for us to maintain a separate download or link.

**Comment by worldofpeace** [comment]
> The entire recent reference is included with each release. There's no need for us to maintain a separate download or link.

Meaning that fetching this file is unneeded and will be removed from the build process?

**Comment by scolobb** [comment]
Thank you for your answer @benfry , but it turns out this is my situation: I am looking at updating a [Nix](https://nixos.org/nix/) package which fetches Processing from GitHub, and which therefore needs to get the reference manual from somewhere.

Is there a public (Git) repository with the reference manual?  What is the recommended way of building Processing with the reference manual included?

If I manage to find out an answer, I'll happily submit a small extension to `CONTRIBUTING.md`.

Thank you for your time and for the development of this awesome software!

**Comment by benfry** [comment]
@worldofpeace No, just that the only reason it exists is for me running `ant dist` to push out a new release. 

@scolobb Yeah, the docs/reference repo is [here](https://github.com/processing/processing-docs). When substantial changes are made there, Casey does a build that creates a new `reference.zip`. Then when a new release happens (out of this repo), the latest .zip is downloaded as needed.

**Comment by scolobb** [comment]
Thank you for your answer @benfry !

I have trouble finding time right now (the school year is starting), but I'll get back to updating the Nix package and doing a pull request to `CONTRIBUTING.md` as soon as I can.
