### ISSUE TITLE
FX2D text() leaks memory

### ISSUE THREAD

**Issue by dzaima** [processing/processing#5715]
## Description
The simple code
```java
void setup(){ size(400, 400, FX2D); }
void draw(){ text("0", 123, 456); }
```
slowly uses a lot of memory.

## Expected Behavior
Used memory stays constant.

## Current Behavior
Over some time (a couple of minutes) the RAM usage can go over 2GB (and then I stop it because I don't want my system to freeze). This doesn't occur with other renderers, and it doesn't happen if a `text()` call isn't present (though I haven't tested many other methods). A call to `System.gc()` every frame doesn't help either.

## Steps to Reproduce
1. paste the code into PDE
2. run it
3. wait

## Your Environment
* Processing version: 3.4, also happens on the master branch here
* Operating System and OS version: Linux Mint 18.3, 64-bit

**Comment by relaxing** [comment]
Cannot reproduce with Processing 3.5.1, Java 1.8.0 b131, MacOS 10.14.2. Looking at heap usage all I see is the normal sawtooth GC behavior. Total heap size only decreases over time.

@dzaima can you upgrade, then run VisualVM and use the sampler to see what classes are using the most memory? Then you can use the profiler tab to see where those classes are being created.

**Comment by dzaima** [comment]
@relaxing VisualVM doesn't show any unusual heap usage (heap size staying below 73MB), but my used RAM definitely is still going above multiple gigabytes in 3.5.1. (same with the IntelliJ IDEA debugger). Not sure what could be the cause for that to happen.

**Comment by benfry** [comment]
Other possibilities: 
1. Make sure you're not using OpenJDK
2. If you have enough memory, the JVM may not bother garbage collecting (and your OS may not bother de-allocating) until absolutely necessary. This is the way modern memory management works—it's only a leak if you run out of memory.

**Comment by dzaima** [comment]
> 1. Make sure you're not using OpenJDK
> 2. If you have enough memory, the JVM may not bother garbage collecting (and your OS may not bother de-allocating) until absolutely necessary.

1. Trying using OpenJDK doesn't even work. 
2. As I said, adding `System.gc();` to the draw loop doesn't help (and everywhere else I've tried, a call to it _will_ reduce used RAM to the minimum), and considering that this is the only java program that gives me this problem, I wouldn't think it to be the cause. I can't say for sure that it is a leak, but it's definitely able to freeze linux to a complete halt.

Running in Oracle Java 10 (with some modifications to PSurfaceFX for it to even run) I still get this problem.

**Comment by relaxing** [comment]
> @relaxing VisualVM doesn't show any unusual heap usage (heap size staying below 73MB), but my used RAM definitely is still going above multiple gigabytes in 3.5.1. (same with the IntelliJ IDEA debugger). Not sure what could be the cause for that to happen.

Wait, are you sure which process is consuming memory? Have you checked by running the 'top' command and sorting by memory usage (shift-M)? 

It's possible the memory is being used by something else entirely, such as console output and an unlimited scrollback history buffer.

**Comment by dzaima** [comment]
> Wait, are you sure which process is consuming memory? Have you checked by running the 'top' command and sorting by memory usage (shift-M)?
> 
> It's possible the memory is being used by something else entirely, such as console output and an unlimited scrollback history buffer.

[Screenshot](https://user-images.githubusercontent.com/5551338/52090301-9de94a00-25b9-11e9-92fd-a53f768e0326.png) of `xprop` on the sketch window, followed by `top`. I also rechecked that the PID of jvisualvm matches the process.

**Comment by cluder** [comment]
i also cannot reproduce the problem in Ubuntu with processing 3.3.5 openjdk 10.0.2.
Sketch is running since 15 min, using constant ~5 MB .

Use https://www.eclipse.org/mat/downloads.php to create and analyze a memory dump of your process.
If there is a memory leak, MAT will show it.
(create multiple dumps a few minutes apart and compare the differences)

**Comment by dzaima** [comment]
@cluder Memory dumps consistently stay low. MAT too showed usage of ~5MB, while the java process clearly was using over 1GB. No idea how and what would allow that to be a possibility, but it probably isn't Processings fault..

**Comment by dzaima** [comment]
Cannot reproduce now (neither in 3.5.3 nor 4.0), closing on the assumption this was an OS problem (I've now upgraded to Linux Mint 19) or some other external thing.
