### ISSUE TITLE
An error occurred during startup with 3.4(0265)

### ISSUE THREAD

**Issue by flamthunder** [processing/processing#5716]
## Description
processing error occurred during startup,I can't open the processing. I try to download the latest processing file on processing.org. And reinstall the latest java 8u191, still don't work.
I also find there is another issue in version2.2.1, the solution is delete the contribution.txt file, but in this version I can't find any file in library.
<img width="673" alt="2018-12-05 10 38 05" src="https://user-images.githubusercontent.com/45614193/49486853-00a0bc80-f87b-11e8-8638-bd1d7d249a0a.png">

## Expected Behavior
open the processing

## Current Behavior
 can't open processing

## Your Environment

 

* Processing version:3.4(0265)
* Operating System and OS version:Maos 10.14.1
* Other information:

**Comment by benfry** [comment]
That looks like you've deleted a file you should not have (the contributions file) and now it's broken. But really, this is a question for the [forum](https://discourse.processing.org), not here.
