### ISSUE TITLE
My code is suddenly in only one line

### ISSUE THREAD

**Issue by HenriSta** [processing/processing#5721]
## Description
When I pressed control-z to undo everything of my code was suddenly in one line.

## Steps to Reproduce
I copied the error message in a text file which I will attach to this issue.
[Error Processing.txt](https://github.com/processing/processing/files/2669200/Error.Processing.txt)

## Your Environment
* Processing version: 3.4
* Operating System and OS version: windows 10

## Possible Causes / Solutions
It is probably a bug in the code for the Processing i.d.e..

**Comment by jeremydouglass** [comment]
This can probably be closed ass a duplicate of #4775
