### ISSUE TITLE
png images do not keep transparency in P2D / P3D

### ISSUE THREAD

**Issue by b2renger** [processing/processing#5723]
## Description

When displaying a png image in P2D or P3D transparent areas are not kept. The expected behavior is observed when using other renderers (including FX2D).

## Current Behavior

Transparent areas are displayed with black pixels

## Steps to Reproduce

1. load a png image with transparent areas
2. display it using the classic renderer
3. display it using P2D or P3D

## Your Environment

 

* Processing version: 3.4
* Operating System and OS version: Mac OS - 10.13.1 and 10.12.6
* Other information:

**Comment by jeremydouglass** [comment]
I am not able to reproduce this behavior on Processing 3.4 with P2D or P3D -- the transparent png loads correctly.

```
size(512,512, P3D);
PImage img = loadImage("https://processing.org/img/processing3-logo.png");
background(255,0,0);
image(img, 0, 0);
```

**Comment by benfry** [comment]
Check out the paragraph on the [Troubleshooting](https://github.com/processing/processing/wiki/Troubleshooting) page that starts with “Objects with alpha”. That's probably what you're seeing.
