### ISSUE TITLE
IDE wrong link to FAQ

### ISSUE THREAD

**Issue by MyRaspberry** [processing/processing#5729]
## Description
in Processing IDE 3.4 
Menu / Help / Frequently Asked Questions /
links to :
https://wiki.processing.org/w/FAQ
ERROR 404
should be :
https://github.com/processing/processing/wiki/FAQ

## Environment
* Processing version: IDE 3.4
* windows 7  and Raspberry Pi Raspbian

**Comment by benfry** [comment]
Oops… that (and a couple others) have been wrong for a long time. I know folks don't like Help menus, but wow…
