### ISSUE TITLE
Drawing lines fails. No idea really, a floating point problem?

### ISSUE THREAD

**Issue by SDI2018** [processing/processing#5731]
## Description

Double Pendulum just disappears while processing code after x iterations.

Had my sweet little fun with:
https://www.youtube.com/watch?v=uWzPe_S-RVE&t=455s

## Expected Behavior
Well, it ain't over till..

## Current Behavior
Just stops drawing and the pendulum vanishes, only the lines remain

## Steps to Reproduce
Run my code for +20 seconds?

## Your Environment
Processing version 3.4 
on OS X 10.14.2

## Possible Causes / Solutions
no idea, runs fine until you set
float g = 8.5
that is the/one sweet spot

## Code

float r1 = 135;
float r2 = 300;
float m1 = 20;
float m2 = 20;
float a1 = PI/2;
float a2 = PI/2;
float a1_v = 0;
float a2_v = 0;
float g = 8.5; // breaks here!!!

float preX2 = -1;
float preY2 = -1;
float centerX, centerY;   

PGraphics canvas;

void setup() {
  
size(900,900);
centerX = width / 2;
centerY = height / 2;
canvas = createGraphics(width, height);
canvas.beginDraw();
canvas.background(255);
canvas.endDraw();
}
void draw(){
  float num1 = -g * (2 * m1 + m2) * sin(a1);
  float num2 = -m2 * g * sin(a1 - 2 * a2);
  float num3 = -2 * sin(a1 - a2) * m2;
  float num4 = a2_v * a2_v *  a1_v * a1_v * r1 * cos(a1-a2);
  float den = r1 * (2 * m1 + m2 - m2 * cos(2*a1-2*a2));
  
  float a1_a = (num1 + num2 + num3 * num4) / den;
  
   num1 = 2 * sin(a1 - a2);
   num2 = (a1_v * a1_v * r1 * (m1 + m2));
   num3 = g * (m1 + m2) * cos(a1);
   num4 = a2_v * a2_v * r2 * m2 * cos(a1-a2);
   den = r2 * (2 * m1 + m2 - m2 * cos(2*a1-2*a2));
  
  float a2_a = (num1 * (num2 + num3 + num4)) / den;
  
image(canvas,0,0);
stroke(0);
strokeWeight(2);

translate(centerX, centerY);

float x1 = r1 * sin(a1);
float y1 = r1 * cos(a1);

float x2 = x1 + r2 * sin(a2);
float y2 = y1 + r2 * cos(a2);

line(0,0,x1,y1);
fill(0);
ellipse(x1,y1,m1,m1);

line(x1,y1,x2,y2);
fill(0);
ellipse(x2,y2,m2,m2);

a1_v += a1_a;
a2_v += a2_a;
a1 += a1_v;
a2 += a2_v;

a1_v *= 0.999;
a2_v *= 0.999;

canvas.beginDraw();
canvas.translate(centerX, centerY);
canvas.strokeWeight(1);
canvas.stroke(0);
if (frameCount > 1) {
canvas.line(preX2, preY2, x2 , y2);
}
canvas.endDraw();

preX2 = x2;
preY2 = y2;
}

**Comment by Maharal** [comment]
there is nothing wrong with processing, this behavior can be minimized by adding the `dt` constant in your code.
```processing
float r1 = 100;
float r2 = 150;
float m1 = 20;
float m2 = 20;
float a1 = PI/2;
float a2 = PI/2;
float a1_v = 0;
float a2_v = 0;
float g = 8.5; // breaks here!!!
float dt = 0.1; // I add this constant

float preX2 = -1;
float preY2 = -1;
float centerX, centerY;

PGraphics canvas;

void setup() {

  size(600, 600);
  centerX = width / 2;
  centerY = height / 2;
  canvas = createGraphics(width, height);
  canvas.beginDraw();
  canvas.background(255);
  canvas.endDraw();
}
void draw() {
  float num1 = -g * (2 * m1 + m2) * sin(a1);
  float num2 = -m2 * g * sin(a1 - 2 * a2);
  float num3 = -2 * sin(a1 - a2) * m2;
  float num4 = a2_v * a2_v * a1_v * a1_v * r1 * cos(a1-a2);
  float den = r1 * (2 * m1 + m2 - m2 * cos(a1-a2));

  float a1_a = (num1 + num2 + num3 * num4) / den;

  num1 = 2 * sin(a1 - a2);
  num2 = (a1_v * a1_v * r1 * (m1 + m2));
  num3 = g * (m1 + m2) * cos(a1);
  num4 = a2_v * a2_v * r2 * m2 * cos(a1-a2);
  den = r2 * (2 * m1 + m2 - m2 * cos(a1-a2));

  float a2_a = (num1 * (num2 + num3 + num4)) / den;

  image(canvas, 0, 0);
  stroke(0);
  strokeWeight(2);

  translate(centerX, centerY);

  float x1 = r1 * sin(a1);
  float y1 = r1 * cos(a1);

  float x2 = x1 + r2 * sin(a2);
  float y2 = y1 + r2 * cos(a2);

  line(0, 0, x1, y1);
  fill(0);
  ellipse(x1, y1, m1, m1);

  line(x1, y1, x2, y2);
  fill(0);
  ellipse(x2, y2, m2, m2);

  a1_v += a1_a * dt;
  a2_v += a2_a * dt;
  a1 += a1_v * dt;
  a2 += a2_v * dt;

  a1_v *= 0.999;
  a2_v *= 0.999;

  canvas.beginDraw();
  canvas.translate(centerX, centerY);
  canvas.strokeWeight(1);
  canvas.stroke(0);
  if (frameCount > 1) {
    canvas.line(preX2, preY2, x2, y2);
  }
  canvas.endDraw();

  preX2 = x2;
  preY2 = y2;
}
```

**Comment by MLanghof** [comment]
The problem here is definitely not Processing but your mathematical approach. You are essentially integrating a differential equation with one of the simplest integration schemes: Explicit Euler (you are calculating acceleration and velocity only based on current status). This scheme can give nonsensical results ("diverge") because there are parameters for which it is unstable. The most important parameter for stability of explicit Euler is the time step.

@Maharal showed how to use a different time step than the one you are implicitly using (1). It appears that for your original time step choice, your approach leads to instabilities, with velocities flying off towards infinity and thus your variables eventually becoming NaN. Processing then won't draw any more lines (because you are not passing finite numbers as coordinates but not-a-number values).

**Comment by SDI2018** [comment]
Thank you both for clarifying on this!

I presumed there would be not math problem as i had tried some really weird setting before without running into problems.
I used to have fun with unrealistic velocity behavior of the Pendulum leading to interesting shutter effects. Especially if the velocity was not limited or slowed down at all.

Next time, i'll think twice before posting.
