### ISSUE TITLE
App not finding it's files

### ISSUE THREAD

**Issue by rickyardo1234** [processing/processing#5735]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by benfry** [comment]
Copy Processing.app to your Applications folder from the DMG. Outside of that, please use [the forum](https://forum.processing.org) for questions like this.

**Comment by rickyardo1234** [comment]
Thanks that worked and I will be in touch...

Have tried it before and I think it is a work of art...

Ricky
