### ISSUE TITLE
Processing "Could not get the settings folder"

### ISSUE THREAD

**Issue by JINCGames** [processing/processing#5744]
I recently installed processing 3.4 on windows 10. When I installed it, there was an error telling me to move the Processing folder to a different location. I did this attempted to launch it and then a popup screen came up:

![image](https://user-images.githubusercontent.com/38552500/50667068-5b0c7480-1003-11e9-96dd-27e50a300b99.png)

I have no idea what this means, could someone please help.

**Comment by Bobby54** [comment]
You probably moved Processing to a Folder or Position where it can't start.
If you move all Folders of Processing to e.g. your Downloads it might work out.

**Comment by benfry** [comment]
At the top of the error message, it lists two locations on your machine that it's trying to access to save the preferences file. In Windows, you'll need to check to make sure your account has permission to write to those locations.
