### ISSUE TITLE
Allow Processing to run on OSX using JDK > 1.8 by utilizing the new java.awt.desktop classes

### ISSUE THREAD

**Issue by ssilverman** [processing/processing#5746]
## Description
`processing.core.ThinkDifferent` should use the `QuitHandler` from the newer `java.awt.desktop` package in addition to `com.apple.eawt.QuitHandler`. Some adapter code could be written that allows this to run on all JDKs, without explicitly removing `com.apple.eawt.QuitHandler` support.

## Expected Behavior
Allow Processing to work on OSX beyond JDK 1.8, while still keeping compatibility.

## Current Behavior
Only works on JDK 1.8 and below.

## Steps to Reproduce
Run any Processing app on JDK > 1.8.

## Your Environment
* Processing version: 3.4
* Operating System and OS version: macOS 10.14.2
* Other information:

## Possible Causes / Solutions
Better cross-platform support was added for "desktop" apps and this removed some of the Apple-specific classes in favour of JDK-provided ones.

**Comment by ssilverman** [comment]
The pull request: #5747.

**Comment by benfry** [comment]
Fixed with https://github.com/processing/processing4/pull/1 and continued development happening at https://github.com/processing/processing4
