### ISSUE TITLE
Initializing textures loads the pixels array, even if not needed aferwards

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#5748]
When the OpenGL renderer initializes the Texture object that caches a PImage, it loads the image's pixels to copy the current bitmap into the OpenGL texture, [here](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L6415). But if the PImage is not using the pixels array to begin with, this results in a bunch of potentially large pixels arrays taking up memory, even if they are no longer used. So, of the pixels array is null before setting the texture, it should be made null again at the end to avoid extra memory consumption.

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing/commit/869da8c52e5a87589ca707fd4d1629fff7a71d07 and https://github.com/processing/processing/commit/a0f7665edd4e7b354eede9c4bc011deda8bbe947

**Comment by JakubValtar** [comment]
Good idea. When does it happen though that you want to draw an image with null pixels and no texture? When the image is a non OpenGL renderer?

**Comment by codeanticode** [comment]
I believe this should have no effect outside the OpenGL renderer. Images in the OpenGL renderer always have a backing texture, or at least they should :-), so if the pixels array is null, it's initialized temporarily so it can be used to copy the image contents into the texture buffer, after which is turned into null again. If this has an unintended consequence or generates a regression, please let me know!

**Comment by JakubValtar** [comment]
Ok, I guess the use case would be that you create the image only as a handle for a texture, and then you update the texture directly (e.g. Spout library works like this I think).

**Comment by codeanticode** [comment]
In that case this optimization should have no effect, shouldn't it? Have you tried Spout with 3.5.1? Does it work as expected?
