### ISSUE TITLE
Where are the java options set?

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#5755]
Where are the java options set, for example the option to enable assertions?
Normally assertion checking is off by default in java, but in Processing it is on by default.
At the moment I’m using a library that has some heavy assertion checking slowing things down and I would like to turn it off.

Run this to see that `-ea` is indeed enabled in processing by default:
```
assert false : "ouch";
```

**Comment by jeremydouglass** [comment]
linked discussion: https://discourse.processing.org/t/where-are-the-java-options-set/7076

**Comment by benfry** [comment]
Changing `run.options` in `preferences.txt` should do the trick.

Faux documentation can be seen in [defaults.txt](https://github.com/processing/processing/blob/master/build/shared/lib/defaults.txt).
