### ISSUE TITLE
Ctrl+/ not commenting out selection

### ISSUE THREAD

**Issue by Ghoelian** [processing/processing#5763]
## Description
`Ctrl+/` not commenting out selection.
Also, I just noticed that in the Edit tab, it lists the keybind as `meta+/`.

## Expected Behavior
On `ctrl+/` the selected text, or the current line, should be commented out.

## Current Behavior
Nothing happens on `ctrl+/`.

## Steps to Reproduce
Literally just press `ctrl+/` in the PDE.

## Your Environment
* Processing version: 3.5.1
* Operating System and OS version: Windows 10 Pro, build 1803

**Comment by Ghoelian** [comment]
## Additional notes
It might be nice to be able to change the keybindings ourselves.

**Comment by benfry** [comment]
Nuts. That's a regression from [this fix](https://github.com/processing/processing/issues/2199) which was implemented to allow users to specify better shortcuts on a per-locale basis. Unfortunately it's not translating the shortcuts correctly between the Mac (where meta is used), vs Windows and Linux (where ctrl is used). I'll fix and get an update out shortly.

**Comment by benfry** [comment]
Fixed for 3.5.2.
