### ISSUE TITLE
About Processing 4

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5771]
Hello,

In advance excuse my french, oops my english, because it's very weird for a mother talker :)
I don't know if it's a good place to post it... so in the doubt i do it.

I read you need help in https://github.com/processing/processing/wiki/Processing-4. I'm a Processing user and I hope one day can help deeply Processing Foundation not just make a critic or feedback. Actualy I try to understand how to the pullrequest work. I hope soon to manage that. but in time I can give my feedback on the huge road map of Processing 4 ; few thing resonate for me ?

# vector
You wan move or change PVector for new Vector class, I made my own Vector class inspired from `PVector` and from `vec`of `GLSL` like that : `Vec2` `Vec3` `Vec4` `Vec5` `Vec6` plus `iVec2` `iVec3` `iVec4` `iVec5` `iVec6` and `bVec2` `bVec3` `bVec4` `bVec5` `bVec6` with all PVector operation from `Vec2` to `Vec4` the `Vec5` and `Vec6` it's storage Vec.
see the src of my lib https://github.com/StanLepunK/Rope/tree/master/src/rope/vector

 I adapte too all Processing Method that I can ; like `point(Vec2)` `point(Vec3)` `vertex(Vec2)`
see 
https://github.com/StanLepunK/Rope_method/blob/master/Rope_method/Z_Rope_Processing_Method.pde
 
plus add my own util method
https://github.com/StanLepunK/Rope_method/blob/master/Rope_method/Z_Rope_Vector_method.pde

I do a traduction of usual GLSL method to compare the Vector and other helpful
https://github.com/StanLepunK/Rope_method/blob/master/Rope_method/Z_Rope_glsl_method.pde

Maybe that's can be a source of inspiration ?

# surface 
You write about `surface` if people use it. I use it a lot for change the window size and position.

# openGL
there is idea to change JOGL to LWGL, sure that's can be good. there is a plan to add the `ambient occlusion` this type of light can be very very a big step if it's possible, the result is very simple and beautifull.

# aspect
You write about `aspect()` not like you imagine, but interesting.  method for me is `aspect(int fill, int stroke, float strokeWeight)`to manage easily the `fill()``stroke()`and `strokeWeight()` it's very helpful to swich when there alpha fill is 0, to use `noFill()`for example.

# costume
I code a method helpfull too is `costume()`use like that `costume(Vec pos, Vec size, int which_costume)`after the method can select the shape automaticly between available one, like `ellipse``rect``box``sphere`... and the method detect if the rendering if `P2D`or `P3D` and if the user ask for a pshere, an allipse is displaying and the consol show warning to explain what for !

Et voilà, I hope that's can help a little, and i'm available to help any time I can !

**Comment by benfry** [comment]
Thanks; will keep these in mind.

**Comment by StanLepunK** [comment]
I have project to improve my different class Vector are you interested I create a Processing Branch for that ? If yes, the name i want use is like GLSL > `vec#`,` ivec#`, `bvec#` or your prefere something like `Vec#`, `Ivec#` and `Bvec#`, or `Vec#`,` IVec#`, `BVec#` like classic naming class ? my preference if make something like GLSL, that's can be good for the bridge with the shader i think and it's more elegent when it's write :) Plus I want add the better method from toxilib too. Keep me in touch.
