### ISSUE TITLE
Behavior of ceil()

### ISSUE THREAD

**Issue by STPR** [processing/processing#5772]
## Description

```
int a = 5;
int b = 2;
int n = ceil(a / b);
print(n);
```
**This code return 2.**

```
float a = 5;
float b = 2;
int n = ceil(a / b);
print(n);
```
**This code return 3.**
## Expected Behavior

Both codes should return 3.

## Your Environment

 

* Processing version:
3.5.2
* Operating System and OS version:
Windows 10 Home (Build 1809)

**Comment by STPR** [comment]
```
int a = 5;
int b = 2;
int n = ceil(a / b);
print(n);
```
**This return 2.**

While:
```
float a = 5;
float b = 2;
int n = ceil(a / b);
print(n);
```
**Return 3.**

Is this normal ? I would expect both results to be the same (3)

**Comment by benfry** [comment]
You're probably familiar with JavaScript, or another language that works that way. Java handles types differently, and an `int` is never converted to a `float`. More here: https://github.com/processing/processing/wiki/Troubleshooting#why-does-2--5--0-instead-of-04

**Comment by STPR** [comment]
Since ceil is asking for a float as parameter, i would have expected it to float every integers...
```
int a = 5;
int n = ceil(float(a) / 2);
print(n);
```
**This code return 3:**

So 2 has been treated as a float while it's an integer.

Why not treating every integers variables as float ?
I'm not asking to change the language behavior, just one command...
