### ISSUE TITLE
Redo assigned to meta-Y instead of ctrl-Y in 3.5.2 on Windows

### ISSUE THREAD

**Issue by abelaaa** [processing/processing#5773]
## Description
Redo not working with CTRL+Y and Meta+Y is just uncool, as not many of the devices i know have it. 🤔

## Expected Behavior
For it to redo an action undone.
Would be cool to have it work with Ctrl + Y as before. Or at least have the option to go back to CTRL+Y

## Current Behavior
CTRL + Y doesn't seem to do anything now. And there is no option to remap it to a different key combination.

## My Environment
Processing 3.5.2
Windows 10 [x64] - 1803 update

4: 6:31 WY

![image](https://user-images.githubusercontent.com/17273174/51786685-d253a500-2178-11e9-8f3e-535c7aea3274.png)

**Comment by benfry** [comment]
Agh, it's a typo in the languages file.

Until I can post 3.5.3, you can add this line to `preferences.txt` and it'll work properly:
```
menu.edit.redo.keystroke.windows = ctrl pressed Y
```

**Comment by benfry** [comment]
Fixed for 3.5.3.
