### ISSUE TITLE
The package “META” does not exist. You might be missing a library.

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#5778]
OSX 10.12.6
Processing 3.5.2

I try to use the library byte-buddy, which I assume is well written cause the creator received the  Duke's Choice award by Oracle.

The library is Located here:
https://mvnrepository.com/artifact/net.bytebuddy/byte-buddy/1.9.2

In VSCode it works fine but now I want to use it in processing.
When dragging it on a sketch and then running I get:

> The package “META” does not exist. You might be missing a library.

I unzipped the jar and looked for “META” all I founded is:

`<manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>`

But there are a lot of binary files.

I have a suspicion that this is wrong on the processing site and things "META" might need to be skipped or something.

I wan't to look later in the issue but I need descent internet first to download the source of processing.

**Comment by benfry** [comment]
It's because there's a `.class` file inside the `META-INF` directory. (Not sure that's legal?) 

When it tries to automatically determine the imports, it's trying to include that. But we should skip `META-INF` anyway, so I'll just add a check for it.

**Comment by benfry** [comment]
Added a workaround for 3.5.3.

**Comment by clankill3r** [comment]
@benfry I looked a bit into it.

The file, as you know was `module-info.class`, this is a thing of java 9.
From somewhere else:

> Right, thanks. We've seen problems even when the main .class files are compiled for an older version but the module-info.class is present. As I understand it, various tools try to process all .class files, and they need to be updated to ignore module-info.class.

So it seems like you fixed a bug
