### ISSUE TITLE
Ctrl-space code completion has stopped working on MacOS

### ISSUE THREAD

**Issue by grandbander** [processing/processing#5780]
## Description
Code completion has stopped working with the latest version on MacOS. 

## Expected Behavior
When enabling Ctrl-space code completions and hit Ctrl-space, completions show up.

## Current Behavior
I have enabled Ctrl-space and no list of completions come up.

## Your Environment
* Processing version: 3.5.2
* Operating System and OS version:  MacOS 10.13.6
* Other information:  

## Possible Causes / Solutions
It worked with 3.4.
I also enabled pdex.completion.trigger=true and still no completion.

**Comment by benfry** [comment]
Hm, working fine here: 

<img width="740" alt="screen shot 2019-01-30 at 9 16 43 am" src="https://user-images.githubusercontent.com/1623101/51987223-f7ddf880-246f-11e9-9a76-b958ea805830.png">

To reset the behavior, I also just did this and it turned on just fine:

1. Quit Processing
2. Rename ~/Library/Processing/preferences.txt to something else
3. Restart Processing
4. Open the Preferences window and enable code completion
5. Code completion working again
