### ISSUE TITLE
Sketch window resets position

### ISSUE THREAD

**Issue by cdaein** [processing/processing#5781]
## Description

While running a Processing sketch, move the window to somewhere on screen, re-run it - the window always resets itself to the center of screen. Version 3.4 downloaded from the website does not have this issue.

## Expected Behavior

The sketch window should remember the last position and be displayed there when re-running the sketch.

## Current Behavior

The window always resets itself to the center of screen, blocking the code editor window.

## Steps to Reproduce

1. run a sketch.
2. move the sketch window to someplace else.
3. stop the sketch and re-run it.
4. the window resets to the default position.

## Your Environment

 

* Processing version: 3.5.2
* Operating System and OS version:
* Other information:

**Comment by benfry** [comment]
What OS and version are you using?

**Comment by cdaein** [comment]
Sorry I forgot to mention it.
MacOS 10.14.2 (Mojave)

**Comment by benfry** [comment]
That's odd… I don't think anything has changed in that code.

**Comment by abelaaa** [comment]
It happens on Windows too actually.

**Comment by minipif** [comment]
Version 3.5.3 and 3.5.4 have the same problem. Version 3.4 doesn't.

MacOs version: Catalina 10.15.2

**Comment by REAS** [comment]
This is happening for me as well 3.5.3 on OS X 10.14.6. I didn't notice when it started, unfortunately.

**Comment by jeremydouglass** [comment]
Can confirm *not* happening in 3.4 on 10.12.6

**Comment by benfry** [comment]
Found and fixed for 4.0 alpha 4: https://github.com/processing/processing4/issues/158
