### ISSUE TITLE
Error message is helpful but incomplete.

### ISSUE THREAD

**Issue by molecule** [processing/processing#5784]
## Description
As of [Nov 2016](https://github.com/processing/processing/issues/4738), processing [detects a host file whose configuration](https://github.com/processing/processing/issues/3123) will cause problems. The error message is:
"processing cannot run due to changes in your hosts file"

Processing very helpfully warns the user that their hosts file is configured incorrectly but gives no indication what the correct configuration is. Also, the hosts file has this line:

  4 # localhost is used to configure the loopback interface
  5 # when the system is booting.  Do not change this entry.
  
Which would seem to contraindicate any editing of the localhost file. It would be nice if the error message could show an example of a correct hosts file.

## Steps to Reproduce
Here's my original host file:

  2 # Host Database
  3 #
  4 # localhost is used to configure the loopback interface
  5 # when the system is booting.  Do not change this entry.
  6 ##
  7 127.0.0.1       <comp name>
  8 255.255.255.255 broadcasthost
  9 ::1             localhost

Adding this below the last line made it work:

10 127.0.0.1             localhost

## Your Environment
* Processing version: 3.5.3
* Operating System and OS version: Mac 10.11.6

## Possible Causes / Solutions
Show an example of a correctly configured host file.

**Comment by benfry** [comment]
Nah, telling people what “correct” is for their hosts file isn't something we should be responsible for telling users. That's just way too far from something that Processing, as a piece of software on your machine for creating interactive graphics, should be doing. 

The message is there to say “You screwed up your hosts file. It's up to you to undo that mess, whatever it may have been.” There are too many possibilities.
