### ISSUE TITLE
Run button doesn't appear deactivated after window is closed

### ISSUE THREAD

**Issue by AbelWondafrash** [processing/processing#5786]
## Description
Run button stays on after window is closed. Either with exit(), manually closing (X). 'anything' but the stop button seems to not stop it from appearing on. Not much of a big deal but, would be less vague to see it fixed especially when you have the surface.setVisible(false); and something is running in the background but is expected to exit() after sometime.

## Your Environment
Windows 10 #1803 Update [x64 bit]
Processing 3.5.3

**Comment by benfry** [comment]
Yeah, thought I saw that as well. Is this a new issue that you've just seen recently, or have you tried it with 3.4 or any others?

**Comment by abelaaa** [comment]
> Yeah, thought I saw that as well. Is this a new issue that you've just seen recently, or have you tried it with 3.4 or any others?

Didn't happen with 3.4 or the former releases. It started with 3.5.2 and now on3.5.3.
Tested it on (3.0.2, 3.3.6, 3.3.6, 3.3.7 & 3.4). Works on all.

**Comment by benfry** [comment]
Thanks; that's what I suspected.

**Comment by neilcsmith-net** [comment]
Just to say, in case it's useful, that there's the same issue on Ubuntu 18.04 so it's not Windows / OS specific.

**Comment by Sardtok** [comment]
Also happens in OS X, so it's definitely general.

**Comment by benfry** [comment]
Just checked and this is working fine with 4.0 beta 6. I think this was caused by other regressions with window placement that happened between 3.4 and 3.5.
