### ISSUE TITLE
 video Capture example code fails:       Video Capture.list() does not exist.   

### ISSUE THREAD

**Issue by TPMoyer** [processing/processing#5787]
Copied the example code from the processing Capture page 
[https://processing.org/reference/libraries/video/Capture.html](https://processing.org/reference/libraries/video/Capture.html) 
into Capture.pde       Downloaded the video library and tried to run code.  
red error message appeared:    

The function list() does not exist. 

Environment is:
 Processing 3.5.3  
 Library:   Video 1.0.1   The Processing Foundation     GStreamer-based video library for Processing.

Same fail on Raspberry PI and Windows64 platforms.
Specifics are:
 Raspbian GNU/Linux 9 (stretch) with recent runs of sudo apt-get update   and sudo apt-get upgrade
 Windows64 ver 6.1.7601 platforms. 
Both platforms have the DashedLines 0.0.3 library installed, and both platforms have multiple other sketches functioning.

**Comment by benfry** [comment]
Please file this over here: https://github.com/processing/processing-video/issues
