### ISSUE TITLE
LoadTable breaks if if finds a newline in a csv cell

### ISSUE THREAD

**Issue by Jesse-McDonald** [processing/processing#5790]
## Description
If a csv contains a new line in a cell inside quotes it is loaded as several tableRows instead of 1 table row
consider the csv
`name,description
person,"Hi I am a person.
Are you a person"
person2,"yes"`
rather than being processed as 2 lines and a header, it will be processed as 3 lines, one of which has 1 column rather than 2

## Steps to Reproduce
1.open csv with a multi line cell (like the one above)
2.try to process each row and watch your program crash

## Possible Causes / Solutions
The csv parse likely runs .split("/n") on the file before any other action, rather than doing that, it should scan character by character and track if it is inside of "" or not before processing /n (note it already has this behavior for commas in cells)

**Comment by benfry** [comment]
Pass `newlines` as one of the options to `loadTable()`. It's not enabled by default because this situation is rare and makes parsing far slower.

**Comment by Jesse-McDonald** [comment]
ok, thank you, that should work fine
