### ISSUE TITLE
Processing 3.5.3 running slow and crashing.

### ISSUE THREAD

**Issue by sr05110421** [processing/processing#5793]
## Description
Recently, I installed Processing 3.5.3 on my computer. Whenever I run any code, the software freezes, and prevents me from typing, and closing the software. I've tried both 64 and 32 bit versions of Processing 3.5.3. In addition, the software runs very slowly, and takes a while to open.

## Expected Behavior
I'd like it so that I can use the software correctly. Being able to run and save code, and the software being much faster to open, and use.

## Steps to Reproduce
I'm not sure how to reproduce this, as all I've done is install and run the software. I've been trying to diagnose it myself for about 2 or 3 days to no avail.

## Your Environment
* Processing version: 3.5.3, 64 bit (I've also tried the 32 bit version) 
* Operating System and OS version: Windows 10, 64 bit.
* Other information: The software is running on a school network, but on an account administrator privileges.

**Comment by benfry** [comment]
There's nothing here that I can possibly use to figure out where the problem might be. If you've already read the troubleshooting page, then I'd see about getting help at https://discourse.processing.org/ in case someone has ideas for what might be happening.

**Comment by sr05110421** [comment]
Thanks for the help!
