### ISSUE TITLE
pop() and push() function doesn't work 

### ISSUE THREAD

**Issue by sonuKumar03** [processing/processing#5795]
## Description

Function push() and pop() not exit in my Java Mode of Proceesing
![screenshot from 2019-02-15 15-33-55](https://user-images.githubusercontent.com/45958357/52849892-262e2a00-3138-11e9-88a9-d5b0cf37119a.png)

**Comment by GRsni** [comment]
Which Processing version are you using? Are you sure it's 3.5.3?

**Comment by StanLepunK** [comment]
I see you're in Processing 3.4 in my mail box, that's not appear here. So it's normal, update you're Processing and that's work fine after that.

**Comment by Bobby54** [comment]
It is called 
pushMatrix();    and
popMatrix();

Then it should work out.

**Comment by GRsni** [comment]
In 3.5.3 push() and pop() where added. They combine pushMatrix() and pushStyle() in a single function.

**Comment by benfry** [comment]
`push()` and `pop()` require 3.5.3, which the original poster seems to not have been using. Closing this thread…
