### ISSUE TITLE
Compile processing with a -sources.jar

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#5798]
How can processing be compiled in such a way that it creates the `core-sources.jar`?
I find this help full when it comes to debugging, but I'm stuck to `3.3.7` now since that is the only version I could find the source files jar from.

**Comment by cluder** [comment]
This is how i created a core.jar, which includes the source.
```ant
diff --git a/core/build.xml b/core/build.xml
index 0b82eba..79bedc2 100644
--- a/core/build.xml
+++ b/core/build.xml
@@ -50,6 +50,7 @@
 	   encoding="UTF-8"
 	   includeAntRuntime="false"
 	   debug="true"
+        debuglevel="lines,vars,source"
 	   destdir="bin"
 	   classpath="apple.jar; 
                       library/jogl-all.jar; 
@@ -72,6 +73,7 @@
         <include name="processing/opengl/shaders/*.glsl" />
         <include name="processing/opengl/cursors/*.png" />
         <include name="icon/*.png" />
+      	<include name="**/*.java" />
       </fileset>
     </copy>
   </target>		

```

**Comment by cluder** [comment]
But a new ant target, which creates a separate source-jar would probably be the cleanest.

**Comment by clankill3r** [comment]
I can't get it to work. Any help is still welcome, I'm stuck on using 3.3.7 now for ages.

**Comment by clankill3r** [comment]
(A note for myself)
git clone --branch processing-0269-3.5.3 --depth 1 https://github.com/processing/processing
git checkout tags/processing-0269-3.5.3

**Comment by cluder** [comment]
i built a new jar, with the changes mentioned before: https://github.com/cluder/processing-examples/blob/master/lib/core.jar, you cant try this if you want.
This core.jar includes the sources too.
I might try to add a new ant target later, which builds the sources jar optionally.

**Comment by clankill3r** [comment]
@cluder 

I found a way to get it:

In `processing/core/build.xml`:
Change the last target to:

```
<target name="build" depends="compile" description="Build core library">
    <jar basedir="bin" destfile="library/core.jar"> 
    </jar>
    <jar basedir="bin" destfile="library/core-sources.jar"> 
      <fileset dir="src" includes="**/*.java"/>
    </jar>
  </target>
```

**Comment by clankill3r** [comment]
Ok, not sure if this was possible before but this works out of the box:

```
cd core
ant source-jar
```

**Comment by benfry** [comment]
Yeah, added in 4.0 alpha 3 and in the release notes:

* You can now create a “source” `.jar` file by typing `ant source-jar` inside the `core` directory. [118](https://github.com/processing/processing4/issues/118)
