### ISSUE TITLE
Sketch not running on P2D and P3D

### ISSUE THREAD

**Issue by joogps** [processing/processing#5802]
## Description

I'm trying to add some 3D shapes to the Processing Build (from source code) 0270, but, apparently, the sketch won't run when specifying the renderer as P2D or P3D. 

**Note**: FX2D does work on Build 0270 and all renderers are working on Processing 3.5.3.
**Note 2**: No changes were made in the source code before building.

## Expected Behavior

![Processing-3.5.3](https://user-images.githubusercontent.com/41346220/53304609-042e5900-3856-11e9-8f1d-a920cddd8c94.PNG)
![P2D-Processing-3.5.3](https://user-images.githubusercontent.com/41346220/53304563-9d10a480-3855-11e9-8e2c-8120ac770528.PNG)
![P3D-Processing-3.5.3](https://user-images.githubusercontent.com/41346220/53304560-971ac380-3855-11e9-9d7e-a414a522c9d1.PNG)

## Current Behavior

![Processing-Build-0270](https://user-images.githubusercontent.com/41346220/53304622-258f4500-3856-11e9-92e8-6e47c9e2a8e4.PNG)
![P2D-Processing-Build-0270](https://user-images.githubusercontent.com/41346220/53304575-b74a8280-3855-11e9-9500-81fff8890e40.PNG)
![P3D-Processing-Build-0270](https://user-images.githubusercontent.com/41346220/53304576-b87baf80-3855-11e9-8f57-705c479ad5e6.PNG)

## Code
```processing
void setup() {
	size(640, 640, RENDERER);
}
``` 

## My Environment

 

* Processing version: Build 0270 and 3.5.1
* Operating System and OS version: Microsoft Windows 8 Enterprise

**Comment by Bobby54** [comment]
Have you already tried to update your processing Version?

**Comment by joogps** [comment]
I think there were no build versions since I encountered the issue...

**Comment by Bobby54** [comment]
You said you were running processing 3.5.1, but there is already version 3.5.3.

**Comment by joogps** [comment]
oh! it was a typo... thanks for warning!

**Comment by chollaaa** [comment]
same problem, @joogps  do you fix it now?
my environment: win10 CPU:i7 Graphic card:RTX2080
processing 3.0.1   3.3.6   3.5.3 all could not open P2D/P3D sketch, 2.2.1 is ok.
btw, just after the system re-install, the P2D/P3D sketch could open, but after two days, now it can't...

**Comment by joogps** [comment]
I don't even remember LOL

**Comment by benfry** [comment]
You may need to turn off your virus scanning software. Overly aggressive virus scanners on Windows are sometimes removing OpenGL files (or preventing their use) while sketches are launched.

**Comment by foong** [comment]
hello there, having the same issue on RTX 2060, disabled firewall and still same results, any suggestions?
