### ISSUE TITLE
Open a non-main pde file as first tab.

### ISSUE THREAD

**Issue by SanielDan** [processing/processing#5804]
I'm trying to create a program that can open a  .pde file from a Processing project in the Processing editor.
After many researches, I found no way to do this.
Now every .pde file that I'm trying to open redirect to the main .pde file of the  project.
I think it would be nice if the processing editor could open directly the selected file, or at least have some command line options to do this.

My Environment:
Processing version: 3.5.3
Operating System: Windows 10 Pro

**Comment by benfry** [comment]
Yeah, that's just not how the PDE works. I'd definitely recommend using a Java IDE if you want more flexibility.
