### ISSUE TITLE
Looking for a fix! The console is showing special characters instead of normal characters. 

### ISSUE THREAD

**Issue by ExtraStressTrial** [processing/processing#5808]
I've reinstalled and updated Processing many times, but it doesn't do anything. I ran out of solutions.

![image](https://user-images.githubusercontent.com/48315327/53946742-465c6380-40bc-11e9-8979-07f3e4fc6e02.png)

**Comment by StanLepunK** [comment]
You need to pass your environment : OS, computer, Processing version to have an idea of the bug. By the way that's work fine on OS Mojave / macbook pro / Processing v270.

**Comment by Gerardo-Sanchez** [comment]
I have the same problem. Can you explain it more please? I really don't understand.

**Comment by ExtraStressTrial** [comment]
> I have the same problem. Can you explain it more please? I really don't understand.

I managed to fix it. You don't need to re-install or reset your computer. The default font had some compatibility issues with Windows 10, so I changed the font.

![image](https://user-images.githubusercontent.com/48315327/55200676-1f72e800-51b7-11e9-9423-1d1b91f8f4da.png)

**Comment by Gerardo-Sanchez** [comment]
Oh thank you so much! 
You have no idea how much I appreciate your help.
