### ISSUE TITLE
sketches won't run, no error messages

### ISSUE THREAD

**Issue by cshallenberg** [processing/processing#5811]
## Description

Sketches won't run.

## Expected Behavior

Sketches to run as normal.

## Current Behavior

No sketch will run. No error messages. When pressing the Run button, it engages as though the sketch were running, but no sketch window appears. I deleted and re-installed Processing, moved the sketch folder, deleted the preferences.txt file. 

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version: 3.5.3
* Operating System and OS version: Mac OS 10.13.6
* Other information: The only major change I made to my system was to set up a password protected ad hoc network using Loopback. I ran the following commands in terminal:
sudo networksetup -createnetworkservice Loopback lo0
sudo networksetup -setmanual Loopback 172.20.42.42 255.255.255.255
Then set up internet sharing over wifi through Loopback. Now no sketch will run even with internet sharing turned off.
I have also been using Syphoner to use the sketch as a source in Isadora, but this has been working fine up until today.

**Comment by jeremydouglass** [comment]
see: https://github.com/processing/processing/issues/5784

**Comment by benfry** [comment]
I can't help untangle networking issues on your machine that have broken the software… This isn't a Processing bug, it's probably hanging because you've broken how loopback is working.
