### ISSUE TITLE
offset are wrong

### ISSUE THREAD

**Issue by MauroMombelli** [processing/processing#5813]
## Description
Does not seems to happen in Windows; does happen in plasma:
if i try to translate for window width and draw a circle, the circle is not perfectly centered: it seems processing does not take into account for window border

## Expected Behavior
The circle is cut perfectly

## Current Behavior
there is an odd cut

## Steps to Reproduce

```
void setup(){
  size(500,500);
}
int size = 100;
void draw(){
  background(0,255,0);
  translate(0,height);
  //scale(1,-1);
  pushMatrix();
  translate(0,-size);
  strokeWeight(0);
  ellipseMode(CENTER);
  ellipse(0,0,size*2,size*2);
  popMatrix();
}
```

## Your Environment
* Processing version: Processing 3 (0269 ?)
* Operating System and OS version: Arch linux
* Other information: does not happen in windows

![image](https://user-images.githubusercontent.com/6372561/54074207-fdf59f00-428f-11e9-9b12-ef0993b86a55.png)

**Comment by jeremydouglass** [comment]
Cannot reproduce on macOS 10.12, Processing 3.4. When I run your code, the bottom of the circle is aligned with the bottom of the window.

**Comment by benfry** [comment]
It's a problem w/ your window manager; there are only so many of these we can account for since Linux doesn't consistently give us good window geometry.
