### ISSUE TITLE
I can't save

### ISSUE THREAD

**Issue by FlamingFireHand** [processing/processing#5819]
## Description

I can't save my programs.

Whenever I try to save my program (using the file tab and then selecting save/save as), it displays an error message that says the folder directory and then:"File not found. Check the file name and try again."

## Expected Behavior

I expected it to save with the name that I gave it.

## Current Behavior

It displays an error message whenever I try to save a program.

## Steps to Reproduce

1.Write any code (it can even be blank).
2.Go to the files tab and click on Save/Save as...
3.Enter any name (you don't have to change it).

## Your Environment

 

* Processing version:3.5.3
* Operating System and OS version: Windows 10
* Other information:

## Possible Causes / Solutions

No idea.

**Comment by Bobby54** [comment]
Could you send examples of the names you are trying to give your scetches?

**Comment by FlamingFireHand** [comment]
It doesn't matter what the names are. It has normal letters, no numbers/spaces/other.

**Comment by Bobby54** [comment]
You say your step three to reproduce was to give it any name to save.
But you have to select a folder under which you want to save it. That means you don't type in the name you want to name your project with but the folder name in which you want to save it.

**Comment by Bobby54** [comment]
I've just tried it and everything works fine for me.
Have you changed any settings for processing or on your computer? This could lead to the error message if e.g. your system settings don't allow you(or processing) to save in the folder you are trying to.
Also, are you the admin of the device or is an other user the admin?
Or are you trying to save the sketches in a place where the system generally doesn't allow you to save?

**Comment by FlamingFireHand** [comment]
I haven't changed any settings that I know of and I am the admin of my computer. I used to be able to save my sketches but now I can't.

**Comment by FlamingFireHand** [comment]
I am currently redownloading processing. I will let you know how it went.

**Comment by FlamingFireHand** [comment]
It saves! Thank you for trying to help me with my problems.
