### ISSUE TITLE
Build failed: JDK 8u202 required

### ISSUE THREAD

**Issue by whykatherine** [processing/processing#5827]
## Description

First time contributor! Tried to build source code on my local machine according to the [instructions](https://github.com/processing/processing/wiki/Build-Instructions) but failed when running `ant run`.

## Expected Behavior

Expected source code to build.

## Current Behavior

Getting this error when trying to build.
```
BUILD FAILED
/Users/kathey/Documents/code/processing/build/build.xml:308: The following error occurred while executing this line:
/Users/kathey/Documents/code/processing/build/build.xml:518: JDK 8u202 required.
To build on OS X, you must install Oracle's JDK 8u202 from
http://www.oracle.com/technetwork/java/javase/downloads
Or... type 'ant download-jdk-macosx' to download it to your Desktop.
Note that only 8u202 (not a later or earlier version) will work. 
And it must be the JDK, not the JRE. And do not try to defy me again.
```

## Steps to Reproduce

1. Clone source repository.
2. Navigate to Processing directory.
3. Type:
```
cd build
ant run
```

## Your Environment

 

I am on macOS 10.14.3. I successfully downloaded JDK from [here](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html). When typing `java -version` into the command line, I get:
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

## Possible Causes / Solutions

I'm not sure if JDK 8 downloaded successfully, or if there are multiple versions of Java installed and the system isn't finding JDK 8. How can I fix this issue?

**Comment by whykatherine** [comment]
Forgot to add that I also tried to run `ant download-jdk-macosx` as the message suggests, which gives me:
```
download-jdk-macosx:
[downloader] Redirecting to https://edelivery.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-macosx-x64.dmg
[downloader] Redirecting to http://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-macosx-x64.dmg?AuthParam=1553809146_039d7908a3e7b8a1fc4fabe7d7a175e1
[downloader] Redirecting to https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-macosx-x64.dmg?AuthParam=1553809146_039d7908a3e7b8a1fc4fabe7d7a175e1
[downloader] Downloading /Users/kathey/Desktop/jdk-8u202.dmg from https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-macosx-x64.dmg?AuthParam=1553809146_039d7908a3e7b8a1fc4fabe7d7a175e1

BUILD SUCCESSFUL
```

However, running `ant run` again after this still gives me the same error about JDK 8u202.

**Comment by kevin51jiang** [comment]
From what I can see, you installed java version `8u201`, but the compiler wants `8u202`.

Make sure you're getting the version installed (scroll down on that same webpage) and try it again.

**Comment by benfry** [comment]
After downloading `jdk-8u202.dmg`, you have to install it. And having done that, open a new Terminal window, which will hopefully pick up 202 as the most recent (and correct) version to use.

**Comment by whykatherine** [comment]
@kevin51jiang You're right! I must have downloaded 8u201 without seeing 8u202 lower down on the page. @benfry I checked again and it works now! Thanks all for the help!

**Comment by benfry** [comment]
For anyone finding this issue because of problems with the build script… Oracle now requires a user account and login for download Java releases, which breaks the build.

You'll need to manually install Java 8u202 from [this page](https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html) in order to build Processing. On macOS, download the JDK. On Windows and Linux, only the JRE is required. But it must be version 8u202.

**Comment by benfry** [comment]
Now fixed as of https://github.com/processing/processing/commit/89a080814895234b54201c0240625e47a5b369cf
