### ISSUE TITLE
rename-variable dialog doesn't allow 1st-char underscore

### ISSUE THREAD

**Issue by digimeas** [processing/processing#5828]
Hi!

When using the right-click rename variable function, trying to use an underscore as first character results in a "Barbie" message of "Naming is Hard"/"_xxx is not a valid name"

Processing 3.5.2

Thanks
Doug

Edit:
It seems that in java/src/processing/mode/java/pdex/Rename.java
```
   JButton renameButton = new JButton("Rename");
    renameButton.addActionListener(e -> {
      final String newName = textField.getText().trim();
      if (!newName.isEmpty()) {
        if (newName.length() >= 1 &&
-            newName.chars().limit(1).allMatch(Character::isUnicodeIdentifierStart) &&
-            newName.chars().skip(1).allMatch(Character::isUnicodeIdentifierPart)) {
+            newName.chars().limit(1).allMatch(Character::isJavaIdentifierStart) &&
+            newName.chars().skip(1).allMatch(Character::isJavaIdentifierPart)) {
          rename(ps, binding, newName);
          window.setVisible(false);
        } else {
          String msg = String.format("'%s' is not a valid name", newName);
          JOptionPane.showMessageDialog(editor, msg, "Naming is Hard",
                                        JOptionPane.PLAIN_MESSAGE);
        }
      }
    });
      rootPane.setDefaultButton(renameButton);
```
substituting "isJavaIdentifierStart/Part" for "isUnicodeIdentifierStart/Part" might solve the problem?

**Comment by jeremydouglass** [comment]
> isUnicodeIdentifierStart

https://www.tutorialspoint.com/java/lang/character_isunicodeidentifierstart.htm

> _ may start a Unicode identifier is false

**Comment by digimeas** [comment]
@jeremydouglass 
That does seem to be the problem, alright.
https://www.tutorialspoint.com/java/lang/character_isjavaidentifierstart.htm
  _ may start a Java identifier is true
