### ISSUE TITLE
Contributions Manager Error

### ISSUE THREAD

**Issue by thetoalbooth** [processing/processing#5829]
I am having trouble connecting to the Contributions Manager.  

I recently installed Processing 3.5.3 and when attempting to add the Python Mode, it throws me the same pink error that others have had as well, stating: 

Could not connect to the Processing server. Contributions cannot be installed or updated without an Internet connection. Please verify your network connection again, then try connecting again.

The previous threads about this issue did not help my problem, unfortunately.  Any ideas?

https://github.com/processing/processing/issues/4718
https://github.com/processing/processing/issues/5720

**Comment by dbetchkal** [comment]
Same error, Processing 3.5.4 on Ubuntu 18.04.5.

**Comment by dbetchkal** [comment]
Ah, a bit embarrassing, but I had a similar situation to #5720 - the various folders associated with Processing didn't have the correct permissions.

Fixed in the terminal by using:
`sudo chown -R $USER: $HOME`
