### ISSUE TITLE
SyntaxError after saving

### ISSUE THREAD

**Issue by depperm** [processing/processing#5834]
## Description

Using processing for x64 version 3.5.3:

I'm following along with the [tutorial](https://www.youtube.com/watch?v=mhjuuHl6qHM&list=WL&index=70&t=0s). I can run it before saving and see the expected result (a dot on the page currently). However, as soon as I save I get the following error:

>SyntaxError: jdk.nashorn.internal.ir.Block cannot be cast to jdk.nashorn.internal.ir.FunctionNode

## Expected Behavior

It to continue working like it did before saving.

## Steps to Reproduce

1. Download processing 3.5.3 for windows 64, install p5.js mode, and switch to that mode.
2. Edit the sketch_### file to be:
```
const flock=[];

function setup() {
  createCanvas(400, 400);
  
  flock.push(new Boid());
}


function draw() {
  background(220);
  for(let boid of flock){
    boid.show();
  }
}
```
Add a file boid.js with:
```
class Boid{
  constructor(){
    this.position=createVector(width/2,height/2);
    this.velocity=createVector();
    this.acceleration=createVector();
  }
  show(){
    strokeWeight(16);
    stroke(255);
    point(this.position.x,this.position.y);
  }
}
```
3. Run it and you should see a white circle in a rectangle.
4. Save it, I named mine Flocking but you can choose whatever.
5. Run it again.
6. Examine the error and wonder where it comes from.

## Your Environment

 

* Processing version: 3.5.3
* Operating System and OS version: Windows 10 x64 processor
* Other information:
Intel core i7-5600U CPU @ 2.6 GHz
16 GB RAM

**Comment by benfry** [comment]
This is an issue with a separate project: https://github.com/fathominfo/processing-p5js-mode

But this particular problem will be fixed in the next release of that software.
