### ISSUE TITLE
Sketch crashes with swing.JOptionPane using P2D on macOs Mojave 10.14.4

### ISSUE THREAD

**Issue by GabrieleMoretti** [processing/processing#5836]
I’ve just installed Mojave 10.14.4 on my MacBook Pro 2018. Using P2D used to give a warning in previous macOs versions  but JOptionPane worked properly... Installing Mojave 10.14.4 caused the crash of my application when I call javax.swing.JOptionPane.showInputDialog() to ask the user to input data. It seems like it can’t open the new popup window. Same issue with javax.swing.JOptionPane.showMessageDialog().
I must use P2D because I need P3D for some images, but trying to launch a sketch without P2D the popup window is opening properly.

Do you have any suggestion? Is somebody working on solving issues with macOs so that I can expect this one solved in the next version? Do you suggest any light and easy workaround for asking just one field to the user?

## Your Environment

* Processing version: 3.4.3
* Operating System and OS version: 10.14.4
* Other information: MacBook Pro 2018, Processing IDE

**Comment by daniellasry** [comment]
I'm using: `PApplet.runSketch(new String[] {this.getClass().getSimpleName()}, this); `
to open a new window. I'm also getting a crash after updating to 10.14.4.

No exception is thrown, it just hangs forever on the runSketch call.

**Comment by retiutut** [comment]
In addition to the above errors, getting a "pinwheel of death" when using `selectInput()` to open a file dialog box after updating to Mojave 10.14.4!

**Comment by benfry** [comment]
Not likely a Processing bug… You're probably creating/manipulating the `JOptionPane` on the EDT which is gonna cause a deadlock. This is just a headache of Java programming; you'll want to learn a bit more about how the EDT works if you're gonna use AWT/Swing components.

**Comment by retiutut** [comment]
This has been fixed already. Thanks.
