### ISSUE TITLE
mousePressed(); not working

### ISSUE THREAD

**Issue by EV4gamer** [processing/processing#5838]
## Description
When i use void mousePressed() { }, it doesn't register any of my mouse clicks. This is weird because yesterday it did work, and since then i havent changed my code in any way.
When i create a new sketch in order to try mousePressed(), it also doesnt work, so my poor programming skills aren't the (main) problem.

## Expected Behavior

mousePressed(){} should register my mouse clicks.

## Current Behavior

mousePressed(){} doesnt do anything at all.

## Steps to Reproduce

1.  make a new sketch.
2.  add the void mousePressed() function.
3. watch as it doesnt do anything.

## Your Environment

 

* Processing version: 3.5.3
* Operating System and OS version: windows 10

**Comment by StanLepunK** [comment]
Can you pass your work who's not work ?

**Comment by Hendrikto** [comment]
Do you have a `draw()` method?

**Comment by Bobby54** [comment]
Could you try this code?

void setup(){
  size(200, 200);
}

void draw(){
  background(0);
  if(mousePressed){
    background(255);
  }
}

**Comment by EV4gamer** [comment]
It seems to work again, i have no idea what went wrong. 
Everything now works and i dont seem to be able to replicate the problem i had.

**Comment by GRsni** [comment]
@EV4gamer Please close this issue, to avoid clutter in the issues page. Thank you.
