### ISSUE TITLE
Help > Libraries Reference > submenu items don't work

### ISSUE THREAD

**Issue by bangnoise** [processing/processing#5839]
## Expected Behavior
The reference for the installed library should open

## Current Behavior
Nothing happens

## Steps to Reproduce
1. Install a library from the Contribution Manager (eg Syphon)
2. Select that library in Help > Libraries Reference > Syphon
3. Nothing happens

## Your Environment
* Processing version: 3.5.3
* Operating System and OS version: macOS 10.14.4

**Comment by GRsni** [comment]
I'm unable to reproduce the bug on a Windows system. Might be OS related?

**Comment by benfry** [comment]
Fixed for 4.0 beta 9.
