### ISSUE TITLE
loadXml doesn't t trows errors

### ISSUE THREAD

**Issue by thierry75** [processing/processing#5846]
hi,
if trying to load an  xml file, and the file is not there,  processing 3.3.7 catch an error, but since then, P 3.4 and P 3.5.x  the catch is not triggered

ThanKs

test code: 
XML Projects;
 void setup(){
   try {
    Projects = loadXML(sketchPath("Projects.xml"));
  }   
  catch (RuntimeException e)
    {
    println("there");
  }
 }

**Comment by dzaima** [comment]
It seems that Processing 3.4+ returns `null` when the file is not found, instead of throwing an error, so a simple `Projects != null` if&else check should work.

**Comment by thierry75** [comment]
Hi, Thanks for fast respond.
yep, if(xml != null) is a solution
sounds more logic to me to get an error for asking a non-existing file...
have a good day !

**Comment by GRsni** [comment]
@thierry75 Please close this issue, to remove clutter from the issues page. Thank you
