### ISSUE TITLE
Processing fails to recognize the existence of a class in the same folder

### ISSUE THREAD

**Issue by LahaLuhem** [processing/processing#5847]
## Description
Doesn't recognize another class in the same folder when I try to add it use it inside another class as an object, but does for another class

## Expected Behavior
it does not give me a "class doesn't exist" error for one class and not for another

## Steps to Reproduce

<1st tab>
class AI {
  
}

<2nd Tab>
class Ship {
  
}

<3rd Tab>
class Board {
  AI ai;
  Ship ship;
  
}

"class Ship does not exist" error under the 'Ship' of 'Ship ship' and none under 'AI ai'.

## Your Environment
* Processing version: 3.5.3
* Operating System and OS version: Windows 10
* Other information:

## Possible Causes / Solutions
-NA-

![image](https://user-images.githubusercontent.com/47954571/56813035-71ea0780-683c-11e9-9930-731c703cf758.png)

**Comment by dzaima** [comment]
Processing might give weird errors if there are no functions in the sketch because a function-less sketch is equal to having it all be wrapped in `void setup() { ... }`.  
So the code is equal to
```
void setup() {
  class AI { }
  class Board { AI ai; Ship ship; }
  class Ship { }
}
```
which would be problematic in regular java.

Adding `void setup() { }` (or any other function) anywhere fixes it.

**Comment by Bobby54** [comment]
Try to add the implementation for ship by making a constructor which says `ship = new Ship();`.
This might solve it.

**Comment by LahaLuhem** [comment]
It worked thanks a lot

**Comment by GRsni** [comment]
You can close this issue now @LahaLuhem
