### ISSUE TITLE
stroke() with clip() has no effect on PGraphics[SOLVED, NO BUG].

### ISSUE THREAD

**Issue by LuislopezMartinez** [processing/processing#5852]
When y draw a simple ellipse() on a PGraphics object the stroke() ever draws on top of any fill() color object. stroke() not respect the normal overlap order.

Windows 10 pro.
Processing 3.5.3 x64 official release.

**Comment by LuislopezMartinez** [comment]
No bug, sorry.

**Comment by jeremydouglass** [comment]
If this is solved and not a bug, then you can CLOSE to mark your issue Closed.
