### ISSUE TITLE
processing-tool wiki link is wrong

### ISSUE THREAD

**Issue by yoyou446** [processing/processing#5856]
## Description
The help menu for the processing-tool in command line says to go to "https://github.com/processing/processing/wiki/Command-Line" or aid but this link is not right.

## Expected Behavior
Expected Behavior is to print "https://github.com/processing/processing/wiki/Processing-CLI%3A-Command-Line-Interface" 

## Current Behavior
Printing bad link

## Steps to Reproduce

1. `$ ./processing-tool`

## Your Environment

 

* Processing version: 3.5.3
* Operating System and OS version: macOSX
* Other information:

## Possible Causes / Solutions

Just a simple fix of tool

**Comment by kfrajer** [comment]
[Wiki page](https://github.com/processing/processing/wiki/Command-Line) has been updated to reflect help description when running `processing-java` tool. @benfry Please close this.

**Comment by ezzabi** [comment]
That is it

**Comment by yoyou446** [comment]
@kfrajer I gotch u fam
