### ISSUE TITLE
Building Procesing using ant

### ISSUE THREAD

**Issue by kfrajer** [processing/processing#5860]
Windows 10
Building Processing from source using ant
Previous related bugs: 
- Build failed: JDK 8u202 required #5827 
- Also #5608

Currently I have installed the following Java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode, sharing)

Running `ant run` on a clone version of Processing produces the following error:
 
> (.....)
> jre-download:
> [downloader] Redirecting to https://edelivery.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-windows-x64.tar.gz
> [downloader] Redirecting to http://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-windows-x64.tar.gz?AuthParam=1557651765_62c6f0ffae26b48d7fd7239dd880f422
> [downloader] Redirecting to https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-windows-x64.tar.gz?AuthParam=1557651765_62c6f0ffae26b48d7fd7239dd880f422
> [downloader] Header Name:Accept-Ranges
> [downloader] Header value:bytes
> [downloader]
> [downloader] Header Name:null
> [downloader] Header value:HTTP/1.1 404 Not Found
> [downloader]
> [downloader] Header Name:Server
> [downloader] Header value:Akama.........

I can see that from the latest available commit (37108add372272d7b1fc23d2500dce911c4d1098) that there was a [note left](https://github.com/processing/processing/blob/master/build/build.xml#L80)  in the `processing/build/build.xml` file about Oracle's new requirement to accept the license and login to download the JRE.

Since the `build.xml` defines 8_202 but I have installed 8_211, my questions are:
* Do I need to revert my java library to 202 (I do not think to find 202 in Oracle's site)
* Can I change the `build/xml` file to reflect 211 version? I was able to get a hash value related to the 8.211 distribution from the Oracle site but it did not work. 
* I created an account in Oracle and downloaded 211 and 212. Can I provide this tar.gz files so to force `ant` not to download the jre?

**Comment by kfrajer** [comment]
Problem solved by bypassing the auto downloader and instead, making the **jre** manually available to the build. Instructions (adjust to your platform): 
* Download  the proper JRE from [Oracle download](https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html)
* The downloaded file will have a name similar to `jre-8u212-windows-x64.tar.gz`. 
* Then I renamed it to `jre-8u212.tgz`
* Move it into the cloned repo inside the folder `processing/build/windows/. 
* As a final step before running `ant run`, I have to modified the `build.xml` to ensure he property name `jdk.update` has a value of `212`.
* Runign `ant run` will launch Processing

**Comment by GRsni** [comment]
Hi. This could be an unrelated issue, but after having this same problem, and following your steps, I now get this error message:
![Captura](https://user-images.githubusercontent.com/39127204/58467014-24aecd80-813b-11e9-8709-45fd4c07460a.PNG)

I have included the repo folder in Windows defender exclusion list, but to no avail.

**Comment by kfrajer** [comment]
@GRsni Since this file is in the `Processing_source_code/build/windows/work/lib` folder, it must be generated or copied when `ant` is executed.

If you have a running version of Processing, you should find this missing file in `path_to_Processing3/lib` folder. I suggest you copy this file into the above folder and see if this hack solves your issue. 

Can you please provide the version of ant, your OS, java version?

**Comment by GRsni** [comment]
The thing is, there is a jnidispatch.dll inside the `build/windows/work/lib` directory, but it doesn't like that one I suppose. These are my versions:

-Apache Ant(TM) version 1.10.6 compiled on May 2 2019
-Java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
-Windows 10 Home 64b

Even after swapping the `jnidispatch.dll` files, still no luck. Any other ideas?

**Comment by kfrajer** [comment]
* I am using `Apache Ant(TM) version 1.10.1 compiled on February 2 2017`
* I installed the latest JDK (212) and set the JAVA_HOME to this folder. This is required by ant
* Then I did the steps I mentioned above: edit the build file to update the java version and the build value **plus** rename the zip jdk file and copied it to the proper location.

Could you try running an older version of ant to see if this is the issue?

**Comment by GRsni** [comment]
I finally managed to make it work. Reinstalling a different version of `ant` didn't help, but I renaming the folder where the Java SDK was installed from `/jdk1.8` to `/jdk1_8` actually solved the problem. I guess periods in the paths are a bad idea. Anyways, thanks for the help.

**Comment by benfry** [comment]
Due to more unfortunate changes by Oracle, Java 8u202 is the only version that works at the moment. I've updated the [build instructions](https://github.com/processing/processing/wiki/Build-Instructions) to reflect this.

**Comment by benfry** [comment]
Now fixed as of https://github.com/processing/processing/commit/89a080814895234b54201c0240625e47a5b369cf
