### ISSUE TITLE
FileDialog fail in P3D, P2D and FX2D

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5861]
When the method setVilsible(true) is calling nothing happen and Processing freeze.

## Expected Behavior
Dialogue file open window like with `selectInput()`

## Current Behavior
Processing freeze, no error message, just the apple color wheel after few seconds.

## Steps to Reproduce
```
import java.awt.FileDialog;
void setup() {
  size(300,300,P2D); // don't work
  // size(300,300,P3D); // don't work
  // size(300,300,FX2D); // don't work
  // size(300,300,JAVA2D); // work
  //size(300,300); // work
  FileDialog dialog = new FileDialog(frame, "machin", FileDialog.LOAD);
  dialog.setVisible(true);
}
```

## Your Environment
OSX Mojave / Processing 3.5.3 / MacBook Pro 2018

**Comment by dzaima** [comment]
This seems like standard java behavior (`FileDialog` is a class unaffected by Processing).
Some googling got me to use the following code to stop the blocking:
```java
  SwingUtilities.invokeLater(new Runnable() {
    public void run() {
      dialog.setVisible(true);
    }
  });
```

**Comment by StanLepunK** [comment]
Interresting way but how to use this syntax in Processing ?

**Comment by dzaima** [comment]
@StanLepunK Oh, sorry, I was testing the code on an updated java/preprocessor branch, so didn't get that error. Instead of `FileDialog dialog = ...` using `final FileDialog dialog = ...` should work in Processing 3.

**Comment by benfry** [comment]
AWT/Swing code like `FileDialog` will cause problems with Processing. That's why `selectInput()` et all exist.
