### ISSUE TITLE
running window very small

### ISSUE THREAD

**Issue by celestialro** [processing/processing#5862]
when i downloaded processing it was fine, but it now produces really small window whenever i tried to run the code.  this has happened for a bunch of different coding attempts and i had a friend enter the exact same code in her processing and it ran fine.  i cant maximise the window or change the size.  any idea how i can fix this?

**Comment by Ikbenjijbent** [comment]
Uninstall and reinstall processing?  Update graphics drivers?

**Comment by Bobby54** [comment]
Are u using a `size()` function?

**Comment by dzaima** [comment]
Assuming you have a proper `size(x, y);` in `setup()` or `settings()` and it doesn't work, what does `println(width, height, displayWidth, displayHeight);` output?  
Does it happen on different renderers (`size(800, 800, P2D)`, try swapping `P2D` with `P3D` and `FX2D`)?  
Does the print value update after resizing the window (add `surface.setResizable(true);` to allow resizing)?  
Can you resize with `surface.setSize(800, 800);`?

**Comment by celestialro** [comment]
Yea I am, I just got told by someone it’s a problem that processing sometimes has when running on windows 10 – would you know how to get around this? Thanks for trying to help

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by GRsni** [comment]
Did you manage to solve the problem? If not, what suggestions from the comments above have you tried?

**Comment by benfry** [comment]
Closing, since no details on resolution for five months.
