### ISSUE TITLE
Rect() causes image to be drawn instead of rectangle?

### ISSUE THREAD

**Issue by Matrx007** [processing/processing#5863]
In my game there are enemies wandering around, their draw() method is simple:

```
        if(facingRight) {
            core.displayBuffer.image(image,
                    x, y + offsetY, 80, 80);
        } else {
            float tX = -core.camera.x+core.game.width/2f + x;
            float tY = -core.camera.y+core.game.height/2f+ y;
            
            core.displayBuffer.pushMatrix();
    
            core.displayBuffer.translate(core.camera.x-core.game.width/2f,
                    core.camera.y-core.game.height/2f);
            core.displayBuffer.translate(tX, tY);
            core.displayBuffer.scale(-1, 1);
            
            core.displayBuffer.image(image,
                    -80, offsetY, 80, 80);
            
            core.displayBuffer.popMatrix();
        }
```

Then when we are going to draw walls, we just draw a coloured rectangle like this:

        core.displayBuffer.noStroke();
    
        if(destroyed) {
            core.displayBuffer.fill(0, 0, 0, 16);
            core.displayBuffer.rect(x, y, w, h);
        } else {
            core.displayBuffer.fill(64);
            core.displayBuffer.rect(x, y - WALL_HEIGHT, w, h);
            core.displayBuffer.fill(32);
            core.displayBuffer.rect(x, y + h - WALL_HEIGHT, w, WALL_HEIGHT);
        }

But for some reason, the walls have the texture of the enemies? Here's the loop in which the objects are drawn:

        PMatrix displayMatrix = displayBuffer.getMatrix();
        PMatrix bloomMatrix = bloomLayer.getMatrix();
        PStyle displayStyle = displayBuffer.getStyle();
        PStyle bloomStyle = bloomLayer.getStyle();
        
        onScreenObjects.forEach(o -> {
            displayBuffer.setMatrix(displayMatrix);
            bloomLayer.setMatrix(bloomMatrix);
            displayBuffer.style(displayStyle);
            bloomLayer.style(bloomStyle);
            o.draw(this);
        });
        
        displayBuffer.setMatrix(displayMatrix);
        bloomLayer.setMatrix(bloomMatrix);
        displayBuffer.style(displayStyle);
        bloomLayer.style(bloomStyle);

Here's example of the results, red rectangles are around the walls, that are drawn incorrectly.
Also the bullets are flickering for some reason? These 2 bugs don't appear when I don't draw the enemies onto the screen (or I draw just rectangles instead), so that means, that the image() is doing something weird in the background? 

![bug](https://user-images.githubusercontent.com/20418076/58264845-3f71f280-7d87-11e9-9665-1a84dfd3d854.png)

Ask for additional info if needed!

----
Nvidia Quadro 4000.
Graphics card driver is from 2016, can't upgrade it, all other games are working fine tho.
Processing version: 3.5.3 (Library)
Operating System and OS version: Windows 10 build 17134

Possible Causes / Solutions:
Maybe that the image() manipulates the current texture being used and rect() uses the texture?

**Comment by Matrx007** [comment]
The source code of the project is at github.com/Matrx007/TheLostBits

**Comment by Matrx007** [comment]
Anyone?

**Comment by dzaima** [comment]
Looks like P2D PGraphics (`PGraphicsOpenGL`) weren't designed with the ability to have more than one being drawn with `beginDraw()`; No idea if that's the intention (if it is, it really should be mentioned, like, everywhere). Simplified example of the problem (with an arbitrary png named "a.png"):

**Comment by Matrx007** [comment]
I will try it out, thank you!

**Comment by Matrx007** [comment]
The entire time, from the beginning, I thought that it isn't my mistake, like how could rect() draw an image, it must be bug in Processing not in my code! It was, thanks to @dzaima it's fixed now.

**Comment by Ikbenjijbent** [comment]
> The source code of the project is at https://github.com/Matrx007/TheLostBits

404'd!  Maybe update link?

**Comment by Matrx007** [comment]
I made that repo private.
