### ISSUE TITLE
I cant downloaod the file

### ISSUE THREAD

**Issue by nasko12345678** [processing/processing#5864]
When i first downloadwed processing it failed, now when i try to retry the instalation it says the its forbiden and when i try to download it from the website nothing happens.

**Comment by GRsni** [comment]
Where are you downloading Processing from? What kind of error did you encounter when downloading it the first time?

**Comment by nasko12345678** [comment]
sorry for the late reply, when i download proccesing from their site, it always freezes on 127/127 MB 
i have tried countless times to reset and re-download proccesing but nothing happens

**Comment by GRsni** [comment]
Are you using Windows? Whenever you download a file on Windows, Windows Defender will automatcally scan it for viruses, so it takes a while until the file is ready to be used, even after the actual download has finished. You can check if this is the problem by opening the task manager, and looking for a Windows defender process when you try to download a file from the web.

**Comment by nasko12345678** [comment]
It did not give me any messages that said tha ti checked my he download might be infected
I checked my task manager to see if windwos protector was runing, it was not, i close the download bar so it will not disturb me, its still downloading

**Comment by GRsni** [comment]
There's no notification, it just does it automatically as a preemptive messure. Wait until the download is at 127/127 MB or whatever, then look for the Windows defender process in task manager.

**Comment by nasko12345678** [comment]
i already did

**Comment by nasko12345678** [comment]
i already cheked if the windows manager was there
i did not see it
also the proggres thing down at the chrome logo is halway done and has been stiting like that for almost 2 hours

**Comment by nasko12345678** [comment]
please

**Comment by GRsni** [comment]
Seems like a different issue altogether. I'm sorry I can't help

**Comment by nasko12345678** [comment]
..

**Comment by GRsni** [comment]
Seems like a lot of people are having problems downloading Processing. The only option is to wait and see. Sorry I couldn't be of much help.

**Comment by avrahambraun** [comment]
בס"ד

have you tried a different browser. I was trying to download yesterday using google chrome and then internet explorer, and i think i was having the same issues you describe. this morning i tried downloading w/ safari (i think probably a little outdated version of safari), and it looks like it was successful.

**Comment by nasko12345678** [comment]
Well, try to use firefox, there is a really weird glitch whit the site, try to download it on
 firefox.

**Comment by benfry** [comment]
Please use https://discourse.processing.org/ for questions like this.
