### ISSUE TITLE
convert a .png image to array use processing

### ISSUE THREAD

**Issue by ccu1tn** [processing/processing#5865]
Dear everyone. 
I want to use processing to convert an image .png to array/ 
Does anyone have an example to do it? Please share me a little. 
Many thanks

**Comment by GRsni** [comment]
This isn't the place to ask this kind of question unfortunately. This is for specific problems and bugs when using Processing. For general coding questions and needs, I suggest going to the [Processing subreddit](https://www.reddit.com/r/processing/). The people there will be glad to help you with your coding problems. 

Cheers.
