### ISSUE TITLE
Can't seem to select charsets with createFont()

### ISSUE THREAD

**Issue by burnedsap** [processing/processing#5867]
Hello, I'm trying to use createFont and I can't seem to understand why I can't seem to be unable to get all glyphs to appear. I checked the PFont code, and can't seem to find documentation of selecting charsets.

If I'm not mistaken, this should enable me to see all the glyphs.
createFont("NotoSans-Regular", 17, true, new char[65536]);

NotoSans has the most amount of glyphs if I'm not mistaken, so shouldn't be an issue displaying all glyphs, but I'm still getting the dreaded rectangle Unicode characters.

For some context, using loadFont("NotoSans-Regular-17.vlw"); works perfectly and all glyphs display correctly. I'm forced to use createFont as I'm using the PDF renderer.

Processing version: 3.5.3
Operating System and OS version: Mac OS 10.14.4

I know that using the Create Font tool and selecting All Characters solves this issue, and I assume this is linked to charsets. How can i call the same arguments within createFont()?

**Comment by benfry** [comment]
If you pass in `new char[65536]` without putting anything in that array, you're requesting for the `NUL` (0) glyph 65,536 times. You have to tell it what characters you want, as it says in the method description itself:

```
@param charset array containing characters to be generated
```
