### ISSUE TITLE
Raspberry Pi Camera not working with GL Video or OpenCV 

### ISSUE THREAD

**Issue by FrankOcean11** [processing/processing#5872]
i been trying to run on my Raspberry Pi 3 B+ the Video Library with no luck to this particular error
![20190602_012225](https://user-images.githubusercontent.com/10504709/58757679-e831f780-84d5-11e9-8118-402f797b3011.jpg)

maybe i can get a pointer? i was trying to run one of the simple examples found in openCv library "livecamtest"

```
import gab.opencv.*;
import processing.video.*;
import java.awt.*;

Capture video;
OpenCV opencv;

void setup() {
  size(640, 480);
  video = new Capture(this, 640/2, 480/2);
  opencv = new OpenCV(this, 640/2, 480/2);
  opencv.loadCascade(OpenCV.CASCADE_FRONTALFACE);  

  video.start();
}

void draw() {
  scale(2);
  opencv.loadImage(video);

  image(video, 0, 0 );

  noFill();
  stroke(0, 255, 0);
  strokeWeight(3);
  Rectangle[] faces = opencv.detect();
  println(faces.length);

  for (int i = 0; i < faces.length; i++) {
    println(faces[i].x + "," + faces[i].y);
    rect(faces[i].x, faces[i].y, faces[i].width, faces[i].height);
  }
}

void captureEvent(Capture c) {
  c.read();
}
```

i when ahead and follow along as provided by [https://pi.processing.org/technical/#video-library-capture]

> **Video library**
> 
> Use the new GL Video library to make use of the Raspberry Pi’s accelerated video decoding hardware. (also available from the Contribution Manager)
> 
> Examples show the various ways the library can be used. Please file issues here.
> **Video library: Capture**
> 
> If you’re receiving the error IllegalArgumentException: No such Gstreamer factory: v4l2src with the (regular) Video library, try installing the necessary packages by executing `sudo aptitude install gstreamer0.10-plugins-good` in a terminal.
> 
> Alternatively, the GL Video library also contains some (very limited) functionality for using capture hardware. See this example for details.
> 
> If you want to use the Raspberry Pi camera with the GL Video library, add the following line to your` /etc/modules` file and reboot:
> 
> `bcm2835_v4l2`
> 
> (Note this is a lowercase L not a number one.) After the reboot your camera should show up as `/dev/video0.`

i will go ahead and say that i did NOT do the last part of the edit text file as i did not know or understood where is it that im supposed to go and change `If you want to use the Raspberry Pi camera with the GL Video library, add the following line to your /etc/modules file and reboot:`
if someone can tell me what was i suppose to change then ill go and give that a try aside from that i thought that by me running the sudo command mentioned in step 1 that the Pi would just update all that for me which did not.

**Comment by FrankOcean11** [comment]
okay so i did a `sudo nano /dev/video0.` and reboot but nothing yet when i try to run the sketch using the raspberry pi camera module.

**Comment by FrankOcean11** [comment]
i like to add if is any help that i ran the sketch and left it running and in about 45seconds or so the draw window goes black which is new and i stop getting those error msg's in the console section and i start to see this
```
0
0
0
0
0
0
0
0
0
0
0
0
```
which to me looks like the algorithm has not found a face which is what it suppose to do but i see no feed of pixels in the draw window so it sounds like the sketch is working but the feed is not capturing from the camera module.
i did unplug the RSP PI Camera module out of the PI and plugged in a regular webcam and everything works ~fine "except that its slow" but this is not what we want we want the raspberry  pi camera module
![71qbw8jUfML _SL1500_](https://user-images.githubusercontent.com/10504709/58758314-59c27380-84df-11e9-8277-5c933abfd309.jpg)

**Comment by FrankOcean11** [comment]
?

**Comment by FrankOcean11** [comment]
no ideas guys?

**Comment by FrankOcean11** [comment]
any tips?

**Comment by FrankOcean11** [comment]
may i get some sort of support on the matter please?

**Comment by FrankOcean11** [comment]
?

**Comment by benfry** [comment]
Please post video issues here: https://github.com/processing/processing-video/issues
