### ISSUE TITLE
P3D transparent textures areas bug.

### ISSUE THREAD

**Issue by LuislopezMartinez** [processing/processing#5873]
bug in transparent areas in textured objects in P3D mode.

In the video you can see the "glitch" malfunction.

I leave my project to be able to do the test.

Change "priority" value to negative for view the glitch from the other side.

2 game object are in game.pde file.

Control player with arrow keys..

**BINARY:** https://www.dropbox.com/s/dowxy4vloa0p2yh/test3D.zip?dl=0
**PROJECT FOR TEST:** https://www.dropbox.com/s/xse6ll8w8lop7ta/test3D_project.zip?dl=0
**VIDEO TO VIEW GLITCH:** https://www.dropbox.com/s/7u7lnaib2epv2lp/2019-06-03%2014-18-54.flv?dl=0

**Comment by StanLepunK** [comment]
Hi, are you talk of your bug on forum before post here ?

**Comment by LuislopezMartinez** [comment]
Yes, https://discourse.processing.org/t/hi-this-is-a-bug-3d-game-engine/11800/2


the problem is the complexity of the subject, I guess nobody has done real games with processing before? because there is nothing on the internet, I have been looking and there are only tests and examples and small tests, but complete games I have not seen anything. I guess nobody has started to develop real 3d games with processing and that's why there is no record of this type of glitch.

I have tried to reproduce the problem without the video buffer and it passes exactly the same, it does not seem to be related to the PGraphics object, rather it seems related to the zbuffer of the P3D render

**Comment by jeremydouglass** [comment]
On the forum thread, please post an MCVE -- just a drawn buffer tile on your background showing the problem. Chances are you need to use a rendering hint for depth / compositing.

This is probably a code issue - not a bug.

**Comment by LuislopezMartinez** [comment]
Thanks for the info, but not works with textures with alpha_channel and total transparent zones, Probably are a bug with z order mixing shapes.
In any case y decide to continue work with  a non translucid textures :)

**Comment by benfry** [comment]
Usually this is what's covered on the Troubleshooting page:

> Objects with alpha (lines or shapes with an alpha fill or stroke, images with alpha, all fonts) are displayed in P3D and OpenGL based on their drawing order. This creates some annoying effects like making things opaque if they're drawn out of order with objects above or beneath them. This is simply how most 3D rendering works. To improve appearance, add hint(ENABLE_DEPTH_SORT) to setup(). We don't enable this by default because it would make all sketches slower, not just ones that need it.

That doesn't fix everything, but it's usually the problem w/ transparency.
