### ISSUE TITLE
Android mode: loadShape() not load a .mlt and texture files asociated to .obj

### ISSUE THREAD

**Issue by LuislopezMartinez** [processing/processing#5877]
Android mode not load PShape ".obj" correctly.. "error: close stream" when attempt to load a .mtl material file asociated to 3d model.

**Comment by LuislopezMartinez** [comment]
I have found the specific failure, when loading a 3d model with loadShape () the .mtl file and the .png associated with the model are tried to load from the "data" folder, but it should be loaded from the folder that hosts the model.

This is a bug!

**Comment by dzaima** [comment]
Where exactly is the place that the model files are placed in? And why do you think that it shouldn't be trying to load them from the `data` folder (unless you're talking about full paths)?

Also, if this is android-specific, there is [a separate repository](https://github.com/processing/processing-android) for it.

**Comment by LuislopezMartinez** [comment]
I post the problem first in the forum, but i found the exact problem now.
In this post are an example to view the problem.

https://discourse.processing.org/t/android-mode-loadshape-is-broken/11938

I post this bug on android zone, thxs.

**Comment by benfry** [comment]
(Closing/locking since it's an Android issue)
