### ISSUE TITLE
Load SVG shape do not load text elements

### ISSUE THREAD

**Issue by mengzhen94** [processing/processing#5878]
## Description

I am loading a svg file with a bunch of text elements on it.
Here is a example of text tag in the svg file
```
<g id="g4408" transform="matrix(0.41926233,0,0,0.41926233,358.69347,78.772123)">
      <text linespacing="125%" id="text4402" y="141.68008" x="1300.9614" style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:sans-serif;text-align:center;letter-spacing:0px;word-spacing:0px;text-anchor:middle;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" xml:space="preserve">
        <tspan y="141.68008" x="1300.9614" id="tspan4404" role="line">Hello</tspan>
        <tspan id="tspan4406" y="191.68008" x="1300.9614" role="line">World</tspan>
      </text>
    </g>
```
The code to load the image:

```
PShape por_shp;
por_shp = loadShape(image);
shapeMode(CENTER);
shape(por_shp, 0, 0, dx, dy);
```
## Expected Behavior

Should load and display these text elements

## Current Behavior

All text elements are missing, but other elements are showing properly.

## Your Environment

 

* Processing version: 3
* Operating System and OS version: Ubuntu

Does anyone has any idea how to display text elements in svg file?

**Comment by benfry** [comment]
Text isn't supported in SVGs; sorry! https://github.com/processing/processing/issues/5935
