### ISSUE TITLE
Sketch menu > Clicking an opened sketch to give it focus doesn't work anymore

### ISSUE THREAD

**Issue by ONyX888** [processing/processing#5882]
## Description
When using sketch menu, clicking an opened sketch to give it focus doesn't work anymore.

## Expected Behavior
When using sketch menu, clicking an opened sketch to give it focus should make it appear in front of other opened sketches windows. The tick at the left of the current focused sketch should be updated.

## Current Behavior
When using sketch menu, clicking an opened sketch to give it focus doesn't work anymore. The tick at the left of the current focused sketch doesn't update.

## Steps to Reproduce
1. Open at least 2 sketches.
2. Go to "Sketch" menu.
3. A this end of the menu, try to select a non focused sketch (without the tick at the left).

## Your Environment
* Processing version: 3.5.3
* Operating System and OS version: macOS Majave 10.14.5

## Possible Causes / Solutions
Maybe regression ?

<img width="439" alt="Capture d’écran 2019-06-17 à 21 58 16" src="https://user-images.githubusercontent.com/39488732/59633695-5e2c9480-914d-11e9-91a0-9216ed108c9e.png">

**Comment by GusFermin** [comment]
Hello. 
I am having this exact same issue. 
My Environment:
Processing version: 3.5.3
Operating System and OS version: macOS El Capitan 10.11.6

**Comment by benfry** [comment]
Fixed for 4.x with https://github.com/processing/processing4/commit/5d3d1aacb852bfe20da723a7c3b4c1bb338ea709
