### ISSUE TITLE
sketches dont run

### ISSUE THREAD

**Issue by Pixelpower3780** [processing/processing#5884]
I am currently using processing 3.5.3 and whenever I run a sketch it takes hours to start. this happens with every sketch no matter how old, new, small or large. as you can imagine this is very annoying. how can I fix this??

**Comment by dzaima** [comment]
Details would be helpful for understanding what the problem is - what OS are you on? What's your CPU, is there enough free RAM? Does running a sketch slow down only at the first run or every time? How long exactly are you talking about?

**Comment by Pixelpower3780** [comment]
I have a windows 10, 8GB DDR4 memory, Radeon RX vega10 graphic card and ryzen 7 processer.
when I press play I literally have to wait hours before the sketch runs

**Comment by benfry** [comment]
In the bug template, there is text explaining the information needed and links for when sketches "don't run". Please use those resources, otherwise we can't help you.
