### ISSUE TITLE
SVG Loadshape position incorrect

### ISSUE THREAD

**Issue by mechengineermike** [processing/processing#5885]
When loading svg files the position of the loaded SVG file is incorrect no matter what shapemode you use. The image is offset by some unknown quantity. 

Example to reproduce:
  //Use rectangle to draw a bounding box
 rectMode(CORNERS);
 rect, ( x1, y1, x2, y2);

//Load an SVG file and scale/position it with the bounding box parameters within shape()
void loadShape(){
  Image = loadShape(fileName);
  shapeMode(CORNERS);
  shape(Image, x1, y1, x2, y2 );

## Your Environment
Using latest version of processing and the geomerative library.
Rendering with P3D.
Using windows 10 .

**Comment by mechengineermike** [comment]
![error report](https://user-images.githubusercontent.com/16481000/59959943-153e4e00-9475-11e9-9840-131fe0b2d1af.JPG)
  See attached image which shows a blue bounding box and the logo image which is offset and should be inside the bounding box.

**Comment by benfry** [comment]
Probably something wrong with the boundaries set in your SVG file. There are several different places that need to be set correctly, and you'll get different results depending on the software you use to generate the SVG.
