### ISSUE TITLE
Contribution Manager UI - bug

### ISSUE THREAD

**Issue by Fubaxiusz** [processing/processing#5891]
## Description
![image](https://user-images.githubusercontent.com/34406163/61251445-cc6b7380-a75a-11e9-86e7-76b9dbe83f83.png)
Contribution Manager UI colors only partially support system UI colors resulting invisible text when system UI is white-text on dark-background.
Solution for that would be forcing all text in Processing UI to have fixed color (most reasonable) or supporting system UI colors in full (too much hassle).

## Expected Behavior
Text in the Contribution Manager should be visible no matter the system UI colors.

## Current Behavior
Now Contribution Manager seems to take text color from system settings, ignoring the background color, which results with white text on white background :(

## Steps to Reproduce
1. Download the .theme file for Windows
[Dark98Style(Win7).zip](https://github.com/processing/processing/files/3394343/Dark98Style.Win7.zip)
2. Apply theme (just double click, it's just a text file with color settings)
3. Open Processing and the Contribution Manager

## Your Environment
* Processing version: 3.5.3
* Operating System and OS version: Windows 7 Pro x64
* Other information: Using classic shell theme with dark colors

## Possible Causes / Solutions
Just force the Contribution Manager to use fixed color for list text like 0x000000

**Comment by benfry** [comment]
We can't control odd theme files that folks may have installed…

**Comment by honzasvasek** [comment]
On ubuntu same problem when  system theme is dark
