### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by thomasclifford** [processing/processing#5892]
Good day.
I'm running Win 10 on a Dell Laptop, Java v1.8.0_211-b12 64-bit, and I cloned the 
processing dir and ran ant run in the build directory, and got:

>ant run
Buildfile: C:\dl\java\java3d\processing\build\build.xml

run:

ignore-tools:
     [echo] Ignore the 'Unable to locate tools.jar' message.
     [echo] The tools.jar file is not required to build Processing.

revision-check:

windows-check-os:

jre-check:

downloader-setup:

compile:
    [mkdir] Created dir: C:\dl\java\java3d\processing-master\build\jre\bin
    [javac] Compiling 1 source file to C:\dl\java\java3d\processing-master\build\jre\bin

dist:
      [jar] Building jar: C:\dl\java\java3d\processing-master\build\jre\downloader.jar

jre-download:
[downloader] Redirecting to https://edelivery.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-windows-x64.tar.gz
[downloader] Redirecting to http://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-windows-x64.tar.gz?AuthParam=1563471391_a679b81ddd3c39c9eb973f97b41d4949
[downloader] Redirecting to https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-windows-x64.tar.gz?AuthParam=1563471391_a679b81ddd3c39c9eb973f97b41d4949
[downloader] Header Name:Accept-Ranges
[downloader] Header value:bytes
[downloader]
[downloader] Header Name:null
[downloader] Header value:HTTP/1.1 404 Not Found
[downloader]
[downloader] Header Name:Server
[downloader] Header value:AkamaiNetStorage
[downloader]
[downloader] Header Name:ETag
[downloader] Header value:"477d9862374177c810b0b7d73b4f1e53:1531792454.541174"
[downloader]
[downloader] Header Name:Connection
[downloader] Header value:keep-alive
[downloader]
[downloader] Header Name:Last-Modified
[downloader] Header value:Wed, 31 Aug 2011 20:28:54 GMT
[downloader]
[downloader] Header Name:Content-Length
[downloader] Header value:7073
[downloader]
[downloader] Header Name:Date
[downloader] Header value:Thu, 18 Jul 2019 17:34:33 GMT
[downloader]
[downloader] Header Name:Content-Type
[downloader] Header value:text/html
[downloader]

The only thing close to an error were the lines:

[downloader] Header Name:null
[downloader] Header value:HTTP/1.1 404 Not Found

But that doesn't seem like a deal-breaker....

Thanks for your work on this......

**Comment by Soul-Drake** [comment]
This is a known issue with Processing (see #5868 and #5860 ).
As of now, the only JRE version working is 8u202, which you will have to install and make available to the build process manually (#5860 has instructions on this), as the download process was broken by changes made to the Java download from Oracle's servers.

This issue will likely be closed shortly by the maintainer - I hope you can get it to work on your end (I'm still struggling with this myself -_-)

**Comment by benfry** [comment]
Closing as duplicate; this is already covered in the [Build Instructions](https://github.com/processing/processing/wiki/Build-Instructions).
