### ISSUE TITLE
loadShape fails to render svg on Android mode

### ISSUE THREAD

**Issue by phanirithvij** [processing/processing#5894]
When I use `loadShape` with some `SVGs` it's not rendering properly in Android mode.
But it's getting rendered correctly in the java mode.
This is one such svg
<img src="https://res.cloudinary.com/rootworld/image/upload/v1563699329/ogears.svg" alt="orange-svg" width="200px"/>
I've put together this simple code that demos what I mean.

```java
PShape svg;

void settings() {
  size(displayWidth, displayHeight);
}

void setup(){
  svg = loadShape("ogears.svg");
}

void draw(){
  background(255);
  push();
  scale(map(mouseY, 0, height, 0, 1));
  shape(svg);

  push();
  noFill();
  stroke(0);
  strokeWeight(1);
  rect(0, 0, svg.width, svg.height);
  pop();

  pop();
}

// these are not available in Android mode.
// comment the lines below in Java mode.
void push(){
  pushMatrix();
  pushStyle();
}

void pop(){
  popStyle();
  popMatrix();
}
```

A simple project file which can be opened with processing [SVGTests.zip](https://github.com/processing/processing/files/3414434/SVGTests.zip)

And it is working when I use `size(.., .., P2D)`. Why is that? What is the default renderer if not P2D?

**Comment by benfry** [comment]
Please post Android issues here: https://github.com/processing/processing-android/issues
