### ISSUE TITLE
Networking not working in processing 3.5.3

### ISSUE THREAD

**Issue by KevinWh0** [processing/processing#5899]
- Found a bug

#### Details about the bug: 

- Operating System:   Windows 10  Processing V3.5.3
- Steps to reproduce this bug:

I wanted to do some networking, so I went to this site(https://processing.org/tutorials/network/). I copied the second example, into my sketchbook, I made 2 sketches for the client and server. I ran then without them being saved, and that worked, only when I saved them they suddenly got a bunch of errors. I was looking for a way to suppress this or something, as it won't let me run the program at all if I save it.

I expect it to connect like it does before I save it.

![image](https://user-images.githubusercontent.com/45321184/62249664-c6eb6b80-b39f-11e9-9486-6fd8fad44f45.png)

// 2A: Shared drawing canvas (Server)

import processing.net.*;

Server s; 
Client c;
String input;
int data[];

void setup() { 
  size(450, 255);
  background(204);
  stroke(0);
  frameRate(10); // Slow it down a little
  //s = new Server(this, 12345);  // Start a simple server on a port
  s = new Server(this, 21212); 
} 
void draw() { 
  if (mousePressed == true) {
    // Draw our line
    stroke(255);
    line(pmouseX, pmouseY, mouseX, mouseY); 
    // Send mouse coords to other person
    s.write(pmouseX + " " + pmouseY + " " + mouseX + " " + mouseY + "\n");
  }
  
  // Receive data from client
  c = s.available();
  if (c != null) {
    input = c.readString(); 
    input = input.substring(0, input.indexOf("\n"));  // Only up to the newline
    data = int(split(input, ' '));  // Split values into an array
    // Draw line using received coords
    stroke(0);
    line(data[0], data[1], data[2], data[3]); 
  }
}

// 2B: Shared drawing canvas (Client)

import processing.net.*; 

Client c; 
String input;
int data[]; 

void setup() { 
  size(450, 255); 
  background(204);
  stroke(0);
  frameRate(10); // Slow it down a little
  // Connect to the server’s IP address and port­
  c = new Client(this, "127.0.0.1", 12345); // Replace with your server’s IP and port
} 

void draw() {         
  if (mousePressed == true) {
    // Draw our line
    stroke(255);
    line(pmouseX, pmouseY, mouseX, mouseY); 
    // Send mouse coords to other person
    c.write(pmouseX + " " + pmouseY + " " + mouseX + " " + mouseY + "\n");
  }

  // Receive data from server
  if (c.available() > 0) { 
    input = c.readString(); 
    input = input.substring(0,input.indexOf("\n"));  // Only up to the newline
    data = int(split(input, ' '));  // Split values into an array
    // Draw line using received coords
    stroke(0);
    line(data[0], data[1], data[2], data[3]); 
  } 
}

**Comment by Sardtok** [comment]
You saved the sketch with the name Server. Which is also the class you are trying to import. So you are getting a name conflict. Rename the sketch to something like MyServer, or use fully qualified names for Server elsewhere:

`processing.net.Server s;`

and

`s = new processing.net.Server(this, 21212);`

**Comment by jeremydouglass** [comment]
Thanks, this can be closed -- it is actually a programming question; when encountering problems with a sketch, first ask a question on the forum before opening a bug report: https://discourse.processing.org/
