### ISSUE TITLE
Could not run the sketch

### ISSUE THREAD

**Issue by meskor** [processing/processing#5901]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by meskor** [comment]
I can not run a sketch after charging a picture from the Data folder.
The Processing version is : 3.5.3
The OS version is Windows 7


code that will produce the error :       color pixelColor= img.pixels[loc];

Red spew that I see in the console : 
ArrayIndexOutOfBoundsException: 252000
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.

If somebody can help me ?

Regards,

JPKO

**Comment by whykatherine** [comment]
The ArrayIndexOutOfBoundsException probably means that you're trying to access a location in the array that doesn't exist, like trying to get the 6th element of an array that only has 5 elements.

What is `loc` in your example? Could you post more of your code?

**Comment by meskor** [comment]
Thanks Katherine for your answer, but unfortunatly I am not at home for the moment but in Asia . I will be back in France  in one week and will give you more informations.

Best regards,

Jean Pierre

**Comment by jeremydouglass** [comment]
Do not ask or answer coding questions here -- this is for tracking bugs only.  
Please ask your coding questions on the forum -- there someone can give you help.

-   http://discourse.processing.org

(it sounds like loc is a number larger than your image pixel count)

**Comment by meskor** [comment]
Hi Jeremy,
Thanks for your mail and informations.
You are right and it was a problem due to my image pixel count.
