### ISSUE TITLE
"Save As..." and "Open Recent..." don't work well together

### ISSUE THREAD

**Issue by villares** [processing/processing#5902]
## Description
I use "Save As..."  a lot to try a new idea from a previous sketch, and I often want to open the previous sketch to check out on a previous state of the code.
The "Open Recent" feature ignores a previously open sketch if it was "saved as" something new.

## Expected Behavior
I wish the "Open Recent" list kept the name of the recently open sketch, even if it was saved as something else.

## Current Behavior
"Open Recent" only lists the name of a recently open sketch if it was not "saved as" with another name. (Note that in case of a "Save As", the sketch was not "renamed", there is still a copy on disk of the previously named sketch).

## Steps to Reproduce
1. Create a sketch named sketch_A, save and close.
2. Crete a sketch named sketch_B, save only (without closing).
3. Save sketch_B as sketch_C.
4. Look at "Open Recent" options. You will see: sketch_A and sketch_C only.

## Your Environment
* Processing version: 3.5.3
* Operating System and OS version: Xubuntu 18.0
(I think it's the same on Mac OS and Windows).

**Comment by WilliamMars20** [comment]
I am new but I am interested in tackling this issue.

**Comment by jeremydouglass** [comment]
> * (I think it's the same on Mac OS

It is the same on MacOS. I would also like this feature: it is common for me to Save As, then want to open the previous sketch file so that I can work on the two different versions side-by-side.

**Comment by benfry** [comment]
Ok, that was just a bad assumption about what the default behavior should be. Changed for the next release after 3.5.3.
