### ISSUE TITLE
How do I upload java projects to the web or can I only upload java script projects to the web

### ISSUE THREAD

**Issue by NOLAN13435463231567485356785668754** [processing/processing#5903]
If you know how to do it please tell me

**Comment by whykatherine** [comment]
Typically if you want to use Processing on the web, the easiest and most common way is to use [p5.js](https://p5js.org), which is a JavaScript version of Processing. If you prefer using the original Processing, or you have an existing Processing sketch you want to upload to the web, you can try using [Processing.js](http://processingjs.org/), which converts Processing sketches for the web, though there are some limitations.

**Comment by benfry** [comment]
Please use the forum for this type of question: https://discourse.processing.org
