### ISSUE TITLE
Processing on macOS Catalina beta

### ISSUE THREAD

**Issue by mkGit-1** [processing/processing#5907]
### Platform
I have been using the latest developers beta for macOS Catalina(10.15 Beta)
### Issue
When I try to open Processing 3 it will freeze on loading screen indefinitely. I haven't been able to find any other beta users to check if it was me or the beta causing the problem.
### Probable cause
I'm new to processing so its either me screwing up or processing not yet working on the beta

**Comment by jeremydouglass** [comment]
Forum user describes a similar problem, says it was "fixed in dev beta 5"

https://discourse.processing.org/t/processing-3-with-macos-catalina/13338/3?u=jeremydouglass
