### ISSUE TITLE
size() not working on ubuntu 16 and processing 3.5.3

### ISSUE THREAD

**Issue by eyaler** [processing/processing#5912]
## Description
 
size() not working. It displays a windows with the size of my monitor although i am not using fullscreen()

## Expected Behavior
size() function should set Processing canvas size.

## Current Behavior
It displays a windows with the size of my monitor although i am not using fullscreen().
in my case width=1920 height=1200

## Steps to Reproduce
Using settings or setup gives the same result:
 
```processing
void settings() {
    size(200, 300);
}

// or

void setup() {
    size(200, 300);
}
```

## Your Environment 
* Processing version: 3.5.3
* Operating System and OS version: Ubuntu 16.04

downgrading to 3.4 fixed it

**Comment by JulixoMS** [comment]
That happened to me too, but it works perfectly if i use FX2D instead of P2D or P3D.

**Comment by eyaler** [comment]
FX2D didn't work for me.
eventually I had too much trouble getting my sketch to work on linux, due to issues with camera drivers, video and audio codecs, and full screen issues. Installing windows was turned out to be a highly time efficient solution to all my issues.

**Comment by sampottinger** [comment]
Hey there @eyaler and @JulixoMS,

Thank you for reporting this issue and for your patience. I have tested this with Processing 4 (https://github.com/processing/processing4) using Ubuntu 16.04 and it appears this is resolved in the new version. @benfry would you like to investigate this over here further or just focus on the processing4 fork?

Thanks,
Sam

**Comment by Programmer-Sean** [comment]
Anyone find a fix for this? my program defaults to full-screen but when I println the size and width they are the specified values. (example: size(500,500) program opens at full-screen but the values width and height are stored as 500 500)

**Comment by emilyj0y** [comment]
I am having this problem as well, but on Windows 10. Tested with 3.5.4 and 3.5.3 on example sketches. 
If I should make a new thread for Windows (vs. this Ubuntu one) please let me know.

**Comment by benfry** [comment]
@sampottinger I've not been able to reproduce this; hopefully it's a Java error that's fixed with 4.0.

**Comment by sampottinger** [comment]
Nice @benfry! LMK if there is anything I can do to help.

**Comment by benfry** [comment]
For anyone running into this, please try with the 4.x releases and report there if it's still a problem: https://github.com/processing/processing4/releases (or here if it's fixed!)

**Comment by benfry** [comment]
No further responses, closing.

If you run into this problem, try with a 4.x release: https://github.com/processing/processing4/releases

And if you have a problem with one of those, file a new issue here: https://github.com/processing/processing4/issues/new
