### ISSUE TITLE
even with processing examples: Could not run the sketch (Target VM failed to initialize).

### ISSUE THREAD

**Issue by mativa** [processing/processing#5915]
EDIT: Processing functions as normal after I changed the screen settings from:
    Surround displays, 2560 * 720
to
    Surround displays, 3840 * 1080

Error is not reproducible, even after changing back to original resolution (2560 * 720)

----------------------------------------Original Issue:-------------------------------------------------
## Description
After the last reboot, any sketch (even any processing example) I am running returns the following error:

"Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting."

the maximum code that will compile and run is an emtpy setup() function. (edit: anything called inside setup() will run).
When adding an empty draw function, said error is produced. together with:

"[0x7FFBC602C3A0] ANOMALY: meaningless REX prefix used
[0x7FFBC602C3A0] ANOMALY: meaningless REX prefix used

Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting."

## Your Environment
* Processing version: 3.5.3 (Error is also  present with Processing 3.4)
OS: Windows 10     Version 10.0.18362 Build 18362
System:
- AMD Ryzen 2700x, 
- GTX 1080 TI, driver version: 436.02
- 2 Full HD Screens, set to "Surround displays, 2560 * 720

Measures taken so far:
- creating a fresh sketchbook folder
- reinstalling processing
- deleting the preference file (the folder in which the file is supposed to be doesn't exist to begin with: Users → username → AppData)
- entering ".\processing.exe --l4j-debug" into command prompt (returned:
" '.\processing.exe' is not recognized as an internal or external command,
operable program or batch file."")
- updating the graphics driver to the most recent release (432.02)

Any Help would be greatly appreciated.

**Comment by benfry** [comment]
If changing the display resolution fixes it, then it sounds like you've got a problem with your graphics drivers; that's not the sort of thing we have any control over.
