### ISSUE TITLE
Error code on Startup

### ISSUE THREAD

**Issue by yucky1** [processing/processing#5916]
I tried going through the troubleshooting page with no luck. I tried uninstalling and reinstalling processing several times. I can’t open my Processing anymore.
I had processing downloaded on my computer for a while, but I hadn’t opened it in a couple months and now when I try to run it I get an error code. I’m running mac OS 10.12.6. I tried uninstalling and reinstalling but no luck. Any help would be much appreciated.
<img width="648" alt="Screen Shot 2019-08-19 at 10 20 45 PM" src="https://user-images.githubusercontent.com/54383397/63479147-cf384300-c441-11e9-8ad1-571ca8f9a92d.png">

**Comment by REAS** [comment]
This is probably the same as #5482 and that issue has a suggestion. Please follow the suggestion and use that issue to follow up.

**Comment by benfry** [comment]
This one is a duplicate of #5823, which is fixed for 3.5.4.
