### ISSUE TITLE
Justified Text Align in PDF Generation

### ISSUE THREAD

**Issue by gramagrass** [processing/processing#5919]
Justified text is not ideal (in usability terms) for most of digital uses but in printing and publishing is really extended its use (in some cases is a must). Right now I'm doing a generator of books in processing and I can't achieve the usual justified text blocks for printed books --I found a solution that works on screen but not in the PDF creation--. Please consider adding support for this feature, I'm sure it will be handy for many printed-matter uses (that's an important use for PDFs anyway). Thanks a lot for your time.

**Comment by benfry** [comment]
Duplicate of https://github.com/processing/processing/issues/225
