### ISSUE TITLE
Processing 3 Text Positioning Issue

### ISSUE THREAD

**Issue by uPixelar** [processing/processing#5922]
Main Tab
```
Button OK;
void setup()
{
  size(1280, 720);
  OK = new Button(50, 50, 120, 50, 0, 255, 255, "OK");
  
}

void draw()
{
  OK.create();

  
}
```
Button Tab
```
class Button
{
  PVector pos = new PVector();
  float h;
  float w;
  color c;
  String t;
  Boolean Clicked;
  
  Button(int x_, int y_, int w_, int h_, int r_, int g_, int b_, String t_)
  {
        pos.x = x_;
        pos.y = y_;
        w = w_;
        h = h_;
        c = color(r_, g_, b_);
        t = t_;
  }
  
  void event() 
  {
    if(mousePressed == true && mouseButton == LEFT && mouseX <= pos.x+w && mouseX >= pos.x && mouseY <= pos.y+h && mouseY >= pos.y)
    {
      Clicked = true;
    }
  }
  
  void create()
  {
   fill(c);
   rect(pos.x, pos.y, pos.x+w, pos.y+h);

   fill(0);
   textAlign(CENTER, CENTER);
   text(t, pos.x+w/2, pos.y+h/2);//Text positioning
  }
  
  boolean isClicked() {
   return Clicked; 
  }
  
}

```

Result : "OK" is near Left Top Corner not in the middle
![SS](https://user-images.githubusercontent.com/55291701/64880190-3f607000-d660-11e9-9dee-f821d12e7c88.jpg)

**Comment by dzaima** [comment]
By default `rect()` takes arguments as `rect(xPos, yPos, width, height)`. Note that the last two aren't the other corners coordinates, but the size of the rectangle. This can be changed by using `rectMode(CORNERS)` beforehand. (though for you changing the usage would make more sense)

Also, [the Processing forums](https://discourse.processing.org) would be a more appropriate place for such questions, as this isn't a problem/bug in Processing but your code.

**Comment by uPixelar** [comment]
Thanks, closing issue.
