### ISSUE TITLE
Ant run doesn't seem to work

### ISSUE THREAD

**Issue by HarlanJ** [processing/processing#5923]
When running `ant run` in the build folder, processing does not open.

I think it has to do with the license acceptance stuffs that Oracle has you do when you download the JRE, and the (new?) requirement that you be logged in to download from the archive.

I'm running Ubuntu 19.04, Oracle java 1.8.0_202, build 08. 64-bit. This is on the most recent version of the github repo. 

here's a pastebin of the spew when I run `ant run` https://pastebin.com/980S8sZJ

**Comment by dzaima** [comment]
There have indeed been mentions of the 1.8.0_202 requirement (e.g. [here](https://github.com/processing/processing/wiki/Build-Instructions/_compare/9a4a81b6c84f820e973a510856d6145eda496682...e5931a5856beeb265b9f5d8185f2b131b7e17520?short_path=1f7d75c#diff-1f7d75cac6a53d885ad1d8d5bfa55abb) and [here](https://github.com/processing/processing/commit/37108add372272d7b1fc23d2500dce911c4d1098) though I thought there was a more proper place with that info) though it is strange that the build script doesn't find it if it's installed. I'd try symlinking whatever place contains your Oracle Java JRE 1.8.0_202 installation to `/usr/lib/jvm/jre1.8.0_202`, but that's by no means a normal/proper fix.

As a side-note, there is [this](https://github.com/sampottinger/processing) which completely gets around the issue by using OpenJDK, but that may not be suitable for your building needs as it also changes many other things.

**Comment by HarlanJ** [comment]
The java 1.8.0_202 requirement is in the build instructions as well, which is why I've used it. My 1.8.0_202 install is actually there, so no need to symlink. 
![image](https://user-images.githubusercontent.com/21362563/64988138-c5ff9200-d898-11e9-819e-4b51769eb7a9.png)

**Comment by Sardtok** [comment]
Did you look at the error message at the top of the build log? It complains about not finding tools.jar. Did you look in the directory if the tools.jar is there? Do you have the appropriate rights to the file, perhaps you need to chmod or chown something.

**Comment by dzaima** [comment]
@Sardtok a bit below it says `Ignore the 'Unable to locate tools.jar' message. The tools.jar file is not required to build Processing.`

An option would be to manually download & place the JRE file in the [proper path](https://github.com/processing/processing/blob/37108add372272d7b1fc23d2500dce911c4d1098/build/build.xml#L219) - something like `/build/linux/jre-8u202.tgz`. Currently as it seems Processing doesn't make any attempt of using any installed JRE.

**Comment by HarlanJ** [comment]
@dzaima I'll try that in a bit, and let you know if it works.

**Comment by HarlanJ** [comment]
@dzaima Didn't work, I'm gonna do some digging around and try to fix the script to use a version it can access, maybe skip over trying the download, I think maybe the 404 is causing it to give up.

**Comment by HarlanJ** [comment]
Got it working, not sure what fixed it, I don't think I actually have changed anything, but it's using the jre in the linux folder now!
