### ISSUE TITLE
Shapes on P3D leave "traces" error

### ISSUE THREAD

**Issue by danieltorrer** [processing/processing#5928]
## Description
When running any sketch with P3D all shapes leave a "trace" as they move. Strange enough when I render the same shape but using `PGraphics` the traces dont appear.

## Expected Behavior
Shapes move without leaving a trace

## Current Behavior
Shapes leave "traces" when moving.
![draw](https://user-images.githubusercontent.com/2329316/65830511-6fd71980-e2b0-11e9-9b85-ef574464ebb7.png)

## Steps to Reproduce

Any moving P3D will do it. 

```
void setup() {
  size(640, 360, P3D); 
  background(0);
  lights();
}
void draw() {
  background(0);
  noStroke();
  pushMatrix();
  translate(130, height/2, 0);
  rotateY(1.25);
  rotateX(radians(frameCount));
  box(100);
  popMatrix();
}

void keyPressed() {
  saveFrame("###.png");
}
```

If you export the image, or use a `PGraphics` and then `image()` to draw to screen, the error doesnt appear.
![182](https://user-images.githubusercontent.com/2329316/65830537-ba589600-e2b0-11e9-8407-cf2f1515b3cc.png)

## Your Environment

Dell XPS 9360 - Win 10
Processing 3.3.6 (but can confirm that also appears in new versions)
java version "1.8.0_221"

## Possible Causes / Solutions
Tried on a MacBook Pro and the error doesnt appear. So could be windows related

Seems also to affect `background()` in the following image you can see the sketch version and the exported version, Please also note the "traces" on the shape's edges 

![errordraw](https://user-images.githubusercontent.com/2329316/65830648-8f227680-e2b1-11e9-808f-fab1b3bd1d79.png)

**Comment by benfry** [comment]
Looks like weird rounding errors causing artifacts when run on that other machine. It's probably an issue that requires 1) updating your drivers, 2) messing with your anti-aliasing settings, or 3) using a better graphics card (if that's an option) on the device that's having trouble. But in any case, it's unlikely to be a Processing bug.
