### ISSUE TITLE
Processing won't run any sketch

### ISSUE THREAD

**Issue by srnlytx** [processing/processing#5930]
Hi, I downloaded Processing today and I learned to write some codes on it. However, Processing doesn't run any of my sketches on my laptop. I tried my codes on different computers and they were just fine. When I hit the Run button, it freezes and after some time it continues to work but it doesn't run my sketch, it doesn't do about running. What is the problem?

**Comment by benfry** [comment]
Because I'm not an omnipotent mind-reader I don't know what's wrong with your laptop. 

But as mentioned in the text you deleted before submitting this, https://discourse.processing.org is a better way to get help with this kind of problem.
