### ISSUE TITLE
Obj file didn't loaded correctly

### ISSUE THREAD

**Issue by zz-zsys** [processing/processing#5931]
## Description

I try to load an object file [(Link to the .obj file)](https://drive.google.com/file/d/1mBaGpzjOTu5WbQEZ95gzM5QyuXGThOiO/view) 
using LoadDisplayOBJ example from the IDE. However the loaded object doesn't looked as expected. On the obj 3d model, there should be 3 leds on the right side, but on the display it is shown on the left side. I try to view the obj file using two different online viewer [(3dviewer.net](https://3dviewer.net/) and [(creator3d.com](https://www.creators3d.com/online-viewer). Using both platform, the displayed model was as expected. 
## Expected Behavior

Example: Three led (circle) should be on the right side instead of on the left side. Here is the snapshot: [IOT585 snapshot](https://drive.google.com/file/d/1kUUfQMLCOBrSVdodyXGvLOrJBlU0DUzq/view?usp=sharing)

## Current Behavior

See expected behavior

## Steps to Reproduce

1. Run the LoadDisplayOBJ example from the IDE.
2. Change the data files with the IOT585 from the links.
3. Observe the object.

## Your Environment

 

* Processing version: Processing 3.5.3
* Operating System and OS version: Windows 10
* Other information:

## Possible Causes / Solutions

Unknown.

**Comment by zz-zsys** [comment]
Update to the issues:

In my default program, scale(40) was used and this behaviour is observed.

But if scale(-40) is used, the expected model is rendered correctly. 

Is there any reason why this happen?

**Comment by jeremydouglass** [comment]
This is a probably a programming question -- please first open a discussion on the forum: http://discourse.processing.org

scale(-1) mirrors the coordinate space, so that:

-1 ---- 0 ----- 1
 
becomes

1 ----- 0 ---- -1
