### ISSUE TITLE
Problem with the Files menu in the Reference page

### ISSUE THREAD

**Issue by morpurgo** [processing/processing#5932]
When the Reference page is open, the Files menu contains
![FilesMenu1](https://user-images.githubusercontent.com/3214856/66133806-94f0c280-e5f7-11e9-99bf-a5d2c3ecdeb9.png)
But, after searching the web page for "createW", its contents modifies to
![FilesMenu2](https://user-images.githubusercontent.com/3214856/66133961-d5504080-e5f7-11e9-8e0b-ee7cc16dcc4c.png)

Best regards,
Giulio

P.S. is there a way of having all the reserved keywords in alphabetical order? Sometimes one does not know which section contains a given keyword

**Comment by jeremydouglass** [comment]
This is the repo for Processing software. Please report issues with the website to 

https://github.com/processing/processing-docs/issues

Also, the Reference page is not changing

https://processing.org/reference/

Hit "Find" in your browser, and look for "Files." You will find two sections:

1. Input : Files
2. Output : Files

That is why one section contains load load load methods, and the other contains save save save methods.
