### ISSUE TITLE
Unsecure URL for contrib list

### ISSUE THREAD

**Issue by pacien** [processing/processing#5936]
The contribution list is downloaded from an unsecure URL:

https://github.com/processing/processing/blob/48b44cb303d1ac95fbe9355f3896b84a4aa69f05/app/src/processing/app/contrib/ContributionListing.java#L44

Someone on the same network as the user could intercept this request and substitute package URLs at will, which would then be downloaded, installed and executed on the user's machine.

Please use some digital signature for this package list, or at least use HTTPS and verify the certificate.
It would be a good idea to do some hash pinning for the packages as well.

**Comment by benfry** [comment]
Even for as far-fetched as that scenario might be, to fix it would mean breaking all existing versions of Processing that are out there. In the future we'll move to https, but we can't do it for existing releases.

**Comment by pacien** [comment]
Using HTTPS for newer versions while leaving the previous ones as they are seems fine.
Why close this issue though?
