### ISSUE TITLE
square() function doesn't turn blue in the editor

### ISSUE THREAD

**Issue by wiskiv1** [processing/processing#5939]
## Description

The square() function doesn't turn blue in the editor when i use it
## Expected Behavior

The text "square" in "square();" should turn blue
## Current Behavior

It stays black like it's a none processing function even tho its on the processing reference
## Steps to Reproduce

1.open Processing
2.type "square();"
3.see how text doesn't turn blue like other processing functions
4.It's really simple

## Your Environment

 

* Processing version: 3.5.3
* Operating System and OS version: windows 10 home
* Other information:

## Possible Causes / Solutions

just change the collor, all the other functions have it otherwise it feels neglected

**Comment by kfrajer** [comment]
The OP is referring to this:
https://github.com/processing/processing/blob/master/java/keywords.txt

I can reproduce in Win10 x64 and P3.5.3 

Kf.

**Comment by benfry** [comment]
Working in 3.5.4.
