### ISSUE TITLE
P2D black margins on top and right side

### ISSUE THREAD

**Issue by saesols** [processing/processing#5940]
## Description
When using size with P2D the actual canvas is shifted left and down and black margins appear on right and top. With default render everything works fine, but image in my app becomes blurry. 
[Screenshot](https://pasteboard.co/ICQ5D3g.png)

## Expected Behavior
Background color (red in my example) fill all the window

## Current Behavior
As in description

## Steps to Reproduce
Code included

## Your Environment

* Processing version: Can't find. Comes as embedded library in Unfoldingmap.
* Operating System and OS version: win10
* Other information: latest driver for Nvidia 1060 ti

```
/**
 * Hello World!
 * 
 * This is the basic stub to start creating interactive maps.
 */
public class HelloUCSDWorld extends PApplet {

	public void setup() {
		size(800, 600, P2D);
	}

	public void draw() {
		background(255, 0, 0);
	}
	static public void main(String args[]) {
		PApplet.main(new String[] { HelloUCSDWorld.class.getName() });
	}

}

```

**Comment by clankill3r** [comment]
You can upload images to github. Your image link is a dead link already.

**Comment by dzaima** [comment]
This is definitely an old version of Processing - that window icon hasn't been used for a while, and neither is `size()` allowed in `setup` now, so the problem may be fixed in the latest version.

**Comment by jeremydouglass** [comment]
> Processing version: Can't find. Comes as embedded library in Unfoldingmap

@saesols -- Where did you get that version of Unfoldingmap with Processing embedded? What Unfoldingmap version?

**Comment by benfry** [comment]
Closing since no response & using an old version of Processing.
