### ISSUE TITLE
Issue with multi monitors

### ISSUE THREAD

**Issue by jdroo** [processing/processing#5941]
okay

**Comment by jdroo** [comment]
Description

Okay I have 4 monitors, and i have my main monitor using my Nvidia GeForce GT 1030, one other also shares this card, the other two are using my on board AMD Radeon HD 8670D.

The issue is when my main monitor is set to nvidia card there is an error when trying to run P3, the error being...
![javaw_yPUQbC2S1g](https://user-images.githubusercontent.com/13055804/67229068-2a65c200-f400-11e9-8ebd-7d1774b201ab.png)

Expected Behavior

shows boot up image, No error, Run as expected.

Current Behavior

Shows boot up image, gives error, never runs.

Steps to Reproduce

I have no idea. set main display to Nvidia? lol

Your Environment

    Processing version: Latest. [have tried upgrading and downgrading, all versions do it]
    Operating System and OS version: Windows 10 Enterprise.
    Other information: N/A

Possible Causes / Solutions

The only fix i found is temp changing my main monitor to one of the AMD ran ones. But I would like it if i could just keep my default using nvidia...

**Comment by kfrajer** [comment]
In the forum, try checking for "display" posts. I had a quick search in Google and Found some related links:

* https://forum.processing.org/two/discussion/11304/multiple-monitors-primary-dragable-secondary-fullscreen
* https://forum.processing.org/one/topic/latest-multiple-monitors-advice.html

For the last one, despite it says 2 month old, it could be actually more than 2 years old so take it with a grain of salt. 

Also, try most-pixels-ever as described here:
https://forum.processing.org/one/topic/splitting-screen-across-multiple-displays.html

Finally, did you read this: https://github.com/processing/processing/wiki/Window-Size-and-Full-Screen

Let us know what you tried and what did not work. Describe error messages and any other detail that could assist understanding your issue.

Kf

**Comment by clankill3r** [comment]
Try disconnecting you monitors connected to your AMD video card.
Then launch processing, then reconnect the monitors to the AMD video card.

**Comment by benfry** [comment]
No follow-up, closing.
