### ISSUE TITLE
Error occurring on startup (unable to load application)

### ISSUE THREAD

**Issue by jamesmckeand** [processing/processing#5943]
## Description

When trying to start the processing application I am faced with an error during startup. The error is displayed in a window that is attached below.
<img width="693" alt="Screen Shot 2019-10-26 at 7 11 27 PM" src="https://user-images.githubusercontent.com/57050436/67627196-7f9d3b80-f825-11e9-8517-9383ba5d95a1.png">
This error only began to happen when I updated my OS to Mac OS Catalina version 10.15. The error does not allow the application to run at all. The error window is presented and the application is quit when the ok is pressed in error window.
## Current Behavior

The processing application is unable to run due to an error during startup.

## Steps to Reproduce

1. This occurs when the application is clicked on and start up in initiated. 
2.
3.

## Your Environment

 

* Processing version: Version 3.5.3
* Operating System and OS version: Mac OS Catalina 10.15
* Other information:

**Comment by ElieDDD** [comment]
I have exactly the same problem, MacBookPro with Catalina, Processing cannot start 
<img width="1440" alt="Screenshot 2019-11-02 at 09 47 38" src="https://user-images.githubusercontent.com/30892423/68069292-1f8f2380-fd56-11e9-8ba8-f1db7b1d06be.png">

**Comment by benfry** [comment]
Please see the second item beneath the “Processing Won't Start” section of the Troubleshooting page: https://github.com/processing/processing/wiki/Troubleshooting#processing-wont-start-nothing-or-something-strange-happens-when-i-click-run

**Comment by N1U** [comment]
I also encountered the same problem.Did you find a solution?

*Processing 3.5.3
*macOS Catalina 10.15.2

**Comment by ellieddd** [comment]
No, it just doesn't work......:-/

**Comment by N1U** [comment]
> 不，那根本不起作用……：-/

您找到有效的解决方案了吗？

**Comment by N1U** [comment]
> No, it just doesn't work......:-/

Have you found an effective solution?

**Comment by N1U** [comment]
@ellieddd I found a solution, you can try this method.  #5970
