### ISSUE TITLE
[OSX] runSketch from P3D only works for P3D subsketches

### ISSUE THREAD

**Issue by onimatrix** [processing/processing#5945]
This happens in Processing 3.4 and OSX Mojave (10.14.6)

Main sketch uses P3D.
Second sketch uses default renderer.
App freezes if using runSketch to spawn the second sketch, no console output.

All other combinations (Default->P3D, Default->Default, P3D->P3D) work perfectly.
It also works as expected on Processing 3.4 and Windows 10.

Minimal (non)working example follows.

```
void settings()
{
  size(400, 300, P3D);  
}

void setup()
{  
  String[] args = {TestApplet.class.getName()};
  PApplet.runSketch(args, new TestApplet());
}

class TestApplet extends PApplet
{
  void settings()
  {
    size(300, 200); // Works if P2D or P3D
  }
};
```

**Comment by onimatrix** [comment]
It also happens in Processing 3.5.3.

**Comment by clankill3r** [comment]
For me it works fine on OSX 10.12.6 for processing 3.5.3.
Maybe apple is screwing things up again.

**Comment by benfry** [comment]
Definitely wouldn't use `runSketch()` this way (or call it, ever, for that matter). It's an internal function that's only available publicly so that other Mode authors (i.e. for Python Mode) can launch sketches. 

What you're seeing is probably a weird interaction between the EDT and the main thread (another reason you don't want to call things this way).

**Comment by clankill3r** [comment]
@onimatrix 
Getting multiple windows to work in processing in P2D / P3D is next to impossible. Codeanticode is working on LWJGL support to replace JOGL eventually and he is going to look for support of multiple windows. Don't expect this anytime soon.

I guess the best way for now is either have a sketch P2D and the other the JAVA renderer or something. Or split up in two sketches and use sockets to send messages if you have too.
If you need to share graphics you can look into syphon.

**Comment by onimatrix** [comment]
Thank you both for the feedback.
The project I'm working on can be found at www.voxedit.io, if you feel curious about the use case.
