### ISSUE TITLE
custom editor window height and width overwritten by hard-coded default

### ISSUE THREAD

**Issue by earthbound19** [processing/processing#5946]
If I set a custom window editor height and width higher than the "shipped" default and the minimum width and height to the same, processing overwrites both with the same lower hard-coded "shipped" default when I close Processing. I see this on Windows.

- open the file -> preferences menu
- click the link in the dialog to open the `preferences.txt` file
- change these preferences:

`editor.window.height.default=530`
`editor.window.height.min=530`
`editor.window.width.default=400`
`editor.window.width.min=400`

-- to these:

`editor.window.height.default=963`
`editor.window.height.min=963`
`editor.window.width.default=1386`
`editor.window.width.min=1386`

- save the `preferences.txt` file
- close all Processing sketches (and I would imagine, if this is duplicated on Mac, terminate Processing).
- reopen a processing sketch. _It doesn't use the specified windows sizes--it reverts to 400x530. This is reflected in `preferences.txt` as well.

Weirdly, it seems that it keeps the preferences if I keep `editor.window.height.min` and `editor.window.width.min` at lower values.

Double weirdly, this seems to be intermittent, or it only happened the first time ever that I saved `preferences.txt` with `~.default` and `~.min` at the same values. In subsequent tests it "stuck" if I set them both to different, identical, higher values, _or_ it "stuck" after I first saved it with lower `~.min` values, but then set the `~.min` values the same as `~.max` on subsequent tries. So set it twice and then it will respect it, or once with `~.min` values lower?!

Using Windows 7 x64 with most current OS patches, Processing 3.5.3

**Comment by benfry** [comment]
Don't edit the preferences file while Processing is running.
