### ISSUE TITLE
 'A library used by this sketch is not installed properly' with video on Linux

### ISSUE THREAD

**Issue by Alex-Delbrey** [processing/processing#5947]
Hello,

This is technically not a duplicated issue. I have been searching for this error online and the only solution I found is that the path to access Processing contains a character that is not an ASCII character. 

While I was exploring through the library file of video, I noticed that there is only a file for macosx64, windows32, and windows64 and when I looked through the library files of OpenCV, it contains the ones mentioned plus linux32 and linux64. Does this mean that the library for video does not support the Linux system?
If it does not, could there be a possible update on the library in order for it to support linux32, linux64, and macosx32, since those other systems would have the same problem?

Thank you!

**Comment by benfry** [comment]
The video library is a separate project, so you'll have better luck [at this link](https://github.com/processing/processing-video/issues).
