### ISSUE TITLE
Windows Downloads broken

### ISSUE THREAD

**Issue by markuszeller** [processing/processing#5948]
Both Windows Downloads 32 and 64 bit Download links are broken.

https://download.processing.org/processing-3.5.3-windows64.zip
https://download.processing.org/processing-3.5.3-windows32.zip

**Comment by kfrajer** [comment]
I just downloaded and install 3.5.3 Win 64 and it worked for me. Comparing your links to the ones in the Processing site, yours are using HTTPS. Use http instead:

`http://download.processing.org/processing-3.5.3-windows64.zip`

Kf

**Comment by markuszeller** [comment]
I am sorry. Did not think of disabling https everywhere.
