### ISSUE TITLE
Dowload link in HTTP and not HTTPS

### ISSUE THREAD

**Issue by sucrecacao** [processing/processing#5949]
The dowload links at https://processing.org/download/ only work on HTTP and not HTTPS, which is not very safe a binary

**Comment by PixsaOJ** [comment]
It redirects me to HTTPS, everything is broke on processing and p5js today. p5js has removed p5 dom library and documentation is gone. Now I cant download processing to code.

**Comment by REAS** [comment]
Please try downloading from Firefox or Safari or another browser that isn't Chrome. Chrome seems to be redirecting automatically to HTTPS. I'm trying to figure this out...

**Comment by D3add3d** [comment]
> 
> 
> Please try downloading from Firefox or Safari or another browser that isn't Chrome. Chrome seems to be redirecting automatically to HTTPS. I'm trying to figure this out...

Does not work in Firefox, it redirects to HTTPS too.

**Comment by PixsaOJ** [comment]
> > Please try downloading from Firefox or Safari or another browser that isn't Chrome. Chrome seems to be redirecting automatically to HTTPS. I'm trying to figure this out...
> 
> Does not work in Firefox, it redirects to HTTPS too.

I did it with Firefox. Try disabling extensions/use custom downloader. You can also use curl or wget.

**Comment by benfry** [comment]
Just finished reconfiguring the servers to support SSL for download.processing.org.
