### ISSUE TITLE
setAlwaysOnTop hangs in P2D

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#5951]
This code hangs:

```java

import processing.opengl.PGraphicsOpenGL;
import processing.opengl.PSurfaceJOGL;
import com.jogamp.newt.opengl.GLWindow;


void setup() {
  size(500, 500, P2D);
  PSurfaceJOGL psurface = (PSurfaceJOGL) surface;
  GLWindow gwindow = (GLWindow) psurface.getNative();
  gwindow.setAlwaysOnTop(true);
}

```

Processing 3.5.3
OSX 10.12.6

**Comment by jeremydouglass** [comment]
Hangs on Processing 3.4 OSX 10.12.6 as well.

What is this? Why are you doing it?

**Comment by benfry** [comment]
We can't really prevent you from doing weird things with the internals that are accessible, but there's just no way this can be considered our bug if you're calling a non-Processing method on the guts of the renderer…
