### ISSUE TITLE
Circle() not in keywords.txt

### ISSUE THREAD

**Issue by jeffThompson** [processing/processing#5954]
## Description
The `circle()` command doesn't highlight like `ellipse()`, etc – a look in `keywords.txt` shows that `circle()` isn't there but probably should be, since it's in the main reference.

## Your Environment
* Processing 3.5.3
* Mac 10.14.6

## Possible Causes / Solutions
Looking at `keywords.txt` there are some warnings not to modify the file – not sure where this is officially stored and/or generated. Happy to create a PR if I had a better idea what/where to change.

**Comment by Prometal328** [comment]
you should look for keywords_base.txt in the repo processing-documents.

**Comment by jeffThompson** [comment]
Thanks @Prometal328 – I posted this over there and will close this issue.
