### ISSUE TITLE
Processing Download Fail

### ISSUE THREAD

**Issue by FBSeletronica** [processing/processing#5955]
I Can't download Processing Linux package from the site.

I got this message: The requested URL was not found on this server.

Could someone fix it?

**Comment by Bobby54** [comment]
I just tested on Ubuntu, everything working fine.
I downloaded the Linux 64-Bit version and was able to use it how it is supposed to be.

**Comment by FBSeletronica** [comment]
Thanks @Bobby54 

I tried in another browser and works. 

However, I still receive this error in google chrome: 
Not Found
The requested URL was not found on this server.
Apache/2.4.18 (Ubuntu) Server at download.processing.org Port 443

**Comment by benfry** [comment]
Your browser is forcing SSL to a site (download.processing.org) that doesn't currently support SSL.
