### ISSUE TITLE
Push a Release

### ISSUE THREAD

**Issue by Julian** [processing/processing#5956]
Hi. Would it be possible to cut a new release?

The version currently available in e.g. Homebrew is the latest release (v3.5.3), which suffers from #5805.

Thanks.

**Comment by jeremydouglass** [comment]
When there *is* a new release, I believe the update for Homebrew cask will be reported to:

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/processing.rb

(I also believe that cask isn't maintained by this Processing foundation)

**Comment by benfry** [comment]
We don't have anything to do with the Homebrew release, and it's frustrating to get bug reports for it.
