### ISSUE TITLE
All downloads broken (404)

### ISSUE THREAD

**Issue by D3add3d** [processing/processing#5958]
## Description

All downloads seem to be broken, every download link at https://processing.org/download/ returns a 404 page.

## Expected Behavior

Every link on the download page should point to a valid location to download the described version of Processing.

## Current Behavior

Every link on the download page returns a 404 page.

## Steps to Reproduce

1. Go to https://processing.org/download/
2. Choose and navigate to any download link

## Your Environment

 

* Processing version: irrelevant
* Operating System and OS version: Windows 10 Pro, version 1903
* Other information: Browser: Firefox 70.0.1

## Possible Causes / Solutions

404 suggests that the files are actually gone or the path to them has changed.
502 would suggest that there is a reverse-proxy and the actual server that is serving the files is offline for some reason.

**Comment by D3add3d** [comment]
Update: downloads work using wget, possibly relates to #5949

**Comment by REAS** [comment]
The downloads are OK and the links haven't changed, but I think the behavior on some browsers have changed. I'm looking into this over at #5949 and I think this is a duplicate, so I'm closing it.
