### ISSUE TITLE
PDF file not searchable with Control F 

### ISSUE THREAD

**Issue by einarlorentzen** [processing/processing#5963]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

## Possible Causes / Solutions

0,

**Comment by jeremydouglass** [comment]
If your goal is to learn *how* to embed searchable text in a PDF, please open a discussion on the forum:

https://discourse.processing.org

Note that when you post there, this is not enough information! A PDF created by Processing? What kind of PDF? How was it created, with what code?
