### ISSUE TITLE
kindly whiteliste your XD software at chrome

### ISSUE THREAD

**Issue by Dj-jom2x** [processing/processing#5965]
![image](https://user-images.githubusercontent.com/12135498/70380231-b745ea00-1972-11ea-8a46-b60d511f9c98.png)

waste of bandwidth hahaha fuck this chrome

**Comment by jeremydouglass** [comment]
I was able to download `processing-3.5.3-windows64.zip` using Chrome 78.0.3904.108 with no "Virus detected" problem. @Dj-jom2x are you still having this problem? If so, what version of Chrome, and do you have extra virus scanner plugins installed?

**Comment by Dj-jom2x** [comment]
![image](https://user-images.githubusercontent.com/12135498/71093023-55437b00-21e3-11ea-809c-42ca133945fc.png)

**Comment by benfry** [comment]
As far as I know, we don't have any control over this. If someone knows otherwise, or how we can apply for whitelisting, please open an issue with that information.
