### ISSUE TITLE
macOS processing unable to start "we're off on the wrong foot"-solved

### ISSUE THREAD

**Issue by N1U** [processing/processing#5970]
## Processing unable to start.
I have been using it normally before, and suddenly this appears today.
I don't understand deeper principles, but I haven't found a solution for a long time. Hope you all help me, thank you very much.

Much like [＃5943](https://github.com/processing/processing/issues/5943) problem, but the solution in [＃5943](https://github.com/processing/processing/issues/5943) does not solve the problem
<img width="779" alt="processing-error" src="https://user-images.githubusercontent.com/20842136/70897026-cdb40b80-202c-11ea-856c-17bce5bbb402.png">
## Steps to Reproduce
01. Start processing
02. Prompt "we're off on the wrong foot", Click ok, the program closes.
03. Execute `cd /Applications
./Processing.app/Contents/MacOS/Processing ` prints `minRe`
## Environment
* Processing 3.5.3 
* macOS Catalina 10.15.2

## solved: ##
I found the solution!
[Processing won't start up(using OSX Mavericks](https://forum.processing.org/two/discussion/1218/processing-won-t-start-up-using-osx-mavericks) to the author of this article.
**Solutions**
1. Open Finder and execute shift + cmd + G, type ~/Library/Application Support ,click ok.
2. find the “processing” folder here and delete it.
3. finally download and start the latest processing

**Comment by ellieddd** [comment]
Thanks for posting the solution, I will try it !

**Comment by jeremydouglass** [comment]
@N1U -- did you mean to reopen this issue, or should it be closed?

**Comment by N1U** [comment]
> @N1U -- did you mean to reopen this issue, or should it be closed?

I needed to add something after closing, so I reopened the issue. Now I want to close it.
