### ISSUE TITLE
mouseClicked not seen

### ISSUE THREAD

**Issue by kllsamui** [processing/processing#5971]
see possibly connected:
https://github.com/processing/processing/issues/4687
there it was reported ( but linked to OPENGL )

## Description
processing not always see mouseClicked()
esp. bad 
- - when mouse is moving
- - after sketch start

if not a processing bug ( JAVA 8), discourage to use  mouseClicked(), 
mousePressed() works well.

## Steps to Reproduce
```
void setup() {
  size (500, 500);
  strokeWeight(5);
}

void draw () {}

//void mousePressed() {  // works good 
void mouseClicked() {
  point(mouseX,mouseY);
  println("mouse clicked at " + mouseX + "/" + mouseY);
}

```

tested: 
* win 10 64 bit / processing 3.5.3 64bit
* Raspian buster / processing 3.5.3

* Other information: forum:
https://discourse.processing.org/t/mouse-is-very-slow/16423/11
reported by @fredstout

## Possible Causes / Solutions
suspect timer / logic conflict mouseDragged()

**Comment by benfry** [comment]
If there's any movement in the mouse, a “clicked” event may not fire. That would cover the % of events that are being missed. 

If you just need to know the mouse is down, just track the press event instead.
