### ISSUE TITLE
importing libraries

### ISSUE THREAD

**Issue by rajat98dogra** [processing/processing#5973]
Hello!...I want to import some python libraries into Processing 3 env. 
Please guide me . If this feature is not available then you can add this connective if you want.
thank you.

**Comment by kfrajer** [comment]
Hello,
This site is meant to track issues and feature requests for Processing related to the IDE, core, java mode, etc. I suggest you open a thread in the [Processing Forum](https://discourse.processing.org/) first to understand what you need to do. 

There is no support for the nature of your question here.

Kf
