### ISSUE TITLE
Communication between Arduino and Processing

### ISSUE THREAD

**Issue by muhammadbilal125** [processing/processing#5974]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by muhammadbilal125** [comment]
Can anyone guide me to run a video on arduino by using processing. A video can be runon processing but how i can run a video on arduino through processing. Kindly urgently give em some solution..

**Comment by kfrajer** [comment]
Hello,
This site is meant to track issues and feature requests for Processing related to the IDE, core, java mode, etc. I suggest you open a thread in the [Processing Forum](https://discourse.processing.org/) first to understand what you need to do.

There is no support for the nature of your question here.

Kf
