### ISSUE TITLE
 How i can give path of the video to run on processing software?

### ISSUE THREAD

**Issue by muhammadbilal125** [processing/processing#5976]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by kfrajer** [comment]
Hello,
This site is meant to track issues and feature requests for Processing related to the IDE, core, java mode, etc. I suggest you open a thread in the [Processing Forum](https://discourse.processing.org/) first to understand what you need to do.

There is no support for the nature of your question here.

Kf
