### ISSUE TITLE
install script links to old version

### ISSUE THREAD

**Issue by kllsamui** [processing/processing#5980]
## Description
using
```
curl https://processing.org/download/install-arm.sh | sudo sh
```
installs 3.5.3

## Expected Behavior
should install 3.5.4

## Current Behavior
but installs old version

## Your Environment
* Operating System and OS version:
Raspbian Buster on Raspberry Pi

**Comment by benfry** [comment]
The ARM maintainer quit so there's no ARM build for 3.5.4, you'll have to use 3.5.3 or build your own. That's why it's not listed on the download page.

**Comment by kllsamui** [comment]
> The ARM maintainer quit so there's no ARM build for 3.5.4,... 
 ..build your own.

i would love to do that / or even get that 'open job',
who can help me to get started?
