### ISSUE TITLE
Processing Fresh Download Very Slow to Open and also to Run Examples

### ISSUE THREAD

**Issue by noxiddd** [processing/processing#5986]
#5334  Description

Opening and running a simple sketch(one of the examples) takes an extended amount of time 
Examples attemted: Brightness/Relativity/Hue

## Expected Behavior

Opening shouldn't be more than a minute and running the examples should take 20 seconds max i think.

## Current Behavior

Running a simple sketch takes minutes, the play button is highlighted suggesting a sketch is running, but nothing pops up for upwards of 5 minutes, even when running the basic examples that comes packaged with processing, 

## Steps to Reproduce

1.Just download the latest procssing version 3.5.4 in my case 
2.Try opening, takes forever
3.Try running a skecth, takes forever

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: Windows 8
* Other information:

**Comment by benfry** [comment]
Try turning off any virus scanning software you have running. That’s usually what causes this problem.

**Comment by noxiddd** [comment]
thanks, it fixed the issue
