### ISSUE TITLE
error while trying to get the sketchbook.....why?

### ISSUE THREAD

**Issue by chennatrinath** [processing/processing#5990]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by jeremydouglass** [comment]
**Please don't post a question with no details!**
What error? What version of processing? How did it happen? Without details, this issue will be closed.

**Comment by benfry** [comment]
No response; closing. This belongs on https://discourse.processing.org/ anyway…
