### ISSUE TITLE
P2D Hangs if no internet connection

### ISSUE THREAD

**Issue by CallumHoward** [processing/processing#5991]
## Description

Hi, I have encountered an odd error which I narrowed down with the following minimal repro:

```java
void settings() {
  size(500, 500, P2D);
  pixelDensity(1);
}
```

This sketch works fine if the computer is connected to a network with internet connection, or if the wifi is turned off, however it does not work if connected to a network without internet connection. It hangs on start. Adding println statements show that it does complete the settings function, but nothing after that. The problem doesn’t manifest if JAVA2D or FX2D are used, however they provide a signifigantly worse framerate for my current application.

Note the repro above is a minimal repro, the problem has been occurring with proper sketches with `setup` and `draw` functions.

Any help would be appreciated!

Processing 3.5.4
MacOS 10.15.1
MacBook Pro 15" 2012, 2880x1800, NVIDIA GeForce 650m, OpenGL version 4.1 NVIDIA-14.0.31

Seems to work fine on Windows.

I tried both a basic router and also an ESP32 microcontroller set up as an access point - I think this detail is probably not relevant though.

Forum link: https://discourse.processing.org/t/p2d-hangs-if-no-internet-connection/17633

## Expected Behavior

Expect no hang when using P2D on a router with no internet.

## Current Behavior
Hangs as described.

## Steps to Reproduce

Use snippet from above as full sketch, run on macOS. Run with a router with no internet.

## Your Environment

 

* Processing version: Processing 3.5.4
* Operating System and OS version: MacOS 10.15.1
* Other information: MacBook Pro 15" 2012, 2880x1800, NVIDIA GeForce 650m, OpenGL version 4.1 NVIDIA-14.0.31

**Comment by jeremydouglass** [comment]
Please consult the forum for help on this -- this is a network configuration problem. PDE requires local network access to communicate with a sketch. If your network is misconfigured or it is blocked by firewall et cetera it cannot do this.

Forum: https://discourse.processing.org/

Related post from previous forum:

https://forum.processing.org/two/discussion/12578/sketches-not-running#latest

**Comment by benfry** [comment]
Yeah, sounds like a routing problem. Also make sure you haven't messed with `/etc/hosts`, which can cause similar issues. Regardless, not a Processing issue…
