### ISSUE TITLE
Graphics not updated on clientEvent()

### ISSUE THREAD

**Issue by hkiel** [processing/processing#5992]
## Description
Graphics commands from `clientEvent()` are ignored.

## Expected Behavior
Should be displayed

## Current Behavior
Nothing is shown

## Steps to Reproduce
```
// Server Sketch, start first
import processing.net.*;
Server s;

void setup() {
  background(255);
  strokeWeight(5);
  s = new Server(this, 12345);
  noLoop();
}

void draw() {
  println("redraw!");
}

void serverEvent(Server someServer, Client someClient) {
  println("new client" + someClient.ip());
  redraw();
}

void clientEvent(Client someClient) {
  stroke(255, 0, 0);
  int[] data = int(split(someClient.readString(), ','));
  point(data[0], data[1]);
  println("draw point at", data[0], data[1]);
  redraw();
}

void mousePressed() {
  stroke(0, 0, 255);
  point(mouseX, mouseY);
  redraw();
}
```

```
// Client Sketch, start later and click in window
import processing.net.*;
Client c;

void setup() {
  c = new Client(this, "127.0.0.1", 12345);  
  noLoop();
}

void draw() {
}

void mousePressed() {
    c.write(mouseX+","+mouseY);
}

```
When clicking into client's window the click-coordinates are sent to the server and shoud be displayed there as red dots. The graphics is not displayed at all, though the "redraw!" text from `draw()` is printed (however in the wrong console - see #5774)

## Your Environment
* Processing version: 3.5.4
* Operating System and OS version: macOS Mojave
* Other information:

**Comment by jeremydouglass** [comment]
Are you able to run the reference example sketch that changes the `background()` from `clientEvent()`?

https://processing.org/reference/libraries/net/clientEvent_.html

or is that not working either?

**Comment by hkiel** [comment]
@jeremydouglass That example is also not working for me. I see `Server says:  <changing number>` on the console, but the background does not change.
I just checked on a windows10 machine and see the same bug (also v3.5.4).

I know that this worked in a previous version of processing.

**Comment by hkiel** [comment]
I checked processing versions down to 3.0 and graphics update only works sporadically ( = only for a few messages received). In all cases the graphics is not updated for most (>99%) of the messages. The text on the console is always there and gives reasonable values.
Can anyone confirm this bug?

**Comment by jeremydouglass** [comment]
I don't work with the Network library often, but if you are interested in getting community members to help narrow it down then I would recommend also creating a post on the forum, here:

https://discourse.processing.org/c/processing/processing-libraries

A workaround (there are many libraries that do not support drawing from hook functions) is to set your values in clientEvent() to state variables / objects and then draw from that updated state in draw(). That doesn't resolve the question of whether or not this is a bug, of course -- just suggesting it if you are blocked.

**Comment by kfrajer** [comment]
I recommend to update the sketch only on draw as a best practice. The client example above should be updated to reflect this.  I will let the owners of the repo correct me if I'm wrong. -Kf

**Comment by benfry** [comment]
Graphics can/should only be updated inside `setup()` or `draw()`. The mouse and key events also hide this complexity (by storing key/mouse events and playing them back at the bottom of `draw()`). 

Looks like the doc for `clientEvent` needs to be fixed, though, since it's doing a `background()` call.
