### ISSUE TITLE
Processing 3.5.4 onto Raspberry Pi 4: No Java Virtual Machine

### ISSUE THREAD

**Issue by SLIMprojects** [processing/processing#5996]
I am having issues opening the latest version of Processing onto my Raspberry Pi 4 after following this tutorial (which I know is from an older version): http://helloraspberrypi.blogspot.com/2016/04/install-processing-on-raspbian-jessie.html

The error messages I'm receiving say that the library extension is not supported and to "use ~classpath instead" (screenshot attached).
![IMG_7188](https://user-images.githubusercontent.com/49345892/74553061-2bc17a00-4f1c-11ea-9140-a2c951410b6a.jpeg)

Any thoughts?

**Comment by benfry** [comment]
https://discourse.processing.org/ is a better place for asking questions like this that are specific to your system, or someone else's tutorial that we didn't write.
