### ISSUE TITLE
过来学习一下，很早之前翻译了两本Processing的书

### ISSUE THREAD

**Issue by lifengquan52** [processing/processing#5998]
过来学习一下，很早之前翻译了两本Processing的书，现在学习一下怎么提交Github issue。 
Probably your code does not have any problem. I just want to confirm the whole progress is right that I could submit the Github issue.

**Comment by jeremydouglass** [comment]
Google Translate: "Come and learn, I translated two Processing books a long time ago, now I will learn how to submit a Github issue."

@lifengquan52 -- 您翻译了哪两本书？Which two books did you translate?

Please do not open test issues. If you have questions about submitting issues, but you do not have a real issue, then please start a conversation on the forum instead:

https://discourse.processing.org/
