### ISSUE TITLE
Calling frameRate() in settings() fails with NullPointerException

### ISSUE THREAD

**Issue by jrichardsen** [processing/processing#6000]
## Description
Calling `frameRate()` inside `settings()` throws a `NullPointerException`

## Expected Behavior
Setting the frame rate in the `settings()` method should work, also it is the recommended place for setting the frame rate ([Docs](https://processing.org/reference/frameRate_.html))

## Current Behavior
In order to work properly, `frameRate()` has to be called after `PApplet.runSketch()`

## Steps to Reproduce
```java
@Overwrite
public void settings() {
    frameRate(30);
}
```

## Your Environment

 

* Processing version: 3.5.3
* Operating System and OS version: Ubuntu Linux 18.04
* Other information:

## Possible Causes / Solutions

The exception is thrown, because inside `PApplet.runSketch()` `handleSettings()` is called before `surface` is initialized and `frameRate()` calls `surface.setFrameRate(float)`.

Therefore, a solution might be to pre-initialize `surface` (see first two lines of `initSurface()`), then call handleSettings(), and then call `initSurface()` which obviously should then not create a new `PSurface`, but instead just change the existing `this.surface` (To implement this, it should be sufficient to delete the first two lines of `initSurface()`, therefore removing the declaration of the local `surface` variable, which should change the following occurences to refer to the `surface` attribute instead)

**Comment by jrichardsen** [comment]
Ok, I was under the impression that you should use `settings()` instead of `setup()` for programming outside of the Processing IDE in *every* case. Apparently just setting the frame rate inside `setup()` works as intended.

**Comment by jeremydouglass** [comment]
That is correct -- `settings()` is "only useful when it's absolutely necessary to define the parameters to size() with a variable." Everything else can go in `setup()`. https://processing.org/reference/settings_.html

As a rule, `size()` should be defined as early as possible -- in settings or as the first statement in `setup()`.
