### ISSUE TITLE
freeglut (foo): failed to open display

### ISSUE THREAD

**Issue by Allwin12** [processing/processing#6003]
## Description
Hi I have a running ec2 instance(ubuntu 18.04). we use opengl to generate graph. On local everything works fine. But we are getting an error like this "freeglut (foo): failed to open display" on the ec2 instance. Any solutions would be great.

**Comment by benfry** [comment]
There are some headless instructions here: https://github.com/processing/processing/wiki/Running-without-a-Display

But this isn't the place for troubleshooting your setup… please use https://discourse.processing.org/ for open-ended questions like this.
