### ISSUE TITLE
“Can't find folder: 646c6962” for getLibraryFolder() on startup

### ISSUE THREAD

**Issue by masteroGoGo** [processing/processing#6017]
After installing processing, I opened it and I get an error message

<img width="760" alt="Screenshot 2020-03-30 at 1 17 40 AM" src="https://user-images.githubusercontent.com/62854053/77859068-eb486200-7224-11ea-9fe4-dc21cfb1a178.png">

**Comment by jeremydouglass** [comment]
Please don't ignore the basic information requested in the issue template

> ## Your Environment
> <--- Include details about your environment. -->
> <--- Thousands of people use Processing every day and may not have --> 
> <--- this issue, this might give us clues about why you’re seeing it. -->
> * Processing version:
> * Operating System and OS version:

**Comment by masteroGoGo** [comment]
I'm a designer and I have very little knowledge about these things, can you elaborate a bit more on how I should proceed? It would be of great help :)

**Comment by masteroGoGo** [comment]
System : MacOS Mojave
Version : 10.14.6
Processing : 3.5.4

**Comment by benfry** [comment]
Has your ~/Library folder been renamed in a non-standard way? Do you have additional security settings on your machine? Have you modified the Processing application or the version of Java that it's using?

**Comment by TaylorHokanson** [comment]
I'm having this same error message, also running OSX 10.14.6. I get the error for both Processing 3.5.4 and 3.5.3 (which was previously installed and working). To my knowledge I have not modified the application or Java. My security settings are the defaults.

**Comment by TaylorHokanson** [comment]
A simple restart seemed to fix it. Will report back if the issue persists.

**Comment by benfry** [comment]
No further response; closing.
