### ISSUE TITLE
PShape.fill() & PShape.stroke() replaced by fill() & stroke() when in thread

### ISSUE THREAD

**Issue by clementballot38** [processing/processing#6018]
## Description

A class that extends Thread and creates PShape(s) into its void run() can produce shapes with wrong fill/stroke color if draw() uses fill() and/or stroke() with different values. As example, if a thread creates a blue shape and draw() draws a black text, sometimes the shape will be black too. You may need to create a lot of shapes into void run() to see the bug. I saw this issue when P3D was defined as renderer (didn't tested with other renderers).

## Expected Behavior

PShape.fill() and PShape.stroke() have priority to fill() and stroke().

## Current Behavior

fill() and stroke() before beginShape() changes shape's stroke/fill color, after beginShape() if PShape.fill()/PShape.stroke() is used, any fill()/stroke() will have no effect to the shape.

## Steps to Reproduce

1. Create a class extended by Thread and create shapes into its void run() (may need lot of shapes to see the bug)
2. Put simple code that use fill() and/or stroke() into void draw()
3. When shapes are created, display it : some shapes will have wrong fill/stroke color

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: Windows 10 Pro x64 version 18363

**Comment by dzaima** [comment]
I'm pretty sure `PShape`s weren't meant to be multithreadable in general, and [drawing definitely isn't](https://processing.org/reference/thread_.html).

Otherwise, I can't reproduce the bug - do you have some example code?

**Comment by clementballot38** [comment]
Here is an example of what I'm talking about.
The blocks should not be strocked or filled (some are black). If move all the run() content to the class constructor there is no problem.

[mc_test.zip](https://github.com/processing/processing/files/4443839/mc_test.zip)

**Comment by dzaima** [comment]
So..

[`PGraphicsOpenGL` sets the `tint` color to the fill color](https://github.com/processing/processing/blob/3952f6f7247dba50920662da3276e91166426fb7/core/src/processing/opengl/PGraphicsOpenGL.java#L3547) to function, and [`PShapeOpenGL` copies it](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PShapeOpenGL.java#L368) while the text is being drawn, resulting in the weird coloring.
There's probably something similar happening with texture offsets (e.g. add `noTint()` at every created shape and look closely - the texture is still there, but at a strange offset).

This tells me that `PShape` creation, indeed, isn't meant to be multithreaded.

**Comment by jeremydouglass** [comment]
I believe that almost nothing (or nothing at all) in Processing is intended to be multithreaded....

**Comment by clementballot38** [comment]
OK thanks, not an issue then… It could be nice to have a future update to bring multithreading rendering.
Thanks for your help !
