### ISSUE TITLE
Inheritance from Exception Issue

### ISSUE THREAD

**Issue by real-yfprojects** [processing/processing#6019]
I couldn't find anything about this Issue.

## Description
When creating your own Exception by extending from Exception or java.lang.Exception, the Constructors defined by Exception aren't inherited. There is a "workaround". But this seems to be a bug nevertheless.

## Expected Behavior
The Constructors `Exception(String msg)` and `Exception(String msg, Exception e)` should be inherited. So that the only code needed for creating an Exception is:

```java
class MyException extends Exception{}
```

## Current Behavior
Currently the compiler (i think) raises the error 
> The constructor MyException(String) is undefined

## Steps to Reproduce
This code demonstrates the Issue and a workaround.

```java
//import java.lang.Exception;  //Doesn't matter

class MyException extends Exception{}

class Workaround extends Exception{
  Workaround(String msg){
    super(msg); //Exception(String) does exist
  }
}

class Test{
 
 public void test1() throws MyException{
  throw new MyException("This is not possible"); // The constructor MyException(String) does not exist
 }
 
 public void test2() throws Workaround{
   throw new Workaround("This is a workaround");
 }
}

void setup(){
  Test t = new Test();
  try {
    
    t.test1();
   
   } catch(Exception e){println(e);} try{
     
     t.test2();
   
   } catch(Exception e){println(e);} 
}
```
I didn't find a build folder.

## My Environment
Processing 3.5.4
Windows 10 Home 1909

**Comment by dzaima** [comment]
This is just now how Java works. You must always specify every constructor you want to use on a particular class. Constructors aren't inherited.

**Comment by jeremydouglass** [comment]
Many tutorials and explainers on this here:
https://www.google.com/search?q=java+constructors+inheritence

**Comment by real-yfprojects** [comment]
Thank you!
For some reason, it doesn't say anything about that in my Java book.
I am sorry to have bothered you.
