### ISSUE TITLE
Error with frame extraction  - Funtion captionLabel does not exist / Size

### ISSUE THREAD

**Issue by AdriAdriADri** [processing/processing#6022]
I'm new to Processing and I ran it for the first time following the instructions given in this video: https://vimeo.com/134367767

I'm running Processing 2.2.1 on a Mac. 

I downloaded the libraries (ControlP5 and OpenCV), opened mm16_frame_extracion_multiple and followed the instructions. When I try to run the program I get this error message:

> The function captionLabel() does not exist.

I then tried with the newest version of Processing (3.4.5). I got a different error: 

> Please fix the size() line to continue

Can you help me on this? What am I supposed to do?

Thank you very much!

**Comment by ljcontrerasguz** [comment]
any luck on this event? having the same error.

**Comment by benfry** [comment]
You should probably contact the person who created the video, or you could see if someone on the forum would like to figure it out with you: https://discourse.processing.org/
