### ISSUE TITLE
[Feature] Dictionary with CLI arguments

### ISSUE THREAD

**Issue by friaca** [processing/processing#6024]
## Description
When running a sketch through the Processing CLI, have some way to name the arguments.

## Expected Behavior
Execute something like:
`C:\Processing\processing.exe --sketch=C:\ProcessingSketches\SomeSketch --run --first=somestring --second=1957 --third`
and be able to access a dictionary with the additional arguments to get:
`{
  first: "somestring",
  second: "1957",
  third: true
}`
(doesn't necessarily need to convert types in the case of "value-less" arguments, can be all passed to this dictionary as strings).

## Current Behavior
Right now you can pass arguments to sketches like this:
`C:\Processing\processing.exe --sketch=C:\ProcessingSketches\SomeSketch --run first second third`
and you'll get an array with the additional arguments, in this case:
`["first", "second", "third"]`

## Motivation
Right now, I have some sketches I need to automate, and with the current behavior the only way I can do this is by calling the sketch and attaching the arguments I use in it. If I have to change the sketch or the application which calls Processing, I have to adjust every argument with caution. If I had some kind of way to directly target a property of this "arguments object" the sketches would be easier to maintain.
 
--
Sorry if this is already available, I searched everywhere and couldn't find a solution.

**Comment by jeremydouglass** [comment]
Please first bring questions like this to the Processing forum first if you have not already.

I don't believe that Java (the command line runner) supports named parameters. The convention is to pass arguments with =, receive them as String[] and then split them on = and put the results into a HashMap. See for example:

https://stackoverflow.com/a/24893326

**Comment by friaca** [comment]
@jeremydouglass Thanks, man! Had to do some adjustments but that led me to the right direction.
