### ISSUE TITLE
File>Examples>Basics>Lights>Directional doesn't work

### ISSUE THREAD

**Issue by BruceMardle** [processing/processing#6025]
Processing 3.5.4
Windows 7 Pro 64-bit on some PC!
Problem: if I load the sample File>Examples>Basics>Lights>Directional and try to run it, I get the following in the 'errors' windows:
OpenGL error 1280 at bot beginDraw(): invalid enumerant
java.lang.RuntimeException: Cannot link shader program:
Fragment shader uses varying gl_FrontFacing but vertex shader does not write to it.

The same is true of the OnOff example.

**Comment by Bobby54** [comment]
Well, it is working on windows 10, so I guess the issue is that some parts of OpenGL don't work on windows 7.
So you either don't run a recent OpenGL version or windows 7 just doesn't support your OpenGL version.

**Comment by benfry** [comment]
Please use the discussion board for troubleshooting questions: https://discourse.processing.org/
