### ISSUE TITLE
PGraphics save() issue when using P2D or P3D

### ISSUE THREAD

**Issue by RectangleWorld** [processing/processing#6027]
This bug was first reported in https://github.com/processing/processing/issues/5817 and perhaps it has resurfaced. But I am only seeing this behavior when using the P2D or P3D renderers.

It seems putting a PGraphics save() call _after_ endDraw() causes an error where a completely black image is saved. However, the save works correctly if the save() call is put _before_ endDraw(), which seems counterintuitive.

Example code: The code below will cause a black image to be saved. Also note that the image will not be drawn to the sketch window as expected.

```Java
PGraphics pg;
void setup() {
  size(800, 800, P2D);
  pg = createGraphics(800, 800, P2D);
  pg.beginDraw();
  pg.background(0xFFFFFF00);
  pg.fill(0xFF0000ff);
  pg.ellipse(500, 400, 200, 200);
  pg.endDraw();
  pg.save("test.png");
  image(pg, 0, 0);
}
```

However if the endDraw() and save() lines are swapped:

```Java
PGraphics pg;
void setup() {
  size(800, 800, P2D);
  pg = createGraphics(800, 800, P2D);
  pg.beginDraw();
  pg.background(0xFFFFFF00);
  pg.fill(0xFF0000ff);
  pg.ellipse(500, 400, 200, 200);
  pg.save("test.png");
  pg.endDraw();
  image(pg, 0, 0);
}
```
then the image save just fine and it is also drawn to the sketch window.

When I use the default renderer, however, both versions display and save the image without issues.
 

* Processing version: 3.5.4
* Operating System and OS version: Windows 10
* Other information:

**Comment by benfry** [comment]
Not a bug… it's just that anything that modifies/uses the drawing area has to occur inside begin/endDraw. It's an OpenGL rule because we can't just mess with the drawing buffer whenever we want. So that includes `save()`.
