### ISSUE TITLE
No  "cannot be resolved to a variable" error after initializing a non-declared PGraphics

### ISSUE THREAD

**Issue by kaba4cow** [processing/processing#6028]
I get no errors after initializing a variable without declaring it
Here's the code:

void setup() {
  size(2048, 1536, P3D);
  frameRate(30);
  noSmooth();

  g = createGraphics(width / 2, height / 2);
}

g is not declared as a PGraphics but still no errors occur and the program runs successfully

* Processing version: 3.5.4
* Operating System and OS version: Windows 7

**Comment by dzaima** [comment]
Just as there are the variables `width`, `height`, `mouseX`, etc., there is a global variable `g` [in Processing](https://github.com/processing/processing/blob/3952f6f7247dba50920662da3276e91166426fb7/core/src/processing/core/PApplet.java#L178), which holds the `PGraphics` object for the main screen, and you're writing over it. (I don't think there's any mention of it in the reference though)

**Comment by jeremydouglass** [comment]
> I don't think there's any mention of it in the reference though

That's correct. `g` is public but not advertised on the reference page. It is documented in the JavaDoc linked from the reference page, here:

http://processing.github.io/processing-javadocs/core/processing/core/PApplet.html#g

When you call `line()`, `rect()`, `point()` etc. from a sketch `draw()` you are actually calling `g.line()`, `g.rect()`, `g.point()` etc. for the sketch PGraphics.
