### ISSUE TITLE
Processing 3.5.4 crashing on startup in Windows 10 1809

### ISSUE THREAD

**Issue by utwistedpair** [processing/processing#6032]
I am trying to run Processing. It shows the splash screen for a couple seconds and exits.

Steps to reproduce:
1. Run program

Troubleshooting steps:
1. Update Java
2. Delete and redownload Processing
3. Restart Computer
4. Delete preferences.txt

Only step 4 allows Processing to open fully. However, if I close Processing and try to open it again, it crashes after the splash screen. 

Here is the l4j-debug dump:

```
Version: 3.9
CmdLine: C:\processing-3.5.4\processing.exe --l4j-debug
WOW64: yes
Working dir: C:\processing-3.5.4.
Bundled JRE: java
Check launcher: C:\processing-3.5.4\java\bin\javaw.exe (OK)
Heap -Xmx: Requested 256 MB / 0%, Available: 1513 MB, Heap size: 256 MB
Substitute: EXEDIR = C:\processing-3.5.4
Add classpath: lib\pde.jar
Add classpath: core\library\core.jar
Add classpath: lib\jna.jar
Add classpath: lib\jna-platform.jar
Add classpath: lib\antlr.jar
Add classpath: lib\ant.jar
Add classpath: lib\ant-launcher.jar
Launcher: C:\processing-3.5.4\java\bin\javaw.exe
Launcher args: -Xmx256m -Djava.ext.dirs=“C:\processing-3.5.4\java\lib\ext” -Djna.nosys=true -Djna.boot.library.path=lib -Djna.nounpack=true -Dsun.java2d.d3d=false -Dsun.java2d.ddoffscreen=false -Dsun.java2d.noddraw=true -classpath “lib;lib\pde.jar;core\library\core.jar;lib\jna.jar;lib\jna-platform.jar;lib\antlr.jar;lib\ant.jar;lib\ant-launcher.jar” processing.app.Base
Args length: 358/32768 chars
Exit code: 0

```

**Comment by s4lt3d** [comment]
I'm having the same issue after a recent update.

**Comment by aliabdulwahhab** [comment]
i have version 2.2.1 it is work normal but with 3.5.3&3.5.4 the running window get start with full screen even i select the size in the void setup() !!!!!!!!!

**Comment by benfry** [comment]
Please use the discussion board for this type of problem: https://discourse.processing.org/
