### ISSUE TITLE
Typing is slow in ide and causes the cpu to spike

### ISSUE THREAD

**Issue by paulgoux** [processing/processing#6033]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

Windows 10 64
8gb ram
i5 2.6ghz

## Possible Causes / Solutions

I am working on a rather large project, but as using other ide's isn't necessarily straight forward I have decided to stick with the default, however now that I have several tabs and over 1000 lines of code the ide stutters when I type.

**Comment by jeremydouglass** [comment]
If you turn off `Preferences > Continuously check for errors`, does this still happen?
With or without warnings?

Ideally do a quick check with:

1. [x] errors [x] warnings
2. [x] errors [_] warnings
4. [_] errors

You *may* need to relaunch -- I didn't, but I'm on macOS.

**Comment by paulgoux** [comment]
No I have already switched this off, auto completion is also off.

**Comment by benfry** [comment]
Please use the forum for troubleshooting questions: https://discourse.processing.org/
