### ISSUE TITLE
NullPointerException in ContributionManager.updateFlagged() on startup

### ISSUE THREAD

**Issue by MSJ0ver** [processing/processing#6034]
When I tried opening up processing it gives me the error where it says "an error occurred during startup", I have tried re downloading it a couple of times and I also have tried restarting my laptop, but nothing works. Is there a solution for it?

Processing version: 3.5.4
Operating System and OS version: Mac OS Catalina (version 10.15.4)

![Screen Shot 2020-05-07 at 2 36 57 PM](https://user-images.githubusercontent.com/64987715/81342570-aeb42580-9070-11ea-9d7a-440018b76583.png)

**Comment by jeremydouglass** [comment]
Possibly related?

https://github.com/processing/processing/issues/5823

**Comment by MSJ0ver** [comment]
But I have a Mac OS, I think the thread you linked is for windows users. Is
it not?

**Comment by slrobertson1** [comment]
I'm seeing the exact same error on Catalina 10.15.5.

**Comment by benfry** [comment]
Resolved for 4.x. It's looking for a folder called "modes" or "tools" in your sketchbook and not finding it. Not sure why it would be missing on your machine, but creating one should fix the issue until the fixed version is available.
