### ISSUE TITLE
Some fonts cannot be displayed on FX2D renderer

### ISSUE THREAD

**Issue by SanielDan** [processing/processing#6039]
Some font cannot be correctly displayed on FX2D renderer, for example:

<code>
 size(100, 100, FX2D); 
PFont font = createFont("Brush Script MT italic", 24);
textFont(font);
text("Hello World", 0, 50);
</code>

does not draw the correct font, while with other renderers it perfectly works.

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: Windows 10
* Other information:

**Comment by Bobby54** [comment]
Using your example font, running the code resultsin following error:
![image](https://user-images.githubusercontent.com/47862814/82083353-e57de180-96e9-11ea-910e-bf3145bc6e4f.png)

So it's probably the best if you use another font.

**Comment by SanielDan** [comment]
The error you see depends on which fonts are actually installed in the environment, The font in my example is present in the environment and properly displayed in any renderer but FX2D.

**Comment by benfry** [comment]
This is noted in the reference:

> Not all fonts can be used and some might work with one operating system and not others.

https://processing.org/reference/createFont_.html
