### ISSUE TITLE
Cannot easily change exported Sketch icon

### ISSUE THREAD

**Issue by SanielDan** [processing/processing#6043]
I was wandering if were possible to implement an AndroidMode-like icon changing system. Allowing the programmer set the icon of the exported sketch by putting a sketch.ico file directly into the project folder.

**Comment by benfry** [comment]
Unlike on Android, where there are specific sizes and a single format, each OS (Windows, macOS, Linux) has radically different ways of implementing icons. So this would be a huge request, not something simple like dropping in a `.png` file the way that Android works.
