### ISSUE TITLE
Friendly names for Processing Sketches like the p5.js web editor

### ISSUE THREAD

**Issue by KartikSoneji** [processing/processing#6045]
## Description
Improvement: Friendly names for Processing Sketches like the p5.js web editor

## Expected Behavior
New sketches should have an easy-to-identify name.

## Current Behavior
New sketches are named with a number date string, sketch_201231b. This mix of numbers can make it hard to distinguish sketches, especially at a glance.

## Steps to Reproduce
1. Open Processing.
2. Create a new Sketch.
3. Create another new Sketch.
4. Try telling which sketch is which by quickly reading the name.

## Your Environment
* Processing version: 3/4
* Operating System and OS version: Windows 10, Version 1909, Build 18363.657
* Other information: 

## Possible Causes / Solutions
I have started a thread on [the Processing forum](https://discourse.processing.org/t/friendly-names-for-processing-sketches-like-the-p5-js-web-editor/).
I am interested in submitting a PR for this feature.

This is the current implementation:
![image](https://user-images.githubusercontent.com/25801283/82716939-b7833900-9cb7-11ea-8561-afc769a14752.gif)

Please find my branch [here](https://github.com/KartikSoneji/processing/tree/feature-friendly-names).

**Comment by KartikSoneji** [comment]
Sorry, accidently closed the issue.

Please find the PR [here](https://github.com/processing/processing/pull/6048).

**Comment by jeremydouglass** [comment]
It is a nice touch that this is the same  system used by the p5.js web editor.

Thinking through the various modes and tools, I'm not sure if any of them rely on the sketch_YYMMDDa default name structure -- I can't think how they would.

**Comment by KartikSoneji** [comment]
We also have to consider that old users might be used to the `sketch_{yy}{mm}{dd}a` naming scheme.
It is always nice to provide the option to switch back if possible.

**Comment by benfry** [comment]
Implemented for 4.0 beta 9, arriving shortly.
