### ISSUE TITLE
When compiling sketch, nothing is seen in the window ?

### ISSUE THREAD

**Issue by molo32** [processing/processing#6047]
When compiling sketch, nothing is seen in the windows?

when you export the sketch to exe, then open it doesn't show anything.
How do I solve this?

my laptop component:
Processing 3.3
windows 8.1 pro x64
intel hd graphics

**Comment by Bobby54** [comment]
Can you send some code example which doesn't run?
Do you embed java in your exports?

**Comment by molo32** [comment]
I solved it by moving the assets (images, audio) where the exe is, and it worked.
i think processing should have a way to package the assets inside the exe.

**Comment by Bobby54** [comment]
![image](https://user-images.githubusercontent.com/47862814/83346401-488f8b00-a31c-11ea-86d9-b015f7f787fd.png)

Usually when you have a picture or any other file in your scetch and you export this sketch, then all of these files are in the data folder which means you don't have to move anything.

**Comment by mapuya19** [comment]
I'm running into a similar issue with Audio libraries;

For some reason, neither Minim nor Sound library files are being generated in the exported data folder.

**Comment by benfry** [comment]
Please use https://discourse.processing.org/ for troubleshooting help.
