### ISSUE TITLE
first time using my own function, why wont the upper curve show? 

### ISSUE THREAD

**Issue by mogos1** [processing/processing#6049]
void setup() {
size(400,400);
frameRate(2);

}
void draw(){
background(20);
half (200,200);
}

void half (int x, int y) {
  
  noStroke();
  
  fill(#008EFF); //blue  
bezier(x-100,y  ,x-100,random(y-0,y-100)  ,x+100,random(y-0,y-100)  ,x+100,y);          //CURVE_UP

 
 fill(#FFFDC4); //yellow  
bezier(x-100,y  ,x-100,random(y+0,y+100)  ,x+100,random(y+0,y+100)  ,x+100,y);          //CURVE_DOWN

  
  fill(#D64123);
ellipse(x,y,10,10); //MIDDLE
}

**Comment by jeremydouglass** [comment]
Please post coding questions on the forum, not here!

https://discourse.processing.org/c/processing/processing-questions/15
