### ISSUE TITLE
Nothing appears in output box of Processing 3.5.4 sketch

### ISSUE THREAD

**Issue by kl-42** [processing/processing#6054]
I'm very much a beginner, so I'm sorry if this is just a stupid mistake:
My sketch involves loading text from text files (each 30 lines and about 1600 characters), splitting the lines and assigning them to variables, and parsing some of them to integers. I was having trouble turning my strings into integers because of hidden characters in my unicode text files, so I converted my files to ASCII (I'm using Apple TextEdit). Now, nothing will print to my output box at all, and no error messages appear. I can open windows using size() but I can't print anything, and I'm unable to figure out how where in the code the problem is occurring. After changing to ASCII I was briefly getting a really long error that said something like "timeout due to packet 641 not loading" but I stopped seeing that. I've tried restarting my computer and quitting Processing - nothing works.

My code (please let me know if it would be helpful to have the Player class, but it's just more splitting strings, converting them to integers, and storing them in Arrays):
//declaring variables
ArrayList<Player> players=new ArrayList<Player>();

void setup(){
  String[] lines1415=loadStrings("TXT14-15.txt");
  String[] lines1516=loadStrings("TXT15-16.txt");
  String[] lines1617=loadStrings("TXT16-17.txt");
  String[] lines1718=loadStrings("TXT17-18.txt");
  String[] lines1819=loadStrings("TXT18-19.txt");
  
  for (int x=1;x<lines1415.length;x+=1){
    String line=lines1415[x];
    if (players.size()==0){
      players.add(new Player(line));
    }
    else{
      String[] pieces=split(line,"!");
      String playername=pieces[0];
      for (int i=0;i<players.size();i+=1){
        if (players.get(i).getPlayerName().equals(playername)){
          players.get(i).update(line);
        }
        else{
          players.add(new Player(line));
        }
      }
    }
  }
}

**Comment by benfry** [comment]
Please use https://discourse.processing.org/ for coding questions.
