### ISSUE TITLE
Problem starting Processing

### ISSUE THREAD

**Issue by daviddowning2006** [processing/processing#6056]
Hi, 

I have an Apple Mac Book pro running Catalinia 10.15.5

I have been running Processing but in the last week I get the error message below and can no longer do so. I have tried uninstalling and reinstalling all available versions of Processing but it has no effect. 

I think my version of Java is correct, how do I fix this issue?

![image](https://user-images.githubusercontent.com/66905647/84591621-d8aef380-ae37-11ea-82be-7d2e31dfc620.png)

I am a complete beginner please help

 

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by Bobby54** [comment]
There have been multiple issues regarding this topic.
One was solved by giving Processing full disk access in the system preferences.

**Comment by daviddowning2006** [comment]
Hi Bobby54 your solution was perfect, up and running now, thanks so much for your help
