### ISSUE TITLE
Why showing a lot of PImage slows down the sketch?

### ISSUE THREAD

**Issue by molo32** [processing/processing#6057]
Why showing a lot of PImage slows down the sketch.

windows8.1
processing 3.5.4
lenovo g480 laptop

I have several Pimage drawing on the screen, like 30 100x100 pimages. When I deactivate "draw pimages" it becomes faster, I don't know if the pimages need a lot of memory and therefore the processing becomes slow.

imagesnsw draw in a loop

image (pimages [i], 100 * i, 0);

Someone clarify this for me and how I can draw many things on the screen without delay.

**Comment by R4ph3rd** [comment]
Actually if you load a lot a images in the loop, it is normal is go slower : you load the same images at each frames ( 30 or 60 / second by default ). You should take a look to the [Processing forum](https://discourse.processing.org/) for this type of question.

**Comment by benfry** [comment]
(Closing/locking since this belongs on the forum)
