### ISSUE TITLE
HDPI support GNOME desktop

### ISSUE THREAD

**Issue by anto-1** [processing/processing#6059]
The user interface is too small to be usable.
![processing](https://user-images.githubusercontent.com/46658878/85249025-a184a780-b420-11ea-96a4-da64079018ca.png)

Fedora 31
GNOME Version 3.34.6

**Comment by Bobby54** [comment]
Just go to file -> Preferences ->untick automatic interface scaling
![image](https://user-images.githubusercontent.com/47862814/85319489-e14f9b80-b4c1-11ea-8971-22a2c1e4015e.png)
Then choose a different percentage, click OK and restart Processing.

**Comment by anto-1** [comment]
Well that was easy. Thank you so much!

**Comment by anto-1** [comment]
![menu](https://user-images.githubusercontent.com/46658878/85323968-ffec6d00-b496-11ea-9de0-cece252c6f8e.png)
Is there a way to make the menu appear a bit bigger? The interface got scaled up but the menu did not follow.

**Comment by Bobby54** [comment]
I don't think there is but you can check the processing code and might be able to change the size of the menu there.

**Comment by Bobby54** [comment]
I opened a discussion on Processing Discourse.
Maybe somebody else can help there.
https://discourse.processing.org/t/change-size-of-menu-bar/22086

**Comment by anto-1** [comment]
The bundled version of java Java is 1.8.0_202 from `~/processing-3.5.4/java/release`. Which does not appear to support automatic hdpi scaling. With the OpenJdk you can install version 9 which appears to solve the problem for other programs.
see [](http://openjdk.java.net/jeps/263)

 But since this project use Oracle's version, I'll have to test the program with a more recent one by changing the default configuration.

**Comment by benfry** [comment]
Can you try with the 4.0 alpha 2 release and let us know if it's working better?

**Comment by maxdevjs** [comment]
Where the 4.0 alpha 2 can be found?

**Comment by cansik** [comment]
In 4.0 alpha 3, the menubar is still small, but the menu items are bigger now:

![image](https://user-images.githubusercontent.com/5220162/107429354-162d6300-6b24-11eb-8307-2b3fdd0e26e4.png)

**Comment by benfry** [comment]
That looks like a problem with the Window Manager you're using. Perhaps try another and see if it's still a problem?

**Comment by benfry** [comment]
Should be resolved in the 4.0 releases: https://github.com/processing/processing4/releases

**Comment by letorbi** [comment]
The scaling seems to work fine with beta 1 on GNOME/Wayland now:

![Screenshot from 2021-08-10 10-31-57](https://user-images.githubusercontent.com/1268015/128835074-35b1de58-5f83-4850-a855-389f7f1944dd.png)

**Comment by benfry** [comment]
Thanks for the verification.
