### ISSUE TITLE
Inconsistent behavior for arc

### ISSUE THREAD

**Issue by ziyaointl** [processing/processing#6063]
## Description
When start and end angles are both 2*PI, arc produces unexpected behavior.

## Expected Behavior
When start angle and end angle for arc are the same, nothing is drawn.

## Current Behavior
Depending on the mode, when the start angle and the end angle for arc are the same, either a dot or a line is drawn.
![](https://user-images.githubusercontent.com/18119047/85369950-dbb67d80-b4e2-11ea-9e57-18bec7b75dc5.png)

## Steps to Reproduce
```java
void setup() {
  size(640, 360);
}

void draw() {
  int offset = 0;
  for (float x = 0; x < PI * 2; x += QUARTER_PI) {
     arc(50.0 + offset, 50.0, 50.0, 50.0, x, 2*PI);
     arc(50.0 + offset, 100, 50, 50, x, 2*PI, OPEN);
     arc(50.0 + offset, 150, 50, 50, x, 2*PI, CHORD);
     arc(50.0 + offset, 200, 50, 50, x, 2*PI, PIE);
     offset += 50;
  }
}
```

## Your Environment
* Processing version: 3.5.4
* Operating System and OS version:  MacOS 10.15.5

## Possible Causes / Solutions
A naive one: check if the start angle and end angle are the same. If so, return.

**Comment by dzaima** [comment]
Your start and end angles aren't actually ever _exactly_ equal - even the condition for your `for` loop checks that `x < 2*PI`, which implies that `x != 2*PI`. A `println(x == 2*PI);` in the `for` loop will never print `true`.

If you added `if (2*PI < x+.001) x = 2*PI;` to set `x` to exactly `2*PI` if it's close enough, Processing will, as you expected, display nothing.

What would be the exact point it would need to move from drawing a single black pixel to nothing? How would the condition change from a 5 pixel wide arc to a 10000000 pixel one (which, yes, does draw correctly, and a 0.000001 radian change in the angle is very significant)

**Comment by ziyaointl** [comment]
Hi @dzaima,

Thanks for pointing this out! You are right in that the start angles and end angles are acutally not the same in my script. And when I manully set them to be the same, nothing is drawn, which is expected.

I think the sensible behavior here is to draw nothing when `start_angle == end_angle` and always draw the border when `start_angle != end_angle`, which seems to be the case as of now.
