### ISSUE TITLE
Processing launches automatically and locks serial port from use by other apps

### ISSUE THREAD

**Issue by baqwas** [processing/processing#6067]
## Description
- Processing is launched automatically when Arduino IDE is launched
- Processing has control over serial port that prevents Arduino IDE to code upload to board
- Closing Processing closes Arduino IDE too (i.e. Arduino IDE no longer functional)

Would like:
- Processing not to launch when another app (albeit Java sibling Arduino IDE) is launched
- Detach serial port connection so that Arduino IDE can upload code

## Expected Behavior
- Processing should not launch automatically when Arduino IDE is launched
- Processing should permit release of serial port if even launched so that Arduino IDE can use the serial port for its code upload to an attached board

Provide some way to disable/detach the use of a serial port from Processing

## Current Behavior
Processing is automatically launched when Arduino IDE is launched even if the user/operator does not want Processing to run
Closing Processing closes Arduino IDE also rendering the latter totally ineffective in interacting with boards for code uploads

## Steps to Reproduce
1. Install Arduino IDE
2. Install Processing
3. Run Arduino IDE to upload code to board using serial port
4. Launch Processing
5. Assign serial port (same as the one in use by Arduino for Serial Monitor) for use by Processing
6. Close Processing and Arduino IDE
7. Launch Arduino IDE
8. Processing is automatically launched (even if user doesn't want to)

## Your Environment
* Processing version: v3.5.4
* Operating System and OS version: Ubuntu 20.04 (with all standard OS updates/patches applied as of 2020-07-11)
* Other information: Arduino IDE 1.18.12

## Possible Causes / Solutions
Possibly some JRT issue?

**Comment by benfry** [comment]
You'd have to ask the Arduino folks; we have no control over what happens when their app launches.

**Comment by baqwas** [comment]
@benfry , the Arduino folks stated (_before_ I posted the issue) that they do not control the **Processing** app. Thx for closing the issue without bothering to investigate.

Kind regards.
