### ISSUE TITLE
Error creating an array of binary-formatted integers

### ISSUE THREAD

**Issue by golanlevin** [processing/processing#6073]
Integers formatted as binary numbers, when used in a literal array, cause an error ("unexpected token: int"). 

* It is possible to declare integers in binary format (e.g., `int myBinaryNumber = 0b00101101;`)
* It is possible to declare integers in hex format (e.g. `int myHexNumber = 0xDEADBEEF;`)
* It is possible to declare arrays of hex numbers (e.g. `int myHexArray[] = {0x00AACCFF, 0xDEADBEEF};`)
* Declaring an array of binary-formatted numbers throws an error. (e.g. `int myBinaryArray[] = {0b00101101, 0b00100100};`)

The program below demonstrates this. 
I'm using Processing v.3.5.4.

```
int myBinaryNumber = 0b00101101;
println(myBinaryNumber);

int myHexNumber = 0xDEADBEEF;
int myHexArray[] = {0x00AACCFF, myHexNumber};
println(myHexArray); 

int myBinaryArray[] = {0b00101101, 0b00100100};
```

**Comment by dzaima** [comment]
The `0b` syntax isn't really supported by Processing 3, as the [ANTLR syntax grammar](https://github.com/processing/processing/blob/master/java/src/processing/mode/java/preproc/java15.g) for it is based off of Java 1.5, which didn't support binary literals (if anything's a bug, it's that they work in variable declarations). The work-in-progress Processing 4, however, supports Java 11, including the `0b` syntax.

**Comment by golanlevin** [comment]
Uh, OK, thanks. I guess this will be fixed in Processing 4.

**Comment by jeremydouglass** [comment]
Yes `0b` syntax currently works in Processing 4 out of the box. In the meantime on Processing 3 a workaround is `unbinary(int(value))`.

For previous related discussion on further binary features in Processing 3 see also the declined PR https://github.com/processing/processing/pull/5681
