### ISSUE TITLE
App crash when scale to full screen 2880x1800

### ISSUE THREAD

**Issue by song50119** [processing/processing#6074]
## Description
App crash when scale to full screen 2880x1800

## Expected Behavior
Should not crash when scale to larger screen 

## Steps to Reproduce
Run any samples app at https://github.com/danginsburg/opengles3-book
I running on Chapter_2
On App's window press to `Enter full screen button`. Or drag window to full screen 

## Environment
* Processing version: OpenGL version string: 2.1 INTEL-14.7.8
* Operating System and OS version: Ubuntu 18.04.4 
* Other information:
Errors logs `XIO: fatal IO error 11 (Resource temporarily unavailable) on X server ":1" after 693 requests (691 known processed) with 0 events remaining.`

**Comment by jeremydouglass** [comment]
This is a C program.

https://github.com/danginsburg/opengles3-book/blob/master/Chapter_2/Hello_Triangle/Hello_Triangle.c

What does this have to do with Processing (which is Java-based)? I think you may have posted this to the wrong repo.

This is the repo for processing.org

**Comment by song50119** [comment]
Oops!, thank you
