### ISSUE TITLE
How to add a font in the list ?

### ISSUE THREAD

**Issue by fotosettore** [processing/processing#6075]
Hi
i need to add a font in the list that is given by TOOL --> CREATE FONT
That font is already installed in windows10 and it is a true-type (it is seen by photoshop), but it does not appear in the Processing list.
I need only to create a .vlw file (i need to use it in esp32 tft) without using sketch.
Any help is appreciated.

many thanks

p.s. is it possibile that this font is not compatible ? here is it : http://www.homoandroidus.com/font/

**Comment by fotosettore** [comment]
> Hi
> i need to add a font in the list that is given by TOOL --> CREATE FONT
> That font is already installed in windows10 and it is a true-type (it is seen by photoshop), but it does not appear in the Processing list.
> Any help is appreciated
> many thanks
> 
> p.s. is it possibile that the font is not compatible ? this is the font : [http://www.homoandroidus.com/font/]

**Comment by fotosettore** [comment]
> > Hi
> > i need to add a font in the list that is given by TOOL --> CREATE FONT
> > That font is already installed in windows10 and it is a true-type (it is seen by photoshop), but it does not appear in the Processing list.
> > Any help is appreciated
> > many thanks
> > p.s. is it possibile that the font is not compatible ? this is the font : [url]http://www.homoandroidus.com/font/[/url]

**Comment by fotosettore** [comment]
> > > Hi
> > > i need to add a font in the list that is given by TOOL --> CREATE FONT
> > > That font is already installed in windows10 and it is a true-type (it is seen by photoshop), but it does not appear in the Processing list.
> > > Any help is appreciated
> > > many thanks
> > > p.s. is it possibile that the font is not compatible ? this is the font : (http://www.homoandroidus.com/font/)

**Comment by StanLepunK** [comment]
Hello, the forum is better place for this discussion https://discourse.processing.org/. Any way there is no problem for me to load your font on my Mac.
Sometime the problem with the Font List on the Processing IDE, you cannot see all your font because the console size is limited, maybe try to launch Processing with SublimText ?

```
PFont f;
void setup() {
  size(300,200);
  String[] fontList = PFont.list();
  printArray(fontList);
  f = createFont("Stereofunk", 34);
}
void draw() {
  textFont(f);
  text("StereoFunk", 10,height/2);
}
```
![stereofunk](https://user-images.githubusercontent.com/3332269/88379956-09be0480-cda4-11ea-9047-05201cf381fe.jpg)

**Comment by fotosettore** [comment]
hi
i tried to ask for but forum did not give me a solution
this is the result of your code (under win10)
```
...
[371] "Yu Gothic UI Semibold"
[372] "Yu Gothic UI Semilight"
"Stereofunk" is not available, so another font will be used. Use PFont.list() to show available fonts.
```
and the banner of the result is :
![steronotfound](https://user-images.githubusercontent.com/45329325/88486208-6aa03500-cf7c-11ea-84f2-9c393104cce6.PNG)

**Comment by StanLepunK** [comment]
oohhhh, it's weird and smell bad. I don't have a windows 10 to test it. I hope a an other window 10 coder can test it and help you.  Maybe try to find an stereofunk.otf I believe this format is accept too.

**Comment by fotosettore** [comment]
absolutely !! i use the normal font install for fonts and they are available in all applications (word, excel, photoshop etc).
for example, the font **Brain Wants** is a . otf font, installed and wortking fine, but ....

![brain not found](https://user-images.githubusercontent.com/45329325/88521780-b4793180-cff5-11ea-9884-167bff964582.PNG)

**Comment by StanLepunK** [comment]
I hope a window user can try, see if he have a same problem as you, and find a way to solve it and see if it's Processing Bug or just a problem on your computer. Sorry I cannot help any more.

**Comment by benfry** [comment]
Please use the discussion board for usage questions: https://discourse.processing.org/
