### ISSUE TITLE
Files don't save correctly in exported applications.

### ISSUE THREAD

**Issue by Mira-nda** [processing/processing#6076]
When running a program from Processing that saves files, everything works normally—the files are put in the data folder, or in a sub-folder if directed. 
However, after exporting the application, instead of saving the files to the data folder within the application, it creates a _new_ data folder in the same directory as the application and puts the files in there. So when attempting to read that file, the app doesn't find anything.

To reproduce this issue, simply write any program in Processing that creates a file, such as with saveJSONObject() or saveStrings() (those are what I tested myself), then go to File -> Export Application -> Export. Once the exporting is complete, attempt to use the new application to create a file.

This is an issue for people like me who want to create applications to distribute online, because any feature that includes saving files won't work.

I am using Processing 3.5.4 on macOS Catalina Version 10.15.4 on a MacBook Pro 13" (2019)

EDIT: This issue is still present when not imbedding Jave for Mac OS X.

**Comment by benfry** [comment]
This is because you can't save files *inside* a macOS application, where the data directory would otherwise live. We're doing this specifically to work around how Apple has set things up.
