### ISSUE TITLE
rotateX() in P3D is not tracking the updated axis orientation but rotateY() and rotateZ() are working in some orientations

### ISSUE THREAD

**Issue by ram5000** [processing/processing#6077]
## Description
rotateX() will only apply to the default orientated X axis, i.e. horizontal across the display. It wont track the objects newly orientated X axis. It will only ever rotate whatever axis is currently located across the horizontal of the display. This could be Y or Z or combinations of XYZ. 

This is sometimes not an issue for rotateY() or rotateZ() because they in some orientations. They can track the object orientation and rotate about there newly orientated axis, so they are not an issue sometimes.

## Expected Behavior
I expected that the rotateX(), rotateY() and rotateZ() function to track the object orientation as it moves in free space and be able to rotate about the newly orientated axis orientation.

## Current Behavior
rotateX() function in particular is not behaving correctly, its stuck in rotation of the horizontal orientation only.

## Steps to Reproduce
Please see Example code below. You can rotate the axis by pressing the number keypad values 
where: 
8 = +X
2 = -X
6 = +Y
4 = -Y
9 = +Z
7 = -Z

Any help would be much appreciated. 

I have used WB_Render3D to draw and control the orientation of my objects as a work around, but it would be nice if Processing IDE could do this correctly as that would probably be most peoples preference. 
Thanks for you help.
Kind regards.

//--------------------------------------------------------------
float xAxisAngle = 0.0;
float yAxisAngle = 0.0;
float zAxisAngle = 0.0;

float updateXaxisAngle = 0.0;
float updateYaxisAngle = 0.0;
float updateZaxisAngle = 0.0;

void setup()
{
  size(900,900,P3D);
}

void draw()
{
  
  translate(width/2, height/2, 0);
  
  updateXaxisAngle = radians(xAxisAngle);

  updateYaxisAngle = radians(yAxisAngle);
  
  updateZaxisAngle = radians(zAxisAngle);
  
  rotateX(updateXaxisAngle);
  rotateY(updateYaxisAngle);
  rotateZ(updateZaxisAngle);
  
  background(200);
  
  fill(0);
  textSize(14);
  stroke(0);
  
  text("+Y Axis", -28, -200, 0);
  text("-Y Axis", -28, 200, 0);
  
    rotateY(radians(90));
      text("+Y Axis", -28, -220, 0);
      text("-Y Axis", -28, 220, 0);
    rotateY(radians(-90));
  
  text("+X Axis", 200, 4, 0);
  text("-X Axis", -250, 4, 0);
  
    rotateX(radians(90));
      text("+X Axis", 200, 24, 0);
      text("-X Axis", -250, 24, 0);
    rotateX(radians(-90));
    
  
  rotateY(radians(90));
  
    text("+Z Axis", -250, 4, 0); 
    text("-Z Axis", 200, 4, 0);
  
      rotateX(radians(90));
        text("+Z Axis", -250, 24, 0); 
        text("-Z Axis", 200, 24, 0);
      rotateX(radians(-90));
      
  rotateY(radians(-90));
  
  line(0,180,0,0,-180,0); // 3D line from +Y to -Y
  line(-180,0,0,180,0,0); // 3D line from -X to +X
  line(0,0,180,0,0,-180); // 3D line from -Z to +Z
 
}

void keyPressed()
{

 if(keyCode == 136) // keypad '8' up arrow
  {
      xAxisAngle+=10;
  }
  else if(keyCode == 130) // keypad '2' down arrow
  {
      xAxisAngle-=10;
  }
  else if(keyCode == 132) // keypad '4' left arrow
  {
    yAxisAngle-=10;
  }
  else if(keyCode == 134) // keypad '6' right arrow
  {
    yAxisAngle+=10;
  }
  else if(keyCode == 137) // keypad '9' 
  {
    zAxisAngle+=10;
  }
  else if(keyCode == 135) // keypad '7'
  {
    zAxisAngle-=10;
  }
}

**Comment by jeremydouglass** [comment]
very belatedly:

This is a coding question, and I think you are misunderstanding. All three rotate methods work in the same way. However, in your code, you are applying rotateX **first**, then rotateY, then rotateZ.

```
rotateX(updateXaxisAngle);
rotateY(updateYaxisAngle);
rotateZ(updateZaxisAngle);
```

This is the order in which your variables are applied. Thus xAxisAngle is alway a rotation from the default, because that is what you are doing in your code. If you want z to be the base rotation, then

```
rotateZ(updateXaxisAngle);
rotateX(updateYaxisAngle);
rotateY(updateZaxisAngle);
```

...but if what you want is to incrementally change the total orientation in a relative way with each keypress then your approach won't work. I'd suggest opening a thread for advice on the forum, discourse.processing.org

**Comment by benfry** [comment]
Closing; any follow-up should happen at https://discourse.processing.org/
