### ISSUE TITLE
Declaring private variables or methods in a class does not make the elements private

### ISSUE THREAD

**Issue by Kevin-Lmy** [processing/processing#6085]
## Description

Private variables and methods in a class are being accessed directly by other parts of a program.
Declaration is done using java syntax.

## Expected Behavior

Accessing private elements from other parts of a program without accessor methods should cause a runtime error.

## Current Behavior

Program runs successfully.

## Steps to Reproduce

class Test {
    private int x, y;

    /* code */
}

Test t;

void setup() {
    t = new Test();
}

void draw() {
    t.x = 10; // should cause error
}

## Your Environment

 

* Processing version: 3
* Operating System and OS version: Win x64
* Other information:

**Comment by dzaima** [comment]
This is a side-effect of the Processing code actually being pre-processed to a single file, which (very simplified) can look like this:

```java
public class Sketch extends PApplet {
  public static void main(String[] args) {
    Sketch s = new Sketch();
    /* ... */
    s.setup();
    /* ... */
  }
  class Test {
    private int x;
  }
  Test t;
  void setup() {
    t = new Test();
    t.x = 3;
  }
}
```

As this is allowed by Java, there's not really much Processing could do to make it error without either needing to write its own compiler or completely changing how it works.

**Comment by benfry** [comment]
Yep; what @dzaima said.
