### ISSUE TITLE
Saving an OpenGL PGraphics results in a black image

### ISSUE THREAD

**Issue by jbellis** [processing/processing#6094]
This looks a lot like https://github.com/processing/processing/issues/4578 except that it still happens with DISABLE_ASYNC_SAVEFRAME.  The workaround to get a PImage first doesn't work, either -- but I can still draw it to the main canvas!

(This *does* work with a Java2D PGraphics.)

Code to reproduce:

```
    private PGraphics pg;

    public void settings() {
        size(400, 400, P2D);
    }

    public void setup() {
        pg = createGraphics(200, 200, P2D);
        pg.hint(PConstants.DISABLE_ASYNC_SAVEFRAME);
    }

    public void draw() {
        pg.beginDraw();
        pg.fill(0, 100, 100);
        pg.rect(0,0, pg.width,pg.height);
        pg.endDraw();

        // this works
        image(pg, 0,0); 
        
        // this doesn't work (saves completely black image)
        pg.save("C:\\temp\\foo.png"); 
        
        // this doesn't work either
        PImage pi = pg.get();
        pi.save("C:\\temp\\foo.png"); 
        
        noLoop();
    }
    
```

**Comment by jbellis** [comment]
Discussion suggests that this is specific to Windows: https://discourse.processing.org/t/pgraphics-color-and-saving/23748/

**Comment by dzaima** [comment]
[Duplicate.](https://github.com/processing/processing/issues/6027) It is weird that the image can be drawn but not saved, but it does make some sense - after its `endDraw` the image could very well be completely transferred to some other format (maybe the GPU, but i have no clue what's actually happening), at which point reading it for anything other than drawing on-screen could be hard.

**Comment by jbellis** [comment]
Thanks, confirmed that calling save before endDraw fixes the problem.
