### ISSUE TITLE
GUI shortcut Ctrl + Slash not working on text editor (Comment / Uncomment button)

### ISSUE THREAD

**Issue by OrnithOrtion** [processing/processing#6099]
## Description

The shortcut `ctrl + Slash` does not work on Processing GUI. It do not comment the line (either selected or not) by adding double slash '//' or uncomment commented line(s) by removing these doubles slash.

## Expected Behavior

I expected that when I hit `ctrl + Slash` as noted in Processing Edit Menu, it will do exactly the same as clicking on the button "Edit / Comment Uncomment".

## Current Behavior

Nothing seems to happens while hitting the shortcut keys.

## Steps to Reproduce

1. Launch Processing IDE (java)
2. Type any line(s) of code
3. Select (or not) these line(s) en press `Ctrl + Slash`

## Your Environment

 

* Processing version:  Processing v3 (3.5.4)
* Operating System and OS version: Ubuntu (Linux) 20.04 (64-bit)
* Other information: Works fine else.

## Possible Causes / Solutions

Lack of implementation in GUI code (not following the menu item label) ?

Hope this could help somehow.

**Comment by benfry** [comment]
Working fine here with a fresh Ubuntu 20.04 installation… maybe check your window manager and see if something else is interfering?

![issue 6099 short](https://user-images.githubusercontent.com/1623101/94364126-178a5180-0095-11eb-84f0-15bcebbc4b1b.gif)

**Comment by OrnithOrtion** [comment]
I really do not understand what can be the cause of my issue. 
It do not work for me with either on Ubuntu 20.04 gnome on Clevo laptop nor on old HP Elite Book 6930p running Ubuntu 20.04 MATE. 
I did not see any interfering shortcuts in both desktop environment. Moreover the shortcuts works fine in VSCodium and other code editors.

**Comment by dzaima** [comment]
Is it possible you're using some keyboard layout Processing might not recognize (what's the output of `setxkbmap -query`?)? If applicable, does the slash on the numpad work?

**Comment by OrnithOrtion** [comment]
I am indeed not using QWERTY keyboard layout. I use fr-pc (AZERTY) layout.
Here is the output of `setxkbmap -query` : 
```
rules:      evdev
model:      pc105
layout:     fr
```
As I did mention on previous message, `slash` key is otherwise functional, as I am able to use `Ctrl + Slash` on other code editor such as Atom or VSCodium.

**Comment by dzaima** [comment]
AFAICT with the `fr` layout, slash is ctrl+:, totaling to shift+ctrl+colon; I'd assume whatever's parsing the keystrokes is expecting shift to not be held (because there could be separate shortcuts with & without shift in a layout where slash doesn't require shift); Changing `menu.edit.comment_uncomment.keystroke.linux` in `lib/languages/PDE.properties` (or one of the localized ones if applicable) to `ctrl shift pressed COLON` makes it work, but it's by no means a solution for everyone (and i have no idea what could be).

**Comment by OrnithOrtion** [comment]
Thank you a lot for your help. It solved the issue, even if it is not a very a user-friendly option, as you said.

**Comment by benfry** [comment]
I see; that's this issue here: https://github.com/processing/processing/issues/2199#issuecomment-455735927, and there's more detail about it here: https://github.com/processing/processing/wiki/Localization#shortcuts-and-key-bindings
