### ISSUE TITLE
error occurred during startup 

### ISSUE THREAD

**Issue by cammorales** [processing/processing#6101]
Hi 
I am having problems with installing Processing 3.5.4 on my pc laptop. I am running windows 10 and after unexplainably loosing my desktop files, I had to reinstall processing and since keep getting an error at startup. I reinstalled and deinstalled many times and looked at the Java NullPointerException at startup -ContributionManager.java #5823. Was wondering if anyone else has had an issue with this and can help, here is a screenshot of my error message.
![Screenshot (64)](https://user-images.githubusercontent.com/47129452/94427512-32c09400-015d-11eb-8b4c-060f6c79db5b.png)

**Comment by cammorales** [comment]
realized one drive was saving a copy of the tools folder once deleted processing worked again.

**Comment by benfry** [comment]
Ok, thanks for the update. Sorry for the trouble.
