### ISSUE TITLE
Save and saveFrame have recently stopped working

### ISSUE THREAD

**Issue by ricardocanada** [processing/processing#6102]
## Description

save() and saveFrame() still open a new tab in Safari or Chrome iOS, but rather than contain a screen image, the page is now blank (white).

## Expected Behavior

save() and saveFrame() when invoked, should open a new browser tab in Safari or Chrome iOS containing a screen image. 

As described above.
## Current Behavior

Both save() and saveFrame() were working fine until mid-September 2020. Now they both open tabs to blank pages.
## Steps to Reproduce

1. ellipse(width/2, height/2, 100, 100)
2.save('pix.jpg');  OR
3.saveFrame('pix.jpg')
4. [a new tab should open with an image of what was drawn]

## Your Environment

Working in Safari and Chrome on an iPad Pro.
 

* Processing version:
Processingjs V1.6.6 running on OpenProcessing
* Operating System and OS version:
iPad Pro 11" (late 2019 model) running iOS 14.0.1
* Other information:

## Possible Causes / Solutions

The tech support person for OpenProcessing suggests that Apple may have made an iOS change in how browsers save images.

**Comment by benfry** [comment]
You'd have to take that up elsewhere; OpenProcessing and Processing.js are unrelated projects: https://github.com/processing-js/processing-js

**Comment by ricardocanada** [comment]
Your response is a pretty good indicator to me as to why Processing is a dying language. OpenProcessing offers users the choice of a current version of Processing.js or p5js. Sadly Processing gets more bugs with each passing month. Users are migrating more and more to p5js, even translating their existing sketches. Now you tell me to look elsewhere for help because OP and Processing.js are separate projects!? So are OP and p5js, but the p5js team still fixes bugs.

I guess your position relieves your group of any responsibility for Processing bug fixes on OP. I will pass your response along to Sinan Ascogliu, the OP moderator. My guess is that OP will drop Processing in the next year and concentrate solely on P5.js. 

One more nail in Processing's coffin. Well played!

**Comment by ricardocanada** [comment]
No problem. I am aware that Processing is now unsupported and will never see a new version. Open Processing will likely drop it soon and concentrate exclusively on p5js

**Comment by benfry** [comment]
Processing, the repository you're now using, continues to be supported. Processing.js is an unrelated project, linked above.
