### ISSUE TITLE
Canvas window is always a gray square when I run the code.

### ISSUE THREAD

**Issue by chiya7** [processing/processing#6107]
I'm just getting started and no matter what line of code I run, the canvas window is always a gray square, with nothing happening. I'm running Processing 3 on Mac OS 10.14.6

<img width="1333" alt="Screen Shot 2020-10-12 at 1 09 30 PM" src="https://user-images.githubusercontent.com/15383162/95773352-5242db00-0c8c-11eb-9d4e-53599ebf27ea.png">

Thank you!

**Comment by dzaima** [comment]
`rect(400,300,50,50);` would draw a rectangle at coordinates (400;300) with size 50×50. The default sketch size is 100×100, so the rectangle drawn at (400;300) would be outside of the bounds of the screen, so nothing will be drawn. You probably want to add something like `size(800,800);` at the start.

Also, please use https://discourse.processing.org/ for programming questions, this issue page is only for issues/bugs in Processing itself.

**Comment by benfry** [comment]
Closing since it's a coding question.
