### ISSUE TITLE
Tabs are not displayed inside texts when using P2D or JAVA2D

### ISSUE THREAD

**Issue by SanielDan** [processing/processing#6109]
## Description
 Tabs are not displayed inside texts when using P2D or JAVA2D but they work while using FX2D renderer

## Current Behavior
tabs are not displayed neither typing them nor writing '\ t'

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: Windows 10

**Comment by benfry** [comment]
Tabs are not supported, sorry; there isn't a good way to make them predictable across renderers without a lot of extra code. It's a surprise to me that they work in FX2D.
