### ISSUE TITLE
Movie maker .mov not compatible with quicktime player

### ISSUE THREAD

**Issue by moritzsalla** [processing/processing#6110]
My movie maker seems to generate corrupt files. `saveFrame()` works fine, and there are no error messages during movie generation. VLC will open the video without error.

The generated generated file's icon is the quicktime logo – not a preview, as macOS usually displays. Upon opening, I get this error message: 
> The document “out.mov” could not be opened. The file isn't compatible with quicktime player.

I am running Processing 3.5.4 on MacOS Catalina 10.15.7

**Comment by moritzsalla** [comment]
Just confirming that my iPhone cannot open the video either.

**Comment by moritzsalla** [comment]
Using ffmpeg from terminal creates the same issue. Perhaps Movie Maker uses ffmpeg? 

Anyways, adding the flag `-pix_fmt yuv420p` fixed things for me. 
Found this solution here https://superuser.com/a/820137.

**Comment by moritzsalla** [comment]
Update: This is still happening on Big Sur.

<img width="372" alt="Screenshot 2020-11-19 at 00 32 04" src="https://user-images.githubusercontent.com/42788026/99604986-a749dd80-29fe-11eb-8e0a-12ca30398075.png">

**Comment by nikitalastochkin** [comment]
same problem ;/

**Comment by benfry** [comment]
MovieMaker uses a fairly old codec (RLE, IIRC), so maybe Apple has removed it from QuickTime. 

It'll have to be rewritten, or maybe redone to use ffmpeg or something else.

**Comment by moritzsalla** [comment]
Ok, thanks Ben!

**Comment by benfry** [comment]
After a little more digging… it seems that when 32-bit support was removed after Mojave (in Catalina), QuickTime Player's ability to automatically convert older files also went away: https://support.apple.com/en-us/HT202884 

From here on our, Apple supports very few video formats (some MPEG, plus their own ProRes codecs). Best option will be to redo MovieMaker to use `ffmpeg`, or in the meantime, folks can use that on the command line.

**Comment by benfry** [comment]
I've just finished rewriting Movie Maker for 4.0 so that it uses FFmpeg and can instead produce MPEG-4 files and Animated GIFs. You can either build from the source to use it now: https://github.com/processing/processing4 or wait for 4.0 alpha 6 (or beta 1, whatever the next release is called).
