### ISSUE TITLE
image processing

### ISSUE THREAD

**Issue by Toprun123** [processing/processing#6113]
in this code
instead of displaying an image then waiting then displaying another image it just waits then displays the second image
any help would be ok thanks for giving time
```java
PImage l2;
PImage l1;

void setup(){
  size(500,500);
  l1 = loadImage("loading...2.png");
  l2 = loadImage("loading...1.png");
  image(l1,0,0);
  delay(2000);
  image(l2,0,0);
}

void draw(){
 
}
```
Syed Daanish

**Comment by dzaima** [comment]
The screen is updated only at the end of execution of `setup` or `draw`, so you need to draw the image depending on some state in `draw`.

Also, this place is only for bugs & feature requests of the Processing implementation, please use https://discourse.processing.org/ for questions.
