### ISSUE TITLE
Big Sur seems to have broken P3D & P2D renderers

### ISSUE THREAD

**Issue by moritzsalla** [processing/processing#6121]
## Problem
Since the update to Big Sur, processing's P3D and P2D renders do not appear to be working. When running a P3D sketch on my intel mac, a window opens to the specified dimensions, displaying the default grey. P3D worked fine before the OS update.

I've tried most of Daniel Shiffman's examples from the [P3D tutorials](https://processing.org/tutorials/p3d/), to no effect.

## Example
```
size(640,360,P3D);
background(0);
lights();

pushMatrix();
translate(130, height/2, 0);
rotateY(1.25);
rotateX(-0.4);
noStroke();
box(100);
popMatrix();

pushMatrix();
translate(500, height*0.35, -200);
noFill();
stroke(255);
sphere(280);
popMatrix();
```

<img width="752" alt="Screenshot 2020-11-19 at 00 22 57" src="https://user-images.githubusercontent.com/42788026/99604486-8634bd00-29fd-11eb-82cd-203a275c45b2.png">

## My environment
* Processing version: 3.5.4
* Operating System and OS version: macOS Big Sur 11.0.1
* Other information: 2017 Intel MBP

**Comment by moritzsalla** [comment]
Update: the sketch appears for a split second when closing the window. `saveFrame()` exports are successful.

**Comment by nosarious** [comment]
THANK YOU! I thought it was just me having this problem.

I tried different 3d-model examples with both Processing 3.5.4 and the 4.0 beta as well and was unable to get P3D to work.

**Comment by fredvernier** [comment]
It did it to me with Processing4. I just move the empty window to another screen (because I have multiple screen) then get it back to the original screen and then it works.

**Comment by gnefiy** [comment]
Has anyone solved the problem? Save poor boy!!! 😭

**Comment by fredvernier** [comment]
did you check if you're in standard java mode ? some mode are broken

**Comment by gnefiy** [comment]
How to check? I've tried  the P3D tutorials in standard java mode, then no effect. But something is very strange when I closed the running window, and that moment can see the running result,  but just the moment.

**Comment by moritzsalla** [comment]
I've found a workaround. Specifying `frameRate()` will make it run fine. 
Perhaps it has something to do with OpenGL being deprecated.

**Comment by gnefiy** [comment]
THANK YOU！it works！！！

**Comment by benfry** [comment]
Try using the alpha release of Processing 4 instead: https://github.com/processing/processing4/releases

This problem was due to a problem in the OpenGL library that we rely on, which we've updated in that release.
