### ISSUE TITLE
Processing UI unreadable on 4K Monitor

### ISSUE THREAD

**Issue by andykmiles** [processing/processing#6122]
## Description
When installed on a PC with a 4K monitor the UI is far too small to read, even after setting scaling to 300%

## Expected Behavior
DIsplay should be rendered so it is readable

## Current Behavior
See above

## Steps to Reproduce

1. Install on PC with 4K monitor
2. Review the UI

## Your Environment

* Processing version: Latest
* Operating System and OS version: Ubuntu 20.10
* Other information:

**Comment by benfry** [comment]
Have you set the scaling in the Preferences panel for Processing?

**Comment by andykmiles** [comment]
Yes. I mentioned above that even at 300% it is still unreadable. Thanks for the suggestion though

**Comment by benfry** [comment]
This should be in better shape in 4.0 beta 4, and with additional improvements coming in beta 5.
