### ISSUE TITLE
I get an error, while trying to open processing

### ISSUE THREAD

**Issue by EinsMalte** [processing/processing#6123]
## Expected Behavior

I expected processing 4 to open

## Current Behavior

I get an unknown error
## Steps to Reproduce

1. Download Processing
2. Extract Processing from zip file
3. Try opening processing.exe

## Your Environment

Windows 10
 

* Processing version: 4.02a
* Operating System and OS version: Windows 10
* Other information:
![Fehler](https://user-images.githubusercontent.com/49271270/99902142-ccb73f80-2cbb-11eb-960b-577052e7f781.png)

**Comment by lucabuka** [comment]
I had the same on platform
   Win 10 Home, Ver 20H2 - OS build 19042.685

In my case is was the antivirus (Microsoft defender antivirus - Bit defender)
who identify the processing lib as a virus (troyan) and removes it.

After telling bit-defender the processing lib was not a virus, everything works as expected.
...hopefully the antivurus was wrong...

**Comment by benfry** [comment]
Make sure `core.jar` hasn't been deleted by Windows Defender. 

If you're still having trouble, please use the forum for general troubleshooting questions: https://discourse.processing.org.
