### ISSUE TITLE
problem with P3D mode 

### ISSUE THREAD

**Issue by linuxthio** [processing/processing#6125]
Profile GL4bc is not available on X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x7f117801b150, owner true, ResourceToolkitLock[obj 0x77d05e1, isOwner true, <34291d6, 46400fda>[count 1, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>]]], but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES3.hw], GLProfile[GL2ES1/GLES1.hw], GLProfile[GL4ES3/GL4.hw], GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GLES3/GLES3.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw], GLProfile[GL2GL3/GL4.hw]]

**Comment by benfry** [comment]
Sounds like https://github.com/processing/processing/issues/6154 or https://github.com/processing/processing/issues/6160 but this is too little information to know.
