### ISSUE TITLE
sketch window is small and I can't see my sketches 

### ISSUE THREAD

**Issue by wynn9284u493** [processing/processing#6130]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by BlueBlueTeam** [comment]
Maybe check the size() parameter of the sketch, or if there even is one?

**Comment by safakonol** [comment]
> Maybe check the size() parameter of the sketch, or if there even is one?

Yeah thanks. I did something similar to that, someone commented a few lines to copy and paste on top, and it works. But it’s still not working ideally. I’m new to programming and hopefully figure such things out on the way :)

**Comment by benfry** [comment]
Sounds like it's working? But if not, please use the forum: https://discourse.processing.org/
