### ISSUE TITLE
Print () println () generate a weird language

### ISSUE THREAD

**Issue by icecr5** [processing/processing#6136]
## Description
print () println() statement generate a weird language 
 I using windows and when i execute for example print ("hello world"); it will execute a weird language in the console box 

## Expected Behavior
When i execute print ("hello world")
It should execute hello world in console box

## Current Behavior
but when i execute print ("hello world") it shows weird language 
![z](https://user-images.githubusercontent.com/76030388/102177443-29ca9d80-3ed6-11eb-880d-7bd4d7126c01.JPG)

## Your Environment

 

* Processing version: Processing 3.5.4
* Operating System and OS version: Windows 10 home version 1909

**Comment by benfry** [comment]
It looks like you've changed your Editor/Console font in the Preferences. Change it back and see if it works again. Otherwise, please use https://discourse.processing.org/ for troubleshooting questions.
