### ISSUE TITLE
Invalid POM.xml file for org.processing:core:3.3.7 Maven repository

### ISSUE THREAD

**Issue by mateuszbugaj** [processing/processing#6137]
## Description

I cannot build maven project with org.processing:core:3.3.7 because of an error in library's POM file

## Current Behavior

Running `mvn package -X` shows an error that later prevents from executing application.

```
[WARNING] The POM for org.processing:core:jar:3.3.7 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.processing:core:3.3.7
[ERROR] 'dependencies.dependency.systemPath' for com.apple:AppleJavaExtensions:jar must specify an absolute path but is ${project.basedir}/apple.jar @ 
```

## Steps to Reproduce

1. Include Maven dependency in pom.xml
2. run `mvn package -X`
3. Processing is not recognized by app

## Your Environment

 

```
$ mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 14.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-14-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-33-generic", arch: "amd64", family: "unix"
```

## Possible Causes / Solutions

Update pom.xml file of Processing Core library maven repository

**Comment by benfry** [comment]
Not our project.
