### ISSUE TITLE
Update Processing version on Maven

### ISSUE THREAD

**Issue by ademuri** [processing/processing#6138]
I am starting a new project using Processing, and would like to use Maven as I am pulling in other Java libraries. The version on Maven central is 3.3.7, a bit behind the current release (3.5.4). Could you update the Maven repository, please?

**Comment by ademuri** [comment]
Link to Processing on Maven: https://search.maven.org/artifact/org.processing/processing-complete/3.3.7/pom

**Comment by dzaima** [comment]
[duplicate](https://github.com/processing/processing/issues/6006) - Processing doesn't actually own the maven packages, so you have to ask whoever does.

**Comment by davidpc-te** [comment]
If you just need the Processing core library, you can add it to your local Maven repository by downloading the latest release (3.5.4), changing to the `core/library` directory and running this command:

`mvn install:install-file -Dfile=core.jar -DgroupId=org.processing -DartifactId=core -Dversion=3.5.4 -Dpackaging=jar`

After doing that, you should be able to add the dependency to your `pom.xml` like this:
```
<dependency>
    <groupId>org.processing</groupId>
    <artifactId>core</artifactId>
    <version>3.5.4</version>
</dependency>
```
If you need other libraries, they could probably be added in a similar fashion.

**Comment by davidpc-te** [comment]
Found another public maven package that includes the Processing core library at version 3.5.3. To include it in your pom.xml, add the repository like this:
```
<repositories>
    <repository>
        <id>clojars</id>
        <url>https://clojars.org/repo/</url>
    </repository>
</repositories>
```

Then add the dependency: 
```
<dependencies>
    <dependency>
        <groupId>quil</groupId>
        <artifactId>processing-core</artifactId>
        <version>3.5.3</version>
    </dependency>
</dependencies>
```

**Comment by davidpc-te** [comment]
Turns out, it's not that hard to create a simple Maven repo to host a jar file.
Here's what I came up with: https://processing-for-maven.netlify.app

**Comment by benfry** [comment]
It's not supported since I don't have time, and nobody's volunteered to support it consistently.

I wish folks wouldn't post it there because then the bug reports about it being broken still come to me. Like this one. And many others, i.e.: https://github.com/processing/processing/issues/5666
