### ISSUE TITLE
Unexpected unreadable font in Main menus of Processing 3.5.4 English Win7x64

### ISSUE THREAD

**Issue by Sunnysky** [processing/processing#6140]
## Description
1st time install shows unexpected font in main menu only

![image](https://user-images.githubusercontent.com/2910007/103421928-ec6c3e00-4b6c-11eb-93e4-f6e12528fcf3.png)
 

## Your Environment
 Win7 x64  English
![image](https://user-images.githubusercontent.com/2910007/103421982-348b6080-4b6d-11eb-9be0-d87644037ba0.png)

Installed latest java , + enable passthru firewall
 
Shown in procexp below
![image](https://user-images.githubusercontent.com/2910007/103422180-17a35d00-4b6e-11eb-848f-87019afe5b4d.png)

Very weird for java to do this.  Need Help.

**Comment by benfry** [comment]
Doesn't look like a Processing problem. Those are system fonts, and it looks like you're using a hacked copy of Windows…
