### ISSUE TITLE
documentation for colorMode() does not make clear what the default mode is, if a sketch never calls it

### ISSUE THREAD

**Issue by macginitie** [processing/processing#6141]
For example, let's say I'm a newbie, trying to jump in with an example. The example includes calls to fill() and background() that pass a single integer value. (The example code includes NO call to colorMode()). I want to know what those parameter values mean. How would I find the doc for colorMode()? I look at the reference for fill() or background() and see it listed there in the "see also" section.

It seems to me therefore, that the doc for colorMode() is a logical place to state what Processing's default setting for colorMode is. If someone else thinks so too, I'd be glad to try to add it. Or, if someone closing this issue would kindly explain why I'm wrong, I could learn something. Thanks for your great work :)

**Comment by benfry** [comment]
I think you may have just missed it; it's the fourth sentence in the fill() documentation.

**Comment by macginitie** [comment]
heh, thanks, I learned something :-o

**Comment by benfry** [comment]
:)
