### ISSUE TITLE
randomSeed behavior

### ISSUE THREAD

**Issue by ChuckGaston** [processing/processing#6143]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by ChuckGaston** [comment]
When using random() after randonSeed(), one should expect a different result for each different seed; however, the FIRST random() value seems independent of the seed.  Solution:  immediately after randomSeed(), get and discard one random() number.

**Comment by ChuckGaston** [comment]
Example output from a program that sets a randomSeed(seed) then gets a sequence of four random(100, 500) numbers -- except for the first "random" returned, it works as expected.
seed rnd1  rnd2  rnd3  rnd4
100   388   393   177   386   
101   388   101   245   306   
102   388   178   442   145   
103   388   286   110   465   
104   388   424   449   468   
105   388   131   117   388   
106   388   209   313   227   
107   388   316   381   147

**Comment by benfry** [comment]
Can't reproduce this, it's probably a bug in your code, i.e. something strange about how your loops are interacting with each other.

```processing
randomSeed(12);
for (int i = 0; i < 10; i++) {
  println(int(random(100, 500)));
}
```

Produces:

```
391
123
210
187
292
114
475
347
116
472
```

```processing
randomSeed(17);
for (int i = 0; i < 10; i++) {
  println(int(random(100, 500)));
}
```

Produces:

```
392
418
378
335
133
260
426
495
117
437
```

**Comment by ChuckGaston** [comment]
No bug in my code.  It's a real bug with randomSeed.  

You almost reproduced the problem, but didn't try enough random seeds.  I didn't try enough different ones either, and thought the first random number was always 388.
For seeds 0 through 17, the first random is 392 except for seeds 12, 13 & 15, which give 391.  (I suspected it was no coincidence when your two examples gave numbers close together.)
Seeds 80 to 95 all give 390.  Seeds 100-111 all give 388.  As you can see in the attached screen shots, 1053 different seeds gave no more than 52 different (integer) values for the first random number.
 
I haven't investigated the fundamental floating-point values, but that first random number after a seed is clearly not random.
Chuck Gaston
 
 
-----Original Message-----

**Comment by benfry** [comment]
Sorry, missed this response earlier before the bot locked it. 

This is fundamentally how random numbers work, and why the need to “seed” the random number generator exists. It's not random at all (just pseudorandom) and the seed provides a way to initialize something to appear more random, or create repeatable results. There's no guarantee that a different seed will produce a different first result. If it was `391` regardless of the seed, that would be a concern. But all we're doing is calling out to Java's built-in `Random` class, which was created by people smarter than me.
