### ISSUE TITLE
size() not parsed proplerly in "condensed" sketches

### ISSUE THREAD

**Issue by micuat** [processing/processing#6144]
## Description

size function seems not parsed properly when generating intermediate java code.

## Expected Behavior

this code should compile

```java
float i,A,B;size(800,800);noStroke();background(-1);
```

## Current Behavior

the code above aborts with 

```
p5t.pde:1:2:1:2: unexpected token: float
```

## Steps to Reproduce

I found this issue through tweet processing (code golf) - that this code doesn't work

ref: https://twitter.com/reona396/status/1347148957915385857

```java
float i,A,B;size(800,800);noStroke();background(-1);
```

if there is space or newline after the semicolon of float, it compiles

```java
float i,A,B; size(800,800);noStroke();background(-1);
```

or swapping float and size works too

```java
size(800,800);float i,A,B;noStroke();background(-1);
```

generating the following intermediate java code

```java
import processing.core.*; 
import processing.data.*; 
import processing.event.*; 
import processing.opengl.*; 

import java.util.HashMap; 
import java.util.ArrayList; 
import java.io.File; 
import java.io.BufferedReader; 
import java.io.PrintWriter; 
import java.io.InputStream; 
import java.io.OutputStream; 
import java.io.IOException; 

public class p5t extends PApplet {
  public void setup() {
float i,A,B; noStroke();background(-1);
    noLoop();
  }

  public void settings() {  size(800,800); }
  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "p5t" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
```

## Your Environment

* Processing version: 3.5.4
* Operating System and OS version: linux/windows (perhaps mac too)

**Comment by dzaima** [comment]
This appears to already be fixed in Processing 4, for what it's worth. (Processing 4 rewrote most of the code parsing/generation)

**Comment by benfry** [comment]
Yeah, this is why all that code was rewritten in 4.x. I recommend using the alpha releases; they're in better shape for just about everything.
