### ISSUE TITLE
any way to set custom font sizes in PDE for the UI?

### ISSUE THREAD

**Issue by derVedro** [processing/processing#6145]
## Description

On gnome3 the PDE has a really tiny user interface. For example line numbers or code completion drop down menus are weeny. The coding experience is bad. I read some another issues about UI scaling here, and it's looks like an Linux/Gnome3 problem with DPI. But it is a really old one. I can remember that if I tried do some processing in last 10 years I had always the same eyes cancer. I do not think that it will be solved on gnome side. So on PDE side you can set the console and code font sizes, why not do some additional settings for the rest of UI?

## Your Environment

 

* Processing version: 3.5.3
* Operating System and OS version: Ubuntu 20.10 / Gnome3

**Comment by benfry** [comment]
It's directly below the font size settings:

<img width="535" alt="Screen Shot 2021-01-17 at 5 28 47 PM" src="https://user-images.githubusercontent.com/1623101/104857891-8a8c3200-58e9-11eb-8998-40ec115906f8.png">

**Comment by derVedro** [comment]
Okay with 150% scaling I get readable line numbers, but code comletion drop down menu is still terrible. 

![fooo](https://user-images.githubusercontent.com/4129535/105179886-2d32f380-5b2a-11eb-8441-fd5f717213c1.png)
