### ISSUE TITLE
P3D SIGILL on 2020 iMac

### ISSUE THREAD

**Issue by airbornemint** [processing/processing#6146]
## Description

P3D renderer crashes on my 2020 iMac with SIGILL. Log attached.

## Steps to Reproduce

```
void setup() {
  size(640, 360, P3D);
}

```

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: macOS Big Sur 11.1 (20C69)
* Other information:

Running on 27" 2020 Retina 5K iMac, 10-core 3.6GHz Intel Core i9 CPU, 40GB RAM, AMD Radeon Pro 5500 XT 8 GB VRAM. Full system profile attached 

[hs_err_pid74628.log](https://github.com/processing/processing/files/5791420/hs_err_pid74628.log)

[iMac.spx.zip](https://github.com/processing/processing/files/5791434/iMac.spx.zip)

**Comment by benfry** [comment]
That's an error inside the OpenGL library we're using (JOGL). Your machine is similar to the one I use for testing and development but don't have this problem, so you might check to see if there's anything else (other graphics software installed, etc) that might be causing trouble. 

Or we're just at the mercy of any JOGL updates that might resolve the issue.
