### ISSUE TITLE
IDE Close - Save changes dialogue ignores Y and N

### ISSUE THREAD

**Issue by RichardDL99** [processing/processing#6147]
## Description
When you close the IDE it may prompt you to save changes - with Yes and No buttons. The Y and N are underlined, indicating that it accepts Y or N (or y or n) but it doesn’t.

## Expected Behavior
It should accept the keypresses Y,y,N,n as the same as mouse click on the yes and no buttons.

## Current Behavior
It ignores the keypresses.

## Steps to Reproduce
1. New sketch window
2. Type something
3. Close the window ^w
4. On save changes window press y

## Your Environment
Windows 10
Processing 3.5.3
Issue also present on RPi.

**Comment by dzaima** [comment]
The underlined characters mark that they are valid shortcuts while alt is held - and, sure enough, alt+y and alt+n work.

**Comment by RichardDL99** [comment]
Oh yes, so they do work, but no-one knows that.  I posted on the forum
[https://discourse.processing.org/t/processing-interaction-imperfections-on-windows/18686](url) and no-one pointed that out.

In all(?) other Windows programs on Save y/n dialogue, alt is not needed. Notepad++, SciTE, MS Word, Excel, MS Paint, Notepad, Visual Studio.

**Comment by benfry** [comment]
Closing since it sounds like it's a misunderstanding.

**Comment by RichardDL99** [comment]
I don't see it as a mis-understanding.  I see it that this dialogue in Processing works differently from equivalent dialogues in other Windows programs.  I'd have thought you'd want it to follow the standard scheme.
