### ISSUE TITLE
processing 3pd issues

### ISSUE THREAD

**Issue by birdy123123** [processing/processing#6150]
### Issue description
wrong code
but I'm a freshman, so 

2020-12-28 22:44:30.873 java[4437:360571] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
0 AppKit 0x00007fff22c798bf -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 352
1 AppKit 0x00007fff22c64561 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1375
2 AppKit 0x00007fff22c63ffb -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
3 libnativewindow_macosx.jnilib 0x000000012a3043fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
4 ??? 0x000000011b11dc84 0x0 + 4749122692
)

by the way ,my laptop is macbookpro 2015 13.3

**Comment by benfry** [comment]
Closing; not enough information here to follow up because the template was ignored.
