### ISSUE TITLE
Port not found

### ISSUE THREAD

**Issue by tanjunyu-tanjunyu** [processing/processing#6153]
## Description

I using processing and cannot find any port 
And the line "println(Serial.list());" is yellow color

I not sure ist a bug of window or what,
I already read through many website and post still cannot find any way to solve it

## Expected Behavior

I just wanted to find back my port that can use 
Before that i can use and find a port, but don know y suddenly dissapear

## Current Behavior

Cannot find the port 
Println the serial list is nothing come out 

## Steps to Reproduce

I use this code and the "println(Serial.list());" is empty and yellow under line,
At the debug i find a red color word 
"RuntimeException: Error opening serial port ttyACM0: Port not found"

import processing.serial.*;
Serial myport; // Create object from Serial class

void setup() {
println("Here is a list of serial ports:");
println(Serial.list());
println("List finished, opening port");
myport = new Serial(this, "ttyACM0", 9600);
myport.bufferUntil('\n');
}
void draw()
{
}

void serialEvent(Serial myport)
{
String inString = myport.readStringUntil( '\n' );

println(inString);
}

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

## Possible Causes / Solutions

If can thank for helping I go through many about processing port and I cannot find and solve

**Comment by benfry** [comment]
Please use https://discourse.processing.org/ for troubleshooting questions.
