### ISSUE TITLE
P3D doesnt work on gl4bc and Nvidia drivers

### ISSUE THREAD

**Issue by aquaresima** [processing/processing#6154]
## Description
Hi, I tried to wrap my mind around this before posting, but can't find a way out. On Linux everything with graphic cards is complicated and I don't want to break my configuration with the nvidia.

Basically, this is the trouble:

when I run

`size(myW,myH,P3D)`

I get:

`Profile GL4bc is not available on X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x7f9ecc01b110, owner true, ResourceToolkitLock[obj 0x557a062a, isOwner true, <5145885d, 14470c11>[count 1, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>]]], but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES3.hw], GLProfile[GL2ES1/GLES1.hw], GLProfile[GL4ES3/GL4.hw], GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GLES3/GLES3.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw], GLProfile[GL2GL3/GL4.hw]]`

## Your Environment
Kernel: 4.19.163-1-MANJARO #1 SMP Fri Dec 11 17:21:11 UTC 2020 x86_64 * Processing version:
Processing version: 3.5.4
Graphic drivers: 
`mhwd -d -li `
   NAME:	video-modesetting
   ATTACHED:	PCI
   VERSION:	2020.01.13
   INFO:	X.org modesetting video driver.
   PRIORITY:	1
   FREEDRIVER:	true
   DEPENDS:	-
   CONFLICTS:	-
   CLASSIDS:	0300 
   VENDORIDS:	* 

   NAME:	video-linux
   ATTACHED:	PCI
   VERSION:	2018.05.04
   INFO:	Standard open source drivers.
   PRIORITY:	2
   FREEDRIVER:	true
   DEPENDS:	-
   CONFLICTS:	-
   CLASSIDS:	0300 0380 0302 
   VENDORIDS:	1002 8086 10de 

   NAME:	video-hybrid-intel-nvidia-prime
   ATTACHED:	PCI
   VERSION:	2020.11.30
   INFO:	Hybrid prime solution for NVIDIA Optimus Technology - Closed source NVIDIA driver & open source intel driver.
   PRIORITY:	6
   FREEDRIVER:	false
   DEPENDS:	video-modesetting 
   CONFLICTS:	video*nvidia* 
   CLASSIDS:	0300 0302 0300 
   VENDORIDS:	10de 8086

**Comment by ciaron** [comment]
I found this workaround to "fix" the issue: https://discourse.processing.org/t/solved-p2d-p3d-sketches-wont-start-on-fresh-ubuntu-18-04-installation/3568/33

The problem seems to have been around in various forms since 2018 (on newer hardware?). Like you, I'm reluctant to mess about with Linux graphics stuff. Slightly frustrated that I will have to modify all my sketches.

Dell Latitude 7410
Mesa Intel® UHD Graphics (CML GT2)
Ubuntu 20.04.2 LTS
Processing 3.5.4

**Comment by benfry** [comment]
Try with the 4.x alpha releases, which have a newer JOGL.

**Comment by benfry** [comment]
Closing since it should be fixed in the 4.0 releases: https://github.com/processing/processing4/releases
