### ISSUE TITLE
Processing does not build on Oracle JDK 8u281

### ISSUE THREAD

**Issue by lourkeur** [processing/processing#6155]
## Description

When using the latest JDK from Oracle, `ant build` fails to compile `PSurfaceFX` because of missing methods in `com.sun.glass.ui.Screen`. it builds fine on the previous release (8u271) under the exact same circumstances.

## Expected Behavior

Compilation should succeed.

## Current Behavior
Compilation fails with the [attached error output](https://github.com/processing/processing/files/5882577/processing.log).

## Steps to Reproduce

1. Retrieve the source code of Processing 3.5.4
2. Install or select Oracle JDK 8u281
3. Attempt to build Processing

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: NixOS 20.09 (a GNU/Linux distribution)
* Other information: I am a NixOS contributor and discovered this issue when trying to update [Oracle JDK on our end.](https://github.com/NixOS/nixpkgs/pull/110798)

## Possible Causes / Solutions

The most likely cause is the fact that between the two versions, the (internal use) interface of `com.sun.glass.ui.Screen` changed, removing the `getUIScale()` and `getRenderScale()` methods. This is evidenced in the `javafx-src.zip` file in both distributions.

There does not seem to be a patch in the master branch.

I might take a stab at trying to restore functionality with the new methods. I will also check processing4 because it might already contain a usable patch.

#5059 tackles the issue of version-bumping the jdk dependency. (because of the same class, funnily enough)
#5286 discusses the use of these methods in the long run.

**Comment by benfry** [comment]
That's not a release of Java that we're supporting, sorry.
