### ISSUE TITLE
Recent install failures on Ubuntu 20.10

### ISSUE THREAD

**Issue by JLBD7** [processing/processing#6157]
Thank you for making this great software available.  I am running it in MacOs and on Raspberry Pi OS. I followed the instructions in this video to install it on Ubuntu 20.10.  https://www.youtube.com/watch?v=ZhWP1hx-oyQ.  I got the nice icon but nothing happens when I click on it.  It does not work for me.  This is what happens when I try to run it.  Maybe a Java versioning issue and if I fix Processing I break something else?

AFTER CLICKING ON THE PROCESSING ICON I OPEN A TERMINAL AND TYPE "sudo tail -f /var/log/syslog" AND IT GIVES THE FOLLOWING:
Feb  2 09:02:18 ub-desktop systemd[1621]: Started Application launched by gnome-shell.
Feb  2 09:02:18 ub-desktop processing-pde.desktop[37287]: -Djava.ext.dirs=/home/ub/Downloads/processing-3.5.4/java/lib/ext is not supported.  Use -classpath instead.
Feb  2 09:02:18 ub-desktop processing-pde.desktop[37287]: Error: Could not create the Java Virtual Machine.
Feb  2 09:02:18 ub-desktop processing-pde.desktop[37287]: Error: A fatal exception has occurred. Program will exit.
Feb  2 09:02:18 ub-desktop systemd[1621]: app-gnome-processing\x2dpde-37277.scope: Succeeded.

TERMINAL INFORMATION
ub@ub-desktop:~/Downloads/processing-3.5.4$ pwd
/home/ub/Downloads/processing-3.5.4
ub@ub-desktop:~/Downloads/processing-3.5.4$ ./processing
ub@ub-desktop:~/Downloads/processing-3.5.4$ -Djava.ext.dirs=/home/ub/Downloads/processing-3.5.4/java/lib/ext is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
^C
ub@ub-desktop:~/Downloads/processing-3.5.4$ java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.10)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.10, mixed mode)
ub@ub-desktop:~/Downloads/processing-3.5.4$ 

A cursory we search indicates that Processing installs have not worked on Ubuntu recently.  And the Processing download website does not have the previous downloads that appeared to work.  I will go on to other things, spending more time on this is not worth it right now.  

Thanks again.

**Comment by crazy-logic** [comment]
Just checked and it installs fine with the current versions of 20.04.02 and processing 3.5.4, will try 20.10 now.

**Comment by crazy-logic** [comment]
Just checked and it installs fine with the current versions of 20.10 and processing 3.5.4. it also runs the sketches just fine. if i do 'java --version' it says java actually isn't installed, so i assume given the folders that processing folder/java/bin is where the java being used is actually installed. try downloaded and extracting to a new folder (with new name) and then from a terminal running ./path-to-folder/processing

**Comment by benfry** [comment]
It doesn't work with Java 11 (https://github.com/processing/processing/wiki/Supported-Platforms#java-versions), but it will work with the version of that's included with the Processing software. That's why we include an embedded version of Java with the download.
