### ISSUE TITLE
Set double in glsl shader

### ISSUE THREAD

**Issue by GanerCodes** [processing/processing#6165]
Doubles were added to GLSL a bit ago, however they are not included in the types that can be passed with .set()

**Comment by dzaima** [comment]
[previous issue](https://github.com/processing/processing/issues/6084) - the library Processing uses to interface with GLSL just doesn't have any way to set doubles.

**Comment by benfry** [comment]
Closing as duplicate of https://github.com/processing/processing/issues/6084
