### ISSUE TITLE
[Feature request] Ignore window size change during loadPixels() and updatePixels()

### ISSUE THREAD

**Issue by MisterPrintf** [processing/processing#6172]
Currently, surface.setResizable(true) is semi-useless when utilized in conjunction with pixels[], since loadPixels() and updatePixels() both throw ArrayIndexOutOfBounds exceptions if the window size changes during their operation.

What I'd like to see is some sort of implementation that separates canvas size from window size, and then refuses to resize the canvas while loadPixels() or updatePixels() is active.

**Comment by benfry** [comment]
If we didn't update the size of the pixel buffer, the sketch window would be blurry when the window was enlarged, which would be a totally unacceptable result for nearly all users.
