### ISSUE TITLE
Implementation of PVector.setHeading()

### ISSUE THREAD

**Issue by arijit4** [processing/processing#6176]
There's an method named `PVector.setHeading()` in `p5.Vector` class of p5.js to set the direction of an vector to any given angle. But there's no such option in Processing. It can be settled down easily. But the function seems more self explanatory and easy to understand. It also goes well with the `PVector.heading()` method already present in Processing.

An implementation might look like the following :
```processing
void setHeading(float angle) {
    this.rotate(angle - this.heading());
}
```

**Comment by StanLepunK** [comment]
I think for this suggestion it's better to post here https://github.com/processing/processing4/issues

**Comment by benfry** [comment]
Incorporated for 4.0 alpha 4 (no plans to backport to 3.x)
