### ISSUE TITLE
Sketch not running with P2D/P3D

### ISSUE THREAD

**Issue by shadoxxhd** [processing/processing#6177]
## Description
When trying to run a sketch with P2D/P3D renderer, no window opens.

## Expected Behavior
The sketch window opens.

## Current Behavior
The sketch window doesn't open with P2D/P3D renderer,  but a jogamp_exe_tst[some number].exe process is spawned (that doesn't close when the java.exe is stopped from the processing IDE).

## Steps to Reproduce

1. size(1920,1080) -> works
2. size(1920,1080,P2D) -> doesn't work

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: windows 10
* Other information: my AV reported no actions, so it is quite unlikely to be the cause of the issue

**Comment by StanLepunK** [comment]
Hello, I don't have Window OS to test. But just for test the bug are you try : 
if the bug happen only with size(1920,1080,P2D) or with different size ?
and test to change the size dynamiclly ?
```
void set() {
  size(300,300,P2D);
  surface.setResizable(true);
}

void draw() {
 surface.setSize(1920,1080);
}
```

To see what happen in this case ?

**Comment by shadoxxhd** [comment]
with 300x300 the behavior is the same. I can't try resizing since even a blank 300x300 P2D sketch doesn't even start.

**Comment by StanLepunK** [comment]
What happen with P3D render ?

**Comment by shadoxxhd** [comment]
Sorry for the long delay - P3D has the same problem, FX2D seems to work. I did not try Processing 4 yet.

**Comment by shadoxxhd** [comment]
I was just trying again, and it seems that if I click the "run" button, then open my task manager and kill the "jogamp..." process twice (it apparently revives once), the sketch opens (but not before that)...

**Comment by shadoxxhd** [comment]
And even without a running jogamp... process P2D-exclusive features like shaders in the BlurFilter example work fine.

**Comment by shadoxxhd** [comment]
When running a sketch, a "%temp%\jogamp_exe_tst<some long number>.exe" process is created. Once I terminate that, a %temp%\jogamp_0000\joganp_exe_ts<some *different* number>.exe" replaces it. And when I terminate *that*, the sketch finally opens.

**Comment by benfry** [comment]
The OpenGL library may be triggering virus scanning on your machine, which can cause a significant delay while the sketch starts up. Other than that, please use the forum for troubleshooting issues like this.
