### ISSUE TITLE
java.util.EmptyStackException reported

### ISSUE THREAD

**Issue by tSchneckenhaus** [processing/processing#6180]
I'm programming a multiplayer game using the network library from processing. Sometimes, after I start the server, I can only press the stop button in processing and the rest does not react. I haven't yet recognized a pattern of when it crashes and when it doesn't.
Until now, I have always restarted the program (but the memory request still came, which means that no data was lost) until the following error message came up:
![Problem with Network-library](https://user-images.githubusercontent.com/62906715/117883884-44017f80-b2ac-11eb-8804-5b082a461b08.JPG)
Since it said that I should report this error, I have now done this here.
I use processing 3.5.4 on Windows 10 (HP Pavilion 550-235ng Intel i5)

**Comment by robertesler** [comment]
I'm getting something similar but I'm not using the network library.  I'm testing my own audio library using jPortAudio.  This happens somewhat randomly but definitely after running a sketch a few times.  The error gets thrown when trying to run the sketch and this dialog box appears when I try to open a new sketch via the menu.    
![ProcessingError](https://user-images.githubusercontent.com/13873685/118567157-23ad4700-b72a-11eb-9913-19ebfc5ad10a.PNG)
When I run my audio library outside of P3, just pure Java in Eclipse, I don't get the error.  I've also tested my library with Java's sound API, no errors.  So it seems to be something with jPortAudio and P3.  Any ideas on what could be happening would be most welcome. 
I'm also on P3 3.5.4, Win10, i7.

**Comment by tSchneckenhaus** [comment]
In the network library there is an event for clients with which they can receive the messages from the server. You do not have to use this event, however, because you can also permanently query in the draw whether a new message has arrived. The problem with this, however, is that messages sent too quickly are made directly to each other (for example, from "say: Hello" and "drive: 10" it would make "say: Hellodrive: 10" and instead of saying Hello and drive 10) he say Hellodrive:10)
I then just put a \ to each command at the end so that it then separates all messages there again.
Since then, Processing has only been crashed once. So the problem is probably with the event.

**Comment by benfry** [comment]
These look like doing an excessive amount of `print()` statements from the code, or doing them exceptionally quickly. You might also check if they're `print()` and not `println()` statements, causing the console to get jammed up with a single line that's thousands and thousands of letters long.

**Comment by ashraf546** [comment]
Instead, what you should do:

Read the input. For each symbol:
  if it is a number,
    push it on the stack.
  else,
    pop two numbers from the stack,
    perform the operation and
     push the result.

**Comment by benfry** [comment]
The original issue here should be resolved in Processing 4 as part of this issue https://github.com/processing/processing4/issues/338
