### ISSUE TITLE
Wrong path set for embeded java Linux(64-bit) in Exported Application script from Processing 3 IDE (3.5.4)

### ISSUE THREAD

**Issue by akseidel** [processing/processing#6182]
In the Exported Application sh script for Linux64 where java is selected to be embeded, the path for the embeded java is not correct, or you could say the embeded java is not placed where it should be.

The Exported Application script has $APPDIR/java/bin/java. It needs to be $APPDIR/java/java/bin/java to point where the embeded java is actually placed.

**Comment by benfry** [comment]
Seems to be exporting correctly for me here on a fresh install and Ubuntu 20.04. 

Do you have your `java` directory symlinked to a different installation or something on those lines?

**Comment by akseidel** [comment]
No I do not think so because java is not installed. I am using the “Embed java for Linux(64-bit)” option. However, I now find it working also! I did perform a full-upgrade prior to testing and it has been weeks since I tested it last.

**Comment by benfry** [comment]
Ok, glad it's working.
