### ISSUE TITLE
running 3D program is so slowly 

### ISSUE THREAD

**Issue by niukailun** [processing/processing#6183]
I am new to learn 3D in processing, when I running some easy and small size 3D program it is works. However, when I use big size like size(1500,1000,P3D); it is running sooo slowly and every time I try to interacation with my program, it is respond so slowly as well, how can I fix this problem? it is my laptop issuse or something else?

**Comment by benfry** [comment]
Hi, please use https://discourse.processing.org/ for troubleshooting questions like this. Thanks!
