### ISSUE TITLE
Export fails in Big Sur when there is an existing application.macosx folder

### ISSUE THREAD

**Issue by akseidel** [processing/processing#6185]
Prior to Mac OSX update to Big Sur (11.4) Processing 3.5.4 would successfully overwrite any existing application.macosx export (with embedded Java option). Now it does not unless the application.macosx folder and its contents are first deleted. Error starts as:

> Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Unable to load library 'CoreServices': Native library (darwin/libCoreServices.dylib) not found in resource path. ..................

**Comment by benfry** [comment]
This seems to be a problem with Big Sur and the JNA library that we use. I've already added a workaround for Processing 4.0 alpha 4 (not yet posted), but it's unlikely to be fixed for 3.x.

**Comment by benfry** [comment]
Confirmed to be working with 4.0 alpha 4. (It's the same as this issue: https://github.com/processing/processing4/issues/159)

I recommend using that release once it's available; I won't have time to backport changes to 3.x.
