### ISSUE TITLE
 forum.processing.org isn't working in my region.

### ISSUE THREAD

**Issue by ilanzs** [processing/processing#6187]
## Description
I was have a problem which I ended up figuring out by myself but when I want to forum.processing.org it said I was on the wrong time and didn't let me access the page. it said "your clock is ahead". I live in Israel and I am on standard Israeli time and it seems like your website is getting confused by it.

## Expected Behavior
I was expecting to go on to  forum.processing.org and look at the link I clicked on. 

## Current Behavior
gives me a screen that says "your clock is ahead. a private connection to forum.processing.org cannot be established because your computers date and time are incorrect.

## Steps to Reproduce
1.change your computer time to israel time
2.go to forum.processing.org

## Your Environment
I am on a lenovo laptop and I am in israel

## Possible Causes / Solutions
I am not much of a backend web developer but I would assume there is a way to include people on israeli time to go onto your wedsite

**Comment by dzaima** [comment]
forum.processing.org has an outdated SSL certificate, this isn't a problem just for israeli time. But it's just a redirect to https://discourse.processing.org/, which works fine

**Comment by benfry** [comment]
That's correct; it has nothing to do with Israel or timezones. The certificate had just expired. That should now be fixed.

Though the server also had to be moved to a different IP, it may be unavailable until your machine gets the new DNS information. (If anyone has trouble, you can reset your DNS cache, reboot your machine, or yell at your internet provider for their slow DNS updates; whatever makes you feel best.)
