### ISSUE TITLE
Really portable

### ISSUE THREAD

**Issue by SebCanet** [processing/processing#6189]
Hi,
I'm working in schools and I would to use a portable version, usable on USB stick. Also because there are securities, and as I work in different schools there are different securities. On Processing4a6 I didn't find all the option I could find in Processing2 preferences to make quite portable (because it still write in c:\Users\AppDatat\etc). I tried to use relative path (like save datas in './data') but it transforms it in absolute path.

Thanks a lot for helping me.

**Comment by benfry** [comment]
Duplicate of #3948.
