### ISSUE TITLE
java.util.ConcurrentModificationException in formerly working script

### ISSUE THREAD

**Issue by i-make-robots** [processing/processing#6197]
## Description
https://github.com/i-make-robots/truchetTiles/ was written for processing 3.
In processing 4 in no longer works... some of the time.

## Expected Behavior
Unchanged from processing 3.

## Current Behavior

	java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at truchetTiles$Line.draw(truchetTiles.java:101)
	at truchetTiles.draw(truchetTiles.java:249)
	at processing.core.PApplet.handleDraw(PApplet.java:2209)
	at processing.awt.PSurfaceAWT$10.callDraw(PSurfaceAWT.java:1419)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:354)

Problem 2 is the error message seems to be gibberish.  The lines in question aren't being run - put a println() on the line above, does not get hit.  Put a break point, same story.

Note the _truchetTiles$Line.draw(truchetTiles.java:101)_ " : Line.draw() exists from file lines 81 to 86.  it can't possibly be on line 101.

## Steps to Reproduce
Run app, select "alan-turing.jpg" as first file, select "code.jpg" as second file.  Still works.
Run app, select "alan-turing.jpg" as first file, select "drug.jpg" as second file.  No longer works.

## Your Environment
* Processing version: 4.0b1
* Operating System and OS version: Windows 10
* Other information: I have OpenJDK 15 installed for other java work.  not sure if related.

## Possible Causes / Solutions
Since the debugger is misleading, I'm not sure what to suggest here.  Sorry if that makes for a crappy bug report.

Thank you for all your hard work.

**Comment by benfry** [comment]
That's a bug in your code, unfortunately. It means that more than one thread is trying to make changes to that `ArrayList` at the same time. I'd post at https://discourse.processing.org/ to see about getting help with it. You probably have one part of the code adding an entry, and another part removing/modifying part of it, and there's a collision. (The fact that it worked in 3.x, and sometimes works in 4.x is just the nature of issues with threads.)

The line number is from the `.java` version of the code, not your `.pde` file. The PDE itself should be translating that line number to the correct line in your code (highlighting it in the editor), but it's not always able to do that, so it may not be happening for you.

To see what that `.java` file looks like, you can use Export to Application, which should create that same `.java` file in the `src` subfolder that it creates, and you can see if the line number matches up better there.
