### ISSUE TITLE
Welcome screen persistent

### ISSUE THREAD

**Issue by ajvdmeij** [processing/processing#6200]
## Description
When I start Processing 4, I get a welcome screen. Towards the bottom there is a checkbox that says: "Show this message on startup" I don't check this box (I don't want this screen) and the next time I start Processing it jumps up again. I thought maybe it should have said:" DON'T show this page on setup"  and so I check the box and then it pops up again when I start Processing. So it doesn't do anything and the screen is persistent.

## Expected Behavior
I hope to start up Processing without the Welcome Screen

## Current Behavior
It shows up, regardless of the status of the checkbox.

## Steps to Reproduce
1.Start up Processing
2.Don't check "Show this screen on startup"
3.Terminate the program
4.Start it up again.

## Your Environment
* Processing version: 4
* Operating System and OS version: MacOS, Big Sur
* Other information: none

## Possible Causes / Solutions
I think the opt-out checkbox will be most convenient.
<img width="431" alt="Schermafbeelding 2021-08-14 om 11 52 11" src="https://user-images.githubusercontent.com/14240955/129442457-58596c42-9ea9-431a-9265-f6284e9b2e90.png">

**Comment by KevinWorkman** [comment]
Note that Processing 4 is in a new repo. Here's a bug in that repo with a potential workaround: https://github.com/processing/processing4/issues/253

**Comment by benfry** [comment]
(Closing since the issue has already been moved.)
