### ISSUE TITLE
Processing 4.0b1 core.jar reports as TrojanDownloader:Java/OpenConnection.PM

### ISSUE THREAD

**Issue by kiwi-fruitiwi** [processing/processing#6202]
## Steps to Reproduce

1. Extraction from processing-4.0b1-windows64 yields a virus warning for core.jar
2. In Windows Defender, this is reported as TrojanDownloader:Java/OpenConnection.PM

## Your Environment

 

* Processing version: 4.0b1
* Operating System and OS version: Win10 64bit, windows update is up to date as of 2021.08.18
* Other information:

**Comment by kiwi-fruitiwi** [comment]
I submitted a request to the Microsoft Defender team and they replied with,

> Analyst comments:
> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
> 
> Thank you for contacting Microsoft.

**Comment by jeremydouglass** [comment]
Thank you so much, @kiwi-fruitiwi -- for opening an issue, submitting a report, and reporting on the result.

Please note that Processing 4 and its issues are in a separate repo:

https://github.com/processing/processing4/issues

If you would, it might be helpful to cross-link the issue there in case it re-emerges in the future.

**Comment by benfry** [comment]
Since this is showing up in search results, you can read about this problem here:
https://github.com/processing/processing4/wiki/Troubleshooting#viruses-and-trojans
