### ISSUE TITLE
Processing make a virus when run

### ISSUE THREAD

**Issue by Nhanle109** [processing/processing#6203]
## Error info
1.  Run file
Have generated a virus when finish the running the processing.exe on the .zip file
2.  Virus info
Virus (trojan) is named "Oneeva.A!ml", the level of the trojan is Serve

**Comment by jeremydouglass** [comment]
This sounds like a false positive.

1. What version number of Processing do you have, and where did you get it? Did you download it from processing.org?
2. What is the name of the virus checker program that is giving this message about 
"Oneeva.A!ml"

**Comment by Nhanle109** [comment]
1: I use Processing 4.0 beta 12: Microsoft Security Được gửi từ Thư dành cho Windows Từ: Jeremy DouglassĐã gửi: 19 Tháng Tám 2021 10:41 SAĐến: processing/processingCc: Nhanle109; AuthorChủ đề: Re: [processing/processing] Processing make a virus when run (#6203) This sounds like a false positive.What version number of Processing do you have, and where did you get it? Did you download it from processing.org?What is the name of the virus checker program that is giving this message about"Oneeva.A!ml"—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benfry** [comment]
It's a false positive. Please report it to Microsoft; if enough people report it, maybe they'll fix it.
