### ISSUE TITLE
4.0b1 suddenly unable to open

### ISSUE THREAD

**Issue by samuelskottenborg** [processing/processing#6207]
## Description

All of the sudden Processing 4.0b1 is unable to open.  I tried downloading it afresh, but it still doesn't open.
The older 3.3.5 version is still able to open. I haven't tested other versions.

I'm not sure what has changed that suddenly prevents it from running correctly. I haven't installed new programs or other changes - and I already restarted my PC of course.

I tried opening as admin, but it doesn't help. It seems like there's no processes related to Processing that are visible in the task manager (even when opening).

## Environment

 

* Processing version: 4.0b1
* Operating System and OS version: Windows 10 - newest update
* Other information: 3.3.5 still works

**Comment by benfry** [comment]
Please use https://discourse.processing.org/ for general troubleshooting questions.
