### ISSUE TITLE
"NullPointerException" in MidiBus Basic example on 4.0b1 version

### ISSUE THREAD

**Issue by kkirklewski** [processing/processing#6212]
I'm getting "NullPointerException" error while trying to run the Basic example of the MidiBus library. It works fine on 4.0a2 (I just checked it). I use MacBook Pro M1 (Big Sur) with latest 4.0b1 version of Processing.

**Comment by benfry** [comment]
Please report to the author of the MidiBus library, who is responsible for that code.
