### ISSUE TITLE
Caret and selection highlight offset from character position in the editor

### ISSUE THREAD

**Issue by Jared730** [processing/processing#6213]
The Caret indicator and the selection highlight become offset to the right as you add more characters to a line when typing in the editor. After 19 characters the caret is moved to the right of about 1 character. The bug appears to happen with any combination of characters, including space. It also happens under all fonts listed in the preferences. When clicking in the middle of a line the location is properly selected but the caret indicator remains offset. This also occurs in insert mode.

The bug seems to just be visual and not actually altering the text in any way, though it makes editing lines difficult as there is no way to tell where the caret actually is or what characters are selected. 

Steps to Reproduce

1. Create a new sketch
2. Type a string of text or code more than 20 characters long into a single line in the editor.
3. Replace a word in the middle of the string
4. Compare where the caret indicator is displayed to where characters are being added/deleted/replaced

I am using a clean install of processing with no previous versions and no libraries or modifications made. This bug started occurring on the first sketch I created and it persists when reopening Processing and restarting the computer. Processing has editor font size set to 12 and the interface scale set to automatic.
I have a copy of Java version 8 build 301 on this computer.
* Processing version: 4.0b1
* Operating System and OS version: Windows 10

**Comment by soprano** [comment]
Do you have the display settings in Windows higher than 100%?

**Comment by EWokkel** [comment]
I have the same issue,  and indeed my display setting is higher than 100%. 
Setting it to 100% resolved the problem. Sort of...   I now had to change the resolution of my TV/Monitor to a non native resolution. Not ideal

**Comment by soprano** [comment]
It seems to be the same issue as here:

https://github.com/processing/processing4/issues/231

**Comment by andybak** [comment]
Just to add a comment to highlight the severity of this. The bug makes editing impossible. The workaround to change Windows display scale to 100% makes everything on my laptop screen so small as to be unreadable.

**Comment by benfry** [comment]
Closing as duplicate.
