### ISSUE TITLE
Python Mode for Processing not working in 4.0b1 on macOS

### ISSUE THREAD

**Issue by brianhouse** [processing/processing#6218]
## Description

Processing does not launch a canvas window or print to console when in Python Mode on macOS.

## Expected Behavior

I hope that Python Mode will be included in the 4.0 update!

## Steps to Reproduce

```py
print("Hello World")
circle(width/2, height/2, 50)
```

## Your Environment

 

* Processing version: 4.0b1
* Operating System and OS version: macOS 11.5.2 (Big Sur)

## Possible Causes / Solutions

Guessing this has to do with the Java version upgrade.

**Comment by benfry** [comment]
This is not the place to report Python Mode issues.
