### ISSUE TITLE
Processing IDE keyboard shortcut on macos ⌘ + / doesn't work on azerty keyboard

### ISSUE THREAD

**Issue by alicericci** [processing/processing#6219]
## Description
Because the way the azerty keyboard, it's impossible to press ⌘ and / without pressing another key (shift key). 
When ⌘, shift and / key are pressed alltogether, nothing appends. 
I randomly found out that pressing ⌘ and = will toggle comment. 
Proposed change: make keyboard shortcuts editable, to increase accessibility

## Your Environment

 

* Processing version: Processing 4 (was also happening in previous version) 
* Operating System and OS version: macOS 11.4
* Other information: azerty keyboard

**Comment by benfry** [comment]
The fix is described at the end of the Localization page in the Wiki: https://github.com/processing/processing/wiki/Localization#shortcuts-and-key-bindings
