### ISSUE TITLE
[ISSUES] processing/processing - problems with association between gstreamer video + opencv processing 4 - september 2021

### ISSUE THREAD

**Issue by tmm88** [processing/processing#6220]
### [ISSUES] processing/processing - problems with association between gstreamer video + opencv processing 4 - september 2021

*I currently noticed some issues between:*
- **processing current iteration and the co-operation between opencv and gstreamer video services and processing.**

*i wanted to use motion capture data between processing and a video of mine performing with bratsche on contemporary improvisation*

*my current setup is:*
- **an acer predator helios 300 from 2019 with:**
  - **core i7 cpu**
  - **8 gb of ram**
  - **ssd 256+sata500gb**
  - **nvidea gtx 1050**

***i am running the latest arch linux version. everytime i run a video throughout the combination between gstreamer and openv it crashes, and doesn't simply load up***

*a piece of advice:*
- **keep different versions of libraries for each processing version (where each is processing 2,3,and 4. with backups made at different times by different people**

### looking forward
***kind regards***

**Comment by tmm88** [comment]
in fact, the problem persists amongst all arch linux programs created with processing, so it may have something to do with the compilation of processing and the arch kernel. I tried the processing 3 and 2, the problem persists. so, it may also be related to problems in my machine. i can provide further feedback

**Comment by benfry** [comment]
Sounds like a better discussion for https://discourse.processing.org/
