### ISSUE TITLE
Visual cursor offset 

### ISSUE THREAD

**Issue by 213302** [processing/processing#6223]
## Description
When typing, the text cursor slowly moves further than the end of the line. It looks as if it is offset to the right. this offset increases if you type more on one line. By cursor, I mean the blinking line also known as the text cursor. The same thing also occurs when highlighting. 

I know this is not part of the bug report but I would also like to say that I really enjoy processing. I hope this report helps to improve it. 

## Expected Behavior
I was expecting that the text cursor would be where the text appears.

## Current Behavior
the text cursor is not where the text appears.

## Steps to Reproduce

1. Download Processing 4 beta 1
2. Boot it up
3. Type

## My Environment

 

* Processing version: Processing 4.0 beta 1
* Operating System and OS version: Windows 10 Home 20H2 OS build: 19042.1165
* Other information: Let me know if needed

## Possible Causes / Solutions

It seems to only be a graphical issue

**Comment by Albert** [comment]
For reference, I posted this in the `processing/processing4` repo w/out realizing it was here as well...

https://github.com/processing/processing4/issues/277
