### ISSUE TITLE
Flatpak version is using out of date freedesktop runtime

### ISSUE THREAD

**Issue by LeSnake04** [processing/processing#6224]
## Description
The Fatpak version of Processing IDE is using an outdated version of the Freedesktop Runtime

## Expected Behavior

Flatpak update shows no warnings (At least no one Related to Processing IDE)

## Current Behavior

Flatpak shows error: Info: org.freedesktop.Platform//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Applications using this runtime:
   org.processing.processingide
Info: org.freedesktop.Platform.VAAPI.Intel//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version

## Steps to Reproduce

1. Install Processing IDE flatpak
2. Update flatpaks
3. Flatpak shows the outdated runtime warning.

## Your Environment
* Processing version: 3.5.4
* Operating System and OS version: Artix Runit
* Other information: 

## Possible Causes / Solutions
Migrate to latest Freedesktop (21.08).

**Comment by benfry** [comment]
We don't make a flatpak version. It should probably be removed if whoever did that isn't going to support it properly.

**Comment by LeSnake04** [comment]
Would you consider asking the Flathub team is you could adopt it. Many love flatpaks and use the flatpak version of Processing, so it would be in your best interest that the package is properly maintained by doing it yourself.

**Comment by benfry** [comment]
Sorry, I just don't have time for that. This is already way more work than I can do in my free time.
