### ISSUE TITLE
Python Mode has disappeared from the contribution manager window

### ISSUE THREAD

**Issue by tabreturn** [processing/processing#6226]
Screenshot from Processing 3.5.4

![Screenshot from 2021-09-25 13-21-09](https://user-images.githubusercontent.com/9858145/134753088-6c529257-416a-4d87-b591-c3ce4dbda0f6.png)

**Comment by GSM1967** [comment]
Does anyone have a fix for this?

**Comment by tabreturn** [comment]
@GSM1967 -- 

The SSL certificate for py.processing.org has expired. Here is the workaround (until the issue is fixed): https://discourse.processing.org/t/i-can-not-see-the-python-mode-processing-3-5-4/32440

**Comment by tabreturn** [comment]
Python Mode has reappeared in the Contribution Manager window 😄
