### ISSUE TITLE
Java 17 - error in PApplet

### ISSUE THREAD

**Issue by padreati** [processing/processing#6228]
## Description
When I run Processing using Java 17 GA version (I tried with OpenJDK, Azul and Corretto) I get an Exception while parsing the java.version system property.

> Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
	at java.base/java.lang.String.substring(String.java:2704)
	at processing.core.PApplet.<clinit>(PApplet.java:120)

## Expected Behavior

Run smooth.
## Current Behavior

Currently this crashed and I would expect to not happen. Java 17 is a GA release with long term support.

## Steps to Reproduce
Create a maven Java project with a simple pom.xml like
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.padreati</groupId>
    <artifactId>rapaio3d</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.processing</groupId>
            <artifactId>core</artifactId>
            <version>3.3.7</version>
        </dependency>
    </dependencies>
</project>
```
Write a class with nothing but PApplet initialization
```
public class Test extends PApplet {
    public static void main(String[] args) {
        PApplet.main(Test.class.getName());
    }
}
```
## Your Environment

 

* Processing version: 3.3.7
* Operating System and OS version: Ubuntu 20.04.3 LTS (Focal Fossa)
* Other information: Java 17 Azul

## Possible Causes / Solutions

It happens in the static initializer in PApplet class:
```
static {
    String version = javaVersionName;
    if (javaVersionName.startsWith("1.")) {
      version = version.substring(2);
    }
    javaPlatform = parseInt(version.substring(0, version.indexOf('.')));
  }
```
This happens because in Java 17 the java.version property is just "17", no "17.0" or else. I tried to change the property with a JVM parameter but I did not solve it. 

The solution is pretty simple, I think. Simply to check the result of version.indexOf to be greater than 0, and if not to replace with version.length() or something. I would try to do it myself, but I do not know if there are other implications in Processing, so I would expect somebody with some experience regarding that to give me an advice or even implement it.

**Comment by benfry** [comment]
Java 17 isn't supported for 3.x: https://github.com/processing/processing/wiki/Supported-Platforms#java-9-10-and-11 

Though we do use 11 for Processing 4. https://github.com/processing/processing4
