### ISSUE TITLE
Second shortcut repopulates after capture and deployment

### ISSUE THREAD

**Issue by rm2930** [processing/processing#6232]
## Description
There were two shortcuts created for Processing by mistake. One is working and the other is broken. The broken one is pinpointing to a share folder on our network. I remove the shortcut from start and perform a capture via MDT. After the capture I deploy the captured image and the shortcut get repopulated. When I go back to the capture image it also repopulates on there as well. 

## Steps to Reproduce
1. Remove the broken shortcut.
2. Capture the image then deployed for testing.
3. Shortcut repopulates on both the captured image as well as the deployed image.

## Your Environment
* Processing version: 3.5.4
* Operating System and OS version: 20H2
* Other information: Using MDT for capture and deployment.

**Comment by benfry** [comment]
I'm not sure what this is, but it doesn't sound like a Processing bug. The software doesn't make any shortcuts.
