### ISSUE TITLE
Python mode fails on OSX 10.14.6 with Processing 4.0 beta 2.0

### ISSUE THREAD

**Issue by nedelec** [processing/processing#6234]
## Steps to Reproduce

1. I downloaded Processing 4.0
2. I select python mode
3. I press 'run'... nothing happens

Also fails with a simple test:
'''
def setup():
    size(400, 400)

def draw():
    background(255)
    fill(0)
    ellipse(mouseX, mouseY, 50, 50)
'''

## Your Environment

 

* Processing version: 4.0 beta 2
* Operating System and OS version: OSX 10.14.6 Mojave
* Other information: Python mode works in Processing 3.5.4

**Comment by tabreturn** [comment]
Use Processing 3.5.4. Right now, there's no Processing 4 support for Python Mode.

**Comment by benfry** [comment]
Didn't @villares get it working with the patches I submitted? 

In either case, this unfortunately needs to live in the repo for Python Mode, not here.
