### ISSUE TITLE
"Missing right curly bracket"}" " is wrong (line.11)

### ISSUE THREAD

**Issue by DarthElimo** [processing/processing#6235]
I checked the whole Code ans it even when I click on the curly bracket that is meant, it shows me the other one

` int s = 40;
 void zeichnequadrat (int farbe, int x, int y, boolean left) {
 fill(farbe);
 rect(x, y, x+s, y+s);
 if (farbe == 255) {
   fill(0);
   }else{ 
   fill(255);
}
 
 ellipseMode(CORNER) {
 noStroke();
 int d = s/4;
 if(links == true){
 ellipse(x, y, x+d, y+d);
 ellipse(x, y + 3*d, x+d, y+s); 
   }else{
 ellipse(x + 3*d, y, x+s, y+d);
 ellipse(x+ 3*d, y+ 3*d, x+s, y+s);
     }
  }
} 
 void setup () {
   size (600,400);
   background(#EAE11F);
   zeichnequadrat();
 }`

**Comment by reejuBhattacharya** [comment]
Hi, I would like to help, could you please elaborate on your problem?
Also, you seem to have an extra closing brace, after "ellipse(x+ 3d, y+ 3d, x+s, y+s);".

**Comment by benfry** [comment]
No response, closing.
