### ISSUE TITLE
Could not find a method to load http://....

### ISSUE THREAD

**Issue by MrCheatEugene** [processing/processing#6237]
## Description

When I try to load a picture using PHP script(http://test.example/img.php?img=1 for now) but I get error. My webserver is NGINX 1.14. 
## Expected Behavior

I was expecting for it to load image.
## Current Behavior

It returns error Could not find a method to load http://test.example/img.php?img=1
## Steps to Reproduce

1. Create sketch
2. Add code that is in attachement

## Your Environment

 

* Processing version: 3
* Operating System and OS version:  Windows 7 SP1 32 bit
* Other information: Webserver must be NGINX 1.14 with PHP7.2-FP
[loadingImg.zip](https://github.com/processing/processing/files/7689219/loadingImg.zip)

**Comment by benfry** [comment]
That image doesn't have an extension, so you need to specify what kind of image it is (jpg, png, etc). See the reference for `loadImage`: https://processing.org/reference/loadImage_.html

> The extension parameter is used to determine the image type in cases where the image filename does not end with a proper extension. Specify the extension as the second parameter to loadImage(), as shown in the third example on this page.
