### ISSUE TITLE
loadStrings() omits last empty line in 4.0 Beta2

### ISSUE THREAD

**Issue by derbirch** [processing/processing#6238]
I saw there was an old identical issue  #5572
And I crushed on this too. loadStrings() won't read the last line if it's empty.

System: MacOS 12.1 M1 MBP
Processing: 4.0 Beta2

<img width="796" alt="Screen Shot 2021-12-19 at 20 29 19" src="https://user-images.githubusercontent.com/33411000/146674985-25da3304-c5a9-4ae5-a896-94301d57b222.png">

**Comment by dzaima** [comment]
Some things (e.g. [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206)) define a text file to be a list of lines, each of which ends with a newline character. Then, the newline after the last file is just ending the last line.

Processing follows that definition (while also not breaking when there are characters after that newline). Your files just should have trailing newlines. (you may notice that `saveStrings` will add a trailing newline too).

Without this definition, you couldn't ever have a file with 0 lines, which is pretty bad.

**Comment by wardmatter** [comment]
> while also not breaking when there are characte

Thanks for your explanation, I got it now XD. 
Guess I should close this issue.
