### ISSUE TITLE
Python Mode not working - Processing 4 on Mac (M1)

### ISSUE THREAD

**Issue by econn31** [processing/processing#6241]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by tabreturn** [comment]
Use Processing 3.5.4. Currently, there is no Python Mode support for Processing 4.

**Comment by benfry** [comment]
This belongs in the repository for Python Mode, not here.

**Comment by econn31** [comment]
Thank you very much! And sorry for mislabeling.

Eric Conn
McDonogh School
