### ISSUE TITLE
Release Processing 3.5.5

### ISSUE THREAD

**Issue by StEvUgnIn** [processing/processing#6243]
When do you have plans to release Processing 3.5.5 or 3.6.0? You seem to concentrate your effort on Processing 4 already.

**Comment by benfry** [comment]
No, see the front page of this repository: 

> # Since the release of Processing 3.5.4 in January 2020, development has moved to [a new repository](https://github.com/processing/processing4/). 
> Using a [4.0 release](https://github.com/processing/processing4/releases) (even an alpha or beta version) is recommended if you find an issue. To avoid confusion, this repo will remain open at least until a 4.0 release is the default download at https://processing.org/download.

Due to continued changes by Apple, Processing 3 is likely to stop working soon for macOS, though I'd expect the Windows and Linux to follow at some point in the future.

**Comment by StEvUgnIn** [comment]
You could still maintain it for Windows and GN/Linux at least.

**Comment by dzaima** [comment]
Maintaining it is just pointless extra work for an outdated piece of software, on an unsupported java version.

**Comment by StEvUgnIn** [comment]
Any java software is fully compatible with newer versions. Java never introduces breaking changes.

**Comment by dzaima** [comment]
That is just not true. Java definitely introduces breaking changes (not many, but still plenty enough to break stuff; Processing 3 even had problems with Oracle java 8 vs OpenJDK 8). If you tried to run processing 3 with java 17, you would find that it, indeed, breaks in various ways (but processing does not make it easy to use a JVM other than the one that is built in it, and gives you a warning if you succeed about anything other than java 8 not being supported). [this](https://github.com/processing/processing/pull/5753) contains a list of some of the changes that were necessary for Processing to support Java 11.
