### ISSUE TITLE
could not run the sketch

### ISSUE THREAD

**Issue by krisasher** [processing/processing#6244]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by harshlancer** [comment]
I want to contribute to this project,but I'm not sure where to start?

**Comment by rinkydevi** [comment]
i think this is a void issue , i would request @limzykenneth to check this and close this extra issue

**Comment by benfry** [comment]
Closing.
