### ISSUE TITLE
Question: No desktop, not headless

### ISSUE THREAD

**Issue by nigeljohnson73** [processing/processing#6248]
I have a display attached to the PI, but no desktop running.

I have rummaged through the options [here](https://github.com/processing/processing/wiki/Running-without-a-Display) but they do not use the inbuilt framebuffer on the raspberry pi, and all output goes to a magic space in the invisible world. 

I use `fbi` and `mplayer` without a problem and both of these output to a 4k display, and `mplayer` will happily play 720p videos at 60fps.

mplayer works like this:

```
sudo SDL_VIDEODRIVER=fbcon SDL_FBDEV=/dev/fb0  mplayer ...
```

`fbi` runs without any display parameters

Without installing a desktop, How can I make the processing-java output to the frame buffer?

I do know that I can install a basic window manager, and I have done this with chromium to run some P5.js stuff, but I want to run this as light (and simple) as possible... The window manager (or possibly chromium) was a little flakey, I'd like to avoid that if possible.

Any help much apprecaited.

**Comment by reiaaoyama** [comment]
Disclaimer: I have not tried this. It looks interesting. I may try it out.

There is a wiki - [Running without a Display](https://github.com/processing/processing/wiki/Running-without-a-Display) - which points to  [Headless Processing on Pi3](https://nocduro.com/post/headless-processing3/) Hope it gives you some idea.

I also notice that the procedure is using "xinit" (part of X-window GUI) so it still not writing to the /dev/fb0

ReiA

**Comment by benfry** [comment]
Questions should go to https://discourse.processing.org/
