### ISSUE TITLE
Question: Python3 Mode

### ISSUE THREAD

**Issue by wsj20010128** [processing/processing#6254]
I wonder whether there is a python 3 mode. If not, how I can contribute one？

**Comment by tabreturn** [comment]
Processing Python Mode / Processing.py employs [Jython](https://en.wikipedia.org/wiki/Jython), which is compatible with Python 2.7.

You could look at [py5](https://py5coding.org/), which "is a new version of Processing for Python 3.8+, that makes the Java Processing jars available to the CPython interpreter using [JPype](https://github.com/jpype-project/jpype)." There might be a way to integrate this approach into a PDE plug-in/mode.
