### ISSUE TITLE
Windows 4 detects virus when downloading Processing 4.1.2

### ISSUE THREAD

**Issue by sifhg** [processing/processing#6258]
The moment I'm done downloading the .zip-file from the website for Processing 4.1.2, Windows warns me that it has found a virus and removes the file.

I don't know if this is a bug or a security threat and as I'm no security expert, I won't do anything. I just want to make you aware of this and hope you'll look into it.

## Steps to Reproduce
1. Download the latest version of Processing (4.1.2) on Windows 10 from https://processing.org/download

**Comment by benfry** [comment]
It's a false positive, you can read about it here: https://github.com/processing/processing4/wiki/Troubleshooting#viruses-and-trojans

If you'd like to help, you can also submit it to Microsoft (the link is at that page) as a false positive and they can confirm for you.
