### ISSUE TITLE
m1 pro and processing can not run sketch say failed to load vm

### ISSUE THREAD

**Issue by fatherOfMS** [processing/processing#6269]
## Description

m1 pro and processing can not run sketch say failed to load vm

## Expected Behavior

after running the processing, after a few times 
run stop
and the sketch will not run properly 
and show can not start specific version java  vm

## Current Behavior

when i change to Applications dir in terminal, i can not change to Processing dictionary, and it say do not have processing dictionary.

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by fatherOfMS** [comment]
after a few time run and stop, the program will can not run

**Comment by SableRaf** [comment]
Hello @fatherOfMS,

Make sure you’re using the [latest version of Processing4](https://processing.org/download). Be careful to select the "Apple Silicon" version for your M1 Mac.

If you’re still having trouble, please check out post on the [Processing Forum](https://discourse.processing.org/) for support. The community can help you troubleshoot.

Please note the correct location for reporting bugs with Processing4 is at [processing/processing4](https://github.com/processing/processing4/issues).
