### ISSUE TITLE
redo the Preferences window using BoxLayout or GroupLayout

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#67]
_Original author: b...@processing.org (June 07, 2010 00:15:49)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=73

Comment from fry, 2005-07-15 16:20

redo panel to use proper Box layout etc
also needs to look good across all platforms

_Original issue: http://code.google.com/p/processing/issues/detail?id=28_

**Comment by Akarshit** [comment]
![Preference Window](https://cloud.githubusercontent.com/assets/7762605/7116895/b5b04d94-e212-11e4-95f2-6386a2b27dfb.png)
@benfry how do you feel about this layout of Preference Window , this has been done using Group Layout , if you need any changes please comment i will include them and then issue the PR.   Meanwhile i am also changing layout of Find/Replace dialog to GroupLayout.

**Comment by benfry** [comment]
Please keep the layout closer to the original. The 'Run sketches on display' line doesn't need a popup that extends the entire width of the window (neither do the others that take up the full horizontal space), and the three "More preferences" lines at the bottom should have less space between them.

**Comment by Akarshit** [comment]
@benfry i have made the changes as you instructed, please look into the PR for more suggestions

**Comment by benfry** [comment]
Incorporated for 3.0a6.
