### ISSUE TITLE
callback for requestImage()

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#680]
_Original author: t...@constantx.com (April 21, 2011 20:22:07)_

Feature request, add callback to requestImage()

Can be empty function(), or can be overwritten for useful functionality after an image is loaded.

_Original issue: http://code.google.com/p/processing/issues/detail?id=641_

**Comment by teo1978** [comment]
So which are the better asynchronous loading support methods that eventually replaced requestImage()? By the way, I don't see requestImage() marked as deprecated in the docs.

**Comment by benfry** [comment]
We didn't get around to it for 2.0.

**Comment by benfry** [comment]
Moved to https://github.com/processing/processing/issues/3165
