### ISSUE TITLE
sketch archive format for posting examples

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#73]
_Original author: b...@processing.org (June 07, 2010 00:16:52)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=88

Comment from fry, 2005-07-16 10:40

when posting things for people, would be nice to open a sketch directly
from a zip file. could just pack up the sketch folder as a zip

_Original issue: http://code.google.com/p/processing/issues/detail?id=34_

**Comment by benfry** [comment]
Finally implemented for 4.0… it'll be in the alpha 7 or beta 1 release, whatever we decide to call it. Just rename a sketch .zip file to end with .pdez and it'll unpack automatically and load in the PDE.

Been wanting to do this for years; first filed in 2005!

<img width="750" alt="Screen Shot 2021-08-06 at 9 39 53 PM" src="https://user-images.githubusercontent.com/1623101/128584081-7fdb994e-2a75-41d7-96c8-22eee0bb6def.png">

**Comment by ybakos** [comment]
🤘
