### ISSUE TITLE
svg fonts with loadFont / createFont

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#787]
_Original author: fjen...@gmail.com (June 23, 2011 17:32:35)_

In Processing.js the best (in terms of visual output) variant to render x-browser text is to use .svg fonts. These can be generated with Apache Batik (batik-ttf2svg.jar) from .ttf fonts. Since there currently is no method of making sure that text renders similar in standard / js i was thinking if it would be an idea to integrate .svg font support into loadFont / createFont as they do with P.js.

&quot;Create Font&quot; tool could then just offer a switch between the two formats and would hide all non-ttf fonts from the list.

_Original issue: http://code.google.com/p/processing/issues/detail?id=748_

**Comment by benfry** [comment]
Rolling SVG requests into https://github.com/processing/processing/issues/5935
