### ISSUE TITLE
Video Issues, OPENGL Issues pages on wiki

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#866]
_Original author: r...@processing.org (September 02, 2011 18:30:19)_

http://wiki.processing.org/w/Video_Issues
http://wiki.processing.org/w/OpenGL_Issues

These pages need to be reviewed and altered for the 2.0 release. The video page is linked from the reference pages on the main site, which I have updated in the source, but not yet on the site.

http://processing.org/reference/libraries/video/index.html

_Original issue: http://code.google.com/p/processing/issues/detail?id=828_

**Comment by codeanticode** [comment]
I already started adding some materials to those wikis. We no longer need this issue.
