### ISSUE TITLE
implement depth sorting for triangles to fix rendering issues with transparent objects in 3D

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#90]
_Original author: b...@processing.org (June 07, 2010 00:27:42)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=176

Comment from fry, 2005-10-15 10:27

Objects with alpha (lines or shapes with an alpha fill or stroke, images
with alpha, all fonts) are displayed in OpenGL (and P3D, in fact) based on
their drawing order. This creates some annoying effects like making things
opaque if they're drawn out of order with objects above or beneath them.
This is simply how OpenGL works, but is something that we'd like to develop
a workaround for in the future. Currently, you should just try to draw
things back-to-front as best as possible.

_Original issue: http://code.google.com/p/processing/issues/detail?id=51_

**Comment by antonvh** [comment]
I have this problem too. I don't know how to fix it manually in the sketch, as I use a sequence of translates to build my scene. Having to to sort all translate operations by depth would make my sketch terribly complex. This should be done in an OpenGL draw buffer. But it is beyond my skills.

**Comment by benfry** [comment]
Locking this issue because of multiple comments/queries for help on sketches, rather than contributions to the issue itself.

**Comment by codeanticode** [comment]
implemented in https://github.com/processing/processing/pull/3507, https://github.com/processing/processing/pull/3477, https://github.com/processing/processing/pull/3410, https://github.com/processing/processing/pull/3372
