### ISSUE TITLE
Parsing generic fails when package is specified (also a problem with Map.Entry)

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#918]
_Original author: cpau...@gmail.com (October 26, 2011 16:27:52)_

If you attempt to declare something that takes a generic parameter while using the full package name Processing throws a Syntax error. For example:

java.util.ArrayList&lt;Integer&gt; stuff;

Throws  the error &quot;Syntax error on token &quot;&lt;&quot;, TypeArgumentList1 expected after this token&quot;.

I am using Processing 1.5.1 on Mac OS 10.7.2.

_Original issue: http://code.google.com/p/processing/issues/detail?id=880_

**Comment by JakubValtar** [comment]
Still an issue. Running
```processing
import java.util.Map;

HashMap<String, Integer> people = new HashMap<String, Integer>();

people.put("Ava", 1);
people.put("Cait", 35);
people.put("Casey", 36);

for (Map.Entry<String, Integer> person : people.entrySet()) {
  println(person.getKey());
}
```
prints
```
Syntax error, insert ">" to complete ReferenceType1

**Comment by benfry** [comment]
Fixed in beta 4.
