### ISSUE TITLE
prevent library .jar files from overwriting core classes

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#95]
_Original author: b...@processing.org (June 07, 2010 00:35:45)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=321

Comment from fry, 2006-04-12 17:11

aiexport.jar included processing.core, which would overwrite the library mapping and cause 
problems because an older version of core would be used.

_Original issue: http://code.google.com/p/processing/issues/detail?id=56_

**Comment by JakubValtar** [comment]
Still needs to be tested.

**Comment by benfry** [comment]
Fixed several related issues here: https://github.com/processing/processing/issues/4608

But still need to check whether a library developer can break things by including parts of pde.jar or core.jar.

**Comment by benfry** [comment]
Fixed for the 4.x series with https://github.com/processing/processing4/commit/690500f4a75e781d1d606f57fc721ac28691fbef
