### ISSUE TITLE
don't grab pixels of java2d images unless asked

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#99]
_Original author: b...@processing.org (June 07, 2010 00:37:35)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=356

Comment from fry, 2006-05-20 13:49

since lots of image use in java2d is a matter of calling loadImage() and
then image() (and not manipulating pixels), can probably avoid grabbing the
pixel data in many situations. this would save lots of time (and memory) in
such situations. it's a hairy one to debug (opens up a whole new set of
scenarios) but would be useful.

_Original issue: http://code.google.com/p/processing/issues/detail?id=60_

**Comment by JakubValtar** [comment]
Might be a good idea if possible, seems that images load pixels into pixel array automagically.

**Comment by benfry** [comment]
In the distant past, `loadPixels()` wasn't necessary. But the magic was never removed, for lack of time and debugging wherewithal.

**Comment by benfry** [comment]
Big thing here is a that it might break others' code in strange ways, or behave weirdly with `PGraphicsJava2D` when drawn into other renderers or whatever. Not sure, just needs testing. So a quick fix, then we can debug further through the beta cycle.

**Comment by JakubValtar** [comment]
What happens right now is that PImage is loaded into BufferedImage, and image data are copied into pixels array where they live. When the image is drawn, ImageCache containing BufferedImage is created and filed with image data from pixels array.

To pull this off we would have to add `Object nativeImage`

**Comment by JakubValtar** [comment]
What happens right now is that PImage is loaded into BufferedImage, and image data are copied into pixels array where they live. When the image is drawn, ImageCache containing BufferedImage is created and filed with image data from pixels array. Options:
1) overload loadImage and create ImageCache right there without loading pixels, image would then need to be linked to the cache to have some reference to the image data
2) add native image field to PImage where native image would live, deal with multiple renderer problems
3) leave it as it is, pixels array can be used with multiple renderers where each PGraphics creates its own native image cache

**Comment by benfry** [comment]
Sounds like it's too messy; let's not bother.
